### ISSUE TITLE
Unexpected console.log with next-auth v5.0.0-beta.11

### ISSUE THREAD

**Issue by phev8** [nextauthjs/next-auth#10034]
### Environment

macOS, NodeJS v21.2.0

### Reproduction URL

https://github.com/ukhsa-flusurvey/flusurvey-admin/tree/auth-rework

### Describe the issue

After upgrading to next-auth v5.0.0-beta.11 I see log line after each request the middleware is run with similar content:
```
{ x-middleware-next: '1' }
{
  set-cookie: 'authjs.session-token=<redacted>; Path=/; Expires=Sat, 16 Mar 2024 09:21:21 GMT; HttpOnly; SameSite=Lax',
  x-middleware-next: '1'
}
```

### How to reproduce

Maybe related to these changes?

<img width="1158" alt="Screenshot 2024-02-15 at 10 24 12" src="https://github.com/nextauthjs/next-auth/assets/13927969/340027c7-8896-4f4b-9def-e932f8ef3883">

### Expected behavior

Can these be removed somehow?

**Comment by Lady-vamp** [comment]
Encountering the same issue where the cookie is regenerated upon navigating to a new page, with its expiration date resetting concurrently with each logged message. Not sure this behavior is normal

**Comment by activemonkeys** [comment]
Also encountering the same behaviour with next-auth v5.0.0-beta.11 in development and unable to turn this logging off.

**Comment by omarasdider** [comment]
How can remove this problem in terminal 2day try but failed pls any solution
