### ISSUE TITLE
Getting NEXT_REDIRECT instance of Error when using Next 14 to sign in

### ISSUE THREAD

**Issue by TreNgheDiCode** [nextauthjs/next-auth#10056]
### Environment

 System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 2.52 GB / 15.83 GB
  Binaries:
    Node: 20.6.1 - C:\Program Files\nodejs\node.EXE        
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.112)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @auth/prisma-adapter: ^1.4.0 => 1.4.0
    next: 14.1.0 => 14.1.0
    next-auth: ^5.0.0-beta.4 => 5.0.0-beta.4
    react: ^18 => 18.2.0

### Reproduction URL

https://github.com/TreNgheDiCode/KLTN-demo-deploy

### Describe the issue

Note: I'm using Prisma Adapter for this project.

I've been learning AuthJS for a while, but I've hit a snag when deploying to Vercel. Whenever a user tries to log in, the process gets stuck at the signIn method for over 10 seconds before timing out. While everything works smoothly on my local development site, I'm seeing a "NEXT_REDIRECT" error in the logs when logging out for debugging.

![image](https://github.com/nextauthjs/next-auth/assets/88233797/bd2bcb14-5733-4d47-a172-e9305873786a)

### How to reproduce

**Steps to reproduce:**

1. Initiate the login process by clicking on the "Login" button.
2. Input the following test data into the login form:
-    Email: test@gmail.com
-    Password: 123456
3. Upon clicking the "Login" button, the form will submit a request that activates the /actions/login.ts file, which calls upon the signIn method extracted from auth.ts.

**Issue:**

- **Production build on Vercel**: The signIn method fails to execute successfully, resulting in a timeout exceeding the 10-second limit for login. This behavior contrasts with the development environment, where logins consistently complete within 2-3 seconds. The API calls similarly experience timeouts exceeding 10 seconds in the production environment.

### Expected behavior

Current situation:

**Development:**

- The login process functions correctly, except for an unspecified error upon user login.
- Login speed is comparable between the local workspace and development version.

**Production (Vercel):**

- Login issue: The signIn method within the /actions/login.ts file fails to execute, resulting in a timeout exceeding 10 seconds.
- Faster login than development: If everything work correctly, successful logins on production are significantly faster than those on the local workspace, likely due to optimizations provided by NextJS.

**Comment by balazsorban44** [comment]
The timeout might be because of a slow DB query, make sure your database is deployed close to where the application is deployed. There might be other optimizations you could do, like reducing the amount of code in general on critical paths, check out https://nextjs.org/docs/app/building-your-application/optimizing/bundle-analyzer

As for the `NEXT_REDIRECT` error, it is thrown by [`redirect()`](https://nextjs.org/docs/app/building-your-application/routing/redirecting#redirect-function), which is how Next.js is handling redirects in Server Components. If you are seeing it in your logs, it indicates that you might accidentally be catching this error instead of letting Next.js handle it, which could halt the login/logout process.

This doesn't sound like a `next-auth` bug.

**Comment by thameera** [comment]
> As for the `NEXT_REDIRECT` error, it is thrown by [`redirect()`](https://nextjs.org/docs/app/building-your-application/routing/redirecting#redirect-function) (also [see](https://nextjs.org/docs/app/api-reference/functions/redirect#server-component)), which is how Next.js is handling redirects in Server Components. If you are seeing it in your logs, it indicates that you might accidentally be catching this error instead of letting Next.js handle it, which could halt the login/logout process.

Thanks for pointing this out. I was getting the NEXT_REDIRECT error and that was because  I was try/catching the `await signOut()` call.

**Comment by kana120799** [comment]
Yes, .isRedirectError it just like a function , that tells,  this error is just for redirecting, not a real problem. 
When we use  await signIn("google", { redirectTo: "/" }); in try catch block.
