### ISSUE TITLE
error: workspace dependency "@auth/core" not found with latest beta version

### ISSUE THREAD

**Issue by arvinxx** [nextauthjs/next-auth#10073]
### Environment

next-auth: beta

### Reproduction URL

https://github.com/lobehub/lobe-chat

### Describe the issue

try with bun:

<img width="1282" alt="image" src="https://github.com/nextauthjs/next-auth/assets/28616219/b3afa40c-0530-466f-86e2-81512a64b004">

but failed with `workspace dependency "@auth/core" not found`

### How to reproduce

 git clone https://github.com/lobehub/lobe-chat

bun i

### Expected behavior

install deps suceessful

**Comment by MrOxMasTer** [comment]
It's about the same problem, but I can't even install it.
![image](https://github.com/nextauthjs/next-auth/assets/59291123/b1c8114e-3860-475d-8c62-0c93fd9d762d)

**Comment by TimKieu** [comment]
I am happy to know who can show off the v5 release roadmap please. 
thanks much

**Comment by 95tuanle** [comment]
I'm having the same issue with bun and npm, temp fix to lock it at `"next-auth": "5.0.0-beta.11"`

**Comment by arvinxx** [comment]
The cause I think is dependency wrong

https://www.npmjs.com/package/next-auth/v/5.0.0-beta.12?activeTab=code

```
78  "license": "ISC",
79  "dependencies": {
80    "@auth/core": "workspace:*"
81  }

```

**Comment by KeizerBong** [comment]
Installing of 5.0.0-beta.11 solves the issue. Seem like this is the root cause of it

> The cause I think is dependency wrong
> 
> https://www.npmjs.com/package/next-auth/v/5.0.0-beta.12?activeTab=code
> 
> ```
> 78  "license": "ISC",
> 79  "dependencies": {
> 80    "@auth/core": "workspace:*"
> 81  }
> ```

**Comment by mches** [comment]
> The cause I think is dependency wrong
> 
> https://www.npmjs.com/package/next-auth/v/5.0.0-beta.12?activeTab=code
> 
> ```
> 78  "license": "ISC",
> 79  "dependencies": {
> 80    "@auth/core": "workspace:*"
> 81  }
> ```

I think you're right. Here is a targeted workaround, for pnpm, that allowed me to upgrade to 5.0.0-beta.12.

package.json:
```json
{
  …
  "pnpm": {
    "overrides": {
      "next-auth@5.0.0-beta.12>@auth/core@workspace:*": "0.27.0"
    }
  }
}
```

**Comment by Itsnotaka** [comment]
Add this to package.json if you are using pnpm.
```"
pnpm": {
    "overrides": {
      "@auth/core": "0.27.0"
    }
  }
```

**Comment by InsafNilam** [comment]
Remove the existing node_module -> next_auth package using the command below
`npm uninstall next-auth`

Add the code below in your package.json

`{
  "overrides": {
    "next-auth@5.0.0-beta.12": {
      "@auth/core": "0.27.0"
    }
  }
}`

Save your package.json file and then install the module using the below command
`npm i next-auth@5.0.0-beta.12`

This is definitely work
![Capture](https://github.com/nextauthjs/next-auth/assets/89188261/251c6398-86a5-489e-b15d-02cd298a3faa)
![Capture-1](https://github.com/nextauthjs/next-auth/assets/89188261/8168fc94-1dc2-4ebb-ac3b-6d4eedf964e1)

**Comment by ThangHuuVu** [comment]
Sorry for the trouble, I fixed it in https://www.npmjs.com/package/next-auth/v/5.0.0-beta.13?activeTab=code

**Comment by 95tuanle** [comment]
> Sorry for the trouble, I fixed it in https://www.npmjs.com/package/next-auth/v/5.0.0-beta.13?activeTab=code

Thank you!
