### ISSUE TITLE
[3.2.0-canary.1] TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by melanieseltzer** [nextauthjs/next-auth#1007]
**Describe the bug**
Followed the [example tutorial](https://next-auth.js.org/tutorials#adding-authentication-to-an-existing-nextjs-application-in-no-time) to get Google auth working. Every time I'd attempt signing in with my Google account, I'd get kicked back to the sign in page with a message saying "Try signing with a different account." and this error in the console:

```
[next-auth][error][oauth_callback_handler_error] TypeError: Cannot read property 'toString' of undefined
    at /Users/melanieseltzer/Sites/example/node_modules/next-auth/dist/server/routes/callback.js:115:32
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/melanieseltzer/Sites/example/node_modules/next-auth/dist/server/routes/callback.js:26:103)
    at _next (/Users/melanieseltzer/Sites/example/node_modules/next-auth/dist/server/routes/callback.js:28:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) 
https://next-auth.js.org/errors#oauth_callback_handler_error
```

`id` is not available as part of the `user` object (I only have `name`, `email` and `image`) so the code from [this PR](https://github.com/nextauthjs/next-auth/commit/19f2664a78dbdf8e13aeaff3f9100e8ddde00936) (`user.id.toString()`) is failing. 

Is it expected or should it check first if `user.id` exists?

Works fine using `v3.1.0` so I'll stay on that version for now.

**Steps to reproduce**
Install `v3.2.0-canary.1` and follow [example tutorial](https://next-auth.js.org/tutorials#adding-authentication-to-an-existing-nextjs-application-in-no-time) to authenticate with Google.

**Expected behavior**

**Screenshots or error logs**

<img width="374" alt="Screen Shot 2020-12-29 at 10 49 27 PM" src="https://user-images.githubusercontent.com/17421347/103334931-30095f80-4a28-11eb-8d16-e326364c0695.png">

**Additional context**

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Thanks for tracking this down! I'll try releasing a fix for it in the near future.

**Comment by Sidemen19** [comment]
Yep, I have the same exact issue, with the Discord provider. I'm also only receiving `name`, `email` and `image`. I'll downgrade for the time being.

**Comment by melanieseltzer** [comment]
Thanks for the quick fix 👍
