### ISSUE TITLE
FaunaDB should be a dev dependency, not a regular one

### ISSUE THREAD

**Issue by kripod** [nextauthjs/next-auth#1012]
As I’ve noticed in the latest canary release (`3.2.0-canary.3`), `faunadb` has been added as a dependency, but [it doesn’t seem to be used besides a test](https://github.com/nextauthjs/next-auth/search?q=faunadb). I would like to suggest adding `faunadb` to `devDependencies` while removing it from `dependencies`.

**Comment by balazsorban44** [comment]
We have something called `peerOptionalDependencies`, but honestly have no idea how we handle these, as it doesn't seem to be an npm standard. `fauna` should be added there I guess.

**Comment by kripod** [comment]
Yeah, I see your point, it should be implemented as outlined here, then: https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-optional-peer-dependencies.md#2-detailed-design

**Comment by balazsorban44** [comment]
I think we use this at the moment: https://github.com/christkv/require_optional

**Comment by kripod** [comment]
Unfortunately, that doesn’t seem to be a living standard. However, the `peerDependenciesMeta` field is respected by Yarn and will eventually be adopted by npm if my memories are correct.

**Comment by balazsorban44** [comment]
cc @iaincollins

**Comment by balazsorban44** [comment]
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta Looks like it is in npm@7 now!

**Comment by balazsorban44** [comment]
Fauna has been removed for now, see the explanation at #1146

**Comment by balazsorban44** [comment]
https://github.blog/2021-02-02-npm-7-is-now-generally-available/
