### ISSUE TITLE
`url` in redirect() callback is always baseUrl

### ISSUE THREAD

**Issue by melanieseltzer** [nextauthjs/next-auth#1013]
**Describe the bug**
I have the following `redirect()` callback code (used [this tutorial](https://blog.logrocket.com/using-authentication-in-next-js/) as reference):

```js
redirect: async (url: string, baseUrl: string) => {
  console.log(url);

  if (url === '/api/auth/signin') {
    return Promise.resolve('/dashboard');
  }

  return url.startsWith(baseUrl)
    ? Promise.resolve(url)
    : Promise.resolve(baseUrl);
}
```

I'm just starting to set up my auth, and was working on it last night. It was working just fine for a period of time - as you can see from this screenshot, the URLs were correctly logged when hitting each page. So when `/api/auth/signin` was hit, it was correctly setting the redirect URL as `/dashboard` and I was correctly getting redirected to the dashboard on sign in.

<img width="434" alt="Screen Shot 2020-12-30 at 10 15 28 AM" src="https://user-images.githubusercontent.com/17421347/103373177-12b8ad80-4a89-11eb-89ec-7c980cddaad6.png">

However, suddenly it's only ever logging the `url` as `http://localhost:3000` no matter what page you're hitting. 

<img width="417" alt="Screen Shot 2020-12-30 at 10 16 54 AM" src="https://user-images.githubusercontent.com/17421347/103373240-3bd93e00-4a89-11eb-8db0-360402105137.png">

This obviously means that in the redirect callback, it's never seeing that the URL is the sign in page, so it's never setting the callback URL to `/dashboard`.

Not really sure what the issue is, as it seemingly stopped working super randomly (I didn't really change much in the code). I've verified that the issue persists for me even when moving between package versions. I'm not really sure why it was working one minute and stopped the next. Any ideas? 

My full `[...nextauth]` file:

```js
import { NextApiRequest, NextApiResponse } from 'next';
import NextAuth from 'next-auth';
import Providers from 'next-auth/providers';

import { NEXTAUTH_URL, GOOGLE_ID, GOOGLE_SECRET } from '@constants';

const options = {
  site: NEXTAUTH_URL,
  providers: [
    Providers.Google({
      clientId: GOOGLE_ID,
      clientSecret: GOOGLE_SECRET,
      authorizationUrl:
        'https://accounts.google.com/o/oauth2/v2/auth?prompt=consent&access_type=offline&response_type=code'
    })
  ],
  callbacks: {
    signIn: async (user: any, account: any, profile: any) => {
      return Promise.resolve(true);
    },
    redirect: async (url: string, baseUrl: string) => {
      console.log(url);

      if (url === '/api/auth/signin') {
        return Promise.resolve('/dashboard');
      }

      return url.startsWith(baseUrl)
        ? Promise.resolve(url)
        : Promise.resolve(baseUrl);
    }
  }
};

export default (req: NextApiRequest, res: NextApiResponse) =>
  NextAuth(req, res, options);
```

**Steps to reproduce**
Steps to reproduce the behavior.

Include a link to public repository which can be used to reproduce the behaviour.

**Expected behavior**

**Screenshots or error logs**
If applicable add screenshots or error logs to help explain the problem.

**Additional context**

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by melanieseltzer** [comment]
My mistake - I misread the docs and didn't realize the `url` param provided to the redirect callback directly correlates to the `next-auth.callback-url` cookie 🙃 Now that I understand that, the flow is a lot more clear!

**Comment by musaa-muhsen** [comment]
> My mistake - I misread the docs and didn't realize the `url` param provided to the redirect callback directly correlates to the `next-auth.callback-url` cookie 🙃 Now that I understand that, the flow is a lot more clear!

Hi Melanie,

I'm having this issue that you were. Could you explain what you meant by "url param provided to the redirect callback directly correlates to the next-auth.callback-url cookie"? 

Any help would be much appreciated. Thanks
