### ISSUE TITLE
Documentation for App router

### ISSUE THREAD

**Issue by arnavnagpurkar** [nextauthjs/next-auth#10211]
### What is the improvement or update you wish to see?

In the https://next-auth.js.org/ there is a section titled as "Add authentication in minutes!" where the code is given to create authentication.
In the latest version of Next.js, instead of the `pages` router, `app` router is proffered to use.
Slowly people will start using app router instead of pages router so the documentation need to be updated accordingly...
![image](https://github.com/nextauthjs/next-auth/assets/84492896/fb0bb485-927a-47d3-89dc-35865bc98a82)
Instead of using the `pages` router in the documentation use the `app` router!!

### Is there any context that might help us understand?

To update NextAuth.js with the latest Next.js version that uses the `app` router instead of `pages` router, we just need to update the documentation based on `app` router.

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/

**Comment by 18601673727** [comment]
Exactly what I need atm, it was such a painful ride trying to integrate with App router myself. And [this](https://docs.login.xyz/integrations/nextauth.js) too. 🙏

**Comment by deelo55** [comment]
I agree...the documentation is really difficult to follow for app router and after hours I still have no idea what you're meant to do to get an app router working.

**Comment by 11samype** [comment]
Struggling through integrating with azure auth right now. Updated docs would be much appreciated.

**Comment by arnavnagpurkar** [comment]
Reminder for development team to update the documentation !!

**Comment by ndom91** [comment]
Hey folks, just wanted to share that we've launched a brand new docs site at https://authjs.dev. It's focused on v5 and app router first so this should be covered :pray:
