### ISSUE TITLE
Hosted 

### ISSUE THREAD

**Issue by DuarteMartinho** [nextauthjs/next-auth#10224]
@DuarteMartinho No, I dont think this is related. Please open an issue with more details, like the version of Next.js and next-auth yuo're using as well as the Auth.js config and any other relevant details :pray:

_Originally posted by @ndom91 in https://github.com/nextauthjs/next-auth/issues/10094#issuecomment-1979389352_
 
Regarding the above here is more information

# Environment
Docker container using docker-compose and Dockerfile

## Dockerfile 
FROM node:latest

WORKDIR /usr/src/app

COPY frontend/package*.json ./frontend/
RUN cd frontend && npm install
COPY frontend/ ./frontend/
RUN cd frontend && npm build

EXPOSE 3000

CMD ["npm", "run", "start"]
 
#  Describe the issue

I have this container on port 3000 running behind a reverse proxy with a domain pointed to it. 

For example frontend.mydomain.com -> reverse proxy pointing at container -> container_IP:3000

The webpage looks fine but no authentication works

Also when i go to frontend.mydomain.com/api/auth/providers i get the following 

{
"github": {
"id": "github",
"name": "GitHub",
"type": "oauth",
"signinUrl": "https://localhost:3000/api/auth/signin/github",
"callbackUrl": "https://localhost:3000/api/auth/callback/github"
}
}

As you can see both signinUrl and callbackUrl are pointing to localhost

**Comment by ndom91** [comment]
Hey @DuarteMartinho sorry, it got auto closed because there's no valid reproduction URL. 

But basically, make sure you set the `AUTH_URL` env var to your full external url. 

Also in a docker setup, make sure you set `trustHost: true` in your auth.js config
