### ISSUE TITLE
List of Integrations page is unavailable. 

### ISSUE THREAD

**Issue by AnshSharma2001** [nextauthjs/next-auth#10235]
### What is the improvement or update you wish to see?

The List of integrations that are supported page throws a page not found error. 
https://authjs.dev/guides/frameworks/reference#integrations

### Is there any context that might help us understand?

I was looking for a guide to integrate authjs with a Django backend and I cannot find any resources on the internet. When I opened the list of integrations, it throws a page not found error. 

### Does the docs page already exist? Please link to it.

https://authjs.dev/guides/frameworks/reference#integrations

**Comment by ndom91** [comment]
The page is available in our new docs [here](https://authjs.dev/getting-started/integrations) :pray:
