### ISSUE TITLE
Typescript errors on module augmentation (5.0.0-beta.15)

### ISSUE THREAD

**Issue by bfourgeaud** [nextauthjs/next-auth#10271]
### Environment

System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz  
    Memory: 7.85 GB / 15.95 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.3 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.80)
  npmPackages:
    @auth/prisma-adapter: ^1.0.12 => 1.4.0
    next: ^14.1.0 => 14.1.0
    next-auth: ^5.0.0-beta.15 => 5.0.0-beta.15
    react: ^18.2.0 => 18.2.0

### Reproduction URL

https://github.com/bfourgeaud/repro--next-auth-module-augmentation

### Describe the issue

Module augmentation broke on 5.0.0-beta.15
It worked on beta.11

`user.isAdmin` is not defined anymore in `jwt callback` nor in `session`

```ts
import type { NextAuthConfig } from "next-auth"
import GoogleProvider from "next-auth/providers/google"

export const authConfig = {
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID as string,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET as string,
    }),
  ],
  callbacks: {
    jwt: async ({ token, session, user, trigger }) => {
      if (user) {
        token.isAdmin = user.isAdmin  // --> isAdmin does not exist on type User
      }

      if (trigger === "update" && session?.isAdmin) {
        token.isAdmin= session.isAdmin
      }

      return token
    },
  },
} satisfies NextAuthConfig

```

```ts
import { DefaultSession, DefaultUser } from "next-auth"

type SessionUser = {
  isAdmin: boolean
}

declare module "@auth/core/jwt" {
  interface JWT extends SessionUser {}
}

declare module "@auth/core" {
  interface User extends DefaultUser, SessionUser {}
}

declare module "@auth/core/adapters" {
  interface AdapterUser extends SessionUser {}
}
```

```ts
import { auth } from "@/auth"

export const getSession = async () => auth()

export async function getCurrentUser() {
  const session = await getSession()

  console.log(session?.user?.isAdmin) // --> isAdmin does not exist on type User
  return session?.user
}
```

### How to reproduce

Upgrade from beta.11 to beta.15
See reproduction URL files `auth.ts` and `next-auth.d.ts`

### Expected behavior

I should be able to augment Session and User interfaces with typescript

**Comment by luciotiago22** [comment]
I have the same bug, typescript is not recognizing the augmented Session but they are still working.

**Comment by abencun-symphony** [comment]
Can confirm, having the same issue while trying to migrate to v5

**Comment by flawnson** [comment]
Same here, I have the next-auth.d.ts set up as per the docs on v4.

**Comment by ThangHuuVu** [comment]
<img width="778" alt="Screenshot 2024-05-26 at 12 01 27" src="https://github.com/nextauthjs/next-auth/assets/31528554/a3922482-3f7a-4c9e-8b9e-8918fa0c3c01">


Are you still seeing this issue? I checked the reproduction and see that the type is properly augmented.

my `next-auth.d.ts`: note that you don't need to import from `@auth/core`:
```ts
import type { JWT } from "next-auth/jwt";
import type { User } from "next-auth";

interface SessionUser {
  isAdmin: boolean;
}

declare module "next-auth/jwt" {
  interface JWT extends SessionUser {}
}

declare module "next-auth" {
  interface User extends SessionUser {}
  interface AdapterUser extends SessionUser {}
}

```
I'm going to close this issue for now. For anyone who still has the issue, feel free to open another one with a minimal reproduction, thanks!

**Comment by MrOxMasTer** [comment]
Can someone explain why when setting different types in `next-auth.d.ts`, I have all other types fail altogether
The file has been added to `tsconfig.json`
![image](https://github.com/user-attachments/assets/3c6003af-d7a4-413e-b6d1-ad8eaeee2a31)
![image](https://github.com/user-attachments/assets/76948347-17c0-455d-b6ac-801e50490b5a)
![image](https://github.com/user-attachments/assets/a1b2a5da-7862-493d-bcac-3e1686cc76bc)

Fixes it if I move it to auth.ts are all types, but this file will be very huge anyway. I don't want to shove any more types in there.

**Comment by JulianKingman** [comment]
@MrOxMasTer did you solve your issue? I'm facing the same thing and can't tell where my problem lies.
