### ISSUE TITLE
Oauth flow continues even if no code is query

### ISSUE THREAD

**Issue by mmahalwy** [nextauthjs/next-auth#1028]
**Describe the bug**
In the case of the Salesforce oauth, user is redirected back to the app without the `code=` param. Next-auth then continues the Oauth flow and tries to make request to fetch access token (without a code). 
For example, this is the callback after authenticating on Salesforce side: `http://localhost:3000/api/auth/callback/salesforce?error=OAUTH_APP_ACCESS_DENIED&error_description=user+is+not+admin+approved+to+access+this+app&state=7f881326863351680ee8fc5cff76917739b0c169b3ce7ac62fc4fc298249f03b`

**Steps to reproduce**
This is an app specific error but can we done with visiting:
`http://localhost:3000/api/auth/callback/salesforce?error=OAUTH_APP_ACCESS_DENIED&error_description=user+is+not+admin+approved+to+access+this+app&state=7f881326863351680ee8fc5cff76917739b0c169b3ce7ac62fc4fc298249f03b`

Include a link to public repository which can be used to reproduce the behaviour.

**Expected behavior**
An error is thrown showing missing `code` in callback url

**Screenshots or error logs**
None

**Additional context**
None

**Feedback**
None.

* [x] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
It seems to be a configuration error, not entirely sure what `next-auth` should do about it.

`user+is+not+admin+approved+to+access+this+app` this does not come from us.


Could you maybe add a reproduction repository?
