### ISSUE TITLE
Pages configuration doesn't work in NextAuth V5

### ISSUE THREAD

**Issue by chungweileong94** [nextauthjs/next-auth#10289]
### Environment

```
System:
  OS: macOS 14.4
  CPU: (8) arm64 Apple M2
  Memory: 1.59 GB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 18.19.0 - ~/Library/Caches/fnm_multishells/16910_1710223396800/bin/node
  Yarn: 1.22.21 - ~/Library/Caches/fnm_multishells/16910_1710223396800/bin/yarn
  npm: 10.2.3 - ~/Library/Caches/fnm_multishells/16910_1710223396800/bin/npm
  pnpm: 8.14.0 - ~/Library/Caches/fnm_multishells/16910_1710223396800/bin/pnpm
  bun: 1.0.30 - /opt/homebrew/bin/bun
Browsers:
  Safari: 17.4
npmPackages:
  next: canary => 14.2.0-canary.16 
  next-auth: 5.0.0-beta.15 => 5.0.0-beta.15 
  react: ^18.2.0 => 18.2.0 
```

### Reproduction URL

https://github.com/chungweileong94/next-auth-custom-pages-bug

### Describe the issue

In the latest NextAuth V5, if we try to customize the pages via [`pages` options](https://authjs.dev/reference/nextjs#pages), NextAuth will not redirect to the custom page accordingly.

For example: If we set the error page to `/auth/error`, NextAuth will always redirect to the incorrect URL `http://localhost:3000/api/auth/auth/error`.

### How to reproduce

1. Clone the repro code
2. Start the server
3. Navigate to `http://localhost:3000`
4. Click the "Sign In" link
5. Click "Sign In with Credentials", the `CredentialsProvider` should throw a fake error at this point.

### Expected behavior

**Expected**

- It should redirect to `http://localhost:3000/custom/error?error=Configuration`.

**Actual** 
- It redirects to `http://localhost:3000/api/auth/custom/error?error=Configuration` instead.

**Comment by dresandev** [comment]
> I am experiencing a similar issue. In my case with OAuth and google. I have set a custom signIn page `/auth/login` but the redirect goes to `http://localhost:3000/api/auth/auth/login?error=OAuthAccountNotLinked` with the original `/api/auth` base

Same here

**Comment by doctorrweb** [comment]
I am also experiencing the same issue with OAuth. I use Github and Google and even though I redirect the signin to /auth/login, I am redirected to http://localhost:3000/api/auth/auth/login?error=OAuthAccountNotLinked.

**Comment by maytees** [comment]
Same here..
