### ISSUE TITLE
Securing Pages & API routes recommends deprecated getToken

### ISSUE THREAD

**Issue by jarrodmedrano** [nextauthjs/next-auth#10293]
### What is the improvement or update you wish to see?

![Screenshot 2024-03-12 at 9 20 21 AM](https://github.com/nextauthjs/next-auth/assets/1929136/c070c473-2877-4c8c-8004-642c0c2a0397)

this page recommends next-auth/jwt but if you try to use it, you will get an error.

![Screenshot 2024-03-12 at 9 19 49 AM](https://github.com/nextauthjs/next-auth/assets/1929136/128c1b23-9e5a-412e-a431-0695d046ab27)

This should be marked as deprecated or removed to avoid confusion.

### Is there any context that might help us understand?

Why is this there, if I can't use it?

### Does the docs page already exist? Please link to it.

https://authjs.dev/guides/basics/securing-pages-and-api-routes

**Comment by michaelzewdu** [comment]
Salt is required on the getToken function but I don't even have a salt on the NextAuth setup. I am using next-auth5.0.0-beta.15 ??

**Comment by michaelzewdu** [comment]
I don't see the point of using this function anymore. Looks like Next Auth 5 can retrieve the user from the session cookie itself. 
I just imported auth from NextAuth and called `const session = await auth();` and there is my user object. But this only works on the server side

**Comment by visualcookie** [comment]
> I don't see the point of using this function anymore. Looks like Next Auth 5 can retrieve the user from the session cookie itself. I just imported auth from NextAuth and called `const session = await auth();` and there is my user object. But this only works on the server side

This does not work for API routes tho. I've tried various attempts now, which are stated in the documentation, along with `const session = await auth(req, res)`. I can't get the current user inside my API route, which is a bummer, since I have to return data specific to the currently signed in user only.

It's also crazy, how unmaintained the documentations are.

**Comment by jarrodmedrano** [comment]
> > I don't see the point of using this function anymore. Looks like Next Auth 5 can retrieve the user from the session cookie itself. I just imported auth from NextAuth and called `const session = await auth();` and there is my user object. But this only works on the server side
> 
> This does not work for API routes tho. I've tried various attempts now, which are stated in the documentation, along with `const session = await auth(req, res)`. I can't get the current user inside my API route, which is a bummer, since I have to return data specific to the currently signed in user only.
> 
> It's also crazy, how unmaintained the documentations are.

Have you tried it like this?

`import NextAuth from "next-auth";

import authConfig from "@/auth.config";
import {
  DEFAULT_LOGIN_REDIRECT,
  apiAuthPrefix,
  authRoutes,
  publicRoutes,
} from "@/routes";

const { auth } = NextAuth(authConfig);

export default auth((req) => {
  const { nextUrl } = req;
  const isLoggedIn = !!req.auth;

  const isApiAuthRoute = nextUrl.pathname.startsWith(apiAuthPrefix);
  const isPublicRoute = publicRoutes.includes(nextUrl.pathname);
  const isAuthRoute = authRoutes.includes(nextUrl.pathname);

  if (isApiAuthRoute) {
    return null;
  }

  if (isAuthRoute) {
    if (isLoggedIn) {
      return Response.redirect(new URL(DEFAULT_LOGIN_REDIRECT, nextUrl))
    }
    return null;
  }

  if (!isLoggedIn && !isPublicRoute) {
    let callbackUrl = nextUrl.pathname;
    if (nextUrl.search) {
      callbackUrl += nextUrl.search;
    }

    const encodedCallbackUrl = encodeURIComponent(callbackUrl);

    return Response.redirect(new URL(
      `/auth/login?callbackUrl=${encodedCallbackUrl}`,
      nextUrl
    ));
  }

  return null;
})

// Optionally, don't invoke Middleware on some paths
export const config = {
  matcher: ['/((?!.+\\.[\\w]+$|_next).*)', '/', '/(api|trpc)(.*)'],
}`

This will only work on Edge though. I am not able to use it because I am using pg

**Comment by visualcookie** [comment]
> > > I don't see the point of using this function anymore. Looks like Next Auth 5 can retrieve the user from the session cookie itself. I just imported auth from NextAuth and called `const session = await auth();` and there is my user object. But this only works on the server side
> > 
> > 
> > This does not work for API routes tho. I've tried various attempts now, which are stated in the documentation, along with `const session = await auth(req, res)`. I can't get the current user inside my API route, which is a bummer, since I have to return data specific to the currently signed in user only.
> > It's also crazy, how unmaintained the documentations are.
> 
> Have you tried it like this?
> 
> ```
> 
> import authConfig from "@/auth.config";
> import {
>   DEFAULT_LOGIN_REDIRECT,
>   apiAuthPrefix,
>   authRoutes,
>   publicRoutes,
> } from "@/routes";
> 
> const { auth } = NextAuth(authConfig);
> 
> export default auth((req) => {
>   const { nextUrl } = req;
>   const isLoggedIn = !!req.auth;
> 
>   const isApiAuthRoute = nextUrl.pathname.startsWith(apiAuthPrefix);
>   const isPublicRoute = publicRoutes.includes(nextUrl.pathname);
>   const isAuthRoute = authRoutes.includes(nextUrl.pathname);
> 
>   if (isApiAuthRoute) {
>     return null;
>   }
> 
>   if (isAuthRoute) {
>     if (isLoggedIn) {
>       return Response.redirect(new URL(DEFAULT_LOGIN_REDIRECT, nextUrl))
>     }
>     return null;
>   }
> 
>   if (!isLoggedIn && !isPublicRoute) {
>     let callbackUrl = nextUrl.pathname;
>     if (nextUrl.search) {
>       callbackUrl += nextUrl.search;
>     }
> 
>     const encodedCallbackUrl = encodeURIComponent(callbackUrl);
> 
>     return Response.redirect(new URL(
>       `/auth/login?callbackUrl=${encodedCallbackUrl}`,
>       nextUrl
>     ));
>   }
> 
>   return null;
> })
> 
> // Optionally, don't invoke Middleware on some paths
> export const config = {
>   matcher: ['/((?!.+\\.[\\w]+$|_next).*)', '/', '/(api|trpc)(.*)'],
> }
> ```
> 
> This will only work on Edge though. I am not able to use it because I am using pg

Tried this idea too, but still that does not seem to work at all and even gives me a redirection error. Since I'm using Drizzle with a PG DB, I will now submit an API call with a custom header.

``` typescript
const session = await auth()
console.log(session?.user)
const data = await fetch('http://localhost:3000/api/pressure', {
  headers: {
    'X-User-Id': session?.user?.id as string,
  },
}).then((res) => res.json())
console.log(data)
```

**Comment by ndom91** [comment]
We shipped updated docs the other day and they include a specific section on "getting user session" which should be more straight forward to use :pray: 

https://authjs.dev/getting-started/session-management?sessionTab=get-session

**Comment by ndom91** [comment]
I'm going to close this issue as `getToken` has been deprecated in v5 and the new docs no longer recommend it

**Comment by figure002** [comment]
> We shipped updated docs the other day and they include a specific section on "getting user session" which should be more straight forward to use 🙏
> 
> https://authjs.dev/getting-started/session-management?sessionTab=get-session

I'm getting a 404

**Comment by PestoP** [comment]
> > We shipped updated docs the other day and they include a specific section on "getting user session" which should be more straight forward to use 🙏
> > https://authjs.dev/getting-started/session-management?sessionTab=get-session
> 
> I'm getting a 404

It's https://authjs.dev/getting-started/session-management/get-session now

But IMHO, it doesn't answer correctly this issue. Perhaps, [this comment](https://github.com/nextauthjs/next-auth/issues/7913#issuecomment-2425100061) could help you
