### ISSUE TITLE
Line provider OAuth Provider returned an error

### ISSUE THREAD

**Issue by OKHand-Zy** [nextauthjs/next-auth#10308]
### Provider type

Line

### Environment

  System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
    Memory: 5.40 GB / 7.61 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash

  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    bun: 1.0.22 - ~/.nvm/versions/node/v20.11.0/bin/bun

  npmPackages:
    @auth/prisma-adapter: ^1.5.0 => 1.5.0
    next: 14.0.4 => 14.0.4
    next-auth: ^5.0.0-beta.15 => 5.0.0-beta.15
    react: ^18 => 18.2.0

### Reproduction URL

https://github.com/OKHand-Zy/AuthPervider

### Describe the issue

I use Auth.jsV5 provider google it ok ,but i use Line provider found error .
my Provider setting (in src/auth.config.ts):
```
Line({
      clientId: process.env.REACT_APP_LINE_ID,
      clientSecret: process.env.REACT_APP_LINE_SECRET,
    }),
```
this gif is my behavior:
![CallbackError](https://github.com/nextauthjs/next-auth/assets/109845859/c9a03d5e-ca4b-40d4-b7bd-dbb82cc70b64)

terminal show this message:
```
[auth][error] OAuthCallbackError: OAuth Provider returned an error .Read more at https://errors.authjs.dev#oauthcallbackerror
    at handleOAuth (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/actions/callback/oauth/callback.js:55:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.callback (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/actions/callback/index.js:35:41)
    at async AuthInternal (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/index.js:42:24)
    at async Auth (webpack-internal:///(rsc)/./node_modules/@auth/core/index.js:126:34)
    at async /home/ziyu/Web/chancetix/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:63251
ROUTE: /api/auth/signin
```
and  i found error web GET some message about this error
```
http://localhost:3000/api/auth/callback/line?error=INVALID_REQUEST&error_description=%27state%27+is+not+specified.
``` 
![authError](https://github.com/nextauthjs/next-auth/assets/109845859/ceaccc82-4559-4b26-8ab9-59acb5e0a8df)

```
http://localhost:3000/api/auth/callback/line?error=INVALID_REQUEST&error_description=%27state%27+is+not+specified.
```
![foundError](https://github.com/nextauthjs/next-auth/assets/109845859/034684d0-19de-465b-8e96-f50ddc0f3d30)

### How to reproduce

yarn 
yarn dev
http://localhost:3000/auth/login
Go to Click Line Button 
=> fail go to  http://localhost:3000/api/auth/signin?error=OAuthCallbackError

### Expected behavior

Click Line Button and it go to http://localhost:3000/api/auth/signin?error=OAuthCallbackError , and show message "Try signing in with a different account.'

**Comment by OKHand-Zy** [comment]
Oh~I find answord in here https://github.com/nextauthjs/next-auth/issues/9596#issuecomment-1977762487
i add ```checks: ["state"]``` in Line provider is working

**Comment by ghostza1209** [comment]
> Oh~I find answord in here [#9596 (comment)](https://github.com/nextauthjs/next-auth/issues/9596#issuecomment-1977762487) i add `checks: ["state"]` in Line provider is working

thanks, it works
