### ISSUE TITLE
Jose modules version 4.15.5 is vulnerable

### ISSUE THREAD

**Issue by JosielHernandezDev** [nextauthjs/next-auth#10307]
### Environment

![image](https://github.com/nextauthjs/next-auth/assets/73715766/c63c75d7-c148-4ba1-baec-025204c9b80d)

### Reproduction URL

https://github.com/advisories/GHSA-hhhv-q57g-882q

### Describe the issue

jose module require into next-auth is vulnerable to resource exhaustion via specifically crafted JWE with compressed plaintext

### How to reproduce

run  -> npm audit

![image](https://github.com/nextauthjs/next-auth/assets/73715766/8308074f-ac85-4012-99fa-2758cd113fa6)

### Expected behavior

should be done  npm audit step

**Comment by balazsorban44** [comment]
https://github.com/panva/jose/security/advisories/GHSA-hhhv-q57g-882q ^4.15.5 is fine which NextAuth.js v4 is using, make sure to upgrade: https://github.com/nextauthjs/next-auth/blob/bd1d91383ae96e1710cd38bdb55881b43e6ea3d3/packages/next-auth/package.json#L94
