### ISSUE TITLE
Cannot parse action at /session. unable to use login and can not redirect after login!

### ISSUE THREAD

**Issue by Lucifer472** [nextauthjs/next-auth#10331]
### Environment

 System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M2
    Memory: 309.91 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 17.3.1
  npmPackages:
    @auth/prisma-adapter: ^1.0.12 => 1.5.0 
    next: 14.1.2 => 14.1.2 
    next-auth: ^5.0.0-beta.9 => 5.0.0-beta.15 
    react: ^18 => 18.2.0 
    
 

### Reproduction URL

https://github.com/Lucifer472/emi-calculator

### Describe the issue

I am trying to build an App with credentials login which i have built 3 times in past but for some reason now its not working at all no matter what i do First error is in this Next JS Action

export const LoginUser = async (v: z.infer<typeof LoginSchema>) => {
  const validateData = LoginSchema.safeParse(v);

  if (!validateData.success) {
    return { error: "Invalid Fields" };
  }
  try {
    await signIn("credentials", {
      email: validateData.data.email,
      password: validateData.data.password,
      redirect: false,
    });

    return {success:"Login Successful"}
  } catch (error) {
    console.log(error);
    return { error: "something went wrong" };
  }
};

I am unable to redirect the user no matter what i do so i decided to make redirect false but now my middleware file is not working i am keep getting this error in the file

 overload matches this call.
  Overload 1 of 4, '(args_0: GetServerSidePropsContext): Promise<Session | null>', gave the following error.
    Argument of type '(req: NextAuthRequest) => Response | null' is not assignable to parameter of type 'GetServerSidePropsContext'.
  Overload 2 of 4, '(args_0: (req: NextAuthRequest) => void | Response | Promise<void | Response>): AppRouteHandlerFn', gave the following error.
    Argument of type '(req: NextAuthRequest) => Response | null' is not assignable to parameter of type '(req: NextAuthRequest) => void | Response | Promise<void | Response>'.
      Type 'Response | null' is not assignable to type 'void | Response | Promise<void | Response>'.
        Type 'null' is not assignable to type 'void | Response | Promise<void | Response>'.ts(2769)
Parameter 'req' implicitly has an 'any' type.ts

also my midleware file is not working at all

import NextAuth from "next-auth";
import authConfig from "@/auth.config";
import { loginPaths, redirect_path } from "@/routes";

const { auth } = NextAuth(authConfig);

export default auth((req) => {
  const { nextUrl } = req;
  const isLoggedIn = !!req.auth;

  console.log(req.auth); // this console log keeps outputting bad request

  if (isLoggedIn) {
    if (nextUrl.pathname === "/login") {
      return Response.redirect(new URL(redirect_path, nextUrl));
    }
    return null;
  }

  if (loginPaths.includes(nextUrl.pathname)) {
    return Response.redirect(new URL("/login", nextUrl));
  }

  return null;
});

export const config = {
  matcher: ["/((?!.+\\.[\\w]+$|_next).*)", "/", "/(api|trpc)(.*)"],
};

and in my console i keep getting this error

[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (webpack-internal:///(middleware)/./node_modules/@auth/core/lib/utils/web.js:105:15)
    at toInternalRequest (webpack-internal:///(middleware)/./node_modules/@auth/core/lib/utils/web.js:37:40)
    at Auth (webpack-internal:///(middleware)/./node_modules/@auth/core/index.js:84:103)
    at getSession (webpack-internal:///(middleware)/./node_modules/next-auth/lib/index.js:20:60)
    at handleAuth (webpack-internal:///(middleware)/./node_modules/next-auth/lib/index.js:134:35)
    at Object.request [as handler] (webpack-internal:///(middleware)/./node_modules/next-auth/lib/index.js:111:24)
    at eval (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/adapter.js:193:27)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/async-storage/request-async-storage-wrapper.js:81:24)
    at eval (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/adapter.js:180:122)  

### How to reproduce

i do not know how to reproduce it but i am using PRISM ORM (MySQL DATABASE) with Next-Auth V5

but you can checkout my repo: https://github.com/Lucifer472/emi-calculator

### Expected behavior

It should login in the user!

**Comment by 42tte** [comment]
I got the same when I added `NEXTAUTH_URL`, this need to end with `/api/auth` (or your custom path to auth)

**Comment by KasperiP** [comment]
I believe this is a fairly common problem. As @42tte suggested, adding `/api/auth` to your NEXTAUTH_URL fixes the issue, at least in the latest version. However, I think the [documentation](https://authjs.dev/getting-started/providers/oauth-tutorial#setting-up-nextauth_url) is somewhat misleading regarding this aspect.

> When deploying your site, you need to set the NEXTAUTH_URL environment variable to the **canonical URL** of your website:
> NEXTAUTH_URL=https://example.com

**Comment by ThangHuuVu** [comment]
duplicated of https://github.com/nextauthjs/next-auth/issues/10081

**Comment by Lucifer472** [comment]
well it fixes the issue when i added http://localhost:3000/api/auth but there is still a typescript error in my middleware which i don't understand at all

No overload matches this call.
  Overload 1 of 4, '(args_0: GetServerSidePropsContext): Promise<Session | null>', gave the following error.
    Argument of type '(req: NextAuthRequest) => Response | null' is not assignable to parameter of type 'GetServerSidePropsContext'.
  Overload 2 of 4, '(args_0: (req: NextAuthRequest) => void | Response | Promise<void | Response>): AppRouteHandlerFn', gave the following error.
    Argument of type '(req: NextAuthRequest) => Response | null' is not assignable to parameter of type '(req: NextAuthRequest) => void | Response | Promise<void | Response>'.
      Type 'Response | null' is not assignable to type 'void | Response | Promise<void | Response>'.
        Type 'null' is not assignable to type 'void | Response | Promise<void | Response>'
        
this is the error

**Comment by Lucifer472** [comment]
but now there is another weird error it works only if i go and reload my env everytime i login into the app so if login like normal i get an error and then i go to env and press ctrl + s and login works which pretty weird!
