### ISSUE TITLE
Build fails on latest Sveltekit 2 and @auth/sveltekit

### ISSUE THREAD

**Issue by subpublic** [nextauthjs/next-auth#10332]
### Environment

 System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M1
    Memory: 45.52 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.8.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 17.3.1
  npmPackages:
    @auth/sveltekit: ^0.14.0 => 0.14.0 

### Reproduction URL
https://stackblitz.com/edit/sveltejs-kit-template-default-furqfa?file=README.md
or
https://github.com/subpublic/sveltekit2-auth-failing

### Describe the issue

Build fails on latest sveltekit and @auth/sveltekit

```
TypeError: Cannot read properties of undefined (reading 'length')
    at Object.handle (/.svelte-kit/output/server/chunks/hooks.server.js:136:26)
    at respond (/.svelte-kit/output/server/index.js:2603:43)

node:internal/event_target:1033
  process.nextTick(() => { throw err; });
                           ^
```

### How to reproduce

Installing the latest sveltekit 2 demo repo
Installing @auth/sveltekit
Follow usage instructions on
https://authjs.dev/reference/sveltekit
(adding auth.ts and hooks.server.ts)

### Expected behavior

Build should succeed

**Comment by syslev** [comment]
I have this exact issue as well. This is the line that is causing the error:

```ts
      const action = url.pathname.slice(
        // @ts-expect-error - basePath is defined in setEnvDefaults
        _config.basePath.length + 1
      ).split("/")[0];
```
Here is the link to this in the code: https://github.com/nextauthjs/next-auth/blob/e9a3e8ea527eb93621f75edbc650e1e31411346d/packages/frameworks-sveltekit/src/lib/index.ts#L362

**Comment by subpublic** [comment]
Solved it now by adding `basePath` inside the config
```
export const { handle, signIn, signOut } = SvelteKitAuth({
	basePath: ''
});
```

The documentation says it's optional, so should probably have a default setting
https://authjs.dev/reference/core#authconfig
```
basePath?: string;
```

**Comment by ThangHuuVu** [comment]
thanks for reporting this, the issue happens when you have a `prerender` page `export const prerender = true
`
