### ISSUE TITLE
Provide front-end code example for Passkeys

### ISSUE THREAD

**Issue by DePasqualeOrg** [nextauthjs/next-auth#10346]
### What is the improvement or update you wish to see?

I'd love to integrate Passkeys into my app, but it's not clear to me how to do this on the front end based on the [documentation](https://authjs.dev/reference/core/providers/passkey). It would be good to provide code examples in the major frameworks supported by Auth.js (I'm using SvelteKit).

### Is there any context that might help us understand?

See above

### Does the docs page already exist? Please link to it.

https://authjs.dev/reference/core/providers/passkey

**Comment by ndom91** [comment]
I see you've stumbled over the passkeys provider :sweat_smile:. It's not really been publicly announced and the docs aren't public yet either as we're still working on it internally.

It's only working with Next.js + Prisma atm btw.

Keep an eye on this PR though (https://github.com/nextauthjs/next-auth/pull/9924) and we'll announce the docs soon too :+1:
