### ISSUE TITLE
Comply to Vercel Open Source sponsorship

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#1035]
**Summary of proposed feature**

- A Vercel banner in the footer of each site page.
- A Vercel banner in the source repository's README.md file.
- All links back to Vercel should use a UTM tag with the format: ?utm_source=[team-name]&utm_campaign=oss

See the full list of criteria:
https://vercel.com/knowledge/can-vercel-sponsor-my-open-source-project

**Purpose of proposed feature**

We could make sure that everyone in our core team has access to the Vercel dashboard.

**Additional context**
You can find the [banner here](https://github.com/nextauthjs/next-auth/blob/canary/www/static/img/powered-by-vercel.svg).

**Comment by suraj10k** [comment]
Hey can I get assigned this issue?

**Comment by balazsorban44** [comment]
Yes, it's yours! 😊

**Comment by suraj10k** [comment]
where exactly in the readme.md file do you want the Vercel banner?

**Comment by balazsorban44** [comment]
I guess we could add it to the Acknowledgements section, with some text:

"Thanks to Vercel sponsoring this project by allowing it to be deployed for free for the entire NextAuth.js Team."

Or something similar. Not sure about the wording

**Comment by balazsorban44** [comment]
@suraj10k Do you have any information on your progress? 🙂 Do you need further assistance?

**Comment by suraj10k** [comment]
hey sorry i was a little busy due to exams. i have added the banner to the readme file . with the provided text, would you like the Vercel banner to lead to any specific website?

**Comment by balazsorban44** [comment]
@suraj10k understandable! Thanks for getting back to this.

> All links back to Vercel should use a UTM tag with the format: ?utm_source=[team-name]&utm_campaign=oss

I guess we could link the user to `https://vercel.com?utm_source=[team-name]&utm_campaign=oss`


Could you open a PR on this already? It doesn't have to be finished, it would just make it easier to track your progess. 🙂

**Comment by suraj10k** [comment]
ok i opened a PR
