### ISSUE TITLE
Login and Middleware not working in producation or in localhost

### ISSUE THREAD

**Issue by Lucifer472** [nextauthjs/next-auth#10356]
### Environment

 System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M2
    Memory: 72.05 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 17.3.1
  npmPackages:
    @auth/prisma-adapter: ^1.2.0 => 1.5.0 
    next: 14.1.0 => 14.1.0 
    next-auth: ^5.0.0-beta.5 => 5.0.0-beta.15 
    react: ^18 => 18.2.0 

### Reproduction URL

https://github.com/Lucifer472/emi-calculator

### Describe the issue

So here is what happening i am using credentials provider to make sing up using email and password and i have done this in past 3-4 times.. and i am following those same code lines but first the middleware is not working it does not protect my site at all 

import NextAuth from "next-auth";
import authConfig from "@/auth.config";
import { loginPaths, redirect_path } from "@/routes";

const { auth } = NextAuth(authConfig);

export default auth((req) => {
  const isLoggedIn = !!req.auth;
  const { nextUrl } = req;

  console.log(isLoggedIn);

  if (isLoggedIn) {
    if (nextUrl.pathname === "/login") {
      return Response.redirect(new URL(redirect_path, nextUrl));
    }
    return;
  }

  if (loginPaths.includes(nextUrl.pathname)) {
    return Response.redirect(new URL("/login", nextUrl));
  }

  return;
});

export const config = {
  matcher: ["/((?!.+\\.[\\w]+$|_next).*)", "/", "/(api|trpc)(.*)"],
};

here is the middleware code second login does not work i am using server actions
this is the action 

"use server";
import { signIn } from "@/auth";
import { redirect_path } from "@/routes";
import { LoginSchema } from "@/schema";
import { AuthError } from "next-auth";
import * as z from "zod";

export const LoginUser = async (v: z.infer<typeof LoginSchema>) => {
  const validateData = LoginSchema.safeParse(v);

  if (!validateData.success) {
    return { error: "Invalid Fields" };
  }
  try {
    await signIn("credentials", {
      email: validateData.data.email,
      password: validateData.data.password,
      redirect: true,
      redirectTo: redirect_path,
    });

    return { success: "Login Successful" };
  } catch (error) {
    console.log(error);
    return { error: "something went wrong" };
  }
};

i am getting next redirect error if don't redirect then i get can't parse session at ./ error

i tried removing the nextauth url it kind works sometimes sometimes it does not but in producation it just plain and simply don't work with out the nextauth url so i have no idea what to do

### How to reproduce

Check out my repo for:
https://github.com/Lucifer472/emi-calculator

### Expected behavior

Middleware should protect my site and redirect should redirect instead of giving me redirect error!

**Comment by AdityaBorkar** [comment]
I am facing the same issue. I **suspect** there's a problem in supporting edge environment. Since middlewares use edge environment, it gives this error. I am getting this error trace:

```
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (/home/aditya/projects/leo/.next/server/edge/chunks/43de1_@auth_core_402597._.js:914:27)
    at Module.toInternalRequest (/home/aditya/projects/leo/.next/server/edge/chunks/43de1_@auth_core_402597._.js:858:40)
    at Module.Auth (/home/aditya/projects/leo/.next/server/edge/chunks/43de1_@auth_core_402597._.js:4896:265)
    at getSession (/home/aditya/projects/leo/.next/server/edge/chunks/node_modules__pnpm_a06365._.js:4201:231)
    at handleAuth (/home/aditya/projects/leo/.next/server/edge/chunks/node_modules__pnpm_a06365._.js:4315:35)
    at Object.request [as handler] (/home/aditya/projects/leo/.next/server/edge/chunks/node_modules__pnpm_a06365._.js:4296:24)
    at /home/aditya/projects/leo/.next/server/edge/chunks/_a25a4e._.js:6720:27
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (/home/aditya/projects/leo/.next/server/edge/chunks/_a25a4e._.js:2907:24)
    at /home/aditya/projects/leo/.next/server/edge/chunks/_a25a4e._.js:6707:395
```

**Comment by AdityaBorkar** [comment]
UPDATE: My issue has been resolved.

It was my bad that I did `AUTH_URL=https://customdomain.com` instead of `AUTH_URL=https://customdomain.com/api/auth`

@Lucifer472 Can you confirm what's your AUTH_URL or NEXTAUTH_URL value?

**Comment by Lucifer472** [comment]
Ok its working but only if i use AUTH_URL it does not work with NEXTAUTH_URL..

**Comment by OborrinLucas** [comment]
@Lucifer472 please, I'm facing the same issue. Is it in the .env that you're adding it ?
