### ISSUE TITLE
MongoServerSelectionError: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by YuriGor** [nextauthjs/next-auth#1037]
**Describe the bug**
Bug in typeorm dep

**Steps to reproduce**

- Execute [`create-next-app`](https://github.com/vercel/next.js/tree/canary/packages/create-next-app) with [npm](https://docs.npmjs.com/cli/init) or [Yarn](https://yarnpkg.com/lang/en/docs/cli/create/) to bootstrap the example:
```bash
npx create-next-app --example with-next-auth with-next-auth-app
```
- Configure to use MongoDB Atlas.
- Configure Google OAuth
- run `npm run dev`
- try to login

**Expected behavior**
Should work

**Screenshots or error logs**
```bash

https://next-auth.js.org/errors#adapter_connection_error
[next-auth][error][oauth_callback_handler_error] TypeError: Cannot destructure property 'manager' of 'connection' as it is null.
    at Object.<anonymous> (/home/gor/Development/planzed/node_modules/next-auth/dist/adapters/typeorm/index.js:102:9)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/gor/Development/planzed/node_modules/next-auth/dist/adapters/typeorm/index.js:28:103)
    at _next (/home/gor/Development/planzed/node_modules/next-auth/dist/adapters/typeorm/index.js:30:194) 
https://next-auth.js.org/errors#oauth_callback_handler_error
```

**Additional context**
Issue should be fixed in typorm@v0.2.30
https://github.com/typeorm/typeorm/issues/7009#issuecomment-749398661

Here is my pr: #1036
but v0.2.30 is not published yet.

**Feedback**
* [x] N/A
* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
isn't this a duplicate of #833?

**Comment by YuriGor** [comment]
Yes, looks like dup, sorry, will try workarounds there
Looks like incoming typorm v0.2.30 is also going to fix this in a straightforward way.
