### ISSUE TITLE
Apple times out on canary

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#1038]
> I'm testing Sign in with Apple, and just getting a task timeout on Vercel. Not sure why that is, though!

> [POST] /api/auth/callback/apple - Task timed out after 10.01 second

originally posted by @ryangittings in #1026

Worked in canary 8

**Comment by balazsorban44** [comment]
Ryan, does this happen locally, or only on Vercel?

**Comment by ryangittings** [comment]
I've only tested on Vercel, both on canary 8 and canary 10. 8 worked, but 10 didn't!

**Comment by ryangittings** [comment]
Let me know if I can help at all!

**Comment by balazsorban44** [comment]
@ryangittings Could you check if canary 14 works with Apple on Vercel now? I found a related bug that I fixed now.
