### ISSUE TITLE
ERR_INVALID_URL

### ISSUE THREAD

**Issue by themixednuts** [nextauthjs/next-auth#10408]
### Environment

  System:
    OS: Linux 6.5 Linux Mint 21.3 (Virginia)
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 20.12 GB / 31.26 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 21.7.1 - /usr/bin/node
    npm: 10.5.0 - /usr/bin/npm
    pnpm: 8.15.1 - ~/.local/share/pnpm/pnpm
    bun: 1.0.35 - ~/.bun/bin/bun
  Browsers:
    Chrome: 122.0.6261.128
  npmPackages:
    @auth/core: ^0.28.1 => 0.28.1 
    @auth/sveltekit: ^0.14.1 => 0.14.1

### Reproduction URL

https://github.com/themixednuts/sveltekit-example

### Describe the issue

Error thrown for invalid url

```
code: 'ERR_INVALID_URL',
input: 'http:://localhost:5173'
```

Issue comes from file `@auth/core/lib/utils/env.js` line 80 in src, 66 in node_modules 

```ts
url = new URL(`${detectedProtocol}://${detectedHost}`); // detectedProtocol logs out 'http:' 
```

### How to reproduce

create project, handle middleware and call locals.auth()

### Expected behavior

Remove ':' or handle

**Comment by AlbertMarashi** [comment]
Also getting this issue

Old code was
```
export function createActionURL(action, headers, basePath) {
    let url = env.AUTH_URL;
    if (!url) {
        const host = headers.get("x-forwarded-host") ?? headers.get("host");
        const proto = headers.get("x-forwarded-proto");
        
        url = `${proto === "http" || dev ? "http" : "https"}://${host}${basePath}`;
    }
    return new URL(`${url.replace(/\/$/, "")}/${action}`);
}
```

New library code is:
    
```ts
export function createActionURL(action, protocol, headers, envObject, basePath) {
    let envUrl = envObject.AUTH_URL ?? envObject.NEXTAUTH_URL;
    let url;
    if (envUrl) {
        url = new URL(envUrl);
        if (basePath && basePath !== "/" && url.pathname !== "/") {
            logger.warn(url.pathname === basePath
                ? "env-url-basepath-redundant"
                : "env-url-basepath-mismatch");
            url.pathname = "/";
        }
    }
    else {
        const detectedHost = headers.get("x-forwarded-host") ?? headers.get("host");
        const detectedProtocol = headers.get("x-forwarded-proto") ?? protocol ?? "https";
        url = new URL(`${detectedProtocol}://${detectedHost}`);
    }
    // remove trailing slash
    const sanitizedUrl = url.toString().replace(/\/$/, "");
    if (basePath) {
        // remove leading and trailing slash
        const sanitizedBasePath = basePath?.replace(/(^\/|\/$)/g, "") ?? "";
        return new URL(`${sanitizedUrl}/${sanitizedBasePath}/${action}`);
    }
    return new URL(`${sanitizedUrl}/${action}`);
}
```

**Comment by AlbertMarashi** [comment]
Downgrading one patch version fixes the bug

**Comment by Carlos-err406** [comment]
also getting this

**Comment by rachitpant** [comment]
If you downgrade , you wont have to deal with this url issue , but the signout page would have an extra "/signout". Something that was fixed with https://github.com/nextauthjs/next-auth/pull/9901

**Comment by rachitpant** [comment]
The old code worked for me , the signin urls always used to start with http in dev before this update , I am using express/auth with netlify functions ( `netlify dev` ) , so there is no way for me to control if netlify sets `x-forwarded-proto` before forwarding the request.
Now the signin urls are all starting with `https` for me.

**Comment by rachitpant** [comment]
> The old code worked for me , the signin urls always used to start with http in dev before this update , I am using express/auth with netlify functions ( `netlify dev` ) , so there is no way for me to control if netlify sets `x-forwarded-proto` before forwarding the request. Now the signin urls are all starting with `https` for me.

Ok , i was able to get this working locally with netlify dev , there is a way to add redirect header.
```
[[redirects]]
  force = true
  from = "/oauth/*"
  status = 200
  to = "/.netlify/functions/oauth/:splat"
  [redirects.headers]
    X-Forwarded-Proto = "http"     <<----
```
