### ISSUE TITLE
Issue with determining the protocol when converting an incoming express request to web request.

### ISSUE THREAD

**Issue by rachitpant** [nextauthjs/next-auth#10434]
### Environment

node 20.11.1 , mac m2 pro

### Reproduction URL

https://github.com/rachitpant/basic_netlify

### Describe the issue

The `http-api-adapter` in the `@auth/express` package checks the incoming express requests protocol before converting to web request.. This works fine in most cases. However when the express app is run in a serverless context locally ( eg. using `netlify dev` ) , an http request is simulated to https. Atleast netlify does this. I am talking about the below code.
```
/**
 * Adapts an Express Request to a Web Request, returning the Web Request.
 */
export function toWebRequest(req) {
    const url = req.protocol + "://" + req.get("host") + req.originalUrl;
    const headers = new Headers();
```

I noticed that in other parts of `@auth/core` package , we are not just relying on the req protocol for this reason. Instead we are checking the header 'x-forwared-proto'. This is a really nice solution. It allows the developer to set this protocol locally and also this would work with a forwarding proxy. My suggestion is to use a similar approach . Even better we should re-use this method from `@auth/core` to form the url since `@auth/express` will always depend on it.

```
export function createActionURL(action, protocol, headers, envObject, basePath) {
    let envUrl = envObject.AUTH_URL ?? envObject.NEXTAUTH_URL;
    let url;
    if (envUrl) {
        url = new URL(envUrl);
        if (basePath && basePath !== "/" && url.pathname !== "/") {
            logger.warn(url.pathname === basePath
                ? "env-url-basepath-redundant"
                : "env-url-basepath-mismatch");
            url.pathname = "/";
        }
    }
    else {
        const detectedHost = headers.get("x-forwarded-host") ?? headers.get("host");
        const detectedProtocol = headers.get("x-forwarded-proto") ?? protocol ?? "https";
        url = new URL(`${detectedProtocol}://${detectedHost}`);
    }
    // remove trailing slash
    const sanitizedUrl = url.toString().replace(/\/$/, "");
    if (basePath) {
        // remove leading and trailing slash
        const sanitizedBasePath = basePath?.replace(/(^\/|\/$)/g, "") ?? "";
        return new URL(`${sanitizedUrl}/${sanitizedBasePath}/${action}`);
    }
    return new URL(`${sanitizedUrl}/${action}`);
}
```

### How to reproduce

Clone the repo locally , supply the google client id and secret and then run `netlify dev` after that visit the home page and follow the links.

### Expected behavior

The protocol should be http and not https in the first link. In the default sigin page shown in the second page , the google provider sign-in page starts with https. It should start with http and the sigin link would work if you change it to http ( using your browser dev tools )

**Comment by rachitpant** [comment]
Thank you .. that was straighforward. We can close this.

**Comment by BowlingX** [comment]
Related to this issue, this line here:

```
const url = req.protocol + "://" + req.get("host") + req.originalUrl;
```
https://github.com/nextauthjs/next-auth/blob/main/packages/frameworks-express/src/lib/http-api-adapters.ts#L48

Takes the `protocol` correctly, but `req.get("host")` will not consider the `x-forwarded-host` headers. It should be `req.hostname`  / `req.host` instead.

I will create a new issue
