### ISSUE TITLE
Next Auth token

### ISSUE THREAD

**Issue by Bohemedanslalune** [nextauthjs/next-auth#10468]
### What is the improvement or update you wish to see?

I'm interested in learning how to configure a token without any expiration date, or with an expiration date set to infinity.

### Is there any context that might help us understand?

I need a user to have a token whit no expiration (the api user)

**Comment by shadiramadan** [comment]
Security wise- if you aren't expiring the tokens you are better off making API keys and tracking them so that you can later rotate or revoke them.

**Comment by balazsorban44** [comment]
For API users/machines, you would use something like Machine-to-Machine or the OAuth Client credentials flow, and you won't need Auth.js. See https://oauth.net/2/grant-types/client-credentials/
