### ISSUE TITLE
Need discussion about the "refresh_token_expires_in" field.

### ISSUE THREAD

**Issue by SH5H** [nextauthjs/next-auth#10474]
### What is the improvement or update you wish to see?

Since "github" is not the only one that supports this field, it would be good to mention in the documentation which providers support this field and provide a workaround.

### Is there any context that might help us understand?

I found that one of built-in providers, kakao, supports the "refresh_token_expires_in" field, so we did some additional work accordingly.

**Comment by ndom91** [comment]
What would you like to use this field for exactly? We don't document every additional field that each provider supports / returns, so I don't think that makes sense, but maybe we can come up with a more spec-compliant / supported way to do what you're trying to do :thinking:

**Comment by SH5H** [comment]
By default, this field throws an error when used with the Prisma adapter. Personally, I'd like to see a small mention on the Prisma adapter page about the error and workaround when using a provider that supports this field.

**Comment by balazsorban44** [comment]
Hi, I will close this issue, because as of v5 and other Auth.js libraries, `refresh_token_expires_in` won't be part of the default `Account`.

See: https://github.com/nextauthjs/next-auth/blob/862a505782588a0760721eafb6a3bb905f3e383f/packages/core/src/lib/utils/providers.ts#L114-L124

**Comment by SH5H** [comment]
Nothing has been decided in this issue.
Multiple providers use the `refresh_token_expires_in` field, 
I thought it would be nice to address this issue at the library level, so I created this issue.
But, as I said, nothing is set in stone here, so you should probably check with Pinterest itself to make sure they haven't changed the specification.

> What happened here? We've been using NextAuth for 4 years, now all of a sudden Pinterest crashes because of this: `Unknown argument "refresh_token_expires_at". Did you mean "refresh_token_expires_in"?`
> 
> If you decided to change fields in the schema for Prisma adapters, why is it not backwards compatible? Or are we missing something?
> 
> ![Image](https://github.com/user-attachments/assets/8cf21f26-709b-419d-bb78-8a669b3b6a72)
