### ISSUE TITLE
Replace node-oauth dependency

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#1048]
https://github.com/ciaranj/node-oauth Is a library we use to communicate with OAuth providers. Although it works, we have already patched it in many places, mainly because it uses callbacks over Promises, and the library itself looks abandoned. (Last commit was in 2017).

We should either get rid of it, or replace it fully.

[`node-openid-client`](https://github.com/panva/node-openid-client) looks like a nice alternative, but it does not seem to support OAuth 1.0.

We could add it now, and only utilize it for OAuth 2 and OIDC flows, and we could remove OAuth 1 support at a later point. (It would be a breaking change)

As far as I can tell, only the Twitter provider uses OAuth 1.

Ref: https://developer.twitter.com/en/docs/authentication/api-reference/token

**Comment by franleplant** [comment]
I have used the proposed lib extensively and it is awesome. One thing that is obviously missing from next-auth is the discovery mechanism that oidc providers have by which the only provider config is the main url, the client will request all the remaining configs (discovery doc) to the provider and you are good to go

**Comment by balazsorban44** [comment]
True! It's nice, but would require an additional request to an external endpoint. It could be a nice fallback though incase we want to call an endpoint that was not defined by the user where we could add a very specific warning how they could define it statically.
