### ISSUE TITLE
Argument of type 'null' is not assignable to parameter of type 'SignInOptions | undefined'.ts(2345)

### ISSUE THREAD

**Issue by snrnieto** [nextauthjs/next-auth#10486]
### What is the improvement or update you wish to see?

In the documentation [https://next-auth.js.org/getting-started/client](https://next-auth.js.org/getting-started/client) 
![image](https://github.com/nextauthjs/next-auth/assets/49009866/46a171bb-1d32-46ef-9269-ada4cf97881b)

says i can put this line signIn("identity-server4", null, { prompt: "login" }) to always ask the user to re-authenticate, but i am trying to place that line in my code but i am getting this error

![image](https://github.com/nextauthjs/next-auth/assets/49009866/7468ab34-a410-4e0b-a8a9-1b810c8f405f)

Could someone help me to fix this or what is the correct way to do it please, i want to ask for the user to re login on every click of the Login Button.

### Is there any context that might help us understand?

Could someone help me to fix this or what is the correct way to do it please, i want to ask for the user to re login on every click of the Login Button.

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/getting-started/client

**Comment by ndom91** [comment]
What version of `next-auth` are you using? That documentation is for `v4` and below.

The new docs (https://authjs.dev/guides/configuring-oauth-providers) include some updated info on this.

**Comment by snrnieto** [comment]
I solved it like this

`signIn("azure-ad", {}, { prompt: "login" });`

**Comment by snrnieto** [comment]
I solved it like this

signIn("azure-ad", {}, { prompt: "login" });
