### ISSUE TITLE
Github and Discord providers ship incorrect SVGs that blend in with the background colour.

### ISSUE THREAD

**Issue by abhishekjaiswar221** [nextauthjs/next-auth#10481]
### Provider type

Discord, GitHub

### Environment

System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz
    Memory: 1.06 GB / 7.79 GB

  Binaries:
    Node: 20.9.0 - C:\Program Files\NodeJs\node.EXE
    Yarn: 1.22.19 - D:\JSpiders Institute\Piyush Garg Code\piyushgarg-dev\node_modules\.bin\yarn.CMD
    npm: 9.8.1 - C:\Program Files\NodeJs\npm.CMD
    pnpm: 8.14.2 - ~\AppData\Roaming\npm\pnpm.CMD

  Browsers:
    Edge: Chromium (123.0.2420.65)
    Internet Explorer: 11.0.22621.1

  npmPackages:
    next: ^13.1.1 => 13.4.5
    next-auth: ^4.18.10 => 4.22.1
    react: 18.2.0 => 18.2.0

### Reproduction URL

https://github.com/piyushgarg-dev/piyushgargdev-nextjs/blob/main/pages/api/auth/%5B...nextauth%5D.js

### Describe the issue

The SVGs that are delivered by Github and Discord providers are wrong and mix in with the background colour.
It appears that instead of providing light SVG's in dark mode, the providers are shipping dark SVG's in dark mode.
![image](https://github.com/nextauthjs/next-auth/assets/113609441/da05562a-6afa-4481-94a6-1e80d9974240)

### How to reproduce

Go to https://www.piyushgarg.dev/
Click Login in the navigation bar.
![image](https://github.com/nextauthjs/next-auth/assets/113609441/8076dab7-ac2d-49d8-aaff-f96292f1ef18)

### Expected behavior

The providers should ship light SVGs in dark mode and dark SVGs in light mode.

**Comment by Bisxsh** [comment]
Seems like this issue has been resolved with https://github.com/nextauthjs/next-auth/pull/10542 standardising the bg colour for all providers

**Comment by abhishekjaiswar221** [comment]
@Bisxsh Bro. I don't think the issue is solved because the problem appears to be still there. 
Do visit the link https://www.piyushgarg.dev/api/auth/signin?callbackUrl=https%3A%2F%2Fwww.piyushgarg.dev%2Findex%23

**Comment by Bisxsh** [comment]
@abhishekjaiswar221 The fix went in for [next-auth@5.0.0-beta.17](https://github.com/nextauthjs/next-auth/releases/tag/next-auth%405.0.0-beta.17).
That project for the link you provided is on [v4.18.10](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/blob/main/package.json) so they won't have the changes on the website.
You'd have to create an issue on their repo to update to that version or above if you want the fix to be present there

**Comment by abhishekjaiswar221** [comment]
Hello @Bisxsh, Thank you for filling me in with that version thing. I was unaware of it, and I will absolutely create an issue in their repo to upgrade the version of next-auth to the most recent version.
And I will close this issue too.
