### ISSUE TITLE
Passkey's documentation is lacking

### ISSUE THREAD

**Issue by HunteRoi** [nextauthjs/next-auth#10482]
### What is the improvement or update you wish to see?

The first update that would be really interesting is to fix the dependency mention. We need to server one, not the browser.

Also if you could add some example of the implementation, it might help to understand how to use it (and perhaps even configure it).

### Is there any context that might help us understand?

I tried to follow the docs and it has been a real pain as the first issues I had were gibberish non-sense. By debugging, I could succeed and understand that 1) the dependency mentionned in the docs is not the right one 2) the db adapter is highly related to how the rest will work si it must be mentionned too

### Does the docs page already exist? Please link to it.

https://authjs.dev/reference/core/providers/passkey

**Comment by balazsorban44** [comment]
Hi, Passkey support is experimental, the docs is work in progress.

That said, here is a sneak peak of the new docs page that is coming out in the following days:

https://authjs-nextra-docs.vercel.app/getting-started/authentication?tab=webauthn
https://authjs-nextra-docs.vercel.app/reference/core/providers/passkey
