### ISSUE TITLE
Confusing documentation structure and lack of examples

### ISSUE THREAD

**Issue by Birddle** [nextauthjs/next-auth#10499]
### What is the improvement or update you wish to see?

Anyone else new here like me and confused about the docs?
First of all the documentation structure lacks a hands-on tutorial. A tutorial to get started like react-router. Secondly I've noticed that there is sample code everywhere, even different examples for the same API.
After following the official documentation for hours, despite being able to get a simple implementation. But I still felt uneasy.

### Is there any context that might help us understand?

Is it possible to add complete cases. Or change the structure of documentation like react-router, MUI.

**Comment by balazsorban44** [comment]
Thanks for the feedback. We have worked on a new documentation, that should be out in the folowing days, addressing a lot of the feedback we've received. Here is a sneap peek https://authjs-nextra-docs.vercel.app/

Feel free to open a new issue with more feedback, if something is missing or confusing still!

**Comment by Birddle** [comment]
> Thanks for the feedback. We have worked on a new documentation, that should be out in the folowing days, addressing a lot of the feedback we've received. Here is a sneap peek https://authjs-nextra-docs.vercel.app/
> 
> Feel free to open a new issue with more feedback, if something is missing or confusing still!

https://authjs-nextra-docs.vercel.app/getting-started/authentication?tab=credentials

<img width="1472" alt="image" src="https://github.com/nextauthjs/next-auth/assets/86408260/171ca0d0-061f-4c8d-afcd-71db69b0ac94">

There should be `signInSchema` not `createUserSchema `
