### ISSUE TITLE
Integrating @auth/mongodb-adapter breaks logging in with " SignIn from 'next-auth/react'; "

### ISSUE THREAD

**Issue by grolox69** [nextauthjs/next-auth#10524]
### Adapter type

@auth/mongodb-adapter

### Environment

"@auth/mongodb-adapter": "2.4.0"
"mongodb": "6.3.0"
"next-auth": "5.0.0-beta.16"
"next": "14.0.0"
"react": "18.2.0"

Node.js v19.6.0
Windows 11 - WSL2
Google Chrome 

#### auth.config.ts

```typescript
import { NextAuthConfig } from "next-auth";
import Google from 'next-auth/providers/google';

export default {
  secret: process.env.AUTH_SECRET,
  providers: [
    Google({
      clientId: process.env.OAUTH_CLIENT_ID as string,
      clientSecret: process.env.OAUTH_CLIENT_SECRET as string,
      authorization: {
        params: {
          scope: [
            "openid",
            "email",
            "profile",
            "https://www.googleapis.com/auth/adwords",
            "https://www.googleapis.com/auth/webmasters.readonly",
          ].join(" "),
          prompt: "consent",
          access_type: "offline",
          response_type: "code",
        },
      },
    })
  ],
  callbacks: {
    async session({ session, token, user }) {
      if (session) {
        session = Object.assign({}, session, { access_token: token.access_token })
      }
      return session;
    },
    async jwt({ token, account }) {
      if (account) {
        token = Object.assign({}, token, { access_token: account.access_token });
      }
      return token;
    },
  },
} satisfies NextAuthConfig
```

#### auth.ts

```typescript
import NextAuth from 'next-auth';
import { MongoDBAdapter } from "@auth/mongodb-adapter";
import clientPromise from 'Lib/mongodb';
import authConfig from './auth.config';

export const {
  handlers: { GET, POST },
  auth
} = NextAuth({
  ...authConfig,
  adapter: MongoDBAdapter(clientPromise),
  session: { strategy: "jwt" }
});
```

#### navbar.tsx

```typescript
"use client";
import { signIn, signOut } from 'next-auth/react';

export default function Navbar({ user }: Props) {
         ....
    return (
              ....
         <button
                  onClick={() => signIn('google')}
          >
               Sign in
         </button>
    );
}
```

### Error
After clicking signIn button:
![image](https://github.com/nextauthjs/next-auth/assets/58383371/27bea05f-62be-4c35-80f2-b1fb10f68953)

Error contains a larger number of nodejs (serverside) missing modules like: http, kerberos, snappy, aws-sdk, crypto, ...

### How to reproduce

Add signIn function imported from 'next-auth/react' to a client-component button, and click it.

### Expected behavior

Be able to signIn using this button. 

#### Note 1
This worked perfectly fine before importing adding mongodb adapter.

#### Note 2
I tried the solution in https://github.com/nextauthjs/next-auth/issues/10048, but maybe I didn't apply it correctly as I need client side auth

**Comment by balazsorban44** [comment]
answered here https://discord.com/channels/1200116961590399008/1228064180318503063

it was a `export const runtime = "edge"` in the Route Handler
