### ISSUE TITLE
email http docs link broken

### ISSUE THREAD

**Issue by A-NAME-0** [nextauthjs/next-auth#10533]
### What is the improvement or update you wish to see?

the link from here:
https://next-auth.js.org/providers/email

to here:
https://authjs.dev/guides/providers/email-http?_gl=1*1h208ba*_gcl_au*NzcwMjM2MzcwLjE3MTIyNTY2ODguNjc3NzE5MzA5LjE3MTI3ODEyOTIuMTcxMjc4MjIxNg..

is broken

### Is there any context that might help us understand?

the link is broken so I cannot access the docs relating to HTTP setup for the email provider in next auth

### Does the docs page already exist? Please link to it.

https://authjs.dev/guides/providers/email-http?_gl=1*1h208ba*_gcl_au*NzcwMjM2MzcwLjE3MTIyNTY2ODguNjc3NzE5MzA5LjE3MTI3ODEyOTIuMTcxMjc4MjIxNg..

**Comment by ndom91** [comment]
Thanks for pointing this out, we'll get it fixed.

However, this is also from the old docs - current documentation about the Email (`nodemailer`) provider and other magic link providers (`sendgrid`, `postmark` and `resend`) are available in the new docs [here](https://authjs.dev/getting-started/authentication/email).

**Comment by ndom91** [comment]
> @ndom91 it seems that Postmark provider is not yet available? 
> `Cannot find module 'next-auth/providers/postmark' or its corresponding type declarations.ts(2307)`
> version "next-auth": "^5.0.0-beta.16",

Ah you're right. It is in `main` though, so therefore will be released in the next release (`beta.17`). We're shooting for sometime this week 🤞 

In the mean time, we did bring back the custom http email provider guide for v5: https://authjs.dev/guides/configuring-http-email
