### ISSUE TITLE
fetchData Callback

### ISSUE THREAD

**Issue by RaknaXTR** [nextauthjs/next-auth#1054]
**Summary of proposed feature**
Adding extra information to the session when the user logs in.

**Purpose of proposed feature**
Like fetching the user's servers at login and assigning them to the session.

**Detail about proposed feature**
```js
callbacks: {
  fetchData: async(accessToken, session) => {
    const data = await fetch(...);
    session.user.guilds = data;
    return Promise.resolve(session);
  }
}
```

**Comment by balazsorban44** [comment]
Ho there, this is why you have the `jwt` and `session` callbacks. Please check the documentation https://next-auth.js.org/configuration/callbacks

**Comment by RaknaXTR** [comment]
But this works when every session is checked. I just want a callback that comes when the user is logged in.

**Comment by balazsorban44** [comment]
The jwt token takes several params, but all of them except the first are only available only the time the jwt is created. you can simply add an if check to add any additional data, and return the previous token in subsequent checks.
