### ISSUE TITLE
Example of how to extend JWT interface

### ISSUE THREAD

**Issue by DavDeDev** [nextauthjs/next-auth#10544]
### What is the improvement or update you wish to see?

First, congrats on these new amazing docs!

I would like to ask if you could add an example of how to extend JWT type with custom properties, like you did for the Session interface here:
![image](https://github.com/nextauthjs/next-auth/assets/104097735/7ea077a8-4da7-44d8-a432-595a1599e777)

Unfortunately, I always struggle with JWT type and a visual example would be great!

Thanks

### Is there any context that might help us understand?

I can't extends JWT with ease, and I think this type of example can benefit many devs.

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/typescript#module-augmentation

**Comment by ndom91** [comment]
If you scroll a little further down there's an example for the `JWT` interface :blush: 

Let me know if that doesn't work for you

![image](https://github.com/nextauthjs/next-auth/assets/7415984/953a14b9-1e5f-4889-9035-317461e0ed7b)

**Comment by DavDeDev** [comment]
> If you scroll a little further down there's an example for the `JWT` interface 😊
> 
> Let me know if that doesn't work for you
> 
> ![image](https://private-user-images.githubusercontent.com/7415984/321953729-953a14b9-1e5f-4889-9035-317461e0ed7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MzkxMzYsIm5iZiI6MTcxMjkzODgzNiwicGF0aCI6Ii83NDE1OTg0LzMyMTk1MzcyOS05NTNhMTRiOS0xZTVmLTQ4ODktOTAzNS0zMTc0NjFlMGVkN2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMTYyMDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI5M2RiNGFjY2UzZTE0YjM3M2Y4YmJjZjk5OWFiOTEzMDAyMzYzNjViMTE3ZDAwNGRkYzlhYmEzNGFkMDM2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Y1Jyanx4-IOckA_LeAoSV9iI-lfuWCHarVjxMAgSR44)

Hi saw that, but it doesn't work for me if I use `@auth/core` but it does when I use `next-auth/jwt`, and also you can notice some discrepancy in the two sections, the Session example augments `next-auth` module while the second section recommends to ues `@auth/core` module, which didn't work in my case. So I was wondering if you can give a full example in `@auth/core` to better understand!

Thanks for your reply!

**Comment by cbdabner** [comment]
The only way I had success was to augment everything from `next-auth` as the submodule `@auth/core/jwt` couldn't be found (pnpm project). Also means you don't have to install `@auth/core` just for typing.

_next-auth.d.ts:_
```ts next
import type { DefaultSession } from 'next-auth';

declare module 'next-auth' {
  interface Account { ... }
  interface Profile { ... }
  interface Session {
    // NOTE: Session.user contains the full User object, so you'd only need this if you
    //       really wanted to extend, specifically, Session.user in addition to User.
    user: { ... } & DefaultSession['user'];
  }
  interface User { ... }
}

declare module 'next-auth/jwt' {
  interface JWT { ... }
}
```

**Comment by ndom91** [comment]
Yeah it should always be `next-auth/*`, as a user you shouldn't have to deal with `@auth/core` at all.

We've recently fixed this in the [TypeScript](https://authjs.dev/getting-started/typescript) doc as well :pray:

**Comment by DavDeDev** [comment]
I've just saw you updated the article, thank you so much!
