### ISSUE TITLE
⨯ Error: The edge runtime does not support Node.js 'crypto' module.

### ISSUE THREAD

**Issue by Set27** [nextauthjs/next-auth#10540]
### Environment

```System:
    OS: Linux 6.5 Linux Mint 21.2 (Victoria)
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13600K
    Memory: 22.75 GB / 31.10 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.asdf/installs/nodejs/20.11.1/bin/node
    Yarn: 1.22.22 - ~/.asdf/installs/nodejs/20.11.1/bin/yarn
    npm: 10.2.4 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.15.4 - ~/.asdf/installs/nodejs/20.11.1/bin/pnpm
  Browsers:
    Chrome: 123.0.6312.86
  npmPackages:
    @auth/pg-adapter: ^0.8.0 => 0.8.0
    next: 14.1.4 => 14.1.4
    next-auth: ^5.0.0-beta.16 => 5.0.0-beta.16
    react: ^18 => 18.2.0
```

### Reproduction URL

https://github.com/Set27/nextjs-bug-repo

### Describe the issue

Reproduction from https://authjs.dev/getting-started, leads to a bug
Server Error
Error: The edge runtime does not support Node.js 'crypto' module.
Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime
![image](https://github.com/nextauthjs/next-auth/assets/49077110/b0964061-a55f-4a50-b243-8fcafaa8ef9d)

### How to reproduce

just clone
https://github.com/Set27/nextjs-bug-repo

### Expected behavior

no error

**Comment by balazsorban44** [comment]
it's nothing to do with Auth.js but the og package as shown in the error message. see https://authjs.dev/getting-started/migrating-to-v5#edge-compatibility

**Comment by umerfarooq5349** [comment]
thanks dude it works for me

**Comment by antonlvovych** [comment]
Next.js now supports configuring the Node.js runtime for middleware, resolving this issue.
Example here: https://github.com/vercel/next.js/discussions/71727#discussioncomment-12063767
