### ISSUE TITLE
middleware v5 document link to 404 page

### ISSUE THREAD

**Issue by Niko030303** [nextauthjs/next-auth#10546]
### What is the improvement or update you wish to see?

I need to see the v5 middleware docs

### Is there any context that might help us understand?

nope

**Comment by ndom91** [comment]
Hey @Niko030303 can yuo share which link 404-ed exactly what where you found it? Thanks!

**Comment by mattizhu** [comment]
I presume he means the link below, I am also seeing a 404 error:

[https://authjs.dev/getting-started/securing/middleware](https://authjs.dev/getting-started/securing/middleware)

**Comment by ndom91** [comment]
Okay great, thanks for the additional details. Its been fixed :pray:
