### ISSUE TITLE
Role-based access control "Page Not Found" 404

### ISSUE THREAD

**Issue by kusainovv** [nextauthjs/next-auth#10543]
### What is the improvement or update you wish to see?

![image](https://github.com/nextauthjs/next-auth/assets/72627773/69a7c4d5-f2a2-499a-8141-268ad18f26d2)
![image](https://github.com/nextauthjs/next-auth/assets/72627773/d86ae7af-74e5-43cd-abf9-a56d8d1f47e4)

### Is there any context that might help us understand?

I'm trying to go [this link](https://authjs.dev/guides/basics/role-based-access-control) but I'm getting 404 error.

**Comment by FuzzyNat26** [comment]
Hi there! Just to add, [the guide](https://next-auth.js.org/guides/fullstack#adding-role-based-login-to-database-session-strategy) also containing the same link, which is also not accessible.

After checking a bit, I found the updated domains.
Old: [https://authjs.dev/guides/basics/role-based-access-control](https://authjs.dev/guides/basics/role-based-access-control)
New: [https://authjs.dev/guides/role-based-access-control](https://authjs.dev/guides/role-based-access-control)
