### ISSUE TITLE
 Credentials provider broken link

### ISSUE THREAD

**Issue by AlexShonia** [nextauthjs/next-auth#10555]
### What is the improvement or update you wish to see?

should link here I'm guessing 
https://authjs.dev/getting-started/authentication/credentials#credentials-provider
instead of 
https://authjs.dev/getting-started/providers/credentials-tutorial

### Is there any context that might help us understand?

the link: "Credentials provider" is broken.

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/dashboard-app/adding-authentication#adding-the-credentials-provider

**Comment by ndom91** [comment]
Thanks for pointing this out, however this is on the Next.js docs that would need to get updated. I've reached out to the team :pray:

**Comment by balazsorban44** [comment]
Closing as this is upstream.
