### ISSUE TITLE
Reference to Auth.js | Nextjs 

### ISSUE THREAD

**Issue by suraj-sharma-911** [nextauthjs/next-auth#10559]
### What is the improvement or update you wish to see?

The reference link for [Auth.js | Next.js](https://authjs.dev/reference/nextjs) is inactive. Please update it with the correct URL for accessibility.

### Is there any context that might help us understand?

You can find the nextjs-Auth URL attached in the following link https://nextjs.org/learn/dashboard-app/adding-authentication

**Comment by ndom91** [comment]
Thanks for pointing this out, we've updated the redirect :pray:

**Comment by suraj-sharma-911** [comment]
I wanted to kindly bring to your attention that there are a few more inactive reference links that require updating:

- [oauth-tutorial](https://authjs.dev/getting-started/providers/oauth-tutorial)
- [providers](https://authjs.dev/getting-started/providers)

**Comment by ndom91** [comment]
@suraj-sharma-911 these are from the Next.js docs as well? Unfortunately we don't have any control over that, but we can add a redirect. I'll update it for those two as well :pray:
