### ISSUE TITLE
missing "Creates a user in the database and returns it"

### ISSUE THREAD

**Issue by itsOmSarraf** [nextauthjs/next-auth#10556]
### What is the improvement or update you wish to see?

Need this page

https://authjs.dev/guides/adapters/creating-a-database-adapter#user-management

### Is there any context that might help us understand?

![image](https://github.com/nextauthjs/next-auth/assets/83817663/dc70483b-4a28-4b42-b073-eca8e4bf8717)

https://authjs.dev/reference/core/adapters#createuser

**Comment by ndom91** [comment]
Thanks for pointing this out! This link and more are getting fixed [here](https://github.com/nextauthjs/next-auth/pull/10560) :pray:

**Comment by itsOmSarraf** [comment]
Thanks :D
