### ISSUE TITLE
The link to the official documentation in the index.ts file comment is not reachable.

### ISSUE THREAD

**Issue by kugorang** [nextauthjs/next-auth#10575]
### What is the improvement or update you wish to see?

The link to the Initialization documentation in the top comment of `AuthConfig` in `node_modules` is getting a 404 Not Found.

### Is there any context that might help us understand?

The path to the document is `./node_modules/@auth/core/src/index.ts`.

### Does the docs page already exist? Please link to it.

https://authjs.dev/reference/configuration/auth-options

**Comment by ndom91** [comment]
Thanks for pointing this out! It's been fixed and will be available in the next release :pray:
