### ISSUE TITLE
404 Page Not Found about next auth url

### ISSUE THREAD

**Issue by tarunama** [nextauthjs/next-auth#1057]
**Describe the bug**
```
[next-auth][warn][nextauth_url] NEXTAUTH_URL environment variable not set 
https://next-auth.js.org/warning#nextauth_url
```
404 Page Not Found https://next-auth.js.org/warning#nextauth_url

**Expected behavior**
Not 404 Page Not Found.

**Comment by balazsorban44** [comment]
Its a typo in the docs, should be `warnings` not `warning`. Care to open a PR and fix? 😊

**Comment by tarunama** [comment]
Thank you for your great working !
