### ISSUE TITLE
Documentation doesn't make clear that update() from useSession() doesn't log you out

### ISSUE THREAD

**Issue by adam-carruthers** [nextauthjs/next-auth#10598]
### What is the improvement or update you wish to see?

In the docs for `useSession()` at /docs/docs/getting-started/client.md it would be good to mention that `update()` won't update if the user is logged out (e.g: by their session expiring).

### Is there any context that might help us understand?

In the docs for `useSession()` at /docs/docs/getting-started/client.md there is no mention that `update()` won't update if the user is logged out. I was trying to use that function to auto log a user out after their session expired. However in the code, if the user is logged out by their session expiring, the update function doesn't update the SessionProvider context. Therefore my code to log the user out did not work at all and it was quite difficult to work out why.

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/getting-started/client#usesession

**Comment by balazsorban44** [comment]
You should not use this method for logging the user out, use the `signOut` method instead.

**Comment by adam-carruthers** [comment]
I just want to check if the user has been auto logged out via the timeout on their session, I don't want to log them out

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
