### ISSUE TITLE
error on middleware documentation link

### ISSUE THREAD

**Issue by anuradhan** [nextauthjs/next-auth#10601]
### What is the improvement or update you wish to see?

please fix documentation page not found error link

### Is there any context that might help us understand?

error when clicking link at https://authjs.dev/getting-started/migrating-to-v5#authenticating-server-side
to
https://authjs.dev/reference/nextjs#in-middleware

<img width="542" alt="image" src="https://github.com/nextauthjs/next-auth/assets/5119469/672c21e1-b014-4a33-8c9d-4d20a276feb5">

**Comment by ndom91** [comment]
Thanks for pointing it out! We've fixed it now :pray:
