### ISSUE TITLE
Sveltekit Custom Error Pages within /auth path

### ISSUE THREAD

**Issue by phil-w** [nextauthjs/next-auth#10607]
### What is the improvement or update you wish to see?

_(I'd do this myself but I'm not sure (a) I'm right; or (b) precisely how to do it)_

The error pages for auth.js in Sveltekit seem to be hard coded as `/auth/error`. The guide [here](https://auth-docs-pdsfz8jbx-authjs.vercel.app/guides/pages/error) has some information on this but the SvelteKit example isn't there (I've not written it...). Anyway, here's what I know.

## 1 What I want to do 
Catch user errors during 3rd party authorization via auth.js and use my standard error handling system (logging, error page, the whole shebang) for those errors, just like any other errors. It's all the same to me. And I think to users.

## 2 The Problem: obvious ways to override the canned page don't work
If you wanted to avoid the canned error screen, as I do, then you might think that either of these would work:
- you could just override the route to '/auth/error' by putting '/routes/auth/error' in SvelteKit, or 
- that the default error page `+error.svelte` would catch this

### The reason that fails
Neither works, in my case because... I have `/auth/[role]` as the root of my authenticated directory structure, so when auth.js tries to hit `/auth/error`, it hits the middleware I have in `hooks.server.js`, the stuff which looks like this:
~~~ 
import { handle as authjs } from './auth'

async function authorizationHandle({ event, resolve }) {  // Where I do my own authorization checks.
...
}
export const handle = sequence(authjs, authorizationHandle) 
~~~
I make the auth.js stuff blow up in test and get the canned error page. The error happens inside the auth.js code, and that's within the above pipeline, so there's nothing looking at redirecting it, it seems. So I get no pretty error page and no server log of what is a client event.

## 3 My solution
I may be missing something obvious, but this works. 
 - add another "handler" on the front of the chain of stuff in the middleware
 - the new handler will see the canned error page generated by auth.js...
 - .. and can redirect it to the error page where my server gets to log it
 - .. and where it can be unpacked and dealt with.
~~~ 
import { handle as authjs } from './auth'

async function authorizationHandle({ event, resolve }) {  ... }
async function errorHandle({ event, resolve }) {
	// Redirect if the error was from auth.js.
	if (event.url.pathname == '/auth/error') {
		// Send to standard error page, not within "/auth" section at all.
		throw redirect(302, `/error/authjs${event.url.search}`)	// Works but requires a redirect.
	}
	return resolve(event)
}

export const handle = sequence(authjs, authorizationHandle) 
~~~

- The downside is that this effectively throws a 404, so the "catching" code has to understand the anatomy of the auth.js specific error and all that malarkey. It does work though.

### Is there any context that might help us understand?

If your "protected" pages aren't under /auth, this may work out of the box, I'm not sure, that's not where I started. 

### Does the docs page already exist? Please link to it.

https://auth-docs-pdsfz8jbx-authjs.vercel.app/guides/pages/error

**Comment by ndom91** [comment]
@phil-w thanks for pointing that out. Yeah so as you noticed, in SvelteKit the `hooks.server.ts` will catch that route before anything else.

We do have a config option for custom pages though, check out the [api reference](https://authjs.dev/reference/core/types#pagesoptions).

It's basically the same as any other custom page configuration and would look like this:

```ts

export const { handlers, auth, signIn, signOut } = NextAuth({
  providers,
  pages: {
    error: "/auth/error",
  },
})
```

Just make sure you have a route at the `/auth/error` path then! As the api reference docs above says, you'll just get a query param with a `?error=` value on it, the link above has the possible values you can check against.

Let me know if that still doesn't help :pray:

**Comment by ndom91** [comment]
Also out of curiosity, where did you come across the preview deploy docs link? The normal produciton version is released and available under https://authjs.dev. You should use that from now on :wink:

**Comment by phil-w** [comment]
Thanks - I found the "pages" array and ripped out the more complex approach! The documentation is... confusing as there are different versions. The same URL in my mobile phone shows this "pages" information, but that same URL in a standard browser doesn't. I did double check. But maybe I'm confused; there's good documentation some places, different documentation elsewhere... and not all the documented functions work. I know, it's being migrated, I'm not complaining!

**Comment by ndom91** [comment]
I think you might have been on an earlier preview deploy. The https://authjs.dev deployment should be all app router, at least in regard to the Next.js info. There are a few code example for pages, but they are clearly marked "Next.js (Pages)" in the framework tab picker thing.

Anyway, if you do still find anything confusing let us know we'd love to improve it! :pray:

**Comment by coryvirok** [comment]
FYI I don't believe this works. I haven't found a way to host my own routes on `/auth/signin` or similar. See https://github.com/nextauthjs/next-auth/discussions/7287#discussioncomment-13768651
