### ISSUE TITLE
Broken link on https://authjs.dev/concepts/faq#security

### ISSUE THREAD

**Issue by statusunknown418** [nextauthjs/next-auth#10617]
### What is the improvement or update you wish to see?

https://authjs.dev/concepts/faq#security throws a 404 not found

### Is there any context that might help us understand?

documentation

**Comment by ndom91** [comment]
Thanks for pointing that out, where did you come across that link?

**Comment by statusunknown418** [comment]
right in here https://authjs.dev/getting-started/authentication
the FAQ link
<img width="921" alt="Screenshot 2024-04-17 at 13 00 53" src="https://github.com/nextauthjs/next-auth/assets/74371045/5ceade97-8a39-40af-b744-f17adaeb35d3">
