### ISSUE TITLE
Better exception handling in providers

### ISSUE THREAD

**Issue by arxenix** [nextauthjs/next-auth#1062]
**Summary of proposed feature**
Currently, it seems like all provider exception are caught and handled the same way -- redirect the user back to the sign up page.

**Purpose of proposed feature**
Better exception handling should be in place so that we can give better diagnostic information to the user.

**Detail about proposed feature**
In my use case, I am using a custom Discord OAuth Provider but I only want to accept users with the  `email_verified` profile field set to `true`. Currently, the only way for me to reject the invalid users is to throw an exception in my profile callback, which causes the user be redirected to signin. I am unable to provide any diagnostic information to the user.

**Potential problems**
N/A

**Describe any alternatives you've considered**
N/A

**Additional context**
https://github.com/nextauthjs/next-auth/blob/65504d691736087195ef4cb220d528064751ba70/src/server/lib/oauth/callback.js#L148

*Please indicate if you are willing and able to help implement the proposed feature.*
I am unsure of the best way to go about implementing this, but would be willing to attempt it with some guidance.

**Comment by balazsorban44** [comment]
Hi there!

You could check out the `signIn` callback that allows you to redirect the user to a page, if you deem they should not be logged in.

Docs might be a bit confusing/complicated at the moment, but here is a link:
https://next-auth.js.org/configuration/callbacks#sign-in-callback

Example how to implement it:
```js
// /api/auth/[...nextauth].js
...
callbacks: {
  async signIn(user) {
    if (user.emailVerified) {
      return true
    }
    throw "/email-not-verified"
  }
}
...


Would this help?

**Comment by arxenix** [comment]
Ah, this would definitely help! Must have missed that in the docs, thank you very much.

**Comment by balazsorban44** [comment]
Awesome! Do tell if you did not manage to solve your problem.
