### ISSUE TITLE
Links is not provided for oath providers in v5

### ISSUE THREAD

**Issue by a0m0rajab** [nextauthjs/next-auth#10639]
### What is the improvement or update you wish to see?

I wanted to share the link to identityserver4 with someone from this page: https://authjs.dev/getting-started/authentication/oauth yet when I chose the identityserver4 no link is provided to share, which is a bit painful. it would be great to show links/slugs at the end of the URL to share it. 

### Is there any context that might help us understand?

Nope/ 

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/authentication/oauth

**Comment by a0m0rajab** [comment]
Related code: https://github.com/nextauthjs/next-auth/blob/07e7654ab0b4f6255eaaa5c4c3dbe7e32c0fcd77/docs/pages/getting-started/authentication/oauth.mdx#L2

**Comment by a0m0rajab** [comment]
I would like to work on this though.

**Comment by ndom91** [comment]
@a0m0rajab hey thanks, that makes sense, we had deep linking here at some earlier point actually. If yuo want to take a stab at implementing it again we'd be happy to take a look. 

What we didn't like previously was that the query param was always there then when one navigated away from that page and interfered with other deep linking components on other pages. So maybe if it's just removed before navigating away? :thinking: 

Anyway, I'm going to close this issue, but feel free to open a PR if you want to take a stab at it and we can talk more concretely about it there
