### ISSUE TITLE
Credentials documentation missing exports

### ISSUE THREAD

**Issue by shanecranor** [nextauthjs/next-auth#10643]
### What is the improvement or update you wish to see?

The credentials page is missing exports 

### Is there any context that might help us understand?

For the nextjs example, only handlers and auth are exported. 
`export const { handlers, auth } = NextAuth({`

This means that on the sign in form this will not work
`import { signIn } from "@/auth"`

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/authentication/credentials

**Comment by ndom91** [comment]
Nice catch, thanks! I've updated the code example
