### ISSUE TITLE
Update OAuth , email, and NextAuth.js links

### ISSUE THREAD

**Issue by narcelin** [nextauthjs/next-auth#10640]
### What is the improvement or update you wish to see?

On Chapter 15 of the tutorial under [Adding The Credentials Provider ](https://nextjs.org/learn/dashboard-app/adding-authentication#adding-the-credentials-provider) links in the "Good To Know" paragraph are invalid (Status 404).

Thank you.

### Is there any context that might help us understand?

Link to proper source

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/dashboard-app/adding-authentication#adding-the-credentials-provider

**Comment by mticciati** [comment]
In case this helps:

`https://authjs.dev/getting-started/providers` 

seems to forward to ->

`https://authjs.dev/getting-started/getting-started/authentication/oauth`

**Comment by ndom91** [comment]
Thanks for pointing these out! We can't control the Next.js docs / links of course, but we've added the required redirects :pray:
