### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by TheTwistyTie** [nextauthjs/next-auth#10649]
### What is the improvement or update you wish to see?

The link on [https://next-auth.js.org/configuration/databases](url) labeled "Documentation for adapters" is a broken link to [https://authjs.dev/getting-started/adapters](url)

### Is there any context that might help us understand?

should link to [https://next-auth.js.org/adapters](url)

**Comment by ndom91** [comment]
Thanks for pointing this out, v4 docs need some cleanup with the URL change of the main docs. We'll go through the v4 docs and clean that up :pray:
