### ISSUE TITLE
Broken link to AccessDenied error type

### ISSUE THREAD

**Issue by GetPsyched** [nextauthjs/next-auth#10658]
### What is the improvement or update you wish to see?

Fix the broken link to `AccessDenied` on this page: https://authjs.dev/reference/next-auth#signin

### Is there any context that might help us understand?

NA

**Comment by ndom91** [comment]
Thanks for pointing it out! It'll be released with the next `next-auth` beta release :pray: 

https://github.com/nextauthjs/next-auth/commit/00ded61b3b57e14c4de2ab97de8617d9486e7e35
