### ISSUE TITLE
Documentation for Drizzle Adapter has wrong schema

### ISSUE THREAD

**Issue by matthiasfeist** [nextauthjs/next-auth#10655]
### What is the improvement or update you wish to see?

The Drizzle schema mentioned here https://authjs.dev/getting-started/adapters/drizzle seems to be wrong compared with the default schema for Drizzle Postgres as seen here: https://github.com/nextauthjs/next-auth/blob/07e7654ab0b4f6255eaaa5c4c3dbe7e32c0fcd77/packages/adapter-drizzle/src/lib/pg.ts#L64

The problem is that the schema in the docs does **_not_** have the column `id` and is also missing some indexes.
This leads to JS throwing errors when starting the project as the session id column is not found.

I assume that it's not strictly needed anymore in the DB schema that is shown in the adapter docs page but I assume then the custom schema needs to be passed to the adapter? (something that the docs don't show)

### Is there any context that might help us understand?

I followed the Getting Started Guide to set up AuthJS with NextJS and Drizzle: https://authjs.dev/getting-started/installation?framework=next.js 

Versions:
```
 "@auth/drizzle-adapter": "^1.0.0",
 "next-auth": "^5.0.0-beta.16",
```

I also added my Drizzle schemas as described here: https://authjs.dev/getting-started/adapters/drizzle

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/adapters/drizzle

**Comment by jrhizor** [comment]
I'm running into this too and got `PostgresError: column session.id does not exist` after following the Drizzle / Postgres guide.

**Comment by AntonioErdeljac** [comment]
Same issue for me, downgrading the adapter fixed the issue to work with schema from the docs

**Comment by ndom91** [comment]
Just wanted to post here as well, we're aware and working on shipping a fix. Discussion in Discord atm

- Invite: [discord.authjs.dev](https://discord.authjs.dev/)
- Drizzle Adapter Thread: [discord.com/channels/1200116961590399008/1231534836859146241](https://discord.com/channels/1200116961590399008/1231534836859146241)

**Comment by ndom91** [comment]
I've merged an initial docs fix, so I'm going to close this issue. 

However we're aware theres some more work that needs to be done. I'll update the docs whenever thats merged. Again, if anyone comes across this, check out the discord if you're curious or want to help out :pray:
