### ISSUE TITLE
customizing a built-in OAuth provider link dose not work

### ISSUE THREAD

**Issue by RAHUL1115** [nextauthjs/next-auth#10652]
### What is the improvement or update you wish to see?

in the package JSDOC documenation customizing a built-in OAuth provider wich redirect to here "https://authjs.dev/guides/providers/custom-provider#override-default-options" and the link dose not seem to be there or it maybe moved

### Is there any context that might help us understand?

import auth0Provider from '@auth/sveltekit/providers/auth0';

when i hovaer over this auth0Provder it give some documantion link in the example section that dose not wokring

**Comment by ndom91** [comment]
Thanks for pointing this out! The correct link is [here](https://authjs.dev/guides/configuring-oauth-providers). I'll update the Auth0 Provider link
