### ISSUE TITLE
Postmark provider import is not working

### ISSUE THREAD

**Issue by googamanga** [nextauthjs/next-auth#10665]
### What is the improvement or update you wish to see?

import Postmark from "next-auth/providers/postmark";

This returns an error

### Is there any context that might help us understand?

import Postmark from "next-auth/providers/postmark";

This returns an error

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/authentication/email#setup-provider-2

**Comment by blackge** [comment]
I'm seeing the same issue with SendGrid.

**Comment by ndom91** [comment]
Postmark and Sendgrid aren't released in `next-auth` yet, it was only merged to `main`. Sorry about that - we've added a note in the docs. It'll be out in the latest `next-auth` beta release.

**Comment by ndom91** [comment]
Sendgrid and Resend are available in `next-auth@5.0.0-beta.16`, for example, though.

If you need somethign else, we have a "setup your own http email provider" guide available now though that might help - https://authjs.dev/guides/configuring-http-email
