### ISSUE TITLE
Broken link pointing to https://authjs.dev/reference/nextjs#auth in https://authjs.dev/getting-started/migrating-to-v5#details

### ISSUE THREAD

**Issue by adriancuadrado** [nextauthjs/next-auth#10674]
### What is the improvement or update you wish to see?

https://authjs.dev/getting-started/migrating-to-v5#details
![image](https://github.com/nextauthjs/next-auth/assets/29214635/315cccef-4fa9-45d4-99c3-46212c3d78bb)

### Is there any context that might help us understand?

![image](https://github.com/nextauthjs/next-auth/assets/29214635/7ceed0ac-5124-455f-beb4-3f7b364b4004)

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/migrating-to-v5#details

**Comment by ndom91** [comment]
Thanks for pointing this out! Fixed :pray:
