### ISSUE TITLE
Allow manipulation of provider response 

### ISSUE THREAD

**Issue by jackHedaya** [nextauthjs/next-auth#1067]
**Summary of proposed feature**
I believe it would be useful for there to be a callback for right after the Provider API is hit. 

**Purpose of proposed feature**
This is helpful because some OAuth Providers will send back tokens in different formats such as `refresh_token` instead of `refreshToken`.

**Detail about proposed feature**
There would be a `res` callback.

**Potential problems**
None that I could tell. 

**Describe any alternatives you've considered**
N/A

*Please indicate if you are willing and able to help implement the proposed feature.*
Yes

**Comment by balazsorban44** [comment]
Hi there, do you have a special case where this has been a problem?

As far as I can tell, the [OAuth spec](https://tools.ietf.org/html/draft-ietf-oauth-v2-07#section-5.1.5) says it has to be in the form at `refresh_token`, and as you see here:
https://github.com/nextauthjs/next-auth/blob/fb8ec8a46962f4349ab5ab7a211ecdd9e3d7c7c5/src/server/lib/oauth/client.js#L167

we do expect it to be `refresh_token`.


If there is an OAuth provider that for some reason returns a `refreshToken`, we could add an extra if statement for that particular provider, but to keep the user-facing API simple (#1022 ), I wish not to expose a new options if your case is an isolated one. You could rather add a new provider to the [list of supported providers](https://next-auth.js.org/configuration/providers), and we can handle a special case internally, using the `provider.id`

**Comment by jackHedaya** [comment]
That's my bad then, I'm not sure why my custom provider isn't working. I opened a new discussion issue if you wouldn't mind checking it out.
