### ISSUE TITLE
missing ethereum signin docs

### ISSUE THREAD

**Issue by tohodakilla** [nextauthjs/next-auth#10679]
### What is the improvement or update you wish to see?

i wish to see missing documentation about ethereum signin

### Is there any context that might help us understand?

https://authjs.dev/reference/core/providers/credentials#see
here is the broken link

### Does the docs page already exist? Please link to it.

https://authjs.dev/guides/providers/credentials#example---web3--signin-with-ethereum

**Comment by ndom91** [comment]
@tohodakilla If you'd like to write a guide, we can definitely link to it :pray:

**Comment by ndom91** [comment]
Ah I think I misunderstood. Where did yuo find that second (broken) link?

**Comment by ndom91** [comment]
Okay I found the link and the original content. This is what it linked to:

---


The credentials provider can also be used to integrate with a service like [Sign-in With Ethereum](https://login.xyz).

For more information, check out the links below:

- [Tutorial](https://docs.login.xyz/integrations/Auth.js)
- [Example App Repo](https://github.com/spruceid/siwe-next-auth-example)
- [Example App Demo](https://siwe-next-auth-example2.vercel.app/)
