### ISSUE TITLE
Collect profile info in passwordless email signIn() flow

### ISSUE THREAD

**Issue by lawrencecchen** [nextauthjs/next-auth#1069]
**Summary of proposed feature**
I want to collect a new user's full name using: `signIn("email", { email })`

**Purpose of proposed feature**
I encountered this use case.

**Detail about proposed feature**
A createProfile option:
`signIn("email", { email: "lawrence@example.com", createProfile: { name: "Lawrence" } })`
If createProfile exists, name will be persisted to the database. If omitted, standard behavior occurs.

**Potential problems**
Couldn't think of any.

**Describe any alternatives you've considered**
Collecting username after authenticated, but this is inconvenient.

**Additional Context**
Would probably involve changing the `{ email }` placeholder in [line 159 of src/server/routes/callback.js](https://github.com/nextauthjs/next-auth/blob/canary/src/server/routes/callback.js#L159) if createProfile exists.

*Please indicate if you are willing and able to help implement the proposed feature.*
Yes! (But I'm new to this so might need guidance later on...)

**Comment by balazsorban44** [comment]
Could you please elaborate a bit more on your use case?

**Comment by lawrencecchen** [comment]
If the user is new, I would like to collect and persist their name somewhere in the authentication flow. For example, if you create a new account on Medium, the email verification link redirects you to a page that asks for your name. While this can be implemented in the client side by checking if the "name" key exists on the session.user object and then prompting the user for their name to persist to the database, I think this is a common use case for passwordless auth that can be solved with a `signUp()` method or changing the `signIn()` method's behavior if a new user is indicated.

This is my sign up screen that collects name as well as email. I have a separate sign in screen that calls `signIn()` with only the email.
<img width="537" alt="Screen Shot 2021-01-10 at 2 48 25 PM" src="https://user-images.githubusercontent.com/54008264/104137593-e5a2af80-5352-11eb-894f-aa992c76c08d.png">

Sorry if this use case is already possible. If so, this might be better suited in discussions. Thanks for your help!

**Comment by MousaZeidBaker** [comment]
If you have some metadata that is only available in the signIn callback, how do you include that in the JWT? The signIn documentation says:

> @return {boolean}         Return `true` (or a modified JWT) to allow sign in

So how do I modify the JWT and make sure the `profile.sub` is available in the JWT?

```javascript
callbacks: {
  /**
   * @param  {object} user     User object
   * @param  {object} account  Provider account
   * @param  {object} profile  Provider profile 
   * @return {boolean}         Return `true` (or a modified JWT) to allow sign in
   *                           Return `false` to deny access
   */
  signIn: async (user, account, profile) => {
    profile.sub // This metadata is only available in signIn callback (AWS cognito)

    return Promise.resolve(true)
  }
}
```

**Comment by topheeee** [comment]
There also doesn't appear to be any way to access the db within callback handlers. Would be nice to have an extra context parameter that exposes the underlying adapter.

**Comment by merelinguist** [comment]
Not stale.

**Comment by madhums** [comment]
Yea this would be great! If there is some way to specify `name` in the `signin()` method.

**Comment by bduff9** [comment]
Yes, agreed. I mentioned this in my issue over here as well: #1825 

Would love to see this!

**Comment by balazsorban44** [comment]
Coming back to this, I might have an idea.

before an email is sent, we save a token in the database for the user to be created. there, we could probably add the extra info temporarily, and after they have clicked on the link in their email, the user/account would be created.

We cannot create the user BEFORE they clicked the link, as it wouldn't be secure in my opinion.

This can be a followup of #2361 after it is merged. Not sure we will be able to squeeze this into v4, maybe it will be a subsequent feature release, but I think I now have the proper understanding for doing this.

**Comment by shivamragnar** [comment]
Hi @balazsorban44, do we have any updates on this ? 
I have a similar use case where we need it with other social login flow as well. We need to pass additional metadata as 
`signIn('google', {metadata:  {isReferral: true, referrer: 'ragnarLothbrok'}})` 
and save this info with the user profile created in our DB on successful login. Do you have any idea if this is possible right now?

**Comment by sergeyshaykhullin** [comment]
Does someone can reopen this issue?

**Comment by chrisb2244** [comment]
I'm also trying to implement something very similar to this:

> This is my sign up screen that collects name as well as email. I have a separate sign in screen that calls `signIn()` with only the email. <img alt="Screen Shot 2021-01-10 at 2 48 25 PM" width="537" src="https://user-images.githubusercontent.com/54008264/104137593-e5a2af80-5352-11eb-894f-aa992c76c08d.png">

I can't quite work out how or if this is possible using NextAuth - should this be the current approach?


> Coming back to this, I might have an idea.
> 
> before an email is sent, we save a token in the database for the user to be created. there, we could probably add the extra info temporarily, and after they have clicked on the link in their email, the user/account would be created.
> 
> We cannot create the user BEFORE they clicked the link, as it wouldn't be secure in my opinion.
> 
> This can be a followup of #2361 after it is merged. Not sure we will be able to squeeze this into v4, maybe it will be a subsequent feature release, but I think I now have the proper understanding for doing this.

It looks like #2361 was merged already - does it help with this issue?

**Comment by chrisb2244** [comment]
> Coming back to this, I might have an idea.
> 
> before an email is sent, we save a token in the database for the user to be created. there, we could probably add the extra info temporarily, and after they have clicked on the link in their email, the user/account would be created.
> 
> We cannot create the user BEFORE they clicked the link, as it wouldn't be secure in my opinion.
> 
> This can be a followup of #2361 after it is merged. Not sure we will be able to squeeze this into v4, maybe it will be a subsequent feature release, but I think I now have the proper understanding for doing this.

How would I link this to the user?
I can store data during the signIn callback, but at that time I don't have access to the verificationToken. Without the token, I don't know how to retrieve the stored values after the email is verified (because presumably I want to tie the 'speculative' user to the verification token, not to the providerId (i.e. email). Otherwise, I as another user can register for your email address, and fail to verify, but when you actually create data, the database will return two sets of data for your email address, one provided by me as an attacker? (or I've completely misunderstood... in which case, I'd love to be corrected)

**Comment by daniellin215** [comment]
This would be a good feature to add, any update on this?

**Comment by madhums** [comment]
Can we reopen this? Is there a proposed alternative/solution on how to go about this?

**Comment by LOGOLFGODORD** [comment]
Ya fix it !! I’ll been done shortly

**Comment by LOGOLFGODORD** [comment]
Creat don't take !! I'll do it For you . Are you planning on using it for the better good ? I've been seeing a lot of mixed emotions on how this platform works from the young bucks out here .Prove yourself. I'll teach you .

**Comment by unsphere** [comment]
> Hi @balazsorban44, do we have any updates on this ? I have a similar use case where we need it with other social login flow as well. We need to pass additional metadata as `signIn('google', {metadata: {isReferral: true, referrer: 'ragnarLothbrok'}})` and save this info with the user profile created in our DB on successful login. Do you have any idea if this is possible right now?

I also need to store a referrer on first login for the affiliate system in my app. So I thought about using cookies-next storing ref query parameter from url in a cookie if exists. And then get the cookie in createUser event, but this does not work, because I have no context. Any update on this?
