### ISSUE TITLE
no adapter is working with nextjs

### ISSUE THREAD

**Issue by Sparkenstein** [nextauthjs/next-auth#10697]
### Environment

```
 System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 7800X3D 8-Core Processor
    Memory: 13.86 GB / 31.15 GB
  Binaries:
    Node: 20.11.1 - ~\AppData\Local\fnm_multishells\144804_1713873935982\node.EXE
    Yarn: 4.1.1 - ~\AppData\Local\fnm_multishells\144804_1713873935982\yarn.CMD
    npm: 10.5.0 - ~\AppData\Local\fnm_multishells\144804_1713873935982\npm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
  npmPackages:
    @auth/mongodb-adapter: ^3.0.0 => 3.0.0
    @auth/pg-adapter: ^1.0.0 => 1.0.0
    @auth/typeorm-adapter: ^2.0.0 => 2.0.0
    next: 14.1.3 => 14.1.3
    next-auth: ^5.0.0-beta.16 => 5.0.0-beta.16
    react: 18.2.0 => 18.2.0
```

### Reproduction URL

https://github.com/Sparkenstein/authjs-bug

### Describe the issue

previously closed issue describes the errors well, but in short with current nextjs version I could not make any adapter work. 

Check https://github.com/nextauthjs/next-auth/issues/10695

### How to reproduce

Checkout above repo, there's also a patch https://github.com/Sparkenstein/authjs-bug/blob/master/change.patch  to see the difference between official next-auth-example. 

### Expected behavior

It should not crash

**Comment by balazsorban44** [comment]
This is not an Auth.js-specific issue. See: https://authjs.dev/getting-started/migrating-to-v5#edge-compatibility

**Comment by Sparkenstein** [comment]
The way given in that guide doesn't work as well, would be helpful if we don't close issues for beta libraries without a proper discussion.
