### ISSUE TITLE
Show oauth user info in pages

### ISSUE THREAD

**Issue by marmundo** [nextauthjs/next-auth#10702]
### What is the improvement or update you wish to see?

Using a custom oauth provider, the auth() only shows 4 user fields. I'd like to see all information present in User interface like [GitHubProfile](https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/providers/github.ts)

### Is there any context that might help us understand?

Unfortunately only name,email and image is possible. It's good to show a way to store more info on session.

**Comment by anampartho** [comment]
Please add a code example. @marmundo

**Comment by ndom91** [comment]
We have a guide on "Extending the session" which shows how this can be done with both `jwt` and `database` session strategies.

https://authjs.dev/guides/extending-the-session

Basically, in the `jwt` callback, the `token` argument should be the entire contents of the `GitHubProfile` you're referring to. You can decide which fields to put ont he jwt and then which fields to pass onto the frotnend via the `session` callback. Hope that helps!

**Comment by ndom91** [comment]
I've added a link to that guide in the "Session Management" page, "Get Session": https://github.com/nextauthjs/next-auth/commit/954d9a227aa92839bab90413b31279104bfab2bd

**Comment by marmundo** [comment]
Thanks for your addition. 

Just a thought, if I want to inform for example user role or other informations, I'll make token.role=user.role or in a abstract way token.user_property=user.property? Is it a a counter intuitive way to do? You pollute token object with non-related token information.  Does just to get these information inside session function? Or am I having a wrong idea about these feature described in next.js doc?

I don't know if is it a real concern but for me is a non-optimal semantic way to do.

**Comment by ndom91** [comment]
> Thanks for your addition. 
> 
> Just a thought, if I want to inform for example user role or other informations, I'll make token.role=user.role or in a abstract way token.user_property=user.property? Is it a a counter intuitive way to do? You pollute token object with non-related token information.  Does just to get these information inside session function? Or am I having a wrong idea about these feature described in next.js doc?
> 
> I don't know if is it a real concern but for me is a non-optimal semantic way to do.

No this makes sense 👌 

You can also check out our guide on RBAC, for example, it recommends the same thing. 

https://authjs.dev/guides/role-based-access-control
