### ISSUE TITLE
Incorrect Drizzle Schema

### ISSUE THREAD

**Issue by Lodimup** [nextauthjs/next-auth#10710]
### What is the improvement or update you wish to see?

Incorrect Drizzle Schema present in the doc. 
The following set of code is incorrect and is different from '@auth/drizzle-adapter'
```
import {
  timestamp,
  pgTable,
  text,
  primaryKey,
  integer,
} from "drizzle-orm/pg-core"
import type { AdapterAccount } from "next-auth/adapters"
import { randomUUID } from "crypto"
 
export const users = pgTable("user", {
  id: text("id").primaryKey().$defaultFn(() => randomUUID()),
  name: text("name"),
  email: text("email").notNull().unique(),
  emailVerified: timestamp("emailVerified", { mode: "date" }),
  image: text("image"),
})

... and more

```

### Is there any context that might help us understand?

mirror @auth/drizzle-adapter 

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/adapters/drizzle

**Comment by Lodimup** [comment]
![Screenshot 2024-04-24 at 20 25 24](https://github.com/nextauthjs/next-auth/assets/17614655/6ff7739d-5f2a-49cb-af2b-9588caed380c)

additional errors

**Comment by ndom91** [comment]
Thanks for pointing this out, the drizzle adapter has had a good bti of changes the last few days.

The [docs](https://authjs.dev/getting-started/adapters/drizzle) shuold now be up to date with `@auth/drizzle-adapter@1.0.1` :pray:
