### ISSUE TITLE
Missing Link on PG documentation for schema

### ISSUE THREAD

**Issue by Mahdi-s** [nextauthjs/next-auth#10738]
### What is the improvement or update you wish to see?

Update schema description link to a valid page 
(https://authjs.dev/docs/database)

### Is there any context that might help us understand?

On the page related to PG schema the following link leads to page not found. 
The source page: https://authjs.dev/getting-started/adapters/pg
The line:
The SQL schema for the tables used by this adapter is as follows. Learn more about the models at our doc page on [Database Models](https://authjs.dev/docs/database).

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/adapters/pg

**Comment by ndom91** [comment]
Thanks for pointing it out, we've fixed the link :+1:
