### ISSUE TITLE
Fix Github stars icon

### ISSUE THREAD

**Issue by amanr-dev** [nextauthjs/next-auth#10746]
### What is the improvement or update you wish to see?

Github stars numbers is not appering correctly.

## screenshot
![Screenshot 2024-04-27 205547](https://github.com/nextauthjs/next-auth/assets/124811276/d1374bd6-c963-4e10-86ce-574b27a1b171)

### Is there any context that might help us understand?

no

**Comment by ndom91** [comment]
Thanks for pointing it out, it's fixed :pray:
