### ISSUE TITLE
Calls to /sessions when you get back to the tab

### ISSUE THREAD

**Issue by lnikell** [nextauthjs/next-auth#1074]
**Describe the bug**
Using `"next-auth": "^3.1.0"` I have a weird behaviour, so everytime I click to Chrome Inspector or switch from one tab to another it does an extra call to `/sessions`. The same behavior I see on Next Auth demo page.

**Screenshots or error logs**

https://user-images.githubusercontent.com/2697570/104128614-fcec9780-5368-11eb-8f9b-d142d45bfe21.mov

Is it expected behavior?

**Comment by balazsorban44** [comment]
Hi,

it is indeed an expected behavior. This is so that the session will be synced between tabs, and always up to date.


Relevant code:
https://github.com/nextauthjs/next-auth/blob/78fd783bac990d8f2109487ac6598a38e3173f40/src/client/index.js#L71-72

**Comment by lnikell** [comment]
Thank you @balazsorban44. Would you like to consider moving to a more modern solution for this ?https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API
That will improve the dev experience because we won't have a lot of spam calls in the console network tab when you debug a completely different thing. Also, it will improve performance because we won't rerender components when it is not necessary.

**Comment by balazsorban44** [comment]
Interesting! Browser support is looking good as well!

Would you be interested in implementing this? (In that case, could you open a feature request issue referencing this, and explaining the reason you would like this change :slightly_smiling_face:  )

cc @iaincollins

**Comment by lnikell** [comment]
@balazsorban44 yes, I can handle it.
