### ISSUE TITLE
Middleware Route Protection nextjs example result in Middleware relative urls error

### ISSUE THREAD

**Issue by Ucok23** [nextauthjs/next-auth#10760]
### What is the improvement or update you wish to see?

The next-auth docs about protecting route in getting started section resulting middleware relative urls error

```
import { auth } from "./auth"

export default auth((req) => {
  if (!req.auth) {
    return NextResponse.redirect("/login")
  }
})
```
![Screenshot_20240429_145119_DWService](https://github.com/nextauthjs/next-auth/assets/42701951/16753584-e4f5-404a-882b-b639cb6c8456)

### Is there any context that might help us understand?

```NextResponse.redirect(url)```
url should be absolute url i think

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/session-management/protecting

**Comment by balazsorban44** [comment]
Fix in the docs: https://authjs.dev/getting-started/session-management/protecting#nextjs-middleware

In short, you can replace the current URLs pathname.
