### ISSUE TITLE
`callbackUrl` is ignored (redirects to baseUrl)

### ISSUE THREAD

**Issue by FjolleJagt** [nextauthjs/next-auth#1077]
**Describe the bug**
NextAuth.js no longer uses `callbackUrl` when logging in (at least when using "credentials", but I believe in general).

**Steps to reproduce**
Use `signIn("credentials", {callbackUrl: 'http://localhost:3000/mycallbackurl'})` to navigate to the signin page with a callback url. Sign in.

(I don't have a minimal code example, but I have precise code pointers below, which are hopefully enough. If need be I can also create a code example.)

**Expected behavior**
I expected to be redirected to `http://localhost:3000/mycallbackurl` but instead end up at `http://localhost:3000/`.

**Additional context**

The problem appears to be in [this recent change](https://github.com/nextauthjs/next-auth/commit/f2ad69358fb6e650035c85d320440468d0286377#diff-846e308afe343fa0238d38943beed033bec2ab41582b904029a4ef0106d634a1R223).

Previously `options.callbackUrl` was set, which was then passed in to `callback.js` and unpacked [on this line](https://github.com/nextauthjs/next-auth/blob/fb8ec8a46962f4349ab5ab7a211ecdd9e3d7c7c5/src/server/routes/callback.js#L17). However, the above change just sets `callbackUrl` as a variable and expects `callback.js` to unpack `req.options`. This means that `callbackUrl` is always undefined in `callback.js`.

**Comment by FjolleJagt** [comment]
A "quick fix" would be to manually set `req.options.callbackUrl = callbackUrl` in `server/index.js`, but I don't know how you feel about this. If you're okay with that suggestion, then I can create a PR to fix this.

**Comment by balazsorban44** [comment]
It looks like tests are not running right now, and I believe only @iaincollins knows the real reason.
Until tests are in place again, feedback like this is very welcome! Indeed, I did a mistake while refactoring, thanks for noticing!

It should be fixed again: https://github.com/nextauthjs/next-auth/blob/173df76c0f34a69c29ad215dd259573ad6a7c96d/src/server/lib/callback-url-handler.js#L32


Please try `next-auth@3.2.0-canary.18` and report back if the issue is solved!

**Comment by FjolleJagt** [comment]
Thanks for the quick response! In `canary.18`, the clientside code isn't populating the form element that sets the CSRF token, so I get redirected back to the signin page by [server/index.js](https://github.com/nextauthjs/next-auth/blob/173df76c0f34a69c29ad215dd259573ad6a7c96d/src/server/index.js#L195). The generated HTML is `<input type="hidden" name="csrfToken">`. In `canary.17` the value was populated correctly.

I haven't had time to dig in to see why this is happening, though, so it's possible it's a mistake on my side this time.

**Comment by balazsorban44** [comment]
My bad again, sorry!

This commit https://github.com/nextauthjs/next-auth/commit/e504044489060a5f7f5e8ae1802ee07b2aae2547
will hopefully fix this, and is available at `canary.19`


(It's scary to do big refactorings, especially when tests won't run, that's why it's good to have a canary channel 🤗)

**Comment by FjolleJagt** [comment]
I tested on next-auth@3.2.0-canary.20 and all seemed to work fine. Thanks again for the quick responses and all the work you're doing on next-auth, it seems a great package!
