### ISSUE TITLE
Missing: https://authjs.dev/guides/providers/credentials

### ISSUE THREAD

**Issue by mzamarripa-irys** [nextauthjs/next-auth#10776]
### What is the improvement or update you wish to see?

Have reference if v5 changes the way to implement the credentials provider

### Is there any context that might help us understand?

None

### Does the docs page already exist? Please link to it.

https://authjs.dev/guides/providers/credentials

**Comment by ndom91** [comment]
v5 doesn't change anything about implementing the credentials provider.

You can find more info about it here: https://authjs.dev/getting-started/providers/credentials
