### ISSUE TITLE
Add tutorial on passing access token to session (good first issue)

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#1078]
**Summary of proposed feature**
A large number of issues are created that asks how to pass `access_token` to the session.

**Purpose of proposed feature**
Currently, we point the users to the `jwt` and `session` [callbacks documentation](https://next-auth.js.org/configuration/callbacks), but since it's such a highly requested thing, we might just want to create a specific tutorial under https://next-auth.js.org/tutorials that explains this in details. 

**Detail about proposed feature**
We could either add it directly to the tutorials as a standalone page, or add la link to an external post, preferably with code examples, maybe a working demo app as well, that is live on an accessible url.

**Describe any alternatives you've considered**
Docs are clearly not good enough, as we are still asked quite a lot.

*Please indicate if you are willing and able to help implement the proposed feature.*

This is up for grab, marked as a good first issue.

**Comment by jackHedaya** [comment]
I'd be happy to tackle this issue once I figure out the solution in #1068 :)
