### ISSUE TITLE
Documentation on Custom Providers

### ISSUE THREAD

**Issue by ebratz** [nextauthjs/next-auth#10799]
### What is the improvement or update you wish to see?

Would be great to have a good documentation explainin on how to create a custom authentication provider, as we had on previous versions

### Is there any context that might help us understand?

On previous versions, we had the possibility to extend the providers creating custom providers. One example would be to have an Email Provider supporting Amazon SES as email service.

**Comment by ndom91** [comment]
Yeah that makes sense. We have the following general "extend the providers" / "use your own provider" guide: https://authjs.dev/guides/configuring-oauth-providers#use-your-own-provider

And for email specifically: https://authjs.dev/guides/configuring-http-email

Do those cover what you're looking for?

**Comment by ebratz** [comment]
That could help for advanced users, but the documentations should be more user friendly for intermediate users as well. The type definitions are not clear on the examples, you need to dig into the core code to understand how other providers were implemented. I feel lost going back and forth trying to implement something custom.

**Comment by ndom91** [comment]
Yeah I can definitely appreciate that. What would you recommend for making those two examples I provided above, for example, more beginner / intermediate friendly?

**Comment by ndom91** [comment]
Going to close this issue, feel free to open a PR with any improvements you may see and we can talk about it more there :pray:
