### ISSUE TITLE
Auth.js Pages Documentation Page link is broken - Shows 404

### ISSUE THREAD

**Issue by nihalmohammed18** [nextauthjs/next-auth#10801]
### What is the improvement or update you wish to see?

404 page not found error for `https://authjs.dev/guides/basics/pages`

### Is there any context that might help us understand?

The Auth.js pages documentation link is broken - `https://authjs.dev/guides/basics/pages`

### Does the docs page already exist? Please link to it.

https://authjs.dev/guides/basics/pages

**Comment by balazsorban44** [comment]
Hi, where do you see this link?

**Comment by nihalmohammed18** [comment]
Hi, it was through a Google Search. Realised it later that the docs might have been updated and it's taking time for Search Engines to pick it up properly. Really sorry for the false alarm. You can close this I guess.

**Comment by ndom91** [comment]
Thanks for pointing it out! We'll take a look at the google search console :pray:
