### ISSUE TITLE
URL Redirection Error on Authentication Failure (Middleware file)

### ISSUE THREAD

**Issue by mdfaizanahmed786** [nextauthjs/next-auth#10824]
### Describe the issue

Page URL: https://authjs.dev/getting-started/session-management/protecting#nextjs-middleware

```js
import { auth } from "app/auth";

export default auth((req) => {
if (!req. auth) {
const url = req.url.replace(req.nextUrl.pathname, "/login")
return Response.redirect(url)
}
});

```

This redirects to the incorrect URL path if no session: http://login/localhost:3000/

### Approach to Fix

Can use a similar standard approach

```js
import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

// This function can be marked async if using await inside
export function middleware(request: NextRequest) {
return NextResponse.redirect(new URL('/home', request.url))
}

```

### Expected behavior

It should redirect to http://localhost:3000/login

**Comment by sfsajid91** [comment]
This issue is found after upgrading Next.js to 14.2.

The current solution is to downgrade Next.js for now

**Comment by mdfaizanahmed786** [comment]
@sfsajid91 so, let this issue be opened?

**Comment by sfsajid91** [comment]
Let the issue be opened till the fix

**Comment by oyal** [comment]
I tried to do this, but got stuck in infinite redirection:

```ts
import { auth } from '@/auth'

export default auth((req) => {
  if (!req.auth) {
    const url = new URL('/auth/sign-in', req.nextUrl.origin)
    return Response.redirect(url)
  }
})

export const config = {
  matcher: ['/((?!api|_next/static|_next/image|favicon.ico).*)'],
}
```

![image](https://github.com/nextauthjs/next-auth/assets/88022434/d6452344-6783-4787-b2ad-c8458647dbe2)

**Comment by ThangHuuVu** [comment]
@oyal to avoid infinite redirection, you'll need to exclude /login from the middleware 
```ts

export const config = {
  matcher: ['/((?!/auth/sign-in|api|_next/static|_next/image|favicon.ico).*)'],
}
```

**Comment by ThangHuuVu** [comment]
@mdfaizanahmed786 seems like a documentation issue to me. The example code is wrong
```js
    // input: 'http://localhost:3000/', output: 'http:/auth/signin/localhost:3000/' 
    const url = req.url.replace(req.nextUrl.pathname, "/auth/signin")
```
It should use the syntax `new URL()` like your "Approach to fix" section instead. And it isn't related to next version.

**Comment by ThangHuuVu** [comment]
Closing as duplicated, as it was fixed in https://github.com/nextauthjs/next-auth/issues/10815
