### ISSUE TITLE
Route "[...nextauth]/route.ts" does not match the required types of a Next.js Route. Invalid configuration "GET":

### ISSUE THREAD

**Issue by avi312singh** [nextauthjs/next-auth#10845]
### Environment

```
  System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 239.02 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - ~/.nvm/versions/node/v21.5.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.5.0/bin/npm
  Browsers:
    Chrome: 124.0.6367.119
    Safari: 17.4.1
  npmPackages:
    next: ^14.2.3 => 14.2.3 
    next-auth: ^5.0.0-beta.17 => 5.0.0-beta.17 
    react: 18.3.1 => 18.3.1 
```

### Reproduction URL

https://github.com/avi312NHS/next-auth-issue

### Describe the issue

After migrating to next-auth v5 I am getting a build error with my current route.ts configuration

![image](https://github.com/nextauthjs/next-auth/assets/5769090/a36b4d1b-959a-4289-a42b-d6863f63e5ce)

### How to reproduce

As per reproduction repo cloned from - https://github.com/nextauthjs/next-auth-example, export auth configuration options to another directory and try to `npm run build`

**app/api/auth/[...nextauth]/route.ts**
```
import NextAuth from 'next-auth';
import { authOptions } from '../../../../config/authOptions';

const handler = NextAuth(authOptions);

export { handler as GET, handler as POST };

```

**config/authOptions.ts**
```
import { NextAuthConfig } from 'next-auth';
import CredentialsProvider from 'next-auth/providers/credentials';

let users: any[] = [];

export const authOptions: NextAuthConfig = {
  providers: [
    CredentialsProvider({
      name: 'Credentials',
      credentials: {
        email: { label: 'Email', type: 'text', placeholder: 'Enter Email' },
        password: { label: 'Password', type: 'password' },
      },
      async authorize(credentials, req) {
        if (!credentials || !credentials.email || !credentials.password) {
          return null;
        }
        const user = users.find((item) => item.email === credentials.email);
        if (user?.password === credentials.password) {
          const modifiedUser = {
            ...user,
            accountStatus: 'Active',
          };

          return modifiedUser;
        }
        return null;
      },
    }),
  ],
  pages: {
    signIn: '/signin',
    error: '/autherror',
  },
};
```

### Expected behavior

No TS build failures after migrating from V4 to v5, I cannot see any docs related to the changing of the route exporting format -> [Next auth docs](https://next-auth.js.org/configuration/initialization#route-handlers-app)
This code was fully functional with:
```
"next": "^13.5.6",
"next-auth": "^4.24.5"
```

### Other unanswered issues with same error

[https://stackoverflow.com/questions/78214384/type-error-route-app-api-auth-nextauth-route-ts-does-not-match-the-requi](https://stackoverflow.com/questions/78214384/type-error-route-app-api-auth-nextauth-route-ts-does-not-match-the-requi)
[https://stackoverflow.com/questions/77637651/authoptions-is-not-a-valid-route-export-field](https://stackoverflow.com/questions/77637651/authoptions-is-not-a-valid-route-export-field)

**Comment by mattixpet** [comment]
Using that last stackoverflow link actually solved the error for me in my app.

**Comment by avi312singh** [comment]
Yes likewise

**Comment by Minttsaka** [comment]
correct

**Comment by freidev** [comment]
To fix the issue, simply remove the `export `keyword from the line `export const authOptions`. The code should look like this: `const authOptions`.

**Comment by davidchang** [comment]
Worth noting that the docs show code exporting `authOptions` like this in https://next-auth.js.org/configuration/nextjs#getserversession , that's how i ran into this issue

<img width="914" alt="image" src="https://github.com/user-attachments/assets/f6307dd2-3d6f-4dbd-8761-6b1ca2b3a061">

**Comment by chrisidakwo** [comment]
Either of these fixes the error:

```ts
import NextAuth from 'next-auth';

import { authOptions } from '@/lib/auth';

const { handlers: { GET, POST } } = NextAuth(authOptions);

export { GET, POST };
```

OR

```ts
import NextAuth from 'next-auth';

import { authOptions } from '@/lib/auth';

const handlers = NextAuth(authOptions);

export const GET = handlers.handlers.GET;
export const POST = handlers.handlers.POST;
```

**Comment by stellaoliveirabertt** [comment]
### ✅ Definitive Solution for Next.js 15 with `next-auth@5`

If you're getting this build error:

```bash
Type error: Route "src/app/api/auth/[...nextauth]/route.js" does not match the required types of a Next.js Route.
"authOptions" is not a valid Route export field.
```

⚠️ It means that **Next.js 15 no longer allows exporting helper objects (like `authOptions`) directly from route files** such as `app/api/**/route.js` or `.ts`.

---

#### ✅ How to fix it properly:

---

### 1. Create a separate file for your `authOptions`

**Suggested path:** `src/app/lib/auth.js`

```js
// src/app/lib/auth.js
import AzureADProvider from "next-auth/providers/azure-ad";

const authOptions = {
  providers: [
    AzureADProvider({
      clientId: process.env.AZURE_AD_CLIENT_ID,
      clientSecret: process.env.AZURE_AD_CLIENT_SECRET,
      tenantId: process.env.AZURE_AD_TENANT_ID,
    }),
  ],
  pages: {
    signIn: "/dashboard/login",
  },
  callbacks: {
    async session({ session, token }) {
      session.user.id = token.sub;
      return session;
    },
  },
};

export default authOptions;
```

---

### 2. Then fix your `[...nextauth]/route.js` (or `.ts`) like this:

```js
import NextAuth from "next-auth";
import authOptions from "@/app/lib/auth";

const handler = NextAuth(authOptions);

export const GET = handler;
export const POST = handler;
```

---

### ✅ Now run:

```bash
npm run build
```

Your app should now build successfully on **Next.js 15 + `next-auth` v5**.
