### ISSUE TITLE
How to ignore / edit provider response format

### ISSUE THREAD

**Issue by Nik-Novak** [nextauthjs/next-auth#10856]
### Environment

```
next: ^14.2.3 => 14.2.3 
    next-auth: ^5.0.0-beta.17 => 5.0.0-beta.17 
    react: ^18.3.1 => 18.3.1
```

### Reproduction URL

https://github.com/Nik-Novak/Mind-Knight

### Describe the issue

In AuthJs V4, we could create custom Providers like this one: https://pastebin.com/rDH6GZ1a

In V5, the same methods which allowed for generic response formats don't work.

### How to reproduce

Take certain providers and try to migrate them to V5

### Expected behavior

.

**Comment by balazsorban44** [comment]
As we are doubling down on stricter spec compliance, the overly permissive `request` methods have been dropped/replaced with `conform`, which is a hidden api reserved for official providers.

We want providers to stay on the happy path by discouraging deviating from the specification.
