### ISSUE TITLE
Improve contributing instructions on using tests

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#1086]
As per @iaincollins's request https://github.com/nextauthjs/next-auth/pull/1085#issuecomment-757903043

We should better document the tests, and why/how are they useful.

**Comment by iaincollins** [comment]
Thanks for the reminder!

**Comment by balazsorban44** [comment]
Closing this as the there is lack of activity on this matter. Once we have a better strategy for testing we can join forces and create sufficient documentation around it together.
