### ISSUE TITLE
Add missing error explanations to docs

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#1089]
Currently, the [Errors documentation page](https://next-auth.js.org/errors) has missing/empty sections all over.

We should document when these errors occur and describe how to resolve them, if possible.

**Comment by balazsorban44** [comment]
@lluia @ndom91 for starters, I think we could add these pages in the navbar in the docs for discoverability:

https://next-auth.js.org/errors

https://next-auth.js.org/warnings

Currently, I think they are only reachable if an error/warning is shown in your terminal.

**Comment by ndom91** [comment]
Yeah exaclty, they are not discoverable in the page / search.

**Comment by ndom91** [comment]
Closing this issue - missing errors / warnings were described (in `next` docs - https://next-auth-git-next-nextauthjs.vercel.app/errors) and the pages are also now in the sidebar / findable in search :tada:
