### ISSUE TITLE
 Exporting auth as middleware doesn't work

### ISSUE THREAD

**Issue by ShahriarKh** [nextauthjs/next-auth#10912]
### Environment

```
OS: Windows 10 10.0.19045
Node: 20.12.2
bun: 1.1.2

Firefox Developer Edition 126.0b9

next: 14.2.3 
next-auth: 5.0.0-beta.18
react: 18.3.1
```

### Reproduction URL

https://github.com/ShahriarKh/middleware-test

### Describe the issue

Using the method mentioned in the [examples](https://github.com/nextauthjs/next-auth/blob/main/apps/examples/nextjs/middleware.ts) and also in the [docs](https://authjs.dev/getting-started/session-management/protecting#nextjs-middleware)  doesn't work at all.
```js
export { auth as middleware } from 'auth'

export const config = {
  matcher: ['/((?!api|_next/static|_next/image|favicon.ico).*)'],
};
```
I tried switching bun/Node, and also switching Next.js version (downgraded to 14.1.0 and 14.2.0 and both had the same issue)

I have to use a custom function like this, which is not desirable:
```js
import { auth } from 'auth'

export default auth((req) => {
  if (!req.auth) {
    const url = req.url.replace(req.nextUrl.pathname, '/login');
    return Response.redirect(url);
  }
});

export const config = {
  matcher: ['/((?!api|_next/static|_next/image|favicon.ico).*)'],
};
```

### How to reproduce

Clone the app and visit / or /test.

### Expected behavior

The middleware should automatically redirect to the login page if the request is unauthenticated.

**Comment by MateusTum** [comment]
Same error here!
The workaround that I found was using request cookies to check for session-token and validating it by using an api route. Here is my code:

```
// middleware.ts
import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";

export async function middleware(req: NextRequest) {
  const cookies = req.cookies;

  if (!cookies.get("authjs.session-token")) {
    return NextResponse.redirect(new URL("/login", req.url));
  } else {
    try {
      const sessionResponse = await fetch(
        `${req.nextUrl.origin}/api/auth/session`,
        {
          headers: {
            cookie: req.headers.get("cookie") || "", // Pass cookies to the API route
          },
        }
      );
      if (sessionResponse.status !== 200) {
        throw new Error("Session not found");
      }
    } catch (error) {
      
      console.log(error);
      const response = NextResponse.redirect(new URL("/login", req.url));
      response.cookies.set('authjs.session-token', '', { expires: new Date(0) });
      return response;
    }
  }
  return NextResponse.next();
}

export const config = {
  matcher: "/admin/:path*",
};
```

```
// api/auth/session/route.ts
import { auth } from "@/auth";
import { NextResponse } from "next/server";
import { Session } from "next-auth";

export async function GET() {
  const session: Session | null = await auth();
  if (!session) {
    return NextResponse.json({ message: "Auth required" }, { status: 401 });
  }
  return NextResponse.json({ message: "succc" }, { status: 200 });
}

```

**Comment by bibblebabl** [comment]
I am also experiencing a problem with incorrect req type definition in middleware. Is it the same for you?

```js
No overload matches this call.
  Overload 1 of 4, '(args_0: GetServerSidePropsContext): Promise<Session | null>', gave the following error.
    Argument of type '(req: NextAuthRequest) => Response | null' is not assignable to parameter of type 'GetServerSidePropsContext'.
  Overload 2 of 4, '(args_0: (req: NextAuthRequest, ctx: AppRouteHandlerFnContext) => void | Response | Promise<void | Response>): AppRouteHandlerFn', gave the following error.
    Argument of type '(req: NextAuthRequest) => Response | null' is not assignable to parameter of type '(req: NextAuthRequest, ctx: AppRouteHandlerFnContext) => void | Response | Promise<void | Response>'.
      Type 'Response | null' is not assignable to type 'void | Response | Promise<void | Response>'.
        Type 'null' is not assignable to type 'void | Response | Promise<void | Response>'.ts(2769)
```

<img width="884" alt="image" src="https://github.com/nextauthjs/next-auth/assets/9008978/421254b7-ef33-4d9e-b463-a277e489992e">

**Comment by drcodecamp** [comment]
@bibblebabl same

**Comment by dml0031** [comment]
> > Same error here! The workaround that I found was using request cookies to check for session-token and validating it by using an api route. Here is my code:
> > ```
> > // middleware.ts
> > import type { NextRequest } from "next/server";
> > import { NextResponse } from "next/server";
> > 
> > export async function middleware(req: NextRequest) {
> >   const cookies = req.cookies;
> > 
> >   if (!cookies.get("authjs.session-token")) {
> >     return NextResponse.redirect(new URL("/login", req.url));
> >   } else {
> >     try {
> >       const sessionResponse = await fetch(
> >         `${req.nextUrl.origin}/api/auth/session`,
> >         {
> >           headers: {
> >             cookie: req.headers.get("cookie") || "", // Pass cookies to the API route
> >           },
> >         }
> >       );
> >       if (sessionResponse.status !== 200) {
> >         throw new Error("Session not found");
> >       }
> >     } catch (error) {
> >       
> >       console.log(error);
> >       const response = NextResponse.redirect(new URL("/login", req.url));
> >       response.cookies.set('authjs.session-token', '', { expires: new Date(0) });
> >       return response;
> >     }
> >   }
> >   return NextResponse.next();
> > }
> > 
> > export const config = {
> >   matcher: "/admin/:path*",
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > // api/auth/session/route.ts
> > import { auth } from "@/auth";
> > import { NextResponse } from "next/server";
> > import { Session } from "next-auth";
> > 
> > export async function GET() {
> >   const session: Session | null = await auth();
> >   if (!session) {
> >     return NextResponse.json({ message: "Auth required" }, { status: 401 });
> >   }
> >   return NextResponse.json({ message: "succc" }, { status: 200 });
> > }
> > ```
> 
> This workaround works so far. I hope a fix will be released soon

FYI At least from what I found, the cookie name for me appears to be set as `__Secure-authjs.session-token` instead of just `authjs.session-token` on a site deployed to vercel that I was testing. Locally this was working for me fine, but once deployed still wasnt working and believe that is why. Still using a modified version of this to check for both so appreciate the workaround!

**Comment by BertVanHeckeCertifisc** [comment]
Same error here.

**Comment by surya-teja-222** [comment]
```ts
import NextAuth from 'next-auth';
import { authConfig } from './auth.config';

const { auth } = NextAuth(authConfig);

export default async function middleware(...args: Parameters<typeof auth>) {
  return auth(...args);
}

export const config = {
  matcher: [ 'matchers/'],
};
```

This is what I use and it works fine for me.
I'm on `5.0.0-beta.19`

**Comment by subhajit100** [comment]
> I am also experiencing a problem with incorrect req type definition in middleware. Is it the same for you?
> 
> ```js
> No overload matches this call.
>   Overload 1 of 4, '(args_0: GetServerSidePropsContext): Promise<Session | null>', gave the following error.
>     Argument of type '(req: NextAuthRequest) => Response | null' is not assignable to parameter of type 'GetServerSidePropsContext'.
>   Overload 2 of 4, '(args_0: (req: NextAuthRequest, ctx: AppRouteHandlerFnContext) => void | Response | Promise<void | Response>): AppRouteHandlerFn', gave the following error.
>     Argument of type '(req: NextAuthRequest) => Response | null' is not assignable to parameter of type '(req: NextAuthRequest, ctx: AppRouteHandlerFnContext) => void | Response | Promise<void | Response>'.
>       Type 'Response | null' is not assignable to type 'void | Response | Promise<void | Response>'.
>         Type 'null' is not assignable to type 'void | Response | Promise<void | Response>'.ts(2769)
> ```
> 
> <img alt="image" width="884" src="https://private-user-images.githubusercontent.com/9008978/333142394-421254b7-ef33-4d9e-b463-a277e489992e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDIyMDYsIm5iZiI6MTcxODcwMTkwNiwicGF0aCI6Ii85MDA4OTc4LzMzMzE0MjM5NC00MjEyNTRiNy1lZjMzLTRkOWUtYjQ2My1hMjc3ZTQ4OTk5MmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMDkxMTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjU1NDcwY2YzMjk0NDY1YmNjYjQyZTVjY2M2Y2FiMzc3ZjhmYjE3NjdkOWE2NjAyN2ViYjgxYjk2N2RiMTBlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fKWyxhn4pQ27-t8AzIWVAxWaoW2TIYTnzrW5mRyUT9w">

Hi @bibblebabl , this issue can be resolved if you write `return;` in place of `return null;` for all occurrences. In short, remove the null from return and return nothing. The messaeg also suggests `Type 'Response | null' is not assignable to type 'void | Response | Promise<void | Response>'.` which means null is not accepted, and uses void instead.

**Comment by balazsorban44** [comment]
Looks like the main problem is that https://authjs.dev/getting-started/session-management/protecting#nextjs-middleware forgets to mention the `authorized` callback: https://authjs.dev/reference/nextjs#authorized

If anyone wants to add it to the getting started docs, feel free to open a PR!

Suggestions here about `fetch`-ing the `/api/auth/session` should not be followed, as it will slow down your app's performance significantly, by doing an unnecessary network call on every single page request.

**Comment by jcourson-bg** [comment]
I'm still getting this issue. 

```export { auth as middleware } from "./auth"```

works on dev server, but does not work when hosted on vercel.

If I write the logic in the middleware.ts it works as expected, but this is not the described functionality.
