### ISSUE TITLE
No redirection after successful signOut()- NextAuth

### ISSUE THREAD

**Issue by Gaurav-Narayan-Varma** [nextauthjs/next-auth#10944]
### Environment

```
  System:
    OS: macOS 14.4.1
    CPU: (8) x64 Apple M1
    Memory: 16.27 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 124.0.6367.208
    Safari: 17.4.1
  npmPackages:
    next: 14.2.3 => 14.2.3 
    next-auth: ^5.0.0-beta.18 => 5.0.0-beta.18 
    react: ^18 => 18.3.1 ```
```

### Reproduction URL

https://github.com/Gaurav-Narayan-Varma/dgcl

### Describe the issue

Even though signOut() includes instructions to redirect the user after signout, the user remains on the same page even while they are signed out.

### How to reproduce

The sign out form:
```
import { signOut } from "@/auth";
import PowerIcon from "@heroicons/react/24/outline/PowerIcon";

export default function AdminHome() {
  return (
    <div>
      <div>Admin Home</div>
      <form
        action={async () => {
          "use server";
          await signOut({
            redirect: true,
            redirectTo: "http://localhost:3000/login-admin",
          });
        }}
      >
        <button className="...">
          <PowerIcon className="w-6" />
          <div className="hidden md:block">Sign Out</div>
        </button>
      </form>
    </div>
  );
}
```
The user logs out successfully but remains on the same page. My goal is to redirect them to the login page (http://localhost:3000/login-admin). 

For added context this is my auth.config file:
```
import type { NextAuthConfig } from "next-auth";

export const authConfig = {
  pages: {
    signIn: "/login-admin",
  },
  callbacks: {
    authorized({ auth, request: { nextUrl } }) {
      const isLoggedIn = !!auth?.user;
      const isInAdmin = nextUrl.pathname.startsWith("/admin");
      if (isInAdmin) {
        if (isLoggedIn) return true;
        return false; // Redirect unauthenticated users to login page
      } else if (isLoggedIn) {
        return Response.redirect(new URL("/admin", nextUrl));
      }
      return true;
    },
  },

  providers: [], // Add providers with an empty array for now
} satisfies NextAuthConfig;
```
Any thoughts on how to achieve the desired redirection after sign-out? 

### Expected behavior

I expect the user to be redirected to /login-admin after they click the signOut button.

**Comment by Gaurav-Narayan-Varma** [comment]
Update: I replaced the hardcoded Url with a variable fetched from headers() with no success:
```
import { signOut } from "@/auth";
import PowerIcon from "@heroicons/react/24/outline/PowerIcon";
import { headers } from "next/headers";

export default function AdminHome() {

  return (
    <div>
      <div>Admin Home</div>
      <form
        action={async () => {
          "use server";
          const origin = headers().get("origin");
          console.log("Headers:", headers());
          console.log("Origin:", origin);

          await signOut({
            redirect: false,
            redirectTo: `${origin}/login-admin`,
          });
        }}
      >
        <button className="...">
          <PowerIcon className="w-6" />
          <div className="hidden md:block">Sign Out</div>
        </button>
      </form>
    </div>
  );
}
```

**Comment by sfsajid91** [comment]
NextAuth V5 has some redirect issue with NextJs 14.2. The current solution is to downgrade NextJs in 14.1

If it works don't forget to delete the Upwork job post.

**Comment by Gaurav-Narayan-Varma** [comment]
> NextAuth V5 has some redirect issue with NextJs 14.2. The current solution is to downgrade NextJs in 14.1
> 
> If it works don't forget to delete the Upwork job post.

This does indeed work, thanks!

**Comment by weijyun9008** [comment]
> I'm having the same issue with @auth/sveltekit. It used to work I'm sure, but I just noticed it's broken now. My version numbers are all different...
> 
> ```
> @auth/mongodb-adapter": "^3.1.0"
> @auth/sveltekit": "^1.1.0"
> ```

You might want to try separating the redirect from the signOut function. I've noticed that signOut() can trigger an error in frameworks like Next.js (and possibly Svelte in your case), preventing the redirect inside signOut() from running. By placing redirect() inside a finally clause, it allows the redirect to run, regardless of whether there's an error or not.

Here's an example:

```typescript
export async function deauthenticate() {
  let errorOccurred = false;
  try {
    await signOut();
  } catch (error) {
    if (error instanceof AuthError) {
      errorOccurred = true;
      return 'Something went wrong.';
    }
    throw error;
  } finally {
    if (!errorOccurred) {
      redirect('/login');
    }
  }
}
```

In this code, if an error caused by Auth.js occurs during signOut(), it sets `errorOccurred` to true and prevents the redirect. Otherwise, the redirect to '/login' will execute in the finally block, ensuring it runs regardless of any errors during signOut().
