### ISSUE TITLE
AdapterUser Type Cuts Off Database Information

### ISSUE THREAD

**Issue by YTG2G3** [nextauthjs/next-auth#10958]
### Environment

```
  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 3.07 GB / 15.91 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @auth/drizzle-adapter: ^1.0.1 => 1.0.1
    next: 14.2.3 => 14.2.3
    next-auth: 5.0.0-beta.17 => 5.0.0-beta.17
    react: ^18 => 18.3.1
```

### Reproduction URL

https://github.com/YTG2G3/nextauth-demo

### Describe the issue

The BETA version of NextAuth uses 
`
{
  session: { user: AdapterUser } & AdapterSession
  /** Available when {@link AuthConfig.session} is set to `strategy: "database"`. */
  user: AdapterUser
}
`
as session callback parameter, and the AdapterUser is an interface that extends User:
`
export interface AdapterUser extends User {
  id: string
  email: string
  emailVerified: Date | null
}
`

However, when a custom column that is not defined in type is added to the users table (I used drizzle):
`
export const users = pgTable('user', {
  id: text('id')
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  name: text('name'),
  email: text('email').notNull(),
  emailVerified: timestamp('emailVerified', { mode: 'date' }),
  image: text('image'),
  admin: boolean('admin').default(false) // custom column
});
`
the column is not reflected on the callback:
`
callbacks: {
  session({ session, user }) {
    return {
      ...session,
      user: {
        ...session.user,
        admin: user.admin // this always results in undefined
      }
    };
  }
}
`

Thus, [Role Based Access Control](https://authjs.dev/guides/role-based-access-control#with-database) does not work

### How to reproduce

Explained above

### Expected behavior

Current version: {
  id: 'UUID-UUID-UUID-UUUUUUUID',
  name: 'John Doe',
  email: 'john@doe.com',
  emailVerified: null,
  image: null
}

Expected: {
  id: 'UUID-UUID-UUID-UUUUUUUID',
  name: 'John Doe',
  email: 'john@doe.com',
  emailVerified: null,
  image: null,
  admin: true
}

**Comment by k-taro56** [comment]
Hi,

This is not a bug.

You forgot to set the [`profile`](https://authjs.dev/reference/core/providers#profile) of the `providers` as described in the URL you provided.

```ts
    Google({
      profile(profile) {
        return { role:  false, ... profile }
      }
    })
  ],
```

If you need further help, don't hesitate to ask.
Thank you!

**Comment by YTG2G3** [comment]
Forgot to include that part in replication of the bug, but tested that it does not work in original codebase.

```
providers: [
    Google({
      profile(profile) {
        return { admin: false, ...profile };
      }
    })
  ],
  callbacks: {
    async session({ session, user }) {
      console.log(user);
    }
```

Output of console.log remains the same as above.

**Comment by k-taro56** [comment]
Oh, sorry.
But you will need to pass your own schemas when you add additional columns.

https://authjs.dev/getting-started/adapters/drizzle#passing-your-own-schemas

And you will probably need to extend the [`defineTable`](https://github.com/nextauthjs/next-auth/blob/2a5b13d06d3f0d9a70251a5d30f0354b39b93bdf/packages/adapter-drizzle/src/lib/pg.ts#L23) function.

**Comment by YTG2G3** [comment]
working solution. thank you for your help! I'll close the issue now
