### ISSUE TITLE
TypeOrm dependency installed while using Prisma

### ISSUE THREAD

**Issue by JakubKoralewski** [nextauthjs/next-auth#1097]
**Describe the bug**
I see that typeorm is installed by "next-auth", even though I use Prisma. Shouldn't these including "nodemailer" etc be a peer dependency? I'm not an expert so just asking.

```
"next-auth": {
      "version": "3.1.0",
      "resolved": "https://registry.npmjs.org/next-auth/-/next-auth-3.1.0.tgz",
      "integrity": "sha512-e+s6hjPZpqbnjla9WOi0VuLkDlLMU3cJmS0jTBBvsvSGsOPvMbaCCAMBEoNV3nWSgPrq6zLG2dixmCCxzG7fXA==",
      "requires": {
         ...
        "typeorm": "^0.2.24"
      }
    },
```

**Comment by balazsorban44** [comment]
Good call, I'll discuss this with @iaincollins soon.

#1093 should fix this, if accepted.

**Comment by balazsorban44** [comment]
So after a talk with @iaincollins ,we decided that it would probably be a breaking change to remove this, so we will wait until the next release. I'm going to close this issue for now but don't worry, I noted this, and I can assure you that the next major release will deal with this in a better way. (we will probably proceed as #1093, just wait out until the next major release with it)
