### ISSUE TITLE
Domain Changes in Twitter

### ISSUE THREAD

**Issue by Advanced-Boy-Shreyash** [nextauthjs/next-auth#10988]
### Provider type

Twitter

### Environment

```
 System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 1.02 GB / 7.87 GB
  Binaries:
    Node: 20.11.0 - E:\Node JS\node.EXE
    npm: 10.5.2 - E:\Node JS\npm.CMD
  Browsers:
    Edge: Chromium (124.0.2478.105)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    next: 14.2.3 => 14.2.3
    next-auth: ^4.24.7 => 4.24.7
    react: ^18 => 18.3.1
```

### Reproduction URL

https://github.com/Advanced-Boy-Shreyash/NextJS-Project

### Describe the issue

I was practicing next auth and when using twitter auth I realize that domain of twitter has changed so when I was trying to click on Login with Twitter I found that it is redirecting me to a page which suggests me to login with another method.

So there is a need of change for **TWITTER OAUTH** links used in this `signIn('twitter')` function.

Here is my route on which I am working (origin\api\[...nextauth]\route.js):
```
import NextAuth from 'next-auth'
import TwitterProvider from "next-auth/providers/twitter"

export const authoptions = NextAuth({
    providers: [
        TwitterProvider({
            clientId: process.env.TWITTER_CLIENT_ID,
            clientSecret: process.env.TWITTER_CLIENT_SECRET
        }),
    ]
})

export { authoptions as GET, authoptions as POST }
```

### How to reproduce

To reproduce 
1. Just start the app with : `npm run dev`
2. On `http://localhost:3000/login` try clicking on Login with Twitter

### Expected behavior

Expected is that it should redirect user to a twitter page which is changed to x.com for entering users credentials or authentication.
![image](https://github.com/nextauthjs/next-auth/assets/99673377/c2a00b59-8314-4dc2-8fed-371802096d0b)

**Comment by balazsorban44** [comment]
Fixed in https://github.com/nextauthjs/next-auth/pull/11047

**Comment by mrienstra** [comment]
FYI, as of today, the latest release of `next-auth` was June 1st, this PR was merged June 2nd, it was the second merge into `main` to "miss the boat": https://github.com/nextauthjs/next-auth/compare/next-auth%405.0.0-beta.19...main

Just for convenience, relevant docs on installing a specific GitHub commit: [npm](https://docs.npmjs.com/cli/v9/configuring-npm/package-json?v=true#git-urls-as-dependencies), [pnpm](https://pnpm.io/cli/add#install-from-git-repository), [yarn](https://yarnpkg.com/cli/add#examples).

Related issue: #10967.
