### ISSUE TITLE
Osso Provider Links Dead

### ISSUE THREAD

**Issue by tylerlazenby** [nextauthjs/next-auth#10989]
### What is the improvement or update you wish to see?

The links for OSSO no longer are valid and therefore do not assist with the demo app or documentation for Osso.

### Is there any context that might help us understand?

Update links for the correct site for Osso, or add the needed documentation in page.

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/providers/osso

**Comment by ndom91** [comment]
Thanks for pointing this out, it looks like the Osso project might be dead. Their [repo](https://github.com/enterprise-oss/osso) hasn't been touched in a long time and the homepage, as you pointed out, is dead.

Anyway, I've removed the dead links from our docs page :+1:
