### ISSUE TITLE
Why can User have an undefined id?

### ISSUE THREAD

**Issue by peguerosdc** [nextauthjs/next-auth#10992]
### What is the improvement or update you wish to see?

In the [User](https://authjs.dev/reference/nextjs#user-2) page, it's not clear in which cases I can expect an undefined `id`, which is labeled as `optional` .

### Is there any context that might help us understand?

I am using `events` to perform actions for users logging in into my app. The [createUser](https://authjs.dev/reference/nextjs#createuser) event is triggered once a user is created. In this context, I wouldn't expect `user.id` to be `undefined`, but apparently it can be. Can it? If not, is it a bug in the type of the object passed to `createEvent`?

### Does the docs page already exist? Please link to it.

https://authjs.dev/reference/nextjs#user-2

**Comment by masterjanic** [comment]
Hi @peguerosdc,
have a look at the code [here](https://github.com/nextauthjs/next-auth/blob/a616aad328054a3fa65541e6baa4d8cfbc7171e0/packages/core/src/index.ts#L447). 

For example when used in the `signIn` callback depending on whether you are using the credentials provider or an oauth provider the type is either User or AdapterUser. If it is an [AdapterUser](https://authjs.dev/reference/core/adapters#adapteruser) then the id is always defined. 

So if you are only using oauth providers and you rely on the database strategy I suppose it is safe to assume that the id is defined. But before any user is created, the id might be `undefined`.
