### ISSUE TITLE
Prisma Adapter: warn(prisma) findOne is deprecated. Please use findUnique instead

### ISSUE THREAD

**Issue by SelfDevTV** [nextauthjs/next-auth#1099]
Hi guy:

a little Bug I think.
When you use the Prisma adapter you get a few of these warnings in the console:

>warn(prisma)  findOne is deprecated. Please use findUnique instead.

I think it has to do with this file / line: https://github.com/nextauthjs/next-auth/blob/1a1a1f97214bedc7a2a0e092b168b331ffa6a64b/src/adapters/typeorm/index.js#L230

**Comment by timshingyu** [comment]
@SelfDevTV I also got the same error using Prisma Adapter.
My next-auth version is 3.1.20
After digging through the code, it's seems the 3.1.20 Prisma adapter still using `findOne`. But the main branch already has this fixed.
try to reinstall the package to using the lastest one, it should get rid of this error message.
```
npm install next-auth@next
```

**Comment by SelfDevTV** [comment]
Hi @timshingyu 

You shure about that. The main branch says this:

>This branch is 10 commits ahead, 85 commits behind canary.

I hope it's not bricking anything else :D 
I'll give it a try

**Comment by timshingyu** [comment]
@SelfDevTV should be `canary` instead.

**Comment by SelfDevTV** [comment]
`yarn add next-auth@next` fixes the issue. What branch is the release branch anyone knows?

**Comment by balazsorban44** [comment]
Our default branch is `canary`, our npm channel is also `canary`!
