### ISSUE TITLE
Invalid MongoDB schema for the prisma adapter (next-auth@beta)

### ISSUE THREAD

**Issue by Blu-Tiger** [nextauthjs/next-auth#10999]
### What is the improvement or update you wish to see?

The docs for the MongoDB schema in the prisma adapter are missing an alternative to the compound ids in the Authenticator model.

### Is there any context that might help us understand?

In the current docs for the prisma adapter, the schema for MongoDB includes compound ids in the Authenticator model, which are not supported by MongoDB.

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/adapters/prisma#schema

**Comment by ndom91** [comment]
Thanks for pointing this out! Just pushed a fix :+1:

**Comment by Blu-Tiger** [comment]
Thank you for the rapid fix, but there seems to still be an error: MongoDB models require exactly one identity field annotated with @id.

**Comment by ndom91** [comment]
> Thank you for the rapid fix, but there seems to still be an error: MongoDB models require exactly one identity field annotated with `@id`.

Hmm okay, I've updated it like this, mapping the `credentialID` field to `_id`. What do you think?

```prisma
// Optional for WebAuthn support
model Authenticator {
  credentialID         String  @unique @map("_id")
  userId               String  @db.ObjectId
  providerAccountId    String
  credentialPublicKey  String
  counter              Int
  credentialDeviceType String
  credentialBackedUp   Boolean
  transports           String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([userId, credentialID])
}
```

**Comment by Blu-Tiger** [comment]
It gives the same error: ```Invalid model: MongoDB models require exactly one identity field annotated with @id```.
Probably one has to be `@id`.

**Comment by ndom91** [comment]
@Blu-Tiger what do you mean by ".. I don't knwo if it would work as the documentation intends" exactly?

**Comment by Blu-Tiger** [comment]
I mean that in the documentation (for nextauth beta) there is a step by step guide on how to setup everything, but i don't know if those changes on the database setup for mongodb need further changes in the other steps of the setup, i just wanted a confirmation on that.

**Comment by ndom91** [comment]
Ah no, there's no later updates to the schema or anythign like that. This is it. So yeah I'll update it to the schema you suggested here (with the explicit `@id` mapping for `credentialID`). Thanks!

**Comment by Blu-Tiger** [comment]
Thanks for the help and clarification.
