### ISSUE TITLE
v5 Beta does not work with Next 15 RC (React 19 RC) - Middleware issue

### ISSUE THREAD

**Issue by Aralf** [nextauthjs/next-auth#11006]
### Environment

```
 System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 79.98 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 9.0.2 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
  Browsers:
    Chrome: 125.0.6422.112
    Safari: 17.4.1
  npmPackages:
    next: 15.0.0-rc.0 => 15.0.0-rc.0 
    next-auth: 5.0.0-beta.18 => 5.0.0-beta.18 
    react: 19.0.0-rc-935180c7e0-20240524 => 19.0.0-rc-935180c7e0-20240524 
```

### Reproduction URL

https://github.com/Aralf/next-intl-react-19-compiler/tree/authjs-v5

### Describe the issue

The issue is related to this change https://github.com/vercel/next.js/pull/65424 where in case we import something from react it will only import server related api and giving error for client apis.

I had a reproduction repository that uses next-intl and next-auth v4 as I had initially raised this issue with next-intl amannn/next-intl#1075 
The root cause was found https://github.com/amannn/next-intl/issues/1075#issuecomment-2128903737 and after applying the suggested change everything got resolved.

But the issue still persisted in another project where I use v5 instead. So I made the a new branch (the one I provide as reproduction) where I have updated to v5 and sure enough a face the same issue. 

When import the universal `auth` into `middlware.ts` it throws the following error

<img width="979" alt="Screenshot 2024-05-25 at 01 09 00" src="https://github.com/nextauthjs/next-auth/assets/7780231/aa3d6f8c-6e84-441f-b631-2e86a284a050">

I don't know if it is because `auth` itself of because the use of `next-auth` that returns `auth` along with the handlers, signIn, signOut, etc. and everything is exported from the same file. As the issue on next-intl was because of importing the file where their navigation solution (that used next/link internally ) was also exported, I assume something similar is happening here.

### How to reproduce

Make sure you are on the branch `authjs-v5` and run `pnpm install` & `pnpm dev`. Application will crash from the start.
You can then try with `main` where next-auth v4 is used and see that the application runs fine.

### Expected behavior

It should work with Next 15 & React 19

**Comment by Gawdfrey** [comment]
I had the same issue with `next-intl` and now `next-auth`, but it seems the latest canary release has a fix for both of these issues, see the [fix](https://github.com/vercel/next.js/pull/66175). It works fine for me at least now.

[Release](https://github.com/vercel/next.js/releases/tag/v14.3.0-canary.81)

**Comment by Aralf** [comment]
> I had the same issue with `next-intl` and now `next-auth`, but it seems the latest canary release has a fix for both of these issues, see the [fix](https://github.com/vercel/next.js/pull/66175). It works fine for me at least now.
> 
> [Release](https://github.com/vercel/next.js/releases/tag/v14.3.0-canary.81)

You are absolutely right, changing to latest canary where that [fix](https://github.com/vercel/next.js/pull/66175) is included resolves all the issues. Thanks @Gawdfrey

**Comment by ThangHuuVu** [comment]
Closed as this isn't an issue with `next-auth`, thanks @Gawdfrey for pointing it out.

> I had the same issue with `next-intl` and now `next-auth`, but it seems the latest canary release has a fix for both of these issues, see the [fix](https://github.com/vercel/next.js/pull/66175). It works fine for me at least now.
> 
> [Release](https://github.com/vercel/next.js/releases/tag/v14.3.0-canary.81)
