### ISSUE TITLE
Add data to Session callback for Credentials provider

### ISSUE THREAD

**Issue by dcantatore** [nextauthjs/next-auth#1102]
**Describe the bug**
When running the authorize function for a custom Credentials provider I return/resolve with an object such as: 
``` 
{ name: 'name', email: 'Email', id:'UserID', test: 'test', image: 'any.jpg' }
```

However all of the data here is not persisted except for the name, email, and picture. I have noticed that I can access it in the signIn callback, and for some reason only in the first time the jwt callback runs.

From what I'm reading and the other bug reports it seems like this data should be available in the session callback. The session callback parameters of (first param) session and (second param) user do not have it. From what I can tell it should be in the user object since that is where the rest of the data ends up that is not stripped. 

Is this a bug? How can I make this data persist so that I can use the returned data from authorize to build the session object?

Do not report bugs with your own project here, ask from help by raising a question instead - this helps us a lot with administration overhead.

**Steps to reproduce**
Add additional fields to the return from the Credentials provider authorization.

**Expected behavior**
Data to persist into other callbacks.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [X] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Hi there! So for anything else to be available in the session callback, it must go through the jwt callback first.

On the first time the jwt is created, you will have all the info you need through the additional params on the jwt callback. Simply do an if check and return a token with the data you need, and return the token as is otherwise. Than you can check the second param of session, which will be your token. Return as many info from it as you wish. 


Check the docs for reference:

https://next-auth.js.org/configuration/callbacks#jwt-callback

**Comment by dcantatore** [comment]
@balazsorban44 

Thanks for the reply, is this a safe/good way to attach the data:

```
 jwt(token, profile) {
            if (profile) {
                token = Object.assign(token, profile);
            }
            return Promise.resolve(token)
        },
```

**Comment by balazsorban44** [comment]
Yes, if you ask me though, I would write it like this:

```js
jwt(token, profile) {
  if(profile) {
    return {...token, user: profile}
  }
  return token
},
session(session, token) {
  return token
}
```
(Then when you access the session, everything user related would be available on the `session.profile` property, it is more organized for my taste.)

You don't need to wrap the return result in `Promise.resolve()` in any case. 😉

But nothing wrong with yours either.

**Comment by dcantatore** [comment]
If we are building a larger session object with some other "fetched" data, is the most efficient place to do so in the jwt callback - such as in that initial conditional?

**Comment by balazsorban44** [comment]
Most browsers has a limit of 4096 bytes per cookie. as long as you don't exceed that, you are good.

**Comment by oliver-daniel** [comment]
Szia @balazsorban44, thank you so much for this! I've been trying to figure out how to mesh NextAuth with Django Rest Framework's `SessionAuthentication` for a week now. I'd have to figure that enough people want to use Next with some pre-existing, authenticated API that this would be a frequent use case. Maybe this should be referenced somewhere in the documentaiton?

**Comment by balazsorban44** [comment]
Szia @oliver-daniel could you maybe open a different issue and add a bit more information about your usecase?

**Comment by strafe** [comment]
@balazsorban44 sorry for the ancient ping but returning token in TS causes errors since it expects a `Session`. Is there a best practice as far as your earlier example is concerned for TS?
