### ISSUE TITLE
Loking for alternative to client secret In Azure Ad Provider

### ISSUE THREAD

**Issue by prasadkukkadapu** [nextauthjs/next-auth#11086]
### What is the improvement or update you wish to see?

in nextAuth Azure - Ad is one of the provider. Is there any way to use toekn credential or default credential prop instead on client secret. recently my flagged  security incident for using client secret. 

### Is there any context that might help us understand?

in nextAuth Azure - Ad is one of the provider. Is there any way to use toekn credential or default credential prop instead on client secret. recently my flagged  security incident for using client secret.

**Comment by balazsorban44** [comment]
You can use PKCE by adding `checks: ["pkce"]` to the provider configuration, which doesn't require a client secret in that case.

We have a type bug, so, you still might need to add `clientSecret: ""`, but it should work nonetheless

**Comment by prasadkukkadapu** [comment]
@balazsorban44 - We updated as you suggested, but we are getting the following error - "invalid_client (AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'
![image](https://github.com/nextauthjs/next-auth/assets/12912512/a35b5398-e50a-43cf-ae3a-621509989c82)

**Comment by prasadkukkadapu** [comment]
> You can use PKCE by adding `checks: ["pkce"]` to the provider configuration, which doesn't require a client secret in that case.
> 
> We have a type bug, so, you still might need to add `clientSecret: ""`, but it should work nonetheless

@balazsorban44 - Can you please validate my above configuration.

**Comment by PauloMigAlmeida** [comment]
@prasadkukkadapu did you manage to get that working? I'm getting the exact same error
