### ISSUE TITLE
Keycloak provider does not work in docker

### ISSUE THREAD

**Issue by benmarte** [nextauthjs/next-auth#11082]
### Provider type

Keycloak

### Environment

```
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 5.36 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 9.1.3 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 125.0.6422.142
    Edge: 125.0.2535.85
    Safari: 17.5
```

### Reproduction URL

https://github.com/benmarte/authjs-docker/

### Describe the issue

I created a repo with instructions, videos and screenshots where you can reproduce the issue easily by running `docker-compose up` and test in docker and locally.

The repo can be found here: https://github.com/benmarte/authjs-docker/

I copied the Keycloak instructions from that repo here, keep in mind the instructions in repo have more context and provides the ability to test with authentik provider as well.

Here is a short video displaying the problem.

https://github.com/nextauthjs/next-auth/assets/693275/9eb9d0df-c0a5-49a2-98a4-8238c4706bd6

### How to reproduce

Edit your /etc/hosts file with the following entries:

- 127.0.0.1 keycloak.local
- 127.0.0.1 webapp.local

## Creating a User in Keycloak

Once Keycloak is up and running, log into the Keycloak admin interface by visiting `http://keycloak.local` in your browser.

The credentials to log into Keycloak are:

```sh
username: admin
password: admin
```

After logging in, select the `webapp` realm from the left navigation dropdown.

![webapp-realm](https://github.com/nextauthjs/next-auth/assets/693275/2e584af1-4848-4c86-a30a-cac32dfadb5b)

Then, click `Users` and on the users page, click `Create new user`.

![create-new-user](https://github.com/nextauthjs/next-auth/assets/693275/14b2c069-825f-43df-a382-d09609f07c70)

Enter the username you want to use to log into the `webapp`. For simplicity, you can use `admin`.

![username](https://github.com/nextauthjs/next-auth/assets/693275/b5ee6aa3-a6bb-4315-a0fb-4957bdd7b8f3)

After creating the user, click the `Credentials` tab and then `Set password`. Enter the desired `password` and `password confirmation`, uncheck the temporary toggle switch, and click `Save`. Confirm by clicking `Save password`.

![password](https://github.com/nextauthjs/next-auth/assets/693275/275f50e3-b4d8-4000-ad4e-42ae03c1d769)

This concludes the Keycloak setup.

---

## Logging into the Webapp with Keycloak

Log into the webapp with the username and password you set in Keycloak and click `Sign In`.

![login](https://github.com/nextauthjs/next-auth/assets/693275/1de43e87-303e-464b-af26-06e863844e66)

The first time you log into the webapp, Keycloak will ask you to update your account information. Enter the required information and click `Submit`.

![update-account](https://github.com/nextauthjs/next-auth/assets/693275/f5b3664d-85e2-4bba-ae17-b1da224402fe)

Once you update your account information, you will encounter the `ECONNREFUSED` error, preventing you from using the webapp.

![server-error](https://github.com/nextauthjs/next-auth/assets/693275/b6f15d93-5c75-42c9-867d-f31f4079a44c)

> A logger entry has been added in [auth.ts](https://github.com/benmarte/authjs-docker/blob/bcd4fdd945247a2d852500c8bc13a8775003929f/nextjs-auth-example/auth.ts#L136) with console logs to facilitate debugging in Docker.

---

## Testing Keycloak in Docker with Local Webapp

To run Keycloak in Docker, execute:

```sh
docker-compose -f docker-compose-keycloak.yml up
```

Follow the steps to [create a user for the webapp in Keycloak](https://github.com/benmarte/authjs-docker/tree/main?tab=readme-ov-file#creating-a-user-in-keycloak), open a second terminal window, navigate to the project directory, and rename `.env.example` to `.env.local`. Then run:

```sh
npm run dev
```

Use the credentials you set in Keycloak to log in without any issues.

![loggedin](https://github.com/nextauthjs/next-auth/assets/693275/ee8473dc-a6ed-448c-9cbf-86eb0975e285)

---

## Notes

The documentation specifies that you only need three environment variables:

```sh
AUTH_KEYCLOAK_ID
AUTH_KEYCLOAK_SECRET
AUTH_KEYCLOAK_ISSUER
```

Using only these three values works fine when running locally, but running in Docker results in an error because Auth.js does not pass the authorization URL, leading to the same `ECONNREFUSED` error when clicking the sign-in button.

If you replace the Keycloak provider in [`auth.ts`](https://github.com/benmarte/authjs-docker/blob/main/nextjs-auth-example/auth.ts#L78) with the following configuration, you will progress further in the authorization process in Docker, but the error persists.

> Note: When running the web app locally, the Keycloak client needs to be public; otherwise, it will not work with a confidential client in Keycloak. When running Keycloak in Docker, it does not work regardless of whether the client is public or confidential.

```javascript
Keycloak({
  clientId: process.env.AUTH

_KEYCLOAK_ID,
  clientSecret: process.env.AUTH_SECRET,
  issuer: `${process.env.AUTH_KEYCLOAK_ISSUER}`,
  // these are needed in order to have authjs get further in the authorization process in docker
  authorization: `${process.env.AUTH_KEYCLOAK_ISSUER}/protocol/openid-connect/auth`,
  wellKnown: `${process.env.AUTH_KEYCLOAK_ISSUER}/.well-known/openid-configuration`,
  token: `${process.env.AUTH_KEYCLOAK_ISSUER}/protocol/openid-connect/token`,
  userinfo: `${process.env.AUTH_KEYCLOAK_ISSUER}/protocol/openid-connect/userinfo`,
});
```

![server-error](https://github.com/nextauthjs/next-auth/assets/693275/0255fe8d-acad-4f5f-b8fd-59ea7932c94e)

This is the log with the error:

```
webapp-1      | CREATE_PKCECODEVERIFIER [
webapp-1      |   { value: 'wguHZrGrVQ8VI-6yuxOmYGgy3AqNKge3Mfq1-1EFbT0', maxAge: 900 }
webapp-1      | ]
webapp-1      | authorization url is ready [
webapp-1      |   {
webapp-1      |     url: URL {
webapp-1      |       href: 'http://keycloak.local/realms/webapp/protocol/openid-connect/auth?scope=openid+profile+email&response_type=code&client_id=webapp&redirect_uri=http%3A%2F%2Fwebapp.local%2Fauth%2Fcallback%2Fkeycloak&code_challenge=uAijCLJ6Fey--nU5Bp0I6UohW3o8ksueVvWs9FsYpio&code_challenge_method=S256',
webapp-1      |       origin: 'http://keycloak.local',
webapp-1      |       protocol: 'http:',
webapp-1      |       username: '',
webapp-1      |       password: '',
webapp-1      |       host: 'keycloak.local',
webapp-1      |       hostname: 'keycloak.local',
webapp-1      |       port: '',
webapp-1      |       pathname: '/realms/webapp/protocol/openid-connect/auth',
webapp-1      |       search: '?scope=openid+profile+email&response_type=code&client_id=webapp&redirect_uri=http%3A%2F%2Fwebapp.local%2Fauth%2Fcallback%2Fkeycloak&code_challenge=uAijCLJ6Fey--nU5Bp0I6UohW3o8ksueVvWs9FsYpio&code_challenge_method=S256',
webapp-1      |       searchParams: URLSearchParams {
webapp-1      |         'scope' => 'openid profile email',
webapp-1      |         'response_type' => 'code',
webapp-1      |         'client_id' => 'webapp',
webapp-1      |         'redirect_uri' => 'http://webapp.local/auth/callback/keycloak',
webapp-1      |         'code_challenge' => 'uAijCLJ6Fey--nU5Bp0I6UohW3o8ksueVvWs9FsYpio',
webapp-1      |         'code_challenge_method' => 'S256' },
webapp-1      |       hash: ''
webapp-1      |     },
webapp-1      |     cookies: [ [Object] ],
webapp-1      |     provider: {
webapp-1      |       id: 'keycloak',
webapp-1      |       name: 'Keycloak',
webapp-1      |       type: 'oidc',
webapp-1      |       style: [Object],
webapp-1      |       clientId: 'webapp',
webapp-1      |       clientSecret: 'MohY0/2zSQw/psWEnejC2ka3Al0oifvY4YjOkUaFfnI=',
webapp-1      |       issuer: 'http://keycloak.local/realms/webapp',
webapp-1      |       authorization: [Object],
webapp-1      |       wellKnown: 'http://keycloak.local/realms/webapp/.well-known/openid-configuration',
webapp-1      |       token: [Object],
webapp-1      |       userinfo: [Object],
webapp-1      |       signinUrl: 'http://webapp.local/auth/signin/keycloak',
webapp-1      |       callbackUrl: 'http://webapp.local/auth/callback/keycloak',
webapp-1      |       redirectProxyUrl: undefined,
webapp-1      |       checks: [Array],
webapp-1      |       profile: [Function: C],
webapp-1      |       account: [Function: I]
webapp-1      |     }
webapp-1      |   }
webapp-1      | ]
webapp-1      | env-url-basepath-redundant []
webapp-1      | callback route error details [
webapp-1      |   {
webapp-1      |     method: 'GET',
webapp-1      |     query: {
webapp-1      |       session_state: 'dc54b9b2-5500-417e-b7eb-f078cf281371',
webapp-1      |       iss: 'http://keycloak.local/realms/webapp',
webapp-1      |       code: '867f1b23-7574-4c7d-ba08-411dce3cbf8b.dc54b9b2-5500-417e-b7eb-f078cf281371.61010cc3-48ae-401b-9764-e086e4b43814'
webapp-1      |     },
webapp-1      |     body: undefined
webapp-1      |   }
webapp-1      | ]
webapp-1      | a: Read more at https://errors.authjs.dev#callbackrouteerror
webapp-1      |     at is (/app/.next/server/chunks/428.js:393:38923)
webapp-1      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
webapp-1      |     at async im (/app/.next/server/chunks/428.js:393:45531)
webapp-1      |     at async ig (/app/.next/server/chunks/428.js:393:50443)
webapp-1      |     at async /app/node_modules/.pnpm/next@14.1.4_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
webapp-1      |     at async eI.execute (/app/node_modules/.pnpm/next@14.1.4_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
webapp-1      |     at async eI.handle (/app/node_modules/.pnpm/next@14.1.4_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737)
webapp-1      |     at async doRender (/app/node_modules/.pnpm/next@14.1.4_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1317:42)
webapp-1      |     at async cacheEntry.responseCache.get.routeKind (/app/node_modules/.pnpm/next@14.1.4_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1539:28)
webapp-1      |     at async NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/.pnpm/next@14.1.4_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1447:28) {
webapp-1      |   type: 'CallbackRouteError',
webapp-1      |   kind: 'error',
webapp-1      |   [cause]: {
webapp-1      |     err: TypeError: fetch failed
webapp-1      |         at node:internal/deps/undici/undici:12502:13
webapp-1      |         at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
webapp-1      |         at async globalThis.fetch (/app/.next/server/chunks/675.js:1:36483)
webapp-1      |         at async t2 (/app/.next/server/chunks/428.js:393:27136)
webapp-1      |         at async is (/app/.next/server/chunks/428.js:393:34159)
webapp-1      |         at async im (/app/.next/server/chunks/428.js:393:45531)
webapp-1      |         at async ig (/app/.next/server/chunks/428.js:393:50443)
webapp-1      |         at async /app/node_modules/.pnpm/next@14.1.4_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
webapp-1      |         at async eI.execute (/app/node_modules/.pnpm/next@14.1.4_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
webapp-1      |         at async eI.handle (/app/node_modules/.pnpm/next@14.1.4_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737) {
webapp-1      |       [cause]: [Error]
webapp-1      |     },
webapp-1      |     errno: -3001,
webapp-1      |     code: 'EAI_AGAIN',
webapp-1      |     syscall: 'getaddrinfo',
webapp-1      |     hostname: 'keycloak.local',
webapp-1      |     provider: 'keycloak'
webapp-1      |   }
webapp-1      | } []
webapp-1      | env-url-basepath-redundant []
```

Even though Authjs throws an error you can see the session is generated in keycloak when you try to login to the webapp.

![keycloak-session](https://github.com/nextauthjs/next-auth/assets/693275/c27fcf6a-0f00-4889-9413-789d8ec1a029)

---

Thank you for helping debug this problem. Hopefully, we can get Auth.js to work in Docker as intended.

### Expected behavior

You should be able to login using the keycloak provider and be redirected to the app and see the users session information.

**Comment by ShagaiOppa** [comment]
Any workaround here such as overriding callback methods or something?

**Comment by benmarte** [comment]
I’m not using nginx so thats not it, I’m just using authentik as my IDP for now until this gets resolved.

**Comment by balazsorban44** [comment]
Closing as this as not an Auth.js bug.

See https://nextjs-docker-example.authjs.dev, our hosted Docker example, working as expected with proper setup of Keycloak. The fetch error indicates a fault network configuration.

**Comment by benmarte** [comment]
If anyone is using docker-compose and is still running into this issue I got it resolved thank to the help of another keycloak user in their forums: https://keycloak.discourse.group/t/issues-running-keycloak-in-docker-and-authenticating-with-authjs/26443/14
