### ISSUE TITLE
Update documentation to enhance type safety for environment variables in NextAuth configuration

### ISSUE THREAD

**Issue by dhairyathedev** [nextauthjs/next-auth#11114]
### What is the improvement or update you wish to see?

The NextAuth configuration documentation should be updated to enhance type safety for environment variables. Specifically, the code snippets should include the non-null assertion operator (!) after the environment variables process.env.SUPABASE_URL and process.env.SUPABASE_SERVICE_ROLE_KEY. This change ensures TypeScript treats these variables as non-null and non-undefined, improving overall type safety.

### Is there any context that might help us understand?

The current documentation uses environment variables directly without ensuring they are non-null and non-undefined. This method does not fully ensure the variables are defined at runtime, potentially leading to runtime errors if the environment variables are not set. By using the non-null assertion operator (!), we can enforce that these variables are always defined, aligning with TypeScript's strict type-checking practices.

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/adapters/supabase

**Comment by balazsorban44** [comment]
Non-null assertions are a "lie" by typescript. You cannot safely type check environment variables, they have to be checked at runtime. This is out of scope for Auth.js

But you can for example check out https://github.com/t3-oss/t3-env
