### ISSUE TITLE
How to add a custom login email template?

### ISSUE THREAD

**Issue by alextseitlin** [nextauthjs/next-auth#1111]
**Your question**

I want to change this template. Is there an example?
![image](https://user-images.githubusercontent.com/13120976/104634477-5b877d80-56a9-11eb-9da5-9fd8bf37e4e8.png)

I understand that the email through "sendVerificationRequest" https://next-auth.js.org/providers/email#customising-emails but it is not working for me. Are there any examples I can check?

**Feedback**
Could not find relevant information and examples in the documentation...

**Comment by alextseitlin** [comment]
I tried adding verifyRequest like this
```
 pages: {
    signIn: '/login',
    verifyRequest: '/auth/verify-request',
  },
```

With this same code here https://github.com/nextauthjs/next-auth/blob/1838e43b275fa36b1eb7bd046eead6795cfd0f2d/src/server/pages/verify-request.js but I get an error "Cannot read property 'replace' of undefined"

**Comment by balazsorban44** [comment]
What do you mean it is not working for you? Do you have a public repository or a reproduction of this?
