### ISSUE TITLE
Refresh token rotation

### ISSUE THREAD

**Issue by deelo55** [nextauthjs/next-auth#11121]
### What is the improvement or update you wish to see?

1. The doc on refresh token rotation for JWT, doesn't work with the client side functionality as it doesn't put an error into the session.
2. If an error occurs, the session still remains authenticated albeit with an error message attached. This doesn't seem secure as a user can still see resources which require authentication. I believe the status should change to unauthenticated?

### Is there any context that might help us understand?

N/A

### Does the docs page already exist? Please link to it.

https://authjs.dev/guides/refresh-token-rotation

**Comment by balazsorban44** [comment]
Hi, I just updated the guide with more details https://github.com/nextauthjs/next-auth/commit/862a505782588a0760721eafb6a3bb905f3e383f

Please have a look.

> the client side functionality as it doesn't put an error into the session

This sounds like a bug, please open a bug report, and we will have a look!
