### ISSUE TITLE
Api auth path error when using with turbopack

### ISSUE THREAD

**Issue by sawa-ko** [nextauthjs/next-auth#11127]
### Environment

```
  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 4.35 GB / 15.78 GB
  Binaries:
    Node: 22.2.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.4 - C:\Program Files\nodejs\pnpm.CMD
    bun: 1.1.12 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (125.0.2535.92)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    next: 14.2.3 => 14.2.3 
    next-auth: 5.0.0-beta.19 => 5.0.0-beta.19 
    react: 18.3.1 => 18.3.1 
```

### Reproduction URL

https://github.com/sawa-ko/next-auth-example/tree/draft/interesting-haze

### Describe the issue

Currently when you try to use next-auth api routes with turbopack you get an error that x library could not be parsed.

```
Error: Could not parse module '[project]/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/future/route-modules/app-route/vendored/contexts/app-router-context.js'
```

### How to reproduce

1. Use the reproduction project
2. Try login with the login button
3. See error

### Expected behavior

That next-auth can be used correctly, because with webpack it works fine.

**Comment by emulienfou** [comment]
Hi @sawa-ko,
 your issue seems to be related to this one: https://github.com/vercel/next.js/issues/66162.
The fix will be in Next.js v14.3.0 when released

**Comment by trulysinclair** [comment]
I also have this issue, I tried using some canaries for Next and React but that only broke things

**Comment by tevass** [comment]
Hi @sawa-ko,
i was having this issue in version `5.0.0-beta.19`. I downgraded to `5.0.0-beta.18` and it worked for me.

**Comment by sawa-ko** [comment]
@tevass I can confirm that using the version you say works fine again.

**Comment by emulienfou** [comment]
I can also confirm that `5.0.0-beta.19` is introducing issue with `next@15.0.0-canary` and ` react@19.0.0-rc`.
Downgrading to `5.0.0-beta.18` is also fixing the issue with Turbo!

**Comment by bgolubovic** [comment]
> I can also confirm that `5.0.0-beta.19` is introducing issue with `next@15.0.0-canary` and ` react@19.0.0-rc`.
> Downgrading to `5.0.0-beta.18` is also fixing the issue with Turbo!

The same here. Thank you. 

I was getting the error: 
`Error: Could not parse module '[project]/node_modules/next/dist/server/future/route-modules/app-route/vendored/contexts/app-router-context.js'`

**Comment by MarkLyck** [comment]
Thanks for posting this. I also had this error on `5.0.0-beta.19`. Downgrading to `5.0.0-beta.18` fixed it 👍

**Comment by ZinhleBu** [comment]
Im also getting this error. Downgrading to `5.0.0-beta.18` fixed my issue.

**Comment by aianddeng** [comment]
5.0.0-beta.20 not fixed, sad

**Comment by essuraj** [comment]
this bug is breaking login, rolling back to beta 18. still broken in beta 20

**Comment by balazsorban44** [comment]
Hi folks, I did some digging here! See #11551 for the solution/explanation. A fix will be out in the next release!

**Comment by luisalrp** [comment]
downgrading to 5.0.0-beta.18 worked in dev. Build still breaks. Did somebody build properly? Thanks!

**Comment by brycefranzen** [comment]
> downgrading to 5.0.0-beta.18 worked in dev. Build still breaks. Did somebody build properly? Thanks!

I am able to build without issues on `5.0.0-beta.18`.
