### ISSUE TITLE
Attempted import error: 'parse' is not exported from 'cookie' with

### ISSUE THREAD

**Issue by MarkLyck** [nextauthjs/next-auth#11235]
### Environment

```
  System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 359.38 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
    pnpm: 8.7.0 - ~/Library/pnpm/pnpm
    bun: 1.1.12 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 119.1.60.118
    Chrome: 125.0.6422.60
    Safari: 17.5
  npmPackages:
    next: 15.0.0-rc.0 => 15.0.0-rc.0
    next-auth: 5.0.0-beta.19 => 5.0.0-beta.19
    react: 19.0.0-rc-f994737d14-20240522 => 19.0.0-rc-f994737d14-20240522
```

### Reproduction URL

https://github.com/MarkLyck/next-auth-cookie-err-reproduction

### Describe the issue

When building a NextJS@15 rc application on Vercel with next-auth@5.0.0-beta.19 I get the following error:

```
> next build

  ▲ Next.js 15.0.0-rc.0
  - Environments: .env

   Creating an optimized production build ...
Failed to compile.

./node_modules/@auth/core/lib/utils/web.js
Attempted import error: 'parse' is not exported from 'cookie' (imported as 'parseCookie').

Import trace for requested module:
./node_modules/@auth/core/lib/utils/web.js
./node_modules/@auth/core/index.js
./node_modules/next-auth/index.js
./src/auth.ts
./src/app/api/[...nextauth]/route.ts

./node_modules/@auth/core/lib/utils/web.js
Attempted import error: 'serialize' is not exported from 'cookie' (imported as 'serialize').

Import trace for requested module:
./node_modules/@auth/core/lib/utils/web.js
./node_modules/@auth/core/index.js
./node_modules/next-auth/index.js
./src/auth.ts
./src/app/api/[...nextauth]/route.ts


> Build failed because of webpack errors
```

Things I have tried:
- Removing all unneeded dependencies
- Removing browserslist from package.json
- Pinning the cookie dependency to 0.6.0
- downgrading to `next-auth@5.0.0-beta.15`
- Tried different package managers: `npm` & `bun`
- Tried a lot of changes to my tsconfig.json, including copying the config from the next-auth example.
- Downgrading next to the latest stable version 14.

Nothing worked, I started a new minimal repo and was able to reproduce the issue there.

### How to reproduce

- Clone this repo: https://github.com/MarkLyck/next-auth-cookie-err-reproduction
- run `npm install`
- run `npm run build`

### Expected behavior

The cookie library imports should work.

**Comment by MarkLyck** [comment]
Switching to `pnpm` seems to be a possible workaround.

I was able to get past this error using `pnpm` but I'd be sad to give up using `bun` to be able to use `next-auth`

**Comment by balazsorban44** [comment]
https://unpkg.com/browse/cookie@0.6.0/index.js It looks like the `cookie` library correctly exports the mentioned methods. <picture data-single-emoji=":thinking:" title=":thinking:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/thinking/a89918a57b536d5b.gif" alt=":thinking:" align="absmiddle"></picture>

Given the provided reproduction, I get a successful build both using npm and Bun.

If you are still experiencing this issue, please reopen with an updated reproduction.

**Comment by MarkLyck** [comment]
@balazsorban44 I still have this issue. But it's most likely an issue with either Vercel or Bun, and not `next-auth` itself.

**Comment by MarkLyck** [comment]
I figured out what was causing the issue.

In Vercel I had an environment variable `NODE_PATH` set to `./`

I'm guessing there's an issue with Bun or Vercel that uses this differently than expected and caused the import errors in this ticket.

Removing the env variable from Vercel solved the issue.

**Comment by genki** [comment]
In Qwik, this issue occurs too.
![image](https://github.com/user-attachments/assets/8e7ab47d-7d1a-425c-94d6-67aa73081d2a)

**Comment by martin-jensen** [comment]
@genki did you find a solution to the issue in qwik ?

**Comment by ianlet** [comment]
@genki @martin-jensen in Qwik, you might have to update your vite config to bundle `cookie` properly:

```ts
// File: vite.config.ts

export default defineConfig(() => {
  return {
    // ...
    optimizeDeps: {
      include: ['cookie'],
    },
  };
});
```

Let me know if it helps so we can update the docs.

**Comment by vincehi** [comment]
> @genki @martin-jensendans Qwik, vous devrez peut-être mettre à jour votre configuration vite pour regrouper `cookie`correctement :
> 
> ```ts
> // File: vite.config.ts
> 
> export default defineConfig(() => {
>   return {
>     // ...
>     optimizeDeps: {
>       include: ['cookie'],
>     },
>   };
> });
> ```
> 
> Faites-moi savoir si cela aide afin que nous puissions mettre à jour la documentation.

This enabled me to get my solidStart

**Comment by martin-jensen** [comment]
@ianlet and @vincehi

Just started the project up again to test the solution, my time had been relocated to other projects. Uncommented the code causing the parse error, for some reason the error is gone, i am unsure if i might have updated something at some point. 

But none the less thank you, at least now i know if it should pop up again to try and add it to the optimizeDeps

**Comment by ianlet** [comment]
Thanks for following up! I'll check where we can add this in the docs and create a PR then.
