### ISSUE TITLE
Runtime error "Cannot read property 'event' of null" when testing with Cypress

### ISSUE THREAD

**Issue by HeikoMueller** [nextauthjs/next-auth#1125]
**Describe the bug**
When using NextAuth in conjunction with Cypress in next dev mode, occasionally an unhandled runtime error "TypeError: Cannot read property 'event' of null" shows up. 

**Steps to reproduce**
Run Cypress test with running local Next dev server (npm run dev). Sign in using Cypress ui handler with credentials on /api/auth/signin, then test protected api routes and/or protected pages. Tests are all passing, but in the visual representation of the UI, the error shows up, pointing to next-auth/dist/client/index.js 60:0 (see screenshot). This error is not thrown if Next has been started with next build / next start. 

**Expected behavior**
No error when running in dev mode. 

**Screenshots or error logs**

![Bildschirmfoto 2021-01-16 um 11 07 40](https://user-images.githubusercontent.com/2492274/104809350-f8066880-57ec-11eb-8ec1-35a3c4ad0902.png)

**Additional context**
node v14.15.1
npm 6.14.10
next: "10.0.1",
next-auth: "^3.1.0",
and for Cypress:
Cypress package version: 6.2.1
Cypress binary version: 6.2.1
Electron version: 11.1.1
Bundled Node version: 12.18.3

**Feedback**

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Hi there, it doesn't sound like a `next-auth` issue, rather something with your setup. Also, you had the same issue, which you closed and answered here: https://github.com/nextauthjs/next-auth/issues/1103#issuecomment-761538419 I assume this one has been opened with an accident or such. If not, do tell!

**Comment by HeikoMueller** [comment]
Hi @balazsorban44 , you are right, I had a similar issue before, which I handled with preserving the next-auth cookies in Cypress setup. However, this error warning here is slightly different. In the first one, message was missing. Here it is complaining that it cannot read property 'event' of null. This issue does not have a high impact, since tests are running. However, would be nicer if these warnings would not appear. It's possible that it is not directly a NextAuth issue, but it concerns the interplay between NextAuth, Cypress and NextJs dev mode. Maybe somehow related to re-build or re-rendering behavior in dev mode? 
If you say, it might be related to my setup, do you have a hint what I should look into?

**Comment by balazsorban44** [comment]
It would help if you showed your setup first. But on a side note, I haven't used Cypress for testing myself.

**Comment by HeikoMueller** [comment]
Sure. I have no public git repository though. The overall setup is as described under "context":

node v14.15.1
npm 6.14.10
next: "10.0.1",
next-auth: "^3.1.0",
and for Cypress:
Cypress package version: 6.2.1
Cypress binary version: 6.2.1
Electron version: 11.1.1
Bundled Node version: 12.18.3

My cypress.json looks like:

`{
    "baseUrl": "http://localhost:3000",
    "ignoreTestFiles": ["*.hot-update.js", "**/ignoredTestFiles/*.js"],
    "testFiles": [
        "rethinkdb/*.js",
        "stores/*.test.js"
    ],
    "viewportWidth": 1600,
    "viewportHeight": 800,
    "chromeWebSecurity": false
}
`
If you need more information, please let me know. 

What is strange here is that both errors point to the same line 47 in next-auth/dist/client/index.js 

`if (message.event && message.event === 'session' && message.data) {`

So, if I am not wrong, it is telling me again that message is null, but this time in another way than in the first issue. So, might be that preserving the cookies did not solve the actual problem as I thought it had, but the error message just changed for some reason...

**Comment by dmmulroy** [comment]
Also wanted to pop in and say that I'm also having this exact error. @HeikoMueller did you find any resolution this by chance?

**Comment by dmmulroy** [comment]
@balazsorban44 would you welcome a change updating 

`if (message.event && message.event === 'session' && message.data) {`

to

`if (message && message.event && message.event === 'session' && message.data) {`

Based on https://developer.mozilla.org/en-US/docs/Web/API/StorageEvent it reads as though `newValue` can sometimes be null/undefined when `clear is called.  This is likely occurring due to clean up before/after tests in cypress.

**Comment by HeikoMueller** [comment]
@dmmulroy  @balazsorban44 
Thanks !!
