### ISSUE TITLE
MongoDB adapter "Add the MongoDB client" is out of date from NextJS

### ISSUE THREAD

**Issue by nalenb** [nextauthjs/next-auth#11255]
### What is the improvement or update you wish to see?

On this adapter page [MongoDB Adapter](https://authjs.dev/getting-started/adapters/mongodb) the example code for connecting in NextJS is out of date. MongoDB team says not to cache the promise. NextJS has updated their [example documentation](https://github.com/vercel/next.js/blob/canary/examples/with-mongodb/lib/mongodb.ts )

### Is there any context that might help us understand?

[Response from MongoDB](https://github.com/mongodb-developer/nextjs-with-mongodb/pull/1)

[MongoDB Jira ticket](https://jira.mongodb.org/browse/NODE-6179)

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/adapters/mongodb

**Comment by odeta939** [comment]
This was updated in #11393, so the issue can be closed.

**Comment by balazsorban44** [comment]
Closing per above comment.
