### ISSUE TITLE
Discord invite is invalid

### ISSUE THREAD

**Issue by Skiuileuf** [nextauthjs/next-auth#11264]
### What is the improvement or update you wish to see?

The discord community link that's written in the documentation is invalid.

### Is there any context that might help us understand?

Links I've tried:
https://discord.com/invite/nwgKuTPJmj
https://discord.authjs.dev/

**Comment by k-taro56** [comment]
Hi,

Thank you for your cooperation.

I have created a new invitation link, please use this it.
https://discord.gg/V7X2RRxrKS

Thank you.

**Comment by k-taro56** [comment]
Duplicate of #11250

**Comment by balazsorban44** [comment]
discord.authjs.dev should be fixed now: https://github.com/nextauthjs/next-auth/discussions/11250#discussioncomment-9912740
