### ISSUE TITLE
"UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined" error when connecting to http://localhost:3000/api/auth/signin

### ISSUE THREAD

**Issue by sunrunner4kr-simon** [nextauthjs/next-auth#1126]
**Your question**
UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined when visiting http://localhost:3000/api/auth/signin

**What are you trying to do**
I'm trying to set up a simple user authentification with MongoDB following this tutorial - https://blog.logrocket.com/using-authentication-in-next-js/
Getting the below error when visiting http://localhost:3000/api/auth/signin

Similar to this issue - https://github.com/nextauthjs/next-auth/issues/636

I checked the filenaming and dir

![image](https://user-images.githubusercontent.com/58920692/104810576-7105c000-57ed-11eb-8485-396937d0dad2.png)

Full error below

Thanks in advance for any help!

(node:15228) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Users\simon.edge\PROJECTS\FromGrave\nexts-blog\node_modules\next-auth\dist\server\index.js:68:28
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\simon.edge\PROJECTS\FromGrave\nexts-blog\node_modules\next-auth\dist\server\index.js:48:103)
    at _next (C:\Users\simon.edge\PROJECTS\FromGrave\nexts-blog\node_modules\next-auth\dist\server\index.js:50:194)
    at C:\Users\simon.edge\PROJECTS\FromGrave\nexts-blog\node_modules\next-auth\dist\server\index.js:50:364
    at new Promise (<anonymous>)
    at C:\Users\simon.edge\PROJECTS\FromGrave\nexts-blog\node_modules\next-auth\dist\server\index.js:50:97
    at C:\Users\simon.edge\PROJECTS\FromGrave\nexts-blog\node_modules\next-auth\dist\server\index.js:342:22
    at new Promise (<anonymous>)
    at C:\Users\simon.edge\PROJECTS\FromGrave\nexts-blog\node_modules\next-auth\dist\server\index.js:58:12
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\simon.edge\PROJECTS\FromGrave\nexts-blog\node_modules\next-auth\dist\server\index.js:48:103)
    at _next (C:\Users\simon.edge\PROJECTS\FromGrave\nexts-blog\node_modules\next-auth\dist\server\index.js:50:194)
    at C:\Users\simon.edge\PROJECTS\FromGrave\nexts-blog\node_modules\next-auth\dist\server\index.js:50:364
    at new Promise (<anonymous>)
    at C:\Users\simon.edge\PROJECTS\FromGrave\nexts-blog\node_modules\next-auth\dist\server\index.js:50:97
(node:15228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)

**Reproduction**

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Hi there, could you maybe show us your `[...nextauth.js]` file?

**Comment by sunrunner4kr-simon** [comment]
Hey, here is its

![image](https://user-images.githubusercontent.com/58920692/104834565-2bea9800-5898-11eb-8afa-487725998a30.png)

**Comment by balazsorban44** [comment]
Could you please remove the site option?

Since 3.x, there is no need to pass it as an option:

https://next-auth.js.org/configuration/options#nextauth_url

just set the NEXTAUTH_URL correctly. What is the value of that env variable for you?

**Comment by sunrunner4kr-simon** [comment]
Thanks!
Removed that

![image](https://user-images.githubusercontent.com/58920692/104844754-ea72e080-58c9-11eb-944b-440a299841fb.png)

Here's my .env.local

![image](https://user-images.githubusercontent.com/58920692/104844738-d202c600-58c9-11eb-911b-e17566ba510c.png)

Still getting the same error

**Comment by balazsorban44** [comment]
is this only happening for the /api/auth/signin url, or any other will have the same issue, like /api/auth/session for example?

**Comment by sunrunner4kr-simon** [comment]
It's not happening on other pages, just /api/auth route. So I get the same error with /api/auth/session

**Comment by sunrunner4kr-simon** [comment]
I replaced what I had with the following example from the site: - https://next-auth.js.org/getting-started/example

I still get that same error

**Comment by balazsorban44** [comment]
then it's most certainly a configuration error somehow.

**Comment by sunrunner4kr-simon** [comment]
My package.json states 
![image](https://user-images.githubusercontent.com/58920692/105051360-95200600-5a66-11eb-996f-f31b18c51d36.png)

**Comment by sunrunner4kr-simon** [comment]
I've tried installing the latest version

**Comment by balazsorban44** [comment]
It's really hard to guess, without a proper reproduction. From the images and info you showed it should work just fine! Could you try to create a reproduction repository, or provide link to your project directly?

**Comment by sunrunner4kr-simon** [comment]
Yep - https://github.com/sunrunner4kr-simon/FromGrave
I've sent you an invite

Thanks

**Comment by balazsorban44** [comment]
You will be mad, but I found the issue... 😅 The filename was wrong!
Bad:  `[…nextauth].js `
Good: `[...nextauth].js`

The `…` character is not equal to three `.` characters, and therefore Next.js (so not actually `next-auth`) could not group the url path segments into an array, and that's why you got the above error.

Simply change `…` to `...` and it should work!

Additionally, remove `options={{ site: process.env.SITE }}` from `pages/_app.js`, it does nothing. Unfortunatelly the blog post you looked at seems to be outdated in certain things. 😕 If you have the opportunity to contact the autor, please send them to this issue, or tell them to contact us directly.

**Comment by sunrunner4kr-simon** [comment]
Ahhh, annoying!
Thank you for spending the time to help @balazsorban44 
It's always something stupid...right?!

**Comment by sunrunner4kr-simon** [comment]
FYI it's a brackets.io thing that caused it
![image](https://user-images.githubusercontent.com/58920692/105410985-b0d40980-5c2a-11eb-9861-18292ac48ba5.png)

**Comment by balazsorban44** [comment]
You will get used to it! 😅 Have a nice day! 🙌

**Comment by balazsorban44** [comment]
The image you show says the filename cannot END with dots, but the dots are not at the end of the filename anyway.

**Comment by sunrunner4kr-simon** [comment]
Yeah...but brackets then replaces the ... with … automatically.
I had to rename the file outside of brackets.io to get it to work

All working now! Thanks again
