### ISSUE TITLE
Dead link in v4 documentation 

### ISSUE THREAD

**Issue by erik-gullberg-devoteam** [nextauthjs/next-auth#11263]
### What is the improvement or update you wish to see?

The link https://next-auth.js.org/configuration/providers appears in multiple places in the v4 documentation and code comments.

The link leads to a 404 page.

I'd suggest replacing with https://next-auth.js.org/configuration/providers/oauth 

### Is there any context that might help us understand?

I found this while implementing next-auth, while reading the AuthOptions documentation

**Comment by balazsorban44** [comment]
https://providers.authjs.dev is probably an even better replacement. Want to PR? :pray:
