### ISSUE TITLE
typescript - How do I add custom type definitions to user in session

### ISSUE THREAD

**Issue by rasha-rahman123** [nextauthjs/next-auth#1127]
**Your question**

How do I add extra type definitions for user (name, email, image) in session?

**What are you trying to do**

In my [...nextAuth] file, I have a callback that adds the user Id to the session, so when I use [session] I can access the ID from session.user.id. The only problem is, typescript is giving me troubles because id is not a typed defined variable, so I cannot build unless I ts ignore. It does work when I add it to the node_modules index.d.ts file, but I cannot do that for production deployment.

**Reproduction**

I have tried adding my own typed file but it overwrites everything:
`declare module 'next-auth/client' {
    export interface User {
        name?: string | null;
        email?: string | null;
        image?: string | null;
        id?: number | null;
    }

}`

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Hi there! If you define your own types, I think you can just re-export everything and override only the parts you need to, and it should work. 😉
