### ISSUE TITLE
Session undefined upon initial login

### ISSUE THREAD

**Issue by Rykuno** [nextauthjs/next-auth#1130]
**Describe the bug**
Upon initial login with a provider, the session returned from `AppProps` within `_app.js` is undefined. Refreshing the page fixes the issue and causes the session to reflect its correct value. I'm also unsure if this is related to the issue but some providers append a `#` to the url subsequently removing the ability to perform `signout` right after login. 

**Steps to reproduce**
For the session being undefined upon initial login, simply log the session within `_app.js` upon login. 
```js
const App = ({ Component, pageProps, router }: AppProps) => {
  const { session } = pageProps;
  console.log("SESSION TOKEN -=> ", session?.token);
```

The "#" issue I believe can be replicated at the example site https://next-auth-example.now.sh/#. 
Attempt to logout right after logging in.

**Expected behavior**
The session is updated when a user is authenticated and its reflected in `_app.js`

**Additional context**
If anyone else is having this issue, I was able to solve it through utilizing `getInitialProps` and a redirect from within `useEffect` for the "#" issue. This is not an ideal solution as we lose Automatic Static Optimization through the use of `getInitialProps` but it currently solves my issue.
```js
const MyApp = ({ Component, pageProps, router, session }: AppProps) => {
  const apolloClient = useApollo(pageProps.initialApolloState, session?.token);
  
  useEffect(() => {
    if (router.asPath.endsWith("#")) router.push(router.pathname);
  });

  return (
    <>
      <Head>
        <link rel="shortcut icon" href="/images/favicon.ico" />
      </Head>
      <NextAuthProvider session={session}>
        <ApolloProvider client={apolloClient}>
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </ApolloProvider>
      </NextAuthProvider>
    </>
  );
};

MyApp.getInitialProps = async context => {
  const appProps = await App.getInitialProps(context);
  const session = await getSession(context);

  return {
    ...appProps,
    session
  };
};

export default MyApp;
``` 

I'm currently utilizing the latest release
```
    "next-auth": "^3.1.0",
```

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Hi there. I guess it is communicated badly on our side, but simply adding a `Provider` in the `_app` file won't magically add any session. The props provided to the `_app` component must come from somewhere. In this case, either from `getInitialProps` or `getServerSideProps`.

Eg.:

```js
// pages/index.js
import {getSession} from "next-auth/client"
...
export async function getServerSideProps(ctx) {
  const session = await getSession(ctx)
  return ({props: {session}})
}
...
```


This then will be available through `pageProps.session`, and this is the value you have to provide to the `Provider`.

Hope this helps.

**Comment by balazsorban44** [comment]
As the original question has been answered, I closed this issue. I am not aware of the second problem with that "#" problem, but if you do need further help with that, could you please separate it out into a different issue, desirably with a reproduction repository linked to it.

**Comment by Radmehr-aghdam** [comment]
I have this problem too!
we can login but session is undefined!

**Comment by balazsorban44** [comment]
Please open a new bug report with a reproduction.

**Comment by EugeneGohh** [comment]
I have the same problem too. After OAuth flow, I went on `console.log(session)`, I got `undefined`.

**Comment by balazsorban44** [comment]
Please open a new bug report with a reproduction.
