### ISSUE TITLE
Session not being persisted when I close the browser

### ISSUE THREAD

**Issue by pbteja1998** [nextauthjs/next-auth#1131]
Hi, Is there a way to persist the session? As soon as I close the browser, the user is being logged out. 

When I saw the cookies that are set, I see `Expires/Max-Age` value of `next-auth.session-token` set to `Session`. I am using the default configuration. By default, I assumed the max-age will be set to 30 days as per documentation. But that doesn't seem to be the case. Am I missing something?

**Comment by balazsorban44** [comment]
Hi there, could you create a reproduction for this, cause what you are saying does not hold up:
![image](https://user-images.githubusercontent.com/18369201/104824307-ddfe7180-5850-11eb-8e3f-97d1629eb34d.png)

The session token WILL by default expire in 30 days. In addition, any time the /api/auth/session endpoint is invoked, the session will be updated for to expire the next 30 days from the moment the session endpoint's response is received by the browser.

**Comment by pbteja1998** [comment]
@balazsorban44 
Hi, you can take a look at https://github.com/pbteja1998/nextjs-starter

<img width="924" alt="Screenshot 2021-01-17 at 4 07 43 AM" src="https://user-images.githubusercontent.com/17903466/104824651-a5bf5900-5879-11eb-94f7-16bf8457ad08.png">

This might be related to the new Fauna adapter that is in the works.

Here is my fauna adapter file - https://github.com/pbteja1998/nextjs-starter/blob/master/src/adapters/fauna/index.ts

Copied directly from https://github.com/nextauthjs/next-auth/pull/708

**Comment by balazsorban44** [comment]
Yeah, I guess it is some kind of calculation issue on the session age. I think the session age is somehow set to a lower value than the current date, in that case, the max-age will be set to `Session`. I would start debugging where this goes wrong.

**Comment by pbteja1998** [comment]
Where is this calculation being done? Is it in the fauna adapter file or in some other file in next-auth codebase?

**Comment by balazsorban44** [comment]
In the adapter, the one you just linked. I would check the `updateSession` function to begin with.

Also, here is the code being called when calling the `/api/auth/session` endpoint:

https://github.com/nextauthjs/next-auth/blob/78fd783bac990d8f2109487ac6598a38e3173f40/src/server/routes/session.js#L61-L94

As you can see, this should update the cookie expiry whenever session is accessed. In case the sessionToken was found but invalid though, the cookie will be removed. So I would also check the getSession function.

**Comment by pbteja1998** [comment]
Ok, thanks. Will try to debug. If you were able to figure it out before me, please update it here.

**Comment by pbteja1998** [comment]
Found it in the below line.
https://github.com/pbteja1998/nextjs-starter/blob/master/src/adapters/fauna/index.ts#L284

It should be `session.data.expires` not `session.expires`

**Comment by pbteja1998** [comment]
Changing it like above did not fix it.

**Comment by pbteja1998** [comment]
@balazsorban44 I was able to fix it. Thanks for pointing out the relevant code.

Here is the diff:
https://github.com/pbteja1998/nextjs-starter/commit/9d885ae5d88e443fe6d1a3e69ddcd6e99e6c9470

**Comment by balazsorban44** [comment]
Awesome!

**Comment by balazsorban44** [comment]
@ndom91 Should this be dealt with in the Fauna adapter we introduced in #708?

**Comment by pbteja1998** [comment]
> @ndom91 Should this be dealt with in the Fauna adapter we introduced in #708?

Tag me if necessary. I am happy to open up PR with these additions.

**Comment by ndom91** [comment]
@balazsorban44 yeah I'd say update that file in the fauna adapter. This only affects that adapter, right? 

Good work @pbteja1998

**Comment by balazsorban44** [comment]
As far as I know. (haven't tested other adapters). @pbteja1998 then we would be glad to accept a PR from you to fix this! 🙂

**Comment by pbteja1998** [comment]
I'm on it.

**Comment by pbteja1998** [comment]
@balazsorban44 Opened the PR at #1134
