### ISSUE TITLE
Explain how to populate Provider in _app

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#1132]
In the current version of the docs https://next-auth.js.org/getting-started/client#provider we do not explain how the `pageProps.session` prop is populated. It is not something that comes magically by `next-auth` as explained here: https://github.com/nextauthjs/next-auth/issues/1130#issuecomment-761689414

Simply adding a `Provider` in the `_app` with a `session={pageProps.session}` file won't magically add any session. The props provided to the `_app` component must come from somewhere. In this case, either from `getInitialProps` or `getServerSideProps`. Do note that this does not have to be in the `_app` file, so you don't necessarily opt-out of any Next.js optimization. Add it only to those pages that need auth.

Eg.:

```js
// pages/index.js
import {getSession} from "next-auth/client"
...
export async function getServerSideProps(ctx) {
  return {
    props: {
      session: await getSession(ctx)
    }
  }
}
...
```

This then will be available through `pageProps.session`, and this is the value you have to provide to the `Provider`. Thanks to this, any subsequent `useSession()` hook calls will only get the client-cached session value, instead of re-visiting the backend. You can configure how long you want to cache the session before getting the new one from the backend. Documented here: https://next-auth.js.org/getting-started/client#options

It would be nice to incorporate this into the docs, to avoid further confusion.

**Comment by kriscarle** [comment]
Hi, I just wanted to leave a note that the example in the NextJS repo appears to implement this incorrectly too? https://github.com/vercel/next.js/tree/canary/examples/with-next-auth

**Comment by balazsorban44** [comment]
Absolutely, many projects does that, and I think it is easier for us to manage a single example, instead of two, where one is even in another repo.

But we definitely must add this to our docs as well, I'm glad that at least our example project does it correctly 😅:

https://github.com/nextauthjs/next-auth-example/blob/918ef6de41b56840ac4a7c4e95f542c06a6a135d/pages/server.js#L35

**Comment by jeremyhaile** [comment]
Where does this come from in Next.JS 13 with appDir?
