### ISSUE TITLE
All login attempts on a Firebase server end at http://localhost:3000/api/auth/signin/:provider

### ISSUE THREAD

**Issue by eliooses-zondax** [nextauthjs/next-auth#1133]
**Describe the bug**
All login attempts on a Firebase server end at `http://localhost:3000/api/auth/signin/:provider`

**Steps to reproduce**
1. Download the Next Auth Example: https://github.com/nextauthjs/next-auth-example
2. Put the code into a Firebase ready to deploy project (good luck with that)
3. Predeploy & Deploy to Firebase
4. Visit page
5. Try to login with any provider

**Expected behavior**
Successful login!

**Screenshots or error logs**
![image](https://user-images.githubusercontent.com/74009760/104827502-0e3c1500-583d-11eb-8c9c-72d914c4cd92.png)

**Additional context**
I just upload a REPO for reproduction: https://github.com/eliooses-zondax/nextauth-repo-for-issue

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [X] Could not find relevant documentation
* [ ] Found the example project helpful
* [X] Did not find the example project helpful

**Comment by eliooses-zondax** [comment]
Any help, workaround, patch or idea that can be done to solve this problem will be appreciated and if the media allows it, rewarded with a beer or coffe.

**Comment by balazsorban44** [comment]
So the /api/auth/signin/<provider>

endpoint only accepts POST requests, with a CSRF token in place in the request. see the docs:

https://next-auth.js.org/getting-started/rest-api#post-apiauthsigninprovider

You can go to /api/auth/signin to get a list of  providers to log in with one of them, or you can use the client side method `signIn` that properly sets the CSFR token for you. See the docs:

https://next-auth.js.org/getting-started/client#signin

**Comment by eliooses-zondax** [comment]
Hi @balazsorban44 thanks for the reply.

I tried that and many others things, but making `signIn("github")` the result is this error:

`https://github.com/login/oauth/authorize?redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fauth%2Fcallback%2Fgithub&scope=user&state=798aba0b20c573bcdcfa0e6d06a46e006d02c6cd85f42e26f5b96139b4ab4933&client_id=`

And in the case of making `signIn("google")` the result is this error:

`https://accounts.google.com/signin/oauth/error?authError=Cg9pbnZhbGlkX3JlcXVlc3QSJU1pc3NpbmcgcmVxdWlyZWQgcGFyYW1ldGVyOiBjbGllbnRfaWQaNWh0dHA6Ly9jb2RlLmdvb2dsZS5jb20vYXBpcy9hY2NvdW50cy9kb2NzL09BdXRoMi5odG1sIJAD&client_id`

If you notice, in the GitHub URL, `localhost` persists for some reason, when it is not present in any variable of my code.

On the other hand, if all the logic to use CSFR is necessary, why or where is it included in the sample code?

**Comment by eliooses-zondax** [comment]
I have tried more than 15 examples, all with different implementations, most of them work perfectly locally and in development mode and I can log in. 

But in all, without exception, once deployed in Firebase it ends up with the same error.

I can understand that this is a Firebase problem and not NextAuth, but what can it be?

I have thought that the problem may be in the environment variables used in the providers, I do not know, maybe they are not accessible or I do not know, but I have tried in all cases to use Firebase Functions and the result is the same.

So there are three possibilities left:

1. It is a NextAuth bug
2. It is a NextAuth bug with Firebase
3. It is a Firebase bug

**Comment by balazsorban44** [comment]
Please, make sure you have set the NEXTAUTH_URL correctly, and you configured the callback url in your Google and github apps.

**Comment by eliooses-zondax** [comment]
> Please, make sure you have set the NEXTAUTH_URL correctly, and you configured the callback url in your Google and github apps.

This is OK in my code and set.

In the other hand, if the signIn function already performs the CSRF implementation, then I insist with my previous three alternatives.

I will try to deploy the App in another environment and thus rule out that it is a problem between NextAuth and Firebase.

Otherwise, I kindly ask you to re-tag the issue as a bug. Or simply that you refer me to some starter or example or open project that has made a successful implementation of NextAuth in Firebase.

**Comment by eliooses-zondax** [comment]
From @iaincollins on https://github.com/nextauthjs/next-auth/issues/497#issuecomment-664995695:

> In the case of Vercel, it actually reads in the instance name of VERCEL_URL as a fallback if NEXTAUTH_URL is not set (and, as that has no protocol, assumes HTTPS, which it always is on Vercel). If neither environment variable is set it assumes http://localhost:3000 for the hostname. If no base path for the auth routes is specified, it uses /api/auth as the default. This makes it really easy for folks to get started and try things out.

I really believe this is happening. My code is the following:

```
import NextAuth from 'next-auth'
import Providers from 'next-auth/providers'

const options = {
  site: process.env.NEXTAUTH_URL,
  providers: [
    Providers.GitHub({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET
    }),
    Providers.Google({
      clientId: process.env.GOOGLE_ID,
      clientSecret: process.env.GOOGLE_SECRET
    })
  ],
}

export default (req, res) => NextAuth(req, res, options)
```

Is it possible that the NEXTAUTH_URL is not being set correctly or in the opposite case that Firebase does not deliver the environment variable correctly?

**Comment by eliooses-zondax** [comment]
To rule out that it is a problem with reading the environment variables, I have just included the variables as strings:

`/pages/api/auth\[...nextauth].js`:

```
import NextAuth from 'next-auth'
import Providers from 'next-auth/providers'

const options = {
  // site: process.env.NEXTAUTH_URL,
  site: 'https://zx-next.web.app',
  providers: [
    Providers.GitHub({
      clientId: '52d57dc41423a8d462e9',
      clientSecret: 'efa2c4c752a611e5bcd1cfb733052080f20f0a9a'
    }),
    Providers.Google({
      clientId: '132461042521-pbopsfi2ub7spaokl82e757ttolgun4n.apps.googleusercontent.com',
      clientSecret: 'IWxew6qMRWi6i9Twy9Qyg8H9'
    })
  ],
}

export default (req, res) => NextAuth(req, res, options)
```

With the same bad result. I am really infuriated with this situation.

**Comment by eliooses-zondax** [comment]
To rule out that it is a problem with reading the environment variables, I have just included the variables as strings:

`/pages/api/auth\[...nextauth].js:`

```
import NextAuth from 'next-auth'
import Providers from 'next-auth/providers'

const options = {
  // site: process.env.NEXTAUTH_URL,
  site: 'https://xx-xxxx.web.app',
  providers: [
    Providers.GitHub({
      clientId: '52xxxxxxxxxxxe9',
      clientSecret: 'efxxxxxxxxxxxxxxxxx9a'
    }),
    Providers.Google({
      clientId: '13xxxxxxxxxxxxxxxx.apps.googleusercontent.com',
      clientSecret: 'IWxewxxxxxxxxxxxxxxxx8H9'
    })
  ],
}

export default (req, res) => NextAuth(req, res, options)
```

With the same bad result. I am really infuriated with this situation.

**Comment by eliooses-zondax** [comment]
Just FYI:

One of the many things I have tried was exposing environment variables to the browser according to the official documentation:

https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser

`.env`

```bash
NEXT_PUBLIC_NEXTAUTH_URL="https://xx-xxxx.web.app"
NEXT_PUBLIC_GITHUB_ID="52xxxxxxxxxxxxe9"
NEXT_PUBLIC_GITHUB_SECRET="a3xxxxxxxxxxxxxxxxxxxxxxxx70"
NEXT_PUBLIC_GOOGLE_ID="13xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxom"
NEXT_PUBLIC_GOOGLE_SECRET="IWxxxxxxxxxxxxxxxxxxxxxxxxxxH9"
```

`/pages/api/auth\[...nextauth].js:`

```js
import NextAuth from 'next-auth'
import Providers from 'next-auth/providers'

const options = {
  site: process.env.NEXT_PUBLIC_NEXTAUTH_URL,
  providers: [
    Providers.GitHub({
      clientId: process.env.NEXT_PUBLIC_GITHUB_ID,
      clientSecret: process.env.NEXT_PUBLIC_GITHUB_SECRET,
    }),
    Providers.Google({
      clientId: process.env.NEXT_PUBLIC_GOOGLE_ID,
      clientSecret: process.env.NEXT_PUBLIC_GOOGLE_SECRET,
    }),
  ],
}

export default (req, res) => NextAuth(req, res, options)
```

The results was the this same issues previously reported: https://github.com/nextauthjs/next-auth/issues/1133#issuecomment-761896888

But!, changing the settings to:

`.env`

```bash
NEXTAUTH_URL="https://zx-next.web.app"
NEXT_PUBLIC_GITHUB_ID="52d57dc41423a8d462e9"
NEXT_PUBLIC_GITHUB_SECRET="a3528a5d99fe03ac333b839afe5300009f004170"
NEXT_PUBLIC_GOOGLE_ID="132461042521-pbopsfi2ub7spaokl82e757ttolgun4n.apps.googleusercontent.com"
NEXT_PUBLIC_GOOGLE_SECRET="IWxew6qMRWi6i9Twy9Qyg8H9"
```
`/pages/api/auth\[...nextauth].js:`

```js
import NextAuth from 'next-auth'
import Providers from 'next-auth/providers'

const options = {
  providers: [
    Providers.GitHub({
      clientId: process.env.NEXT_PUBLIC_GITHUB_ID,
      clientSecret: process.env.NEXT_PUBLIC_GITHUB_SECRET,
    }),
    Providers.Google({
      clientId: process.env.NEXT_PUBLIC_GOOGLE_ID,
      clientSecret: process.env.NEXT_PUBLIC_GOOGLE_SECRET,
    }),
  ],
}

export default (req, res) => NextAuth(req, res, options)
```

The result is different:

![image](https://user-images.githubusercontent.com/74009760/104986568-083b6500-59f2-11eb-9eb8-0bbe811b20a5.png)

```
502. That’s an error.

The server encountered a temporary error and could not complete your request.

Please try again in 30 seconds. That’s all we know.
```

**Comment by eliooses-zondax** [comment]
I just deployed the same code in Vercel and its working like a charm. OK.

 ̷1̷.̷ ̷I̷t̷ ̷i̷s̷ ̷a̷ ̷N̷e̷x̷t̷A̷u̷t̷h̷ ̷b̷u̷g̷
2. It is a NextAuth bug with Firebase
3. It is a Firebase bug

**Comment by balazsorban44** [comment]
Please read the documentation carefully:

https://next-auth.js.org/configuration/options

The variable name MUST BE `NEXTAUTH_URL`. Nothing else is accepted.

You also don't have to use the `site` property anymore. Simply setting the env variable correctly should work.

VERCEL_URL is just a fallback, in case you don't set the NEXTAUTH_URL variable. But you shouldn't rely in it, rather be explicit and set it.

Try logging out this variable so you can see in the logs that it is correctly set.
