### ISSUE TITLE
Dynamically adding query parameters to the Google authorization URL (e.g. the hd param)

### ISSUE THREAD

**Issue by alexbudure** [nextauthjs/next-auth#1141]
**Summary of proposed feature**
Dynamically adding query parameters to the Google authorization URL using the `signIn` method

**Purpose of proposed feature**
I have a sign-in page that's just an email input and sign-in button. Once the user fills out their email and clicks sign-in, I'd like to be able to give them a better experience by providing them a more concise Google prompt through the [hd param](https://developers.google.com/identity/protocols/oauth2/openid-connect#hd-param) since I know their email domain from the input. Ideally, it'd look something like: `signIn('google', { params: { hd: 'example.com' } } )`.

I'm willing to work on this :)

**Comment by balazsorban44** [comment]
This has been in the canary release before, and because of popular request, may come back in anither canary release soon: https://github.com/nextauthjs/next-auth/pull/823

**Comment by alexbudure** [comment]
@balazsorban44 That landed in canary 🎉 however, I noticed the params passed need to adhere to a specific spec. Is there a way to just dynamically add a query to the authorization URL? `https://accounts.google.com/o/oauth2/auth?response_type=code<lots of stuff here>&hd=example.com`?

**Comment by balazsorban44** [comment]
Check the third argument of the signIn function:

https://next-auth-git-canary.nextauthjs.vercel.app/getting-started/client#additional-params

**Comment by alexbudure** [comment]
That's what I've tried but had no luck:

```typescript
signIn('google', null, { hd: 'example.com' })
```

I thought maybe only params in the [OpenID spec](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) get passed through

**Comment by balazsorban44** [comment]
odd. could you add `debug: true` and look for `GET_AUTHIRIZATION_URL` in the terminal?

**Comment by alexbudure** [comment]
Here's what I get:

`"https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&response_type=code&prompt=consent&0=%5B&1=o&2=b&3=j&4=e&5=c&6=t&7= &8=O&9=b&10=j&11=e&12=c&13=t&14=%5D&redirect_uri=http://localhost:3000/api/auth/callback/google&scope=https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/admin.directory.user.readonly https://www.googleapis.com/auth/user.organization.read&state=<state>&client_id=<client_id>"`

Here's my next-auth provider config:

```typescript
const DEFAULT_PROVIDERS = [
  Providers.Google({
    clientId: process.env.NEXTAUTH_GOOGLE_CLIENT_ID as string,
    clientSecret: process.env.NEXTAUTH_GOOGLE_CLIENT_SECRET as string,
    authorizationUrl:
      'https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&response_type=code&prompt=consent',
    scope:
      'https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/admin.directory.user.readonly https://www.googleapis.com/auth/user.organization.read',
  }),
];
```

**Comment by balazsorban44** [comment]
@alexbudure I made some small changes that might affect this in a positive way. Could you check if canary.36 fixed the issue? I found a bug in forwarding the params from the signIn function, and fixed those. I tested it with a provider locally and everything in the third argument of signIn will now be forwarded properly.

**Comment by alexbudure** [comment]
Works! Thank you 🙌
