### ISSUE TITLE
Nextjs Client email signIn() function doesn't work in custom page

### ISSUE THREAD

**Issue by RahulBirCodes** [nextauthjs/next-auth#11438]
### Environment

```
System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 10.43 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - /opt/homebrew/bin/npm
    pnpm: 9.5.0 - ~/Library/pnpm/pnpm
  Browsers:
    Brave Browser: 115.1.56.20
    Chrome: 126.0.6478.183
    Safari: 17.4.1
    Safari Technology Preview: 17.4
  npmPackages:
    @auth/prisma-adapter: ^2.4.1 => 2.4.1 
    next: 14.2.5 => 14.2.5 
    next-auth: ^5.0.0-beta.19 => 5.0.0-beta.19 
    react: ^18 => 18.3.1 
```

### Reproduction URL

https://github.com/RahulBirCodes/authjs-bug

### Describe the issue

Recently started migrating a project from pages router to app router and upgraded from v4 to v5. However, I just can't get the email login to work. I tried doing it from scratch and it works when I use the default authjs pages but the moment I add a custom page it won't work. I kept the sign-in page as a client component and use the client version of signIn() which is a requirement for our project (though I keep getting csrf errors if I try with server) and when I click login the loading state appears and just turns off with nothing happening. Im getting 302 codes from api/auth/signin and even with debug turned on I'm getting nothing. This is a huge blocker and I'd like to stay with NextAuth. Any help with this is very appreciated!

### How to reproduce

Route /feed is protected. Go to localhost:3000/feed and it will redirect to login page. Attempt logging in.

### Expected behavior

Authentication should work normally.

**Comment by DinerIsmail** [comment]
Hey @RahulBirCodes, funnily I think had the exact same issue this evening. From looking at your repo, it looks like you need to add `id: 'email'` to the Sendgrid provider, like below. That's how signIn('email'...) will be linked to the right provider.
 
![CleanShot 2024-07-24 at 00 19 02](https://github.com/user-attachments/assets/99cd2b63-033d-4342-a2ba-a15dee4f81c1)

**Comment by RahulBirCodes** [comment]
@DinerIsmail That was it!!!!!! I thought I was going crazy lol I didn't even think about that.
