### ISSUE TITLE
MISSING_NEXTAUTH_API_ROUTE_ERROR

### ISSUE THREAD

**Issue by dhruvkaushik305** [nextauthjs/next-auth#11445]
### Environment

```
  System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 5.18 GB / 7.41 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.15.1/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
    pnpm: 9.6.0 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 126.0.6478.182
```

### Reproduction URL

https://github.com/dhruvkaushik305/Finify/tree/dev

### Describe the issue

The issue is that i am facing the MISSING_NEXTAUTH_API_ROUTE_ERROR. I have tried writing a simple GET function that returns a json response and it is working which means that the catch all routes work

### How to reproduce

on the / page, hit the login button which runs the signin function

### Expected behavior

it should open the signin page

**Comment by balazsorban44** [comment]
This is not a bug, you have empty spaces in the catch-all route path:
![image](https://github.com/user-attachments/assets/c0d8cc63-d1b2-4f25-a3d8-442b055aa8d8)

See the URL below, note the `%20`: https://github.com/dhruvkaushik305/Finify/tree/dev/app/api/auth/%5B%20.%20.%20.%20nextauth%5D

Ref: https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes#catch-all-segments

**Comment by dhruvkaushik305** [comment]
yeah that worked, i had seen some previous similar questions where you said to add spaces, that is why i tried that. anyways, thanks mate!
