### ISSUE TITLE
AUTH_TRUST_HOST doesn't support explicit false values to disable

### ISSUE THREAD

**Issue by veda-tschoening** [nextauthjs/next-auth#11452]
### What is the improvement or update you wish to see?

The docs contain the following:

> The AUTH_TRUST_HOST environment variable serves the same purpose as setting trustHost: true in your Auth.js configuration. This is necessary when running Auth.js behind a proxy. When set to true we will trust the X-Forwarded-Host and X-Forwarded-Proto headers passed to the app by the proxy to auto-detect the host URL (AUTH_URL)

https://authjs.dev/getting-started/migrating-to-v5

While setting the environment variable to `true` works as documented, setting it e.g. to `false` doesn't, because the that string string evaulates to `true` in the actual implementation:

```
export function detectOrigin(forwardedHost: any, protocol: any) {
  // If we detect a Vercel environment, we can trust the host
  if (process.env.VERCEL ?? process.env.AUTH_TRUST_HOST)
    return `${protocol === "http" ? "http" : "https"}://${forwardedHost}`

  // If `NEXTAUTH_URL` is `undefined` we fall back to "http://localhost:3000"
  return process.env.NEXTAUTH_URL
}
```

So when `true` is mentioned, at least I instantly think of `false` being supported as well, which is not the case. Instead the value needs to be removed. Additionally, [there are some threads where people set e.g. some URL](https://github.com/nextauthjs/next-auth/issues/8327) as value, because that string evaluates to `true` as well. While that is unnecessary, when seeing such examples, it's easier to think of emptying the value to disable something, because there's no "opposite" of a configured URL.

### Is there any context that might help us understand?

My projects contain all important config keys with default values. I need `AUTH_TRUST_HOST` in some environments, so it's available in the default config file. And because I saw `true` mentioned in different places and explicitly mentioned that URLs don't need to be configured because boolean etc., my default value looked like the following:

> AUTH_TRUST_HOST=false

And that simply doesn't work as expected, broke in one of my environments and was difficult to debug. So it would be great if the docs could be more clear or simply the implementation more flexible and consider `false` a falsy value.

Thanks!

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/migrating-to-v5

**Comment by balazsorban44** [comment]
Hi, this is unrelated to Auth.js, this is just how environment variables (more specifically `dotenv` used by Next.js) work. They can only be strings, and strings are always truthy, except the empty string `''`.

You have three options:
1. `AUTH_TRUST_HOST=`
2. `AUTH_TRUST_HOST=''`
3. set `trustHost: process.env.AUTH_TRUST_PROXY !== 'false'` in your [auth config](https://authjs.dev/reference/nextjs#trusthost)

Ref: https://www.npmjs.com/package/dotenv#what-rules-does-the-parsing-engine-follow

I rather skip parsing this value in our code base or add specific notes on how dotenv works, but happy to accept a PR for parsing it in our codebase, if you have strong opinions. Technically this would also be a breaking change, but hopefully nobody setting "false" would do it to disable this value. Note, if you end up opening a PR, you probably would want to handle "0" as `false` as well.

Source code: https://github.com/nextauthjs/next-auth/blob/aef630d47fdf3da229e193059304d8e48a146c26/packages/core/src/lib/utils/env.ts#L29
