### ISSUE TITLE
Remove FaunaDB

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#1146]
As we have started working on getting a stable release out, we have to be careful we don't add too much overhead to the package in the process. FaunaDB was never something the original author intended to add as a builtin adapter, and we even discussed ways of separating current adapters into their own packages as well.

As such, we should remove the Fauna DB adapter for now.

If someone needs it, it can still be implemented with the custom adapter option.

@pbteja1998 had a good go at it:
https://github.com/nextauthjs/next-auth/issues/1131#issuecomment-761691464

**Comment by pbteja1998** [comment]
Once I review the code that the original author has written, I would create it as a separate package. Since I am using it in my projects, I would make sure to maintain it. 

Will update here when I make it into a separate package.

Meanwhile, if anyone is interested, you can checkout https://github.com/pbteja1998/nextjs-starter repo to get an idea of how to use it.

**Comment by ndom91** [comment]
Yeah I agree, especially for getting out a stable release with the tons of other features / PRs that have been merged recently. This makes sense.

**Comment by iaincollins** [comment]
@balazsorban44 Thanks for the update! 

@pbteja1998 hank you for the work on this adapter!

I'm sorry we don't have the ability to support them as first-party / part of core right now - I just feel we are stretched and wouldn't do a good job of maintaining or testing it.

I would welcome pull requests to update the documentation to link out to it (and to any other third party maintained adapters), so we can let folks know where to find them.

Should folks like to create repos inside next-auth GitHub org where they could be managed (and/or published from an NPM org if we ever get around do doing that) so they could be more official without being part of the core package, I think that's something we could facilitate.

To confirm this isn't about not liking Fauna! :-) Ultimately, it seems like the direction is likely that we will have no adapter code in core (or possibly one small and general purpose adapter) to reduce the size of core, but we are little way out from doing that right now - and there are tradeoffs for module size / user experience to compare.

We have two adapters right now (TypeORM and Prisma) but we are trying not to add more to core as while the current size is manageable ideally could be smaller - and keeping it small might become more important if we start looking at other libraries (e.g. to support Open ID connect features) as that might require us to bring in more dependencies.

**Comment by pbteja1998** [comment]
@iaincollins 
Yes, I think that would be better — to create a repo inside `next-auth` GitHub org.

**Comment by balazsorban44** [comment]
@pbteja1998 I created a private repo and added you with write access, in case you would like to add your Fauna DB adapter to start with.

What do you think about the package naming `@next-auth/adapters`? Where each adapter is an independent module, so you could import FaunaDB through
```js
import FaunaAdapter from @next-auth/adapters/fauna
```

Or should we even publish adapters as individual packages?

```js
import FaunaAdapter from @next-auth/fauna-adapter
```
