### ISSUE TITLE
[Mobile]: search results overlapping

### ISSUE THREAD

**Issue by Jay-Karia** [nextauthjs/next-auth#11478]
### What is the improvement or update you wish to see?

In the mobile, I am unable to read search results as they are overlaping with the Navbar items.

### Is there any context that might help us understand?

![Screenshot_20240727_214728_Chrome](https://github.com/user-attachments/assets/ff992135-aa87-443d-9d29-ca2ba2bf3510)

### Does the docs page already exist? Please link to it.

https://authjs.dev/

**Comment by krakenftw** [comment]
is there a way to make search work in local development? since its using external algolia search, i am having issues with even getting the search results.
