### ISSUE TITLE
docs: black and white logos

### ISSUE THREAD

**Issue by Jay-Karia** [nextauthjs/next-auth#11477]
### What is the improvement or update you wish to see?

It would be better to add colors to logos like Svelt and Qwik in the home page below Example Apps

### Is there any context that might help us understand?

![Screenshot_20240727_214303_Chrome](https://github.com/user-attachments/assets/12f1a8e9-3eb9-43a9-b42b-fa6e1f16191d)

### Does the docs page already exist? Please link to it.

https://authjs.dev/

**Comment by balazsorban44** [comment]
Stylistic choice, they are colored when you hover over them.
