### ISSUE TITLE
docs: no syntax higlighting

### ISSUE THREAD

**Issue by Jay-Karia** [nextauthjs/next-auth#11476]
### What is the improvement or update you wish to see?

Update the home page by adding syntax highlighting to the code examples

### Is there any context that might help us understand?

![Screenshot_20240727_212921_Chrome](https://github.com/user-attachments/assets/cb674708-cab6-4d0e-a65a-8fa7f89431f1)

### Does the docs page already exist? Please link to it.

https://authjs.dev/

**Comment by balazsorban44** [comment]
Hi, this was part of a refactor. I think this is a stylistic debate. If someone fixes this I don't mind, but I kinda prefer the simpler look on our landing page.

**Comment by Jay-Karia** [comment]
Hi, maybe I can work on this issue.
Will send a pull. 🙂
