### ISSUE TITLE
Feature: Include Forward Email @forwardemail as a recommended email provider

### ISSUE THREAD

**Issue by titanism** [nextauthjs/next-auth#11491]
### What is the improvement or update you wish to see?

The docs at <https://authjs.dev/getting-started/providers/nodemailer> and <https://authjs.dev/guides/configuring-http-email> fail to include @forwardemail, which is the **only** 100% open source email service that is privacy and security focused.

It offers all the features as the others do, and it also has IMAP, POP3, and CalDAV, which pretty much nobody else offers.

The API is extensive and you can even generate mailboxes using the API too (e.g. for storing mail).

See https://forwardemail.net and https://forwardemail.net/api

### Is there any context that might help us understand?

See above

**Comment by balazsorban44** [comment]
Sorry about that, it might have happened during our full documentation rewrite. Care to open a new PR? :pray:

**Comment by balazsorban44** [comment]
Auth.js has no opinion on which provider you chose.

Most of the OAuth Providers we support are closed-source as well.

I understand your concern, and really appreciate the open-source mentality. I don't think we would like to replace Resend, but we certainly are not "gearing towards" it. Can you explain why do you feel this being the case? I think one thing people like with Resend is the ease of setup, compared to a `nodemailer` alternative. `nodemailer` also does not work in Edge runtimes which is tecnhincally not an Auth.js issue, but we are so often targeted that we had to write a special page explaining it: https://authjs.dev/guides/edge-compatibility

I think we should definitely add a new `ForwardEmail` provider though! :green_heart: Do you know if it is actively maintained? the [related npm package](https://www.npmjs.com/package/forward-email) hasn't received updates in 2 years.

Or how could you envision an ideal setup with it?

**Comment by balazsorban44** [comment]
Adding an HTTP-based version of your email provider makes sense then!
