### ISSUE TITLE
account callback is not available with Google

### ISSUE THREAD

**Issue by tiendq** [nextauthjs/next-auth#11498]
### What is the improvement or update you wish to see?

It needs to be mentioned here https://authjs.dev/getting-started/migrating-to-v5#main-changes or https://authjs.dev/reference/core/providers#account

### Is there any context that might help us understand?

This [example](https://authjs.dev/reference/core/providers#example) has no effect with Google provider, `account` received in `signIn`, `jwt`... is still same original one, not the `account()` return.

### Does the docs page already exist? Please link to it.

https://authjs.dev/reference/core/providers

**Comment by balazsorban44** [comment]
The account callback affects what is saved in the database as per [docs](https://authjs.dev/reference/core/providers#account):

>  It is used to create the account associated with a user in the database.

It does _not_ change what `signIn` and `jwt` receives.
