### ISSUE TITLE
Grammatical erorr

### ISSUE THREAD

**Issue by Jay-Karia** [nextauthjs/next-auth#11509]
### What is the improvement or update you wish to see?

Found a grammatical error in https://next-auth.js.org/contributors under the `"Notes"` section.

### Is there any context that might help us understand?

![Screenshot_20240803_230541_Chrome](https://github.com/user-attachments/assets/941586ab-1639-4530-9b32-52674b589cb2)

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/contributors

Fixed by #11465

**Comment by balazsorban44** [comment]
Thanks!
