### ISSUE TITLE
Cookie policy for using NextAuth inside iframe

### ISSUE THREAD

**Issue by bdesouza** [nextauthjs/next-auth#1151]
**Your question**
I've noticed that the cookie isn't being set when embedded in a page via an iframe. 

**What are you trying to do**
I'd like to embed the app using NextAuth in an iframe in a partner's website. Example: `a.com` has an iframe that references our website (`b.com`). I would like the users who visit `a.com` to be able to login.

**Reproduction**
Go to https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe
Link any next-auth app in the iframe URL and attempt to login.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Hi there! For increased security, all our cookies are same site only by default:

https://github.com/nextauthjs/next-auth/blob/canary/src/server/lib/cookie.js#L114-L147

You can override this as documented here:

https://next-auth.js.org/configuration/options#cookies

Please do it at your own risk!

**Comment by pankaj9296** [comment]
@balazsorban44 
How about social login? Can we make it work in an iframe?
Maybe using signInWithPopup option, just like firebase does.

**Comment by unsphere** [comment]
Added fully working example: #1585

**Comment by unsphere** [comment]
> @balazsorban44
> How about social login? Can we make it work in an iframe?
> Maybe using signInWithPopup option, just like firebase does.

Added fully working example: #1585

**Comment by balazsorban44** [comment]
So as I don't think this is easy to solve in a fully secure way that we could advise our users to do, I am going to close this for now. @unsphere provided a good solution that can be implemented in user land. We may revisit this in the future.
