### ISSUE TITLE
AUTH_URL gives [auth][warn][env-url-basepath-redundant]

### ISSUE THREAD

**Issue by fabpico** [nextauthjs/next-auth#11522]
### Environment

```
  System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 14.16 GB / 15.47 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 9.4.0 - ~/.nvm/versions/node/v18.18.2/bin/pnpm
  npmPackages:
    next: 14.2.5 => 14.2.5 
    next-auth: ^5.0.0-beta.19 => 5.0.0-beta.19 
    react: ^18 => 18.3.1 
```

### Reproduction URL

https://github.com/fabpico/next-auth-basepath-redundant

### Describe the issue

The issue is already mentioned here https://github.com/nextauthjs/next-auth/discussions/10429 .

I require to customize the AUTH_URL.  
As soon as I define `AUTH_URL="http://localhost:3000/auth"` in `.env.local` and start the devserver, the warning appears in the devserver log.

The reproduction project shows 1 warning. As the project grows, the warning comes multiple times and worsens the overview of the log.

Full `.env.local`:
````
AUTH_SECRET="xx"
AUTH_KEYCLOAK_ID="xx"
AUTH_KEYCLOAK_SECRET="xx"
AUTH_KEYCLOAK_ISSUER="http://localhost:8100/realms/foo"
AUTH_URL="http://localhost:3000/auth"
````

### How to reproduce

1. Clone reproduction project `git clone git@github.com:fabpico/next-auth-basepath-redundant.git`
2. Install `npm install`
3. Copy following to `.env.local`:
````
AUTH_SECRET="xx"
AUTH_KEYCLOAK_ID="xx"
AUTH_KEYCLOAK_SECRET="xx"
AUTH_KEYCLOAK_ISSUER="http://localhost:8100/realms/foo"
AUTH_URL="http://localhost:3000/auth"
````
4. Run project `npm run dev`
5. Open http://localhost:3000/
6. Look devserver log
![image](https://github.com/user-attachments/assets/ef46d7a6-a78a-4d21-81fa-8b42843b1cd6)

### Expected behavior

The warning should not appear when cusotmizing AUTH_URL.

**Comment by shakedhagag** [comment]
I also experience the same issue. I dont have the basePath configured in the auth config object.

- No basePath configured in auth config
 - Locally: Works fine without AUTH_URL in .env.local, no warning
- Production:

    -     Without AUTH_URL: Redirects to 0.0.0.0
    -     With AUTH_URL: Auth works, but warning persists
    -     Need AUTH_URL in prod env for auth to function, despite warning

**Comment by k-taro56** [comment]
We are currently working on a fix for this issue. If your config is correct, you can safely ignore it.

**Comment by angelgbi** [comment]
is this fix available? @k-taro56 @ThangHuuVu

**Comment by brothatru** [comment]
Same still waiting on this one
