### ISSUE TITLE
my own api with jwt

### ISSUE THREAD

**Issue by itxtoledo** [nextauthjs/next-auth#1152]
I already have a JWT generation system in my own api, but the next-auth insists on trying to transform my jwt into another jwt, how can I use this jwt that comes from my api?

![image](https://user-images.githubusercontent.com/21026675/104983855-5b121e00-59ec-11eb-86a0-63454e6ba078.png)

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by balazsorban44** [comment]
next-auth creates its own jwt, and currently there is nothing you can do about it.

I assume we do this in the name of security, but @iaincollins coyod probably explain the exact reason
