### ISSUE TITLE
Auth and Cloudfront

### ISSUE THREAD

**Issue by dartmoordunbar** [nextauthjs/next-auth#1153]
**Your question**
Do you have to do anything specific to allow next-auth to work through AWS Cloudfront?
**What are you trying to do**
I have a previously working next-auth app hosted on Elastic Beanstalk - I have now put Cloudfront in front of it to allow for HTTPS. The login link takes me to here
https://dartmoortrust.org/api/auth/signin?callbackUrl=https%3A%2F%2Fdartmoortrust.org%2F
Then on click I redirect to here
https://dartmoortrust.org/api/auth/signin?csrf=true
But nothing else happens and there are no errors in the console.
**Reproduction**
As above.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Can it be that CloudFront tries to cache the /api pages? Could you verify that this is not the case?

**Comment by iaincollins** [comment]
This would be my gut feeling too.

It should work fine on AWS Cloudfront but could be tripping up depending on the CDN configuration.

Disable caching for all `/api/auth/` routes is probably the easiest way to resolve this.

I'm open to suggestions for changes to default Cache-Control headers which would avoid folks getting caught out by this.

e.g. adding `Cache-Control: private, no-cache, no-store` on all routes by default.

**Comment by balazsorban44** [comment]
@iaincollins Next.js already sets necessary cache  headers for every /api route

**Comment by balazsorban44** [comment]
![image](https://user-images.githubusercontent.com/18369201/105420515-c9e7b500-5c40-11eb-8604-ee1796771a66.png)
Confirmed, Cloudfront caches your /api routes! This should not be the case, in any case, it has nothing to do with `next-auth`. Next.js sets the correct headers as mentioned above.

**Comment by coldice** [comment]
I was seeing a constant redirect to `/api/auth/signin?csrf=true` when trying to submit the form, disabling caching totally didn't help. Turned out when using the new cloudfront _Cache policy and origin request policy_, all cookie forwarding is disabled by default, unless explicitly enabled on the Origin request policy section. Not forwarding cookies was causing this behaviour.

Quick fix: Select the "AllViewer" managed Origin request policy.

**Comment by salauddinn** [comment]
Thanak @coldice  it worked for me but I had  to put "AllViewerExcpetHostHeader"
