### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#1154]
**Summary of proposed feature**
`next-auth` pages are currently only available in English: https://next-auth.js.org/configuration/pages

**Purpose of proposed feature**
These pages can be customized/replaced by the user to mitigate any requirements, but it would be nice if we provided a way to show these pages in multiple languages out-of-the-box.

**Detail about proposed feature**

Next.js 10 added new features for a better [i18n development experience](https://nextjs.org/blog/next-10#internationalized-routing) which we could [utilize](https://github.com/nextauthjs/next-auth/discussions/1129#discussioncomment-293562).

`next-auth` takes a `pages` property to configure/replace the built-in ones.

`pages` could take a new property, called `locales`, which would hold the translations for the different built-in pages.

Example:
```js
// /api/auth/[...nextauth].js
import NextAuth from "next-auth"
export default NextAuth({
  ...
  pages: {
    locales: {
      en: {
        "verify-request": {
          title: "Check your e-mail",
          subtitle: "A sign in link has been sent to your email address.",
        },
        signout: {
          title: "Are you sure you want to sign out?",
          button: "Sign out",
        },
        ...
      },
    },
  }
  ...
})
```

**Potential problems**
?

**Describe any alternatives you've considered**
The only way to achieve this today is through fully custom pages.

**Additional context**
Any other context, screenshots, etc.
Originally asked here: https://github.com/nextauthjs/next-auth/discussions/1129
In #831, there was an attempt to add support for language change in the sent e-mails.

**Comment by stevedaniels-traintime** [comment]
@balazsorban44 did you manage to implement this through fully custom pages?

It would be awesome if you could give us some tips on how this was achieved 🙏

**Comment by YuriGor** [comment]
Hi @stevedaniels-traintime currently I am using next/router to navigate to signIn custom page instead of `signin` method and it seems to work fine.

```js
import { useRouter } from 'next/router';
import { useSession } from 'next-auth/client';
import useTranslation from 'next-translate/useTranslation';
import { AlertTitle } from '@material-ui/lab';
import { useRouter } from 'next/router';
import Link from './link';
import Alert from './alert';

export default function withAuth(Component, { pageTitle }) {
  return (props) => {
    const router = useRouter();
    // below is instead of 'signin' next-auth method
    const signin = () => {
      router.push(`/auth/welcome?callbackUrl=${window.location.href}`);
    };
    const [session] = useSession();
    const { t } = useTranslation('common');
    if (!session) {
      return (
        <Alert severity="access">
          <AlertTitle>{t('welcomeBack')}</AlertTitle>
          {pageTitle && t('accessingPage', { pageTitle: t(pageTitle) })}
          <br />
          {t('pleaseSignInLabel')}
          <Link href="#" onClick={signin}>
            {t('pleaseSignInButton')}
          </Link>
          !
        </Alert>
      );
    }
    return <Component {...props} />;
  };
}
```

**Comment by iffa** [comment]
Needed this functionality myself as well, so started working on an implementation: #1489

**Comment by balazsorban44** [comment]
Nice preliminary work by @iffa at their PR that I think we can follow up on and hopefully merge some time!

**Comment by TiagoCavalcante** [comment]
How is this now?

**Comment by omattman** [comment]
Any updates on this?

**Comment by hamzaseif13** [comment]
any updates ?

**Comment by arrenanv** [comment]
Hello. I want to add custom titles in my language to an error messages. Is there any suggestions on how to do that? Or maybe some updates regarding this feature request?

**Comment by relense** [comment]
any updates for this?
