### ISSUE TITLE
How I get the userId from hook useSession

### ISSUE THREAD

**Issue by emersonlaurentino** [nextauthjs/next-auth#1155]
**Your question**
The useSession hook currently has a response to the session:

`accessToken`, `expires` and `user`. In `user` it brings `name`, `email` and `image`, I would like it to also include the `id` of the user.

**What are you trying to do**
Read the user id from session

**Reproduction**
this is not a bug

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Please read the docs about the `jwt` and `session` callbacks https://next-auth.js.org/configuration/callbacks

**Comment by oliviermtl** [comment]
callbacks.session = async (session, user) => {
  session.userId = user.sub;
  return Promise.resolve(session);
};

**Comment by emersonlaurentino** [comment]
Yes, @oliviermtl I did exactly like your example. Thank you anyway!
