### ISSUE TITLE
Add none-default fields to a user in a database

### ISSUE THREAD

**Issue by Yedidya10** [nextauthjs/next-auth#11567]
### What is the improvement or update you wish to see?

I am trying to add the following fields to a user in a database, beyond 3 fields that are updated by default (name, email and image)  :

 firstName: profile?.given_name,
 lastName: profile?.family_name,
 role: 'user',

I tried to do this, but it only updates after logging out and logging in a second time:
```
callbacks: {
 signIn: async ({ user, account, profile }) => {
      await User.findOneAndUpdate(
        { email: user?.email },
        {
          firstName: profile?.given_name,
          lastName: profile?.family_name,
          role: 'user',
        },
        { new: true }
      )

      return true
    },
}
```

It should be noted that before that I put the above function in the session callback, but recently I realized that this is problematic, because the session callback is called a lot during the use of the website

It is not clear to me from the documents how I can update the user from the fields of the "profile" parameter such as given_name and family_name or even add my own, such as role

### Is there any context that might help us understand?

I saw that there is a brief mention in the new version about profile functions (https://authjs.dev/reference/core/providers#profile). But it's version 5 beta and I'm currently using version 4 and not ready to migrate yet

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/configuration/callbacks#sign-in-callback

**Comment by balazsorban44** [comment]
> I saw that there is a brief mention in the new version about profile functions (https://authjs.dev/reference/core/providers#profile). But it's version 5 beta and I'm currently using version 4 and not ready to migrate yet


v4 has the same method. whatever returned in the profile callback will be saved on the user during creation.

https://authjs.dev/guides/role-based-access-control#with-database
