### ISSUE TITLE
Unknown argument `provider_providerAccountId`. Did you mean `providerId_providerAccountId`? Available options are marked with ?

### ISSUE THREAD

**Issue by dhruvkaushik305** [nextauthjs/next-auth#11568]
### Adapter type

@auth/prisma-adapter

### Environment

```
  System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 2.94 GB / 7.41 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.15.1/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
    pnpm: 9.6.0 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 127.0.6533.99
  npmPackages:
    next: 14.2.5 => 14.2.5
    next-auth: ^4.24.7 => 4.24.7
    react: ^18.3.1 => 18.3.1
```

### Reproduction URL

https://github.com/dhruvkaushik305/Finify/blob/dev/prisma/schema.prisma

### Describe the issue

Following the documentation given on the prisma adapter, this schema should login the user. However it is returning the an error.
Unknown argument `provider_providerAccountId`. Did you mean `providerId_providerAccountId`? Available options are marked with ?. {
  message: '\n' +
    'Invalid `prisma.account.findUnique()` invocation:\n' +
    '\n' +
    '{\n' +
    '  where: {\n' +
    '    provider_providerAccountId: {\n' +
    '    ~~~~~~~~~~~~~~~~~~~~~~~~~~\n' +
    '      providerAccountId: "110485415897385727029",\n' +
    '      provider: "google"\n' +
    '    },\n' +
    '?   id?: String,\n' +
    '?   providerId_providerAccountId?: AccountProviderIdProviderAccountIdCompoundUniqueInput,\n' +
    '?   AND?: AccountWhereInput | AccountWhereInput[],\n' +
    '?   OR?: AccountWhereInput[],\n' +
    '?   NOT?: AccountWhereInput | AccountWhereInput[],\n' +
    '?   userId?: StringFilter | String,\n' +
    '?   providerType?: StringFilter | String,\n' +
    '?   providerId?: StringFilter | String,\n' +
    '?   providerAccountId?: StringFilter | String,\n' +
    '?   refreshToken?: StringNullableFilter | String | Null,\n' +
    '?   accessToken?: StringNullableFilter | String | Null,\n' +
    '?   accessTokenExpires?: DateTimeNullableFilter | DateTime | Null,\n' +
    '?   createdAt?: DateTimeFilter | DateTime,\n' +
    '?   updatedAt?: DateTimeFilter | DateTime,\n' +
    '?   user?: UserRelationFilter | UserWhereInput\n' +
    '  },\n' +
    '  select: {\n' +
    '    user: true\n' +
    '  }\n' +
    '}\n' +
    '\n' +
    'Unknown argument `provider_providerAccountId`. Did you mean `providerId_providerAccountId`? Available options are marked with ?.',
  stack: 'PrismaClientValidationError: \n' +
    'Invalid `prisma.account.findUnique()` invocation:\n' +
    '\n' +
    '{\n' +
    '  where: {\n' +
    '    provider_providerAccountId: {\n' +
    '    ~~~~~~~~~~~~~~~~~~~~~~~~~~\n' +
    '      providerAccountId: "110485415897385727029",\n' +
    '      provider: "google"\n' +
    '    },\n' +
    '?   id?: String,\n' +
    '?   providerId_providerAccountId?: AccountProviderIdProviderAccountIdCompoundUniqueInput,\n' +
    '?   AND?: AccountWhereInput | AccountWhereInput[],\n' +
    '?   OR?: AccountWhereInput[],\n' +
    '?   NOT?: AccountWhereInput | AccountWhereInput[],\n' +
    '?   userId?: StringFilter | String,\n' +
    '?   providerType?: StringFilter | String,\n' +
    '?   providerId?: StringFilter | String,\n' +
    '?   providerAccountId?: StringFilter | String,\n' +
    '?   refreshToken?: StringNullableFilter | String | Null,\n' +
    '?   accessToken?: StringNullableFilter | String | Null,\n' +
    '?   accessTokenExpires?: DateTimeNullableFilter | DateTime | Null,\n' +
    '?   createdAt?: DateTimeFilter | DateTime,\n' +
    '?   updatedAt?: DateTimeFilter | DateTime,\n' +
    '?   user?: UserRelationFilter | UserWhereInput\n' +
    '  },\n' +
    '  select: {\n' +
    '    user: true\n' +
    '  }\n' +
    '}\n' +
    '\n' 

### How to reproduce

Running the development server, logging in with google creds

### Expected behavior

Login completes

**Comment by balazsorban44** [comment]
https://github.com/dhruvkaushik305/Finify/blob/3e2582312001d8dfbbc43ee30bfdca2ba4cc47f5/prisma/schema.prisma#L14

This should be `provider`, not `providerId`

**Comment by dhruvkaushik305** [comment]
okay makes sense, i had used the wrong old documentation
