### ISSUE TITLE
Create list of providers dynamically from provider docs front matter

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#1157]
Currently, we define providers twice in the documentation. We have a `www/providers.json` file, but each provider documentation has the same information about the provider id and title. We could create the `providers.json` file out of those front matters, and add it as a pre-build step for the documentation page. This would minimize the number of files that need to be added/edited when adding a new provider.

Ref: https://github.com/nextauthjs/next-auth/commit/1a1a1f97214bedc7a2a0e092b168b331ffa6a64b#commitcomment-46130313

all supported providers: https://github.com/nextauthjs/next-auth/tree/canary/www/docs/providers
providers.json: https://github.com/nextauthjs/next-auth/blob/canary/www/providers.json

**Comment by ndom91** [comment]
Yeah great idea!
