### ISSUE TITLE
Where to learn about inner workings of next auth to contribute

### ISSUE THREAD

**Issue by RahulBirCodes** [nextauthjs/next-auth#11583]
### What is the improvement or update you wish to see?

Old link in contributing guide is broken. Where should I go to now?

### Is there any context that might help us understand?

No where at the moment to learn how next auth works internally to help contribute.

**Comment by k-taro56** [comment]
Which has the broken link in contributing guide?

**Comment by balazsorban44** [comment]
Hi, the entire source code is public. I would start at the root directory and than delve into packages you would like to contribute to

https://github.com/nextauthjs/next-auth/tree/main/packages

contributing guide is here https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md
