### ISSUE TITLE
Missing FusionAuth from types

### ISSUE THREAD

**Issue by jeremy-london** [nextauthjs/next-auth#1158]
**Describe the bug**

Property 'FusionAuth' does not exist on type 'Providers'

**Steps to reproduce**
Steps to reproduce the behavior.

Include a link to the public repository which can be used to reproduce the behavior.

**Expected behavior**
Types should be complete with the latest release of next-auth
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/next-auth is currently not showing the same supported providers as the current release

**Feedback**

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [X] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
With TypeScript issues, please go to https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/next-auth for now. TS support is currently a community effort.

**Comment by jeremy-london** [comment]
May want to re-address the README a bit: https://github.com/nextauthjs/next-auth/blob/canary/README.md#typescript

**Comment by balazsorban44** [comment]
Thanks, I will do that!
