### ISSUE TITLE
Is there a way set google's scope in [...nextauth].ts file

### ISSUE THREAD

**Issue by get6** [nextauthjs/next-auth#1160]
Hello.

I was really happy knowing this library.

and I only need Google's Provider. so is not difficult to use it.

NextAuth simply worked. 

But I have a question.

**Your question**

Is there any scope option for Google's provider?

**What are you trying to do**

I need Google Calendar API for the Company Admin site

I have to get permission about Calendar API When the user signs in 

There is a sample explaining Node.js OAuth2 on the Google Calendar API site.

I can make OAuth2 URL with the permission scope.

is the only way to use it?

Thx!
I'm not good at English But I love it

**Reproduction**

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by get6** [comment]
Hi. For fixing this error. I tried two ways. but it doesn't affect.

As you know I need to set the scope.

Somehow, I thought it works that I had an idea to set google provider authorization URL with a scope on [...nextauth].ts.

but some error came out
`
OAuth 2 parameters can only have a single value: scope
`

so I used another way.

Set Url with scope to button href

THE callback API is the same as NextAuth.js

and I got this error
`
[next-auth][error][callback_oauth_error] Error: Invalid state returned from oAuth provider
    at /Users/sjhwang/GitHub/socialbox-admin/node_modules/next-auth/dist/server/lib/oauth/callback.js:46:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/sjhwang/GitHub/socialbox-admin/node_modules/next-auth/dist/server/lib/oauth/callback.js:26:103)
    at _next (/Users/sjhwang/GitHub/socialbox-admin/node_modules/next-auth/dist/server/lib/oauth/callback.js:28:194)
    at /Users/sjhwang/GitHub/socialbox-admin/node_modules/next-auth/dist/server/lib/oauth/callback.js:28:364
    at new Promise (<anonymous>)
    at /Users/sjhwang/GitHub/socialbox-admin/node_modules/next-auth/dist/server/lib/oauth/callback.js:28:97
    at /Users/sjhwang/GitHub/socialbox-admin/node_modules/next-auth/dist/server/lib/oauth/callback.js:143:17
    at /Users/sjhwang/GitHub/socialbox-admin/node_modules/next-auth/dist/server/routes/callback.js:58:31
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/sjhwang/GitHub/socialbox-admin/node_modules/next-auth/dist/server/routes/callback.js:26:103)
    at _next (/Users/sjhwang/GitHub/socialbox-admin/node_modules/next-auth/dist/server/routes/callback.js:28:194)
    at /Users/sjhwang/GitHub/socialbox-admin/node_modules/next-auth/dist/server/routes/callback.js:28:364
    at new Promise (<anonymous>)
    at /Users/sjhwang/GitHub/socialbox-admin/node_modules/next-auth/dist/server/routes/callback.js:28:97
    at /Users/sjhwang/GitHub/socialbox-admin/node_modules/next-auth/dist/server/routes/callback.js:346:17 
https://next-auth.js.org/errors#callback_oauth_error
`

It's pretty difficult...

**Comment by get6** [comment]
Maybe I have to replace Providers.Google to Custom Provider.

I'm using typescript. Where I can find Profile's type?

The profile doesn't have a picture attribute.

And Callback error told me
`
Invalid state returned from oAuth provider
`

**Comment by get6** [comment]
Oh I resolved this problem!

For someone who read this.
`
{
      id: 'google',
      name: 'Google',
      type: 'oauth',
      version: '2.0',
      scope:
        'https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/calendar',
      params: { grant_type: 'authorization_code' },
      accessTokenUrl: 'https://accounts.google.com/o/oauth2/token',
      requestTokenUrl: 'https://accounts.google.com/o/oauth2/auth',
      authorizationUrl: 'https://accounts.google.com/o/oauth2/auth?response_type=code',
      profileUrl: 'https://www.googleapis.com/oauth2/v1/userinfo?alt=json',
      profile: (profile: any) => {
        return {
          id: profile.id,
          name: profile.name,
          email: profile.email,
          image: profile.picture,
        };
      },
      clientId: `${process.env.GOOGLE_ID}`,
      clientSecret: `${process.env.GOOGLE_SECRET}`,
    },
`

And add click event signIn('google') on your button

**Comment by get6** [comment]
I think this is a better code. before testing this, I didn't think it worked.
`
Providers.Google({
      clientId: `${process.env.GOOGLE_ID}`,
      clientSecret: `${process.env.GOOGLE_SECRET}`,
      scope:
        'https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/calendar',
      authorizationUrl:
        'https://accounts.google.com/o/oauth2/v2/auth?prompt=consent&access_type=offline&response_type=code',
    }),
`

**Comment by Yummy-sk** [comment]
In v4
```javascript
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID!,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
      authorization: {
        params: {
          scope: "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
        }
      }
```
