### ISSUE TITLE
v5 with next.js，       sessionToken maxAge: undefined not work

### ISSUE THREAD

**Issue by 1148453957** [nextauthjs/next-auth#11610]
### Environment

    "next": "14.2.5",
    "next-auth": "5.0.0-beta.20",

### Reproduction URL

https://github.com/1148453957/next-chatBond/blob/main/auth.ts

### Describe the issue

I want to set the expiration time to empty so that when I close my browser, the cookie will be automatically deleted.  
But when I set maxAge to a number, such as 100, it will take effect.But when I set it to undefined, it won't take effect.The cookie of the browser is set to 30 days
// auth.ts 
```
  cookies: {
    sessionToken: {
      name: "authjs.session-token",
      options: {
        httpOnly: true,
        path: "/",
        maxAge: undefined,
      },
    },
  },
```

### How to reproduce

```
  cookies: {
    sessionToken: {
      name: "authjs.session-token",
      options: {
        httpOnly: true,
        path: "/",
        maxAge: undefined,
        expires: undefined, // 将 expires 设置为 undefined 使其成为会话 cookie
      },
    },
  },
```

### Expected behavior

I hope that when maxAge is set to undefined, it will take effect and the browser's cookie will indeed be set

**Comment by balazsorban44** [comment]
Hi, this is currently not an option, as browsers (like Chrome) don't really respect the `Session` expiry. They keep running in the background, and so cookies would never expire. You are safer to set a low value instead.
