### ISSUE TITLE
Atlassian Provider not working but its in the docs for v5

### ISSUE THREAD

**Issue by tcarbs** [nextauthjs/next-auth#11613]
### What is the improvement or update you wish to see?

I would like to see Atlassian implemented in v5. I see it is in v4, maybe you guys just haven't gotten around to it. All good, but remove it as an option from your v5 docs when you search for OAuth providers.

### Is there any context that might help us understand?

These are the docs for v5.
https://authjs.dev/getting-started/authentication/oauth

You can search for Atlassian but it is not in the v5 packages.
https://github.com/nextauthjs/next-auth/tree/main/packages/core/src/providers

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/authentication/oauth

**Comment by tcarbs** [comment]
found the actual link that is empty.

https://authjs.dev/getting-started/providers/atlassian

**Comment by arwanfiles** [comment]
same issue :(

**Comment by quinnsprouse** [comment]
Running into the same issue...

**Comment by balazsorban44** [comment]
I dropped the code in https://github.com/nextauthjs/next-auth/commit/cb1a260523d7b5c6a5af59b63f1e911a60a9edb1

but quite frankly I don't remember why. Form my description, I assessed it was somehow relying on OAuth 1.0, which is not supported anymore.

Im fine if we re-add it. Here is the documentation https://developer.atlassian.com/cloud/jira/software/oauth-2-3lo-apps/

**Comment by DevRish** [comment]
@balazsorban44 Thanks for providing the latest docs! I have made the necessary modifications for oauth2.0 and brought back the atlassian provider. Please review the PR.
