### ISSUE TITLE
Using auth to access other googleapis

### ISSUE THREAD

**Issue by amitrahav** [nextauthjs/next-auth#1162]
**Your question**
What is the best way of using next-auth as an auth instant to googleapis?

**What are you trying to do**
I'm trying to send a mail with gmail api from the backend.  

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by get6** [comment]
It might be helpful for you.

First, you should visit Google's API libraries and add APIs that you want.

Go to the OAuth consent screen menu. Click the EDIT APP next to the title.

In step two. you can find ADD OR REMOVE SCOPES button.

Maybe there is Gmail API. If you already added this API at APIs libraries.

In my case, I needed Calendar API. so I added this Calendar API scope
`
https://www.googleapis.com/auth/calendar
`

If you selected some scope save it.

Next, you update your options's providers in [...nextAuth].js

Because you changed your scope at console.develoepers.google.com

You can see a custom provider.
#1160

**Comment by amitrahav** [comment]
I did all of those steps, but when I try to initialize googleapis I need to pass an Auth instance. At the [googleapis docs](https://github.com/googleapis/google-api-nodejs-client) they make it very clear - If there's a need of using blooger for example I need to pass one of those:
```Javascript
// 1. API KEY
const blogger = google.blogger({
  version: 'v3',
  auth: 'YOUR API KEY'
});

// 2. Oauth instance
const oauth2Client = new google.auth.OAuth2(
  YOUR_CLIENT_ID,
  YOUR_CLIENT_SECRET,
  YOUR_REDIRECT_URL
);

const drive = google.drive({
  version: 'v2',
  auth: oauth2Client
});

// 3. Key file
const auth = new google.auth.GoogleAuth({
  keyFile: '/path/to/your-secret-key.json',
  scopes: ['https://www.googleapis.com/auth/cloud-platform'],
});

const drive = google.drive({
  version: 'v2',
  auth
});

``` 

So I'm searching for a way to pass the Oath instance I used with `next-auth` In to the auth property of `googleapis`.

**Comment by get6** [comment]
I think we should change authorizationUrl. Look at this [Google on NextAuth.js page](https://next-auth-git-canary.nextauthjs.vercel.app/providers/google).

In my case, Some hours works fine. but access_token changed to Invalid Credentials.

So I query Account Entity from Database with Prisma.

Then I make new credentials added access_token, refresh_token

Put this credential to auth's place.

I was able to respond Calendar Events list from googleapis

**Comment by Marcus-Rise** [comment]
I just reach the goal: get the file list from [google drive user appdata folder](https://developers.google.com/drive/api/v3/appdata) from specific api url. 

`pages/api/auth/[...nextauth].ts`
```ts
import type { InitOptions, User } from "next-auth";
import NextAuth from "next-auth";
import Providers from "next-auth/providers";
import type { NextApiHandler } from "next";
import type { GenericObject, SessionBase } from "next-auth/_utils";

const scopes = [
  "https://www.googleapis.com/auth/userinfo.email",
  "https://www.googleapis.com/auth/userinfo.profile",
  "https://www.googleapis.com/auth/drive.appdata",
];
const JWT_SECRET = String(process.env.NEXTAUTH_JWT_SECRET);
const authorizationUrl = new URL("https://accounts.google.com/o/oauth2/v2/auth");
authorizationUrl.searchParams.set("prompt", "consent");
authorizationUrl.searchParams.set("access_type", "offline");
authorizationUrl.searchParams.set("response_type", "code");

const options: InitOptions = {
  providers: [
    Providers.Google({
      clientId: String(process.env.GOOGLE_CLIENT_ID),
      clientSecret: String(process.env.GOOGLE_CLIENT_SECRET),
      authorizationUrl: authorizationUrl.toString(),
      scope: scopes.join(" "),
    }),
  ],
  secret: JWT_SECRET,
  jwt: {
    encryption: true,
    secret: JWT_SECRET,
  },
  debug: process.env.NODE_ENV === "development",
  callbacks: {
    async jwt(token: GenericObject, user: User, account: GenericObject): Promise<GenericObject> {
      if (account) {
        token.accessToken = account?.accessToken;
        token.refreshToken = account?.refreshToken;
      }

      return token;
    },
    async session(session: SessionBase, user: any): Promise<GenericObject> {
      session.accessToken = user.accessToken;
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore
      session.refreshToken = user.refreshToken;

      return session;
    },
  },
};

const AuthHandler: NextApiHandler = (req, res) => NextAuth(req, res, options);

export default AuthHandler;
```
`pages/api/test/index.ts`
```ts
import type { NextApiHandler } from "next";
import { getSession } from "next-auth/client";
import { google } from "googleapis";

const TestHandler: NextApiHandler = async (req, res) => {
  const session = await getSession({ req });

  if (!session) {
    res.status(401);
  }

  const clientId = process.env.GOOGLE_CLIENT_ID;
  const clientSecret = process.env.GOOGLE_CLIENT_SECRET;
  const accessToken = session?.accessToken;
  const refreshToken = session?.refreshToken;

  const auth = new google.auth.OAuth2({
    clientId,
    clientSecret,
  });
  auth.setCredentials({
    access_token: accessToken,
    refresh_token: refreshToken,
  });

  const drive = google.drive({ auth, version: "v3" });

  await drive.files
    .list({ spaces: "appDataFolder" })
    .then((data) => {
      console.debug(data.data);
      res.json(data.data);
    })
    .catch((e) => {
      const error = e?.stack ?? e?.response?.data?.error;
      res.status(error?.code ?? 500).json(error ?? e);
    });
};

export default TestHandler;
```
`http://localhost:3000/api/test`
```json
{
  "kind": "drive#fileList",
  "incompleteSearch": false,
  "files": [
    
  ]
}
```

Of course, code is a draft variant. It's only demonstrating the plain solution.

Full [repo is here](https://github.com/Marcus-Rise/BuyList/blob/feat/auth/pages/api/auth/%5B...nextauth%5D.ts).

**Comment by get6** [comment]
I had faced an issue too.

I got this message 'token has been expired or revoked.' from requesting API.

@Marcus-Rise 
Don't you get the same message?

I think refresh_token is expired.

The solution is simple. just follow NextAuth.js example until login.

And you might have API keys on your console. [See](https://console.developers.google.com/)

In my case, I use google's calendar API. So my code like this.
`
const auth: Auth.OAuth2Client = new google.auth.OAuth2(
  process.env.GOOGLE_ID,
  process.env.GOOGLE_SECRET,
  process.env.GOOGLE_CALLBACK,
);

google.options({
  auth,
});

const calendar = google.calendar({ version: 'v3', auth: `${process.env.GOOGLE_API_KEY}` });

`

Now I don't need credentials anymore.

For more information. you'd better look at [it](https://googleapis.dev/nodejs/googleapis/latest/oauth2/index.html#using-api-keys)

**Comment by Marcus-Rise** [comment]
@get6, to solve the refreshing issue I used the solution @lawrencecchen, described [here](https://github.com/nextauthjs/next-auth/issues/1079#issuecomment-759116770)

His full example is [here](https://github.com/lawrencecchen/next-auth-refresh-tokens/blob/main/pages/api/auth/%5B...nextauth%5D.js)

I'm implementing this solution too, and it's working. Maybe today I will push my implemention and share the link.
Or you can just wait for changes on my [branch](https://github.com/Marcus-Rise/BuyList/blob/feat/auth/pages/api/auth/%5B...nextauth%5D.ts)

**Comment by Marcus-Rise** [comment]
@get6, I need credentials, because trying to use Google Drive application data, to store user data in this own storage.
And on sigin process he will be notified about that.

**Comment by Marcus-Rise** [comment]
@get6, there is a ready solution based on @lawrencecchen

[`pages/api/auth/[...nextauth].ts`](https://github.com/Marcus-Rise/BuyList/blob/feat/auth/pages/api/auth/%5B...nextauth%5D.ts)

```ts
import type { InitOptions, User } from "next-auth";
import NextAuth from "next-auth";
import Providers from "next-auth/providers";
import type { NextApiHandler } from "next";
import type { GenericObject } from "next-auth/_utils";
import type { IGoogleConfig } from "../../../src/server/google";
import { GOOGLE_CONFIG } from "../../../src/server/google";
import { inject } from "../../../src/server/ioc";
import type { AuthPayload } from "../../../src/server/auth/auth-payload.interface";

/**
 * Takes a token, and returns a new token with updated
 * `accessToken` and `accessTokenExpires`. If an error occurs,
 * returns the old token and an error property
 */
const refreshAccessToken = async (
  payload: AuthPayload,
  clientId: string,
  clientSecret: string,
): Promise<AuthPayload> => {
  try {
    const url = new URL("https://oauth2.googleapis.com/token");
    url.searchParams.set("client_id", clientId);
    url.searchParams.set("client_secret", clientSecret);
    url.searchParams.set("grant_type", "refresh_token");
    url.searchParams.set("refresh_token", payload.refreshToken);

    const response = await fetch(url.toString(), {
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
      },
      method: "POST",
    });

    const refreshToken = await response.json();

    if (!response.ok) {
      throw refreshToken;
    }

    // Give a 10 sec buffer
    const now = new Date();
    const accessTokenExpires = now.setSeconds(now.getSeconds() + refreshToken.expires_in - 10);

    return {
      ...payload,
      accessToken: refreshToken.access_token,
      accessTokenExpires,
      refreshToken: refreshToken.refresh_token,
    };
  } catch (error) {
    console.error(error);

    return {
      ...payload,
      error: "RefreshAccessTokenError",
    };
  }
};

const AuthHandler: NextApiHandler = (req, res, googleConfig = inject<IGoogleConfig>(GOOGLE_CONFIG)) => {
  const scopes = [
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/userinfo.profile",
    "https://www.googleapis.com/auth/drive.appdata",
  ];
  const JWT_SECRET = String(process.env.NEXTAUTH_JWT_SECRET);
  const authorizationUrl = new URL("https://accounts.google.com/o/oauth2/v2/auth");
  authorizationUrl.searchParams.set("prompt", "consent");
  authorizationUrl.searchParams.set("access_type", "offline");
  authorizationUrl.searchParams.set("response_type", "code");

  const options: InitOptions = {
    providers: [
      Providers.Google({
        clientId: googleConfig.clientId,
        clientSecret: googleConfig.clientSecret,
        authorizationUrl: authorizationUrl.toString(),
        scope: scopes.join(" "),
      }),
    ],
    secret: JWT_SECRET,
    jwt: {
      encryption: true,
      secret: JWT_SECRET,
    },
    debug: process.env.NODE_ENV === "development",
    callbacks: {
      async jwt(payload: AuthPayload, user: User, account: GenericObject): Promise<AuthPayload> {
        let res: AuthPayload;

        const now = Date.now();

        // Signing in
        if (account && user) {
          const accessToken = account.accessToken;
          const refreshToken = account.refreshToken;

          res = {
            accessToken,
            accessTokenExpires: account.accessTokenExpires,
            refreshToken,
            user,
          };
        } else if (payload.accessTokenExpires === null || now < payload.accessTokenExpires) {
          // Subsequent use of JWT, the user has been logged in before
          // access token has not expired yet
          res = payload;
        } else {
          // access token has expired, try to update it
          res = await refreshAccessToken(payload, googleConfig.clientId, googleConfig.clientSecret);
        }

        return res;
      },
      async session(_, payload: GenericObject): Promise<GenericObject> {
        return payload;
      },
    },
  };

  return NextAuth(req, res, options);
};

export default AuthHandler;
```

**Comment by get6** [comment]
@Marcus-Rise Thank you for your kindly explaining what i missed

Now I realized what I have to do.

You are awesome!🤩

**Comment by amitrahav** [comment]
@Marcus-Rise Thank you! this method works fine, I really think it should be added to documentation.

**Comment by balazsorban44** [comment]
@amitrahav I came up with this user land refresh token solution at work, glad that folks are discovering it. :) definitely would be a good addition to the docs, that's why we have an open "good first issue" on it! feel free to contribute https://github.com/nextauthjs/next-auth/issues/1079

**Comment by Blackspadez006** [comment]
> @get6, there is a ready solution based on @lawrencecchen [repo](https://github.com/lawrencecchen/next-auth-refresh-tokens/blob/main/pages/api/auth/%5B...nextauth%5D.js)
> 
> [`pages/api/auth/[...nextauth].ts`](https://github.com/Marcus-Rise/BuyList/blob/feat/auth/pages/api/auth/%5B...nextauth%5D.ts)
> 
> ```ts
> import type { InitOptions, User } from "next-auth";
> import NextAuth from "next-auth";
> import Providers from "next-auth/providers";
> import type { NextApiHandler } from "next";
> import type { GenericObject } from "next-auth/_utils";
> import type { IGoogleConfig } from "../../../src/server/google";
> import { GOOGLE_CONFIG } from "../../../src/server/google";
> import { inject } from "../../../src/server/ioc";
> import type { AuthPayload } from "../../../src/server/auth/auth-payload.interface";
> 
> /**
>  * Takes a token, and returns a new token with updated
>  * `accessToken` and `accessTokenExpires`. If an error occurs,
>  * returns the old token and an error property
>  */
> const refreshAccessToken = async (
>   payload: AuthPayload,
>   clientId: string,
>   clientSecret: string,
> ): Promise<AuthPayload> => {
>   try {
>     const url = new URL("https://oauth2.googleapis.com/token");
>     url.searchParams.set("client_id", clientId);
>     url.searchParams.set("client_secret", clientSecret);
>     url.searchParams.set("grant_type", "refresh_token");
>     url.searchParams.set("refresh_token", payload.refreshToken);
> 
>     const response = await fetch(url.toString(), {
>       headers: {
>         "Content-Type": "application/x-www-form-urlencoded",
>       },
>       method: "POST",
>     });
> 
>     const refreshToken = await response.json();
> 
>     if (!response.ok) {
>       throw refreshToken;
>     }
> 
>     // Give a 10 sec buffer
>     const now = new Date();
>     const accessTokenExpires = now.setSeconds(now.getSeconds() + refreshToken.expires_in - 10);
> 
>     return {
>       ...payload,
>       accessToken: refreshToken.access_token,
>       accessTokenExpires,
>       refreshToken: refreshToken.refresh_token,
>     };
>   } catch (error) {
>     console.error(error);
> 
>     return {
>       ...payload,
>       error: "RefreshAccessTokenError",
>     };
>   }
> };
> 
> const AuthHandler: NextApiHandler = (req, res, googleConfig = inject<IGoogleConfig>(GOOGLE_CONFIG)) => {
>   const scopes = [
>     "https://www.googleapis.com/auth/userinfo.email",
>     "https://www.googleapis.com/auth/userinfo.profile",
>     "https://www.googleapis.com/auth/drive.appdata",
>   ];
>   const JWT_SECRET = String(process.env.NEXTAUTH_JWT_SECRET);
>   const authorizationUrl = new URL("https://accounts.google.com/o/oauth2/v2/auth");
>   authorizationUrl.searchParams.set("prompt", "consent");
>   authorizationUrl.searchParams.set("access_type", "offline");
>   authorizationUrl.searchParams.set("response_type", "code");
> 
>   const options: InitOptions = {
>     providers: [
>       Providers.Google({
>         clientId: googleConfig.clientId,
>         clientSecret: googleConfig.clientSecret,
>         authorizationUrl: authorizationUrl.toString(),
>         scope: scopes.join(" "),
>       }),
>     ],
>     secret: JWT_SECRET,
>     jwt: {
>       encryption: true,
>       secret: JWT_SECRET,
>     },
>     debug: process.env.NODE_ENV === "development",
>     callbacks: {
>       async jwt(payload: AuthPayload, user: User, account: GenericObject): Promise<AuthPayload> {
>         let res: AuthPayload;
> 
>         const now = Date.now();
> 
>         // Signing in
>         if (account && user) {
>           const accessToken = account.accessToken;
>           const refreshToken = account.refreshToken;
> 
>           res = {
>             accessToken,
>             accessTokenExpires: account.accessTokenExpires,
>             refreshToken,
>             user,
>           };
>         } else if (payload.accessTokenExpires === null || now < payload.accessTokenExpires) {
>           // Subsequent use of JWT, the user has been logged in before
>           // access token has not expired yet
>           res = payload;
>         } else {
>           // access token has expired, try to update it
>           res = await refreshAccessToken(payload, googleConfig.clientId, googleConfig.clientSecret);
>         }
> 
>         return res;
>       },
>       async session(_, payload: GenericObject): Promise<GenericObject> {
>         return payload;
>       },
>     },
>   };
> 
>   return NextAuth(req, res, options);
> };
> 
> export default AuthHandler;
> ```

Can you look at this for once?
