### ISSUE TITLE
Custom Providers - broken link

### ISSUE THREAD

**Issue by GFJankavs** [nextauthjs/next-auth#11629]
### What is the improvement or update you wish to see?

There is an issue currently with `https://authjs.dev/guides/providers/custom-provider` as this link shows no content.

![image](https://github.com/user-attachments/assets/923ab893-fe80-43e4-9950-155551c11f3b)

### Is there any context that might help us understand?

No additional context provided

**Comment by balazsorban44** [comment]
Where is the link located?
