### ISSUE TITLE
Mention nextauthjs/adapters repository in the docs

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#1163]
We recently added a new repository that should serve as the official home for third-party adapters, maintained by the community.

See: https://github.com/nextauthjs/adapters

Also, see the discussion here: https://github.com/nextauthjs/next-auth/discussions/1161

We should probably mention this under:
https://next-auth.js.org/schemas/adapters
and
https://next-auth.js.org/tutorials/creating-a-database-adapter

for better discoverability.

**Comment by aissshah** [comment]
Hi! Could I work on this please? :)

**Comment by balazsorban44** [comment]
yes please! please open a PR, so we can track your progress on this issue.
