### ISSUE TITLE
Found broken `/reference/qwik` link. Please fix!

### ISSUE THREAD

**Issue by thatchr1s** [nextauthjs/next-auth#11650]

**Comment by balazsorban44** [comment]
Where?

**Comment by thatchr1s** [comment]
Link found on page 
https://authjs.dev/getting-started/integrations

Broken URL
Qwik Auth (@auth/qwik)	Released
https://authjs.dev/reference/qwik

![Screenshot_20240822-065634.png](https://github.com/user-attachments/assets/4ff60e6a-2e21-4131-88cc-e1213f8a2ed6)
