### ISSUE TITLE
Hi there, was it opened by a mistake, or you arenkotnfimished with this PR yet? I'm not totally sure what this is.

### ISSUE THREAD

**Issue by kadirselcuk** [nextauthjs/next-auth#1165]
Hi there, was it opened by a mistake, or you arenkotnfimished with this PR yet? I'm not totally sure what this is.

_Originally posted by @balazsorban44 in https://github.com/nextauthjs/next-auth/pull/1164#issuecomment-763778293_

**Comment by balazsorban44** [comment]
I'm confused. What's happening? 🙂

**Comment by kadirselcuk** [comment]
Hi everyone, there is no mistake but I'm trying to develop a vercel study nextauthjs next authorization, with respect

**Comment by kadirselcuk** [comment]
https://next-auth-git-fork-kadirselcuk-feature-forward-signin-response.nextauthjs.vercel.app/
