### ISSUE TITLE
Simpler UX for signing users in (credentials based)?

### ISSUE THREAD

**Issue by oweskeez** [nextauthjs/next-auth#1167]
**Your question**
If the user is _not_ signed in, can I present a sign in form immediately? (Without first having them click on a "Sign in" button that redirects to `/api/auth/signin` per the [example](https://next-auth.js.org/getting-started/example).)

**What are you trying to do**
Avoid step (2) under "Current flow," which will yield something closer to "Ideal flow."

Current flow:
1. User hits the site, unautheticated
2. Immediately sees "Not signed in" with a button that links to `/api/auth/signin`
3. Must click button, and sign in on the following page

Ideal flow:
1. User hits the site, unautheticated
2. Immediately presented with sign in form

**Reproduction**

Example `header.tsx` that checks session on each page:
```    
const Header = ({ children }) => {
    const [ session, loading ] = useSession()
    return <>
        {!session && <>
            // User is not signed in, display form
        </>}
        {session && <>
            // User is signed in, display content
        </>}	
   </>
}	
export default Header
```

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
you could check if the `useSession` hook returns anything for `session` when `loading: false`. in that case just do `router.push("/api/auth/signin")` for example.

**Comment by oweskeez** [comment]
@balazsorban44 That works brilliantly—thanks so much!
