### ISSUE TITLE
redirect_uri of OAuth cannot be overwritten during callback

### ISSUE THREAD

**Issue by JiaAnTW** [nextauthjs/next-auth#11697]
### Environment

```
Sorry I cannot run the command now
```

### Reproduction URL

https://github.com/JiaAnTW/next-auth-example

### Describe the issue

(Note: same as https://github.com/nextauthjs/next-auth/issues/11695, but add a dummy link)

When having a custom oAuth `redirect_uri` instead of `api/auth/callback/${providerId}`, it is available to overwrite it via

```js
OktaProvider({
  authorization: {
    url: "https://example.com/oauth/authorization",
    params: { redirect_uri: "http://my-domain/api/customCallbackPath" }
  },
  token: {
    url: "https://example.com/oauth/authorization",
    params: { redirect_uri: "http://my-domain/api/customCallbackPath" }
  }
})
```

However, the `callbackUrl` inside provider is forced to set as `${url}/callback/${id}` here

https://github.com/nextauthjs/next-auth/blob/342ea540f018fee25aa425b21ab4aa7f5ec42252/packages/core/src/lib/utils/providers.ts#L37-L45

**This makes callback fail if the `redirect_uri` set in OAuth cannot be `api/auth/callback/${providerId}`**

https://github.com/nextauthjs/next-auth/blob/342ea540f018fee25aa425b21ab4aa7f5ec42252/packages/core/src/lib/actions/callback/oauth/callback.ts#L104-L107

One way is using `AUTH_REDIRECT_PROXY_URL`, but this cannot work when it has same origin as url

https://github.com/nextauthjs/next-auth/blob/342ea540f018fee25aa425b21ab4aa7f5ec42252/packages/core/src/lib/init.ts#L78-L86

### How to reproduce

When having a custom `redirect_uri`, and the `redirect_uri` set in OAuth cannot be `api/auth/callback/${providerId}`

### Expected behavior

The `callbackUrl` inside provider(or the `redirect_uri` value used in callback) should be able to be customized via options.

**Comment by balazsorban44** [comment]
The signIn method has the `redirdctTo` option for this usecase.

**Comment by kotmatpockuh** [comment]
@JiaAnTW did it work for you? Same situation, and redirectTo/callbackUrl or callbacks -> redirect
**do not work**

@balazsorban44 how to make it work?
