### ISSUE TITLE
Add Dataswift.io as a auth provider

### ISSUE THREAD

**Issue by pperzyna** [nextauthjs/next-auth#1170]
**Summary of proposed feature**
I would like to use the Dataswift.io solution directly in next-auth

**Purpose of proposed feature**
It simplifies the auth/registration process to simple few steps.

**Detail about proposed feature**
I would like to see Dataswift auth in the same way as auth0

**Potential problems**
-

**Describe any alternatives you've considered**
Create a separate module for Dataswift auth?

**Additional context**
Dataswift is an out of box solution where you can store your client's data fully in all compliance with GDPR and clients have always the right to see and delete their data.
https://www.youtube.com/watch?v=vYef5SHr08s&ab_channel=DataswiftforDevelopers

*Please indicate if you are willing and able to help implement the proposed feature.*
Yep!

**Comment by balazsorban44** [comment]
Awesome that you would be interested in implementing this!
You can find a lot of examples here:

https://github.com/nextauthjs/next-auth/tree/canary/src/providers

When added, could you also mention it in the documentation in these places:
- https://github.com/nextauthjs/next-auth/blob/canary/www/providers.json
- https://github.com/nextauthjs/next-auth/tree/canary/www/docs/providers

**Comment by balazsorban44** [comment]
@pperzyna any interest in picking this up? 😊

**Comment by pperzyna** [comment]
Yes, will try
