### ISSUE TITLE
Cannot find module @auth/providers/roblox

### ISSUE THREAD

**Issue by bill1on** [nextauthjs/next-auth#11717]
### Provider type

Roblox

### Environment

```

  System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 3.80 GB / 15.79 GB
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.61)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @auth/prisma-adapter: ^2.4.2 => 2.4.2
    next: 14.2.7 => 14.2.7
    next-auth: ^5.0.0-beta.20 => 5.0.0-beta.20
    react: ^18 => 18.3.1
```

### Reproduction URL

https://github.com/bill1on/next-auth-example

### Describe the issue

The documentation states that there is a roblox provider available, yet, the example code on the documentation does not seem to work because the provider module cannot be found.
Link to documentation: https://authjs.dev/reference/core/providers/roblox

### How to reproduce

Start a nextjs project with nextauth beta installed
Follow the documentation and try to implement the Roblox provider

### Expected behavior

The roblox provider module should be found

**Comment by balazsorban44** [comment]
It's there, will be out in the next release https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/providers/roblox.ts
