### ISSUE TITLE
Broken Link in Documentation

### ISSUE THREAD

**Issue by irgiys** [nextauthjs/next-auth#11736]
### What is the improvement or update you wish to see?

There is a broken link in the Vercel guide titled "Next.js, Prisma, and PostgreSQL. The link directs users to learn more about certain models in the NextAuth.js docs, but it leads to a "Page Not Found" page instead of the intended content.

### Is there any context that might help us understand?

I encountered the broken link while following the instructions to adjust my database schema. The link was supposed to provide more information about the models, but it seems to be misconfigured or outdated. This could confuse users who are trying to learn more about how to implement these models properly.

### Does the docs page already exist? Please link to it.

https://authjs.dev/reference/adapters#models

**Comment by balazsorban44** [comment]
Please report this to Vercel. Correct link is https://authjs.dev/getting-started/database#models
