### ISSUE TITLE
Can not get Auth0's access token from the session object

### ISSUE THREAD

**Issue by michealj13402** [nextauthjs/next-auth#1177]
**Tech Stack**
nextjs + nextauth with typescript

**Question**
I use nextauth to help my project(built with nextjs) integrate with auth0 as the identity provider, i was able to get the access token from the session object that retrieved from this nextauth api, https://next-auth.js.org/getting-started/client#getsession

Today I suddenly found that I just can't see the "accessToken" property on this "session" object anymore but I didn't remember changing any nextauth config (the options) or any related code. Tried to defined the callbacks option as mentioned in some other threads but no luck with that.

Any thoughts about what could go wrong? Thanks!

**Comment by balazsorban44** [comment]
@michealj13402 your repo must be private, because I get a 404 when opening.

**Comment by michealj13402** [comment]
@balazsorban44 

Sorry, yes for some reason that Repo has to be private, i shouldn't link it in the original post.

So there could be cases that the account doesn't exist (thus no access token)? And why could i get the access token before (no related changes since that point), did nextAuth make some changes to force consumer config the callback options?

**Comment by michealj13402** [comment]
Also, im see this error at the terminal when running the project at local

[next-auth][error][jwt_session_error] JWSVerificationFailed: signature verification failed
    at jwsVerify (C:\Users\Hang\Repos\uxDGeneration\node_modules\jose\lib\jws\verify.js:159:13)
    at Object.module.exports [as verify] (C:\Users\Hang\Repos\uxDGeneration\node_modules\jose\lib\jwt\verify.js:235:5)
    at Object.<anonymous> (C:\Users\Hang\Repos\uxDGeneration\node_modules\next-auth\dist\lib\jwt.js:100:30)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\Hang\Repos\uxDGeneration\node_modules\next-auth\dist\lib\jwt.js:22:103)
    at _next (C:\Users\Hang\Repos\uxDGeneration\node_modules\next-auth\dist\lib\jwt.js:24:194)
    at C:\Users\Hang\Repos\uxDGeneration\node_modules\next-auth\dist\lib\jwt.js:24:364
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Hang\Repos\uxDGeneration\node_modules\next-auth\dist\lib\jwt.js:24:97)
    at Object.decode (C:\Users\Hang\Repos\uxDGeneration\node_modules\next-auth\dist\lib\jwt.js:104:18) {
  code: 'ERR_JWS_VERIFICATION_FAILED'

**Comment by michealj13402** [comment]
@balazsorban44 Ok after i add this to the nextAuth config, it seems solved the issue

  callbacks: {
    session: async (session: any, user: any) => {
      if (user && user.accessToken) {
        session.accessToken = user.accessToken;
      }
      return Promise.resolve(session);
    },
    jwt: async (token, user, account, profile, isNewUser) => {
      if (account && account.accessToken) {
        token.accessToken = account.accessToken;
      }

      return Promise.resolve(token);
    }
  }

and thank you so so much!!

**Comment by balazsorban44** [comment]
You could even simplify this to:

```js
callbacks: {
    async session(session: any, token: any) {
      if (token?.accessToken) {
        session.accessToken = user.accessToken
      }
      return session
    },
    async jwt(token, _, account) {
      if (account?.accessToken) {
        token.accessToken = account.accessToken
      }
      return token
    }
  }
}
```

This is such a highly reoccurring question by the users, that we should really document this better! (#1078)

`jwt` will be passed additional params in the first call (right after signin). This info can be  saved in the `jwt` callback on `token` for later use.

`session` callback is the function deciding what should be visible to the user when reaching for `useSession`, `getSession` or `/api/auth/session` (hint, at the end, all just fetches `/api/auth/session`).


So in `jwt`, first you add the access_token to the jwt session for later use, then in `session`, you actually return it to the client.
