### ISSUE TITLE
Docs: Showing incorrect property name for redirecting in signIn function in  `Next.js (Client)`

### ISSUE THREAD

**Issue by arpittyagi102** [nextauthjs/next-auth#11786]
### What is the improvement or update you wish to see?

In the [Auth.js documentation page](https://authjs.dev/getting-started/session-management/login), There is an example given for `Next.js Client-side`, demonstrating the redirection after logging in 

```
"use client"
import { signIn } from "next-auth/react"
 
export function SignIn() {
  return (
    <button onClick={() => signIn("github", { redirectTo: "/dashboard" })}>
      Sign In
    </button>
  )
}
```

The example is using `redirectTo` property in `options` for `signIn` function. But the property `redirectTo` is not for the `Next.js Client-side` it is for `Next.js` _(server side)_ 
`redirectTo` does not work in this case.

### Is there any context that might help us understand?

For the Client Side, the correct property name is `callbackUrl`, which is also mentioned in the this [NextAuth docs page](https://next-auth.js.org/getting-started/client#specifying-a-callbackurl)

Please correct me If I am wrong

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/session-management/login

**Comment by balazsorban44** [comment]
This will now be supported in the endt release.
