### ISSUE TITLE
Missing env variable in OIDC configurations that require issuer

### ISSUE THREAD

**Issue by edelagnier** [nextauthjs/next-auth#11802]
### What is the improvement or update you wish to see?

When following the [getting started guide](https://authjs.dev/getting-started/authentication/oauth) and selecting keycloak, there is no mention of the "AUTH_KEYCLOAK_ISSUER" variable

![image](https://github.com/user-attachments/assets/6a11a980-143f-4f0f-94b4-508087af8375)

It will result in the following error "[auth][error] InvalidEndpoints: Provider "keycloak" is missing both `issuer` and `authorization` endpoint config."

The information is correct in the dedicated [keycloak page](https://authjs.dev/getting-started/providers/keycloak) 
![image](https://github.com/user-attachments/assets/e2e3410b-3dc0-49df-839d-8c36d305b9ff)

### Is there any context that might help us understand?

none

**Comment by balazsorban44** [comment]
This is not unique to Keycloak. See my comment: https://github.com/nextauthjs/next-auth/pull/11848#issuecomment-2351764054

**Comment by DevRish** [comment]
@balazsorban44 I went through the Provider documentation pages and listed the ones requiring `_ISSUER` env variable.

These are the ones I found:
- authentik
- azure-ad-b2c
- battlenet
- beyondidentity
- boxyhq-saml
- cognito
- descope
- duende-identityserver-6
- fusionauth
- identity-server4
- keycloak
- mastodon
- mattermost
- okta
- osso
- passage

I added a field to the `manifest.json` file to contain this list, and implemented the displaying of the additional env variable for them. 

Please let me know if I missed any providers or wrongly included any of them. Also, please review my PR #11976 .

Thanks!
