### ISSUE TITLE
There is no relesase note from next-auth@4.24.4 to next-auth@4.24.7

### ISSUE THREAD

**Issue by takakikasuga** [nextauthjs/next-auth#11806]
### What is the improvement or update you wish to see?

The next-auth docs（relesase note） is missing information about relesase note from next-auth@4.24.4 to next-auth@4.24.7.

### Is there any context that might help us understand?

We develop sass system and  use your auth package.
we have to update next-auth version from next-auth@4.22.1 to  next-auth@4.24.7
because we have to do security fix for vulnerabilities.
but the relesase note is not here, so our investigation will be stopped...

### Does the docs page already exist? Please link to it.

https://github.com/nextauthjs/next-auth/releases?q=+next-auth&expanded=true

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth/releases/tag/next-auth@4.24.4
https://github.com/nextauthjs/next-auth/releases/tag/next-auth@4.24.5
https://github.com/nextauthjs/next-auth/releases/tag/next-auth@4.24.6
https://github.com/nextauthjs/next-auth/releases/tag/next-auth@4.24.7

**Comment by takakikasuga** [comment]
@balazsorban44 

thk!!
I have searched `next-auth@` word in release tags, but I coudn't find by github pagination.
thank you for sharing link🙏
