### ISSUE TITLE
Improve Session documentation & "Edit this page on GitHub"

### ISSUE THREAD

**Issue by fabpico** [nextauthjs/next-auth#11803]
### What is the improvement or update you wish to see?

Version: `5.0.0-beta.19`

The current `SessionProvider` [example](https://authjs.dev/getting-started/session-management/get-session#page-client-side) is not working (I have app router), the session variable is undefined, as mentioned in https://github.com/nextauthjs/next-auth/issues/7760.

The workaround `const session = await getServerSession(authOptions);` is not working, this function is not available, it led me to https://authjs.dev/getting-started/migrating-to-v5#universal-auth `Use auth() instead of getServerSession (..)`.

I was already using `const session = await auth()`, but now I want to pass it down with `SessionProvider`, which the docs give a not working example.

### Is there any context that might help us understand?

Following expermient worked for me:

Server side
````js
import {SessionProvider} from "next-auth/react"
import {auth} from "@/auth";
import ClientSidePageContent from "@/app/foo/ClientSidePageContent";

export default async function FooPage() {
    const session = await auth()
    return <SessionProvider session={session}>
        <ClientSidePageContent/>
    </SessionProvider>
}
````
Client side
````js
import {useSession} from "next-auth/react";

export default function DeeperComponent() {
    const {data: session} = useSession()
    // ..
}
````

Can you verify this solution and add it to the docs?
I would have liked to make a pull request for the documentation, but a button like `Edit this page on GitHub`, like in https://authjs.dev/guides/extending-the-session, is missing.

In general the https://authjs.dev/guides also miss documentations for session.

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/session-management/get-session#page-client-side

**Comment by jelmd** [comment]
> The available documentation primarily focuses on using the Pages Router ...

Yepp, it is awful.

> Please note that the SessionProvider is only needed for client-side rendering; otherwise, it is not required.

IMHO it depends (at least in v15.0.0-rc.0). E.g.:
```typescript
// app/layout.tsx

import { SESSION_TIMEOUT } from "@/lib/utils";
import { SessionProvider } from "next-auth/react";
import React, { StrictMode } from "react";
import { auth } from "@/auth";

import '@/styles/reset.css';
// ...

import BasePage from "@/components/basePage"

export default async function RootLayout({ children }: { children: React.ReactNode })
{
	const session = await auth();
	let s = process.env['APP_CONTEXT'] ?? '';
	s = s.trim();
	const APP_CONTEXT = s.startsWith('/') ? s.substring(1) : s;
	return (
		<StrictMode>
			<SessionProvider session={session}
				refetchInterval={SESSION_TIMEOUT} basePath={APP_CONTEXT}>
					<html lang="de">
						<body><BasePage>{children}</BasePage></body>
					</html>
			</SessionProvider>
		</StrictMode>
	);
}
```
It (i.e. useSession()) does not work w/o the session parameter (i.e. returns null).

**Comment by jelmd** [comment]
I used `console.log(session)` in RootLayout(...) and BasePage() when testing with and w/o passing it to SessionProvider. The RootLayout() always logged the session content, BasePage() not. Perhaps it is a bug in nextjs 15 rc or react 19 rc ...

**Comment by halvaradop** [comment]
I think you’re right; maybe this error is caused by this version. I have written code with React 19, and it works well for me (but I'm not using Next 15).

**Comment by Foxeye-Rinx** [comment]
I think the title for the Tab is obscure, Inside `Nexjs (Client)`, it has a section for server,  that's not really easy to understand.

Instead, `Nextjs (app router)` and `Nextjs (page router)` might be better names for the tabs

<img width="862" alt="image" src="https://github.com/user-attachments/assets/7b4f61da-ebae-4485-a71a-05ed11663169">

**Comment by halvaradop** [comment]
I understand your reasoning, but I don't think the aim of the documentation is to show implementations for both the app router and the page router. The documentation is focused on demonstrating how to integrate NextAuth on both the client and server sides. Although some sections contain code for the page router, it is not recommended to use it, as the app router provides several improvements.

**Comment by Foxeye-Rinx** [comment]
@halvaradop, thanks, that makes a lot of sense, in `Next.js` tab, this component might be used in a page router and using 
`const session = await auth()` will not work if that's the case, but the doc does not tell that we cannot use that line of code if this component is used from a `page router` page, so anyone just open this doc and haven't seen the `Next.js (Client)` tab will not understand why this code does not work

<img width="868" alt="image" src="https://github.com/user-attachments/assets/eb15ffda-3fdc-454f-95ab-4b797dd49bb7">

**Comment by halvaradop** [comment]
Thanks, you helped me understand the confusion better. The auth function is also supported in the page router; however, there are extra steps required to use it (in my opinion, we shouldn't use it). As mentioned in the previous comments, I don't think it's a good idea to change the name of the tabs. Instead, we could move the page router under the server-side tab to demonstrate how to get data in SSR using the page router.

This way, there will be a section to support getting the session both on the server and on the client.

**Comment by jelmd** [comment]
What about naming it `nextjs app server` `nextjs app client` `nextjs page server` `nextjs page client` ?
