### ISSUE TITLE
please improve the documentation, their is no productional level code mentioned either Credentials nor Oauth, and how do we return the message back to user

### ISSUE THREAD

**Issue by mohdfaizan5** [nextauthjs/next-auth#11875]
### What is the improvement or update you wish to see?

please add proper documentation in the library docs, I can just see the basic use cases, but I can't implement it as a beginner 

### Is there any context that might help us understand?

-

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/authentication/credentials

**Comment by balazsorban44** [comment]
This is too vague of a request. Please be more specific

Check out https://next-auth-example.vercel.app, it should be a solid starter for most projects.

If something is missing PRs welcome, or open a more specific issue with a description
