### ISSUE TITLE
Regarding UI of the Documentation

### ISSUE THREAD

**Issue by ankursharma12345** [nextauthjs/next-auth#11883]
### What is the improvement or update you wish to see?

When I open the site then it is automatically in light mode and at the top where authjs.dev link is given ,it is half hidden and I am not clearly show it. But when I switch to the dark mode then it looks perfect. I think the structure of the of the home page is not correct, some style can be missing which leads to that problem.

### Is there any context that might help us understand?

![Screenshot (16)](https://github.com/user-attachments/assets/5b095e84-a694-4fb0-937f-39b5a520db5c)

As you can see at the top side of the app is not responsive

**Comment by eliezerjoel** [comment]
This seems to be done already
