### ISSUE TITLE
TypeError: getCurves is not a function

### ISSUE THREAD

**Issue by sunrunner4kr-simon** [nextauthjs/next-auth#1190]
**Your question**
Getting this error after installing next-auth

![image](https://user-images.githubusercontent.com/58920692/105630626-2a921000-5e42-11eb-900e-1b4ab13475f1.png)

**What are you trying to do**
Trying to implement next-auth on web project. Not getting any errors on app compile, but after installing next-auth

npm install --save next-auth

I get this error

Relates to Jose module...which I don't have installed, or believe am using at all.

**Reproduction**

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by JakubKoralewski** [comment]
Had the same thing, I was importing a function on the client-side, that imported function had a `import jwt from 'next-auth/jwt'`. Even though the function I imported didn't depend on the `jwt` import it still threw this same error. What worked for me was moving the function I wanted client-side into a separate file.

**Comment by sunrunner4kr-simon** [comment]
Thanks @JakubKoralewski 
The import that's causing it for me is the 

`import { Provider } from 'next-auth'`

from the example code, in my /src/App.js

Not sure where else I could put it...

**Comment by JakubKoralewski** [comment]
I'm pretty sure the import you mention is not the problem. I'm doing the same and it's not a problem.

In what file do you have the line that imports `next-auth/jwt`? For me it is `import {getToken} from 'next-auth/jwt'`. You cannot be importing that on the client side. And you can't be importing the file which imports `next-auth/jwt` from client-side.

**Comment by sunrunner4kr-simon** [comment]
I'm not importing /jwt anywhere

Which is why I was confused :/

**Comment by JakubKoralewski** [comment]
Sorry then unfortunately I won't be able to help 😞 I think to make your chances of getting help from a contributor as high as possible you should either create a reproduction repo/gist etc. or at least show some code. If I were you I'd double check and paste any imports you might be making. Again, sorry I couldn't help and good luck.

**Comment by sunrunner4kr-simon** [comment]
Thanks for the help @JakubKoralewski 

If anyone is willing to have a look, here's my Repo: - https://github.com/sunrunner4kr-simon/EchosDeparted

Let me know and I'll grant access. Thanks again

**Comment by balazsorban44** [comment]
@sunrunner4kr-simon I think your import should look like this:
```js
import Provider from "next-auth/providers"
```

Could you check if this makes a difference?

Also could you give me access to your repo so I can have a direct look?

**Comment by sunrunner4kr-simon** [comment]
That worked! Thanks again @balazsorban44
