### ISSUE TITLE
Update in folder structure of API Route

### ISSUE THREAD

**Issue by prathmesh796** [nextauthjs/next-auth#11907]
### What is the improvement or update you wish to see?

> Add API route

To add NextAuth.js to a project create a file called route.js in app/api/auth/[...nextauth]. This contains the dynamic route handler for NextAuth.js which will also contain all of your global NextAuth.js configurations.

`
//pages/api/auth/[...nextauth]/route.js
import NextAuth from "next-auth"
import GithubProvider from "next-auth/providers/github"

export const authOptions = {
  // Configure one or more authentication providers
  providers: [
    GithubProvider({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET,
    }),
    // ...add more providers here
  ],
}

export default NextAuth(authOptions)
`

### Is there any context that might help us understand?

Actually in Next.js 14, we cannot create an api file called as [...nextauth].js. To have a api logic working in the project we have write it in the file named as route.js located inside the api directory.

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/getting-started/example

**Comment by balazsorban44** [comment]
You can continue using Pages Router in any version of Next.js, and as such the documented code is correct.
