### ISSUE TITLE
Custom Login Page Error Handling?

### ISSUE THREAD

**Issue by Lightgaming** [nextauthjs/next-auth#1192]
I have a **custom login page** that uses the signIn method (LDAP Credential Provider) which works perfectly. 
**When the wrong credentials are entered the user is redirected to an Error page, which I don't want.**
I don't want this error redirect.
![image](https://user-images.githubusercontent.com/18364007/105645239-a8820580-5e9a-11eb-872d-b662eeb269b0.png)

Is there a way to use the signIn method like this?:

![image](https://user-images.githubusercontent.com/18364007/105645166-2d205400-5e9a-11eb-8582-a3956d20408b.png)

Or maybe something similar, so I can handle the error myself?

**Comment by balazsorban44** [comment]
You could try creating a custom error page as well? you will receive the type of error as a query parameter to handle the different cases

**Comment by Lightgaming** [comment]
I could do that, this would solve my redirect problem since it's just a route, but how would I get the error message back in my React Login component? 

I want it that way: When the user clicks login and the creds are wrong I get the error in my React Logic and show some nicely formatted error message in the form, so the user knows what's wrong

**Comment by balazsorban44** [comment]
Duplicate of #989

**Comment by balazsorban44** [comment]
@Lightgaming follow #1219 :wink:

**Comment by Taha-mlaiki** [comment]
@Lightgaming  did you resolve your problem , because I'm facing it to right now
??

**Comment by Lightgaming** [comment]
@Taha-mlaiki unfortunately I don't really know. It was a school project and I don't have access to the code anymore
