### ISSUE TITLE
TypeError: Cannot read property 'session' of undefined

### ISSUE THREAD

**Issue by sunrunner4kr-simon** [nextauthjs/next-auth#1196]
**Your question**
The pageProps object I suspect is empty, and so is undefined. However it's being exported with getServerSideProps

**What are you trying to do**
I'm following this tutorial linked from the nextauth website: - https://dev.to/ndom91/adding-authentication-to-an-existing-serverless-next-js-app-in-no-time-with-nextauth-js-192h to set up next auth on my existing app.

Have the Providers defined, and the Provider wrapped around my App.
And I'm using getServerSideProps in my server.js

**Reproduction**
Here is my repo: - https://github.com/sunrunner4kr-simon/EchosDeparted
let me know if you want access

And my /src/App.js where the error is triggered

```
import React from 'react';
import './App.css';

import { BrowserRouter as Router, Switch, Route } from 'react-router-dom';
import Home from './pages';
import SigninPage from './pages/signin';
import { Provider } from 'next-auth/client'

function App({Component, pageProps}) {
  return (
    <Provider session={pageProps.session}>
      <Component {...pageProps} />
      <Router>
        <Switch>
          <Route path='/' component={Home} exact />
          <Route path='/signin' component={SigninPage} exact />
        </Switch>
      </Router>
    </Provider>
  );
}

export default App;
```

Appreciate any help!

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Your file should be in `pages/_app.js` nor `src/App.js`. I am also not sure why you would use `react-router`. Are you building a Next.js project at all? Currently `next-auth` will only work if you build a Next.js application

**Comment by sunrunner4kr-simon** [comment]
🤦‍♂️ I've been using a react app...no wonder I'm having problems. Sorry for wasting your time @balazsorban44

**Comment by balazsorban44** [comment]
It's fine 😅. Hope you will find a good solution.

If you wish to convert your app to Next.js, have a look at this: https://nextjs.org/docs/migrating/incremental-adoption

**Comment by sunrunner4kr-simon** [comment]
It's a bit confusing as a beginner, people use node and react interchangeably.
And the examples I've seen don't match the _app.js structure

I've seen: -
/app.js with examples of Node and Express
/pages/_app.js with the Node.js tutorials
/src/App.js with react and node

https://medium.com/better-programming/introduction-to-node-js-create-your-first-web-app-96b705c28023
https://closebrace.com/tutorials/2017-03-02/creating-a-simple-restful-web-app-with-nodejs-express-and-mongodb
https://www.youtube.com/watch?v=W-sZo6Gtx_E&t=426s
