### ISSUE TITLE
Neo4J Edge compatibility Docs

### ISSUE THREAD

**Issue by DatScreamer** [nextauthjs/next-auth#11981]
### What is the improvement or update you wish to see?

Edge Compatibility listed on Adapter pages for each adapter, or a link to a chart or spreadsheet or something with the edge compatibilities for each adapter in the current version at least

### Is there any context that might help us understand?

The page below mentions edge compatibility in regards to the database adapters
https://authjs.dev/getting-started/migrating-to-v5

Naturally I went to the page for the adapter I need and it's missing any mention of edge compatibility. 
https://authjs.dev/getting-started/adapters/neo4j

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/adapters/neo4j

**Comment by balazsorban44** [comment]
Adapters themselves are compatible. Peer dependencies for these adapters might not be. It makes more sense for them to document compatibility.

for example prisma has these

https://www.prisma.io/blog/prisma-orm-support-for-edge-functions-is-now-in-preview

https://www.prisma.io/docs/orm/prisma-client/deployment/edge/overview


We have this in the migration guide 

> Please follow up with your library/database/ORM’s maintainer to see if they are planning to support the Edge runtime/infrastructure.
