### ISSUE TITLE
Create a server-side only API function that gets authenticated user session info out of the atabase using the session token in the cookie.

### ISSUE THREAD

**Issue by theniallriver** [nextauthjs/next-auth#1199]
Currently, the recommended and only supported way of getting a session is via the `/api/auth/session` endpoint, which is exposed via the `getSession` and `session` client API functions. It is unnecessary to call another server side endpoint when you are already in the server. Additionally, when doing this in a serverless environment, it creates an unnecessary lambda execution.

It would be better for performance and for my wallet if I could just get the session directly from the database, rather than fetching a separate endpoint, and running a separate lambda function.

**Comment by balazsorban44** [comment]
See the reasoning behind this here:

https://github.com/nextauthjs/next-auth/issues/947#issuecomment-762150858
