### ISSUE TITLE
OpenId Support

### ISSUE THREAD

**Issue by Wolfleader101** [nextauthjs/next-auth#1201]
**Summary of proposed feature**
I would like next-auth to support OpenId for login types such as steam.

**Purpose of proposed feature**
Right now there isn't really any way of making a steam log in serverless and it would be awesome to be able to use in nextjs API routes.

**Detail about proposed feature**
Supporting OpenId

**Potential problems**
The only issue is there won't be a fallback email.

**Describe any alternatives you've considered**
passport-steam, however, I didn't get this working serverless in next,

*Please indicate if you are willing and able to help implement the proposed feature.*
Yes I am.

**Comment by balazsorban44** [comment]
Hi there, we already support a subset of openid, since it has a nice overlap with OAuth 2.0. Any particular feature you are missing that we don't support yet?

**Comment by Wolfleader101** [comment]
> Hi there, we already support a subset of OpenID, since it has a nice overlap with OAuth 2.0. Any particular feature you are missing that we don't support yet?

Hey,
I couldn't find any support for specifically OpenID 2.0 which is what steam login uses.
![image](https://user-images.githubusercontent.com/25214835/106068008-c7062c00-613a-11eb-966a-12959961a319.png)

Anyway, this could be supported? I could not find any support for it online, I tried using passport-JS however that doesn't work with API Routes

**Comment by balazsorban44** [comment]
do you mean OAuth 2.0 or OpenID Connect?

do you have a link to some documentation?

**Comment by Wolfleader101** [comment]
> do you mean OAuth 2.0 or OpenID Connect?
> 
> do you have a link to some documentation?
> 
> UPDATE:
> I found this:
> https://openid.net/developers/libraries/obsolete/
> 
> It sounds like OpenID 2.0 is now obsolete, and so I'm not sure we will support it consciously.

Oh well that is super annoying, I guess there isn't a way to use nextauth with steam login then?

**Comment by balazsorban44** [comment]
we support oauth 1, 2, and openid connect (successor of openid 2). you point me to some documentation that says Steam supports any of these, than there is no problem. Please look at this section in the docs https://next-auth.js.org/configuration/providers#using-a-custom-provider

**Comment by rodilo** [comment]
> we support oauth 1, 2, and openid connect (successor of openid 2). you point me to some documentation that says Steam supports any of these, then there is no problem. Please look at this section in the docs https://next-auth.js.org/configuration/providers#using-a-custom-provider

HI, @balazsorban44  do you have some example of how to set up a custom provider for the opened connect? I'm converting angular app that's using open id connect login, and the configuration is an object that has a structure like this:

```
      stsServer: '',
      redirectUrl: '',
      postLogoutRedirectUri: window.location.origin,
      clientId: '',
      scope: 'openid offline_access',
      responseType: 'code',
      silentRenew: true,
      silentRenewUrl: `${window.location.origin}/silent-renew.html`,
```

How can I achieve this via a custom provider?

**Comment by Wolfleader101** [comment]
> we support oauth 1, 2, and openid connect (successor of openid 2). you point me to some documentation that says Steam supports any of these, then there is no problem. Please look at this section in the docs https://next-auth.js.org/configuration/providers#using-a-custom-provider

Steam does not actually support oAuth or opened connect, unless you are a game developer, for using it as site login you must use the old openid 2
