### ISSUE TITLE
Use new prisma adapter  and get  [get_user_by_provider_account_id_error] [{"clientVersion":"2.15.0"}] 

### ISSUE THREAD

**Issue by mynlexi** [nextauthjs/next-auth#1202]
**Your question**
How do i get rid of this error?

in the issue #1166, the consensus seems to be that this issue is solved with the canary build.

my error message:
[next-auth][error][get_user_by_provider_account_id_error] [{"clientVersion":"2.15.0"}] 
https://next-auth.js.org/errors#get_user_by_provider_account_id_error
[next-auth][error][oauth_callback_handler_error] [{}] 
https://next-auth.js.org/errors#oauth_callback_handler_error

**What are you trying to do**
authenticating with githubconnect

**Reproduction**

My versions:
"@prisma/cli": "^2.15.0",
    "@prisma/client": "^2.15.0",
    "next": "10.0.5",
    "next-auth": "^3.2.0-canary.36",

My schema:
```prisma
model Quiz {
  id        Int      @default(autoincrement()) @id
  title     String
  question  String
  points    Int
  answer_1  String 
  
}

model Account {
  id                 Int       @id @default(autoincrement())
  userId             Int
  providerType       String
  providerId         String
  providerAccountId  String
  refreshToken       String?
  accessToken        String?
  accessTokenExpires DateTime?
  createdAt          DateTime  @default(now())
  updatedAt          DateTime  @updatedAt
  user               User      @relation(fields: [userId], references: [id])

  @@unique([providerId, providerAccountId])
}

model Session {
  id           Int      @id @default(autoincrement())
  userId       Int
  expires      DateTime
  sessionToken String   @unique
  accessToken  String   @unique
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
  user         User     @relation(fields: [userId], references: [id])
}

model User {
  id            Int       @id @default(autoincrement())
  name          String?
  email         String?   @unique
  emailVerified DateTime?
  image         String?
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt
  accounts      Account[]
  sessions      Session[]
  quizs         Quiz[]
}

model VerificationRequest {
  id         Int      @id @default(autoincrement())
  identifier String
  token      String   @unique
  expires    DateTime
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
}
```

from the adapter doc [here](https://github.com/nextauthjs/adapters/blob/canary/packages/prisma/README.md)

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [x] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Seems to be the same as https://github.com/nextauthjs/next-auth/issues/1191#issuecomment-767254863

Logging is a bit busted on canary at the moment, it is a bit unfortunate in this case. I'll have to prioritize to fix that, because, without the actual error, I cannot guess what the problem is.

**Comment by balazsorban44** [comment]
@mynlexi latest canary should provide better log messages now!

**Comment by mynlexi** [comment]
with canary.42:
Code:

`
  [next-auth][error][get_user_by_provider_account_id_error] 
  https://next-auth.js.org/errors#get_user_by_provider_account_id_error PrismaClientValidationError: 
  Invalid `prisma.account.findUnique()` invocation:
  
  {
    where: {
      compoundId: '2d582dc89e29d512d929e610ecbf7db3031af4ffa44eeeb7506e225783a34e27'
      ~~~~~~~~~~
    }
  }
  
  Unknown arg `compoundId` in where.compoundId for type AccountWhereUniqueInput. Available args:
  
  type AccountWhereUniqueInput {
    id?: Int
    providerId_providerAccountId?: AccountProviderIdProviderAccountIdCompoundUniqueInput
  }
  
  
      at Document.validate (/home/mynlexi/code/mynlexi/next-stuff/equiz/node_modules/@prisma/client/runtime/index.js:76239:19)
      at NewPrismaClient._executeRequest (/home/mynlexi/code/mynlexi/next-stuff/equiz/node_modules/@prisma/client/runtime/index.js:78067:17)
      at /home/mynlexi/code/mynlexi/next-stuff/equiz/node_modules/@prisma/client/runtime/index.js:78002:52
      at AsyncResource.runInAsyncScope (node:async_hooks:197:9)
      at NewPrismaClient._request (/home/mynlexi/code/mynlexi/next-stuff/equiz/node_modules/@prisma/client/runtime/index.js:78002:25)
      at Object.then (/home/mynlexi/code/mynlexi/next-stuff/equiz/node_modules/@prisma/client/runtime/index.js:78122:39)
      at processTicksAndRejections (node:internal/process/task_queues:93:5) {
    clientVersion: '2.15.0'
  }
  [next-auth][error][oauth_callback_handler_error] 
  https://next-auth.js.org/errors#oauth_callback_handler_error Error: GET_USER_BY_PROVIDER_ACCOUNT_ID_ERROR
      at /home/mynlexi/code/mynlexi/next-stuff/equiz/node_modules/next-auth/dist/adapters/prisma/index.js:166:35
      at Generator.throw (<anonymous>)
      at asyncGeneratorStep (/home/mynlexi/code/mynlexi/next-stuff/equiz/node_modules/next-auth/dist/adapters/prisma/index.js:16:103)
      at _throw (/home/mynlexi/code/mynlexi/next-stuff/equiz/node_modules/next-auth/dist/adapters/prisma/index.js:18:291)
      at processTicksAndRejections (node:internal/process/task_queues:93:5)

`

So i guess it looks for an identifier, Prisma adapter gives back the compound id, but that's not what next-auth wanted?

Thanks for the ongoing concern!

**Comment by balazsorban44** [comment]
So I see you linked to the new adapters repo Prisma schema changes.
https://github.com/nextauthjs/adapters/blob/canary/packages/prisma/README.md

The `canary` release does not replace the current Prisma adapter, because it would be a breaking change.
Rather the adapters repo contains a new Prisma adaptation that might take over the current one at a later point.

If you want to try out the new adapter, you can add it to your project with `npm install @next-auth/prisma-adapter`, and `import Prisma from "@next-auth/prisma-adapter"`.

Otherwise you should be using Prisma with `canary` as before.

@williamluke4 could you verify this?

**Comment by mynlexi** [comment]
I works with the current provided schema, like you said, and current prisma adapter.
Thanks a lot for the help, typically mistake of changing 10 things if something doesn't work  -_-.

If you want, just so you know for sure I can also try using the optional prisma adapter + corresponding schema?

**Comment by balazsorban44** [comment]
We are going to test the new Prisma adapter before we deem it stable, so it is not necessary, but thank you for your offer! You can test it if you want anyway, and report back if you had any issues.

**Comment by alteredorange** [comment]
It looks like this is still happening, I'm on the latest canary build (3.3.0-canary.11), but I get the `[error][get_user_by_provider_account_id_error]` error and the following details:

```
Invalid prisma.account.findUnique() invocation:
{
  where: {
    compoundId: '768dea23534d5f3c73e3ae6c86e205b911e9e0a6e2e9816cd9ffc0732c68a6f1'
    ~~~~~~~~~~
  }
}
Unknown arg `compoundId` in where.compoundId for type AccountWhereUniqueInput. Available args:
type AccountWhereUniqueInput {
  id?: Int
  providerId_providerAccountId?: AccountProviderIdProviderAccountIdCompoundUniqueInput
}
```

Even though the schema is specifying compoundId as unique, it doesn't seem to take. It looks like this is an sqlite specific issue on the Prisma side (https://www.prisma.io/docs/guides/general-guides/database-workflows/unique-constraints-and-indexes/sqlite), but an easy fix is to add an index for `compoundId`.

Doing so seems to fix the error, see revised model below:
```
model Account {
    id                 Int       @id @default(autoincrement())
    compoundId         String    @unique @map(name: "compound_id")
    userId             Int       @map(name: "user_id")
    providerType       String    @map(name: "provider_type")
    providerId         String    @map(name: "provider_id")
    providerAccountId  String    @map(name: "provider_account_id")
    refreshToken       String?   @map(name: "refresh_token")
    accessToken        String?   @map(name: "access_token")
    accessTokenExpires DateTime? @map(name: "access_token_expires")
    createdAt          DateTime  @default(now()) @map(name: "created_at")
    updatedAt          DateTime  @default(now()) @map(name: "updated_at")


    @@index([providerAccountId], name: "providerAccountId")
    @@index([providerId], name: "providerId")
    @@index([userId], name: "userId")
    //Add this index
    ---> @@index([compoundId], name: "compoundId")
    @@map(name: "accounts")
}
```

Just in case anyone happens to google this issue and is using SQlite :)

**Comment by sir-dunxalot** [comment]
@balazsorban44 I experienced this issue and it was resolved with `@next-auth/prisma-adapter`. My implementation seems to be working as follows:

```js
import NextAuth from 'next-auth';
import Providers from 'next-auth/providers';
import PrismaAdapter from '@next-auth/prisma-adapter';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export default NextAuth({
  adapter: PrismaAdapter({ prisma }),
  secret: process.env.authSecret,

  providers: [
    Providers.Google({
      clientId: process.env.googleClientID,
      clientSecret: process.env.googleClientSecret,
    }),
  ],
});
```

The only 'gotcha' was not realizing `PrismaAdapter()` required an object with `prisma` passed in.

**Comment by huynhminhcanh** [comment]
************

**Comment by huynhminhcanh** [comment]
- [ ] [_![image](https://user-images.githubusercontent.com/79802828/109447426-380c6c80-7a76-11eb-9bc0-29a7c8a7545d.jpeg)_]()

**Comment by thecodelearner** [comment]
So I tried what @sir-dunxalot suggested [here](https://github.com/nextauthjs/next-auth/issues/1202#issuecomment-787603137) but now I'm faced with another error:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/lib/errors' is not defined by "exports" in /Users/sahil/code/carbon-ghost/node_modules/next-auth/package.json
    at new NodeError (node:internal/errors:363:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:321:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:546:3)
    at resolveExports (node:internal/modules/cjs/loader:478:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:518:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:27)
    at Function.mod._resolveFilename (/Users/sahil/code/carbon-ghost/node_modules/next/dist/build/webpack/require-hook.js:4:1784)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/sahil/code/carbon-ghost/node_modules/@next-auth/prisma-adapter/dist/index.js:54:16)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

@sir-dunxalot did you face any of this? Thanks for the help, much appreciated.
