### ISSUE TITLE
Provider in _app.tsx not working with Custom signIn mehtod

### ISSUE THREAD

**Issue by Lightgaming** [nextauthjs/next-auth#1205]
I am using a custom Login Page with the signIn function.

I used the useSession hook in my _app.tsx before but now I want to switch to the Provider method so I don't have too many api/session requests. 

I am using Material-Ui, Recoil and Use-Dark-Mode in my _app.tsx
![image](https://user-images.githubusercontent.com/18364007/106055934-59cca980-60ee-11eb-8be0-7e706c6f53a7.png)
![image](https://user-images.githubusercontent.com/18364007/106055839-399cea80-60ee-11eb-880e-e1131bc6dca9.png)

**When I try to log in it just keeps refreshing the page and when I log the pageProps.session object it retunes undefined**
Please Help

**Comment by balazsorban44** [comment]
From the information provided, it is hard to guess what is happening. Do you maybe have a complete reproduction/link to your repo? Remember, `pageProps.session` will only be defined, if you somehow passed it to `pageProps`, like from `getServerSideProps` or `getInitialProps`

**Comment by Lightgaming** [comment]
Well I was trying to follow this tutorial: https://next-auth.js.org/getting-started/client#provider
It doesn't mention anything about me having to get the session via getServerSideProps/getInitialProps

**Comment by balazsorban44** [comment]
Yes it's true. (That's why I created this issue https://github.com/nextauthjs/next-auth/issues/1132) 

 Although you have to understand that it must come from somewhere. 😊
