### ISSUE TITLE
args removed from signIn

### ISSUE THREAD

**Issue by amaron09** [nextauthjs/next-auth#1206]
**Your question**

I've been trying the carnary version (3.2.0-canary.36) of Next-auth in order to resolve the oAuth State problem. However, I've noticed that the signIn function is no longer working in the carnary version, at least in the way I use it. The argument is simply not registered. When tracking the github changelog I could see that ...args has been removed from the body. Why was it removed and how should I send in username and password now?

This is how I use the signIn:
```javascript
signIn('credentials, { username, password})
```

**What are you trying to do**

Trying to login with credentials using the signIn function

**Reproduction**

```javascript
signIn('credentials, { username, password})
```
 signIn no longer registers username and password in 3.2.0-canary.36

Can be tracked to changes in signIn function where ...args has been removed from the body

3.2.0-canary.36
```javascript
 // If is any other provider type, POST to provider URL with CSRF Token,
    // callback URL and any other parameters supplied.
    const fetchOptions = {
      method: 'post',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
      },
      body: _encodedForm({
        csrfToken: await getCsrfToken(),
        callbackUrl: callbackUrl,
        json: true
      })
    }
```

3.1.0 Main
```javascript
// If is any other provider type, POST to provider URL with CSRF Token,
    // callback URL and any other parameters supplied.
    const fetchOptions = {
      method: 'post',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
      },
      body: _encodedForm({
        ...args,
        csrfToken: await getCsrfToken(),
        callbackUrl: callbackUrl,
        json: true
      })
    }
```
**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
🤦 apologies @amaron09! Should be fixed soon.
