### ISSUE TITLE
Microsoft Entra

### ISSUE THREAD

**Issue by martgra** [nextauthjs/next-auth#12072]
### What is the improvement or update you wish to see?

Microsoft Entra example for authjs is currently wrong for ```tenantId```. The type has no such attribute, instead there is ```issuer```

Example for https://authjs.dev/getting-started/providers/microsoft-entra-id

```ts
import NextAuth from "next-auth"
import MicrosoftEntraID from "next-auth/providers/microsoft-entra-id"
 
const { handlers, auth, signIn, signOut } = NextAuth({
  providers: [
    MicrosoftEntraID({
      clientId: process.env.AUTH_MICROSOFT_ENTRA_ID_ID,
      clientSecret: process.env.AUTH_MICROSOFT_ENTRA_ID_SECRET,
      tenantId: process.env.AUTH_MICROSOFT_ENTRA_ID_TENANT_ID,
    }),
  ],
})
```
Documentation should be updated accordingly.

### Is there any context that might help us understand?

This is how I got Entra working:

```ts
  providers: [
    MicrosoftEntraID({
      clientId: AZURE_ENTRA_CLIENT_ID,
      clientSecret: AZURE_ENTRA_CLIENT_SECRET,
      issuer: `https://login.microsoftonline.com/${AZURE_ENTRA_TENANT_ID}/v2.0`,
    })
  ],
``` 

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/providers/microsoft-entra-id

**Comment by martgra** [comment]
Its on my bucket-list of this year to have a PR merged for a open source repo. Would love to get to contribute to this.

**Comment by rfverbruggen** [comment]
I've ran into this issue without knowing it existed and created a PR. @martgra feel free to contribute to the PR is you want!

**Comment by balazsorban44** [comment]
Fixed in https://github.com/nextauthjs/next-auth/pull/12103

**Comment by rfverbruggen** [comment]
You are right, I got it working with Entra External ID by using the following:

```javascript
providers: [
    MicrosoftEntraID({
      clientId: process.env.AUTH_MICROSOFT_ENTRA_ID_ID,
      clientSecret: process.env.AUTH_MICROSOFT_ENTRA_ID_SECRET,
      issuer: process.env.AUTH_MICROSOFT_ENTRA_ID_ISSUER,
      token: process.env.AUTH_MICROSOFT_ENTRA_ID_TOKEN,
      //userinfo: process.env.AUTH_MICROSOFT_ENTRA_ID_USERINFO,
      authorization: {
        url: process.env.AUTH_MICROSOFT_ENTRA_ID_AUTHORIZATION_URL,
        params: {
          scope: "openid profile email offline_access",
        },
      },
    }),
  ],
  session: {
    strategy: "jwt",
  },
```

With the following in my environment variables (removed my own tenant values):

```
# Entra ID authn/authz configuration
AUTH_MICROSOFT_ENTRA_ID_ID=""
AUTH_MICROSOFT_ENTRA_ID_SECRET= ""
AUTH_MICROSOFT_ENTRA_ID_TENANT_ID=""
AUTH_MICROSOFT_ENTRA_ID_TENANT_SUB_DOMAIN=""
AUTH_MICROSOFT_ENTRA_ID_ISSUER=https://$AUTH_MICROSOFT_ENTRA_ID_TENANT_ID.ciamlogin.com/$AUTH_MICROSOFT_ENTRA_ID_TENANT_ID/v2.0
AUTH_MICROSOFT_ENTRA_ID_TOKEN=https://$AUTH_MICROSOFT_ENTRA_ID_TENANT_SUB_DOMAIN.ciamlogin.com/$AUTH_MICROSOFT_ENTRA_ID_TENANT_ID/oauth2/v2.0/token
AUTH_MICROSOFT_ENTRA_ID_USERINFO=https://graph.microsoft.com/oidc/userinfo
AUTH_MICROSOFT_ENTRA_ID_AUTHORIZATION_URL=https://$AUTH_MICROSOFT_ENTRA_ID_TENANT_SUB_DOMAIN.ciamlogin.com/$AUTH_MICROSOFT_ENTRA_ID_TENANT_ID/oauth2/v2.0/authorize
```

This one is now specific to Entra External ID (ciamlogin.com) and not using Entra ID (workforce tenant).
The docs need to be updated to support both cases IMO.

**Comment by mz8i** [comment]
@balazsorban44 could we reopen this please? I feel it needs more discussion (see the above messages)
