### ISSUE TITLE
Module not found: Can't resolve '@node-rs/argon2-wasm32-wasi'

### ISSUE THREAD

**Issue by vladdg-dev** [nextauthjs/next-auth#12138]
### Provider type

Credentials

### Environment

```
 System:
    OS: Linux 5.15 Linux Mint 21 (Vanessa)
    CPU: (8) x64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
    Memory: 18.17 GB / 31.10 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 21.5.0 - ~/.nvm/versions/node/v21.5.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v21.5.0/bin/yarn
    npm: 10.8.3 - ~/.nvm/versions/node/v21.5.0/bin/npm
    pnpm: 9.12.3 - ~/.nvm/versions/node/v21.5.0/bin/pnpm
  Browsers:
    Chrome: 130.0.6723.58
    Chromium: 129.0.6668.100
  npmPackages:
    @auth/prisma-adapter: ^2.7.2 => 2.7.2 
    next: 15.0.1 => 15.0.1 
    next-auth: ^5.0.0-beta.25 => 5.0.0-beta.25 
    react: 19.0.0-rc-69d4b800-20241021 => 19.0.0-rc-69d4b800-20241021 
```

### Reproduction URL

https://github.com/vladdg-dev/next-auth-bug

### Describe the issue

I'm using the `@node-rs/argon2` package to hash and verify my passwords, and if I use `argon2.verify` inside the `authorize` function in `auth.config.ts` I get the following error:
```
Module not found: Can't resolve '@node-rs/argon2-wasm32-wasi'
> 1 | export * from '@node-rs/argon2-wasm32-wasi'
    | ^
  2 |
  ```
 The same is with the package `argon2` where the error is the following:
  ```
  UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme). Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
```
I have verified the `verifiyPassword` function outside the authorize function, and it's working just fine. However it's not working inside `authorize`. Something like `bcryptjs` works, but I want to use `@node-rs/argon2` or `argon2`.

### How to reproduce

Execute `npm run dev` and you'll be met with the error

### Expected behavior

To work without errors

**Comment by balazsorban44** [comment]
see https://authjs.dev/guides/edge-compatibility

**Comment by lorenzobalzani** [comment]
I still don’t quite understand how to solve the problem.
