### ISSUE TITLE
Something missing in .github/CONTRIBUTING?

### ISSUE THREAD

**Issue by dowski** [nextauthjs/next-auth#12144]
### What is the improvement or update you wish to see?

I'm trying to follow the instructions in [`.github/CONTRIBUTING`](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md#setting-up-local-environment) to set up an environment to work on a new integration. Following the instructions seems to work all the way up until I open a browser pointing at `http://localhost:3000/`. At that point, I get this error:

```
 GET / 404 in 2ms
 ⨯ ./pages/_app.tsx:1:1
Module not found: Can't resolve 'next-auth/react'
> 1 | import { SessionProvider, signIn, signOut, useSession } from "next-auth/react"
    | ^
  2 | import "./styles.css"
  3 | import { Header } from "components/header"
  4 | import styles from "components/header.module.css"

https://nextjs.org/docs/messages/module-not-found
```

### Is there any context that might help us understand?

Here are some key versions and other info about commands used during setup:

```
% node --version
v18.18.0
% pnpm --version
9.12.3
% which node
/Users/christian/.nvm/versions/node/v18.18.0/bin/node
% which pnpm
/opt/homebrew/bin/pnpm
```

### Does the docs page already exist? Please link to it.

https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md

**Comment by dowski** [comment]
After filing, I thought maybe the issue was my `node` binary was installed with `nvm` and `pnpm` was from Homebrew. I uninstalled the Homebrew version and reinstalled everything in `next-auth` after running `corepack enable pnpm`. That gave me a `pnpm` adjacent to my `nvm` installed `node` binary:

```
% which pnpm
/Users/christian/.nvm/versions/node/v18.18.0/bin/pnpm
```

Unfortunately, I get the same error.

**Comment by balazsorban44** [comment]
It happens intermittently, you might need to manually build `packages/next-auth` first. `pnpm dev` is supposed to build it though.

**Comment by dowski** [comment]
Yes, I had to manually run `pnpm build` in `packages/next-auth`. Otherwise none of the TypeScript in `packages/next-auth/src` gets compiled to JS.
