### ISSUE TITLE
While specifing "samesite" and "secure" cookie flags, only one applies

### ISSUE THREAD

**Issue by forefy** [nextauthjs/next-auth#1217]
**Describe the bug**
Using auth-next v5, by specifing both "secure" and "samesite" cookie security flags, only secure applies.

Although if I just supply the "samesite" cookie without the "secure" one, the "samesite" is added.

It seems the bug is that when two cookie security attributes are added, only one is being picked.

**Steps to reproduce**
Simply use this config:
```
 auth: {
    cookie: {
      options: {
        sameSite: 'Strict',
        secure: true
      }
    }
}
```
and look at the Cookie storage

**Expected behavior**
Expected behavior is that nuxt will add both "secure" and "samesite" attributes specified to the cookie storage items it stores.

**Feedback**

 Found the documentation helpful
- [x] Could not find relevant documentation
- [x] Did not find the example project helpful

**Comment by balazsorban44** [comment]
After googling, I am pretty sure on the wrong repo here.

https://www.npmjs.com/package/@nuxtjs/auth-next

You should go to https://github.com/nuxt-community/auth-module#readme
