### ISSUE TITLE
Entra ID provider causes JWTInvalid: JWTs must use Compact JWS serialization, JWT must be a string error

### ISSUE THREAD

**Issue by ay13** [nextauthjs/next-auth#12187]
### Provider type

_This is using **Entra ID** provider. Entra wasnt an option in the drop down so I chose AD_
Azure Active Directory

### Environment

```
  System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 27.52 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.18.0 - ~/.nvm/versions/node/v20.18.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.18.0/bin/yarn
    npm: 10.8.2 - ~/.nvm/versions/node/v20.18.0/bin/npm
    pnpm: 9.9.0 - ~/.nvm/versions/node/v20.18.0/bin/pnpm
  Browsers:
    Chrome: 130.0.6723.92
    Edge: 130.0.2849.68
    Safari: 17.5
  npmPackages:
    @auth/sveltekit: ^1.7.3 => 1.7.3
```

### Reproduction URL

https://github.com/ay13/auth-entra

### Describe the issue

After the initial auth process it redirects back to the app and displays the message:

>  Server error
> 
> There is a problem with the server configuration.
> 
> Check the server logs for more information.

in the console I see the error:

> [auth][details]: {
> "provider": "microsoft-entra-id"
> }
> [auth][error] CallbackRouteError: Read more at [https://errors.authjs.dev#callbackrouteerror](https://errors.authjs.dev/#callbackrouteerror)
> [auth][cause]: JWTInvalid: JWTs must use Compact JWS serialization, JWT must be a string

### How to reproduce

1. New SvelteKit project using `npx sv create`
2. Set up SvelteKit integration using directions from https://authjs.dev/getting-started/installation?framework=SvelteKit
3. Set up the Entra ID provider using https://authjs.dev/getting-started/providers/microsoft-entra-id
4. Try to sign in.

### Expected behavior

I expected to authenticate without an error

**Comment by diego-gt** [comment]
Hi @ay13 ! 
I ran into this issue as well, my specific cause was that I was not setting the issuer url correctly. 

Assuming that you're trying to use a Microsoft 365 business plan for this, please try to verify that your issuer variable is set to `https://login.microsoftonline.com/{tenantId}/v2.0`, you can reference the docs here https://learn.microsoft.com/en-us/entra/identity-platform/v2-protocols-oidc#find-your-apps-openid-configuration-document-uri. 

Hopefully that helps.

**Comment by ay13** [comment]
Thanks for the reply @diego-gt , I verified that my issuer is set up the correct way. Same issue.

**Comment by ay13** [comment]
Disregard this issue, it was my mistake. 

In the redirect section of Entra ID I set my redirect as a Single-page app, when I set it as a web app it worked correctly.

**Comment by warrantor** [comment]
Hi @ay13 
I've also been racking my brain on this for 3 days. 
Is this the proposed fix, setting the redirect as a web app?
Does everything work as expected?

Thanks!

**Comment by ay13** [comment]
@warrantor For me, setting the platform to `Web` worked and `Single-page application` did not. I believe Entra returns the token differntly based on which of those you select.
![image](https://github.com/user-attachments/assets/218ac83d-5bb5-40d0-b606-4e79af428486)

**Comment by diego-gt** [comment]
Glad you got it working!
Yes, the redirect should be set as a Web app instead of SPA, the Entra platform will provide different tokens (Access Tokens for SPAs vs ID Tokens for Web app) depending on that type.
It doesn't limit you to use only server components, it works on both. The way you access the session is different though.
Docs for app types: https://learn.microsoft.com/en-us/entra/identity-platform/v2-app-types

**Comment by brandonavant** [comment]
> Disregard this issue, it was my mistake. 
> 
> 
> 
> In the redirect section of Entra ID I set my redirect as a Single-page app, when I set it as a web app it worked correctly.

I'd like to confirm that this fixed the issue for me as well.

**Comment by yangyao1234** [comment]
> @warrantor For me, setting the platform to `Web` worked and `Single-page application` did not. I believe Entra returns the token differntly based on which of those you select. ![image](https://private-user-images.githubusercontent.com/72563/385040909-218ac83d-5bb5-40d0-b606-4e79af428486.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMTQ0MzUsIm5iZiI6MTczMzIxNDEzNSwicGF0aCI6Ii83MjU2My8zODUwNDA5MDktMjE4YWM4M2QtNWJiNS00MGQwLWI2MDYtNGU3OWFmNDI4NDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDA4MjIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4ZTc1NzFkZWM3MmM5NDEzOTYxZmE3ODVhZmM2MDZhNzY0NGYzMmU1NGQ1MTA1YzU1OWM1NmI2ZmQxMjlmNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.z_NK3Usnu1-rdltkspHK2AWO6eLcJOssQFMjgj2AbYo)
> 
> How my Authentication settings look now. ![image](https://private-user-images.githubusercontent.com/72563/385041490-c8c5cfe6-61b1-4437-9385-56a9cf8d62ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMTQ0MzUsIm5iZiI6MTczMzIxNDEzNSwicGF0aCI6Ii83MjU2My8zODUwNDE0OTAtYzhjNWNmZTYtNjFiMS00NDM3LTkzODUtNTZhOWNmOGQ2MmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDA4MjIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MzBlMDI2NGEyZTUxMGE5ODI5NTY1NWE1Y2ExNjM0MTY0ZWQ2ODQxZTYwNTIzMWQ2ZDdhODdlZjgwMGVjMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6EPvPb4R4zR4duu4eeScZWV4drfBTY-caPhrTIhBlcc)

great . it works ,

**Comment by sicarius97** [comment]
@yangyao1234 @ay13 @brandonavant Are you guys on next auth v5 or v4? Im using nextjs but I am having issues with this as well, even when set up as a web app

**Comment by brandonavant** [comment]
> @yangyao1234 @ay13 @brandonavant Are you guys on next auth v5 or v4? Im using nextjs but I am having issues with this as well, even when set up as a web app

@sicarius97 , I am using v5 but will be moving down to v4 as v5 is still beta.

For v5, the fix was setting the platform to `web`.

**Comment by jonaddams** [comment]
I was getting the same error in the latest release. I can confirm choosing Web instead of SPA in the App registration/Platform configurations section resolved the error.

**Comment by rubenmamo** [comment]
I have it set as Web and not SPA but I am still getting this error. I'm using v 5.0.0-beta.25

**Comment by YanaYahello23** [comment]
@rubenmamo Check what you are using for AUTH_MICROSOFT_ENTRA_SECRET. It should be the secret value, not the ID. For me, this fixed the issue with the same version of NextAuth

**Comment by nemvince** [comment]
Also encountering this issue, I have double checked that all my values are correct, I have it set up as Web instead of SPA, etc. etc.

**Comment by KuyaKoya** [comment]
I am also encountering this issue though Im using azure-ad as my provider.
I have the correct secrets and set the redirect to web.
I got it working in local setup but when I deploy to AWS EB, I get the error.

**Comment by roybarber** [comment]
The fix for me in V5 beta was to ensure the following:

````typescript
MicrosoftEntraID({
    clientId: process.env.AUTH_MICROSOFT_ENTRA_ID_ID,
    clientSecret: process.env.AUTH_MICROSOFT_ENTRA_ID_SECRET,
    issuer: process.env.AUTH_MICROSOFT_ENTRA_ID_ISSUER,
    authorization: {
        params: {
            scope: 'openid profile email' // make sure you ask for openid and have this configured on the API permissions tab of your entra app.
        }
    }
})
````

Then in my env i set:

````
AUTH_MICROSOFT_ENTRA_ID_ID="XXXXXX" // this is your "Application (client) ID" from the overview 
AUTH_MICROSOFT_ENTRA_ID_SECRET="XXXXXX" // this is the secret itself, not the ID of the secret, in "Certificates & secrets" use the "Value" not the "Secret ID"
AUTH_MICROSOFT_ENTRA_ID_ISSUER="https://login.microsoftonline.com/{TENANT_ID}/v2.0" // this has to be the URL including the tenant ID, this is your "Directory (tenant) ID from the overview tab, you can view your endpoints by clicking "Endppoints" on the overview tab
````

**Comment by howlettt** [comment]
I ran into this error when the secret configured in Azure had expired
