### ISSUE TITLE
Calling oauth url with http results in an error

### ISSUE THREAD

**Issue by anton-mauritzson** [nextauthjs/next-auth#12194]
### Environment

System:
    OS: macOS 14.2.1
    CPU: (10) x64 Apple M1 Max
    Memory: 810.92 MB / 64.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
  Browsers:
    Chrome: 130.0.6723.116
    Safari: 17.2.1
    Safari Technology Preview: 14.0.1
  npmPackages:
    next: 15.0.1 => 15.0.1 
    next-auth: ^5.0.0-beta.19 => 5.0.0-beta.25 
    react: 19.0.0-rc-69d4b800-20241021 => 19.0.0-rc-69d4b800-20241021 

### Reproduction URL

https://github.com/panva/oauth4webapi

### Describe the issue

after upgrading to next 15 and thus upgrading next-auth to beta-25 it seems that next-auth has upgraded its dependency of https://github.com/panva/oauth4webapi to 3.0 that included breaking changes to not allow by default requests from the module to insecure addresses.   https://github.com/panva/oauth4webapi/commit/4829da646e930f225732ec6a8e57721c103299b3

This commit seem to have something missing https://github.com/nextauthjs/next-auth/commit/0244513061d41656e8a65b5d3da4bfdf14c6bf7a i'm unable to trace why but we're getting an error from next-auth 
<img width="806" alt="image" src="https://github.com/user-attachments/assets/4bd15955-ab74-4faa-a457-baa3ed629b22">

We are running an oAuth server in a kubernetes cluster and the service calling the oauth server is in the same cluster so https is not required for us.

### How to reproduce

install next 15 and the latest next-auth 5.0.0-beta.25. 
set up a custom provider with http protocol for the token request.

### Expected behavior

looking at the code in the commit where oauth4webapi was upgraded, it seems that it should be allowed from this package.

**Comment by panva** [comment]
You can see in the specific [PR](https://github.com/nextauthjs/next-auth/pull/11994/files) that bumped oauth4webapi that all http-triggering requests made are configured to allow http requests.

**Comment by anton-mauritzson** [comment]
@panva yes i can see that, however that doesn't explain how oauth4webapi is throwing the error i'm getting. Because this error 
<img width="760" alt="image" src="https://github.com/user-attachments/assets/bbdc706d-2bb4-4334-a596-3d470ee9a396">
is from oauth4webapi
<img width="698" alt="image" src="https://github.com/user-attachments/assets/fbc565ba-7e27-418f-a975-99fb043c5a1c">

**Comment by panva** [comment]
Providing a source-map based stack trace would probably come a long way towards being able to identify the actual reason for this behaviour.
