### ISSUE TITLE
Hubspot provider - How to add scopes?

### ISSUE THREAD

**Issue by realtebo** [nextauthjs/next-auth#12229]
### What is the improvement or update you wish to see?

By default, Hubspot provider in sending request for only `oauth` scopes, and it's ok, it's the default for Hubspot.

But now we must receive more authorizations, so, in Hubspot, we added a new scop `settings.users.red`. 

I need to add this scope to what is sent when redirecting user to HS login page. 
How can I add more scopes?

### Is there any context that might help us understand?

Nothing to add 

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/providers/hubspot

**Comment by VovaGayduk42** [comment]
Hi
I solved this problem for keycloak provider
```
export const authConfig: NextAuthConfig = {
    providers: [
        Keycloak({
            authorization: {
                params: {
                    scope: "openid profile email xrm_back",
                },
            },
        }),
    ],
    ....
```

**Comment by realtebo** [comment]
I discovered or I think to understand that options are not deep merged. 
I must use

```
      authorization: {
        url: process.env.AUTH_PORTAL_ID
          ? `https://app.hubspot.com/oauth/${process.env.AUTH_PORTAL_ID}/authorize`
          : "https://app.hubspot.com/oauth/authorize",
        params: {
          scope: "oauth crm.objects.companies.read",
          client_id: process.env.AUTH_HUBSPOT_ID,
        },
      },
    }),
```

But cannot for example use only

```
      authorization: {
        params: {
          scope: "oauth crm.objects.companies.read",
        },
      },
    }),
```

because all defaults nested into `authorization` and `authorization.params` seems to be not merged
