### ISSUE TITLE
Minor issue with TypeScript and getToken function

### ISSUE THREAD

**Issue by ransomedesign** [nextauthjs/next-auth#1224]
**Describe the bug**
Hi, I found a minor bug with the getToken TS declaration, I believe the `raw` param should be a boolean as per the docs on your website, but it shows as an option String in jwt.d.ts so I had to pass `true` as `"true"`. I'm using v3.1.0

BTW many thanks for the lib, I'm just getting to grips with how to send JWTs to my backend to get protected user data, I think this should do the job.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [Y] Found the documentation helpful
* [Y] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
We currently let the community provide TypeScript. Check out the Readme for more info https://github.com/nextauthjs/next-auth#typescript

**Comment by ransomedesign** [comment]
@balazsorban44 Thanks, I didn't see that info in the README. At some point in the future may I can chip in with a pull request. This is a great project.

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth/pull/1223 some initial work and ideas how we should proceed. We get many feature request, and TS support is only one of them it would still require a lot of effort, not just for the actual migration, but maintenance. In the long run I hope someone with great TS skills will emerge from the community to help out with future issues also. Right now, any help is welcome!
