### ISSUE TITLE
`options.redirectTo` prop not working for SvelteKit `SignIn` component

### ISSUE THREAD

**Issue by Stadly** [nextauthjs/next-auth#12274]
### Environment

```
  System:
    OS: Linux 6.5 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 5.50 GB / 7.74 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.17.0 - ~/nvm/current/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.8.2 - ~/nvm/current/bin/npm
    pnpm: 9.11.0 - ~/nvm/current/bin/pnpm
  npmPackages:
    @auth/sveltekit: latest => 1.7.4 
    @sveltejs/kit: 2.5.7 => 2.5.7 
    svelte: 4.2.19 => 4.2.19 
```

### Reproduction URL

https://github.com/Stadly/reproduction/tree/authjs/signin-redirect

### Describe the issue

The user is not redirected to `/protected` after clicking the sign-in button and signing in.

### How to reproduce

```svelte
<script lang="ts">
  import { SignIn } from "@auth/sveltekit/components"
</script>
<SignIn options={{ redirectTo: "/protected" }}/>
```

If you try the reproduction URL, click the two sign-in buttons in the header and inspect the `authjs.callback-url` cookie. The button using the `SignIn` component does not set `/protected` in the cookie.

### Expected behavior

The user is redirected to `/protected` after signing in.

**Comment by NazgoooAtanasov** [comment]
Hello @Stadly,

I believe i have found a working workaround for now. I explained shorlty what it is in another issue #10135 
Reference to the comment https://github.com/nextauthjs/next-auth/issues/10135#issuecomment-2506641312
