### ISSUE TITLE
Cannot find module "next/server" in Vitest as of next-auth@5.0.0-beta-21 

### ISSUE THREAD

**Issue by Boonstra** [nextauthjs/next-auth#12280]
### Environment

```
System:
    OS: macOS 15.1
    CPU: (8) arm64 Apple M2
    Memory: 82.11 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v22.11.0/bin/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
    pnpm: 9.12.3 - ~/.nvm/versions/node/v22.11.0/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.86
    Edge: 131.0.2903.63
    Safari: 18.1
  npmPackages:
    next: 14.2.18 => 14.2.18 
    next-auth: ^5.0.0-beta.25 => 5.0.0-beta.25 
    react: ^18 => 18.3.1 
```

### Reproduction URL

https://github.com/Boonstra/next-auth-vitest

### Describe the issue

Upgrading my project's dependency on `next-auth@5.0.0-beta.20` to `next-auth@5.0.0-beta.25`, I ran into the issue where my project's tests started failing, while the production code remains working correctly.

The issue seems to be that when Vitest runs a test that imports `next-auth`, it can not resolve the [recently changed import](https://github.com/nextauthjs/next-auth/pull/11551) of `next/server`. Failing the test with the below error message:

```
FAIL  auth/auth.test.ts [ auth/auth.test.ts ]
Error: Cannot find module '/[project_path]/node_modules/next/server' imported from /[project_path]/node_modules/next-auth/lib/env.js
Did you mean to import "next/server.js"?
```

The LOC that's causing the issue can be found in [`src/lib/env.ts#L2`](https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/lib/env.ts#L2), which was apparently [changed to address Turbopack compatibility issues](https://github.com/nextauthjs/next-auth/pull/11551):

```
import type { NextRequest } from "next/server"
```

It however introduced this issue in Vitest, and potentially also [this other open issue related to using `auth` inside `getServerSideProps`](https://github.com/nextauthjs/next-auth/issues/12217).

### How to reproduce

1. Clone the repo in the reproduction URL
2. Run `npm i` to install dependencies
3. Run `npm run test`
4. See the test fail with the aforementioned error message, related to not being able to resolve the path to `next/server`

### Expected behavior

The linked repo that contains the code to reproduce the issue is a clean installation. It contains only Next 14, Next Auth 5-beta.25, React 18, and the basic requirements to setup Vitest with React Testing Library.

The repo is setup accordion to official documentation for Next.JS:
1. Create Next app: https://nextjs.org/docs/14/getting-started
2. Add testing libs: https://nextjs.org/docs/14/app/building-your-application/testing/vitest
3. Setup next-auth: https://authjs.dev/getting-started/migrating-to-v5

I've added a single test to demonstrate what happens when a test file imports a file that imports `next-auth`.

The expected behaviour is that, following the documentation, I can execute tests on a file that imports from `next-auth` without having to mock the `next-auth` import.

**Comment by CHC383** [comment]
See https://github.com/vitest-dev/vitest/issues/4554#issuecomment-1827824912

**Comment by Boonstra** [comment]
> See [vitest-dev/vitest#4554 (comment)](https://github.com/vitest-dev/vitest/issues/4554#issuecomment-1827824912)

This solution worked perfectly. Thanks a ton for linking it here!
