### ISSUE TITLE
session does not include user_id in user object when calling getSession()

### ISSUE THREAD

**Issue by sunrunner4kr-simon** [nextauthjs/next-auth#1233]
**Your question**
session does not include user_id in user object when calling getSession()

do you know how I can get the user_id, or why it's not in the session object?

Appreciate any help!

**What are you trying to do**
I'm trying to get the user_id from the user element of the session. I'm using getSession() to get the current session object so that I can use the user_id to validate the user logged in, with a user record

![image](https://user-images.githubusercontent.com/58920692/106493369-f3120c00-64b0-11eb-8d6a-ceccffaa3eae.png)

**Reproduction**
getSession() returns below object for example: -
```
{
  user: {
    name: 'Simon Edge',
    email: 'simonedge9@gmail.com',
    image: 'https://lh3.googleusercontent.com/-wVA_njx-MYY/AAAAAAAAAAI/AAAAAAAAAAA/AMZuucmCmJ95KmcrPvK2q2cVnzZszUI4HQ/s96-c/photo.jpg'
  },
  accessToken: '3aa195cfa4b9920a46541adbac097b74d4baf6e935203946c1988fac6942b8b6',
  expires: '2021-03-02T19:07:42.054Z'
}

```
**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
If you want to add the User ID property you can use the session callback.

https://next-auth.js.org/configuration/callbacks#session-callback

The current documentation could use improving I think (to better reflect it is a User object *or* a JWT token, depending on if you are using a database or not), but this gets asked a lot and you should be able to find an answer to it in the closed issues.

**Comment by sunrunner4kr-simon** [comment]
Thank you @iaincollins I stupidly was filtering issues when searching on 'open'
Got it all working now, thanks again
