### ISSUE TITLE
Database foreign keys

### ISSUE THREAD

**Issue by StefanSelfTaught** [nextauthjs/next-auth#1235]
**Your question**
I was wondering why in the adapters repo the Prisma adapter for NextAuth is using foreign keys and in the docs there is not foreign keys.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
So thanks for asking this. The adapters repo is still in development, and currently not the Prisma adapter is not the one as the built in version (what the documentation refers to).

We are in a process of moving the adapters to the other repo for easier maintenance, but would like to do it with minimal annoyance for our users. For a while, both Prisma adapters will exist, so we can swap the old one with the new, and eventually remove the old one (or maybe keep it as a legacy alternative)


@williamluke4 may have more to say, but you at least got my reasoning. 😊 Hope this helps.

**Comment by StefanSelfTaught** [comment]
Got it, thanks for clarification 😄
