### ISSUE TITLE
Get more data while creating user (with custom adapter) for GitHub and LinkedIn

### ISSUE THREAD

**Issue by pbteja1998** [nextauthjs/next-auth#1238]
I have set up `GitHub` and `LinkedIn` auth using `next-auth`. Even though, I am setting the scope to `read:user` for GitHub, I am only getting `name`, `email`, and `image` fields under profile. Is there a way to get other fields like `username` from GitHub?

Also, when I logged in with LinkedIn, I am unable to get a profile image.

Here are my providers with corresponding scopes:
```js
providers: [
    Providers.GitHub({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET,
      scope: 'read:user',
    }),
    Providers.LinkedIn({
      clientId: process.env.LINKEDIN_ID,
      clientSecret: process.env.LINKEDIN_SECRET,
      scope: 'r_liteprofile r_emailaddress',
    }),
  ],
```

I have a custom adapter, and I am trying to get the details from `createUser` function.

```js
// createUser function in the custom adapter.
async function createUser(profile) {
    // I am expecting more information from this "profile" object
}
```

Any help related to this is highly appreaciated.

Thanks.

**Comment by balazsorban44** [comment]
This is what the `profile` provider method property is for! It receives all the data we get from your provider, than you can map it over to whatever you want. That is then sent as the first argument in the `signIn` callback, and the as the second argument to the `jwt` callback. You can than use those callbacks to persist/send that info to the client.

**Comment by pbteja1998** [comment]
Thanks a lot 🙏 @balazsorban44 
I was able to resolve this by using the above method. 

---

For anybody who comes across this issue, I also had to update to the latest version for it to work. 

Previous versions:
```
"next-auth": "3.1.0",
"@types/next-auth": "3.1.18"
```

Current versions: 
```
"next-auth": "3.2.0",
"@types/next-auth": "3.1.24"
```

**Comment by balazsorban44** [comment]
@iaincollins, I don't remember changing anything with the adapter code in the new release? Do you have an idea why updating would fix this?

**Comment by pbteja1998** [comment]
Also for getting the profile picture for LinkedIn, I also had to overwrite `profileUrl` field. 

My LinkedIn provider looks like below:

```javascript
Providers.LinkedIn({

      clientId: process.env.LINKEDIN_ID,

      clientSecret: process.env.LINKEDIN_SECRET,

      scope: 'r_liteprofile',

      profileUrl: 'https://api.linkedin.com/v2/me?projection=(id,localizedFirstName,localizedLastName,profilePicture(displayImage~digitalmediaAsset:playableStreams))',

      profile: (profileData) => {
          const profileImage = profileData?.profilePicture?.['displayImage~']?.elements[0]?.identifiers?.[0]?.identifier ?? ''
          return {
              id: profileData.id,
              name: profileData.localizedFirstName + ' ' + profileData.localizedLastName,
              email: null,
              image: profileImage,
          }
      },
}),
```

**Comment by pbteja1998** [comment]
@balazsorban44 and @iaincollins

Is there any possibility to support multiple profile URLs and merge the results together to form the profile object?

**Usecase:**
For example, to get the email in LinkedIn, I have to send a request to `https://api.linkedin.com/v2/emailAddress` where as to get other profile info, I have to send the request to `https://api.linkedin.com/v2/me`.

**Source:**
- [Retrieving member email address](https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin#retrieving-member-email-address)
- [Retrieving member profile picture](https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin#retrieving-member-profile-picture)

**Comment by danyel117** [comment]
> @balazsorban44 and @iaincollins
> 
> Is there any possibility to support multiple profile URLs and merge the results together to form the profile object?
> 
> **Usecase:**
> For example, to get the email in LinkedIn, I have to send a request to `https://api.linkedin.com/v2/emailAddress` where as to get other profile info, I have to send the request to `https://api.linkedin.com/v2/me`.
> 
> **Source:**
> 
> * [Retrieving member email address](https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin#retrieving-member-email-address)
> * [Retrieving member profile picture](https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin#retrieving-member-profile-picture)

In my case, since Linkedin is not returning neither the email nor the profile picture, I did the following:

For the image, I implemented the code you wrote above and worked perfectly. For the email, however, I wrote the following callback SignIn function:

`
    async signIn(user, account, profile) {
      if (account.provider === 'linkedin' && !user.email) {
        const LinkedinEmail: string = await getLinkedinEmail(account.accessToken).then((res) => {
          return res.elements[0]['handle~'].emailAddress;
        });
        user.email = LinkedinEmail;
      }
      return true;
    },
`
where getLinkedinEmail is a helper fetch function to the URL  `https://api.linkedin.com/v2/emailAddress?q=members&projection=(elements*(handle~))&oauth2_access_token=${accessToken}`

**Comment by pbteja1998** [comment]
Thanks @danyel117. Will try this out.

**Comment by balazsorban44** [comment]
I think we could make this easier for users by providing the `access_token` as the second parameter to `provider.profile()`.

https://github.com/nextauthjs/next-auth/blob/2d364f246ab9fe27ed2badadaa4bf6fce4567c88/src/server/lib/oauth/callback.js#L97-L111


```diff
-        profileData = JSON.parse(profileData) 
+       profileData = JSON.parse(profileData, tokens.access_token)
```

**Comment by pbteja1998** [comment]
> I think we could make this easier for users by providing the access_token as the second parameter to provider.profile().

Nice. That would be awesome.

---

Also is there a way to trigger email verification workflow manually? 
**Usecase:** I have a GitHub login — which will not always returns email, because of users's privacy settings. So it would be good to manually allow them to enter their email after they log in with GitHub, and verify it in a similar way we do it with passwordless login.

**Comment by jahirfiquitiva** [comment]
hey @pbteja1998 @danyel117 ... I have added a mix of your code but it isn't working as expected. I'm not able to retrieve the user email **and** profile picture.

Would you mind guiding me or letting me know what I'm doing wrong?

Thanks in advance 🙏🏼

```typescript
/* eslint-disable @typescript-eslint/no-unused-vars,@typescript-eslint/ban-ts-comment */
import fetch from 'isomorphic-fetch';
import { NextApiRequest, NextApiResponse } from 'next';
import NextAuth, { InitOptions } from 'next-auth';
import Providers from 'next-auth/providers';

import { NextApiFunc } from '../../../types';

const getLinkedInEmail = async (accessToken: string) => {
  try {
    const projectionUrl = `https://api.linkedin.com/v2/emailAddress?q=members&projection=(elements*(handle~))&oauth2_access_token=${accessToken}&scope=r_emailaddress`;
    const request = await fetch(projectionUrl);
    const response = await request.json();
    return response.elements[0]['handle~'].emailAddress;
  } catch (e) {
    return '';
  }
};

const getLinkedInPhoto = async (accessToken: string) => {
  try {
    const projectionUrl = `https://api.linkedin.com/v2/me?projection=(id,firstName,lastName,profilePicture(displayImage~:playableStreams))&oauth2_access_token=${accessToken}`;
    const request = await fetch(projectionUrl);
    const response = await request.json();
    return (
      response?.profilePicture?.['displayImage~']?.elements[0]?.identifiers?.[0]
        ?.identifier ?? ''
    );
  } catch (e) {
    return '';
  }
};

const options: InitOptions = {
  providers: [
    Providers.LinkedIn({
      clientId: process.env.LINKEDIN_CLIENT_ID || '',
      clientSecret: process.env.LINKEDIN_CLIENT_SECRET || '',
      scope: 'r_liteprofile',
      profileUrl:
        'https://api.linkedin.com/v2/me?projection=(id,localizedFirstName,localizedLastName,profilePicture(displayImage~digitalmediaAsset:playableStreams))',
      profile: (profileData: {
        profilePicture?: unknown;
        id?: string;
        localizedFirstName?: string;
        localizedLastName?: string;
      }) => {
        const profileImage =
          // @ts-ignore
          profileData?.profilePicture?.['displayImage~']?.elements[0]
            ?.identifiers?.[0]?.identifier ?? '';
        return {
          id: profileData.id,
          name: `${profileData.localizedFirstName} ${profileData.localizedLastName}`,
          email: null,
          image: profileImage,
        };
      },
    }),
    Providers.Discord({
      clientId: process.env.DISCORD_CLIENT_ID || '',
      clientSecret: process.env.DISCORD_CLIENT_SECRET || '',
    }),
  ],
  database: process.env.DATABASE_URL,
  secret: process.env.AUTH_SECRET,
  session: {
    jwt: true,
    // Seconds - How long until an idle session expires and is no longer valid.
    maxAge: 30 * 24 * 60 * 60, // 30 days
    updateAge: 24 * 60 * 60, // 24 hours
  },
  jwt: {
    encryption: true,
    secret: process.env.JWT_SECRET,
    signingKey: process.env.JWT_SIGNING_KEY,
    encryptionKey: process.env.JWR_ENCRYPTION_KEY,
  },
  pages: {
    signIn: '/',
    signOut: '/',
  },
  debug: (process.env.NODE_ENV || '').includes('dev'),
  callbacks: {
    async signIn(user, account, profile) {
      // TODO: send user data to backend

      const accountProvider = account?.provider ?? '';

      if (account.provider === 'linkedin') {
        if (!user.email) {
          user.email = await getLinkedInEmail(account.accessToken);
        }
        if (!user.image) {
          user.image = await getLinkedInPhoto(account.accessToken);
        }
      }

      try {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        user.provider = accountProvider;
      } catch (e) {}

      return true;
    },
  },
};

export default (req: NextApiRequest, res: NextApiResponse): NextApiFunc =>
  NextAuth(req, res, options);
```

**Comment by pbteja1998** [comment]
@jahirfiquitiva It looks correct. Maybe your app isn't verified? Are you able to see `r_liteprofile` under `OAuth2.0 scopes` in your LinkedIn app?

<img width="761" alt="Screenshot 2021-03-17 at 10 49 47 AM" src="https://user-images.githubusercontent.com/17903466/111418971-9e4bed00-870e-11eb-92c0-e60ac3f879fe.png">

**Comment by jahirfiquitiva** [comment]
@pbteja1998  yes, I see both scopes there 🤔

**Comment by ahallora** [comment]
I managed to get email and image from linkedIn with this code using a combination of the awesome tips and tricks above:

```ts
const getLinkedInEmail = async (accessToken: string) => {
  try {
    return axios
      .get(
        `https://api.linkedin.com/v2/emailAddress?q=members&projection=(elements*(handle~))&oauth2_access_token=${accessToken}`
      )
      .then(
        (response: any) =>
          response?.data?.elements?.[0]?.["handle~"]?.emailAddress
      )
      .catch(() => null);
  } catch (e) {
    return null;
  }
};

const getLinkedInPhoto = async (accessToken: string) => {
  try {
    return axios
      .get(
        `https://api.linkedin.com/v2/me?projection=(id,localizedFirstName,localizedLastName,profilePicture(displayImage~digitalmediaAsset:playableStreams))&oauth2_access_token=${accessToken}`
      )
      .then(
        (response: any) =>
          response?.data?.profilePicture?.["displayImage~"]?.elements?.[0]
            ?.identifiers?.[0]?.identifier ?? ""
      )
      .catch(() => null);
  } catch (e) {
    return null;
  }
};

export default NextAuth({
  providers: [
    Providers.LinkedIn({
      clientId: process.env.LINKEDIN_CLIENT_ID,
      clientSecret: process.env.LINKEDIN_CLIENT_SECRET,
      scope: "r_liteprofile,r_emailaddress",
      async profile(prof: any, tokens: any) {
        const { accessToken } = tokens;
        return {
          ...prof,
          email: await getLinkedInEmail(accessToken),
          image: await getLinkedInPhoto(accessToken),
        };
      },
    }),
  ],
  //...
});
```

returning this (redacted) payload on succesful sign in with LinkedIn: 💯 

```js
[next-auth][debug][oauth_callback_response] {
  profile: {
    localizedLastName: 'H...',
    id: 'Z...',
    localizedFirstName: 'A...',
    email: 'a...@...',
    image: 'https://media-exp3.licdn.com/...'
  },
  account: {
    provider: 'linkedin',
    type: 'oauth',
    ...
```

**Comment by RandomDude123** [comment]
the solution i went with. maybe helpful for the next one figuring out how to properly get image and email from LinkedIn...

```
import NextAuth, { Profile, TokenSet } from 'next-auth';
import Providers from 'next-auth/providers';

const getLinkedInEmail = async (accessToken: TokenSet['accessToken']) => {
  try {
    const response = await fetch(
      `https://api.linkedin.com/v2/emailAddress?q=members&projection=(elements*(handle~))&oauth2_access_token=${accessToken}`
    );
    const data = await response.json();
    return data.elements?.[0]?.['handle~']?.emailAddress;
  } catch (e) {
    return null;
  }
};

const getLinkedInPhoto = async (accessToken: TokenSet['accessToken']) => {
  try {
    const response = await fetch(
      `https://api.linkedin.com/v2/me?projection=(id,localizedFirstName,localizedLastName,profilePicture(displayImage~digitalmediaAsset:playableStreams))&oauth2_access_token=${accessToken}`
    );
    const data = await response.json();
    return data.profilePicture?.['displayImage~']?.elements?.[0]
      ?.identifiers?.[0]?.identifier;
  } catch (e) {
    return null;
  }
};

export default NextAuth({
  providers: [
    Providers.LinkedIn({
      clientId: process.env.LINKEDIN_CLIENT_ID,
      clientSecret: process.env.LINKEDIN_CLIENT_SECRET,
      scope: 'r_liteprofile,r_emailaddress',
      async profile(profileData: Profile, { accessToken }: TokenSet) {
        const [email, image] = await Promise.all([
          getLinkedInEmail(accessToken),
          getLinkedInPhoto(accessToken),
        ]);
        return {
          id: `${profileData.id}`,
          name: `${profileData.localizedFirstName} ${profileData.localizedLastName}`,
          email,
          image,
        };
      },
    }),
  ],
});

```

**Comment by balazsorban44** [comment]
Hi, just a heads up, in v4 both image and email will be returned by default! See #2821

**Comment by developer-irfan** [comment]
@pbteja1998 How to retrieve all other information like profile title, about and experience etc?
