### ISSUE TITLE
Users Collection not being created for Email Provider

### ISSUE THREAD

**Issue by PranayPant** [nextauthjs/next-auth#1240]
**Describe the bug**
Upon successful login of via email provider, the users table is not being created in MongoDB Atlas

Do not report bugs with your own project here, ask from help by raising a question instead - this helps us a lot with administration overhead.

**Steps to reproduce**
Steps to reproduce the behavior.
Clone https://github.com/PranayPant/nextjs-blog
cd nextjs-blog
yarn dev
Navigate to http://localhost:3000/api/auth/signin
Sign in via email
Click on verification link in email u received
Successfully see profile page as having been signed in

Include a link to public repository which can be used to reproduce the behaviour.

**Expected behavior**
A Users table is created in MongoDB atlas

**Screenshots or error logs**
![image](https://user-images.githubusercontent.com/3720731/106679480-63d52900-6582-11eb-8230-a07160af81fb.png)

**Additional context**

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by rootlinux2** [comment]
Hi @PranayPant I'm facing this issue, How could you solve this.

**Comment by iaincollins** [comment]
I'm not aware of any bugs related to MongoDB support in the current release. If you having problems using MongoDB with NextAuth.js the best idea is to post an example of the config you are using in the Discussions forum - versions of MongoDB/TypeORM/Next.js/NextAuth.js is also helpful.

If you set `debug: true` in the options you may be able to see what's going wrong. Typically it indicates a problem with DB credentials which are indicated from errors on the console.

**Comment by rootlinux2** [comment]
Thanks, I will!
