### ISSUE TITLE
Spending hours because read wrong documentation

### ISSUE THREAD

**Issue by upsidecode** [nextauthjs/next-auth#12405]
### What is the improvement or update you wish to see?

Please make the clear different name/documentation/module name about the next auth version 4 or 5.

### Is there any context that might help us understand?

I've spend 8 hours only to figuring out the next auth documentation.
My project use v5, but what i read is the old version of next auth v4.

What i read is, the version 4 documentation which is the top search result on google.
I think that's not my vault, since this module have 2 different versions.
With additional version npm install next-auth"@beta" and not.

No offense intended, but I hope this is reconsidered

**Comment by ywwa** [comment]
when you go to next-auth website it shows message on top of the page :man_shrugging: 
![image](https://github.com/user-attachments/assets/15b6ddae-3d1d-4902-9938-86391a4eb630)

**Comment by ndom91** [comment]
Yeah we have the banner at the top of the v4 docs and the authjs.dev new docs also mention a few times that its specifically for v5.

Closing this issue, but if you have any recommendations we'd be happy to look at any PRs :pray:
