### ISSUE TITLE
Callback URL not approved for this client application

### ISSUE THREAD

**Issue by AlexBHarley** [nextauthjs/next-auth#1242]
**Describe the bug**

```
Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings
```

Everything works perfectly in development, but when I try to login in production (Vercel) it all falls over. I've been getting numerous errors but this is the most consistent.

Any thoughts?

It's here https://social-bios.com if you want to try login with Twitter. The correct API keys are configured and no issues on the Twitter side.

<img width="673" alt="Screenshot 2021-02-03 at 13 43 12" src="https://user-images.githubusercontent.com/11168524/106748646-d3502480-6625-11eb-85e1-e7590ec4b624.png">

**Comment by balazsorban44** [comment]
Could you maybe share your config? I am also assuming you use the version `3.1.0`. Could you see if upgrading to `3.2.0` makes any differenc?

**Comment by AlexBHarley** [comment]
Yeah nothing deployed works 😔. Anyway trying to fix Twitter authentication before anything else.

After upgrading to `3.2.0` I get `"TypeError [ERR_INVALID_CHAR]: Invalid character in header content [\"Location\"]"`.

No spaces in the callback URL or secrets, and all my permissions in Twitter are correct. I'm pretty stumped.

**Comment by balazsorban44** [comment]
I would still like to see your config, or ideally a reproduction repository. it's nearly impossible to help you without seeing any of your code. I have tested Twitter and it worked fine, so I suspect a configuration error.

**Comment by AlexBHarley** [comment]
I've moved off away from that project for the moment. Will get back to you if I revisit it.

**Comment by pbshgthm** [comment]
@AlexBHarley @balazsorban44 I'm facing the same issue. Everything works fine on the local machine. On deploying to vercel (in preview environment), this is happening.

**Comment by wack-overflow** [comment]
I am struggling bad with this.  I simply cannot get the `next-auth-example` app to work with a Twitter login in my local environment.

I set up `.env.local` with the correct `TWITTER_ID` and `TWITTER_SECRET`, and set `NEXTAUTH_URL=http://127.0.0.1:3000`.  I have verified several times that there are no newline or other unexpected characters in these values.

I have set up my twitter callback url with `http://127.0.0.1:3000/` as follows: 

![image](https://user-images.githubusercontent.com/83986403/121122425-acc21600-c7de-11eb-8945-8351032d69bd.png)

I run the app and navigate to `http://127.0.0.1:3000`, then click the "Sign In" button, then click the "Sign in with Twitter" button.

I can see a `POST` request being made to `http://127.0.0.1:3000/api/auth/signin/twitter` with what appear to be correct `csrfToken` and `callbackUrl` in the form data as follows:

![image](https://user-images.githubusercontent.com/83986403/121123311-40481680-c7e0-11eb-93f4-c3dbaeced65a.png)

However, it gives me an error "Try signing into a different account", and I can see the dreaded "Callback URL not approved" error in my terminal:

![image](https://user-images.githubusercontent.com/83986403/121123462-7f766780-c7e0-11eb-97be-478b1ae22c14.png)

How can I solve this? Any help is greatly appreciated!

**Comment by balazsorban44** [comment]
@wack-overflow answered your bug report at #2142, but I can say it again here so others see this. See the docs:
![image](https://user-images.githubusercontent.com/18369201/121159395-72db2900-c84b-11eb-9b65-ede285a032ca.png)
https://next-auth.js.org/configuration/providers#how-to
