### ISSUE TITLE
@next-auth/prisma-adapter is missing build assets

### ISSUE THREAD

**Issue by huv1k** [nextauthjs/next-auth#1243]
**Describe the bug**
`@next-auth/prisma-adapter` is missing build assets, the package is published without dist folder. I tried both `latest` and `canary`, only possible solution is going to `node_modules` and build the package manually.

**Expected behavior**
The package should have build assets published to `npm`.

**Additional context**

<img width="446" alt="Screenshot 2021-02-03 at 18 28 04" src="https://user-images.githubusercontent.com/5691926/106785550-c9dab280-664d-11eb-9c5e-71980abdda1e.png">

**Comment by balazsorban44** [comment]
cc @williamluke4

**Comment by williamluke4** [comment]
Sounds like quite a large oversight 🙈 . I'll sort it out in the morning.

**Comment by huv1k** [comment]
> Sounds like quite a large oversight 🙈 . I'll sort it out in the morning.

I pinged you about this adapter on Prisma public slack, so maybe we can sync about it? There are a few more problems 🙈

**Comment by williamluke4** [comment]
@huv1k Sure! You might have pinged a dead account of mine as I can't see any messages

**Comment by williamluke4** [comment]
This is now fixed in 0.4.1
