### ISSUE TITLE
outdated types in @types/next-auth

### ISSUE THREAD

**Issue by pavandv** [nextauthjs/next-auth#1245]
**Describe the bug**
With the latest version `3.2.0` of `next-auth`, the types from `@types/next-auth` are outdated.

For example, the **signIn** method now accepts **3 parameters** which are `provider, args, authorizationParams`, 
https://github.com/nextauthjs/next-auth/blob/cdc1ac52b2f20a62a3218ce0f1c7e0aac04c08fb/src/client/index.js#L237

but the type for signIn in `@types/next-auth` only accepts **2 parameters**

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/78d3871eaac015aa1e7093327ed654832315cae7/types/next-auth/client.d.ts#L49

**Expected behavior**
The types from **DefinitelyTyped** should match with implementation.

**Comment by balazsorban44** [comment]
We Unfortunately we cannot do much h about this right now. The whole point of choosing DefinitelyTyped over a TS code base is that the maintainers of this package have less to maintain for the time being. So if you find something outdated, please open a PR with your suggestions to the DefinitelyTyped repo! 🙏
