### ISSUE TITLE
verificationRequest removed from signin callback, incorrect documentation

### ISSUE THREAD

**Issue by kriscarle** [nextauthjs/next-auth#1251]
The documentation for the `signin` callback at https://next-auth.js.org/configuration/callbacks#sign-in-callback says
> Email accounts do not have profiles in the same way OAuth accounts do. On the first call during email sign in the profile object will include an property verificationRequest: true to indicate it is being triggered in the verification request flow. When the callback is invoked after a user has clicked on a sign in link, this property will not be present.

>You can check for the verificationRequest property to avoid sending emails to addresses or domains on a blocklist (or to only explicitly generate them for email address in an allow list).

Looking at the history it appears to have been removed in https://github.com/nextauthjs/next-auth/pull/959 here:
 
https://github.com/nextauthjs/next-auth/pull/959/files#diff-273ce1b1ba70a2520a63bb41cff4da08d8272e82a43dc57b9e9a402daf26621dL57

Possibly just a bug? Would it be safe to add `verificationRequest: true` back in that line?

**Comment by balazsorban44** [comment]
yes, that looks like it was removed by accident, thanks for tracking this issue down! are you interested in opening a PR with the fix?
