### ISSUE TITLE
useSession in a [[...slug].js page results in component not being 'released'

### ISSUE THREAD

**Issue by TimNZ** [nextauthjs/next-auth#1252]
Do not know if this is a Next or Next-Auth issue.

**Describe the bug**
I'm implementing my own nested page router, using /pages/admin/[[...slug]].js mechanism.

When useSession() is used in a component, and I change route e.g. /pages/admin/a from /pages/admin/b, the component function for /pages/admin/a is still being executed when I change route to /pages/admin/b due to useSession() internal _getSession being called by the 'focus' event handler.

**Steps to reproduce**
https://github.com/TimNZ/next-auth-session-usesession-bug

Run and open devtools console and switch between 'Page A' and 'Page B' via links and see 'A' is always being printed to the console even though it is no longer being rendered.

**Screenshots or error logs**
![useSession](https://user-images.githubusercontent.com/1051701/106855300-923d3a80-6721-11eb-8c20-b2aebf2959ea.gif)

![image](https://user-images.githubusercontent.com/1051701/106855387-b6991700-6721-11eb-9f01-6011f783eea9.png)

**Additional context**
Once I switch to another page outside of the slug, useSession stops firing for component A.

**Comment by iaincollins** [comment]
I don't know what is going on here but just wanted to say thanks for this really clear example and video, that is super helpful!

**Comment by TimNZ** [comment]
I think it's just a foundational Javascript issue where the unmounted component is still being referenced by the event listener.

You might have to return an on unmount function in the internal _getSession useEffect() to unlisten.

**Comment by balazsorban44** [comment]
The client code is completely rewritten in v4 (hoping to release this summer), which will much better align with React paradigms, have a look here:

https://github.com/nextauthjs/next-auth/blob/next/src/client/react.js

If that won't fix the issue, it might not be NextAuth.js after all.
