### ISSUE TITLE
Adding Keycloak to providers 

### ISSUE THREAD

**Issue by manuschillerdev** [nextauthjs/next-auth#1261]
**Summary of proposed feature**
[Keycloak](https://www.keycloak.org/) is a great, lightweight open source auth provider that can easily be self hosted. This feature adds a default Provider for using keycloak with next-auth and OpenID2. Feature request originated from https://github.com/nextauthjs/next-auth/discussions/1195 

**Purpose of proposed feature**
A clear and concise description description of why this feature is necessary and what problems it solves.
The feature solves the problem of unknown configs in regard of using keycloak with next-auth.

**Detail about proposed feature**
Keycloak basically has two dynamic parts in its oauth config urls. The domain and the realm name:
e.g. `https://${options.domain}/auth/realms/${realm}/protocol/openid-connect/token`

I would propose that it can be configured similarly to the [IdentityServer4Provider](https://github.com/nextauthjs/next-auth/blob/canary/src/providers/identity-server4.js) and add the `options.realm` attribute to it.
In most of the cases simple Keycloak setups only use one realm (`master`) so it can be discussed, if `options.realm` should set to `master` by default.

```js
// src/providers/keycloak.js
export default ({ realm = "master", ...options }) => {
  return {
    id: "keycloak",
    name: "Keycloak",
    type: "oauth",
    version: "2.0",
    params: { grant_type: "authorization_code" },
    scope: "openid profile email",
    accessTokenUrl: `https://${options.domain}/auth/realms/${realm}/protocol/openid-connect/token`,
    requestTokenUrl: `https://${options.domain}/auth/realms/${realm}/protocol/openid-connect/auth`,
    authorizationUrl: `https://${options.domain}/auth/realms/${realm}/protocol/openid-connect/auth?response_type=code`,
    profileUrl: `https://${options.domain}/auth/realms/${realm}/protocol/openid-connect/userinfo`,
    profile: (profile) => ({ ...profile, id: profile.sub }),
    ...options,
  };
};
```

demo of currently working version:

https://user-images.githubusercontent.com/56154253/107019705-4aaac300-67a2-11eb-9ded-c7247cd4da09.mov

**Potential problems**
In local environments you often use Keycloak via `docker-compose` and serve the application via `http` instead of `https`.
For these cases you would need to set all URLs separately again only for the DEV-Environment, because the default urls in the provider do not allow to change the protocol. Please compare the [IdentityServer4Provider](https://github.com/nextauthjs/next-auth/blob/canary/src/providers/identity-server4.js) implementation, which currently has the same problem locally.

```js
    // pages/api/auth/[...nextauth].js
    Providers.Keycloak({
      domain: process.env.KEYCLOAK_DOMAIN,
      clientId: "nextjs_local",
      clientSecret: process.env.KEYCLOAK_CLIENT_SECRET,
      // following lines are only needed in dev environments, 
      // because the protocol can not be changed from http to https via options
      accessTokenUrl: `http://${options.domain}/auth/realms/${realm}/protocol/openid-connect/token`,
      requestTokenUrl: `http://${options.domain}/auth/realms/${realm}/protocol/openid-connect/auth`,
      authorizationUrl: `http://${options.domain}/auth/realms/${realm}/protocol/openid-connect/auth?response_type=code`,
      profileUrl: `http://${options.domain}/auth/realms/${realm}/protocol/openid-connect/userinfo`,
    }),
```
**Describe any alternatives you've considered**
We could offer to make the protocol dynamic, but set its default to `https`:
```js
export default ({ realm = "master", protocol = "https", ...options }) => {
    accessTokenUrl: `${protocol}://${options.domain}/auth/realms/${realm}/protocol/openid-connect/token`,
```

This would deviate from the other provider APIs, so it should be discussed how the API should look in general (also regarding the IdentityServer4 provider).

**Additional context**
<details>
  <summary>Local keycloak setup via docker-compose (localhost:8080) for testing (credentials: `admin/admin)`:</summary>
  
```yaml
version: '3'

volumes:
  postgres_data:
    driver: local
services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - postgres
```
</details>

<details>
  <summary>nextjs_local client app config - can be imported via admin UI</summary>
  
```json
{
    "clientId": "nextjs_local",
    "name": "nextjs_local",
    "rootUrl": "http://localhost:3000",
    "adminUrl": "http://localhost:3000",
    "baseUrl": "http://localhost:3000/api/auth/callback/keycloak",
    "surrogateAuthRequired": false,
    "enabled": true,
    "alwaysDisplayInConsole": false,
    "clientAuthenticatorType": "client-secret",
    "redirectUris": [
        "http://localhost:3000/*"
    ],
    "webOrigins": [
        "http://localhost:3000"
    ],
    "notBefore": 0,
    "bearerOnly": false,
    "consentRequired": false,
    "standardFlowEnabled": true,
    "implicitFlowEnabled": false,
    "directAccessGrantsEnabled": true,
    "serviceAccountsEnabled": false,
    "publicClient": false,
    "frontchannelLogout": false,
    "protocol": "openid-connect",
    "attributes": {
        "saml.assertion.signature": "false",
        "access.token.lifespan": "600",
        "saml.force.post.binding": "false",
        "saml.multivalued.roles": "false",
        "saml.encrypt": "false",
        "saml.server.signature": "false",
        "saml.server.signature.keyinfo.ext": "false",
        "exclude.session.state.from.auth.response": "false",
        "saml_force_name_id_format": "false",
        "saml.client.signature": "false",
        "tls.client.certificate.bound.access.tokens": "false",
        "saml.authnstatement": "false",
        "display.on.consent.screen": "false",
        "saml.onetimeuse.condition": "false"
    },
    "authenticationFlowBindingOverrides": {
        "direct_grant": "ffba6037-ec82-4aab-8e02-5adfbdac7715",
        "browser": "7a40d4df-442f-49f3-af30-6d603a470a2d"
    },
    "fullScopeAllowed": false,
    "nodeReRegistrationTimeout": -1,
    "protocolMappers": [
        {
            "name": "client_role",
            "protocol": "openid-connect",
            "protocolMapper": "oidc-usermodel-client-role-mapper",
            "consentRequired": false,
            "config": {
                "multivalued": "true",
                "userinfo.token.claim": "true",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "role",
                "jsonType.label": "String",
                "usermodel.clientRoleMapping.clientId": "nextjs_local"
            }
        }
    ],
    "defaultClientScopes": [
        "web-origins",
        "role_list",
        "roles",
        "profile",
        "email"
    ],
    "optionalClientScopes": [
        "address",
        "phone",
        "offline_access",
        "microprofile-jwt"
    ],
    "access": {
        "view": true,
        "configure": true,
        "manage": true
    }
}
```

</details>

*Please indicate if you are willing and able to help implement the proposed feature.*
Absolutely. Once the questions are cleared I can happily provide a PR, documentation and a blogpost for it.
I would assume the current information in this PR requires some knowledge about Keycloak on how to set the example up locally for testing. I will try to provide an example repo asap.

**Comment by balazsorban44** [comment]
So in my opinion, we should not add one-off options that satisfy a single specific provider (see #1022).

If it is possible to add it in a way that is useful for most/many providers, I think it is worth considering. Otherwise, I would like to see if this isn't possible to solve easily in the userland?

```js
// pages/api/auth/[...nextauth].js
const protocol = process.env.NODE_ENV !==  "production" ? "http" : "https"
...
Providers.Keycloak({
  domain: `${protocol}://${process.env.KEYCLOAK_DOMAIN}/auth/realms/${process.env.KEYCLOAK_REALM}/protocol/openid`
  clientId: "nextjs_local",
  clientSecret: process.env.KEYCLOAK_CLIENT_SECRET,
  accessTokenUrl: "/token",
  requestTokenUrl: "/auth",
  authorizationUrl: "/auth?response_type=code",
  profileUrl: "/userinfo",
}),
```

And then:
```js
// src/providers/keycloak.js
export default ({ realm = "master", ...options }) => {
  return {
    id: "keycloak",
    name: "Keycloak",
    type: "oauth",
    version: "2.0",
    params: { grant_type: "authorization_code" },
    scope: "openid profile email",
    profile: (profile) => ({ ...profile, id: profile.sub }),
    ...options,
    accessTokenUrl: `${options.domain}${options.accessTokenUrl}`,
    requestTokenUrl: `${options.domain}${options.requestTokenUrl}`,
    authorizationUrl: `${options.domain}${options.requestTokenUrl}`,
    profileUrl: `${options.domain}${options.profileUrl}`,
  };
};
```

This way we don't have to introduce any new options just for the sake of Keycloak.

What do you think?

**Comment by manuschillerdev** [comment]
I agree on keeping the interface for options consistent 👍 
But I don't feel to confident in the decision on setting the default protocol based on `NODE_ENV`. 

what's the reason that `auth/realms/${process.env.KEYCLOAK_REALM}` is part of `options.domain`, and `/protocol/openid/` is part of the actual URLs?

Since keycloak mainly is used as self hosted solution maybe it just doesn't make sense to include some kind of default with dynamic parts, but rather keeping it simple and leave the decision up to the user?

So: 
```js
export default (options) => {
  return {
    id: "keycloak",
    name: "Keycloak",
    type: "oauth",
    version: "2.0",
    params: { grant_type: "authorization_code" },
    scope: "openid profile email",
    profile: (profile) => ({ ...profile, id: profile.sub }),
    ...options,
  };
};
```

```js
// pages/api/auth/[...nextauth].js
...
Providers.Keycloak({
  clientId: "nextjs_local",
  clientSecret: process.env.KEYCLOAK_CLIENT_SECRET,
  accessTokenUrl: `${process.env.KEYCLOAK_BASE_URL}/token`,
  requestTokenUrl: `${process.env.KEYCLOAK_BASE_URL}/auth`,
  authorizationUrl: `${process.env.KEYCLOAK_BASE_URL}/auth?response_type=code`,
  profileUrl: `${process.env.KEYCLOAK_BASE_URL}/userinfo`
}),
```

```
KEYCLOAK_BASE_URL=http://localhost:8080/auth/realms/master/protocol/openid-connect
```

it would not use `domain`, but I think that would be alright.

What do you think?

**Comment by balazsorban44** [comment]
Yes, it is certainly the easiest/fastest way! I think we could add it as you suggested, and come back to it later on if we can provide it with fewer options.

**Comment by iaincollins** [comment]
Something closer to the design from @balazsorban44 makes sense to me it appreciate I'm not up to speed on typical Keycloak implementations.

Seems like it's worth referencing existing implementations done for v1 (which I worked on but can't remember much about now) and perhaps in Passport.js Strategies and in Keycloak docs to see if they assume sensible defaults so configuration can be as simple as possible in the majority of cases.

This is actually not a challenge unique to Keycloak, all provider properties can be overridden as options but most of the time that's a minority scenario; if there are sensible default parts of paths we should treat those as assumed defaults (and show how to override them in the docs). Some of the existing providers might also provide inspiration.

**Comment by manuschillerdev** [comment]
@iaincollins totally agree. it would be awesome to have sensible defaults for the adapter. But i fear I don't know enough yet about either keycloak or next-auth to be a big help. 
If you have any idea I will happily include it in the PR :)

**Comment by OliverDudgeon** [comment]
I'd still like to see Keycloak added to the built-in providers.

**Comment by softshipper** [comment]
@manuschillerdev 
Could you please provide an example of how to integrate next-auth to Keycloak? Example with the resource.  

Thanks

**Comment by Senseye** [comment]
Also interested in having a Keycloak Provider.
I've got the login working with a custom provider for now, but having issues refreshing the token.

Can anyone share their working KC config?

**Comment by manuschillerdev** [comment]
I could try to set up a blog post about it. It will take me a week, though - sorry!

**Comment by Senseye** [comment]
> I could try to set up a blog post about it. It will take me a week, though - sorry!

Cool! I hope it will help some people around here. 

I've fixed the token rotation issue by the way, here's the correct request:

```js
const response = await fetch(TOKEN_ENDPOINT, {
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: new URLSearchParams({
        client_id: CLIENT_ID,
        client_secret: CLIENT_SECRET,
        grant_type: 'refresh_token',
        refresh_token: refreshToken,
      }),
      method: 'POST',
    })

    const refreshedTokens = await response.json()
```
