### ISSUE TITLE
Help: Request is missing required authentication credential when adding google scopes

### ISSUE THREAD

**Issue by adiliqbl** [nextauthjs/next-auth#1277]
**Your question**
How to use next-auth's access token to access google calendar events.

**What are you trying to do**
I am trying to get google calendar events for the logged in user using access token from google sign-in.  I've added `scope` field but getting 401 oauth_calback_error _"Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential"_.

**Reproduction**
`[...nextauth].js`
```javascript
const SCOPES = ['https://www.googleapis.com/auth/calendar.readonly'];

export default NextAuth({
	providers: [
		Providers.Google({
			clientId: process.env.GOOGLE_CLIENT_ID,
			clientSecret: process.env.GOOGLE_CLIENT_SECRET,
			scope: SCOPES.join(' '),
			authorizationUrl:
				'https://accounts.google.com/o/oauth2/v2/auth?prompt=consent&access_type=offline&response_type=code'
		})
	],
	callbacks: {
		session: async (session, user) => {
			if (user && session.user) {
				session.user.id = user.userId;
				session.accessToken = user.accessToken;
				session.refreshToken = user.refreshToken;
			}
			return session;
		},
		jwt: async (token, user, account, profile, isNewUser) => {
			if (user) token.userId = user.id;
			if (account) {
				token.accessToken = account.accessToken;
				token.refreshToken = account.refreshToken ;
			}
			return token;
		}
	},
	secret: process.env.COOKIE_SECRET,
	session: { jwt: true },
	jwt: {
		secureCookie: process.env.NODE_ENV === 'production',
		encrypt: true
	}
});
```

Any help would be greatly appreciated. Thanks :)

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
Hey someone asked a slightly different but I suspect related question in #1275

Might want to take a look at the answer I just left there as I think will help! =)

**Comment by adiliqbl** [comment]
It worked, thanks for the help @iaincollins.  :)
