### ISSUE TITLE
Add the character encoding of the signin page

### ISSUE THREAD

**Issue by ExpressGradient** [nextauthjs/next-auth#1284]
**Describe the bug**
The sign in page did not have a character encoding.

**Steps to reproduce**
Just click a button with `signIn()` method on it.

**Expected behavior**
You'll see this error in your console. 
```
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.
```

**Screenshots or error [logs**]
![image](https://user-images.githubusercontent.com/59659961/107323395-329db100-6acc-11eb-9c5e-6275e6dab76c.png)

**Additional context**
Just add a
```html
<meta charset="utf-8" />
```
in the `<Head>` of the page and the error will go away.  
And also please add favicon too.  
Thank You and have a great day. 

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Thanks for opening this. Would you care to open a PR to add this?

**Comment by ExpressGradient** [comment]
Ohh, you mean, you would add a fix for this with #1154? Then oki.
Or else if you want me to do it, I can't find that particular file in this repo. Please direct me to it.
Thenks.

**Comment by balazsorban44** [comment]
#1154 is not intended to fix this per se, but it would benefit from adding UTF-8 encoding if we want to support multiple languages with foreign symbols later.
 
So we use `preact` to prerender the built-in pages server-side.

Here is the relevant HTML wrapper code:
https://github.com/nextauthjs/next-auth/blob/69cc6bfa12a301adfe9dc44e71fe00c9027404c1/src/server/pages/index.js#L13

You could add `<meta charset="utf-8"/>` to the `head` as you suggested.

**Comment by balazsorban44** [comment]
@ExpressGradient following up on this, are you interested in making a PR?

**Comment by ExpressGradient** [comment]
Ohh, I'm so sorry. I completely forgot about this. To avoid this, I just used the signIn function on my button.
I will definitely do it now. Thank you.
