### ISSUE TITLE
app crash because of next-auth api route

### ISSUE THREAD

**Issue by ehsmsh** [nextauthjs/next-auth#1302]
**Describe the bug**
if type url address manually to <localhost:port>/api/auth/error, app crashes because of a try to lowercase an undefined value.

Do not report bugs with your own project here, ask from help by raising a question instead - this helps us a lot with administration overhead.

**Steps to reproduce**
just add the basin Email provider for next-auth and try the url mentioned above.

Include a link to public repository which can be used to reproduce the behaviour.

**Expected behavior**
a 404 page shall be indicated instead of app crash and exit.

**Screenshots or error logs**
/home/node/app/node_modules/next-auth/dist/server/pages/error.js:59
  } = errors[error.toLowerCase()] || errors.default;
                   ^
TypeError: Cannot read property 'toLowerCase' of undefined
    at error (/home/node/app/node_modules/next-auth/dist/server/pages/error.js:59:20)
    at Object.error (/home/node/app/node_modules/next-auth/dist/server/pages/index.js:65:31)
    at /home/node/app/node_modules/next-auth/dist/server/index.js:222:29
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/node/app/node_modules/next-auth/dist/server/index.js:52:103)
    at _next (/home/node/app/node_modules/next-auth/dist/server/index.js:54:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
error Command failed with exit code 1.

**Comment by ehsmsh** [comment]
changing errors[error.toLowerCase()] || errors.default to errors[error?.toLowerCase()] || errors.default in /dist/server/pages/error.js:59:20 would solve the problem and return the default error page.

**Comment by iaincollins** [comment]
Thanks! It looks like this was introduced during refactoring.

**Comment by balazsorban44** [comment]
Nice catch @ehsmsh, and thank you for taking the time to dig into the source code!
