### ISSUE TITLE
Expose session_state to allow checking identity session using iframe

### ISSUE THREAD

**Issue by nulladdict** [nextauthjs/next-auth#1305]
**Summary of proposed feature**
Add a way to pass `session_state` from identity provider response to jwt callback

**Purpose of proposed feature**
`session_state` parameter is a required part to use in check_session_iframe scenario. By forwarding it to the jwt callback it can be saved to client session and used in the browser to find out if identity session has changed

**Detail about proposed feature**
Minimal required change would probably be passing `req.query.session_state` to the jwt callback, although I'm not quite sure in which object or parameter it should be put  

**Potential problems**
`session_state` is not useful for all scenarios and may not be supported by certain oidc providers 

**Describe any alternatives you've considered**
Polling identity provider with `prompt=none`, but this causes extra network traffic
Polling introspection endpoint to find if `access_token` is still valid, but this requires using `access_token` and having access to introspection

**Additional context**
More info about [oidc session management](https://openid.net/specs/openid-connect-session-1_0.html)

*Please indicate if you are willing and able to help implement the proposed feature.*
I am willing to implement the feature, but I might require some additional guidance as to where to actually put the parameter

**Comment by balazsorban44** [comment]
Could you check if `account.sessoin_state` is defined for you in the `jwt` callback?

We started forwarding the raw results:
https://github.com/nextauthjs/next-auth/blob/e293e786a8818175bdb0ee92215998d03f0b9518/src/server/lib/oauth/client.js#L179

Not sure in which version we introduced it, but `3.4.1` certainly includes this.

**Comment by nulladdict** [comment]
Yes, `session_state` is only present in the initial response with `code` (I'm using Identity Server 4, authorization code flow), it's not present when the `code` is exchanged to `access_token`, although I'm not sure how standard this behaviour is

**Comment by balazsorban44** [comment]
Yes, we are using IDS4 at work too, and actually came across this parameter while debugging something! Forwarding it to `jwt` would be super easy, although I don't know in which param should it be either. Should it be a new one...? We already have 5 params, in the next major release, I definitely want to turn it into named parameters...

@iaincollins any suggestions? New param, add it to one of them? Which one?

**Comment by nulladdict** [comment]
I think just having access to the `session_state` is fine, forwarding it to the client and polling the iframe should be trivial, example can be found here: [oidc-client-js](https://github.com/IdentityModel/oidc-client-js/blob/dev/src/CheckSessionIFrame.js)

**Comment by balazsorban44** [comment]
So #1698 could expose `session_state` in the `account` object in `jwt` and `signIn`, once finished.

See also: https://github.com/panva/node-openid-client/blob/main/docs/README.md#new-tokensetinput

**Comment by balazsorban44** [comment]
Sorry, this hasn't been forgotten, but still needs some work. Wearing many hats at the moment. 🎩😊

**Comment by balazsorban44** [comment]
@nulladdict if you are still following, I created a temporary version for you to check out!

We aim for a v4 release this summer, and `session_state` will be available as mentioned above.

Here: `npm i next-auth@0.0.0-pr.1698.d16e2ddc`

There are quite a few breaking changes that are documented in the https://github.com/nextauthjs/next-auth/releases pre-release release notes. There will be migration documentation when we are close to the actual release.

**Comment by balazsorban44** [comment]
There is a workaround actually, that should work in 3.x already.

```js
// [...nextauth].js
export default function auth(req, res) {
  return NextAuth(req, res, {
    callbacks: {
      jwt() {
          const sessionState = req.query.session_state
      }
    }
  })
}
```

**Comment by nulladdict** [comment]
Thanks, I'll check it out when I have time to go through api changes

**Comment by balazsorban44** [comment]
I am confident that this will be resolved in the above mentioned PR, so I'll close this now. when v4 is released, feel free to check and report back here if it wasn't the case. we can reopen then. 😊
