### ISSUE TITLE
For oAuth1.0 NextAuth incorrectly refers to accessTokenSecret as refreshToken

### ISSUE THREAD

**Issue by aksanoble** [nextauthjs/next-auth#1321]
**Describe the bug**
For oAuth1.0 there is no concept of refreshToken. Yet nextauth gives you a `refreshToken` as part of the token object even when used with oAuth1.0 provider. Other users have been looking for access_token_secret but haven't been able to becaue of this incorrect naming. #855 

**Steps to reproduce**
Can be reproduced with any oAuth1.0 provider. For example using the twitter provider. 

**Expected behavior** 
The token object should replace the `refreshToken` key with `accessTokenSecret` key. The documentation also needs to be updated. 

**Feedback**

* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
@aksanoble Thanks for reporting! I did some digging, and I think I see the problem, and created a PR for fixing it (#1322). I tested with Twitter, and it did not break, so I have hope that it could potentially fix OAuth 1 flows for other providers as well! It would help a lot, if you could review my PR and give feedback how it went!

**Comment by mahcr** [comment]
This ticket should be reopened. I was able to replicate this issue using the twitter provider and firebase
```
 "next-auth": "^3.27.3"
"@next-auth/firebase-adapter": "^0.1.2",
```

**Comment by balazsorban44** [comment]
please open a new bug report with your reproduction 🙏
