### ISSUE TITLE
useSession Hook isn't returning accessToken

### ISSUE THREAD

**Issue by harshithpabbati** [nextauthjs/next-auth#1327]
**Describe the bug**

useSession hook isn't returning accessToken, but it should return according to the [example session object](https://next-auth.js.org/getting-started/client#example-session-object).

**Steps to reproduce**
Console log session object from the following [example](https://github.com/nextauthjs/next-auth-example)

**Expected behavior**
It shoud return user, accessToken and expires. But only returns user, expires.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
It does not do that by default.

Check out the jwt and session callbacks: 
https://next-auth.js.org/configuration/callbacks#jwt-callback
https://next-auth.js.org/configuration/callbacks#session-callback
