### ISSUE TITLE
Upgrade of next-auth from 3.1.0 to 3.4.2 throws: JWTs must have three components

### ISSUE THREAD

**Issue by oleics** [nextauthjs/next-auth#1335]
Hi,

First: Thank you all very much for this project!

Sadly, there is one bug

**Describe the bug**

Upgrade next-auth from 3.1.0 to 3.4.2 results in: JWTs must have three components

This is thrown by jwt-decode https://www.npmjs.com/package/jwt-decode

**Steps to reproduce**
Just upgrade next-auth from 3.1.0 to 3.4.2
I did not even try to login, the Error throws anyways
Rolling back to 3.1.0 makes the error disapear

**Expected behavior**
No error. :-)

Might be related: https://github.com/nextauthjs/next-auth/discussions/970

**Comment by balazsorban44** [comment]
could you please share a reproduction, otherwise we cannot help. thanks!

**Comment by oleics** [comment]
> could you please share a reproduction, otherwise we cannot help. thanks!

I understand, and as soon as I touch the auth-part of the project again I might come up with something reproduce-able, which I'll post here. Thank you! :)

**Comment by balazsorban44** [comment]
If you could narrow down which version change introduced your issue, it might also be very helpful! You can see all the releases here:
https://github.com/nextauthjs/next-auth/releases
