### ISSUE TITLE
Credentials Providers: routing question

### ISSUE THREAD

**Issue by neophob** [nextauthjs/next-auth#1337]
**Your question**
In the provider docs (https://next-auth.js.org/providers/credentials) is written that
> except that you need to define a handler for authorize() that accepts credentials submitted via HTTP POST as input and returns either

So my `[...nextauth].js` file looks like this (pretty default):

```
import NextAuth from 'next-auth';
import Providers from 'next-auth/providers';

// see https://next-auth.js.org/configuration/options#events
const options = {
  providers: [
    Providers.Credentials({
      name: 'Some Magic',
      credentials: {
        username: { label: "Username", type: "text", required:true, placeholder: "jsmith" },
        password: {  label: "Password", type: "password" }
      },
      async authorize(credentials) {
        console.log('authorizeauthorize');
        const user = { id: 1, name: 'J Smith', email: 'jsmith@example.com' }
        if (user) {
          return user
        } else {
          return null
        }
      }
    })
  ],
  session: {
    jwt: true,
    // Seconds - How long until an idle session expires and is no longer valid.
    maxAge: 30 * 24 * 60 * 60, // 30 days
  },
};
export default (req, res) => NextAuth(req, res, options);
```

**Main Question**: the POST request should be terminated at the Next.JS server and call the `authorize` function? Because today the POST call seems to timeout and nothing is happening. Before I wanted to dig around, I wanted to make sure I understand the theory.

As I use https://github.com/fastify/fastify-nextjs this means I need to define my Next.js routes like this:
```
  fastify
    .register(fastifyNextJs, { dev: true, logLevel: 'debug' })
    .after(() => {
      fastify.next('/api/*', { method: 'GET' });
      fastify.next('/api/*', { method: 'POST' });
      fastify.next('/foo');
    });
```

**What are you trying to do**
I try to use the Credentials Providers, so I can use the JWT "secured" backend and support login/logout there.

**Reproduction**
I'm happy to provide a demo project if needed.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [X] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [X] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

Btw - this issue number is RAD!

**Comment by balazsorban44** [comment]
a reproduction would go a long way for us to be able to help you, so please do share if you have one :)

**Comment by neophob** [comment]
I created https://github.com/neophob/nextjs-fastify-auth and tried to describe how to reproduce the issue

**Comment by neophob** [comment]
Ok I created the same project as Next.js only, no fastify (https://github.com/neophob/nextjs-auth) and there it works as expected, so the error is related to the fastify next integration.
