### ISSUE TITLE
Could we check authenticate for all pages inside same folder at /pages?

### ISSUE THREAD

**Issue by trilam1409** [nextauthjs/next-auth#1338]
**Your question**
I have many pages at /pages/admin/...
I want to redirect to /login page when not login. I try to add the AuthenWrapper component to every page to check authentication.

**What are you trying to do**
I don't know that we have another way to check authentication for all pages inside /pages/admin instead of adding the AuthenWrapper component to any pages or not?

**Reproduction**
```
import { useSession } from 'next-auth/client';
import { useRouter } from 'next/router';

type PropsTypes = {
    children: JSX.Element,
}

const AuthWrapper = (props: PropsTypes) => {
    const [session] = useSession();
    const router = useRouter();

    if (!session) {
        router.push('/auth/login');
    }

    return props.children;
};

export default AuthWrapper;
```
This is my AuthenWrapper.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
I think it's more like a Next.js question, and currently I have two ideas in mind:

1. Do the Auth check in `_app.jsx`
2. Use a catch-all route inside admin, like `[[...admin]].jsx`

Or we could explore this idea from @kripod: https://github.com/nextauthjs/next-auth/issues/1210

**Comment by ttoni** [comment]
@balazsorban44 How could an implementation for scenario 1. look like? 
What would be the prefered way to redirect or router.push(signIn()) from _app.jsx to the login page?

Maybe like this?

```
useEffect(() => {
  if (!session) {
    if (!router.pathname.includes("/auth/signin")) {
      router.push(signIn(), undefined, { shallow: true });
    }
  }
}, []);
```

**Comment by balazsorban44** [comment]
So I was thinking about it, and 1. probably wouldn't be ideal. It would be trying to call the `/api/auth/session` endpoint for every page, even those that wouldn't need auth. I think the best scenario right now is wrap each page individually with some logic as @trilam1409 did in their original post

**Comment by balazsorban44** [comment]
@ttoni So I could not stop thinking about it and after even more thinking, I came up with a (IMO) neat pattern that uses `_app` anyway :grinning:. Have a look at it here: https://github.com/nextauthjs/next-auth/issues/1210#issuecomment-782630909

**Comment by trilam1409** [comment]
> @ttoni So I could not stop thinking about it and after even more thinking, I came up with a (IMO) neat pattern that uses `_app` anyway 😀. Have a look at it here: [#1210 (comment)](https://github.com/nextauthjs/next-auth/issues/1210#issuecomment-782630909)

Your solution could resolve my question. Thank you very much 👍
