### ISSUE TITLE
Cognito authentication not working , How to set-up ?

### ISSUE THREAD

**Issue by Rashmi-278** [nextauthjs/next-auth#1339]
Hey guys , I was having issues implementing AWS cognito auth in next-auth.

If you look at the documentation of next-auth for cognito.
It asks client secret key , but that's not actually supported by AWS cognito is it ? 

How can I make it work please help ?

**What are you trying to do**
Add AWS cognito authentication to my next app using next-auth

**Reproduction**
Download the next-auth-example repo

Add cognito provider in API endpoint

Create the app client as per documentation , without the client secret key while creation ( because AWS cognito doesn't supply secret keys yet ) 

Add the cognito Id and domain name in environment variables and leave the  cognito secret key blank.

**Feedback**

* [x] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [x] Found the example project helpful

**Comment by Rashmi-278** [comment]
@iaincollins @balazsorban44  @Will956  Can you please help ?

**Comment by balazsorban44** [comment]
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-client-apps.html Could this be relevant?

**Comment by Rashmi-278** [comment]
Followed the instructions as per docuemntation
ERROR:
This site can’t be reached
https’s server IP address could not be found.DNS_PROBE_FINISHED_NXDOMAIN
and the oauth flow links to this
https://https//testnextauth1.auth.ap-south-1.amazoncognito.com/oauth2/authorize[…]cope=openid%20profile%20email&client_id=7v9lcvufjsvlaa3akts2ge0mut

**Comment by balazsorban44** [comment]
At a first glance, it does not seem to be a `next-auth` related issue, but also the link you posted is cut off, meaning it cannot be reached (not that it matters in this case, I think.) @LoriKarikari I see you added Cognito in the first place. Do you have any insight?

**Comment by Rashmi-278** [comment]
Here are the steps to reproduce this issue 
https://hackmd.io/ZwAN8iahRQWX5O_mXDArBw

**Comment by Rashmi-278** [comment]
@LoriKarikari  Can you please provide us some insight on how we might  resolve this please ? :)
We had plans to use this for production

**Comment by Rashmi-278** [comment]
Hey ! The issue is resolved ! the problem was with client secret and domain name provision. 

I'll document everything clearly and post a link here for others 
and then close the issue soon. 

have a good one y'all :)

**Comment by balazsorban44** [comment]
Awesome that you managed to solve it! 😍

**Comment by Rashmi-278** [comment]
RESOLVED , Here' the solution 

https://hackmd.io/ZwAN8iahRQWX5O_mXDArBw
