### ISSUE TITLE
Ability to hook into signup

### ISSUE THREAD

**Issue by jasonkuhrt** [nextauthjs/next-auth#1356]
**Summary of proposed feature**

GitHub provider does not guarantee user email. It also does not provide user name.

In our case we want to enforce that all users have email and user name, before creating a new user record in the database for them.

We would like a signup callback hook where we can augment the profile data and validate it. When validation fails there should be a mechanism to display a nice error to the user.

**Detail about proposed feature**
In order to satisfy this requirement we would like to hook into a callback called `signUp`. In here we would like to be able to:

  1. Augment the profile information. 
 
  2. Throw an error with structured metadata. We would like this structured data to be made available to the client for nice error feedback. In our case here we might say something like:

      > Please change your settings on GitHub so that your email is not private.

In the future instead of blocking GitHUb signup when their email is private, we might want to augment the flow with custom UI views where the user can _input their email manually_.

We're not sure how this should be achieved but an idea... redirect to a view (configurable, default `/auth/signup`). The view will do what it needs to do, and send back a request to e.g. `/api/auth/custom-signup-flow-complete`. The payload to this request will contain some data that can be merged into the profile on the backend to complete the signup flow.

And of course a callback hook could be available for any server side processing needs between `/api/auth/custom-signup-flow-complete` and it continuing the the Next Auth signup logic.

To keep things secure a temporary hash could be generated before redirecting to `/auth/signup` that is required to hit `/api/auth/custom-signup-flow-complete`. This hash could be kept in memory or when a db is setup, in the db. This would protect the endpoint from being hit in unexpected ways.

**Potential problems**
Describe any potential problems or potential limitations or caveats that might apply to the proposed solution.

The custom signup redirection stuff seems tricky to get right from a generalized point of view.

**Describe any alternatives you've considered**

Writing our own GitHub provider?

**Comment by balazsorban44** [comment]
Hi there, could this recently made change help here?:

https://github.com/nextauthjs/next-auth/pull/1329

**Comment by jasonkuhrt** [comment]
Hey @balazsorban44, would that solution entail creating a custom provider? https://next-auth.js.org/configuration/providers#using-a-custom-provider

**Comment by balazsorban44** [comment]
No, just add the profile callback to your provider config.

**Comment by jasonkuhrt** [comment]
Ok, TS typings must be off 

![image](https://user-images.githubusercontent.com/284476/108759856-e8302180-751a-11eb-9015-fff71d139533.png)

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth#typescript :slightly_smiling_face:

**Comment by jasonkuhrt** [comment]
@balazsorban44 Just tried it out and that helps a lot!

Makes sense to have this hook at the provider level.

What's mostly missing now is a way to block with a nice user-facing error.

I don't know how much this issue makes sense now.

**Comment by balazsorban44** [comment]
you can use the signIn callback where if you return a string, you can return the user to any page you want.

For example you can check if profile.email is undefined.

**Comment by jasonkuhrt** [comment]
@balazsorban44 I guess with that pattern we could effectively lock the user out of the app until they have fulfilled certain user record requirements.

**Comment by balazsorban44** [comment]
if you return false or a string from the signIn callback, the users won't be logged in to your app! that's the whole point of the signIn callback.

**Comment by jasonkuhrt** [comment]
In our case we would prefer to make strong guarantees about the User model in the database. So we'd want to intercept at signup time.

**Comment by Fronix** [comment]
> In our case we would prefer to make strong guarantees about the User model in the database. So we'd want to intercept at signup time. Instead of e.g. a optional db field for User email that is only optional so that it can be filled in lazily later in the UI.

A way to intercept sign up would be great! There are several cases where you would want to sign in using an external provider, but you want additional information from the user before actually creating the user.

**Comment by trompx** [comment]
Hey @jasonkuhrt, did you manage to add custom data before the user is created or you ended up just login the user, then with a HOC, check if some data are missing and ask for it before redirecting him?
For a user onboarding flow, I'd also prefer to create the user only if all data are provided, so if this is still not supported, could this be reopened please?
Thanks

**Comment by Fronix** [comment]
> Hey @jasonkuhrt, did you manage to add custom data before the user is created or you ended up just login the user, then with a HOC, check if some data are missing and ask for it before redirecting him? For a user onboarding flow, I'd also prefer to create the user only if all data are provided, so if this is still not supported, could this be reopened please? Thanks

Quick tip if you want to solve this without waiting, you can do a patch and add your own callback in [callback-handler.ts](https://github.com/nextauthjs/next-auth/blob/86b7bfdcdc420a7a08547165e36917edd9ac569b/packages/next-auth/src/core/lib/callback-handler.ts#L161) after user is signed in and before user is created. At least that's how I've solved it because we use certain providers that don't have email or usernames.

I won't go into much detail on this solution though because it's kind of a hack and now that nextjs has middleware support there might be a much better solution.

**Comment by Fronix** [comment]
> Hey @jasonkuhrt, did you manage to add custom data before the user is created or you ended up just login the user, then with a HOC, check if some data are missing and ask for it before redirecting him? For a user onboarding flow, I'd also prefer to create the user only if all data are provided, so if this is still not supported, could this be reopened please? Thanks

Quick tip if you want to solve this without waiting, you can do a patch and add your own callback in [callback-handler.ts](https://github.com/nextauthjs/next-auth/blob/86b7bfdcdc420a7a08547165e36917edd9ac569b/packages/next-auth/src/core/lib/callback-handler.ts#L161) after user is signed in and before user is created. At least that's how I've solved it because we use certain providers that don't have email or usernames.

I won't go into much detail on this solution though because it's kind of a hack and now that nextjs has middleware support there might be a much better solution.

**Comment by jasonkuhrt** [comment]
I don't have power to re-open this issue.

**Comment by trompx** [comment]
Thanks for your suggestion @Fronix but I'd rather not resort to a hack to solve this and have to maintain it at each upgrade.
Concerning middlewares, you mean to check if some data are missing in a middleware and redirect to an onboarding page until the data is correctly filled?

**Comment by Fronix** [comment]
> Thanks for your suggestion @Fronix but I'd rather not resort to a hack to solve this and have to maintain it at each upgrade. Concerning middlewares, you mean to check if some data are missing in a middleware and redirect to an onboarding page until the data is correctly filled?

I understand, in our case we had no choice.

Yes, exactly, doing a check in the middleware that will decide if the user need to "do something extra" before being allowed to continue.
