### ISSUE TITLE
Ability to provide additional user data to signin POST submission

### ISSUE THREAD

**Issue by james2406** [nextauthjs/next-auth#1358]
**Summary of proposed feature**
Allow additional user data (e.g. name) to be passed to the signin method and request.

**Purpose of proposed feature**
This will allow users to submit their names during the signup flow.

**Potential problems**
The user will be able to submit their name on both signin and signup as the method is the same. However, it's not too much of an issue because the user can just be taken to a different route (based on whether they want to signin or signup).

**Describe any alternatives you've considered**
Redirect new users to a page after they submit their email where they can submit additional user data.

**Additional context**
<img width="1440" alt="Screenshot 2021-02-22 at 21 45 14" src="https://user-images.githubusercontent.com/10858584/108775465-03218680-7559-11eb-9ba2-76da8a52f545.png">
<img width="1440" alt="Screenshot 2021-02-22 at 21 45 37" src="https://user-images.githubusercontent.com/10858584/108775484-074da400-7559-11eb-857f-dadca81282a2.png">
<img width="1062" alt="Screenshot 2021-02-22 at 21 47 17" src="https://user-images.githubusercontent.com/10858584/108775495-09affe00-7559-11eb-9ba6-2a30e88085e1.png">
<img width="1062" alt="Screenshot 2021-02-22 at 21 47 53" src="https://user-images.githubusercontent.com/10858584/108775502-0b79c180-7559-11eb-98a2-685f24d789b7.png">

**Comment by albertpak** [comment]
👍  i was able to modidy `User` model - but would be great to know how to modify that attribute that was added, let's say user's mood, which is saved on `User` model

**Comment by goforbg** [comment]
Hi were you able to find any alternatives for this?

**Comment by joepetrillo** [comment]
Any updates on this? Trying to do the same thing.

**Comment by NoHara42** [comment]
Also looking to do the same thing. Please keep us updated with solutions. 🙏

**Comment by austintackaberry** [comment]
Can we open this issue? Seems like it is still a problem :pray:

**Comment by jasondainter** [comment]
Did this ever got solved? Having similar issues

**Comment by fkozlicki** [comment]
Yeah, facing exactly same issue.

**Comment by djm158** [comment]
Can we reopen this issue?
