### ISSUE TITLE
Discord Profile Picture

### ISSUE THREAD

**Issue by Shift4id** [nextauthjs/next-auth#1364]
For premium users, your code automatically sets the filetype to gif. [This is the link](https://github.com/nextauthjs/next-auth/blob/e80f6e936d6521aec43da53645ed406feebe09fa/src/providers/discord.js#L18) to the faulty line of code
```js
export default (options) => {
  return {
    // ...
    profile: (profile) => {
      if (profile.avatar === null) {
        const defaultAvatarNumber = parseInt(profile.discriminator) % 5
        profile.image_url = `https://cdn.discordapp.com/embed/avatars/${defaultAvatarNumber}.png`
      } else {
        // THIS LINE HERE ⬇️
        const format = profile.premium_type === 1 || profile.premium_type === 2 ? 'gif' : 'png' // SETS THE FILETYPE TO GIF
        profile.image_url = `https://cdn.discordapp.com/avatars/${profile.id}/${profile.avatar}.${format}`
      }
    },
    // ...
  }
}
```
I have checked the discord API, and instead of assigning the format based on the premium_type attribute of the profile, it is based on the image data. [Source](https://discord.com/developers/docs/reference#image-formatting-cdn-endpoints)
``** In the case of endpoints that support GIFs, the hash will begin with a_ if it is available in GIF format. (example: a_1269e74af4df7417b13759eae50c83dc)``

Your code should instead be
```js
export default (options) => {
  return {
    // ...
    profile: (profile) => {
      if (profile.avatar === null) {
        const defaultAvatarNumber = parseInt(profile.discriminator) % 5
        profile.image_url = `https://cdn.discordapp.com/embed/avatars/${defaultAvatarNumber}.png`
      } else {
        // THIS LINE HERE ⬇️
        const format = profile.avatar.startsWith('a_') ? 'gif' : 'png' // Checks if string begins with a_ to determine whether the filetype is a gif or png.
        profile.image_url = `https://cdn.discordapp.com/avatars/${profile.id}/${profile.avatar}.${format}`
      }
    },
    // ...
  }
}
```

Feel free to ask me any questions you have regarding this issue if you would like me to clarify.

**Comment by balazsorban44** [comment]
Thanks for providing both a bug report, a source to the docs, and a solution for this! Nice work!

**Comment by Daggy1234** [comment]
so sorry for doing this, Kinda slipped my mind that non-nitro gif users existed. So sorry
