### ISSUE TITLE
Is it possible to add more fields to session[.user]?

### ISSUE THREAD

**Issue by ArcticSpaceFox** [nextauthjs/next-auth#1372]
**Your question**
I want to check if a user has a certain role and then depending on taht role load data, is it secure to do that with the session?
Is it possible to add a field to the session that tracks the role for a user?

**What are you trying to do**
I am trying to load data differently for certain roles

**Feedback**

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by luizhcardim** [comment]
Look here: 
https://stackoverflow.com/questions/64576733/where-and-how-to-change-session-user-object-after-signing-in/64595973#64595973

**Comment by ArcticSpaceFox** [comment]
Thank you so much that is so helpful. Sry that i missed that 😅👍 have an awesome day

**Comment by balazsorban44** [comment]
FWIW, it's in the docs as well :slightly_smiling_face: 
https://next-auth.js.org/configuration/callbacks#jwt-callback
https://next-auth.js.org/configuration/callbacks#session-callback
