### ISSUE TITLE
callbackUrl is not URL encoded when custom login page is applied

### ISSUE THREAD

**Issue by geekdada** [nextauthjs/next-auth#1375]
**Describe the bug**

https://github.com/nextauthjs/next-auth/blob/564b342f6903421744a4c55a14b8ebdfabbef67b/src/server/index.js#L151-L155

The URL would be messed up if error is shown in the URL, because `callbackUrl` is not encoded.

**Steps to reproduce**

The description is enough I guess, but I will provide one if needed.

**Expected behavior**
URL should be encoded, whether the error exists.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Can you please confirm this with a reproduction? 🙏

**Comment by joostvanwollingen** [comment]
> Can you please confirm this with a reproduction? 🙏

I've set up an example here: https://github.com/joostvanwollingen/next-auth/tree/issue-1375

### Steps to reproduce
- Checkout the branch
- Create .env file and enter values for the keys below:
```
DISCORD_CLIENT_ID=
DISCORD_CLIENT_SECRET=
REDDIT_CLIENT_ID=
REDDIT_CLIENT_SECRET=
BASE_URL='http://localhost:3000
```
- Run `yarn dev`
- Go to main page, top left will show a button `sign in`
- Click it to go to the custom login page. Notice the callbackUrl query param is not encoded.
- Select a login provider and login
- After authentication you will be redirected back to the custom login page at `http://localhost:3000/auth/signin?callbackUrl=http://localhost:3000/#_`
- Expected result: redirected back to `http://localhost:3000/`

**Comment by geekdada** [comment]
@joostvanwollingen Thank you!

**Comment by balazsorban44** [comment]
will look into this and get back to you!

**Comment by ndom91** [comment]
@joostvanwollingen so I noticed if you define the callbackUrl manually in the `signin()` call on the custom signin page in your example, it seems to work.

**Comment by balazsorban44** [comment]
You can also utilize the `useRouter()` and do it like so:
```jsx
export default function SignInPage() {
  const {callbackUrl} = useRouter().query
  return (
    <button onClick={() => signIn(provider.id, { callbackUrl })}>Sign in with {provider.name}</button>
  )
}

**Comment by balazsorban44** [comment]
The question is, does this resolve your original issue @geekdada? You haven't actually provided a reproduction with the problem, so I am not sure here...

**Comment by joostvanwollingen** [comment]
@ndom91 @balazsorban44 Completely missed that in the docs, thanks for clarifying. 

I've opened https://github.com/nextauthjs/next-auth/pull/1406 to clean up one of the examples in the docs regarding the context being passed to the providers call

**Comment by dimitrisnl** [comment]
Hey there, what about if the user lands in the page by typing the path in the URL? 

In my case, I'm using the Email provider, and if there is an error, the page refreshes with the following:

`http://localhost:3000/auth/login?callbackUrl=http://localhost:3000/#&error=EmailSignin`

Consequently the `error` won't be available

```ts
Login.getInitialProps = async (context) => {
  return {
    csrfToken: await csrfToken(context),
    errorCode: context.query.error,
  };
};
```

Thoughts?

**Comment by balazsorban44** [comment]
This seems to be an unrelated question, but you could use `useRouter` to obtain the error
https://nextjs.org/docs/api-reference/next/router


or you could simply use the `signIn` function without redirect https://next-auth.js.org/getting-started/client#using-the-redirect-false-option
