### ISSUE TITLE
Stored JSON Web token is not updated when using getSession()

### ISSUE THREAD

**Issue by matthewgalang** [nextauthjs/next-auth#1381]
**Describe the bug**
Using `getSession()` invokes the JWT callback by calling `/api/auth/session` but does not update the JSON web token stored in the cookie `next-auth.session-token`.

**Steps to reproduce**
1. [Secure an api route using getSession](https://next-auth.js.org/tutorials/securing-pages-and-api-routes#using-getsession).
2. Modify data in the JSON web token in the [JWT callback](https://next-auth.js.org/configuration/callbacks#jwt-callback).
3. Refresh the secure api route
4. Observe the stored JWT and returned JWT

[Example repository](https://github.com/matthewgalang/next-auth-issue) for reproduction.
In the example repository, I edited the JWT callback to return the token with a modified value and logged the token before modification to the terminal to be observed.

**Expected behavior**
If I continuously refresh the API route at `api/example/protected`, the stored JWT should be modified over time. I'm expecting this because `getSession()` should invoke the JWT callback which I'm led to believe will update the JWT.

**Screenshots or error logs**
```
async jwt(token, user, account, profile, isNewUser) { 
      if(user) {
        return {
          ...token,
          modifiedCount: 0
        }
      }
      console.log(token)
      return {
        ...token,
        modifiedCount: token.modifiedCount + 1,
      }
    }
```

**Additional context**
The stored JWT is also not modified _sometimes_ when using client-side navigation. The stored JWT **IS** modified when refreshing any non-api page and switching between tabs. This odd behavior must be related to `useSession()` but I can open a new topic if needed.

This will affect any implementation that depends on and manipulates data using the JWT callback (e.g. [refresh token rotation](https://next-auth.js.org/tutorials/refresh-token-rotation))

Overall, it seems that the JWT callback _sometimes_ updates the JWT but only for certain next-auth API methods which is not clearly documented.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
In the example repository sessions are configured to be valid for 30 days and to be updated only every 24 hours.

If you change this value to more frequently (or even to 0) it will be rotated, and the callback invoked, more often. You may incur additional costs with your hosting provider if you do this.

https://next-auth.js.org/configuration/options#session

**Comment by iaincollins** [comment]
You may also find the options for the React Provider relevant; they can control how often the client will actually poll the server in normal operation, outside of events like change of focus.

If this does not resolve your issue feel free to ask for help in the Discussion forum

**Comment by balazsorban44** [comment]
Here is the docs for the Provider Iain is talking about:

https://next-auth.js.org/getting-started/client#provider

**Comment by matthewgalang** [comment]
@iaincollins @balazsorban44 Changing the options for the session configuration did not resolve the issue. Changing the options for the React Provider option did change the polling frequency at which the JWT was updated BUT it did not resolve the issue for the specific use case when using `getSession()` for a secured api route.

I'm thinking that only it is only possible to update the JWT using `useSession()` and `getSession()` does not. Is this intentional?

**Comment by balazsorban44** [comment]
In your example repo you have the following line:
```js
async session(session, user) { return session },
```

In case you don't use a database, the name `token` or `jwt` would actually be more proper for the second param.

In that case, it might be more obvious that to get the updated cookie in your session request, you actually have to expand the session callback to something like this:

```js
async session(session, token) {
  session.modifiedCount = token.modifiedCount
  return session
},
```

Adding new properties to the session cookie through the `jwt` callback does not automatically make them available at the session endpoint, for increased security. You have to be explicit and state which properties you want to make available through the `session` callback.

**Comment by matthewgalang** [comment]
By inspection of the JWT stored at `next-auth.session-token` cookie in the browser after calling the secure api route multiple times, making changes to the session callback does not resolve the issue. Additionally, there are several reasons to keep data within the JWT and not assigned to the session. For example, in the [docs for refresh token rotation](https://next-auth.js.org/tutorials/refresh-token-rotation), the refresh token is read and stored in the JWT and not assigned to the session. The issue still stands.

**Comment by matthewgalang** [comment]
I've concluded that using `getSession()` during client side rendering saves the updated JWT in the cookie. In contrast, using `getSession()` on secured API routes and during server side rendering does not. I think this is intentional since the JWT cookie can only be stored on the browser and therefore cannot be manipulated since the browser cannot set it during server side rendering. This includes Next's server side functions like `getServerSideProps` and api routes. Can anyone confirm that this is correct when using `getSession`?

Here's an example of using `getSession()` with client side rendering in my example repo that demonstrates the expected behavior:
```
// pages/client.js

export default function Page () {
  async function myFunction() {
    const session = await getSession()
    const token = await fetch('api/examples/jwt')
    const response = await token.json()
    console.log('jwt', response) // Logs the currently stored and returned JWT from the JWT callback
  }

  useEffect(() => {
    myFunction();
  })
  ...
}
```

Cases that implement refresh token rotation or require reading and updating data in the JWT should utilize client side rendering similar to what I describe above. Hopefully this helps anyone who approaches this issue.

**Comment by avisra** [comment]
@balazsorban44 @iaincollins can someone answer his question above? I am also curious on this, as it does not appear to be documented if it is true - but I have the same findings. If the JWT callback is triggered from getSession in an API route - will updates persist there or not?

**Comment by matthewgalang** [comment]
@avisra In my investigation of the issue, I don't think the behavior for JWT callback modifications to persist specifically through Next's server-side operations like API routes and getServerSideProps are [documented where expected](https://github.com/nextauthjs/next-auth/blob/aacc34bbfdda764389d4e906490ebfe7364b35a2/src/server/routes/session.js#L52).

Although it appears in the source that [JWT callback modifications](https://github.com/nextauthjs/next-auth/blob/aacc34bbfdda764389d4e906490ebfe7364b35a2/src/server/routes/session.js#L42) are expected to be updated in the [cookie](https://github.com/nextauthjs/next-auth/blob/aacc34bbfdda764389d4e906490ebfe7364b35a2/src/server/routes/session.js#L52), I haven't found it to perform as expected during server side operations.

This led me to conclude the behavior I [commented](https://github.com/nextauthjs/next-auth/issues/1381#issuecomment-787508497) earlier, such that session and jwt callback modifications will work as long as they are executed from client side methods.

------------------
but...

@balazsorban44 @iaincollins A proper solution might be to ensure that the cookie is being set with any callback modifications during Next's server side operations. 

I finally settled my issue by modifying the request headers to use the current cookie for the request parameter in getSession, reading the new cookie after the callback modifications, then applying the new cookie in the response headers. This was done using an additional dependency for reading, writing, and applying cookies. I updated my [example repository](https://github.com/matthewgalang/next-auth-issue) to illustrate how the cookie now updates after each visit to a [protected api route](https://github.com/matthewgalang/next-auth-issue/blob/main/pages/api/examples/protected.js).

There are several caveats with my approach that may not be recommended for production or related to my use case, so readers beware.
