### ISSUE TITLE
sync encode/decode from next-auth/jwt

### ISSUE THREAD

**Issue by jasonkuhrt** [nextauthjs/next-auth#1388]
**Summary of proposed feature**
Allow sync decode/encode api from `next-auth/jwt`.

**Purpose of proposed feature**
Allow integration testing with Jest.

**Detail about proposed feature**
Using `next-auth/jwt` for tests is useful as it allows mocking fewer things, creating a token that a client uses to call the running server in an integration test, for example.

The encode/decode exported functions are async.

Jest is a test runner that supports setting up logic before tests suites, but only synchronous (the exception is the global setup file, but it cannot expose global variables for test suites). Often in setup it is useful to expose things on global for all tests. we for example seed users into the database and then expose the created users data onto the global scope.

This these two points make integration hard, because next-auth jwt async and jest test setup are a pain.

The proposal is to expose a sync variant of the encode/decode api found in `next-auth/jwt`.

**Potential problems**
Describe any potential problems or potential limitations or caveats that might apply to the proposed solution.

**Describe any alternatives you've considered**
None

**Additional context**
None

**Comment by balazsorban44** [comment]
Could you please fill out the whole feature request issue template? 🙏 https://github.com/nextauthjs/next-auth/issues/419

**Comment by huynhminhcanh** [comment]
- @
