### ISSUE TITLE
Auto redirect to the provider's Login Page

### ISSUE THREAD

**Issue by sebastienlabine** [nextauthjs/next-auth#1404]
Hi,

My use case is pretty simple: I have a IdentityServer4 server acting as my OAuth2 provider. It has all the pages I required to login, signup, confirm email of users, etc...

With react, I could use oidc-client to setup IdentityServer4 as my provider, and automatically redirect the user to my oauth login page. I want to be able to translate this behaviour in NextAuth. I don't want to build the whole UI for login. I just want to be able to use the useSessionHook, then redirect to my provider if not logged in. Same goes for logging out.

Is it possible to impletement?

**Comment by balazsorban44** [comment]
Please use the correct issue template for questions next time, and check out the docs:

https://next-auth.js.org/getting-started/client#starts-google-oauth-sign-in-flow-when-clicked

**Comment by mujtabafurqan** [comment]
hey @sebastienlabine , did you find a solution to this?
