### ISSUE TITLE
Invitation only signup

### ISSUE THREAD

**Issue by ericvrp** [nextauthjs/next-auth#141]
Is there something written about how to do this with NextAuth? If not a would like to request this feature.

**Comment by iaincollins** [comment]
I absolutely want to add this!

The current email system was designed with this in mind as it's a use case I have too, and is part of the reason why it doesn't create an account until AFTER an email address has been verified.

However, I'm not quite sure how these could be generated currently as there is no admin interface.

I guess a simple admin interface, where you can paste in email address - and customise the invite message - might suffice. Another alternative is a command line interface that takes a text file or CSV with a list of email addresses.

**Comment by iaincollins** [comment]
One option I'm considering, as an interim option, is to allow people to restrict access using a function which checks who can sign up and only allows sign in from allowed accounts (e.g. from a hard coded list, a list read from a file or google sheet, or a list of domains).

This would only work securely for Email sign up, or providers like Google with the verified email address option, but it would provide very similar functionality - effectively you'd just have to email people invitations yourself.

**Comment by ericvrp** [comment]
Sounds good I think. And the invited users would be required to set a password?

**Comment by slaivyn** [comment]
this library is awesome! I have recently adapted some old passwordless login module to next.js but it is definitively not secured enough for a serious project.
Now that I need more security I am very happy to discover your work!
And I would be very interested to have the type of feature your are discussing here. For my current project and others: I hate passwords and non-corporate oAuth is often refused by my clients. So every time I try to convince them to choose passwordless login. And there is often this need of a constrained signup. It could be based on a white list of e-mail addresses or domain names.
@iaincollins the validating function your are suggesting would be a very good starting point as anyone would be able to implement his own validation logic.

**Comment by iaincollins** [comment]
@slaivyn Thanks for the feedback!

Yes, the `SignIn()` callback can be used to reject sign in for disallowed email addresses (either by domain or by whitelist). 

This works well for things like corporate or admin dashboards, with email sign in and with OAuth providers like Google that supply an `email_verified` flag so you know it's verified. 

This approach can be used to limit who can sign in to a site without a user database using a check like `profile.email_verified && profile.email.endsWith('@example.com')`, an array of allowed addresses, a text file or a spreadsheet.

This is something I intend to write up a tutorial for soon!

**Comment by slaivyn** [comment]
Great! Thank you for the tip!
This is good enough for my needs. And my client has accepted the passwordless strategy 🍾
