### ISSUE TITLE
Expected 2-3 arguments, but got 1

### ISSUE THREAD

**Issue by Baterka** [nextauthjs/next-auth#1417]
**Describe the bug**
`TS2554: Expected 2-3 arguments, but got 1.  index.d.ts(127, 48): An argument for 'res' was not provided.`

**Steps to reproduce**
```
import NextAuth from "next-auth"
import Providers from "next-auth/providers"
import Adapters from 'next-auth/adapters'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

export default NextAuth({   <----- Error starts here
  providers: [
    Providers.Discord({
      clientId: process.env.DISCORD_CLIENT_ID,
      clientSecret: process.env.DISCORD_CLIENT_SECRET
    })
  ],
  adapter: Adapters.Prisma.Adapter({ prisma }),
}); <----- Error ends here
```

**Expected behavior**
No type error

**Additional context**
```
"next": "^10.0.7",
"next-auth": "^3.7.0",
"@types/next-auth": "^3.1.25", 
```

* [ ] Found the documentation helpful
* [X] Found documentation but was incomplete
* [X] Could not find relevant documentation
* [ ] Found the example project helpful
* [X] Did not find the example project helpful

**Comment by StefanSelfTaught** [comment]
You can use it like this until it's resolved.

```ts
import NextAuth from "next-auth"
import Providers from "next-auth/providers"
import Adapters from 'next-auth/adapters'
import { PrismaClient } from '@prisma/client'
import { NextApiHandler } from 'next';

const options = {
  providers: [
    Providers.Discord({
      clientId: process.env.DISCORD_CLIENT_ID,
      clientSecret: process.env.DISCORD_CLIENT_SECRET
    })
  ],
  adapter: Adapters.Prisma.Adapter({ prisma }),
}

const authHandler: NextApiHandler = (req, res) => NextAuth(req, res, options);

export default authHandler

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth#typescript

**Comment by StefanSelfTaught** [comment]
That error is present even with `@types/next-auth` installed

**Comment by balazsorban44** [comment]
I'm aware, but as we state in the link above:

> As of now, TypeScript is a community effort. If you encounter any problems with the types package, please create an issue at DefinitelyTyped. Alternatively, you can open a pull request directly with your fixes there

**Comment by Baterka** [comment]
Any recommendations how to edit it in types to make pull request in their repo?

**Comment by balazsorban44** [comment]
if you mean it locally, check out module augmentation https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation

otherwise just open a PR to DefinitelyTyped following their guides and wait for it to be merged

**Comment by lluia** [comment]
Thanks for raising it @Baterka 🙌🏽 💯 . This [bit of code](https://github.com/nextauthjs/next-auth/blob/main/src/server/index.js#L249-L256) changed, and now `NextAuth()` can be called with just 1 argument. It shouldn't be hard to update the types; I'll look at it  today 💭 and post the state of the PR here 👍🏽

**Comment by lluia** [comment]
FYI the PR ☝🏽 to address this issue.

I'll need reviews from some of the other owners of the types ( either @JuanM04 or @iaincollins )

**Comment by balazsorban44** [comment]
@lluia do you know who adds owners to the types? I might be able to help out time-to-time, either with a review or update types whenever something changes in core.

**Comment by lluia** [comment]
@balazsorban44 I [added you](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51575/files#diff-9fda210ef628d559546e578a73049a164e92d7c27280ce4301e4076745300db1) 👍🏼 , you'll get notifications now to review PRs 🙌🏽  ( we could discuss as well whether the team prefers to keep the types external or have them moved to this repo )

**Comment by balazsorban44** [comment]
It think @iaincollins would still prefer if we just keep these separated for now, and forward issues to DefinitelyTyped if they are TS related. I'll try updating some stuff over there and will help with reviewing PRs. That would hopefully make TS users happier as well.

(note. I started added .d.ts files in this repo but only for internal use at this moment. might be useful resource for when someone works on @types/next-auth

**Comment by lluia** [comment]
@Baterka this [has been addressed](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51575), if you pull the latest version of the types ( `3.7.0` )
```
$ yarn add -D @types/next-auth
```
you shouldn't hit this error anymore 📐
