### ISSUE TITLE
A config way to override server/routes/signin to pass down email being verified in case of email auth.

### ISSUE THREAD

**Issue by agustif** [nextauthjs/next-auth#1423]
**Summary of proposed feature**
I would like a way similarto how pages config works

**Purpose of proposed feature**
to modify how signin works in this page
https://github.com/nextauthjs/next-auth/blob/76df2b5e702be2084674c81e098d989c2ec39ed9/src/server/routes/signin.js

IN my case I want to pass down the email being verified, so I can show it in the verify'request page similar how slack does it.

Right now can´t read it from anywhere.

**Detail about proposed feature**
A way to extend-config server routes behaviour passing it as a config object like pages for frontend right now works.
**Potential problems**
too much custom need- or info being passed_
Describe any potential problems or potential limitations or caveats that might apply to the proposed solution.

**Describe any alternatives you've considered**
Reading session with useSession or getSession, but since not authenticated not gonna work, also saving something in cookie-localstorage-jwt or something when doing the sign in so I can read the email

**Additional context**
Any other context, screenshots, etc.

*Please indicate if you are willing and able to help implement the proposed feature.*
Im willing and able to implement it if makes sense

**Comment by balazsorban44** [comment]
Do you maybe have an English screenshot, please? 🙂

**Comment by agustif** [comment]
> Do you maybe have an English screenshot, please? 🙂

Not really will make one later.

Main point is I want to have access to email being verified on verify-request so I can show it in the UI to the user, so he or she can spot any typos and ask for another link.

**Comment by agustif** [comment]
https://github.com/nextauthjs/next-auth/blob/76df2b5e702be2084674c81e098d989c2ec39ed9/src/server/routes/signin.js#L69-L72

I would like to pass down the actual email from this signin function
from this```
    return res.redirect(`${baseUrl}${basePath}/verify-request?provider=${encodeURIComponent(
      provider.id
    )}&type=${encodeURIComponent(provider.type)}`)
  }
```
To this:
```
++
    return res.redirect(`${baseUrl}${basePath}/verify-request?provider=${encodeURIComponent(
      provider.id
    )}&type=${encodeURIComponent(provider.type)}&email=encodeEmail(email)`)
```

So in verify-request page I can read from the url being called such email and show it in the UI to the user to spot typos in.

**Comment by balazsorban44** [comment]
I would rather try the `redirect: false` option on the `signIn` function to achieve this.

https://next-auth.js.org/getting-started/client#using-the-redirect-false-option

you'll get the result back as the a promise from signin, then you can update your UI accordingly. You'll still have the user's typed in email as well.

**Comment by agustif** [comment]
Thanks @balazsorban44 that makes much more sense and I was way over-engineering. will try it the way you said.
