### ISSUE TITLE
Additional parameters on GitHub Provider when signing in

### ISSUE THREAD

**Issue by luizwhite** [nextauthjs/next-auth#1434]
**Describe the bug**

I can't give the GitHub Provider another parameter like `login`. It just vanishes and NextAuth doesn't use that:
```js
...
  providers: [
    Providers.GitHub({
      login: 'luizwhite',
      clientId: process.env.GITHUB_CLIENT_ID || 'default',
      clientSecret: process.env.GITHUB_CLIENT_SECRET || 'default',
    }),
  ]
...
```

**Steps to reproduce**
`signIn('github')` OR `signIn()` then click Github

**Expected behavior**

I expect my `signIn('github')` method to give GitHub a URI like that:
```
https://github.com/login/oauth/authorize?client_id=CLIENT_ID&login=luizwhite&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fauth%2Fcallback%2Fgithub&scope=user&state=5cd91b84427c6c4f4aec585312df6a5098059caff43a1fb147ebb94730efcd1f
```

**Additional context**
Using last version of NextAuth and next@10.0.7 

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

##  EDIT:

For anyone coming here, the problem was that the documentation is [**unclear**](https://next-auth.js.org/getting-started/client#additional-params) (to me) when using a third parameter with the signIn method, and it only works with undefined on the second parameter (not null). Besides, my TS is giving me error because it gets the declare function of signIn on `./node_modules/next-auth/client.d.ts`

![image](https://user-images.githubusercontent.com/4944479/109962098-90877800-7cc9-11eb-8ca8-f7d9ce9a264d.png)

![Sem título](https://user-images.githubusercontent.com/4944479/109963141-d2fd8480-7cca-11eb-8b4b-68f825e0032c.png)

**Comment by StefanSelfTaught** [comment]
Try to do it like this:
```js
...
providers: [
  Providers.GitHub({
    params: {},
    authorizationParams: {},
    clientId: process.env.GITHUB_CLIENT_ID || 'default',
    clientSecret: process.env.GITHUB_CLIENT_SECRET || 'default',
  }),
]
...

**Comment by luizwhite** [comment]
@StefanSelfTaught i just solved my issue, thanks!
See my EDIT in my issue. If there is something you could do to about that

**Comment by balazsorban44** [comment]
Regarding TS issues: https://github.com/nextauthjs/next-auth#typescript

Regarding the unclear documentation, do you maybe have a suggestion on how to make it more clear?

**Comment by luizwhite** [comment]
@balazsorban44 tks for the explanation!

About the doc, which are the cases when null in the second parameter doesnt give me error because of the callbackUrl?

Maybe update the doc example with 'null or undefined', because when i got the error I thought "I'm doing something wrong", and in a way I wasnt

_Ps.: can you link me to doc that explains me how I update my session user object? I have to get the adapter and call updateUser? I could find it.. _

**Comment by luizwhite** [comment]
About the TS issue, here is the PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51605
