### ISSUE TITLE
Is it possible to configure the hashing options for passwords in NextAuth (eg: salt, rounds)?

### ISSUE THREAD

**Issue by colin-bethea** [nextauthjs/next-auth#1436]
**Your question**
Is it possible to configure the hashing options for passwords in NextAuth (eg: salt, rounds)?

**What are you trying to do**
We're migrating from Auth0 to NextAuth and need to find a method of mimicking their hashing configuration (in order to migrate our password hashes correctly).

**Reproduction**
N/A

**Feedback**
N/A

* [ ] Could not find relevant documentation

**Comment by StefanSelfTaught** [comment]
You could implement your own logic in the `authorize` function:
```js
export default NextAuth({
  providers: [
    Providers.Credentials({
      async authorize(credentials) {
        ...
    }),
  ],
});
```
As the docs said:
> It comes with the constraint that users authenticated in this manner are not persisted in the database, and consequently that the Credentials provider can only be used if JSON Web Tokens are enabled for sessions.

Read more here: https://next-auth.js.org/providers/credentials
