### ISSUE TITLE
getToken({ ... raw: 'true' }) not encoded correctly.

### ISSUE THREAD

**Issue by pawsaw** [nextauthjs/next-auth#1437]
```js
const token = await getToken({
    req,
    secret,
    raw: 'true',
  });
```
generates Tokens like this:
```
eyJhbGciOiJIUzUxMiJ9.eyJuYW1lIjoiUGF3ZWwgU2F3aWNraSIsImVtYWlsIjoicHVibGljQHBzYXdpY2tpLmRlIiwicGljdHVyZSI6Imh0dHBzOi8vcGxhdGZvcm0tbG9va2FzaWRlLmZic2J4LmNvbS9wbGF0Zm9ybS9wcm9maWxlcGljLz9hc2lkPTE2MjQxODI0MjExMzM1MTQmaGVpZ2h0PTUwJndpZHRoPTUwJmV4dD0xNjE3NDQ1NjE2Jmhhc2g9QWVUdFZycTBkM0NucFJSVnZnZyIsInN1YiI6Ijk5Njg2NDU3LTFkMjItNDgwOS04ZjJlLTUwMDAyY2JlODQ1YiIsImlhdCI6MTYxNDg3OTcyMSwiZXhwIjoxNjE3NDcxNzIxfQ.m8dANEgnAdjoAIIiPUh8OsBdTO92m21dUAqXx-coa3Ah9kbI169beJ68C5BlqPpBJcxtwWHMKJy9Y09uTns5QQ\r\n
```
... take a careful look on the end of the token, it contains **illegal characters**. 
Therefor most services fails on most implementations, including https://jwt.io/

Usually it should be `base64urlencoding` encoded.

```js
let jwt = 'eyJhbGciOiJIUzUxMiJ9.eyJuYW1lIjoiUGF3ZWwgU2F3aWNraSIsImVtYWlsIjoicHVibGljQHBzYXdpY2tpLmRlIiwicGljdHVyZSI6Imh0dHBzOi8vcGxhdGZvcm0tbG9va2FzaWRlLmZic2J4LmNvbS9wbGF0Zm9ybS9wcm9maWxlcGljLz9hc2lkPTE2MjQxODI0MjExMzM1MTQmaGVpZ2h0PTUwJndpZHRoPTUwJmV4dD0xNjE3NDQ1NjE2Jmhhc2g9QWVUdFZycTBkM0NucFJSVnZnZyIsInN1YiI6Ijk5Njg2NDU3LTFkMjItNDgwOS04ZjJlLTUwMDAyY2JlODQ1YiIsImlhdCI6MTYxNDg3OTcyMSwiZXhwIjoxNjE3NDcxNzIxfQ.m8dANEgnAdjoAIIiPUh8OsBdTO92m21dUAqXx-coa3Ah9kbI169beJ68C5BlqPpBJcxtwWHMKJy9Y09uTns5QQ\r\n'

const JWT_REGEX = /^[a-zA-Z0-9\-_]+?\.[a-zA-Z0-9\-_]+?\.([a-zA-Z0-9\-_]+)?$/;

JWT_REGEX.test(jwt) // --> false --> wrong format
```

Fails with NESTJs.

**Comment by pawsaw** [comment]
For now I managed to get a correct token, using 'jwt-simple'.

Example:
```ts
import axios from 'axios';
import { NextApiRequest, NextApiResponse } from 'next';
import { getToken } from 'next-auth/jwt';
import jwt from 'jwt-simple';

const secret = process.env.SECRET;

export default async (req: NextApiRequest, res: NextApiResponse<unknown>): Promise<void> => {
  const url = 'http://localhost:3001/profile';
  const token = await getToken({
    req,
    secret,
  });
  const encodedToken = jwt.encode(token, secret, 'HS512');
  const response = await axios.get(url, {
    headers: {
      Authorization: `Bearer ${encodedToken}`,
    },
  });

  res.status(200).json({ profile: response.data });
};

```

**Comment by iaincollins** [comment]
Please use the provided issue template when creating a new issue. 

It's not clear what you are trying to achieve.

You can use custom `encode` and `decode` functions to define how JSON Web Tokens are encoded / decoded:
https://next-auth.js.org/configuration/options#jwt

_Note: You will almost always need to use these and/or the `jwt` callback to define custom encoding/signing/encrypting and/or claims if you want to use a use the same JSON Web Token with NextAuth.js with other sites / frameworks._

We could consider introducing base 64 encoding as an simple option but as it would increase the pay load by 33% I'm not inclined to recommend this as the default behaviour without a clearly understood use case.

_i.e. to understand if it is something people are trying to do with good reason and if the change will actually help them (obviously it's of no value if it simply results in a larger token that still doesn't interoperate in the desired scenario for other reasons)_

**Comment by Fronix** [comment]
@iaincollins From my undestanding, the `decode()` function in `getToken()` can't be overridden since it calls the `jwt.js` file's decode function.

**Comment by iaincollins** [comment]
> @iaincollins From my undestanding, the `decode()` function in `getToken()` can't be overridden since it calls the `jwt.js` file's decode function.

Thanks, just took a look and can confirm that assertion is correct:
https://github.com/nextauthjs/next-auth/blob/main/src/lib/jwt.js#L129

I think we should probably fix that, and allow `decode()` to be passed as an argument to the helper for convenience.

Am happy to regard that as a valid bug as it's confusing and I don't think is what is intended.

It should be quick fix to add the option to somewhere around Line 109:
https://github.com/nextauthjs/next-auth/blob/main/src/lib/jwt.js#L109

As the function is quite small, in the interim is probably worth just implementing it locally - the only interesting bit really is the cookie name handling behaviour, which has it check for a prefixed cookie name in production (HTTPS) and a non-prefixed cookie name in development (HTTP).

**Comment by Fronix** [comment]
@iaincollins I forgot to also mention that I wrote about it here as well https://github.com/nextauthjs/next-auth/issues/484#issuecomment-800858316
