### ISSUE TITLE
Getting session on invalid uri on visibilitychange with NEXTAUTH_URL to be set

### ISSUE THREAD

**Issue by TotallWAR** [nextauthjs/next-auth#1441]
**Describe the bug**
Session request is sent on invalid (default) uri on `visibilitychange` event however NEXTAUTH_URL is set.
Other requests (server side, sign in and session are working great)

**Steps to reproduce**
- set NEXTAUTH_URL=https://example.com/prefix/api/auth (**note** it's with prefix!)
- setup jwt authorisation with credentials provider
- build project
- start project in production mode
- signin
- after redirect to your home page change focus to other window to produce `visibilitychange` event
- see console error output:
```
GET https://example.com/api/auth/session 404
next-auth][error][client_fetch_error]
POST https://example.com/api/auth/_log
```

**Expected behavior**
I expect request to be sent to `https://example.com/prefix/api/auth/session`

**Screenshots or error logs**
<img width="1439" alt="Screenshot 2021-03-05 at 02 58 44" src="https://user-images.githubusercontent.com/11501611/110047311-b6ab2780-7d5e-11eb-8eb5-676792236d1d.png">

**Feedback**
https://next-auth.js.org/errors#client_fetch_error

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [*] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
coups you specify which version are you using?

**Comment by ThangHuuVu** [comment]
Hi, @TotallWAR , I'm closing this one because it was opened against v3 which is no longer maintained 👀
If you or anyone are still having this issue, feel free to open a new one against our latest package@auth/core 🙌 Thanks for your understanding 🙇‍♂️
