### ISSUE TITLE
Access request and response objects in authorize method

### ISSUE THREAD

**Issue by nickfla1** [nextauthjs/next-auth#1445]
**Your question**
Is it possible to access the request and response objects from the credentials provider authorize method?

**What are you trying to do**
I would like to set some cookies at the end of the authentication process, to do so I need the original request and response objects used to handle the request.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Hi there, could you tell us a bit more about your use-case? What kind of cookie would you like to set?

**Comment by nickfla1** [comment]
Hi, of course, sorry for not being clear.
The application uses one time cookies to display error messages and old form inputs and we would like to use the same mechanism on login and registration pages. I know that you can throw an exception or return an error from the authorize callback to redirect with a message, it's the current implementation, but is not ideal.

**Comment by balazsorban44** [comment]
Have you seen the `redirect: false` option of `signIn`? https://next-auth.js.org/getting-started/client#using-the-redirect-false-option

**Comment by nickfla1** [comment]
Didn't think about it. I will try moving the error management client side. I'll let you know. 
Thanks!

**Comment by balazsorban44** [comment]
it probably gives a much better user experience. The reason its not the default that it's a recent addition, and if we wanted to make it the default, it would be a breaking change (we might do that in a future major release)

**Comment by richchurcher** [comment]
One use-case I've struck is the need to access an existing session cookie from a legacy application on the same domain. The request object in particular would be very useful context here.

**Comment by yuzhakovvv** [comment]
In my case the service I use to authenticate has "Set-Cookie" header. So this header is lost and isn't passed to client where it should set a cookie.

@balazsorban44 any solutions for this?

**Comment by balazsorban44** [comment]
We do expose the request as an option now! Will have to check if there is a good reason to expose response as well.
