### ISSUE TITLE
Multiple (rapid) requests for refresh token (following documentation)

### ISSUE THREAD

**Issue by avisra** [nextauthjs/next-auth#1454]
**Describe the bug**
I setup the refresh token rotation copying the code form the tutorials section. However, on page refresh after the expiration... my refresh token is failing, and by adding console.logs to the different areas in the code, I determined that it is calling refreshAccessTokens two times (back to back, rapid fire, with the same refresh token). The first response is successful - the second response is not. And its the second response which fails everything because after the first request - it invalidates the refresh token - so the second one fails.

**Steps to reproduce**
Setup the refresh token example with IdentityServer4 as the provider.

**Additional context**
Using IdentityServer4 as the provider

![image](https://user-images.githubusercontent.com/433538/110198526-2bdf3100-7e21-11eb-910f-ae3f44fce35f.png)

**Comment by balazsorban44** [comment]
would you be able to share some of your code/configuration?

We are using this technique at work together with IDS4 and works fine. So it must be some misconfiguration on your side.

400 means bad request, so might be sending something that is not supposed to be sent or something similar.
