### ISSUE TITLE
Dynamic profileUrl

### ISSUE THREAD

**Issue by unsphere** [nextauthjs/next-auth#1460]
First, thanks for the lib. Really easy to use.

I am in a situation where I need to use a profileUrl based on the tenant id of the logged user.

My custom provider looks like this:

```
{
  id: 'superoffice',
  name: 'SuperOffice',
  type: 'oauth',
  version: '2.0',
  scope: 'openid',
  params: {
    grant_type: 'authorization_code',
  },
  accessTokenUrl: `https://${process.env.SUPEROFFICE_ENV}.superoffice.com/login/common/oauth/tokens`,
  authorizationUrl: `https://${process.env.SUPEROFFICE_ENV}.superoffice.com/login/common/oauth/authorize?response_type=code`,
  profileUrl: `https://${process.env.SUPEROFFICE_ENV}.superoffice.com/{DYNAMIC_TENANT_ID}/api/v1/User/currentPrincipal`,
  async profile(profile, tokens) {
    return {
      id: `${profile.DatabaseContextIdentifier}-${profile.AssociateId}`,
      name: profile.FullName,
      email: profile.EMailAddress,
    };
  },
  clientId: process.env.SUPEROFFICE_ID,
  clientSecret: process.env.SUPEROFFICE_SECRET,
}
```

I get the tenant id or profile api url path from the decoded id_token of the access token response:

**"http://schemes.superoffice.net/identity/ctx": "Tenant123",
"http://schemes.superoffice.net/identity/webapi_url": "https://sod.superoffice.com/Tenant123/api/"**

```
{
  "sub": "john.doe@domain.com",
  "http://schemes.superoffice.net/identity/associateid": "123",
  "http://schemes.superoffice.net/identity/identityprovider": "central-superid",
  "http://schemes.superoffice.net/identity/email": "john.doe@domain.com",
  "http://schemes.superoffice.net/identity/upn": "john.doe@domain.com",
  "http://schemes.superoffice.net/identity/is_administrator": "True",
  "http://schemes.superoffice.net/identity/ctx": "Tenant123",
  "http://schemes.superoffice.net/identity/company_name": "John Doe Ltd",
  "http://schemes.superoffice.net/identity/serial": "123456789",
  "http://schemes.superoffice.net/identity/netserver_url": "https://sod.superoffice.com/Tenant123/Remote/Services87/",
  "http://schemes.superoffice.net/identity/webapi_url": "https://sod.superoffice.com/Tenant123/api/",
  "http://schemes.superoffice.net/identity/system_token": "token123",
  "iat": "1615048098",
  "http://schemes.superoffice.net/identity/initials": "JD",
  "http://schemes.superoffice.net/identity/so_primary_email_address": "john.doe@domain.com",
  "nbf": 1615048038,
  "exp": 1615048398,
  "is": "https://sod.superoffice.com",
  "aud": "234oj23o4j23j423oj42i34"
}
```

A callback to return the profileUrl would be great.

**Comment by balazsorban44** [comment]
The `profileUrl` is set before the `profile` callback is invoked, so you cannot set it in reverse.

What you could do is to set `idToken: true`, then you can bypass the call to the `profileUrl` endpoint, and pass the decoded `idToken` to the `profile` callback. https://next-auth.js.org/configuration/providers#oauth-provider-options

**Comment by unsphere** [comment]
> The `profileUrl` is set before the `profile` callback is invoked, so you cannot set it in reverse.
> 
> However you can set `idToken: true`, then you bypass the call to the `profileUrl` endpoint, and use the decoded `id_token` instead in the `profile` callback. https://next-auth.js.org/configuration/providers#oauth-provider-options.
> 
> You could then also invoke another call to the `profileUrl` endpoint from inside the `profile` callback, if you need additional data from another endpoint. Notice that the `profile` callback has a second parameter called `tokens` that will have your raw `access_token` an `id_token`, hopefully enough to request more user data if needed.

Thank you very much. I did it exactly as you suggested and it works. Didn't know that the profile call will be bypassed when you set idToken to true.

**Comment by balazsorban44** [comment]
It is because `OIDC` compliant clients can send the user data encoded in the `id_token`. In that case, we don't have to make an additional request to the user endpoint.
