### ISSUE TITLE
Always redirected to /auth/signin after updating to 3.8.0

### ISSUE THREAD

**Issue by ValentinH** [nextauthjs/next-auth#1467]
**Describe the bug**
I noticed an issue after upgrading to today's latest and after trying each version between 3.1.0 and 3.11.0, I managed to determine that the issue mentioned below started with 3.8.0. Even though the release notes only mentioned adding the Instagram provider, I noticed that there was also quite a large refactoring of the client code in #1428. I think the issue comes from this commit.

The issue I have is that if I go to a page different than `/auth/signin`, I'm always redirected to `/auth/signin` even though I'm already logged-in. Then, once the signin page opens, I'm redirected back to the original requested page as I'm already logged-in.

Then, when I land on the original page, something extremely slow is going on and I can see my chrome devtools using more than 100% of CPU. I have the same behaviour on Firefox though. (This slowness is only on 3.8.0 and not on the latest though, probably fixed by https://github.com/nextauthjs/next-auth/pull/1462).

**Steps to reproduce**
My application is quite large so I'm still in the process of trying to find why I get redirected on load.
 
**Expected behavior**
When I am logged-in and refresh a page, I should not be redirected to the signin page.

**Screenshots**
I cannot tell if this happens before or after the redirection but I actually have an error in the console:
![image](https://user-images.githubusercontent.com/2678610/110245212-88963500-7f62-11eb-9e00-1f8d0b52bca5.png)

It might be because the  `/session` call is cancelled: 
![image](https://user-images.githubusercontent.com/2678610/110245245-a4014000-7f62-11eb-91f9-20b8a3abf72d.png)

**Comment by ValentinH** [comment]
I actually found why I'm redirected to the signin page: this is coming from a part of my code that calls  `signIn()` in a `useEffect()` of a page if the `session` returned by `useSession()` is `undefined` and the  `isLoading` is false.

I commented the call to `signIn`  and instead added a log for the session state and the place where I would redirect:
![image](https://user-images.githubusercontent.com/2678610/110245493-a748fb80-7f63-11eb-82e6-7b8e386f35b3.png)

As you can see, the third log is wrong as the session is `undefined` while it is defined on the next session log.

**Comment by balazsorban44** [comment]
Thanks for taking the time to hunt this down, and actually creating a PR for it! Yes, refactorings shouldn't be visible to users, that is why it wasn't mentioned in the release notes. Of course, if something breaks because of them, it might be harder to find the issue 😬. Glad that you did anyway! Unfortunately, we still don't have a robust test system in place to avoid problems like this, but it is being worked on.

**Comment by ValentinH** [comment]
Thank you for taking over this awesome package 🙂

**Comment by balazsorban44** [comment]
Haven't taken over, I still have Iain involved in important decisions and he gives me infinite good advice from the background as he hasn't had a lot of free time on his hand in the recent past. Not to mention that the core logic is solely his work, I just happen to maintain it right now. But I'm glad that you like me working on this! 😊

**Comment by ValentinH** [comment]
Yes I definitely don't forget the job done by Iain. Open-source requires both time and motivation and the best is to have multiple people involved. That's why I'm happy to see you jumping in as Iain might have less time for this project 🙂
