### ISSUE TITLE
Next-auth and Wordpress Headless is possible?

### ISSUE THREAD

**Issue by marcoriesco** [nextauthjs/next-auth#1471]
**Your question**
Next-auth and Wordpress Headless is possible?

**What are you trying to do**
There is a way to make next-auth work in conjunction with Wordpress.

I did a test removing the prefixes from the Wordpress tables, but without success Wordpress depends on the prefixes.

There goes my doubt, is there any way to change the columns that auth-next uses? for example Users change to wp_user, just an example.

I am thinking of creating an adapter, but it was not very clear to me, if it is possible to change the tables that are necessary for the next-auth.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Please use the provided issue template for questions!

**Comment by marcoriesco** [comment]
@balazsorban44 ready!

**Comment by balazsorban44** [comment]
so my adapters knowledge is limited, but would this help: https://next-auth.js.org/tutorials/typeorm-custom-models

if not, maybe another maintainer (maybe @ndom91?) could help out to answer this?

**Comment by ndom91** [comment]
So you want to use the preexisting wordpress user db as the backend for next-auth?

If you feel comfortable rewriting a lot of the user management code (i.e. methods for adding users, looking up users, creating sessions, etc.) then you could write our own [adapter](https://next-auth.js.org/tutorials/creating-a-database-adapter) (this of wordpress as its own kind of "db" in this case). I'm not sure if wordpress has APIs for this or if you'd have to write sql to query against its db. I'm sure wordpress doesn't like others messing around in its user db though..

Another (much more sane) option is to use wordpress as a provider of some sort. Again like I said i'm not sure what it provides in terms of user mgmt / auth APIs out of the box, but a quick google search turned up this OAuth Server plugin for wordpress: https://wordpress.org/plugins/oauth2-provider/

Then you'd just need to write a quick provider. See [here] for the code for our existing examples (Github, Google, Facebook, etc.). This part isn't very hard.

Good luck!

**Comment by marcoriesco** [comment]
> So you want to use the preexisting wordpress user db as the backend for next-auth?
> 
> If you feel comfortable rewriting a lot of the user management code (i.e. methods for adding users, looking up users, creating sessions, etc.) then you could write our own [adapter](https://next-auth.js.org/tutorials/creating-a-database-adapter) (think of wordpress as its own kind of "db" in this case). I'm not sure if wordpress has APIs for this or if you'd have to write sql to query against its db. I'm sure wordpress doesn't like others messing around in its user db though..
> 
> Another (much more sane) option is to use wordpress as a provider of some sort. Again like I said i'm not sure what it provides in terms of user mgmt / auth APIs out of the box, but a quick google search turned up this OAuth Server plugin for wordpress: https://wordpress.org/plugins/oauth2-provider/
> 
> **EDIT**: Not sure if that version is paid only or not, but heres another provider I found which definitely has a free version: https://wordpress.org/plugins/miniorange-login-with-eve-online-google-facebook/
> 
> Then you'd just need to write a quick provider. We have a section on ["Using your own OAuth provider"](https://next-auth.js.org/configuration/providers#using-a-custom-provider) in the docs!
> 
> Good luck!

You are sure, I have been testing and studying a little, it is very unviable, but it would be very good to have an adapter for Wordpress Headless. Anyway, I have no luggage for that.

If you want to close the discussion, that's fine.
