### ISSUE TITLE
Override URL /api/auth/session when use JWT for session - improve performance.

### ISSUE THREAD

**Issue by meotimdihia** [nextauthjs/next-auth#1478]
## Summary of proposed feature
Override URL `/api/auth/session` when use JWT for session. For example:  
My website: https://example.com is deployed on Vercel.
And I want to verify JWT session on URL: https://a.example.com/api/auth/session - use Cloudflare Worker

## Purpose of proposed feature
This may be saved for users 200-400ms using Cloudflare Worker to verifying JWT - if their location is too far deployed server.

Related with: 
**API is slow when deploying to Vercel**
https://github.com/nextauthjs/next-auth/discussions/1432
https://github.com/vercel/next.js/discussions/22753

**Use Cloudflare for Next-auth**
https://github.com/nextauthjs/next-auth/issues/725#issuecomment-701825393 
As @iaincollins said, I want to use Cloudflare workers to read and validate a JWT. Currently, I used Cloudflare Workers for 2 APIs in my websites.

## Detail about proposed feature
I checked this problem was implemented on auth0: https://github.com/auth0/nextjs-auth0/blob/c485044/src/frontend/use-user.tsx#L136

## Potential problems
No.

## Describe any alternatives you've considered
No.

## Additional context
No.

## Please indicate if you are willing and able to help implement the proposed feature.
I am using `next-auth` in my prod website.

**Comment by balazsorban44** [comment]
Hi there, I was curious, is the performance hit occurring when you try to sue `getSession` inside `getServerSideProps`?

**Comment by meotimdihia** [comment]
Hi, I don't test pages that used `getServerSideProps` yet because `getServerSideProps` is slow and it always requests to deployed the server first. But I don't think `getSession` affects performance when the request directs to the server in this case.

**Comment by balazsorban44** [comment]
I think this is out of scope for now. We may revisit this in the future.
