### ISSUE TITLE
Session is always null when app is in iframe

### ISSUE THREAD

**Issue by unsphere** [nextauthjs/next-auth#1497]
**Describe the bug**
According to the discussion [here](https://github.com/nextauthjs/next-auth/discussions/902) you are unable to login when the app is inside an iframe. I also tried to use a window.open approach and found out that the session is always null then. 

**Steps to reproduce**

1. Create a page with an iframe. ([Example](https://codepen.io/unsphere/full/eYBbWwO))

`<iframe src="https://next-auth-example.now.sh/" width="100%" height="550"></iframe>`

2. Click on "Sign in" and try to login with one of the providers.
3. Notice that nothing happens.

**or new window approach with HOC:**

Auth is working here, but it causes an infinite loop, because the session is always null after window.opener.location.reload();

```javascript
pages/index.js

import withAuth from '../hocs/withAuth';

function Index() {
  return <div>Protected page</div>;
}

export default withAuth(Index);
```

```javascript
hocs/withAuth.js

import React from 'react';
import { getSession, signIn } from 'next-auth/client';

const withAuth = (WrappedComponent) => {
  return class extends React.Component {
    static async getInitialProps(context) {
      const session = await getSession(context);

      const componentProps =
        WrappedComponent.getInitialProps &&
        (await WrappedComponent.getInitialProps(context));

      return {
        session,
        ...componentProps,
      };
    }

    render() {
      if (typeof window === 'undefined') {
        return null;
      }

      if (!this.props.session) {
        if (window.top === window.self) {
          signIn('google');
          return null;
        } else {
          window.open('/login', 'provider_login', 'width=500,height=500');
          return <div>Please login inside the popup window...</div>;
        }
      }

      return <WrappedComponent {...this.props} />;
    }
  };
};

export default withAuth;
```

```javascript
pages/login.js

import { useEffect } from 'react';
import { signIn, useSession } from 'next-auth/client';

const Login = () => {
  const [session, loading] = useSession();

  useEffect(() => {
    if (loading || typeof window === 'undefined') return null;
    if (!session) return signIn('google');
    if (window.opener) {
      window.opener.location.reload();
      window.close();
    }
  }, [session, loading]);

  return null;
};

export default Login;
```

**Expected behavior**
Auth should be initiated and the session shouldn't be null at all when app is in iframe.

**Additional context**
The use case here is that I want to create an app for the given provider which will be displayed in an iframe. Shopify apps for example are also embedded in an iframe.

**Feedback**

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by unsphere** [comment]
Solved it by using the following cookie options:

```
    cookies: {
      sessionToken: {
        name: `next-auth.session-token`,
        options: {
          path: '/',
          httpOnly: true,
          sameSite: 'none',
          secure: true,
        },
      },
      callbackUrl: {
        name: `next-auth.callback-url`,
        options: {
          path: '/',
          sameSite: 'none',
          secure: true,
        },
      },
      csrfToken: {
        name: `next-auth.csrf-token`,
        options: {
          path: '/',
          httpOnly: true,
          sameSite: 'none',
          secure: true,
        },
      },
    },
```

**Comment by balazsorban44** [comment]
I am no expert on the matter, but I have a feeling that setting `sameSite: 'none'` on the `next-auth.session-token` might be dangerous, as other sites will have access to your session information. at the very least, I think you have to make sure that the JWT is encrypted. @iaincollins might explain it better than I can though

**Comment by unsphere** [comment]
Thank you for the reminder. Of course, I encrypt it:

```
    jwt: {
      encryption: true,
      secret: process.env.JWT_SECRET,
      signingKey: process.env.JWT_SIGNING_KEY,
      encryptionKey: process.env.JWT_ENCRYPTION_KEY,
    },
```

And on my API route I get the token:

```
  const token = await getToken({
    req,
    encryption: true,
    secret: process.env.JWT_SECRET,
    signingKey: process.env.JWT_SIGNING_KEY,
    encryptionKey: process.env.JWT_ENCRYPTION_KEY,
  });
```

**Comment by unsphere** [comment]
Added fully working example: #1585

**Comment by Chucheen** [comment]
For me the names on the snippet above, didn't work. So in the NextAuth properties I had to add a prefix to the names so that they are equal to the previously existing cookies. Otherwise after signing in, i was receiving a 307 temporary redirect from Next. If someone can explain why, that would be awesome. My fix looks like this

```
cookies: {
    sessionToken: {
      name: `__Secure-next-auth.session-token`,
      options: {
        path: '/',
        httpOnly: true,
        sameSite: 'none',
        secure: true,
      },
    },
    callbackUrl: {
      name: `__Secure-next-auth.callback-url`,
      options: {
        path: '/',
        sameSite: 'none',
        secure: true,
      },
    },
    csrfToken: {
      name: `__Host-next-auth.csrf-token`,
      options: {
        path: '/',
        httpOnly: true,
        sameSite: 'none',
        secure: true,
      },
    },
```

Hope this is helpful for anyone else
