### ISSUE TITLE
Pass my SignIn options to sendVerificationRequest

### ISSUE THREAD

**Issue by skilesare** [nextauthjs/next-auth#1501]
**Summary of proposed feature**
Currently I get a set number of fields in the opts argument of sendVerificationRequest.  It looks like this:

     {identifier: 'test@test.com',
      url: 'http://localhost:3000/api/auth/callback/email?email=test%40test.com&token=fa027dc15ea41575c5c456489b833448d3bcdf797e8474d10cd3c50fb84bea86',
      token: 'fa027dc15ea41575c5c456489b833448d3bcdf797e8474d10cd3c50fb84bea86',
      baseUrl: 'http://localhost:3000',
      provider: {
        id: 'email',
        type: 'email',
        name: 'Email',
        server: 'smtp://127.0.0.1:1025',
        from: '<noreply@example.com>',
        maxAge: 86400,
        sendVerificationRequest: [Function: sendVerificationRequest],
        signinUrl: 'http://localhost:3000/api/auth/signin/email',
        callbackUrl: 'http://localhost:3000/api/auth/callback/email'
      }

I want to get other variables that I've passed in in these options as well.  I call using:

    signIn ('email',{
        email: result.data.data.invitation.email,
        redirect: false,
        callbackUrl: 'http://' + window.location.host + "/api/publishInvite?phrase=" + result.data.data.invitation.phrase,
        testVar: 'yo'});

I want to get callbackUrl and testVar in these options as well.

**Purpose of proposed feature**
I want to vary the text of my email based on what is in these variables.  Currently I can't marshal anything into these options except by cloning the email provider.

**Detail about proposed feature**
Add a query: {} object to the options

**Potential problems**
None

**Describe any alternatives you've considered**
Clone the email provider for each template I want(yuck)
Pass the request in as a var.  This is currently a get request and these options are added onto the query string

My time is a bit cramped at the moment, but if I get some time I may take a stab at it.

**Comment by ahallora** [comment]
To others looking for answers to this; `callbackUrl` is supported now, so you could consider adding your `testVar` to the callbackUrl as a querystring parameter. 

```javascript
signIn ('email', {
    email: emailFromState,
    callbackUrl: `${yourCallbackUrl}?testVar=yo`,
    redirect: false
});
```

**Comment by nvegater** [comment]
> To others looking for answers to this; `callbackUrl` is supported now, so you could consider adding your `testVar` to the callbackUrl as a querystring parameter.
> 
> ```js
> signIn ('email', {
>     email: emailFromState,
>     callbackUrl: `${yourCallbackUrl}?testVar=yo`,
>     redirect: false
> });
> ```

And how would we access `testVar` inside of the `sendVerificationRequest()` ?
