### ISSUE TITLE
Can't access to publicRuntimeConfig after client side rendering

### ISSUE THREAD

**Issue by lavcraft** [nextauthjs/next-auth#1505]
**Describe the bug**
After upgrade to next 10.0.8 (10.0.9.canary.6 now) i have some problems with env properties

I'm using `getConfig` and `next.config.js` for access to some env based variables.
After navigate via next Link (client side rendering) this properties have default value (instead of value from env)

**Steps to reproduce**
My next.config.js
```javascript
module.exports = {
    publicRuntimeConfig: {
        backendEndpoint: process.env.NEXT_PUBLIC_BACKEND_ENDPOINT ?? 'http://localhost:8080',
    }
}
```
My fetch function
```javascript
const {publicRuntimeConfig} = getConfig();
const backendUrl =  `${publicRuntimeConfig.backendUrl}/api/someurl}`;

export function ini(): Promise<any> {
    return fetch(`${API_ENDPOINT}`);
}
```

first page index.js:
```javascript
export const IndexPage: React.FunctionComponent<Props> = ({}) => {

    return (
                <div>
                    <Link href='/creator'>
                               <div>Next</div>
                    </Link>
                </div>
    );
};
export default IndexPage;
```
second page creator.js:
```javascript
export const CreatorPage: React.FunctionComponent<Props> = ({}) => {

    return (
                <div onClick() => { init() }>Click Me</div>
    );
};
export default CreatorPage;
```

1. open index page
2. Click Next
3. Click "Click Me"
4. Function init start fetching from 'http://localhost:8080' - not from process.env.NEXT_PUBLIC_BACKEND_ENDPOINT 
5. Reload page and click "Click Me" again
6. Function init start fetching from not from process.env.NEXT_PUBLIC_BACKEND_ENDPOINT  !!!
**Expected behavior**
Always fetch from process.env.NEXT_PUBLIC_BACKEND_ENDPOINT

**Additional context**
It may related to https://github.com/vercel/next.js/issues/22938

**Comment by iaincollins** [comment]
Hi there,

For NextAuth.js you will need to configure `NEXTAUTH_URL` appropriately:
https://next-auth.js.org/configuration/options

Notes:

* `NEXTAUTH_URL` defaults to `http://localhost:3000` if not specified (with a base path value of `/api/auth`).
* `NEXTAUTH_URL`  MUST be set in a `.env` file (including something like `.env.local`) or in the run time environment.
* Setting `NEXTAUTH_URL` in `next.config.js` won't work.
* You can specify a custom basepath path as well as a hostname
   e.g. `NEXTAUTH_URL=https://example.com/custom-route/api/auth`

**Comment by lavcraft** [comment]
@iaincollins sorry. This issue in nextjs project. Not in next-auth, it's my fault :(
