### ISSUE TITLE
accessTokenExpires in "account" is always "null" despite the response

### ISSUE THREAD

**Issue by St-Permiakov** [nextauthjs/next-auth#1529]
**Your question**
Why `accessTokenExpires` may be always `null`?
Even when there's a clearly stated `expires_in` in response and `exp` in token?

**What are you trying to do**
I'm using custom oAuth provider.

On token request I get response like this:
```
{
    "access_token": <id_token_here>,
    "refresh_token": <refresh_token_here>,
    "id_token": <id_token_here>,
    "token_type": "Bearer",
    "expires_in": 7199
}
```

But in jwt-callback in `account` parameter I always get this:
```
{
    provider: <provider>,
    type: 'oauth',
    id: <id>,
    refreshToken: <refresh_token>,
    accessToken: <access_token>,
    accessTokenExpires: null
 }
```

Question is: why?

Sadly I can't provide a repo for reproduction due to privacy policy.
Nevertheless, count on your support!

My nextauth config:
```
{
  providers: [
    {
      id: <provider_id>,
      name: <provider_name>,
      type: 'oauth',
      version: '2.0',
      scope: 'profile openid email',
      params: { grant_type: 'authorization_code' },
      accessTokenUrl: getAccessTokenUrl,
      requestTokenUrl: getAccessTokenUrl,
      authorizationUrl: `${getAccessCodeUrl}?response_type=code`,
      profileUrl: getProfileUtl,
      profile: async (profile) => {
        return {
          id: profile.uid,
          role: profile.role,
          name: profile.displayName,
          email: profile.mail
        };
      },
      clientId: CLIENT_ID,
      clientSecret: CLIENT_SECRET
    }
  ],
  pages: {
    signIn: '/auth'
  },
  events: {},
  callbacks: {
    session: async (_session, token) => {
      return { ...token };
    },
    jwt: async (token, user, account, profile) => {
      if (account && user) {
        return {
          accessToken: account.accessToken,
          accessTokenExpires: Date.now() + account.expires_in * 1000,
          refreshToken: account.refreshToken
        };
      }

      if (Date.now() < token.accessTokenExpires || !token.accessTokenExpires) return token;

      return refreshAccessToken(token);
    }
  }
};
```

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
accessTokenExpires is set to null for historical reason. Just use `account.expires_in`

**Comment by St-Permiakov** [comment]
That's definetely not the case.
There is no `expires_in` in account.
In my example above I stated the whole `account` object I get.
Only 6 keys: `provider`, `type`, `id`, `refreshToken`, `accessToken` and `accessTokenExpires`

**Comment by balazsorban44** [comment]
Try upgrading to the latest version.

**Comment by St-Permiakov** [comment]
Yes, that did the trick.
Sorry for bothering.
Thank you!

**Comment by balazsorban44** [comment]
No problem! Happy that it worked out 🙂
