### ISSUE TITLE
Signout only works after some time has passed

### ISSUE THREAD

**Issue by mikeyim337** [nextauthjs/next-auth#1538]
**Your question**

I'm having a hard time getting signout to work.

Signin and signout work in development and this bug happens only in production. When I give my app some time to idle and then try to sign out then it SOMETIMES works.

The error message I get is: 
  [next-auth][error][client_fetch_error] 
  https://next-auth.js.org/errors#client_fetch_error    csrf TypeError: Failed to fetch
and also:
  Uncaught (in promise) TypeError: Failed to fetch

The network console shows signout request as pending and its form data's csrfToken as undefined

Just in case this is relevant, I am using a custom login page and I find that even when I'm signing in with facebook the request gets the EmailSignin error. But facebook oauth still goes through and also this sign out issue occurs when I have signed in with email too, so I'm not sure. 

Thank you very much and any help would be greatly appreciated. 

**What are you trying to do**

I am trying to get signout to work.

**Reproduction**

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by mikeyim337** [comment]
On vercel's  real-time function log I get this error every time I try to sign out. 

20:23:47:56
[POST] /api/auth/_log
20:23:45:47
Loaded env from .env.production
2021-03-20T03:23:55.522Z 48524c55-80a0-4453-aa8c-05e7ef9b9641 Task timed out after 10.01 seconds

**Comment by balazsorban44** [comment]
@mikeyim337 I think I found the problem, thanks to your additional log information from Vercel! Thank you!

**Comment by mikeyim337** [comment]
> @mikeyim337 I think I found the problem, thanks to your additional log information from Vercel! Thank you!

Thank you for the reply. 

This fix did clear up all the errors from vercel's logger, but I still get the client_fetch_error and csrf token as undefined in my signout request, so I'm still unable to sign out. 

In the network tab I find that my csrf request keeps getting canceled and returns 304 instead of 200 OK. 

my nextauth url is NEXTAUTH_URL=https://mydomain.org/   in .env.production.

Thanks for the help.

**Comment by mikeyim337** [comment]
So a couple of things. With the logger fixed, now it consistently returns 304 instead of the signout method sometimes working.

I think there's something wrong with the clientside signout method. When I navigate to mydomain.org/api/auth/signout and click the sign out button from there then sign out works. 

Hope these help with fixing the bug.

**Comment by mikeyim337** [comment]
Figured it out. I put the onclick signout method on a live link so it was redirecting before it could sign out. Oops!

**Comment by balazsorban44** [comment]
Awesome, thanks for reporting back!
