### ISSUE TITLE
JWKS endpoint

### ISSUE THREAD

**Issue by Shadowfaxenator** [nextauthjs/next-auth#1543]
**Summary of proposed feature**
Good to have JWKS endpoint with auto-generated keys (it possible with rotation)

**Purpose of proposed feature**
This will allow remote APIs to verify next-auth's JWT tokens

**Comment by balazsorban44** [comment]
Please follow the issue template!

**Comment by ahmedelq** [comment]
Any update on this? I need this too. I'm using Next.js's API routes in a raspberry project. 

Is there, currently, anyway to secure the API with a key? Is there an ad-hoc to do it? Thanks.

**Comment by micheljung** [comment]
I created #3150
