### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by sualko** [nextauthjs/next-auth#1554]
**Describe the bug**
Email addresses are not validated. 

At least with the email provider, every string is forwarded to `sendVerificationRequest` which results in a few issues:

- you get errors from nodemailer that no recipient is defined. It's annoying, but otherwise no issue.
- people can use `foo@mail;bar` or `foo+bar@mail` to create an infinit amount of accounts for the email `foo@mail`. I think usually you only want to have one account per e-mail address.

**Steps to reproduce**
Use email provider and send a mail with `foo@mail;bar@mail`.

**Expected behavior**
Sign in should be rejected.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Possible solutions**
I can reject invalid addresses in `sendVerificationRequest`, but mail addresses with `+suffix` are generally valid, so there should be a user created without the suffix. Therefore I would prefer that this application is handling that on a global level.

EDIT: even if the +suffix part is annoying according to rfc6854 it's a valid character and it's only used by some servers for special purpose. Therefore this part should be fine, but I still think that next-auth should check if there is `,;` characters (or at least mention that this should be checked).

**Comment by balazsorban44** [comment]
So you propose that we validate emails. I guess that's a valid point, but email validation is notoriously hard to get right. Do you have any suggestions?

For context, here is the source code where this could/should be addressed:

https://github.com/nextauthjs/next-auth/blob/bcb9383aecaee490ba0c4979f3d0f5b0457924a3/src/server/routes/signin.js#L47

What you could do maybe is before NextAuth is invoked in your API handler you could validate req.body.email first and if it's not valid according to your standards, you could reject the signin process early on.

Would thay be sufficient or you do want to see a built-in method? If so, do you have a proposal?

**Comment by sualko** [comment]
> I'm trying to get back to old issues. 

:clap: 

> So you propose that we validate emails. I guess that's a valid point, but email validation is notoriously hard to get right.

You are absolutely right. After writing this issue and searching for a solution, I read a lot of rfc's and this is really tricky.

> Do you have any suggestions?

Currently I check the address in `sendVerificationRequest` and throw an `SEND_VERIFICATION_EMAIL_ERROR` error if it is not valid. It would be maybe nice to have a decent error code for this and to have some documentation about it.

Additionally I would love to see some basic validation which prevents to enter multiple email address (`foo@mail;bar@mail`) like mentioned above.

**Comment by Izhaki** [comment]
I really don't think this library should write or maintain code that validates emails. This is for other libraries to do like:

https://www.npmjs.com/package/deep-email-validator
https://www.npmjs.com/package/validator

As you said, this can be done in `sendVerificationRequest`, but that would be the safety net. You should probably really do this in the UI as well.
