### ISSUE TITLE
Providers.AzureADB2C not implemented with typescript

### ISSUE THREAD

**Issue by ViniciusAugusto** [nextauthjs/next-auth#1556]
**Describe the bug**
Providers.AzureADB2C not implemented with typescript 

"@types/next-auth": "^3.7.1",

**Screenshots or error logs**
![image](https://user-images.githubusercontent.com/3280420/111835890-524aa500-88d4-11eb-958c-ee9fbebefc1d.png)

**Additional context**

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth#typescript
