### ISSUE TITLE
error with typescript when implementing callback session

### ISSUE THREAD

**Issue by Eriickson** [nextauthjs/next-auth#1572]
I am trying to use the session callback, but typescript shows me this error, to be safe I copied and pasted the same code from the documentation, as you can see in the image, but still the problem was not solved. Thanks

![image](https://user-images.githubusercontent.com/38663299/112398191-ffa92880-8cd9-11eb-9588-572da625049b.png)

**Comment by mhdalmajid** [comment]
I got same error,
I have been one day try to figure out why I have errors in CallbacksOptions!
dose next-auth support typescript?


I'm using [@types/next-auth](https://www.npmjs.com/package/@types/next-auth)

**Comment by mhdalmajid** [comment]
I found out but `not sure`  the only solution for now is to uninstall @types/next-auth and just declare  next-auth in index.d.ts 
```typescript 
declare module 'next-auth'
declare module 'next-auth/providers'
declare module 'next-auth/client'
declare module XXX
```

**Comment by StefanSelfTaught** [comment]
https://github.com/nextauthjs/next-auth#typescript

Try this:
```ts
import type { Callbacks } from 'next-auth'

const callbacks: Callbacks = {
   async session(session, token) {}
   ...
}

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth#typescript

**Comment by mhdalmajid** [comment]
> @mhdalmajid the real solution is to provide a PR with a fix to DefinitelyTyped 🙂
> 
> https://github.com/nextauthjs/next-auth#typescript

You right @balazsorban44 
I just newbie typescripter

**Comment by balazsorban44** [comment]
Me too! One of the reasons we rely on our community.

**Comment by eliorivero** [comment]
@Eriickson @mhdalmajid I solved it like this:

1. defined a type:
```js
import { Session } from 'next-auth'
import { WithAdditionalParams } from 'next-auth/_utils'

export type CallbackSession = WithAdditionalParams<Session & { user: { id: number } }>
```

2. used it to type `session` callback:
```
    callbacks: {
        session: async (session: CallbackSession, user: User) => {
            session.user.id = user.id
            return Promise.resolve(session)
        },
```

3. and to type `useSession`:
```
const session = (await getSession({ req })) as CallbackSession
// now session.user.id is a number
```
