### ISSUE TITLE
Custom SignIn does not work in iOS Browsers Only

### ISSUE THREAD

**Issue by mikeyim337** [nextauthjs/next-auth#1581]
**Describe the bug**
A clear and concise description of the bug in NextAuth.js.

Custom Sign-in page just flickers when clicked on provider sign-in or email sign-in.  
This behavior is only found in iOS browsers.

When I comment out the signIn route from the Pages object in [nextauth].js config, the custom sign-in button redirects me to the default next auth js sign-in page, and then the sign in works, so there's something wrong with the custom signin. 

I have tested on PC, macOS, and Android and the custom signIn page works as expected. Its just my iPhone that is causing problems :/ 

Any help would be appreciated. 

Do not report bugs with your own project here, ask from help by raising a question instead - this helps us a lot with administration overhead.

**Steps to reproduce**
Steps to reproduce the behavior.

Include a link to public repository which can be used to reproduce the behaviour.

**Expected behavior**

**Screenshots or error logs**
If applicable add screenshots or error logs to help explain the problem.

**Additional context**

My app is a pwa. I have seen an issue about pwa not working with next-auth on ios,  and although I am facing the same issue when it comes to not being able to resolve Facebook oAuth login, I think this custom signin page issue is separate from that one because it persists even when I had disabled pwa. 

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Please don't skip the template!

Steps to reproduce the behavior.

Include a link to public repository which can be used to reproduce the behaviour.

**Comment by mikeyim337** [comment]
Sorry about that.
I figured out that wrapping the input in a form element will cause this bug. 
Now it works great. 
Thank you very much for your work in next-auth js!

**Comment by balazsorban44** [comment]
Not you actually intrigued my interest! 😧 How wrapping an input in a form element here would be relevant? Could you please show some code anyway? I would appreciate it!

**Comment by mikeyim337** [comment]
Yeah this was pretty crazy. I think it's one of those iOS browser jank. It took me a long while to find that the form element was the problem. I made a public repo to reproduce the behavior, and it kept working bc it was just a bare bone input and a button lol

The first picture is the function log with the form element wrapped(bug). The second is the one without the form element(works). 

![with-form-fails](https://user-images.githubusercontent.com/39456023/112601423-ade2ca00-8dcf-11eb-81a0-ac0de8913bae.PNG)
![without-form-works](https://user-images.githubusercontent.com/39456023/112601440-b2a77e00-8dcf-11eb-80ad-7225bb62ec67.PNG)

When wrapped in a form element it does a get request to sign in with email as the query

And the repo I was using to test: 
https://github.com/mikeyim337/custom-signin-example

**Comment by balazsorban44** [comment]
Right! Isn't this because you should be calling `onSubmit={e => e.preventDefault()}` on the `form` element to, well, prevent the form's default behavior?

**Comment by mikeyim337** [comment]
Yup. Sounds like that’s it. It was wo
