### ISSUE TITLE
Sign in directly to provider seems to fallback to default signin page

### ISSUE THREAD

**Issue by crrmacarse** [nextauthjs/next-auth#1582]
**Describe the bug**
Signin directly to provider doesn't seem to work

Per documentation:

```
If you want to create a custom sign in link you can link to /api/auth/signin/[provider] which will sign in the user in directly with that provider.
```
refer: https://next-auth.js.org/configuration/providers

What I did:

**Steps to reproduce**

Using below:

```
<a href="/api/auth/signin/google">Sign in with Google</a>
```
Will redirect you to the default Login page instead of Google

**Expected behavior**
Should be redirected to Google Login Page

**Screenshots or error logs**
None

**Additional context**
None

**Comment by balazsorban44** [comment]
please try the provided clientside method `signin("provider")`. looks like the documentation was wrong here. it has the behavior you are describing, because signin must be  a post request with CSRF token present in the body. the signin function does most of the work for you.

https://next-auth.js.org/getting-started/client#signin

**Comment by designbyadrian** [comment]
> please try the provided clientside method `signIn("provider")`. looks like the documentation was wrong here. it has the behavior you are describing, because signin must be a post request with CSRF token present in the body. the signin function does most of the work for you.
> 
> https://next-auth.js.org/getting-started/client#signin

This method doesn't work inside getServerSideProps

**Comment by designbyadrian** [comment]
It seems that `/api/auth/signin/[anything]` directs to the same page.

**Comment by balazsorban44** [comment]
It is, and it should. Check https://github.com/nextauthjs/next-auth/issues/1582#issuecomment-943587716

**Comment by arsantiagolopez** [comment]
> I'd like to see an example of this, as I'm sure more users only have one sign-in provider.

I'd love see an example as well. I can't get the /api/auth/signin/[anything] endpoint to work from my custom rest express backend.

**Comment by balazsorban44** [comment]
#2294 might open this up. the core is ready, feel free to experiment. I'm focusing elsewhere for the time being, but here is a version of the `getSession` method working server-side:

https://github.com/nextauthjs/next-auth/blob/ba39efb2566466dfe695bb90513050896d96a2d2/src/next/index.ts#L99-L123

something similar might work for sign-in as well. :shrug:

**Comment by arsantiagolopez** [comment]
Great, thanks @balazsorban44 I think I'll be able to handle the extra logic post signIn with the callback functions.

**Comment by morearie** [comment]
> Great, thanks @balazsorban44 I think I'll be able to handle the extra logic post signIn with the callback functions.

can you share the logic in post signIn?

**Comment by adam-binks** [comment]
Is there a way to do this with middleware?

**Comment by pixelpax** [comment]
I don't think this issue should be closed without opening up a new one.

The underlying issue here is that this extremely common use-case (probably the most common if I had to guess) is not easily implemented from the docs.

An example of just redirecting to the provider page instead of going through this sign-in page is sorely needed.

**Comment by maykon-oliveira** [comment]
> Is there a way to do this with middleware?

I tried something like this, but the request don't returns the google authorization url to client redirect.

```ts
import { getToken } from "next-auth/jwt";
import { getProviders } from "next-auth/react";
import { NextResponse } from "next/server";
import type { NextRequest } from 'next/server';

export default async function middleware(req: NextRequest) {
    const { pathname, search, basePath } = req.nextUrl;

    const token = await getToken({
        req,
        secret: process.env.NEXTAUTH_SECRET
    });

    const csrfToken = req.cookies.get("next-auth.csrf-token");

    if (token || !csrfToken) {
        return NextResponse.next();
    }

    const providers = await getProviders();

    if (!providers || !('google' in providers)) {
        return NextResponse.next();
    }

    const body = new URLSearchParams({
        redirect: "true",
        callbackUrl: `${pathname}${search}`,
        csrfToken: csrfToken.value.includes('|') ? csrfToken.value.split('|')[0] as string : csrfToken.value,
        json: "true"
    });

    const res = await fetch(`${providers.google.signinUrl}?`, {
        method: 'POST',
        body
    });

    const data = await res.json();
    console.log(data);

    return NextResponse.redirect(data?.url || '')
}

export const config = { matcher: ["/app/:path*"] };
```

**Comment by IuliiaBondarieva** [comment]
I struggled with it quite a lot and still could not make `singin` with Rest API work.

**Comment by Writtscher** [comment]
Hi. Is there any progress on this? Why isn't it higher prioritized? At the moment it is awkward to have our users to click on "Sign in with X" even though there is no other authentication provider. I'd like to navigate the user straight to the sign in page of the authentication provider and skip the sign in page.

Whenever the session runs out and the user refreshes the page there is this unnecessary sign in page.

**Comment by alegonzaleza** [comment]
Hi, has anyone solved it yet?
at least a workaround?

**Comment by abhishekkundu25** [comment]
Here’s the setup that works for me:

app/api/auth/[...nextauth]/route.ts
```

import NextAuth from "next-auth";
import AzureADProvider from "next-auth/providers/azure-ad";

export const authOptions = {
  providers: [
    AzureADProvider({
      clientId: process.env.AZURE_AD_CLIENT_ID!,
      clientSecret: process.env.ZURE_AD_CLIENT_SECRET!,
      tenantId: process.env.AZURE_AD_TENANT_ID,
      authorization: {
        params: { scope: "openid profile offline_access" },
      },
    }),
  ],
  secret: process.env.NEXTAUTH_SECRET,
  pages: {
    signIn: "/auth/signin", // must be a real page
  },
};

const handler = NextAuth(authOptions);
export { handler as GET, handler as POST };


```
components/AutoAzureSignIn.tsx

```
"use client";

import { useEffect, useRef } from "react";
import { signIn } from "next-auth/react";

export default function AutoAzureSignIn({ callbackUrl }: { callbackUrl?: string }) {
  const started = useRef(false);

  useEffect(() => {
    if (started.current) return;
    started.current = true;

    signIn("azure-ad", {
      callbackUrl: callbackUrl ?? window.location.href,
    });
  }, [callbackUrl]);

  return null;
}
```


app/auth/signin/page.tsx

```
import AutoAzureSignIn from "@/components/AutoAzureSignIn";

export default function SignInPage({ searchParams }: { searchParams?: { callbackUrl?: string } }) {
  return <AutoAzureSignIn callbackUrl={searchParams?.callbackUrl} />;
}

```

app/test/page.tsx

```
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import AutoAzureSignIn from "@/components/AutoAzureSignIn";

export default async function Page() {
  const session = await getServerSession(authOptions);

  if (!session) {
    return <AutoAzureSignIn callbackUrl="/test" />;
  }

  return <div>Protected server-side page</div>;
}
```


With this setup, you can still sign in directly to your provider (Azure AD in my case), but through a proper page that calls signIn() instead of hitting the API route directly.
