### ISSUE TITLE
What is 'account" in "signIn"  callback?

### ISSUE THREAD

**Issue by typedashutosh** [nextauthjs/next-auth#1597]
**Your question**

Question: What is *account* and where does it come from?
in `@types/next-auth/index.d.ts` , at interface CallbacksOptions, signin function has this type 
```
 signIn?:
        | (() => true)
        | ((user: User, account: Record<string, unknown>, profile: Record<string, unknown>) => Promise<never | string | boolean>);
```

**What are you trying to do**

**Reproduction**

in `@types/next-auth/index.d.ts` , at `interface CallbacksOptions`

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth#typescript
