### ISSUE TITLE
Expanded Logging Customisation

### ISSUE THREAD

**Issue by mod-flux** [nextauthjs/next-auth#1602]
**Summary of proposed feature**
Additional boolean flags in options to be used in conjunction with [logger](https://next-auth.js.org/configuration/options#logger) object that allows for disables the sending of log events to the `_log` endpoint.

**Purpose of proposed feature**
Serverless function invocation costs per request on Vercel. For customers that implement client and server-side exception tracking services (such as Sentry) already pay for these exceptions to be captured on said services. Having the exceptions also invoking the `_log` function is redundant in this scenario and would incur additional, unnecessary costs and double up on alerting.

**Detail about proposed feature**
Offer the ability to set `_log endpoint` or similar to `false` which disables it from being created in Vercel and disables the client and server parts of next-auth from attempting to `POST` data to the endpoint when an exception is caught. Customers are then encouraged to use the pre-existing `logger` object to capture and alert with their own logging platform.

**Potential problems**
None that I can think of.

**Describe any alternatives you've considered**
Attempting to link Sentry to DataDog to capture `_log` events but this seems backward.

**Additional context**
I can obviously try and help with this implementation.

**Comment by balazsorban44** [comment]
Thank you for opening. So adding a boolean to log invocations to be able differentiate between client and server logs are easy, but to set an option to don't send logs from the client at all is a bit harder. There might be an option to set it in the `Provider` as a property in the options prop, but that would probably require some potentially breaking refactoring. I need to think about it.

**Comment by mod-flux** [comment]
Thanks for responding @balazsorban44, would this move to `Provider` also affect custom OAuth clients as well as pre-configured ones? Had a look at the code changes but couldn't determine.

Ideally not sending it at all would be great as redundant serverless invocations wouldn't be necessary. However, even providing some context as to where an error has originated from within the `logger` callbacks would be a good step.

**Comment by balazsorban44** [comment]
It would be nice to have @iaincollins's opinion on #1473 for this to be resolved properly, but adding a simple `frontend: true` boolean to client-side logs shouldn't be hard. Any interest in implementing it? Either in the server/index.js _log case, or in the proxyLogger function in lib/logger

**Comment by balazsorban44** [comment]
There hasn't been much interest in this from the community. Adding a frontend flag is still on the table for me, but since these logs should only be sent when something is not working correctly, I don't think a high number of function invocations would occur.

**Comment by balazsorban44** [comment]
This will be closed by #2344 
It adds a `client: true` flag, when the log event comes from the frontend
