### ISSUE TITLE
Easier Manipulation of Cookie prefixes

### ISSUE THREAD

**Issue by mod-flux** [nextauthjs/next-auth#1603]
**Summary of proposed feature**
An easy ability to modify the cookie prefixes (e.g. `nexauth_`) beyond customising every option of the cookies.

**Purpose of proposed feature**
Having the name of the plugin responsible for critical functionality of the website exposed in plaintext in the cookie name increases the likelehood of a targeted attack on a vulnerability.

**Detail about proposed feature**
It's strongly recommended on next-auth documentation that users should avoid modifying the cookie settings of the plugin unless absolutely necessary due to potential security implications. Whilst this is good advice, the name prefix/suffix of the cookie should be configerable by a simple string in the options.

**Potential problems**
Could conflict with the advanced cookie setup options for those rare occassions this has been done. Perhaps if this is done, it overrides the cookie name parameter.

**Describe any alternatives you've considered**
Managing all of the cookies manually by the options already provided by next-auth

**Additional context**
I can obviously try and help with this implementation. Though, cookies are a bit of a dark art and I worry I may not have the skills necessary to do a good job.

**Comment by balazsorban44** [comment]
Since there hasn't been any comments in this and the current API allows overriding cookie names (with an emphasis on that it is advanced usage), I think it's not something we want to change for now.
