### ISSUE TITLE
Default Pages Toggle

### ISSUE THREAD

**Issue by mod-flux** [nextauthjs/next-auth#1606]
**Summary of proposed feature**
Off the ability to provide the `pages` object in the `options` as a boolean as well as an object of pages. Providing `false` would disable all custom pages and use the homepage for everything.

**Purpose of proposed feature**
Whilst the default pages are useful, there are many situations where clients may just want to disable them outright and providing a boolean flag as opposed to the following feels like a nice little efficiency bonus:

```
pages: {
	signIn: ‘/‘,
	signOut: ‘/‘,
	error: ‘/‘,
	verifyRequest: ‘/'
}
```

**Detail about proposed feature**
See above.

**Potential problems**
None that I can see.

**Describe any alternatives you've considered**
I've currently used the approach of setting all pages to `/`.

**Additional context**
I may be able to help on this one. I've not see the code that does it but I don't feel it should be too tricky so happy to do so.

**Comment by balazsorban44** [comment]
It might be my own opinion only, but I don't see the problem here. I think setting pages explicitly is much less confusing than setting a boolean and magically default to false. Maybe `pages: "/"`? would be a better way?

**Comment by mod-flux** [comment]
Yeah, it's only a shorthand @balazsorban44 but you're probably right, explicit maybe the best option in this case. Just a thought. :-)

Feel free to close!

**Comment by balazsorban44** [comment]
I'll leave it open, and if no one responds to it, it will be closed automatically after 60 days. Let's see if there is interest.

**Comment by balazsorban44** [comment]
Even if it hasn't been full 60 days, I think there is little interest for this, and it would just unnecessarily complicate the core code for very little gain.

**Comment by green-hosking** [comment]
this is not true. i want create popup for login|register in my project, but i can't this, because there is redirect. for me is big problem.
please, fix this, so i cant do it
