### ISSUE TITLE
Steam Provider

### ISSUE THREAD

**Issue by Glutch** [nextauthjs/next-auth#1614]
**Your question**
When searching next-auth issues & discussion for Steam, there is a couple of old threads debating adding steam and openid 2.0 support. And the most recent seems to have maybe added support for it https://github.com/nextauthjs/next-auth/pull/1373
Apprently steam does not use the new "openid connect" but the old "open id 2.0". But since this commit is named steam... i hope it works

My question is: Is it possible now? And could someone guide me through it / show an example?

**What are you trying to do**
next-auth steam

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
See https://github.com/nextauthjs/next-auth/discussions/697
