### ISSUE TITLE
What am I doing wrong? "TypeError: Cannot use 'in' operator to search for 'undefined' in null"

### ISSUE THREAD

**Issue by wuperguy** [nextauthjs/next-auth#1615]
**Your question**
What am I doing wrong? I am getting this error during runtime 
TypeError: Cannot use 'in' operator to search for 'undefined' in null

**What are you trying to do**
Just setup a simple Twitch Oauth Provider

**Reproduction**
Happens every time I run the code.

**Comment by wuperguy** [comment]
Disregard, I was using a different path for my providers and didn't realize it needed to strictly be /api/auth/[...nextauth]

I was using /api/v1/auth/[...nextauth] - edited in src to allow this.

**Comment by MhmdNdri** [comment]
I have this same error, and I am using the exact path that the documentation said.
I'm struggling with this issue for about two days, and I find no way to fix it.

**Comment by balazsorban44** [comment]
@MhmdNdri if you are having a problem, please open an issue with a reproduction.
