### ISSUE TITLE
SignIn using Email Provider server side

### ISSUE THREAD

**Issue by pbteja1998** [nextauthjs/next-auth#1625]
**Your question**
Is it possible to `signin` the user using the email provider, server-side?

**What are you trying to do**
I have a stripe webhook setup, through which I will get the email of the new user. Now, I want to create an account with this email, and also send the verification email (to sign in).

**What methods I have tried**
1. I tried using the `signIn` method – `signIn('email', {redirect: false, email: customer.email})`, but it throws an error saying `window is not defined`.
2. I tried directly sending the `POST` request directly with the `csrfToken` and `email`, but it just returns a HTML text.
```javascript
// This code is being executed server-side in an API route.

const csrfToken = await getCsrfToken({ req })

// and then I am using the above `csrfToken` in the `fetch` request.
fetch(
    'http://localhost:3000/api/auth/signin/email',
    {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ csrfToken, email: customer.email }),
    }
  )
```

**Reproduction**
// Added above

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by pbteja1998** [comment]
Updated to the latest version of `next-auth`. Now I am getting different response, but still no email is being sent.

```javascript
const response = await signIn('email', {
  redirect: false,
  email: customer.email,
  callbackUrl: '',
})
```

The above code is returning the following json.
```js
{
  error: null,
  status: 200,
  ok: true,
  url: 'http://localhost:3000/api/auth/signin?csrf=true'
}
```

**Comment by balazsorban44** [comment]
hmm, the response you are providing suggests that it doesn't accept your csrfToken for some reason. if I had to guess, the page you are visiting for the first time must not be the one that is making this request, because the CSRF cookie hasn't been set yet.

the signIn method not working server-side is expected, as it is meant to be used client-side.
