### ISSUE TITLE
Easier flow for incorporating provider data during sign-in

### ISSUE THREAD

**Issue by zackdotcomputer** [nextauthjs/next-auth#1633]
**Summary of proposed feature**

I would like a callback to add account data from an auth provider to the next-auth User during sign-in.

**Purpose of proposed feature**

To be able to populate and update my users with data from auth providers without having to make a second call for the user's data immediately after sign-in.

**Detail about proposed feature**

I would propose simplifying this either by changing the signature of the methods on the Adapter so that they are all provided with the full information about the authentication or else by adding a "didSignIn" callback at the end of the process which would be provided with the user object, provider details, etc. The latter is no doubt simpler and requires less API changes, but does not fix the issue of needing two database calls to the Users table.

**Potential problems**

- A solution that changes the signature of the Adapter would require a larger Semver change.
- Customizing the adapters is hard
- Doing customization via callback is easiest but requires two database calls (probably ok)

**Describe any alternatives you've considered**

Currently, the provider's account and profile information are provided to the `signIn` callback, but since the `signIn` callback is called before any objects are actually created via the Adapter there is no way to customize the models in memory at that point.

I also looked into customizing the adapters, but the full profile and account information isn't passed to the adapters, only to the provider object itself. So the only way currently to pass data from the provider's profile and account info (e.g. a Twitter handle) is to override both the provider object's `profile` method AND the adapter's `createUser` method. Even then, the user will not be updated every time their remote data changes on the provider.

*Please indicate if you are willing and able to help implement the proposed feature.*

Sure

**Comment by zackdotcomputer** [comment]
I think I might be able to hack what I am looking for into the events system, though I don't feel great about using the logging events to modify the objects in the database...

**Comment by franky47** [comment]
> I think I might be able to hack what I am looking for into the events system, though I don't feel great about using the logging events to modify the objects in the database...

How would you do this ? The event only has the user object fetched from the database, and no link to the OAuth profile data that's available in the `signIn`, `jwt` and initial `session` callbacks.

Asking as I have the same use-case: I'm trying to create a `User` in the database that has the Twitter handle at creation. On another app it's the GitHub username. In both cases I've been able to hack my way in by storing the handle/username as the email address (I don't collect nor need the actual email), but it's very brittle and unsustainable.

There might be something to play with [the `profile` method in the provider](https://github.com/nextauthjs/next-auth/issues/1238#issuecomment-771503990): the adapter could look for keys defined in the object returned by `profile`, and attempt to store those in the database from the input of `createUser`.

**Comment by zackdotcomputer** [comment]
@franky47 Yeah same use case, same issues. I wound up putting a `syncTwitterToUser` method in the `events.signIn` that just does another API call for /users/show from the Twitter API. It's redundant and it leaves me with the user handle and tweet count not being perfectly "guaranteed" but this is a side project so more than one 9 of reliability isn't really necessary for me.

How I would do this if I were to PR it against the codebase would be:

1. Check the flow of User, Token (if using), and Session so that we were always sending in and getting out the same kind of object (i.e. if you use a backing database, make sure you're always getting the DATABASE user/token/session rather than just a synthetic one).
2. Rework the callback methods so that all of them receive the same arguments: `sessionState` with the internal next-auth values of Session/Token (if using)/User and `providerState` with both the account and providerProfile. Right now all the callbacks get sent subsets of these values, but those subsets are determined by what the library originally needed each callback to do and so it doesn't actually allow you to _extend_ the functionality in a meaningful way.

**Comment by balazsorban44** [comment]
#2361 is aiming to resolve issues like this for our next major version. Please comment there if you have suggestions! 🙏
