### ISSUE TITLE
Property 'Prisma' does not exist on type 'Adapters'

### ISSUE THREAD

**Issue by s-kris** [nextauthjs/next-auth#1638]
**Describe the bug**
Trying to use Prisma Adapter in ts project throws error: `Property 'Prisma' does not exist on type 'Adapters'`

**Steps to reproduce**
1. Import Adapters from next-auth/adapters
2.  Try to set Prisma with `adapter: Adapters.Prisma.Adapter({ prisma })`

**Expected behavior**
No type errors

**Screenshots or error logs**
I checked the `adapters.d.ts` only to find no Prisma property in the Adapters interface.
![Screenshot 2021-04-02 at 5 30 05 PM](https://user-images.githubusercontent.com/3975305/113413830-2c93c480-93d9-11eb-9375-d450455d780f.png)

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by zackdotcomputer** [comment]
Are you on the latest version and pulling from `npm` directly? I am on `"next-auth": "3.13.3"` in my package.json and I am seeing the following in that file:

```typescript
interface Adapters {
    Default: TypeORMAdapter['Adapter'];
    TypeORM: TypeORMAdapter;
    Prisma: PrismaAdapter;
}
```

**Comment by s-kris** [comment]
Thank you @zackdotcomputer 

Yes, I'm pulling from npm and I'm on the same version.

![Screenshot 2021-04-02 at 5 41 07 PM](https://user-images.githubusercontent.com/3975305/113414492-b98b4d80-93da-11eb-8450-b38a7634c97e.png)

**Comment by s-kris** [comment]
But crazily, the prisma adapter works fine wuth the auth flow.

**Comment by zackdotcomputer** [comment]
Oh I just realized my types are coming from `"@types/next-auth": "3.13.0",` - are you on the latest version for that as well?

**Comment by zackdotcomputer** [comment]
For completeness sake I also deleted and reinstalled my node_modules folder and it landed correctly. I suppose if we REALLY wanted to be thorough we'd clear that folder and run `npm cache clean --force`...

**Comment by s-kris** [comment]
Thats it. I completely forgot that next-auth's types are from the `DefinitelyTyped` repo.
Sorry about this, it's fixed now. I updated @types/next-auth to latest version.
