### ISSUE TITLE
302 redirects not followed

### ISSUE THREAD

**Issue by jonjrodriguez** [nextauthjs/next-auth#1642]
**Describe the bug**

302 redirects are not followed for the `profileUrl` when authenticating with OAuth 2. The root cause is due to the underlying library used for authentication, [oauth](https://github.com/ciaranj/node-oauth). However, this library is unmaintained and has had an open issue for it for 6+ years: https://github.com/ciaranj/node-oauth/issues/201.

This issue causes `profileData` to be an empty string. Then in [getProfile](https://github.com/nextauthjs/next-auth/blob/073da60c3d6c06cfa0ee0918cba0d65b55faf898/src/server/lib/oauth/callback.js#L97), an error is raised due to `JSON.parse`.

**Steps to reproduce**

I'm creating a custom provider where the `profileUrl` returns a redirect to the actual url. In this instance, `/api/users/current` redirects to `/api/users/{current_user_id}`.

**Expected behavior**

The `Location` header is followed for `302` redirects. Alternatively, the library includes a way for developers to follow the redirects themselves.

**Additional context**

If help is needed, I can open a PR for this. I think the callback to `_request` [here](https://github.com/nextauthjs/next-auth/blob/073da60c3d6c06cfa0ee0918cba0d65b55faf898/src/server/lib/oauth/client.js#L228-L236) can take in the `response` and issue another request if it's a response with a `Location` header and `3xx` status code.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Hi there, would #1846 help here if you got full control on how to fetch the user's profile?

**Comment by jonjrodriguez** [comment]
@balazsorban44 yeah that looks like it would solve my issue.

**Comment by ThangHuuVu** [comment]
See https://github.com/nextauthjs/next-auth/pull/2276#issuecomment-972674917 
Closing because we're no longer using `oauth` as underlying package for `@auth/core`.
