### ISSUE TITLE
What am I doing wrong? "TypeError: Cannot use 'in' operator to search for 'undefined' in null".

### ISSUE THREAD

**Issue by MhmdNdri** [nextauthjs/next-auth#1645]
**Your question**

**What are you trying to do**

**Reproduction**

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by dandrei** [comment]
In your `./api/auth/[...nextauth].js` file, your `providers` option you pass to `NextAuth` is empty.
