### ISSUE TITLE
What am I doing wrong? "TypeError: Cannot use 'in' operator to search for 'undefined' in null", and I am using the exact path that the documentation said.

### ISSUE THREAD

**Issue by MhmdNdri** [nextauthjs/next-auth#1646]
**Your question**
What am I doing wrong? I am getting this error during runtime
TypeError: Cannot use 'in' operator to search for 'undefined' in null.

**What are you trying to do**
Trying to setup authentication for my Project.

**Comment by balazsorban44** [comment]
please add a complete reproduction
