### ISSUE TITLE
Adding Instagram as a provider results to - TypeError: Cannot read property '#<Class>' of null

### ISSUE THREAD

**Issue by LGmatrix13** [nextauthjs/next-auth#1658]
**Describe the bug**
When I add Instagram as a provider with the clientId and clientSecret, I get the following error: `TypeError: Cannot read property '#<Class>' of null`. When I remove Instagram as a provider, it works perfectly.

**Steps to reproduce**
Add Facebook, Google, Github, and Instagram as a provider as showing the documentation: https://next-auth.js.org/getting-started/example#add-api-route

My code is setup as follows:

```
import NextAuth from "next-auth";
import Providers from "next-auth/providers";

const authHandler = (req, res) => NextAuth(req, res, options);
export default authHandler;

const options = {
  providers: [
    Providers.GitHub({
      clientId: 
      clientSecret:
    }),
    Providers.Facebook({
      clientId:
      clientSecret: 
    }),
    Providers.Google({
      clientId: 
      clientSecret:
    }),
    Providers.Instagram({
      clientId: 
      clientSecret:
    })
  ]
};
```

**Expected behavior**
I expected it to show the default sign-in page with all my providers

**Screenshots or error logs**
Screenshot: ![image](https://user-images.githubusercontent.com/19254314/113608334-6ef71480-9618-11eb-80f6-6977b199c3db.png)

 **Documentation**
- [ ] Found the documentation helpful
- [ ]  Found documentation but was incomplete
- [x]  Could not find relevant documentation
- [ ]  Found the example project helpful
- [ ]  Did not find the example project helpful

**Comment by balazsorban44** [comment]
please add a complete reproduction
