### ISSUE TITLE
error=callback when signing in with provider

### ISSUE THREAD

**Issue by tommhuth** [nextauthjs/next-auth#1661]
When signing in with Facebbok, I suddenly get the following `error` via the url param:

`<domain>/login?callbackUrl=<domain>/login?callbackUrl=<domain>/&error=Callback#_=_`

What does that error mean? I cannot find any documentation for it in the docs. Also: is there something strange going on with the callback url seemingly being nested two levels deep?

I'm running my own login screen at `/login`.

**Comment by balazsorban44** [comment]
Please add a complete reproduction!

**Comment by tommhuth** [comment]
Do you need a complete reproduction to tell me what the `Callback` error mean?

**Comment by balazsorban44** [comment]
Yes. There can be several reasons, and from the information you have provided, it is hard to pinpoint what that is.

**Comment by tommhuth** [comment]
Could you possibly give some quick hints as to what those reasons are?

**Comment by balazsorban44** [comment]
Configuration error in your OAuth client at Facebook, configuration in your next-auth/Next.js setup, implementation error in your client for triggering signin. Also knowing the versions of dependencies would help narrow down issues, like if you have the error that has been already patched, a simple update of the package would be enough. It is hard to say without the context though.
