### ISSUE TITLE
Pass additional params to redirect callback

### ISSUE THREAD

**Issue by anonrose** [nextauthjs/next-auth#1671]
**Summary of proposed feature**
currently the only available params in the redirect are urls, it would be great to pass additional params to redirect callback such as session or token so that we can properly handle a redirect say, to any page based on the user logging in[pick up where they left off].

**Purpose of proposed feature**
above.

**Detail about proposed feature**
Pass token to redirect callback

**Potential problems**
not sure, haven't looked through the entire codebase

**Describe any alternatives you've considered**
n/a

**Additional context**
https://github.com/nextauthjs/next-auth/blob/76df2b5e702be2084674c81e098d989c2ec39ed9/src/server/lib/callback-url-handler.js#L19-L24

*Please indicate if you are willing and able to help implement the proposed feature.*
Yes

**Comment by balazsorban44** [comment]
By default, when you sign in, the user will be redirected to the same page they started on. You can easily override this with the `callbackUrl` option on `signIn` https://next-auth.js.org/getting-started/client#specifying-a-callbackurl and it CAN contain any params.
Otherwise, I am not sure I understand you correctly.

**Comment by balazsorban44** [comment]
I'm not sure what you mean still.

> you want to redirect them to the page they were previously on after login

This is the default behaviour already.


> Or say you want to redirect the user to their own profile page after login. You don't know what their profile is when setting the callbackUrl, but once they user has logged in you know.

Can't you just redirect them to something like `/profile`? Or what kind of user specific url structure would you like for logged in user profiles?

**Comment by anonrose** [comment]
If the route you want to redirect to is dynamic `/user/[username]` and you don't know what `username` is until after login, also if the last time the user was logged in they were looking at a particular page and you want to return them to that same page.

**Comment by typedashutosh** [comment]
If, Somehow, we could get `User` from `Authorize` available in `redirect` method of NextAuthOptions, then, I think the desired '/user/[username]' rout could work, as username will be coming from database.
Although, using getSession in initialPageProps should do the trick easily.

**Comment by balazsorban44** [comment]
Unfortunately, I think this is out of scope for now, as a simple client-side redirect should do the trick. We might revisit this in the future.
