### ISSUE TITLE
`v3.14.0` bug: TypeError: [provider.protection].flat is not a function

### ISSUE THREAD

**Issue by liamross** [nextauthjs/next-auth#1675]
**Describe the bug**

`provider.protection` is not a required property, and not providing it breaks the package since `.flat()` is called without first verifying it is an array.

**Steps to reproduce**

Add a custom provider without specifying `protection` property

**Additional context**

Here are all the places this is done:
https://github.com/nextauthjs/next-auth/search?q=%5Bprovider.protection%5D.flat%28%29

**Comment by balazsorban44** [comment]
thanks, I think you are right! A PR is very welcome for this as it should be an easy fix, but if no one volunteers, I'll just do it myself. 🙂

**Comment by liamross** [comment]
I can, but what about this case where provider.protection is assigned a string?

https://github.com/nextauthjs/next-auth/blob/dbe283f0fa5b0521b6a4be1f63bf916891c0d5fe/src/server/index.js#L79

Should that be an array? The documentation is not super clear on what types `provider.protection` is allowed to be.

**Comment by balazsorban44** [comment]
Originally it was supposed to be a string, but later I was told it would be great if it did support different methods of protection, like PKCE AND state for example (there is also nonce, which isn't implemented right now). For that not to be a breaking change, we still support both a string and an array of strings.

**Comment by fxamauri** [comment]
A provisional solution until we wait for the pull request, use node 11 or higher for Array.prototype.flat to be available :stuck_out_tongue_winking_eye:

**Comment by fxamauri** [comment]
see if this can be fixed in this version #1684
