### ISSUE TITLE
What to do when using Zones within NextJs

### ISSUE THREAD

**Issue by divslingerx** [nextauthjs/next-auth#1676]
**Your question**

Is it possible to set the default url for all auth requests?

**What are you trying to do**

I am currently building an app that utlizes zones. [zone example](https://github.com/vercel/next.js/tree/canary/examples/with-zones).
The site is split into a "site" and an "admin" zone.
the site zone runs on port 3000 and the admin zone runs on port 4000

going to localhost:3000/admin will redirect to the admin app running at localhost:4000 behind the scenes

Nextauth api route is located in /admin/pages/api/auth/[...nextauth]

When trying to use the hooks all request are made to localhost:3000/api/auth when I believe it should be localhost:3000/admin/api/auth
using the `NEXTAUTH_URL=http://localhost:3000/admin/api/auth` environent variable does not seem to work as I expected.

logic would say that moving NextAuth into the "site" zone would solve the problem however there is no auth needed for aspect of the site app so i would prefer to keep it in the admin app if possible.

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Could you see if https://github.com/nextauthjs/next-auth/issues/689#issuecomment-699927237 helps?
