### ISSUE TITLE
Option to bypass auth screen with one provider

### ISSUE THREAD

**Issue by halfmatthalfcat** [nextauthjs/next-auth#1688]
**Summary of proposed feature**
Option to bypass auth screen with one provider

**Purpose of proposed feature**
I'm currently using the Twitter auth provider and only that provider. The auth flow is quite simple where the user just has to simply click through the unbranded next-auth page to get to the Twitter login. I want to be able to bypass this click-through and get to the Twitter login page in one click.

**Detail about proposed feature**
A flag on the NextAuth route controller that allows a passthrough of the auth screen, or potentially there's a flag on the Provider(s) that, if flagged for bypass, will automatically passthrough the auth screen.

**Potential problems**
If there's more than one Provider specified that doesn't allow bypass but then you'd just default to showing the (un)branded auth page.

**Describe any alternatives you've considered**
Creating a custom auth page that automatically redirects to the auth route.

**Comment by balazsorban44** [comment]
Use `signIn("twitter")`

https://next-auth.js.org/getting-started/client#starts-google-oauth-sign-in-flow-when-clicked
