### ISSUE TITLE
using a base path does not work

### ISSUE THREAD

**Issue by martinratinaud** [nextauthjs/next-auth#1712]
**Describe the bug**
whenever I use a custom NEXTAUTH_URL along with a nextjs custom basePath, it leads to this error in the client

**Steps to reproduce**

```
git clone git@github.com:nextauthjs/next-auth.git
cd next-auth
npm i 
cp .env.local.example .env.local
```
change NEXTAUTH_URL in `.env.local` to `NEXTAUTH_URL=http://localhost:3000/preprod/api/auth`

Then go to `pages/api/auth/[...nextauth].js` and comment out all providers except Credentials to keep it simple

and add a `next.config.js` file

```
module.exports = {
  basePath: '/preprod',
};
```

And finally launch `npm run dev`

**Expected behavior**
The website loads correctly on http://localhost:3000/preprod and when I click on "Sign In", I should arrive on the signing page

**Screenshots or error logs**
Instead, clicking on the "Sign In" button leads to this

```
TypeError: right-hand side of 'in' should be an object, got null

src/client/index.js (205:8) @ _callee7$

  203 | 
  204 |   // Redirect to sign in page if no valid provider specified
> 205 |   if (!(provider in providers)) {
      |        ^
  206 |     // If Provider not recognized, redirect to sign in page
  207 |     window.location = `${baseUrl}/signin?callbackUrl=${encodeURIComponent(callbackUrl)}`
  208 |     return

```
This comes from the signIn method and it seems `providers` are null

Thanks for your help

**Comment by balazsorban44** [comment]
Could you try this: https://github.com/nextauthjs/next-auth/issues/689#issuecomment-699927237

**Comment by balazsorban44** [comment]
Closing in favor of #1713. Feel free to comment there!
