### ISSUE TITLE
[useSession] getSession called every time visibilitychange fires

### ISSUE THREAD

**Issue by jmuffat** [nextauthjs/next-auth#1714]
**Describe the bug**
When I switch tab to/from a page using useSession(), a call to getSession is made and a request is made to the /api/auth/session endpoint. 

**Steps to reproduce**
standard _app.js:
```js
import { Provider } from 'next-auth/client'
import '~/styles/globals.scss'

function MyApp({ Component, pageProps }) {
  return (
    <Provider session={pageProps.session}>
      <Component {...pageProps} />
    </Provider>
  )
}

export default MyApp
```
add a test page :
```js
import React from 'react'
import { useSession } from 'next-auth/client'

function Page() {
    const [session] = useSession()
    return (
        <code>
            <pre>
                {JSON.stringify(session,null,2)}
            </pre>
        </code>
    )
}

export default Page
```

Load the page in a browser, switch tab back and forth, see the "expires" field change (because getSession is being called)

now, change the _app file to use a clientMaxAge of 5mins and see that the "expires" field is now stable

**Expected behavior**
By default, the session is not expected to get refreshed

**Additional context**
next-auth@3.14.6

**Comment by jmuffat** [comment]
In case it helps:
- nextauth is configured to use JWT
- the provider is AzureADB2C

**Comment by balazsorban44** [comment]
This is the default and intended behavior as described in the docs: https://next-auth.js.org/getting-started/client#client-max-age

**Comment by jmuffat** [comment]
ok, I didn't read it that way. I understand. Setting maxAge to 5mins fixes my application, so no big deal. 

For the record, here is how I found out this behaviour that I didn't expect:

I'm working on a form where it is very likely the user will switch between it and another app to copy-paste elements. When using the default settings, the page queries the server and gets a new session every time I switch back. I had a component that had a `useEffect(..., [session])` and that ended up triggering re-renders every time, which was clearing all changes to fields. I figured I was wrong to use _session_ in this way, which was easily solved, but that made me realize _next-auth_ was constantly querying the server every time I was switching between pages/applications.

Maybe it's worth mentioning in the page you mentioned, as it's not super obvious it should be doing that. (or maybe not, it's hard to get the wording right and not cause more confusion ;) )

Anyways, thanks a lot for the clarification.

**Comment by balazsorban44** [comment]
Yes, I guess the "correct" behavior is hard to define. Probably every app has different meanings for it. I understand that in your situation it created confusion. If you have a suggestion on how to improve the docs for it, please open a PR! 😊
