### ISSUE TITLE
Change redirect url but still signin the user

### ISSUE THREAD

**Issue by ludersGabriel** [nextauthjs/next-auth#1716]
**Your question**

Can I change the redirect url based on a condition and still signin the user?

**What are you trying to do**

In the signin callback, I pull some data from my backend after I get the user token to see if its the first login. If it is, I'm returning a string to redirect to, which works. The problem is that the user doesn't get signed in, so I lose the session/token.

Is there a way to redirect the user and still keep the session/token? 

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
the intended behavior of this callback is to indicate that the user cannot login, if anything else is returned than `true`

https://next-auth.js.org/configuration/callbacks#sign-in-callback

When logged in, you can do a client-side check and redirect the user to anywhere else, based on their session.
