### ISSUE TITLE
Refresh JWT Token Tutorial outdated?

### ISSUE THREAD

**Issue by TrueshotBarrage** [nextauthjs/next-auth#1729]
**Your question**

Is the tutorial at https://next-auth.js.org/tutorials/refresh-token-rotation outdated for the current release of NextAuth.js?

**What are you trying to do**

It seems like the code differs a lot from the other tutorials, but I wasn't sure, so to clear up the confusion, I wanted to ask here. For instance, `const [session] = useSession()` in the tutorial, v.s. `const [session, loading] = useSession()` for the newest release.

**Reproduction**

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
not sure I understand the problem. if you have a suggestion to improve the tutorial, please open a PR with proper explanation what you think can be improved and how.

**Comment by TrueshotBarrage** [comment]
Sorry, I suppose my question must have been unclear. My question is whether the tutorial is outdated for the current release or not, because I'm quite a noob at this and not sure if the tutorial code in its current state works for the latest release of NextAuth.js.
