### ISSUE TITLE
Confusion around the Okta provider

### ISSUE THREAD

**Issue by kaseymccurdy** [nextauthjs/next-auth#1738]
**Your question**
👋 Hello - I'm looking at using Okta to authenticate my Nextjs application and running into some difficulty / confusion. Is the Okta provider for next-auth intended to allow people to sign in with Okta only? 

**What are you trying to do**
More clearly, my goal is to have people sign into my app with facebook, google or their email. If I have a series of identity providers setup in Okta, and use Okta as an auth provider for next-auth, will my users be able to sign up / in with their social credentials, or is this intended only for people to sign in with their Okta account credentials (i.e. - me, as a person, who has an okta account from my company)

THANK YOU SO MUCH!

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by kaseymccurdy** [comment]
To whomever this helps on the internet, I think I've figured out the answer to my question. I believe it has to do with the way you construct the base URL / domain of your auth server...

# Examples
### Sign in with Okta (and only Okta)
If you want to allow people to sign into an application using their **Okta** credentials (i.e. - an application that you wish individuals with an Okta account from within your company to sign into) -- you would use what is called the "Okta Org Authorization Server" -- and the URL would look like: `https://${yourOktaDomain}/oauth2/default`

> ___**This is not what you want if you simply want to allow end-users to sign into your application with their social credentials, for example**___



### Sign in, using Okta as the Identity Provider for your application
To do this, you need to [create](https://developer.okta.com/docs/guides/customize-authz-server/) a "[Custom Authorization Server](https://developer.okta.com/docs/concepts/auth-servers/)",  which would mean that your domain for auth now becomes: `https://${yourOktaDomain}/oauth2/${OKTA_CUSTOM_AUTH_SERVER_ID}`

# More info:
https://developer.okta.com/docs/reference/api/oidc/#composing-your-base-url

**Comment by balazsorban44** [comment]
@kaseymccurdy if this clarifies things for Okta users in your opinion, would you be so kind and update the documentation with your findings? 😊

It's this file: https://github.com/nextauthjs/next-auth/blob/main/www/docs/providers/okta.md
