### ISSUE TITLE
NO DOCUMENTATION: Next-auth with Cognito sign up/sign in

### ISSUE THREAD

**Issue by JavaJamie** [nextauthjs/next-auth#1741]
Can't find any documentation on this at all.

Do I need to create a custom backend to facilitate Cognito user sign ups / logins? In this case, what does the `Providers.Cognito` even do? It seems creating a custom authentication for this defeats the purpose of using Cognito altogether?

I essentially need a standard email/password login to register and login users inside a Cognito user pool.

**Comment by balazsorban44** [comment]
https://next-auth.js.org/providers/cognito
