### ISSUE TITLE
Extending the database to have more tables

### ISSUE THREAD

**Issue by yannickgloster** [nextauthjs/next-auth#1744]
**How do I extend the database to have another table**

**I'm creating groups of users and am trying to create a database that contains groups and another one that has list of users connected to a groups**

**Feedback**

* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth/discussions/1745
