### ISSUE TITLE
Typescript errors when using customer provider

### ISSUE THREAD

**Issue by bhaskarmurthy** [nextauthjs/next-auth#1752]
**Describe the bug**
I'm getting a type error when passing a custom `Provider` to the `NextAuth` method.

**Error 1**
When passing an `id` to the provider config, there's an error about `Type 'string' is not assignable to type 'undefined'.`

**Error 2**
However, if I don't set the `id` property, I get a different error about `Object literal may only specify known properties, and 'protection' does not exist in type 'Provider<undefined, "oauth">'`

**Error 3**
I'm also getting another type error if for `domain` if I set the Provider type using the template:
`const customProvider: Provider<'custom'> = {...}`

Error:
`Property 'domain' is missing in type 'Provider<"custom", "oauth">' but required in type '{ domain: string; }'`

```
import NextAuth from "next-auth";
import { Provider } from "next-auth/providers";

const customProvider: Provider = {
  // required
  id: "custom",
  name: "Custom Provider",
  type: "oauth",
  version: "2.0",
  accessTokenUrl: process.env.OAUTH_TOKEN_URL,
  authorizationUrl: `${process.env.OAUTH_AUTHORIZE_URL}?response_type=code`,
  clientId: process.env.OAUTH_CLIENT_ID,
  // optional
  params: { grant_type: "authorization_code" },
  protection: ["pkce", "state"],
};

export default NextAuth({
  providers: [customProvider],
  // debug: true,
});
```

**Steps to reproduce**
Steps to reproduce the behavior.

Include a link to public repository which can be used to reproduce the behaviour.

**Expected behavior**
If I set the `id` to be a string constant using the `Provider<'custom'>` type, I should be able to set the `protection` optional value (as per the docs)

**Screenshots or error logs**
If applicable add screenshots or error logs to help explain the problem.

**Additional context**

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
a big rewrite and built-in types are coming soon, watch out for 

https://github.com/nextauthjs/next-auth/pull/1690

it will first be merged to beta, then soon after to main.

hopefully that should address all your problems.

if not, feel free to repoen this.
