### ISSUE TITLE
Provide union type instead string for sign in

### ISSUE THREAD

**Issue by softshipper** [nextauthjs/next-auth#1761]
Hi all 
We should provide for sign-in function an union type instead a string to make it more typesafe:
```
declare function signin(
    provider?: string,
    data?: Record<string, unknown> & {
        callbackUrl?: string;
        redirect?: boolean;
    },
    authorizationParams?: string | string[][] | Record<string, unknown> | URLSearchParams
): Promise<void>;
```
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7c785c26527720bf726f8b8bcbab2f96c600d1a4/types/next-auth/client.d.ts#L53

Here is the list of providers that are supported https://next-auth.js.org/configuration/providers.   

Thanks

**Comment by balazsorban44** [comment]
will be addressed in https://github.com/nextauthjs/next-auth/pull/1690

**Comment by softshipper** [comment]
Awesome. Thanks a lot
