### ISSUE TITLE
Discord: User ID (snowflake) not available on profile

### ISSUE THREAD

**Issue by sbauch** [nextauthjs/next-auth#1776]
The Discord provider, afaict, is not attaching the user ID to the profile. It's a bit odd as according to the Discord docs, the snowflake id should be available at the `id` on the user object - https://discord.com/developers/docs/resources/user#user-object

**Steps to reproduce**
Follow the example code to setup Discord.

I blogged about this, so there's some code to look at here, but the source isn't open just yet - https://cryptorchids.io/almanac/blog/web-2-0-web-3

**Expected behavior**

For the user's snowflake ID to be on the profile object.

**Screenshots or error logs**

here's a console. (the userId attribute is fdrom my workaround, see below)
<img width="873" alt="Screen Shot 2021-04-19 at 4 32 51 PM" src="https://user-images.githubusercontent.com/923033/115299579-f79fa580-a12c-11eb-9dc9-574543f24e69.png">

**Additional context**
I am working around this right now with callbacks:

```ts
export default NextAuth({
  providers: [
    Providers.Discord({
      clientId: process.env.DISCORD_CLIENT_ID,
      clientSecret: process.env.DISCORD_CLIENT_SECRET,
    }),
  ],
  callbacks: {
    async session(session, userOrToken) {
      session.userId = (userOrToken as JWT)?.userId as string;
      return Promise.resolve(session);
    },
    async jwt(token, _user, account, _profile, _isNewUser) {
      if (account?.id) {
        token.userId = account.id;
      }
      return token;
    },
  },
})
```

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
not using Discord myself, but can you spot any error here?:

https://www.github.com/nextauthjs/next-auth/tree/main/src%2Fproviders%2Fdiscord.js

the profile callback assumes that it gets an `id` from the provider.

**Comment by balazsorban44** [comment]
Also keep in mind that id is not in the default session payload.

https://github.com/nextauthjs/next-auth/blob/457952bb5abf08b09861b0e5da403080cd5525be/src/server/routes/session.js#L33

Your "workaround" looks to me as the solution.

**Comment by sbauch** [comment]
Oh yup that explains it. Ok right on thanks, will stick with that then and close this.
