### ISSUE TITLE
Logger is being called infinitely and intercepting any errors

### ISSUE THREAD

**Issue by samueleguino97** [nextauthjs/next-auth#1793]
**Describe the bug**
Whenever I have any console.error, including the one about keys in a list in react, I get an error message telling me that the call stack size is being overflwon and nothing else runs. Am i doing something wrong?

**Steps to reproduce**
It happened in a new next js project with typescript, just putting the Provider from next-auth causes this issue

**Expected behavior**
I should be able to see what error messages I have without next0auth intercepting them

**Screenshots or error logs**
![2021-04-20_20h05_56](https://user-images.githubusercontent.com/45829271/115478300-d49bf100-a213-11eb-8189-ea2eb4e33aea.png)

**Comment by balazsorban44** [comment]
Fixed in `3.15.5`, please upgrade.

See also #1783
