### ISSUE TITLE
Handle errors on GET requests to callback url

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#1819]
For more info, see https://github.com/nextauthjs/next-auth/discussions/1740#discussioncomment-648097

**Comment by ThangHuuVu** [comment]
This seems to be fixed now https://github.com/nextauthjs/next-auth/blob/a7601d0b453348a4e5f9c32876807d64c7663cf1/packages/next-auth/src/core/lib/oauth/callback.ts#L24-L34, So I am closing it
