### ISSUE TITLE
How to modify user during create/link account?

### ISSUE THREAD

**Issue by bduff9** [nextauthjs/next-auth#1825]
**Your question**
Hello!  I am loving NextAuth for its simplicity to initially set up, but I'm also struggling with some customizations that don't seem overly complicated.  Currently, I have an app with Email, Google, and Twitter auths.  I have no issues with users signing up using any of the 3, and even linking their Google and Twitter accounts after signing in with email.

However, I do not see any way to actually modify the built-in models data.  For instance, I have created a firstName and lastName on the user model, and if I manually populate these fields on the DB, it's returning the correct data.  But I see no possible way to use the first and last name returned from Google, for instance, to update this data either on account creation or account link.  Similar to image, if someone signs up with email, I see no way to update the image field from Google or Twitter when linking the account.

I see a ton of similar questions on here, but nothing definitively answered.  I know of the callbacks and the events, however, I have concerns with using either one of those.  For the callbacks, I have my GQL server on a different server due to a completely unrelated bug to NextAuth that prevents it from running in NextJS:
https://github.com/vercel/next.js/discussions/12254

So, if I wanted to follow some of the other answers about updating the names and image in the signIn callback, I believe it would cause a large delay in actually signing in while it waits on the GQL mutation to update the data.  If I wanted to use the events (createUser and linkAccount look like great options here), this looks like it would be non-blocking which would be a better solution, however unfortunately the profile data I need is not present there.

To me, the ideal would be if the model or repository was available either in the callback arguments or similar, so I can just update the model's data directly using the existing connection to my DB (i.e. `await userRepository.update(user.id, user);`).  I don't really want to bring in more of my database code to my NextJS project since I have to keep the majority of it separate anyway due to the above bug, and don't want to duplicate this code more than absolutely necessary.

**What are you trying to do**
Simply trying to fill out a user's information using the auth services.  If a user signs up with email, and then links google, their name, first name, last name and image should all be populated after linking Google.

Conversely, if a user signs up with Twitter, so we only have something like email and image, linking Google should then populate name, first name, and last name.

Regardless of the approach to this, I need to populate missing fields *only* when signing up/linking accounts, so we don't populate something the user purposefully deleted either.

**Reproduction**
I have my repo public here:
https://github.com/bduff9/nfl-pool-fe/tree/develop

Specifically, my NextAuth config is here:
https://github.com/bduff9/nfl-pool-fe/blob/develop/pages/api/auth/%5B...nextauth%5D.ts

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by Fronix** [comment]
There's no real way to stop a user from being created/logged in before they enter some additional information with next-auth. You would have to create a db adapter that you can use oustide of next-auth. Then create some form of HoC that can detect when some information is missing and redirect them to a page that lets them fill it out before continuing to the site.

You might be able to do it with the profile callbacks, but there might be some issues getting the data you want to the database. Maybe a combination of profile callbacks in the providers while using the `signIn` callback and identify when a user needs to be updated.

**Comment by bduff9** [comment]
@Fronix Sorry for the confusing question, but unfortunately that's not what I'm trying to do at all.  In fact, if I were, that is actually much easier since I am already doing something similar for a different use case. :) 

Let me try to clarify:

If a new user 'A' signs up using their email address, the DB would have their email address only (no image, no name, no first name, or last name).  This is expected and totally fine as we ask them to enter that information on the next screen after signing up anyway.  However, on this next 'Finish Registration' screen, we also allow them to link their other accounts.  So, if they then link their Google account on this screen after being signed in, Google returns all that data (name, image, first name, last name), but none of it is saved to the user.

Similarly, if a new user 'B' comes to the site and signs up with Twitter, they might be missing data like first name and last name (as NextAuth stores name, image and email on signup with OAuth).  However, I can make an educated guess on first name and last name (essentially first name would be first word, and last name would be rest of the words).  This won't be 100% accurate due to certain first names (i.e. `Billy Bob` or `Mary Sue`) but it will be close and is fine if wrong since the user can update it themselves.

So what I am asking for is not stopping the user at all, it's just tying into the current signIn callback or signIn and/or linkAccount events.

Here's some pseudo code to hopefully help illustrate what I am envisioning:

```ts
callbacks: {
async signIn(user, account, profile) {
  if (!user.image && profile.image) {
    user.image = profile.image;
    user.save();
  }

  if (!user.name && profile.name) {
     user.name = profile.name;
    user.save();
  }

  if (!user.firstName || !user.LastName) {
    const [firstName, ...lastName] = (user.name || profile.name || '').split(' ');
    user.firstName = firstName;
    user.lastName = lastName.join(' ');
    user.save();
  }

  ...rest of sign in logic...
},
...rest of callbacks...
},
```

I know the above won't work, but the ideal would be tying into the existing TypeORM user repository or connection nextauth uses so I can make the changes needed either on sign-in or when linking accounts.  Because if I call my current backend from this callback, I am worried it will take too long and will be a bad UX if the user has to wait too long.  And I don't want to move more backend logic into this project and set up a new connection and then update it there since I want to keep the FE and BE as separate as possible, and also would still need to set up a new connection, make the DB update call, and then shut down the connection, which is a lot of overhead.

Alternatively, there are the signIn and linkAccount events which are asynchronous and so would be a better place to call this in my mind, but I don't have the data needed there as it only passes one thing (such as the current user object in the message field).

I hope this helps to clarify but if I am still being unclear, please let me know and I'm happy to provide more information on what I am looking for

**Comment by bduff9** [comment]
Or, it's entirely possible I am coming at this the wrong way and there is a better/simpler way to accomplish it.  The root question is how do I use the data I already have from OAuth sign in/link to populate additional fields?  So I extended the user model with first and last name, how can I populate those using the data from OAuth (either first and last name fields like Google returns, or by running custom logic to parse the name returned)?  Or fill in missing data when linking accounts, i.e. the image field?

**Comment by Fronix** [comment]
@bduff9 Okay I see, well what you really are looking for is the `profile()` callback in the providers. That's the only place where you will be able to access all the information you are looking for.

I've never tried authenticating users with multiple providers after they sign in, but I feel like your example code should work. I'd suggest taking a look at the [callback.js L83](https://github.com/nextauthjs/next-auth/blob/fbb09303af8fbe8061437cb033eee8c1ae217493/src/server/routes/callback.js#L83) [callback.js L179](https://github.com/nextauthjs/next-auth/blob/fbb09303af8fbe8061437cb033eee8c1ae217493/src/server/routes/callback.js#L179) and [callback-handler.js](https://github.com/nextauthjs/next-auth/blob/main/src/server/lib/callback-handler.js) files. You will notice that `callbackHandler` recievies the `profile` and `account` objects, those are then used to save the user's data.

If you then combine this with your own DB adapter you can do some magic with the `profile` and `account` objects and send your own information using one of the arguments in `[linkAccount()](https://github.com/nextauthjs/adapters/blob/edff7803d6680045fcf67e46dc7e072d86b7e0d6/packages/typeorm-legacy/src/index.js#L216)` in that function you could call `updateUser()` or whatever you want.

There might be a better solution, but this is what I could think of off the top of my head.

**Comment by bduff9** [comment]
Thanks, I will take a look.  I had not seen the profile callback before, so if anyone else finds this issue in the future, this is documented here:
https://next-auth.js.org/configuration/providers#oauth-provider-options

For the record, all the data I need is in the signIn callback already, in the user and profile objects, there's just no way to save it directly to the user object there (without calling something external).  I'd prefer not to set up a full adapter as I have everything I need currently other than this one piece. So if the profile callback lets me return the shape of data to save, that might be the best place.

However, I will review the profile callback and the links you sent to see if I can find anything from there on a good way to accomplish this.  Thanks again!

**Comment by bduff9** [comment]
Just to update and close this, it looks like it is not possible to do what I needed with this library.  Perhaps some future changes to oauth providers or the signIn callback could help, but as of current, there is no way I can see to add data to the user in signIn or access the existing db connection.

Just for completeness, to solve our requirements, I had to manually create a DB connection and use MySQL to run queries in signIn to handle my use case (populating data from the returned OAuth profile).  This is still not ideal as I have to run multiple queries in signIn to get/verify data plus update data if needed.  I also am creating another DB connection there so even though I am sure to close it in a finally block, I worry that under load it will stress the DB since the backend opens conns to the db, next-auth opens a conn to the DB, and now my custom code is also opening a conn to the DB.  However, there was no other way I could see to do what we needed.  Hope this helps someone else if they also are looking for something similar.

**Comment by ozgursef** [comment]
same issue
