### ISSUE TITLE
Signing in using magic link with Outlook email when SafeLinks enabled does not work

### ISSUE THREAD

**Issue by dweemx** [nextauthjs/next-auth#1840]
**Describe the bug**
Signing in with an Outlook email which is linked to an account where the `SafeLinks` premium feature is enabled does not work.

Another authentication library seems to have the same issue: https://github.com/FusionAuth/fusionauth-issues/issues/629.
When this Outlook feature is enabled, the magic link is encapsulated by a `SafeLinks` Outlook protection URL, e.g.:
```
https://eur02.safelinks.protection.outlook.com/?url=<magic-link-url>
```

From the issue in `FusionAuth`, it seems that the token gets invalidated because of some request that `SafeLinks` is being made beforehand. (Source: https://github.com/FusionAuth/fusionauth-issues/issues/629#issuecomment-629157742)

**Steps to reproduce**
1. Sign in with Outlook email which has `SafeLinks` enabled
2. Click on Sign link from email

**Expected behavior**
User should be able to login

**Screenshots or error logs**
None. The user gets redirected to `/auth/sign-in?error=Verification`

**Additional context**
/

**Feedback**

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
I am a bit confused and have no knowledge of what SafeLinks is. Could you point to some documentation and/or try to explain your problem a bit better?

**Comment by ndom91** [comment]
I've done a bit more research, and it seems that Microsoft makes a HEAD request to the URL in the query params (our magic URL) before hand therefore "using up" the magic code and invalidating it for the user.

The fusion auth issue thread is pretty detailed / lots of discussion back and forth.  A quick fix that seemed to work was to simply ignore HEAD requests in the invalidating magic code logic. 

An Opencollective maintianer posted in that thread as well saying they'd had to work around a similar issue with outlook.com robots, and linked a PR through which they were able to get around the issue - https://github.com/opencollective/opencollective-frontend/pull/5476

**Comment by dweemx** [comment]
Indeed @ndom91 
We followed the suggestion from the discussion i.e.: ignoring the HEAD request.

**Comment by Raggok** [comment]
any workaround  that we can implement ???

**Comment by dweemx** [comment]
@Raggok, one workaround is available here https://github.com/nextauthjs/next-auth/pull/1841

**Comment by Raggok** [comment]
how can i use this workaround on my production code? thx!

**Comment by dweemx** [comment]
You can either use this branch https://github.com/dweemx/next-auth/tree/fix/prod%2Fmagic-link-outlook-safe-links or you'd have to fork `NextAuth` and patch it in custom branch and install `NextAuth` using that particular branch

**Comment by balazsorban44** [comment]
@dweemx as mentioned, your suggestion in #1840 cannot possibly work, as I explain in https://github.com/nextauthjs/next-auth/pull/1841#pullrequestreview-650666198. I am guessing you have added some other changes as well. Right?

**Comment by ndom91** [comment]
@Raggok you can also whitelist domains in the office365 portal apparently, haven't tried it myself but I've read it. 

So you could whitelist the domain of your application and then outlook won't "check" the URL and trigger the magic link 1-time-use URL and invalidate it for the user.

**Comment by thmsrmbld** [comment]
Just wanted to say for the record and for anyone else - I came into this issue (I run a platform using NGINX on the front, as a reverse proxy for a Django application, but the principles are the same for any stack) and here are some options for sorting it:

- Take any HEAD requests at the web server level requesting this URL and bounce them out somewhere safe rather than letting them through to the application code (fast, secure, but more complicated from an update perspective, and might have unexpected side effects).
- Alternatively allow the request through as normal, but protect your view to only allow HEAD / GET requests and then check if it’s HEAD - if it is, redirect the request somewhere you know is safe and will return a 200 (which is what I did and it worked).
- Alternatively, you could also just block all HEAD requests from this endpoint (which I’d prefer to do) but initially I wouldn’t recommend it especially if you need a fast fix - because I’m not certain that blocking HEAD requests won’t trip something in the MS SafeLinks technology and give the user an ‘unsafe’ warning or similar.

Anyway yes, annoying bug but but the solution for me was to handle the HEAD requests in the endpoint and pass them somewhere else, which doesn't invalidate your tokens by completing the GET operation by accident.

Solved for me on both Outlook web client and desktop client with SafeLinks enabled.

**Comment by rdoyle99** [comment]
Just adding in for anyone else coming in from google and experiencing this:

I'm seeing this issue with a lot of my corporate clients who rely on outlook. Organization protocol mandates SafeLinks, which screws them up, and invalidates their Login Via Email.

Would be great to see support for this merged into NextAuth out of the box!

**Comment by balazsorban44** [comment]
Doesn't seem like a general enough use case.

See a proposed solution here: https://github.com/nextauthjs/next-auth/issues/1840#issuecomment-848791994

See https://next-auth.js.org/configuration/initialization#advanced-initialization for advanced use cases like this. If someone creates a tutorial/example repo specific to this problem, I'm happy to link to it from the docs under https://next-auth.js.org/tutorials#advanced for example.

**Comment by cymen** [comment]
I ran into this problem and ended up adding a `/api/ok` endpoint that just returns HTTP 200 with "ok" as the body (and doesn't require authentication). Then I added this rewrite rule in the nginx configuration:

```nginx
    if ($request_method = HEAD) {
      rewrite ^/api/auth/callback/email.* /api/ok last;
    }
```

You of course might have to do something else and there might be some way to do this without adding the `/api/ok` route but I wanted that anyway.

**Comment by mbaraa** [comment]
UPDATE:
safe links no longer sends a **HEAD** request, instead it sends a **GET** with a very useful headers `user-agent` and `x-native-host` which contain `OneOutlook` somewhere in them.

example headers from the new outlook on windows 11:
```
'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.47 OneOutlook/1.2023.927.100'
'x-native-host': 'OneOutlook/1.2023.927.100'
```

So I ignored every request with `OneOutlook` in the mentioned headers, and it worked!

example in Nuxt 3
```ts
// server/middlewares/bypass-safelink.ts
export default defineEventHandler(async (event) => {
  if (
    event.headers.get('user-agent')?.toLowerCase().includes('oneoutlook') ||
    event.headers.get('x-native-host')?.toLowerCase().includes('oneoutlook')
  ) {
    setResponseStatus(event, 200)
    return {}
  }
})
```
You might wanna check for the email's specific callback endpoint, but I'm not sure if there's anything else that sends those headers.

**Comment by happyfire** [comment]
> UPDATE: safe links no longer sends a **HEAD** request, instead it sends a **GET** with a very useful headers `user-agent` and `x-native-host` which contain `OneOutlook` somewhere in them.
> 
> example headers from the new outlook on windows 11:
> 
> ```
> 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.47 OneOutlook/1.2023.927.100'
> 'x-native-host': 'OneOutlook/1.2023.927.100'
> ```
> 
> So I ignored every request with `OneOutlook` in the mentioned headers, and it worked!
> 
> example in Nuxt 3
> 
> ```ts
> // server/middlewares/bypass-safelink.ts
> export default defineEventHandler(async (event) => {
>   if (
>     event.headers.get('user-agent')?.toLowerCase().includes('oneoutlook') ||
>     event.headers.get('x-native-host')?.toLowerCase().includes('oneoutlook')
>   ) {
>     setResponseStatus(event, 200)
>     return {}
>   }
> })
> ```
> 
> You might wanna check for the email's specific callback endpoint, but I'm not sure if there's anything else that sends those headers.

As I just tested, there is no user-agent and x-native-host headers in safelink request now. And there are only 'x-real-ip', 'x-forwarded-for', 'connection' and 'hsot' in headers.

**Comment by mbaraa** [comment]
> > UPDATE: safe links no longer sends a **HEAD** request, instead it sends a **GET** with a very useful headers `user-agent` and `x-native-host` which contain `OneOutlook` somewhere in them.
> > example headers from the new outlook on windows 11:
> > ```
> > 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.47 OneOutlook/1.2023.927.100'
> > 'x-native-host': 'OneOutlook/1.2023.927.100'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So I ignored every request with `OneOutlook` in the mentioned headers, and it worked!
> > example in Nuxt 3
> > ```ts
> > // server/middlewares/bypass-safelink.ts
> > export default defineEventHandler(async (event) => {
> >   if (
> >     event.headers.get('user-agent')?.toLowerCase().includes('oneoutlook') ||
> >     event.headers.get('x-native-host')?.toLowerCase().includes('oneoutlook')
> >   ) {
> >     setResponseStatus(event, 200)
> >     return {}
> >   }
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You might wanna check for the email's specific callback endpoint, but I'm not sure if there's anything else that sends those headers.
> 
> As I just tested, there is no user-agent and x-native-host headers in safelink request now. And there are only 'x-real-ip', 'x-forwarded-for', 'connection' and 'hsot' in headers.

are you sure that you tested it with the new outlook? (the one with the hexagonal icon, and the word "new" on it)

**Comment by MagnusAycox** [comment]
As the GET and HEAD filtering doesn't seem to work and Microsoft 365's way of checking links is changing more often than an influencers mood and profile picture, isn't there a more robust way of filtering the requests?
Like the "Referer" header value...
Does Microsoft 365 and other link checkers really have the site URL as "Referer" in the request? If not, then the easiest way might be to just ignore the POST/GET/HEAD method and all other values that probably will change, and concentrate on this one. Or is the "Referer" header value empty/invalid for the authentication request when the link is clicked?

**Comment by JonParton** [comment]
I've also encountered this today and found no way around it ... There are no obvious indications when it is outlook / Defender detonating the links (As they want to appear as human as possible so malicious actors can't act good for them either!) so the only option I can seem to think of is to make the tokens multi use for a short time period to get around this ... which I'm sure is terrible practice. 

Any suggestions of other ways around this welcome! ...

p.s. for office 365 domains you control you could of course disable this link checking for your specific domain...., but you can't on unknown client's outlook instances!

**Comment by FilipMasar** [comment]
@balazsorban44 We also just run into this issue. I think it affects a lot of users. I would say almost every corporate users using outlook or maybe also other email providers.

Do you think there might be some way around this on a library level?

**Comment by ndom91** [comment]
@FilipMasar 

Yeah so the general idea is that outlook/other email providers scan all the URLs in the email to check for malware, etc. and by doing that and making a request to the use-verification-token-up endpoint of Auth.js, they "use up" the verification token so that it can't be used again. So when the user goes to click on the link in the Email, it'll fail because the token is already used.

So more specifically, some workarounds / fixes could be to (1) allow verification tokens to be used twice, this isn't a good idea for many other reasons. So (2) would be to filter out the requests from outlook/other email clients and not count those against verification token requests.

As you can see in this thread, many people have found and tried various filters for Outlook requests, but (1) outlook seems to change this every once in a while and (2) you don't want to block legitimate traffic at the same time.

I dont think anyone on the team has the time to dig into this further at the moment, but if you or anyone else come across a good filter that **only** targets and blocks Outlook / email client traffic without blocking legitimate traffic, we can definitely take a closer look and potentially implement it :pray:

**Comment by FilipMasar** [comment]
@ndom91 thanks for for feedback. 

We did some research and ended up with following solution. We create our custom magic link which redirects users to "welcome" page and includes original magic link as a query parameter. On this welcome page user has to click button to continue. Button just navigates to original magic link.

Hope this can help others as well. I believe this is the best approach to this.

From here we learned about this option https://supabase.com/docs/guides/auth/auth-email-templates#email-prefetching

**Comment by ndom91** [comment]
@FilipMasar ah yeah this is a great idea too, nice one

**Comment by frederickmannings** [comment]
Same issue here. 

Thanks @FilipMasar  for the suggestion. Will implement a similar solution and inform whether it worked for us in!

**Comment by FilipMasar** [comment]
@frederickmannings actually we needed do do one more thing and that is add recaptcha. Because it looks like bots can also click on buttons. Here it is described more https://github.com/MicahParks/magiclinksdev/pull/3

I don't actually understand why is this happening. If we would be sending emails with unsubscribe link, then will users be automatically unsubscribed because of this outlook safe link functionality? 
We also noticed that users with outlook are getting our emails with ~10mins delay which is terrible UX. It is probably because outlook is first checking if the email is fine. Does anyone know if we can do something about it? Is this the case with every email that ends up in outlook?

**Comment by frederickmannings** [comment]
> > I don't actually understand why is this happening. If we would be sending emails with unsubscribe link, then will users be automatically unsubscribed because of this outlook safe link functionality?
> 
> I don't know about your other questions but from my tests the token is only consumed when you click on the link. Links in the email get verified when you click them, either by embedding them into a MS URL or verifying before it goes to the browser.

That's not what my experience suggests. It seem to me that outlook is **following** the links, as when the user eventually gets them (embedded or not), the token has been consumed.

@FilipMasar, FWIW adding an additional page with a submit button and reCAPTCHA did the trick for me also 👍🏼

**Comment by davidlky** [comment]
> We also noticed that users with outlook are getting our emails with ~10mins delay which is terrible UX. It is probably because outlook is first checking if the email is fine. Does anyone know if we can do som

Did you figure out why this is happening? @FilipMasar ? getting the same delay

**Comment by riccardolardi** [comment]
We've opted to use the OTP token code since we can't foresee nor control how M$ may change their bot safelink logic in the future...

**Comment by frederickmannings** [comment]
> We've opted to use the OTP token code since we can't foresee nor control how M$ may change their bot safelink logic in the future...

Good idea. We have done the same.

**Comment by frederickmannings** [comment]
@jasondainter, yes that's right.

Using OTP avoids all the problems, but it's a solution that you'll have to bake yourself.

**Comment by jasondainter** [comment]
Hi All.

Finally coming to fix this (have more safelinks customers complaining they cant log in). Doing OTP is a much bigger job so tryig to avoid for now.

I am planning to (in the email that gets sent with the magic link url) also provide a text version eg 

https://www.yoursite.com/api/auth/callback/email?callbackUrl=https%3A%2F%2Fwww.yoursite.com%2Fapp%2Floader&token=XYZthisisntreal1bfeff499a1cb7fc84432b112&email=your%40email.com

So worst case if this happens to users I can put in some smaller text for them to copy and paste that URL into a browswer to log them in.

I'm wondering if anyone has tried this route with any success, and curious if anyone knows if safelinks/outlook will rewrite the URL even if it's written in text form.

**Comment by jasondainter** [comment]
Hmm. So I now read online that these urls are not only wrapped in a safelinks url but they are actually "pre-examined" (eg clicked) by outlook which of course would invalidate the token.

If anyone can confirm that is there experience also that would be super handy.

Would a possible workaround be to modify nextauth not to use the token if "safelinks" is contained in the url? Or would that be as much work as implementing a OTP?

**Comment by lesderid** [comment]
We fixed this by adding an interstitial page that dynamically consumes the token (by navigating to the original link with `router.replace()`).

**Comment by jasondainter** [comment]
Hmm, are you sure that works in Outlook and have you specifically tested with a client that definately has Outlook with SafeLinks enabled? I believe SafeLinks actualy consumes the token *before*actually this step so I'm not convinced an interstitial page would solve it.

I ended up implementing OTP giving users a backup OPT code in the email which they could click to open a new OTP page in the cases where they had Outlook Safelinks this solved it.

**Comment by lesderid** [comment]
> I believe SafeLinks actualy consumes the token _before_actually this step so I'm not convinced an interstitial page would solve it.

We modified the e-mail sent by NextAuth/Auth.js so it includes a link to the interstitial page instead of the link to the token consuming page.

> I ended up implementing OTP giving users a backup OPT code in the email which they could click to open a new OTP page in the cases where they had Outlook Safelinks this solved it.

I do agree OTP codes are a good (and possibly better) solution, but we wanted to change the user experience as little as possible.

**Comment by jasondainter** [comment]
Interesting soltution! 

Turns out Microsoft Safelinks is not *that* safe after all then :-D

**Comment by Lukasvo** [comment]
Since these relevant docs weren't referenced here before: https://next-auth.js.org/tutorials/avoid-corporate-link-checking-email-provider

**Comment by lesderid** [comment]
> We fixed this by adding an interstitial page that dynamically consumes the token (by navigating to the original link with `router.replace()`).

In the end, this didn't prove to be sufficient for all link checkers. We now set a cookie when the e-mail address is entered and check for its presence on the interstitial page. This has the same effect as a captcha but is transparent to the user.

**Comment by lesderid** [comment]
> Since these relevant docs weren't referenced here before: https://next-auth.js.org/tutorials/avoid-corporate-link-checking-email-provider

As of 2025 (but presumably, [since at least 2022](https://github.com/nextauthjs/next-auth/pull/3900#issuecomment-1231965273)), this is insufficient for Safe Links (Microsoft 365): ["URLs that don't have a valid reputation are detonated asynchronously in the background."](https://learn.microsoft.com/en-us/defender-office-365/safe-links-about#:~:text=URLs%20that%20don%27t%20have%20a%20valid%20reputation%20are%20detonated%20asynchronously%20in%20the%20background.).
