### ISSUE TITLE
`getCsrfToken()` requires an empty object when called on `client` side

### ISSUE THREAD

**Issue by typedashutosh** [nextauthjs/next-auth#1847]
**Summary of proposed feature**
When calling `getCsrfToken()` or `getSession()` on client side, TS complains to provide at-least 1 argument, which is an empty object `{}`. Although documentation doesn't say any such thing.
Can we remove passing an empty object in those function?

**Purpose of proposed feature**
Just to make it less confusing when using nextauthjs with Typescript

**Additional content**
![image](https://user-images.githubusercontent.com/68853189/115983231-9f99f080-a5bd-11eb-997f-833e0f245d9a.png)
![image](https://user-images.githubusercontent.com/68853189/115983294-f7d0f280-a5bd-11eb-91ee-ace7f1207e23.png)
![image](https://user-images.githubusercontent.com/68853189/115983247-b7717480-a5bd-11eb-8d41-8e906115390c.png)

PS: `"next-auth": "^3.15.9"`
Notify if fixed in newer versions. Thanks!

**Comment by balazsorban44** [comment]
sure, do you want to open a PR? 😊

**Comment by typedashutosh** [comment]
I've never done that to a public repository ever. Can you guide me what to do?
I believe, only types definitions needs some tweaks? If I'm not wrong.

**Comment by balazsorban44** [comment]
sure, you'll have to make the parameter optional on this line:

https://github.com/nextauthjs/next-auth/blob/065d9eb310cd873f2aa80b01bfb97d6d4a2bcceb/types/client.d.ts#L55

you can click the edit button in the upper right corner of the screen, do your change, commit it at the bottom, and just follow the instructions for creating a Pull Request. 😊 tell me how it goes

**Comment by typedashutosh** [comment]
It was saying `You must be on a branch to make or propose changes to this file` so I switched to `main` branch and made PR #1850

**Comment by balazsorban44** [comment]
Awesome thank you for your contribution!
