### ISSUE TITLE
I got an `Illegal arguments` error while signing in.

### ISSUE THREAD

**Issue by typedashutosh** [nextauthjs/next-auth#1849]
**Your question**
What does this error means?
http://localhost:5500/signin?error=Illegal%20arguments:%20string,%20undefined

**What are you trying to do**
Was trying to sign in user with `credentials`

**Reproduction**
https://github.com/typedashutosh/blog-app-nextjs/commit/ecf4a3fa6cec921e44fce841d88cc5152abbd756

**Comment by balazsorban44** [comment]
A quick Google suggests that it is something with your bcrypt compare call:

 https://www.google.com/search?q=illegal+arguments+string+undefined
