### ISSUE TITLE
Why does it take seconds to to get session after getting to the page with router.push() and next Link?

### ISSUE THREAD

**Issue by kabiskac** [nextauthjs/next-auth#1857]
**Your question**
What am I doing wrong? It works fine without redirection and regular a tags.

**What are you trying to do**
I am trying to redirect to a secured page with either router.push() or a next Link, but it takes seconds until the page loads with the session.

**Reproduction**
```javascript
import Link from "next/link";
import { useSession } from "next-auth/client";
import { useRouter } from "next/router";
import { useEffect } from "react";

export default function Foo() {
  const [session, loading] = useSession();
  const router = useRouter();

  useEffect(() => {
    if (!loading && !session?.accessToken) {
      router.push("/auth/login");
    }
  }, [loading, session]);

  if (!session) {
    return <div></div>;
  }
  return (
    <div>
      <h1>Foo Page</h1>
      <Link href="/welcome">Welcome Page Link</Link>
      <div>
        <button
          onClick={() => {
            router.push("/welcome");
          }}
        >
          Welcome Page Router
        </button>
      </div>
      <a href="/welcome">Welcome Page A Tag</a>
    </div>
  );
}
```

Might the problem be related to the fact that I use internationalisation?

**Comment by rozenmd** [comment]
If you're testing this on a dev-server (not deployed), Next.js rebuilds the page `<Link>` points to *every time*.

**Comment by balazsorban44** [comment]
@rozenmd is true, it has nothing to do with `next-auth`, it's the default behavior of the Next.js dev server. If you are using a database adapter, your connection to that might also affect this. in any case, there is nothing we can do here, unfortunately.

**Comment by kabiskac** [comment]
So what should I do? I get the same behaviour if I do npm run start.

**Comment by balazsorban44** [comment]
Without a reproduction, it is hard to tell.

**Comment by kabiskac** [comment]
https://codesandbox.io/s/distracted-browser-fyjek

For some reason in the sandbox it only happens after going back from "welcome" to "index" with the browser's back button and then pressing the button again.
