### ISSUE TITLE
Infinite loop on error

### ISSUE THREAD

**Issue by danlobo** [nextauthjs/next-auth#1863]
When an error occurs, logger.js starts to call itself.

![Screenshot_14](https://user-images.githubusercontent.com/3091181/116139394-5a082100-a6ac-11eb-858e-379f98811a73.png)

Line 67 of logger.js is 
`_logger[level](code, ...message);`
, and line 15 is
`console.error("[next-auth][error][".concat(code.toLowerCase(), "]"), "\nhttps://next-auth.js.org/errors#".concat(code.toLowerCase()), ...message);`.

My guess is _logger === console, which makes logger to call itself infinitely.

The error itself is a forgotten key param inside a loop, nothing fancy.
`Warning: Each child in a list should have a unique \"key\" prop.%s%s See https://reactjs.org/link/warning-keys for more information.%s`

Everytime line 15 is executed the code is concatenated, generating messages like
`[next-auth][error][[next-auth][error][[next-auth][error][warning: each child in a list should have a unique \"key\" prop.%s%s see https://reactjs.org/link/warning-keys for more information.%s]]]`
and beyond, until the stack size is exceeded. 

Any help here is appreciated!

**[...nextauth].js**
```import NextAuth from 'next-auth'
import Providers from 'next-auth/providers'

import db from '../../../models/index.js'

export default NextAuth({
  // Configure one or more authentication providers
  providers: [
    Providers.Credentials({
        // The name to display on the sign in form (e.g. 'Sign in with...')
        name: 'Credentials',
        // The credentials is used to generate a suitable form on the sign in page.
        // You can specify whatever fields you are expecting to be submitted.
        // e.g. domain, username, password, 2FA token, etc.
        credentials: {
          username: { label: "Usuário", type: "text" },
          password: {  label: "Senha", type: "password" }
        },
         async authorize(credentials) {
          const dbUser = await db.usuario.findOne({
            where: {
              login: credentials.username
            },
            attributes: { include: ['senha'] }, 
          })

          if (!dbUser)
            return null

          if (!dbUser.validPassword(credentials.password))
            return null

          const _user = dbUser.get({plain: true})
          delete _user.senha

          return _user
        }
      })
  ],
  pages: {
    signIn: '/auth/signin'
  }
})
```

**pages/auth/signin.js**
```
import { getCsrfToken } from 'next-auth/client'

export default function SignIn({ csrfToken, query }) {
  return (
    <form method='post' action='/api/auth/callback/credentials'>
      <input name='csrfToken' type='hidden' defaultValue={csrfToken}/>
      <label>
        Usuário
        <input name='username' type='text'/>
      </label>
      <label>
        Senha
        <input name='password' type='password'/>
      </label>
      <button type='submit'>Entrar</button>
    </form>
  )
}

// This is the recommended way for Next.js 9.3 or newer
export async function getServerSideProps(context) {
  return {
    props: {
      csrfToken: await getCsrfToken(context),
      query: context.query,
    }
  }
}
```

**Comment by balazsorban44** [comment]
It has been fixed in a newer release, please upgrade to the latest. See: https://github.com/nextauthjs/next-auth/issues/1783
