### ISSUE TITLE
GitHub Provider fails - if you're *already* logged into github

### ISSUE THREAD

**Issue by xpollen8** [nextauthjs/next-auth#1883]
## Description 🐜

If one is already logged-into github in a browser and then tries to use `next-auth` to *Sign in with GitHub*,
the internal call to `https://github.com/login/oauth/authorize?state=...` fails with 404.

When *Sign in with GitHub* is used in a private window, it works as expected.

## How to reproduce ☕️

1) login into github
2) open a new tab
3) using a next-auth-based app, attempt to use the *Sign in with GitHub*

## Screenshots / Logs 📽

While logged-in

<img width="1052" alt="404" src="https://user-images.githubusercontent.com/552254/116502399-45708800-a868-11eb-95b8-bf97532b9afd.png">

While in a private window

<img width="715" alt="200" src="https://user-images.githubusercontent.com/552254/116502489-75b82680-a868-11eb-9cdd-84d010b7501e.png">

## Environment 🖥

Please run this command:

```
$ npx envinfo --system --binaries --browsers --npmPackages "{next-auth}"
```

```npx: installed 1 in 2.313s

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 2.93 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.0.0 - ~/.nvm/versions/node/v14.0.0/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v14.0.0/bin/npm
  Browsers:
    Brave Browser: 85.1.14.84
```

**Comment by balazsorban44** [comment]
Please provide a reproduction. This is not the case when I try it locally. There must be an issue with your config somewhere

**Comment by lsbyerley** [comment]
@xpollen8 did you ever figure out what the issue with your config was? I'm experiencing the same thing

**Comment by xpollen8** [comment]
Issue persists.
