### ISSUE TITLE
Issue running the dev app

### ISSUE THREAD

**Issue by i-palindrome-i** [nextauthjs/next-auth#1892]
## Description 🐜

I am getting an error when trying to run the dev app following the instructions in CONTRIBUTING.md. It is saying:
```
Module not found: Can't resolve 'next-auth/providers'
```

## How to reproduce ☕️

Follow the instructions in CONTRIBUTING.md to get the dev app running.

## Environment 🖥

```
  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 232.13 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/Documents/Projects/test-next-auth/next-auth/node_modules/.bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Edge: 90.0.818.49
    Firefox: 88.0
    Safari: 14.0.3
```

**Comment by balazsorban44** [comment]
I'm working on a fix for this, thank you for reporting!

**Comment by i-palindrome-i** [comment]
@balazsorban44 in the meantime, do you have a workaround (even if its manually copying some files, etc)? I'm trying to test a PR to enable a new provider which requires a small change to the code itself.

**Comment by balazsorban44** [comment]
comment out the adapter import and the right side of the optional chaining here:

https://github.com/nextauthjs/next-auth/blob/aa9c1e7c96fcbc23462a6f1488cb53c11dc42caa/src/server/index.js#L89

and instead of `import Providers from "next-auth/providers" `, do `import YourProvider from "next-auth/providers/your-provider"`

**Comment by balazsorban44** [comment]
@i-palindrome-i no workaround should be needed anymore, if you base your fork off of the `main` branch from now!
