### ISSUE TITLE
Redirect based on headers / cookies

### ISSUE THREAD

**Issue by cyrus-za** [nextauthjs/next-auth#1898]
## Summary 💭

Use next 10.2's new `has` feature for headers/cookies inside next.config.js to redirect if headers/cookiess missing

## Description 📓

With Next 10.2's [cookie and query matching rewrites](https://nextjs.org/blog/next-10-2#header-cookie-and-query-matching-for-rewrites-and-redirects) it is possible to check for headers "natively" without needing to run `getServerSideProps` or even worse a withAuth HOC that extends Page.getInitialProps.

Correct me if I am wrong, but next-auth has a opinionated way of storing the cookies and could thus have a default next.js.config extension to have these checks come baked in to the config as opposed to needing to use a HOC or to rely on the context provider to run inside react's event loop (even if its server side).

This will probably have a huge performance improvement for all next-auth users.

I know next-auth is a lib and not a framework so it does not have control over the next.config.js but there can be a small function exported from next-auth/config or something that one can import into next.config.js to have that default config/

```js
// next.config.js

const withNextAuth = require('next-auth/config')

modules.export = withNextAuth({
 // the usual next config can go in here
})
```

This can then under the hood add a rewerite. See copy pasted example from [nextjs blog](https://nextjs.org/blog/next-10-2) below

```js
// next.config.js

module.exports = {
  async redirects() {
    return [
      {
        source: '/:path*',
        has: [
          {
            type: 'header',
            key: 'x-authorized',
            value: '(?<authorized>yes|true)'
          }
        ],
        destination: '/dashboard?authorized=:authorized',
        permanent: false
      }
    ]
  }
}
```

The above example checks for headers, but cookies are also possible.

**Comment by balazsorban44** [comment]
I am aware of this addition to Next.js, but I am not sure what we could do here, to be honest. Our HttpOnly session cookie needs to be verified (if the JWT signature is not tampered with, and in case if it was encrypted, it has to also be decrypted) so merely checking its existence wouldn't be enough to determine if the user is authorized.

Do I misunderstand something?

**Comment by cyrus-za** [comment]
> so merely checking its existence wouldn't be enough to determine if the user is authorized.

I completely agree. But if it does not exist, it is safe to say the user is not authorized and could do with a instant redirect to the login screen without bothering to run any js code

**Comment by balazsorban44** [comment]
I don't think there is point in introducing a new api when you could do this:

```
{​
  ​source​: ​'/:path*'​,​
  ​has​: ​[​{​ 
    type​: ​'cookie'​,
    ​key​: ​''​__Secure-next-auth.session-token",
  }],​
  destination​: ​'/api/auth/session'​,​
  permanent​: ​false​
}
```

Where destination will be tweaked in probably 90% of the cases. I'm happy to accept a note about this somewhere in the docs though. But let's say the cookie was there it was just invalid. You will still need to do the same check as before, so not sure if there is any gain.

**Comment by balazsorban44** [comment]
I won't say that this is the best method, but have a look at my suggestion from a previous issue:

https://github.com/nextauthjs/next-auth/issues/1210#issuecomment-782630909

this will be non-blocking (no getServerSideProps required) but still won't let the user see protected content unless they are authorized. You can expand it to support different roles, show fallback content, a skeleton, a blank page, etc.
