### ISSUE TITLE
Custom signout page url has 'error=undefined' as a querystring param

### ISSUE THREAD

**Issue by anubisoft** [nextauthjs/next-auth#1910]
## Description 🐜
Any custom page that overrides the default signout page shows an "?error=undefined" querystring param when the errors value is undefined (meaning there are no errors)

http://localhost:3000/auth/signout?error=undefined

Looking at the next-auth codebase, specifically the GET handler for 'signout' doesn't appear to check the error variable before outputting it as a querystring param. The GET signin handler does do this.

**Comment by balazsorban44** [comment]
please fill out the template correctly!

**Comment by anubisoft** [comment]
No error is thrown. The bug is about the signout url having an error querystring param for the case where "error" is undefined. The signin case below has logic that checks "error" but the signout case does not (nor does it append callbackUrl).

https://github.com/nextauthjs/next-auth/blob/main/src/server/index.js

```
 case 'signin':
  if (pages.signIn) {
    let signinUrl = `${pages.signIn}${pages.signIn.includes('?') ? '&' : '?'}callbackUrl=${req.options.callbackUrl}`
    if (error) { signinUrl = `${signinUrl}&error=${error}` }
    return res.redirect(signinUrl)
  }
  return render.signin()
case 'signout':
  if (pages.signOut) {
    return res.redirect(`${pages.signOut}${pages.signOut.includes('?') ? '&' : '?'}error=${error}`)
  }
  return render.signout()
```

**Comment by anubisoft** [comment]
The default signout page handling via "render.signout()" does not have the 'error=undefined' param added.

**Comment by balazsorban44** [comment]
I see. Would you be interested in opening a PR with a fix?

**Comment by anubisoft** [comment]
Yes I'll submit a PR with a proposed fix.
