### ISSUE TITLE
Linking OAuth account to combine credentials sign in with google oauth 

### ISSUE THREAD

**Issue by tanyibate** [nextauthjs/next-auth#1915]
Hello, I already have a database in place and managed to implement authentication using Credentials. Now currently I'm trying to implement google auth too. I implemented the default Postgres next auth schema and successfully managed to implement it with the fields I previously had in the users table such as level to represent the number users they referred, referral code, city, and country. I was able to test and successfully authenticate a user using google sign but if a user's google email was already present in the users table instead of letting them sign in using that method it would give me this error 'To confirm your identity, sign in with the same account you used originally. On http://localhost:3000/api/auth/signin?error=OAuthAccountNotLinked#. I'm assuming the account isn't linked with google oauth. How do I go about linking credentials and google oauth?
Below are screenshots of the users table layout in two pics and an example of me signing up using the registration form and another example using google oauth. How do I ag about linking credentials and google oauth?

<img width="1174" alt="Screenshot 2021-05-03 at 13 21 03" src="https://user-images.githubusercontent.com/33326060/116875302-97236480-ac12-11eb-8567-5fdfb19898aa.png">
<img width="1176" alt="Screenshot 2021-05-03 at 13 20 50" src="https://user-images.githubusercontent.com/33326060/116875308-98549180-ac12-11eb-8452-3903aa469ebc.png">
<img width="1153" alt="Screenshot 2021-05-03 at 13 20 36" src="https://user-images.githubusercontent.com/33326060/116875310-98ed2800-ac12-11eb-8701-a8221679a987.png">
<img width="1142" alt="Screenshot 2021-05-03 at 13 20 11" src="https://user-images.githubusercontent.com/33326060/116875311-98ed2800-ac12-11eb-82a0-a72acf21ddba.png">

**Comment by balazsorban44** [comment]
I believe there is a similar discussion in #1002 that might be relevant here. Although, that is a closed PR, so I think this open issue is a more suited place to track further discussions, so I'll leave it open.

**Comment by tanyibate** [comment]
> I believe there is a similar discussion in #1002 that might be relevant here. Although, that is a closed PR, so I think this open issue is a more suited place to track further discussions, so I'll leave it open.

After having a read of similar issues, accounts can not be automatically linked with an OAuth provider how do I go about doing this manually?

**Comment by balazsorban44** [comment]
linking accounts is mostly an automated process, you can see the relevant code here:


https://github.com/nextauthjs/next-auth/blob/17b789822de64eb845e1e8e49ea83dbff56344f4/src/server/lib/callback-handler.js


I haven't used it myself much, but I'll try to read up on it and follow this up as good as I can.

**Comment by zanami** [comment]
@balazsorban44 Do you know how to override that callback handler without forking next-auth?
I'm using a custom credentials provider (email/password) and was hoping to support Google and Email, all 3 linked.

**Comment by balazsorban44** [comment]
you cannot override the source code without forking, sorry. will come back to account linking when we are done with other more important items.

**Comment by emperorgurgeh** [comment]
Bumping up. This creates some pretty bad ux. At a minimum nextauth should allow us to show an error indicating which provider the user had an account with

**Comment by johnmasonwilliams** [comment]
Is there any update on this feature? Automatically linking new provider accounts to the original account via email would be such a level up for next auth.

**Comment by DZuz14** [comment]
Really appreciate the work on this project guys, but the user experience of getting that cryptic error message about a previous account is pretty bad. I'd be glad to help work on fixing this.

**Comment by alemosa** [comment]
Hello, no news about account linking on NextAuth? It would be interesting to at least allow account linking when the user has logged in using credentials and verified his email.

**Comment by steven-tey** [comment]
Hey @emperorgurgeh @johnmasonwilliams @alemosa – you can now do that with the `allowDangerousEmailAccountLinking` option: https://next-auth.js.org/configuration/providers/oauth#allowdangerousemailaccountlinking-option
