### ISSUE TITLE
How can I include user id in session.user?

### ISSUE THREAD

**Issue by madhums** [nextauthjs/next-auth#1921]
I am using `Providers.Email` with jwt. When I do

```js
const [session] = useSession();
```

The session object contains the following __but misses the user `id`__ (which I am in need of)

```js
{
  expires: "2021-06-03T10:38:06.139Z",
  user: {
    email: "kivijis714@httptuan.com",
    image: null,
    name: null
  }
}
```

I see in this PR https://github.com/nextauthjs/next-auth/pull/1725 this was addressed somewhat. I tried using `v4.0.0-next.6` but it doesn't make any difference. 

How can I get the user `id` field in the session?

**Comment by madhums** [comment]
Ok I seem to have found the answer. Using [session callback](https://next-auth.js.org/configuration/callbacks#session-callback)

In `pages/auth/[...nextauth].js`

```js
// using the jwt and session callbacks
  callbacks: {
    async session(session, token) {
      session.user.id = token.sub;
      return session;
    },
  },
```

Using `next-auth@4.0.0-next.6`

**Comment by balazsorban44** [comment]
Should work the same in `latest` as well. We just don't send the ID to the client by default
