### ISSUE TITLE
New session cookie generated every time /session is called

### ISSUE THREAD

**Issue by ramiel** [nextauthjs/next-auth#1934]
## Description 🐜

Everytime the application page is loaded a call to `/session` is done. This sets a new cookie even if the old cookie is not expired. I'm wondering if this behaviour is wrong and no cookie should be set if one valid is already available. Same happens when the session is checked after the setup time interval

## How to reproduce ☕️

You can simply see this happening in the demo app

## Screenshots / Logs 📽

The set-cookie always happens

![Screenshot_20210505_131605](https://user-images.githubusercontent.com/324687/117133084-109e8c80-ada4-11eb-8452-9d7a3d248055.png)

## Environment 🖥

Please run this command:

```
$ npx envinfo --system --binaries --browsers --npmPackages "{next-auth}"
```

  System:
    OS: Linux 5.4 KDE neon 5.21
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 666.77 MB / 15.51 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.1 - /usr/bin/node
    Yarn: 1.22.10 - ~/.npm-global/bin/yarn
    npm: 6.14.12 - /usr/bin/npm
  Browsers:
    Brave Browser: 90.1.23.75
    Chrome: 90.0.4430.93
    Firefox: 88.0
  npmPackages:
    next-auth: ^3.15.5 => 3.15.9 

## Contributing 🙌🏽

It takes a lot of work 🏋🏻‍♀️ maintaining a library like `next-auth`; any contribution is more than welcome 💚

In case you're willing to help fix this bug, please let us know here, and we'll reach you 😊 . Otherwise, you can have a look at the issues labelled with [`"good first issue"`](https://github.com/nextauthjs/next-auth/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) and pick any of them.

**Comment by balazsorban44** [comment]
You have to use some kind of caching for the session. See [Provider](https://next-auth.js.org/getting-started/client#provider)

**Comment by ramiel** [comment]
Thanks for the answer but that probably don't answer the initial question: why a new session is created if the old one is not expired?

**Comment by balazsorban44** [comment]
When you don't cache the response, it means that every call of `useSession` will contact the api.

And the API does update the expiry time as seen here:

https://github.com/nextauthjs/next-auth/blob/main/src/server/routes/session.js

This is to keep your session alive. Happens in both cases when you use JWT or database sessions as well.

**Comment by bfourgeaud** [comment]
Does someone have a sample code to cache the session ? I have not found any viable solution and `set-cookie` is still called at every page load ...
I tried `unstable_cache `from nextjs but nothing improved ...

**Comment by jzzj** [comment]
> Does someone have a sample code to cache the session ? I have not found any viable solution and `set-cookie` is still called at every page load ... I tried `unstable_cache `from nextjs but nothing improved ...

Same issue, have you found any solution?
