### ISSUE TITLE
No title set on main website page

### ISSUE THREAD

**Issue by ajmeese7** [nextauthjs/next-auth#1935]
## Description 🐜

Something is going wrong with the docasaurus build, and the title from `docasaurus.config.js` isn't being applied to the site's index page. I checked this on Brave and Firefox and the issue appeared across both, no `<title>` tag is being set on the page.

## How to reproduce ☕️

Visit [the main website](https://next-auth.js.org/).

## Screenshots / Logs 📽

![no title set](https://user-images.githubusercontent.com/17814535/117145251-90aefd00-ad78-11eb-84bd-433b77b094bd.png)

## Contributing 🙌🏽

It takes a lot of work 🏋🏻‍♀️ maintaining a library like `next-auth`; any contribution is more than welcome 💚

In case you're willing to help fix this bug, please let us know here, and we'll reach you 😊 . Otherwise, you can have a look at the issues labelled with [`"good first issue"`](https://github.com/nextauthjs/next-auth/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) and pick any of them.

**Comment by balazsorban44** [comment]
Hmm, I think you are correct. Same in Chrome. There is an open PR that should upgrade Docosaurus in #1826, but it is currently a draft. Don't know if that would fix anything though.

**Comment by Akhil132-dev** [comment]
I want to work this issue can you please help me how can i start

**Comment by balazsorban44** [comment]
Fixed in #1989
