### ISSUE TITLE
Should `react-dom` be locked to a specific version?

### ISSUE THREAD

**Issue by joshuabaker** [nextauthjs/next-auth#1953]
Unsure if this is a typo or intentional. Should `react-dom` be locked to `16.13.1` instead of `^16.13.1`?

https://github.com/nextauthjs/next-auth/blob/6eb41259d109a56c138d4634a5b501a033a555ea/package.json#L81-L82

Just noticed a warning when upgrading to `16.14.0`.

**Comment by balazsorban44** [comment]
probably a typo, seems it was OK before https://github.com/nextauthjs/next-auth/pull/819/files

would you be interested in opening a PR? 😊

**Comment by lluia** [comment]
I just opened a PR addressing it ☝🏽 😃
