### ISSUE TITLE
Missing User properties on credentials Provider

### ISSUE THREAD

**Issue by yagop** [nextauthjs/next-auth#1959]
## Description 🐜

When using `Providers.Credentials` returned custom User properties are missing.

Only `DefaultUser` properties are preserved.

```ts
// Expected
{ id: 1, name: 'Test' }
// Received
{ name: 'Test', email: null, image: null }
```

## How to reproduce ☕️

We encourage you to use one of the templates set up on **CodeSandbox** to reproduce your issue:

- [`next-auth-example`](https://codesandbox.io/s/pedantic-chebyshev-n50iq?file=/components/header.js)

## Environment 🖥

```
  System:
    OS: Linux 5.11 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 24.46 GB / 31.29 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.15.4 - ~/n/bin/node
    npm: 6.14.10 - ~/n/bin/npm
  Browsers:
    Chromium: 90.0.4430.93
    Firefox: 88.0
  npmPackages:
    next-auth: ^3.13.3 => 3.20.1 
```

**Comment by yagop** [comment]
Hey @balazsorban44 thanks for replying but I already checked the docs... those are either incomplete or misleading

What I think you mean is I would need to implement the `session` callback, right?

But properties are missing there.


```js
export default NextAuth({
  // https://next-auth.js.org/configuration/providers
  providers: [
    Providers.Credentials({
      name: "Test",
      credentials: {
        username: { label: "Username", type: "text", placeholder: "user" },
        password: { label: "Password", type: "password" }
      },
      async authorize(credentials) {
        return Promise.resolve({
          name: "Test",
          id: 444,
          lolol: "lolol"
        });
      }
    })
  ],
  callbacks: {
    async session(session, user) {
      console.log("Session", session);
      // Session { user: { name: 'Test', email: null, image: null },
      console.log("User", user);
     // User { name: 'Test', sub: '444', iat: 1620645203, exp: 1623237203 }
      session.user.id = user.sub;
      return session;
    }
  },
 ```

As you can see, `lolol` property is missing and id has became `sub`.

**Comment by balazsorban44** [comment]
Since you don't seem to use a database, you are using a JWT session. check out the `jwt` callback, in addition to the `session` callback.
