### ISSUE TITLE
Add request object to credentials authorize method

### ISSUE THREAD

**Issue by igordanchenko** [nextauthjs/next-auth#1975]
## Summary 💭

Credentials `authorize` method should have access to the original request IP address.

## Description 📓

Credentials provider `authorize` method currently supplies only username/password as method parameters, and there is no way to obtain the remote IP address of the request. Knowing an IP address is crucial for robust authentication implementation as most authentication backends have IP rate limit filters in place. In most cases an IP address can be obtained from HTTP headers (x-real-ip, x-forwarded-for, etc.) depending on deployment, hence the request to add request object (or at least HTTP headers) to the `authorize` method.

**Comment by igordanchenko** [comment]
I saw that answer, thank you, and it's a terrible one. 
I have described a particular use case for credentials authentication that requires IP address for rate limiting. Your recommendation to look into implementing it somewhere upstream to next-auth makes very little sense as IP rate limiting should be happening downstream at the authentication backend. The ask is pretty simple - expose the request object to `authorize` method. Are there any specific concerns around this?

**Comment by balazsorban44** [comment]
Please don't call anyone's suggestions terrible, unless you pay them for it. 😉

If you want a more elaborate answer, I suggest you fill out the whole feature request template, and do tell if you are interested in contributing with this feature.

I'm curious about your opinion and how have you tried solving this problem or what do you think a shortcoming with your suggestions would be. Whenever we expand the user facing API, there are multiple things to take into consideration, even though it would solve YOUR special usecase.

A suggestion of mine to solve this would be:

```js
// [...nextauth].js

export default (req, res) => {
  if(isIPBlocked(req) {
    res.redirect("/blocked")
  }
  NextAuth(req, res, options)
}
```

Or go even further. If you have access to the hosting service, you could create a rule there to block certain IPs.

I don't say your suggestion is wrong or mine will be good enough for you, but this definitely needs more thinking, and potentially offering a contribution would accelerate the process. 

I'll reopen this at your request, no problem.

**Comment by igordanchenko** [comment]
> Please don't call anyone's suggestions terrible, unless you pay them for it. 😉
Fair enough 

Okay, let me start again. Here is the use case. Credentials provider calls authentication backend with username/password.

```js
Providers.Credentials({
    name: "Credentials",
    credentials: {
        username: {label: "Username", type: "text"},
        password: {label: "Password", type: "password"}
    },
    async authorize(credentials) {
        return axios
            .post(process.env.NEXT_PUBLIC_BACKEND_API + "/signin",
            {
                username: credentials.username,
                password: credentials.password,
            })
            .then((response) => {
                return {
                    id: response.data.sub,
                    role: response.data.role,
                };
            })
            .catch((error) => {
                // custom error handling
                return null;
            });
    }
})
```

Authentication backend has a number of rate-limiting rules in place; some of them are based on IP address. For example, 10 failed login attempts from the same IP would block that IP for 10 minutes (the actual rules are more elaborate). But for that to happen, the backend needs to know the requestor IP. Otherwise, it would eventually block Next.js backend IPs as all authentication API calls originate there. A solution for that would be to pass the IP address as follows:

```js
    async authorize(credentials, request) {  // here we expose the request object to 'authorize' method
        return axios
            .post(process.env.BACKEND_AUTH_API + "/signin",
            {
                username: credentials.username,
                password: credentials.password,
            }, {
                headers: {
                    "x-forwarded-for": obtainIpAddressFromRequest(request), // here we obtain the IP address and forward it to the backend API
                    "x-forwarded-for-trust": process.env.XFF_SHARED_SECRET,
                }
            })
            // ...
```

The suggestion you mentioned above would not work for the following reason:
 - Authentication backend would not know actual IP addresses where authentication calls are coming from and wouldn't know which ones should be blocked.

I hope this clarifies the issue.

**Comment by igordanchenko** [comment]
Yes, it's a custom header so that the Backend API knows that 'x-forwarded-for' actually came from Next.js app, and it can be trusted.

**Comment by ndom91** [comment]
Yeah so while theoretically I'm also for only sending on some sane defaults instead of passing the whole req object - there are so many different headers a user may want I think it makes sense to just pass the whole object. 

For example, the ip address could appear in any of the following headers depending on the web server / setup being used: `X-Forwarded-For-Host`, `X-Forwarded-For`, `Forwarded`, `X-Real-IP`, etc. 

Is there anything else security relevant we should be considering in the req object that is unsafe to pass on?

@igordanchenko if you want to open a PR and If i'm not mistaken, you'll want to take a look here: https://github.com/nextauthjs/next-auth/blob/ca0f4c6fba29dee565fcbeafcb2b8c14bd4448fa/src/server/routes/callback.js#L338-L340

**Comment by igordanchenko** [comment]
> Is there anything else security relevant we should be considering in the req object that is unsafe to pass on?

My preference here is to expose the request object only to Credentials provider since app developer is solely responsible for the `authorize` method code. Passing request object to all providers carries a risk of unintentional sensitive data exposure.

**Comment by dogomedia-github** [comment]
We are also eagerly awaiting this feature. Our use case is obtaining the remote IP (via x-real-ip, x-forwarded-for, etc.) in order to implement IP banning for abuse.

**Comment by balazsorban44** [comment]
Done, check out `3.23.0`! :tada:
