### ISSUE TITLE
Can I make a custom sign in page with SSG instead of SSR?

### ISSUE THREAD

**Issue by adrianfdez469** [nextauthjs/next-auth#2007]
## Question 💬

I have a Next app, and I'm using NextAuth to allow login with several providers. 
I created a custom sign in page (following the [documentation](https://next-auth.js.org/configuration/pages#oauth-sign-in)) but the example there uses SSR, and I want to used with SSG to improve performance and load times. So my question:
- Its possible to create the custom sign in page with Static Site Generation (SSG)?
  - Where can I find an example?
  - Its there something I should know before I use this approach?
Thanks.

**Comment by balazsorban44** [comment]
absolutely. change `getServerSideProps` to `getStaticProps`, and you are done. 😄

**Comment by Zaffer** [comment]
but next removes the api routes when you run `next export` so how can nextauth.js work without the api routes?

**Comment by balazsorban44** [comment]
you are talking about static HTML export, which is a different thing: https://nextjs.org/docs/advanced-features/static-html-export
