### ISSUE TITLE
Next-auth does not store sessions

### ISSUE THREAD

**Issue by AlandSleman** [nextauthjs/next-auth#2010]
## How to reproduce ☕️
I'm using next-auth with Postgres without adapters
I've setup postgresql database with this Schema:
[https://next-auth.js.org/schemas/postgres](https://next-auth.js.org/schemas/postgres)
And i'm using this example:
[https://github.com/nextauthjs/next-auth-example](https://github.com/nextauthjs/next-auth-example)
i just added  NEXTAUTH_URL,SECRET,GOOGLE_ID,GOOGLE_SECRET and DATABASE_URL to the .env file i didn't do any other configuration.

## Description 🐜
I setup google as a sign  in method, After i sign in everything works fine a new account gets stored into the accounts table alongside a new user get stored in the users table.
but the sessions table is empty, the session didn't get stored...
On the client side the user is signed in and the session is stored in  the cookie.

In this tutorial by Leigh Halliday you can clearly see after he signed in the seession gets stored in the database:
[https://youtu.be/3q4BtCzuryY?t=1565](https://youtu.be/3q4BtCzuryY?t=1565)

So what could be the problem? Is it because that he is using prisma? i don't want to use prisma, It should store session either 
Thanks for answering and sorry for my bad english/spelling.

**Comment by balazsorban44** [comment]
Is `jwt` set to `true` in your `session` configuration by any chance? https://next-auth.js.org/configuration/options#session

**Comment by AlandSleman** [comment]
> Is `jwt` set to `true` in your `session` configuration by any chance? https://next-auth.js.org/configuration/options#session
> 
> The example repo you link to explicitly sets it to `true` https://github.com/nextauthjs/next-auth-example/blob/d18e8a7132c139beb3e7693cfee474de12388444/pages/api/auth/%5B...nextauth%5D.js#L61
> 
> Usually, when you use an adapter, it will default to `false`, but the example repo overrides that.
> 
> Just remove `jwt: true`
> 
> I am confident this is the answer, if not, I'll happily reopen this.

Yes it's working fine now after removing `jwt: true`
Thank you so much

**Comment by absamo** [comment]
@balazsorban44 what about if I want to a Providers.Credentials and the new PrismaAdapter from @next-auth/prisma-adapter? jwt:true is required when using signIn callback? So how I can use PrismaAdapter and get the session stored?

**Comment by balazsorban44** [comment]
You can't for the credentials provider. See the docs https://next-auth.js.org/providers/credentials

**Comment by absamo** [comment]
Noted, thanks @balazsorban44 :-)

**Comment by killjoy2013** [comment]
> You can't for the credentials provider (at least not out-of the box). See the docs https://next-auth.js.org/providers/credentials
> 
> We don't plan to change that

So, what would you reccommend to store credential provider's session in database? Using our corporate Active Directory. Can create jwt and use getSession. However, eachtime I call getSession, a new token created. To keep the current token during the session, I need to persist it in a database AFAIK. What would be the best option?

**Comment by balazsorban44** [comment]
I generally don't recommend it, as there are too many foot guns. I am not a security expert so I'm not the right person to ask to begin with, but if you have to ask what's the recommended way, you should probably not implement such a solution either.

If you have a more specific (to your project) question, I recommend opening a discussion instead, with code examples/explanations etc.
