### ISSUE TITLE
nextauth uses an expired access token and doesn't refresh it.

### ISSUE THREAD

**Issue by Pixelatex** [nextauthjs/next-auth#2017]
## Description 🐜

I log in with okta and use the access token to send it to my backend. We noticed that we got a lot of unauthenticated calls after a while.

Once the okta access token expires.. next auth will remain logged in, refreshing the browser doesn't do a thing. So either it's not updating the session with new tokens or next auth is incorrectly allowing the user to remain logged in with an expired token.

## How to reproduce ☕️

leave your user logged in overnight and then try to verify the token manually with okta and you will get the expired errors.

## Environment 🖥

```
  System:
    OS: macOS 11.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 1.99 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.14.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.7.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0.1
    Safari: 14.1
```

**Comment by balazsorban44** [comment]
We currently don't have a built-in token rotation for OAuth providers built-in. You can check out this tutorial to get you started, and see if it helps.: https://next-auth.js.org/tutorials/refresh-token-rotation

**Comment by Pixelatex** [comment]
hang on, so next-auth by default will never ask to re-authenticate a user or refresh tokens? Then how does this thing know to keep a user logged in?

**Comment by balazsorban44** [comment]
No, not for your OAuth providers at least, currently. NextAuth.js can keep track of sessions in two ways. Either using JWT session cookies, or database persisted sessions.

If JWT is used, whenever you ask about the session (`/api/auth/session`, `getSession()`, `useSession()`), the following logic is invoked: https://github.com/nextauthjs/next-auth/blob/main/src/server/routes/session.js

Which will reset the expiry date of the session on the session cookie, and in case of a db session also updates the session expiry in the database. So we do "rotate" our own JWT, but not the one coming from your OAuth provider, currently. I linked to an example of how to do that in my previous comment.


Some relevant documentation:
https://next-auth.js.org/configuration/options#session
https://next-auth.js.org/configuration/options#jwt
