### ISSUE TITLE
Catch without error identifier

### ISSUE THREAD

**Issue by mtt87** [nextauthjs/next-auth#2018]
## Description 🐜

I've started to see these errors reported in Sentry from some Android devices
![Screenshot 2021-05-18 at 10 41 11](https://user-images.githubusercontent.com/2150927/118629889-ed250a00-b7c5-11eb-8e95-7087e359bfaa.png)

So I checked and seems like this try/catch block is missing the error identifier
https://github.com/nextauthjs/next-auth/blob/main/src/lib/logger.js#L78

According to this StackOverflow answer https://stackoverflow.com/a/21624546/2352322
the spec says that the error identifier should be there but some browsers like Firefox/Chrome are happy without it.
Overall it's not advised to do this because other browsers will error and I think that's what is happening here.

## How to reproduce ☕️

This error was reported from a Chrome mobile v62 WebView on Android 11 but I've seen others reported from Samsung browsers as well etc

## How to fix

I think just adding the error identifier in the try/catch should fix this issue
```js
try {

} catch (err) {

}
```

**Comment by balazsorban44** [comment]
According to https://2ality.com/2017/08/optional-catch-binding.html and https://medium.com/@selvaganesh93/javascript-whats-new-in-ecmascript-2019-es2019-es10-35210c6e7f4b this is called an "optional catch binding", and is a living standard since ES2019. If you see an error, there might be an error in our bundling which is odd, because we try to support even IE11 currently! https://github.com/nextauthjs/next-auth/blob/main/config/babel.config.js

**Comment by balazsorban44** [comment]
I am curious, what version of `next-auth` are you using?

**Comment by mtt87** [comment]
I'm using `"next-auth": "3.23.0"`.
I just opened the `logger.js` file in the `dist` folder of `node_modules` that should contain the transpiled code shipped to npm but it looks like it's not transpiled correctly as this is not changed at all
```js
    return clientLogger;
  } catch {
    return _logger;
  }
```

I wonder if it's just adding a quick `(err)` can fix it rather than spending more time to understand why babel/ts are not transpiling this part correctly 😄

**Comment by balazsorban44** [comment]
Well, this is an incorrect way in our bundling, so potentially just working around it may have unintended consequences later on. I see that your suggestion would work with this special use case, but I'm inclined to actually find the source of this issue.

I tested it locally and adding `"@babel/plugin-proposal-optional-catch-binding"` to our plugins list helped, so it looks that maybe the note on https://babeljs.io/docs/en/babel-plugin-proposal-optional-catch-binding saying

> This plugin is included in @babel/preset-env

is not true, or I misunderstand something. I'll investigate.

**Comment by mtt87** [comment]
Good investigation 😄  yes I agree with you that finding the root of the problem would indeed be a better approach than a quick fix 👍

**Comment by mtt87** [comment]
It seems like it is included indeed
https://github.com/babel/babel/blob/main/packages/babel-preset-env/src/available-plugins.js#L14
I also did a quick test
https://babeljs.io/repl#?browsers=defaults%2C%20ie%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=C4JwngBA3gUBEGMD2A7AzkgNgUwHSaQHMAKAcgAttMDSBKGAX0QENgFzo5l0s8CTS2ECCQg6ERkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact&prettier=false&targets=&version=7.14.3&externalPlugins=

If you change target to `not ie 11` you see that it will transpile into `catch (_unused)`

**Comment by balazsorban44** [comment]
This is the target currently:
https://github.com/nextauthjs/next-auth/blob/12517f629b05d3a800759d603a50eb445503349f/config/babel.config.js#L15

What do you mean by setting it to `not ie 11`? It sounds counter intuitive. We do want to transpile to support IE11

**Comment by mtt87** [comment]
Sorry maybe I wasn't clear, I meant that you can try with the Babel repl, check the link and the sidebar
https://babeljs.io/repl#?browsers=defaults%2C%20ie%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=C4JwngBA3gUBEGMD2A7AzkgNgUwHSaQHMAKAcgAttMDSBKGAX0QENgFzo5l0s8CTS2ECCQg6ERkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact&prettier=false&targets=&version=7.14.3&externalPlugins=

![Screenshot 2021-05-18 at 12 28 23](https://user-images.githubusercontent.com/2150927/118643542-9a068380-b7d4-11eb-8b7d-3b634f82f518.png)

**Comment by balazsorban44** [comment]
![](https://i.imgur.com/5ujQoHE.png)

Unfortunately, it did not do the trick.
