### ISSUE TITLE
Google Sign In alway redirect to https://workspace.google.com/products/currents/

### ISSUE THREAD

**Issue by ardiansyaherwin** [nextauthjs/next-auth#2027]
## Description 🐜

Hi,

Currently I'm working on a website that allows user to sign in with Google Sign-in, and I use Google Providers for that.

**Once the setup is done, the Google Sign In works perfectly but for only 1-3 days.**

**But now**, whenever the users do the Google Sign in, once they're successfully login to Google Account, they will be redirected to https://workspace.google.com/products/currents/, and the authentication is failed, no tokens are generated.

Any idea why is this happening? Did I miss something.

Pls note that there is no changes in Google API keys configuration on my account while the error suddenly emerged.

## How to reproduce ☕️

1. Get the secret GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET
2. Create a file under /pages/api/auth/[...nextauth].js
3. In the that file, insert new Google Provider
`Providers.Google({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
      authorizationUrl: 'https://profiles.google.com/o/oauth2/v2/auth? 
      prompt=consent&access_type=offline&response_type=code',
 }),`

4. In the component file, import the function
`import { signIn, getSession } from 'next-auth/client';`
5. the sign in function as follow:
`signIn(providerName, { callbackUrl: router?.query?.callbackUrl || '/' });` 

    

## Environment 🖥
System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz
    Memory: 58.57 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.6.0 - ~/.nvm/versions/node/v15.6.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.4.0 - ~/.nvm/versions/node/v15.6.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 87.0
    Safari: 14.0.3

**Comment by balazsorban44** [comment]
Follow the issue template, or your issue is at risk of being closed.

**Comment by ardiansyaherwin** [comment]
@balazsorban44 I've updated the issue. pls let me know if i missed anything

**Comment by ardiansyaherwin** [comment]
@balazsorban44 I get it fixed simply by comment this line out, wandering if it's the correct way
`// authorizationUrl: 'https://profiles.google.com/o/oauth2/v2/auth?prompt=consent&access_type=offline&response_type=code',`

seems like the `authorizationUrl:` caused this issue

**Comment by balazsorban44** [comment]
authorizationUrl is not mandatory as we set a default for it.

https://github.com/nextauthjs/next-auth/blob/main/src/providers/google.js

glad it worked out
