### ISSUE TITLE
Add more properties to the Session interface

### ISSUE THREAD

**Issue by leduardo99** [nextauthjs/next-auth#2028]
## Question 💬

I would like to add some other properties to the Session interface, however if I add something the default values will disappear.

Make sure you [link]() to external documentation if necessary and provide inline code examples like so:

```js
# next-auth.d.ts
import NextAuth from 'next-auth'

declare module 'next-auth' {
  interface Session {
    user: {
      address: string
    }
  }
}
```

![image](https://user-images.githubusercontent.com/35582603/118766512-e5f80d80-b852-11eb-8eb1-dc5d28a435fc.png)

If I remove the added values, the default value appears again

![image](https://user-images.githubusercontent.com/35582603/118766628-0f189e00-b853-11eb-9439-7045dd6d44ae.png)

`next-auth: ^3.23.1`

**Comment by balazsorban44** [comment]
Yes, this is intentional. If someones decides to override the `Session` it is best to "reset" it. It's harder for someone to remove the unwanted fields than for someone who needs them to add it back.

So you could do:

```ts
import { DefaultSession } from "next-auth"

declare module "next-auth" {
  interface Session {
    user: DefaultSession["user"] & {
      address: string
    }
  }
}
```

This will get you there:
![](https://i.imgur.com/2SsEwqw.png)
