### ISSUE TITLE
UnhandledPromiseRejectionWarning: ReferenceError: log is not defined

### ISSUE THREAD

**Issue by meerbahadin** [nextauthjs/next-auth#2031]
## Description 🐜
Hello, I'm facing this issue with the latest version of next-auth & nodej.js

![carbon (1)](https://user-images.githubusercontent.com/59086176/118865819-0aeb8f80-b8ea-11eb-8593-b4142e53ea26.png)

**Comment by balazsorban44** [comment]
Have you seen the issue template before you posted this? Please fill it out, so we can help you more efficiently. Otherwise, your report is at risk of being closed. Thank you.

**Comment by balazsorban44** [comment]
Did you manage to solve it? I'm curious what the problem was for future reference!

**Comment by meerbahadin** [comment]
Yess! I manage to fix it thanks for the response I faced the issue with placing the code in the issue, the problem was npm cache 
I ran npm clear cache --force fixed the issue and I named the app next-auth in the package.json and i changed the name to something else
