### ISSUE TITLE
Okta Authorization code with PKCE

### ISSUE THREAD

**Issue by Herber230** [nextauthjs/next-auth#2033]
## Question 💬

I am trying to integrate a NextJS application with Okta, using the Authorization code flow with PKCE. The flow is not complete because the token request is not being performed. 

This is the configuration for the provider: 

```
import NextAuth from 'next-auth';

const oktaBaseUrl = 'https://my-okta-domain.com/oauth2/[auth-server-id]';
const clientId = '[My Client Id]';

const authorizationUrl =
  oktaBaseUrl +
  '/v1/authorize?response_type=code&response_mode=query&state=false';

const accessTokenUrl = oktaBaseUrl + '/v1/token';
const profileUrl = oktaBaseUrl + '/v1/userinfo';

export default NextAuth({
  providers: [
    {
      id: 'okta',
      name: 'Okta',
      type: 'oauth',
      version: '2.0',
      protection: 'pkce',
      clientId,
      clientSecret: '',
      accessTokenUrl,
      authorizationUrl,
      profileUrl,
      scope: 'services',
      params: {
        grant_type: 'authorization_code',
      },
      profile(profile) {
        return {
          id: profile.id as string,
          name: profile.name,
          email: profile.email
        };
      }
    }
  ],
});

```

Thefirst stage seems to be perfromed correctly, but when okta returns the code, I only see a message in my application showing an 403 code. It seems it is trying to get the code without perform the request to the token endpoint

![image](https://user-images.githubusercontent.com/24439949/118904820-d8389b80-b8d7-11eb-83d1-af659dfb560f.png)

Message in console: 

```
[next-auth][error][oauth_get_access_token_error]
https://next-auth.js.org/errors#oauth_get_access_token_error { statusCode: 403, data: '' } okta y64EzO0u9ZbwqFdjJWqapXggDmC1bWx2DGQaITCpta4
[next-auth][error][oauth_callback_error]
https://next-auth.js.org/errors#oauth_callback_error { statusCode: 403, data: '' }

```

Is there a configuration I am missing?

**Comment by yuriy-eleks** [comment]
@Herber230 NextAuth already has provider for okta

https://next-auth.js.org/providers/okta

Just integrated, all works well

**Comment by Herber230** [comment]
Hi @yuriy-eleks 

I use this configuration and the error is exactly the same:

```
const oktaBaseUrl = 'https://dev-XXXX.okta.com/oauth2/[server-instance-id]';

const authorizationUrl =
  oktaBaseUrl +
  '/v1/authorize?response_type=code&response_mode=query&state=false';

  Providers.Okta({
      protection: 'pkce',
      clientId,
      domain: 'dev-XXXX.okta.com/oauth2/[server-instance-id]',
      authorizationUrl,
      scope: 'services'
  })
```

I can notice that the code to exchange for tokens is comming from Okta, but then the token request is never performed

![image](https://user-images.githubusercontent.com/24439949/119021867-2b086680-b95d-11eb-9227-6a4f7569c230.png)



Could you please share an example of how to integrate it using PKCE?

**Comment by yuriy-eleks** [comment]
@Herber230 Hello, here is my config

`import {
  SECRET,
  OKTA_CLIENT_ID,
  OKTA_CLIENT_SECRET,
  OKTA_DOMAIN,
  OKTA_SCOPE,
} from '../../../config';

import NextAuth from 'next-auth';
import Providers from 'next-auth/providers';
import { JWT } from 'next-auth/jwt';
import { NextApiRequest, NextApiResponse } from 'next';
import { refreshAccessToken } from '../../../services/okta-api';

const OKTA_AUTHORIZATION_URL =
  `https://${OKTA_DOMAIN}/oauth2/default/v1/authorize?` +
  new URLSearchParams({
    client_id: OKTA_CLIENT_ID as string,
    response_type: 'code',
    scope: OKTA_SCOPE,
  });

export default (req: NextApiRequest, res: NextApiResponse) =>
  NextAuth(req, res, {
    secret: SECRET,
    providers: [
      Providers.Okta({
        clientId: OKTA_CLIENT_ID,
        clientSecret: OKTA_CLIENT_SECRET,
        domain: `${OKTA_DOMAIN}/oauth2/default`,
        authorizationUrl: OKTA_AUTHORIZATION_URL,
      }),
    ],
    callbacks: {
      async jwt(token: JWT, user, account) {
        // Initial sign in
        if (account && user) {
          return {
            accessToken: account.accessToken,
            idToken: account.idToken,
            accessTokenExpires:
              Date.now() + (account.expires_in as number) * 1000,
            refreshToken: account.refresh_token,
            user,
          };
        }

        // Return previous token if the access token has not expired yet
        if (Date.now() < (token.accessTokenExpires as number)) {
          return token;
        }

        // Access token has expired, try to update it
        return refreshAccessToken(token);
      },
      async session(session, token) {
        if (token) {
          session.user = token.user as Record<string, string>;
          session.accessToken = token.accessToken;
          session.error = token.error;
        }

        return session;
      },
    },
    session: {
      jwt: true,
    },
    jwt: {
      secret: SECRET,
    },
  });
`

**Comment by jaydioar** [comment]
From version 3.1 you need to add an '/oauth2' to the domain name to work. 

Providers.Okta({
      clientId: process.env.OKTA_CLIENTID,
      clientSecret: process.env.OKTA_CLIENTSECRET,
      domain: process.env.OKTA_DOMAIN + **'/oauth2'**,
      })

**Comment by JizongL** [comment]
can i ask where do you get the client secret? the current Okta doesn't seem to have any secret provided under the PKCE workflow?

**Comment by Herber230** [comment]
This is the final configuration that worked for me:

```
const oktaBaseUrl = process.env.OKTA_BASE_URL;
const clientId = process.env.CLIENT_ID;
const debugAuth = process.env.DEBUG === 'true';
const authorizationUrl = `${oktaBaseUrl}/v1/authorize?response_type=code&response_mode=query&state=false`;
const accessTokenUrl = `${oktaBaseUrl}/v1/token`;

export default NextAuth({
  debug: debugAuth,
  providers: [
    Providers.Okta({
      protection: 'pkce',
      idToken: true, // IMPORTANT
      clientId,
      authorizationUrl,
      accessTokenUrl,
      scope: 'openid email services',
    }),
  ],
  pages: {
    signIn: LOGIN,
    signOut: LOGIN,
  },
});
```

Two important details:

- It is necessary to set `idToken: true` since a **PKCE** by definition doesn't allow to retrieve data from `/userinfo`. This flow is preferred for public apps and doesn't require a **Client Secret**
- The scope has to include `openid` to enable the `id_token` field in the tokens retrieved. (Okta has to be configured regarding this feature)
