### ISSUE TITLE
Serverless Function Issue

### ISSUE THREAD

**Issue by sarthakagrawal927** [nextauthjs/next-auth#2036]
## Description 🐜

When using an API folder in root directory, the API folder in pages directory is undetected. This is not the usual scenario of NextJS, I have previously used functions from root/api and root/pages/api together. 

## How to reproduce ☕️

Just clone the example project provided by next-auth to test it out. Create api folder in root directory with some function. That function would be working but rest all functions will not.  To run the application in server mode use
```
vercel dev
```

Running application usually (yarn dev), does not all serverless function and hence pages/api is unaffected in that case.
Let me know if there is any issue in reproducing or I lack some information to make this work.

## Screenshots / Logs 📽

![folder](https://user-images.githubusercontent.com/43884471/119011649-e4ddf200-b9b2-11eb-92df-4a8ffe024496.PNG)
![undefined](https://user-images.githubusercontent.com/43884471/119011653-e60f1f00-b9b2-11eb-9a82-60a389e0ce3a.PNG)

## Environment 🖥

```
 System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 3.75 GB / 6.11 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.5 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
```

## Contributing 🙌🏽

It takes a lot of work 🏋🏻‍♀️ maintaining a library like `next-auth`; any contribution is more than welcome 💚

In case you're willing to help fix this bug, please let us know here, and we'll reach you 😊 . Otherwise, you can have a look at the issues labelled with [`"good first issue"`](https://github.com/nextauthjs/next-auth/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) and pick any of them.

**Comment by sarthakagrawal927** [comment]
When I move api from pages to root I get this error:

```
[next-auth][error][missing_nextauth_api_route_error] 
https://next-auth.js.org/errors#missing_nextauth_api_route_error Cannot find [...nextauth].js in pages/api/auth. Make sure the filename is written correctly.
[next-auth][warn][nextauth_url] 
https://next-auth.js.org/warnings#nextauth_url NEXTAUTH_URL environment variable not set
[next-auth][error][missing_nextauth_api_route_error] 
https://next-auth.js.org/errors#missing_nextauth_api_route_error Cannot find [...nextauth].js in pages/api/auth. Make sure the filename is written correctly.
```

Also it would be great if someone could let me know that the error is for me only.

**Comment by balazsorban44** [comment]
The Next.js documentation says:

> In Next.js, a page is a React Component exported from a .js, .jsx, .ts, or .tsx file in the pages directory.

https://nextjs.org/docs/basic-features/pages

Or alternatively:

> src/pages will be ignored if pages is present in the root directory

https://nextjs.org/docs/advanced-features/src-directory

I have never used an API folder directly in the route, but I am almost certain it is not intended. Moving your code into `pages` or `src/pages` will solve the problem.

**Comment by sarthakagrawal927** [comment]
Hi , thanks for looking into my issue.  I am most certainly missing something.

https://vercel.com/docs/serverless-functions/supported-languages

In the note section it says 

> NOTE: In a Next.js application, use /pages/api for Node.js functions and use/api for all other languages. 

And if you look at the attached screenshot that is exactly what I am attempting to do. 

The problem I am facing is when using next-auth, I am not able to use both folders root/api and root/pages/api in production (can't use root/api folder in development so can't tell) for some reason.  When I move next-auth folder to root/api it is not detected. And in production mode when root/api folder kicks in the root/pages/api  (only when next-auth is installed ) is not accessible. 

Like I am able to use in this project:

![Capture](https://user-images.githubusercontent.com/43884471/119092436-13e47a00-ba2c-11eb-9b0f-ccc38db101c6.PNG)

(Both projects have all the latest packages)

Also this is my first issue , so yay. I hope you get a notification for this XD. Also I must say I really like next-auth. You guys have done a great job. 

It would be great  (if this is not an issue) if could tell me the folder structure to use a python serverless function with next-auth. I have tried all possible permutations to make it work.

Regards
Sarthak

**Comment by balazsorban44** [comment]
Unfortunately I still don't think it is an actual problem with NextAuth.js. If your repo is open or you could provide a minimal reproduction, I might be able to help a bit more.

**Comment by sarthakagrawal927** [comment]
Sure I will share the repos: 

Where python serverless function is working (without next-auth)

https://github.com/sarthakagrawal927/next-events

Where python serverless function is not working (with next-auth)

https://github.com/sarthakagrawal927/next-auth-test

If you do not want to go with the hassle with cloning and all I would recommend  just trying to implement a serverless python function alongside nextauth.js.  

Thanks a lot for helping.

**Comment by nodeworks** [comment]
I think the issue here is related to `vercel dev`. You can have an `/api` folder at the root of your project but that should be used if you plan on / are using other runtimes like Go, Python, etc. If you do put this folder at the root of your project it will override the `pages/api` folder. If both exist the root `/api` folder will be used. Other runtimes do not work in the `pages/api` folder.

That being said, NextAuth does not work in the root `/api` folder, it only works in the `pages/api` folder.

**Comment by sarthakagrawal927** [comment]
Aah yes, it is an issue of ```vercel dev``` 

Thanks a lot for pointing this out. I just tested in production again and everything works fine. Now I feel silly creating an issue here. Really sorry should have tested out everything more thoroughly.

**Comment by BirajAd** [comment]
> 

if you are on latest version, you need to use ```[...nextauth].js``` instead of ```[...nextAuth].js``` and if you are wondering what the difference is, its just the latter one has uppercase A and that's all that's what is wrong with it. I hope it solves the problem for you.

**Comment by hassanpasha5630** [comment]
Im having the same issue were you able to figure out a solution
