### ISSUE TITLE
faq: confidential client?

### ISSUE THREAD

**Issue by IntranetFactory** [nextauthjs/next-auth#2045]
> NextAuth.js is designed as a secure, confidential client and implements a server side authentication flow.
   
https://github.com/nextauthjs/next-auth/blob/ad8100d4024071395c36b07abbeee7263f7d1fdf/www/docs/faq.md#L57   
   
From my understanding next-auth supports OAuth2/PKCE flow, which is designed to securely perform the OAuth exchange from public clients.  (see https://oauth.net/2/pkce/). So I'm wondering if my initial understanding of NextAuth.js is wrong, or if the FAQ might be outdated?

**Comment by balazsorban44** [comment]
So, unfortunately, I cannot dig it up from the previous issues, but @iaincollins has answered this before. If I recall it correctly, he explained that theoretically, we wouldn't need to do it, but to be compliant with certain OpenID Connect providers, we chose to implement it anyway. I cannot give you the perfect answer here, but from the link you provided, you can see that using PKCE won't harm you even if the client is confidential:

> It was originally designed to protect mobile apps, but its ability to prevent authorization code injection makes it useful for every OAuth client, even web apps that use a client secret.

**Comment by balazsorban44** [comment]
Here is a pretty good article explaining some of the protection mechanisms, also PKCE specifically with confidential clients: https://danielfett.de/2020/05/16/pkce-vs-nonce-equivalent-or-not/

> ...With PKCE, the same protection as for public clients kicks in: The attacker cannot use the code himself and cannot inject the code into a client, as there is not session where the client would use the correct code_verfier except the session between the user’s browser and the client.
