### ISSUE TITLE
Credentials AND Session Token

### ISSUE THREAD

**Issue by teamgigify** [nextauthjs/next-auth#2056]
## Question 💬

Hey all and I love Next auth, but there is one thing.
I am trying to make credentials an option on my site ( since the password less way is not my fave ) but it only allows for JWT kinda thing. I really really hate jwt. 

Is there a way I can manipulate next auth to let my create a session (with a session id) that then references back to the user object in mongodb? - basically how passport works with connect-mongo

Thankssss :)

## How to reproduce ☕️

Try making sessions with credentials...

**Comment by balazsorban44** [comment]
https://next-auth.js.org/providers/credentials

> The functionality provided for credentials based authentication is intentionally limited to discourage use of passwords due to the inherent security risks associated with them and the additional complexity associated with supporting usernames and passwords.
