### ISSUE TITLE
Change table names using the TypeORM adapter

### ISSUE THREAD

**Issue by oldo** [nextauthjs/next-auth#2060]
Hi there,

I'd like to use some different table names than the ones provided by the SQL that generates `accounts`, `users`, `verification_requests`, etc. This is because I'd like to use the table name `accounts` for something other than oauth accounts.

Currently I'm using the TypeORM adapter and I've been able to succesfully extend the User schema to include columns that are not in the default `users` table. I've taken the same approach to try and modify the accounts schema and setting `name` to `UserOauthAccount` in the hope that it then uses the table that I've created: `user_oauth_accounts`, however it doesn't seem to make a difference.

Is there a way that I can modify the TypeORM adapter to use custom table names?

**Comment by balazsorban44** [comment]
I see you have already asked this here:

https://github.com/nextauthjs/next-auth/discussions/2050

Please don't open issue duplicates.

**Comment by oldo** [comment]
Sorry about that @balazsorban44 
Definitely poor form on my behalf and obviously not the right way to go about getting assistance.
