### ISSUE TITLE
Invalid `Error()` call in src/providers/email.js

### ISSUE THREAD

**Issue by emrysal** [nextauthjs/next-auth#2077]
Observation whilst browsing the code, the following line is invalid, it didn't cause any error as I was just browsing but this will cause confusing behaviour whilst encoutering errors using the email provider:

https://github.com/nextauthjs/next-auth/blob/0392a8df9a4a1dd825067732f2227acfa84d58a4/src/providers/email.js#L47

**Comment by balazsorban44** [comment]
Could you elaborate more (please use the provided issue templates)? If you refer to the double arguments passed to Error, yes it isn't supposed to be there, but it shouldn't cause any actual problems. The error will be logged with logger anyway.

**Comment by emrysal** [comment]
@balazsorban44 I know, this was more as an informative FYI, not actually something you need to address now (or even in the future), but thought it at least worth reporting.

**Comment by balazsorban44** [comment]
Totally! Thanks! You could open a PR cleaning this up, that would be no problem. 😊
