### ISSUE TITLE
If user exists, but not account, add it on login

### ISSUE THREAD

**Issue by btmorex** [nextauthjs/next-auth#2084]
## Summary 💭

If a user exists, but an account for the user doesn't, it would be nice if it was added on the first login. Currently, I get an error "Please login to the original account you logged in as".

## Description 📓

The use case for this is creating seed data during development. A lot of my tables depend on user, so I have to seed a user, but I'd rather not check in login credentials by seeding an account too. Instead it would be nice if logging in as the user (same email) would create a corresponding account.

**Comment by balazsorban44** [comment]
Please fill out the template in a more detailed manner, also indicate if you are willing to work on this.
