### ISSUE TITLE
callbackUrl parameter does not work with Apple Signin

### ISSUE THREAD

**Issue by pedrojpj** [nextauthjs/next-auth#2089]
## Description 🐜

By adding a callback url in the signIn with apple like this:

`onClick={() => signIn("apple", { callbackUrl: 'url' })}`

On the first call, this url is received, but on Apple's return it is lost and redirected back to the original url.

**Comment by balazsorban44** [comment]
please don't skip the template.

**Comment by quypb** [comment]
@pedrojpj same issue with me.

**Comment by balabeir** [comment]
How can I do with this problem?

**Comment by guswls1846** [comment]
help me..
