### ISSUE TITLE
127.0.0.1 and localhost are treated as different URLs if you set your NEXTAUTH_URL to localhost

### ISSUE THREAD

**Issue by QuaKe8782** [nextauthjs/next-auth#2094]
## Description 🐜

If I sign in on `http://localhost:3000`, and it's the `NEXTAUTH_URL` that's set in `.env.local`, and I open a tab and go to `127.0.0.1:3000`, Next Auth behaves as if they are two different users.

## How to reproduce ☕️

Set your NEXTAUTH_URL to localhost, sign in on localhost and then go to `127.0.0.1`.

## Screenshots / Logs 📽

N/A

## Environment 🖥

```  
  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 24.11 GB / 31.94 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.964.0), Chromium (91.0.864.37)
    Internet Explorer: 11.0.19041.1
```

## Contributing 🙌🏽

N/A

**Comment by balazsorban44** [comment]
not sure what you mean by two different users, but it is certainly two different urls. you can set either, but it will only work for that one.

**Comment by ntalamdotcom** [comment]
The bug is still alive
