### ISSUE TITLE
getSession in ssr sent undefined!

### ISSUE THREAD

**Issue by Radmehr-aghdam** [nextauthjs/next-auth#2118]
## Description 🐜

Hi, I'm using Next-Auth in Nextjs project.
Next-auth connected to db with prisma.

Every thing was working but suddenly getSession in ssr sent undefined!
I'm refreshed the page but session not set. This problem shown after login Specifically !

 package.json list:
    "next": "^10.2.0",
    "next-auth": "^3.24.1",
    "react": "17.0.2"
    "@prisma/client": "^2.22.1",

and the code:

```
import { signIn, signOut, useSession, getSession } from 'next-auth/client'
...
export async function getServerSideProps({ ctx }) {

    const session = await getSession(ctx)
    if (!session) {
        return {
            redirect: {
                permanent: false,
                destination: '/auth/signin'
            }
        }
    } else {
        console.log(session.user.name)
    }
```

output:
`TypeError: Cannot read property 'user' of null`

**Comment by balazsorban44** [comment]
please provide a whole reproduction. the code you are showing doesn't make sense. if you check session existence in the if condition, in your else block, it is no way that session is `null`

**Comment by Radmehr-aghdam** [comment]
this is the all code of a test page and 

```
import {useSession, getSession } from 'next-auth/client'

const test = () => {

    const [session] = useSession()
    console.log("client==> " + session.user.name)
    
    return (
        <div>
            Enter
        </div>
    );
}

export default test;


export async function getServerSideProps({ ctx }) {

    const session = await getSession(ctx)
    console.log("SSR ==> " + session.user.name)

return{
    props:{
        
    }
}
}
```

![ksnip_20210603-002815](https://user-images.githubusercontent.com/73892124/120544407-a3156880-c402-11eb-9be6-2b88b55cc828.png)

**Comment by balazsorban44** [comment]
In case the user is not logged in, session will be `null`, so you have to have some kind of a check on line 23, eg `session?.user.name` to safely use session. Or use an if statement, as you did in your first example.

There is nothing for us to do here, it is not a bug in `next-auth`. If you need further assistance, please open a question in our Discussions section: https://github.com/nextauthjs/next-auth/discussions

**Comment by Radmehr-aghdam** [comment]
After the logging this problem created!
I can get session in client in test page but I cant get session in server!
If I use getSession in serverside, client side sesssion change to null too on test page, BUT I can get client session on other pages!

It's so strange and make not sense!

**Comment by Radmehr-aghdam** [comment]
FIXED!
I used `session?.user.name` in Client and used `req` instead of `ctx` or `context` in serverside.

I don't know why this happen but I want to tell you that you can help others if this issue happen!

Thanks for answering!
