### ISSUE TITLE
Remove DynamoDB from docs

### ISSUE THREAD

**Issue by manishprivet** [nextauthjs/next-auth#2122]
## Description 🐜

The DynamoDB adaptor for next-auth is completely broken and should be removed from the docs.

## How to reproduce ☕️

Please refer https://github.com/nextauthjs/adapters/issues/125 for details

## Screenshots / Logs 📽

N/A

## Environment 🖥

N/A

## Contributing 🙌🏽

I'm willing to fix this by using [TypeDORM](https://github.com/typedorm/typedorm), which is a well maintained ORM for DynamoDB, and will create PR soon in the adaptors repo.

**Comment by balazsorban44** [comment]
Let's keep this separate in the other issue you opened. 😉
