### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/lib/errors'

### ISSUE THREAD

**Issue by taylorpreston** [nextauthjs/next-auth#2128]
## Question 💬

I'm not sure if this is a question or an issue, but here we go 🚗 🔥 

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/lib/errors' is not defined by "exports" in blah /blah/node_modules/next-auth/package.json

I'm not totally sure what the issue is here, but errors don't seem to be exported correctly

Bellow is a screenshot of the next auth package.json in my project.
![Image 2021-06-03 at 9 30 14 PM](https://user-images.githubusercontent.com/14971676/120736999-e7604180-c4b2-11eb-9dc8-29a47ee28550.jpg)

```

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/adapters/issues?q=is%3Aissue+err+is%3Aclosed+

**Comment by vladimir-e** [comment]
I know it's not directly related, but if someone is trying to solve the following error in `4.0.0-beta.6`:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './providers/cognito' is not defined by "exports" in ...
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './providers/credentials' is not defined by "exports" in ...
```

Check you node version, it should be ^12.22.0

> which is the first version of Node.js with native ES Modules support.

as I accidentally found in [nextjs 12 upgrade guide](https://nextjs.org/docs/upgrading#upgrading-from-11-to-12)


To the maintainers:
do you think it's worth mentioning node requirement on the [main page](https://next-auth.js.org/getting-started/introduction)?

**Comment by balazsorban44** [comment]
yes we could add a note.

We only have this info in the source code right now, I believe https://github.com/nextauthjs/next-auth/blob/f998bf27688deb2197550448ee49bc4faf93de49/config/babel.config.js#L1-L3

Feel free to open a PR at https://github.com/nextauthjs/docs
