### ISSUE TITLE
verifyBeforeUpdateEmail

### ISSUE THREAD

**Issue by edgarasben** [nextauthjs/next-auth#2133]
## Summary 💭
Send a verification email, before updating an existing email.

## Description 📓

It often happens in applications that users want to change their email address. Maybe they want to use another email address for a particular app, or maybe they have a new email. Or sometimes that's an easy way to transfer account to somebody else.

Currently in Next Auth there is no way (as far as I know) to send a verification email to a new address, before overriding the old email.

Firebase has a feature called verifyBeforeUpdateEmail which does pretty much what I am describing

https://firebase.google.com/docs/reference/js/firebase.User#verifybeforeupdateemail:
```js
firebase.auth().currentUser.verifyBeforeUpdateEmail(
  'user@example.com', actionCodeSettings)
  .then(function() {
    // Verification email sent.
  })
  .catch(function(error) {
    // Error occurred. Inspect error.code.
  });
```

## Contributing 🙌🏽

I would like to contribute to this feature, but I don't have enough understanding at this point how Next Auth works. However, this is how I think the algorithm should work:

1. User types new email to an input
2. Email verification is sent.
3. User clicks the verification link.
(Here I think we could update the database schema to have a relation between the User and VerificationRequest)
4. If VerificationRequest has a relation to existing user, AND the VerificationRequest email address is different from the current email address in User table then we can update the current email address with the new email address.
5. The user should be redirected back to the page where the request was sent from and we should display a message "Your email was updated".

**Comment by edgarasben** [comment]
Does anybody know if there was any progress on this, or there is an alternative way to achieve similar?

**Comment by zrthomas** [comment]
I am also looking for a solution to this issue.
