### ISSUE TITLE
Cannot succesfully login with twitter and `next-auth-example` 

### ISSUE THREAD

**Issue by wack-overflow** [nextauthjs/next-auth#2142]
## Description 🐜

I am struggling to successfully login with the twitter provider using the `next-auth-example` project.

## How to reproduce ☕️

1. I clone the `next-auth-example` repo
1. I set up `.env.local` with the correct `TWITTER_ID` and `TWITTER_SECRET`, and set `NEXTAUTH_URL=http://127.0.0.1:3000`.  I have verified several times that there are no newline or other unexpected characters in these values.
1. I set up my twitter callback url with `http://127.0.0.1:3000/` as follows: 
![image](https://user-images.githubusercontent.com/83986403/121122425-acc21600-c7de-11eb-8945-8351032d69bd.png)
1. I run the app and navigate to `http://127.0.0.1:3000`, then click the "Sign In" button, then click the "Sign in with Twitter" button.
1. I can see a `POST` request being made to `http://127.0.0.1:3000/api/auth/signin/twitter` with what appear to be correct `csrfToken` and `callbackUrl` in the form data as follows:

![image](https://user-images.githubusercontent.com/83986403/121123311-40481680-c7e0-11eb-93f4-c3dbaeced65a.png)

1. However, it gives me an error "Try signing into a different account", and I can see the dreaded "Callback URL not approved" error in my terminal:

![image](https://user-images.githubusercontent.com/83986403/121123462-7f766780-c7e0-11eb-97be-478b1ae22c14.png)

## Screenshots / Logs 📽

**Help us help you**. We can address the bug you found much faster if you provide contextual screenshots or screen recordings showcasing the issue.

See [Kap](https://getkap.co/) for a good, easy-to-use, cross-platform screen recording tool.

## Environment 🖥

Please run this command:

```
$ npx envinfo --system --binaries --browsers --npmPackages "{next-auth}"
```

and paste the output here.

System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 83.79 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 90.1.24.84
    Chrome: 91.0.4472.77
    Firefox: 88.0.1
    Safari: 14.1.1
    
    
Any help is greatly appreciated! Thank you!

**Comment by balazsorban44** [comment]
This is due to the fact that the you did not configure your Twitter app correctly. The url you should be setting is `http://127.0.0.1:3000/api/auth/callback/twitter`
