### ISSUE TITLE
How to send callbackUrl in email link

### ISSUE THREAD

**Issue by lionelrudaz** [nextauthjs/next-auth#2143]
## Question 💬

In my app, I'd like to invite new user from an admin interface, then onboard them. 

In other words, I'm trying to signIn() a new user by sending a new URL by email. The user needs to land on a specific on boarding URL.

The thing is that when I specify callbackUrl as an option, it's saved in the cookies of the current user, but it won't get available in the link sent to the invited user.

Do you know a way to do that? Or to have some options in the send verification method? 

## Contributing 🙌🏽

If the solution doesn't exist, I can help creating a pull request.

**Comment by ahmadigbaryia** [comment]
I have a similar problem, I'm using Email provider for authentication.
customers can login at any point of the application, and I want them to be redirected to the same point when they decided to login.

I've added a callbackUrl in the querystring, for OAuth providers it works, but for Email it doesn't.

**Comment by ahallora** [comment]
You could do 

```javascript
signIn("email", {
   email: "user@email.com",
   callbackUrl: "https://the.url.you/want/your/user/to/land/on/once/validated"
}
```

**Comment by lionelrudaz** [comment]
I believe that's what I did, but it wasn't working. Was there any updated in the meantime that could have fixed that?

**Comment by ahallora** [comment]
Ahhh, so you want to change the link in the verification email to contain more than just the user-email and verification-token. Yeah, I want that too actually, but haven't found a way yet.

I've come some of the way by being able to override the generated HTML, by setting `sendVerificationRequest` according to this: https://next-auth.js.org/providers/email#customising-emails 

```js
Providers.Email({
  server: process.env.EMAIL_SERVER,
  from: process.env.EMAIL_FROM,
  sendVerificationRequest: customVerificationRequest,
}),
```

But I'm still unable to actually pass parameters (e.g. my own JWT) to the customVerificationRequest function. Perhaps if we could wrap `export default NextAuth({...})` and grab the `NextApiRequest` before returning NextAuth-default behaviour, we could probably intercept and add the required parameters to the sendVerificationRequest...

I've tried like this:

```js
export default async (req: NextApiRequest) => {
  console.log("nextauth query", req.query);
  return NextAuth({...});
}
```
... but it didn't work and logs out this:

```
nextauth query { nextauth: [ 'session' ] }
API resolved without sending a response for /api/auth/session, this may result in stalled requests.
```

We might come up with a way together!? 😄 🙈

**Comment by balazsorban44** [comment]
@ahallora you can do:

```js
export default async (req, res) => {
 nreturn NextAuth(req, res, options
}
```

😊

**Comment by ahallora** [comment]
@balazsorban44  oh man, you're the best 😄 🙌 Thank you. 

So, I got my locale sent to the sendVerificationRequest like this:

```ts
export default async (req: NextApiRequest, res: NextApiResponse) =>
  NextAuth(req, res, {
    providers: [
      Providers.Email({
        server: process.env.EMAIL_SERVER,
        from: process.env.EMAIL_FROM,
        // @ts-ignore
        sendVerificationRequest: async ({
          identifier,
          url,
          baseUrl,
          token,
          provider,
        }) => {
          const locale = (req?.query?.locale || "") as string;
          return await customVerificationRequest({
            identifier,
            url,
            baseUrl,
            token,
            provider,
            locale, // <-- oh baby 
          });
        },
      }),
    ],
  });
```

And that's how you can carry the locale, callbackUrl or whatever out and into the verification email. 

The last piece in the puzzle, getting the verification link to actually route properly, I would look into the `redirect` callback in next-auth, perhaps something like this (NOT TESTED): 

```js
    callbacks: {
      redirect: async (url) => {
        const newUrl = new URL(url);
        const redirectUrl = newUrl.searchParams.get("my_email_callbackUrl") || url;
        return Promise.resolve(redirectUrl);
      },
```

Let me know how it goes, @lionelrudaz . 🙏

**Comment by balazsorban44** [comment]
No, problem. 😁 Obviously this can be (and hopefully will be) improved in the future, so such workarounds won't be necessary. But it is a totally valid workaround IMO. NextAuth is not magic, just an API route handler. 🙂

**Comment by balazsorban44** [comment]
@lionelrudaz 


What you are describing is onboarding, in which case you can use the `pages.newUser` option:
https://next-auth.js.org/configuration/options#pages

Would that help? 

So after some digging, it looks like `callbackUrl` does only work if the user clicks the link in the same browser as where they started:

https://github.com/nextauthjs/next-auth/blob/main/src/server/routes/callback.js#L294-L303

This is because validating the callbackUrl uses cookies:

https://github.com/nextauthjs/next-auth/blob/17b789822de64eb845e1e8e49ea83dbff56344f4/src/server/lib/callback-url-handler.js

**Comment by ahallora** [comment]
Like I did above with locale I'm also doing with callbackUrl. You can add `callbackUrl` to the email token link, and it will work without cookies (so you can request a  token from a PC and get a working sign-in-link with proper callback when clicking on it from another device).

So in my `customVerificationRequest` function I simply override the `url` and append the `callbackUrl` querystring property:
```js
const urlWithCallback = `${url}&callbackUrl=${callbackUrl}`;
//...
return `<a href="${urlWithcallback}">Sign in</a>`
```

And voila, it works. 😎

**Comment by balazsorban44** [comment]
Not sure if that has any security issues though. Our callbackUrl runs through a validation before being used. Using the built-in `pages.newUser` option might be safer.

**Comment by ahallora** [comment]
@balazsorban44 , if you verify the redirect with the baseUrl it should be fine. And also works on subsequent logins for not new users. 😄

**Comment by balazsorban44** [comment]
Hopefully @lionelrudaz is happy with that solution. If not, I will reopen this.

**Comment by lionelrudaz** [comment]
Thanks all of you for your replies, that helped a lot.

**Comment by dan-kwiat** [comment]
@ahallora you're right you can put a callback url in the query string of the verification link using a custom `sendVerificationRequest`. That gives you a verification link structured like this:

```bash
https://example.com/api/auth/callback/email?email=me@gmail.com&token=abcd&callbackUrl=https://example.com/somewhere/special
```

But have you tested the second part i.e. retrieving the query string parameter inside the `redirect` callback? I don't think that function ever gets called with the verification link href, since the link is not considered a redirect url.

**Comment by dan-kwiat** [comment]
Update: it turns out `callbackUrl` in the query string is already respected by NextAuth internally, so all that's needed to fix the cross-device issue is to include `callbackUrl` in the query string.

**Comment by jasondainter** [comment]
I am attempting to do something similar to this (ultimately I am trying to send the user to a custom URL after they have clicked the email provider "magic link" URL) and wondered if someone could kindly confirm if these customisations involving a wrapper like below are still necessary. I see this thread is a bit old and wondered if there was a better way or should I go down this path still?

> @ahallora you can do:
> 
> ```js
> export default (req, res) => {
>   return NextAuth(req, res, options)
> }
> ```
> 
> 😊

**Comment by lionelrudaz** [comment]
Hey @jasondainter, here's the code I'm using for the EmailProvider.

```
export const authOptions: NextAuthOptions = {
  // Configure one or more authentication providers
  providers: [
    EmailProvider({
      server: process.env.EMAIL_SERVER,
      from: process.env.EMAIL_FROM,
      async sendVerificationRequest({
        identifier,
        url,
        token
      }) {
        try {
          /* your function */
          const magicLinkReq = await fetch(`${process.env.TASTERS_API_HOST}/magic_links`, {
            method: 'POST',
            headers: {
              'Content-Type': "application/json"
            },
            body: JSON.stringify({
              email: identifier,
              url,
              token: token
            })
          })

          const magicLink = await magicLinkReq.json();
        } catch (e) {
          console.log(e);
          throw new Error("Magic link can't be sent:" + e);
        }
      },
    })
    // ...add more providers here
  ],
```

As you can see, I'm sending the email with my own API method, and the URL is part of the payload.

Works like a charm.
