### ISSUE TITLE
Cookie “next-auth.session-token” is ignored due to reaching max size limit

### ISSUE THREAD

**Issue by Firas-Al-Azizy** [nextauthjs/next-auth#2145]
## Cookie “next-auth.session-token” is ignored due to reaching max size limit 💬

In the repository [strapi-nextauth-template](https://github.com/osmarpb97/strapi-nextauth-template), the author  integrated Next-Auth with Strapi Jwt and used the local Starpi Postgres database to be able to keep persistent the accounts of users, but in my Next-js Strapi web application I separated the front-end from the back-end into different repositories and deployed the Strapi back-end to Heroku, so I took the connection string to the Postgres database that is located in Heroku, then I assigned it to the database property in [...nextauth.js] file, the site worked fine until I got this error

>  ( Set-Cookie header is ignored in response from URL: http://localhost:3000/api/auth/callback/credentials?. Cookie length should be less than or equal to 4096 characters )

I discoverer that there was no connection, so when I deleted the database property in [...nextauth.js] the site did not throw any error and worked with Strapi Jwt storing in the Cookie “next-auth.session-token” but it says that it reached its max size, then the login page redirects you to the login page, not allowing you to sign in to the site.

**Comment by balazsorban44** [comment]
I'm not even sure what is the question here. Browsers do have a general 4096bytes cookie limitation, we cannot do much about it. You have to make sure that if you use the JWT session flow, you don't exceed this. Otherwise, you will need to use a database to persist your sessions.

https://next-auth.js.org/faq#what-are-the-disadvantages-of-json-web-tokens

**Comment by Firas-Al-Azizy** [comment]
Thanks for responding, but how can I connect my next app to the Postgres database hosted in Heroku, which I use for my Strapi backend also ?

**Comment by Firas-Al-Azizy** [comment]
Thanks for being rude to me while I am only seeking help ????!!!!!
