### ISSUE TITLE
Doesn't provide `@prisma/client` peer dependency

### ISSUE THREAD

**Issue by nicholaschiang** [nextauthjs/next-auth#2147]
## Description 🐜

Please provide a clear and concise description of the bug in NextAuth.js.

🚧 – _Do not report bugs with your own project here; ask for help [by raising a question instead](https://github.com/nextauthjs/next-auth/issues/new?assignees=&labels=question&template=question.md) - this helps us a lot with administration overhead._

When installing with Yarn v2 (with PNP enabled), I get a warning:

> next-auth@npm:3.25.0 [01e23] doesn't provide @prisma/client (p90d0c), requested by @next-auth/prisma-legacy-adapter

## How to reproduce ☕️

We encourage you to use one of the templates set up on **CodeSandbox** to reproduce your issue:

- [`next-auth-example`](https://codesandbox.io/s/next-auth-example-1kktb)
- [`next-auth-typescript-example`](https://codesandbox.io/s/next-auth-typescript-example-se32w)

🚧 – _If you don't provide any way to reproduce the bug, the issue is at risk of being closed._

1. Create a new Next.js project: `yarn create next-app`
2. Install this package: `yarn add next-auth`
3. See warning message

## Screenshots / Logs 📽

**Help us help you**. We can address the bug you found much faster if you provide contextual screenshots or screen recordings showcasing the issue.

See [Kap](https://getkap.co/) for a good, easy-to-use, cross-platform screen recording tool.

See the last command run in the following screenshot:

![image](https://user-images.githubusercontent.com/20798889/121238580-1bd65380-c84d-11eb-9355-c4d4375d2915.png)

## Environment 🖥

Please run this command:

```
$ npx envinfo --system --binaries --browsers --npmPackages "{next-auth}"
```

and paste the output here.

```
npx: installed 1 in 1.222s

  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
    Memory: 13.60 GB / 15.46 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 2.4.2 - ~/.nvm/versions/node/v12.18.3/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
```

## Contributing 🙌🏽

It takes a lot of work 🏋🏻‍♀️ maintaining a library like `next-auth`; any contribution is more than welcome 💚

In case you're willing to help fix this bug, please let us know here, and we'll reach you 😊 . Otherwise, you can have a look at the issues labelled with [`"good first issue"`](https://github.com/nextauthjs/next-auth/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) and pick any of them.

**Comment by balazsorban44** [comment]
You have to install `@prisma/client`

**Comment by nicholaschiang** [comment]
@balazsorban44 that's not the issue here. This package (`next-auth`) should specify that `@prisma/client` is a peer dependency so that it's descendant can access it in Yarn PNP. If I install `@prisma/client` at a workspace level, `@next-auth/prisma-legacy-adapter` (which I'm assuming is a dependency listed on `next-auth`) won't be able to access it in Yarn PNP.

Specifying `@prisma/client` as a peer dependency is required for `next-auth`. I will get the same warning, but it'll be the correct one (i.e. something like "`tutorbook@workspace` doesn't provide `@prisma/client` as requested by `next-auth`").

**Comment by balazsorban44** [comment]
`next-auth` does not depend on `@prisma-client` though, `@next-auth/prisma-legacy-adapter` does. And as you can see it here:
https://github.com/nextauthjs/adapters/blob/4961e43c72d2dfe21ff43726f066b7240dedfb56/packages/prisma-legacy/package.json#L37

It is defined as a peer dependency.

Historically, we had some hiccups before with Yarn 2 PnP. From what I could gather than, Yarn 2 walks its own path handling things a bit differently than others, so I am not sure how to assist here, I have never used it myself. Doesn't seem to be a problem with other tools.
See also: https://github.com/nextauthjs/next-auth/pull/1034

**Comment by nicholaschiang** [comment]
Doesn't `next-auth` list `@next-auth/prisma-legacy-adapter` as a dependency though? Because if it does, then it's up to `next-auth` to either include all of `@next-auth/prisma-legacy-adapter`'s peer dependencies or list them as peer dependencies itself.

**Comment by balazsorban44** [comment]
Still doesn't explain why does it work with any other tools? I tried with NPM 6, 7, and even Yarn 1.

Is it an actual error (meaning you cannot run code with it), or only producing a warning while installing?

**Comment by nicholaschiang** [comment]
@balazsorban44 Yarn v2 with PNP is fundamentally different from all those other tools: https://yarnpkg.com/features/pnp

**Comment by balazsorban44** [comment]
My point. As mentioned earlier, we did have problems with this before and as then, I don't think we wish to use our efforts on this now either. Feel free to open a PR with a proposed fix, and I can try to discuss it with another maintainer later on, but as a heads up, it won't be prioritized as seemingly anything else works with the current implementation, and `next-auth@4` (hopefully coming this summer) will make this redundant anyway, as you will always have to install adapters directly you rely on.

**Comment by nicholaschiang** [comment]
No problem! Yeah, I've started using `node_modules` anyways because of vercel/next.js#25869.
