### ISSUE TITLE
Custom field input before signIn

### ISSUE THREAD

**Issue by cloudagon** [nextauthjs/next-auth#2149]
## Question 💬

How do I provide a custom field before `signIn`? I want all my users to have unique usernames so they can easily be identified, but this is not possible with the current information. I want them to input a username before clicking signIn, but I'm not sure what to do from there. How do I get it into my database? I'm using the [Prisma adapter](https://www.npmjs.com/package/@next-auth/prisma-adapter) if it matters.

**Comment by balazsorban44** [comment]
Possible duplicate of #1069
