### ISSUE TITLE
Auth0 Provider: Obtain JWT access instead of opaque accessToken

### ISSUE THREAD

**Issue by ysahnpark** [nextauthjs/next-auth#2157]
## Summary 💭

Add additional parameter in Auth0 provider options so it returns JWT accessToken instead of the default opaque accessToken.

## Description 📓

By default the Auth0 returns an opaque accessToken (see this [article](https://auth0.com/docs/tokens/access-tokens/get-access-tokens), also the [API doc](https://auth0.com/docs/api/authentication#authorization-code-flow)). To obtain JWT accessToken, during the authorization flow, `audience` parameter should be added with the Management API v2 identifier.

The following modification to the `provides/auth.js` is a simple implementation of this feature

```js
...
function Auth0(options) {
  // Add following line to include the audience param
  const extraAuthParam = options.audience ? `&audience=${options.audience}`: '';
  return {
    id: "auth0",
...
    accessTokenUrl: `https://${options.domain}/oauth/token`,
    // Modify the following line to include the audience parameter.
    authorizationUrl: `https://${options.domain}/authorize?response_type=code${extraAuthParam}`,
    profileUrl: `https://${options.domain}/userinfo`,
...
```

Then in my `[...nextauth].js` I can have:
```js
const options = {
  providers: [
    Providers.Auth0({
      clientId: process.env.AUTH0_CLIENT_ID,
      clientSecret: process.env.AUTH0_CLIENT_SECRET,
      domain: process.env.AUTH0_DOMAIN,
      audience: process.env.AUTH0_AUDIENCE,  // Yay this works! It returns JWT accessToken
    }),
...
```

- **Purpose of the feature**: When using Auth0, obtain JWT accessToken instead of opaque token.
- **potential problems**: None
- **potential alternatives**: In the sample code above, instead of `audience`, it could be generalized using an object, and then create a querystring out of it.

**Comment by balazsorban44** [comment]
You can easily override any of the parameters, so this should work:

```js
Providers.Auth0({
  //...
  authorizationUrl: `https://${process.env.AUTH0_DOMAIN}/authorize?${new URLSearchParams({
    response_type: "code"
    audience: "your audience"  
  })}`,
})
```

This is basically a one-liner on the user's side, so I don't think we need to do any changes. I advocate for keeping as few one-off provider options as possible. as `audience` would be unique for Auth0, I don't think we should add this.

#1846 could provide much more flexibility.

Closing this, as in the proposed form, I don't want us to implement this.
