### ISSUE TITLE
Unable to connect: app redirects to url api/auth/signin/facebook showing an empty screen

### ISSUE THREAD

**Issue by ziedHamdi** [nextauthjs/next-auth#2177]
## Description 🐜

I'm trying to run the code sample in https://next-auth.js.org/ 

My code here:
**pages/_app.js**
```
import {ApolloProvider} from '@apollo/client'
import {useApollo} from '../apollo/client'
import {Provider} from 'next-auth/client'

export default function App({Component, pageProps}) {
    const apolloClient = useApollo(pageProps.initialApolloState)

    return (
        <ApolloProvider client={apolloClient}>
            <Provider session={pageProps.session}>
                <Component {...pageProps} />
            </Provider>
        </ApolloProvider>
    )
}

```

**pages/index.js** 
```
import {
    useSession, signIn, signOut
} from 'next-auth/client'

export default function Component() {
    const [ session, loading ] = useSession()
    if(session) {
        return <>
            Signed in as {session.user.email} <br/>
            <button onClick={() => signOut()}>Sign out</button>
        </>
    }
    return <>
        Not signed in <br/>
        <button onClick={() => signIn()}>Sign in</button>
    </>
}
```

**pages/api/auth/[...nextauth].js**
```
import NextAuth from 'next-auth'
import Providers from 'next-auth/providers'

export default NextAuth({
    // Configure one or more authentication providers
    providers: [
        Providers.Facebook({
            clientId: process.env.FACEBOOK_ID,
            clientSecret: process.env.FACEBOOK_SECRET
        }),
        // ...add more providers here
    ],

    // A database is optional, but required to persist accounts in a database
    database: process.env.DATABASE_URL,
})
```
**.env**
```
# Secrets like the one below should go into `.env.local` instead to avoid pushing
# them to a repository, this is an exception for the sake of the example
TOKEN_SECRET="this-is-a-secret-value-with-at-least-32-characters"
FACEBOOK_ID="51...40"
FACEBOOK_SECRET="93d0...860"
DATABASE_URL="mongodb://localhost:27017/weally"
NEXTAUTH_URL="localhost:3000"
```
🚧 – _Do not report bugs with your own project here; ask for help [by raising a question instead](https://github.com/nextauthjs/next-auth/issues/new?assignees=&labels=question&template=question.md) - this helps us a lot with administration overhead._

## How to reproduce ☕️
Clicking on **SignIn** I'm redirected to a generated page with the facebook SignIn button at [http://localhost:3000/api/auth/signin?callbackUrl=http%3A%2F%2Flocalhost%3A3000%2F](http://localhost:3000/api/auth/signin?callbackUrl=http%3A%2F%2Flocalhost%3A3000%2F)

But when I click on the "Sign In with facebook" button, I'm redirected to the url [https://localhost:3000/api/auth/signin/facebook](https://localhost:3000/api/auth/signin/facebook) which is a blanc page with the ERR_CONNECTION_CLOSED error

When I tried to log in from a "private navigation browser", I didn't reach the facebook page that asks me to "allow" the app to access my data. It seams the error is even before reaching out to the provider

I also noticed this warning when I install packages: 
warning "next-auth > @next-auth/prisma-legacy-adapter@0.0.1-canary.127" has unmet peer dependency "@prisma/client@^2.16.1". (why would I need prisma to call facebook?)

Please note that the [`next-auth-example`](https://codesandbox.io/s/next-auth-example-1kktb) you provide gives an error message on facebook login : Internal Server Error

## Screenshots / Logs 📽
Nothing in logs

## Environment 🖥

Please run this command:

```
$ npx envinfo --system --binaries --browsers --npmPackages "{next-auth}"
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 2.37 GB / 11.90 GB
  Binaries:
    Node: 14.16.1 - D:\dev\nodejs\node.EXE
    Yarn: 1.22.5 - D:\Programs\Yarn\bin\yarn.CMD
    npm: 6.14.12 - D:\dev\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.77
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.48)
    Internet Explorer: 11.0.19041.1

## Contributing 🙌🏽

It takes a lot of work 🏋🏻‍♀️ maintaining a library like `next-auth`; any contribution is more than welcome 💚

In case you're willing to help fix this bug, please let us know here, and we'll reach you 😊 . Otherwise, you can have a look at the issues labelled with [`"good first issue"`](https://github.com/nextauthjs/next-auth/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) and pick any of them.

**Comment by ndom91** [comment]
Hi ziedHamdi, thanks for writing up such a detailed issue! So a few things here..

1. Which version of `next-auth` are you using exactly? And which other packages did you install? Did you install the prisma adapter?
2. I see you're specifying a mongodb database string. We don't support mongodb as an adapter directly, only through the `typeorm-adapter`, so if you want to persist users in a mongodb database, yuo'll have to install and use the typeorm adapter. If you just want to get a quick example up and running without persisting users to a database, i.e. simply authenticate them via facebook, I suggest you not passing a database string at all and falling back to jwt's (just remove the `database: process.env.DATABSEURL` part in your `pages/api/auth/[...nextauth].js`).
3. Finally, the `NEXTAUTH_URL` in your `.env` should always be specified with the protocol prefix, i.e. `http://localhost:3000`

Let us know if that gets you up and running, if not we can take a closer look again depending on which version your using, etc. :tada:

**Comment by balazsorban44** [comment]
Quick correction of @ndom91 here, currently we DO support mongodb connection strings as the OP did it. 😊

**Comment by ziedHamdi** [comment]
Hi Nico and Balazs, 

Thanks for guiding me, things were fixed by updating the NEXTAUTH_URL with the protocol

I'd consider it as a bug since it all fails silently: I think there should be a validation of the NEXTAUTH_URL  variable, or at least an error saying the lib couldn't connect to the specified url.

It works for me with the db Balazs. What would be great would be to allow the community to add a plugin that completes needed information in the saved user (eg: friends, interests etc...: i'm doing it manually for each platform)

Being able to link different accounts to the same user would be great too.

Thanks for the great lib anyway

**Comment by balazsorban44** [comment]
Glad that it worked out!

We currently only check for the existence of the `NEXTAUTH_URL` variable:

https://github.com/nextauthjs/next-auth/blob/5a89ab69d3ceee2f84b683b6fa67455126f80815/src/server/index.js#L20-L22

We could either extend this validation or make the `parseUrl` function smarter to be able to handle URLs without the protocol. https://github.com/nextauthjs/next-auth/blob/main/src/lib/parse-url.js.

Looking at the code, I think we do a bit of too much string magic in `parseUrl`. We could probably utilize the [`URL`](https://developer.mozilla.org/en-US/docs/Web/API/URL) constructor for parsing.
