### ISSUE TITLE
Custom _app and getServerSideProps

### ISSUE THREAD

**Issue by geekus** [nextauthjs/next-auth#2187]
## Question 💬

I think the docs may be a bit misleading on how to do session checks for all pages. In [this section](https://next-auth.js.org/getting-started/client#provider) they suggest using `getServerSideProps` in `_app`, while the [NextJS docs in this section](https://nextjs.org/docs/advanced-features/custom-app#caveats) states that `getServerSideProps` does not work with custom `_app` file. From my experience the suggested approach in the NextJS Auth docs does not work.

Could I be doing it wrong, or am I correct in assuming the suggested approach in NextJS Auth docs will not work. If so they should be changed.

**Comment by PaulPCIO** [comment]
I don't think the docs are suggesting using `getServerSideProps` in the `_app`. 

If you look above the code block in the docs, it shows an example which is being used in `pages/index.js`, remember any props passed down from a SSR function in your pages will also be available in `_app.js` under `pageProps

If you would like to do it globally you could use the `getInitialProps` in the `_app`. You can do the following, but this disables the ability to perform automatic static optimization.

```js
import App from 'next/app'
import { Provider, getSession } from 'next-auth/client'

export default function MyApp({ Component, pageProps }) {
  return (
    <Provider session={pageProps.session}
      options={{
        clientMaxAge: 60     // Re-fetch session if cache is older than 60 seconds
        keepAlive:    5 * 60 // Send keepAlive message every 5 minutes
      }}
      >
      <Component {...pageProps} />
    </Provider>
  )
}

// Only uncomment this method if you have blocking data requirements for
// every single page in your application. This disables the ability to
// perform automatic static optimization, causing every page in your app to
// be server-side rendered.
MyApp.getInitialProps = async (appContext) => {
   // calls page's `getInitialProps` and fills `appProps.pageProps`
   const appProps = await App.getInitialProps(appContext);
   const session = await getSession(appContext.ctx)
   return { ...appProps, session }
}
```

**Comment by balazsorban44** [comment]
I think the OP is right in that the phrasing in the docs is a bit unfortunate, and not clear:
> This only works on pages where you provide the correct pageProps, however. This is normally done in getInitialProps or getServerSideProps like so:
```js
// pages/index.js
import { getSession } from "next-auth/client"

...

export async function getServerSideProps(ctx) {
  return {
    props: {
      session: await getSession(ctx)
    }
  }
}
```

If every one of your pages needs to be protected, you can do this in _app, otherwise you can do it on a page-by-page basis. Alternatively, you can do per page authentication checks client side, instead of having each auth check be blocking (SSR) by using the method described below in alternative client session handling.

Hence I am happy to accept a clarification PR for this, to make it more explicit that it i

**Comment by matteoturini** [comment]
I think that it's pretty clear in the docs, it's written on the getServerSideProps snippet the name of the file: pages/index.js.
