### ISSUE TITLE
[Provider: FusionAuth] Add `secure` configuration option to specify HTTP/HTTPS

### ISSUE THREAD

**Issue by bharatkashyap** [nextauthjs/next-auth#2193]
## Summary 💭

Addition of an additional `secure` (or some such) configuration option for the FusionAuth provider for users to be able to specify protocol type.

## Description 📓

While developing locally, for a FusionAuth instance installed locally, the path is invariably `http://localhost:9011`; while the provider definition [file](https://github.com/nextauthjs/next-auth/blob/main/src/providers/fusionauth.js) specifies `https` in the definition itself, like so:

```js
export default function FusionAuth (options) {
 let authorizationUrl = `https://${options.domain}/oauth2/authorize?response_type=code`
 ...
```

Instead of trying to setup SSL for localhost (painful), I got around this by modifying the definition in this file in my `node-modules`, but I thought this could trouble potential other adopters as well.

Willing to implement a simple fix which modifiers the code like so:

```js
export default function FusionAuth (options) {
 let authorizationUrl = `http${options.secure ? 's': ''}://${options.domain}/oauth2/authorize?response_type=code`
 ...
```

**Comment by balazsorban44** [comment]
So as mentioned in the docs, you can override any of the options, the one you refer to are only the built-in ones. See

https://next-auth.js.org/providers/fusionauth#options
