### ISSUE TITLE
Set idToken for cognito provider as true by default

### ISSUE THREAD

**Issue by shriah** [nextauthjs/next-auth#2211]
## Summary 💭

Set idToken for cognito provider as true by default

## Description 📓

Cognito provider currently does not set `idToken` option to `true` even though Cognito supports it. This limits the profileData that is available for use. Setting the `idToken` to `true` enables access to lot more information from cognito which is available in the token and avoids a network call in getting the limited profile data. This does not break the existing implementation since data returned by the network call is a subset of data returned by `id_token`.

`idToken` is set to `true` by default in only one provider (Apple). 

- **purpose of the feature**
Avoid a network call and potentially get more data in the profile of the user by setting `idToken` to `true` by default 
- **potential problems**
None that I am aware of
- **potential alternatives**
An addition in Cognito provider doc to mention that `idToken` is supported and the potential to get more data by setting it true

**Comment by balazsorban44** [comment]
So as I tried to pinpoint in #2202, although this is not the default setting for the [`Cognito provider`](https://next-auth.js.org/providers/cognito#options), you can certainly set it like this:

```
import Providers from `next-auth/providers`
...
providers: [
  Providers.Cognito({
    clientId: process.env.COGNITO_CLIENT_ID,
    clientSecret: process.env.COGNITO_CLIENT_SECRET,
    domain: process.env.COGNITO_DOMAIN,
    idToken: true
  })
]
...
```

I have nothing against setting it by default either, but if we do, it would be good to know why this wasn't set by the creator of the provider in the first place. I see it was @LoriKarikari, let us see if we get an answer.

In any case, you can utilize the `idToken` as mentioned above. :slightly_smiling_face:

**Comment by shriah** [comment]
I figured this setting after debugging the internal of next-auth. Being new to both Cognito and next-auth, I was not aware of this token or the setting.

If there is any hesitation to add this as a default in the code. I think documenting this in the Cognito provider will help someone like me out.

**Comment by balazsorban44** [comment]
It is documented, please see the link I just sent jn my previous comment.

A list of overrideable options for OAuth providers can also be found here:

https://next-auth.js.org/configuration/providers#options

If you have a suggestion on how we could make this more clear, please tell us. 😊

**Comment by shriah** [comment]
I feel adding the suggestions directly under the provider documentation will make this more clearer. In the current documentation for provider options mentions that `idpToken` is valid for supported providers , not the specific providers that support this options which would be more useful.

**Comment by balazsorban44** [comment]
We support a large amount of providers out of the box, and unfortunately we cannot keep track of all of them and their supported functionality over time. (We would like to make this a bit better by setting up some basic tests, so we know at least the login flow works as expected. Will work on this with @lluia at some point), so we rely on the community to keep those and their documentation as up to date as possible. As I said, if you have a suggestion please tell us, preferably open a PR with your precise suggestion, so we can review it.
