### ISSUE TITLE
Custom cookie creation (size limitation workaround)

### ISSUE THREAD

**Issue by digitalhank** [nextauthjs/next-auth#2213]
## Summary 💭

Due to the size limitations of cookies, i cannot store both the refresh & access token i am receiving from Cognito in the session cookie. It would be incredibly favourable if the library allowed you to a create cookies arbitrarily so that i for instance, could store the refresh token inside a separate cookie.

Edit - i realize this is fairly trivial to implement yourself but it would be nice if the library offered this feature oob.

**Comment by balazsorban44** [comment]
Thank you for this issue. To overcome this, currently you could utilize a database adapter. We offer quite a few options:

https://next-auth.js.org/adapters/overview

Would be also interesting to know if you are interested in creating a PR for this with your ideal implementation? 🙂

**Comment by mtt87** [comment]
Out of curiosity how long are the cognito `access_token` and `refresh_token`?
I'm using another oAuth provider and I can easily fit both in the session cookie to be honest.

**Comment by digitalhank** [comment]
@balazsorban44 thank you but unfortunately our service does not store any data.

**Comment by digitalhank** [comment]
@mtt87 refresh token is about 1700 b and the session token, which consists of a few profile properties & the access token is around 1850. total size is below chrome's limit but the browser was still printing warnings.

**Comment by balazsorban44** [comment]
would be interesting to know what is inside the access token? We use IdentityServer 4, and by not adding identity claims to the access token, we could spare a lot of space.

**Comment by digitalhank** [comment]
see here - https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-the-access-token.html

**Comment by dennervidal** [comment]
@digitalhank can you share your current solution for this? I'm facing the same issue using keycloak provider

**Comment by digitalhank** [comment]
@dennervidal something like this 

`import NextAuth from 'next-auth'
import Cookies from 'cookies'

const setRefreshCookie = ({ cookies, refresh_token }) => {
    const date = new Date()
    const time = date.getTime()
    const expireTime = time + 24 * 60 * 60 * 1000 * 30 // 30 days
    date.setTime(expireTime)

    cookies.set('refresh_token', refresh_token,
        {
            sameSite: 'strict',
            overwrite: true,
            expires: date,
            httpOnly: true
        })
}

const Auth = (req, res) => {
    const cookies = new Cookies(req, res)

    return (
        NextAuth(req, res, {
            secret: process.env.JWT_SECRET,
            callbacks: {
                async session(session, token) {
                    if (token) {
                        session.user.last_name = token.last_name
                        session.user.first_name = token.first_name
                        session.user.role = token.role
                        session.access_token = token.access_token
                        session.error = token.error
                    }

                    return session
                },
                async jwt(token, user, account, profile) {
                    if (profile) {
                        token.last_name = profile['custom:last_name']
                        token.first_name = profile['custom:first_name']
                        token.role = profile['custom:role']
                    }

                    if (account) {
                        token.access_token = account.access_token
                        token.accessTokenExpires = Date.now() + account.expires_in * 1000

                        setRefreshCookie({ cookies, refresh_token: account.refresh_token })
                    }

                    if (Date.now() < token.accessTokenExpires) {
                        return token
                    }
                }
            },
            providers: [
                Providers.Cognito({
                    clientId: process.env.COGNITO_CLIENT_ID,
                    clientSecret: process.env.COGNITO_CLIENT_SECRET,
                    domain: publicRuntimeConfig.COGNITO_ENDPOINT,
                    session: {
                        maxAge
                    }
                })
            ]
        })
    )
}


export default Auth
`

**Comment by mtt87** [comment]
Out of curiosity how do you refresh the token? Doesn’t seem like you handle it in the code posted here

**Comment by digitalhank** [comment]
yeah i removed it for brevity. my refreshAccessToken function is quite similar to the docs

**Comment by mtt87** [comment]
OT have you ever experienced issues with refresh token rotation? We are working on fixing some stuff but would be curious to hear if you ever noticed any issue with your cognito setup
https://github.com/nextauthjs/next-auth/issues/2071

**Comment by digitalhank** [comment]
Not yet. My implementation is fairly new so it hasn't been thoroughly tested yet. I can report back if anything unexpected happens.

**Comment by indianabenny** [comment]
Hi @digitalhank. I'm running into the same issue. Thank you for posting your code example above. I'm new to Next.js. Would you mind posting a quick example of how you are calling Auth in your code? Are you even using the [...nextauth].js with a <Provider> setup in _app.js or are you handling that in some other manner?

**Comment by digitalhank** [comment]
@indianabenny the only significant difference between how it's invoked in the docs and my implementation is that I am wrapping the NextAuth function with my own as you can see above.

**Comment by dennervidal** [comment]
This workaround is pretty neat actually. I've been working with keycloak auth services, and had to apply this in my app to work properly. Only thing I say to you who had the same problem using JWT is to pay attention on session time and cookie expiration. In order to auto refresh the tokens, set the provider options.

I think this should be considered in future versions of next-auth, since not every JWT is short enough to fit in a cookie.

**Comment by indianabenny** [comment]
See another example here for how this can be solved:
https://stackoverflow.com/a/68181560/16337541

**Comment by thetaPC** [comment]
This is still an issue.
