### ISSUE TITLE
NextAuth should not invalidate the client-side session when the browser is offline

### ISSUE THREAD

**Issue by igordanchenko** [nextauthjs/next-auth#2215]
## Description 🐜

NextAuth invalidates the client-side session when the browser is offline and the NextAuth client cannot communicate with the NextAuth backend. From an application perspective, the expectation is that the NextAuth library must provide the last-known session state unless session TTL runs out or the NextAuth client receives an authoritative response from the NextAuth backend.

## How to reproduce ☕️

```
git clone https://github.com/nextauthjs/next-auth.git
cd next-auth 
cp app/.env.local.example app/.env.local 
npm install
npm run dev:setup
npm run dev
```

- Open http://localhost:3000/protected in Chrome
- Sign In with credentials using "password" as password
- Observe that the page says "This is protected content. You can access this content because you are signed in."
- Open Chrome dev tools Network tab and select the "Offline" mode
- Minimize the browser window
- Restore the browser window
- Observe that the page says "Access Denied. You must be signed in to view this page"

## Screenshots / Logs 📽

Logs in browser console:
```
react_devtools_backend.js:2560 [next-auth][error][client_fetch_error] 
https://next-auth.js.org/errors#client_fetch_error session TypeError: Failed to fetch

asyncToGenerator.js?1da1:6 Uncaught (in promise) TypeError: Failed to fetch
```

## Environment 🖥

```
  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 1.37 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.1 - /usr/local/bin/node
    npm: 6.14.13 - ~/Temp/next-auth/node_modules/.bin/npm
  Browsers:
    Chrome: 91.0.4472.106
    Firefox: 89.0
    Safari: 14.1.1
```

## Contributing 🙌🏽

I'm more than happy to author a PR but I'm just not sure about the logic behind https://github.com/nextauthjs/next-auth/blob/5a89ab69d3ceee2f84b683b6fa67455126f80815/src/client/index.js#L106 Is there any specific reason to force clientMaxAge=0 session re-validation on keep-alive timer or visibilitychange events? IMO clientMaxAge=0 session must be presumed valid unless the backend says the session is no longer valid (which would be triggered by 'storage' event).

**Comment by balazsorban44** [comment]
Hi there, I wouldn't flag this as a bug, more of an enhancement. The thing you experience happens, because we re-fetch the session when the tab/window gets focused. Currently this behavior cannot be turned off, but in v4, there will be an option for it. See #

**Comment by igordanchenko** [comment]
Thanks for pointing me to that enhancement. However, the more I think about this, the stronger I feel that current behavior is incorrect. And to be clear, my main concern is with the way NextAuth handles network failures / offline mode and not the 'visibilitychange' event. 

Let's imagine you have an email client app that uses the following session settings:
```
clientMaxAge: 120,
keepAlive: 5,
```
These settings establish the following contract:
a) let's use session data on the client for up to 120 minutes before considering it stale
b) and also let's ping the server every 5 minutes to renew the session and reset the 120-minute rolling window

But what is happening is that NextAuth evicts client-side session data even when a single keep-alive call to the server fails and returns no fresh data.

Now imagine you are commuting to work by train reading emails, and all of a sudden, your favorite email app tells you "Hey, your session is no longer good, and you need to sign in again" all just because the train went through a tunnel and you were offline for couple minutes. This is a bad user experience in my books, and I do not see a clear way for an app developer to work this around unless NextAuth correctly handles failed keep-alive / session refresh calls.

What are your thoughts on this?

**Comment by igordanchenko** [comment]
Here is a PR that I believe addresses this issue.

**Comment by balazsorban44** [comment]
Thank you for your detailed example. I can see how it would be a problem, but I still think that any request to a new session should invalidate the old one as well. Let's say the session contains an `access_token` that is about to expire, and that is why you set up polling, so it gets refreshed before expiry. Now if the refresh fails and you are stuck with the old token, you might risk unauthenticated calls to your APIs.

This problem can be worked around in user land in my opinion. You could set up an event listener for network changes, and whenever you experience that the network is unavailable, you could clear the polling by setting `keepAlive` to 0.

Suggestion for `_app.jsx`:

```jsx
import * as React from "react"
import { Provider } from "next-auth/client"

function useOnlineStatus() {
  const [online, setOnline] = React.useState(() => navigator.onLine)

  React.useEffect(() => {
    const goOnline = () => setOnline(true)
    const goOffline = () => setOnline(false)
    window.addEventListener("online", goOnline)
    window.addEventListener("offline", goOffline)
    return () => {
      window.removeEventListener("online", goOnline)
      window.removeEventListener("offline", goOffline)
    }
  }, [])

  return online
}

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}) {
  const isOnline = useOnlineStatus()
  return (
    <Provider keepAlive={isOnline ? 5 * 60 : 0}>
      <Component {...pageProps} />
    </Provider>
  )
}
```

**Comment by igordanchenko** [comment]
> Thank you for the PR, although I am going to close this for now.

>First of all, we are in the process of releasing a new major version (v4), and the client code has been refactored significantly on the next branch. Any significant changes should therefore be made against the next branch. (See the new client code at: https://github.com/nextauthjs/next-auth/blob/next/src/client/react.js)

I'm more than happy to create a PR against the v4 branch as the code change would be pretty much identical. 

> Furthermore, I am not really sure about this proposal. If there is a network error while fetching the session, then there is a big chance that this network error will propagate through the app, thus keeping the old session wouldn't be that useful, in my opinion.

And that's exactly what's happening because NextAuth Provider is sitting at the top of the components tree in the _app.js, and triggers a re-render of the whole app when session state changes. It is entirely legit behavior when the session state changes (a user signs in or signs out in another tab), but it's not quite logical when an opportunistic keepAlive call fails due to network or server error. Maybe we are treating keepAlive calls differently. In my view, keepAlive calls are opportunistic "heartbeats" that are meant to renew session expiration TTL and fetch an updated session state if it changes. But it's totally okay to skip some heartbeats when the user is offline. For example, users would expect their email client app or book reading app to stay open and mounted in the browser when they briefly go offline.

Would you be more open to adding a configuration option that would define keepAlive semantic and allow it to work both ways?

**Comment by igordanchenko** [comment]
Thank you for the creative proposal utilizing navigator.onLine. However, it can't reliably cover all possible use-cases of why keepAlive call may fail. Think of a network issue anywhere between your router and Next backend server (your direct ISP or any intermediate ISP), or intermittent issue with the backend server itself causing it to respond with 500 error. navigator.onLine would miss this kind of issue, but keepAlive call would still fail.

**Comment by igordanchenko** [comment]
> Let's say the session contains an access_token that is about to expire, and that is why you set up polling, so it gets refreshed before expiry. Now if the refresh fails and you are stuck with the old token, you might risk unauthenticated calls to your APIs.

In this case I would setup keepAlive interval of at least 1/10th of access_token TTL, and if it happens that all 10 heartbeats couldn't reach the server then I would deal with the expired access token on the application level (and it would be much easier problem to solve rather than not being able to differentiate user sign out vs failed keepAlive call as both flip the session to null)

**Comment by balazsorban44** [comment]
Thanks for the additional info. You bring up logical reasons, so I am willing to give in, but I would like someone else's opinion on the matter.

Would be nice to check how others have implemented this:

- SWR by Vercel: https://swr.vercel.app/docs/revalidation#revalidate-on-interval / https://swr.vercel.app/docs/options#options (`refreshWhenOffline`) If I want to read into it, I would say they implemented it the way I described (disabling polling when offline by default)
- React Query: https://react-query.tanstack.com/reference/useQuery I cannot find it directly, but it seem to have these more granular options as well (different settings to handle offline/online changes etc).

Before opening a new PR, would you be up to creating a small codesandbox.io example using `swr` and `react-query` to see how they behave? I am happy to accept your proposal if any of these keep the stale data around on failed polling requests, as they are well established solutions and I trust them more than my word on this matter.

**Comment by igordanchenko** [comment]
Here is code sandbox example using swr and react-query - https://gxoks.sse.codesandbox.io/

With both libraries the app stays mounted and displays previously fetched data.

**Comment by anguskeatinge** [comment]
Some options to handle offline-ness would be pretty helpful.
A few of my users have complained about being sporadically logged out when they are on patchy internet.

I ended up solving this with useSWR https://github.com/nextauthjs/next-auth/issues/596#issuecomment-760251882

**Comment by TimNZ** [comment]
@igordanchenko I'm still on v3 and need to handle offline robustly, please hook me up with your patch package

**Comment by igordanchenko** [comment]
@TimNZ, here you go.

patch-package: https://gist.github.com/igordanchenko/554f1572da8f24611adfa8960d2774b0#file-next-auth-3-29-10-patch

yarn patch: https://gist.github.com/igordanchenko/554f1572da8f24611adfa8960d2774b0#file-next-auth-npm-3-29-10-12aff06fed-patch

**Comment by TimNZ** [comment]
@igordanchenko [spends 20 mins going down the rabbit hole of patch-package and figuring out a patch file name that works 😅 ]
Thanks!  Got it applying.
<img width="379" alt="image" src="https://user-images.githubusercontent.com/1051701/184552142-4218bda9-13e0-405b-ae36-f2036602a805.png">

But it doesn't work as I expected.

My goal in applying that patch was to stop useSession() clearing the session on an offline/internet disconnected scenario as discussed above.
I simulated an 'offline' in Chrome DevTools, did tab changes to trigger 'visibilitychange' to error next-auth, and then went 'online', and the session was still null.

My _app.tsx usage

```
        <NextAuthProvider
          options={{
            clientMaxAge: 10, // parseInt(process.env.THISAPP_NEXTAUTH_CLIENT_CACHE_SECONDS), // Re-fetch session if cache is older than 10 seconds
            keepAlive: 300, // parseInt(process.env.THISAPP_NEXTAUTH_CLIENT_KEEPALIVE_SECONDS) // Send keepAlive message every 5 minutes
          }}
        >
```

What should I be doing?

**Comment by igordanchenko** [comment]
I'm pretty sure the behavior you are seeing is cause by `clientMaxAge: 10`. You are basically instructing next-auth to use the cached session object for up to 10 seconds, so the above patch won't be of much help (unless you go offline and back online within under 10 seconds)

Here is the logic implemented in this patch:

```jsx
const newClientSessionData = await getSession(
  { triggerEvent: !triggeredByStorageEvent },
  // fail over to the current session if the update wasn't triggered by a storage event or max age timeout
  !triggeredByStorageEvent && (clientMaxAge === 0 || currentTime < clientLastSync + clientMaxAge) ? clientSession : null
)
```

**Comment by TimNZ** [comment]
Yeah I think that too.

I set it to 0 after I commented and will probably leave it that way for now until I feel like reassessing the implications around freshness of client data in the UI.

**Comment by igordanchenko** [comment]
I've updated my project to next-auth@4.10.3 today, and unfortunately, v4 handles unreliable network conditions even worse than v3. It takes just one `/api/auth/session` network request to fail, and next-auth flips the session to null and completely stops trying to re-fetch the session (even when `refetchInterval` is defined).

Here is an updated patch for v4: https://gist.github.com/igordanchenko/e1e40c2da14ccdc2823c7fc31a5b2de2

Installation:
1) Download the patch file as `./patches/next-auth+4.10.3.patch`
2) Follow the patch-package installation instructions - https://www.npmjs.com/package/patch-package

Patch source code: https://github.com/igordanchenko/next-auth/commit/0918a5fbbfd7e11e9d0996fe49ccf27cd81ab375

**Comment by ajaykarthikr** [comment]
@balazsorban44 Is a fix planned for this issue?

**Comment by Sliffcak** [comment]
Same issue. Following!

**Comment by jozefhruska** [comment]
@Sliffcak Since I last commented on this issue, a new `refetchWhenOffline` option has been added (https://github.com/nextauthjs/next-auth/issues/4935#issuecomment-1185695446). Could you try setting this to `false` and see if it helps?

**Comment by igordanchenko** [comment]
@jozefhruska, the `refetchWhenOffline` option does an excellent job at hiding this issue in most cases, but it doesn't eliminate it since it doesn't fix the root cause. It just makes this issue less frequent but even more challenging to reproduce and troubleshoot, which is a poor customer experience in my books.

Here is a simple demo illustrating this issue - https://pnlkxs-3000.preview.csb.app ([source code](https://codesandbox.io/p/sandbox/next-auth-2215-1-pnlkxs))

1) Open the test page
2) Click the "Sign In" button
3) Sign in with any username and password
4) Wait till the countdown timer is about to hit 0
5) Switch your phone into airplane mode or kill the wi-fi on your laptop (you may need to repeat this step several times to catch the bug)
6) Observe the session state flipped to "unauthenticated"
7) Bring your device back online
8) The session state remains "unauthenticated"

**Comment by nfadili** [comment]
Running into this as well using next-auth 4.24.5 - the patch discussed above seems like reasonable behavior for SessionProvider to have but has fallen out of date and is a brittle long term solution.. Has anyone solved this problem in another way or have a more recent issue open with next-auth regarding this? I've poked around a bit but haven't seen anything 😬

**Comment by igordanchenko** [comment]
Well, it's been almost 3 years with no alternative solution in sight, so I'm treating the above patch as a permanent solution for my projects that still use `next-auth`. I've updated the patch to make it compatible with the latest version.

**Comment by OmkarArora** [comment]
Any chance of this getting solved in v5?

**Comment by FINDarkside** [comment]
Now that it's shown that it cannot be worked around in userland and that SWR nor react query invalidate all data on network errors either can the fix be finally accepted to this project @balazsorban44? 

Are there some arguments for keeping this behaviour that are left uncovered? Shouldn't it at least be an option to allow not invalidating sessions like this? Imagine if Netflix logged people out every time they have connectivity issues.

**Comment by laurenswuyts** [comment]
Can this be integrated please?

**Comment by usuallyno** [comment]
Hi @igordanchenko your .patch works perfect! I've notice that is a little but behind the main branch, your version is 4.24.7 and  now we have 4.24.10, can you provide the source code of the edits you did? I want to maintain the patch and update to this current version in order to share with the community :)

**Comment by usuallyno** [comment]
thank you!!
