### ISSUE TITLE
Modify Session Object Value ?

### ISSUE THREAD

**Issue by sushilbalami** [nextauthjs/next-auth#2225]
Can I modify the session object?
I am using a credentials provider so.., I am authenticating with a custom database so
although I put this obj

```
"role": "user",
"_id": "60c1f6d9abaa0e2670b06b85",
"email": "sush@gmail.com",
"createdAt": "2021-06-10T11:26:17.308Z",
"updatedAt": "2021-06-10T11:26:17.308Z",
"__v": 0 
```
this returns

```
{
  user: { name: null, email: 'sush@gmail.com', image: null },
  expires: '2021-07-11T07:08:46.365Z'
}
```
on getSession({req});

so any way to add custom key-value or custom value on session obj?

Saw this: https://next-auth.js.org/configuration/callbacks#session-callback

only name, email and image keys are parsed why so ?
`user: { name: 'sushilbalami', email: '***@gmail.com', image: null },
`
tried putting id on
`session.user.id = customId,`
but only name, email, image values are only parsed

**Comment by balazsorban44** [comment]
Check out the JWT callback as well. For increased security/privacy - by default - we only persist a subset of the user data in the JWT token.

https://next-auth.js.org/configuration/callbacks#jwt-callback
