### ISSUE TITLE
client_fetch_error when testing in a JSDOM environment with NEXTAUTH_URL set 

### ISSUE THREAD

**Issue by willsoto** [nextauthjs/next-auth#2238]
## Description 🐜

When running tests in a JSDOM environment (headless browser in Node) a `client_fetch_error` is raised because the url is missing the host. 

## How to reproduce ☕️

A simple test should display this behavior when running Jest in a JSDOM [`testEnvironment`](https://jestjs.io/docs/configuration#testenvironment-string)

```ts
test("does not raise a 'client_fetch_error' in a jsdom environment", () => {
  return expect(getSession()).not.toThrow();
});
```

## Screenshots / Logs 📽

```
  console.error
    [next-auth][error][client_fetch_error]
    https://next-auth.js.org/errors#client_fetch_error session TypeError: Invalid URL: /api/auth/session
        at new URLImpl (/code/app/node_modules/whatwg-url/dist/URL-impl.js:21:13)
        at Object.exports.setup (/code/app/node_modules/whatwg-url/dist/URL.js:54:12)
        at new URL (/code/app/node_modules/whatwg-url/dist/URL.js:107:22)
        at new Request (/code/app/node_modules/node-fetch/src/request.js:46:16)
        at /code/app/node_modules/node-fetch/src/index.js:37:19
        at new Promise (<anonymous>)
        at fetch (/code/app/node_modules/node-fetch/src/index.js:35:9)
        at _callee9$ (/code/app/node_modules/next-auth/dist/client/index.js:629:20)
        at tryCatch (/code/app/node_modules/regenerator-runtime/runtime.js:63:40)
        at Generator.invoke [as _invoke] (/code/app/node_modules/regenerator-runtime/runtime.js:293:22)
```

## Environment 🖥

Please run this command:

```
$ npx envinfo --system --binaries --browsers --npmPackages "{next-auth}"
```

```
  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 959.29 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.volta/tools/image/node/14.17.0/bin/node
    Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 7.16.0 - ~/code/app/node_modules/.bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.1
    Safari: 14.1.1
```

## Contributing 🙌🏽

I believe the fix for this issue would be to adjust this method to check if it's a [JSDOM environment](https://github.com/jsdom/jsdom/issues/1537). The core problem is that in JSDOM, `typeof window !== "undefined"`, so the code block that includes the `baseUrlServer` is not hit, returning a relative URL.

https://github.com/nextauthjs/next-auth/blob/84094b0ee7ed48471128a3e1b1081d21631c4fd2/src/client/index.js#L331-L343

My proposal would be to add the following:

```ts
function _isJSDOM() {
  return typeof window !== 'undefined' && window.navigator.userAgent.includes('jsdom')
}
```

```diff
function _apiBaseUrl() {
+  if (typeof window === "undefined" || _isJSDOM()) {
    if (!process.env.NEXTAUTH_URL) {
      logger.warn("NEXTAUTH_URL", "NEXTAUTH_URL environment variable not set");
    }
    return "".concat(__NEXTAUTH.baseUrlServer).concat(__NEXTAUTH.basePathServer);
  }
  return __NEXTAUTH.basePath;
}
```

If the maintainers agree this is an issue and also agree this is an acceptable solution, I can make a PR with my suggested fix.

**Comment by balazsorban44** [comment]
What about:
```js
beforeAll(() => {
  process.env.NEXTAUTH_URL = window.location.origin
}
```

**Comment by willsoto** [comment]
The issue isn't that `process.env.NEXTAUTH_URL` is not being set - I confirmed it's set by the time the library attempts to read it - the problem is that it isn't actually reading that because it thinks it's in the browser.

I do find it curious that you all are not encountering the same issue, as you are also using jsdom and jest. Maybe `node-fetch` is the problem (I am using that as a `fetch` polyfill.) I'll look into using [`whatwg-fetch`](https://github.com/nextauthjs/next-auth/blob/main/config/jest-setup.js#L2) like you all are and see if that fixes it.

**Comment by willsoto** [comment]
So switching to `whatwg-fetch` makes it work, but it's unclear to me why. I guess `node-fetch` must not be spec compliant? Regardless, I'll go ahead and close this since it's resolved. 

I would like to say that regardless of the environment, the logic in `_apiBaseUrl` could probably be tweaked to support "browser like environments that run in Node" without having any logic specific to JSDOM. Probably not that big of a deal though. 

Thanks for the comment and the great library!
