### ISSUE TITLE
Wrong member type in DefaultJWT interface

### ISSUE THREAD

**Issue by nenadfilipovic** [nextauthjs/next-auth#2257]
## Question 💬

Shouldn't `picture` member be called `image` like in session, or I'm missing something?

```js
export interface DefaultJWT extends Record<string, unknown> {
  name?: string | null
  email?: string | null
  picture?: string | null
  sub?: string
}
```

```
export interface DefaultSession extends Record<string, unknown> {
  user?: {
    name?: string | null
    email?: string | null
    image?: string | null
  }
  expires?: string
}
```

I can quickly push PR with change if this is error.

**NOTE:** Questions will be converted to Discussions. You can find them [here](https://github.com/nextauthjs/next-auth/discussions)!

## How to reproduce ☕️

We encourage you to use the template set-up on **CodeSandbox** as a playground to represent your question or doubt:

- [`next-auth-typescript-example`](https://codesandbox.io/s/next-auth-typescript-example-se32w)

## Contributing 🙌🏽

It takes a lot of work 🏋🏻‍♀️ maintaining a library like `next-auth`; any contribution is more than welcome 💚

In case you're willing to help answer this TypeScript question, please let us know here, and we'll reach you 😊 . Otherwise, you can have a look at the issues labelled with [`"good first issue"`](https://github.com/nextauthjs/next-auth/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) and pick any of them.

**Comment by balazsorban44** [comment]
The current implementation is correct.

See: https://github.com/nextauthjs/next-auth/blob/b04ff82fb915fc53dc9b27ce15dbaed8ea903bab/src/server/routes/callback.js#L112

**Comment by nenadfilipovic** [comment]
Yea I was confused too, I had typescript problems with rewriting session.user with data from token, but with augmenting only certain fields there is no problem.

```
 async jwt(token, user) {
      if (user) {
        const { id, role } = user;
        token = { ...token, id, role };
      }
      return token;
    },
    async session(session, token) {
      const { id, role } = token;
      session.user = { ...session.user, id, role };
      return session;
    },
```

It was my fault to event try to pass name,email,image to my session.user when its passed by default, but thanks anyway.
