### ISSUE TITLE
I am always getting session null on api/test.ts

### ISSUE THREAD

**Issue by krunaldodiya** [nextauthjs/next-auth#2262]
Hi, thanks for such a nice library, i am trying to integrate, most of the things works but the only issue is that, I am always getting session=null inside api, not sure what i am doing wrong ?

### pages/Hello.tsx

```
import { getSession } from "next-auth/client";
import axios from 'axios';

const Hello = async () => {
  return <div>hello</div>
}

export const getServerSideProps = async (ctx) => {
  const {req} = ctx;
  
  // i am able to get session here
  const session = await getSession({req});

  // but when i send the request to api session is null
  const {data} = await axios.get(`${process.env.APP_URL}/api/test`)
}

export default Hello;

```

### pages/api/test.ts

```
import { getSession } from "next-auth/client";

const testApi = async (req,res) => {
   // i am not able to get session here
   const session = await getSession({req});

return res.status(200).json({status: "okay"})
}

export default testApi;
```

Any help would be appreciated :)

**Comment by balazsorban44** [comment]
I am thinking that maybe the cookies are somehow getting messed up/lost.

Could you see if `req.cookies.__Secure-next-auth.session-token` is present in `testApi`?

You should also make sure that you do an if check of `session` in `getServerSideProps`. If the user is not logged in yet, `session` will naturally be `null`

Generally, it is not recommended to call API routes from within your `getServerSideProps`.

See the notes in the official Next.js docs https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering

**Comment by krunaldodiya** [comment]
thanks for reply, i yes checked ```You should also make sure that you do an if check of session in getServerSideProps. If the user is not logged in yet, session will naturally be null``` user is logged in and i am getting user object in getServerSideProps, just it is not passing that session to api only, and yes thanks for info, i think i should refactor the code and not use fetch calls in getServerSideProps
