### ISSUE TITLE
Error with Prisma and Auth0 integration

### ISSUE THREAD

**Issue by danyel117** [nextauthjs/next-auth#2287]
## Description 🐜

Please provide a clear and concise description of the bug in NextAuth.js.

I installed the latest Prisma, NextAuth and Prisma adapter packages, and when I try to log in for the first time with Auth0 provider, I get an error indicating that the compoundId is required.

The old Prisma schema had the field compoundId. If I manually add the same field to the new schema, the login works and the issue dissapears.

## How to reproduce ☕️

Copy the Prisma schema from https://next-auth.js.org/adapters/prisma and try to log in with Auth0. 

## Screenshots / Logs 📽
```
{
  clientVersion: '2.26.0'
}
[next-auth][error][oauth_callback_handler_error]
https://next-auth.js.org/errors#oauth_callback_handler_error Error:
Invalid prisma.account.findUnique() invocation:

{
  where: {
    compoundId: 'somecompoundidthatithinkishouldnotcopyhere'  
    ~~~~~~~~~~
  }
}

Unknown arg compoundId in where.compoundId for type AccountWhereUniqueInput. Available args:

type AccountWhereUniqueInput {
  id?: String
  providerId_providerAccountId?: AccountProviderIdProviderAccountIdCompoundUniqueInput
}
```

## Environment 🖥

```
  System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
    Memory: 5.23 GB / 15.87 GB
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.124
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.59)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    next: ^11.0.1 => 11.0.1
    next-auth: ^3.27.1 => 3.27.1
    react: ^17.0.2 => 17.0.2
```

Happy to help!

**Comment by balazsorban44** [comment]
could you please share some code? how do you import the Prisma adapter?

**Comment by danyel117** [comment]
I figured that I had the old adapter imports, and that's why NextAuth was looking for the compoundId. My bad.

However, when I use the imports stated in the documentation I get the following typescript error:

`Cannot find module '@next-auth/prisma-adapter' or its corresponding type declarations.ts(2307)`



Here is my [...nextauth].ts file:
```

import NextAuth from 'next-auth';
import Providers from 'next-auth/providers';
import { PrismaAdapter } from '@next-auth/prisma-adapter';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export default NextAuth({
  providers: [
    Providers.Auth0({
      clientId: process.env.AUTH0_CLIENT_ID,
      clientSecret: process.env.AUTH0_CLIENT_SECRET,
      domain: process.env.AUTH0_DOMAIN,
      authorizationUrl: `https://${process.env.AUTH0_DOMAIN}/authorize?response_type=code&prompt=login`,
    }),
  ],
  adapter: PrismaAdapter(prisma),
});
```
I started a small test project from scratch and found the same issue. Here is my repository:

[](https://github.com/danyel117/prisma-nextjs-test)

**Comment by balazsorban44** [comment]
Had an issue with our latest release, try upgrading to `0.5.2`

https://github.com/nextauthjs/adapters/issues/159

**Comment by danyel117** [comment]
It worked! Thanks
