### ISSUE TITLE
Question regarding "Databases" and "Testing" sections of CONTRIBUTING.md

### ISSUE THREAD

**Issue by mahieyin-rahmun** [nextauthjs/next-auth#2292]
## Question 💬
First of all, thank you very much for all the efforts that you make to maintain the NextAuth library which I am a big fan of. I am currently working on implementing a custom provider and I intend to open a PR soon, however, I was looking through the Contributing guidelines and had some confusions. 

[The "Databases" section of CONTRIBUTING.md states that](https://github.com/nextauthjs/next-auth/blob/main/CONTRIBUTING.md#databases):

> Included is a Docker Compose file that starts up MySQL, PostgreSQL, and MongoDB databases on localhost.

I could not find such a .yml file that could start up the docker container in the project directory. 

> You can start them with npm run db:start and stop them with npm run db:stop.

There are no scripts in the `package.json` file that correspond to the aforementioned ones.

[The "Testing" section of CONTRIBUTING.md states that](https://github.com/nextauthjs/next-auth/blob/main/CONTRIBUTING.md#testing):

> Currently, to run tests you need to first have started local test databases (e.g. using npm run db:start).

As mentioned above, there is no such script in the package.json file.

This is also left as part of the `.env.local.example` file:

```env
# You can use any of these as the "DATABASE_URL" for
# databases started with Docker using `npm run db:start`.
# Note: If using with Prisma adapter, you need to use a `.env`
# file rather than a `.env.local` file to configure env vars.
# Postgres: DATABASE_URL=postgres://nextauth:password@127.0.0.1:5432/nextauth?synchronize=true
# MySQL:    DATABASE_URL=mysql://nextauth:password@127.0.0.1:3306/nextauth?synchronize=true
# MongoDB:  DATABASE_URL=mongodb://nextauth:password@127.0.0.1:27017/nextauth?synchronize=true
```

## How to reproduce ☕️
1. Clone the repository.
2. Setup development environment by installing packages and populating secrets file.
2. Try to run `npm run db:start`
3. Error will be shown saying that the corresponding script is missing.
4. I could not find such a docker compose file to start up databases.

## Additional Information
As you can see, there is no mention of either `db:start` or `db:stop` under the `scripts` section.

[`./package.json`](https://github.com/nextauthjs/next-auth/blob/main/package.json#L31)
```json
"scripts": {
    "build": "npm run build:js && npm run build:css",
    "build:js": "node ./config/build.js && babel --config-file ./config/babel.config.js src --out-dir dist",
    "build:css": "postcss --config config/postcss.config.js src/**/*.css --base src --dir dist && node config/wrap-css.js",
    "dev:setup": "npm i && npm run build:css && cd app && npm i",
    "dev": "cd app && npm run dev",
    "watch": "npm run watch:js | npm run watch:css",
    "watch:js": "babel --config-file ./config/babel.config.js --watch src --out-dir dist",
    "watch:css": "postcss --config config/postcss.config.js --watch src/**/*.css --base src --dir dist",
    "test": "jest --config ./config/jest.config.js",
    "test:ci": "npm run lint && npm run test:types && npm run test -- --ci",
    "test:types": "dtslint types --onlyTestTsNext",
    "prepublishOnly": "npm run build",
    "lint": "eslint .",
    "lint:fix": "eslint . --fix",
    "version:pr": "node ./config/version-pr"
  },
```

## Contributing 🙌🏽
If this is mistakenly left as part of the documentation, I am willing to open a PR to address this once I have sufficient information on how this can be addressed.

**Comment by balazsorban44** [comment]
Hi there, this is a mistake on our side, I see! Adapters have been moved to a new home at:

https://www.github.com/nextauthjs/adapters

The above mentioned contribution instructions are leftovers from when this repo contained the adapter code.

See https://github.com/nextauthjs/adapters#testing and the Contributing.md document in that repo instead.

If you wish to clean up the docs here, it's very welcome!
