### ISSUE TITLE
chore(docs): Update Issue Templates

### ISSUE THREAD

**Issue by mahieyin-rahmun** [nextauthjs/next-auth#2305]
_Originally posted by @balazsorban44 in https://github.com/nextauthjs/next-auth/issues/2274#issuecomment-873434436_

> @mahieyin-rahmun just a minor thing, but could you please remove the prefixes in titles in a subsequent PR?
I don't think we need them (eg.: [Bug]:), as we have the labels anyway. They take up significant space, especially in the github mobile app, and it's harder to guess the content from the title. 😊
Also, SOME kind of reproduction should be REQUIRED. I just converted 2 questions, none of them had any code reproduction...

**Comment by mahieyin-rahmun** [comment]
@balazsorban44, I think we introduced a bug with the last PR:

![image](https://user-images.githubusercontent.com/37664921/124381449-7a73dd80-dce4-11eb-9d7e-18e267e1c00c.png)

I can confirm this, since Issue Templates are no longer being used:

![image](https://user-images.githubusercontent.com/37664921/124381476-98d9d900-dce4-11eb-9174-0f1c6c882b44.png)

**Comment by balazsorban44** [comment]
😬

Something like this would make sense you think?

https://stackoverflow.com/questions/34089496/empty-field-in-yaml

**Comment by mahieyin-rahmun** [comment]
> 😬
> 
> Something like this would make sense you think?
> 
> https://stackoverflow.com/questions/34089496/empty-field-in-yaml

I will check this and get back to you in a bit.

**Comment by balazsorban44** [comment]
https://github.com/vercel/next.js/blob/canary/.github/ISSUE_TEMPLATE/1.bug_report.yml

so the easiest way to solve this is to just leave out the title field! 😅

**Comment by mahieyin-rahmun** [comment]
> Something like this would make sense you think?
> 
> https://stackoverflow.com/questions/34089496/empty-field-in-yaml
> 
> (appearantly two single quotes could work as well)
> 
> I reopen this until fixed.

Neither '' nor ~ works. The title must be a string and it must be surrounded in double quotations

**Comment by mahieyin-rahmun** [comment]
> https://github.com/vercel/next.js/blob/canary/.github/ISSUE_TEMPLATE/1.bug_report.yml
> 
> so the easiest way to solve this is to just leave out the title field!

**Comment by balazsorban44** [comment]
thanks! looking good now!
