### ISSUE TITLE
Custom login-form with getCsrfToken

### ISSUE THREAD

**Issue by marcobusemann** [nextauthjs/next-auth#2307]
Hey, I have a question on how a custom login-form is supposed to use getCsrfToken. 
In your example, you suggest to use it like this:
```
export async function getServerSideProps(context){
  const csrfToken = await getCsrfToken(context)
  return {
    props: { csrfToken }
  }
}
```

The csrf-endpoint generates the token and creates a cookie on the response. If I understand it correctly, the cookie is required to do the "double submit cookie method". The problem is, the cookie is never exposed/forwarded to the client. 

On our page this leads to a flow like this:
- User visits /login (no 'next-auth.csrf-token' present)
- User clicks login
- Login page is opened again (with query-param callbackUrl=..., the cookie 'next-auth.csrf-token' is now set)
- User clicks login again
- Login worked

If we call `getCsrfToken` on the client, the 'next-auth.csrf-token' is present right away and the login flow works as expected.
```
  useEffect(() => {
    getCsrfToken()
      .catch(e => console.log(e))
      .then(t => setCsrfToken(t as string))
  }, []);
```

Any thoughts on this? Are we doing something wrong?

**Comment by balazsorban44** [comment]
I believe you are right. fetch from getServerSideProps won't forward the cookies I believe. I think we will need to expose these methods server-side without fetch
related: #1535

fow now, you could use the useEffect method, I am pretty sure that will work
