### ISSUE TITLE
Live Documentation does not represent main branch

### ISSUE THREAD

**Issue by SaschaWebDev** [nextauthjs/next-auth#2309]
### Description 🐜

During using NextAuth myself I stumbled upon this bug in the documentation that could lead to confusion for newcomers. 

https://next-auth.js.org/configuration/pages
In the text it is written to use the `signIn()` function while the corresponding code example says `sign()` function.
![image](https://user-images.githubusercontent.com/19645465/124383434-adaa7280-dccc-11eb-92c2-bcdaff7e421b.png)

In this case, the text is correct, and the code snippet wrong, which could lead to even more problems as most newcomers just copy and paste snippets.

The same mistake is occurring for the credential login code snippet:
![image](https://user-images.githubusercontent.com/19645465/124383479-f9f5b280-dccc-11eb-84bd-4d74104b3dde.png)

As I wanted to fix this bug myself and create a Pull Request, I found out that these mistakes' are already fixed in the main branch and not present there.
![image](https://user-images.githubusercontent.com/19645465/124383508-20b3e900-dccd-11eb-888f-121bfe79b5e3.png)

Thus, my conclusion is either the live documentation on the website is not deployed to main branch or there is a client-side error on the website that replaces `signIn` with `sign` because it is a keyword or something.

I think fixing this could prevent some errors and questions for new people using NextAuth and increase confidence in the documentation.

### Is this a bug in your own project?

No

### How to reproduce ☕️

Go to https://next-auth.js.org/configuration/pages then copy and paste not working snippets telling you to use `sign()` instead of `signIn()`.

### Screenshots / Logs 📽

![image](https://user-images.githubusercontent.com/19645465/124383434-adaa7280-dccc-11eb-92c2-bcdaff7e421b.png)

### Environment 🖥

website

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by lluia** [comment]
Thanks for reporting this, prolly is an easy fix, we'll have a look soon 🙂

**Comment by balazsorban44** [comment]
Hi that is very odd, I don't see what you are describing...

![Screenshot_20210704-134919](https://user-images.githubusercontent.com/18369201/124383802-b8fe9d80-dcce-11eb-94a0-3871c7ce12fd.png)
![Screenshot_20210704-134924](https://user-images.githubusercontent.com/18369201/124383804-bc922480-dcce-11eb-8eae-b384c86c2b53.png)

**Comment by SaschaWebDev** [comment]
> Hi that is very odd, I don't see what you are describing...
> 
> ![Screenshot_20210704-134919](https://user-images.githubusercontent.com/18369201/124383802-b8fe9d80-dcce-11eb-94a0-3871c7ce12fd.png)
> ![Screenshot_20210704-134924](https://user-images.githubusercontent.com/18369201/124383804-bc922480-dcce-11eb-8eae-b384c86c2b53.png)
> 
> The search query https://github.com/nextauthjs/next-auth/search?q=sign%28 doesn't yield any results either.
> 
> I would check if you have a strange browser extension that is doing some funky business 🥸

You are right, it seems to be specific in my browser Google Chrome with several development add-ons. Does not happen in fresh installation. Interesting, and thanks for solving this.

**Comment by balazsorban44** [comment]
Awesome, could you please pinpoint which extension caused this, in case someone else stumbles upon this issue thread?

**Comment by SaschaWebDev** [comment]
> Awesome, could you please pinpoint which extension caused this, in case someone else stumbles upon this issue thread?

I am afraid I don't have the time to pinpoint this down. I can post a screenshot of all of my addons, though. I got some very specific ones, so the chance should be reduced that this happens to a lot of NextAuth users in the future.

![image](https://user-images.githubusercontent.com/19645465/124384081-0c252000-dcd0-11eb-99da-fb298b92028b.png)
![image](https://user-images.githubusercontent.com/19645465/124384087-1810e200-dcd0-11eb-8c2e-f511eb176556.png)
![image](https://user-images.githubusercontent.com/19645465/124384094-1e9f5980-dcd0-11eb-99ad-d908069560bd.png)

**Comment by SaschaWebDev** [comment]
> > Awesome, could you please pinpoint which extension caused this, in case someone else stumbles upon this issue thread?
> 
> I am afraid I don't have the time to pinpoint this down. I can post a screenshot of all of my addons, though. I got some very specific ones, so the chance should be reduced that this happens to a lot of NextAuth users in the future.
> 
> ![image](https://user-images.githubusercontent.com/19645465/124384081-0c252000-dcd0-11eb-99da-fb298b92028b.png)
> ![image](https://user-images.githubusercontent.com/19645465/124384087-1810e200-dcd0-11eb-8c2e-f511eb176556.png)
> ![image](https://user-images.githubusercontent.com/19645465/124384094-1e9f5980-dcd0-11eb-99ad-d908069560bd.png)

Ah, it should be "Binnen-I-be-gone" it detects signIn as german gender language and removes it 😆

**Comment by balazsorban44** [comment]
I'm pretty sure it was the one conveniently named

"Binnen-I be gone"😅:

https://chrome.google.com/webstore/detail/binnen-i-be-gone/ginkajgcbeolbiflkjomlkcdapbegaff
