### ISSUE TITLE
NextAuth starter repository

### ISSUE THREAD

**Issue by plxity** [nextauthjs/next-auth#2326]
### Description 📓

I have made a NextAuth starter repository that has all the basic authentication setups done. 
Here is the link - https://github.com/plxity/Next-auth-starter

Just wanted to know if this can be a part of the documentation so that beginners can get an Idea and use it easily for their projects? :)

### How to reproduce ☕️

-

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
Hi, thank you for sharing!

Although we provide both a JavaScript and TypeScript starter/example here:

- https://github.com/nextauthjs/next-auth-example
- https://github.com/nextauthjs/next-auth-typescript-example

Please tell us if you think something is missing, or open a PR with your suggestion and we will review it!
