### ISSUE TITLE
How I can get the Twitter username or id?

### ISSUE THREAD

**Issue by ShawkiS** [nextauthjs/next-auth#2331]
### Question 💬

I made a login using Twitter and getting the session, it only returns email, name. how can I get the username or Twitter id?

### How to reproduce ☕️

``

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
https://next-auth.js.org/configuration/callbacks#jwt-callback

https://next-auth.js.org/configuration/callbacks#session-callback

**Comment by ShawkiS** [comment]
Hey @balazsorban44, thanks! I checked those but it doesn't return the username or the id
![log](https://user-images.githubusercontent.com/57439827/125178930-fe046180-e1f1-11eb-9c0a-322e8b8eff82.PNG)

**Comment by smakosh** [comment]
You can achieve that by customizing the returned data like so:

```ts
export default NextAuth({
  providers: [
    Providers.Twitter({
      clientId: process.env.TWITTER_ID,
      clientSecret: process.env.TWITTER_SECRET,
      profile(profile) {
        return {
          id: profile.id_str,
          name: profile.screen_name, // this is the Twitter username
          email: profile.email,
          image: profile.profile_image_url_https.replace(/_normal\.(jpg|png|gif)$/, '.$1') as string,
        };
      },
    }),
  ],
```

**Comment by hairyf** [comment]
To prevent anyone from encountering this problem, this is the current solution:
```ts
export default NextAuth({
  providers: [
    TwitterProvider({
      clientId: process.env.TWITTER_ID!,
      clientSecret: process.env.TWITTER_SECRET!,
      version: '2.0',
      userinfo: 'https://api.twitter.com/2/users/me?user.fields=id,username,profile_image_url',
      profile(profile) {
        return {
          id: profile.data.id,
          name: profile.data.username,
          email: profile.data.email ?? null,
          image: profile.data.profile_image_url,
        }
      },
    })
  ],
  secret: process.env.AUTH_SECRET
});
```
