### ISSUE TITLE
Mobile version of the docs hide documention navigation

### ISSUE THREAD

**Issue by MatteoGauthier** [nextauthjs/next-auth#2332]
Hey I noticed que le that the side navigation for the documentation doesn't appear. I'm on Android with Chrome.

Otherwise thanks for this amazing tool 🤠

**Comment by balazsorban44** [comment]
Please give us more info. 😅 I am not sure what to look for, everything works on my Android phone with Chrome.

**Comment by ndom91** [comment]
Also the docusaurus mobile TOC / menu redesign seems soo close to being merged (https://github.com/facebook/docusaurus/pull/4273)

**Comment by ndom91** [comment]
@MatteoGauthier can you take a look at the latest canary version of our documentation page to see if this is fixed for you? I've merged the latest docusaurus updates in - https://next-auth-git-ndom91-add-migration-docs-nextauthjs.vercel.app/.

Thanks!

**Comment by MatteoGauthier** [comment]
> @MatteoGauthier can you take a look at the latest canary version of our documentation page to see if this is fixed for you? I've merged the latest docusaurus updates in - https://next-auth-git-ndom91-add-migration-docs-nextauthjs.vercel.app/.
> 
> Thanks!

Sure it's fixed thanks you @ndom91 👍
