### ISSUE TITLE
[OKTA] self hosted widged

### ISSUE THREAD

**Issue by djleonskennedy** [nextauthjs/next-auth#2338]
### Question 💬

Hello next-auth team! 

Could you please clarify, is there any chance to integrate https://developer.okta.com/code/javascript/okta_sign-in_widget/
in next auth login page, to avoid login on `okta hosted` widged?

BR

### How to reproduce ☕️

no info

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
so from what I understand, the Okta widget is a fully fledged solution, and next-auth doesn't have anything to do really. we do support the Okta oauth flow https://next-auth.js.org/providers/okta

If I misunderstand something, feel free to comment more on this.
