### ISSUE TITLE
Is this usable with a normal React app?

### ISSUE THREAD

**Issue by angelhodar** [nextauthjs/next-auth#2351]
Hey everyone! I am curious about this line in the README:

Designed for Serverless but runs anywhere (AWS Lambda, Docker, Heroku, etc…)

As I know, this library uses the NextJS api routing based on files to configure providers, callbacks and so on. Then my questions is how is this implemented in AWS Lambda or Heroku? Is there any example in the docs? I havent seen anyone.

**Comment by balazsorban44** [comment]
Currently we only support Next.js officially, but have a look at #2294 for how we could expand on it.

That line in the docs refers to that since Next.js can run in any of those environments, next-auth is expected to work there as well. 😊
