### ISSUE TITLE
Azure AD B2C is using the wrong name

### ISSUE THREAD

**Issue by cmatskas** [nextauthjs/next-auth#2362]
### Description 🐜

Hi team,

I was playing around with the providers and I noticed that the Azure AD B2C is minsnamed. After checking the code and setting up a sample, it's clear that the solution is using Azure Active Directory and not B2C.

I know that the Microsoft Identity platform can/is confusing but we would love to work with you to:
a) Make sure that the current provider is right
b) Add a new provider that actually works with the Azure AD B2C endpoints

### Is this a bug in your own project?

No

### How to reproduce ☕️

Configuring the provider needs a proper Azure AD tenant, instead of AAD B2C

### Screenshots / Logs 📽

![image](https://user-images.githubusercontent.com/4126750/125372364-cb648100-e337-11eb-84fe-9d08b5a1703d.png)

### Environment 🖥

Applicable to all environments

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
fixed in #1591

**Comment by cmatskas** [comment]
This is awesome! Thanks for letting me know :) I'll update my code accordingly! Great effort team

**Comment by cmatskas** [comment]
How can we include these samples to the official samples? I'm creating both an AAD and B2C sample and it would be great if we could collaborate on this to help developers implement auth with the Microsoft Identity platform

**Comment by balazsorban44** [comment]
You mean these?:

https://github.com/nextauthjs/next-auth-example

https://github.com/nextauthjs/next-auth-typescript-example

Just open a PR in the repos, and will have a look.

BTW I think @ndom91 is working on setting up accounts on different provider platforms so we can test the login flow by a cron job or similar, so we know our providers still work over time.

Would Microsoft be interested in providing resources for a test account of sorts (if either AAD or B2C cost anything)?

**Comment by cmatskas** [comment]
Microsoft offers a frew M365 Developer tenant that can be use just for that reason. It's easy to sign up, it's free and comes with a full blown Azure AD tenant for testing. 
[Microsoft 365 Developer Signup](https://aka.ms/425Show/devenv)

Unfortunately, B2C requires an Azure Subscription but we can provide vouchers for that to unblock you if you don't already have an account

**Comment by balazsorban44** [comment]
Thanks, will forward that info to the others.

**Comment by Frikki** [comment]
Did you finish those samples, @cmatskas?
