### ISSUE TITLE
Add support for mongodb v4 adapter

### ISSUE THREAD

**Issue by michalbundyra** [nextauthjs/next-auth#2374]
### Description 📓

Recently [mongodb v4](https://github.com/mongodb/node-mongodb-native/releases/tag/v4.0.0) has been released. Would be nice if we can support it here. Not sure tho if it is possible in minor version or it will require new major? Thanks!

### How to reproduce ☕️

```
https://next-auth.js.org/errors#oauth_callback_handler_error Error: optional dependency [mongodb] found but version [4.0.0] did not satisfy constraint [^3.5.9]
```

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
We use `mongodb` through `typeorm`, so I guess it depends on them. https://github.com/typeorm/typeorm/issues/7907#issuecomment-880518853

Head over to their repo for support.
