### ISSUE TITLE
Can we change the object returned by useSession to include the user ID?

### ISSUE THREAD

**Issue by ziedHamdi** [nextauthjs/next-auth#2385]
### Question 💬

Hi all,

Thanks for the cool lib, everything went blazing fast to set up. But now I have an issue: I'd like to know if the logged user is the author of a database record. In the record I save the user ID, but when I was attempting to check if the logged user is that same person, I realized the session object doesn't have the _id field. 
I don't want to compare by email since I want to support multiple emails per user 

So the question is: **can we change the object returned by useSession to include the user ID?**

```
const [session, loading] = useSession()
 function isAuthor() {
        const loggedUser = session?.user;
        logger.debug("logged user: ", loggedUser, " issue user: ", issue.user)
        return loggedUser != null && loggedUser.id === issue.user.userId
    }

```

output

`debug:["logged user: ",{"name":"Zied Hamdi","email":"zhamdi@xyz.com","image":"https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=xyz"}," issue user: ",{"__typename":"ComplaintContributorsUser","userId":"60d079d48cc3ab35c8401bae","userName":"Zied Hamdi","roleInShop":"ASA"}]`

### How to reproduce ☕️

simply call useSesion()

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by ziedHamdi** [comment]
This is maybe similar to the issue [](https://github.com/nextauthjs/next-auth/issues/916) in some points, but there's no code to show how it was solved

**Comment by balazsorban44** [comment]
https://next-auth.js.org/configuration/callbacks check  the jwt and session callbacks 😊

**Comment by ziedHamdi** [comment]
Ok thank you, when I was appending id to the session it was not returned, but adding it to the user works : **session.user.id = token.id**

callbacks: {
        async session(session, token) {
            // Add property to session, like an access_token from a provider.
            session.accessToken = token.accessToken
            session.user.id = token.id
            return session
        }
    }

Thanks for you answer @balazsorban44, I think the doc should be more explicit about the callback (My understanding was that it is called only when a login through a provider executes). I think it shloud be mentioned in the doc of useSession that we can change the default returned object by looking at the docs of callbacks

**Comment by balazsorban44** [comment]
Happy to take suggestions in the form of a PR to make this more clear. 😊
