### ISSUE TITLE
Wrong callbackUrl on custom sign-in page

### ISSUE THREAD

**Issue by jacklimwenjie** [nextauthjs/next-auth#2392]
### Description 🐜

Given that a custom sign-in page is set up,
and the sign-in page is navigated to by calling the REST API `/api/auth/signin`,
the `callbackUrl` query param is inconsistent and most of the time it's wrong. 

Example: 
User clicks on the "Sign In" button on the "/about" page,
when lands on the custom sign-in page e.g. "/auth/signin", the `callbackUrl` query param is expected to be "https://localhost:3000/about", but in fact, it is "https://localhost:3000/profile"

### Is this a bug in your own project?

No

### How to reproduce ☕️

https://codesandbox.io/s/tender-darwin-902dn?file=/pages/auth/signin.js

### Environment 🖥

System:
    OS: macOS 11.4
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 155.62 MB / 8.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.15.0 - ~/.nvm/versions/node/v12.15.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 88.0.1
    Safari: 14.1.1
  npmPackages:
    next: ^11.0.0 => 11.0.0 
    next-auth: ^3.11.2 => 3.11.2 
    react: ^17.0.2 => 17.0.2 

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
I cannot see am about page in your reproduction. Could you please update it?
