### ISSUE TITLE
Typo in docs link for LinkedIn

### ISSUE THREAD

**Issue by Nautman** [nextauthjs/next-auth#2402]
### Description 🐜

The following line has an incorrect link in the docs. It should be linking to this file. https://github.com/nextauthjs/next-auth/blob/main/src/providers/linkedin.js

    LinkedIn Provider options
  

This is the incorrect file/link https://github.com/nextauthjs/next-auth/blob/main/www/docs/providers/linkedin.md#L22

I can fix this but I don't have this repo set up so if it's easy for someone else to fix that would be very kind.

### Is this a bug in your own project?

No

### How to reproduce ☕️

Look at the page

### Screenshots / Logs 📽

<img width="498" alt="image" src="https://user-images.githubusercontent.com/28629647/126133824-27355580-c92e-432e-8758-d6222922649d.png">

### Environment 🖥

none

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
You don't have to set up anything, here is the file in question:

https://github.com/nextauthjs/next-auth/blob/main/www/docs/providers/linkedin.md

GitHub makes it easy to edit in the web view:
![](https://i.imgur.com/wPTq4b6.png)

This will create a fork, from which you can open a PR very easily.

**Comment by Nautman** [comment]
Created a PR. Thanks!
