### ISSUE TITLE
Telegram as an Authentication Provider

### ISSUE THREAD

**Issue by jsjoeio** [nextauthjs/next-auth#2406]
### Description 📓

As a user of `next-auth`, I would like to be able to use [Telegram](https://telegram.org/) as an authentication provider. 

## Links from Telegram

- [User Authorization](https://core.telegram.org/api/auth#sign-insign-up)
- [Telegram Login Widget](https://core.telegram.org/widgets/login)
- [Telegram Login for Websites](https://telegram.org/blog/login)

Note: not sure how difficult it would be to implement this, but with some guidance/suggestions, I might be able to do it myself as a contribution.

### How to reproduce ☕️

N/A - not a bug to reproduce 

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by ndom91** [comment]
The Telegram auth isn't a classic OAuth implementation. However, you could use the credentials provider to implement a custom telegram provider. As there are no username/password provided here it would be a bit trickier to get this working.

From their docs you've linked, it looks like you setup a Telegram bot for your app / company. The user clicks "login" and enters their telegram number, the bot sends them a confirmation code which they then enter in the login widget. 

You would have to replace the nextauth credentials login fields with the telegram login widget through a custom nextauth sign-in page, then in the `authorize` callback of the credentials provider, do the comparison of the returned telegram hash and the sha256 of the bot's secret key, see [checking authorization](https://core.telegram.org/widgets/login#checking-authorization) in their login widget page you linked. If they match, auhtorization was successful and you can return the telegram user details object from the authorize callback.

Just thinking out loud here - the widget takes an argument, `data-auth-url` which is a callback URL telegram will forward to with all the users info attached as query params, maybe define a nextauth callback URL here and do some of the other verification work in one of the callback handlers (https://docs-nextauthjs.vercel.app/configuration/callbacks#sign-in-callback) ?

Unforuntately this is an extremely custom provider that we can't help much further with at the moment. 

NextAuth credentials provider details: https://docs-nextauthjs.vercel.app/providers/credentials
Telegram PHP login example: https://gist.github.com/anonymous/6516521b1fb3b464534fbc30ea3573c2

**Comment by jsjoeio** [comment]
Wow, thanks for thinking out loud on that @ndom91!

So in summary, sounds like it's possible but will look different than other implementations. 

And thank you for linking the examples. That should suffice I think. Thanks so much!

**Comment by ziedHamdi** [comment]
I think there's a lot of peuple joining telegram, not providing a default impregnation will lead to many custom unworking implementations, leading to a lot of issue signalling. I'd like to implement this, because of I use their lib, I'll struggle to notify nextauth that the user is logged in, and I think there are a lot of other people out there with that need. Is there a way to ask how many would be interested by this feature?

**Comment by NayamAmarshe** [comment]
I'd love to have this feature! Telegram has become my daily app and it'd be amazing to have Telegram authentication on websites.

**Comment by v-zdorovcev** [comment]
I support it!. I want to see telegram as a provider. It will be very useful to me and others

**Comment by ndom91** [comment]
We recognize that there is probably a large amount of demand for something like this, however, Telegram doesn't seem to provide a standard OAuth type of login. 

This means that adding its entirely custom login behavior to NextAuth.js is a rather large undertaking. If you'd like to give it a shot, we'd happily look at a PR, but we will not be pursuing this ourselves any time soon.

**Comment by Dax911** [comment]
Currently basing my head on this as it is a core part of the specs I need to meet would have loved to use my go-to toolchain in this case.  If I come up with something significant I will attach a PR. Very helpful thread tho thank you.

**Comment by flschweiger** [comment]
I've submitted a feature request on Telegram's Bugs and Suggestions page, feel free to login with Telegram and upvote the issue here: https://bugs.telegram.org/c/23608

**Comment by flschweiger** [comment]
I would love to see more websites offering Login with Telegram, too! @passsy and I have implemented the custom login flow a few times for smaller side projects but it would be really nice to have a simple 'drop-in' solution. Especially that you can send the authenticated user notifications through Telegram makes it a really cool alternative to other providers.

I've submitted a feature request on Telegram's Bugs and Suggestions page, feel free to **Login with Telegram** 😆 and upvote the issue here: https://bugs.telegram.org/c/23608

**Comment by manzoorwanijk** [comment]
Here is an example using credentials provider, using a custom signing page

https://github.com/manzoorwanijk/telegram-auth/tree/main/examples/next-auth

**Comment by ziedHamdi** [comment]
> Here is an example using credentials provider, using a custom signing page
> 
> https://github.com/manzoorwanijk/telegram-auth/tree/main/examples/next-auth

Thanks for sharing, I hadn't the energy to dig into lib internals. You made my day with this :-)

**Comment by TeaByte** [comment]
> Here is an example using credentials provider, using a custom signing page
> 
> https://github.com/manzoorwanijk/telegram-auth/tree/main/examples/next-auth

i remade it with **app router and server components** and added prismaJS 

https://github.com/TeaByte/telegram-auth-nextjs

**Comment by rashdeva** [comment]
> > Here is an example using credentials provider, using a custom signing page
> > https://github.com/manzoorwanijk/telegram-auth/tree/main/examples/next-auth
> 
> i remade it with **app router and server components** and added prismaJS
> 
> https://github.com/TeaByte/telegram-auth-nextjs

thank you very much!

**Comment by sysadminpower2019** [comment]
hello, was anyone able to get this implemented? i am looking to port this level of telegram authentication for user managemet to several other open source platforms.

**Comment by Akuna444** [comment]
Use the following code for nextjs app router https://github.com/TeaByte/telegram-auth-nextjs

**Comment by Dax911** [comment]
+1 thank you

**Comment by parmetra** [comment]
> i remade it with **app router and server components** and added prismaJS
> 
> https://github.com/TeaByte/telegram-auth-nextjs

Hello! Could you please tell me if there will be a Telegram authorization example for version next-auth ^5?
