### ISSUE TITLE
NextAuth reverify email every sign in

### ISSUE THREAD

**Issue by nenadfilipovic** [nextauthjs/next-auth#2419]
### Question 💬

Are you aware and is it expected that every time I sign in `emailVerified` field get updated with current time? I am talking about passwordless (email) login.

### How to reproduce ☕️

~

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
I'm not sure if it was the original intent, (and the author is hard to reach unfortunately) but I don't see it as an actual issue. in fact, every time you sign in with that flow, you kind of re verify that address.

**Comment by nenadfilipovic** [comment]
It triggers my updated at value so it is not very good for me. I need to manually control updatedAt value then. Thanks anyway.
