### ISSUE TITLE
OAuth login authenticates as different credentials user

### ISSUE THREAD

**Issue by ivanmaeder** [nextauthjs/next-auth#2424]
### Question 💬

I'm trying to figure out how it's possible to log in with OAuth (Google), and up being logged in with a different **credentials** user.

I'm on localhost and I have been logged in previously as the credentials user.

In the callback functions I see a mix of details:

`signIn()`

- `user` refers to the credentials user
- `account` has `provider: 'google'`
- `profile` refers to the Google user

`jwt()`

- `token` has the credentials user details
- `user`: credentials user
- `account` is Google
- `profile`: Google user
- `isNewUser`: false

`session()`

- `session` has the credentials user's details
- `token` the same

The email addresses, name, etc are different for both uers.

When I'm logged out, I can see that the browser is not storing the JWT.

This happens even after signing out. When signing in with Google, I get the Google-hosted page asking which Google account I'd like to use, so that part is working.

The credentials user is in the DB, but the Google user is not being added to the DB.

How could this have happened? Have I done something weird during test? Or could this happen in production? This is not in production yet but that's the big worry: this happening to a real user which would undermine credibility.

I'm using:

- next 10.2.3
- next-auth 3.27.1
- @next-auth/prisma-adapter 0.4.4-canary.81

Let me know if I can help with any other details.

Thanks!

### How to reproduce ☕️

I can't explain everything that led up to this, but right now:

- Log in using Google OAuth
- Choose the appropriate Google account in the Google screen
- App logs into a different **credentials** user
- Sign out (an `onClick` triggers the `next-auth/client` `signOut()` function
- Repeat

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by ivanmaeder** [comment]
An update on this: I've tried another browser where I wasn't previously logged in as the credentials user, and it also logs me in as that user.

**Comment by sastraxi** [comment]
@ivanmaeder Is this other user that you're seeing a different account that you control, or a completely "random" account? Is this a user you've signed in with under a different app you're developing, or even under this one?

I wonder if what's happening is that you've re-used a JWT / secret from a different project which is then being picked up (being the same `localhost` domain), but this is purely speculation without being able to see the code.

If you can help provide a minimal reproduction case (perhaps based on [next-auth-example](https://github.com/nextauthjs/next-auth-example)) we'll be able to triage this and understand what's happening better.

**Comment by ivanmaeder** [comment]
Thanks @sastraxi. In preparing this response I think I've figured it out.

What's happening is that the `id` returned in the Google OAuth profile object matches the `Accounts.userId` of a different user, and it's this other user that ends up in the JWT.

So my guess is that I mangled the DB during testing.

I'll close this, but if you want to look into it further let me know.
