### ISSUE TITLE
Support for authentication using Firebase as it has free authentication as compared to Amazon cognito and Auth0

### ISSUE THREAD

**Issue by SatyamKr07** [nextauthjs/next-auth#2429]
### Description 📓

Firebase has unlimited free authentication for email and password and also for passwordless authentication using link sent to email address. Next Auth has nodemailer/sendgrid support for this purpose but it has some limit to DAU and after that it's paid service. 
So adding firebase auth system will surely be a of great use to all the developers and startups!🙌

### How to reproduce ☕️

It's a feature Request. Waiting to see it soon...

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Regarding this, I think you can use the credentials provider to utilize the email+password flow as long as the firebase api works server side.

The email login might be a bit trickier, because currently we generate our own login tokens and save it in our own database. That might need some more thinking.

**Comment by ndom91** [comment]
@SatyamKr07 we're in the process of adding a firebase adapter with the new adapter API (https://github.com/nextauthjs/adapters/pull/183), it uses firestore as a storage mechanism for your users though, not their auth provider, maybe that is interesting for you?

If you're main problem is running into limits with Email providers like sendgrid, you can also just use your gmail smtp settings, for example. I believe they allow 500 emails / day with free gmail accounts and 5000 emails per day with paid g suite / google workspace accounts. 

AWS SES (https://aws.amazon.com/ses) also has a free tier which allows 62,000 emails per month, so ~2000 per day.
