### ISSUE TITLE
REST API bearer tokens without JWT?

### ISSUE THREAD

**Issue by jaredpalmer** [nextauthjs/next-auth#2433]
### Question 💬

It appears that it is currently not possible for to use next-auth to secure a REST API that uses cors + bearer tokens, unless you use jwt. However, JWT is not feasible for my use case as I must have revokable sessions and (api keys) and I do not want to maintain a blocklist. 

It seems that `getSession({ req })` could easily extract the session token and fetch/load the session if it the request has `headers.authorization` set but no cookie.

I could do this on my own for now, but callbacks wouldn't fire. 

Please advise. 

### How to reproduce ☕️

try to make an authenticated request with an HTTP client, without JWT.

```ts
export default (req, res, next) => {
      const session = await getSession({ req });
      // this doesn't work unless the token is passed via cookie. 
      // it _should_ work if it is passed in authorization header though
      if (session) {
        req.user = session.user as Express.User;
        next();
      } else {
        next(getUnauthorized());
      }
    });
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Could you use the `getToken` method instead? It will extract the session from Authorization headers as well, for convenience:

https://github.com/nextauthjs/next-auth/blob/75ca097ff7585016264f4c6848e58da74c77aaf8/src/lib/jwt.js#L126

**Comment by jaredpalmer** [comment]
No. The `getToken` only works with JWTs. It will not load the session object because I am not using a JWT.

What you actually want on the sever is this:

```tsx
const getServerSession = ({ req, options }) => {   ​
 ​const token = getTokenFromCookie(req) || getTokenFromAuthHeader(req)
  ​if (options.jwt) {
    return options.callbacks.session(decode(token), token)
  }
   // lookup session and user directly in the database
  const session = adapter.getSessionByToken(token)
  const user = adapter.getUser(session.userId)
  return options.callbacks.session(session, user)
}
```

**Comment by balazsorban44** [comment]
I agree, I plan to add something like `getServerSession` when v4 is stable. :+1:

**Comment by balazsorban44** [comment]
@jaredpalmer this is under development now: https://github.com/nextauthjs/next-auth/issues/1535#issuecomment-931785322

**Comment by jaredpalmer** [comment]
Bump
