### ISSUE TITLE
'loading' is always true in production build

### ISSUE THREAD

**Issue by Gabsys** [nextauthjs/next-auth#2446]
### Description 🐜

The `loading` in `const [session, loading] = useSession()` is always returning true in production build. Works fine in development mode though.

### Is this a bug in your own project?

No

### How to reproduce ☕️

1)
```
import { useSession } from 'next-auth/client'

export default function Page() {
   const [session, loading] = useSession();

   if (loading) return null
   return (
      <p>Session valid</p>
   )
}
```

2) `npm run build`
3) `npm run start`

### Environment 🖥

 System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
    Memory: 810.82 MB / 1.94 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
  npmPackages:
    next: 10.2.3 => 10.2.3 
    next-auth: ^3.25.0 => 3.25.0 
    react: 17.0.2 => 17.0.2

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
I cannot reproduce this. You will need to provide a more detailed reproduction or I'm going to move this to discussions. You can use any of our CodeSandbox templates for convenience (it was available in the issue form you filled out.)

**Comment by Gabsys** [comment]
Managed to locate the culprit. Not NextAuth's issue but [a package's](https://github.com/azouaoui-med/react-pro-sidebar) css file that is imported which crashed the app for some reason.
