### ISSUE TITLE
Using session in react context

### ISSUE THREAD

**Issue by Gabsys** [nextauthjs/next-auth#2448]
### Question 💬

Has anyone successfully used `session` in React Context? It seems to always return undefined.

### How to reproduce ☕️

context/userRankContext.js :
```
import { useState, createContext, useContext, useEffect } from 'react';
import { useSession } from 'next-auth/client';


export const UserRankContext = createContext();

export async function useUserRankState() {
    const [session, loading] = useSession();
    const [userRank, setUserRank] = useState(99);


    useEffect(() => {
       console.log(session)
    }, [session])

    return {
        userRank
    }

}

export function useUserRank() {
    const userRank = useContext(UserRankContext);
    return userRank;
}
```

_app.js:
```

import { UserRankContext, useUserRankState } from '../context/userRankContext';
import { Provider } from 'next-auth/client'

function MyApp({ Component, pageProps }) {
  const userRank = useUserRankState();
return(
 <Provider session={pageProps.session}>
        <UserRankContext.Provider value={userRank}>
            <Component {...pageProps} />
        </UserRankContext.Provider>
    </Provider>)
}


export default MyApp
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by devrsi0n** [comment]
@Gabsys `useUserRankState` can only be used in the child component of `next-auth/client/Provider` to make it work, and you can't use the value of `useUserRankState` as your Context provider's value.

**Comment by Gabsys** [comment]
> @Gabsys `useSession` can only be used in the child component of `next-auth/client/Provider` to make it work, and you can't use the value of `useUserRankState` as your Context provider's value.

So placing <UserRankContext> under <Provider> should be correct?

And for can't use value of `useUserRankState` as Context provider's value, why not? :O It is working fine
