### ISSUE TITLE
Twitter Authentication - "Could not authenticate you" error

### ISSUE THREAD

**Issue by SteliosRammos** [nextauthjs/next-auth#2451]
### Description 🐜

When attempting to sign in with Twitter, I get the "Try signing in with a different account." error. The console does not output any error and the logs output a "get_authorization_url_error" and "signin_oauth_error" error both saying "Could not authenticate you." (see screenshots below).

### Is this a bug in your own project?

No

### How to reproduce ☕️

I used the `next-auth-example` project to try out NextAuth and followed the exact instructions in the documentation.

I have configured the Twitter App with the following callback URL: http://localhost:3000/api/auth/callback/twitter

In the .env.local, I set up the TWITTER_ID with the consumer key, the TWITTER_SECRET with the consumer secret key provided by the Twitter App and the NEXTAUTH_URL to http://localhost:3000.

I made no other change to the project.

### Screenshots / Logs 📽

<img width="525" alt="Screenshot 2021-07-29 at 20 38 41" src="https://user-images.githubusercontent.com/24457157/127547710-835b4305-92f7-4027-91bb-7275768c1c96.png">

<img width="333" alt="Screenshot 2021-07-29 at 20 39 03" src="https://user-images.githubusercontent.com/24457157/127547748-2e28092d-7622-4085-b4be-e26f5f92b343.png">

### Environment 🖥

  System:
    OS: macOS 12.0
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 754.36 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.5.0 - ~/.nvm/versions/node/v16.5.0/bin/node
    npm: 7.19.1 - ~/.nvm/versions/node/v16.5.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Safari: 15.0
  npmPackages:
    next: ^11.0.0 => 11.0.1 
    next-auth: latest => 3.27.3 
    react: ^17.0.2 => 17.0.2 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
There must be a configuration error somewhere.

At https://next-auth-example.vercel.app/ you can check that the Twitter login works as expected. It uses the `next-auth-example` repository code also. You must provide a proper reproduction if you need further help.
