### ISSUE TITLE
The redirects uses the default environment URL or need setting it?

### ISSUE THREAD

**Issue by IgorDePaula** [nextauthjs/next-auth#2456]
### Question 💬

I push my app to aws amplify, I register, but on login, on got error the redirect action redirect me to localhost and not to provided url.

### How to reproduce ☕️

https://develop.d1cwc8lbezfn59.amplifyapp.com/   -> my app

my auth config
```
import NextAuth from 'next-auth'
import Providers from 'next-auth/providers'
import {Auth} from 'aws-amplify'

export default NextAuth({
    pages: {
        error: "/login", // Changing the error redirect page to our custom login page
    },
    callbacks: {
        async session(session, token) {
            return token
        },
    },
    providers: [
        Providers.Credentials({
            name: "Credentials",
            async authorize(credentials) {
                try {
                    const user = await Auth.signIn(credentials.email, credentials.password)
                    if (user) {
                        const data = {
                           name: user.attributes.name, email: user.attributes.email, image:'asdasdasd',id:user.attributes.sub,
                        }
                        return data
                    }
                } catch (e) {
                    const errorMessage = e.message
                    throw new Error(errorMessage + "&email=" + credentials.email)
                }
            },
        }),
    ],
})
```

Try you register and after do login.

(I'm using cognito, after register, the cognito will send a code for verification for your email, and you need send this code...after this you can login)

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
You probably forgot to set the `NEXTAUTH_URL` environment variable. It is required in production:

https://next-auth.js.org/configuration/options#nextauth_url

**Comment by IgorDePaula** [comment]
No, I put this variable
![Captura de Tela 2021-07-30 às 09 02 33](https://user-images.githubusercontent.com/2833993/127650262-03d2a888-d258-4938-a9b0-b3749552bacf.png)

**Comment by balazsorban44** [comment]
It looks like it's not being picked up for some reason. Try to log the value server-side. Also, unless you deployed the site on a subpath, the `NEXTAUTH_URL` should be the canonical URL (remove /api/path)

**Comment by IgorDePaula** [comment]
I tried alread, but no success.

**Comment by IgorDePaula** [comment]
The repository need upload any .env file?

**Comment by IgorDePaula** [comment]
I'm using next 11 and, the next auth config is error page is be login, but redirects to error page, why?

**Comment by balazsorban44** [comment]
Really hard to say. Do you have a reproduction?

This is certainly not a problem in `next-auth`, as far as I can tell.
