### ISSUE TITLE
feature to add some payload to session at the time of  signin

### ISSUE THREAD

**Issue by ats1999** [nextauthjs/next-auth#2466]
## Requirement
My website has different user roles, like admin, ta, da,etc... At the time, when it'll call the API, i need those details. Curently i am getting those details form DB each time API calls. 

Now, i want to avoid the DB call because it can be simply included into session object. 

## What we can do
```js
async signIn(user, account, profile) {
      return {
        id, roles, etc..
     }
 }
```
At the time of signin, we can return some payload, which can be included into session object. 

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by matha-io** [comment]
Hello ! So you basically want the role property on the session object that you can access with `getSession` or `useSession` ?
If so, use the [`session` callback](https://next-auth.js.org/configuration/callbacks#session-callback) instead, you can then override data that will be inside the session !

**Comment by ats1999** [comment]
@matha-io 
That is the problem
```js
 async session(session, token) {
   // call every time in backend API routes
  // import { getSession } from "next-auth/client";

   // can't we avoid DB calls
    session.useRole = await getRoleFromDB(session.user);
    return session
  }
```

**Comment by balazsorban44** [comment]
How do you want to receive the session without receiving the session? I thin kwhat you are after is to extend the user object in the database at creation?

**Comment by robinofskii** [comment]
@balazsorban44 I think the link you wanted to provide @ats1999 with was this one, right?
https://next-auth.js.org/getting-started/typescript#module-augmentation

**Comment by balazsorban44** [comment]
I think the OP doesn't necessarily have a TS problem, so it feels irrelevant or at least not the full answer.
