### ISSUE TITLE
CallbackUrl after credential login use the wrong domain/URL from Vercel

### ISSUE THREAD

**Issue by heggemsnes** [nextauthjs/next-auth#2476]
### Question 💬

**Problem**

When trying to redirect correctly after logging in, I get redirected to the current deployment url in Vercel. I want to get redirected to the correct domain.

Example:

https://musikk-i-skolen.vercel.app/logg-inn (Logging in here)
https://musikk-i-skolen-r2t0djwyq-kult-byra.vercel.app (Get redirected here)
I want to be redirected to the specified domain, https://musikk-i-skolen.vercel.app/velkommen

// pages/logg-inn.js
```js
signIn("password-login", {
            email,
            password,
            // The page where you want to redirect to after a
            // successful login
            callbackUrl: `${process.env.NEXT_PUBLIC_FRONTEND_URL}/velkommen`,
          })
```
Everything shows up correctly in the POST request (https://musikk-i-skolen.vercel.app/api/auth/callback/password-login?) with the correct callback url.

I am logged in afterwards if I manually go to the "production domain".

If you need I can help to create a temporary account. Nothing is live yet.

**Version**
3.27.3

### How to reproduce ☕️

To Reproduce

Create credential login project

- Deploy to vercel
- Set callbackUrl to same domain (window.location.origin or .env variable)
- Login with a user
- See that you are redirected to wrong domain
- Expected behavior
- Being redirected to the correct callback

Additional context

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by sastraxi** [comment]
Hello, I'm wondering if `NEXT_PUBLIC_FRONTEND_URL` is an environment variable that you have created yourself (e.g. in `.env.local` or on the Vercel dashboard)? There is a built-in on, `NEXT_PUBLIC_VERCEL_URL` that might do what you're looking for instead: https://vercel.com/docs/environment-variables#system-environment-variables
