### ISSUE TITLE
maxAge received by jwt.encode / jwt.decode is different from defined on session.maxAge

### ISSUE THREAD

**Issue by raphaelpc** [nextauthjs/next-auth#2482]
### Description 🐜

According to the answer given by @iaincollins on https://github.com/nextauthjs/next-auth/issues/796#issuecomment-718765049:

> The default value for `jwt.maxAge` currently set to whatever the default `session.maxAge` is set to, technically you never need to set it or worry about it and can just set `session.maxAge`.

The bug is that the maxAge value sent to the [jwt.encode / jwt.decode functions](https://next-auth.js.org/configuration/options#jwt) always has the value "2592000", or 30 days (the default NextAuth maxAge), even when i set a diferent session.maxAge.

### Is this a bug in your own project?

No

### How to reproduce ☕️

```js
...
  session: {
    jwt: true,
    maxAge: 8 * 60 * 60, // 8 hours
  },
  secret: process.env.JWT_SECRET,
  jwt: {
    secret: process.env.JWT_SECRET,
    encode: async ({ secret, token, maxAge }) => {
      // maxAge is 2592000, and not 28800
      console.log('maxAge encode', maxAge);
      const encodedToken = jwt.sign({
        ...token,
        exp: Math.floor(Date.now() / 1000) + maxAge,
      }, secret);
      return encodedToken;
    },
    decode: async ({ secret, token, maxAge }) => {
      // maxAge is 2592000, and not 28800
      console.log('maxAge encode', maxAge);
      const verify = jwt.verify(token, secret) as JWT;
      return verify;
    },
  },
...
```

### Environment 🖥

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz  
    Memory: 4.92 GB / 15.78 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.19041.423.0
    Internet Explorer: 11.0.19041.1
  npmPackages:
    react: ^17.0.2 => 17.0.2 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by raphaelpc** [comment]
Some more info:

From my tests, i could verify that, in this code:

https://github.com/nextauthjs/next-auth/blob/86baefdd9df9246669d4f788aaab4774605c256a/src/server/routes/session.js#L11-L25

The "jwt" const that comes from "req.option" has an attribute with name maxAge and value 2592000, that is different from the value of const "sessionMaxAge".
I tried doing like that, and, tha way, the value i receive in the "jwt" const is "correct":

```
...
  jwt: {
    secret: process.env.JWT_SECRET,
    maxAge: 8 * 60 * 60, // 8 hours,
    encode: async ({ secret, token, maxAge }) => {
      ...
    },
    decode: async ({ secret, token, maxAge }) => {
      ...
    },
  },
...
```

This works, but:

- There is no documentation about that "masAge" property on jwt;
- That goes agains what @iaincollins described on the issue i referenced earlier.

Thanks in advance!

**Comment by ThangHuuVu** [comment]
I believe this was fixed in https://github.com/nextauthjs/next-auth/issues/6829
