### ISSUE TITLE
Prisma Schema Change History contains wrong info

### ISSUE THREAD

**Issue by nijuyr** [nextauthjs/next-auth#2492]
### Question 💬

If you check the page in the link
https://next-auth.js.org/adapters/prisma
Change History section removes the following line
-  compoundId         String    @unique @map(name: "compound_id")

If you remove this compoundId in your schema you get an error.
The suggests that it is a legacy code but even 4.0.0 doesn't work without it?
Is it under progress? then perhaps the document page was updated too early..

### How to reproduce ☕️

https://github.com/nextauthjs/next-auth/commit/704ded53107ede265c5990f0901595c6be782c6e#diff-40edff82c91b2c1df22a1d8f8b5936af199a0593f9d233fe42eb146f7a7c5e78R179
Remove compoundId in your prisma schema

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
If you compare the two versions, it is actually not required in the newer `@next-auth/prisma-adapter`, so I think the docs is correct. See the difference:

https://github.com/nextauthjs/adapters/blob/main/packages/prisma-legacy/prisma/schema.prisma#L12

https://github.com/nextauthjs/adapters/blob/31181b17648aafc7b85c073d2ffc7c47ab24e49f/packages/prisma/prisma/schema.prisma#L20
