### ISSUE TITLE
Production error

### ISSUE THREAD

**Issue by sourabhmahato** [nextauthjs/next-auth#2504]
### Description 🐜

Nextuth doesn’t create next.auth session token in production and redirects to local host on signin with credentials. I can’t get what’s wrong.

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

It doesn’t signin in production and my next auth_url is set to domain name 

### Environment 🖥

It has all the required packages 

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by sastraxi** [comment]
Hello @sourabhmahato! Can you provide the following?

- a repository / gist / code sample that shows this problem
- details of your production environment: how are environment variables being handled? Have you verified they are being set correctly?

**Comment by sourabhmahato** [comment]
![image](https://user-images.githubusercontent.com/54588817/128661115-459c22c9-91f1-4dc7-84a1-c440b88bb3f6.png)
this is my .env for production.
this is my [...nextauth] file:
`providers: [
    Providers.Credentials({
     
      name: "Credentials",
      credentials: {
        username: { label: "Username", type: "text", placeholder: "username" },
        password: {
          label: "Password",
          type: "password",
          placeholder: "password",
        },
      },
      async authorize(credentials, req) {
        console.log(credentials.username)
        // console.log(credentials)
        try {
          const user = {
            name: credentials.username,
            password: credentials.password,
          }
          if (user.name === "adminHR" || user.name === "adminRecipe") {
            console.log(user, "user next auth")
            if (user.password === "123hr" || user.password === "123recipe") {
              return user
            }
          } else {
            return "not user"
          }
        } catch (error) {
          if (error) {
            console.log(error)
            Promise.reject(new Error("Wrong username password"))
          }
        }
      },
    }),
  ],
  callbacks: {
    /**
     * @param  {object} user     User object
     * @param  {object} account  Provider account
     * @param  {object} profile  Provider profile
     * @return {boolean|string}  Return `true` to allow sign in
     *                           Return `false` to deny access
     *                           Return `string` to redirect to (eg.: "/unauthorized")
     */
//     async signIn(user, account, profile) {
//       const isAllowedToSignIn = true
//       if (isAllowedToSignIn) {
//         return true
//       } else {
//         // Return false to display a default error message
//         return false
//         // Or you can return a URL to redirect to:
//         // return '/unauthorized'
//       }
//     },
    async redirect(url, baseUrl) {
     return "/database/data-display"
      // url.startsWith(baseUrl) ? baseUrl : url
    },
//     async session(session, token) {
//       // Add property to session, like an access_token from a provider.
//       session.accessToken = token.accessToken
//       return session
//     },
 },
  jwt: {
    signingKey:
      '{"kty":"oct","kid":"1v4AfpYNR0Amh1zRK3AEUZeHkmY-DzVeZhEeVMIMHPw","alg":"HS512","k":"S8p6tVl8oUdPRB2vZCQ_MN16FsGU8i9LlkdzACWAmdM"}',
    encryptionKey:
    '{"kty":"oct","kid":"6OSGwATdP2e2LfMpG1VEqwt5mIVZds2aPU8x98zlH_A","use":"enc","alg":"A256GCM","k":"J1T2jHuH9mJ9kgnk_KDdYGqnxpLUymrBaM6Z0hWLv5c"}',
  },
  
}`
Also when I am clicking on sign in with credentials in production with username password I get this url http://localhost:3000/api/auth/signin?csrf=true , while it works fine in local enviroment

**Comment by sastraxi** [comment]
Have you confirmed that your environment variables are actually getting through to your code? How are you hosting it?

**Comment by sourabhmahato** [comment]
I am hosting it on digital ocean , with docker. Also how do I check if it is going through the code. I could check it in local with console.log, but how in production.

**Comment by sastraxi** [comment]
I'm not familiar enough with digital ocean to know exactly how to confirm your code's environment, but a fail-safe way would be to `console.log` as well and just look through whatever they give you to get at stdout (e.g. ssh / `docker logs`).

By the way, you might want to make sure there are no secrets in your message about; it appears you have `signingKey` and `encryptionKey` pasted in alongside your code.

**Comment by sourabhmahato** [comment]
![image](https://user-images.githubusercontent.com/54588817/128665767-194cbf4f-ad03-4859-8a5e-ba82152a32dc.png)
I am getting this , even after setting my next_auth_url to www.example.com

**Comment by sourabhmahato** [comment]
@sastraxi thanks, it got resolved I had to set .env explicitly in docker. It was issue related to docker.

**Comment by sourabhmahato** [comment]
Hello @sastraxi , now I am able to sign in in now on production but whenever I go back to login page (client side) I get this 
![image](https://user-images.githubusercontent.com/54588817/128681835-f4ebc3c1-c32c-43a1-9fe2-e77c8cd57f53.png)

**Comment by sastraxi** [comment]
@sourabhmahato I'm glad to hear you figured out the `env` stuff! The page you're seeing represents an unhandled javascript exception on the client-side, I believe. You should be able to open developer tools and refresh the page to see the error, or use a frontend monitoring tool like logrocket.

For now, we'll keep this issue closed -- if you see evidence that next-auth is acting up, feel free to open a new issue or start a discussion.

**Comment by Rizki36** [comment]
@sourabhmahato hey i got error like this, how you fix it ?
