### ISSUE TITLE
Custom claims not in scope

### ISSUE THREAD

**Issue by advatar** [nextauthjs/next-auth#2510]
### Question 💬

I am using a custom provider like so:

```
{
      id: "svipe",
      name: "Svipe",
      type: "oauth",
      version: "2.0",
      scope: "openid profile",
      idToken: true,
      params: { grant_type: "authorization_code" },
      accessTokenUrl: "https://api.svipe.com/oidc/v1/token",
      requestTokenUrl: "https://api.svipe.com/oidc/v1/authorize",
      authorizationUrl: "https://api.svipe.com/oidc/v1/authorize?response_type=code",
      profileUrl: "https://api.svipe.com/oidc/v1/userinfo",
      async profile(profile, tokens) {
        return {
          id: profile.svipeid,
          name: profile.name,
          email: profile.email
        }
      },
      clientId: process.env.SVIPE_ID,
      clientSecret: process.env.SVIPE_SECRET
    },
```

This is an OIDC provider and the configuration is here [](https://api.svipe.com/oidc/v1/.well-known/openid-configuration)

Now, this provider has support for the common OIDC claims but also many custom such as passport document_number and such. How do I request this? Using passport and the openid-client strategy I would do this:

```
   var params = {
    claims: {
      device_token: {essential: true},
      issuing_country: {essential: true},
      document_number: {essential: true},
      birthdate: {essential: true},
      person_number: {essential: true},
      email: false,
      phone: false,
      given_name: {essential: true},
      family_name: {essential: true},
      portrait: {essential: true},
      pkpass: req.session.pkpass
     }
    };

    passport.use(
      'oidc',
      new Strategy({ client, params }, (tokenSet, userinfo, done) => {
        var claims = tokenSet.claims();
        claims.id_token = tokenSet.id_token;
        return done(null, claims);
      })
    );

```

How can I do the same with NextAuth?

### How to reproduce ☕️

Nothing to reproduce, this is a "how to" question.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by advatar** [comment]
Config URL got lost https://api.svipe.com/oidc/v1/.well-known/openid-configuration

**Comment by advatar** [comment]
It would btw be nice to just specify the that configuration link for custom Providers.

**Comment by advatar** [comment]
Btw, I am working on this https://certify.exchange/ which you can try if you want to have your Covid certificates in Apple Wallet (or equivalent on Android). Currently I am logging in via separate service running node/express/passport but would like to consolidate and keep it all in nextjs.

**Comment by balazsorban44** [comment]
The current implementation isn't aiming to support OIDC, but v4 (hopefully coming out soon) does! You can see an example for the Twitch provider.

https://github.com/nextauthjs/next-auth/blob/next/src/providers/twitch.js

**Comment by advatar** [comment]
Cool. I actually solved it temporarily like this:

```
authorizationUrl: "https://api.svipe.com/oidc/v1/authorize?response_type=code&claims="+encodeURIComponent(JSON.stringify({
        device_token: {essential: true},
        issuing_country: {essential: true},
        document_number: {essential: true},
        birthdate: {essential: true},
        person_number: {essential: true},
        email: false,
        phone: false,
        given_name: {essential: true},
        family_name: {essential: true},
        portrait: {essential: true}
       })),
```

**Comment by balazsorban44** [comment]
Awesome!
