### ISSUE TITLE
Why is mongodb listed as peerOptionalDependency?

### ISSUE THREAD

**Issue by 4nduril** [nextauthjs/next-auth#2522]
### Question 💬

I use mongodb explicitly in my application and also want to use it for next-auth. The version of `mongodb` in my app is 4.1.0. Next-Auth will not accept that stating that the version installed (4.1.0) doesn't match with the constraint of its optionalPeerDependency declaration (^3.5.9). 

As far as I can see is `next-auth` (the package) not even using mongodb directly. Why would it then define an optionalPeerDependency which breaks the app it's used in? If it was a real dep then npm could just resolve it and install 3.5.9 deeper in the tree. 

If there's no actual need for this I would propose to just remove it from package.json and let adapters handle it explicitly.

### How to reproduce ☕️

Just clone the example repo, install mongodb@4.1.0 and use a mongodb connection string.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
This is because the builtin typeorm adapter is still part of the core as of v3. The next major version will require users to explicitly install adapters they need and this non-standard optionalPeerDependencies will be gone with it.

**Comment by 4nduril** [comment]
I understand that this will be gone with next major version. Thank you for answering!
Still I would like to understand why it is the way it is: 
`require_optional` which throws the error is used in `@next-auth/typeorm-legacy-adapter` not in `next-auth`. As is `mongodb`. But the declaration of peerOptionalDependencies is done in `next-auth`. If you have time for this I would appreciate an explanation very much.

**Comment by balazsorban44** [comment]
`require_optional` and `peerOptionalDependencies` are very intricate non-standard things, and I pretty much am just afraid to change/remove them, in case they would break something I cannot forsee :shrug:. I hate them to be honest 😅

v4 is hopefully out in a few weeks though :crossed_fingers:
