### ISSUE TITLE
Can't use `withSentry` error tracking

### ISSUE THREAD

**Issue by nicholaschiang** [nextauthjs/next-auth#2532]
### Question 💬

I want to use the `withSentry` wrapper for [Sentry error tracking](https://docs.sentry.io/platforms/javascript/guides/nextjs/) in API routes. However, I always encounter a TypeScript error when trying to wrap the `pages/api/auth/[...nextauth].ts` file:

```typescript
import NextAuth from 'next-auth';
import { withSentry } from '@sentry/nextjs';

export default withSentry(NextAuth(config));
```

Doing that results in the following error:

```
Argument of type 'void | Promise<void>' is not assignable to parameter of type 'NextApiHandler<any>'.
  Type 'void' is not assignable to type 'NextApiHandler<any>'.
```

That error is because the `NextAuth` function returns the `ReturnType<NextApiHandler>` which is either `void` or `Promise<void>`. Instead, it'd be nice if the `NextAuth` function would return the `NextApiHandler` itself so that I could wrap it in `withSentry` as shown above (without any TypeScript errors).

### How to reproduce ☕️

See question description.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
API handlers doesn't return anything.

**Comment by amosbastian** [comment]
I get `API resolved without sending a response for /api/auth/session, this may result in stalled requests.` when adding `withSentry` to `[...nextauth].ts`.

**Comment by mongkuen** [comment]
Ran into this problem as well. I'd suggest you report your own events like so 
```typescript
// [...nextAuth].ts

import * as Sentry from '@sentry/nextjs'

export default NextAuth({
  ...config,
  logger: {
    error(code, metadata) {
      Sentry.captureException({ code, metadata })
    },
    warn: () => {
      // no-op
    },
    debug: () => {
      // no-op
    },
  },
})
```
<hr />
If you really insisted on using the `withSentry` middleware then you have to handle the promise that is returned by NextAuth so something like:

```typescript
// [...nextAuth].ts

import { withSentry } from '@sentry/nextjs'

export default withSentry((req, res) => {
  return new Promise((resolve: (value: void) => void, reject) => {
    const nextAuth = NextAuth(req, res, {
      ...config,
      logger: {
        error(code, metadata) {
          reject({ code, metadata })
        },
        warn: () => {
          // no-op
        },
        debug: () => {
          // no-op
        },
      },
    })

    nextAuth && nextAuth.then(() => {
      resolve()
      return
    })
  }).catch((err) => {
    throw err
  })
})
```
While everything will work, Next will still complain about unsent responses and possible stalled requests. 

Also while catching the promise rejection and throwing it again in the `catch` creates an uncaught exception that Sentry will report... it's not recommended.
