### ISSUE TITLE
Support for client authentication using private key

### ISSUE THREAD

**Issue by androa** [nextauthjs/next-auth#2535]
### Description 📓

`private_key_jwt` is one of client authentication methods defined in [OpenID Connect Core 1.0, 9. Client Authentication.](https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication)

Currently NextAuth.js only supports authentication through a shared secret with client_id and client_secret.

Our identity provider only supports authentication through private keys.

### Example
```
import NextAuth from 'next-auth'
import Providers from 'next-auth/providers'

export default NextAuth({
  providers: [
    Providers.GitHub({
      clientId: process.env.PROVIDER_ID,
      clientKeys: JSON.parse(process.env.PROVIDER_KEYS);
    }),
  ],
})
```

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
This (and generally better OIDC compliance) is going to be supported in v4. See #1846, #2411

Aiming for stable release in a few weeks, but there is already a `next` channel if you want to test it out. The migration guide is on the way #2350

**Comment by anthanv** [comment]
Has NextAuth.js added support for the client authentication method using private_key_jwt yet?  I checked 4.3.4 but still appears to be missing.

**Comment by leemcmullen** [comment]
@anthanv Hey. Turns out there are a couple of issues with NextAuth and private_key_jwt auth. I've attempted to address them in this PR: https://github.com/nextauthjs/next-auth/pull/11132 which is awaiting review at the moment.

Adding it here in case it's of any use.
