### ISSUE TITLE
JWTs must have three components

### ISSUE THREAD

**Issue by machmielewski** [nextauthjs/next-auth#2538]
### Description 🐜

Hi when I'm trying to pull the jwt accestoken I have error: 

JWTs must have three components

I've ussed snippet from documentation. 

I'm using Google auth with firebase. 

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

```
import jwt from 'next-auth/jwt'

const secret = process.env.GOOGLE_SECRET

export default async (req, res) => {
  const token = await jwt.getToken({ req, secret })
  if (token) {
    // Signed in
    console.log('JSON Web Token', JSON.stringify(token, null, 2))
  } else {
    // Not Signed in
    res.status(401)
  }
  res.end()
}
```

response:
```
JWTMalformed: JWTs must have three components
.....
 {
  code: 'ERR_JWT_MALFORMED'
}

```

### Environment 🖥

  System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Memory: 106.19 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
  Browsers:
    Brave Browser: 91.1.26.74
    Chrome: 92.0.4515.131
    Safari: 14.1.1
  npmPackages:
    next: 11.0.1 => 11.0.1 
    next-auth: ^3.27.3 => 3.27.3 
    react: 17.0.2 => 17.0.2 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
the secret must be the same as the secret in your NextAuth config

https://next-auth.js.org/configuration/options#secret

NOTE, it is not the same as your provider's secret!

**Comment by machmielewski** [comment]
Hi,

I've changed my config a bit:

```
export default NextAuth({
  providers: [
    Providers.Google({
      clientId: process.env.GOOGLE_CID,
      clientSecret: process.env.GOOGLE_SECRET
    })
    ],
    adapter: FirebaseAdapter(firestore),
    secret: process.env.SECRET
})
```

Then I'm using the same value in the getToken method:

```
const secret = process.env.SECRET

export default async (req, res) => {
  const token = await jwt.getToken({ req, secret })
...
```
But still facing the same problem :(

Mateusz Chmielewski

Cloud Architect

Phone: 71 382 20 00

https://www.linkedin.com/in/mateuszchmielewski/

**Comment by balazsorban44** [comment]
Could you please create a simple reproduction with the CodeSandbox template we provide in the issue form? 🙏

**Comment by machmielewski** [comment]
I'm struggling a bit with the external url OAuth configuration 😅. But it
looks like these:

https://codesandbox.io/s/crazy-booth-dle4p


Mateusz Chmielewski

Cloud Architect

Phone: 71 382 20 00

https://www.linkedin.com/in/mateuszchmielewski/

**Comment by balazsorban44** [comment]
⚠ You should not publish your secrets publicly! You **MUST** immediately change those secrets, because you probably already have been compromised. I was only thinking of your code to be reproduced

**Comment by machmielewski** [comment]
There are dummy secrets for reproduce purpose :)

**Comment by balazsorban44** [comment]
Could you tell me how to reproduce your issue?

**Comment by machmielewski** [comment]
Just try to use getToken method.

**Comment by balazsorban44** [comment]
I did, and the issue did not occur.

**Comment by machmielewski** [comment]
Hmm, so weird anyway, if it works for you, we can close this. Sorry for
wasting your time :(

Mateusz Chmielewski

Cloud Architect

Phone: 71 382 20 00

https://www.linkedin.com/in/mateuszchmielewski/

**Comment by balazsorban44** [comment]
Not wasting my time! 😉 If you find a way to reliably reproduce this issue, I will be happy to look at it again!
