### ISSUE TITLE
Providers Without API Routes?

### ISSUE THREAD

**Issue by ellioseven** [nextauthjs/next-auth#2558]
### Question 💬

I'm looking to build a static Next.js application and I can see immediately that API routes are required. Is it possible to implement NextAuth.js without any server side processing? Apologies if this has been asked before, but I can't seem to find info in the issue queue or documentation.

### How to reproduce ☕️

NA

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
No, a backend environment is an absolute necessity for NextAuth.js. We plan to support other frameworks though. #2294
