### ISSUE TITLE
Document `/api/auth` routes

### ISSUE THREAD

**Issue by nicholaschiang** [nextauthjs/next-auth#2567]
### Question 💬

I couldn't find a "Documentation" issue template, so I thought that a question was the next best thing.

Could you please document the various `/api/auth` routes (e.g. what they do, what data they need to receive, etc)?

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
https://next-auth.js.org/getting-started/rest-api
