### ISSUE TITLE
Discord provider always sending the same data, even with different scopes

### ISSUE THREAD

**Issue by EGGamer** [nextauthjs/next-auth#2576]
### Description 🐜

So these couple of days I tried to find a way to get additional data from the user using the Discord provider. Currently, as we all know, currently only the email, the name and the image get saved onto the session.

So in theory, as the documentation says, we can override what does get passed to the profile in the providers. I just did a test to know what does Next-auth get in the provider profile from Discord's API, and even if we add additional scopes, or even remove some of them, it always sends the same data, it doesn't change. Because of this, we can't add new stuff to the profile, because basically, it isn't there.

In the past, I did stuff with authentication with Discord, and I know for a fact that the provider profile should pass everything we ask in the scopes. But with next-auth it doesn't, so I believe it's a next-auth bug.

### Is this a bug in your own project?

No

### How to reproduce ☕️

This is the options in `[...nextauth].js`:

```js
const options = {
  providers: [
    Providers.Discord({
      clientId: process.env.DISCORD_CLIENT_ID,
      clientSecret: process.env.DISCORD_CLIENT_SECRET,
      scope: "email identify guilds",
      profile(profile) {
        console.log(JSON.stringify(profile)); //This part is just a test to know what we get from the provider profile.
        return {};
      },
    }),
  ],
  database: process.env.DATABASE_URL,
};
```

And the data we get is always the following even if we add or remove scopes:

```json
{
"id":"300537378991505418",
"username":"EG Gamer",
"avatar":"3fce5a1f73a33cf1886873f6b1e516fb",
"discriminator":"7747",
"public_flags":640,
"flags":640,
"banner":null,
"banner_color":"#18191c",
"accent_color":1579292,
"locale":"en-GB",
"mfa_enabled":true,
"email":"*my email here*",
"verified":true
}
```

### Screenshots / Logs 📽

These are the logs that I get when DEBUG is set to true:

```
[next-auth][debug][oauth_callback_protection] Added state to authorization params {
  state: 'cab13b5b22d649208776522bd0d344e77e4031e885811a6b32eefec85f6f7653'
}
[next-auth][debug][get_authorization_url] https://discord.com/api/oauth2/authorize?response_type=code&prompt=none&scope=email%20identify%20guilds&state=cab13b5b22d649208776522bd0d344e77e4031e885811a6b32eefec85f6f7653&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fauth%2Fcallback%2Fdiscord&client_id=877609104493936692
[next-auth][debug][oauth_callback_protection] Comparing received and expected state {
  state: 'cab13b5b22d649208776522bd0d344e77e4031e885811a6b32eefec85f6f7653',
  expectedState: 'cab13b5b22d649208776522bd0d344e77e4031e885811a6b32eefec85f6f7653'
}
[next-auth][debug][profile_data] {
  id: '300537378991505418',
  username: 'EG Gamer',
  avatar: '3fce5a1f73a33cf1886873f6b1e516fb',
  discriminator: '7747',
  public_flags: 640,
  flags: 640,
  banner: null,
  banner_color: '#18191c',
  accent_color: 1579292,
  locale: 'en-GB',
  mfa_enabled: true,
  email: '*my email*',
  verified: true
}
[next-auth][debug][oauth_callback_response] {
  profile: {
    id: '300537378991505418',
    name: 'EG Gamer',
    image: 'https://cdn.discordapp.com/avatars/300537378991505418/3fce5a1f73a33cf1886873f6b1e516fb.png',
    email: '*my email*'
  },
  account: {
    provider: 'discord',
    type: 'oauth',
    id: '300537378991505418',
    accessToken: '*my accessToken*',
    accessTokenExpires: null,
    refreshToken: '*my refreshToken*',
    idToken: undefined,
    access_token: '*my accessToken*',
    expires_in: 604800,
    refresh_token: '*my refreshToken*',
    scope: 'email identify guilds',
    token_type: 'Bearer'
  },
  OAuthProfile: {
    id: '300537378991505418',
    username: 'EG Gamer',
    avatar: '3fce5a1f73a33cf1886873f6b1e516fb',
    discriminator: '7747',
    public_flags: 640,
    flags: 640,
    banner: null,
    banner_color: '#18191c',
    accent_color: 1579292,
    locale: 'en-GB',
    mfa_enabled: true,
    email: '*my email*',
    verified: true,
    image_url: 'https://cdn.discordapp.com/avatars/300537378991505418/3fce5a1f73a33cf1886873f6b1e516fb.png'
  }
}
[next-auth][debug][typeorm_legacy__get_user_by_provider_account_id] discord 300537378991505418
[next-auth][debug][typeorm_legacy__get_user_by_provider_account_id] discord 300537378991505418
[next-auth][debug][typeorm_legacy__create_session] User {
  id: 6120cff06e483e32ecb0068d,
  name: 'EG Gamer',
  email: '*my email*',
  image: 'https://cdn.discordapp.com/avatars/300537378991505418/3fce5a1f73a33cf1886873f6b1e516fb.png',
  createdAt: 2021-08-21T10:05:36.395Z,
  updatedAt: 2021-08-21T10:05:36.395Z
}
[next-auth][debug][typeorm_legacy__get_session] 6761c46db1d3504db23718a663887eff4e2b6979cde74c3569e0aebba91e55a3
[next-auth][debug][typeorm_legacy__update_session] Session {
  userId: 6120cff06e483e32ecb0068d,
  expires: 2021-09-20T10:05:47.529Z,
  sessionToken: '*sessionToken*',
  accessToken: '*accessToken*',
  id: 6120cffb6e483e32ecb00690,
  createdAt: 2021-08-21T10:05:47.529Z,
  updatedAt: 2021-08-21T10:05:47.529Z
}
[next-auth][debug][typeorm_legacy__get_user] 6120cff06e483e32ecb0068d
```

### Environment 🖥

  System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz
    Memory: 8.17 GB / 15.96 GB

  Binaries:
    Node: 12.18.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD

  Browsers:
    Chrome: 92.0.4515.159
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.73)

  npmPackages:
    next: 11.1.0 => 11.1.0
    next-auth: ^3.28.0 => 3.28.0
    react: 17.0.2 => 17.0.2

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
do you have a reproduction maybe? what data don't you get that you wished for?

**Comment by EGGamer** [comment]
@balazsorban44 So for example, in another project of mine (using Express and Passport) when retrieving the profile with these scopes (`email identity connections`) I get the following response (the one I'd like to get):


```json
{
    "id":"300537378991505418",
    "username":"EG Gamer",
    "avatar":"3fce5a1f73a33cf1886873f6b1e516fb",
    "discriminator":"7747",
    "public_flags":640,
    "flags":640,
    "banner":null,
    "banner_color":"#18191c",
    "accent_color":1579292,
    "locale":"en-GB",
    "mfa_enabled":true,
    "email":"*my email*",
    "verified":true,
    "provider":"discord",
    "accessToken":"*accessToken*",
    "connections":[
        {
            "type":"battlenet",
            "id":"EGGamer#21737",
            "name":"EGGamer#21737",
            "visibility":1,
            "friend_sync":false,
            "show_activity":true,
            "verified":true
        },
        {
            "type":"github",
            "id":"40073654",
            "name":"EGGamer",
            "visibility":1,
            "friend_sync":false,
            "show_activity":true,
            "verified":true
        }
    ],
    "fetchedAt":"2021-08-21T12:32:03.530Z"
}
```

As you can see, next auth only got some of this stuff, but not all of it. (In the original post I used guilds instead of connections, but it should appear exactly the same as connections)

**Comment by balazsorban44** [comment]
Passport has a different api, so you cannot expect it to be exactly the same (eg the access token is not returned through  the profile).

If you had a CodeSandbox or a repository with a simple reproduction, I would be happy to look more into it.

**Comment by EGGamer** [comment]
> Passport has a different api, so you cannot expect it to be exactly the same (eg the access token is not returned through the profile).

Yeah I understand that, but It's odd that Next-auth doesn't provide everything.

> If you had a CodeSandbox or a repository with a simple reproduction, I would be happy to look more into it.

A next-auth repo or a Passport repo?

**Comment by balazsorban44** [comment]
Your project, or a minimal reproduction of the bug in next-auth, where you provide a scope and the result is not as you would expect. would be nice to have something I can clone/run myself and verify.

**Comment by EGGamer** [comment]
Here you have:

https://codesandbox.io/s/great-montalcini-5rhv7

**Comment by balazsorban44** [comment]
Looking more into this looks like both `guilds` and `connections` are actually additional endpoints you can call to retrieve more info:

https://discord.com/developers/docs/resources/user#get-current-user-guilds

https://discord.com/developers/docs/resources/user#get-user-connections

**Comment by JoeAshworth** [comment]
@EGGamer do you want to work on a PR for this? I don't see a reason not to fix this and have no idea why it's been marked as wont fix.

**Comment by balazsorban44** [comment]
@JoeAshworth see my comment above... 😅

https://github.com/nextauthjs/next-auth/issues/2576#issuecomment-903187771

you can do it in user land if necessary, but we won't be accepting changes for the default profile.

**Comment by JoeAshworth** [comment]
Unfortunately it doesn't seem to be possible to set a custom provider right now, even with the same setup as defined [here](https://github.com/nextauthjs/next-auth/blob/main/src/providers/discord.js).

```js
export default NextAuth({

  providers: [
    {
      id: "discord",
      name: "Discord",
      type: "oauth",
      version: "2.0",
      scope: "identify email guilds",
      params: { grant_type: "authorization_code" },
      accessTokenUrl: "https://discord.com/api/oauth2/token",
      authorizationUrl:
      "https://discord.com/api/oauth2/authorize?response_type=code&prompt=none",
      profileUrl: "https://discord.com/api/users/@me",
      profile(profile) {
        if (profile.avatar === null) {
          const defaultAvatarNumber = parseInt(profile.discriminator) % 5
          profile.image_url = `https://cdn.discordapp.com/embed/avatars/${defaultAvatarNumber}.png`
        } else {
          const format = profile.avatar.startsWith("a_") ? "gif" : "png"
          profile.image_url = `https://cdn.discordapp.com/avatars/${profile.id}/${profile.avatar}.${format}`
        }
        return {
          id: profile.id,
          name: profile.username,
          image: profile.image_url,
          email: profile.email,
        }
      },
      clientId: process.env.DISCORD_ID,
      clientSecret: process.env.DISCORD_SECRET
    }
  ],
  ```
  Which returns:
  
  ```message: "Cannot read property 'url' of undefined"```

The same error as https://github.com/nextauthjs/next-auth/issues/2735.

**Comment by JoeAshworth** [comment]
@balazsorban44 The issue right now is even if you set the scopes in the Discord Provider, the scopes aren't passed across to the authorization URL. 

If I wanted to do this:
```js
export default NextAuth({
  providers: [
    DiscordProvider({
      clientId: process.env.DISCORD_ID,
      clientSecret: process.env.DISCORD_SECRET,
      scope: "guild identify email",
      profile(profile, tokens) {

        // Request to /users/@me/guilds
        // Set guildArray

        return {
          id: profile.id,
          name: profile.name,
          email: profile.email,
          image: profile.picture
          // guilds: guildArray
        }
      }
    }),
  ],
  ```
  
  I couldn't, as the tokens that are passed back only have the identify and email scopes.

**Comment by balazsorban44** [comment]
using v4? https://next-auth.js.org/getting-started/upgrade-v4#8-providers

**Comment by JoeAshworth** [comment]
Yeah, updated to v4 yesterday. 
`"next-auth": "4.0.0-beta.2",`

Here's my complete next auth file.

```js
import NextAuth from "next-auth"
import DiscordProvider from "next-auth/providers/discord"

export default NextAuth({

  providers: [
    DiscordProvider({
      clientId: process.env.DISCORD_ID,
      clientSecret: process.env.DISCORD_SECRET,
      scope: "identify guild email",
      profile(profile, tokens) {
        
        return {
          id: profile.id,
          name: profile.name,
          email: profile.email,
          image: profile.picture
        }
      }
    }),
  ],

  secret: process.env.SECRET,

  pages: {
    signIn: '/auth/login',  // Displays signin buttons
    // signOut: '/auth/signout', // Displays form with sign out button
    // error: '/auth/error', // Error code passed in query string as ?error=
    // verifyRequest: '/auth/verify-request', // Used for check email page
    // newUser: null // If set, new users will be directed here on first sign in
  },

  callbacks: {
    async signIn(user, account, profile) { return true },
    async redirect(url, baseUrl) { return baseUrl },
    // async session(session, user) { return session },
    // async jwt(token, user, account, profile, isNewUser) { return token }
  },

  debug: true,
})
```

**Comment by balazsorban44** [comment]
API changed, check the migration guide link and the linked PRs in it

**Comment by SteveCookTU** [comment]
According to the docs for v4, setting the scope in the provider (as seen in the post above) should override the default. This doesn't seem to be the case for the discord provider as it's still only providing a token with the default scope.
