### ISSUE TITLE
`logIn()` is stuck on `/api/auth/providers` while using Credentials provider

### ISSUE THREAD

**Issue by asobirov** [nextauthjs/next-auth#2582]
### Description 🐜

Next-auth logIn() is stuck endlessly on /api/auth/providers as can be seen [here.](https://i.stack.imgur.com/7kMRa.png)

`async authorize(credentials)` part doesn't seem to be executed at all, as none of the `console.log` seem to be working.

**/pages/api/auth/[...nextauth].js**
```
import Providers from 'next-auth/providers';
import connectDB from '../../../lib/connectDB';
import User from '../../../models/User';

export default NextAuth({
    //Configure JWT
    session: {
        jwt: true,
    },
    //Specify Provider
    providers: [
        Providers.Credentials({
            async authorize(credentials) {
                console.log('====THIS MESSAGE IS NOT SHOWN ON CONSOLE====')
                connectDB();
                const user = await User.findOne({
                    email: credentials.email,
                });

                console.log(user);

                if (user & (await user.matchPassword(credentials.passowrd))) {
                    client.close();
                    return { email: user.email };
                }
                client.close();
                return null;
            },
        }),
    ],
});

```
**Client** Side
```
  const onLogin = async (values) => {
        const status = await signIn('credentials', {
            redirect: false,
            email: values.email,
            password: values.password,
        });
        console.log('Login Status: ', status);
        // This is not logged as well, due to /api/auth/providers being stuck
  }
```

This question on [stackoverflow](https://stackoverflow.com/questions/68885410/next-auth-login-is-stuck-on-api-auth-providers-while-using-credentials-provid).

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

Code to reproduce the issue has been provided above

### Screenshots / Logs 📽

 [Screenshot from browser console](https://i.stack.imgur.com/7kMRa.png)

No errors on next console

### Environment 🖥

  System:
    OS: macOS 12.0
    CPU: (8) arm64 Apple M1
    Memory: 152.66 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.2 - /opt/homebrew/bin/node
    Yarn: 3.0.0 - /opt/homebrew/bin/yarn
    npm: 7.20.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Safari: 15.0

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
If `console.log('====THIS MESSAGE IS NOT SHOWN ON CONSOLE====')` is not shown, the problem happens before the `authorize()` call.

We will need more information to be able to help you. Do you have a runnable reproduction?

What is shown when you visit http://localhost:3000/api/auth/providers directly?
