### ISSUE TITLE
Signin using component in situ instead of opening a signin page

### ISSUE THREAD

**Issue by madeinspace** [nextauthjs/next-auth#2590]
### Description 📓

Like the title say, it would be nice to have the option of signing in situ with a component instead of being redirected to a dedicated signing page. Thanks for considering

### How to reproduce ☕️

feat request

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
It is. give your provider id to `signIn` as the first param. Example https://next-auth.js.org/getting-started/client#starts-google-oauth-sign-in-flow-when-clicked
