### ISSUE TITLE
Credentials provider: request headers undefined in authorize callback on new Nodes

### ISSUE THREAD

**Issue by svkoskin** [nextauthjs/next-auth#2612]
### Description 🐜

When using Credentials provider, the authorize callback should receive the incoming message object as the second parameter. However, on certain Node versions the incoming message has `undefined` as `headers`.

This happens on Node versions 14.15.2, >=15.1 and >=16.0 and is related to this change: https://github.com/nodejs/node/pull/35281 There is an issue on Node but it is closed (https://github.com/nodejs/node/issues/36550)

 A developer seems to be advising against using the spread operator on `headers` (https://github.com/nodejs/node/issues/36550#issuecomment-747601297) which is exactly what NextAuth is doing before calling `authorize` callback (https://github.com/nextauthjs/next-auth/blob/0fae0c7a8eb224964e38da409ecb9ba0497e8c50/src/server/routes/callback.js#L339).

### Is this a bug in your own project?

No

### How to reproduce ☕️

```
import Providers from `next-auth/providers`
...
providers: [
  Providers.Credentials({
    name: 'Credentials',
    credentials: {
      username: { label: "Username", type: "text", placeholder: "jsmith" },
      password: { label: "Password", type: "password" }
    },
    async authorize(credentials, req) {
      // The following statement should output a structure with the HTTP request headers.
      // On Node 14.15.2, >=15.1 and >=16.0 it outputs undefined and none of the headers can be accessed.
      console.log(req.headers);
      }
    }
  })
]
```

### Environment 🖥

```
  System:
    OS: Linux 4.19 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 16.37 GB / 25.02 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.2.0 - ~/.nvm/versions/node/v16.2.0/bin/node
    npm: 7.13.0 - ~/.nvm/versions/node/v16.2.0/bin/npm
  npmPackages:
    next: 11.1.0 => 11.1.0
    next-auth: 3.28.0 => 3.28.0
    react: 17.0.2 => 17.0.2

```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by ilijaNL** [comment]
> I wouldn't say it's a bug, more of an inconvenience maybe. Feel free to open a PR that strips the internal options and cookies from the request. We want to gate people from messing with those.
> 
> You have access to the original request though, just do:
> 
> ```js
> export default function auth(req, res) {
>   NextAuth(req, res, {
>      ... 
>      authorize(credentials) {
>        req
>     } 
>    ... 
>   })
> }
> ```

Or add additional parameter: rawrequest

**Comment by balazsorban44** [comment]
this will actually change, once #2857 is merged!

we won't pass the whole req anymore, as we won't have it.
