### ISSUE TITLE
Use LinkedIn and Github Authentication Provider at the same time conflicts with providerAccountId type

### ISSUE THREAD

**Issue by AydinChavez** [nextauthjs/next-auth#2632]
### Description 🐜

Hi all,

might be an easy one:

I have implemented both Authentication Providers: LinkedIn and Github.
I am using the PrismaAdapter for this. 

But I noticed that for LinkedIn I need to set in the schema to make it work:

```
model Account {
..
  providerAccountId  String
..
}
```

and for Github I need to set same field to a integer type to make it work:
```
model Account {
..
  providerAccountId  Int
..
}
```

Otherwise I am getting an error like this:
```

[next-auth][error][prisma__get_user_by_provider_account_id_error]
https://next-auth.js.org/errors#prisma__get_user_by_provider_account_id_error PrismaClientValidationError:
Invalid `prisma.account.findUnique()` invocation:

{
  where: {
    providerId_providerAccountId: {
      providerId: 'github',
      providerAccountId: 15386811
                         ~~~~~~~~
    }
  },
  select: {
    user: true
  }
}

Argument providerAccountId: Got invalid value 15386811 on prisma.findUniqueAccount. Provided Int, expected String.
```

Where could you do a type conversion of this field in next-auth framework? 

### Is this a bug in your own project?

No

### How to reproduce ☕️

see description

### Environment 🖥

```
 System:
    OS: macOS 11.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 672.92 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Safari: 14.1.2
  npmPackages:
    next: ^11.1.0 => 11.1.2
    next-auth: 3.28.0 => 3.28.0
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
try searching in old issues/PRs, this has been answered multiple times. will be fixed in the upcoming release

**Comment by AydinChavez** [comment]
Thanks, you're right.
Fixed it with

```
..
return {
          id: String(profileData.id),
..
```
