### ISSUE TITLE
Next auth 4.0.0 sign in provider will only accept Email or Credentials 

### ISSUE THREAD

**Issue by Patryks1** [nextauthjs/next-auth#2654]
### Description 🐜

Currently in 4.0.0 sign in provider type is 
```
export type RedirectableProvider = "email" | "credentials"
```

which means any other provider will be seen as an error to typescript.  I believe changing it to a optional string will fix the issue. 

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

Following line will throw type error when building as google is not part of the RedirectableProvider 
```
signin("google"); 
```

### Environment 🖥

System:
    OS: Windows 10 10.0.19043
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 17.91 GB / 31.92 GB
  Binaries:
    Node: 14.17.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.38)
    Internet Explorer: 11.0.19041.906
  npmPackages:
    @preact/compat:  0.0.4
    next: 11.1.0 => 11.1.0
    next-auth: 4.0.0-next.26 => 4.0.0-next.26

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
`4.0.0-beta.2` is has been released, with a fix for this!
