### ISSUE TITLE
How to limit domain for Google provider

### ISSUE THREAD

**Issue by arnodel** [nextauthjs/next-auth#266]
Hi there, I am trying to convert a project from v1 to v2.  I have some difficulties with restricting the domain users can choose.  In v1 I had in `next-auth.providers.js` the following.

```js
    providers.push({
      providerName: "Google",
      providerOptions: {
        scope: ["profile", "email"],
        hd: "mydomain.com"
      },
      // [...]
    });
```

The `hd` provider option only allowed users to sign in with an email in the `mydomain.com` domain.  In v2 I don't know how to achieve that.  I tried

```js
    Providers.Google({
      clientId: process.env.GOOGLE_ID,
      clientSecret: process.env.GOOGLE_SECRET,
      hd: "mydomain.com",
    }),
```

But that has no effect.  Is there a way to achieve this in v2?  It's a very important feature for me.

**Comment by LoriKarikari** [comment]
I think that parameter isn't currently supported. I'll check it out and update the provider if needed.

**Comment by iaincollins** [comment]
From a quick search it seems maybe Google call this option `hostedDomain` now? 

We don't currently support it, but seems like a thing we would want to!

You can also enforce access controls [using the `signin()` callback](https://next-auth.js.org/configuration/callbacks) something like this should work:

```js
callbacks: {
  signin: async (profile, account, metadata) => {
    if (metadata.email_verified === true &&
        metadata.email.endsWith('@example.com')) {
    return Promise.resolve(true)
   } else {
    return Promise.resolve(false)
   }
  },
}
```

Note: I am not 100% sure of the data structure there, so you might want to `console.log()` those objects to double check that.

**Comment by arnodel** [comment]
Thanks @iaincollins, I will implement the callback as it will help.  It would be good if the `hd/hostedDomain` parameter was implemented - perhaps I can look into it if I have some time but I think it may be non-trivial as it appears the underlying library implementing oauth has changed from `passport-google-oauth` to `oauth` - I don't know how the latter would support it.

**Comment by ndom91** [comment]
@arnodel as a workaround, and this is what I currently do, you can explicitly define your oauth credentials to be able to be used internally only. That way Google itself will take care of only allowing people / accounts from inside your domain.

**Comment by iaincollins** [comment]
@ndom91 Oh that's neat, thank you, I didn't know you could do that.

**Comment by arnodel** [comment]
@ndom91 That's interesting - if I understand you correctly, I don't think I can use that though as the domain for this app is not the domain of our users' gmail account.

**Comment by ndom91** [comment]
@arnodel no, that's not necessary, its only necessary that the account with which you created the google developer console project and generated the oauth token, be a part of the users gmail domain. 

I just double checked, and I guess its Project-wide however, not on a key by key basis. 

So in the Google Dev Console, once you've selected your project, you can go to "OAuth Consent Screen" in the left menu. There you can select "Public" or "Internal" application. 

![image](https://user-images.githubusercontent.com/7415984/84760338-29555680-afc8-11ea-98dc-6544f5dc441c.png)

**Comment by arnodel** [comment]
@ndom91 Thank you!  That would be great if I can get it configured like this.

**Comment by ThewBear** [comment]
I can get it works by passing custom `authorizationUrl` and appending the `hd` parameter.
```js
const options = {
  providers: [
    Providers.Google({
      clientId: process.env.GOOGLE_ID,
      clientSecret: process.env.GOOGLE_SECRET,
      authorizationUrl:
        "https://accounts.google.com/o/oauth2/auth?response_type=code&hd=domain.com", // hosted domain is domain.com
    }),
  ],
};
```

**Comment by arnodel** [comment]
> I can get it works by passing custom `authorizationUrl` and appending the `hd` parameter.
> [...]
> Note for `hosted domain` feature: Don't rely on this UI optimization to control who can access your app, as client-side requests can be modified. You still need to validate on your server side as in @iaincollins['s comment](https://github.com/nextauthjs/next-auth/issues/266#issuecomment-644279150)

It's great though, as it prevents users from inadvertently trying to sign in with an unauthorized account (as Google with narrow down the list of accounts to choose from).

**Comment by ThewBear** [comment]
Maybe we can add [my solution](https://github.com/nextauthjs/next-auth/issues/266#issuecomment-682390478) to the docs?

**Comment by balazsorban44** [comment]
Would you be interested in opening a PR @ThewBear?
