### ISSUE TITLE
[V4 Beta][TS] `useSession` types unexpectedly strict

### ISSUE THREAD

**Issue by TheoBr** [nextauthjs/next-auth#2674]
### Description 🐜

![image](https://user-images.githubusercontent.com/6751787/132146034-c487ca2c-f20b-4058-81cc-df2291050109.png)

![image](https://user-images.githubusercontent.com/6751787/132146028-c90a1d2c-688b-4372-b26a-c430f52c78ff.png)

### Is this a bug in your own project?

No

### How to reproduce ☕️

https://github.com/TheoBr/next-auth-v4-prisma-demo/blob/signin-types-broken-demo/pages/index.tsx

### Environment 🖥

Modern MacOS and node 16 lts

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
It misses a `?` on options. Care to open PR? (preferably against the `beta` branch)

**Comment by balazsorban44** [comment]
I now fixed this but will await publishing `beta.2` to accumulate multiple fixes. In the `beta` phase, I don't wish to have 20+ releases anymore... :sweat_smile:
