### ISSUE TITLE
Navigating to custom sign in page using `signIn()` replaces history. Is there a way to configure that or is this a bug?

### ISSUE THREAD

**Issue by mikecabana** [nextauthjs/next-auth#2676]
### Question 💬

When invoking the front end `signIn()` method, I get redirected to my custom sign in page. If I then hit the back button, it goes back to a blank page with `about:blank` in the URL. 

**Is there a way to configure history or back behaviour when invoking the front end `singIn()` method or is this a bug?**

I'm following the [pages documentation v3](https://next-auth.js.org/v3/configuration/pages).

### How to reproduce ☕️

`[...nextauth].ts`
```typescript
...
pages: {
    signIn: '/auth/signin',
},
...
```

`Nav` component
```tsx
...
<button onClick={() => signIn()}>
    Log in
</button>
...
```

My sign in page is basically a combo of email and providers (not email).

`/pages/auth/signin.tsx`
```typescript
import { FunctionComponent } from 'react';
import { GetServerSideProps } from 'next';
import {
    signIn,
    getSession,
    getProviders,
    getCsrfToken,
    ClientSafeProvider,
} from 'next-auth/client';

interface SigninProps {
    providers: ClientSafeProvider[];
    csrfToken: string;
}

const Signin: FunctionComponent<SigninProps> = ({ providers, csrfToken }) => {
    return (<>...</>);
};

export default Signin;

export const getServerSideProps: GetServerSideProps = async (ctx) => {
    const {req, res} = ctx;
    const session = await getSession();

    if (session && res && session.access_token){
        res.writeHead(302, {
            location: '/'
        });
        res.end();
        return;
    }

    const providers = await getProviders();

    let csrfToken: string = null;
    if (Object.values(providers).find((p) => p.type === 'email')) {
        csrfToken = await getCsrfToken(ctx);
    }

    const providersWithoutEmail = Object.values(providers).filter(
        (p) => p.type !== 'email'
    );

    return {
        props: {
            providers: providersWithoutEmail,
            csrfToken,
        },
    };
};
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by ndom91** [comment]
Yeah so currently we're using `window.location.replace` which does not add the navigation to your history, causing the behavior your described. 

See: https://github.com/nextauthjs/next-auth/blob/0989accf23d19c0cbc9cb52a32275634219104cc/src/react/index.tsx#L226

@balazsorban44 is there a security reason for this possibly? Or would it make sense to change it to just `window.location.href = ..` ?

See first paragraph here: https://developer.mozilla.org/en-US/docs/Web/API/Location/href

**Comment by balazsorban44** [comment]
I can try to trace this back, but generally I think it would be alright. I know there has been issues in the past that discussed using Next.js's `router.push` as well. It might be worth it to find that and see if there is an old reasoning for the current behavior.

**Comment by nguyenthetoan** [comment]
hello @balazsorban44 , have you found the reason yet?

**Comment by saeedseyfi** [comment]
I found this behavior of next-auth very strange as well. User should be able to use navigate back if they changed their mind and don't want to signin anymore.

>  I know there has been issues in the past that discussed using Next.js's router.push as well

@balazsorban44 if `router.push` didn't work as expected, what if you use `window.push`?
I'd really appreciate if you let us know what was the problem with router.push.

**Comment by mikecabana** [comment]
Closing since the solution will appear in an upcoming release.

**Comment by nickdandakis** [comment]
We're running into the inverse problem here where we want the history replaced instead of pushed.

Is there any appetite for an additional parameter to `signIn` to indicate a replace instead of a push? Maybe something like `redirectReplace`? I can work on a PR if so, @balazsorban44 

—

For more context about our use-case. We've created some dedicated pages for `/login` etc and have links that point to them. Navigating back once on the auth provider takes the user to the `/login` page which just redirects them back to the auth provider. Using a replace would fix that
