### ISSUE TITLE
TypeScript complains on `CredentialsConfig`

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#2677]
### Discussed in https://github.com/nextauthjs/next-auth/discussions/2672

<div type='discussions-op-text'>

<sup>Originally posted by **Rhym** September  6, 2021</sup>
Good morning! I am updating my next auth in preparation for the 4.0 release and my previously working Credentials provider has an issue with the `authorize` callback.

I receive a 
```
"Types of parameters 'credentials' and 'credentials' are incompatible. Type 'Record<never, string>' is missing the following properties from type '{ username: string; password: string; }': username, password". "The expected type comes from property 'authorize' which is declared here on type 'Partial<CredentialsConfig<{}>>'"
```

I see that the `CredentialsConfig` takes a generic, but I'm not actually sure where to set the config. Any help would be appreciated, thank you. Example of my code: 

```typescript
providers: [
  // https://next-auth.js.org/configuration/providers
  CredentialsProvider({
    id: "login",
    name: "Login",
    credentials: {
      username: {},
      password: {},
    },

    authorize: async (credentials: { username: string; password: string }) => {
      const DATA = { username: credentials.username, password: credentials.password };
      // Login logic...
    },
  }),
],
```
</div>

**Comment by balazsorban44** [comment]
The problem is in this file:

https://github.com/nextauthjs/next-auth/blob/beta/src/providers/credentials.ts

PRs welcome, otherwise I'll dig into it once I have the time.

**Comment by balazsorban44** [comment]
Hi @Rhym

So the general thinking is that whatever fields you define on `credentials` will be available in the `authorize` callback, like so:

![](https://i.imgur.com/AcEm0XL.png)

There _was_ a small issue with the type I think, which I now corrected in #2683.

This all means that you don't actually need a generic!

**Comment by Rhym** [comment]
Awesome, thank you @balazsorban44 for your swift response. So will that be available in BETA 2

**Comment by balazsorban44** [comment]
Yes, hoping to release it soon. Currently awaiting #2655

**Comment by Rhym** [comment]
Oh, that's a nice feature. Looking forward to the release. Have a great day!

**Comment by balazsorban44** [comment]
`4.0.0-beta.2` has been released, including a fix for this!

**Comment by Rhym** [comment]
Hey, @balazsorban44 I've updated to `beta.2` and now I get a fun new message with the following code:

```typescript
providers: [
  Credentials({
    name: "Credentials",
    credentials: {
      username: {
        label: "username",
        type: "text",
      },
      password: {
        label: "password",
        type: "password",
      },
    },
    async authorize(credentials, _req) {
      // Auth logic...
    },
  }),
],
```

Typescript error:

```typescript
Type 'CredentialsConfig<{ username: { label: string; type: string; }; password: { label: string; type: string; }; }>' is not assignable to type 'Provider'.
  Type 'CredentialsConfig<{ username: { label: string; type: string; }; password: { label: string; type: string; }; }>' is not assignable to type 'CredentialsConfig<{}>'.
    Types of property 'authorize' are incompatible.
      Type '(credentials: Record<"username" | "password", string>, req: NextApiRequest) => Awaitable<Omit<User, "id"> | { id?: string | undefined; } | null>' is not assignable to type '(credentials: Record<never, string>, req: NextApiRequest) => Awaitable<Omit<User, "id"> | { id?: string | undefined; } | null>'.
        Types of parameters 'credentials' and 'credentials' are incompatible.
          Type 'Record<never, string>' is missing the following properties from type 'Record<"username" | "password", string>': username, password
```

Looks like the update to the config had a side effect?

**Comment by balazsorban44** [comment]
I cannot seem to reproduce:

![](https://i.imgur.com/1QHvEPg.png)

If you still have issues, please open a new issue with a reproduction. :wink:

**Comment by dragoncorf** [comment]
I have the same Typescript error:
```
Type 'CredentialsConfig<{ username: { label: string; type: string; }; password: { label: string; type: string; }; }>' is not assignable to type 'Provider'.
  Type 'CredentialsConfig<{ username: { label: string; type: string; }; password: { label: string; type: string; }; }>' is not assignable to type 'CredentialsConfig<{}>'.
    Types of property 'authorize' are incompatible.
      Type '(credentials: Record<"username" | "password", string>, req: NextApiRequest) => Awaitable<Omit<User, "id"> | { id?: string | undefined; } | null>' is not assignable to type '(credentials: Record<never, string>, req: NextApiRequest) => Awaitable<Omit<User, "id"> | { id?: string | undefined; } | null>'.
        Types of parameters 'credentials' and 'credentials' are incompatible.
          Type 'Record<never, string>' is missing the following properties from type 'Record<"username" | "password", string>': username, password
```

**Comment by balazsorban44** [comment]
then please provide a reproduction. 😊

**Comment by dragoncorf** [comment]
Yes! I made this issue with a reproduction #2701

**Comment by jaydave1412** [comment]
I have this config that is working but it should not

    import nextAuth from "next-auth/next";
    import { AuthOptions } from "next-auth";
    import CredentialsProvider from "next-auth/providers/credentials";
    
    export const authOptions: AuthOptions = {
      providers: [
        CredentialsProvider({
          credentials: {
            email: {},
            password: {},
          },
          async authorize(credentials) {
            const user = { id: "hello", name: "jay", password: "dave" };
            if (!user || !user.password) return null;
    
            const passwordsMatch = user.password === credentials?.password;
    
            if (passwordsMatch) return user;
            return null;
          },
        }),
      ],
    };
    
    export default nextAuth(authOptions);

how I decided to add id, 
I looked into the types, 

this is how credentials config interface is defined

    export interface CredentialsConfig<
      C extends Record<string, CredentialInput> = Record<string, CredentialInput>
    > extends CommonProviderOptions {
      type: "credentials"
      credentials: C
      authorize: (
        credentials: Record<keyof C, string> | undefined,
        req: Pick<RequestInternal, "body" | "query" | "headers" | "method">
      ) => Awaitable<User | null>
    }

as you can see it returns awaitable user and user is defined like this

    export interface DefaultUser {
      id: string
      name?: string | null
      email?: string | null
      image?: string | null
    }
    
    /**
     * The shape of the returned object in the OAuth providers' `profile` callback,
     * available in the `jwt` and `session` callbacks,
     * or the second parameter of the `session` callback, when using a database.
     *
     * [`signIn` callback](https://next-auth.js.org/configuration/callbacks#sign-in-callback) |
     * [`session` callback](https://next-auth.js.org/configuration/callbacks#jwt-callback) |
     * [`jwt` callback](https://next-auth.js.org/configuration/callbacks#jwt-callback) |
     * [`profile` OAuth provider callback](https://next-auth.js.org/configuration/providers#using-a-custom-provider)
     */
    export interface User extends DefaultUser {}

as you can see password is not part of User in the interface then why is it working
