### ISSUE TITLE
LinkedIn provider should expose entire profile

### ISSUE THREAD

**Issue by anindha** [nextauthjs/next-auth#2685]
### Description 📓

Currently the LinkedIn provider doesn't expose all the attributes returned by LinkedIn.

### How to reproduce ☕️

Standard example with LinkedIn provider.

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
https://next-auth.js.org/providers/linkedin#options

**Comment by anindha** [comment]
@balazsorban44 Why was this closed?

**Comment by balazsorban44** [comment]
Have you checked the link? Have a particular look at the `profile` callback.
