### ISSUE TITLE
Naming of returned object with v4 useSession hook

### ISSUE THREAD

**Issue by Thisen** [nextauthjs/next-auth#2696]
### Question 💬

I'm trying out v4 of `next-auth` and I'm wondering about the naming of the returned object in the `useSession` hook:

```ts
const { data } = useSession(); 
```
I've not sure about using `data` as the property to hold `session` data.

Why isn't it simply:
```ts
const { session } = useSession(); 
```
While migrating, I found myself doing the following search/replace to minimize changes in the application:
`const [session] = useSession()` -> `const { data: session } = useSession();`

I'm sorry if this has already been clarified, if so I haven't been able to find it.

### How to reproduce ☕️

See question.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Because the variable name `session` should be reserved for:

```ts
const session = useSession();

// here `session.session` would have been awkward
```

It was a personal choice, but I stand by it.

**Comment by balazsorban44** [comment]
It is also similar to how React Query, SWR, Apollo and trpc return data, so most people will already be more familiar with this patter.

**Comment by balazsorban44** [comment]
If it's irritating, you can just create a custom hook:
```ts
import {
  useSession as useSessionNA
} from "next-auth/react"

function useSession(...args) {
  const session = useSessionNA(...args)
  return { ...session, session: session.data
}
```

and use that instead. 😊

**Comment by Thisen** [comment]
> Because the variable name `session` should be reserved for:
> 
> ```ts
> const session = useSession();
> 
> // here `session.session` would have been awkward
> ```
> 
> It was a personal choice, but I stand by it.

Makes complete sense, I understand the choice.
