### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED] react

### ISSUE THREAD

**Issue by gkielwasser** [nextauthjs/next-auth#2699]
### Question 💬

Hi,

I'm using the beta.2 version.

My build give me the following error `Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './react' is not defined by "exports" in my-project\node_modules\next-auth\package.json`. 
The error happen as soon as I encapsulate my app with the SessionProvider provider.

I'm using the following to wrap my app:
```
import { SessionProvider } from "next-auth/react"

<SessionProvider session={pageProps.session}>
      [...]
 </SessionProvider>     
```

Also, I'm not sure what usefull informations I could share about this error.

Thanks for help!

### How to reproduce ☕️

Here is my nextauth dependency: "next-auth": "4.0.0-beta.2"

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
have a reproduction?
