### ISSUE TITLE
Comply with TypeScript strict mode

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#2709]
#2552 introduced TypeScript to the core. A long-time wish from the community, and the maintainers.

For an easier migration, I decided to go with `"strict": false`, and we still allow ".js" files.

As an improvement, we should make set `"strict": true` in our `tsconfig.json` and fix the remaining issues, and convert the rest of the files to TypeScript as well.

**Comment by Thisen** [comment]
@balazsorban44 Happy to work on it - However I want to split in multiple PRs, so it's smaller changes.

**Comment by balazsorban44** [comment]
sounds good, I could suggest setting `strict: true`, but not actually committing it.

**Comment by DopamineDriven** [comment]
Yes please 🙏 

I work with Strict, always strict, and strict null check flags set to true

This would be greatly appreciated

**Comment by Thisen** [comment]
Working on it. 🙂

**Comment by balazsorban44** [comment]
#2802 has been merged now, anything left here?

**Comment by balazsorban44** [comment]
@Thisen, @sldavidson could you test `next-auth@4.0.0-beta.7`?

**Comment by copleykj** [comment]
> @Thisen, @sldavidson could you test `next-auth@4.0.0-beta.7`?

@balazsorban44 so this fixed an issue I was having with the credentials provider throwing a type error for username and password keys, but now it's throwing a type error for the jwt key of the session option.

**Comment by copleykj** [comment]
![Screenshot from 2021-11-18 13-28-38](https://user-images.githubusercontent.com/1511556/142475412-051f1c28-9139-4b00-8abc-59342e78a644.png)

**Comment by balazsorban44** [comment]
that's expected, renamed for clarity 
https://next-auth.js.org/getting-started/upgrade-v4#session-strategy

**Comment by copleykj** [comment]
Oh.. Sorry. This section of the v4 docs had me confused.

![image](https://user-images.githubusercontent.com/1511556/142517765-db5ff09e-c878-4cf8-a9db-c02fe0a0d342.png)

**Comment by balazsorban44** [comment]
Good catch, just updated the docs!

**Comment by Thisen** [comment]
> @Thisen, @sldavidson could you test `next-auth@4.0.0-beta.7`?

It didn't work for me. Also, it looks like the first argument is required for `useSession` in that version, is that expected?

**Comment by balazsorban44** [comment]
no it isn't and was supposed to be fixed in https://github.com/nextauthjs/next-auth/commit/419ffe7787a9c6038f55dcfd4cbb1b44cc5b7cba

**Comment by currenthandle** [comment]
> #2701 unfortunately is still a thing (but was closed in favor for this one, which then went stale for some reason).

I'm still getting this same issue as well.

**Comment by Simvolick** [comment]
Really waiting for this because of the VkProvider

**Comment by karambir-zz** [comment]
I'm having the same problem with #2701

**Comment by ondraczsk** [comment]
Yes #2701 still an error

**Comment by nos-nart** [comment]
I encounter the same error, turn off the strict mode in **tsconfig.json** still shows type error, temporarily I return **null as any** to suppress it.

**Comment by coycoylaniba** [comment]
does anyone have a fix for this? im also getting this error.

**Comment by Zarathos1084** [comment]
Still getting the same error as well

**Comment by sumanchapai** [comment]
This fixes issues for me in the `authorize` function with strict typescript mode. 
```
import { API_LOGIN } from "lib/apis"
import NextAuth from "next-auth"
import CredentialsProvider from "next-auth/providers/credentials"

export default NextAuth({
    providers: [
        CredentialsProvider({
            type: 'credentials',
            credentials: {},
            async authorize(credentials: Record<string, string> | undefined, req) {
                const authResponse = await fetch(API_LOGIN, {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json",
                    },
                    body: JSON.stringify(credentials),
                })

                if (!authResponse.ok) {
                    return null
                }

                const user = await authResponse.json()

                return user
            },
        }),
    ],
})
```

Note that 
```
import { API_LOGIN } from "lib/apis"
```
line is custom to your project!
