### ISSUE TITLE
unpublish version `4.0.0` (exact version)

### ISSUE THREAD

**Issue by ramiel** [nextauthjs/next-auth#2716]
### Question 💬

I know there's something I'm missing, but in documentation I see this statement "Due to an unfortunate publish on npm, there is a 4.0.0 version out there that is NOT suitable for use". My question is, why can't you unpublish it?

### How to reproduce ☕️

Nothing to reproduce

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Because of this 😕:

https://docs.npmjs.com/policies/unpublish#packages-published-more-than-72-hours-ago

Running `npm unpublish next-auth@4.0.0` gives me this:

```bash
npm ERR! code E405
npm ERR! 405 Method Not Allowed - PUT https://registry.npmjs.org/next-auth/-rev/430-5b08d78eacf2261c32b115a83c90a2c8 - You can no longer unpublish this package.
npm ERR! Failed criteria: 
npm ERR! has dependent packages in the registry, has more than 1 maintainer
```

**Comment by ramiel** [comment]
I guess you can contact npm directly and they can unpublish it. Sorry for the silly question, it was out of curiosity. Good job so far with the new version, kudos!

**Comment by balazsorban44** [comment]
It is a totally fair question!

And FYI, upon reading it, I actually decided to contact npm support and see if they have good advice here, so thank you! :green_heart: 

I'll write back here the response from them.

**Comment by balazsorban44** [comment]
Bec

https://docs.npmjs.com/policies/unpublish#packages-published-more-than-72-hours-ago I got an answer from npm, and unfortunately they cannot do anything about it, our best option will be deprecation. I'll try to come up with a clever message then.

Thabks for nudging me into doing something about this!

**Comment by balazsorban44** [comment]
I deprecated the exact version `4.0.0`!

From now on, if you try to install it in any way, for example: `npm i next-auth@4.0.0`

It will give you the following warning:
```bash
npm WARN deprecated next-auth@4.0.0: This is a bad release. Make sure you have 4.0.1 or newer, or you use a `next` or `beta` release tag.
```

**Comment by jonioni** [comment]
Thanks for the question and the explanation! A quick question for @balazsorban44 : when do you estimate `v4` to become the new stable version (npm default)? We are considering upgrading `next-auth` from `v3` to `v4` for the better webpack 5 support (TypeORM dependency problem mentioned in other issue) but not sure if it is a good time to do so.

**Comment by balazsorban44** [comment]
Hi @jonioni, I don't have an ETA, but I can quickly mention the things that are left:

1. In v4, we intend to ship our built-in providers with confidence. This is a hard task, as most providers were added by community members without proper testing/opinionated configs. You can follow the progress here: #2524 This is a very tedious and manual process, unfortunately.
2. Not necessarily a must, but I would like to merge/finish as many of the open PRs on adapters as possible: https://github.com/nextauthjs/adapters/pulls
3. We are currently discussing the possibility for a security check on NextAuth which I don't really have an estimation for.

Help on 1. and 2. would accelerate things significantly.

Other than these, if your adapter/provider has been refactored to support v4 and doesn't mind waiting for 3 (Don't take my word on it, but we have had a huge userbase with v3 as well, and haven't really gotten serious security complaints yet, so I don't expect major issues. We have to see though. :crossed_fingers: )

Most of the API hopefully won't change anything (or much at least). So for new projects, you might want to test out v4.

**Comment by jonioni** [comment]
Thank you for the quick response. We will check out v4 and test on 1. (the provider we use has already been labeled ✅ so it should be good).

Regarding the release, I fully agree that it's of utter importance for the library to remain stable and reliable, and so there's really no reason to rush for the major release until everything is ready 👌

**Comment by Mosquid** [comment]
How do I get the correct version installed? Installing by `npm install next-auth@beta` give me "^4.0.0-beta.2", while in your docs you're saying:

> In your project's package.json, make sure you don't have a ^ character before the version number

**Comment by balazsorban44** [comment]
Just remove the `^` in `package.json`, and run `npm i` again. Otherwise installing `npm I next-auth@4.0.0-beta.2` should give an exact version as well.
