### ISSUE TITLE
getUserByAccount is not a function

### ISSUE THREAD

**Issue by joshua-isaac** [nextauthjs/next-auth#2738]
### Description 🐜

Using `next-auth@4.0.0-beta.2` with `prisma` and `@next-auth/prisma-adapter`, I get an error trying to authenticate with the google provider

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

```
import NextAuth from "next-auth";
import GoogleProvider from "next-auth/providers/google";
import { PrismaAdapter } from "@next-auth/prisma-adapter";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export default NextAuth({
  adapter: PrismaAdapter(prisma),
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    }),
  ],
});
```

### Environment 🖥

  System:
    OS: macOS 11.0.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Memory: 1.05 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
    Firefox: 84.0.2
    Safari: 14.0.1
  npmPackages:
    next: 11.1.2 => 11.1.2 
    next-auth: 4.0.0-beta.2 => 4.0.0-beta.2 
    react: 17.0.2 => 17.0.2 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by Louis3797** [comment]
I have the same probleme pls help

**Comment by AydinChavez** [comment]
@Louis3797 The answer is described here https://github.com/nextauthjs/adapters/issues/209

**Comment by shadoath** [comment]
The above link is dead. Can you repost a solution?

**Comment by AydinChavez** [comment]
Don't remember the content of the dead link (seems that the issue section was deactivated in the related repo), but maybe this helps:
https://stackoverflow.com/questions/69899392/how-to-resolve-getuserbyaccount-is-not-a-function-in-next-auth/70773430
