### ISSUE TITLE
getUserByAccount is not a function - next auth & prisma google provider

### ISSUE THREAD

**Issue by joshua-isaac** [nextauthjs/next-auth#2739]
### Description 🐜

Using `next-auth@4.0.0-beta.2` with `prisma` and `@next-auth/prisma-adapter`, I get an error trying to authenticate with the google provider

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

set up next-auth:

```
import NextAuth from "next-auth";
import GoogleProvider from "next-auth/providers/google";
import { PrismaAdapter } from "@next-auth/prisma-adapter";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export default NextAuth({
  adapter: PrismaAdapter(prisma),
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    }),
  ],
});
```

### Screenshots / Logs 📽

![Screen Shot 2021-09-12 at 8 51 19 PM](https://user-images.githubusercontent.com/40035381/133009259-67b514d2-bc90-485a-9157-e5fe82f421e2.png)

### Environment 🖥

  System:
    OS: macOS 11.0.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Memory: 846.43 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
    Firefox: 84.0.2
    Safari: 14.0.1
  npmPackages:
    next: 11.1.2 => 11.1.2 
    next-auth: 4.0.0-beta.2 => 4.0.0-beta.2 
    react: 17.0.2 => 17.0.2 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by joshua-isaac** [comment]
update: looks like the same error for twitter provider as well

**Comment by balazsorban44** [comment]
duplicate. please search through closed issues before opening a new one.

**Comment by joshua-isaac** [comment]
> duplicate. please search through closed issues before opening a new one.
> 
> This is actually the fifth time I close the same issue all originating from the same user mistake. 🤦‍♂️
> 
> open for suggestions how to avoid it in the future! (please come back to it after you have done the research)

thanks for the response @balazsorban44, do you mind sharing the closed issue that resolves this? i cant seem to find it..

thanks,

**Comment by joshua-isaac** [comment]
when the adapter is removed, authentication works as expected

**Comment by AydinChavez** [comment]
> > duplicate. please search through closed issues before opening a new one.
> > This is actually the fifth time I close the same issue all originating from the same user mistake. 🤦‍♂️
> > open for suggestions how to avoid it in the future! (please come back to it after you have done the research)
> 
> thanks for the response @balazsorban44, do you mind sharing the closed issue that resolves this? i cant seem to find it..
> 
> thanks,

@balazsorban44 am having the same issue. What's the mentioned user mistake here ? Couldn't find the reason for this / original issue in closed ones.

**Comment by balazsorban44** [comment]
Remember to check adapter related issues jn the adapters repo:

https://github.com/nextauthjs/adapters/issues?q=is%3Aissue+getUserByAccount+is%3Aclosed
