### ISSUE TITLE
Custom session expire date

### ISSUE THREAD

**Issue by aboveyunhai** [nextauthjs/next-auth#2789]
### Question 💬

I want to modify the session expire date to keep it consistency with a one of the token expire date from server. 
But I am not sure how the session expire date is handled internally by `next-auth`.

Currently  what I did is just to change the session by
```
session(session, userOrToken) {
        session.expires = userOrToken.refresh_token_expiration;
}
```
```
2021-10-18T23:00:01.182Z     <---- next-auth default generated string
2021-10-18T18:58:42.618517-04:00    <---- server generated string
```
You can see there are some format difference between two strings;

### My question: Is this enough to be handled automatically by `next-auth` or there are some extra things I still have to handle. 

What I try to achieve is that once server token expires, session will be expired as well, hence user auto logout in this case **at the moment of refreshing the page or open the page where session callback is trigged** due to session expire. 

Of course, I know there are some separated cases I had to handle, I just wonder what happen for this particular one.

### How to reproduce ☕️

Not applicable

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
The session expiry is not the same as a third party access token. next-auth rotates the session expiry, meaning whenever the client contacts the backend, it will update the session expiry date. (which is basically the cookie lifetime)

If the user doesn't open the page for a while, the cookie will expire and will be removed automatically. so make sure the session expiry is always lower than your access token expiry date, if you cannot refresh the access token.

hope that makes sense!
