### ISSUE TITLE
Can't resolve 'next-auth/react'

### ISSUE THREAD

**Issue by Radmehr-aghdam** [nextauthjs/next-auth#2804]
### Description 🐜

I'm upgrading from v3 to v4 beta
I changed all needs with (https://next-auth.js.org/getting-started/upgrade-v4) but I have an error.
But when I change it to `'next-auth/client'` it's worked!

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

```
Module not found: Can't resolve 'next-auth/react'
import { signIn, signOut, getSession } from 'next-auth/react'
```

### Environment 🖥

  System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (3) x64 QEMU Virtual CPU version 2.5+
    Memory: 2.03 GB / 3.84 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.6 - /usr/bin/node
    npm: 7.22.0 - /usr/bin/npm
  npmPackages:
    next: ^11.1.2 => 11.1.2 
    next-auth: ^4.0.0-beta.2 => 4.0.0 
    react: ^17.0.2 => 17.0.2

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
As your `Environment` suggests, you have a wrong version installed:

`next-auth: ^4.0.0-beta.2 => 4.0.0`

See: https://next-auth.js.org/getting-started/upgrade-v4#verify-the-correct-version

**Comment by Radmehr-aghdam** [comment]
> As your `Environment` suggests, you have a wrong version installed:
> 
> `next-auth: ^4.0.0-beta.2 => 4.0.0`
> 
> See: https://next-auth.js.org/getting-started/upgrade-v4#verify-the-correct-version
> 
> I am curious when you installed `4.0.0`, you should have gotten an npm WARNING in the console. Did you see it?

No!

**Comment by Radmehr-aghdam** [comment]
> As your `Environment` suggests, you have a wrong version installed:
> 
> `next-auth: ^4.0.0-beta.2 => 4.0.0`
> 
> See: https://next-auth.js.org/getting-started/upgrade-v4#verify-the-correct-version
> 
> I am curious when you installed `4.0.0`, you should have gotten an npm WARNING in the console. Did you see it?

Yes, I saw it but I cannot find the correct installation command to install it.

**Comment by balazsorban44** [comment]
It says right there:

> In your project's package.json, make sure you don't have a ^ character before the version number. Read more in the npm docs
