### ISSUE TITLE
Client Side Authentication- Setup with OneLogin Provider

### ISSUE THREAD

**Issue by EJon-bit** [nextauthjs/next-auth#2805]
### Question 💬

**Could you aid in Identifying where in my code or provider configuration I may have made a mistake?** - 

**DETAILS**
Im Using the v4 beta of Next-Auth for client-side authentication (since documentation implies that OneLogin Provider is present) . 

I followed the [documentation](https://next-auth.js.org/providers/onelogin) and produced a code similar to [sample](https://codesandbox.io/s/sharp-pateu-ojk2q?file=/pages/_app.js). Upon clicking Link to a protected page and pressing  the "Sign in with OneLogin" button, the UI returns the message :

![Screenshot (154)](https://user-images.githubusercontent.com/59263624/134087555-7f0d1caa-9bda-4e45-a228-8af1aa16d9e0.png) 

 **AND**

 In the terminal the provider object is returned:

```sh
 _provider: {
      id: 'onelogin',
      name: 'OneLogin',
      type: 'oauth',
      wellKnown: //link to .well-known config was invalid...had an extra "/oidc/2",
      authorization: { params: [Object] },
      idToken: true,
      profile: [Function: profile],
      signinUrl: 'http://localhost:3000/api/auth/signin/onelogin',
      callbackUrl: 'http://localhost:3000/api/auth/callback/onelogin',
      clientId: //correct ID was displayed here,
      clientSecret: //correct Secret was displayed here,
      issuer: 'https://vasopsdev-dev.onelogin.com/oidc/2',
      checks: [ 'state' ]_**
  },
```

  **The Error message**: 'unable to get local issuer certificate'

**The Error Object**
```sh
  error: {
    message: 'unable to get local issuer certificate',
    stack: 'RequestError: unable to get local issuer certificate\n' +
      '    at ClientRequest.<anonymous> (C:\\Users\\ET604127\\OneDrive - Digicel Caribbean Ltd\\Desktop\\Test App\\VASOps-Next-App\\vas-ops-gui\\node_modules\\got\\dist\\source\\core\\index.js:956:111)\n' +
      '    at Object.onceWrapper (events.js:422:26)\n' +
      '    at ClientRequest.emit (events.js:327:22)\n' +
      '    at ClientRequest.EventEmitter.emit (domain.js:486:12)\n' +
      '    at ClientRequest.origin.emit (C:\\Users\\ET604127\\OneDrive - Digicel Caribbean Ltd\\Desktop\\Test App\\VASOps-Next-App\\vas-ops-gui\\node_modules\\@szmarczak\\http-timer\\dist\\source\\index.js:43:20)\n' +
      '    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n' +
      '    at TLSSocket.emit (events.js:315:20)\n' +
      '    at TLSSocket.EventEmitter.emit (domain.js:486:12)\n' +
      '    at emitErrorNT (internal/streams/destroy.js:106:8)\n' +
      '    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n' +
      '    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)\n' +
      '    at TLSSocket.emit (events.js:315:20)\n' +
      '    at TLSSocket.EventEmitter.emit (domain.js:486:12)\n' +
      '    at TLSSocket._finishInit (_tls_wrap.js:932:8)\n' +
      '    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)',
    name: 'RequestError'
  }
```
**OneLogin developer Configurations**:
![Screenshot (156)](https://user-images.githubusercontent.com/59263624/134088361-b373dbce-a0f7-49a2-bc43-2fff397c22af.png)

### How to reproduce ☕️

See [code sample](https://codesandbox.io/s/sharp-pateu-ojk2q?file=/pages/api/auth/%5B...nextauth%5D.js)

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Hi, their docs says the following:
https://developers.onelogin.com/openid-connect/api/provider-config

![image](https://user-images.githubusercontent.com/18369201/135548021-dc5db30b-aeef-44fd-8f92-e0186256f54d.png)

**Comment by EJon-bit** [comment]
Hi, do you have a clear example of the code you used for testing this provider locally. It is my first time using Next-Auth. I read the one login docs before making posting issue here. But I am still unclear about how the configuration should be. Is the example here [here](https://next-auth.js.org/providers/onelogin) all that is necessary for this provider?

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth/blob/beta/src/providers/onelogin.js

**Comment by pmwisdom** [comment]
Just in case someone runs into this, it may be because your token authentication method isn't `Basic` in OneLogin and this plugin defaults to Basic auth. I couldn't use basic token auth (I had to use POST) so here's the example with the method overloaded.


``` javascript
            OneLoginProvider({
               clientId: creds.client_id,
                clientSecret: creds.client_secret,
                wellKnown: `${ONE_LOGIN_ISSUER}/oidc/2/.well-known/openid-configuration`,
                id: 'onelogin',
                name: 'OneLogin',
                type: 'oauth',
                authorization: { params: { scope: 'openid profile email groups' } },
                idToken: true,
               // Here is the change
                client: {
                    token_endpoint_auth_method: 'client_secret_post',
                },
                profile(profile) {
                    return {
                        id: profile.sub,
                        name: profile.nickname,
                        email: profile.email,
                        image: profile.picture,
                    };
                },
            }),
```
