### ISSUE TITLE
Sign in with Apple does not work in v4

### ISSUE THREAD

**Issue by mmmoussa** [nextauthjs/next-auth#2833]
### Description 🐜

I never tested Apple sign in with v3, but we are currently setting up our project using v4 and have discovered that the Apple provider does not work. Following the next-auth documentation, I set up all of the environment variables for the provider correctly and setup an https domain with an associated service id in the Apple developer dashboard. On attempting to sign in, I get the following error:
```
[next-auth][error][SIGNIN_OAUTH_ERROR] 
https://next-auth.js.org/errors#signin_oauth_error Cannot read property 'url' of undefined {
  error: {
    message: "Cannot read property 'url' of undefined",
    stack: "TypeError: Cannot read property 'url' of undefined\n" +
      '    at openidClient (webpack-internal:///./node_modules/next-auth/server/lib/oauth/client.js:23:69)\n' +
      '    at getAuthorizationUrl (webpack-internal:///./node_modules/next-auth/server/lib/oauth/authorization-url.js:59:51)\n' +
      '    at Object.signin (webpack-internal:///./node_modules/next-auth/server/routes/signin.js:30:68)\n' +
      '    at NextAuthHandler (webpack-internal:///./node_modules/next-auth/server/index.js:202:31)\n' +
...
```

I debugged this and discovered the issue is with the `userinfo` url: https://github.com/nextauthjs/next-auth/blob/beta/src/server/lib/oauth/client.js#L24. I tried defining `userinfo: {url: ""}` in the provider configuration but then get the following error:
```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error userinfo_endpoint must be configured on the issuer {
  error: {
    message: 'userinfo_endpoint must be configured on the issuer',
    stack: 'TypeError: userinfo_endpoint must be configured on the issuer\n' +
      '    at assertIssuerConfiguration (/Users/mohamed/GitHub/tarteel/frontend/node_modules/openid-client/lib/helpers/assert.js:15:11)\n' +
      '    at Client.userinfo (/Users/mohamed/GitHub/tarteel/frontend/node_modules/openid-client/lib/client.js:1052:5)\n' +
      '    at oAuthCallback (webpack-internal:///./node_modules/next-auth/server/lib/oauth/callback.js:109:30)\n' +
...
```

I tried to find the legitimate userinfo endpoint but [it seems Apple does not fully comply with OpenID Connect and does not provide such an endpoint](https://hub.packtpub.com/openid-foundation-questions-apples-sign-in-feature-says-it-has-security-and-privacy-risks/).

At this point I am stuck and hoping that someone with more context on the implementation for OpenID Connect can suggest a workaround. This issue might be related to #2753.

### Is this a bug in your own project?

No

### How to reproduce ☕️

```
AppleProvider({
    clientId: process.env.APPLE_ID,
    clientSecret: {
        appleId: process.env.APPLE_ID,
        teamId: process.env.APPLE_TEAM_ID,
        privateKey: process.env.APPLE_PRIVATE_KEY,
        keyId: process.env.APPLE_KEY_ID,
    },
}),
```

### Environment 🖥

next: 11.1.2
next-auth: 4.0.0-beta.2
react: 17.0.2

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
Closing in favor of #2524. I would like to fix this, but I will need someone to help us out with an Apple client. If I am correct, it costs some money to apply for being an Apple Developer, so it would be awesome if you could reach out to help us by providing an application we could test against :pray:
