### ISSUE TITLE
Typo in docs: import "next-auth/react"

### ISSUE THREAD

**Issue by deadcoder0904** [nextauthjs/next-auth#2878]
### Description 🐜

Under https://next-auth.js.org/configuration/pages#email-sign-in, there is a code block with:

```ts
import { getCsrfToken } from "next-auth/react"
```

It should be:

```ts
import { getCsrfToken } from "next-auth/client"
```

Someone even made a Stackoverflow issue which I found through Google Search → https://stackoverflow.com/questions/69088378/next-auth-react-module-not-found-when-making-custom-email-sign-in-page-in-next

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

Yada yada yada

### Environment 🖥

No need

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by deadcoder0904** [comment]
Was gonna send a PR so searched for it & found this PR → https://github.com/nextauthjs/next-auth/pull/1473#issue-824062271

Which is funny bcz the Stackoverflow question is new.

I still get in VSCode:

> Cannot find module 'next-auth/react' or its corresponding type declarations.ts(2307)

How do I solve it?

**Comment by deadcoder0904** [comment]
Solved it installing beta version:

```bash
➜ npm i next-auth@beta
```

Gonna go update the Stackoverflow answer :)

**Comment by balazsorban44** [comment]
Some good advice for the next time. Please fill out the issue form before posting a new issue, we created it the way it is for a reason!

"Yada yada yada", and "No need" aren't very helpful. And indeed, posting your environment would have been very needed after all! Your issue originated from not reading the documentation, and you didn't saw the note that is on top of every page.

If you don't take it seriously, why would a maintainer do it?

**Comment by deadcoder0904** [comment]
@balazsorban44 It's a docs issue so I didn't fill it. There's nothing in docs to make a repro. Jeez, you don't need to get so serious.

> "Yada yada yada", and "No need" aren't very helpful. And indeed, posting your environment would have been very needed after all! Your issue originated from not reading the documentation, and you didn't saw the note that is on top of every page.

Yeah, if you didn't knew, nobody reads a docs top-to-bottom. Word-by-word. We skim & skip. Lots. Everyone does it. And like I said, someone else found that an issue & posted a Stackoverflow question & I felt like fixing it. so sent a PR.

Some good advice for next time. Don't take everything seriously. I felt like fixing so opened an issue so stop putting your anger on the internet for no reason.

"Yada yada yada" was just bcz of the required field & had nothing to with anything else. Jeez!

**Comment by balazsorban44** [comment]
I wouldn't boost taking a maintainer's time by not reading the docs. :wink: Remember, I work on this library in my free time. This issue has in no way contributed to making either the docs or this library better for anyone.
