### ISSUE TITLE
Decode jwt on the client without fetching `/session` route

### ISSUE THREAD

**Issue by remorses** [nextauthjs/next-auth#2885]
### Description 📓

Currently `getSession` and `useSession` hooks are fetching the `/session` route to decode the jwt cookie, instead we could just decode the jwt on the client (without verification)

Maybe this could be an option passed to the `useSession` hook like `skipJwtVerification: true`

### How to reproduce ☕️

The official demo (https://next-auth-example.vercel.app) does the initial `/session` request even if it is using JWTs

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
This is impossible as the jwt is only readable server-side (it's a httponly secure cookie)

**Comment by Noitidart** [comment]
Darn, I was also looking for a way without doing an extra request.
