### ISSUE TITLE
zlib: incorrect data check while installing

### ISSUE THREAD

**Issue by Shokhrukh2606** [nextauthjs/next-auth#2902]
### Description 🐜

While installing next-auth via npm occures error saying zlib: incorrect data check

### Is this a bug in your own project?

No

### How to reproduce ☕️

https://codesandbox.io/s/next-auth-example-1kktb

### Screenshots / Logs 📽

npm ERR! code Z_DATA_ERROR
npm ERR! errno -3
npm ERR! zlib: incorrect data check

npm ERR! A complete log of this run can be found in:

### Environment 🖥

MacBook Pro (2019) macOS  Big Sur 11.6

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Upon googling, `zlib` is a Python library: https://github.com/madler/zlib

I am closing this until further evidence is give to prove this is an issue with `next-auth`
