### ISSUE TITLE
[V4] Cognito Authentication Errors

### ISSUE THREAD

**Issue by DregondRahl** [nextauthjs/next-auth#2905]
### Description 🐜

Hi I'm using version "next-auth": "^4.0.0-beta.4"

```
    CognitoProvider({
      clientId: `${process.env.COGNITO_CLIENT_ID}`,
      clientSecret: `${process.env.COGNITO_CLIENT_SECRET}`,
      issuer: `${process.env.COGNITO_ISSUER}`,
    }),

```

I'm getting below error.
```
[next-auth][error][SIGNIN_OAUTH_ERROR]
https://next-auth.js.org/errors#signin_oauth_error Cannot read property 'params' of undefined {
  error: {
    message: "Cannot read property 'params' of undefined",
    stack: "TypeError: Cannot read property 'params' of undefined\n" +
      '    at getAuthorizationUrl (D:\\Work\\NodeJS\\BDiLabs\\next+mui\\frontend\\node_modules\\next-auth\\server\\lib\\oauth\\authorization-url.js:25:48)\n' +
      '    at Object.signin (D:\\Work\\NodeJS\\BDiLabs\\next+mui\\frontend\\node_modules\\next-auth\\server\\routes\\signin.js:30:68)\n' +    
      '    at NextAuthHandler (D:\\Work\\NodeJS\\BDiLabs\\next+mui\\frontend\\node_modules\\next-auth\\server\\index.js:202:31)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n' +
      '    at async D:\\Work\\NodeJS\\BDiLabs\\next+mui\\frontend\\node_modules\\next-auth\\server\\index.js:251:32\n' +
      '    at async Object.apiResolver (D:\\Work\\NodeJS\\BDiLabs\\next+mui\\frontend\\node_modules\\next\\dist\\server\\api-utils.js:101:9)\n' +
      '    at async DevServer.handleApiRequest (D:\\Work\\NodeJS\\BDiLabs\\next+mui\\frontend\\node_modules\\next\\dist\\server\\next-server.js:770:9)\n' +
      '    at async Object.fn (D:\\Work\\NodeJS\\BDiLabs\\next+mui\\frontend\\node_modules\\next\\dist\\server\\next-server.js:661:37)\n' +   
      '    at async Router.execute (D:\\Work\\NodeJS\\BDiLabs\\next+mui\\frontend\\node_modules\\next\\dist\\server\\router.js:205:32)',      
    name: 'TypeError'
  },

  message: "Cannot read property 'params' of undefined"
}
````

### Is this a bug in your own project?

No

### How to reproduce ☕️

I'm guessing its coming from here : https://github.com/nextauthjs/next-auth/blob/beta/src/server/lib/oauth/authorization-url.js#L21

```
    const params = { ...provider.authorization.params,
      ...req.query
    };
```
When i make it optional provider.authorization?.params  it works, but then another issue comes up, session is missing data it used to name like 'name'. This data was there in v3

```
  profile: {
    id: 'c5ceee18-999-43de-8ea5-d847e6c48b12',
    name: undefined,
    email: 'niranjith.perumal@moo.com',
    image: undefined
  },
``


### Screenshots / Logs 📽

I can share cognito credentials if it will help 

### Environment 🖥

  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 4.36 GB / 15.85 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.24.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 94.0.4606.71
    Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.44)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    next: 11.1.3-canary.7 => 11.1.3-canary.7
    next-auth: ^4.0.0-beta.4 => 4.0.0-beta.4
    react: ^17.0.2 => 17.0.2

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Correct! This was introduced in https://github.com/nextauthjs/next-auth/pull/2884/files 🤦

I removed some checks which I thought weren't necessary anymore, but I was wrong. Care to open a PR to fix it?

**Comment by thorep** [comment]
Any updates on this? Im getting the same error

**Comment by balazsorban44** [comment]
Will be addressed in #2932, but you were running into a different problem @thorep. You forgot to migrate the config to v4 at all.

I replied to your issue with a possible solution at https://github.com/nextauthjs/next-auth/issues/2949#issuecomment-943409796

**Comment by justinphilpott** [comment]
Any progress on this? I'm experiencing:

[next-auth][error][GET_AUTHORIZATION_URL_ERROR] 
https://next-auth.js.org/errors#get_authorization_url_error expected 200 OK, got: 400 Bad Request 

[next-auth][error][SIGNIN_OAUTH_ERROR] 
https://next-auth.js.org/errors#signin_oauth_error expected 200 OK, got: 400 Bad Request {

},
provider: {
id: 'cognito',
name: 'Cognito',
type: 'oauth',
wellKnown: 'https://[my_sub_domain].auth.eu-west-2.amazoncognito.com/.well-known/openid-configuration',
profile: [Function: profile],
checks: [ 'state' ],
clientId: >>> REMOVED <<<
clientSecret: >>> REMOVED <<<
issuer: 'https://[my_sub_domain].auth.eu-west-2.amazoncognito.com',
idToken: true,
signinUrl: 'http://localhost:3000/api/auth/signin/cognito',
callbackUrl: 'http://localhost:3000/api/auth/callback/cognito'
},
message: 'expected 200 OK, got: 400 Bad Request'

([my_sub_domain] is just as it was and working in v3)
clientId and secretId are also just the same as with v3
N.B. in v3, it worked without https:// prefix to the issuer

Cognito worked with same AWS setup in v3........ any clues pls???

**Comment by fram7** [comment]
**v3**
```
providers: [
   Providers.Cognito({
     clientId: process.env.COGNITO_CLIENT_ID_AWS,
     clientSecret: process.env.COGNITO_CLIENT_SECRET_AWS,
     domain: process.env.COGNITO_DOMAIN_AWS,
 ],
```

**v4.0.1**
```
providers: [
CognitoProvider({
clientId: process.env.COGNITO_CLIENT_ID_AWS,
clientSecret: process.env.COGNITO_CLIENT_SECRET_AWS,
issuer: `https://${process.env.COGNITO_DOMAIN_AWS}`, //also try with / at the end
}),
],
```

`COGNITO_DOMAIN_AWS={cognito domain}[.auth.us-east-1.amazoncognito.com]`

**Error:**
```
[next-auth][error][GET_AUTHORIZATION_URL_ERROR] 
 message: 'expected 200 OK, got: 400 Bad Request',
 error: {
    message: 'expected 200 OK, got: 400 Bad Request',
    stack: 'OPError: expected 200 OK, got: 400 Bad Request\n' +
      '    at processResponse (I:\\CuentaMedica\\vOCR\\cuentaMedica-OCR\\cuenta-medica-ocr\\node_modules\\openid-cl    id: 'cognito',
    name: 'Cognito',
    type: 'oauth',
    wellKnown: 'https://XXXXX.auth.us-east-1.amazoncognito.com/.well-known/openid-configuration',
    profile: [Function: profile],
    checks: [ 'state' ],    
    clientId: 'XXXX',
    clientSecret: 'YYYY',    
    issuer: 'https://XXX.auth.us-east-1.amazoncognito.com',
    signinUrl: 'http://localhost:3000/api/auth/signin/cognito',    
    callbackUrl: 'http://localhost:3000/api/auth/callback/cognito'
  },  message: 'expected 200 OK, got: 400 Bad Request'
```

**Comment by balazsorban44** [comment]
Looks like people have misread the docs. Please check the tip explaining how the issuer should look like: https://next-auth.js.org/providers/cognito

I just tested it locally, works fine.

**Comment by fram7** [comment]
I made it work, thank to the help of @balazsorban44

In Issuer you have to put, your aws region and your UserPoolId, that's not the same that ClientId

issuer: `https://cognito-idp.us-east-1.amazonaws.com/${process.env.COGNITO_USER_POOL_ID},`

<img width="547" alt="Erro2" src="https://user-images.githubusercontent.com/10606288/144336186-fadd0f6d-53b3-4e3c-9840-4df7bb1d3a31.png">

**Comment by vanduc1102** [comment]
Took me an hours to figure out.
Given you have this ARN: `arn:aws:cognito-idp:ap-southeast-1:74051077XX03:userpool/ap-southeast-1_XXnxUPYvFj4`


the issuer: `https://cognito-idp.ap-southeast.amazonaws.com/ap-southeast-1_XXnxUPYvFj4`

Notice the **cognito-idp** and **amazonaws.com** 
I was so into the Cognito Domain **https://2-xxxxxxxxxxxxxxxx.auth.ap-southeast-1.amazoncognito.com**
