### ISSUE TITLE
Facebook provider not working - next-auth v4.0.0-beta.4

### ISSUE THREAD

**Issue by davidgustys** [nextauthjs/next-auth#2934]
### Description 🐜

Seems the "state" query param is lost in between request. I did some light debugging it seems that the error originates from `node-openid-client` I saw that it had specific node.js requirements, but I do seem to meet them (14.18.0)

My current simple setup:
<img width="646" alt="Screenshot 2021-10-11 at 16 55 00" src="https://user-images.githubusercontent.com/627037/136802384-cc000bd0-ee1f-46b9-9033-ef09a207a8d0.png">

Error that I'm getting with (Debug enabled + additional logging):
<img width="2186" alt="Screenshot 2021-10-11 at 16 58 37" src="https://user-images.githubusercontent.com/627037/136802851-23ea8a0e-8137-47f2-b492-c6d4a47cb7c8.png">

### Is this a bug in your own project?

No

### How to reproduce ☕️

Just a simple setup as in the example.
Facebook login callback setting:
<img width="986" alt="Screenshot 2021-10-11 at 17 03 39" src="https://user-images.githubusercontent.com/627037/136803762-5c2bcefb-2b3b-4cb2-93b3-7a08e2916d9e.png">
 

### Environment 🖥

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 198.18 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
  Browsers:
    Chrome: 94.0.4606.71
    Edge: 94.0.992.38
    Firefox: 90.0.2
    Safari: 14.0
  npmPackages:
    next: ^11.1.2 => 11.1.2 
    next-auth: ^4.0.0-beta.4 => 4.0.0-beta.4 
    react: 17.0.2 => 17.0.2 

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by lionelrudaz** [comment]
Can you elaborate on your solution @davidgustys, because I've got the same error appearing from time to time? Thanks in advance

**Comment by davidgustys** [comment]
@lionelrudaz we basically had a custom next.js server entry point, which was modifying the req.url thus causing the next-auth to fail with some providers. 

So best to check if your code does not modify the req.url before reaching the next-auth handlers. Hope this helps.

**Comment by lionelrudaz** [comment]
Thanks @davidgustys, I'm afraid that's not my case. Will continue to dig into the issue.
