### ISSUE TITLE
Add secret signature on sessionToken

### ISSUE THREAD

**Issue by danirolopes** [nextauthjs/next-auth#2994]
### Description 📓

I use the sessionToken in my external API to authenticate the requests of my user. So, everytime I receive a request from my Next App with the NextAuth sessionToken, I have to hit the database to check the validity of the session token.

For security and stability reasons, I would like to verify if the sessionToken is valid before hitting the database, reducing the load when under attack

If we use the secret provided by the user to also sign the sessionToken, I can verify on the server if the request is valid

### How to reproduce ☕️

Implementation idea on 

```
function generateSessionToken(nextauthSecret) {
  const _randomUUID = _crypto.randomUUID;
  const signature = hashFunction(_randomUUID, nextauthSecret)
  return _randomUUID+"$"+"signature";
}
```

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
Your external API should not use the NextAuth.js generated session token. Any API route can already verify your token already. You could for example proxy your requests through an API endpoint, or use your provider's `access_token` when calling the third party.

See also, https://github.com/nextauthjs/next-auth/issues/3150#issuecomment-962982197
