### ISSUE TITLE
Can't complete the upgrade to v4, issues in documentation

### ISSUE THREAD

**Issue by lionelrudaz** [nextauthjs/next-auth#3023]
### Question 💬

Hey folks,

I was running through the [migration guide](https://next-auth.js.org/getting-started/upgrade-v4). Everything went smoothly, up to the point where I had to make some changes in the data model.

Here are the issues that I've faced:

1. I've renamed all fields email_verified as expected. But I had an error, because the User table still requires emailVerified. The guide is wrong, but the error was straightforward and I was able to fix it
2. There's no indication that the table verification_requests is now verification_tokens. Again, error was clear enough, I could fix it on my own
3. I can't request a new token by email. I've got the following error:

```
[next-auth][error][SIGNIN_EMAIL_ERROR] 
https://next-auth.js.org/errors#signin_email_error date/time field value out of range: "1635236284553" QueryFailedError: date/time field value out of range: "1635236284553"
    at QueryFailedError.TypeORMError [as constructor] (/Users/lionelrudaz/Sites/tasters/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new QueryFailedError (/Users/lionelrudaz/Sites/tasters/node_modules/typeorm/error/QueryFailedError.js:13:28)
    at PostgresQueryRunner.<anonymous> (/Users/lionelrudaz/Sites/tasters/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:277:31)
    at step (/Users/lionelrudaz/Sites/tasters/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/Users/lionelrudaz/Sites/tasters/node_modules/tslib/tslib.js:124:57)
    at rejected (/Users/lionelrudaz/Sites/tasters/node_modules/tslib/tslib.js:115:69)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  name: 'CreateVerificationTokenError'
```

There's no document explaining what I should do with that. Can you help me with this?

Let me know if you need more information.

### How to reproduce ☕️

Explained in the description.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by davecarlson** [comment]
Having the same issue with mine, tried creating a new project and the same. 

Could we AT LEAST get user.id added to the default. I know we are supposed to user augmentation, but it simply doesn't work at the moment. I know the typescript compiler is picking it up, but using a credentials provider, any extra fields I set just disappear. At least if I had the id, i could do a subsequent call to populate

**Comment by davecarlson** [comment]
Nevermind, finally got something working. I think the docs need extending in the example, and the augmentation is wrong.

types/next-auth.d.ts
```
import NextAuth from "next-auth"

global {
    declare module "next-auth" {
    /**
     * Returned by `useSession`, `getSession` and received as a prop on the `SessionProvider` React Context
     */

    interface User {
      id: string;
      name: string;
      email: string;
    }

    interface Session {
      user: User;
    }
  }
}
```

[...nextAuth.js]
```
providers: [
    Credentials({
      async authorize(credentials, req) {
        const user = {
          id: 123,
          name: 'me',
          image: 'photo.jpg',
          email: 'test@test.com'
        }
        return user
      }
],
callbacks: {
      async session({ session, user, token }) {
      session.user = {
        ...session.user,
        id: token.id
      }
      return session
}
```

**Comment by Zertz** [comment]
Unless I'm also missing something, it seems like the documentation is indeed slightly incomplete. Building on on @davecarlson's solution, I came up with this:

```ts
declare module "next-auth" {
  interface User extends Session["User"] {
    role: "admin" | "user";
  }

  interface Session {
    user: User;
  }
}
```
