### ISSUE TITLE
Support Next.js 12 Middleware

### ISSUE THREAD

**Issue by ramiel** [nextauthjs/next-auth#3037]
### Description 📓

After watching the recent Nextjs conf, I'm wondering if there's a way to move authentication api (here it's the `/session` endpoint) to run on the edge instead that on server. Looking at this very basic example 

https://youtu.be/PWi-49ODKAs?t=3203

maybe there's a way to take advantage of this in NextAuth too, even if in an opt-in way.

### How to reproduce ☕️

Nothing to reproduce

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
FYI there is a working example here https://github.com/nextauthjs/next-auth-example/pull/40

**Comment by ramiel** [comment]
That's great, a good starting point.    
Is RSC  "Rendered server components" or similar?

**Comment by ramiel** [comment]
Trying this by myself I get a `TypeError: getCurves is not a function` error on jose.

**Comment by balazsorban44** [comment]
React Server Components: https://reactjs.org/blog/2020/12/21/data-fetching-with-react-server-components.html

You will need `4.0.0-beta.6` at least, `jose` is working fine for the use case we have in `next-auth`

**Comment by ramiel** [comment]
Sure,that one 😀. Version beta 6 has problems for me, so I cannot upgrade. I'll have another look later.

**Comment by erlinghaugstad** [comment]
> FYI there is a working example here [nextauthjs/next-auth-example#40](https://github.com/nextauthjs/next-auth-example/pull/40)
> 
> it's only working with jwt sessions at the moment and there is no way to pass the session down as props to the page yet. So the client will have to make an additional API request and the authenticated page will experience a loading state, unlike if you use `getServerSideProps`. In my opinion, it means there is little gain using middleware here at the moment.

@balazsorban44 One thing that you can gain by using middlewares as is, is to for instance limit access to an entire subtree of paths, i.e adding a middleware to `/client/[id]/_middleware.ts` and check in the middleware if the user actually should have access to the client in question, i.e authorize. I can live with the double requests for now(not live yet) 😄 

Looking forward to a fully fledged integration with this, it does seem quite powerful 💪🏻

**Comment by batuhanbilginn** [comment]
import { getToken } from "next-auth/jwt"
import { NextResponse } from "next/server"

/** @param {import("next/server").NextRequest} req */
export async function middleware(req) {
  if (req.nextUrl.pathname === "/middleware-protected") {
    const session = await getToken({ req, secret: process.env.SECRET })
    // You could also check for any property on the session object,
    // like role === "admin" or name === "John Doe", etc.
    if (!session) return NextResponse.redirect("/api/auth/signin")
    // If user is authenticated, continue.
  }
}

This example doesn't work in production :/ @balazsorban44 Did you test in production? Does anything that comes to your mind cause a bug in production such as secure cookies etc?

**Comment by balazsorban44** [comment]
Sorry, I can see the problem. I assume you deployed to Vercel. This change was necessary to get it working:

https://github.com/nextauthjs/next-auth-example/blob/3af7650733b236cb70334c99ada38c93e09fd705/pages/_middleware.js#L11-L13

I turned down an offer to fix this out-of-box at https://github.com/nextauthjs/next-auth/pull/1672#issuecomment-815924589 by @cathykc :grimacing:

Given we still support `VERCEL_URL` at other places and it doesn't seem to change right now, we should probably go "all in", rather than creating confusion by removing it at other places, not to mention it would be a breaking change anyway, which I don't intend to do right now. I'll follow up in a PR, until then, see the code I linked above.

**Comment by batuhanbilginn** [comment]
> Sorry, I can see the problem. I assume you deployed to Vercel. This change was necessary to get it working:
> 
> https://github.com/nextauthjs/next-auth-example/blob/3af7650733b236cb70334c99ada38c93e09fd705/pages/_middleware.js#L11-L13
> 
> I turned down an offer to fix this out-of-box at [#1672 (comment)](https://github.com/nextauthjs/next-auth/pull/1672#issuecomment-815924589) by @cathykc 😬
> 
> Given we still support `VERCEL_URL` at other places and it doesn't seem to change right now, we should probably go "all in", rather than creating confusion by removing it at other places, not to mention it would be a breaking change anyway, which I don't intend to do right now. I'll follow up in a PR, until then, see the code I linked above.

We have fixed almost in the same time  :) This was mine:

```js
const session = await getToken({
    req: request,
    secret: process.env.SECRET,
    secureCookie: process.env.NODE_ENV === "production",
  });
```

Anyway, thank you for the quick support!

**Comment by balazsorban44** [comment]
It would break when you want to test a production build locally on `http://localhost:3000`. We know that you set `NEXTAUTH_URL` though, so we can rely on that locally, and then rely on `VERCEL_URL` in production. But glad that you figured out a solution!

**Comment by balazsorban44** [comment]
Hmm. It looks like setting `secureCookie` inside `_middleware` *is* required. My change here https://github.com/nextauthjs/next-auth/blob/30a0fc6bc0246b30eb03c19b8a0ceb6c040c1b2e/src/jwt/index.ts#L73-L74

was not picked up otherwise.

**Comment by always-maap** [comment]
imagine a protected website like an admin panel. the whole application is behind a middleware. 

```typescript
// pages/_middleware.ts
export async function middleware(req: any) {
  const session = await getToken({ req, secureCookie: '' });
  // redirect directly to provider
  const signInUrl = getSignIn(args)
  if (!session) return NextResponse.redirect(signInUrl);
}
```

currently, this is not possible. getSignIn like method needed. right?

**Comment by alessandrojcm** [comment]
> imagine a protected website like an admin panel. the whole application is behind a middleware.
> 
> ```ts
> // pages/_middleware.ts
> export async function middleware(req: any) {
>   const session = await getToken({ req, secureCookie: '' });
>   // redirect directly to provider
>   const signInUrl = getSignIn(args)
>   if (!session) return NextResponse.redirect(signInUrl);
> }
> ```
> 
> currently, this is not possible. getSignIn like method needed. right?

If you know the name of the provider you want to sign in with, you can just redirect using the [REST API](https://next-auth.js.org/getting-started/rest-api#post-apiauthsigninprovider)

Taking your snippet:

```typescript
// pages/_middleware.ts
export async function middleware(req: any) {
  const session = await getToken({ req, secureCookie: '' });
  if (!session) return NextResponse.redirect(`${NEXTAUTH_URL}/api/auth/signin/google);
  return NextResponse.next();
}
```

**Comment by alessandrojcm** [comment]
That is not possible, as the sign-in process needs to be initiated client-side by calling `signIn`; I had the same problem, see https://github.com/nextauthjs/next-auth/discussions/2719

**Comment by always-maap** [comment]
@balazsorban44

I see but this step is uncessery. starting sign-in in the server is beneficial. we can use _middleware in page/profile and redirect all requests to sign-in. currently, I use getInitialProps and `signIn()` in client-side. which is not the best user and developer experience. if the sign-in API becomes public helps a lot.

**Comment by balazsorban44** [comment]
This https://github.com/nextauthjs/next-auth/issues/3037#issuecomment-989028923 should not be necessary if/when https://github.com/vercel/next.js/pull/33141 lands.

**Comment by zpg6** [comment]
> This [#3037 (comment)](https://github.com/nextauthjs/next-auth/issues/3037#issuecomment-989028923) should not be necessary if/when [vercel/next.js#33141](https://github.com/vercel/next.js/pull/33141) lands.

Looks to have landed in [12.0.8](https://github.com/vercel/next.js/releases/tag/v12.0.8) release yesterday 🚀

**Comment by balazsorban44** [comment]
I am proposing a `withAuth` method, that could add authentication for the whole site (or any subsection) with a single line! Please check out #3657 and tell me what you think!

**Comment by develowl** [comment]
Hey guys, this way work to me. I hope could help someone out too.

`
      const csrfTokenResponse = await fetch(`${baseUrl}/csrf`)
      const { csrfToken } = await csrfTokenResponse.json()

      const headers = new Headers()
      headers.append('Content-Type', 'application/x-www-form-urlencoded')
      headers.append('Cookie', csrfTokenResponse.headers.get('set-cookie')!)

      const buildAuthorize = await fetch(`${baseUrl}/signin/auth0`, {
        method: 'POST',
        headers,
        // @ts-expect-error
        body: new URLSearchParams({
          csrfToken,
          json: true
        })
      })
      const { url } = await buildAuthorize.json()

      return NextResponse.redirect(url)
`

**Comment by develowl** [comment]
Hey guys, this way helped me out.

```

      const csrfTokenResponse = await fetch('http://app.local:3000/api/auth/csrf')
      const { csrfToken } = await csrfTokenResponse.json()

      const headers = new Headers()
      headers.append('Content-Type', 'application/x-www-form-urlencoded')
      headers.append('Cookie', csrfTokenResponse.headers.get('set-cookie')!)

      const buildAuthorize = await fetch('http://app.local:3000/api/auth/signin/auth0', {
        method: 'POST',
        headers,
        // @ts-expect-error
        body: new URLSearchParams({
          csrfToken,
          json: true
        })
      })
      const { url } = await buildAuthorize.json()

      return NextResponse.redirect(url)
    
```

**Comment by jim-y** [comment]
> Hey guys, this way helped me out.
> 
> ```
> 
>       const csrfTokenResponse = await fetch('http://app.local:3000/api/auth/csrf')
>       const { csrfToken } = await csrfTokenResponse.json()
> 
>       const headers = new Headers()
>       headers.append('Content-Type', 'application/x-www-form-urlencoded')
>       headers.append('Cookie', csrfTokenResponse.headers.get('set-cookie')!)
> 
>       const buildAuthorize = await fetch('http://app.local:3000/api/auth/signin/auth0', {
>         method: 'POST',
>         headers,
>         // @ts-expect-error
>         body: new URLSearchParams({
>           csrfToken,
>           json: true
>         })
>       })
>       const { url } = await buildAuthorize.json()
> 
>       return NextResponse.redirect(url)
>     
> ```

This is working, I just hope next-auth will add an abstraction like this. E.g

```
export default function middleware(req: NextRequest) {
    if (['/', '/page', '/anotherpage'].some((path) => path === req.nextUrl.pathname)) {
        return withAuth(req, {
            provider: 'auth0'
            redirectToIdP: true
        });
    }
}
```

**Comment by redarccoder** [comment]
The way I solved this was:
* Add a secret to my [...nextauth].ts file
![image](https://user-images.githubusercontent.com/3534955/157074252-8e625fd5-dfd9-432b-a1c8-9cd73296bf46.png)

* Use that secret while getting my token:
![image](https://user-images.githubusercontent.com/3534955/157074540-9ed37fcc-6d43-4a0b-905b-b7312620c984.png)

And ready, you can get your token from the middleware
