### ISSUE TITLE
Add back default secret generation for dev convenience

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#3044]
#3039 removed the automatic secret generation. We should add it back, **but** make it much more clear that this is only intended as a convenience in development. We should probably throw an error if we detect the user is in production and they don't have a secret explicitly defined.

**Comment by balazsorban44** [comment]
Addressed in #3143. Will show this warning https://next-auth.js.org/warnings#no_secret

**Comment by Zertz** [comment]
Any suggestion as to what should be used in production? I'm thinking something with `crypto.randomBytes` but I'm no security expert! What about length, encoding, etc.? Would it be possible to add guidelines in the docs?
