### ISSUE TITLE
Custom model/user property in V4

### ISSUE THREAD

**Issue by vahidtakro** [nextauthjs/next-auth#3070]
### Question 💬

Hello, how can I add custom model on v4?
I am using Prisma provider, and I added new column to User table, called username,
I want to get `{session.user.username}` how can I add username property?

### How to reproduce ☕️

now I get this error:
![Screenshot 2021-10-30 143726](https://user-images.githubusercontent.com/40500566/139530582-a69b7f5b-be10-41ac-9e79-26932991d2b2.jpg)

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
https://next-auth.js.org/getting-started/typescript
