### ISSUE TITLE
Access_token in profileUrl?

### ISSUE THREAD

**Issue by nikitalk** [nextauthjs/next-auth#308]
Hi! I'm trying to make an authentication via [mail.ru](https://mail.ru). According to the [documentation](https://o2.mail.ru/docs), it is necessary to include `access_token` into the request for user information. Is it possible to add` access_token `to profileUrl like this `https://oauth.mail.ru/userinfo?access_token=8e41b7a475aa7691aeead06ef0db28f989fbab0c37363830`?

**Comment by LoriKarikari** [comment]
The access token is automatically added to the profileUrl. So it should work without it.

**Comment by nikitalk** [comment]
But metadata shows:
```js
{
  error: 'invalid request',
  error_code: 2,
  error_description: 'missing request parameter: access_token'
}
```

**Comment by iaincollins** [comment]
Hmm, can you share your provider details? (minus Client ID/Secret)?

Maybe we need to do something special for this provider - a small number of providers have uncommon implementations and require specific hacks to support (e.g. Okta, Twitch).

**Comment by nikitalk** [comment]
```js
export default (options) => {
  return {
    id: 'mailru',
    name: 'Mail.ru',
    type: 'oauth',
    version: '2.0',
    scope: 'userinfo',
    params: { grant_type: 'authorization_code' },
    accessTokenUrl: 'https://oauth.mail.ru/token',
    requestTokenUrl: 'https://oauth.mail.ru/token',
    authorizationUrl: 'https://oauth.mail.ru/login?response_type=code',
    profileUrl: 'https://oauth.mail.ru/userinfo',
    profile: (profile) => {
      return {
        id: profile.id,
        name: profile.name,
        email: profile.email,
        image: profile.image,
      };
    },
    ...options,
  };
};
```

**Comment by nikitalk** [comment]
Error:
![image](https://user-images.githubusercontent.com/33490517/85413476-88d8d680-b573-11ea-93eb-7b267852bd05.png)

**Comment by iaincollins** [comment]
Thanks! Will take a look later.

**Comment by nyedidikeke** [comment]
#521 adds support for [Mail.ru](https://mail.ru/) as [custom OAuth Service Provider](https://next-auth.js.org/configuration/providers#using-a-custom-provider).

Also, built-in support for Mail.ru has been added.

**Comment by ndom91** [comment]
Closing this issue as the PR is basically completed and the discussion as moved there (https://github.com/nextauthjs/next-auth/pull/522)
