### ISSUE TITLE
Can make magic link work cross devices?

### ISSUE THREAD

**Issue by shouze** [nextauthjs/next-auth#309]
*Please refer to the [documentation](https://next-auth.js.org/getting-started/introduction), the [example project](https://github.com/iaincollins/next-auth-example) and existing issues before creating a new issue.*

**Your question**
Can make magic link work cross devices?

**What are you trying to do**
Given passwordless & magic link signin, is it possible to add the feature that kind of scenario:
1. I start signin process on my desktop
2. I open email with magic link on my phone and click on it
3. I get logged in on my desktop as on my phone

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
This isn't currently supported, but would welcome something like this as a feature request!

I would love to have session management and sign in / sign out be possible across devices.
