### ISSUE TITLE
Strava provider bad request

### ISSUE THREAD

**Issue by alexclark-nz** [nextauthjs/next-auth#3090]
## Issue

With the NextAuth v4 Beta, am getting a the error message "expected 200 OK, got: 400 Bad Request" after authorizing the app through Strava. Seems to work okay in NextAuth V3.

## Additional context

My project uses Prisma with "@next-auth/prisma-adapter": "^0.5.2-next.19".

### Is this a bug in your own project?

No

### Reproduction: 

[Next Auth Strava Provider Reproduction](https://github.com/alexclark-nz/nextauth-strava-provider-reproduction)

I've included a working provider (Google) in the project to narrow it down. To reproduce accurately..

```
cp .env.example .env
```

1. Add the Strava and Google credentials, along with database URL
2. ```npm install && npx prisma migrate dev --name="init"```
3. ```npm run dev```
4. Click "Sign in"
5. Authorize the application with Strava
6. Receive error on callback

### Screenshots / Logs 📽

[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error expected 200 OK, got: 400 Bad Request {
  error: {
    message: 'expected 200 OK, got: 400 Bad Request',
    stack: 'OPError: expected 200 OK, got: 400 Bad Request\n' +
      '    at processResponse (/Users/alex/Sites/SITENAME/node_modules/openid-client/lib/helpers/process_response.js:48:11)\n' +
      '    at Client.grant (/Users/alex/Sites/SITENAME/node_modules/openid-client/lib/client.js:1265:26)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
      '    at async Client.oauthCallback (/Users/alex/Sites/SITENAME/node_modules/openid-client/lib/client.js:561:24)\n' +
      '    at async oAuthCallback (/Users/alex/Sites/SITENAME/node_modules/next-auth/core/lib/oauth/callback.js:105:16)\n' +
      '    at async Object.callback (/Users/alex/Sites/SITENAME/node_modules/next-auth/core/routes/callback.js:50:11)\n' +
      '    at async NextAuthHandler (/Users/alex/Sites/SITENAME/node_modules/next-auth/core/index.js:103:28)\n' +
      '    at async NextAuthNextHandler (/Users/alex/Sites/SITENAME/node_modules/next-auth/next/index.js:40:7)\n' +
      '    at async /Users/alex/Sites/SITENAME/node_modules/next-auth/next/index.js:80:32',
    name: 'OPError'
  },
  providerId: 'strava',
  message: 'expected 200 OK, got: 400 Bad Request'
}
[next-auth][error][CALLBACK_OAUTH_ERROR] 
https://next-auth.js.org/errors#callback_oauth_error expected 200 OK, got: 400 Bad Request OPError: expected 200 OK, got: 400 Bad Request
    at processResponse (/Users/alex/Sites/SITENAME/node_modules/openid-client/lib/helpers/process_response.js:48:11)
    at Client.grant (/Users/alex/Sites/SITENAME/node_modules/openid-client/lib/client.js:1265:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Client.oauthCallback (/Users/alex/Sites/SITENAME/node_modules/openid-client/lib/client.js:561:24)
    at async oAuthCallback (/Users/alex/Sites/SITENAME/node_modules/next-auth/core/lib/oauth/callback.js:105:16)
    at async Object.callback (/Users/alex/Sites/SITENAME/node_modules/next-auth/core/routes/callback.js:50:11)
    at async NextAuthHandler (/Users/alex/Sites/SITENAME/node_modules/next-auth/core/index.js:103:28)
    at async NextAuthNextHandler (/Users/alex/Sites/SITENAME/node_modules/next-auth/next/index.js:40:7)
    at async /Users/alex/Sites/SITENAME/node_modules/next-auth/next/index.js:80:32 {
  name: 'OAuthCallbackError'
}

### Environment 🖥

System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 6.25 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh

  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm

  Browsers:
    Brave Browser: 95.1.31.87
    Chrome: 95.0.4638.54
    Edge: 95.0.1020.40
    Firefox: 93.0
    Firefox Developer Edition: 84.0
    Safari: 15.0

  npmPackages:
    next: latest => 11.1.2 
    next-auth: ^4.0.0-beta.6 => 4.0.0-beta.6 
    react: ^17.0.2 => 17.0.2

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
This provider hasn't been updated to support v4 yet. It's being tracked here: https://github.com/nextauthjs/next-auth/issues/2524
