### ISSUE TITLE
Cannot use discord authentication

### ISSUE THREAD

**Issue by callumok2004** [nextauthjs/next-auth#3091]
### Question 💬

I get the following error, any idea's why?

![139435390-b5b3dc86-6e43-4b59-b3af-fe8986593da0 1](https://user-images.githubusercontent.com/35779365/139742054-5e96f477-5b7b-4c6a-92a6-9a3228a07770.png)

### How to reproduce ☕️

```ts
export default NextAuth({
    providers: [
        Providers.Discord({
            clientId: process.env.DISCORD_ID,
            clientSecret: process.env.DISCORD_SECRET,
            scope: "guilds"
        })
    ],
    pages: {
        signIn: "/dashboard",
        error: "/auth/error"
    }
})
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Seems like you already opened a discussion about this, please don't open duplicates. https://github.com/nextauthjs/next-auth/discussions/3065
