### ISSUE TITLE
getToken call changed from next-auth.4.0.0-beta.4 and next-auth.4.0.0-beta.6

### ISSUE THREAD

**Issue by carlevans72** [nextauthjs/next-auth#3092]
### Description 🐜

In next-auth.4.0.0-beta.4 I was using the following code:

```
const token = await getToken({ req, secret: process.env.JWT_SECRET });
```

Since next-auth-beta.6 I'm now getting the following error:

```
TS2345: Argument of type '{ req: NextApiRequest; secret: string; }' is not assignable to parameter of type 'GetTokenParams<false>'.   Property 'decode' is missing in type '{ req: NextApiRequest; secret: string; }' but required in type 'Pick<JWTOptions, "decode" | "secret">'.
```

The documentation says to use the code as I have it so unsure why this is now an issue.

### Is this a bug in your own project?

No

### How to reproduce ☕️

Add code in IDE

### Screenshots / Logs 📽

<img width="904" alt="Screenshot 2021-11-01 at 22 25 18" src="https://user-images.githubusercontent.com/42074841/139750215-8b3d3ccd-5e60-4636-8c94-901937b58bc8.png">
)

### Environment 🖥

System:
    OS: macOS 11.6
    CPU: (8) x64 Apple M1
    Memory: 230.16 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/Code/saas-admin/node_modules/.bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 95.0.4638.54
    Firefox: 93.0
    Safari: 15.0
  npmPackages:
    next-auth: 4.0.0-beta.6 => 4.0.0-beta.6

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
Indeed, it should be optional, but we don't handle TS errors as breaking as per docs: https://next-auth.js.org/getting-started/typescript#contributing

Thank you for pointing it out anyway, feel free to open a PR against the `beta` to fix it!

Some options have also been removed, which will be documented in the [migration docs](https://next-auth.js.org/getting-started/upgrade-v4)

**Comment by ashalfarhan** [comment]
Hi @balazsorban44 , can grab this up?. if there's no one is working on this issue

**Comment by balazsorban44** [comment]
Sorry for the late reply, [`edb7e9f` (#3101)](https://github.com/nextauthjs/next-auth/pull/3101/commits/edb7e9fd987bbeb339dfe3e1e0b512e78e4019ce) will actually address this.

**Comment by balazsorban44** [comment]
#3101 merged now, will be out hopefully in a few days.

**Comment by carlevans72** [comment]
That's brilliant - thanks so much @balazsorban44

**Comment by balazsorban44** [comment]
out now https://github.com/nextauthjs/next-auth/releases/tag/v4.0.0-beta.7

**Comment by carlevans72** [comment]
All is working great until come to build and getting an error

openid-client/lib/client.js
line 163

Basically # characters in the above package.

Have you experienced any issues at all?

**Comment by balazsorban44** [comment]
please create a reproduction as asked here https://github.com/panva/node-openid-client/discussions/428#discussioncomment-1647385

**Comment by carlevans72** [comment]
Thanks @balazsorban44 
I’ll try upgrade to webpack5 as you suggest
