### ISSUE TITLE
No session is returned from Strava Provider

### ISSUE THREAD

**Issue by dbeaudway** [nextauthjs/next-auth#3118]
### Question 💬

I'm trying to use the Strava Provider but after authorizing the session is undefined and the callback() functions are never called. Also, I think believe the existing documentation is out-of-date because providing the default values returns an error message.

What is the correct way to use the Spotify Provider in v4?

### How to reproduce ☕️

1. Supplying default values redirects to an error page:
```
StravaProvider({
   clientId: process.env.STRAVA_CLIENT_ID,
   clientSecret: process.env.STRAVA_CLIENT_SECRET
})
```

2. Manually adding the `authorization` key will correctly re-direct you back to your site after authorizing the app. However, the `[...nextauth].js` callback section is never called and the session is `{data: null, status: 'unauthenticated'}`. I can't find any documentation where it says to use `authorization` though. Also, if you re-sign in the app asks for authorization again.
```
StravaProvider({
   clientId: process.env.STRAVA_CLIENT_ID,
   clientSecret: process.env.STRAVA_CLIENT_SECRET,
   authorization: `https://www.strava.com/api/v3/oauth/authorize?client_id=${process.env.STRAVA_CLIENT_ID}&response_type=code&redirect_uri=http://localhost:3000&approval_prompt=force&scope=activity:read_all`
})
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
you mention Spotify once, but 8 believe it's a typo? Starava hasn't been tested with v4 yet. see https://github.com/nextauthjs/next-auth/issues/2524
