### ISSUE TITLE
What is the best way to extend a user profile?

### ISSUE THREAD

**Issue by jaredwiener** [nextauthjs/next-auth#312]
**Your question**
What is the best way to extend a user profile with custom fields?

**What are you trying to do**
I want to store more information about a user -- things like billing information, a username, etc.  I would rather not build a whole new database adapter.  I am okay with storing this information in a separate DB table, but curious if I can expose some form of unique ID that I can use as a primary key?

Are there recommended ways of doing this?

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [X] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
It's a good question, the answer to which is this isn't documented yet and you can track it here:

*  Document how to use custom models #283

**Comment by ndom91** [comment]
Closing this issue as tere is now official documentation on how to extend the user model, for example.

https://next-auth.js.org/tutorials/typeorm-custom-models

If you have any new question, etc. feel free to reopen it!

**Comment by dolie** [comment]
Hello,
I would like to extend the user model to return extra data (first name etc...) inside the JWT.
To do it, the doc describes:
```javascript
  adapter: Adapters.TypeORM.Adapter(
    // The first argument should be a database connection string or TypeORM config object
    "mysql://username:password@127.0.0.1:3306/database_name",
```
Unfortunatly, I'm using Credentials provider, and do not use a database.
Do you have a solution or a specific example to return extradata into the JWT during the signin ?
Thank you !

**Comment by DeBraid** [comment]
@ndom91 

https://next-auth.js.org/tutorials/typeorm-custom-models shows config with database.  Is it possible to extend the `user` model with Adapters and no DB?  I tried passing `null` for DB url, but this failed.

**Comment by ndom91** [comment]
I know you can add properties to the session, and therefore the user object, in the session callback.

https://next-auth.js.org/configuration/callbacks#session-callback

Maybe that can help you along.

**Comment by DeBraid** [comment]
@ndom91 related: https://github.com/nextauthjs/next-auth/issues/562#issuecomment-716740547

I'd prefer to use the `authorize` function to extend `user` since I have already made an API call here and have the relevant dat a accessible.  

Would love to NOT delegate this to state mgmt (Redux, Apollo, etc) and instead rely on `session.user` throughout the app.  I could make additional API call in the `session` callback, but that assumes I have an endpoint like `getUserByRole`, which I may not (role is returned when user gets authenticated). 

Thanks for your help!

**Comment by dohomi** [comment]
Hello,

I'd like to elaborate if this package can extend the profile with user roles: https://github.com/nextauthjs/next-auth/issues/312#issuecomment-671575050
I checked the documentation but for me things like: 
```
- user modifies his roles through buying a product
- refresh user credentials with new user roles
```
How would the database would be updated? Or better how could the a server side callback adjust the user credentials and refetch the new data client side

**Comment by ndom91** [comment]
@iaincollins do you have any suggestion on how best to manipulate the user object? With or without a db?

**Comment by DeBraid** [comment]
My current (hopefully very short term) work around involves hijacking the `image` property on `session.user` and assigning it the value for `role` which is returned by Auth API.

```
import fetch from 'isomorphic-unfetch';

import { API_ENDPOINT } from './constants';

export default async function login({ email, password }) {
  const body = {
    Email: email,
    Password: password,
  };
  const requestOptions = {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(body),
  };

  const response = await fetch(`${API_ENDPOINT}/users/login/`, requestOptions);
  const { user, error } = await response.json(); // user.role send from API response, need to store this on session.user somehow
  if (error) {
    return Promise.reject(`/login?error=${error}&email=${email}`);
  }
  const userToResolve = {
    email: user.Email,
    image: user.Role || 'user', // FIXME DB hack for next-auth user object, set image = role
  };
  return Promise.resolve(userToResolve);
}
```

Obviously, I don't want to do this, and would prefer simply adding `role` to `userToResolve` like so: 

```
  ...
  const userToResolve = {
    email: user.Email,
    role: user.Role || 'user',
  };
  return Promise.resolve(userToResolve);
}
```

Despite extending the `userToResolve` object with arbitrary properties, the `session.user` persist only 3 fields: name, image, email.

**Comment by elilambnz** [comment]
To extend the user without using a database, you can modify the JWT when it is created (i.e. when logging in for the first time), then update the session user from the extra data in the JWT. This is my solution:

```js
callbacks: {
  jwt: async (token, user, account, profile, isNewUser) => {
    // The user argument is only passed the first time this callback is called on a new session, after the user signs in
    if (user) {
      // Add all user entries to the token
      Object.entries(user).forEach(([k, v]) => {
        token[k] = v
      })
    }
    return Promise.resolve(token)
  },
  session: async (session, user) => {
    // Assign user from JWT to session user
    Object.entries(user).forEach(([k, v]) => {
      // Ignore iat and exp keys
      if (k !== 'iat' && k !== 'exp') {
        session.user[k] = v
      }
    })
    return Promise.resolve(session)
  },
}
```

**Note:** it appears that the session callback gets called often, so updating the session user frequently may not be the best solution. I've only been using this library for a few hours, so I'm far from an expert on this!

**Comment by aequasi** [comment]
Can we re-open this ticket and get an official way to extend the user model when not using a DB? cc/ @ndom91 @iaincollins

**Comment by ndom91** [comment]
@aequasi sure, but I think the only way to do this is in the JWT callback. See @elilambnz last post and the docs here: https://next-auth.js.org/configuration/callbacks#jwt-callback

**Comment by subimage** [comment]
Running into this today, while using the firestore adapter. This is not simple, or straightforward. Should not be so hard!

**Comment by marcogalvanize** [comment]
Writing a custom DB adapter with a custom provider and having difficulties extending the user object. The `AdapterUser` object will have a stringified value, but the `User` object will have the `JSON.parsed` equivalent.

My understanding is that the profile callback of the Custom Provider will provide the Type for the `User`.

The `AdapterUser` type extends this profile type `User` that is inferred from the return type of the profile callback.

This has been problematic for my use case as the `AdapterUser` will have `field: string` and `User` will have `field: Record<string, any>`

The adapter will be used to manage the sessions exclusively and long-term application state will be held in the OAuth provider as JSON.

I am nearing a solution but I must concede that the implicated types from the profile/session/ect callbacks without clarifications about how to explicitly extend or omit properties on these types is quite challenging.
