### ISSUE TITLE
Add Binance provider

### ISSUE THREAD

**Issue by jferrettiboke** [nextauthjs/next-auth#3122]
### Description 📓

Binance is a cryptocurrency exchange which is currently the largest exchange in the world in terms of daily trading volume of cryptocurrencies. We have already Coinbase, why not adding Binance as well to our provider set? 🤠

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
Not familiar with this provider but it sounds like they support OAuth, so it's no problem
https://developers.binance.com/docs/api/apis

Check out

https://next-auth.js.org/configuration/providers/oauth-provider#adding-a-new-provider

(please open the PR againast the `beta` branch for now)

**Comment by balazsorban44** [comment]
There was an attempt at adding it in #3128, but the OP hasn't responded to my suggestions, and I would to have a clean repo before next week, we'll do a major release of `next-auth`. We can revisit this when v4 has landed.
