### ISSUE TITLE
MongoDB Adapter | m.collection is not a function

### ISSUE THREAD

**Issue by callumok2004** [nextauthjs/next-auth#3132]
### Question 💬

I am attempting to use the MongoDB database adapter, but it is giving me the error mentioned in the title and I cannot seem to figure out why, any ideas?

### How to reproduce ☕️

https://github.com/callumok2004/nextjs-reproduction

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
wrong repo, but you opened this already, and then closed it...? 

https://github.com/nextauthjs/adapters/issues/293

pleas e help us maintaining this project by not opening multiple issues/discussions with the same question. 🙏
