### ISSUE TITLE
Can "getSession" used in new Next.js middleware (on the edge) to validate the cookie and token?

### ISSUE THREAD

**Issue by saadahmedkhan** [nextauthjs/next-auth#3136]
### Description 📓

I recently tried NextAuth and I loved how complete it is. With Next.js 12 release, I am wondering if method getSession or useSession be used on the edge / server-side (middleware) for cookie and its content validation?

### How to reproduce ☕️

No code to reproduce

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
#3037

**Comment by roelandmoors** [comment]
Issue #3037 is closed, but I don't think this issue is the same question.
It would be great if useSession/getSession could also get the user from edge (if using JWT)

**Comment by surjithctly** [comment]
In case someone wondering: Here's the new way for middleware: https://next-auth.js.org/configuration/nextjs#middleware
