### ISSUE TITLE
Sending cookies to custom server

### ISSUE THREAD

**Issue by AashJ** [nextauthjs/next-auth#3137]
### Question 💬

I have a nextjs application using next-authjs and the github provider. I've successfully logged in and I see my cookies are being set. When i send requests to a next api route I see the cookies are sent in the request header. However, when i send requests to a route at localhost:4000 the cookies are not being sent in the header. What can I do to include them with every request?

### How to reproduce ☕️

This is my current nextauth config:

```
export default NextAuth({
    // Configure one or more authentication providers
    adapter: PrismaAdapter(prisma),
    providers: [
        GitHubProvider({
            clientId: process.env.GITHUB_ID,
            clientSecret: process.env.GITHUB_SECRET,
        }),
    ],
})
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
You don't want to do that. you should scope the cookies for the same site. (that is the default behaviour for next-auth)

im curious what's the usecase?
