### ISSUE TITLE
callbackUrl doesn't work except on localhost

### ISSUE THREAD

**Issue by bdelamotte** [nextauthjs/next-auth#3139]
### Description 🐜

callbackUrl works fine on localhost, but when deploying to Vercel with a URL that has redirect to www automatically it breaks. 

Here is how we used the signIn callbackUrl: 
`onClick={() => signIn(null, { callbackUrl: `${window.location.origin}/dashboard` })}`

Here is the default code from getting it off [here](https://next-auth.js.org/configuration/callbacks#redirect-callback): 

Attached is my Vercel setup which redirects my domain.com to www.domain.com. Because of this redirect (vercel prefers doing this because they say performance on www is better), it breaks the signin callback url.

The solution was to re-write the redirect callback like this:
```
    redirect({ url, baseUrl }) {
      // Handles redirects that automatically add www (Vercel does this because www is preferred by them)
      if(url.includes('www.') && ! baseUrl.includes('www.')) {
        const urlWithoutWWW = url.replace('www.', '')
        return urlWithoutWWW.startsWith(baseUrl) ? url : baseUrl
      }
      return url.startsWith(baseUrl) ? url : baseUrl
    }
```

I'm submitting this in the hopes that it saves other people a few hours to track down this issue and also maybe to see if NextAuth would like to deploy similar logic to the default of the redirect function. 

### Is this a bug in your own project?

No

### How to reproduce ☕️

Deploy to Vercel with a domain that has redirect on for www and then use the callbackUrl option in NextAuth. It won't work unless you strip out 'www'. from the url before comparing to the baseUrl. 

### Screenshots / Logs 📽

![domain setup](https://user-images.githubusercontent.com/8355841/140622678-b2d82717-a848-48ba-96da-711c6721f4a2.png)
![default redirect](https://user-images.githubusercontent.com/8355841/140622681-5c1b2008-979a-41ce-b484-984e29bc1793.png)
![logging](https://user-images.githubusercontent.com/8355841/140622684-efa2dc31-4dd1-474a-a831-51f49c39cb58.png)
![new redirect](https://user-images.githubusercontent.com/8355841/140622692-33adb434-4e35-4e62-8b04-796948e66fee.png)

### Environment 🖥

 System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 1002.59 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.19.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Safari: 15.0
  npmPackages:
    next: 11.0.1 => 11.0.1 
    next-auth: ^4.0.0-beta.2 => 4.0.0-beta.2 
    react: 17.0.2 => 17.0.2 

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
I don't see the bug here, you even gave a "fix". I guess we could loosen the default redirect logic to also allow relative URLs.

Feel free to submit a PR https://github.com/nextauthjs/next-auth/blob/f998bf27688deb2197550448ee49bc4faf93de49/src/core/lib/default-callbacks.ts#L8

**Comment by bdelamotte** [comment]
@balazsorban44 , thanks for looking at this. Actually the fix I gave didn't seem to work even though the redirect callback was returning the url instead of baseUrl, so I think it potentially is still a bug. I wanted to log all this so others running into the same thing could search and find a possible solution. 

It didn't fully work until I did this in the front-end
```
onClick={() => signIn(null, { callbackUrl: `${window.location.origin.replace('www.','')}/dashboard` })}
```

Looking at #3140, It looks like that would work great and would be a great feature! I am concerned that whatever is looking at the return of the callback is not always honoring it though since my original fix above didn't work without also replacing the www's in the callbackUrl too.

**Comment by balazsorban44** [comment]
I believe you could have just done:

Client:
```js
onClick={() => signIn(null, { callbackUrl: "/dashboard" })}
```

Server:

```js
async redirect({ url, baseUrl }) {
  if (url.startsWith(baseUrl)) return url
  // If the redirect url is not absolute, prepend with base URL
  return new URL(url, baseUrl.replace("www.", "")).toString()
},
```

**Comment by bdelamotte** [comment]
@balazsorban44 , Thank you! I'll test that right now.

**Comment by bdelamotte** [comment]
@balazsorban44 That did the trick. In that case, I really think the community would value from #3140. Thank you so much for the help.
