### ISSUE TITLE
Provide JWKS Endpoint and generated RS256 keys

### ISSUE THREAD

**Issue by micheljung** [nextauthjs/next-auth#3150]
### Description 📓

Since #1543 was closed for not following the template, here's my attempt

NextAuth.js can generate JWKs but currently does so with a symmetric HS512 key. In order for another application (e.g. API backend) to verify a JWT, it needs to know the signing key. Therefore, generated keys are basically useless and the key needs to be generated by hand and configured in both applications.

To avoid having to generate and copy the signing key, a private/public key pair could be generated by NextAuth.js instead, and the public key would be exposed by `[...nextauth].js` as `jwks`. See https://eu.battle.net/oauth/jwks/certs as an example of a JWKS endpoint and [Auth0's Navigating RS256 and JWKS](https://auth0.com/blog/navigating-rs256-and-jwks/) about how it works.

This way, consumers can look up the public key and verify the JWT without having the signing key configured.

### How to reproduce ☕️

A non-existing feature can't be reproduced.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
`next-auth` does not try to be an Identity Provider, so I feel this would not match our goals with the library well, at least not in the short term... Your external APIs should generally use the `access_token` provided by your Identity Provider (the one that you log in within your app). If you use API routes at the backend, that will already understand and parse the JWT as expected (eg using `getToken`).

**Comment by micheljung** [comment]
Ok, I was hoping I could reuse the JWT but I'll look into using the `access_token` again.

**Comment by micheljung** [comment]
I got it working by passing the `access_token` via callbacks to `session` as documented and sending it via `Authorization: Bearer $ACCESS_TOKEN` header to my API calls which will then call the IDP for introspection. As for me, this can be closed.

**Comment by hems** [comment]
> I got it working by passing the `access_token` via callbacks to `session` as documented and sending it via `Authorization: Bearer $ACCESS_TOKEN` header to my API calls which will then call the IDP for introspection. As for me, this can be closed.

Assuming by "IDP" you mean "Identity Provider", could you explain how you do "call the IDP" for introspection? 

Considering there are multiple credential providers ( credentials, email, google, facebook, etcs... ) It sounds counter-intuitive to call the IDP directly on a case by case? I think i understood something wrong here...

**Comment by hems** [comment]
> that is more like the intended behavior! 🎉

Is there any documentation / example on how to implement the "expected behaviour" ?

I understand this is a fairly common use of authentication ( to have other APIs dealing with the token ) but i didn't find anything related to that on the documentation.

Being more specific: If sending the `access_token` as `Bearer` is the intended behaviour is there documentation somewhere explaining how to verify the `access_token` let's say on an express ( or any other node.js application ) endpoint?

**Comment by hems** [comment]
What do you mean by "encrypted by default" but "there is no JWT signing by default" @balazsorban44 ?

From my understanding when we say "encrypted" it means it was "signed" by a private key so i don't really understand what you mean by "it's encrypted by default but no JWT signing by default"?

> As an FYI, the JWT creation has been reworked in #3039 and all JWTs are encrypted (JWE) by default in `next-auth@4.0.0-beta.5` and upwards, and there is no JWT signing by default either.

**Comment by hems** [comment]
After some reading and extra considerations i came [to this implementation described here](https://github.com/nextauthjs/next-auth/discussions/5603#discussioncomment-4186868)

Please let me know your thoughts @micheljung / @balazsorban44 !

thanks a lot for sharing your thoughts / work on the library.

**Comment by CharlesHolbrow** [comment]
> I got it working by passing the `access_token` via callbacks to `session` as documented and sending it via `Authorization: Bearer $ACCESS_TOKEN` header to my API calls which will then call the IDP for introspection. As for me, this can be closed.

@micheljung Any chance you could help me understand this? 

If I understand correctly, when the user logs in to your app with a Provider (such as GitHub, Google, etc) they receive an access token FROM that provider. Does this happen in the Browser or the server? 

Then somehow, you set a cookie on the client. How is this accomplished?

Many, many thanks if you can help me 🙏🙏🙏
