### ISSUE TITLE
"authorization.params.scope" not respected for GitHub provider

### ISSUE THREAD

**Issue by kettanaito** [nextauthjs/next-auth#3153]
### Description 🐜

When using the `GitHubProvider` the custom `authorization.params.scope` value is not respected.

### Is this a bug in your own project?

No

### How to reproduce ☕️

1. Configure Next Auth to use `GitHubProvider`:

```js
// pages/api/auth/[...nextauth].ts
import NextAuth from 'next-auth'
import GitHubProvider from 'next-auth/providers/github'

export default NextAuth({
  secret: process.env.SESSION_ENCRYPTION_SECRET,
  providers: [
    GitHubProvider({
      clientId: process.env.GITHUB_APP_CLIENT_ID,
      clientSecret: process.env.GITHUB_APP_CLIENT_SECRET,
      authorization: {
        params: {
          // I wish to request additional permission scopes.
          scope: 'repo read:user user:email',
        },
      },
    }),
  ],
})
```

2. Navigate to [Sign in GitHub route](http://localhost:3000/api/auth/signin/github).
3. Authorize your application in GitHub.
4. Perform the following request in your application:
```js
fetch('https://api.github.com/graphql', {
  method: 'POST',
  headers: {
    Authorization: `Bearer ${YOUR_AUTH_TOKEN}`,
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({
    query: `
      query {
        repository(owner: "prettier", name: "prettier") {
          # Requesting "url" requires "public_repo" scope.
          fundingLinks { url }
        }
    `
  })
})
```

The request will fail, producing the following error:

```sh
Your token has not been granted the required scopes to execute this query. The 'url' field requires one of the following scopes: ['public_repo'], but your token has only been granted the: ['read:user', 'user:email'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
Your token has not been granted the required scopes to execute this query. The 'platform' field requires one of the following scopes: ['public_repo'], but your token has only been granted the: ['read:user', 'user:email'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
```

I can also confirm that the custom `authorization.params.scope` value is ignored when setting `debug: true` on my `NextAuth` options:

```sh
[next-auth][debug][OAUTH_CALLBACK_PROTECTION] {
  state: 'REDACTED',
  csrfToken: 'REDACTED'
}
[next-auth][debug][GET_AUTHORIZATION_URL] {
  url: 'https://github.com/login/oauth/authorize?scope=read%3Auser%20user%3Aemail&client_id=REDACTED&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fauth%2Fcallback%2Fgithub&state=REDACTED'
}
```
> Note the `scope=read%3Auser%20user%3Aemail` query parameter, it misses the "repo" scope I set.

### Environment 🖥

  System:
    OS: macOS 12.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 437.79 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 95.1.31.88
    Chrome: 95.0.4638.69
    Safari: 15.1
  npmPackages:
    next: 11.1.2 => 11.1.2 
    next-auth: 4.0.0-beta.2 => 4.0.0-beta.2 
    react: 17.0.2 => 17.0.2 

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by kettanaito** [comment]
The documentation is also misleading about the custom `scope` option. [Here](https://next-auth.js.org/configuration/options) it lists it as a root option, while [in this reply](https://github.com/nextauthjs/next-auth/issues/2938#issuecomment-941967781) it's mentioned as `authorization.params.scope`. I'm willing to update the docs if you find this an issue.

**Comment by balazsorban44** [comment]
Thanks, could you try to upgrade to `beta.6` see if that helps?

This was probably a hug that was fixed in beta.3

https://github.com/nextauthjs/next-auth/pull/2842 


Also, coincidentally I started going through the OAuth docs to make sure it's up to date https://github.com/nextauthjs/docs/pull/107

Feel free to comment on that PR if I forgot anything 🙏

**Comment by kettanaito** [comment]
@balazsorban44, thank you, updating to `beta.6` helped. Looking forward to having that pull request merged. Keep up the great work!

**Comment by emolr** [comment]
@kettanaito how did you manage to fix this, did you change anything from your example code other than updating to `beta.6`? 

I'm facing the same issue, and with copying your code and updating to `beta.7` this is the result from `debug` set to true:

```
[next-auth][debug][OAUTH_CALLBACK_PROTECTION] {
  state: 'REDACTED',
  csrfToken: 'REDACTED'
}
[next-auth][debug][GET_AUTHORIZATION_URL] {
  url: 'https://github.com/login/oauth/authorize?scope=read%3Auser%20user%3Aemail&client_id=REDACTED&response_type=code&redirect_uri=REDACTED&state=REDACTED'
