### ISSUE TITLE
How to access query parameters on callback

### ISSUE THREAD

**Issue by ccannell** [nextauthjs/next-auth#3155]
### Question 💬

I'm using Intuit as an Identity provider as well as a service to get data from. Users can have multiple "Companies" under the same set of credentials. When intuit hits the callback after the user signs in it passes a query parameter, along with code and state query parameters, with the company the user selected to provide access to.

Is there a way with NextAuth to get access to this query parameter?

### How to reproduce ☕️

See question

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
without knowing much what you want to do with it, would that help?

```js
export default async function auth(req, res) {
  // Based on https://next-auth.js.org/getting-started/rest-api#getpost-apiauthcallbackprovider
  const param = req.query.nextauth.includes("callback") && req.query.yourParam
  return NextAuth(req, res, {
    // rest of your config
  })
}
```
