### ISSUE TITLE
Deauthorization / revoking tokens and removing users

### ISSUE THREAD

**Issue by jonmol** [nextauthjs/next-auth#3159]
### Question 💬

Hi,

Many OAuth providers requires that you have a call back for revoking access, if the user revokes access to your site in the source site. For instance Zoom does so (https://marketplace.zoom.us/docs/guides/auth/deauthorization), and I've failed to find any documentation about that in NextAuth.

Is it there somewhere or is that something which have to be added for the providers requiring it?

### How to reproduce ☕️

Doesn't really apply

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
There is no built-in support for that at the moment. Maybe in the future. You will have to invoke the correct endpoints for your Provider.

**Comment by EarthlingDavey** [comment]
@jonmol Hi I've had to implement something for this recently. I don't expect to get high volume so I added something like this towards the end of my [...nextauth].js file.

```
const providerIds = providers?.map((p) => p?.id) || [];

const [_, action, providerId] =
  req.url.match(
    `^\/api\/auth\/(deauthorize|delete)\/(${providerIds.join('|')})$`
  ) || [];

if (action) {
  console.log({ body: req.body, action, providerId });
  const emailText `New ${action} request form ${providerId}: \n ${req.body}`;
  // Send your email for manual action or automate whatever here. 
  // You need to add code.
  return res.json({ status: 'OK', action, providerId });
}

NextAuth(req, res, options);
```

**Comment by zevsdflkjiuxcvb** [comment]
My idea is, save list `iat` in jwt to table (redis :? ) then every time call `session` Api we will check iat in list :\ if not, logout :D
