### ISSUE TITLE
Missing Azure AD doc

### ISSUE THREAD

**Issue by kuhlaid** [nextauthjs/next-auth#3162]
### Question 💬

Should there be a document for `www/docs/providers/azure-ad.md` as found on https://next-auth.js.org/providers/azure-ad?

### How to reproduce ☕️

Expecting to find Azure AD doc (not B2C) under https://github.com/nextauthjs/next-auth/tree/main/www/docs/providers

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/docs/blob/main/docs/providers/azure-ad.md
