### ISSUE TITLE
Unnecessary import of `nodemailer` for Email Provider

### ISSUE THREAD

**Issue by anguskeatinge** [nextauthjs/next-auth#3167]
### Description 🐜

error - Error: Cannot find module 'nodemailer'

I have a custom sign in page and a custom sendVerificationRequest so nodemailer is a superfluous dependency.

### Is this a bug in your own project?

No

### How to reproduce ☕️

Don't install peer dependency nodemailer when using email provider.

### Environment 🖥

Not necessary

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by anguskeatinge** [comment]
Here is what I was thinking:
https://github.com/nextauthjs/next-auth/pull/3168

**Comment by iaincollins** [comment]
I think @balazsorban44 had some good ideas about this and is either already doing this in v4 or is planned for the future.
