### ISSUE TITLE
Is the documentation for Theme wrong? (How to set theme.brandColor and theme.logo?)

### ISSUE THREAD

**Issue by wanglophile** [nextauthjs/next-auth#3174]
### Question 💬

The [theme documentation](https://next-auth.js.org/configuration/options#theme) says that `theme` accepts an object. E.g.
```
// [...nextauth].js
const settings = {
  theme: {
    colorScheme: "auto", // "auto" | "dark" | "light"
    brandColor: "", // Hex color code
    logo: "" // Absolute URL to image
  }
}
```

However, this code doesn't work and produces an error in the styling: `<body class="__next-auth-theme-[object Object]">`

When I dig into [the Next-Auth code](https://github.com/nextauthjs/next-auth/blob/main/types/index.d.ts), the TypeScript indicates that `theme` should actually be a string value only:
```
// node_modules/next-auth/index.d.ts
// ln 173 - 183
  /**
   * Changes the theme of pages.
   * Set to `"light"` if you want to force pages to always be light.
   * Set to `"dark"` if you want to force pages to always be dark.
   * Set to `"auto"`, (or leave this option out)if you want the pages to follow the preferred system theme.
   * * **Default value**: `"auto"`
   * * **Required**: *No*
   *
   * [Documentation](https://next-auth.js.org/configuration/options#theme) | [Pages documentation]("https://next-auth.js.org/configuration/pages")
   */
  theme?: Theme

// ln 218 - 224
/**
 * Change the theme of the built-in pages.
 *
 * [Documentation](https://next-auth.js.org/configuration/options#theme) |
 * [Pages](https://next-auth.js.org/configuration/pages)
 */
export type Theme = "auto" | "dark" | "light"
```

So the following code does work in setting the `colorScheme` only:

```
// [...nextauth].js
const settings = {
  theme: "dark", // "auto" | "dark" | "light"
}
```

But how can I set the `brandColor` and `logo` then?

### How to reproduce ☕️

Doesn't work:
```
// [...nextauth].js
const settings = {
  theme: {
    colorScheme: "dark", // "auto" | "dark" | "light"
    brandColor: "", // Hex color code
    logo: "" // Absolute URL to image
  }
}
```

Works:
```
// [...nextauth].js
const settings = {
  theme: "dark", // "auto" | "dark" | "light"
}
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by wanglophile** [comment]
Ah, I realize that I am looking at the v4 documentation and I'm on v3.29!

**Comment by leon-do** [comment]
I'm on v4.19.2 and having the same problem. Is this feature still available?

**Comment by jahabeebs** [comment]
> I'm on v4.19.2 and having the same problem. Is this feature still available?

It appears there's an open PR to fix this https://github.com/nextauthjs/next-auth/pull/6884
