### ISSUE TITLE
Github + Prisma adapter doesn't store refresh token

### ISSUE THREAD

**Issue by AashJ** [nextauthjs/next-auth#3209]
### Description 🐜

When using the GitHubProvider + PrismaAdapter, my account table doesn't have the user's refresh token + expiration information

```
export default NextAuth({
    // Configure one or more authentication providers
    adapter: PrismaAdapter(prisma),
    providers: [
        GitHubProvider({
            clientId: process.env.GITHUB_ID,
            clientSecret: process.env.GITHUB_SECRET,
            authorization: {
                params: {
                    scope: 'read:user user:email repo',
                },
            },
        }),
    ],
```

A row in the account table looks something like (with information redacted):

```
{
  id: '------------------------------',
  userId: '-----------------------------',
  type: 'oauth',
  provider: 'github',
  providerAccountId: '-------------------',
  refresh_token: null,
  access_token: '------------------------------',
  expires_at: null,
  token_type: 'bearer',
  scope: 'read:user,repo,user:email',
  id_token: null,
  session_state: null,
  oauth_token_secret: null,
  oauth_token: null
}
```

The refresh token is null preventing me from doing a refresh token rotation.

### Is this a bug in your own project?

No

### How to reproduce ☕️

```
export default NextAuth({
    // Configure one or more authentication providers
    adapter: PrismaAdapter(prisma),
    providers: [
        GitHubProvider({
            clientId: process.env.GITHUB_ID,
            clientSecret: process.env.GITHUB_SECRET,
            authorization: {
                params: {
                    scope: 'read:user user:email repo',
                },
            },
        }),
    ],
```

### Environment 🖥

  System:
    OS: macOS 11.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 21.29 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 2021.10.11.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 95.0.4638.69
    Safari: 14.0.2
  npmPackages:
    next: 12.02 => 12.0.2 
    next-auth: ^4.0.0-beta.6 => 4.0.0-beta.6 
    react: ^17.0.2 => 17.0.2 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Please file it in the correct repo. See the issue templates for more info.
