### ISSUE TITLE
Unexpected default export of anonymous function  

### ISSUE THREAD

**Issue by rzeynalli** [nextauthjs/next-auth#3212]
### Question 💬

When I'm trying to build my next.js app, I'm getting this es-lint warning from compiler. How to fix this? without disable any rule.

Thanks :)

### How to reproduce ☕️

```
export default (req,res) => NextAuth(req, res, options);
```

Compiler warning: 
```
./pages/api/auth/[...nextauth].js
75:1  Warning: Unexpected default export of anonymous function  import/no-anonymous-default-export
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
```js
export default NextAuth(options)
```

https://next-auth.js.org/configuration/initialization
