### ISSUE TITLE
beta 7 introduces credentials only bug

### ISSUE THREAD

**Issue by davecarlson** [nextauthjs/next-auth#3216]
### Description 🐜

If you only have a Credentials provider, you now are unable to get a CSRF token:
```
[next-auth][error][CALLBACK_CREDENTIALS_JWT_ERROR] 
https://next-auth.js.org/errors#callback_credentials_jwt_error Signin in with credentials only supported if JWT strategy is enabled UnsupportedStrategy [UnsupportedStrategyError]: Signin in with credentials only supported if JWT strategy is enabled
```

I've left a comment on the offending code change: 
https://github.com/nextauthjs/next-auth/commit/76bf524e8ec144162bcd0474adba250028f9c4db#r60378488

My config:

```


  providers: [
    Credentials({
      async authorize(credentials, req) {
         // my logic here   
      }
    }),
  ],
  session: {
    strategy: 'jwt'
  },
```

### Is this a bug in your own project?

No

### How to reproduce ☕️

create a new project with the above config, then attempt to get a CSRFToken

### Screenshots / Logs 📽

[next-auth][error][CALLBACK_CREDENTIALS_JWT_ERROR] 
https://next-auth.js.org/errors#callback_credentials_jwt_error Signin in with credentials only supported if JWT strategy is enabled UnsupportedStrategy [UnsupportedStrategyError]: Signin in with credentials only supported if JWT strategy is enabled
    at assertConfig (/node_modules/next-auth/core/lib/assert.js:45:14)
    at NextAuthHandler (/node_modules/next-auth/core/index.js:34:52)
    at NextAuthNextHandler (/node_modules/next-auth/next/index.js:16:51)
    at /node_modules/next-auth/next/index.js:52:38
    at Object.apiResolver (/node_modules/next/dist/server/api-utils.js:102:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DevServer.handleApiRequest (/node_modules/next/dist/server/next-server.js:1014:9)
    at async Object.fn (/node_modules/next/dist/server/next-server.js:901:37)
    at async Router.execute (/node_modules/next/dist/server/router.js:210:32) {
  code: 'CALLBACK_CREDENTIALS_JWT_ERROR'
}

### Environment 🖥

 System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 121.84 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.3 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Brave Browser: 95.1.31.91
    Safari: 15.1
  npmPackages:
    next: ^12.0.3 => 12.0.3 
    next-auth: ^4.0.0-beta.7 => 4.0.0-beta.7 
    react: ^17.0.2 => 17.0.2 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by davecarlson** [comment]
I've also confirmed downgrading to beta6 fixes the issue.

**Comment by balazsorban44** [comment]
oh yes, that was probably supposed to be a `&&`... 😅😬

**Comment by balazsorban44** [comment]
Merged now, if there is a big interest, I'll do a new `beta` release, otherwise here is an experimental one from the PR:

`next-auth@0.0.0-pr.3217.87a21677`

**Comment by phibersoft** [comment]
I'm getting this error too.

I tested in current last version (beta.7),
beta.6,
beta.5,
beta.4 too.

NextAuth options same as the first comment. In localhost its working perfectly but when i deploy to vercel, its this giving error.

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth/issues/3216#issuecomment-970730828

**Comment by Pruxis** [comment]
@balazsorban44 I must've looked over this issue, thanks for pointing this out ;)
Tested with next-auth@0.0.0-pr.3217.87a21677 and can confirm that it's working as expected!

**Comment by JameelKhan9** [comment]
thanks for that experimental release @balazsorban44. Can also confirm this fixes the credentials provider I have had issues with on beta 7.

Would really appreciate a new beta release, but can manage with the experimental release for now.

**Comment by balazsorban44** [comment]
new (stable) v4 release coming this week!

**Comment by davecarlson** [comment]
Maybe an RC first to be on safe side ? People hold off migrating u til the
see stable then pile in. RC for 7 days, if no major issues it it becomes
stable

**Comment by balazsorban44** [comment]
We have had 26 `next` releases, and 7 `beta` releases... We won't get more stable than that :smile:. I'll monitor in the coming days and try to be ready to fix bugs if there will be any.

**Comment by robrechtme** [comment]
I'm still seeing the issue with `4.0.1` 😕 

```tsx
export default NextAuth({
  secret: process.env.NEXTAUTH_SECRET,
  providers: [
    CredentialsProvider<Credentials>({
        ....
    }),
  ],
});
```
<details>
  <summary>Error message</summary>
  
```
[next-auth][warn][NO_SECRET] 
https://next-auth.js.org/warnings#no_secret
ERROR TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (node_modules/node-fetch/lib/index.js:1305:9)
    at node_modules/node-fetch/lib/index.js:1410:19
    at new Promise (<anonymous>)
    at Function.fetch [as default] (node_modules/node-fetch/lib/index.js:1407:9)
    at fetchWithAgent (node_modules/next/dist/server/node-polyfill-fetch.js:38:39)
    at apiFetch (webpack-internal:///./src/lib/apiFetch.ts:18:26)
    at Module.fetchProfile (webpack-internal:///./src/lib/messagingApi.ts:16:67)
    at Object.authorize (webpack-internal:///./src/pages/api/auth/[...nextauth].ts:42:71)
    at Object.callback (node_modules/next-auth/core/routes/callback.js:353:29)
    at NextAuthHandler (node_modules/next-auth/core/index.js:227:41)
```
</details>
