### ISSUE TITLE
Documentation | Session strategy option

### ISSUE THREAD

**Issue by callumok2004** [nextauthjs/next-auth#3224]
### Description 🐜

Either the documentation, or the types are invalid, when trying to specify `strategy` it says `'strategy' does not exist in type 'Partial<SessionOptions>'`

It says it does not exist here
![image](https://user-images.githubusercontent.com/35779365/142277935-ba36eeef-bee9-4b7f-8342-35729443bf72.png)

But the docs say otherwise
![image](https://user-images.githubusercontent.com/35779365/142278020-c27b8adb-56a4-4eed-a7ec-f26de331988a.png)

### Is this a bug in your own project?

Yes

### How to reproduce ☕️
Update to `next-auth4.0.0-beta.7`
Specify the `strategy` option in session options, typescript will give an error. 

### Environment 🖥

Windows 11 removes WMIC, therefore I cannot provide the output of the command.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Interesting... The code looks good: https://github.com/nextauthjs/next-auth/blob/64b2a2c43bef38f71d73095eec7fd65413f4f2e3/src/core/types.ts#L426-L442

**Comment by callumok2004** [comment]
> Interesting... The code looks good:
> 
> https://github.com/nextauthjs/next-auth/blob/64b2a2c43bef38f71d73095eec7fd65413f4f2e3/src/core/types.ts#L426-L442
> 
> Also looks good locally to me:
> 
> ![image](https://user-images.githubusercontent.com/18369201/142288305-c4b86139-d474-42a8-996c-5c416a85af16.png)
> 
> Please provide a reproduction and I can reopen.

Here is a reproduction:
https://github.com/callumok2004/nextjs-reproduction/

**Comment by balazsorban44** [comment]
You have the wrong version installed: https://github.com/callumok2004/nextjs-reproduction/blob/9ab6641ee9659ca1680c066560c429a2ee7e58ff/yarn.lock#L2105-L2107

**Comment by callumok2004** [comment]
> You have the wrong version installed: https://github.com/callumok2004/nextjs-reproduction/blob/9ab6641ee9659ca1680c066560c429a2ee7e58ff/yarn.lock#L2105-L2107

Whoops, never pushed the new yarn.lock, one sec. Manually committed these files due to having some stuff I didn't want on the public repo, check again!

**Comment by balazsorban44** [comment]
No error in your reproduction either:

![image](https://user-images.githubusercontent.com/18369201/142290604-66710eef-5c2a-4bc1-bfcc-c10ce0803617.png)

**Comment by balazsorban44** [comment]
Try restarting VSCode or `Ctrl+Shift+P` and  `TypeScript: Restart TS Server`

**Comment by callumok2004** [comment]
> Try restarting VSCode or `Ctrl+Shift+P` and `TypeScript: Restart TS Server`

I've tried both of these, and it still persists. I'll try restarting my entire computer later before I head to bed.

**Comment by balazsorban44** [comment]
Do that. See line 435 in https://unpkg.com/browse/next-auth@4.0.0-beta.7/core/types.d.ts as well. That is what's published to npm, so the problem is local.
