### ISSUE TITLE
Azure AD Provider - Let the developer set the scopes (optionally)

### ISSUE THREAD

**Issue by jacomo291093** [nextauthjs/next-auth#3233]
### Description 📓

I'm using next auth integrated with MS Graph. I needed the Token to use the graph for User.ReadBasic.All. I had to alter the azure-ad.js file and add the scope manually for this to work. It'd' be nice if the provider gave the option. It's a very simple fix.

### How to reproduce ☕️
scope: "User.Read User.ReadBasic.All'
.

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
https://next-auth.js.org/configuration/providers/oauth#authorization-option
