### ISSUE TITLE
Outdated Documentation (https://next-auth.js.org)

### ISSUE THREAD

**Issue by dankmemetics** [nextauthjs/next-auth#3239]
### Description 🐜

Hello, I've noticed that the documentation on [next-auth.js.org](https://next-auth.js.org) is completely out of date.

I was not able to finish the second step at: https://next-auth.js.org/getting-started/example#add-api-route

I was not able to complete the getting started tutorial and was stuck at `_app.js`. Furthermore, the root problem is most likely because all of the type interfaces have all completely changed.

### Is this a bug in your own project?

No

### How to reproduce ☕️

In the example, you can access providers with:

```typescript
import NextAuth from "next-auth"
import GithubProvider from "next-auth/providers/github"

export default NextAuth({
  // Configure one or more authentication providers
  providers: [
    GithubProvider({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET,
    }),
    // ...add more providers here
  ],
})
```

However, in order for me to successfully compile I needed to use:

```typescript
import NextAuth from "next-auth"
import Providers from "next-auth/providers"

export default NextAuth({
  providers: [
    Providers.GitHub({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET,
    }),
  ],
})
```

Second, I wasn't even able to get `_app.js` to compile properly. I would be thrown errors when attempting to compile:

```typescript
// pages/_app.js
import { SessionProvider } from "next-auth/react"

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}) {
  return (
    <SessionProvider session={session}>
      <Component {...pageProps} />
    </SessionProvider>
  )
}
```

Furthermore, attempting to compile `_app.js` trying this snippet. Would still not work.

```typescript
// pages/_app.js
import { SessionProvider } from "next-auth/client"

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}) {
  return (
    <SessionProvider session={session}>
      <Component {...pageProps} />
    </SessionProvider>
  )
}
```

Explicitly referring to `SessionProvider` a type and not an actual `FC` or `Component`. Would be greatly appreciated if this issue was solved.

Thanks.

### Environment 🖥

```bash
  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 1.40 GB / 15.55 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 96.0.4664.45
    Firefox: 94.0.1
  npmPackages:
    next: ^12.0.4 => 12.0.4 
    next-auth: ^3.29.0 => 3.29.0 
    react: ^17.0.2 => 17.0.2 
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Have a look at the top of the page, there is a banner explaining your situation. :slightly_smiling_face:

**Comment by dankmemetics** [comment]
LOL, no wonder why. Thanks my bad.

@balazsorban44, could you make that banner a little bigger? Would be useful for people like me. Thanks!

**Comment by balazsorban44** [comment]
I will check! FWIW, the banner will be gone in less than 2 weeks. 😊
