### ISSUE TITLE
Database | Updated values not being applied when I sign out and back in.

### ISSUE THREAD

**Issue by callumok2004** [nextauthjs/next-auth#3242]
### Description 🐜

When I sign in, let's say the avatar given by discord is `abcdef` then I change it, log out and back in, now the avatar given is `abcdef123`, I log the response given by the API and it shows the correct value, but the database and session does not update with the new values. This is the same for username, banner etc.

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

https://github.com/callumok2004/nextjs-reproduction/blob/main/src/pages/api/auth/%5B...nextauth%5D.ts

### Screenshots / Logs 📽

![image](https://user-images.githubusercontent.com/35779365/142725501-8b981fb5-4d32-4d88-a746-3334ca84ce84.png)

### Environment 🖥

N/A, Windows 11 removes WMIC which the below command depends on.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
we don't update the user on signing in the second time currently. there are plans to provide an easier way to update the user in the future.
