### ISSUE TITLE
When using google OAuth and new scope is added, user re-signed in with new scope, but Account entity does not get updated automatically

### ISSUE THREAD

**Issue by yuklai** [nextauthjs/next-auth#3250]
### Description 🐜

Not sure if I should expect this would work but I guess I did.

I have two scopes in Google OAuth that user didn't select by default. When user reauthorized with the new scope selected, I expected the Account entity to get updated automatically with the new access/refresh tokens, but it doesn't seem like it does. 

Has anyone seen this before?

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

I don't have an easy to copy snippet I can provide offhand.

### Environment 🖥

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
    Memory: 127.34 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.6.0 - ~/.nvm/versions/node/v16.6.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.9 - ~/node_modules/.bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Firefox: 38.0.1
    Safari: 14.1.2
  npmPackages:
    next: ^11.1.2 => 11.1.2 
    next-auth: ^3.27.0 => 3.29.0 
    react: 17.0.2 => 17.0.2 

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
We don't update the Account in the database right now, you have to do that yourself. token rotation is planned though, at a later point. we could make sure everything else is updated in Account as well.
