### ISSUE TITLE
'checks.state argument is missing' error when click back button after authentication with keycloak

### ISSUE THREAD

**Issue by jalbissimo** [nextauthjs/next-auth#3251]
### Description 🐜

Hello there! 

I`m having an issue with next-auth. After  successfully sign in into the application using the keycloack provider, clicking the back button in the browser window leads to  : 
```sh
error: {
    message: 'checks.state argument is missing',
    stack: 'TypeError: checks.state argument is missing\n' +...//stack trace
     name: 'TypeError'
  },
  providerId: 'sso_provider_1',
  message: 'checks.state argument is missing'
}
```

My configuration for the keycloack provider looks something like this 
```js
export default NextAuth({
  providers: [
    KeycloakProvider({
      id: 'sso_provider_1',
      clientId: process.env.AP_CLIENT_ID,
      clientSecret: process.env.AP_CLIENT_SECRET,
      issuer: process.env.AP_BASE_URL
    })
  ],
  secret: process.env.SECRET,
  debug: true
}); 
```

Is there anything else I should configure in order to make my application work with the keycloack provider or it is just a bug ?

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

Clicking back button after sign in with Keycloack will display this page and the error mentioned above.
![image](https://user-images.githubusercontent.com/37750567/142824926-49f5d486-eec0-4aca-95d4-abf7f9e3bcee.png)

### Environment 🖥

next.js

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by mpetricek** [comment]
I'm getting same error with Google provider and version `4.0.0-beta.7`. With `beta.6` it's working fine (appart from other issues of that version).

**Comment by balazsorban44** [comment]
I believe we don't currently handle login cancelation https://github.com/nextauthjs/next-auth/pull/1820

**Comment by ckruppe** [comment]
We are haveing the same issue with Azure AD B2C. Its an showstopper for us because the customer insists that it should work the same as if you login in office or other microsoft apps. Is anyone working on this?

**Comment by mpetricek** [comment]
@ckruppe  For me it helped to add `checks: console.log() `to the provider. Not sure if it would work for you of course.

Example:
```
GoogleProvider({
      clientId: ...,
      clientSecret: ...,
      authorizationUrl: ...,
      checks: console.log(), // <-- THIS LINE
    }),
```

**Comment by carlreid** [comment]
> We are haveing the same issue with Azure AD B2C. Its an showstopper for us because the customer insists that it should work the same as if you login in office or other microsoft apps. Is anyone working on this?

@ckruppe Did you find any work around for now with Azure AD? We've just got hit by this.

**Comment by NuroDev** [comment]
Currently experimenting setting up a system using a custom subdomain (`app.example.com`) & ran into this same issue.
Unsure if it will fix / help others but I got mine working by adding `checks: "both"` to my provider options.

Example:
```typescript
DiscordProvider({
      checks: "both",
      clientId: "...",
      clientSecret: "...",
}),
```

**Comment by Atali-Albarozzo** [comment]
Did anyone solve this? I am experiencing the same issue.

**Comment by kfcaio** [comment]
> Currently experimenting setting up a system using a custom subdomain (`app.example.com`) & ran into this same issue. Unsure if it will fix / help others but I got mine working by adding `checks: "both"` to my provider options.
> 
> Example:
> 
> ```ts
> DiscordProvider({
>       checks: "both",
>       clientId: "...",
>       clientSecret: "...",
> }),
> ```

It worked, but also redirects to localhost:3000 instead of my custom domain

**Comment by Anishjangra2** [comment]
> > Currently experimenting setting up a system using a custom subdomain (`app.example.com`) & ran into this same issue. Unsure if it will fix / help others but I got mine working by adding `checks: "both"` to my provider options.
> > Example:
> > ```ts
> > DiscordProvider({
> >       checks: "both",
> >       clientId: "...",
> >       clientSecret: "...",
> > }),
> > ```
> 
> It works, but also redirects to localhost:3000 instead of my custom domain

is there any workaround to redirect to custom domain instead ???

**Comment by kfcaio** [comment]
> > > Currently experimenting setting up a system using a custom subdomain (`app.example.com`) & ran into this same issue. Unsure if it will fix / help others but I got mine working by adding `checks: "both"` to my provider options.
> > > Example:
> > > ```ts
> > > DiscordProvider({
> > >       checks: "both",
> > >       clientId: "...",
> > >       clientSecret: "...",
> > > }),
> > > ```
> > 
> > 
> > It works, but also redirects to localhost:3000 instead of my custom domain
> 
> is there any workaround to redirect to custom domain instead ???

What if you set `NEXTAUTH_URL` in the `.env` file? It worked for me

**Comment by Anishjangra2** [comment]
i tried that but is still getting the same error can you pls show me how you did it.

> > > > Currently experimenting setting up a system using a custom subdomain (`app.example.com`) & ran into this same issue. Unsure if it will fix / help others but I got mine working by adding `checks: "both"` to my provider options.
> > > > Example:
> > > > ```ts
> > > > DiscordProvider({
> > > >       checks: "both",
> > > >       clientId: "...",
> > > >       clientSecret: "...",
> > > > }),
> > > > ```
> > > 
> > > 
> > > It works, but also redirects to localhost:3000 instead of my custom domain
> > 
> > 
> > is there any workaround to redirect to custom domain instead ???
> 
> What if you set `NEXTAUTH_URL` in the `.env` file? It worked for me

**Comment by modecry** [comment]
"KeycloakProvider" has error -  argument "boths" is missing
any updates  for this?

**Comment by AnmolSaini16** [comment]
> "KeycloakProvider" has error - type "boths" is missing any updates for this?

Kindly look into this

**Comment by LeptoFlare** [comment]
I believe I have found the *actual* fix, with a lot of doubts.

First of all, it seems like this is a bit of a "very common edge case" bug. For me, it only occurs when using the `signIn("discord")` function on any route that is not the `api/auth/signin` route.

Additionally, people have been reporting that adding `checks: console.log()` or `checks: "both"` to their provider fixed it for them, however, that probably isn't the intended behavior.

For one, `console.log()` returns `undefined` so `checks: undefined` would literally be the same as not passing the parameter at all.
Second, `"both"` isn't even an *option* on latest version of next-auth. So why do these fixes work? As I don't doubt they do.

![image](https://user-images.githubusercontent.com/47790183/184503950-e1d4b8ab-2b3a-4558-9e8a-69555f385c0a.png)

So my current "fix" is to **add a `checks: ["pkce", "state"]` field to my `DiscordProvider`**.

I'm also not sure if my fix is actually the expected and intended behavior, or whether it just somehow bypasses the bug in a peculiar way, the same way that `checks: console.log()` does.

I'd also like to know if that fix works for other people, or if it's just me!

> If you want to know more about the exact error I had, see this unanswered discussion I made 😂 https://github.com/nextauthjs/next-auth/discussions/5140

**Comment by AnmolSaini16** [comment]
Any solution to this bug?

**Comment by AnmolSaini16** [comment]
`checks: 'none'`
This is working for me.

**Comment by Oooooiii** [comment]
In this case 'none` is the only option to make it works. If we do 'state' or 'pkce' or array of ['state', 'pkce'] it does not working. But if we use default of NextAuth.js sign-in page it consist of ['state', pkce']. 
I'm have concern of security issue with 'none'? 
FYI: I have stuck with this about 2 days now and it works just now with 'none'.

**Comment by ianstump** [comment]
checking here if someone has found another solution that is not setting `state` to `none`, since that is not secure.

**Comment by RayBans2111** [comment]
I'm also looking for a solution this issue. I'm currently using netlify and originally thought this was an issue with the jwt option, but I keep coming back to this checks option for providers. 

Would someone explain what the checks option does? I wasn't able to find this option in the documentation, so i'm a little stuck as to what it entails.

**Comment by lassegit** [comment]
I am running:

```
    "@next-auth/prisma-adapter": "^1.0.5",
    "@next/font": "13.1.1",
    "@prisma/client": "4.8.0",
    "next": "13.1.0",
    "next-auth": "4.18.7",
```

And I get the following error in production (can't reproduce locally) and only with GoogleProvider (checked all .env and they are fine):

```
{
  [next-auth][error][OAUTH_CALLBACK_ERROR]
  https://next-auth.js.org/errors#oauth_callback_error checks.state argument is missing {
    error: TypeError: checks.state argument is missing
        at Client.callback (/opt/render/project/src/node_modules/openid-client/lib/client.js:387:13)
        at oAuthCallback (/opt/render/project/src/node_modules/next-auth/core/lib/oauth/callback.js:127:29)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async Object.callback (/opt/render/project/src/node_modules/next-auth/core/routes/callback.js:52:11)
        at async AuthHandler (/opt/render/project/src/node_modules/next-auth/core/index.js:201:28)
        at async NextAuthHandler (/opt/render/project/src/node_modules/next-auth/next/index.js:23:19)
        at async /opt/render/project/src/node_modules/next-auth/next/index.js:59:32
        at async Object.apiResolver (/opt/render/project/src/node_modules/next/dist/server/api-utils/node.js:363:9)
        at async NextNodeServer.runApi (/opt/render/project/src/node_modules/next/dist/server/next-server.js:487:9)
        at async Object.fn (/opt/render/project/src/node_modules/next/dist/server/next-server.js:749:37)
        at async Router.execute (/opt/render/project/src/node_modules/next/dist/server/router.js:253:36)
        at async NextNodeServer.run (/opt/render/project/src/node_modules/next/dist/server/base-server.js:384:29)
        at async NextNodeServer.handleRequest (/opt/render/project/src/node_modules/next/dist/server/base-server.js:322:20) {
      name: 'OAuthCallbackError',
      code: undefined
    },
    providerId: 'google',
    message: 'checks.state argument is missing'
  }
```

I am unsure what exactly `checks` does? Has the following types (`checks?: ChecksType | ChecksType[];` and `declare type ChecksType = "pkce" | "state" | "none" | "nonce";`).

Any solution?

**Comment by lassegit** [comment]
@RayBans2111 Have you been able to solve this?

**Comment by RayBans2111** [comment]
> @RayBans2111 Have you been able to solve this?

I did! There were a couple of things I needed to check. Make sure that your JWT private key doesn't have any odd characters or mistypings. This error popped up for me when my JWT private key was wrong. 

This error would also appear for me if you are not providing the NEXTAUTH_URL variable in your env files. I troubleshooted this by taking a look at the redirectURLs I was getting, and I was getting a bad url, which somehow resulted in this error. 

I did not have to provide "checks" in my next-auth setup at all. Fixing the above would fix the checks error.

**Comment by lassegit** [comment]
@RayBans2111 Thanks. Those are all as they should be, just checked. The default config seems to be `checks: [ 'pkce', 'state' ],`. Perhaps only setting either might work.

Not sure what to do.

**Comment by lassegit** [comment]
It is properly [this](https://github.com/nextauthjs/next-auth/blob/6c45abf38356d685a3a027d32e604b637209df16/packages/core/src/lib/oauth/authorization-url.ts#L62) URL param that isn't being set or something.

**Comment by lassegit** [comment]
Can with pleasure after an hour of intense testing directly on production on a [site](https://aihelperbot.com/) that is going viral report that adding `checks: ['pkce']` seems to resolve it:

```
export default NextAuth({
  adapter: PrismaAdapter(prisma),
  providers: [
    GoogleProvider({ clientId: process.env.GOOGLE_CLIENT_ID, clientSecret: process.env.GOOGLE_CLIENT_SECRET, checks: ['pkce'] }),
  ],
  session: { strategy: 'jwt' },
  jwt: { maxAge: 24 * 60 * 60 * 365 }, // 365 days
});
```

I will talk with my shrink and hope he can calm my nerves after this intense experience 😂.

**Comment by AaronMcCloskey** [comment]
> Can with pleasure after an hour of intense testing directly on production on a [site](https://aihelperbot.com/) that is going viral report that adding `checks: ['pkce']` seems to resolve it:
> 
> ```
> export default NextAuth({
>   adapter: PrismaAdapter(prisma),
>   providers: [
>     GoogleProvider({ clientId: process.env.GOOGLE_CLIENT_ID, clientSecret: process.env.GOOGLE_CLIENT_SECRET, checks: ['pkce'] }),
>   ],
>   session: { strategy: 'jwt' },
>   jwt: { maxAge: 24 * 60 * 60 * 365 }, // 365 days
> });
> ```
> 
> I will talk with my shrink and hope he can calm my nerves after this intense experience 😂.

I was getting this while running it via Cypress, Totally fine on dev and production. Unfortunately in my case, I now get a `nvalid_grant (Missing code verifier.)` when adding `checks: ['pkce']`. I don't know enough as to whether it's a good idea to use `checks: 'none'` in regards to security.

**Comment by leotuna** [comment]
Updates?

**Comment by balazsorban44** [comment]
Closing as this issue is kinda old. Let's open a new one with a fresh, minimal reproduction, if it still exists.

**Comment by leotuna** [comment]
It still exists...

**Comment by balazsorban44** [comment]
have a reproduction with `next-auth@latest`?
