### ISSUE TITLE
The "ikm" argument must be of type string or an instance of SecretKeyObject, ArrayBuffer, TypedArray, DataView, or Buffer. Received undefined

### ISSUE THREAD

**Issue by ev4ndropc** [nextauthjs/next-auth#3255]
### Question 💬

Hi, I'm getting this error and I have no idea why!
I've already searched the entire documentation for next-auth, on google and I can't find anything related to it. can you help me?

OBS: I can't post my code here because it breaks the formatting, I'll leave the file link in my repository

`https://github.com/ev4ndropc/Rocket_Controller/blob/main/src/pages/api/auth/%5B...nextauth%5D.js`

### How to reproduce ☕️

The error happens every time I try to login
![Screenshot_1](https://user-images.githubusercontent.com/34420396/142879903-d2990da9-0a9b-4509-82c7-9b4d428ff188.png)

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
I don't see a top level secret defined.

https://next-auth.js.org/getting-started/upgrade-v4#missing-secret

Also, where did you read about `expiresIn` in the jwt config? It's not something I'm familiar with.
