### ISSUE TITLE
Cannot find module 'next-auth/providers/email' or its corresponding type declarations.

### ISSUE THREAD

**Issue by jrdurant** [nextauthjs/next-auth#3257]
### Question 💬

Hopefully not silly, but I am attempting to use some providers in my typescript project. Here is my [...nextAuth].ts file, straight from the example https://next-auth.js.org/.

I am getting the error from the title TS2307: Cannot find module 'next-auth/providers/google' or its corresponding type declarations. Am I doing something wrong? 

I am using the "next-auth": "4.0.0-beta.2"

`import NextAuth from 'next-auth';
import GoogleProvider from 'next-auth/providers/google';
import EmailProvider from 'next-auth/providers/email';

export default NextAuth({
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_ID,
      clientSecret: process.env.GOOGLE_SECRET,
    }),
    // Passwordless / email sign in
    EmailProvider({
      server: process.env.MAIL_SERVER,
      from: 'NextAuth.js <no-reply@example.com>',
    }),
  ],
});
`

### How to reproduce ☕️

Follow the instructions from here: https://next-auth.js.org/, but in a typescript file instead of .js. 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by Izhaki** [comment]
I have just renamed `[...nextauth].js` > `[...nextauth].ts` with `"next-auth": "4.0.0-beta.7"` and no problems (I get different build errors with `4.0.0-beta.2`.

I have a feeling updating to `4.0.0-beta.7` will solve this issue. If not then I guess something is wrong with your build settings.
