### ISSUE TITLE
npm install next-auth@beta give runtime warning unsupported engine

### ISSUE THREAD

**Issue by kaushal9808** [nextauthjs/next-auth#3265]
### Description 🐜

Hello Team, 

when i am installing the next-auth@beta version its gives warning to me due to this i am not able to install the mongodb-adapter.

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'next-auth@4.0.0-beta.7',
npm WARN EBADENGINE   required: { node: '^12.19.0 || ^14.15.0 || ^16.13.0' },
npm WARN EBADENGINE   current: { node: 'v17.0.1', npm: '8.1.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'openid-client@5.0.2',
npm WARN EBADENGINE   required: { node: '^12.19.0 || ^14.15.0 || ^16.13.0' },
npm WARN EBADENGINE   current: { node: 'v17.0.1', npm: '8.1.0' }
npm WARN EBADENGINE }
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

npm install next-auth@beta on command its provide warning , i have mentioned above.

npm install @next-auth/mongodb-adapter@next

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: next-c@0.1.0
npm ERR! Found: next-auth@4.0.0-next.26
npm ERR! node_modules/next-auth
npm ERR!   next-auth@"^4.0.0-beta.7" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next-auth@">4 || 4.0.0-beta.1 - 4.0.0-beta.x" from @next-auth/mongodb-adapter@0.0.2-next.285
npm ERR! node_modules/@next-auth/mongodb-adapter
npm ERR!   @next-auth/mongodb-adapter@"0.0.2-next.285" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/kaushalkishore/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kaushalkishore/.npm/_logs/2021-11-23T07_09_42_634Z-debug.log

### Screenshots / Logs 📽

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'next-auth@4.0.0-beta.7',
npm WARN EBADENGINE   required: { node: '^12.19.0 || ^14.15.0 || ^16.13.0' },
npm WARN EBADENGINE   current: { node: 'v17.0.1', npm: '8.1.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'openid-client@5.0.2',
npm WARN EBADENGINE   required: { node: '^12.19.0 || ^14.15.0 || ^16.13.0' },
npm WARN EBADENGINE   current: { node: 'v17.0.1', npm: '8.1.0' }
npm WARN EBADENGINE }

added 12 packages, and audited 538 packages in 5s

93 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

### Environment 🖥

development using next framework

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
`openid-client`, one of our dependencies doesn't officially support non-LTS Node releases. That said, ignoring the engines warning will probably work.

https://github.com/panva/node-openid-client/issues/429

**Comment by panva** [comment]
`jose` has the same policy wrt. supported Node.js versions.
