### ISSUE TITLE
Logging in with mobile/desktop/other clients

### ISSUE THREAD

**Issue by leftyfl1p** [nextauthjs/next-auth#327]
**Your question**
I'm trying to figure out a safe/sane way of adding a mobile/desktop 1st party client login to my service.

**What are you trying to do**
My web service also has a mobile (primary) /desktop client that users can sign into. I'm trying to figure out how I can allow users to sign into my service on the web and have the mobile/desktop client receive the required tokens for making api calls to the backend. My first guess was to change the redirect callback to a custom URI (`myapp://`) but that doesn't seem to pass any tokens. My next guess would be to redirect to a custom api endpoint that then calls the URI with the right data but that sounds... weird and maybe not safe?

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
Interesting scenario!

Smart TV apps often have a system like this.

1. When you try to set them up, the devices call an API route to create a verification request - getting an access token / session identifier for the device that is stored internally in the app - and then display a code on screen (e.g. 6 characters) that has a short expiry time. 

2. They then ask you to sign in on a browser (can be the same device, or a different device) and enter the code.

    Note: If you want the user to sign in on the same same device, you would simply open a URL like `https://example.com/activate/123ABC` in your app (where `123ABC` is the code) which would be like opening a form with the value prefilled.

3. Then, they ask the user to sign in / sign up the browser.

    Once the user is signed in they then associate the device ID with the user ID to 'activate' the device.

    Note: In the scenario of a mobile app, you could use the URL like mypp:// just to bring the app to the foreground, it wouldn't need to pass any tokens in the URL.

Typically, after displaying the prompt telling the user to sign in, the TV apps poll an API URL to see if the device has been 'activated' yet. As the device is using a access token / session identifier, and that device is now associated with the user, the API endpoint can return the details for the user (as if it was any other session).

This is the same way the async flow for email verification works in NextAuth.js, except the NextAuth.js email sign in key is valid for longer and is a much longer key embedded in the URL the user needs to click.

**Comment by iaincollins** [comment]
Note: The `Verification Request` table that is used for email sign in in NextAuth.js is actually named the way it is and designed the way it is to support exactly this sort of flow in future, but it's probably be a while before we get to it.

Conceptually it's related to #159
