### ISSUE TITLE
Is it normal that the session in keycloak stays active when i use the signOut() function?

### ISSUE THREAD

**Issue by Uniiq** [nextauthjs/next-auth#3270]
### Question 💬

hello!

I`m having an issue with next-auth keycloak provider. After successfully sign in into the application using the keycloack provider a session is generated in keycloak. When i am signOut the session stays active. The problem is when i sign in again the user logging into the application without being redirected to keycloak login mask. That can be problematic when the user shares the device with someone else or when he want to change the account.

Is it possible to destroy the keycloak session when the user calls the `signOut()` function?

### How to reproduce ☕️

1. sign in with the keycloak provider (nextAuth 4.0.0-beta.6)
2. sign out 
3. sign in again

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
yes. federated logout is not currently supported outbox the box. #836

**Comment by Uniiq** [comment]
@balazsorban44 thx for the answer
