### ISSUE TITLE
How can I override Sign Out method ?

### ISSUE THREAD

**Issue by fangwohung** [nextauthjs/next-auth#3291]
### Question 💬

I'm using next auth 4.0.0-beta.7.
I want to override sign out method, because I stored the refresh token within the session data and I want to revoke it if the user has signed out. I can get the refresh token from session data on client side and revoke it and then sign out, but I want to do that on server side and hide the refresh token.
Is there any ways to customize  or something like callback sign out ? 

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
You should absolutely not expose the refresh token to the client!

Use the signOut event instead https://next-auth.js.org/configuration/events#signout
