### ISSUE TITLE
My No_Secret warning seems to lead to more errors that don't make sense to me.

### ISSUE THREAD

**Issue by Likeless** [nextauthjs/next-auth#3296]
### Question 💬

I am implementing an auth system using this library and I've mostly copied from the docs. I want to require authorisation on every page of my app. (Whilst I'm still learning, my auth process is to simply approve all non-empty requests.) I am getting an error #no_secret, but when I try to add a secret it starts giving other errors that don't seem to make sense to me.

Given that I already have the behaviour I want, how do I get rid of the #no_secret warning? Can I do so without extensive reconfiguration?

### How to reproduce ☕️

/pages/api/auth/[...nextauth].js
```javascript
import NextAuth from "next-auth";
import CredentialsProvider from 'next-auth/providers/credentials';

export default NextAuth({
  providers: [
    CredentialsProvider({
      name: "My Login",
      credentials: {
        username: { label: "Username", type: "text", placeholder: "username" },
        password: { label: "Password", type: "password" },
      },
      authorize: async (credentials, req) => {
        if (
          credentials.username.length < 3
          || credentials.password.length < 3
          ) {
          return null
        }
          return { id: 1, name: 'J Smith', email: 'jsmith@example.com' };
      },
    }),
  ],
});
```

_app.js
```javascript
import React from "react";
import { SessionProvider, useSession, signIn } from "next-auth/react"
import "../styles/globals.css";

const MyApp = ({ Component, pageProps: { session, ...pageProps } }) => {
  return (
    <SessionProvider session={session}>
      <Auth>
      <Component {...pageProps} />
      </Auth>
    </SessionProvider>
  );
};

function Auth({ children }) {
  const { data: session, status } = useSession();
  const isUser = !!session?.user;
  
  React.useEffect(() => {
    if (status === "loading") return // Do nothing while loading
    if (!isUser) signIn() // If not authenticated, force log in
  }, [isUser, status])

  if (isUser) {
    return children
  }

  return <div>Loading...</div>
}

export default MyApp;
```

pages/test.js
```javascript
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Test(props) {

  return (
    <div className={styles.container}>
      <Head>
        <title>aONic | adventuresON.com Interface</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        Test Page
      </main>

    </div>
  )
}
```
When I visit
http://localhost:3000/test
I get the desired behaviour (redirect to login), but I get this warning:
```
[next-auth][warn][NO_SECRET] 
https://next-auth.js.org/warnings#no_secret
```
So I modify [...nextauth].js to add a secret:
```javascript
import NextAuth from "next-auth";
import CredentialsProvider from 'next-auth/providers/credentials';

export default NextAuth({
  providers: [
    CredentialsProvider({
      name: "My Login",
      credentials: {
        username: { label: "Username", type: "text", placeholder: "username" },
        password: { label: "Password", type: "password" },
      },
      authorize: async (credentials, req) => {
        if (
          credentials.username.length < 3
          || credentials.password.length < 3
          ) {
          return null
        }
          return { id: 1, name: 'J Smith', email: 'jsmith@example.com' };
      },
    }),
  ],
  secret: 'INp8IvdIyeMcoGAgFGoA61DdBglwwSqnXJZkgz8PSnw',
});
```
I suddenly get a new error:
```
[next-auth][error][CALLBACK_CREDENTIALS_JWT_ERROR] 
https://next-auth.js.org/errors#callback_credentials_jwt_error Signin in with credentials only supported if JWT strategy is enabled UnsupportedStrategy [UnsupportedStrategyError]: Signin in with credentials only supported if JWT strategy is enabled
```
That error talks about enabling a database and I have not done that so I don't understand where it is coming from.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
duplicate. check old issues.

**Comment by Likeless** [comment]
Could you possibly please give me just a little clue that might possibly lead me in the right direction? 

This was posted as a question, not a new issue. Please could you (or somebody) help out by at least telling me what I'm looking for in the old issues? I Googled before posting but I'm a little stuck. That is why I'm asking for help.

If you give me some help, I will happily read and study but I am honestly confused and it is not obvious to me where I should be looking. If you are feeling truly generous maybe you could even link to the issue this question is asking about.

I searched the issues:
https://github.com/nextauthjs/next-auth/issues?q=is%3Aissue+no_secret+CALLBACK_CREDENTIALS_JWT_ERROR
Nothing. 

Searching for "secret" returns many results and I lack the expertise to know which one is addressing my problem.

**Comment by robrechtme** [comment]
Duplicate of #3216

**Comment by jomuji** [comment]
@Likeless  did you find an answer, i'm stuck in the same place i've checked issue #3216 but i'm not seeing where to put the SECRET= into .env file doesn't seem to work

**Comment by Likeless** [comment]
@jomuji what I did was update Next Auth to version 4.0.1 (latest at the time) and then I added the secret exactly as in my post above.
