### ISSUE TITLE
New oauth accounts get linked to the existing session's user

### ISSUE THREAD

**Issue by paolotiu** [nextauthjs/next-auth#3300]
### Title

New oauth accounts get linked to the existing session's user

### How to reproduce ☕️

https://github.com/paolotiu/next-auth-prisma-linking-repro

### Your question/bug report 📓

When a user is already signed in, but want to sign into a different oauth account, the current session's user gets linked to the newly created account.

https://user-images.githubusercontent.com/61054234/143861832-734e5cf1-2fae-406a-bab0-3bc10af74238.mp4

### Contributing  🙌🏽

Yes, I am

**Comment by balazsorban44** [comment]
Here is the relevant source code:

https://github.com/nextauthjs/next-auth/blob/b01f6805d3a8683ade5f945bd25c7d5089d283fe/src/core/lib/callback-handler.ts#L153-L218

We might do it deliberately, when you are already logged in :thinking:

I haven't written that part of the code. Long shot, but tagging @iaincollins, maybe he might have an answer here.

**Comment by paolotiu** [comment]
Yeah, I also ended up around there when trying to debug. Wasn't sure if this was intended.

**Comment by hparra** [comment]
I think this is an edge case of feature

- Callback-handler links account even if they use different email address as long as user is signed in
- This also (unintentionally?) works for linking another account of same provider but with different email address
- There _are_ use-cases for this, e.g. having both your personal and work Google accounts linked for Calendar access

I think the expected behavior here is to sign out first user and sign in the second user. The existing behavior should be available via option or by moving linking to own routes (#230).

**Comment by RaeesBhatti** [comment]
I'd like to mention here that this is the exact functionality I was looking for. So, it's a feature for me. I do agree that this should be more explicit or configurable though.

**Comment by lluia** [comment]
Here's a [possible solution](https://github.com/nextauthjs/next-auth/issues/230#issuecomment-1036440563) for it, although the use case seems a bit strange to me. 

If you're already signed in, navigating to `api/auth/signin` should not allow you to sign again and prompt you to sign out first if you want to sign in with another account. 💭

**Comment by JonParton** [comment]
> I'd like to mention here that this is the exact functionality I was looking for. So, it's a feature for me. I do agree that this should be more explicit or configurable though.

Another plus one for this to keep this issue alive as this is also being used as a feature for me too... so if changed a configuration option would be usefull!

**Comment by praet09** [comment]
Faced this issue as well. New OAuth logins force the user to be added to the "accounts" of the user in session (tested with Google as provider). Seems like an edge-case feature, unsure why it is default behavior.
