### ISSUE TITLE
Where is the MongoDB Adapter source code?

### ISSUE THREAD

**Issue by ssss1029** [nextauthjs/next-auth#3306]
### Question 💬

I'm having trouble trying to find the source code for the `MongoDBAdapter`. I installed the pacakge using: 
```
npm install next-auth@beta @next-auth/mongodb-adapter@next mongodb
```
But I cannot find the source code for this. I assumed it would be in [here](https://github.com/nextauthjs/adapters/tree/main/packages), but I don't see it there 😮.

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/adapters/tree/next/packages/mongodb
