### ISSUE TITLE
Osu Provider not working

### ISSUE THREAD

**Issue by Entropy-10** [nextauthjs/next-auth#3312]
### Question 💬

Hello, I was trying to use the built in Osu! provider but every time the import throws an error saying module not found. I'm running version 4.0.0-beta.7 of next-auth and the import I'm using is `import OsuProvider from "next-auth/providers/osu"`. 

Image of error:
![image](https://user-images.githubusercontent.com/45132530/144139018-1bb54bce-49e0-4685-8c80-50da8bfe2b0f.png)

### How to reproduce ☕️

You can reproduce this error by installing next-auth version 4.0.0-beta.7 and using the boilerplate code for the Osu! provider found here: https://next-auth.js.org/providers/osu

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Not released yet, sorry for the docs already saying so! https://github.com/nextauthjs/next-auth/pull/3234

It will be out in less than 24 hours as v4 goes stable! :tada:
