### ISSUE TITLE
Strava provider returns 400 bad request

### ISSUE THREAD

**Issue by markandrewj** [nextauthjs/next-auth#3314]
### Question 💬

Hello,

I have created a vanilla Next.js project and added version 4 of next-auth. I am trying to use the Strava provider, but I am receiving a 400 bad request. I am not sure if this is a bug, or a mistake I have made, any help would be appreciated. I have done the following. 

- Created an API/Oauth application on Strava.

![strava_01](https://user-images.githubusercontent.com/142597/144170583-77204232-98d8-4cbe-b67d-9944ebec0343.png)
![strava_02](https://user-images.githubusercontent.com/142597/144170589-beab7827-ceee-4a73-a2c7-b2d0850fbe3a.png)

- Populated __app.js_ with the following.
```
import '../styles/globals.css'

import { SessionProvider } from "next-auth/react"

export default function App({
  Component, pageProps: { session, ...pageProps }
}) {
  return (
    <SessionProvider session={session}>
      <Component {...pageProps}/>
    </SessionProvider>
  )
}
```
- Populated _index.js_ with the following.
```
import styles from "../styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react"

export default function Component() {
  const { data: session } = useSession()
  if(session) {
    return <>
      Signed in as {session.user.email} <br/>
      <button onClick={() => signOut()}>Sign out</button>
    </>
  }
  return <>
    Not signed in <br/>
    <button onClick={() => signIn()}>Sign in</button>
  </>
}
```

- Created _./api/auth/[...nextauth].js_ and populated it with the following.
_Ref: [https://next-auth.js.org/providers/strava](https://next-auth.js.org/providers/strava)_

```
import NextAuth from 'next-auth'
import StravaProvider from 'next-auth/providers/strava'

export default NextAuth({
  providers: [
    StravaProvider({
      clientId: process.env.STRAVA_CLIENT_ID,
      clientSecret: process.env.STRAVA_CLIENT_SECRET,
    })
  ]
})
```

- Created _./.env.local_ file and populated it with the following. I have also tried passing in the environment variables as string quoted.
```
STRAVA_CLIENT_ID=12345
STRAVA_CLIENT_SECRET=examplesecret
NEXTAUTH_URL=http://localhost:3000/
```

When I try logging in using Strava with either the user I created the application under, or a separate Strava user I created for testing, I receive the following error.

```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error expected 200 OK, got: 400 Bad Request {
  error: {
    message: 'expected 200 OK, got: 400 Bad Request',
    stack: 'OPError: expected 200 OK, got: 400 Bad Request\n' +
      '    at processResponse (/scratch/fitness-dashboard/fitness-dashboard/node_modules/openid-client/lib/helpers/process_response.js:48:11)\n' +
      '    at Client.grant (/scratch/fitness-dashboard/fitness-dashboard/node_modules/openid-client/lib/client.js:1265:26)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async Client.oauthCallback (/scratch/fitness-dashboard/fitness-dashboard/node_modules/openid-client/lib/client.js:561:24)\n' +
      '    at async oAuthCallback (/scratch/fitness-dashboard/fitness-dashboard/node_modules/next-auth/core/lib/oauth/callback.js:114:16)\n' +
      '    at async Object.callback (/scratch/fitness-dashboard/fitness-dashboard/node_modules/next-auth/core/routes/callback.js:50:11)\n' +
      '    at async NextAuthHandler (/scratch/fitness-dashboard/fitness-dashboard/node_modules/next-auth/core/index.js:132:28)\n' +
      '    at async NextAuthNextHandler (/scratch/fitness-dashboard/fitness-dashboard/node_modules/next-auth/next/index.js:16:19)\n' +
      '    at async /scratch/fitness-dashboard/fitness-dashboard/node_modules/next-auth/next/index.js:52:32\n' +
      '    at async Object.apiResolver (/scratch/fitness-dashboard/fitness-dashboard/node_modules/next/dist/server/api-utils.js:102:9)',
    name: 'OPError'
  },
  providerId: 'strava',
  message: 'expected 200 OK, got: 400 Bad Request'
}
[next-auth][error][CALLBACK_OAUTH_ERROR] 
https://next-auth.js.org/errors#callback_oauth_error expected 200 OK, got: 400 Bad Request OPError: expected 200 OK, got: 400 Bad Request
    at processResponse (/scratch/fitness-dashboard/fitness-dashboard/node_modules/openid-client/lib/helpers/process_response.js:48:11)
    at Client.grant (/scratch/fitness-dashboard/fitness-dashboard/node_modules/openid-client/lib/client.js:1265:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.oauthCallback (/scratch/fitness-dashboard/fitness-dashboard/node_modules/openid-client/lib/client.js:561:24)
    at async oAuthCallback (/scratch/fitness-dashboard/fitness-dashboard/node_modules/next-auth/core/lib/oauth/callback.js:114:16)
    at async Object.callback (/scratch/fitness-dashboard/fitness-dashboard/node_modules/next-auth/core/routes/callback.js:50:11)
    at async NextAuthHandler (/scratch/fitness-dashboard/fitness-dashboard/node_modules/next-auth/core/index.js:132:28)
    at async NextAuthNextHandler (/scratch/fitness-dashboard/fitness-dashboard/node_modules/next-auth/next/index.js:16:19)
    at async /scratch/fitness-dashboard/fitness-dashboard/node_modules/next-auth/next/index.js:52:32
    at async Object.apiResolver (/scratch/fitness-dashboard/fitness-dashboard/node_modules/next/dist/server/api-utils.js:102:9) {
  name: 'OAuthCallbackError',
  code: undefined
}
[next-auth][warn][NO_SECRET] 
```

**Comment by balazsorban44** [comment]
Strava hasn't been converted yet. https://github.com/nextauthjs/next-auth/issues/2524

Feel free to help out

**Comment by markandrewj** [comment]
@balazsorban44 Thanks for the information. Does this mean it should work under version 3? Is there anything I could do to help migrate the provider to v4 of next-auth?

**Comment by balazsorban44** [comment]
Providers haven't been tested before, so I wouldn't be surprised if it doesn't even work in v3...


https://next-auth.js.org/configuration/providers/oauth#options

This is the file that needs an upgrade https://github.com/nextauthjs/next-auth/blob/main/src/providers/strava.js

**Comment by markandrewj** [comment]
I am still having some trouble getting this to work, maybe you have some ideas.

I tried updating _./node_modules/next-auth/providers/strava.js_ as shown below. I don't think that adding the grant type params are required when using next-auth, but I noticed that when making a request for tokens manually that it was required. I tried without adding the grant_type params also.

```
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = Strava;

function Strava(options) {
  return {
    id: "strava",
    name: "Strava",
    type: "oauth",
    params: {
      grant_type: "authorization_code"
    },
    authorization: {
      url: "https://www.strava.com/oauth/authorize",
      params: { scope: "read" }
    },
    token: "https://www.strava.com/oauth/token",
    options
  };
}_
```

Using the updated provider I am still returned ```code: undefined```

To validate what options are required for the provider I performed the OAuth flow manually. I did this by first going to  OAuth authorization page. The URL for the authorization page is provided by Strava when you create the application. The URL uses the following format.

`https://www.strava.com/oauth/authorize?client_id=<client_id>&response_type=code&redirect_uri=http://localhost:3000&approval_prompt=force`

I then clicked `authorize` and was redirected to the following URL:

`http://localhost:3000/?state=&code=<authorization code>&scope=read`

I then used the authorization code returned to make a POST request to:

`https://www.strava.com/oauth/token?client_id=<client_id>&client_secret=<client secret>&code=<authorization code>&grant_type=authorization_code`

Which returned an _access token_ and _refresh token_.

![token_request_01](https://user-images.githubusercontent.com/142597/144540412-f6902fbf-7f3e-4585-885c-9014e1962f86.png)

![token_request_02](https://user-images.githubusercontent.com/142597/144540428-5b341e67-dde4-49af-b3bc-e7298cef1415.png)

I notice a different URL structure when trying to preform the authorization flow starting from the `Sign In` button located at the index route of my Next.js application. When I click the `Sign In` button I am redirected to the next-auth provider login page at the url `http://localhost:3000/api/auth/signin?callbackUrl=http%3A%2F%2Flocalhost%3A3000%2F`

![2021-12-02 20_40_01-Sign In](https://user-images.githubusercontent.com/142597/144541358-c34c4938-b1ed-4071-8f3e-daad0e571d17.png)

I then click the next-auth `Sign in with Strava` button and I am redirected to the Strava authorization page, but the url structure looks like this:

`https://www.strava.com/oauth/authorize?client_id=<client_id>&scope=read&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fauth%2Fcallback%2Fstrava&nextauth=signin%2Cstrava&state=<authorization code>`

Decoded the URL looks like this:

`https://www.strava.com/oauth/authorize?client_id=<client_id>&scope=read&response_type=code&redirect_uri=http://localhost:3000/api/auth/callback/strava&nextauth=signin,strava&state=<authorization code>
`

I then click `authorizie` on the Strava page, which returns me to the next-auth sign in page, but with the error param in the URL.

![2021-12-02 20_51_25-Sign In](https://user-images.githubusercontent.com/142597/144542439-0fe3f0a1-877e-4b71-baae-e4ab4de159f9.png)

In the terminal I still see same error I posted originally.

![2021-12-02 20_54_11-● https___www strava com_oauth_authorize_c • Untitled-1 - fitness-dashboard  SSH](https://user-images.githubusercontent.com/142597/144542618-b57d7b5e-f66f-4eff-a447-2f0fcd6fed06.png)

**Comment by markandrewj** [comment]
I can also move this information to the issue you referenced if that would be preferred.

**Comment by krautwigundrueben** [comment]
any progress here, @markandrewj? did you finally get it to work somehow? did you try adding strava as a custom provider?

**Comment by markandrewj** [comment]
Hey @krautwigundrueben thanks for following up. I tried editing the provider directly and creating a custom provider. Using either method resulted in the same error. There is more up to date information in #2524. There is likely something small I have got wrong. I was getting frustrated after testing for a while though, so I took a break from it. I am going to try again while I have some time over the holidays.

**Comment by gempi** [comment]
@markandrewj it's working for me with this custom provider:

``` js 
{
      id: "strava",
      name: "Strava",
      type: "oauth",
      clientId: YOUR_CLIENT_ID,
      clientSecret: YOUR_CLIENT_SECRET,
      authorization: {
        url: "https://www.strava.com/api/v3/oauth/authorize",
        params: {
          scope: "profile:read_all",
          approval_prompt: "force",
          response_type: "code",
          redirect_uri: "http://localhost:3000/api/auth/callback/strava",
        },
      },
      token: {
        url: "https://www.strava.com/api/v3/oauth/token",
        async request(context) {
          const response = await fetch(context.provider.token.url, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              ...context.params,
              client_id: context.provider.clientId,
              client_secret: context.provider.clientSecret,
              grant_type: "authorization_code",
            }),
          });

          const { refresh_token, access_token, token_type, expires_at }: any =
            await response.json();

          return {
            tokens: {
              refresh_token,
              access_token,
              token_type,
              expires_at,
            },
          };
        },
      },
      userinfo: "https://www.strava.com/api/v3/athlete",
      profile(profile) {
        return {
          id: profile.id,
          name: `${profile.firstname} ${profile.lastname}`,
          email: null,
          image: profile.profile,
        };
      },
    }
```

**Comment by krautwigundrueben** [comment]
@gempi great, thanks for sharing! will try myself after all this Christmas distraction 😜

**Comment by krautwigundrueben** [comment]
@gempi just tested this and works for me, too? did you consider a pull request here as this should solve issues for most users? I don't wanna steal this from you ;-)

**Comment by markandrewj** [comment]
Yay, this worked for me as well! Thanks @gempi! I think a pull request would make sense as @krautwigundrueben mentioned. All of the provider testing is being tracked under #2524.

**Comment by krautwigundrueben** [comment]
@gempi you might just change approval_prompt to "auto", as this might be the most common use case imho

**Comment by markandrewj** [comment]
Changing approval_prompt to "auto" make sense to me also. The scope can be customised as needed. I just thought I would add this to the thread for reference https://developers.strava.com/docs/authentication/#detailsaboutrequestingaccess.

**Comment by krautwigundrueben** [comment]
ah and you might reference Client ID and secret from the .env file instead to go in line with the other built-in providers e g. like so: client_id = process.env.STRAVA_CLIENT_ID

**Comment by markandrewj** [comment]
That's what I did as well instead of hard coding the client_id and client_secret.

```
 clientId: process.env.STRAVA_CLIENT_ID,
 clientSecret: process.env.STRAVA_CLIENT_SECRET,
```

**Comment by gempi** [comment]
@krautwigundrueben if you have time for pull request - go for it, because I am off for a while.

**Comment by krautwigundrueben** [comment]
https://github.com/nextauthjs/next-auth/pull/3520
