### ISSUE TITLE
Cannot read property 'db' of undefined

### ISSUE THREAD

**Issue by myhendry** [nextauthjs/next-auth#3315]
### Question 💬

I'm getting following error in my console pertaining to my database connection... unhandledRejection: TypeError: Cannot read property 'db' of undefined

I have checked my MONGO_URI and it is correct and it is also read in my mongodb.ts file.

Anyone knows what is incorrect here resulting in the error? I am using "next-auth": "^4.0.0-beta.7",

## inside my .env.local, i have following 
```
MONGODB_URI=mongodb+srv://yyy:aaa@cluster8.5demgi.mongodb.net/myFirstDatabase?retryWrites=true&w=majority // example only
```

## mongodb.ts
```
// This approach is taken from https://github.com/vercel/next.js/tree/canary/examples/with-mongodb
import { MongoClient, MongoClientOptions } from "mongodb";

const uri = process.env.MONGODB_URI;
const options = {
  useUnifiedTopology: true,
  useNewUrlParser: true,
} as MongoClientOptions;

console.log("uri", uri);

let client;
let clientPromise;
const g = !global as any;

if (!process.env.MONGODB_URI) {
  throw new Error("Please add your Mongo URI to .env.local");
}

if (process.env.NODE_ENV === "development") {
  // In development mode, use a global variable so that the value
  // is preserved across module reloads caused by HMR (Hot Module Replacement).
  if (g._mongoClientPromise) {
    client = new MongoClient(uri!, options);
    console.log("c", client);
    g._mongoClientPromise = client.connect();
  }
  clientPromise = g._mongoClientPromise;
} else {
  // In production mode, it's best to not use a global variable.
  client = new MongoClient(uri!, options);
  clientPromise = client.connect();
}

// Export a module-scoped MongoClient promise. By doing this in a
// separate module, the client can be shared across functions.
export default clientPromise as Promise<MongoClient>;

```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by Marc-Klein** [comment]
@myhendry can you please tell me how you fixed this issue ?

**Comment by myhendry** [comment]
I don't remember specifically how I resolved the issue. Here's the [Source Codes](https://github.com/myhendry/lab)  if you like to refer. I just run the codes on my local machine and its able to access my database

**Comment by Marc-Klein** [comment]
Thank you, very much appreciated. Maybe I'll figure it out.

**Comment by myhendry** [comment]
I tested my codes yesterday and it was able to successfully connect to my
mongo db

you can refer to the codes here
https://github.com/myhendry/LAB/tree/main/mongo


inside this repo only codes to connect to mongo

you can reference that
