### ISSUE TITLE
ERR_HTTP_HEADER_SENT requesting api/auth/session

### ISSUE THREAD

**Issue by dcorb** [nextauthjs/next-auth#3321]
### Description 🐜

From client side, there is a request happening to `api/auth/session` that fails, making the server to restart

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

Nothing special (the framework itself is doing the request, when loading any page). I'm not doing request manually

### Screenshots / Logs 📽

```
[01/Dec/2021:13:39:05 +0000] "GET /api/auth/session HTTP/1.1" 304 
_http_outgoing.js:518
 throw new ERR_HTTP_HEADERS_SENT('set');
 ^
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
```

### Environment 🖥

next-auth beta 2

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
please try upgrading, and report back with a reproduction.
