### ISSUE TITLE
Extra query param nextauth

### ISSUE THREAD

**Issue by dnikomon** [nextauthjs/next-auth#3322]
### Question 💬

Our custom provider is very strict what params can be passed and oauth flow fails because there is this NEXTAUTH query param. Is there anything I can do to not send it to the oauth server? I know it's required for next-auth to work correctly so i cant just omit it anywhere in the backend.

Exact error:
VARIABLES IN FORM NOT IN PROCEDURE: NEXTAUTH

### Config, [...nextauth].js
```
export default NextAuth({
  providers: [{
    type: 'oauth',
    id: 'oauth2',
    name: 'duoIdentifier',
    client: {
      client_id: '<client_id>',
      client_secret: '<client_secret>'
    },
    authorization: {
      url: '<auth_url>',
      params: {
        scope: 'duoIdentifier',
      }
    },
    accessTokenUrl: '<access_token_url>'
  }],
})

```

### The problem

This line cause an error on our end `&nextauth=signin%2Coauth2&` if I remove it. Everything works.

`http://*****/oauth2/auth?client_id=<client_id>&scope=duoIdentifier&response_type=code&redirect_uri=<redirect_uri>&nextauth=signin%2Coauth2&state=<state>`

This will work just fine

`http://*****/oauth2/auth?client_id=<client_id>&scope=duoIdentifier&response_type=code&redirect_uri=<redirect_uri>&state=<state>`

### How to reproduce ☕️

Custom provider so can't reproduce

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Do you at least have your nextauth config, and some pictures of where the problem happens? it's hard to do anything without any sort of reproduction. :shrug:

**Comment by dnikomon** [comment]
```
export default NextAuth({
  providers: [{
    type: 'oauth',
    id: 'oauth2',
    name: 'duoIdentifier',
    client: {
      client_id: '<client_id>',
      client_secret: '<client_secret>'
    },
    authorization: {
      url: '<auth_url>',
      params: {
        scope: 'duoIdentifier',
      }
    },
    accessTokenUrl: '<access_token_url>'
  }],
})

```

This is my simple config. 

`http://*****/oauth2/auth?client_id=<client_id>&scope=duoIdentifier&response_type=code&redirect_uri=<redirect_uri>&nextauth=signin%2Coauth2&state=<state>`

This line cause an error on our end `&nextauth=signin%2Coauth2&` if I remove it. Everything works.

`http://*****/oauth2/auth?client_id=<client_id>&scope=duoIdentifier&response_type=code&redirect_uri=<redirect_uri>&state=<state>`

**Comment by balazsorban44** [comment]
I see! That helps! It should be stripped out either here:

https://github.com/nextauthjs/next-auth/blob/fedb84872d8b54004e38cc60d6367e2debe77b52/src/core/lib/oauth/authorization-url.ts#L34

or even earlier/higher.

Feel free to open a PR
