### ISSUE TITLE
Cognito: /signup instead of /login

### ISSUE THREAD

**Issue by D-Pagey** [nextauthjs/next-auth#3331]
### Description 📓

I'd like to send the user to a sign up screen. However the only method I could find was sign in: 

```
import { signIn } from 'next-auth/client';

signIn('cognito', {
  callbackUrl: `${window.location.origin}/dashboard`
});
```

The url will be `https://[domain].auth.us-east-1.amazoncognito.com/login?[...queryParams]` and take the user to a login screen.

![Screenshot 2021-12-02 at 09 44 55](https://user-images.githubusercontent.com/26827986/144397445-4e22e089-0e43-4b70-ad43-209e61a4cb24.png)

What I want is to send users to `https://[domain].auth.us-east-1.amazoncognito.com/signup?[...queryParams]` which would show a sign up screen. 

![Screenshot 2021-12-02 at 09 43 27](https://user-images.githubusercontent.com/26827986/144397180-a3ef6d3c-f711-4bc1-b09e-ee72408eecc7.png)

I can't find anything in the docs to suggest this is an option but a simple change in the url would achieve this.

### How to reproduce ☕️

Set up any next-auth.js app with cognito integration and try to sign up rather than sign in. 

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
https://next-auth.js.org/configuration/providers/oauth#authorization-option

**Comment by D-Pagey** [comment]
I assume that there is no way for this to be conditional? Click Login takes the user to `/login` cognito endpoint and Sign Up to `/signup`

**Comment by D-Pagey** [comment]
> https://next-auth.js.org/configuration/providers/oauth#authorization-option

I can't get this working with Cognito. It seems the `issuer` property overrides the `authorization` property

**Comment by ingveldur** [comment]
@D-Pagey did you figure this out? I'm having the same problem.

**Comment by D-Pagey** [comment]
> 

I think I ended up just using AWS Amplify for the Auth part
