### ISSUE TITLE
Error: Action callback with HTTP GET is not supported by NextAuth.js

### ISSUE THREAD

**Issue by Victugord** [nextauthjs/next-auth#3334]
### Description 🐜

When using the azure-ad-b2c it keeps returning the error: 
Error: Action callback with HTTP GET is not supported by NextAuth.js

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

```
export default NextAuth({
    // Configure one or more authentication providers
    session: {
        strategy: "jwt"
    },
    providers: [
        AzureADB2CProvider({
            tenantId: process.env.AZURE_AD_B2C_TENANT_NAME,
            clientId: process.env.AZURE_AD_B2C_CLIENT_ID,
            clientSecret: process.env.AZURE_AD_B2C_CLIENT_SECRET,
            primaryUserFlow: process.env.AZURE_AD_B2C_PRIMARY_USER_FLOW,
            idToken: true,
            authorization: {params: {scope: 'offline_access openid'}},
        }),
        // ...add more providers here
    ],
})
```

### Screenshots / Logs 📽

![Untitled](https://user-images.githubusercontent.com/51913665/144420880-12b2a7a4-6543-418e-80b5-928b981ffa38.png)

### Environment 🖥

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 1.19 GB / 15.90 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.41)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    next: ^12.0.4 => 12.0.4
    next-auth: ^4.0.1 => 4.0.1
    react: ^17.0.2 => 17.0.2

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by DiagoSmith** [comment]
@Victugord  what was the issue in the end? How did you manage to solve it?

**Comment by nkkky** [comment]
> @Victugord what was the issue in the end? How did you manage to solve it?

interested to hear as well....
