### ISSUE TITLE
next-auth session api routes try to run during build time from nextjs 12

### ISSUE THREAD

**Issue by zigang93** [nextauthjs/next-auth#3343]
### Description 🐜

I am using getStaticProps for one of my pages in my nextjs 12. 
because next-auth only able to run at api routes ( server side ), when I try to run `yarn build`, the static page will try to fetch all api during the build time. 

But, It always try to get session from http://localhost:3000/api/auth/session during the `yarn build` which is will be failed to connect.. I am not sure it's a normal behaviour for next-auth.. nextjs already warn us not to run any api routes at  getStaticProps.. 

lucky, even it show error during the build but it still working when I run `yarn start`..  what should I do if I want to make sure no error during `yarn build`

nextjs: `12.0.4`
next-auth version: `4.0.2`

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

-

### Screenshots / Logs 📽

```zsh
Generating static pages (0/10)[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error request to http://localhost:3000/api/auth/session failed, reason: connect ECONNREFUSED 127.0.0.1:3000 {
  error: {
    message: 'request to http://localhost:3000/api/auth/session failed, reason: connect ECONNREFUSED 127.0.0.1:3000',
    stack: 'FetchError: request to http://localhost:3000/api/auth/session failed, reason: connect ECONNREFUSED 127.0.0.1:3000\n' +
      '    at ClientRequest.<anonymous> (/Users/tanzigang/project/wcs-web-ui/node_modules/node-fetch/lib/index.js:1461:11)\n' +
      '    at ClientRequest.emit (node:events:390:28)\n' +
      '    at Socket.socketErrorListener (node:_http_client:447:9)\n' +
      '    at Socket.emit (node:events:390:28)\n' +
      '    at emitErrorNT (node:internal/streams/destroy:157:8)\n' +
      '    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:83:21)',
    name: 'FetchError'
  },
  path: 'session',
  message: 'request to http://localhost:3000/api/auth/session failed, reason: connect ECONNREFUSED 127.0.0.1:3000'
}
```

### Environment 🖥

mac m1

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Do i understand correctly that you try to use next-auth inside getStaticProps?
