### ISSUE TITLE
Spam filter clicks authentication links

### ISSUE THREAD

**Issue by bardsol** [nextauthjs/next-auth#3345]
### Question 💬

I'm using the email provider. Some users have very strict spam filters that clicks through all URL's in their emails. Thus activating the authentication URL. When the user then clicks the URL the token is all ready used and they get redirected to the error page.

Anyone have any ideas how to avoid this? Is there a way to detect if the request is coming from a spam filter bot?

### How to reproduce ☕️

Not possible

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
This is not strictly `next-auth`'s fault, but you could use advanced initialization https://next-auth.js.org/configuration/initialization#advanced-initialization

and return early if you detect a bot.

**Comment by balazsorban44** [comment]
This is not what I meant. that will just create more friction for your users IMO.
