### ISSUE TITLE
profile callback argument type

### ISSUE THREAD

**Issue by estarossa0** [nextauthjs/next-auth#3350]
### Question 💬

When trying to use the profile callback (42-school provider) I couldn't use the profile type as it was `any` even that most the profiles are now typed in v4 and have `P extends Record<string, any> = ProviderProfile` unless you explicitly typed it with generic `Provider<ProviderProfileType>`
![image](https://user-images.githubusercontent.com/57002508/144659056-50bc14f8-fbc2-4754-ad81-5122885f6960.png)

### How to reproduce ☕️

By using any provider with a typed profile, and then adding the profile callback

```ts
import NextAuth from "next-auth";
import FortyTwoProvider from "next-auth/providers/42-school";

export default NextAuth({
  providers: [
    FortyTwoProvider({
      clientId: process.env.FORTY_TWO_CLIENT_ID,
      clientSecret: process.env.FORTY_TWO_CLIENT_SECRET,
      profile(profile) {
        return {
          id: profile.login,
          name: profile.usual_full_name,
          email: profile.email,
          image: profile.image_url,
          login: profile.login,
        };
      },
    }),
  ],
});
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by estarossa0** [comment]
any response considering this topic 😅 @balazsorban44

**Comment by ThangHuuVu** [comment]
I think the reason is because in the source code `next-auth` define the `Provider` type of `providers: Provider[]` array as following:
```ts
Provider = OAuthConfig<any> | EmailConfig | CredentialsConfig
```

All elements in the `providers` array will take this type. In this case, to use callback type, I think the only option is to explicitly define the Generic Type for the provider function; I don't think there's a way for TS to automatically infer the Generic of array element:
 
```ts
import NextAuth from "next-auth";
import FortyTwoProvider,  { FortyTwoProfile } from "next-auth/providers/42-school";

export default NextAuth({
  providers: [
    FortyTwoProvider<FortyTwoProfile>({ // explicitly define the Generic Type for the provider function;
      clientId: process.env.FORTY_TWO_CLIENT_ID,
      clientSecret: process.env.FORTY_TWO_CLIENT_SECRET,
      profile(profile) { // profile is of type FortyTwoProfile
        return {
          id: profile.login,
          name: profile.usual_full_name,
          email: profile.email,
          image: profile.image_url,
          login: profile.login,
        };
      },
    }),
  ],
});
```

@estarossa0 Does this make sense?

**Comment by balazsorban44** [comment]
@ThangHuuVu the intention is that no generics would be necessary. I believe I've tested this before, but it looks we have to take another look.
