### ISSUE TITLE
callback_oauth_error invalid_grant (Bad Request) OPError: invalid_grant (Bad Request)

### ISSUE THREAD

**Issue by aienzaini** [nextauthjs/next-auth#3356]
### Description 🐜

We have some customers trying to signing in using GoogleProvider and it throws this error:

```
[next-auth][error][CALLBACK_OAUTH_ERROR] 
https://next-auth.js.org/errors#callback_oauth_error invalid_grant (Bad Request) OPError: invalid_grant (Bad Request)
```

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

Just sign in with Google

### Screenshots / Logs 📽

```
[next-auth][error][CALLBACK_OAUTH_ERROR] 
https://next-auth.js.org/errors#callback_oauth_error invalid_grant (Bad Request) OPError: invalid_grant (Bad Request)
    at processResponse (/node_modules/next-auth/node_modules/openid-client/lib/helpers/process_response.js:45:13)
    at Client.grant (/node_modules/next-auth/node_modules/openid-client/lib/client.js:1265:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Client.callback (/node_modules/next-auth/node_modules/openid-client/lib/client.js:450:24)
    at async oAuthCallback (/node_modules/next-auth/core/lib/oauth/callback.js:112:16)
    at async Object.callback (/node_modules/next-auth/core/routes/callback.js:50:11)
    at async NextAuthHandler (/node_modules/next-auth/core/index.js:133:28)
    at async NextAuthNextHandler (/node_modules/next-auth/next/index.js:20:19)
    at async Object.apiResolver (/node_modules/next/dist/server/api-utils.js:102:9)
    at async Server.handleApiRequest (/node_modules/next/dist/server/next-server.js:1054:9) {
  name: 'OAuthCallbackError',
  code: undefined
}
```

### Environment 🖥

```
System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (4) arm64 unknown
    Memory: 7.56 GB / 15.27 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.18.0 - /usr/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 8.2.0 - /usr/bin/npm
  npmPackages:
    next: ^12.0.4 => 12.0.4 
    next-auth: 4.0.2 => 4.0.2 
    react: ^17.0.2 => 17.0.2
```

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by aienzaini** [comment]
@balazsorban44 not sure why this is closed?

**Comment by nileshzala005** [comment]
@aienzaini have you fixed it ?

**Comment by Kaltemrix** [comment]
@aienzaini Can you provide an update on how you resolved this? I am running into this issue. I have the app running in a docker container on AWS App Runner.

**Comment by atlasmac** [comment]
Any updates?

**Comment by vaibhavdeepP** [comment]
Does anyone know a fix to this?

**Comment by BrightKingsley** [comment]
> I had the same issue when developing a login flow that merges the user Google account info with our own accounts system. We had to fetch the access token using the async request in the [token property](https://next-auth.js.org/configuration/providers/oauth#token-option) of Google Provider.
> 
> Requesting the user access token to Google Oauth API (https://oauth2.googleapis.com/token), I had to send as query params both `grant_type` and `code_verifier`, because Google supports [checks](https://next-auth.js.org/getting-started/rest-api#getpost-apiauthcallbackprovider).
> 
> To use both at the same time, your value for `grant_type` should be `'authorization_code'`.
> 
> Your `code_verifier` value is in the request context (`context.checks.code_verifier`)

Please can I see a code snippet for this? I'm not sure how to go about it.

**Comment by th91vi** [comment]
> > I had the same issue when developing a login flow that merges the user Google account info with our own accounts system. We had to fetch the access token using the async request in the [token property](https://next-auth.js.org/configuration/providers/oauth#token-option) of Google Provider.
> > Requesting the user access token to Google Oauth API (https://oauth2.googleapis.com/token), I had to send as query params both `grant_type` and `code_verifier`, because Google supports [checks](https://next-auth.js.org/getting-started/rest-api#getpost-apiauthcallbackprovider).
> > To use both at the same time, your value for `grant_type` should be `'authorization_code'`.
> > Your `code_verifier` value is in the request context (`context.checks.code_verifier`)
> 
> Please can I see a code snippet for this? I'm not sure how to go about it.

You may setup a custom request to get a Google Oauth token like this:

```
import axios from 'axios';

const GOOGLE_OAUTH_BASE_URL = 'https://oauth2.googleapis.com';

export const signIn = async (nextAuthContext) => {
  try {
    const { data: googleResponse } = await axios.post(
      `${GOOGLE_OAUTH_BASE_URL}/token`,
      {},
      {
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        params: {
          code: nextAuthContext.params.code,
          client_id: nextAuthContext.provider.clientId,
          client_secret: nextAuthContext.provider.clientSecret,
          redirect_uri: nextAuthContext.provider.callbackUrl,
          grant_type: 'authorization_code',
          code_verifier: nextAuthContext.checks.code_verifier,
        },
      }
    );

    return googleResponse;
  } catch (error) {
    console.error(error);
  }
};

export const nextAuthGoogleHttpHandler = {
  signIn,
};

```

And you may setup your Google Provider like this:

```
import GoogleProvider from 'next-auth/providers/google';

import { httpHandler } from '../httpHandler';
import { nextAuthGoogleHttpHandler } from '../services/auth/google';

export const Google = GoogleProvider({
  clientId: process.env.GOOGLE_CLIENT_ID,
  clientSecret: process.env.GOOGLE_CLIENT_SECRET,
  token: {
    async request(context) {
      const googleResponse = await nextAuthGoogleHttpHandler.signIn(context);

      const { data } = await httpHandler.signIn.google(
        googleResponse.access_token
      );

      return {
        tokens: {
          ...googleResponse,
          ourCustomVendorLogin: httpHandler.handleResponse(data),
        },
      };
    },
  },
});

export default Google;
```

You will almost certainly need to also create custom callbacks to help this strategy.
