### ISSUE TITLE
how to redirect user after login using provider: credentials ?

### ISSUE THREAD

**Issue by 360synertech-dev1** [nextauthjs/next-auth#3375]
### Question 💬

using version: **```next-auth : ^4.0.0-beta.6```**
Hi,
I want to know how I can redirect users to dashboard after user in login 
and redirect the **user admin** to **/admin/dashboard**
and normal **user** to **/dashboard** page

### How to reproduce ☕️

```js 
providers: [
        CredentialsProvider({
            // The name to display on the sign in form (e.g. 'Sign in with...')
            id:'credentials',
            name: "Login",
            // The credentials is used to generate a suitable form on the sign in page.
            // You can specify whatever fields you are expecting to be submitted.
            // e.g. domain, username, password, 2FA token, etc.
            // You can pass any HTML attribute to the <input> tag through the object.
            credentials: {
                email: {label: "Email", type: "email", placeholder: "Email"},
                password: {label: "Password", type: "password"},
            },
            async authorize(credentials, req) {
                // Add logic here to look up the user from the credentials supplied
                // const user = {id: 1, name: 'J Smith', email: 'jsmith@example.com'}
                console.log(credentials)

                const user = await prisma.user.findFirst({
                    where: {
                        email: credentials.email,
                        // password: credentials.password
                    }
                });

                if (user !== null)
                {
                    userAccount = user;
                    user.redirectUrl = credentials?.afterLoginRedirect
                    return user;
                }
                else {
                    return null;
                }

            }
        })

    ],`

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by Klin-Coders** [comment]
i suppose you should handle the redirects on the client side 
create a profile function with maybe a switch statement to handle redirects to pages  and access useSession to see the client details and redirect them appropriately?

how about that

**Comment by 360synertech-dev1** [comment]
@Klin-Coders this will be not good I wanted to do using the server-side not the client side.
Client side will be less secure

**Comment by Klin-Coders** [comment]
why do you think it would be less secure
you could block the profile page from being accessible from the next config file 

```
module.exports = {
  reactStrictMode: true,
  async redirects() {
    return [
      {
        source: "/profile",
        destination: "/",
        permanent: true,
      },
    ];
  },
```

**Comment by 360synertech-dev1** [comment]
@Klin-Coders can you please explain how this works ?

**Comment by Klin-Coders** [comment]
i suppose you could create a profile page and redirect all users upon successful signin
then write the logic to handle redirects based on users role in the profile page (i am assuming you know how to extract the users from useSession hook)

then add the above logic to your next config file so that anyone who tries to manually access the /profile page would be redirected back to the root hence eradicating your suspicions on security 

what do you think?
or i could help with a working example of how i implemented this in a project

**Comment by 360synertech-dev1** [comment]
@Klin-Coders now I get it thanks for time

**Comment by Klin-Coders** [comment]
i also want to add that it might be better if you handle this using a getServerSideProps in the profile page to avoid a white blank page flashing before the roundtrip to the server to get the session data is completed

**Comment by 360synertech-dev1** [comment]
@Klin-Coders I had the same thought 🤣😂
