### ISSUE TITLE
Rejecting promise with a string in authorize does not lead to correct redirect

### ISSUE THREAD

**Issue by Amantel** [nextauthjs/next-auth#3384]
### Description 🐜

In **authorize** credentials provider throwing a string (`throw '/path/to/redirect'`) does not lead to redirect to the mentioned path, but redirects to `/api/auth/error?error=undefined`
Related docs https://next-auth.js.org/providers/credentials

### Is this a bug in your own project?

No

### How to reproduce ☕️

```
    CredentialsProvider({
      name: 'Credentials',
      credentials: {
        username: { label: 'Email', type: 'email' },
        password: { label: 'Password', type: 'password' }
      },
      async authorize(credentials) {
          throw '/path/to/redirect' // should redirect to /path/to/redirect, but redirects to /api/auth/error?error=undefined
    }
    }),
```

### Environment 🖥

  System:
    OS: Linux 4.15 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (6) x64 AMD Phenom(tm) II X6 1055T Processor
    Memory: 360.27 MB / 7.84 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 16.2.0 - ~/.nvm/versions/node/v16.2.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.13.0 - ~/.nvm/versions/node/v16.2.0/bin/npm
  Browsers:
    Chrome: 94.0.4606.81
    Firefox: 93.0
  npmPackages:
    next: ^12.0.7 => 12.0.7 
    next-auth: ^4.0.2 => 4.0.2 
    react: ^17.0.2 => 17.0.2 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by Amantel** [comment]
Also I'm really not sure what was the correct answer to 'is this a bug in your project' question.

**Comment by balazsorban44** [comment]
as pointed out in https://github.com/nextauthjs/docs/issues/163 it's not intended, and the docs should be updated to reflect that.

**Comment by goproclube** [comment]
This had a different solution?
I have the same problem with version 4.0.5.
