### ISSUE TITLE
Wordpress Provider returning OAuthCallbackError (The required "client_id" parameter is missing.)

### ISSUE THREAD

**Issue by spencerpowell** [nextauthjs/next-auth#3389]
### Description 🐜

I have an existing Wordpress site that has members who subscribe and I'm also building a new Next.js app.  I'm wanting to use OAuth so that those users from the Wordpress site can use their Memberpress login to authenticate into the new Next.js app.

I have copied the [...nextAuth].js file from the nextauthjs-example-repository and have added the `WordpressProvider`. I have checked that environment variables are correctly loaded and have the expected client id and client secret for my Wordpress OAuth app. 

My steps:

- Set up an application through Wordpress to get client id and secret: https://developer.wordpress.com/apps/
- Click on Sign in with Wordpress button in my NextJS app
- Wordpress application consent screen shows up
- Wordpress redirects back to my application using the following url: https://domain.com/api/auth/callback/wordpress
- NextAuthjs receives then in this endpoint redirects me to https://domain.com/api/auth/error?error=oAuthCallback

I see this in the terminal 
<img width="1428" alt="Screen Shot 2021-12-07 at 7 38 06 PM" src="https://user-images.githubusercontent.com/2447847/145127865-b3aca388-6cf7-4166-b7e7-34996d991952.png">

I have reproduced this with multiple Wordpress accounts and have set up everything correctly on the Wordpress side

### Is this a bug in your own project?

No

### How to reproduce ☕️

- Set up an application through Wordpress to get client id and secret: https://developer.wordpress.com/apps/
- Click on Sign in with Wordpress button in my NextJS app
- Wordpress application consent screen shows up
- Wordpress redirects back to my application using the following url: https://domain.com/api/auth/callback/wordpress
- NextAuthjs receives then in this endpoint redirects me to https://domain.com/api/auth/error?error=oAuthCallback

### Screenshots / Logs 📽

<img width="1665" alt="Screen Shot 2021-12-07 at 7 25 47 PM" src="https://user-images.githubusercontent.com/2447847/145127392-936e4457-274f-4a5a-a071-ad7b116a0edc.png">

<img width="1664" alt="Screen Shot 2021-12-07 at 7 26 01 PM" src="https://user-images.githubusercontent.com/2447847/145127398-44b4d070-921f-483e-8f6e-6e3a5d7fbe0b.png">

<img width="1428" alt="Screen Shot 2021-12-07 at 7 38 06 PM" src="https://user-images.githubusercontent.com/2447847/145127651-cfd4d838-8aa5-4762-9d4f-6ed6ac873aa2.png">

### Environment 🖥

System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 5.64 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.18.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.93
    Safari: 13.1.3
  npmPackages:
    next: ^12.0.1 => 12.0.7 
    next-auth: ^4.0.1 => 4.0.2 
    react: ^17.0.2 => 17.0.2 

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
#2524

**Comment by rediahila** [comment]
@spencerpowell this will fix it

```
WordpressProvider({
      clientId: process.env.WORDPRESS_CLIENT_ID,
      clientSecret: process.env.WORDPRESS_CLIENT_SECRET,
      token: {
        url: 'https://public-api.wordpress.com/oauth2/token',
        async request(context) {
          const { provider, params: parameters, checks, client } = context
          const { callbackUrl } = provider

          const tokenset = await client.grant({
            grant_type: 'authorization_code',
            code: parameters.code,
            redirect_uri: callbackUrl,
            code_verifier: checks.code_verifier,
            client_id: process.env.WORDPRESS_CLIENT_ID,
            client_secret: process.env.WORDPRESS_CLIENT_SECRET,
          })
          return { tokens: tokenset }
        },
      },
    })
```

**Comment by klinsc** [comment]
> @spencerpowell this will fix it
> 
> ```
> WordpressProvider({
>       clientId: process.env.WORDPRESS_CLIENT_ID,
>       clientSecret: process.env.WORDPRESS_CLIENT_SECRET,
>       token: {
>         url: 'https://public-api.wordpress.com/oauth2/token',
>         async request(context) {
>           const { provider, params: parameters, checks, client } = context
>           const { callbackUrl } = provider
> 
>           const tokenset = await client.grant({
>             grant_type: 'authorization_code',
>             code: parameters.code,
>             redirect_uri: callbackUrl,
>             code_verifier: checks.code_verifier,
>             client_id: process.env.WORDPRESS_CLIENT_ID,
>             client_secret: process.env.WORDPRESS_CLIENT_SECRET,
>           })
>           return { tokens: tokenset }
>         },
>       },
>     })
> ```

Thank you! This fix my issues as well, but I wonder why?
Because there is no explanation of this code in NextAuthJS documents, only on wordpress's.
And well, wordpress's documents are really easy to read. 😂

**Comment by rediahila** [comment]
> > @spencerpowell this will fix it
> > ```
> > WordpressProvider({
> >       clientId: process.env.WORDPRESS_CLIENT_ID,
> >       clientSecret: process.env.WORDPRESS_CLIENT_SECRET,
> >       token: {
> >         url: 'https://public-api.wordpress.com/oauth2/token',
> >         async request(context) {
> >           const { provider, params: parameters, checks, client } = context
> >           const { callbackUrl } = provider
> > 
> >           const tokenset = await client.grant({
> >             grant_type: 'authorization_code',
> >             code: parameters.code,
> >             redirect_uri: callbackUrl,
> >             code_verifier: checks.code_verifier,
> >             client_id: process.env.WORDPRESS_CLIENT_ID,
> >             client_secret: process.env.WORDPRESS_CLIENT_SECRET,
> >           })
> >           return { tokens: tokenset }
> >         },
> >       },
> >     })
> > ```
> 
> Thank you! This fix my issues as well, but I wonder why? Because there is no explanation of this code in NextAuthJS documents, only on wordpress's. And well, wordpress's documents are really easy to read. 😂

Actually, another user's comment pointed toward this solution but that implementation wasn't for WordPress.

**Comment by dgallardox** [comment]
This is dumb LOL

**Comment by hongjiaherng** [comment]
This is a similar problem as in https://github.com/nextauthjs/next-auth/issues/5122

NextAuth uses openid-client (https://github.com/panva/node-openid-client) under the hood. By default, `token_endpoint_auth_method` from openid-client is set to `client_secret_basic`, which means `client_id` and `client_secret` is sent to the token endpoint using the Authorization header. 

Using a custom provider, my auth provider requires the `client_id` to be in the request body instead of header. So, changing `token_endpoint_auth_method` to `client_secret_post` solves the problem.

Refer to this for more detailed information: https://github.com/nextauthjs/next-auth/issues/5122

Here is how I set the token_endpoint_auth_method for my custom provider in NextAuth:
```ts
const MyCompanyProvider: OAuthConfig<any> = {
  clientId: process.env.MY_COMPANY_CLIENT_ID,
  clientSecret: process.env.MY_COMPANY_CLIENT_SECRET,
  wellKnown:
    "https://mycompany.com/oidc/.well-known/openid-configuration",
  id: "mycompany",
  name: "My Company",
  type: "oauth",
  version: "2.0",
  checks: ["pkce", "state"],
  profile: (profile) => {
    return {
      id: profile.profileid, // unique id for the user
      name: profile.preferred_username, // username in the format of Firstname_Lastname or other format
      email: profile.email, // company email
      image: null, // no image
    };
  },
  idToken: true,
  authorization: {
    params: {
      scope: "openid profile email", // This yields (openid: profileid), (profile: name, given_name, family_name, preferred_username, domain), (email: email, email_verified)
    },
  },
  client: {
    token_endpoint_auth_method: "client_secret_post", // LOOK HERE!!!
  },
```
