### ISSUE TITLE
Live demo redirecting to localhost on auth providers

### ISSUE THREAD

**Issue by bcomnes** [nextauthjs/next-auth#3401]
### Description 🐜

The demo is redirecting to localhost for some reason

https://user-images.githubusercontent.com/166301/145250254-92ba6da0-678f-4c05-b1f0-8e5d95ef9652.mp4

### Is this a bug in your own project?

No

### How to reproduce ☕️

Try to log in with GitHub or any other provider on the live demo.

### Environment 🖥

Safari, Brave etc.

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
Just fixed this, please give it another try :sweat_smile:

**Comment by bcomnes** [comment]
Its working now, and fixed safari login with oauth providers 🤔 just need to figure out what you did there and get that fixed over on my end. 

Thanks and cheers!

**Comment by balazsorban44** [comment]
😬 I, was messing around with the env variable/callback url. see the commit history on the `main` branch.
