### ISSUE TITLE
Allow custom claims in Session.user

### ISSUE THREAD

**Issue by amaster507** [nextauthjs/next-auth#3406]
### Question 💬

in my `[...nextauth].js` script I am setting a custom session callback. In this I am adding additional information to the user `session.user` such as `session.user.username`. This works.

What is then difficult is typing the session when using `getSession` which does not accept a generic type like `getSession<MySessionType>()`. 

If I don't do a type casting with `as` I will get typescript errors.

Can we modify the `DefaultSessions` type to:

```typescript
export interface DefaultSessionUser extends Record<string, unknown> {
  name?: string | null
  email?: string | null
  image?: string | null
}

export interface DefaultSession extends Record<string, unknown> {
  user?: DefaultSessionUser
  expires?: string
}
```

Or can we modify the `client.d.ts` export to:

```typescript
export function useSession<S = Session>(): [S | null, boolean]
```

### How to reproduce ☕️

This causes me to do something like the following which gets messy:

```jsx
  const session = useSession()
  const username = (session as MySessionType).user.username
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
https://next-auth.js.org/getting-started/typescript#module-augmentation

**Comment by amaster507** [comment]
Missed that from the docs. Thank you!
