### ISSUE TITLE
OAuthAccountNotLinked error: 2 different emails but with the same provider

### ISSUE THREAD

**Issue by MZ071999** [nextauthjs/next-auth#3431]
### Question 💬

I got the same error as #519 but my use case is a little different

What I need to do:
I need to test my app for real-time chat, which means I need to log two users at the same time.

What I did that led to the error: 
I opened two different windows and tried to log two different emails at the same time

Notes:
- I am using one provider: google
- I am trying to log two users/two different emails at the same time 
- both users have signed in before (so their details have been recorded in the DB, I use Mongo)
- I am testing this in the development mode, the server running in my own machine

what can I do to resolve this?

### How to reproduce ☕️

n/a

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
we sync tab sessions.(meaning in the same browser context xyou will be logged in with one of the user at a time). 

just use two different windows instead.

**Comment by MZ071999** [comment]
@balazsorban44 but I was using two different windows.. and I still got this error

**Comment by balazsorban44** [comment]
windows or tabs? even tabs separated from the same window won't work. this is defined by the browser BTW. do you have a reproduction?

**Comment by MZ071999** [comment]
yes I mean two different **windows** not tabs, sorry I should've mentioned windows in my original question as well

this is my [...nextauth].js file:
```
import { MongoDBAdapter } from "@next-auth/mongodb-adapter";
import clientPromise from "../../../utils/mongodb";

export default async function auth(req, res) {
  return await NextAuth(req, res, {
    providers: [
      GoogleProvider({
        clientId: process.env.GOOGLE_CLIENT_ID,
        clientSecret: process.env.GOOGLE_CLIENT_SECRET,
      }),
    ],
    adapter: MongoDBAdapter({
      db: (await clientPromise).db("crystal"),
    }),
    callbacks: {
      redirect: async (url, _) => {
        if (url == "/api/auth/signin") {
          return Promise.resolve("/home");
        }
        return Promise.resolve("/home"); //the page user will see if they click sign out
      },
      session: async (session, user, _sessionToken) => {
        return Promise.resolve(session);
      },
    },
  });
}

```

and this is my MongoDB file:

```
import { MongoClient } from "mongodb";

const uri = process.env.MONGODB_URI;
const options = {
  useUnifiedTopology: true,
  useNewUrlParser: true,
};

let client;
let clientPromise;

if (!process.env.MONGODB_URI) {
  throw new Error("Please add your Mongo URI to .env.local");
}

if (process.env.NODE_ENV === "development") {Replacement).
  if (!global._mongoClientPromise) {
    client = new MongoClient(uri, options);
    global._mongoClientPromise = client.connect();
  }
  clientPromise = global._mongoClientPromise;
} else {
  client = new MongoClient(uri, options);
  clientPromise = client.connect();
}

export default clientPromise;

```
