### ISSUE TITLE
Using Azure AD App roles 

### ISSUE THREAD

**Issue by IceInBeard** [nextauthjs/next-auth#3460]
### Question 💬

Hello lovely open-source community! 

My goal is to use Azure AD App roles to separate users into different levels of access, such as "read access", "write access", "admin access" etc, so that I can have all my user management in Azure AD. 

After looking through the documentation for Azure AD, it looks like they are sending this data in the ID token, but not expose it in their user info endpoint (https://graph.microsoft.com/oidc/userinfo). So then I tried to get Id token working. 
I enabled id token in Azure 
![image](https://user-images.githubusercontent.com/11717433/146509802-8cd02b3d-cded-4b80-ae31-2ec13b0491de.png)

And then set `idToken: true` in my provider config. But I still get the error `id_token not present in TokenSet`. 

Am I missing a step? Is id tokens supported by this provider? Is there an alternative way to achieve my goal? 

I am using the AzureAdProvider (next-auth/providers/azure-ad), Next-auth version 4.0.0-beta.7. 

### How to reproduce ☕️

I am using the AzureAdProvider (next-auth/providers/azure-ad), Next-auth version 4.0.0-beta.7. 
This is my provider config: 
```
NextAuth({
    providers: [
      AzureAdProvider({
        clientId: process.env.AZURE_AD_CLIENT_ID,
        clientSecret: process.env.AZURE_AD_CLIENT_SECRET,
        tenantId: process.env.AZURE_AD_TENANT_ID,
        idToken: true,
      }),
    ],})


### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
your screenshot shows that the `id_token` will be set for implicit and hybrid flows, none of which next-auth aims to support.
