### ISSUE TITLE
Model update for prisma adapter

### ISSUE THREAD

**Issue by songhobby** [nextauthjs/next-auth#3465]
### Description 🐜

the Account model defined in the documentation is outdated

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

next-auth-example

### Environment 🖥

latest nextjs prisma

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by songhobby** [comment]
The following solves a lot of the problem
```
model Account {
  id                       String  @id @default(cuid())
  userId                   String
  type                     String
  provider                 String
  providerAccountId        String
  refresh_token            String? @db.Text
  refresh_token_expires_in Int?
  access_token             String? @db.Text
  expires_at               Int?
  token_type               String?
  scope                    String?
  id_token                 String? @db.Text
  session_state            String?
  oauth_token_secret       String? @db.Text
  oauth_token              String? @db.Text

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}```

**Comment by lionelrudaz** [comment]
@songhobby I have an issue with Facebook only, wondering if that's connected to the schema. I've got the same as in your comment, but without @db.Text, is that an issue? I've reported my problem here: https://github.com/nextauthjs/next-auth/issues/3491

**Comment by songhobby** [comment]
Copy this schema and run prisma migrate should solve the issue. The default string type in prisma can’t contain some tokens.
