### ISSUE TITLE
OKTA Provider with PKCE error

### ISSUE THREAD

**Issue by rick-jwq** [nextauthjs/next-auth#3466]
### Description 🐜

I tried to use OKTA as the provider for authenticating my new NextJS App. The following is the configuration I've used for setting up OKTA by trying to the SignIn function provided by the library. The OKTA application is for a SPA and as a result, I don't have a client secret to be configured. The only way I can do is PKCE authentication flow. Can someone please guide me how to resolve this issue?

### Is this a bug in your own project?

No

### How to reproduce ☕️

My `[...nextauth].ts` file contains the following:
```
const options = {
  providers: [
    OktaProvider({
      clientId: process.env.OKTA_CLIENTID || '',
      issuer: `https://${process.env.OKTA_DOMAIN}/oauth2/default`,
      clientSecret: '',
      authorization: {
        params: {
          scope:  'offline_access openid profile email',
        }
      } 
    }),
  ],
  secret: 'secret'
}

export default (req: any, res: any) => NextAuth(req, res, options)
```

### Screenshots / Logs 📽
Landing page after pressing sign in
<img width="1029" alt="Screen Shot 2021-12-17 at 3 04 04 PM" src="https://user-images.githubusercontent.com/26340881/146617678-e3cd414c-822d-4785-bc5e-5f266c11ac8d.png">

Error message
<img width="812" alt="Screen Shot 2021-12-17 at 2 28 44 PM" src="https://user-images.githubusercontent.com/26340881/146615262-13639e6f-af58-4c48-8b6e-01d204336a3e.png">

Okta setting
<img width="724" alt="Screen Shot 2021-12-17 at 2 28 00 PM" src="https://user-images.githubusercontent.com/26340881/146615206-c8b86135-5e5c-4a67-970f-4109623822e9.png">

Okta error log
<img width="997" alt="Screen Shot 2021-12-17 at 3 05 14 PM" src="https://user-images.githubusercontent.com/26340881/146617759-6f467426-a56a-424d-8719-ddd6934a0c59.png">

### Environment 🖥

System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 431.61 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
 Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    npm: 8.1.0 - /usr/local/bin/npm
 Browsers:
    Chrome: 92.0.4515.159
    Firefox: 78.6.1
    Safari: 14.1.2
 npmPackages:
    next: 12.0.7 => 12.0.7
    next-auth: ^4.0.5 => 4.0.5
    react: 17.0.2 => 17.0.2

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
that provider doesn't use PKCE by default.

you can add `checks: ["pkce"]` to the provider config

**Comment by rick-jwq** [comment]
> that provider doesn't use PKCE by default.
> 
> you can add `checks: ["pkce"]` to the provider config.
> 
> fyi, next-auth clients aren't public, so technically you don't need to use PKCE.

Hi, after setting `checks: ["pkce", "state"]`, I am seeing this error trying to sign in 
` providerId: 'okta',
  message: 'client_secret_basic client authentication method requires a client_secret'`
