### ISSUE TITLE
DynamoDb Adapter + EmailProvider do not work properly 

### ISSUE THREAD

**Issue by cosimochellini** [nextauthjs/next-auth#3482]
### Description 🐜

Using this configuration generates an error in the phase of confirming the email
```js
{ 
    providers: [EmailProvider(opts)],
    adapter: DynamoDBAdapter(DocumentClient),
}
```
I've configured the adapter and the provider as the docs say.

Both the email provider and the dynamo document client work properly since the email send the emails (in the [...nextauth].ts and also in the rest of the application) and the dynamo client is capable of reading/writing other data in the rest of the application.

I've followed the guide to configure the table next-auth on AWS and it seems to match the structure you're asking for.

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

- clone the repo https://github.com/cosimochellini/s3-share-files
- configure the .env starting from .env.fake (if you need I can provide a .env proper configured via email)
- yarn 
- yarn dev
- [signin]
- confirm the link sent via email

### Environment 🖥

- both on windows 10 (node v14.18.1) and Vercel (standard deploy https://s3-share-files.vercel.app/root)

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
wrong repo. please follow the instructions
