### ISSUE TITLE
Workaround to have a different name than "type" in Accounts

### ISSUE THREAD

**Issue by lionelrudaz** [nextauthjs/next-auth#3486]
### Question 💬

While upgrading to v4, I had to rename an Account column to "type".

In my case, this is used only to store a value "oauth".

The thing is that the column "type" is used by Rails to define some logic, so it's a reserved name.

How can I use a different name for my model? I'm using Sequelize to run queries. I know how to add a column to a model, not how to rename a column and haven't found the solution in the docs.

### How to reproduce ☕️

Run the migration from v3 to v4 on a Rails app. Retrieve a user and their accounts in the same query. You get the following error:

```
ActiveRecord::SubclassNotFound (The single-table inheritance mechanism failed to locate the subclass: 'oauth'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Account.inheritance_column to use another column for that information.)
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
you can override the `linkAccount` method of the Adapter so it doesn't return the `type` property.

**Comment by lionelrudaz** [comment]
Thanks @balazsorban44 

I've solved it by remapping the field in the model like this:

```
adapter: SequelizeAdapter(sequelize, {
    models: {
      Account: sequelize.define("account", {
        ...models.Account,
        type: {type: DataTypes.STRING, field: 'provider_type'},
        createdAt: {type: DataTypes.DATE, field: 'created_at'},
        updatedAt: {type: DataTypes.DATE, field: 'updated_at'},
      }),
    },
  })
```

Let me know if I can be of any help to document that in the docs.

**Comment by balazsorban44** [comment]
Actually, I can see that for Sequelize, it is already documented actually https://next-auth.js.org/adapters/sequelize#using-custom-models

**Comment by lionelrudaz** [comment]
Yes, it helped a lot. The only thing missing was the option to define another name for the column, but that was easy to find from Sequelize docs.
