### ISSUE TITLE
How to only send magic link if user is known?

### ISSUE THREAD

**Issue by grantspilsbury** [nextauthjs/next-auth#3487]
### Question 💬

I am using "magic" emails to log my users in. 

I only want a couple of known friends to log in at this early stage.

How can I only send out the magic links if the email address is known / on a list / or in my db (I'm using Prisma)?

A terrible attempt in `/pages/api/auth/[...nextauth.ts]`
```
const authHandler: NextApiHandler = (req, res) => {
  if (APPROVED_EMAIL_LIST.includes(req.body.email)) {
    return NextAuth(req, res, options)
  }
}
```
Question [699](https://github.com/nextauthjs/next-auth/issues/699) has the same title but I don't believe it is the same question

### How to reproduce ☕️

I have used [this Prisma starter project ](https://github.com/prisma/prisma-examples/tree/latest/typescript/rest-nextjs-api-routes-auth)

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by kasperaamodt** [comment]
@grantspilsbury did you solve this?

**Comment by georghans** [comment]
having the same problem? has anybody sovled this?

**Comment by georghans** [comment]
in my case this was solved here: https://github.com/nextauthjs/next-auth/discussions/4132
