### ISSUE TITLE
client certificate auth

### ISSUE THREAD

**Issue by Freundschaft** [nextauthjs/next-auth#3489]
### Description 📓

hello,

is there any existing solution/example on how to implement client certificate auth (https://www.ssl.com/how-to/configuring-client-authentication-certificates-in-web-browsers/)?

Thanks & Best

### How to reproduce ☕️

none

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
> Please provide a more in-depth description of the feature proposed
