### ISSUE TITLE
custom invalid method response in /api/auth/

### ISSUE THREAD

**Issue by litlatte** [nextauthjs/next-auth#3493]
### Description 📓

In my opinion, it would be cool to add the possibility of customizing the response that a user gets when an invalid endpoint in the api/auth/ gets requested.

Two possible implementations could be:
1) An object representing the response e.g.:
```
interface InvalidMethodResponse<Body extends string | Record<string, any> | any[] = any>{
  status?: number
  body?: Body
  redirect?: string
}
```
2) Add a function with the "action" and "method" parameters e.g.
```
function invalidMethodResponse(actions: string, method: string){
  return {
    status?: number
    body?: Body
    redirect?: string
  }
}
```

In my opinion, the second option is a better one

### How to reproduce ☕️

Not applicable

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
"it would be cool" is not a valid reason for us to explore this. Do you have an actual use case? Please add as much information as possible. Please read through the issue template you filled with care and take your time answering our questions. It will greatly help anyone interested in the idea to discuss this further or understand your reasoning.

**Comment by litlatte** [comment]
This feature's main purpose would be to allow to change the response that is given to users (and by users I mean the people browsing your site) when they visit a page under /api/auth/, and that page does not exist.
The current response that is given by NextAuth.js is: `Error: Action ${action} with HTTP ${method} is not supported by NextAuth.js` but that is partially wrong since the issue is not the method but the route itself.

Examples:
Vercel:
Example endpoint: https://vercel.com/api/now/registration?mode=login
Vercel's response for example is giving a generic "Not Found" error instead of method not allowed

Dropbox:
Example endpoint: https://www.dropbox.com/ajax_login
Dropbox on the other hand redirects the user to the homepage.

Allowing the developers to customize the response to give on invalid endpoints has also other benefits such as security or/and branding similar to the ones that we have for the custom cookie names.

Let me know if you need any further information @balazsorban44

**Comment by balazsorban44** [comment]
Users are not intended to visit APIs in general. I'm going to close this as I can already tell this is not something we would like to add.
