### ISSUE TITLE
getToken returns null on API call (i.e.: JWT stored as Bearer)

### ISSUE THREAD

**Issue by dweemx** [nextauthjs/next-auth#3506]
### Description 🐜

I'm trying to make the `getToken` function work when making a API call with the `JWT` stored as Bearer in the `Authorization` header.
Unfortunately, the `await getToken({ req, secret })` returns `null`.

### Is this a bug in your own project?

No

### How to reproduce ☕️

1. Clone https://github.com/nextauthjs/next-auth-typescript-example
2. `npm run dev`
3. Make an API call to http://localhost:3000/api/examples/jwt with a Bearer

I think the problem lies here: https://github.com/nextauthjs/next-auth/blob/main/src/jwt/index.ts#L91-L99. The value of the `token` variable is `""` after the statement `let token = sessionStore.value`. Hence the return of the function call is `null`.

### Environment 🖥

```
  System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Memory: 220.55 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
  Browsers:
    Brave Browser: 95.1.31.91
    Chrome: 96.0.4664.110
    Firefox: 95.0.2
    Safari: 14.1.1
  npmPackages:
    next: ^11.1.2 => 11.1.3 
    next-auth: ^4.0.2 => 4.0.2 
    react: ^17.0.2 => 17.0.2
```

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
Fixed https://github.com/nextauthjs/next-auth/pull/3453
