### ISSUE TITLE
Can't use Node v17.3.0

### ISSUE THREAD

**Issue by harshhhdev** [nextauthjs/next-auth#3511]
### Description 🐜

I cloned the next-auth-example repository on GitHub, when I go & try to install the packages, I get an error as the latest Node version on my machine isn't compatible with this library.

### Is this a bug in your own project?

No

### How to reproduce ☕️

1) install Node v17.3.0 or above on your machine
2) clone the next-auth-example starter template
3) install the packages
4) see error

### Screenshots / Logs 📽

```
yarn install v1.22.17
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
error next-auth@4.0.6: The engine "node" is incompatible with this module. Expected version "^12.19.0 || ^14.15.0 || ^16.13.0". Got "17.3.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Environment 🖥

```
  System:
    OS: Linux 5.15 Archcraft
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 10.26 GB / 15.08 GB
    Container: Yes
    Shell: 0.41.0 - /bin/nu
  Binaries:
    Node: 17.3.0 - /usr/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.3.0 - /usr/bin/npm
  Managers:
    Cargo: 1.57.0 - /usr/bin/cargo
  Utilities:
    Make: 4.3 - /usr/bin/make
    GCC: 11.1.0 - /usr/bin/gcc
    Git: 2.34.1 - /usr/bin/git
    Ninja: 1.10.2 - /usr/bin/ninja
    FFmpeg: 4.4.1 - /usr/bin/ffmpeg
  IDEs:
    Nano: 6.0 - /usr/bin/nano
    VSCode: 1.62.0 - /usr/bin/code
    Vim: 8.2 - /usr/bin/vim
  Languages:
    Bash: 5.1.12 - /usr/bin/bash
    Java: 17.0.1 - /usr/bin/javac
    Perl: 5.34.0 - /usr/bin/perl
    Python: 3.10.1 - /usr/bin/python
    Python3: 3.10.1 - /usr/bin/python3
    Rust: 1.57.0 - /usr/bin/rustc
  Databases:
    PostgreSQL: 13.4 - /usr/bin/postgres
    SQLite: 3.37.0 - /usr/bin/sqlite3
  Browsers:
    Brave Browser: 96.1.33.106
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by harshhhdev** [comment]
If anybody else is experiencing a similar issue, try:

```
yarn --ignore-engines
```

**Comment by balazsorban44** [comment]
It's not a bug. As the message states, you are using a node version that isn't tested.
See:
https://github.com/nextauthjs/next-auth/blob/0e8be0c7d28b7304277868804cb20bd128b73d47/package.json#L134

If you are fine with the risks, do as https://github.com/nextauthjs/next-auth/issues/3511#issuecomment-1000471218 said.
