### ISSUE TITLE
Cannot find package 'postcss' when running `npm run dev:setup`

### ISSUE THREAD

**Issue by baptisteArno** [nextauthjs/next-auth#3512]
### Description 🐜

After cloning the project and installing the packages, running `npm run dev:setup` throws:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'postcss' imported from [...]/next-auth/node_modules/postcss-cli/index.js
```

It can be resolved by installing postcss `npm install postcss`

### Is this a bug in your own project?

No

### How to reproduce ☕️

1. Project fresh install
2. Run `npm run dev:setup`

### Environment 🖥

- System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 104.73 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
- Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
- Browsers:
    Chrome: 96.0.4664.110
    Firefox Nightly: 97.0a1
    Safari: 15.1
- npmPackages:
    next: 12.0.7 => 12.0.7 
    react: ^17.0.2 => 17.0.2

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
I could not reproduce this. Make sure you are at least on Node 16 as we are using a newer version of lock file. That might be your issue, but I'm just guessing.
