### ISSUE TITLE
Custom Model documentation has incorrect character length on  Account table.

### ISSUE THREAD

**Issue by betancourtl** [nextauthjs/next-auth#3517]
### Description 🐜

I'm creating a custom adapter for dajngo rest framework. I followed the model documentation to create the db tables. When I try to authenticate with Google I get back an id_token that is 1170 characters in length, but the model I created following the Model documentation specifies a max character of 255.

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

create a custom adapter and model following documentation and try to sign in with google

### Screenshots / Logs 📽

![Screen Shot 2021-12-25 at 7 22 33 PM](https://user-images.githubusercontent.com/7534346/147395996-f809fa19-9da1-45d6-843e-45fa84b560b4.png)

### Environment 🖥

dev

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
Wrong repo, but it has been also mentioned/asked/answered multiple times. Please do a search before opening a new issue to help us with maintenance. 🙏
