### ISSUE TITLE
Anyone help me with this error in typescript

### ISSUE THREAD

**Issue by pradhuman01** [nextauthjs/next-auth#3518]
### Question 💬

![Screenshot 2021-12-26 at 3 43 51 PM](https://user-images.githubusercontent.com/24241624/147405157-5fce1701-b682-4928-9454-7b77767d9358.png)
 Why im getting this kind of error in typescript and how to resolve this ?

### How to reproduce ☕️

I think its not require.. if require then please let me know..

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
https://next-auth.js.org/getting-started/typescript

**Comment by pradhuman01** [comment]
Thanks
