### ISSUE TITLE
Customise scope in Spotify provider

### ISSUE THREAD

**Issue by harshhhdev** [nextauthjs/next-auth#3528]
### Description 📓

Inside the [spotify provider](https://github.com/nextauthjs/next-auth/blob/main/src/providers/spotify.ts), we currently don't have the option to change the scope & it's hardcoded to `user-read-email`. If we want to change this, we have to fork the file which isn't ideal. 

### How to reproduce ☕️

1) Clone the next-auth-example project
2) Setup Spotify provider
3) Do something which is out of the hardcoded scope
4) See error

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by gryevns** [comment]
Came across a similar problem myself today, docs available:
https://next-auth.js.org/configuration/providers/oauth#authorization-option

**Comment by balazsorban44** [comment]
What @gryevns said.
