### ISSUE TITLE
Saving JwtRefresh too large not working.

### ISSUE THREAD

**Issue by wazod** [nextauthjs/next-auth#3529]
### Description 🐜

I have a problem using jwt and saving in one of attributes the jwt refresh token. I realize that is too big, because if I change and put the same as jwt in the attr, it works. But it hasn't sense

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

In [...nextauth].js I have: 

```
pages: {
    signIn: '/app/auth/login',
    signOut: '/app/auth/login',
    error: '/app/auth/login', // Error code passed in query string as ?error=
    verifyRequest: '/app/auth/verify', // (used for check email message)
    newUser: null // If set, new users will be directed here on first sign in
  },
  callbacks: {
    async signIn(user, account, profile) {
      return true
    },
    async session(session, token) {
      session.user.jwt = token.jwt
      delete session.name
      delete session.image
      return session
    },
    async jwt(token, user, account, profile, isNewUser) {
      if(profile?.jwt) token.jwt = profile.jwt
      if(profile?.jwtRefresh) token.jwtRefresh = profile.jwtRefresh
      return token
    }
```

jwtRefresh it has a legnth of 1366, instead jwt has more less that 1100 characters. If I put, it works..:

    ```
async jwt(token, user, account, profile, isNewUser) {
      if(profile?.jwt) token.jwt = profile.jwt
      if(profile?.jwtRefresh) token.jwtRefresh = profile.jwt
      return token
    }
```

### Environment 🖥

System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 7.45 GB / 31.92 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (96.0.1054.62)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    next: 11.1.2 => 11.1.2
    react: 17.0.2 => 17.0.2

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Please upgrade to v4. It comes with cookie chunking, essentially working around any size limitations.
