### ISSUE TITLE
Session data returns undefined in component if passed from getServerSideProps in nextjs

### ISSUE THREAD

**Issue by Klin-Coders** [nextauthjs/next-auth#3533]
### Description 🐜

I tried checking the user session in nextjs getServerSideProps and get a response but if passed as props to the page component, it returns undefined

### Is this a bug in your own project?

No

### How to reproduce ☕️
```js
import Head from "next/head";
import { getSession } from "next-auth/react";

const Dashboard = ({ session }) => {
  console.log(session); // returns undefined
  return (
    <div className="w-full h-screen">
      <Head>
        <title>Dashboard</title>
      </Head>
    </div>
  );
};
export default Dashboard;

export async function getServerSideProps(context) {
  const session = await getSession(context);
  console.log(session); // session is returned correctly
  return { props: { session } }; //returns undefined in page
}
```

### Environment 🖥

 System:
    OS: macOS 12.0.1
    CPU: (8) x64 Apple M1
    Memory: 22.47 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.11.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Safari: 15.1
  npmPackages:
    next: ^12.0.7 => 12.0.7 
    next-auth: ^4.0.6 => 4.0.6 
    react: 17.0.2 => 17.0.2 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Please read the docs.

https://next-auth.js.org/getting-started/client
