### ISSUE TITLE
Adapter for Mongoose or GraphQL with v4

### ISSUE THREAD

**Issue by martinkr** [nextauthjs/next-auth#3542]
### Question 💬

Hi, 
I love next-auth and I used v3 in multiple projects. 
Recently I started a new one which will either use mongoose as ORM for MongoDB or GraphQL.
Unfortunately, there isn't an Adapter for either one and the mongoose adapter example (e.g. https://github.com/nextauthjs/next-auth/issues/1175)  from v3 are not working anymore. I'm struggling to set up the model ( basically because Adapters.TypeORM.Models.User.model is not available anymore).

Is there any chance to have a mongoose or GraphQL adapter or can you point me to a good resource how use next-auth with either of them?

Thank you in advance,

Martin 

### How to reproduce ☕️

n/a

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by choutkamartin** [comment]
Hi, please take a look at https://github.com/nextauthjs/adapters/pull/355 regarding the Mongoose adapter question.

The adapter in that PR takes in MongoDB URI and establishes a connection. However, there are some limitations. The adapter uses a separate connection instead of the one you would use in your application to avoid conflict between models. That means your app will establish two connections to the database: one for the adapter (and its models), one for your application (and its models). 

So, I'm not sure if it's even worth it to have a separate Mongoose adapter. Why? Because you can use MongoDB adapter. Simply establish the connection in `[...nextauth].js` like this and pass the connection to the MongoDB adapter:

```js
import NextAuth from "next-auth"
import { MongoDBAdapter } from "@next-auth/mongodb-adapter"
import { MongoClient } from "mongodb"

client = new MongoClient(process.env.MONGODB_URI);
clientPromise = client.connect();
export default NextAuth({
 adapter: MongoDBAdapter(clientPromise),
 ...
})
```

**Comment by balazsorban44** [comment]
In addition to the above, we have exhaustive documentation/examples on how to create your own adapter (which is objectively much easier than it was with v3)

See our docs on Adapters:

https://next-auth.js.org/adapters/overview

https://next-auth.js.org/tutorials/creating-a-database-adapter

Or see our official adapters for implementation details and how to test your adapter to be conformant: https://github.com/nextauthjs/adapters/tree/main/packages

**Comment by martinkr** [comment]
Thank you for pointing me into the right direction. ❤️

**Comment by huge689** [comment]
the official adapters exmaple is about mogodb, but how to do with mongoose?

**Comment by choutkamartin** [comment]
> the official adapters exmaple is about mogodb, but how to do with mongoose?

I explained it above. You can use MongoDB adapter, even though you are using Mongoose in your project.

**Comment by Tosinkoa** [comment]
Can you pls show us how to do that @choutkamartin

**Comment by martinkr** [comment]
`[...nextauth].js`  
> 
> ```js
> import NextAuth from "next-auth"
> import { MongoDBAdapter } from "@next-auth/mongodb-adapter"
> import { MongoClient } from "mongodb"
> 
> client = new MongoClient(process.env.MONGODB_URI);
> clientPromise = client.connect();
> 
> export default NextAuth({
>  adapter: MongoDBAdapter(clientPromise),
>  ...
> })
> ```
https://github.com/nextauthjs/next-auth/issues/3542#issuecomment-1003202402

**Comment by choutkamartin** [comment]
@martinkr How many connections does your application establish to the DB when running this code on `localhost`, or simply put `npm run dev`?

**Comment by martinkr** [comment]
Hey @choutkamartin

I was just copying the relevant code to answer your question. For an in-depth view please read the original issue about a Mongoose adapter and MongoDB at https://github.com/nextauthjs/adapters/pull/355 

Cheers,

Martin

**Comment by martinkr** [comment]
Hi @choutkamartin,

thank you for your interest.

I was using it but ultimately decided to store the session only in a JWT Token and add the relevant user-data to a custom collection leveaging th `signIn` callback. Using the [collections generated by next-auth](https://next-auth.js.org/adapters/models) was not necessary for my usecase.

Cheers

**Comment by Tosinkoa** [comment]
I think one can use a custom adapter to connect mongoose + mongodb with next-auth v4.

Can you recommend your example for me to use @choutkamartin

**Comment by Tosinkoa** [comment]
Tbh with you, I'm still learning. If you can make you explanation here https://www.npmjs.com/package/@choutkamartin/mongoose-adapter. more simpler, I will like to try it out. I checked the mongoose-adapter on npm too but it's having few download

**Comment by Tosinkoa** [comment]
Why is there no example for mongoose?

**Comment by choutkamartin** [comment]
> Why is there no example for mongoose?

Give me a few minutes. I will prepare an example for you.

**Comment by Tosinkoa** [comment]
Thanks so much @choutkamartin

**Comment by choutkamartin** [comment]
@Tosinkoa Take a look at https://github.com/choutkamartin/next-auth-mongoose

There's pretty much everything you need as an explanation.

**Comment by Tosinkoa** [comment]
Thanks so much @choutkamartin, I'm checking it out now

**Comment by Tosinkoa** [comment]
Thanks for creating this example @choutkamartin. But mongoose-adapter is still a new npm package, and for security reason( company/client I work for in future), I would like to learn something everyone is using for now.

**Comment by choutkamartin** [comment]
> Thanks for creating this example @choutkamartin. But mongoose-adapter is still a new npm package, and for security reason( company/client I work for in future), I would like to learn something everyone is using for now.

Of course it's new, because it's mine and I use it for my personal projects. I'm not telling you to use it. I'm saying, you can create your own adapter, until the PR for the Mongoose adapter gets merged. Or you can fork the adapter, so it isn't dependent on my _npm_ package.

But as I have already said, **you don't have to use the Mongoose adapter**. **You can use the MongoDB adapter**, as I have already wrote in the comments of the `[...nextauth].js` file and as already presented in the repository.

**Comment by Tosinkoa** [comment]
Okay great, I will check that out now
