### ISSUE TITLE
Discord Oauth Acess Token

### ISSUE THREAD

**Issue by AriaFantom** [nextauthjs/next-auth#3547]
### Description 🐜

I was using v3 of next auth without any problem but after the lastest update of v4 i did some changed according to the migration docs from the offical site, but then also after rewiting it many time it just show same error everytime there i need the next auth to have a look to it

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

[[...nextauth].txt](https://github.com/nextauthjs/next-auth/files/7797561/nextauth.txt)
Use my code to reproduce the issue
This is my current file after migrating this code occurs the issue mentioned below. I made many tries even removing things out. Nothing solved the issue

### Screenshots / Logs 📽

![image](https://user-images.githubusercontent.com/55119711/147848721-9c8a820c-37e7-49a7-b00d-f16a09439095.png)

`[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error access_token not present in TokenSet {
  error: {
    message: 'access_token not present in TokenSet',
    stack: 'TypeError: access_token not present in TokenSet\n' +
      '    at Client.requestResource (/home/askar/mysterious-dashboard/node_modules/openid-client/lib/client.js:1128:15)\n' +
      '    at Client.userinfo (/home/askar/mysterious-dashboard/node_modules/openid-client/lib/client.js:1246:33)\n' +
      '    at oAuthCallback (/home/askar/mysterious-dashboard/node_modules/next-auth/core/lib/oauth/callback.js:134:30)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
      '    at async Object.callback (/home/askar/mysterious-dashboard/node_modules/next-auth/core/routes/callback.js:50:11)\n' +
      '    at async NextAuthHandler (/home/askar/mysterious-dashboard/node_modules/next-auth/core/index.js:133:28)\n' +
      '    at async NextAuthNextHandler (/home/askar/mysterious-dashboard/node_modules/next-auth/next/index.js:20:19)\n' +
      '    at async /home/askar/mysterious-dashboard/node_modules/next-auth/next/index.js:56:32\n' +
      '    at async Object.apiResolver (/home/askar/mysterious-dashboard/node_modules/next/dist/server/api-utils.js:102:9)\n' +
      '    at async DevServer.handleApiRequest (/home/askar/mysterious-dashboard/node_modules/next/dist/server/next-server.js:1064:9)',
    name: 'TypeError'
  },
  providerId: 'discord',
  message: 'access_token not present in TokenSet'
}
[next-auth][error][CALLBACK_OAUTH_ERROR] 
https://next-auth.js.org/errors#callback_oauth_error access_token not present in TokenSet TypeError: access_token not present in TokenSet
    at Client.requestResource (/home/askar/mysterious-dashboard/node_modules/openid-client/lib/client.js:1128:15)
    at Client.userinfo (/home/askar/mysterious-dashboard/node_modules/openid-client/lib/client.js:1246:33)
    at oAuthCallback (/home/askar/mysterious-dashboard/node_modules/next-auth/core/lib/oauth/callback.js:134:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.callback (/home/askar/mysterious-dashboard/node_modules/next-auth/core/routes/callback.js:50:11)
    at async NextAuthHandler (/home/askar/mysterious-dashboard/node_modules/next-auth/core/index.js:133:28)
    at async NextAuthNextHandler (/home/askar/mysterious-dashboard/node_modules/next-auth/next/index.js:20:19)
    at async /home/askar/mysterious-dashboard/node_modules/next-auth/next/index.js:56:32
    at async Object.apiResolver (/home/askar/mysterious-dashboard/node_modules/next/dist/server/api-utils.js:102:9)
    at async DevServer.handleApiRequest (/home/askar/mysterious-dashboard/node_modules/next/dist/server/next-server.js:1064:9) {
  name: 'OAuthCallbackError',
  code: undefined
}`

### Environment 🖥

  System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 AMD Ryzen 5 3400G with Radeon Vega Graphics
    Memory: 3.52 GB / 6.74 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
  npmPackages:
    next: latest => 12.0.7 
    next-auth: ^4.0.6 => 4.0.6 
    react: ^17.0.2 => 17.0.2 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
There are multiple errors here, please read the migration docs more carefully:

1. scope has been moved from top-level
https://next-auth.js.org/getting-started/upgrade-v4#providers
https://next-auth.js.org/configuration/providers/oauth#authorization-option

2. you are using a jwt strategy meaning there is no `user` in session, your request to discord fails without an access token.
https://next-auth.js.org/configuration/callbacks#session-callback

3. `database` has been deprecated
https://next-auth.js.org/getting-started/upgrade-v4#adapters

**Comment by AriaFantom** [comment]
Can u please explain your point 2?

**Comment by balazsorban44** [comment]
Please see the attached link.

**Comment by AriaFantom** [comment]
```
import NextAuth from "next-auth";
import DiscordProviders from "next-auth/providers/discord";
import clientPromise from "../../../lib/mongo";
import { MongoDBAdapter } from "@next-auth/mongodb-adapter";
export default NextAuth({
  providers: [
    DiscordProviders({
      clientId: process.env.CLIENT_ID,
      clientSecret: process.env.CLIENT_SECRET,
      authorization: {
        params: { scope: "guilds identify email" },
      },
    }),
  ],
  adapter: MongoDBAdapter(clientPromise),
  session: {
    strategy: "database",
  },

  secret: "iamthebestdeveloperaskar",

  callbacks: {
    async session({ session }) {
      return session
    },

  },
});
```

Can tell me where i am going wrong now?

**Comment by AriaFantom** [comment]
Can u please reopen it or move to discussion??
