### ISSUE TITLE
Accessing Client Side Global State inside Callbacks/Events

### ISSUE THREAD

**Issue by sedhha** [nextauthjs/next-auth#3552]
### Description 📓

While performing next-auth `callbacks` or `events` we get data points about token and session. That is great but when one wants to build a big scalable application, a need for accessing the global state variables may arise. 

- Purpose of the feature
To enable accessing global state of client-side in next-auth callbacks and events
- Potential Problems
Limited accessibility of client-side variables (only coming from `Providers`)
- Potential Alternatives
None

For example, let's say I am accessing my user data from an OAuth client and geo Data from the client-side. I might store this data in my global state and later want to use it to push to a database or so or perform some manipulations at the server-side.

One can argue that since the session is available at the client-side and so one can access both session variable and global state at client side but ideally there are some operations that one might want to perform securely at the server-side without exposing anything at the client end.

So here's an example of feature that I am requesting:

let's say I store my geoData in the redux store and want to access it inside my `signIn` callback. So I should receive a global store prop as shown below:

```
async signIn({ user, account, store }) {        

/*
a store is the global state of client-side application
in case there's no global variables available at client side store can just remain an empty object: {}.
otherwise based on the global states, it can be: {reduxStore:{...},contextAPI:{...},...}
*/
const {geoLocation} = store.reduxStore.geoData;       // pushGeoDataToBQ(geoLocation); Pushes the Data to a database and not needed to be async as it can run in background and user gets their active session 

return true;     }
```

In case if there's no global state or store attached to a given application, the store can just be empty object `{}`. I think people would highly love this feature as this will make next-auth connect to the frontend flawlessly and passing variables from the frontend to the middleware/backend NEXT will be so smooth making it a full-stack framework in all aspects.

### How to reproduce ☕️

One can install the packages:

`npm install next-redux-wrapper react-redux --save`
`npm install next-auth`

And then try to access the global counter state into `/pages/api/auth/[...nextauth].ts`, inside login Callback or so.

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
The content of `[...nextauth].ts` is run in an API route, while the client runs on the user's computer. Unless I misunderstand, this request doesn't really make sense, as those are two different contexts.
