### ISSUE TITLE
Export custom sign in page for credentials provider

### ISSUE THREAD

**Issue by VibingCreator** [nextauthjs/next-auth#3558]
### Description 🐜

I am basically following the documentation's [example](https://next-auth.js.org/configuration/pages#credentials-sign-in) for a custom sign-in page for credentials provider and I have encountered weird issue trying to export the page. The only difference is the approach of exporting things.

```js
import { getCsrfToken } from "next-auth/react";

export default function CredentialsSignin({ csrfToken }) {
    return (
        <form method="post" action="/api/auth/callback/credentials">
            <input name="csrfToken" type="hidden" defaultValue={ csrfToken }/>
            <label>
                Username
                <input name="username" type="text"/>
            </label>
            <label>
                Password
                <input name="password" type="password"/>
            </label>
            <button type="submit">Sign in</button>
        </form>
    );
}

export async function getServerSideProps(context) {
    return {
        props: {
            csrfToken: await getCsrfToken(context)
        }
    };
}
```

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

/pages/api/auth/[...nextauth].js
```js
...
pages: {
        signIn: "/auth/credentials-signin"
    }
...
```
/pages/auth/credentials-signin.js
```js
import { getCsrfToken } from "next-auth/react";

const CredentialsSignin = async ({ csrfToken }) => {
    return (
        <form method="post" action="/api/auth/callback/credentials">
            <input name="csrfToken" type="hidden" defaultValue={ csrfToken }/>
            <label>
                Username
                <input name="username" type="text"/>
            </label>
            <label>
                Password
                <input name="password" type="password"/>
            </label>
            <button type="submit">Sign in</button>
        </form>
    );
};

const getServerSideProps = async (context) => {
    return {
        props: {
            csrfToken: await getCsrfToken(context)
        }
    };
};

export { CredentialsSignin as default, getServerSideProps };
```

### Screenshots / Logs 📽

![image](https://user-images.githubusercontent.com/72659331/147965719-766469c1-0365-4b09-a67a-0ae9ca533691.png)
![image](https://user-images.githubusercontent.com/72659331/147965596-a35e56cc-0606-495e-b964-00bb9b0a8db8.png)

### Environment 🖥

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-3612QM CPU @ 2.10GHz
    Memory: 2.23 GB / 7.86 GB
  Binaries:
    Node: 16.13.1 - D:\Software\nodejs\node.EXE
    npm: 8.1.2 - D:\Software\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.62)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    next: 12.0.7 => 12.0.7
    next-auth: ^4.0.6 => 4.0.6
    react: 17.0.2 => 17.0.2

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
The problem is this line:

`const CredentialsSignin = async ({ csrfToken }) => {`

React components are not async functions.
