### ISSUE TITLE
Unexpected JWT alg received

### ISSUE THREAD

**Issue by Kinbaum** [nextauthjs/next-auth#3559]
### Question 💬

Hello, I have been using Next Auth for quite some time now and I am upgrading from a v4 beta to the latest 4.0.6 version. After making the necessary adjustments mentioned in the release notes, I find myself stuck with the following error

```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error unexpected JWT alg received, expected RS256, got: HS512 {
  error: {
    message: 'unexpected JWT alg received, expected RS256, got: HS512',
    stack: 'RPError: unexpected JWT alg received, expected RS256, got: HS512\n' +
      '    at Client.validateJWT (/node_modules/openid-client/lib/client.js:901:13)\n' +
      '    at Client.validateIdToken (/node_modules/openid-client/lib/client.js:763:60)\n' +
      '    at Client.callback (/node_modules/openid-client/lib/client.js:484:18)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async oAuthCallback (/node_modules/next-auth/core/lib/oauth/callback.js:112:16)\n' +
      '    at async Object.callback (/node_modules/next-auth/core/routes/callback.js:50:11)\n' +
      '    at async NextAuthHandler (/node_modules/next-auth/core/index.js:133:28)\n' +
      '    at async NextAuthNextHandler (/node_modules/next-auth/next/index.js:20:19)\n' +
      '    at async /node_modules/next-auth/next/index.js:56:32',
    name: 'RPError'
  },
  providerId: 'custom',
  message: 'unexpected JWT alg received, expected RS256, got: HS512'
}
```

I have a custom provider set up and I have generated a JWT secret using jose. The secret I'm using looks something similar to this:

`{"kty":"oct","kid":"MkpQ3HZ_xKUg4PLzqV5AHSGuJw5G6tjB0BC-G5bqC3I","alg":"HS512","k":"-9NPYksCCnoynAHOpDkglFoRmlIi87ppyh7kFKlI0_zAoY2F6_P06t5OAJ1Zu6hU7RYqkwmAxxRa42_5S1KYAA"}`

My understanding is that the algorithm used to encode / decode the jwt should be derived from this secret, but it doesn't seem to have an effect. Can someone assist me with this?

### How to reproduce ☕️

It is not going to be possible for me to provide a reproduction scenario as this is an internal oauth provider, but I am able to show the configurations I have:

```js
// custom provider config
export const CustomProvider = {
    id: 'custom',
    name: 'Custom',
    type: 'oauth',
    version: '2.0',
    clientId: process.env.CUSTOM_CLIENT_ID,
    clientSecret: process.env.CUSTOM_CLIENT_SECRET,
    idToken: true,
    authorization: {
        url: process.env.CUSTOM_AUTHORIZATION_URL,
        params: JSON.parse(process.env.CUSTOM_AUTHORIZATION_PARAMS)
    },
    token: {
        url: process.env.CUSTOM_TOKEN_URL,
        params: {  
            grant_type: 'authorization_code'
        }
    },
    userinfo: {
        url: process.env.CUSTOM_PROFILE_URL
    },
    profile: profile => ({
        id: 'custom',
        ...profile
    })
};
```

```js
// nextauth file
export default NextAuth({
    debug: process.env.NODE_ENV !== 'production',
    providers: [ CustomProvider ],
    secret: process.env.SECRET,
    jwt: {
        maxAge: 60 * 30,
        secret: process.env.JWT_SECRET
    },
    callbacks: {
        async jwt({ token, profile }) {
            return token;
        },
        async session({ session, token }) {
            return session;
        }
    }
});
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
See https://github.com/nextauthjs/next-auth/issues/3560#issuecomment-1004470473

We actually derive the secret from the top-level `secret` option for everything now, so that should be enough.

**Comment by Kinbaum** [comment]
@balazsorban44 Unfortunately I'm still receiving the same error after setting the top-level secret. The value of the secret was generated using `jose newkey -s 512 -t oct -a HS512`

**Comment by Kinbaum** [comment]
@balazsorban44 The only way I've been able to get this working again is by specifying resolutions in my `package.json`

```json
"resolutions": {
    "openid-client": "5.0.2"
}
```

**Comment by Kinbaum** [comment]
`Update` I removed the resolutions and added a few additional properties to my custom provider. The following seems to allow this to work

```js
{
    // removed for brevity...
    idToken: true,
    issuer: process.env.CUSTOM_ISSUER,
    client: {
        authorization_signed_response_alg: 'HS512',
        id_token_signed_response_alg: 'HS512'
    }
}
```

**Comment by tyler5136** [comment]
To resolve this issue for myself I had to to enable self-signed-key in the OIDC.
