### ISSUE TITLE
add a credential signup page

### ISSUE THREAD

**Issue by redimongo** [nextauthjs/next-auth#3562]
### Description 📓

I am having issues, we have our users in our database already with our old react website we had made a custom signup page. but now that we have moved to NextJS we have integrated Next-Auth and added Credential login but now we have an issue that we don't have a signup page.

I know I could easily just add a /api/signup page and run it outside of next-auth but think it should be an included feature. Don't get me wrong Google and Twitter etc are cool plugins but we need to integrate our current users and people who don't want to link Facebook and Google to our site.

Any suggestions would be welcomed.

### How to reproduce ☕️
```
import NextAuth from "next-auth"
import CredentialsProvider from "next-auth/providers/credentials"
import jwt from "next-auth/jwt";

export default NextAuth({
    site:"localhost",
    providers: [
        CredentialsProvider({
          // The name to display on the sign in form (e.g. 'Sign in with...')
          name: 'DRN1',
          // The credentials is used to generate a suitable form on the sign in page.
          // You can specify whatever fields you are expecting to be submitted.
          // e.g. domain, username, password, 2FA token, etc.
          // You can pass any HTML attribute to the <input> tag through the object.
          credentials: {
            username: { label: "Username", type: "text", placeholder: "jsmith" },
            password: {  label: "Password", type: "password" }
          },
          async authorize(credentials, req) {
            // You need to provide your own logic here that takes the credentials
            // submitted and returns either a object representing a user or value
            // that is false/null if the credentials are invalid.
            // e.g. return { id: 1, name: 'J Smith', email: 'jsmith@example.com' }
            // You can also use the `req` object to obtain additional parameters
            // (i.e., the request IP address)
            const res = await fetch("/your/endpoint", {
              method: 'POST',
              body: JSON.stringify(credentials),
              headers: { "Content-Type": "application/json" }
            })
            const user = await res.json()
      
            // If no error and we have user data, return it
            if (res.ok && user) {
              return user
            }
            // Return null if user data could not be retrieved
            return null
          }
        })
      ]
});
```
### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
Adding a sign-up page is not planned. The Credentials Provider is intentionally the way it is, to discourage the use of it. See the docs: https://next-auth.js.org/providers/credentials

You will have to create your own sign-up page. Be careful to take necessary security measures, as that would be outside of `next-auth`

**Comment by bonavida** [comment]
@balazsorban44 No need to re-open the issue, but could you explain if there's any way to set the credentials into the next-auth session after a user signs up in the app?

I mean, creating a session when the user signs in with the Credentials Provider is straightforward (same as log out), but I don't know how to proceed when a user signs up and I want to create a session directly after that.

**Comment by HashemKhalifa** [comment]
@bonavida up for that!
