### ISSUE TITLE
Authorization with Instagram fails

### ISSUE THREAD

**Issue by georgekrax** [nextauthjs/next-auth#3564]
### Description 🐜

I try to use the `InstagramProvider`. After successfully signing in and redirecting back to the app, `next-auth` throws the `CALLBACK_OAUTH_ERROR` error. I guess it is from a callback function. The documentation addresses this:

> This can occur during the handling of the callback if the code_verifier cookie was not found or an invalid state was returned from the OAuth provider.

So, this must be an error inside the source code of `next-auth`? Or, am I doing something wrong?

Error message: **"checks.state argument is missing"**

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

My config:
```ts
InstagramProvider({
  clientId: process.env.INSTAGRAM_CLIENT_ID!, 
  clientSecret: process.env.INSTAGRAM_CLIENT_SECRET!,
}),
```

The error is thrown before the `signIn` event is called. After this `next-auth` redirects to `https://f6cf-2a02-587-4c5a-47c6-9917-47c5-aa60-eb3f.ngrok.io/api/auth/signin?error=OAuthCallback#_`

### Environment 🖥

System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx  
    Memory: 1.13 GB / 5.94 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\node_modules\.bin\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (96.0.1054.62)
    Internet Explorer: 11.0.22000.120

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth/pull/3381 might fix this, but the author wasn't responsive to the review. Feel free to have a look.

**Comment by georgekrax** [comment]
Okay, thank you. But, is this pull request and file changes going to solve the issue?

**Comment by balazsorban44** [comment]
I don't know if it would fix it, I said "might".

I had a comment on the PR, but the author did not respond. Until then, I cannot merge.

But please have a look, and experiment yourself. https://next-auth.js.org/configuration/providers/oauth and https://next-auth.js.org/providers/instagram#options should be helpful

**Comment by georgekrax** [comment]
Maybe create the same pull request and merge it?

**Comment by balazsorban44** [comment]
I cannot merge a PR until all the comments are resolved. Feel free to open a new one if you have managed to solve the issue. I can close the old PR in favor of yours if it works better.

**Comment by mamv2137** [comment]
I Have the same issue, any response or any suggestions about how to fix this error? I'm following this #3381 but I doesn't work

**Comment by georgekrax** [comment]
Unfortunately, I am not currently involved with software development. I would love to help but I cannot due to other obligations. Thought it would be nice of me to inform you.

**Comment by iketiunn** [comment]
> #3381

I can confirm that https://github.com/nextauthjs/next-auth/pull/3381 fix this.

All you have to do is paste the fixed snippet into your provider. The default behavior handling callback for Instagram might be changed.

It's my first time using nextauth.js. It's fantastic, but the error is not so obvious even if I turn on the `debug: true`.

**Comment by georgekrax** [comment]
@iketiunn So, now there is not an error thrown by using the solution at #3381?

**Comment by iketiunn** [comment]
> @iketiunn So, now there is not an error thrown by using the solution at #3381?

Yes, works perfectly. you guys can try it.

**Comment by iketiunn** [comment]
Found that when getting an access token from Instagram via `https://api.instagram.com/oauth/access_token` which did not respect the `client_id` and `client_secret `in the `Authorization` header.

After digging [node-openid-client](https://github.com/panva/node-openid-client/blob/main/docs/README.md#client-authentication-methods).
We can just set the client meta in `InstagramProvider` to send the `client_id` and `client_secret` in the post body like:
```js
InstagramProvider({
  clientId: process.env.INSTAGRAM_CLIENT_ID,
  clientSecret: process.env.INSTAGRAM_CLIENT_SECRET,
  client: {
    token_endpoint_auth_method: 'client_secret_post',
  },
}),
```

After adding the client meta I can also make the sign-in flow successful without https://github.com/nextauthjs/next-auth/pull/3381.
Maybe this should be added to the default setting of `InstagramProvider`?

**Comment by georgekrax** [comment]
Ok! Then I guess, I can close the issue.
