### ISSUE TITLE
signIn() button leads to ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by rvmelkonian** [nextauthjs/next-auth#3565]
### Question 💬

I'm pretty sure I've configured everything correctly. 
In my api/auth/[...nextauth].ts

```
import NextAuth from 'next-auth';
import TwitterProvider from 'next-auth/providers/twitter';

export default NextAuth({
    providers: [
        TwitterProvider({
            clientId: process.env.TWITTER_CLIENT_ID,
            clientSecret: process.env.TWITTER_CLIENT_SECRET
        })
    ],
})
```

In my twitter App settings callback URL: 
https://localhost:3000/api/auth/callback/twitter

In client i'm importing 
```
import { SessionProvider } from 'next-auth/react';
import { signIn } from 'next-auth/react';
```

When I click connect to twitter, it takes me through to a blank page prompting me to connect to twitter. After I click that I get 
![Screenshot 2022-01-04 at 19 43 11](https://user-images.githubusercontent.com/35300528/148114820-0376c91a-4d9e-4b37-be89-0fdd37a3bd30.png)

I am not sure what I may be missing here

### How to reproduce ☕️

The repo is public,

To login you login with Blocto wallet (not using next-auth for this)
Then once logged in go to dashboard and click 'Create Artist Account,' Button. Here is where we need the auth with twitter, to validate a user's identity. 

https://github.com/INFLOWMusic/inflow-app

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by rvmelkonian** [comment]
it was my erroneous https:localhost as opposed to http:localhost

**Comment by rafaelsmgomes** [comment]
I'm having the same issue, can you explain how you solved it?

**Comment by rvmelkonian** [comment]
Hey @rafaelsmgomes, in my case I had set the call back url in Twitter Dev Dashboard to a wrong url : https://localhost:3000/api/auth/callback/twitter, where is should have been http://
