### ISSUE TITLE
Export `defaultCookies` to make it easier to customize the cookie options

### ISSUE THREAD

**Issue by devrsi0n** [nextauthjs/next-auth#3568]
### Description 📓

Currently, we can't import `defaultCookies` from next-auth, because there is an error:
![image](https://user-images.githubusercontent.com/7880675/148226503-9282ddf2-76ac-460f-9680-693852a5b4b1.png)

I just want to change `sameSite` value from `lax` to `none` to support iframe usages, but I don't want to modify other options, so it would be better to export it to make it easier to customize. Further, can we merge user options deeply to make it complete free to customize without worrying about internal implementation details?

Thanks for your time. ❤️

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
This is an advanced option and is purposefully made harder to configure.

**Comment by devrsi0n** [comment]
@balazsorban44 Thank you for the update, I got your concern. Could you guide me how to fix this `cross-domain iframe cookie is not working` issue if you're familiar with this area? Thanks in advance!

**Comment by balazsorban44** [comment]
Not without context. But any cookie that would stretch to other domains might be risky.

I can only recall two similar situations mentioning such cookies or iframes:

https://github.com/nextauthjs/next-auth/issues/1664

https://github.com/nextauthjs/next-auth/issues/1305

They might be irrelevant though, I recommend searching through old issues and discussions first to see if they get you an idea.

But sharing your use case might make it easier to guess what a good solution could be.

**Comment by devrsi0n** [comment]
@balazsorban44 Thank you so much for the info. Basically, I have some iframe widgets embedded in other websites, there is a login popup window in these widgets, an iframe widget should be refreshed after user login, but it doesn't because cookie can only be sent with [sameSite='none'](https://stackoverflow.com/questions/45094712/iframe-not-reading-cookies-in-chrome). That's why I have to modify it.

**Comment by jrmyio** [comment]
Just ran into the same problem. I think what would to have at least: 
> Further, can we merge user options deeply to make it complete free to customize without worrying about internal implementation details?

Currently, changing a single cookie property means you have to copy all the defaults which are not exposed by next-auth.

**Comment by MattIPv4** [comment]
👋 @balazsorban44, any chance this could be reopened for consideration based on the above suggestion of exposing this within an internal namespace? I'm also in a situation where I need to set SameSite=none to allow iframes to embed our site, and having to duplicate all other settings from the default config by hand seems rather fragile.
