### ISSUE TITLE
Allow consumer to access a user object when using an adapter and still choosing to handle sessions with jwt strategy

### ISSUE THREAD

**Issue by AdaptingAFM** [nextauthjs/next-auth#3574]
### Description 📓

When choosing to store User's data in a external database through an adapter, one may choose to use JWT or the database itself to host the session tokens. If the consumer is hosting both the user's data and the session tokens in a database, the session callback receive the user object of the current session as a parameter. The library should only request of hosting the data in a database for passing the current User's data to the session callback. It should be independant of whatever the session is also being saved on a database.

### How to reproduce ☕️

```js
// [...nextauth.js]
export default NextAuth({
	adapter: MongoDBAdapter(clientPromise),
	session: { strategy: "jwt" },

	providers: [
		DiscordProvider({
			clientId: "clid",
			clientSecret: "secret",
		}),
	],
	callbacks: {
		async session({ session, user, token }) {
			// If session.stragey is "jwt", user will be undefined when using an adapter.
			return { expires: session.expires, user: { ...user } };
		},
	},
});

```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
You can use the `jwt` callback to extend the `session`, and is received through the `token` property, instead of `user`.

https://next-auth.js.org/configuration/callbacks#session-callback
