### ISSUE TITLE
signIn event not triggered in production

### ISSUE THREAD

**Issue by ikoichi** [nextauthjs/next-auth#3597]
### Description 🐜

Hi, I am trying to use the signIn event with Twitter Authentication.
I basically need to track an analytic event when a Sign In or Sign Up occurs.

Despite it working correctly on local, it seems not working on production with the web app deployed to Vercel Hosting.

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

This is the code I'm using

```
export default NextAuth({
  adapter: PrismaAdapter(prisma),
  providers: [
    Providers.Twitter({
      clientId: process.env.TWITTER_CLIENT_ID,
      clientSecret: process.env.TWITTER_CLIENT_SECRET,
    }),
  ],
  events: {
    async signIn(event: SignInEvent) {
      console.log(">>> signIn event", event)
    },
  },
})
```

On local I see the log, on Vercel not.

### Environment 🖥

System:
    OS: macOS 11.6.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 309.16 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 96.1.33.106
    Chrome: 97.0.4692.71
    Edge: 97.0.1072.55
    Firefox: 89.0.2
    Safari: 14.1.2
  npmPackages:
    next: 12 => 12.0.4 
    next-auth: ^3.29.0 => 3.29.0 
    react: ^17.0.2 => 17.0.2 

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
I can assure you this method is correctly invoked: https://github.com/nextauthjs/next-auth/blob/main/src/core/routes/callback.ts

This is most likely a user error, especially if it works locally. Maybe a misconfiguration of some environment variables.

Sidenote: I encourage you to upgrade to v4 https://next-auth.js.org/getting-started/upgrade-v4

**Comment by ikoichi** [comment]
Yeah, on Vercel it's really difficult to debug with no console, and also the tracking I put in place are not working.
This is very strange.
I could upgrade to v4, but I've some dependencies on the Prisma adapter.
I'll try! Thanks!

**Comment by balazsorban44** [comment]
What do you mean no console? I mean you have Function logs, both for `console.log` and any errors. https://vercel.com/docs/concepts/deployments/logs you can also integrate that with third-party logging services

**Comment by ikoichi** [comment]
Yes, I mean that on Function logs on Vercel I don't see the `console.log` message I added.
Also, I added tracking to a third-party service and it doesn't work as well.
So it really looks like on Vercel that event is not triggered 😔

I really don't know what else to try, as the code posted in the first comment is really straightforward.
I can try to upgrade to NextAuth v4.
