### ISSUE TITLE
Is next-auth using legacy google sign in or the new Sign In with Google (Google Identity)?

### ISSUE THREAD

**Issue by ashwinkhode** [nextauthjs/next-auth#3600]
### Question 💬

Hey, forgive me if its a noob question but I just discovered this article (https://developers.google.com/identity/gsi/web/guides/overview) and I wanted to know whether next-auth is using something like this or something entirely different for google authentication?

### How to reproduce ☕️

NA

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by choutkamartin** [comment]
Hi, no. Next Auth uses OAuth 2.0 protocol directly to get user data from Google. The project specified is a library that contains some finished components (such as Sign In With Google button, Google One Tap). These components take in some necessary information, such as GOOGLE_CLIENT_ID, and they authorize users with little to no setup required from you as a developer.

**Comment by balazsorban44** [comment]
In fact, we are using Google OpenID Connect: https://github.com/nextauthjs/next-auth/blob/main/src/providers/google.ts

https://developers.google.com/identity/protocols/oauth2/openid-connect
