### ISSUE TITLE
GoogleProvider type issue when using family and given name 

### ISSUE THREAD

**Issue by HT-Moh** [nextauthjs/next-auth#3603]
### Question 💬

Hi 
GoogleProvider type issue when using family and given name 

![image](https://user-images.githubusercontent.com/34759569/148930372-0fb11d48-791a-4785-92eb-34a02c1e193f.png)

### How to reproduce ☕️

simply enable good provider and family and given name 

```
```
 GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID || '',
      clientSecret: process.env.GOOGLE_CLIENT_SECRET || '',
      profile: (_profile) => {
        return {
          id: _profile.sub,
          firstName: _profile.family_name,
          lastName: _profile.given_name,
          email: _profile.email,
          name: _profile.name,
        }
      },
      // authorization: {
      //   params: {
      //     prompt: 'consent',
      //     access_type: 'offline',
      //     response_type: 'code'
      //   }
      // }
    }),
```

```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth/blob/82447f8e3ebc7004cf91121725b4f5970d2276d8/src/providers/google.ts#L3

You can open a PR to extend the Profile interface for Google.
