### ISSUE TITLE
`getSession` outside of `SessionProvider` ignores `basePath`

### ISSUE THREAD

**Issue by saevarb** [nextauthjs/next-auth#3605]
### Description 🐜

When using `getSession` inside `getInitialProps` for the `_app` component, as described [here](https://next-auth.js.org/getting-started/client#sessionprovider), and when also using `basePath` in `SessionProvider`, then `getSession` does not know about the `basePath` and will make requests to the wrong URL.

From looking at the code, this seems to be because `SessionProvider` modifies some global `__NEXTAUTH` state, which then gets used by `fetchData` inside `getSession`, and since the `SessionProvider` hasn't been rendered it can't possibly have the correct `basePath`. 

It would be nice to be able to pass this information directly to `getSession` yourself or, better yet, not have to make an actual API request round-trip to get the session data and instead be able to execute the actual session-getting logic directly instead. 

The way I got around this was by doing the `fetch` myself using the `NEXTAUTH_URL` because it also has to include the `basePath` already.

```ts
  const base = process.env.NEXTAUTH_URL ?? `http://localhost:3000/api/auth/session`;
  const res = await fetch(`${base}/session`, {
    headers: appContext.ctx.req?.headers as HeadersInit,
  });
  const session = await res.json();
```

### Is this a bug in your own project?

No

### How to reproduce ☕️

Use `SessionProvider` with `basePath` inside `_app`. Use `getSession` inside `getInitialProps` for `_app`. Observe that it makes requests to the wrong endpoint(without the `basePath`). 

### Environment 🖥

```
  System:
    OS: Linux 5.15 Arch Linux
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 2.87 GB / 31.09 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  npmPackages:
    next: ^12.0.0 => 12.0.0 
    next-auth: ^4.1.0 => 4.1.0 
    react: ^17.0.2 => 17.0.2 

```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
This is being worked on, and there is currently an undocumented `import {getServerSession} from "next-auth/next"` method that avoids this roundtrip. 

See https://github.com/nextauthjs/next-auth/issues/1535#issuecomment-931785322 for more info.

Otherwise, you can just make the fetch call yourself to the correct endpoint for now.

**Comment by saevarb** [comment]
Okay, good to hear this is being worked on. But where is the issue? The issue you linked to doesn't mention this at all, and I was unable to find any other issue mentioning this, and now you just closed this issue, even though it is a genuine bug. So the next time someone runs into the same issue, they might find this and think it is solved because you closed it.

**Comment by saevarb** [comment]
Hello @balazsorban44 Can you link me to the correct issue so I can keep track of how it's going? Since you closed this issue I'm assuming there is another issue for this bug somewhere.

**Comment by apiel** [comment]
We are confronted to the same issue...
