### ISSUE TITLE
Client API: Expose a method for revalidating/reloading the session.

### ISSUE THREAD

**Issue by AdaptingAFM** [nextauthjs/next-auth#3622]
### Description 📓

Currently, whenever the window re-gains focus, session's handled by the client api are revalidated. It would be handy to have a method with which we can request the library to revalidate the current session; implementation could be similar to SWR's conditional fetching, or by adding a method in the useSession hook. 

### How to reproduce ☕️

//

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
https://next-auth.js.org/getting-started/client#refetch-interval

**Comment by dasveloper** [comment]
@balazsorban44 I don't think the close reason satisfies this request. OP (and I) are looking for an imperative way to refetch the session. If I make an API call to update the User and need to display the updated data on page I can't just wait for X seconds for the refetch interval to trigger. I could build my own session management with SWR [like in the docs](https://next-auth.js.org/getting-started/client#nextauthjs--react-query) but wouldn't like to rebuild the wheel just for a refresh/mutate.
