### ISSUE TITLE
Sign in with X when X is a Keycloak string or another brandable oidc provider.

### ISSUE THREAD

**Issue by ericbets** [nextauthjs/next-auth#3630]
### Description 📓

Keycloak and the others of its ilk allow brandable signin. So the string  "Signin with Keycloak" is a bit user unfriendly because it requires tech knowledge that we are using keycloak underneath.

This is a request for KEYCLOAK_TITLE= MyWebsite so that you get:
Signin with MyWebsite 

when you are using Keycloak et al with next-auth.

### How to reproduce ☕️

Click Sign in and get the next-auth provider menu.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
https://next-auth.js.org/providers/keycloak#options
