### ISSUE TITLE
Avoid storing plain-text email

### ISSUE THREAD

**Issue by eric-burel** [nextauthjs/next-auth#3645]
### Question 💬

We recently figured that storing plain-text email just for the purpose of authentication is probably a bad default.

As most auth-related workflow will ask you to type your email anyway, we only need to store a hashed version of said email address in the app database.

How is this handled in next-auth? Is not storing the plain email (or not storing it at all eg for passwordless auth?) the default?

I've checked the Email provider https://next-auth.js.org/providers/email and Credentials  https://next-auth.js.org/providers/credentials but found no answer

### How to reproduce ☕️

No repro here just a question

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
When using no database (`strategy: "jwt"`, or no Adapter defined), the e-mail is never stored, and the Email provider just won't work.

The Credentials provider explicitly only works with this strategy to discourage users from implementing their own auth solutions.

When using the E-mail provider, a temporary `VerificationToken` entry is created in the database, that will hold the `identifier` and a hashed `token`, in addition to an `expires` date field.

When clicking a link in the e-mail, the `token` from the URL is hashed, and in combination with the `identifier`, it is looked up from the database and **immediately deleted** (one-time use). So it is only saved for a short time period. The default is 1 day, but it can be overridden by passing `maxAge: number` (seconds) to the Email provider config:

https://github.com/nextauthjs/next-auth/blob/aa0e8200b3ca5de2ecbef26bb1740490326e5f33/src/providers/email.ts#L13-L18

This is mentioned here https://next-auth.js.org/adapters/models#verification-token and here https://next-auth.js.org/configuration/providers/email#options

With any other Provider and `strategy: "database"`, the user e-mail is saved on the `User` entry and the corresponding `Account`.

It is debatable if we should hash the ENTIRE database by default to save any kind of data, but it can certainly be done [through a custom adapter](https://next-auth.js.org/tutorials/creating-a-database-adapter). A fair amount of implemented examples are available at the adapters repo: https://github.com/nextauthjs/adapters/tree/main/packages

Hope this helps.

If you think this explains something better than the docs, please open a PR with your suggestions against https://github.com/nextauthjs/docs/tree/main/docs :pray:
