### ISSUE TITLE
cannot install use 'yarn add'

### ISSUE THREAD

**Issue by zereight** [nextauthjs/next-auth#3664]
### Description 🐜

When i install "yarn", node version error occurred

### Is this a bug in your own project?

No

### How to reproduce ☕️

`yarn add next-auth`

### Screenshots / Logs 📽

<img width="350" alt="스크린샷 2022-01-19 오전 1 41 51" src="https://user-images.githubusercontent.com/42544600/149980160-b79416cc-e313-426e-8f22-c9638edc0f64.png">

### Environment 🖥

node version 17.3.0

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
Read the message. Unsupported Node.js version. You are probably fine though (at your own risk of breaking something the future), just Google "How to ignore incompatible engine "node"
