### ISSUE TITLE
Type the error message

### ISSUE THREAD

**Issue by RaenonX** [nextauthjs/next-auth#3665]
### Question 💬

It seems that the error messages are not typed. If we could have typed errors, it could further improve customizations.

> According to what I found here: https://github.com/nextauthjs/next-auth/blob/82447f8e3ebc7004cf91121725b4f5970d2276d8/src/core/pages/signin.tsx#L42

An example I can think of is:

```typescript
export type ErrorType = 
  'SignIn' | 
  'OAuthSignin'
```

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
You are free to work on this, please send a PR!

**Comment by RaenonX** [comment]
> You are free to work on this, please send a PR!

Hi, thanks for the quick response! I would like to, however, I may not be able to do so. I can work on this if I have time. Otherwise, if someone has time, feel free to take on this :)

**Comment by norbitrial** [comment]
👋 I have [opened a PR](https://github.com/nextauthjs/next-auth/pull/3740) above for adding the necessary type for `error` prop of `<SigninPage />` component.

Let me know if anything else should be added there, thanks! 🙇 👍
