### ISSUE TITLE
Check session/token in external like express

### ISSUE THREAD

**Issue by lavcraft** [nextauthjs/next-auth#3695]
### Description 📓

Hello. I have a simple case with separated frontend and backend

1. While using next.js app we have a session by getSession on client side and server side
2. But in my separate backend (express for example) i can't get session or token via `import {getToken, getSession}` from `next-auht/react`

**What is the right way for achieve session/token validation in external projects based on express?**

### How to reproduce ☕️

1. Create two projects located in one domain 
example.com - ui based on next.js
example.com/bff - backend based on express
2. Try to shared session/token check logic between this projects based on next-auth package

I try to convert express req to next.js via next function:

```typescript
type RequestParamType = Parameters<RequestHandler>[0];
export function convertExpressToNextRequest(req: RequestParamType): NextApiRequest {
    // @ts-ignore
    return {
        ...req,
        query: {},
        headers: req.headers,
        cookies: req.cookies,
        body: req.body,
        env: {},
        aborted: false,
        httpVersion: req.httpVersion,
        httpVersionMajor: req.httpVersionMajor,
        httpVersionMinor: req.httpVersionMinor,
    }
}
```

And use `getSession({req})` and `getToken({req})` functions

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
For increased security and simplicity, we started not recommending the use of NextAuth.js JWT outside the app. You should use the access token generated by the provider of your choice in third-party services instead.

**Comment by lavcraft** [comment]
@balazsorban44 Thanks for your answer. I'm understand it, but it two different parts of one app and i want to share auth code between two modules of one app (backend and frontend).

Now i achieve this with `decode` function from `next-auth/jwt.
