### ISSUE TITLE
Failed to login with Facebook. It thrown this message `expected 200 OK, got: 400 Bad Request`

### ISSUE THREAD

**Issue by aptarmy** [nextauthjs/next-auth#3711]
### Description 🐜

Logging in with other providers like Google, or Line is working fine, but it's not working when logging in with Facebook using developer account. It always throws this error message `expected 200 OK, got: 400 Bad Request` and the frontend says `Try signing in with different account.`

### Is this a bug in your own project?

No

### How to reproduce ☕️

1. Clone this official Github repo [https://github.com/nextauthjs/next-auth-example](https://github.com/nextauthjs/next-auth-example)
2. Follow instruction in the repo to setup the app
3. Create a new facebook app in [developers.facebook.com](developers.facebook.com)
4. Fill up `FACEBOOK_ID` and `FACEBOOK_SECRET` in `.env.local`
5. Run the app and test Facebook login using your developer account used to create Facebook app

### Screenshots / Logs 📽

This is the error message I got from bash console.
```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error expected 200 OK, got: 400 Bad Request {
  error: {
    message: 'expected 200 OK, got: 400 Bad Request',
    stack: 'OPError: expected 200 OK, got: 400 Bad Request\n' +
      '    at processResponse (/home/user/tmp/next-auth-example/node_modules/openid-client/lib/helpers/process_response.js:41:11)\n' +
      '    at Client.grant (/home/user/tmp/next-auth-example/node_modules/openid-client/lib/client.js:1340:22)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async Client.oauthCallback (/home/user/tmp/next-auth-example/node_modules/openid-client/lib/client.js:612:24)\n' +
      '    at async oAuthCallback (/home/user/tmp/next-auth-example/node_modules/next-auth/core/lib/oauth/callback.js:114:16)\n' +
      '    at async Object.callback (/home/user/tmp/next-auth-example/node_modules/next-auth/core/routes/callback.js:50:11)\n' +
      '    at async NextAuthHandler (/home/user/tmp/next-auth-example/node_modules/next-auth/core/index.js:139:28)\n' +
      '    at async NextAuthNextHandler (/home/user/tmp/next-auth-example/node_modules/next-auth/next/index.js:20:19)\n' +
      '    at async /home/user/tmp/next-auth-example/node_modules/next-auth/next/index.js:56:32\n' +
      '    at async Object.apiResolver (/home/user/tmp/next-auth-example/node_modules/next/dist/server/api-utils.js:102:9)',
    name: 'OPError'
  },
  providerId: 'facebook',
  message: 'expected 200 OK, got: 400 Bad Request'
}
[next-auth][error][CALLBACK_OAUTH_ERROR] 
https://next-auth.js.org/errors#callback_oauth_error expected 200 OK, got: 400 Bad Request OPError: expected 200 OK, got: 400 Bad Request
    at processResponse (/home/user/tmp/next-auth-example/node_modules/openid-client/lib/helpers/process_response.js:41:11)
    at Client.grant (/home/user/tmp/next-auth-example/node_modules/openid-client/lib/client.js:1340:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.oauthCallback (/home/user/tmp/next-auth-example/node_modules/openid-client/lib/client.js:612:24)
    at async oAuthCallback (/home/user/tmp/next-auth-example/node_modules/next-auth/core/lib/oauth/callback.js:114:16)
    at async Object.callback (/home/user/tmp/next-auth-example/node_modules/next-auth/core/routes/callback.js:50:11)
    at async NextAuthHandler (/home/user/tmp/next-auth-example/node_modules/next-auth/core/index.js:139:28)
    at async NextAuthNextHandler (/home/user/tmp/next-auth-example/node_modules/next-auth/next/index.js:20:19)
    at async /home/user/tmp/next-auth-example/node_modules/next-auth/next/index.js:56:32
    at async Object.apiResolver (/home/user/tmp/next-auth-example/node_modules/next/dist/server/api-utils.js:102:9) {
  name: 'OAuthCallbackError',
  code: undefined
}
```

This is the screenshot of frontend after logging in with Facebook
![Screenshot from 2022-01-23 13-46-43](https://user-images.githubusercontent.com/6024196/150668177-5557e6d6-20f3-4104-8b12-9870892423ee.png)

### Environment 🖥

```
  System:
    OS: Linux 5.4 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (2) x64 AMD A4-9125 RADEON R3, 4 COMPUTE CORES 2C+2G
    Memory: 205.46 MB / 3.30 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 16.13.2 - /usr/bin/node
    npm: 8.1.2 - /usr/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Firefox: 96.0
  npmPackages:
    next: latest => 12.0.8 
    next-auth: latest => 4.1.2 
    react: ^17.0.2 => 17.0.2 
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by jhwang09** [comment]
I'm getting the exact same issue here

**Comment by devwasik** [comment]
I should have checked here first. Been struggling with this issue with all day.

**Comment by devwasik** [comment]
Seeing the same issue.

**Comment by viperxeyes** [comment]
Same issue here

**Comment by luisrudge** [comment]
## What Next.js Auth is using:
![image](https://user-images.githubusercontent.com/941075/150863812-440d6597-118c-4f27-b11c-5a63ae6a4632.png)

## What new Facebook apps require
![image](https://user-images.githubusercontent.com/941075/150863837-4b63dd85-b517-4c08-aeed-93b621ed7c79.png)

Code in question: https://github.com/nextauthjs/next-auth/blob/main/src/providers/facebook.ts#L15

I think next.js auth is using an old version of the protocol.

**Comment by jde** [comment]
After months of stability, I've started getting this same error on Monday, Jan 24th 2022. 

I've tried manually setting the api version from 11 to 12, and even creating a new facebook app to connect to but still receive:

```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error expected 200 OK, got: 400 Bad Request {
  error: {
    message: 'expected 200 OK, got: 400 Bad Request',
    stack: 'OPError: expected 200 OK, got: 400 Bad Request\n' +
      '    at processResponse (/Users/jde/dev/github/jde/rolldeep/node_modules/openid-client/lib/helpers/process_response.js:41:11)\n' +
      '    at Client.grant (/Users/jde/dev/github/jde/rolldeep/node_modules/openid-client/lib/client.js:1338:22)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async Client.oauthCallback (/Users/jde/dev/github/jde/rolldeep/node_modules/openid-client/lib/client.js:610:24)\n' +
      '    at async oAuthCallback (/Users/jde/dev/github/jde/rolldeep/node_modules/next-auth/core/lib/oauth/callback.js:114:16)\n' +
      '    at async Object.callback (/Users/jde/dev/github/jde/rolldeep/node_modules/next-auth/core/routes/callback.js:50:11)\n' +
      '    at async NextAuthHandler (/Users/jde/dev/github/jde/rolldeep/node_modules/next-auth/core/index.js:133:28)\n' +
      '    at async NextAuthNextHandler (/Users/jde/dev/github/jde/rolldeep/node_modules/next-auth/next/index.js:20:19)\n' +
      '    at async /Users/jde/dev/github/jde/rolldeep/node_modules/next-auth/next/index.js:56:32\n' +
      '    at async Object.apiResolver (/Users/jde/dev/github/jde/rolldeep/node_modules/next/dist/server/api-utils.js:102:9)',
    name: 'OPError'
  },
  providerId: 'facebook',
  message: 'expected 200 OK, got: 400 Bad Request'
}
[next-auth][error][CALLBACK_OAUTH_ERROR] 
https://next-auth.js.org/errors#callback_oauth_error expected 200 OK, got: 400 Bad Request OPError: expected 200 OK, got: 400 Bad Request
    at processResponse (/Users/jde/dev/github/jde/rolldeep/node_modules/openid-client/lib/helpers/process_response.js:41:11)
    at Client.grant (/Users/jde/dev/github/jde/rolldeep/node_modules/openid-client/lib/client.js:1338:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.oauthCallback (/Users/jde/dev/github/jde/rolldeep/node_modules/openid-client/lib/client.js:610:24)
    at async oAuthCallback (/Users/jde/dev/github/jde/rolldeep/node_modules/next-auth/core/lib/oauth/callback.js:114:16)
    at async Object.callback (/Users/jde/dev/github/jde/rolldeep/node_modules/next-auth/core/routes/callback.js:50:11)
    at async NextAuthHandler (/Users/jde/dev/github/jde/rolldeep/node_modules/next-auth/core/index.js:133:28)
    at async NextAuthNextHandler (/Users/jde/dev/github/jde/rolldeep/node_modules/next-auth/next/index.js:20:19)
    at async /Users/jde/dev/github/jde/rolldeep/node_modules/next-auth/next/index.js:56:32
    at async Object.apiResolver (/Users/jde/dev/github/jde/rolldeep/node_modules/next/dist/server/api-utils.js:102:9) {
  name: 'OAuthCallbackError',
  code: undefined
}
```

Any help would be greatly appreciated!

At this point my app is dead in the water and without any ability to reason about the issue I may have to switch authentication frameworks.

**Comment by jde** [comment]
> I think next.js auth is using an old version of the protocol.

I caught that as well, but updating the version in this file did not fix the issue. It does change the url the request is making, but the result is the same.

**Comment by luisrudge** [comment]
Yeah, but I guess that's expected. The endpoint changed, so it's likely sending a payload that works with 11 but not with 12

**Comment by jde** [comment]
> Yeah, but I guess that's expected. The endpoint changed, so it's likely sending a payload that works with 11 but not with 12

True. This is still the leading explanation for the issue then. In my Facebook app settings it does not allow me to choose v11 (only v12), which is a bit frustrating. They support back to v5, so not being able to choose the last version is painful.

**Comment by aptarmy** [comment]
> At this point my app is dead in the water and I'm facing costly delays and personal embarrassment.

I feel your pain. Creating apps is hard, but seeing it drowning is even harder.

I just got some ideas. I tried using Facebook SDK v12.0 (official client side library) and it's working fine where I can receive Facebook ID Token and call subsequent Graph API requests using the token.

You can try this workaround, while waiting updates from the author.

You can create `Custom Credential Provider` (learn more about this at this link [Credentials Provider](https://next-auth.js.org/providers/credentials)) to verify Facebook token and get user data from Graph API to log user in, and create custom login page ([follow this official tutorial](https://next-auth.js.org/configuration/pages#examples)) to manually place Facebook login button (JavaScript login) using [Facebook SDK](https://developers.facebook.com/docs/javascript/quickstart). Then when user clicks on Facebook login button, you get their Facebook token which you will send to your custom `Credentials Provider` to verify the token and log the user in. So the flow will look like this:

user **->** login page **->** click your facebook login button **->** you get token (client side) **->** send token to custom credentials provider **->** verify token **->** get user data from Graph API **->** log the user in **->** Next session is stored in browser

Hope it helps you and many others.

**Comment by balazsorban44** [comment]
Thanks everyone, I did not realize that there was a new API version and that the old one would break..

I found that Facebook seemingly supports OIDC which would be the way forward for us, if it actually works.

https://developers.facebook.com/docs/facebook-login/limited-login/token/

Although I'm not sure why they call it "Limited Login"...

I'll have a look at the new API and what has changed when I have the time, but you can try messing with the config until it works. Please follow our docs:

https://next-auth.js.org/providers/facebook#options

https://next-auth.js.org/configuration/providers/oauth

**Comment by gkielwasser** [comment]
Hi,

I hope it can help. I'm also having this issue since few days but only in a local environment. My production env has not stopped working.

I'm not using `nextauthjs` for this but I'm using the same under library `openid-cient`

I also receive such an error `expected 200 OK, got: 400 Bad Request` But some more information can be found on the response header Facebook returns.
You can put a breakpoint in `openid-client` to check if you have the same error header.

Here is mine `OAuth "Facebook Platform" "redirect_uri_mismatch" "URL kann nicht geladen werden: Die Domain dieser URL ist nicht in den Domains der App vorhanden. Um diese URL laden zu kÃ¶nnen, fÃ¼ge alle Domains und Subdomains deiner App im Appdomain-Feld in deinen App-Einstellungen hinzu."`

The response header returned by Facebook is `www-authenticate`. In my case it complains about my allowed domains.

You can put a breakpoint on [this line](https://github.com/panva/node-openid-client/blob/5120a076d0b5b24b9ebd0dcdb8b40d4dfcd535a3/lib/client.js#L1340) and inspect the response.

My Facebook test application is configured to work for localhost domain and it has stopped suddently working.

As for now I can only imagine `localhost` domains has been dropped or need to be configured a different way.

**Comment by d3v4nt** [comment]
having the same issue did anyone found any solution yet?

**Comment by larrysharette** [comment]
It looks like it's only an issue with local development. And looking through the documentation the only guess I have is that the params passed to the `access_token` endpoint have changed. It looks like it requires `client_id`, `client_secret`, `redirect_uri`, and `code`. However, when I updated the `token.params` field in the `FacebookProvider` with these values it still doesn't work.

I even manually built a url with all the parameters that they require and I still got an error from Facebook. The error code was 191 which talks about unauthorized domains but it says they should auto-accept localhost. I have no idea because same code works in production 🤷‍♂️

**Comment by d3v4nt** [comment]
Yep, confirmed it works on not local environments

**Comment by viperxeyes** [comment]
UPDATE : as of now I think Facebook is allowing localhost again now , the issue has been resolved and I was able to login normally with Facebook using local host , didn't change anything to my existing configuration.

**Comment by larrysharette** [comment]
Confirmed, it is working for me now. Like @viperxeyes said, no changes needed. It was definitely on Facebook's side

**Comment by gkielwasser** [comment]
> Confirmed, it is working for me now. Like @viperxeyes said, no changes needed. It was definitely on Facebook's side

same

**Comment by balazsorban44** [comment]
Oh, well. it sounds like there is nothing to do for us after all. 🎉

**Comment by Sina-Salahshour** [comment]
I'm getting the same error. i can't change the API to v11. the only available API is v13.

**Comment by Linuhusainnk** [comment]
What was the solution am facing this issue when reintegrating (moving to new app in facebook with old code)

**Comment by dacs30** [comment]
Does anyone ever have the same issue but with Instagram? I am facing that right now.
