### ISSUE TITLE
Unsupported engine

### ISSUE THREAD

**Issue by kailoon** [nextauthjs/next-auth#3715]
### Description 🐜

I am getting the logs below when installing next-auth ^4.1.2 on next 12.0.8.

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

run `npm install next-auth@latest`

### Screenshots / Logs 📽

```
npm i next-auth@latestnpm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'next-auth@4.1.2',
npm WARN EBADENGINE   required: { node: '^12.19.0 || ^14.15.0 || ^16.13.0' },
npm WARN EBADENGINE   current: { node: 'v17.3.1', npm: '8.3.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'openid-client@5.1.2',
npm WARN EBADENGINE   required: { node: '^12.19.0 || ^14.15.0 || ^16.13.0' },
npm WARN EBADENGINE   current: { node: 'v17.3.1', npm: '8.3.0' }
npm WARN EBADENGINE }
```

### Environment 🖥

System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 373.56 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.3.1 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Safari: 15.2
  npmPackages:
    next: 12.0.8 => 12.0.8 
    next-auth: ^4.1.2 => 4.1.2 
    react: 17.0.2 => 17.0.2

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by mrxbox98** [comment]
You need to be using a supported NodeJS version. Download the LTS Node 16 build from https://nodejs.org/en/.

**Comment by ConsoleTVs** [comment]
Short answer, it does not support the current node release XDDD (been out since 2021-10-19)

**Comment by laurenzhonauer** [comment]
Long answer would be nice. Which node version *is* supported?

**Comment by kailoon** [comment]
> You need to be using a supported NodeJS version. Download the LTS Node 16 build from https://nodejs.org/en/.

Thanks! I switch to node 16, it works.

**Comment by balazsorban44** [comment]
This has also been asked multiple times. Before opening a new issue, I highly recommend doing a search in old issues/discussions. For first contributors, see this video on how to help maintainers: https://www.youtube.com/watch?v=cuoNzXFLitc

**Comment by kailoon** [comment]
> This has also been asked multiple times. Before opening a new issue, I highly recommend doing a search in old issues/discussions. For first contributors, see this video on how to help maintainers: https://www.youtube.com/watch?v=cuoNzXFLitc

I did. But maybe I use the wrong keyword, I get no result.

**Comment by nkkky** [comment]
can it please be workable for node v.19.0.0 or v.19.2.0? really sad i need to downgrade.
