### ISSUE TITLE
getToken returns next-auth issued JWT? - can I get my provider issued JWT instead

### ISSUE THREAD

**Issue by colin-riddell** [nextauthjs/next-auth#3719]
### Question 💬

Hello people of NextAuth. 

Loving the library so far, though I've been quite confused with the api side `getToken()` call. My understanding after doing some digging is that it's getting a JWT that next-auth has issued? I actually don't want that.. 

I want the JWT access token that my auth provider (in my case cognito) has issued, so that I can use it in a back-end API call, to my other non-next API which is acting as my oauth resource server I want to do that in next api back-end. So something along the lines of:

```typescript
// /api/someroute.ts

import { getToken } from "next-auth/jwt";

const getJwt = async (req: NextApiRequest) => {
  return await getToken({ req, secret, raw: true });  // doesn't work without raw: true for some reason?
};

export default async function handler(req: NextApiRequest, res: NextApiResponse) {

  const accessToken = await getJwt(req);

  if (req.method === "POST") {
    fetch("http://non-next-service", headers: { "Authorization": `Bearer ${accessToken}`})
     //etc
  }
}
```

Upon logging in next-auth spits out some profile  and account details to the terminal including `id_token`, `access_token` and `refresh_token`. Using the `access_token` in POSTman to call my resource server works perfectly! But it's clearly not the same token that's coming from `getToken()`.

I've read about the callback options in the next-auth config and see there's a callback for `jwt` and `session`. It's not that clear to me what they're useful for, or how it's connected to what happens with `getToken`.

Looking through other issues and the example project I can't honestly see what I'm doing wrong.

Any help or pointers greatly appreciated.

### How to reproduce ☕️

```typescript
// /api/someroute.ts

import { getToken } from "next-auth/jwt";

const getJwt = async (req: NextApiRequest) => {
  return await getToken({ req, secret, raw: true });  // doesn't work without raw: true for some reason?
};

export default async function handler(req: NextApiRequest, res: NextApiResponse) {

  const accessToken = await getJwt(req);

  if (req.method === "POST") {
    fetch("http://non-next-service", headers: { "Authorization": `Bearer ${accessToken}`})
     //etc
  }
}
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by colin-riddell** [comment]
I figured it out. Though it would be nice to hear if it's an ok solution:

To get the providers access token on the server side one must first modify the session object with the callback hooks by `jwt` and `session` like so:

`[...nextauth].ts/js`:
```javascript
 callbacks: {
    async jwt({ token, account }) {
      if (account) {
        token.accessToken = account.access_token;
      }
      return token;
    },
    async session({ session, token, user }) {
      session.accessToken = token.accessToken;
      return session;
    },
  },

```

Then, from a server side route/page you can use `getSession` to get the session object, and then the access token:


`/api/someroute.ts`
```typescript
import { getSession } from "next-auth/react";  // admit I don't understand why this works on server side

const getAccessToken = async (req: NextApiRequest) => {
  const session = await getSession({ req });
  return session?.accessToken;
};

```

**Comment by balazsorban44** [comment]
https://next-auth.js.org/getting-started/example#extensibility

**Comment by ewermor** [comment]
In my case, the access token is always a JWE

**Comment by dion-blutui** [comment]
@colin-riddell wont this allow the `accessToken` to exposed on the client?

**Comment by HBLAB-TruongTT** [comment]
it will not make any sense if you put access token to session

**Comment by cirex-web** [comment]
@dpirad007 +1. I was wondering if there was a way to get the access token (and refresh it if needed) server-side without exposing it in `session`

**Comment by dion-blutui** [comment]
@cirex-web I currently store the access token in the JWT (Auth.js stores an encrypted [JWT](https://authjs.dev/concepts/session-strategies#jwt-session) ) it can be called by the `getToken` method from `next-auth/jwt`.

Also I have to use it in a weird way due to type error (can't find the issue link though)
```js
  const token = await getToken({
    req,
    secret: process.env.AUTH_SECRET!,
    secureCookie: process.env.NODE_ENV === "production",
    salt:
      process.env.NODE_ENV === "production"
        ? "__Secure-authjs.session-token"
        : "authjs.session-token",
  });
  ```

**Comment by TorosyanV** [comment]
would be nice to include @colin-riddell example in the documentation as its real life scenario.
