### ISSUE TITLE
MongoDB Adapter

### ISSUE THREAD

**Issue by MihaiWill** [nextauthjs/next-auth#372]
Hi!
I find this package best out-of-box auth for me. 

Using example code, i successfully added auth to my project:
```
import NextAuth from 'next-auth'
import Providers from 'next-auth/providers'

const options = {
  site: process.env.SITE || 'http://localhost:3000',

  // Configure one or more authentication providers
  providers: [
    Providers.GitHub({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET
    }),
  ],

  // A database is optional, but required to persist accounts in a database
  database: process.env.DATABASE_URL,
}

export default (req, res) => NextAuth(req, res, options)
```

Now I want to do 2 things that I don't understand how to:

1. First, i want to add a feature for users so they can add data to their account (to `users` model in MongoDB):
```
_id
name: string
email: string
image: string
---
favourite: [_id,_id]  ---> ref id from other collecction
```
2. And second, I want to have a button in my frontend so users can link their social account between them if needed

Please tell me how can achive this

**Comment by iaincollins** [comment]
1. This is possible but we don't have any tutorials for this currently.

2. This is technically possible but not documented supported yet.

 Linking and Unlinking accounts after signing in will be supported in a future release.

**Comment by MihaiWill** [comment]
@iaincollins thanks for clarify!
Is there a known roadmap for the docs/tutorials?

**Comment by ndom91** [comment]
@MihaiWill there is now documentation on extending the initial models using typeorm (which has support for mongodb) https://next-auth.js.org/tutorials/typeorm-custom-models.

Closing this issue now. If you have any further questions, etc. feel free to reopen it.
