### ISSUE TITLE
How to rotate "secret" used to sign cookies

### ISSUE THREAD

**Issue by dluc** [nextauthjs/next-auth#3721]
### Question 💬

Is it possible to configure NextAuth to have a "secondary" secret, so that it's possible to rotate the active/primary secret without invalidating all the current cookies?

It's common practice to rotate passwords, secrets etc. to protect from brute force but also from leaks. I'm assuming that when changing the `secret` value (https://next-auth.js.org/configuration/options#secret) all existing cookies become invalid, so a solution should ask users to sign in again. We would prefer a solution where we can "rotate" secrets as a maintenance task every few months, without having to worry about impacting users. Distributed solutions typically support an "active" primary secret, and an "old" secondary secret about to be deprecated.

### How to reproduce ☕️

Does NextAuth allow a similar configuration? e.g. instead of:

```
jwt: {
  // A secret to use for key generation. Defaults to the top-level `secret`.
  secret: 'INp8IvdIyeMcoGAgFGoA61DdBglwwSqnXJZkgz8PSnw',
  ...
}
```

something like:

```
jwt: {
  // A secret to use for key generation. Defaults to the top-level `secret`.
  signingSecret: 'INp8IvdIyeMcoGAgFGoA61DdBglwwSqnXJZkgz8PSnw',
  // Secrets to use to validate a key signature. Defaults to "signingSecret".
  validationSecrets: [
    'INp8IvdIyeMcoGAgFGoA61DdBglwwSqnXJZkgz8PSnw',
    'FwwSqnXJ2z1PSnwIvdIyeMdOpA61DdBkggloGAgFGoZ', 
  ],
  ...
}
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
You can add any logic through Advanced Initialization.

https://next-auth.js.org/configuration/initialization#advanced-initialization
