### ISSUE TITLE
Credentials does not work with `strategy` = `database`

### ISSUE THREAD

**Issue by KATT** [nextauthjs/next-auth#3729]
### Description 🐜

Credentials don't seem to work with strategy database and just tries to create a JWT token

https://github.com/nextauthjs/next-auth/blob/4824f8c02ad1b0799f4c15eea9c86e93fc5c72fc/src/core/routes/callback.ts#L398-L417

### Is this a bug in your own project?

No

### How to reproduce ☕️

- Use Credentials provider
- Use strategy database

### Environment 🖥

```bash

  System:
    OS: macOS 12.0.1
    CPU: (8) x64 Apple M1
    Memory: 86.30 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.3.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 97.0.4692.99
    Firefox: 94.0.1
    Safari: 15.1
  npmPackages:
    next: ^12.0.7 => 12.0.7
    next-auth: ^4.1.2 => 0.0.0-semantically-released
    react: ^18.0.0-rc.0 => 18.0.0-rc.0

```

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
This is intended: https://next-auth.js.org/providers/credentials

We encourage the flow in general.

**Comment by KATT** [comment]
It works with jwt though? And the other provider (Google) that I'm using works without any extra hoops.

How and where is a session created? I don't see any docs on it.

**Comment by KATT** [comment]
Oh, it's disabled, I see.

**Comment by KATT** [comment]
@balazsorban44 
If I want to make my own adapter that works with a user/password strategy which database sessions, what would the steps be? I've made it so it works in jwt mode already

**Comment by jrmyio** [comment]
Just waited a couple hours on this because it silently fails.

@balazsorban44 This should be opened as the current behavior is clear bugged. 

Setting an adapter sets "session" as the default strategy, which in turn makes credentials login fail.
When you signin with username/password, it does create a 'next-auth.session-token'-cookie but the database does not contain that session.

But worse, when you do GET /api/auth/session, your 'next-auth.session-token' cookie is instantly destroyed.

**Comment by jrmyio** [comment]
More people having issues which I think all are related to sessions not being supported for Credentials:
https://github.com/nextauthjs/next-auth/issues/3970
https://github.com/nextauthjs/next-auth/discussions/3787

I somewhat understand using credentials is discouraged but at the of the day, most of the web still is and will continue to use password-based logins. Almost all providers next-auth implements in the end boil down to credentials being used in the provider's ecosystem. For that reason it's not a surprise many people start implementing credentials with next-auth.

I don't really see what makes using the database session with credentials that much different then JWT. If intentional, why is one supported and the other one is not?

Inside https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/core/routes/callback.ts#L329 it seems almost all code should be there to get this to work, it's mostly just that the callbackHandler() is never called for the credentials.

**Comment by tobico** [comment]
Anyone have a workaround for this? At this point I don't really care how hacky it is - both database sessions and support for legacy password-based authentication are business requirements for my project, so this single issue is our only barrier to adopting NextAuth.

I'm generally onboard with the philosophy of going passwordless, but we can't do it overnight and need to continue to support our existing users as we transition.

**Comment by 0x3Anthony** [comment]
> This is intended: https://next-auth.js.org/providers/credentials
> 
> We discourage the flow in general.

@[balazsorban44](https://github.com/balazsorban44) So is there any way to save the session to the database through MongoDBAdapter under multiple login options such as twitter, discord, Credentials, etc. The two logins of twitter and discord are no problem. You can save the db normally, but Credentials does not have any problem. I don't know if there is a way to solve it, thank you!

**Comment by YuriyL-Git** [comment]
Any updates, please? Also, have to implement both types of authorizations and currently it's not possible ((

**Comment by nneko** [comment]
@YuriyL-Git take a look at my response at [#4394](https://github.com/nextauthjs/next-auth/discussions/4394#discussioncomment-3293618)

**Comment by jelmd** [comment]
Yeah, next-auth is a real nightmare. With all this workaround code I wonder, whether it would be better to drop it completely and write its own light weight session/auth handler, which can be understood and used easily ...

**Comment by FullstackJack** [comment]
I keep coming back to NextAuth thinking that issues like this will be solved. I get it that email and password login is antiquated and not as secure, but Credentials should be able to hook into the Adapter.

**Comment by BayBreezy** [comment]
It really sucks that we cant use a DB adapter and with the credentials provider :(

**Comment by Hasankanso** [comment]
you discourage managing credentials in the app, but ther're other use cases using credential provider such as anonymous users. Anonymous users don't have credentials to worry about.

**Comment by jelmd** [comment]
BTW wrt.:

> you discourage managing credentials in the app

If one makes such statements he should name the reasons for it. Otherwise it is the same non-sense as sending tokens by e-mail (xfer == often unencrypted, stored unencrypted - nothing is easier than hijacking e-mails ...). So documentation should be enhanced, too ...

**Comment by cdorfer** [comment]
Why do so many packages in the web development universe have to be opinionated for no reason? This leads to a myriad of different packages that try to solve the same problem in 'their way'. Let the developer decide, nobody needs your religion. After 5 projects with NextAuth that all went smooth we are switching to a more tolerant alternative solution.

**Comment by cdorfer** [comment]
Since the last post in July we have implemented Lucia Auth which works like charm for our use case (2FA with SMS). However, I have seen discussions of the developers about banning credentials sign-in also in Lucia Auth so better do your research on the current state of affairs before going for it.

**Comment by jrmyio** [comment]
> However, I have seen discussions of the developers about banning credentials sign-in also in Lucia Auth ...

Any source for this?

**Comment by cdorfer** [comment]
https://github.com/lucia-auth/lucia/discussions/1231

**Comment by tobico** [comment]
My update two years later is that we didn't end up using NextAuth, or using Next at all, as it had some serious issues with segfaulting when bundling our library code. We instead went with a custom server built on Express, which was a lot of work but got the job done.

**Comment by sovetski** [comment]
> you discourage managing credentials in the app

Any updates? It's the worst technical decision I've seen in my life, I wouldn't like to work in the same company as the creator of this library, only one guy imposes his ideas on everyone, that's the main reason which pushes me every time not to use a lib and to redo everything myself

From what I see, I am not alone: https://www.reddit.com/r/nextjs/comments/1bnhhex/is_it_just_me/

I suggest everyone to use better auth instead

**Comment by BenAHammond** [comment]
So this is just paternalistic bullshit opinionated decision making as opposed an actual technical limitation?
