### ISSUE TITLE
How to specify signin error from callback?

### ISSUE THREAD

**Issue by bscaspar** [nextauthjs/next-auth#373]
I want to display different info to the user for failed logins in based on an extra account validation happening in the signin callback function. Is there a way to specify the error query parameter passed in to the error page from the signin callback? Based on the documentation, the only responses are `Promise.resolve(true)` or `Promise.resolve(false)`. 

If not, is there another place it might make sense to specify this?

**Comment by iaincollins** [comment]
Not at the moment, but this is reasonable and I've considered before but there is not currently a mechanism to do this.

Right now the error code is always `AccessDenied` if you return `false` from the `signin()` callback.

Supporting other error codes by `rejecting` the promise and using the `name` property of the `Error` object (or parsing the response it as a simple string) is likely how we would support returning a custom error.

**Comment by bscaspar** [comment]
Thanks for the response! For now I'll implement the additional validation on a custom callback page. And if it's not already documented, I guess we can consider this issue a feature request/enhancement.

**Comment by bdesouza** [comment]
+1. This would be really helpful.
