### ISSUE TITLE
Allow setting more than one secret to better support production websites

### ISSUE THREAD

**Issue by zmarty** [nextauthjs/next-auth#3741]
### Description 📓

As far as I can tell NextAuth supports a single **secret** in the config for signing JWT tokens. This is a bit problematic on a large-ish production website where we need to rotate the secret every X months. To do that today we need to replace the secret and redeploy/restart. But when we do that all users get logged out since their JWT tokens suddenly stop working.

How we typically we do it other projects is we have at least two secrets in the configuration. When validating a JWT token, the code tries the first secret. If that fails, it tries the second secret.

Allowing 2 or more secrets ensures that we can rotate out one of them without logging out users. We implemented this in our backend already but we cannot release that without NextAuth also support it.

### How to reproduce ☕️

See above.

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by zmarty** [comment]
I **very** briefly took a look at the code and probably it would mean modifying [this](https://github.com/nextauthjs/next-auth/blob/30a0fc6bc0246b30eb03c19b8a0ceb6c040c1b2e/src/core/routes/session.ts#L44) section. I think here we have a try catch which catches if the token is invalid. Here we would need to modify the code to check twice with different secrets.

**Comment by zmarty** [comment]
And/or use the [kid claim](https://stackoverflow.com/questions/43867440/whats-the-meaning-of-the-kid-claim-in-a-jwt-token) to select the right key id

**Comment by balazsorban44** [comment]
You can define your custom encode/decode methods

https://next-auth.js.org/configuration/options#jwt

**Comment by zmarty** [comment]
Thanks, this helps! Although it's a bit more work for every user that needs it, we can implement this on our side then.
