### ISSUE TITLE
Add errorCallbackUrl when signIn() fails to login

### ISSUE THREAD

**Issue by AnderUstarroz** [nextauthjs/next-auth#3752]
### Description 📓

The [signIn()](https://next-auth.js.org/getting-started/client#signin) function has a useful **callbackUrl** for redirecting successfully logged-in users. But when users fails to  signIn(), they got redirected  to the  page **http://localhost:3000/api/auth/signin?error=CredentialsSignin**.  I really miss  having an **errorCallbackURL** for the signIn() function, because I do authentication programatically and I don't want users to be always redirected to the mentioned page. 

Is there currently any way to avoid this behaviour? Actually not redirecting at all would be fine when login fails, but the flag **redirect** affects both successful an failed logins.

### How to reproduce ☕️

just run `signIn("credentials", .. )` with the wrong credentials, users will get redirected to http://localhost:3000/api/auth/signin

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
https://next-auth.js.org/configuration/pages

**Comment by AnderUstarroz** [comment]
Thanks @balazsorban44 that was super useful. Is there any possible way to use the callbackURL when successful login and not redirect at all when failed?

**Comment by AnderUstarroz** [comment]
never mind, just figured out! thanks again.

**Comment by ahmedkhabar** [comment]
@AnderUstarroz Hi, I have the same problem with next-auth version 5, can you tell me what you do to fix this ?
