### ISSUE TITLE
Not working FACEIT provider

### ISSUE THREAD

**Issue by nixuuu** [nextauthjs/next-auth#3753]
### Description 🐜

Login via FACEIT just not working at all. Response from faceit API contains both fields (`access_token` and `id_token`), so library `openid-client` misinterprets the response and throws an error `id_token detected in the response, you must use client.callback() instead of client.oauthCallback()`. But when you change provider configuration to `idToken: true` it is also not working because FACEIT returns JWT token without exp field (whichis required in `openid-client`).

### Is this a bug in your own project?

No

### How to reproduce ☕️

Follow configuration steps from [documentation](https://next-auth.js.org/providers/faceit#configuration)

Finnaly provider should look something like this:

```typescript
FaceItProvider({
  clientId: process.env.FACEIT_CLIENT_ID,
  clientSecret: process.env.FACEIT_CLIENT_SECRET
})
```
or like this (see description):
```typescript
FaceItProvider({
  clientId: process.env.FACEIT_CLIENT_ID,
  clientSecret: process.env.FACEIT_CLIENT_SECRET,
  idToken: true,
})
```

Then just click `Sign in with FACEIT`, finish authorization in FACEIT webpage and wait for callback request

### Screenshots / Logs 📽

Faceit developer portal configuration:

![image](https://user-images.githubusercontent.com/3064153/151253354-86256ad0-087a-4fa0-8e2f-1ba0aeb69865.png)

Console error without `idToken: true`:
![image](https://user-images.githubusercontent.com/3064153/151253941-24955a1e-3576-4095-918d-b9eb5194dc72.png)

Console error with `idToken: true`:
![image](https://user-images.githubusercontent.com/3064153/151254082-d0262d08-92fa-442e-b29d-99812fdb03c2.png)

### Environment 🖥

Host machine:
```
  System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 9.91 GB / 31.94 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (97.0.1072.69)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    next: 12.0.7 => 12.0.7
    react: ^17.0.2 => 17.0.2
 ```

WSL environment:
```
  System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 2.02 GB / 15.60 GB
    Container: Yes
    Shell: 3.1.0 - /usr/bin/fish
  Binaries:
    Node: 16.13.2 - /usr/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.1.2 - /usr/bin/npm
  npmPackages:
    next: 12.0.7 => 12.0.7 
    react: ^17.0.2 => 17.0.2 
```

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
This is an issue with FACEIT implementing the spec wrong. The error says it all. `sub` is required when using `id_token`

https://openid.net/specs/openid-connect-core-1_0.html#IDToken

Please take it up with them.
