### ISSUE TITLE
 Twitter OAuth2 warning causing downgrade to OAuth1

### ISSUE THREAD

**Issue by terose73** [nextauthjs/next-auth#3767]
### Description 🐜

On line 173 in the Twitter OAuth provider source code the warning is causing authentication to revert to the TwitterLegacy provider. If the state of the warning is updated to `warned=true` (for example, the user logs in and then proceeds to log out). 

!warned should not be in the if statement.

### Is this a bug in your own project?

No

### How to reproduce ☕️

Use TwitterProvider with version="2.0", log out and proceed to attempt to log in again.

### Environment 🖥

 System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz  
    Memory: 1.57 GB / 7.86 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE        
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD 
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    next: 12.0.0 => 12.0.0 
    next-auth: ^4.1.2 => 4.1.2 
    react: ^17.0.2 => 17.0.2 

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
Yep good catch. The if block with `! warned` only need to be around the `console.warn`
