### ISSUE TITLE
Server Errror

### ISSUE THREAD

**Issue by bxdr-glitch** [nextauthjs/next-auth#3770]
### Description 🐜

Hello, I've just deployed my project with next-auth on Vercel. Unfortunetly, the sign in does not work because i get Server Error, There is a problem with the server configuration. Check the server logs for more information.

![error](https://user-images.githubusercontent.com/65233807/151765340-6724ce54-f9fa-403a-8370-22868f23b7df.png)

Now when checking the logs, it says ERROR	[next-auth][error][NO_SECRET] 
https://next-auth.js.org/errors#no_secret Please define a `secret` in production. MissingSecret [MissingSecretError]: Please define a `secret` in production.

While on that file i do have a secret that is defined, i even added in vercel the env for the secret but still no luck unfortunetly. Please help me fix this!

### Is this a bug in your own project?

No

### How to reproduce ☕️

This is my [next-auth].js file: 

![js](https://user-images.githubusercontent.com/65233807/151765286-e8944417-7e8c-46df-98c5-2658388628e5.png)

### Screenshots / Logs 📽

Also this is my google Oauth redirections althought i don't think this is the issue here: 

![google](https://user-images.githubusercontent.com/65233807/151765438-4911cb4c-8494-4c2f-a96b-db444b88f2f2.png)

### Environment 🖥

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36

    "@headlessui/react": "^1.4.3",
    "@heroicons/react": "^1.0.5",
    "@tailwindcss/forms": "^0.4.0",
    "faker": "^6.6.6",
    "firebase": "^9.6.5",
    "next": "latest",
    "next-auth": "^4.1.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-moment": "^1.1.1",
    "recoil": "^0.6.1"

### Contributing 🙌🏽

Yes i can help

**Comment by KojoEnch** [comment]
I suggest you try to replace your hard-coded secret in [...nextauth].ts by `process.env.AUTH_SECRET` for instance, then in your Vercel account, head to the Environment Variables page of your Project Settings and add a new variable called `AUTH_SECRET` with your random string.

You'll find all the related information in [next-auth configuration options](https://next-auth.js.org/configuration/options#secret) and [Vercel environment variables](https://vercel.com/docs/concepts/projects/environment-variables).

**Comment by balazsorban44** [comment]
what the above person said you might also need to redeploy the site

**Comment by zenodavids** [comment]
y'all just follow this example :
https://github.com/nextauthjs/next-auth-example

**Comment by everspader** [comment]
I have the same issue happening after I added the middleware like this:
```ts

export { default } from "next-auth/middleware";
```
But my `NEXTAUTH_SECRET` is already defined in the `.env.local` and I am seeing the same server error message in development mode. Any ideas?

**Comment by hu-qi** [comment]
> I have the same issue happening after I added the middleware like this:
> 
> ```ts
> export { default } from "next-auth/middleware";
> ```
> 
> But my `NEXTAUTH_SECRET` is already defined in the `.env.local` and I am seeing the same server error message in development mode. Any ideas?

Maybe the key is named `AUTH_SECRET`, I catch the same error, after I set the `AUTH_SECRET` , it is works.

like this codes https://github.com/nextauthjs/next-auth-example/blob/main/.env.local.example

**Comment by rizkianakbar** [comment]
i solved this issue by adding `AUTH_TRUST_HOST=true` to my env variables

https://authjs.dev/getting-started/deployment#auth_trust_host

**Comment by ezanglo** [comment]
> i solved this issue by adding `AUTH_TRUST_HOST=true` to my env variables
> 
> https://authjs.dev/getting-started/deployment#auth_trust_host

This solved my problem, im running on coolify and its behind proxy. Thank you!

**Comment by Zahoor25** [comment]
I have covered all the issues related to next auth in my blog, 

BLOG URL: http://localhost:4321/blog/how-to-add-oauth-next14

**Comment by debugzhao** [comment]
I encountered the same problem, and it resolved itself after a while.
