### ISSUE TITLE
Inconsistent docs for unlinkAccount

### ISSUE THREAD

**Issue by breyed** [nextauthjs/next-auth#3778]
### Description 🐜

[Create an adapter](https://next-auth.js.org/tutorials/creating-a-database-adapter#unimplemented-methods) indicates that `unlinkAccount` is never used or implemented; however, [Models](https://next-auth.js.org/adapters/models/#account) indicates that it is. The documentation inconsistency should be resolved.

### Is this a bug in your own project?

No

### How to reproduce ☕️

Documentation issue only.

### Environment 🖥

v4 docs

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
I do not see that inconsistency:

> You can manually unlink accounts, **if** your adapter implements the `unlinkAccount` method. Make sure to take all the necessary security steps to avoid data loss.

As mentioned, this is planned as per #230 at some point.

**Comment by breyed** [comment]
Fair enough. The **if** you references had made me think the feature was available.
