### ISSUE TITLE
Email provider errors out

### ISSUE THREAD

**Issue by ThatOneCalculator** [nextauthjs/next-auth#3781]
### Description 🐜

Using the process provided in the docs (and adding `nodemailer` with `yarn`), trying to use `EmailProvider` gives an error: 
```
TypeError: Cannot destructure property 'getUserByEmail' of 'adapter' as it is undefined.
```

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

1. `yarn add nodemailer`
2. Add 
```
EMAIL_SERVER=smtp://CENSORED:CENSORED@smtp.gmail.com:587
EMAIL_FROM=CENSORED@gmail.com
```
to `.env.local`
3. Add
```js
    EmailProvider({
      server: process.env.EMAIL_SERVER,
      from: process.env.EMAIL_FROM
    })
```
to `[...nextauth].js`
4. `yarn dev`
5. Attempt to fill in email

### Screenshots / Logs 📽

![ezgif-2-9da8f9ad1b](https://user-images.githubusercontent.com/44733677/152067582-c6459d0b-94b6-4310-a9b0-9b71d094602c.png)

### Environment 🖥

```
  System:
    OS: Linux 5.16 Arch
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 18.66 GB / 31.35 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.3.0 - /usr/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.4.0 - /usr/bin/npm
  Browsers:
    Firefox: 96.0.3
  npmPackages:
    next: ^12.0.7 => 12.0.9 
    next-auth: ^4.1.0 => 4.1.2 
    react: ^17.0.2 => 17.0.2 
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by ThatOneCalculator** [comment]
@balazsorban44 Why'd you close this without any other message?

**Comment by jacobhq** [comment]
@balazsorban44 I am also experiencing this, why did you close?

**Comment by Pablokiryu** [comment]
I have a typeorm connection and it errors out, but with a different error

"GetUserByEmailError: You must provide selection conditions in order to find a single row."
Should i open up a new issue ?
