### ISSUE TITLE
getSession without token request

### ISSUE THREAD

**Issue by hboylan** [nextauthjs/next-auth#3789]
### Description 📓

I originally asked [this question in discussions](https://github.com/nextauthjs/next-auth/discussions/3763). It appears that there isn't currently support for this feature so I'd like to investigate whether I can contribute a solution for it.

Long story short, I want `await getSession(ctx)` to resolve an existing session if one is already set in the request cookies. Currently, it fetches a new token every time. This may be nice for some use cases, but I would like to avoid the latency overhead whenever possible.

### How to reproduce ☕️

See the related Q&A topic.
https://github.com/nextauthjs/next-auth/discussions/3763

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
This is going to be addressed through `getServerSession` already. This is almost ready, just currently undocumented. See https://github.com/nextauthjs/next-auth/issues/1535#issuecomment-931785322

You can actually already do `import { getServerSession } from "next-auth/next"`

**Comment by hboylan** [comment]
Thank you @balazsorban44! I also found this method while testing and while it does not use HTTP to request the _session_, it will make a request for the _token_ every time.

This adds noticeable latency to page transitions, especially when coupled with API requests. Do you think we should support the option to skip the token request when fetching an existing session?

**Comment by hboylan** [comment]
Oh my gosh. My `jwt` callback was refreshing the token, which was causing the latency. 🤦🏻 

`getServerSession` works perfectly for my scenario. 🎉
