### ISSUE TITLE
Middleware fails with: "result.response.headers is not iterable"

### ISSUE THREAD

**Issue by EvHaus** [nextauthjs/next-auth#3800]
### Description 🐜

I am trying to test out the new Next.js middleware support in 4.2.0. I followed the instructions at https://next-auth.js.org/configuration/nextjs#middleware. I created a `pages/_middleware.ts` page and put:

```
export { default } from 'next-auth/middleware';
```

However, my app now won't load due to this error which is printed both on the backend and on the frontend:

```
TypeError: result.response.headers is not iterable
```

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

Used the base next.js boilerplate and just added the middleware file.

https://stackblitz.com/edit/nextjs-j2ksr1?file=pages/_middleware.ts

### Environment 🖥

  System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 174.69 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2022.01.31.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 97.0.4692.99
    Chrome Canary: 100.0.4867.0
    Firefox: 96.0.2
    Safari: 15.2

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by Fedeorlandau** [comment]
Experiencing the same thing.

```
import { NextRequest, NextResponse } from 'next/server';
import { JWT } from 'next-auth/jwt';
import withAuth from 'next-auth/middleware';

const PUBLIC_FILE = /\.(.*)$/;

export default withAuth(function middleware(
  req: NextRequest & { nextauth: { token: JWT } }
) {
  const isStaticOrApi =
    PUBLIC_FILE.test(req.nextUrl.pathname) ||
    req.nextUrl.pathname.includes('/api/');

  if (isStaticOrApi) {
    return undefined;
  }

  const { pathname } = req.nextUrl;
  if (pathname.match(/dashboard/)) {
    if (!req.nextauth.token) {
      return NextResponse.redirect('/login');
    }
  }
  return NextResponse.next();
});
```

Cheers,

**Comment by balazsorban44** [comment]
I pushed a fix, please upgrade to `4.2.1`

**Comment by balazsorban44** [comment]
Also, be aware of this https://github.com/nextauthjs/next-auth/issues/3802#issuecomment-1029845637

**Comment by tobbbe** [comment]
Getting the exact same error on 4.3.4 😞 Follow this guide: https://next-auth.js.org/configuration/nextjs#wrap-middleware

**Comment by tobbbe** [comment]
@balazsorban44 Getting the exact same error on 4.3.4 😞 Follow this guide: https://next-auth.js.org/configuration/nextjs#wrap-middleware
