### ISSUE TITLE
Recommend using an adapter in token rotation tutorial

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#3809]
Currently, we don't have a token rotation mechanism built-in, so we have the following tutorial users can look at:

https://next-auth.js.org/tutorials/refresh-token-rotation

Storing `refresh_token` in a cookie is not a good idea.

We should refactor the tutorial to use an adapter instead.

At the very least we should mention that if someone absolutely decides to use a JWT, encryption is a must!

**Comment by ndom91** [comment]
`nextauthjs/next-auth` has been migrated to a monorepository. The docs code can now be found here under `packages/docs`. Thanks for your interest in the project!

**Comment by amosbastian** [comment]
Has anyone implemented this while using a database strategy instead of the JWT strategy?

**Comment by balazsorban44** [comment]
Closed in https://github.com/nextauthjs/next-auth/commit/e8fbe5899742d253b032852c455e6f21f62da7d8
