### ISSUE TITLE
Use TypeScript on "Custom Client Session Handling"

### ISSUE THREAD

**Issue by deadcoder0904** [nextauthjs/next-auth#3810]
This should be in TS → https://next-auth.js.org/getting-started/client#custom-client-session-handling

# pages/_app.tsx

```ts
function Auth({ children }: { children: any }) {
	const { data: session, status } = useSession()
	const isUser = !!session?.user

	useEffect(() => {
		if (status === 'loading') return
		if (!isUser) signIn()
	}, [isUser, status])

	if (isUser) {
		return children
	}

	return <div>Loading...</div>
}

interface AppPropsWithAuth extends AppProps {
	Component: AppProps['Component'] & { auth: boolean }
}

const CustomApp = ({ Component, pageProps: { session, ...pageProps } }: AppPropsWithAuth) => {
	return (
		<SessionProvider session={session}>
				{Component.auth ? (
					<Auth>
						<Component {...pageProps} />
					</Auth>
				) : (
					<Component {...pageProps} />
				)}
		</SessionProvider>
	)
}

export default CustomApp
```

**Comment by ndom91** [comment]
`nextauthjs/next-auth` has been migrated to a monorepository. The docs code can now be found here under `packages/docs`. Thanks for your interest in the project!

**Comment by dkraj1101** [comment]
Can you provide a full example I can create the following code

interface AppPropsWithAuth extends AppProps {
	Component: AppProps['Component'] & { auth: boolean }
}
 
But How should I use it for index.tsx

**Comment by balazsorban44** [comment]
Actually, with the introduction of Next.js Middleware, this option is getting obsolete, since you can do the same with a few lines of code:


See https://next-auth.js.org/configuration/nextjs#middleware

If anything, we could probably remove this from the docs in favor of:

`pages/admin/_middleware.js`
```ts
import { withAuth } from "next-auth/middleware"

export default withAuth({
  callbacks: {
    authorized: ({ token }) => token?.role === "admin",
  },
})
```

This has the same effect, but it's much cleaner and more understandable, also not requiring any TS skills. The only thing to add is the augmentation of `JWT` as described in https://next-auth.js.org/getting-started/typescript#module-augmentation

**Comment by dkraj1101** [comment]
Can I Do that on the pages folder on top level?

**Comment by dkraj1101** [comment]
I want to check the user is signed in or not before it lands on the first page. How can I do that can you provide example?

**Comment by balazsorban44** [comment]
You could have opened the link I sent... :upside_down_face:

But here, more precisely:
https://next-auth.js.org/configuration/nextjs#prerequisites
https://next-auth.js.org/configuration/nextjs#default-re-export

`pages/_middleware.js`
```js
export { default } from "next-auth/middleware"
```

That's it! Please read the docs before asking. :+1:
