### ISSUE TITLE
Firebase adapter: db is not a function

### ISSUE THREAD

**Issue by michalscislowski** [nextauthjs/next-auth#3814]
### Title

Firebase adapter: db is not a function

### How to reproduce ☕️

firebase.js:
```
import { initializeApp, getApp, getApps} from "firebase/app";
import { getAnalytics } from "firebase/analytics";
import { getFirestore } from "@firebase/firestore";
import { getStorage } from "@firebase/storage";


const firebaseConfig = {
  apiKey: "xxxxx",
  authDomain: "xxxxx.firebaseapp.com",
  projectId: "xxxxx",
  storageBucket: "xxxx.appspot.com",
  messagingSenderId: "xxxx",
  appId: "xxxxx",
  measurementId: "xxx"
};


const app = !getApps.length ? initializeApp(firebaseConfig) : getApp();
const db = getFirestore(app); 
const storage = getStorage();
const analytics = getAnalytics(app);

export {app, db, storage, firebaseConfig};
```

[...nextauth].js:

```
import NextAuth from "next-auth"
import GithubProvider from "next-auth/providers/github"
import GoogleProvider from "next-auth/providers/google"
import { db } from "../../../firebase"
import { FirebaseAdapter } from "@next-auth/firebase-adapter"

export default NextAuth({
  providers: [
    GithubProvider({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET,
    }),
    GoogleProvider({
        clientId: process.env.GOOGLE_CLIENT_ID,
        clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    }),
  ],
adapter: FirebaseAdapter(db),

theme: {
    colorScheme: 'dark'
}
})
```

error:

```
TypeError: collection is not a function
```

node_module:

```
"node_modules/@next-auth/firebase-adapter": {
      "version": "0.1.2-pr.183-76202b42.8",
      "resolved": "https://registry.npmjs.org/@next-auth/firebase-adapter/-/firebase-adapter-0.1.2-pr.183-76202b42.8.tgz",
      "integrity": "sha512-0zAPcY3YgTB0Od05hhfa1zFrpjOtvu2n/xHPFpk70ideCbxy5lXlojHNm+NRKwSeWx2nkwF3YqIEZVnsOaYnZA==",
      "peerDependencies": {
        "firebase": "^9.0.0-beta.8",
        "next-auth": ">=4"
      }
```

### Your question/bug report 📓

I want to use firebase-adapter to actually persist user data, as I'm not getting user records in firebase console after signup/login.

### Contributing  🙌🏽

No, I'm afraid I cannot help regarding this

**Comment by ndom91** [comment]
`nextauthjs/next-auth` has been migrated to a monorepository. The adapters code can now be found there under `packages/adapter-*`. Thanks for your interest in the project!

**Comment by navindigicita** [comment]
hey! I'm getting similar issue in my next js auth setup

firebase-config.js
`import { getApp, getApps, initializeApp } from "firebase/app";
import { getFirestore } from 'firebase/firestore'
import { getStorage } from 'firebase/storage'

const firebaseConfig = {
    apiKey: process.env.NEXT_PUBLIC_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_APP_ID,
};

const app = getApps.length > 0 ? getApp() : initializeApp(firebaseConfig);

const db = getFirestore(app)

const storage = getStorage(app)

export { app, db, storage }`

[...nextauth].js

`import NextAuth from "next-auth"
import GithubProvider from "next-auth/providers/github"
import { FirebaseAdapter } from '@next-auth/firebase-adapter'
import { db } from "../../../firebase-config"
import * as firebaseFuntions from 'firebase/firestore'

export default NextAuth({
    providers: [
        GithubProvider({
            clientId: process.env.NEXT_PUBLIC_FIREBASE_GOOGLE_ID,
            clientSecret: process.env.NEXT_PUBLIC_FIREBASE_GOOGLE_SECRET_KEY,
        }),
    ],
    adapter: FirebaseAdapter({
        db: db,
        ...firebaseFuntions
    })
})`

and that's the error I'm getting-
![image](https://user-images.githubusercontent.com/65160684/184322166-8436c027-aa06-4a03-a3de-05c2c23bf89e.png)

**Comment by ndom91** [comment]
> import { FirebaseAdapter } from '@next-auth/firebase-adapter'

Can you provide some more info about which versions of next.js you're using and maybe your `next.config.js`?

Becuase `FirebaseAdapter` definitely is a named export from that package :thinking: 

https://github.com/nextauthjs/next-auth/blob/main/packages/adapter-firebase/src/index.ts#L37

**Comment by slicycode** [comment]
Hello,
I have the same issue with the exact same code as [navindigicita](https://github.com/navindigicita) and I still don't find any solution somewhere.
My `next.config.js` file : 

```
/** @type {import('next').NextConfig} */
module.exports = {
  reactStrictMode: true,
}
```


and my `package.json` : 

```
{
  "name": "doggydays",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@next-auth/firebase-adapter": "^1.0.1",
    "autoprefixer": "^10.4.11",
    "eslint-config-prettier": "^8.5.0",
    "firebase": "^9.10.0",
    "next": "latest",
    "next-auth": "4.10.3",
    "postcss": "^8.4.16",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-icons": "^4.4.0",
    "tailwindcss": "^3.1.8"
  },
  "devDependencies": {
    "eslint": "8.23.1",
    "eslint-config-next": "12.3.1"
  }
}

```

**Comment by RonAlmog** [comment]
why is this closed? I have the exact same issue, and I can't see any solution of direction. any idea?
here is my code:

export const authOptions = {
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    })
  ],
  adapter: FirebaseAdapter({ db, ...firestoreFunctions }),
  }
  ...
  export default NextAuth(authOptions);

and the error is:
error - (api)/pages/api/auth/[...nextauth].js (43:27) @ eval
error - TypeError: (0 , _next_auth_firebase_adapter__WEBPACK_IMPORTED_MODULE_6__.FirebaseAdapter) is not a function
    at eval (webpack-internal:///(api)/./pages/api/auth/[...nextauth].js:64:90)

any idea?

**Comment by RonAlmog** [comment]
and btw: with  @next-auth/firebase-adapter@experimental , it works!  
but with the latest version of @next-auth/firebase-adapter, it gives an error.

**Comment by greeenboi** [comment]
> and btw: with @next-auth/firebase-adapter@experimental , it works! but with the latest version of @next-auth/firebase-adapter, it gives an error.

I can no longer use the experimental version..
has it been taken down?

**Comment by greeenboi** [comment]
> hey! I'm getting similar issue in my next js auth setup
> 
> firebase-config.js
> 
> ```
> import { getApp, getApps, initializeApp } from "firebase/app";
> import { getFirestore } from 'firebase/firestore'
> import { getStorage } from 'firebase/storage'
> 
> const firebaseConfig = {
>     apiKey: process.env.NEXT_PUBLIC_API_KEY,
>     authDomain: process.env.NEXT_PUBLIC_AUTH_DOMAIN,
>     projectId: process.env.NEXT_PUBLIC_PROJECT_ID,
>     storageBucket: process.env.NEXT_PUBLIC_BUCKET,
>     messagingSenderId: process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID,
>     appId: process.env.NEXT_PUBLIC_APP_ID,
> };
> 
> const app = getApps.length > 0 ? getApp() : initializeApp(firebaseConfig);
> 
> const db = getFirestore(app)
> 
> const storage = getStorage(app)
> 
> export { app, db, storage }
> ```
> 
> [...nextauth].js
> 
> ```
> import NextAuth from "next-auth"
> import GithubProvider from "next-auth/providers/github"
> import { FirebaseAdapter } from '@next-auth/firebase-adapter'
> import { db } from "../../../firebase-config"
> import * as firebaseFuntions from 'firebase/firestore'
> 
> export default NextAuth({
>     providers: [
>         GithubProvider({
>             clientId: process.env.NEXT_PUBLIC_FIREBASE_GOOGLE_ID,
>             clientSecret: process.env.NEXT_PUBLIC_FIREBASE_GOOGLE_SECRET_KEY,
>         }),
>     ],
>     adapter: FirebaseAdapter({
>         db: db,
>         ...firebaseFuntions
>     })
> })
> ```
> 
> and that's the error I'm getting- ![image](https://user-images.githubusercontent.com/65160684/184322166-8436c027-aa06-4a03-a3de-05c2c23bf89e.png)

I Also have a similar issue. Are there any updates on this from your side?
