### ISSUE TITLE
DynamoDb Adapter + EmailProvider do not work properly

### ISSUE THREAD

**Issue by cosimochellini** [nextauthjs/next-auth#3819]
### Title

DynamoDb Adapter + EmailProvider do not work properly

### How to reproduce ☕️

- clone the repo https://github.com/cosimochellini/s3-share-files (main branch)
- configure the .env starting from .env.fake (if you need I can provide a .env proper configured via email)
- yarn
- yarn dev
- click [signin]
- confirm the link sent via email
- the app redirects to **/api/auth/error?error=Verification**, no error both on the console nor the terminal 😥

### Your question/bug report 📓

Using this configuration generates an error in the phase of confirming the email
```js
{ 
    providers: [EmailProvider(opts)],
    adapter: DynamoDBAdapter(DocumentClient),
}
```
I've configured the adapter and the provider as the docs say.

Both the email provider and the dynamo document client work properly since the email send the emails (in the [...nextauth].ts and also in the rest of the application) and the dynamo client is capable of reading/writing other data in the rest of the application.

I've followed the guide to configure the table next-auth on AWS and it seems to match the structure you're asking for.

### Contributing  🙌🏽

No, I'm afraid I cannot help regarding this

**Comment by ndom91** [comment]
`nextauthjs/next-auth` has been migrated to a monorepository. The adapters code can now be found there under `packages/adapter-*`. Thanks for your interest in the project!

**Comment by cosimochellini** [comment]
@ndom91 I've found the problem with this adapter!

In the `packages/adapter-dynamodb/src/index.ts` you're using the dynamo DB client every time like this way 

```ts
async getUser(userId) {
      const data = await client.get({
        TableName,
        Key: {
          pk: `USER#${userId}`,
          sk: `USER#${userId}`,
        },
      })
      return format.from<AdapterUser>(data.Item)
    },
```
the problem is that in the last versions of the dynamo DB package on npm, you have to do in this way

```ts
async getUser(userId) {
      const data = await client.get({
        TableName,
        Key: {
          pk: `USER#${userId}`,
          sk: `USER#${userId}`,
        },
      }).promise() // with this .promise() method
      return format.from<AdapterUser>(data.Item)
    },
```

So my temporary workaround is to pass in the constructor an object like this 

```ts
```

**Comment by ndom91** [comment]
@cosimochellini which version of `@aws-sdk/client-dynamodb` are you using exactly? In our tests we're using `3.36.1`. We're also using the `@aws-sdk/lib-dynamodb` of the same version, and those types say the `.promise()` method doesn't exist there yet.. 

Tests also still pass, so it should work as advertised with `3.36.1` :thinking:

**Comment by cosimochellini** [comment]
interesting 🤔🤔....

I was not using the `@aws-sdk/client-dynamodb` , instead I've been using the good old [`aws-sdk`](https://www.npmjs.com/package/aws-sdk)

So is correct that you don't see the promise() method.

The very weird thing is that typescript does not blame me for passing a completely different interface 😰😰

I'll try to convert my code to use the correct npm package.

Sorry for the time I wasted you 😥

**Comment by ndom91** [comment]
@cosimochellini no worries! Can you confirm it works for you now though, using the `@aws-sdk/client-dynamodb` instead?

**Comment by cosimochellini** [comment]
yes, with `@aws-sdk/client-dynamodb` now works just fine!
