### ISSUE TITLE
[TypeORM] Typings for TypeORM options and add changed casing to migration docs

### ISSUE THREAD

**Issue by fandy** [nextauthjs/next-auth#3826]
In V3 next-auth was using snake-case for database columns, but now the typeorm legacy next adapter references camelcase version. This is not mentioned in the migration docs, which could break some projects.

**Comment by ndom91** [comment]
`nextauthjs/next-auth` has been migrated to a monorepository. The adapters code can now be found there under `packages/adapter-*`. Thanks for your interest in the project!

**Comment by balazsorban44** [comment]
Hi, we have included a section in the docs specific to TypeORM about naming conventions:

https://next-auth.js.org/adapters/typeorm#naming-conventions

We also have a database migration section in our Upgrade to v4 docs:

https://next-auth.js.org/getting-started/upgrade-v4#database-migration
