### ISSUE TITLE
Prisma adapter fails when trying to create a user

### ISSUE THREAD

**Issue by icflorescu** [nextauthjs/next-auth#3828]
Got this strange error after upgrading from `0.4.4-canary.64`:

```
[next-auth][error][prisma__create_user_error]
https://next-auth.js.org/errors#prisma__create_user_error PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]:
Invalid `prisma.user.create()` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: ToSql(0), cause: Some(Error(Parser(InvalidLength { expected: Any([36, 32]), found: 21 }))) }) })
    at cb (/[...]/node_modules/@prisma/client/runtime/index.js:33820:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async acc.<computed> (/[...]/node_modules/next-auth/dist/adapters/error-handler.js:19:16)
    at async callbackHandler (/[...]/node_modules/next-auth/dist/server/lib/callback-handler.js:151:14)
    at async Object.callback (/[...]/node_modules/next-auth/dist/server/routes/callback.js:100:13) {
  clientVersion: '2.25.0'
}
```

The error seems to originate here: https://github.com/nextauthjs/adapters/blob/main/packages/prisma/src/index.ts#L34

I've slightly adjusted my User model (id as `@db.Uuid`), hence the length mismatch in the error message.

I believe simply passing the destructured profile might not be such a good idea, as `profile` always has an `id` property which will end up overriding the autogenerated User id.

**Comment by ndom91** [comment]
`nextauthjs/next-auth` has been migrated to a monorepository. The adapters code can now be found there under `packages/adapter-*`. Thanks for your interest in the project!

**Comment by balazsorban44** [comment]
Closing as this issue is kinda old. Let's open a new one with a fresh, minimal reproduction, if it still exists.
