### ISSUE TITLE
Try signing with a different account. - Callback error

### ISSUE THREAD

**Issue by ChezCodes** [nextauthjs/next-auth#3830]
**Describe the bug**
When trying to sign in to GitHub it says "Try signing with a different account."

**Steps to reproduce**
- Clone orangopus/libby
- click "Login" 
- Click "Sign in with GitHub"

Make sure to include the client ID and secret in .env as `GITHUB_ID` and `GITHUB_SECRET`

**Expected behavior**
I expected it to login and return to the app.

**Screenshots or error logs**
The error is
![browser_7MIk0bI7BK](https://user-images.githubusercontent.com/45247477/104529167-fc6e2e00-5600-11eb-8127-f78be5dd7ca9.png)

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by ndom91** [comment]
`nextauthjs/next-auth` has been migrated to a monorepository. The adapters code can now be found there under `packages/adapter-*`. Thanks for your interest in the project!

**Comment by devSahinur** [comment]
> Hey william, thanks for this!
> 
> You probably saw it, but theres an issue/PR related to this in the core repo already as well: #2108 + https://github.com/nextauthjs/adapters/issues/130
> 
> Balazs initially said he wanted to hold off on this change until the next major release since it seems like a breaking change. Some users will have already coded around it expecting it to be a number instead of a string, etc.
> 
> How do you see it? Would this be a breaking change in your opinion?
> 
> **EDIT**: Someone posted a workaround in that thread:
> 
> > I'll leave this note here for the benefit of other people who might run into the same issue.
> > Until this gets fixed, use this workaround:
> > import NextAuth, { User as NextAuthUser } from 'next-auth'
> > interface NextAuthUserWithStringId extends NextAuthUser {
> > id: string
> > }
> > ```js
> > Providers.GitHub({
> >       clientId: process.env.GITHUB_ID,
> >       clientSecret: process.env.GITHUB_SECRET,
> >       profile(profile) {
> >         return {
> >           id: profile.id.toString(),
> >           name: profile.name || profile.login,
> >           email: profile.email,
> >           image: profile.avatar_url,
> >         } as NextAuthUserWithStringId
> >       },
> >     }),
> > ```

@ndom91  Thanks, dude!

**Comment by EvgenKoshevoy** [comment]
Hello. I have same issue with Cognito Adapter (with SAML Azure AD). After clicking "Sign in with Cognito" again - i have access to page.

**Comment by Seth-McKilla** [comment]
> ```prisma
> ...
> ```

Hey @trulymittal not sure if you've resolved this already but nonetheless I was running into this exact issue. After digging around closed issues I found this Account schema that is working well for me: https://github.com/nextauthjs/next-auth/issues/3465#issuecomment-997005276

No weird issues yet! 🤞

**Comment by hollerith** [comment]
prisma related issue solved for me by just generating the client again

`npx prisma generate`

**Comment by fullupe** [comment]
just follow the error path and  add ? in front of the value

for (const key in newUser) {
            const value = newUser[key];
            if (value?.toDate)
                newUser[key] = value.toDate();
            else
                newUser[key] = value;
        }

**Comment by VaquarShaikh** [comment]
Try adding 
```
session: {
    // Set to jwt in order to CredentialsProvider works properly
    strategy: "jwt",
  },
```
To [...nextauth]

**Comment by imrankhanjoya** [comment]
Its not about adapter its about next-auth lib issue can some one help me
next-auth][debug][CREATE_STATE] { state: 'O1k6DX0Isddd9wvUdsdnCRksudNFYQyk0ZVO4c8lqqePc', maxAge: 900 }
[next-auth][debug][CREATE_PKCE_CHALLENGE_VERIFIER] {
  code_challenge: 'oEzh0AjPSnp7wIsdsdsdCtYPHVmdU-NDd39J7o',
  code_challenge_method: 'S256',
  code_verifier: 'mYB_6sdsdf8sd0nbTKvoTxeoAacW0w-tuZ_ASfUvITPs8',
  PKCE_MAX_AGE: 900
}
[next-auth][debug][GET_AUTHORIZATION_URL] {
  url: 'https://twitter.com/i/oauth2/authorize?client_id=UlVva1VQM0sxblRnWMVc6MTpjaQ&scope=users.read%20tweet.read%20offline.access&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fauth%2Fcallback%2Ftwitter&state=O1k6DXZNNgI0I9wvUnCRksudNFYQyk0ZVO4c8lqqePc&code_challenge=oEzh0AjPSnp7wICmdPiqEjCcZ7ZBU-NDd39J7o&code_challenge_method=S256',
  cookies: [
    {
      name: 'next-auth.state',
      value: 'eyJhbGciOiJkaXIiLCJlbmJBMjU2R0NNIn0..PkaCKXnqbDyGy-lr.FpYZLVHv9caJ3ITP4kQqW0uiyKyR-BYUzWUsd-d0F4XNk9uU-xts6VAUvD697y7oltF4pgcEEhMUvnTPbwryvDTWLqX4M-w73Td_n-jisl1Zgn7EWKi9C3JjrsHcvSXoxC-de-MUCGhR4XgRtXbnkR6WxQ.rDgOw9i9YQMYIdENxYg-6g',
      options: [Object]
    },
    {
      name: 'next-auth.pkce.code_verifier',
      value: 'eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0sdQ8YT1x1hQUvSBE.02S7_YBK1ok4cRA0aa8MhcvRJ2ypHaznbVasAnhmvigiy1Jz-XNrKo0oYnR-qx5QRVWfKSmRxYI5l0-hoxp6T2Gpdpp273ATBgzQTJs7GYs5Enxjptkva4Vgr-Rw_aRal7W5G0pNHFfRYknc4FPH5cdMCEFoQFjJKSGdcwtks8lwdRSxanBJy6tw2rwxwQ.PJBK-sweSQg_K2RJMUMjA',
      options: [Object]
    }
  ],
  provider: {
    id: 'twitter',
    name: 'Twitter',
    version: '2.0',
    type: 'oauth',
    authorization: { url: 'https://twitter.com/i/oauth2/authorize', params: [Object] },
    token: {
      url: 'https://api.twitter.com/2/oauth2/token',
      request: [AsyncFunction: request]
    },
    userinfo: { url: 'https://api.twitter.com/2/users/me', params: [Object] },
    profile: [Function: profile],
    checks: [ 'pkce', 'state' ],
    idToken: false,
    clientId: 'UlVva1VQM0sxblRnWnc2sdfadhhHH',
    clientSecret: 'ffyz6bdNKWasdf1jOOevA4UQLr_IFmo',
    signinUrl: 'http://localhost:3000/api/auth/signin/twitter',
    callbackUrl: 'http://localhost:3000/api/auth/callback/twitter'
  }
}
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error expected 200 OK, got: 403 Forbidden {
  error: OPError: expected 200 OK, got: 403 Forbidden

**Comment by Ayushpandey80** [comment]
How to allow user to Connect Twitter / LinkedIn account (get access token permanently) after user is logged-in to the next-js app using next-auth's Google provider?


[Exact Question](https://github.com/nextauthjs/next-auth/discussions/6217)

**Comment by keshri95** [comment]
I'm having same issue its a Promise even I placed context
`uncaught (in promise) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at it (blur.js:42:3933)
    at s.useContext (blur.js:42:5675)
    at cr (blur.js:57:31858)
    at blur.js:61:494
    at blur.js:126:5191
    at Generator.next (<anonymous>)
    at I (blur.js:126:4967)`

**Comment by keshri95** [comment]
Guys, 
If you are encountered failed issue then your have to place secrete key 
`providers: [
    GithubProvider({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET,
    }),
    // ...add more providers here
  ],

  secret: process.env.JWT_SECRET
`
Get the secret key in from your terminal
`openssl rand -base64 32`

**Comment by thinkdj** [comment]
> @trulymittal Thanks for the direction. I was able to fix my issue.
NextAuth has mentioned these as small footnotes at https://next-auth.js.org/adapters/models#account

**Comment by ThangHuuVu** [comment]
To everyone who is running into this issue, `next-auth` will forward every property it received from the provider to the DB, so for now you need to make sure that your DB schema matches the payload. Seems like this is still missing from docs, feel free to open a PR to improve it 🙏  
Going forward, as @ndom91 mentioned in https://github.com/nextauthjs/next-auth/issues/3830#issuecomment-861288770, we want to flip this behavior to only accept a number of props and let developers specify what props they want to pass to DB.

**Comment by e-simpson** [comment]
Huge issues with next-auth and GitHub provider with Prisma

**Comment by MrEmanuel** [comment]
For me it was a problem with the connection to the database. 
Fix the environment variable, redeploy to vercel. Presto!

**Comment by mostafa1elgzaeere** [comment]
im faced this issue before , make sure you put ".env.local" file at the project folder , not in page folder or api folder or others

put it at the global folder

**Comment by Nateight8** [comment]
> Awesome! Thankyou @williamluke4 and @ndom91! This works for me now!
> 
> But whenever I login using github as mentioned above, the email is stored as null in my database, how can I enable email to be stored as well as soon as someone logs in?
> 
> <img alt="Screenshot 2021-06-15 at 8 20 19 PM" width="997" src="https://user-images.githubusercontent.com/50735025/122074766-1cf01d80-ce17-11eb-9fca-d747fcf678d9.png">
> 
> EDIT: I can see that the docs mention: `Email address is not returned if privacy settings are enabled.`

During my project work, I encountered an issue where the session was not being returned. However, when I downgraded the version of next-auth to ^4.10.3, the problem was resolved. It seems that the issue was related to the version of next-auth. Please note that this information might not be relevant to your current situation.

**Comment by MilanObrenovic** [comment]
I'm getting this error, but i'm connected to a hotspot of my android phone because the wifi in my house died. I think this causes a whole new set of problems

Anyone knows how to fix this problem when im connected to a mobile 4g hotspot network instead of wifi?

**Comment by natkucera** [comment]
Late to the game but the solution for me was a lot simpler than I could have imagined. I just restarted the server and everything works great now. Feel silly for not trying it sooner

**Comment by rshirani** [comment]
I am hitting this issue using google authentication with prisma. It was working fine before starting to integrate with Prisma.

**Comment by Wissaladd** [comment]
@rshirani i am having the same issue with the google provider did you manage to fix it

**Comment by umerpall** [comment]
I had a wrong "GOOGLE_CLIENT_SECRET" which was causing the problem.

**Comment by Akshay8122** [comment]
error name: 'OAuthCallbackError',
code: undefined
I've missed giving a timeout in provider
 httpOptions: {
        timeout: 5000,
},
in provider and simply my error resolved
I hope this will work for you in case -- this kind of message in terminal: 'outgoing request timed out after 3500 ms'

**Comment by brandonhdez7** [comment]
i added this and it seemed to work for me, i'm only using the google provider 
<img width="1237" alt="Screenshot 2024-01-25 at 10 08 14 PM" src="https://github.com/nextauthjs/next-auth/assets/40280381/58cea0b1-42cc-4b14-b07d-e419b652526d">

**Comment by diasmashikov** [comment]
If anyone is facing problems with getting the MongoDBAdapter, then listen to this:

My problem was that my MongoDBAdapter required the client connection to let it operate with the DB, however, I provided it with the Mongoose connection that would not let me work with it. So, if you are facing this situation, just create a separate file for the MongoClient connection and insert instead. 

Here is the code for the MongoDB client connection

`import { MongoClient } from "mongodb";

if (!process.env.MONGODB_URI) {
  throw new Error('Invalid/Missing environment variable: "MONGODB_URI"');
}

const uri = process.env.MONGODB_URI;
const options = {};

let client;
let mongoClientConnection: Promise<MongoClient>;

if (process.env.NODE_ENV === "development") {
  let globalWithMongo = global as typeof globalThis & {
    _mongoClientPromise?: Promise<MongoClient>;
  };

  if (!globalWithMongo._mongoClientPromise) {
    if (!globalWithMongo._mongoClientPromise) {
      client = new MongoClient(uri, options);
      globalWithMongo._mongoClientPromise = client.connect();
    }
  }
  mongoClientConnection = globalWithMongo._mongoClientPromise;
} else {
  client = new MongoClient(uri, options);
  mongoClientConnection = client.connect();
}

export default mongoClientConnection;
`

**Comment by lenvaz** [comment]
To resolve the issue, one of the ways is to make sure that you have the latest prisma models from [here](https://authjs.dev/getting-started/adapters/prisma?_gl=1*1v5ag1f*_gcl_au*NzE3MjY4MDg4LjE3MTMyNDYxOTYuMTc3ODIyNjg2NC4xNzE1MTA3NzI1LjE3MTUxMDc3MjU.)

**Comment by EliasTouil** [comment]
In my case with **Drizzle and Github within the T3 stack**, I had forgotten to enable the email scope in the GitHub app which caused the email field to be undefined upon signup.

To fix it, go to your github app, open the Permissions and events tab, in the accounts permissions section, select email "read only". 

I'll leave my schema here for reference:

```typescript
// auth.ts

// ... 

export const authOptions: NextAuthOptions = {
  callbacks: {
    // ...
  },
  adapter: DrizzleAdapter(db, {
    usersTable: users,
    accountsTable: accounts,
    sessionsTable: sessions,
    verificationTokensTable: verificationTokens,
  }) as Adapter,
  providers: [
    GithubProvider({
      clientId: env.GITHUB_CLIENT_ID,
      clientSecret: env.GITHUB_CLIENT_SECRET,
    }),
  ],
  secret: env.NEXTAUTH_SECRET,
};

```

```typescript
//schema.ts

import { relations, sql } from "drizzle-orm";
import {
  index,
  integer,
  pgTableCreator,
  primaryKey,
  text,
  timestamp,
  varchar,
  serial,
  uuid,
} from "drizzle-orm/pg-core";

import { type AdapterAccount } from "next-auth/adapters";

/**
 * This is an example of how to use the multi-project schema feature of Drizzle ORM. Use the same
 * database instance for multiple projects.
 *
 * @see https://orm.drizzle.team/docs/goodies#multi-project-schema
 */
export const createTable = pgTableCreator((name) => `poke-${name}`);

export const posts = createTable(
  "post",
  {
    id: serial("id").primaryKey(),
    name: varchar("name", { length: 256 }),
    createdById: uuid("createdById")
      .notNull()
      .references(() => users.id),
    createdAt: timestamp("created_at", { withTimezone: true })
      .default(sql`CURRENT_TIMESTAMP`)
      .notNull(),
    updatedAt: timestamp("updatedAt", { withTimezone: true }),
  },
  (example) => ({
    createdByIdIdx: index("createdById_idx").on(example.createdById),
    nameIndex: index("name_idx").on(example.name),
  }),
);

export const users = createTable("user", {
  id: uuid("id").defaultRandom().notNull().primaryKey(),
  name: varchar("name", { length: 255 }),
  email: varchar("email", { length: 255 }).unique().notNull(),
  emailVerified: timestamp("emailVerified", {
    mode: "date",
    withTimezone: true,
  }).default(sql`CURRENT_TIMESTAMP`),
  image: text("image"),
});

export const usersRelations = relations(users, ({ many }) => ({
  accounts: many(accounts),
}));

export const accounts = createTable(
  "account",
  {
    userId: uuid("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: varchar("type", { length: 255 })
      .$type<AdapterAccount["type"]>()
      .notNull(),
    provider: text("provider").notNull(),
    providerAccountId: text("providerAccountId").notNull(),
    refresh_token: text("refresh_token"),
    access_token: text("access_token"),
    expires_at: integer("expires_at"),
    token_type: text("token_type"),
    scope: text("scope"),
    id_token: text("id_token"),
    session_state: text("session_state"),
  },
  (account) => ({
    compoundKey: primaryKey({
      columns: [account.provider, account.providerAccountId],
    }),
  }),
);

export const accountsRelations = relations(accounts, ({ one }) => ({
  user: one(users, { fields: [accounts.userId], references: [users.id] }),
}));

export const sessions = createTable(
  "session",
  {
    sessionToken: varchar("sessionToken", { length: 255 })
      .notNull()
      .primaryKey(),
    userId: uuid("userId")
      .notNull()
      .references(() => users.id),
    expires: timestamp("expires", {
      mode: "date",
      withTimezone: true,
    }).notNull(),
  },
  (session) => ({
    userIdIdx: index("session_userId_idx").on(session.userId),
  }),
);

export const sessionsRelations = relations(sessions, ({ one }) => ({
  user: one(users, { fields: [sessions.userId], references: [users.id] }),
}));

export const verificationTokens = createTable(
  "verificationToken",
  {
    identifier: varchar("identifier", { length: 255 }).notNull(),
    token: varchar("token", { length: 255 }).notNull(),
    expires: timestamp("expires", {
      mode: "date",
      withTimezone: true,
    }).notNull(),
  },
  (vt) => ({
    compoundKey: primaryKey({ columns: [vt.identifier, vt.token] }),
  }),
);
```

**Comment by DMaskin** [comment]
Your version is old. It should be <i>provider_providerAccountId</i> <br/>
Last actual document: <br/>
https://authjs.dev/reference/adapter/prisma

Update prisma schema and run the migration should fix it:
1. npx prisma generate
2. npx prisma migrate dev

**Comment by muditgoel01** [comment]
Make sure you are also setting the following values in your .env file:

```
NEXTAUTH_URL="http://localhost:3000" # or your prod url

NEXTAUTH_SECRET="type-some-random-string-here" # don't leave empty
```

**Comment by WillMoody27** [comment]
> **Describe the bug** When trying to sign in to GitHub it says "Try signing with a different account."
> 
> **Steps to reproduce**
> 
> * Clone orangopus/libby
> * click "Login"
> * Click "Sign in with GitHub"
> 
> Make sure to include the client ID and secret in .env as `GITHUB_ID` and `GITHUB_SECRET`
> 
> **Expected behavior** I expected it to login and return to the app.
> 
> **Screenshots or error logs** The error is ![browser_7MIk0bI7BK](https://user-images.githubusercontent.com/45247477/104529167-fc6e2e00-5600-11eb-8127-f78be5dd7ca9.png)
> 
> **Feedback** _Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example)._
> 
> * [x]  Found the documentation helpful[ ]  Found documentation but was incomplete[ ]  Could not find relevant documentation[x]  Found the example project helpful[ ]  Did not find the example project helpful

this worked like a charm in 2025. Thank you!
