### ISSUE TITLE
Prisma adapter not creating Session and Account correctly due to wrong prisma.create() syntax

### ISSUE THREAD

**Issue by DevNvll** [nextauthjs/next-auth#3831]
**Describe the bug**
The Prisma adapter is not creating Session and Account correctly due to wrong prisma.account.create() syntax.

**Steps to reproduce**
Create new project with with-prisma example.
Add any provider (in my case, discord)
Try to login.

https://github.com/nextauthjs/next-auth/tree/docs/examples/examples/with-prisma

**Expected behavior**
Create a new account and session and not return a error

**Screenshots or error logs**
![image](https://user-images.githubusercontent.com/3536261/93781623-f2629280-fbff-11ea-811b-42390c61d269.png)
![image](https://user-images.githubusercontent.com/3536261/93782424-efb46d00-fc00-11ea-873f-217d72e0387e.png)
Same happens while creating session.

**Additional context**
I managed to fix the bug creating a new adapter and using the connect: {} prop in the prisma.account.create({}) in both linkAccount() and createSession() methods, but I could not set up a local dev environment to test and submit a pull request, so I'm submitting this bug report.
![image](https://user-images.githubusercontent.com/3536261/93781697-07d7bc80-fc00-11ea-979f-1094b81c4896.png)

**Comment by ndom91** [comment]
`nextauthjs/next-auth` has been migrated to a monorepository. The adapters code can now be found there under `packages/adapter-*`. Thanks for your interest in the project!

**Comment by bananabrann** [comment]
@ndom91 
> `nextauthjs/next-auth` has been migrated to a monorepository. The adapters code can now be found there under `packages/adapter-*`. Thanks for your interest in the project!

I'm still having issues, but I don't know if it's the prisma connector. Right now I have
```ts
// /pages/api/auth/[...nextauth].ts

...
import { NextApiHandler } from 'next';
import NextAuth from 'next-auth';
import { PrismaAdapter } from '@next-auth/prisma-adapter';
import GitHubProvider from 'next-auth/providers/github';
import { PrismaClient } from '@prisma/client';
...

const prisma = new PrismaClient()
const authHandler: NextApiHandler = (req, res) => NextAuth(req, res, options);
export default authHandler;

const options = {
  providers: [
   ...
  ],
  adapter: PrismaAdapter(prisma),
};

```

Are you saying you have to change the import?

**Comment by ndom91** [comment]
> @ndom91 
> > `nextauthjs/next-auth` has been migrated to a monorepository. The adapters code can now be found there under `packages/adapter-*`. Thanks for your interest in the project!
> 
> I'm still having issues, but I don't know if it's the prisma connector. Right now I have
> ```ts
> // /pages/api/auth/[...nextauth].ts
> 
> ...
> import { NextApiHandler } from 'next';
> import NextAuth from 'next-auth';
> import { PrismaAdapter } from '@next-auth/prisma-adapter';
> import GitHubProvider from 'next-auth/providers/github';
> import { PrismaClient } from '@prisma/client';
> ...
> 
> const prisma = new PrismaClient()
> const authHandler: NextApiHandler = (req, res) => NextAuth(req, res, options);
> export default authHandler;
> 
> const options = {
>   providers: [
>    ...
>   ],
>   adapter: PrismaAdapter(prisma),
> };
> 
> ```
> 
> Are you saying there's a change in how it's implemented? 

No, this was just a generic message that the source code has been moved. The package names on npm, for example, and the usage instructions stayed the same. 

Can you elaborate on what problem you're seeing exactly? As this issues been open for a while.. 

Any error messages or similar output would be helpful. Thanks!

**Comment by bananabrann** [comment]
@ndom91 no problems anymore, but it was the same as the OP. Thanks!

For me, the issue was [the guide I was following on Vercel's website](https://vercel.com/guides/nextjs-prisma-postgres) referenced the id of Session being `Int`, where as the [nextauth docs clearly state](https://next-auth.js.org/adapters/prisma) it should be a `String`. 

Switching that (and the other nextauth models) to `String` and rerunning the migrations fixed everything.

**Comment by ndom91** [comment]
This issue seems to have been taken care of in the latest releases, when following the Schema provided in our docs.

I also opened a discussion with Prisma to update that Vercel guide with the correct Schema.

Goign to close this issue for now then.
