### ISSUE TITLE
Version 3.0 Beta

### ISSUE THREAD

**Issue by iaincollins** [nextauthjs/next-auth#384]
Version 3.0 has now been published.

[Please see the release notes for details.](https://github.com/nextauthjs/next-auth/releases/tag/v3.0.0)

**Comment by ThePaulMcBride** [comment]
I've been trying out V3 for a few days an using it with Prisma. This is so good! I've ran into an issue I want to share with you. I'm pretty sure it's an issue with next-auth, but I could be doing something stupid.

I'm using the email provider for signin and I get the following error when I click the link in the email

```js
Invalid `prisma[User].update()` invocation in
/Users/paul/Code/job-hub/node_modules/next-auth/dist/adapters/prisma/index.js:179:33

  175   id
  176 } = user,
  177     rest = _objectWithoutProperties(user, ["id"]);
  178 
→ 179 return prisma[User].update({
        where: {
          id: 'ffd1eb31-da10-4bf6-bef1-ae3c8fd6485e'
        },
        data: {
          email: 'myemail@email.com',
          emailVerified: new Date('2020-07-19T12:50:04.822Z'),
          image: 'https://avatars0.githubusercontent.com/u/1234',
          name: 'My name,
          defaultCompanyId: null,
          ~~~~~~~~~~~~~~~~
          createdAt: new Date('2020-07-19T12:30:32.251Z'),
          updatedAt: new Date('2020-07-19T12:30:32.251Z')
        }
      })

Unknown arg `defaultCompanyId` in data.defaultCompanyId for type UserUpdateInput. Did you mean `defaultCompany`? Available args:
type UserUpdateInput {
  id?: String
  email?: String
  emailVerified?: DateTime
  image?: String
  name?: String
  createdAt?: DateTime
  updatedAt?: DateTime
  sessions?: SessionUpdateManyWithoutUserInput
  accounts?: AccountUpdateManyWithoutUserInput
  companies?: CompanyUserUpdateManyWithoutUserInput
  defaultCompany?: CompanyUpdateOneWithoutCurrentUsersInput
}
```

This is my schema file.

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id               String        @default(uuid()) @id
  email            String?       @unique
  emailVerified    DateTime?
  image            String?
  name             String?
  sessions         Session[]
  accounts         Account[]
  companies        CompanyUser[]
  defaultCompany   Company?      @relation("DefaultCompany", fields: [defaultCompanyId], references: [id])
  defaultCompanyId String?
  createdAt        DateTime      @default(now())
  updatedAt        DateTime      @updatedAt @default(now())
}

model Session {
  id                 String    @default(uuid()) @id
  userId             String
  user               User      @relation(fields: [userId], references: [id])
  accessToken        String    @default(cuid()) @unique
  sessionToken       String    @default(cuid()) @unique
  accessTokenExpires DateTime?
  expires            DateTime?
  createdAt          DateTime  @default(now())
  updatedAt          DateTime  @updatedAt @default(now())
}

model Account {
  id                 String    @default(uuid()) @id
  compoundId         String    @unique
  userId             String
  user               User      @relation(fields: [userId], references: [id])
  providerId         String
  providerType       String
  providerAccountId  String    @unique
  refreshToken       String?
  accessToken        String?
  accessTokenExpires DateTime?
  createdAt          DateTime  @default(now())
  updatedAt          DateTime  @updatedAt @default(now())
}

model VerificationRequest {
  id         String   @default(uuid()) @id
  identifier String
  token      String   @unique
  expires    DateTime
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt @default(now())
}

model Company {
  id                 String        @default(uuid()) @id
  users              CompanyUser[]
  title              String
  plan               String?
  subscriptionStatus String?
  stripeCustomerId   String?       @unique
  currentUsers       User[]        @relation("DefaultCompany")
  createdAt          DateTime      @default(now())
  updatedAt          DateTime      @updatedAt @default(now())
}

model CompanyUser {
  user      User    @relation(fields: [userId], references: [id])
  userId    String
  company   Company @relation(fields: [companyId], references: [id])
  companyId String

  @@id([userId, companyId])
}
```

So I have add the default tables as suggested, but I've extended them a little. I'm only getting this error when signing in with email and it seems fine when signing in with the Github provider.

I'm more than happy to help debug this! Let me know if I can help in any way!

**Comment by Fumler** [comment]
@ThePaulMcBride I'm not sure how it's getting the `defaultCompanyId` passed as `null`, I assume that's something you are doing in your code? As for the problem, my first thought is that it might be because the field is being passed as null, while you have defined `defaultCompany` as a relation in your prisma model, so it would require something like this instead:

```javascript
...
defaultCompany: {
  connect: {
    id: 'something'
  }
}
```

So try deleting the `defaultCompanyId` field instead of passing in `null`, or maybe even `undefined` might work.

**Comment by ThePaulMcBride** [comment]
I’m not sure where I’d change that. This error is thrown as part of the login flow. I don’t think any of my code is ran there, it’s all in nex-auth.

The `defaultCompanyId` is the foreign key for a related model. Is it possible the way next-auth updates the user model on sign in does not play nicely with how prisma expats relations ships to be saved; i.e. setting the foreign key directly instead of using a connect query?

**Comment by Fumler** [comment]
> I’m not sure where I’d change that. This error is thrown as part of the login flow. I don’t think any of my code is ran there, it’s all in nex-auth. The `defaultCompanyId` is the foreign key for a related model. Is it possible the way next-auth updates the user model on sign in does not play nicely with how prisma expats relations ships to be saved; i.e. setting the foreign key directly instead of using a connect query?

Doing the update, next-auth first gets the user by email https://github.com/iaincollins/next-auth/blob/v3/src/adapters/prisma/index.js#L70 - and then we pass in the data from that. I guess we can be explicit in the `updateUser` call from next-auth to only use fields we know of, as I believe this is only used for the email callback right now

**Comment by ThePaulMcBride** [comment]
That sounds about right! Is there anything I can do to help make that change?

**Comment by iaincollins** [comment]
Update on the Prisma issue: The above issue (and a couple of others) should be resolved now.

**Comment by iaincollins** [comment]
Version 3.0.0 is now released.
