### ISSUE TITLE
TypeScript error when disabling JWT encryption

### ISSUE THREAD

**Issue by breyed** [nextauthjs/next-auth#3847]
### Description 🐜

When I added the [JWT option](https://next-auth.js.org/configuration/options#jwt) sample stub functions for disabling JWT encryption to `[...nextauth].ts`, I got a TypeScript error.

### Is this a bug in your own project?

No

### How to reproduce ☕️

Add to `[...nextauth].ts`:

``` ts
jwt: {
  async encode({ secret, token, maxAge }) {},
  async decode({ secret, token }) {},
}
```

### Screenshots / Logs 📽

> Type '({ secret, token, maxAge }: JWTEncodeParams) => Promise<void>' is not assignable to type '(params: JWTEncodeParams) => Awaitable<string>'.
>   Type 'Promise<void>' is not assignable to type 'Awaitable<string>'.
>     Type 'Promise<void>' is not assignable to type 'PromiseLike<string>'.
>       Types of property 'then' are incompatible.
>         Type '<TResult1 = void, TResult2 = never>(onfulfilled?: ((value: void) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<...>) | null | undefined) => Promise<...>' is not assignable to type '<TResult1 = string, TResult2 = never>(onfulfilled?: ((value: string) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<...>) | null | undefined) => PromiseLike<...>'.
>           Types of parameters 'onfulfilled' and 'onfulfilled' are incompatible.
>             Types of parameters 'value' and 'value' are incompatible.
>               Type 'void' is not assignable to type 'string'.

#### System:
 - OS: macOS 12.2
 - CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
 - Memory: 511.94 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
#### Binaries:
 - Node: 16.13.2 - /usr/local/bin/node
 - Yarn: 1.22.15 - /usr/local/bin/yarn
 - npm: 8.4.1 - /usr/local/bin/npm
#### Browsers:
 - Chrome: 98.0.4758.80
 - Safari: 15.3
#### npmPackages:
 - next: ^12.0.10 => 12.0.10 
 - next-auth: ^4.2.1 => 4.2.1 
 - react: ^17.0.2 => 17.0.2 

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment]
You still have to encode/decode the token, i.e. return an encoded/decoded version of the incoming `token`. So the TypeScript type is correct.
