### ISSUE TITLE
Ad-hoc “hard” refresh of JWT

### ISSUE THREAD

**Issue by adamelmore** [nextauthjs/next-auth#3855]
### Description 📓

I’m using JWTs with a backing database (DynamoDB) and my serverless backend makes changes to the user records directly. In that scenario, I’d like to call `GET /api/auth/session` with a query parameter (`/api/auth/session?latest=true`?) and have the JWT callback receive the latest `user` record from the adapter.

### How to reproduce ☕️

NA

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by adamelmore** [comment]
Related to #3648 but in my case I don’t need to call `updateUser` as the user has already been updated by an external process.

**Comment by adamelmore** [comment]
Thoughts on this, @balazsorban44? Would this be a welcome change? Anything I'm overlooking?

**Comment by balazsorban44** [comment]
Haven't had the time to think about it before yet :pray:.

What I would do is in the `jwt` callback, simply set a "lifetime" for the validity, and after that, just go and fetch the new user data. Very similar to refresh token rotation:
https://next-auth.js.org/tutorials/refresh-token-rotation

If you want to update the user data _immediatelly_, you could already achieve what you propose through https://next-auth.js.org/configuration/initialization#advanced-initialization

Just check when the request is going to `/api/auth/session` and have the `?latest` query parameter, and make the call in the `jwt` callback then.
