### ISSUE TITLE
FaunaDB Adapter Setup -- Fauna Shell Commands Fail

### ISSUE THREAD

**Issue by zpg6** [nextauthjs/next-auth#3858]
### Title

Fauna Adapter Setup -- Fauna Shell Commands Fail

### How to reproduce ☕️

When using documentation-provided Fauna shell commands, the **collections are created but not the indexes**. You receive this error.

```
Error: [
  {
    "position": [],
    "code": "validation failed",
    "description": "document data is not valid.",
    "failures": [
      {
        "field": [
          "source"
        ],
        "code": "invalid reference",
        "description": "Cannot read reference."
      }
    ]
  }
]
```

### Your question/bug report 📓

The solution is to separately run the CreateCollection calls altogether, then run the CreateIndex calls altogether.

In other words, just a documentation change from one block to two blocks of commands to run. Maybe a sentence clarifying that they are to be run separately.

### Contributing  🙌🏽

Yes, I am

**Comment by zpg6** [comment]
As reproduced on FaunaDB console:

<img width="579" alt="image" src="https://user-images.githubusercontent.com/17848742/152698676-b4e5d1f3-c805-427a-9844-dd54d095f5cd.png">

**Comment by zpg6** [comment]
If someone can confirm the error + solution proposed, I'm more than happy to submit a PR. If/once maintainers are done with their monorepo migration that is.

**Comment by edizyurdakul** [comment]
Hi! I had the same issue I think we need to separate creating indexes and creating collections, and it worked for me so first create the collections 

`CreateCollection({ name: "accounts" })
CreateCollection({ name: "sessions" })
CreateCollection({ name: "users" })
CreateCollection({ name: "verification_tokens" })`

after running this in the shell continue with: 

`CreateIndex({
  name: "account_by_provider_and_provider_account_id",
  source: Collection("accounts"),
  unique: true,
  terms: [
    { field: ["data", "provider"] },
    { field: ["data", "providerAccountId"] },
  ],
})
CreateIndex({
  name: "session_by_session_token",
  source: Collection("sessions"),
  unique: true,
  terms: [{ field: ["data", "sessionToken"] }],
})
CreateIndex({
  name: "user_by_email",
  source: Collection("users"),
  unique: true,
  terms: [{ field: ["data", "email"] }],
})
CreateIndex({
  name: "verification_token_by_identifier_and_token",
  source: Collection("verification_tokens"),
  unique: true,
  terms: [{ field: ["data", "identifier"] }, { field: ["data", "token"] }],
})`

Hope it works for you!

**Comment by balazsorban44** [comment]
Yep, docs should be alright! :pray:


_Still thinking through the automation of versioning/publishing of packages, but that does not affect the docs site._
