### ISSUE TITLE
Incompatibility with `path` module

### ISSUE THREAD

**Issue by xinmingzh** [nextauthjs/next-auth#3898]
### Description 🐜

When `path` module is included as dependency in package.json, navigating to login works normally but fails when middleware is used in nextjs.

Error shown in terminal:
[next-auth][error][NO_SECRET] 
https://next-auth.js.org/errors#no_secret

This happens even when NEXTAUTH_SECRET is correctly specified in .env.local file

### Is this a bug in your own project?

No

### How to reproduce ☕️

1. Clone template from github.com/nextauthjs/next-auth-example
2. In package.json depedencies add "path": "^0.12.7"
3. Follow instructions to npm install, create .env.local and specify NEXTAUTH_SECRET
4. npm run dev
5. Navigate to localhost:3000/me (controlled by default next-auth middleware)
6. Observe error shown

### Environment 🖥

System:
  OS: Windows 10 10.0.22000
  CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
  Memory: 15.20 GB / 31.91 GB
Binaries:
  Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
  npm: 8.4.1 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Edge: Spartan (44.22000.120.0), Chromium (98.0.1108.43)
  Internet Explorer: 11.0.22000.120
npmPackages:
  next: ^12.0.10 => 12.0.10
  next-auth: latest => 4.2.1
  react: ^17.0.2 => 17.0.2

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
`path` is a Node.js built-in. You should not need to install it.
