### ISSUE TITLE
Update suggested ways of securing pages and API routes

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#3973]
In https://github.com/vercel/next.js/issues/34316#issuecomment-1039037314 I concluded that `getInitialProps` really does not play well with our auth model. There are simply much better solutions for this now.

We should discourage the usage of it entirely.

https://next-auth.js.org/tutorials/securing-pages-and-api-routes should be updated to also mention [Middleware support](https://next-auth.js.org/configuration/nextjs#middleware) and finally decide how and where we should document `getServerSession` (#1535)

**Comment by ndom91** [comment]
In terms of where we should document `getServerSession`, I feel like in the [client](https://next-auth.js.org/getting-started/client#getsession) page by where `getSession` is would make a lot of sense, no?

I'd also link where we say "Client Side: yes, Server Side: yes" under `getSession`, to `getServerSession` instead of "Server side: yes" under `getSession`. Know what I mean?

**Comment by balazsorban44** [comment]
I'm not really sure actually. I want the Client page to go away mostly, or document how a framework-specific client should be implemented (similar to how we have the REST API docs).

`getServerSession` is Next.js specific, so I might put it under https://next-auth.js.org/configuration/nextjs probably.

**Comment by ndom91** [comment]
I think we can close this issue. We've got these two PRs out:

- https://github.com/nextauthjs/next-auth/pull/3982
- https://github.com/nextauthjs/next-auth/pull/4116

What do you think?

**Comment by urtheaman** [comment]
> 
i think documentation structure need a refresh. it's designed in the same old school fashion.

**Comment by ndom91** [comment]
@urtheaman we're always open for suggestions - what were you thinking specifically?

**Comment by ifonefox** [comment]
Now that this issue is closed, what's going to happen two the 2 PRs mentioned earlier? (#4116 and #3982)
