### ISSUE TITLE
Modify session from API Route

### ISSUE THREAD

**Issue by matbee-eth** [nextauthjs/next-auth#3981]
### Question 💬

I've implemented Sign In With Ethereum, and I want to add the users web3 information to their session. It doesn't seem to save the session data, whatsoever.

### How to reproduce ☕️

```
//#pages/api/verify.ts

const handler = async (req: NextApiRequest, res: NextApiResponse) => {
  const { method } = req
  const session = await getSession({req});
  switch (method) {
    case 'POST':
      try {
        const { message, signature } = req.body
        const siweMessage = new SiweMessage(message)
        const fields = await siweMessage.validate(signature)
        session.walletAddress = fields.address;
        session.user.walletAddress = fields.address;
        console.info(session, session.walletAddress);
        res.json({ ok: true })
      } catch (_error) {
        res.json({ ok: false })
      }
      break
    default:
      res.setHeader('Allow', ['POST'])
      res.status(405).end(`Method ${method} Not Allowed`)
  }
}```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
You are not really saving anything, just adding some properties to an intermediate object inside an API route. `session` must be saved as a cookie to actually persist, and currently, we don't expose a way to modify it other than the `jwt` callback. https://next-auth.js.org/configuration/callbacks#jwt-callback

Also, it might not really make sense to update a session when only using the JWT strategy. See: https://github.com/nextauthjs/next-auth/discussions/3941#discussioncomment-2165271

**Comment by mathieug-minogames** [comment]
If there was a way to modify the JWT, that would work fine for me too
