### ISSUE TITLE
Error page redirection fails if error parameter contains special characters

### ISSUE THREAD

**Issue by ForInfinity** [nextauthjs/next-auth#3986]
### Environment

  System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 20.04 GB / 24.88 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 17.1.0 - ~/.nvm/versions/node/v17.1.0/bin/node
    Yarn: 1.22.15 - /usr/bin/yarn
    npm: 8.1.4 - ~/.nvm/versions/node/v17.1.0/bin/npm
  npmPackages:
    next: 12.0.10 => 12.0.10
    next-auth: ^4.2.1 => 4.2.1
    react: 17.0.2 => 17.0.2

### Reproduction URL

https://github.com/ForInfinity/next-auth-redirection-issue/tree/main/pages

### Describe the issue

When a CredentialsProvider throw an error that contains special characters like `%0A` (already URI encoded to show it), a error will be throwen:

```
Server Error
TypeError: Invalid character in header content ["Location"]

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
ServerResponse.setHeader
node:_http_outgoing (579:3)
NextAuthNextHandler
file:///home/xiao/next-oneindex-oss/node_modules/next-auth/next/index.js (43:23)
runMicrotasks
<anonymous>
processTicksAndRejections
node:internal/process/task_queues (96:5)
async
file:///.../node_modules/next-auth/next/index.js (57:32)
async Object.apiResolver
file:///.../node_modules/next/dist/server/api-utils.js (101:9)
async DevServer.runApi
file:///.../node_modules/next/dist/server/next-server.js (320:9)
async Object.fn
file:///.../node_modules/next/dist/server/base-server.js (486:37)
async Router.execute
file:///.../node_modules/next/dist/server/router.js (228:32)
async DevServer.run
file:///.../node_modules/next/dist/server/base-server.js (598:29)
```
![Error](https://user-images.githubusercontent.com/31365560/154307600-73144b92-0fff-41bb-9192-3e13b8d751e3.png)

### How to reproduce

1. Add a customized error page in config
```typescript
export default NextAuth({
    // ...
    pages: {
        error: "/error", // here set customized error page.
    },
})
```
2. Add a CredentialsProvider
```typescript
        CredentialsProvider({
            name: "test provider",
            credentials: {
                username: {label: "Username", type: "text", placeholder: "Enter your username"},
            },
            authorize: async (credentials) => {
                // here throw an error with special characters to test the error handling
                // which is actually an error message from package Prisma.
                if (credentials)
                    throw new Error(decodeURI(
                        "%0AInvalid%20%60prisma.user.count()%60%20invocation%3A%0A%0A%0A%20%20The%20table%20%60main.User%60%20does%20not%20exist%20in%20the%20current%20database.")
                    )
                else
                    return null;
            }
        })
```

### Expected behavior

User should be successfully redirected from `/api/auth/error?error=...` to customized error page.

**Comment by ForInfinity** [comment]
I guess, query string `error` in this line may be not uri encoded?
https://github.com/nextauthjs/next-auth/blob/a72f1b6d21da89b4223542006c865862635c027b/packages/next-auth/src/core/index.ts#L159-L166

**Comment by balazsorban44** [comment]
I don't think this is a NextAuth.js anyway, but I'm not sure why would you throw an error like that onto the user. 

It's probably a security risk even. You should just log the error to your log service and send a code to the user, like "invalid credentials" or similar. We don't recommend being too specific about the error: https://next-auth.js.org/configuration/pages#sign-in-page
