### ISSUE TITLE
Twitter provider: accessToken and secretToken missing 

### ISSUE THREAD

**Issue by doorman02** [nextauthjs/next-auth#3987]
### Provider type

Twitter

### Environment

System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 7.08 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 97.1.34.81
    Chrome: 98.0.4758.80
    Safari: 15.2
  npmPackages:
    next: 12.0.10 => 12.0.10 
    next-auth: ^4.2.1 => 4.2.1 
    react: 17.0.2 => 17.0.2 

### Reproduction URL

not available

### Describe the issue

I am signing in using the Twitter provider and I need to read the accessToken and secretToken within the callback:

```
  async session({ session, user, token }) {
console.log(token.accessToken);
console.log(token.secretToken);
return session;
}
```
However the token object only contains the following properties:

```
{
  name: 'myUser1',
  picture: 'https://urltoprofileimage',
  sub: '2342342345345345',
  iat: 1345345345,
  exp: 1345345345,
  jti: 'aad83348-a382-fbar-9us2-52dr3582ds'
}

```
this used to work in version 3.27.0 before I updated to version 4. Thanks! 

### How to reproduce

Use signin('Twitter') to signin using the Twitter provider. Log the token object within the sesison callback.

### Expected behavior

The token object should contain the access and secretToken.

**Comment by balazsorban44** [comment]
They have been renamed to reflect the OAuth 1 spec. `oauth_token` and `oauth_token_secret`.

Tip, you can now use Twitter with OAuth 2 as well https://next-auth.js.org/providers/twitter#oauth-2

**Comment by doorman02** [comment]
@balazsorban44 thanks for the suggestions. I need to use OAuth 1 because I acting on behalf of a Twitter account. However when I get the token the callback has only the following properties. There is no oauth_token or oauth_token_secret. Any idea why the properties are missing?

```
{
  name: 'myUser1',
  picture: 'https://urltoprofileimage',
  sub: '2342342345345345',
  iat: 1345345345,
  exp: 1345345345,
  jti: 'aad83348-a382-fbar-9us2-52dr3582ds'
}
```
