### ISSUE TITLE
Add support for updating AccessTokens

### ISSUE THREAD

**Issue by iaincollins** [nextauthjs/next-auth#4]
Add a method which auto-updates AccessTokens for APIs which support rotating tokens (like Google) automatically, whenever the current AccessToken expires.

This would be useful for anyone who wants to make API calls as a user once they have signed in with an oAuth service.

I already have handlers to do this, I just need to import them into the project.

**Comment by geraldnolan** [comment]
I know this is a couple of years old. Any chance you can send these handlers to me?  I need to be able to update an AccessToken and was looking at [https://github.com/fiznool/passport-oauth2-refresh](https://github.com/fiznool/passport-oauth2-refresh)

Separate note:  Will NextAuth V2 work OpenID Connect and OAuth 2.0?

**Comment by tommoor** [comment]
I've found that the `access_token` field on account is never updated – is this what you're referring to? Even if I sign out and sign in again and the service gives me a new access token the field in `account.access_token` retains the old value.

**Comment by ndom91** [comment]
@geraldnolan the original issue / post by iain was referring to next-authv1, im assuming. v2 / v3 has been a complete rewrite since then. v3 is now released and contains support for OpenID Connect / many other oauth 2.0 providers / custom oauth 2.0 providers as well.
