### ISSUE TITLE
how to handle basepath?

### ISSUE THREAD

**Issue by rhufsky** [nextauthjs/next-auth#4009]
### Question 💬

I have an app that authenticates against Azure AD using next-auth 4. 
It works fine and I can authenticate.

When I try to configure a custom base path `http://localhost:3000/myapp` for the app and call `signIn()` I get a 404 error telling me that `http://localhost:3000/api/auth/error` is not found.

I have configured all the paths like described below.

What confuses me:

- If I use the standard path I notice that [...nextauth.js] gets executed
- If I use a custom path, [...nextauth.js] is not even executed

A similar scenario in next.auth 3 worked just fine.

Comparing to next-auth 3 it looks like next-auth 4 does not honor NEXTAUTH_URL.

What can I do?

.env.local
```
AZURE_CLIENT_ID= ....
AZURE_CLIENT_SECRET=...
AZURE_TENANT_ID=...

JWT_SECRET=...

NEXTAUTH_URL=http://localhost:3000/myapp/api/auth
NEXTAUTH_URL_INTERNAL=http://localhost:3000/mypp/api/auth
NEXT_AUTH_DEBUG=true

APP_BASE_PATH=/myapp
```

next.config.js:

```
const basePath = process.env.APP_BASE_PATH;

module.exports = {
  reactStrictMode: true,
  basePath: `${basePath}`,
};

```
[...nextauth.js]`

```

export default NextAuth({
  providers: [
    AzureADProvider({
      clientId: process.env.AZURE_CLIENT_ID,
      clientSecret: process.env.AZURE_CLIENT_SECRET,
      scope: "offline_access User.Read",
      tenantId: process.env.AZURE_TENANT_ID,
    }),
  ],
....
  debug: process.env.NEXT_AUTH_DEBUG,
  secret: process.env.JWT_SECRET,
});
```

### How to reproduce ☕️

.env.local
```
AZURE_CLIENT_ID= ....
AZURE_CLIENT_SECRET=...
AZURE_TENANT_ID=...

JWT_SECRET=...

NEXTAUTH_URL=http://localhost:3000/myapp/api/auth
NEXTAUTH_URL_INTERNAL=http://localhost:3000/mypp/api/auth
NEXT_AUTH_DEBUG=true

APP_BASE_PATH=/myapp
```

next.config.js:

```
const basePath = process.env.APP_BASE_PATH;

module.exports = {
  reactStrictMode: true,
  basePath: `${basePath}`,
};

```
[...nextauth.js]`

```

export default NextAuth({
  providers: [
    AzureADProvider({
      clientId: process.env.AZURE_CLIENT_ID,
      clientSecret: process.env.AZURE_CLIENT_SECRET,
      scope: "offline_access User.Read",
      tenantId: process.env.AZURE_TENANT_ID,
    }),
  ],
....
  debug: process.env.NEXT_AUTH_DEBUG,
  secret: process.env.JWT_SECRET,
});
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Hi, we noticed this is a very unused feature, but the docs could be better around this.

It should be mentioned here: https://next-auth.js.org/getting-started/client#options

Basically, you will need to pass the basePath to `SessionProvider` as a prop.

Source code is here: https://github.com/nextauthjs/next-auth/blob/fb8874d6d8fd52385e34c1be5ef0ad655c28428f/packages/next-auth/src/react/index.tsx#L300

For more context, I've been thinking about how to make this better. One option is `NEXT_PUBLIC_NEXTAUTH_URL`, the other is using the `env` option in `next.config.js`.

https://github.com/nextauthjs/next-auth/issues/1713

**Comment by robertwbradford** [comment]
As a note, the `basePath` value is now available from Next's `useRouter` hook: https://nextjs.org/docs/api-reference/next/router#router-object. (I didn't look to see which version of Next introduced this.) Perhaps `SessionProvider` could automatically pull it from there.
