### ISSUE TITLE
Prisma Adapter on MongoDB errors out when updating user after login

### ISSUE THREAD

**Issue by ferrohd** [nextauthjs/next-auth#4030]
### Adapter type

@next-auth/prisma-adapter

### Environment

- next: 12.1.0
- next-auth: 4.2.1
- @next-auth/prisma-adapter: 1.0.1
- react: 17.0.2

### Reproduction URL

https://gist.github.com/ferrohd/d769b39194f03844d18e2bcfe85a61e6

### Describe the issue

I'm using PrismaAdapter with MongoDB as underlying database. I don't know if it's because of the prisma.model I'm using, but Prisma doesn't allow to update the "id" field of a document in a collection. When logging-in with an already registered user, the `updateUser` function is called, and tries to update the `emailVerified` field in the User model.

The `data` argument passed to the function has values:
```typescript
{
      id: '62057f64643a91216fcd9f73', // id of the user to update
      emailVerified: 2022-02-21T08:43:23.333Z
}
```
The implementation of updateUser in @next-auth/prisma-adapter ([here](https://github.com/nextauthjs/next-auth/blob/3ec3761634f7953acc52d460e8bb0b2a678d7703/packages/adapter-prisma/src/index.ts#L16)) passes all the data to the update method, including the id
```typescript
updateUser: (data) => p.user.update({ where: { id: data.id }, data })
```
Which causes the following error:
```
Invalid `prisma.user.update()` invocation:

{
  where: {
    id: '62057f64643a91216fcd9f73'
  },
  data: {
    id: '62057f64643a91216fcd9f73',
    ~~
    emailVerified: new Date('2022-02-21T10:58:02.657Z')
  }
}

Unknown arg `id` in data.id for type UserUpdateInput. Available args:

type UserUpdateInput {
  name?: String | NullableStringFieldUpdateOperationsInput | Null
  email?: String | NullableStringFieldUpdateOperationsInput | Null
  emailVerified?: DateTime | NullableDateTimeFieldUpdateOperationsInput | Null
  image?: String | NullableStringFieldUpdateOperationsInput | Null
  token?: Int | IntFieldUpdateOperationsInput
  accounts?: AccountUpdateManyWithoutUserInput
  sessions?: SessionUpdateManyWithoutUserInput
}
```

## Working Fix
```typescript
updateUser: (data) => {
    const { id, ...rest } = data;
    return p.user.update({ where: { id }, data: rest })
}
```

### How to reproduce

The error occur in the `updateUser` function of the adapter. To do so the user must already be registered in the database, otherwise `createUser` is called.
- Register a User (nothing happens, the `createUser` function is called because the user does't exists)
- Logout
- Login with the same email using the EmailProvider

The last step triggers the `updateUser` function of the adapter to update the `emailVerified` field in the User model.

### Expected behavior

Using Prisma with MongoDB should correctly update the user when logging in with the EmailProvider

**Comment by balazsorban44** [comment]
Thank you, we are still investigating. :+1: The repro steps help a lot!

For the time being, here is a one-liner to override an adapter method. (This is not specific to Prisma, should work with most of them.)

```js
import { PrismaAdapter } from "@next-auth/prisma-adapter"
import { PrismaClient } from "@prisma/client"
const p = new PrismaClient()
const adapter = PrismaAdapter(p)

adapter.updateUser = ({ id, ...data }) => p.user.update({ where: { id }, data })

export default NextAuth({
  adapter,
```

**Comment by balazsorban44** [comment]
I haven't found a better solution than your workaround, so I implemented it in the core, and I also added MongoDB/Prisma tests to make sure we won't regress. I also added a brief note to our Prisma docs that now mentions MongoDB specifically.

**Comment by AmitMirgal** [comment]
just curious to know, any ETA on when we could expect to get a fixed version?
