### ISSUE TITLE
Twitter: oauth_token and oauth_token_secret not part of token session callback

### ISSUE THREAD

**Issue by doorman02** [nextauthjs/next-auth#4032]
### Provider type

Twitter

### Environment

System:
OS: macOS 12.1
CPU: (10) arm64 Apple M1 Pro
Memory: 7.08 GB / 32.00 GB
Shell: 5.8 - /bin/zsh
Binaries:
Node: 16.13.2 - /usr/local/bin/node
Yarn: 1.22.17 - /usr/local/bin/yarn
npm: 8.1.2 - /usr/local/bin/npm
Browsers:
Brave Browser: 97.1.34.81
Chrome: 98.0.4758.80
Safari: 15.2
npmPackages:
next: 12.0.10 => 12.0.10
next-auth: ^4.2.1 => 4.2.1
react: 17.0.2 => 17.0.2

### Reproduction URL

not available

### Describe the issue

I am signing in using the Twitter provider and I need to use OAuth 1. 

  async session({ session, user, token }) {
console.log(token);
return session;
}

However the token doesn't show oauth_token and oauth_token_secret the object only contains the following properties:

{
  name: 'myUser1',
  picture: 'https://urltoprofileimage',
  sub: '2342342345345345',
  iat: 1345345345,
  exp: 1345345345,
  jti: 'aad83348-a382-fbar-9us2-52dr3582ds'
}

this used to work in version 3.27.0 before I updated to version 4 (accessToken and secretToken). 
Thanks!

### How to reproduce

Use signin('Twitter') to signin using the Twitter provider. Log the token object within the sesison callback.

### Expected behavior

The token object should contain the oauth_token and oauth_token_secret properties.

**Comment by balazsorban44** [comment]
It is available on `token` if you actually saved them in the JWT through the jwt callback: https://next-auth.js.org/configuration/callbacks#jwt-callback

**Comment by doorman02** [comment]
@balazsorban44 thanks for your reply. I verified it and i also have the JWT callback defined in the nextauth.tsx but the token is exactly the same as in the session without the oauth_token properties. I am probably missing something, will try this with a new project and see if it works otherwise I will just downgrade back to v3 since it was working there.

**Comment by balazsorban44** [comment]
it's not on the token, but account the first time you log in. it's nothing to do with v3. the only thing changed is the naming which didn't make sense in v3 anyway. 

Twitter uses OAuth 1, and that does not have access tokens.

**Comment by Hasham-dev** [comment]
@doorman02 I'm facing the same issue.
Did you find any solution?
