### ISSUE TITLE
NEXTAUTH_SECRET unnecessary when using own encode/decode

### ISSUE THREAD

**Issue by TomFreudenberg** [nextauthjs/next-auth#4057]
### Question 💬

Hi @balazsorban44,

in https://github.com/nextauthjs/next-auth/blob/3ec3761634f7953acc52d460e8bb0b2a678d7703/packages/next-auth/src/core/lib/assert.ts#L39-L45 you always will check and warn due to assertConfig if the env NEXTAUTH_SECRET (regarding options.secret) is set.

When running own signing and verification by self-developed encode/decode function this makes no sense.

In addition that makes it necessary to set some DUMMY VALUE just to come above the assert ???

If this assert should still exist in future better check also encode/decode in assertConfig.

```js
  if (!options.secret && !options.encode && !options.decode) {
    if (process.env.NODE_ENV === "production") {
      return new MissingSecret("Please define a `secret` in production.")
    } else {
      return "NO_SECRET"
    }
  }
```

For my point of view it is also a security vulnerability in case to expose an env value which is not ever used for function.

### How to reproduce ☕️

Don't give a value to NEXTAUTH_SECRET or options.secret in jwt config.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Going forward, our recommendation will be to set that environment variable, even if you use a custom encode/decode method (which on itself is just a legacy solution for people really wanting to have a custom way, but is basically useless/unnecessary for 99%)

even if you customize those methods, you'll need a secret which we will read in from that variable. I plan to remove the option to pass a secret manually in any other way in the future, as people forget about passing it all the time.

**Comment by TomFreudenberg** [comment]
> PS. Feel free to not tag me for no reason when simply opening a new issue I won't give more attention to the issue, and I do read **all** issues anyway. 😊

Sorry for tagging you - got that

**Comment by TomFreudenberg** [comment]
> even if you customize those methods, you'll need a secret which we will read in from that variable.

Maybe it is just me but - **naming** the private key as SECRET feels strange to me. My personal opinion is here to name it: NEXTAUTH_JWE_PRIVATE_KEY instead calling it: NEXTAUTH_SECRET - but that is maybe only my "view".

Nevertheless - you allow to overwrite encode and decode - what means allowing developers to do stuff on their own decision - forcing then a NOT ANYWHERE USED variable - to be existing - does make still no sense - my 2 cents.

**Comment by balazsorban44** [comment]
It is used for more than JWE though, eg.: hashing one-time tokens for the E-mail provider for example. In the past, it had even more roles I believe.

There might be a better name, but SECRET screams to the user it should not be exposed, and for most of those who only need a working auth library and want to care little about naming, it should probably be fine.

But thanks for the suggestion!

**Comment by TomFreudenberg** [comment]
Got it - thanks for taking time
