### ISSUE TITLE
Facebook provider - expected 200 OK, got: 400 Bad Request when creating new users

### ISSUE THREAD

**Issue by moritzmyrz** [nextauthjs/next-auth#4067]
### Provider type

Facebook

### Environment

Deployed to Vercel @ Node v14.x  
Any browser used, Chrome, Brave, Edge, etc.

npmPackages:
    next: ^12.1.0 => 12.1.0
    next-auth: ^4.2.1 => 4.2.1
    react: 17.0.2 => 17.0.2

### Reproduction URL

https://github.com/moritzmyrz/next-fb-prov-error-ex

### Describe the issue

In production, I am getting this error.

I've checked that my Vercel instance is at Node v14.x and that my database is properly configured and migrated with my Prisma schema. It works well with my own account, however, it doesn't work if one of my friends tries to sign up with Facebook.

```text
[GET] /api/auth/callback/facebook?code=AQCjDd1WazT8DE8SKsstm0e3iOFW10s68xzDOAwk5UNyd1HG-cwh-H5gHNCWBgoAlGIlznyyeJJR4ge588oP_OD262n9e9u1YuO_qcVYu8sPZYGigXeCL1n2ZlFwfQ8EO8x2dtsID_rDjntWpzDbpmtNUki25X9cgbm19h6AC77_HqXwBj8Ublv_y7Dx0yBaovrYqY5FcTv-AqZ1yHNzvy92ZHgv809E7GLJdpxCTux-hXSA5ZKQ22Ru_2W8wFMFaitfwn-4n607O1Y-OxQFf-J_c1Zb_JXEEEpOUM1TLj1aFgYSLlpcOqqwkKfZDkwgvMObubM2_AJfZAF71UodQ9vVWgx1PA8bFT-6G9I_Yyrzjsu9gTIat-8GaF1UPcCHKtI&state=klppdEl9m8SFEYWjPp7UFUbIy-oWawNDgXL3PKv9I-A
21:24:56:43
2022-02-24T20:24:57.173Z	ea894128-a956-40cd-b023-dc791adc17a9	ERROR	[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error expected 200 OK, got: 400 Bad Request {
  error: {
    message: 'expected 200 OK, got: 400 Bad Request',
    stack: 'OPError: expected 200 OK, got: 400 Bad Request\n' +
      '    at processResponse (/var/task/node_modules/openid-client/lib/helpers/process_response.js:41:11)\n' +
      '    at Client.grant (/var/task/node_modules/openid-client/lib/client.js:1340:22)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
      '    at async Client.oauthCallback (/var/task/node_modules/openid-client/lib/client.js:612:24)\n' +
      '    at async oAuthCallback (/var/task/node_modules/next-auth/core/lib/oauth/callback.js:114:16)\n' +
      '    at async Object.callback (/var/task/node_modules/next-auth/core/routes/callback.js:50:11)\n' +
      '    at async NextAuthHandler (/var/task/node_modules/next-auth/core/index.js:139:28)\n' +
      '    at async NextAuthNextHandler (/var/task/node_modules/next-auth/next/index.js:21:19)\n' +
      '    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:182:9)\n' +
      '    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:386:9)',
    name: 'OPError'
  },
  providerId: 'facebook',
  message: 'expected 200 OK, got: 400 Bad Request'
}
2022-02-24T20:24:57.175Z	ea894128-a956-40cd-b023-dc791adc17a9	ERROR	[next-auth][error][CALLBACK_OAUTH_ERROR] 
https://next-auth.js.org/errors#callback_oauth_error expected 200 OK, got: 400 Bad Request OPError: expected 200 OK, got: 400 Bad Request
    at processResponse (/var/task/node_modules/openid-client/lib/helpers/process_response.js:41:11)
    at Client.grant (/var/task/node_modules/openid-client/lib/client.js:1340:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Client.oauthCallback (/var/task/node_modules/openid-client/lib/client.js:612:24)
    at async oAuthCallback (/var/task/node_modules/next-auth/core/lib/oauth/callback.js:114:16)
    at async Object.callback (/var/task/node_modules/next-auth/core/routes/callback.js:50:11)
    at async NextAuthHandler (/var/task/node_modules/next-auth/core/index.js:139:28)
    at async NextAuthNextHandler (/var/task/node_modules/next-auth/next/index.js:21:19)
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:182:9)
    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:386:9) {
  name: 'OAuthCallbackError',
  code: undefined
}
```

### How to reproduce

Publish to Vercel, and it will not work.

### Expected behavior

It should allow a new user who signing up with Facebook to join.

**Comment by balazsorban44** [comment]
I've just tested it locally, and could not reproduce this:

![image](https://user-images.githubusercontent.com/18369201/155922153-02ce0c3b-d540-48f5-bb23-1fb59a5fd163.png)

I'll assume it was a fluke on Facebook's side again.

**Comment by balazsorban44** [comment]
There is not much else to say, really. You can check #3711 for better explanations, but it really was Facebook messing up. :shrug: It's not up to NextAuth.js to ensure the stability of Facebook services. We are just integrating with them.

**Comment by balazsorban44** [comment]
If you think logging could be made better in any way, I'm open to it, please open a PR. :+1:

**Comment by lionelrudaz** [comment]
> There is not much else to say, really. You can check #3711 for better explanations, but it really was Facebook messing up. 🤷 It's not up to NextAuth.js to ensure the stability of Facebook services. We are just integrating with them.

Sure, I get it, but still. Facebook should be one of the most popular providers and all of the sudden it stops working. It's not general, otherwise there would be massive login issues on many websites, don't you think?

I would love to help with more debugging, but I don't know where to add it. Also, for me Facebook login still doesn't work on localhost, despite comments that were saying otherwise. So where can I start? There's no callback being called in such case, so we don't even know what FB is responding with.

Let me know how I can help.

**Comment by balazsorban44** [comment]
> Sure, I get it, but still. Facebook should be one of the most popular providers and all of a sudden it stops working. It's not general, otherwise, there would be massive login issues on many websites, don't you think?

Like I mentioned before, it was **exactly** the case in #3711... I am puzzled about what you think we should do here. If Facebook OAuth does not work or is down for some reason, then NextAuth.js won't work either. :eyes:

If you have an issue, please open a bug report with an attached reproduction, that's the only way we can help you. I am unable to induce an error on my local machine. :shrug:

> I would love to help with more debugging, but I don't know where to add it

We use `openid-client` ([documentation here](https://github.com/panva/node-openid-client/blob/main/docs/README.md)), so you could start with checking how we use that library and see if there are any config options or useful error properties that we could log.

RelyingParty errors (in the case, Facebook) will throw an `RPError` which we do not rethrow (we create our own Error instance) but we log it. There might be some extra properties we could log from it. Assumingly there is `error.response`:

https://github.com/panva/node-openid-client/blob/5120a076d0b5b24b9ebd0dcdb8b40d4dfcd535a3/lib/errors.js#L28

https://github.com/nextauthjs/next-auth/blob/2ea5566d1e94a6f6b65c54aea65dbb765c6dc3b0/packages/next-auth/src/core/lib/oauth/callback.ts#L148-L154
