### ISSUE TITLE
[V4] SessionProvider - refetchInterval is polling at incorrect intervals

### ISSUE THREAD

**Issue by mabaranowski** [nextauthjs/next-auth#4076]
### Environment

  System:
    OS: macOS 12.1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Edge: 96.0.1054.43
    Firefox: 95.0.1
    Safari: 15.2
  npmPackages:
    next: ^12.0.7 => 12.0.7
    next-auth: ^4.2.1 => 4.2.1
    react: 17.0.2 => 17.0.2

### Reproduction URL

No available reproduction url

### Describe the issue

When using `refetchInterval` for session polling, the times are not accurate:
```js
<SessionProvider session={pageProps.session} refetchInterval={540} refetchOnWindowFocus={false}>
  <Component {...pageProps} />
</SessionProvider>
```

I've set `refetchInterval` to poll every 9 minutes, and gathered the results.
First line is current timestamp, while second line is time in miliseconds left till my token expires.
```
2022-02-25T13:51:29.679Z
-60483

2022-02-25T14:00:30.057Z
-60198

2022-02-25T14:09:29.935Z
-59727

2022-02-25T14:18:33.990Z
-60775

2022-02-25T14:27:35.461Z
-61345

2022-02-25T14:36:35.368Z
-59708

2022-02-25T14:45:49.788Z
-74222

2022-02-25T14:54:34.931Z
-44950

2022-02-25T15:03:35.595Z
-60465

2022-02-25T15:13:10.225Z
-94464

2022-02-25T15:21:35.526Z
-25100

2022-02-25T15:31:17.288Z
-101569

2022-02-25T15:39:35.459Z
-17938

2022-02-25T15:49:08.742Z
-93068

2022-02-25T15:57:35.448Z
-26521

2022-02-25T16:07:10.183Z
-94554

2022-02-25T16:16:09.815Z
-59462

2022-02-25T16:34:42.396Z
-632409

2022-02-25T16:34:45.726Z
-635739

2022-02-25T16:34:45.728Z
-635741

2022-02-25T16:34:45.732Z
-635745
```
-60000 is a perfect interval, now observe, that after few intervals at around -60 seconds, it then polls at -74 seconds, so it's off by 14 seconds, and next interval after that polls after 45 seconds, so it's off by 15 seconds but in the opposite direction. It gets worse after that.

These logs are from `jwt` callback at `[...nextauth].js`
I've looked up the setInterval function that uses refetchInterval, however I can't spot any obvious problem [SessionProvider](https://github.com/nextauthjs/next-auth/blob/bc401657a6a6d6ad502bcc2bb2766b9383713c82/packages/next-auth/src/react/index.tsx#L395)

### How to reproduce

To reproduce set `refetchInterval` on `<SessionProvider>`, and add logs to `jwt` or `session` callbacks.
Behaviour reproducible on development environment (`npm run dev`), and production environment (`npm run start`).
Same thing with deployment on Vercel.

`[...nextauth].js`
```js
async function refreshAccessToken(tokenObject) {
    try {
        const tokenResponse;  // Refresh Token Api Call
        
        return {
            ...tokenObject,
            accessTokenExpiry: tokenResponse.data.accessTokenExpiry
        }
    } catch (error) {
        return {
            ...tokenObject,
            error: "RefreshAccessTokenError",
        }
    }
}

const providers = [
    CredentialsProvider({
        name: 'Credentials',
        authorize: async (credentials) => {
            try {
               // Auth Api Call
               return user.data;
            } catch (e) {
                // Error Handling
            }
        }
    })
]

const callbacks = {
    jwt: async ({token, user}) => {
        if (user) {
            token.accessTokenExpiry = user?.data.accessTokenExpiry;
        }

        const timeDiff = Math.round((token.accessTokenExpiry - 120 * 1000) - Date.now());

        // Output from these logs is posted above
        console.log(new Date());
        console.log(timeDiff);

        if (timeDiff > 0) {
            return Promise.resolve(token);
        }

        token = refreshAccessToken(token);
        return Promise.resolve(token);
    },
    session: async ({session, token}) => {
        session.accessTokenExpiry = +token.accessTokenExpiry;
        return Promise.resolve(session);
    },
}

export const options = {
    providers,
    callbacks,
    pages: { },
}

const Auth = (req, res) => NextAuth(req, res, options)
export default Auth;
```

`_app.js`
```js
<SessionProvider session={pageProps.session} refetchInterval={540} refetchOnWindowFocus={false}>
  <Component {...pageProps} />
</SessionProvider>
```

### Expected behavior

I'd expect the session to be polled at the interval I specify in `refetchInterval`.
For `refetchInterval={540}` I'd want the session to be polled every 9 minutes (ofc not precisely to miliseconds, but with a small margin of error)

The example above worked, because I did set to refresh a token on every call for testing.
In production deployment, you'd need a big margin, to ensure those random times will fit between the time you specify a token can be refreshed, and actually the time it expires.

**Comment by mabaranowski** [comment]
I've posted additional relevant code in the **How to reproduce** section. 
To replicate set `refetchInterval` and check consistency of times from `console.log(new Date())` in `jwt` callback using `credentials provider`.

**Comment by balazsorban44** [comment]
So I've done a simpler reproduction and could not verify those huge differences. Here is my code:

`pages/api/auth/[...nextauth].js`:
```js
...
callbacks: {
  jwt({ token }) {
    const now = Date.now()
    const prev = token.now ?? now
    token.now = now
    const diff = token.now - prev
    console.log(diff / 1000, "seconds")
    return token
  },
}
...
```

`pages/_app.js`
```js
...
<SessionProvider
  session={pageProps.session}
  refetchInterval={3}
  refetchOnWindowFocus={false}
>
  <Component {...pageProps} />
</SessionProvider>
...
```

Given this code, unless my browser decides to go idle, I am able to stay within a very low difference, even with a 3 seconds revalidation:

```sh
next-auth-app:dev: 2.999 seconds
next-auth-app:dev: 3.011 seconds
next-auth-app:dev: 2.995 seconds
next-auth-app:dev: 3.004 seconds
next-auth-app:dev: 2.98 seconds
next-auth-app:dev: 3.009 seconds
next-auth-app:dev: 3.008 seconds
next-auth-app:dev: 2.994 seconds
next-auth-app:dev: 2.991 seconds
next-auth-app:dev: 3.01 seconds
next-auth-app:dev: 2.994 seconds
next-auth-app:dev: 3.011 seconds
next-auth-app:dev: 2.984 seconds
next-auth-app:dev: 3.013 seconds
next-auth-app:dev: 2.997 seconds
next-auth-app:dev: 2.998 seconds
next-auth-app:dev: 3.005 seconds
next-auth-app:dev: 2.991 seconds
next-auth-app:dev: 3.009 seconds
next-auth-app:dev: 2.986 seconds
next-auth-app:dev: 3.005 seconds
next-auth-app:dev: 3.001 seconds
next-auth-app:dev: 3.009 seconds
next-auth-app:dev: 3 seconds
next-auth-app:dev: 2.985 seconds
next-auth-app:dev: 3 seconds
next-auth-app:dev: 3 seconds
next-auth-app:dev: 3.014 seconds
next-auth-app:dev: 3.014 seconds
```

Likely your revalidation takes very different times, or there is a small error in your calculation somewhere. I can also imagine that the browser decides to go idle and don't do the polling when the page gets inactive.

In any case, I don't think this is a NextAuth.js bug.

**Comment by mabaranowski** [comment]
Yeh, refetchOnWindowFocus={true} might help, however once I saw how many requests it generates when swiping between full screen apps on macOS (not necessarily the browser window), I've decided to make an effort and upgrade NextAuth.js from v3 to the latest version for this feature alone. I don't feel comfortable, letting the session endpoint to be hammered that hard, if there is a way around it. 

I've took your example, created a fresh project with create-next-app and installed next-auth, no other dependencies, and I was still getting incorrect intervals. It turns out, that when I took the browser window with the app, on the same desktop as the terminal, the times stabilised and were similar to yours. When I fullscreen the browser window and focus another desktop, the intervals are incorrect again. (or no fullscreen the browser, but swipe to another fullscreen app)

I'm not sure what to do with this information tho, because yeh, it's the client that lags for some reason. It affects the time the server is asked for a session refresh. That's why it was replicable on the Vercel environment as well.

However, it indeed is not a bug of NextAuth.js.

**Comment by balazsorban44** [comment]
I'm not sure what you mean about `refetchOnWindowFocus`. It should do exactly one request when the tab is being focused, so what does "endpoint being hammered" mean? :thinking:

The relevant code is here:

https://github.com/nextauthjs/next-auth/blob/2a4d45c66526b9de8af2ef5a99517f5548d20708/packages/next-auth/src/react/index.tsx#L381-L393

**Comment by mabaranowski** [comment]
https://vimeo.com/683195964

Check the video, sorry it's quick but I needed small file size. It would be great if it worked once the window is focused.
However as you can see, even if i'm using two other apps (not even the browser window) with each and every focus change the endpoint get's triggered.

With endpoint being hammered, I mean, now imagine 50k users all having your app opened in the background, even not using it, and going on with their usual stuff, and suddenly you've got millions of requests to your backend for no reason.

Thet's why I try to avoid it. Am I looking at this incorrectly? 

Yeh, when it comes to the code you referenced, seems like event: "visibilitychange" is triggered by any visibility change in the system, not the browser window with your app.
