### ISSUE TITLE
Middleware withAuth, callbacks --> authorize return false goes to login; why?

### ISSUE THREAD

**Issue by DaleSalcedo** [nextauthjs/next-auth#4090]
### Question 💬

Why does returning false in authorized redirect to login?  Shouldn't I be able to control where this goes to?  I'd like it to go to a custom page of my choosing preferably ("You do not have access") or anything but the login page.  (They're already logged in.)

Am I missing something?  I was hesitant to set this as a bug as maybe I'm missing something but I don't see anything in the docs.

`export default withAuth({
  callbacks: {
    authorized: (param) => false,
  },
})`

this goes to login page: http://localhost:3000/api/auth/signin?callbackUrl=.....

if i add:

```
pages: {
  signIn: '/login',
  error: '/error',
}
```

it'll go to: http://localhost:3000/login?callbackUrl=

### How to reproduce ☕️

```
import { withAuth } from "next-auth/middleware"

// More on how NextAuth.js middleware works: https://next-auth.js.org/configuration/nextjs#middleware
export default withAuth({
  callbacks: {
    authorized: (param) => false,
  },
})

```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Usually you want them to log in with a different account. On your custom login page, you could add a note that they should try to log in with a different account, if you can see that they have a verified session. 👍

**Comment by DaleSalcedo** [comment]
hm I think that's pretty narrow minded to think that every user just wants it to go to the login page when not authorized.

you guys should think this one over and let the user dictate where the redirect goes to..
