### ISSUE TITLE
Using two next-auth instances with different ports results in signout

### ISSUE THREAD

**Issue by gabrielcraveiro** [nextauthjs/next-auth#4119]
### Question 💬

Hi guys, I tried to find a answer but couldn't find anything similiar.

I have two next.js app's using next-auth. One using storage session and another using jwt. The first one is using `localhost:8080` and the second `localhost:8081`. The problem is, when I refresh the second app (8081) the sessionProvider refreshs the first app and signout the user.

I need to use both servers at the same time and I can't find a way to keep my `localhost:8080` logged in.

localhost:8080 .env

```
NEXTAUTH_URL=http://localhost:8080
NEXTAUTH_URL_INTERNAL=http://localhost:8080
```

localhost:8080 [nextauth].ts

```
const options = {
  secret: process.env.SECRET,
  session: { strategy: "jwt" },
  jwt: {
    secret: process.env.SECRET,
    async encode({ secret, token, maxAge }) {
      const encodedToken = jwt.sign(token, secret, { algorithm: "HS256" });
      return encodedToken;
    },
    async decode({ secret, token, maxAge }) {
      const decodedToken = jwt.verify(token, secret, { algorithms: ["HS256"] });
      return decodedToken;
    },
  },
... providers
```

localhost:8081 .env has

```
NEXTAUTH_URL=http://localhost:8081
NEXTAUTH_URL_INTERNAL=http://localhost:8081
```

localhost:8081 [nextauth.ts]

```
const options = {
  secret: process.env.SECRET,
  pages: {
    signIn: "/auth/login",
  },
  jwt: {
    signingKey: process.env.SECRET,
  },
...providers
```

localhost:8081 display this error when signing out the user

```
[next-auth][error][JWT_SESSION_ERROR]
https://next-auth.js.org/errors#jwt_session_error Invalid Compact JWE {
  message: 'Invalid Compact JWE',
  stack: 'JWEInvalid: Invalid Compact JWE\n' +
```

Thanks and sorry for the big text :)

### How to reproduce ☕️

I'm sorry but how could I reproduce this on codesandbox

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by gabrielcraveiro** [comment]
Using 0.0.0.0:8081 instead of localhost seems to fix the problem with multiple sessions.

**Comment by steph-query** [comment]
I run one on localhost and the other on 0.0.0.0 and that worked for me.
