### ISSUE TITLE
Update font-family stack

### ISSUE THREAD

**Issue by wayne-shih** [nextauthjs/next-auth#4178]
### Environment

"@headlessui/react": "^1.5.0",
"@heroicons/react": "^1.0.6",
"@next-auth/mongodb-adapter": "^1.0.1",
"mongodb": "^4.4.1",
"next": "12.1.0",
"next-auth": "^4.2.1",
"react": "17.0.2",
"react-dom": "17.0.2"

### Reproduction URL

~

### Describe the issue

The current font-family stack is a tad unconventional

https://github.com/nextauthjs/next-auth/blob/a72f1b6d21da89b4223542006c865862635c027b/packages/next-auth/src/css/index.css#L46-L48

`-apple-system` and `BlinkMacSystemFont` are both defined for Apple's SF system font for Mac. 

However Chromium-based browsers (Chrome, Edge...) doesn't recognise `-apple-system` so means `Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, sans-serif` will get displayed first before it gets the Apple's system font via `BlinkMacSystemFont`

ie. on my Mac, Segoe UI gets rendered first (as I have Segeo UI installed)
<img width="1155" alt="CleanShot 2022-03-14 at 21 41 17@2x" src="https://user-images.githubusercontent.com/51947763/158135610-e20d75ac-1a63-4083-a05f-9740abd91a66.png">

However if considering most users doesn't have _Segoe UI, Roboto, Ubunti, Cantarell, or Noto Sans_ on their mac then `sans-serif` would get displayed -- and this would most likely be Arial :( 

### How to reproduce

Any chromium based browsers

### Expected behavior

Suggest changing system font stack to... 

[Tailwind CSS's default font stack](https://tailwindcss.com/docs/font-family): 
`font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";`

OR 

[GitHub's default font stack](https://primer.style/design/foundations/typography#font-stack): 
`font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";`

both options places `BlinkMacSystemFont` directly after `-apple-system` which would display SF on mac whether you're on Chrome/Safari/Edge/FireFox...

Expected behaviour if changing to tailwind's font stack:
<img width="1169" alt="CleanShot 2022-03-14 at 21 45 28@2x" src="https://user-images.githubusercontent.com/51947763/158136270-74ef58dc-5243-40b5-a112-11b1bb735877.png">

Comparison of LEFT current font stack rendered as Segoe UI ; and RIGHT suggest font stack rendered as SF system font ; (Chrome Mac):
<img width="950" alt="CleanShot 2022-03-14 at 21 46 58@2x" src="https://user-images.githubusercontent.com/51947763/158136532-02d24ab5-a95a-4d77-92b3-d3165dd855b8.png">

**Comment by wayne-shih** [comment]
whatever y'all guys decide to do with this, would be good to reflect changes to the example repo 

https://github.com/nextauthjs/next-auth-example/blob/388aa729cdc361e3351865e280a19f21a676b328/pages/styles.css#L2-L4

**Comment by wayne-shih** [comment]
whatever y'all decide to do with this, would be good to reflect changes to the example repo

https://github.com/nextauthjs/next-auth-example/blob/388aa729cdc361e3351865e280a19f21a676b328/pages/styles.css#L2-L4

**Comment by ndom91** [comment]
This makes sense to me. Not sure where that odd original font stack came from. Would you be willing to prepare a PR for this?

**Comment by balazsorban44** [comment]
Yeah, no strong opinions, feel free to open a PR. :+1:

**Comment by wayne-shih** [comment]
Sweet as! Yep will do :)
