### ISSUE TITLE
200 OK Response on invalid SessionToken

### ISSUE THREAD

**Issue by laurenzhonauer** [nextauthjs/next-auth#4188]
### Environment

This behaviour can be inspected on the deployed example project https://next-auth-example.vercel.app/

### Reproduction URL

https://next-auth-example.vercel.app/

### Describe the issue

The next auth session endpoint https://next-auth-example.vercel.app/api/auth/session is not returning HTTP Error codes as respected

### How to reproduce

1. Sign in in the Deployed Example https://next-auth-example.vercel.app
2. Open Browser Devtools and Copy the /session call as Curl 
<img width="854" alt="visit" src="https://user-images.githubusercontent.com/44588135/158403129-6174de83-a4fc-43b1-bb3d-56a3d3d911a1.png">

3. Import the request to Postman or a similar tool - At this point we can fire a request and get a response like expected
4. Either remove the cookie header completely or just invalidate the SessionToken by changing the text after ` __Secure-next-auth.session-token=`

When firing a request now i would expect a response like 401 Unauthorized but i get 200 OK with an empty Object
![image](https://user-images.githubusercontent.com/44588135/158403507-315c8605-a857-4982-a514-bf250b3ef939.png)

### Expected behavior

When sending a request to https://next-auth-example.vercel.app/api/auth/session with a invalid or missiong cookie header it should return something like 401 unauthorized

**Comment by ndom91** [comment]
I could reproduce this behavior. @balazsorban44 what do you think? I feel like the behavior described by @laurenzhonauer is more appropriate than what we're doing now.

**Comment by balazsorban44** [comment]
That endpoint is usually consumed by functions like `useSession`. The request itself did not fail and does return an empty object on purpose, as the session JWT could not be decrypted (since you forcefully overrode it). I do not think we need a 401 here.
