### ISSUE TITLE
Read before creating a new issue!

### ISSUE THREAD

**Issue by iaincollins** [nextauthjs/next-auth#419]
**NextAuth.js is an open source project built by individual contributors who volunteer their free time.**

*Before raising a new issue, please refer to the [documentation](https://next-auth.js.org/getting-started/introduction), the [example project](https://github.com/iaincollins/next-auth-example) and look through existing issues to see if your question has already been answered there.*

Please **help us help you** by using the issue templates. The more completely you can fill them out, the easier it is to help.

### How you can help

* Questions about NextAuth.js and how to use it are very welcome! 

  We are working hard on providing more examples, tutorials and an FAQ to address frequently asked questions - thank you to those who have been contributing to those!

> **NOTE:** When you fill out the "Question" template, we are going to convert it to [Discussions](https://github.com/nextauthjs/next-auth/discussions). This way, we can organize and better manage our resources around core problems. *(If you are a user of `next-auth` with experience, we welcome you to help others out by answering their questions!)* Whenever we have the time also, we will of course try to help you anyway. 

* Bug Reports and Feature Requests for things mentioned in issues or Pull Requests are very welcome!

  This isn't something we always get time to do and it's easy to forget to come back them, so this is always appreciated.

* Please do jump in on existing issues, but please try avoid accidentally hijacking issues raised by others.

  This is easy to do by mistake and it's not always clear cut if a problem is related or not, but if you would like to go into detail about an issue and you are not sure, you can always open a new issue and link back to the other issue. This helps keep the threads of old issues useful for folks looking for help with same problem that was originally reported.

Thanks for reading this! ❤️

**Comment by stunaz** [comment]
Can't you just favor GitHub Discussions for questions and how-to, and leave GitHub Issue for bug/feature?

**Comment by iaincollins** [comment]
> Can't you just favor GitHub Discussions for questions and how-to, and leave GitHub Issue for bug/feature?

That's the plan! We are eagerly awaiting GitHub Discussions coming out of beta so we can get access to it.

I think that will help a lot - part of the challenge right now is that there are lot of topics that are challenging to get a handle on the first time and commonly recurring questions, and issues are not a great format for facilitating that (especially if also being used to prioritise and track work).

**Comment by Zertz** [comment]
@iaincollins Is there anything we can do to help get some PRs merged?

**Comment by balazsorban44** [comment]
@Zertz thanks for volunteering. I recently started to merge some of them into our new base branch `canary`. Hopefully later this month, I and @iaincollins will be able to produce a new unstable (alpha/canary/beta whatever) release to npm. When the docs have been updated and tests are in place for most of the things, we will be able to push these to stable at a later point as well.

So just ping me on PRs you feel need to be/can be merged and I'll see what I can do.

Triaging issues would be a tremendous help as well. There are many questions from users on usage, some of them are duplicates/have been asked/answered before. I recently set up a stale bot to help to reduce the no. issues, but there are still many questions that need to be answered. I hope that we can soon get GitHub Discussions on the repo, to better separate between user questions and feature requests/bugs. Until then, feel free to chip in on questions and help others if you can.

Thanks again!

**Comment by tomaszs** [comment]
Your bot recognizes your own repositories as invalid reproduction links: https://github.com/nextauthjs/next-auth/issues/9669
