### ISSUE TITLE
'checks.state argument is missing' when using the custom JWT encode/decode methods

### ISSUE THREAD

**Issue by devkiran** [nextauthjs/next-auth#4190]
### Environment

```
  System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 298.23 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.5.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
    Firefox: 97.0.2
    Safari: 15.1
  npmPackages:
    next: 12.1.0 => 12.1.0 
    next-auth: 4.3.0 => 4.3.0 
    react: 17.0.2 => 17.0.2 
```

### Reproduction URL

https://github.com/boxyhq/jackson-hasura-nextjs/blob/main/pages/api/auth/%5B...nextauth%5D.ts

### Describe the issue

I'm having an issue with the next-auth. I'm customizing the JWT for Hasura by overriding the `encode` and `decode` methods. 

In the `[...nextauth].ts`

```
export default NextAuth({
  providers: [
    BoxyHQSAMLProvider({
      issuer: `${process.env.BOXYHQ_SAML_URL}`,
      clientId: "dummy",
      clientSecret: "dummy",
    }),
  ],
  jwt: {
    encode: async ({ secret, token, maxAge }) => {
      console.log({ token });

      const jwtClaims = {
        sub: token?.sub,
        name: token?.name,
        email: token?.email,
        iat: Date.now() / 1000,
        exp: Math.floor(Date.now() / 1000) + 24 * 60 * 60,
        expires: maxAge,
        "https://hasura.io/jwt/claims": {
          "x-hasura-allowed-roles": ["user"],
          "x-hasura-default-role": "user",
          "x-hasura-role": "user",
          "x-hasura-user-id": token?.sub,
        },
      };

      return jwt.sign(jwtClaims, secret, { algorithm: "HS256" });
    },
    decode: async ({ token, secret }) => {
      return jwt.verify(token as string, secret, {
        algorithms: ["HS256"],
      }) as any;
    },
  },
  debug: true,
});
```

I'm getting the following errors

```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error checks.state argument is missing {
  error: {
    message: 'checks.state argument is missing',
    stack: 'TypeError: checks.state argument is missing\n' +
      '    at Client.oauthCallback (/node_modules/openid-client/lib/client.js:530:13)\n' +
      '    at oAuthCallback (/node_modules/next-auth/core/lib/oauth/callback.js:114:29)\n' +
      '    at async Object.callback (/node_modules/next-auth/core/routes/callback.js:50:11)\n' +
      '    at async NextAuthHandler (/node_modules/next-auth/core/index.js:139:28)\n' +
      '    at async NextAuthNextHandler (/node_modules/next-auth/next/index.js:21:19)\n' +
      '    at async /node_modules/next-auth/next/index.js:57:32\n' +
      '    at async Object.apiResolver (/node_modules/next/dist/server/api-utils/node.js:182:9)\n' +
      '    at async DevServer.runApi (/node_modules/next/dist/server/next-server.js:386:9)\n' +
      '    at async Object.fn (/node_modules/next/dist/server/base-server.js:488:37)\n' +
      '    at async Router.execute (/node_modules/next/dist/server/router.js:228:32)',
    name: 'TypeError'
  },
  providerId: 'boxyhq-saml',
  message: 'checks.state argument is missing'
}
```

The code is working perfectly if I remove `jwt:{}` section.

### How to reproduce

We don't have a live demo now. 

Please see the code here https://github.com/boxyhq/jackson-hasura-nextjs/blob/main/pages/api/auth/%5B...nextauth%5D.ts

I can share more information if needed.

### Expected behavior

Nex-auth should return custom JWT successfully.

**Comment by harishannam** [comment]
Facing the same issue while trying to implement JWT. Is there any solution or workaround for this?

**Comment by valstu** [comment]
Same here, using next-auth version 4.3.1

**Comment by valstu** [comment]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/647861/162089978-5119027e-c7be-4dab-900e-4400ac41cdf2.png"> Noticed that next-auth.state cookie is `[object Object]` 🤔

**Comment by valstu** [comment]
And the token parameter that encode gets is actually the `{state: something}`

**Comment by AnasTrk** [comment]
try adding `checks: "both"` on your provider ```
 providers: [
    BoxyHQSAMLProvider({
      issuer: `${process.env.BOXYHQ_SAML_URL}`,
      clientId: "dummy",
      clientSecret: "dummy",
      checks:"both",
    }),
  ]
```

**Comment by corysimmons** [comment]
`checks: 'pkce'` or `checks: 'none'`, `checks: 'both'` isn't a thing anymore.

**Comment by advename** [comment]
> `checks: 'pkce'` or `checks: 'none'`, `checks: 'both'` isn't a thing anymore.

`checks: 'pkce'` definitely is a thing - just depends on how you deploy your Next.js project/registration to the Authorization Server if you can't use state. I.e. `pkce` is used whenever you can't safely store the client secret, meaning in a client application.


> try adding `checks: "both"` on your provider

While this solves the issue, you should explain why tho. `both` uses either `pkce` or `state`. However, it should tho be noted that `state` is recommended since we are in a server environment, where we can safely use Client Secrets. `pkce` should only be used if there's no safe way to store client secret (aka, in a React Client Application).

---

Anyways, I had the same issues, without custom jwt en-/decoder, but simply a custom provider. The error stack track is the same tho.
I somehow managed to solve it. What could help you to debug this issue is:
- delete node_modules/ & package-lock.json -> run a fresh `npm install`
- check for newly added packages. In my case, this occured after i added `next-connect` on a new branch. Above step fixed the issue, and then i was able to install `next-connect` without any bugs.

**Comment by corysimmons** [comment]
You misread my comment (sorry, I didn't write it very clear).

I should've wrote

>_Use_ `checks: 'pkce'` or `checks: 'none'`.
>`checks: 'both'` doesn't work anymore.

Does `checks: 'both'` actually work? It's not on the type:

https://github.com/nextauthjs/next-auth/blob/0a7a9162286346c210dce1231821b2189daf1309/packages/next-auth/src/providers/oauth.ts#L20

**Comment by AnasTrk** [comment]
@corysimmons , you're absolutely right , the latest version doesn't support `checks: 'both'`.

**Comment by nasatome** [comment]
After a lot of debugging, I discovered that Hasura documentation is outdated, it is made for version 3.x and we are using version 4.x of NextAuth.


here is a working example

```js
import NextAuth from 'next-auth';
import GoogleProvider from 'next-auth/providers/google';
import EmailProvider from 'next-auth/providers/email';
import { PrismaAdapter } from '@next-auth/prisma-adapter';
import { PrismaClient } from '@prisma/client';


let jwt = require('jsonwebtoken');

const prisma = new PrismaClient();

export default async function auth (req, res) {
  const providers = [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
      authorization: {
        params: {
          prompt: 'consent',
          access_type: 'offline',
          response_type: 'code'
        }
      }
    }),
    EmailProvider({
      server: {
        host: process.env.EMAIL_SERVER_HOST,
        port: process.env.EMAIL_SERVER_PORT,
        auth: {
          user: process.env.EMAIL_SERVER_USER,
          pass: process.env.EMAIL_SERVER_PASSWORD
        }
      },
      from: process.env.EMAIL_FROM
    })

  ];

  return await NextAuth(req, res, {
      adapter: PrismaAdapter(prisma),
      providers,
      debug: false,
      session: {
        strategy: 'jwt',
        maxAge: 60 * 60 * 24,
        updateAge: 60 * 60 * 4
      },
      secret: process.env.NEXTAUTH_SECRET,
      jwt: {
        // The maximum age of the NextAuth.js issued JWT in seconds.
        // Defaults to `session.maxAge`.
        maxAge: 60 * 60 * 24,
        //openssl genrsa -out private.pem 2048
        //openssl rsa -in private.pem -pubout -out public.pem
        //https://www.google.com/search?q=install+pbcopy&oq=install+pbcopy
        //awk -v ORS='\\n' '1' public.pem | pbcopy
        //in hasura env set:
        // { "type": "RS256", "key": "<insert-your-public-key-here>"}
        //in nextjs env set JWT_SECRET the result:
        //awk -v ORS='\\n' '1' private.pem | pbcopy
        //JWT_SECRET: notes that it ends in \n
        secret: process.env.JWT_SECRET, //-----BEGIN PRIVATE KEY-----\xxxxxxxx...xxxxxxxx=\n-----END PRIVATE KEY-----\n
        // You can define your own encode/decode functions for signing and encryption
        async encode ({ secret, token, maxAge }) {
          return await jwt.sign(token, secret, { algorithm: 'HS256'});
        },
        async decode ({ secret, token, maxAge }) {
          return await jwt.verify(token, secret, { algorithms: ['HS256']});
        }
      },
      callbacks: {
        async jwt ({
          token,
          user
        }) {
          console.log('JWT function Invoked');
          console.log('USER in JWT:', user);
          console.log('token JWT:', token);
          if (user && user.id) {
            //databases queries to allowed roles from id user
            token['https://hasura.io/jwt/claims'] = {
              'x-hasura-allowed-roles': ['commercial', 'admin'],
              'x-hasura-default-role': 'admin',
              'x-hasura-user-id': user.id.toString()
            };
          }
          return token;
        },
        async session ({
          session,
          token,
          user
        }) {
          return session;
        },
        async signIn ({
          user,
          account,
          profile
        }) {
          console.log('==============================');
          console.log('user: ', user);
          console.log('account: ', account);
          console.log('profile: ', profile);
          console.log('==============================');
          // if (user.email.endsWith('@your-allowed-domain.com')) {
          //
          //   const currentUser = your query
          //
          //   if (currentUser?.disabled) {
          //     return false;
          //   }
          //
          //   return true;
          // }

          return false;
        }
      }
    }
  );
}

```

**Comment by corysimmons** [comment]
>`adapter: PrismaAdapter(prisma)`

Off-topic but it's super interesting (but makes perfect sense) you're using Prisma as your db adapter. I'm using this one https://www.npmjs.com/package/@skillrecordings/next-auth-hasura-adapter and it seems to work fine.

**Comment by devkiran** [comment]
Thanks, @nasatome. I got it working finally. 

```javascript
export default NextAuth({
  adapter: HasuraAdapter({
    endpoint: env.hasura.endpoint,
    adminSecret: env.hasura.adminSecret,
  }),
  providers: [
    BoxyHQSAMLProvider({
      issuer: env.jackson.endpoint,
      clientId: 'dummy',
      clientSecret: 'dummy',
    }),
  ],
  session: {
    strategy: 'jwt',
  },
  callbacks: {
    // Add the required Hasura claims
    async jwt({ token, profile }) {
      const allowedRoles = ['admin', 'developer'];
      const defaultRole = 'developer';

      // Fetch the group from profile and add it to the claims
      // If no group found in raw, assume user
      if (profile) {
        const raw = profile.raw as any;

        token['role'] = 'group' in raw ? raw.group : defaultRole;
      }

      return {
        ...token,
        'https://hasura.io/jwt/claims': {
          'x-hasura-allowed-roles': allowedRoles,
          'x-hasura-default-role': token.role,
          'x-hasura-role': token.role,
          'x-hasura-user-id': token?.sub,
        },
      };
    },

    // Add id and token (jwt) to the session object
    async session({ token, session }) {
      const encodedToken = jwt.sign(token!, env.nextauth.secret, {
        algorithm: 'HS256',
      });

      session.id = token.sub;
      session.token = encodedToken;
      session.role = token.role;

      return session;
    },
  },
  jwt: {
    async encode({ token, secret }) {
      return jwt.sign(token!, secret, { algorithm: 'HS256' });
    },
    async decode({ token, secret }) {
      return jwt.verify(token as string, secret, {
        algorithms: ['HS256'],
      }) as JWT;
    },
  },
});
```

**Comment by ryparker** [comment]
If you're using a custom JWT encoder, make sure to include the `token.state` in your claim under the `state` prop.

```ts
export const encode: JWTOptions['encode'] = async ({ secret, token }) => {
  if (!token) throw new Error('Missing token');
  const jwtClaims = {
    state: token.state, // <---- This is required for OAuth
    sub: token.sub,
    name: token.name,
    email: token.email,
    iat: Date.now() / 1000,
    exp: Math.floor(Date.now() / 1000) + 24 * 60 * 60,
    'https://hasura.io/jwt/claims': {
      'x-hasura-allowed-roles': ['user'],
      'x-hasura-default-role': 'user',
      'x-hasura-role': 'user_anonymous_inherited_role',
      'x-hasura-user-id': token.sub,
    },
  };
  return jwt.sign(jwtClaims, secret, { algorithm: 'RS512' });
};
```

**Comment by ivan-kleshnin** [comment]
> I'm using this one https://www.npmjs.com/package/@skillrecordings/next-auth-hasura-adapter and it seems to work fine.

It does not support camelCase option. I was going to fork the repo only to discover there're no sources available.
Only a minified distribution on NPM with no Github/Gitlab repo attached 😨

**Comment by corysimmons** [comment]
>I was going to fork the repo only to discover there're no sources available for this adapter.

Yeah, I asked a question in their Issues and they were like "Oh yeah we forgot about this project. We're going to delete it" 😄 

It seems like the solution is just to use Prisma & the Prisma adapter as an auth server—which works, but sucks we have to maintain some Prisma instance.

@coco98 please put someone on making a next-auth Hasura adapter. Next.js biggest framework. next-auth is one of the most popular auth solutions. Doesn't seem like a crazy amount of work.

**Comment by ivan-kleshnin** [comment]
> It seems like the solution is just to use Prisma & the Prisma adapter as an auth server—which works, but sucks we have to maintain some Prisma instance.

From my experiments I got an impression that Prisma is a bad pair to Hasura. It's much better than ORMs that require you to define models like Sequelize or TypeORM (because then you have 2 sources of truth: db for Hasura and models for ORM and you're already screwed at this point). Nevertheles Prisma did not look good after my tests.

1. Both Prisma and Hasura want to be the highest-level access for your database.
2. Both Prisma and Hasura provide migration tools, deeply engraved in how they are designed and operate.

The only reasonable approach would be to use Prisma without migrations and do only `db pull` and never `db push`.
But Prisma is db-agnostic while Hasura is pg-oriented. So `db pull` produce quite a messy `schema.prisma` file.
`DateTime?` fields will become esoteric `DateTime? @db.Timestamptz(6)` and so on. You'd also be tempted to write something in `schema.prisma`. Basically all tutorials and Prisma docs would become your enemy, pushing you into a wrong direction. Perphaps you or me could live with that by what about junior team members?!

So I actually think the best way is 1) write  DIY adapter based on whatever pg access library you prefer. Here: https://www.jakobmaier.at/posts/next-auth-postgres-adapter/ the author used native `pg`. A one step higher would be `slonik` or `sql-template-strings`. Adapter code is something I'd prefer to see in the app rather than a library.

2) Use Hasura API in most other cases where you'd need ORM and fallback to say `slonik` in other cases.

An alternative would be to find a mid-level library that would generate it's code from DB (as Hasura) and would be PG-oriented (as Hasura). But I never encountered someting mainstream like that.

**Comment by corysimmons** [comment]
In a month or so I'll make/maintain a Hasura adapter.

**Comment by Altroo** [comment]
`
FacebookProvider({
    idToken: true,
    clientId: `${process.env.FACEBOOK_ID}`,
    clientSecret: `${process.env.FACEBOOK_SECRET}`,
    checks: ['pkce', 'state'], // both
  }),
  `

**Comment by corysimmons** [comment]
I ended up switching off Hasura, but I did stumble upon this https://github.com/AmruthPillai/next-auth-hasura-adapter
