### ISSUE TITLE
Setting up Twitter OAuth to get the users email address not present

### ISSUE THREAD

**Issue by dcantatore** [nextauthjs/next-auth#4194]
### Provider type

Twitter

### Environment

  System:
    OS: macOS 12.1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 98.1.35.104
    Chrome: 99.0.4844.51
    Firefox: 90.0.2
    Safari: 15.2
  npmPackages:
    next: ^12.0.10 => 12.0.10 
    next-auth: ^4.2.1 => 4.2.1 
    react: ^17.0.2 => 17.0.2 

### Reproduction URL

https://private.development.site

### Describe the issue

When you are setting up OAuth with twitter they have changed the oauth setup, see screen here:

![Screen Shot 2022-03-16 at 9 10 53 AM](https://user-images.githubusercontent.com/15852431/158598513-ab4985a1-d5b9-4059-843b-95f60d4f7815.png)

In the above image there is no longer a third tab for the email option but it is now in the box at the bottom.

![Screen Shot 2022-03-16 at 9 11 08 AM](https://user-images.githubusercontent.com/15852431/158598351-eed6b468-baa9-4029-848d-a50f632243c8.png)

This image is what you see when you go into the edit on the first image.

The only way to get the optional request to have a users email address is to check 1.0a. 
- When doing so with 2.0 checked you do not get the email address. 
- Using OAuth 1.0a without the version set in the provider causes it to fail and produce this is the console:
```
[next-auth][error][GET_AUTHORIZATION_URL_ERROR] 
https://next-auth.js.org/errors#get_authorization_url_error undefined {
  statusCode: 401,
  data: '{"errors":[{"code":32,"message":"Could not authenticate you."}]}'
}
[next-auth][error][SIGNIN_OAUTH_ERROR] 
https://next-auth.js.org/errors#signin_oauth_error undefined {
  error: {
    statusCode: 401,
    data: '{"errors":[{"code":32,"message":"Could not authenticate you."}]}'
  },
  provider: {
    id: 'twitter',
    name: 'Twitter (Legacy)',
    type: 'oauth',
    version: '1.0A',
    authorization: { url: 'https://api.twitter.com/oauth/authenticate', params: {} },
    accessTokenUrl: 'https://api.twitter.com/oauth/access_token',
    requestTokenUrl: 'https://api.twitter.com/oauth/request_token',
    profileUrl: 'https://api.twitter.com/1.1/account/verify_credentials.json?include_email=true',
    profile: [Function: profile],
    clientId: 'HIDDEN',
    clientSecret: 'HIDDEN',
    signinUrl: 'http://localhost:3000/api/auth/signin/twitter',
    callbackUrl: 'http://localhost:3000/api/auth/callback/twitter'
  },
  message: undefined
}
```

### How to reproduce

Create a new nextjs project, use the twitter provider, and try to create an Oauth app with a dev account on twitter.

### Expected behavior

It should not throw an error when using v1. 
It should have a scope option when using v2 to get the email address.

**Comment by dcantatore** [comment]
I ended up finding things like this after I posted but the errors are still a real thing with using v1 with v2 enabled in twitter settings.

Would also be worth updating the screenshots on the docs pages, could do a PR for them if anyone thinks it's worth the time to add them plus notes that are in the implementation example since it's not the first place you go to info on usage.

**Comment by siegerts** [comment]
Updated docs never hurt 😄

**Comment by ndom91** [comment]
@dcantatore yeah we'd be thrilled if you could prepare a PR to update the docs / screenshots!

Regarding the OAuth2.0 not returning the Email address on its own, as you've mentioned its simply not supported by Twitter at the moment. Check out the example response to the `/users/me` API endpoint at the bottom of [this page](https://developer.twitter.com/en/docs/twitter-api/users/lookup/api-reference/get-users-me#Optional).

**Comment by ndom91** [comment]
Going to close this issue as it's a config problem with Twitter. We just got a PR to update the docs as well 🎉

**Comment by Enrico2** [comment]
This works:
```typescript
providers: [
    Google({ allowDangerousEmailAccountLinking: true }),
    Twitter({
      // Opt into OAuth 2.0 so we can request the newer scopes
      allowDangerousEmailAccountLinking: true,
      // Request the email-capable scope in addition to basic read + offline
      authorization: 'https://x.com/i/oauth2/authorize?scope=users.read%20tweet.read%20offline.access%20users.email',
      // Ask the v2 userinfo endpoint to include the confirmed email
      userinfo: 'https://api.x.com/2/users/me?user.fields=confirmed_email,profile_image_url,verified',
      // Map the provider profile to NextAuth's user shape, pulling email from confirmed_email when present
      profile(profile) {
        const data = profile.data as typeof profile.data & { confirmed_email: string | null }
        return {
          id: data.id,
          name: data.name,
          email: data.confirmed_email ?? null,
          image: data.profile_image_url ?? null,
        }
      },
    }),
  ]
  ```
