### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by bmichotte** [nextauthjs/next-auth#4198]
### Adapter type

@next-auth/prisma-adapter

### Environment

```
  System:
    OS: macOS 12.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 91.80 MB / 16.00 GB
    Shell: 3.3.1 - /usr/local/bin/fish
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 90.1.23.73
    Chrome: 99.0.4844.74
    Firefox: 98.0
    Safari: 15.3
  npmPackages:
    next: 12.1.0 => 12.1.0 
    next-auth: ^4.3.0 => 4.3.0 
    react: 17.0.2 => 17.0.2 


  npmPackages:
    @next-auth/prisma-adapter: ^1.0.2 => 1.0.2 
```

### Reproduction URL

https://github.com/bmichotte/prisma-adapter

### Describe the issue

When using `@next-auth/prisma-adapter` version 1.0.2, the following issue appears 

![image](https://user-images.githubusercontent.com/235510/158614443-22ad0fb7-4ce3-4069-966d-77212a5ec193.png)

(copy-paste here, sorry for the identation)
```
Server Error

SyntaxError: Unexpected token 'export'
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
/Users/benjamin/Developer/tests/prisma-adapter/node_modules/ (next-auth/prisma-adapter/dist/index.js (1)
Object.compileFunction
node:vm (352:18)
wrapSafe
node:internal/modules/cjs/loader (1031:15)
Module._compile
node:internal/modules/cjs/loader (1065:27)
Object.Module._extensions..js
node:internal/modules/cjs/loader (1153:10)
Module.load
node:internal/modules/cjs/loader (981:32)
Function.Module._load
node:internal/modules/cjs/loader (822:12)
Module.require
node:internal/modules/cjs/loader (1005:19)
require
node:internal/modules/cjs/helpers (102:18)
Object.@next-auth/prisma-adapter
file:/Users/benjamin/Developer/tests/prisma-adapter/.next/server/pages/api/auth/[...nextauth].js (22:18)
__webpack_require__
file:/Users/benjamin/Developer/tests/prisma-adapter/.next/server/webpack-api-runtime.js (33:42)
```

### How to reproduce

```
git clone https://github.com/bmichotte/prisma-adapter
yarn install
yarn dev
```

then open http://localhost:3000

You should be redirected to http://localhost:3000/api/auth/error?error=Configuration because Prisma is not configured, but even with a configuration, you have the same error

### Expected behavior

Using version 1.0.1, you have the correct error

![image](https://user-images.githubusercontent.com/235510/158615448-9d96343b-5fa0-4345-8f8c-83678a5981aa.png)

**Comment by temrb** [comment]
Check the updates on package-lock json / package lock.

Try downgrading to "next": "^12.0.10"... I had kind of the same error...

 "Cannot use import statement outside a module" on "next": "^12.1.0". 
 Downgrading reverted the issue for me.

**Comment by balazsorban44** [comment]
This seems to have been caused by our recent monorepo change. It looks like we accidentally changed the outputs to ESM. Downgrading to `1.0.1` would be the workaround for now. @ThangHuuVu or I will be able to look at this soon, thanks for reporting!

**Comment by JoaoFOliveira** [comment]
@balazsorban44 I had this same issue today. Downgraded to 1.0.1, now the whole server crashes and still wont work.

```
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from .env
event - compiled client and server successfully in 214 ms (172 modules)
wait  - compiling /login (client and server)...
event - compiled client and server successfully in 671 ms (175 modules)
wait  - compiling /api/auth/[...nextauth]...
event - compiled client and server successfully in 30 ms (188 modules)
zsh: killed     npm run dev
```

**Comment by goforbg** [comment]
@balazsorban44  @JoaoFOliveira Had the same issue with **Mongo db adapter**, 
Here's my new package.json that worked for me, downgrading next to 12.0.1 made no change, but downgrading to 1.0.1 fixed it. 

  "dependencies": {
    "@crewcharge/core": "^1.0.5",
    **"@next-auth/mongodb-adapter": "1.0.1",**
    **"mongodb": "^4.4.0",**
    **"next": "^12.1.0",**
    **"next-auth": "4.2.1",**
  },

**Comment by iKunalmathur** [comment]
Downgrading "@next-auth/prisma-adapter" to 1.0.1 also works

"dependencies": {
    **"@next-auth/prisma-adapter": "^1.0.1",**
    "@prisma/client": "^3.11.0",
    "next": "12.1.0",
    "next-auth": "^4.3.0",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },

**Comment by jberrydev** [comment]
Hey guys.  I tried downgrading next-auth to 4.2.1 and @next-auth/prisma-adapter to 1.0.1.  I still get the Unexpected token export error.  Do we know the versions that will work for the time being?

**Comment by iKunalmathur** [comment]
Hey @jberrydev, I'm unable to find the exact solution to your problem but here is my nextauth js project I hope you find something useful 

https://github.com/iKunalmathur/learn-next-auth

**Comment by jberrydev** [comment]
> Hey @jberrydev, I'm unable to find the exact solution to your problem but here is my nextauth js project I hope you find something useful
> 
> https://github.com/iKunalmathur/learn-next-auth

I have followed what you have and still receive `error - SyntaxError: Unexpected token 'export'`

**Comment by jberrydev** [comment]
> @jberrydev @iKunalmathur I'm not sure why the nextauth team does not publish the versions here on github but you can find next-auth 4.3.1 as well as the 1.0.3 version of the adapters. Those version fix this issue.

I have done this and still get the error.  After further investigation it appears to be in `next-auth\jwt\index.js` 
```
Object.defineProperty(exports, "__esModule", {
  value: true
});
var _exportNames = {
  encode: true,
  decode: true,
  getToken: true
};
exports.decode = decode;
exports.encode = encode;
exports.getToken = getToken;
```
exports being undefined.  I am using NX so maybe it is something in my setup for ts or some next config option.  Any ideas would be great.  Will continue to debug.

**Comment by takky94** [comment]
I tried the downgrade too, but it didn't work.
So here's what I'm writing, is there anything wrong with this code?

```ts
// next-auth.d.ts

import { /*  custom user type  */ } from '.prisma/client'
import NextAuth, { DefaultSession } from 'next-auth'
import { User } from 'next-auth/core'

declare module 'next-auth' {
  interface Session extends DefaultSession {
    token?: string
    data:
      | { /* custom user type */ }
      | User
    expires: Date
  }
}


// [...nextauth].ts

const prisma = new PrismaClient()

export default NextAuth({
  adapter: PrismaAdapter(prisma),
  providers: [ /* ... */ ],
  callbacks: {
    async session({ session, user }) {
      const userData = await prisma.user
        .findUnique({
          where: {
            id: user.id,
          },
          select: {
            // ...
            sessions: true,
          },
        })
        .catch((e) => {
          throw e
        })
        .finally(async () => {
          await prisma.$disconnect()
        })
      if (!userData) {
        return {
          data: null,
          expires: session.expires,
        }
      }

      const { sessions, ...data } = userData
      return Promise.resolve({
        data: data,
        token: sessions.at(-1)?.sessionToken, // Latest session data for a specific user stored in DB
        expires: session.expires,
      })
    },
  },
 // ...
})
```
