### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by claudiorivera** [nextauthjs/next-auth#4209]
### Adapter type

@next-auth/mongodb-adapter

### Environment

```bash
  System:
    OS: macOS 12.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 61.76 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.1 - ~/Library/pnpm/node
    npm: 8.5.0 - ~/Library/pnpm/npm
  Browsers:
    Safari: 15.4
  npmPackages:
    next: ^12.0.11-canary.4 => 12.1.0 
    next-auth: latest => 4.3.0 
    react: ^17.0.2 => 17.0.2 


  npmPackages:
    @next-auth/mongodb-adapter: 1.0.2 => 1.0.2 
```

### Reproduction URL

https://github.com/claudiorivera/next-auth-example

### Describe the issue

If `pnpm` is not supported, feel free to ignore this!

I've been migrating my projects from `yarn` to `pnpm` and most of my them have worked without a hitch, but I'm getting an error from the `mongodb-adapter` when trying to develop my [`game-night`](https://github.com/claudiorivera/game-night) repo locally.

I reproduced with the [next-auth-example](https://github.com/nextauthjs/next-auth-example) for this issue.

Here's the call stack:
```
Call Stack
<unknown>

/Users/claudio/Developer/next-auth-example/node_modules/.pnpm/ (next-auth+mongodb-adapter@1.0.2_mongodb@4.4.1+next-auth@4.3.0/node_modules/@next-auth/mongodb-adapter/dist/index.js (2)
Object.compileFunction

node:vm (352:18)
wrapSafe

node:internal/modules/cjs/loader (1032:15)
Module._compile

node:internal/modules/cjs/loader (1067:27)
Object.Module._extensions..js

node:internal/modules/cjs/loader (1157:10)
Module.load

node:internal/modules/cjs/loader (981:32)
Function.Module._load

node:internal/modules/cjs/loader (822:12)
Module.require

node:internal/modules/cjs/loader (1005:19)
require

node:internal/modules/cjs/helpers (102:18)
Object.@next-auth/mongodb-adapter

file:///Users/claudio/Developer/next-auth-example/.next/server/pages/api/auth/[...nextauth].js (22:18)
__webpack_require__

file:///Users/claudio/Developer/next-auth-example/.next/server/webpack-api-runtime.js (33:42)
```

### How to reproduce

- On a fresh install of macOS
- Installed `pnpm`
- Installed Node with `pnpm env use --global lts`
- Cloned the [next-auth-example](https://github.com/nextauthjs/next-auth-example)
- Followed the instructions [from the docs](https://next-auth.js.org/adapters/mongodb) (substituting the `npm`/`yarn` commands for their `pnpm` equivalent)
- Ran `pnpm dev`
- In the app, click on `Sign In`
- Unhandled server error appears

### Expected behavior

I expect to get the `next-auth-example`'s sign-in page instead of an unhandled server error.

**Comment by temrb** [comment]
Had similar issue-- fix was to downgrade next auth/ next for me.

https://github.com/nextauthjs/next-auth/issues/4198#issuecomment-1069588130

**Comment by claudiorivera** [comment]
> Had similar issue-- fix was to downgrade next auth/ next for me.
> 
> [#4198 (comment)](https://github.com/nextauthjs/next-auth/issues/4198#issuecomment-1069588130)

Ah, I'll try that! Thanks!

**Comment by dmolin** [comment]
I can confirm that downgrading @next-auth/mongodb-adapter to version 1.0.1 "fixes" the issue for the moment.
