### ISSUE TITLE
Circular redirect when protecting route within getServerSideProps

### ISSUE THREAD

**Issue by ryanbahan** [nextauthjs/next-auth#421]
*Please refer to the [documentation](https://next-auth.js.org/getting-started/introduction), the [example project](https://github.com/iaincollins/next-auth-example) and existing issues before creating a new issue.*

**Your question**
A clear and concise question.

Am I missing a critical step in how server-side redirects are handled, or how the login redirect callback works? Issue below.

**What are you trying to do**
A description of what you are trying to do.

Trying to protect a route by checking for a session on the server, and manually redirecting if there isn't one. Most of the time this works perfectly fine. 

However if I'm on the protected page when the JWT expires and I get redirected to login, after the login is successful I get stuck in an infinite loop of constantly having to log-in and getting redirected to the login page. This happens with both oauth and email login. If I manually re-type the URL i'm supposed to redirect to, or any other URL within my app, the session works again as expected. But the login redirect fails every time, until manually going to a new URL seems to "fix" it.

Code:

<img width="551" alt="Screen Shot 2020-07-10 at 2 09 34 PM" src="https://user-images.githubusercontent.com/54119863/87202208-488c8e80-c2bd-11ea-94ca-766d5d3b52ec.png">

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
Hmm it sounds like something naughty is getting set as a value in the callbackUrl cookie. We might need to (a) clear this cookie after use (b) make sure it can't be something like the sign in page (if that happens somehow).

If you happen to notice anything about this please do share, otherwise will try and think of defensive things we can do to try and prevent it from being triggered.

**Comment by ryanbahan** [comment]
My current solution is to check for session on the server, but do the redirect on the client if necessary. I'll dig into this a little bit more soon, and let you know if I find anything.

**Comment by thanhnha121** [comment]
I had the same problem a few days ago. Then I had changed from:
`res.writeHead(301, { Location: "/login" });`
To
`res.redirect(301, "/login");`
And it worked!

Hey @iaincollins, Do you have any idea from my fix?

**Comment by thanhnha121** [comment]
I had the same problem a few days ago. Then I added this line into current nginx config:
```
    location / {
        ...
        add_header Cache-Control 'max-age=0';
        ...
    }
```
And it worked!

Hey @iaincollins, Do you have any idea from my fix?

**Comment by GeeWee** [comment]
For anyone finding this issue - I got circular redirects as well when I had errors in my `pages` configuration object, so the error might be found in weird places.
