### ISSUE TITLE
OAUTH - PKCE - Can we autosign into a provider at the middleware?

### ISSUE THREAD

**Issue by nvelagaleti** [nextauthjs/next-auth#4211]
### Environment

System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 36.85 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.14.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
    Safari: 14.0.3
  npmPackages:
    next-auth: ^4.2.1 => 4.3.0 
    react: ^17.0.2 => 17.0.2 
    next:  ^12.0.1 => 12.0.10

### Reproduction URL

none

### Describe the issue

I am working on a custom auth provider. We just have one provider. In my case, I would rather want the default signin to directly start the PKCE flow without showing any /auth/api/signin page.
I am thinking at the middleware, I would like to make a check to see if the session exists - If not, I would rather call signIn('providername'). I do not want to see a default signin page here. 

Is this a possibiliy?

As a workaround, I could do it at the page level using useSession() - but I really want to do at the middleware for all pages
const { data: session } = useSession({
        required: true,
        onUnauthenticated() {
                // The user is not authenticated, handle it here.
                signIn('ce');
            },
    });

### How to reproduce

Explained in the issue section.

### Expected behavior

Middleware to support auto signing in the provider.

**Comment by balazsorban44** [comment]
Not currently as documented: https://next-auth.js.org/configuration/nextjs#caveats

We would like to support it in the future.

As a workaround, you could create a dummy sign-in page like:

```js
// pages/signin.js
import * as React from "react"
import { signIn } from "next-auth/react"

export default Page() {
  React.useEffect(() => {
   signIn("ce")
  }, [])
  return null
}
```

And set `pages.signIn: "/signin"`. https://next-auth.js.org/configuration/nextjs#pages

**Comment by nvelagaleti** [comment]
Thanks @balazsorban44 - I have a question here - I have the default middleware 

export { default } from "next-auth/middleware";

I have added the signin page as you mentioned. 
Added pages block to provider config.

pages: {
        signIn: '/signin'
 },

But what I see is too many redirects and in the url I see this. Should I add some more logic in the middleware to not call signin page by checking token or something?

- http://localhost:3000/api/auth/signin?callbackUrl=http%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fsignin%3FcallbackUrl%3Dhttp%3A%2F%2Flocalhost%3A3000%2Fobserve

**Comment by majkl-zumberi** [comment]
@nvelagaleti i have the same problem, were you able to solve it?
