### ISSUE TITLE
Add profile to `linkAccount` event data

### ISSUE THREAD

**Issue by michaelhays** [nextauthjs/next-auth#4218]
### Description 📓

Hello, when linking an OAuth account to a user, I'd like to set `User.image` to the profile picture of the newly linked account, if the user does not currently have an image.

Here's an example of how I'd like to be able to do this in the [`linkAccount` event](https://next-auth.js.org/configuration/events#linkaccount):

```ts
events: {
  async linkAccount({ user, profile }) {
    if (!user.image && profile.image) {
      await prisma.user.update({
        where: { id: user.id },
        data: { image: profile.image },
      })
    }
  },
}
```

This would rely NextAuth.js to send `profile` in the data with the `linkAccount` event, [here](https://github.com/nextauthjs/next-auth/blob/bf4916dd7087e7f8919b665f5fb3de3ae4750f97/packages/next-auth/src/core/lib/callback-handler.ts#L157).

Could we add this? I tested it out locally (by manually editing my `node_modules`), and it worked as expected. Happy to add it in a PR.

(Also, is the `linkAccount` event the best place to do this? To me, it feels like an intuitive place to put it, but the documentation for events seem to imply that events should only be used for debugging/audit logs.)

### How to reproduce ☕️

See code snippet above.

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by ndom91** [comment]
@michaelhays so we actually support adding additional fields to the user schema already. You have to add them to your prisma schema and run `migrate` again and then you can pass the `profile.image` field, for example, in your provider's `profile()` callback. (See: https://next-auth.js.org/adapters/models#user).

**Comment by michaelhays** [comment]
Thanks for the response @ndom91! So the issue here isn't actually adding to the user schema (my schema already has a field for `User.image`), it's that I'm not able to access the `profile.image` when linking an OAuth account.

For my use case, a user can only create an account with the email provider, and not any of the OAuth providers. However, a user can link an OAuth account once they've created their account, and I'd like to update their `User.image` with the value of `profile.image`. I followed the logic in the codebase, and it doesn't seem like the `profile` is exposed anywhere during the `linkAccount` logic, which I need to set the `User.image`.

This is why I was suggesting adding `profile` to the `linkAccount` event [here](https://github.com/nextauthjs/next-auth/blob/bf4916dd7087e7f8919b665f5fb3de3ae4750f97/packages/next-auth/src/core/lib/callback-handler.ts#L157), so that:

```ts
await events.linkAccount?.({ user, account })
```

would become:

```ts
await events.linkAccount?.({ user, account, profile })
```

And then I'd write this in my `linkAccount` event handler:

```ts
events: {
  async linkAccount({ user, profile }) {
    if (!user.image && profile.image) {
      await prisma.user.update({
        where: { id: user.id },
        data: { image: profile.image },
      })
    }
  },
}
```

**Comment by ThangHuuVu** [comment]
To me, this is a reasonable suggestion. It would make `linkAccount` and `signIn` API look almost the same. 
> Also, is the linkAccount event the best place to do this?

I think this is the intented place for handling side effects like your use case 👍

**Comment by ndom91** [comment]
@michaelhays ah okay, I must have misunderstood. I agree with @ThangHuuVu, this sounds reasonable. If yuo want to prepare a PR, we'd be happy to take a look!

**Comment by michaelhays** [comment]
Thanks y'all! Just opened a PR for it :)
