### ISSUE TITLE
Skip fetching session in provider if cookie doesn't exist

### ISSUE THREAD

**Issue by ifightcrime** [nextauthjs/next-auth#4224]
### Description 📓

Currently the React context provider always makes a request to `/api/auth/session` when the page loads, even if the user isn't logged in (no `session-token` cookie exists). Couldn't we just skip making the call to `getSession` in that case? Would be a nice performance optimization, especially for running on Vercel/Netlify.

i.e. If `session-token` cookie isn't present, don't make the call to `getSession` here: https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/react/index.tsx#L327-L329

### How to reproduce ☕️

Use the React `SessionProvider` and notice that it makes a request to `/api/auth/session` on every page load, even if the user is logged out. 

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
The session cookie is HttpOnly, so there is no way to know if the session exists or not, just by looking at `document.cookie`. This is by design (in the name of security) and not a NextAuth.js limitation, just how cookies work.
