### ISSUE TITLE
Is it just me or useSession() called at client side is not triggering the jwt callback

### ISSUE THREAD

**Issue by kecoliva** [nextauthjs/next-auth#4227]
### Environment

System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics        
    Memory: 4.98 GB / 15.40 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (98.0.1108.62)
  npmPackages:
    next: 12.1.0 => 12.1.0
    next-auth: ^4.2.1 => 4.3.1
    react: 17.0.2 => 17.0.2

### Reproduction URL

https://github.com/kecoliva/nextjs-jwt-callback-issue

### Describe the issue

I expect the jwt callback to be fired everytime the useSession() is called which is said here: https://next-auth.js.org/configuration/callbacks#jwt-callback

### How to reproduce

Click the "New Event" button here to trigger render the modal

![image](https://user-images.githubusercontent.com/46006869/159191691-8f8b2e66-7d65-493a-a539-a8231b40521b.png)

### Expected behavior

So you can see in NewEventModal.component.tsx:22 where useSession() is called so everytime the modal is rendered I expect for the jwt to fired.

**Comment by balazsorban44** [comment]
There is no session refetching by default, `useSession` uses what's in the cache. You can poll the session if you need to trigger the JWT callback.

https://next-auth.js.org/getting-started/client#refetch-interval

**Comment by kecoliva** [comment]
@balazsorban44 So if I set a refetchInterval then everytime I call useSession() it will for sure fire the jwt callback? Just tried this before and it still doesn't seem to fire the jwt callback.

**Comment by IrmakD1** [comment]
> There is no session refetching by default, `useSession` uses what's in the cache. You can poll the session if you need to trigger the JWT callback.
> 
> https://next-auth.js.org/getting-started/client#refetch-interval
> 
> Another option is using `getSession` which always visits the backend: https://next-auth.js.org/getting-started/client#getsession

@balazsorban44 Thanks for the clarification. Do you know who is responsible for updating the documentation to reflect this? Because as @kecoliva rightly stated, the documentation is currently stating calling useSession() will call the JWT callback, which it doesn't. My team has lost several days trying to debug an issue while working under this assumption.
