### ISSUE TITLE
Does the Session Provider app wrapper fetch data from NEXTAUTH_URL?

### ISSUE THREAD

**Issue by theotarr** [nextauthjs/next-auth#4272]
### Question 💬

I am building a monorepo (Turborepo) that has an express wrapper of Next Auth on port 4000 and a Next.js app on port 3000 (Source code [here](https://github.com/theotarr/next-auth-microservice)). Currently, I am fetching session data manually (not using the built-in `useSession` and `signIn`/`signOut` hooks). I have not been able to figure out how to integrate the built-in data fetchers with my custom backend. 

I have tried specifying the `baseUrl` and the `basePath`, none of them have worked.
```javascript
const MyApp = ({ Component, pageProps }: AppProps) => (
  <SessionProvider
    session={pageProps.session}
    basePath="http://localhost:4000/api/auth"
  >
      <Component {...pageProps} />
  </SessionProvider>
)
```
Or
```javascript
const MyApp = ({ Component, pageProps }: AppProps) => (
  <SessionProvider
    session={pageProps.session}
    baseUrl="http://localhost:4000"
  >
      <Component {...pageProps} />
  </SessionProvider>
)
```

I am wondering if it is even possible in the current version of Next-Auth to set a different hostname/baseUrl in the Session provider. 

### How to reproduce ☕️

[Here](https://github.com/theotarr/next-auth-microservice) is a minimal reproduction that uses Github OAuth and Prisma with PostgreSQL for storage.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
NextAuth.js will send requests to the same app, so changing the port has no effect.

Cookies are only created for the same domain.
