### ISSUE TITLE
Warning: A cookie associated with a cross-site resource at http://googleusercontent.com/ was set without the `SameSite` attribute.

### ISSUE THREAD

**Issue by ricjohn-acosta** [nextauthjs/next-auth#428]
*Please refer to the [documentation](https://next-auth.js.org/getting-started/introduction), the [example project](https://github.com/iaincollins/next-auth-example) and existing issues before creating a new issue.*

**Your question**
I was wondering if this warning `A cookie associated with a cross-site resource at http://googleusercontent.com/ was set without the SameSite attribute.` is related to next-auth by any chance? How would I fix this?

EDIT: Forgot to add that I'm getting a GET 403 from lh3.googleusercontent.com aswell
EDIT2: could be related to google api, it couldn't be the rate limit since I'm the only one using the app?

**What are you trying to do**
_A description of what you are trying to do._

I'm trying to display a signed in user's gmail profile picture by using the image url provided by the session object but above warning is causing it to not load.

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [X] Could not find relevant documentation
* [X] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by ndom91** [comment]
Google usually gives a 429 when rate-limited. 403 usually means forbidden, meaning you're not allowed to access that resource. I currently use the `session.user.image` from the google oauth session response as well and it doesn't look like it needs any authentication. I copied the resulting Url of my profile image out of my project just now and was able to request the resource in an incognito browser window as well, so I'm not sure of what is going on here.. Are you requesting these images in any sort of non-standard way? You can simply set it as the src of an img.
