### ISSUE TITLE
Setting error page in `pages` does not redirect the user to the defined error pages

### ISSUE THREAD

**Issue by borisno2** [nextauthjs/next-auth#4280]
### Question 💬

I am trying to setup a custom error pages using the `pages` configuration, and it doesn't seam to work for me. look at the code https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/core/index.ts#L140 it looks like the custom error page is only returned if the error is not is not one of these ones
```javascript
  if (
          [
            "Signin",
            "OAuthSignin",
            "OAuthCallback",
            "OAuthCreateAccount",
            "EmailCreateAccount",
            "Callback",
            "OAuthAccountNotLinked",
            "EmailSignin",
            "CredentialsSignin",
            "SessionRequired",
          ]
```
is there any reason the `if (pages.error) ` is not before this line?
Thanks!

### How to reproduce ☕️

set `pages.error` to a custom value and force an error.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by georgiosd** [comment]
@borisno2 was this solved?

**Comment by borisno2** [comment]
Hi @georgiosd,
In my case I was not accounting for the errors that are handled by the signin page as per the [next-auth docs] (https://next-auth.js.org/configuration/pages#sign-in-page). So in my case it was expected behaviour as per [here](https://github.com/nextauthjs/next-auth/blob/2469e44572f23f709fa8c5c65c6b7a4eb2383e9f/packages/next-auth/src/core/index.ts#L179).

Once my custom signin page handled these I was OK.
