### ISSUE TITLE
Does nextauth work with the api and nextauth on another domain (i.e. CORS)? Answer: yes, see below for how

### ISSUE THREAD

**Issue by richardpickett** [nextauthjs/next-auth#4327]
### Question 💬

I've got nextauth configured and working correctly as long as the frontend pages are served by the same nextjs instance that's running the API.

We're trying to get the frontend pages to work from the root domain name, and the api with nextath to be on the subdomain api.<domain>.com

Example:
Frontend: <domain>.com
API w/ nextauth: api.<domain>.com

We think since the jwt is stored in the cookies on the connection to api.<domain>.com, further calls to the api would have that session, but they don't.

Our login process looks like this:

1. On <domain>.com you click a "login" link that goes to api.<domain>.com/login.
2. On api.<domain>.com/login the query string is processed to determine the service to oauth against and the reuturn URL (typically the page the user was originally on).
3.  api.<domain>.com then calls signIn() with those options.
4. The user is walked through the login process with that oath provider and sent back to the original page (on step 1).
5. Further calls to the API from that page fail to get the user from the session.

This all works correctly when we start on api.<domain>.com, further calls to api.<domain>.com from api.<domain>.com pages work as expected.  Just when we start/end on <domain>.com.

No, it's not CORS (we had that issue orgiinally and since then handle OPTIONS and we didn't get CORS errors any more).  We see the requests hit the backend (and can even debug it) and getting the session fails, which failure it returns to the client.

I've read a lot of "separate backend" posts, but none of them seem to be this issue - it appears they are all looking for the nextauth to live on a separate backend than their api - in my case I'm wanting the user (no matter what site they are on) to auth through nextauth on the same subdomain as the api, and then call that api using their nextauth session.

And I get it, "nextauth isn't meant to be an IDP" - but again, that's more the model of a single instance running nextauth serving as auth for a lot of different backends on other (sub)domains.  But that's not what I'm doing.

### How to reproduce ☕️

1. Create a nextauth based app, using a sub-domain (like api.<domain>.com), configured to use google for auth and demonstrate it's working correctly.
2. Create a login page that automatically calls signIn("google") passing the callbackUrl to the referrer (get from headers).
3. Create a second page with a way to test the api call that demonstrates the session is valid (an api call like api.<domain>.com/test).
5. On that second page create a link to the login page.
6. While logged in, test the api call to confirm it works as expected.
7. Clear your cookies
8. The api call should now fail because you've cleared your session.
9. Click the link to go to the login page, it should create your session via google oath
10. Confirm the test api call now succeeds.

I have all of that working ^^^^^

Here's the part that doesn't work:
1. Create a second site from the root domain (i.e. <domain>.com), with the second page in the app above.
2. Confirm the api test call (api.<domain>.com/test) fails because you're not logged in.
3. Click the login link (which will go to api.<domain>.com/login) and login using the same google acct.
4. Confirm you have the session cookies in your browser.
5. Confirm the test api call now succeeds.  <----- This is the only thing that does't work for me.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by richardpickett** [comment]
Closing Issue.

**Comment by subimage** [comment]
Thanks for this. Dealing with similar issue of Next.js app deployed to Google Cloud Run with Firebase hosting; receivng the errors:

```
[next-auth][error][CALLBACK_OAUTH_ERROR]
https://next-auth.js.org/errors#callback_oauth_error checks.state argument is missing TypeError: checks.state argument is missing
```

**Comment by richardpickett** [comment]
Yeah, I don't know how to help on that one, but I will drop this update because I just spent two full days debugging this weird problem.

After extensively trying all the options to figure out which ones were vital, I've narrowed down all the wackiness.

Here are just some of the options I just tested:

- Can Access-Control-Allow-Origin be set to *, or do I have to use the origin if it's a different site?
- Is credentials: 'include' required on all the client calls?
- What are all the Access-Control-Allow-Headers I need?
- What about Vary: "Origin"?
- And Access-Control-Allow-Credentials?

So quick summary of all the above, you **must**:

1. Have headers setup in next.config.js
2. A CORS handler in every request that sets the Access-Control-Allow-Origin to the request origin (if not same server) (see doCORS above)
3. All the next-auth cookies set to sameSite: "none", httpOnly, and secure.
4. Client calls have to have `credentials: "include"` in their request options.
5. Your client has to call API paths that won't be redirected to the "correct" endpoint by nextjs routing.

For 1-4, trust me, don't try to cherry pick from the above, copy/paste it all into your app.  If anything isn't clear, hit me up on twitter and I'll come back to make it more clear.

For number 5, I about lost my mind.  My test was two simple calls.  First getUser (and if no user, show login button), and then get some data.  Both were `GET` calls.  both were made back-to-back - as matter of fact, the browser used the same connection for them because the second one came so fast.

But the second call would always fail for CORS, it said I couldn't send credentials if Access-Control-Allow-Origin was *.  But the `getUser` call seemed to have no problem with it at all.

Here's what was going on under the hood.  The `getUser` call worked like this:

1. Browser connects, sends request.
2. Nextjs routes it to the handler
3. Handler had the doCORS in it, so it sent back headers that had the orgin in Access-Control-Allow-Origin.
4. Handler then sent back the user data

The browser accepted it.

The `getSomeOtherData` call looked like this:

1. Browser connects, sends request.
2. Nextjs saw the request URL ended with / (i.e. https://someSite.com/endpointName/), so it redirected it to the same URL without the ending slash.
3. Since Nextjs was redirecting, it grabbed the headers in `next.config.js`, which had * for Access-Control-Allow-Origin.
4. The browser takes note of the allowed origin being * instead of the domain the webpage was loaded from.
5. Then the browser goes to obey the redirect, and can't send the credentials because it just got the * telling it not to.  _Credentials (cookies) can't be sent unless both Access-Control-Allow-Origin is set to the client domain and the client uses the option credentials: "include" - unless the api fqdn is the same as the client page_.  So the browser throws an error.

I kept thinking nextjs was seeing an OPTIONS request and not delivering it to the handler, and was trying all kinds of things like writing a custom server.js, etc.  I even through apache in front as a reverse proxy and was inserting the Access-Control-Allow-Origin header to have the origin just to get it to work.

Once I realized there was a `Location` header being sent back, I trimmed the `/` off the URL and suddenly it all worked, no custom server, no need for apache.

**Comment by michaelangrivera** [comment]
@subimage were you able to figure out that issue? Running into the same thing.

**Comment by alexng353** [comment]
@richardpickett What is the cookiePrefix variable? What should I set it to/where to find docs?

**Comment by choutkamartin** [comment]
> @richardpickett What is the cookiePrefix variable? What should I set it to/where to find docs?

You don't need the cookiePrefix variable. If I remember correctly, the variable only holds part of the cookie name if you set that the cookie should be a secure one

**Comment by richardpickett** [comment]
You can set the `cookiePrefix` to whatever you want.  I recommend using something that's unique to your site so it's not easily confused with other cookies while you're debugging.

Example:

`const cookiePrefix = "__my_site_";`

**Comment by alexng353** [comment]
Alright, thanks a lot. I'm trying to set up a new nextjs next-auth project to get cross-site-cookies to work

[see repo here](https://github.com/alexng353/nextjs-nextauth)

**Comment by alexng353** [comment]
tbh I have no idea how to get it to work at this point. Gonna keep trying tho. 

My setup is an expressjs api for the API and nextjs for the frontend with nextauth on a vercel serverless thing. I hope I can get it to work tho

**Comment by choutkamartin** [comment]
> Alright, thanks a lot. I'm trying to set up a new nextjs next-auth project to get cross-site-cookies to work

The repo you provided is empty. Also, bear in mind we are talking about domain - subdomain scenario (api.domain.com - domain.com), not domain - domain scenario (domain1.com - domain2.com).

When I tried to make requests to my API from an Android app (Next.js app ported to native Android via Capacitor) I was trying to do similar thing. In case it may help you, I created an example repo https://github.com/choutkamartin/next-auth-capacitor

**Comment by alexng353** [comment]
Oh shoot I haven't put the code on that repo yet. Sorry, I've been quite busy. I'll try to get it up there by tomorrow evening. I am also trying to get it to work domain-subdomain. Thanks for the repo.

**Comment by alexng353** [comment]
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/26424336/218544141-91227f9a-355e-43ca-9df2-9e5f4a1bf814.png">

I've used the same configuration as you (repo should be updated) but it's not sending the cookies in my fetch requests.

**Comment by choutkamartin** [comment]
Are you sure that you are also sending the fetch request with `credentials: include`?

**Comment by alexng353** [comment]
Yo I just sent it using credentials include... thank you so much for your help @choutkamartin!

**Comment by choutkamartin** [comment]
No problem, take in mind that cookies are not send with the request in default when doing cross site request. That's why you had to explicitly define `credentials: include`. 

---
https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials
