### ISSUE TITLE
User can register multiple times with same email address

### ISSUE THREAD

**Issue by giuse-boccia** [nextauthjs/next-auth#4359]
### Provider type

Email

### Environment

System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 10.88 GB / 12.38 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  npmPackages:
    next: ^12.0.7 => 12.1.0 
    next-auth: ^4.0.5 => 4.2.1 
    react: 17.0.2 => 17.0.2 

### Reproduction URL

none (_I believe the description is enough_)

### Describe the issue

Users are able to create multiple accounts using the same email by inserting the same email address but with a dot ('.') before the at symbol ('@').
i.e johndoe@mail.com and john.doe@mail.com are registered as two different accounts in the database.

### How to reproduce

1. Sign in the first time using your real email address (i.e: johndoe@email.com)
2. logout
3. login again but put a dot before the '@' (i.e: john.doe@email.com). An email with the magic link is sent to the same email account, but instead of logging in with the same account on my website, a new account is created.

### Expected behavior

The second time the user should be sent to the same account, as the email account is the same.

**Comment by balazsorban44** [comment]
We don't do any aliasing/normalizing of e-mails:

https://github.com/nextauthjs/next-auth/blob/16668d307d359486aebe3dc9ddee7558365308bb/packages/next-auth/src/core/lib/callback-handler.ts#L88

If you need this behavior, you could do this in multiple ways:

1. Override the `getUserByEmail` of your provider to do so.
2. Normalize client-side, before passing to the `signIn` method.
3. If the second time you are using an OAuth provider, you can override the `profile` method to normalize there instead. See: https://next-auth.js.org/configuration/providers/oauth#override-default-options
