### ISSUE TITLE
Feature request: Provider that doesn't require any external services (yet behaves the same as normal providers, unlike Credentials)

### ISSUE THREAD

**Issue by zenflow** [nextauthjs/next-auth#438]
**Summary of proposed feature**
Add a new provider called `Provider.Password` that supports registration and sign-in using only a username and password. 

**Purpose of proposed feature**

I think an example will illustrate the purpose.

I am writing a small application to demo a [Hasura GraphQL Engine](http://hasura.io/) plus Next.js + next-auth setup. It won't be used in any real-world deployment, but could potentially be cloned and installed by many different developers who want to test & tinker with it. 

With `Provider.Credentials` the users are not persisted to the database, so that's not a really good option to show off the full power of the setup. 

With the remaining available providers, developers would need to set up some external service (i.e. mail server, OAuth2 provider, etc.) just to run the demo. 

While I applaud the decision to support only password-less authentication to push the users into the Pit of Success, 
this use-case exists for a simple email+password authentication. 

**Detail about proposed feature**

A new provider called `Provider.Password` should be added. With this provider, users should be able to sign up with a username and password (and maybe email, if necessary). The new user should be persisted to the database. No confirmation email should be sent to the user. The user should be able to sign in immediately.

Perhaps a warning should be printed to the console when this provider is used.. something to the effect of "Warning: The Password strategy is intended for demonstration purposes only. Please replace it before going to production."

**Potential problems**

Just that some people might use it in production. But if we printed a warning to the console (as suggested above) then we have at least made them aware this is strongly discouraged. It is their own decision if they want to ignore it. And who knows.. they might have their own valid motivation for using this type of provider, other than the motivation I described above.

**Describe any alternatives you've considered**

Use one of the existing providers. However, none of them make it easy to set up an application instance that can demonstrate the normal sign-up & sign-in flow. Either they do not demonstrate the normal flow (i.e. `Credentials`) or they require setting up some external service (remaining providers). 

**Additional context**

n/a

**If the feature request is accepted, I would be happy to try making a PR to implement it!**

Thank you @iaincollins for the awesome library! ❤️

**Comment by leerob** [comment]
I was looking for this as well. For the most simple example, email/pass makes the most sense.

**Comment by zenflow** [comment]
I changed the title: for demo only -> for non-production usage. It's not just about demos. 

It would be nice to be able to develop & test an app (a serious app) *locally* without setting up an external service. 

It would also be nice to be able to just `npm install next-auth` and integrate it into your app and then keep working on your app and worry later about getting OAuth2 keys or SMTP account credentials.

Not as big a deal as I made it out to be above perhaps, but a nice to have.

**Comment by leerob** [comment]
Why not production? Is there an issue with email/pass and this library, or is it only supposed to be used for OAuth / SMTP?

**Comment by iaincollins** [comment]
This is not something we want to look at currently.

**Comment by zenflow** [comment]
@leerob This library doesn't support using passwords because passwords are insecure. 

https://github.com/nextauthjs/next-auth#secure-by-default

So the `Email` provider doesn't use passwords. Instead it sends a magic link to the user's email. 

It makes sense for production, but for local development it's a bit of a nuisance because (as far as I'm aware) you need to bring some SMTP server (of some kind) in order to get the magic link and sign in.  I.e. you cannot obtain the link from next-auth otherwise. (@iaincollins please correct me if I'm wrong on any of that.) Actually maybe this is a better solution to the problem..

**Comment by zenflow** [comment]
Updated the title again. Last time I swear. 

@iaincollins What if we made it so if the `server` option (for the `Email` provider) is undefined (or null string `""`), it operates in a development mode where instead of sending an email it just logs the details to the console, including the magic link?

**Comment by iaincollins** [comment]
@zenflow Thanks for the response and no worries about edits! Good editing is always helpful :-)

I think something like printing it out at the console in development mode would work really well - that's actually how the v1.x example used to work; I've used that a bunch.

I'm really interested in solving the problem of signing with dev / pull request environments well and think we will have something for that soon but still mulling it over. Another option is could bundle a dummy provider just for this.

I'm also considering if we want to support persisting users in the database when being signed in with a credentials provider, although this would rely on some wider changes (like passing in a unique external ID, which could be a username, int, GUID, etc). I'd still like to discourage and provide better alternatives to passwords, including improving the email sign in flow and possibly other built-in provider options, but am trying to find the right balance.

**Comment by ktaras** [comment]
Any updates on this issue? Signing up with a password is still one of the most popular and common approaches. Although I do understand all the downsides it would be really nice to have such a provider and be able to use it at my own risk. A necessity to open the mailing service and wait for the email with a magic link each time I want to sign in to the app - it's just too much.

**Comment by zenflow** [comment]
> A necessity to open the mailing service and wait for the email with a magic link each time I want to sign in to the app - it's just too much.
@ktaras The upside is that once you're signed in, you're signed in until you sign out. Even restarting the browser or the computer does not sign you out. So IMO it's not a huge pain for users. But it will be a pain for developers testing some behavior for authenticated users vs unauthenticated users.
It seems like your issue is with the second scenario (developer experience) rather than the first (user experience).. is that correct?
