### ISSUE TITLE
TypeError [ERR_INVALID_URL]: Invalid URL when using withAuth middleware

### ISSUE THREAD

**Issue by jasonbert** [nextauthjs/next-auth#4381]
### Question 💬

I've added in the simple example middleware to protect a part of a Next.js site, but the middleware is throwing an error when it returns `false`.

`error - TypeError [ERR_INVALID_URL]: Invalid URL:`

`NEXTAUTH_URL` is set as below & `NEXTAUTH_SECRET` is also set in my local environment:

`NEXTAUTH_URL="http://localhost:3000"`

The set up is using Next Auth with Identity Server 4, we're not using the Next Auth sign in page and have a custom component that uses `signIn('ids')` to send the user to the provider as it handles all the SSO (local, Google etc). Ideally I'm looking to use the middleware to send the user to the provider, so they can sign in there, and redirect back to the restricted page.

### How to reproduce ☕️

**_middleware.ts**
```
import { withAuth } from "next-auth/middleware"

export default withAuth({
    callbacks: {
        authorized({ token }) {
            console.log(`Next Auth Middleware | token: ${token}`)
            if (token) return true;
        }
    }
})
```

**[...nextauth].js**
```
export default NextAuth({
    providers: [
        {
            clientId: process.env.IDENTITYSERVER_CLIENT_ID,
            clientSecret: process.env.IDENTITYSERVER_CLIENT_SECRET,
            id: "ids",
            name: "IDS",
            type: "oauth",
            wellKnown: `${process.env.IDENTITYSERVER_HOST}/.well-known/openid-configuration`,
            authorization: { params: { scope: "openid profile api offline_access" } },
            idToken: true,
            checks: ["pkce", "state"],
            profile(profile) {
                return {
                    id: profile.sub,
                    name: profile.name,
                    image: profile.picture
                }
            },
        }
    ],
    callbacks: {
        async jwt({ token, account }) {
            if (account) {
                token.accessToken = account.access_token
                token.accessTokenExpires = new Date(account.expires_at * 1000)
                token.refreshToken = account.refresh_token
                token.idToken = account.id_token
            }

            if (Date.now() < token.accessTokenExpires) {
                return token
            }

            return refreshAccessTokenAuth(token)
        },
        async session({ session, token }) {
            session.user.id = token.sub
            session.userId = token.sub
            session.accessToken = token.accessToken
            session.error = token.error
            return session
        }
    }
})
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by jasonbert** [comment]
For now I'm doing the following as I'm unsure why `withAuth` is not working.

**_middleware.ts**
*NOTE: `getToken` expects a type of `NextApiRequest`, which is why I've had to cast the `NextRequest` to `any`*
```
import { getToken } from "next-auth/jwt";
// import { withAuth } from "next-auth/middleware"
import { NextFetchEvent, NextRequest, NextResponse } from "next/server";

// export default withAuth({
//     callbacks: {
//         authorized({ token }) {
//             if (token) return true;
//         }
//     }
// })

export async function middleware(req: NextRequest) {
    const rawReq: any = req;
    const token = await getToken({ req: rawReq, secret: process.env.NEXTAUTH_SECRET })

    if (token) {
        return NextResponse.next();
    }

    return NextResponse.redirect(`/login?callbackUrl=${req.url}`)
}
```

**login.tsx**
```
import Image from 'next/image'
import { useRouter } from 'next/router';
import { signIn } from 'next-auth/react'
import { useEffect } from 'react';

import { ContainerCenter } from '../components/Containers';
import SimpleLayout from '../components/Layouts/SimpleLayout';

function Login({ }) {
  const router = useRouter();

  useEffect(() => {
    if (router.isReady) {
      const callbackUrl: string = router.query.callbackUrl as string;
      signIn('ids', {
        callbackUrl: callbackUrl ?? '/'
      });
    }
  }, [router.isReady]);

  return (
    <SimpleLayout>
      <ContainerCenter>
        <Image src="/images/logo-light.svg" alt="Logo" height={80} width={80} />
      </ContainerCenter>
    </SimpleLayout>
  )
}

export default Login
```

**Comment by AndrewRayCode** [comment]
For any spelunkers, I was getting this error too, until I bumped my `next` version from `12.0.2` to `12.3.0` (the latest version as of writing this). I don't know why a non-major version bump made this work, especially as both versions are pretty recent. I was getting this error multiple times on startup:

```
$ npm run dev
error - TypeError [ERR_INVALID_URL]: Invalid URL
error - TypeError [ERR_INVALID_URL]: Invalid URL
error - TypeError [ERR_INVALID_URL]: Invalid URL
error - TypeError [ERR_INVALID_URL]: Invalid URL
```
No stack trace, but found it's coming from
```
const signInUrl = new URL(signInPage, origin);
```
in `node_modules/next-auth/next/middleware.js`

This was happening even though I always had `NEXTAUTH_URL` set in my `.env` file, although I don't know if that's related.

I think nextauth could benefit from some more user friendly error handling here, although I'm still not sure what actually caused the issue.

**Comment by jacobdanielrose** [comment]
> Turns out the issue was because my `next` package was not a new enough version! My `package.json` had `latest`, so I'm not sure what version was installed (I'm guessing 11). Ran an `npm update next`, which set the version to `^12.1.5`, followed by `npm install` and this fixed the issue 👍. I only realised this when it couldn't find the `NextMiddleware` type.
> 
> I've ended up with:
> 
> **[...nextauth].js**
> 
> ```
> ...
>     pages: {
>         signIn: '/login',
>     },
> ...
> ```
> 
> **_middleware.ts**
> 
> ```
> import { withAuth } from "next-auth/middleware"
> 
> export default withAuth({ })
> ```
> 
> And **login.tsx** the same as my previous comment.

This also was my issue, updating next worked for me too
