### ISSUE TITLE
Node engine not supported node: 'v17.9.0', npm: '8.6.0' 

### ISSUE THREAD

**Issue by redimongo** [nextauthjs/next-auth#4382]
### Environment

```
  System:
    OS: macOS 12.3.1
    CPU: (4) x64 Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz
    Memory: 49.95 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.9.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.6.0 - /usr/local/bin/npm
  npmPackages:
    next: 12.1.5 => 12.1.5 
    next-auth: ^4.3.1 => 4.3.1 
    react: 18.0.0 => 18.0.0 

```

### Reproduction URL

NA

### Describe the issue

Fresh install and I got the following error

`
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'next-auth@4.3.1',
npm WARN EBADENGINE   required: { node: '^12.19.0 || ^14.15.0 || ^16.13.0' },
npm WARN EBADENGINE   current: { node: 'v17.9.0', npm: '8.6.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'openid-client@5.1.4',
npm WARN EBADENGINE   required: { node: '^12.19.0 || ^14.15.0 || ^16.13.0' },
npm WARN EBADENGINE   current: { node: 'v17.9.0', npm: '8.6.0' }
npm WARN EBADENGINE }
`

### How to reproduce

Upgrade to the latest NodeJS and fresh install

### Expected behavior

The engine should be supported.

**Comment by balazsorban44** [comment]
Correct. Only LTS Node releases are supported. Node 17 is not tested. You can try using the `--ignore-engines` flag at your own risk.
