### ISSUE TITLE
Extending default Prisma models

### ISSUE THREAD

**Issue by Devd0** [nextauthjs/next-auth#4384]
### Question 💬

Currently, I see no way to extend the default Prisma adapter models (like adding a role etc to the user table) without switching to typeORM. Am I missing something in the docs? If its possible right now, I'm not seeing anyway to override the default createUser method either.

### How to reproduce ☕️

----

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
You can simply add the fields to your User model, and make sure you override `profile` callback of your provider to return those values.

https://next-auth.js.org/adapters/models#user

https://next-auth.js.org/configuration/providers/oauth#using-a-custom-provider
