### ISSUE TITLE
next export fails with error

### ISSUE THREAD

**Issue by nagkumar** [nextauthjs/next-auth#4388]
### Environment

react\nextjs\next-auth-example>npx envinfo --system --binaries --browsers --npmPackages "next,react,next-auth"

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
    Memory: 13.99 GB / 23.95 GB
  Binaries:
    Node: 16.14.0 - d:\Apps\Dev\langs\scripting\js\Node\16.x\16.14.0\node.EXE
    Yarn: 1.22.17 - d:\Apps\Dev\langs\scripting\js\Node\16.x\16.14.0\yarn.CMD
    npm: 6.14.16 - G:\DWork\angular\angular-coffee-shop\node_modules\.bin\npm.CMD
  Browsers:
    Chrome: 100.0.4896.88
    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.39)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    next: ^12.0.11-canary.4 => 12.1.5
    next-auth: latest => 4.3.1
    react: ^17.0.2 => 17.0.2

### Reproduction URL

na

### Describe the issue

react\nextjs\next-auth-example>npm run build

> next-auth-example@0.0.0 build G:\DWork\react\nextjs\next-auth-example
> next build & next export

info  - Loaded env from G:\DWork\react\nextjs\next-auth-example\.env.local
info  - Checking validity of types
warn  - No ESLint configuration detected. Run next lint to begin setup
warn  - using beta Middleware (not covered by semver) - https://nextjs.org/docs/messages/beta-middleware
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
info  - Generating static pages (9/9)
info  - Finalizing page optimization

Page                                       Size     First Load JS
┌ ○ /                                      385 B          84.5 kB
├   /_app                                  0 B            80.9 kB
├ ○ /404                                   192 B          81.1 kB
├ ○ /admin                                 451 B          84.6 kB
├ ƒ /admin/_middleware                     1.03 kB         139 kB
├ ○ /api-example                           434 B          84.5 kB
├ λ /api/auth/[...nextauth]                0 B            80.9 kB
├ λ /api/examples/jwt                      0 B            80.9 kB
├ λ /api/examples/protected                0 B            80.9 kB
├ λ /api/examples/session                  0 B            80.9 kB
├ ○ /client                                551 B          84.7 kB
├ ○ /me                                    324 B          84.4 kB
├ ƒ /me/_middleware                        961 B           139 kB
├ ○ /policy                                866 B            85 kB
├ ○ /protected                             855 B            85 kB
└ λ /server                                558 B          84.7 kB
+ First Load JS shared by all              80.9 kB
  ├ chunks/framework-5f4595e5518b5600.js   42 kB
  ├ chunks/main-779b41245c009d2a.js        28.3 kB
  ├ chunks/pages/_app-6f507a0a30b60458.js  9.71 kB
  ├ chunks/webpack-9b312e20a4e32339.js     836 B
  └ css/0f2f9f9cddf39ce1.css               304 B

ƒ  (Middleware)  intercepts requests (uses _middleware)
λ  (Server)      server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)      automatically rendered as static HTML (uses no initial props)

info  - Loaded env from G:\DWork\react\nextjs\next-auth-example\.env.local
info  - using build directory: G:\DWork\react\nextjs\next-auth-example\.next
info  - Copying "static build" directory
info  - No "exportPathMap" found in "undefined". Generating map from "./pages"
info  - Launching 7 workers
warn  - Statically exporting a Next.js application via `next export` disables API routes.
This command is meant for static-only hosts, and is not necessary to make your application static.
Pages in your application without server-side data dependencies will be automatically statically exported by `next build`, including pages powered by `getStaticProps`.
Learn more: https://nextjs.org/docs/messages/api-routes-static-export
[=   ] info  - Exporting (0/9)
Error occurred prerendering page "/server". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Error for page /server: pages with `getServerSideProps` can not be exported. See more info here: https://nextjs.org/docs/messages/gssp-export
    at G:\DWork\react\nextjs\next-auth-example\node_modules\next\dist\export\worker.js:211:27
    at async Span.traceAsyncFn (G:\DWork\react\nextjs\next-auth-example\node_modules\next\dist\trace\trace.js:79:20)
info  - Exporting (9/9)
Error: Export encountered errors on following paths:
        /server
    at G:\DWork\react\nextjs\next-auth-example\node_modules\next\dist\export\index.js:397:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (G:\DWork\react\nextjs\next-auth-example\node_modules\next\dist\trace\trace.js:79:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! next-auth-example@0.0.0 build: `next build & next export`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the next-auth-example@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Raja Nagendra Kumar\AppData\Roaming\npm-cache\_logs\2022-04-14T05_27_37_050Z-debug.log

### How to reproduce

add this in package.json
![image](https://user-images.githubusercontent.com/332234/163319942-73e321ea-77d5-48ad-86ac-31a3993548dd.png)

and run

npm run build

### Expected behavior

It should not give the error

**Comment by balazsorban44** [comment]
`next-auth` does not work with `next export` as it needs a backend to run.

You can see this in the warning you copied above:

> Statically exporting a Next.js application via next export disables API routes.
This command is meant for static-only hosts, and is not necessary to make your application static.
Pages in your application without server-side data dependencies will be automatically statically exported by next build, including pages powered by getStaticProps.
