### ISSUE TITLE
Docs aren't clear enough for server side rendered protected routes!!

### ISSUE THREAD

**Issue by urtheaman** [nextauthjs/next-auth#4399]
### What is the improvement or update you wish to see?

need more guides. 
https://next-auth.js.org/tutorials/securing-pages-and-api-routes#server-side
you've used useSession and getSession both in this example and useSession is used to check  session on client side. why do i need to use useSession on ssr pages? 

you're passing session prop but not using it...! 

### Is there any context that might help us understand?

your own example.
https://next-auth.js.org/tutorials/securing-pages-and-api-routes#server-side

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/tutorials/securing-pages-and-api-routes#server-side

**Comment by urtheaman** [comment]
i'm confused which method to use? useSession works fine but on the client side but i don't want flashing of the content and i wanna redirect to login if session isn't available. used getSession but didn't work. session is undefined even after signing in.

```
export const getServerSideProps = async () => {
  return {
    props: {
      session: await getSession(),
    },
  };
};

const Home: NextPage<{ session: any }> = ({ session }): any => {
  const router = useRouter();
  console.log(session);
  useEffect(() => {
    if (!session) router.push("/signin");
  }, [session, router]);
  if (session) {
    return (
      <div>
    .......some content
</div>
```

"next": "12.1.5",
"next-auth": "^4.3.2",
"react": "18.0.0",

**Comment by urtheaman** [comment]
while getServerSideProps only runs on server-side and never runs on the browser, [server side example](https://next-auth.js.org/tutorials/securing-pages-and-api-routes#server-side) on next-auth docs is wrong. 

how can i even access the session data on server. if i'm storing it in user's browser as cookies...🤔 i just can't!
then what should i use to prevent the flashing of the content?
1. a loader (i don't wanna use loader)
2.  checking & redirecting on the server (session data can't be accessed on the server).

@balazsorban44  or @lluia please guide me a bit on this.

**Comment by Klin-Coders** [comment]
i would suggest you should not send the session back to the client 

check if the session is valid in the getServerSideProps function and trigger a redirect to login page if session is null

here is how i use it in my login page to redirect if user is already logged in 


```js
export async function getServerSideProps({ req, res }) {
  const session = await getSession({ req });
  if (session) {
    return {
      redirect: {
        permanent: false,
        destination: "/profile",
      },
    };
  }
  return {
    props: {}, // will be passed to the page component as props
  };
}```
