### ISSUE TITLE
error callback not available in events options

### ISSUE THREAD

**Issue by maddhruv** [nextauthjs/next-auth#4404]
### Environment

  System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 6.59 GB / 11.65 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
  npmPackages:
    next: ^12.1.4 => 12.1.4
    next-auth: ^4.3.1 => 4.3.1
    react: ^18.0.0 => 18.0.0

### Reproduction URL

https://next-auth.js.org/configuration/options#events

### Describe the issue

The `error` callback mentioned on https://next-auth.js.org/configuration/options#events is not available in typescript - https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/core/types.ts#L360

### How to reproduce

The `error` callback mentioned on https://next-auth.js.org/configuration/options#events is not available in typescript - https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/core/types.ts#L360

### Expected behavior

The `error` callback type should be available

**Comment by ThangHuuVu** [comment]
The error callback is removed in https://github.com/nextauthjs/next-auth/pull/2342. The docs page is outdated and needs to be updated. Thanks for the catch!

> NOTE: events.error has been removed. This method has never been called in the core, so it did actually nothing. If you want to log errors to a third-party, check out the [logger](https://next-auth.js.org/configuration/options#logger) option instead.
