### ISSUE TITLE
Ability to attach multiple accounts to a single user

### ISSUE THREAD

**Issue by gip** [nextauthjs/next-auth#441]
This project is great - thank you for the hard work. I couldn't find how to do what I want in the docs (and that may even be a non-goal for this project) so I'm asking that here.

**Your question**
My app needs the ability to have several accounts for a given user. A user should be able to login into 2+ Google accounts (with different emails). Do we have the ability to do that today (it looks like the DB schema could support this)? If not, is this feature something that could/will be part of this project?

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [X] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [X] Could not find relevant documentation
* [X] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
Hi there! This is a good question.

This is explicitly supported in the schema and internally but it's not yet an advertised feature as it's not quite finished.

Basically, if you sign in, then go to the sign in page AGAIN while already signed in, and this time sign in with a different account you will see both accounts are linked back to the same user and either can be used to sign in on another computer.

(The details from the first account they use are what gets stored as their name / email / image in the user table.)

The reason it's not advertised yet as this is I think account management is the only aspect where there is not yet feature parity with v1. What is missing are API routes for linking and unliking OAuth accounts (and for deleting user accounts all together).

The current behaviour of the sign in page when already signed in will likely change at some point, once these API endpoints are added (e.g. to display page users can use to link/unlink accounts instead).

**Comment by gip** [comment]
Hey - thank you for your answer, it sounds good.

However while logged I've tried logging in again (I've added a new `Add an account` link to `/api/auth/signin` to my app) and this ended up creating a second user and a second account. Any idea what I could be doing wrong? Feel free also to point to the logic that handle that case, I'm happy to spend some time debugging the issue.

**Comment by gip** [comment]
Did some debugging and discovered that it only works when sessions are stored on the DB (`jwt: false`). Not sure what that is intended.

**Comment by iaincollins** [comment]
@gip Thank you for looking into that!

That's not intended and I wasn't aware it was happening (I haven't checked to verify I see that, but I can believe it!).

There is some divergence in what is supported in the Database Session and JWT Session flows (e.g. what providers are supported) and have been thinking about if / how / when to address that.

If you don't mind it's helpful to have this issue open as a reminder to address that specifically in an enhancement and to close it once it's at least been captured with a suggestion about how we might want to handle it in future.

**Comment by gip** [comment]
Sounds goods!

**Comment by ChuckJonas** [comment]
+1 for getting this to work with JWT!

**Comment by Xodarap** [comment]
Is there a way to turn this off? My architecture assumes that there's only one account per user, and I'd rather not extend it to assume a user could have multiple accounts.

**Comment by Xodarap** [comment]
I made a hackey way of preventing accounts from being linked; it would be great if this could be controlled by an option or something:
```
const adapter = Adapters.TypeORM.Adapter(process.env.DB_URL)

// override the linking account function to prevent linking
const originalFunction = adapter.getAdapter;
adapter.getAdapter = async (args) => {
  const originalAdapter = await originalFunction(args)
  originalAdapter.linkAccount = async (userId, providerId, providerType, providerAccountId, refreshToken, accessToken, accessTokenExpires) => {
    console.log('trying to link')
    return Promise.reject(new Error('LINK_ACCOUNT_ERROR', 'linking not allowed'))
  }
  return originalAdapter
}

**Comment by gip** [comment]
I'm not sure it's a severe security issue since if a user is already logged in before logging in with another service and the client was not hacked then both accounts belong to the same user.  

That being said it's indeed not ideal and we should have an option to pick the wanted behavior.

I've fixed that on my end and I can try to do a PR if there is an interest from the core developers (and after the issues with the latest 3.x versions have been fixed - something is broken on 3.21.x for me at the moment).

**Comment by Xodarap** [comment]
Yeah, I was thinking that the sense in which it is a security issue is something like: I'm logged in on my phone and (insecurely) hand it to someone else; they also login; now there account is linked and they can view my data whatever they want, even without my phone. I agree that it requires me taking an insecure action, so it's kind of not really "hacked".

It would be really awesome if you could post your changes, even if the core developers are not interested in merging.

**Comment by gip** [comment]
I have a private fork where changes related to account merging are intertwined with other security-related change specific to my app. So not easy to post - a much easier option would be for the core team to take that on :)

**Comment by balazsorban44** [comment]
As Iain mentioned before, we would like to support a better linking/unlinking account experience, but we have our focus elsewhere currently.

I don't see the problem with https://github.com/nextauthjs/next-auth/issues/441#issuecomment-820780938 though if you are not satisfied with the built-in adapter's behavior, it is extremely easy to create your own. Check out https://github.com/nextauthjs/adapters/tree/canary/packages for examples

**Comment by Xodarap** [comment]
@balazsorban44 FYI the comment I submitted above doesn't work; it has an error that I haven't been able to narrow down yet. If you or someone else has alternative, I would love to see it.

**Comment by balazsorban44** [comment]
closing this as the OP's case is already supported. Anyone else need help/want a new feature, please create a different issue. 🙏

FWIW, a much simpler Adapter API is coming, where overriding single methods of adapters will be very easy! #2361. I am also gaining more confidence in what adapters are actually doing. 😊

**Comment by gip** [comment]
Thanks. Has the issue been resolved yet though (See above: "Did some debugging and discovered that it only works when sessions are stored on the DB (jwt: false). Not sure if that is intended.") ?

**Comment by balazsorban44** [comment]
Hmm. if you could create a reproduction using JWT sessions, and create a new bug report insteadnif it's still an issue, that would be great. This issue has been labeled a question without a reproduction.
