### ISSUE TITLE
Why does `apiBaseUrl` use __NEXTAUTH.basePath when called client-side?

### ISSUE THREAD

**Issue by neongreen** [nextauthjs/next-auth#4434]
### Question 💬

```typescript
export function apiBaseUrl(__NEXTAUTH: NextAuthClientConfig) {
  if (typeof window === "undefined") {
    // Return absolute path when called server side
    return `${__NEXTAUTH.baseUrlServer}${__NEXTAUTH.basePathServer}`
  }
  // Return relative path when called client side
  return __NEXTAUTH.basePath
}
```

I have a NEXTAUTH_URL that doesn't correspond to the frontend URL (I am making an iOS app so that frontend is generated with `next export`).

I expect that all next-auth API calls should be made against NEXTAUTH_URL, but since `apiBaseUrl` returns just a path without the origin, the `/api/auth/providers` call during sign-in is made against `/` and not `my_server_url/...`. 

Is this intentional? Am I misinterpreting NEXTAUTH_URL?

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by neongreen** [comment]
Note: the workaround seems to be:

```jsx
      <SessionProvider
        // https://github.com/nextauthjs/next-auth/issues/4434
        basePath={process.env.NEXTAUTH_URL}
      >
      </SessionProvider>
```

It is also necessary, in general, to configure webpack so that it embeds NEXTAUTH_URL into the frontend bundle. Next.js does this automatically for variables starting with `NEXT_PUBLIC_`, but not for other vars.

```js
/** @type {import('next').NextConfig} */

const webpack = require('webpack')

// Embed NEXTAUTH_URL into the frontend — otherwise next-auth won't work.
const nextauthPlugin = new webpack.DefinePlugin({
  "process.env.NEXTAUTH_URL": JSON.stringify(process.env.NEXTAUTH_URL),
})

module.exports = {
  webpack: (config) => {
    config.plugins.push(nextauthPlugin)
    return config
  },
}
```

**Comment by balazsorban44** [comment]
Client-side `fetch` requests can be relative, as the browser already knows the origin. Your "workaround" of using `basePath` seems to be the appropriate solution here.

I've thought about allowing `NEXT_PUBLIC_NEXTAUTH_URL` before though. More context: https://github.com/nextauthjs/next-auth/issues/1713#issue-856683984

**Comment by jackrdye** [comment]
This should not be closed. Cannot use get session from subdomains without workarounds like this. Can someone in the next auth team please create an app on example.com which has authentication across app.example.com. To be frank the experience is horrible, you will discover that and find so many little quirks and errors that need to be fixed which in the long run will make it a much better experience. I think after 3 days of having to tear through your source code finding 'workarounds' I will have to just use another service
