### ISSUE TITLE
How can you use the CSRF middleware with API endpoints outside of auth?

### ISSUE THREAD

**Issue by ianwalter** [nextauthjs/next-auth#445]
*Please refer to the [documentation](https://next-auth.js.org/getting-started/introduction), the [example project](https://github.com/iaincollins/next-auth-example) and existing issues before creating a new issue.*

**Your question**

How can someone use the same CSRF middleware that next-auth uses in order to protect custom API endpoints?

**What are you trying to do**

So for example, I have a `POST /api/widgets` endpoint to create a widget for logged in users. I would want the CSRF token within requests to that endpoint to be verified against the session before executing the creation logic otherwise it would be susceptible to CSRF attacks. I think I could probably hack together a custom function to do this and wrap my endpoint with it, but it seems to me that this should be an explicit part of next-auth otherwise devs may not realize their endpoints are not protected from CSRF attacks.

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by iaincollins** [comment]
You can't at the moment, but I don't see why this couldn't be refactored and exposed as a helper function!
