### ISSUE TITLE
Can you use `next-auth` to interact w/ Provider API?

### ISSUE THREAD

**Issue by mAAdhaTTah** [nextauthjs/next-auth#447]
**Your question**
Is it possible to use `next-auth` to authenticate & interact with the Provider API (e.g. OAuth with GitHub then interact w/ GH API), instead of the Nextjs API?

**What are you trying to do**
We're in the process of migrating a Django app with React sprinkles into a headless Django app + Nextjs. In this case, the Django app would be both the resource & authorization server, as it currently maintains all the BE business logic. The front-end will primarily be interacting with that Django API, and there's a lot of really good stuff in `next-auth` that would be really helpful for handling this authentication setup, but it looks like the primary use case is authentication for the purpose of accessing the Nextjs API. Would it be possible to take advantage of `next-auth` for this setup? If so, any insight on how would be appreciated. If not, are there changes needed in `next-auth` to make this feasible, and would you accept those changes?

Thank you for your help!

**Documentation feedback**

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by ndom91** [comment]
Just thinking out loud here, but if you define a DB provider, you could pass the session object to API calls to your Django API as well and then on the django side of things, query the db and ensure the session is valid. 

In principal that should work. I'm not sure of the details though, like which exact fields need to be passed back and which you should be looking up on the backend to ensure the session is valid, etc.

**Comment by mAAdhaTTah** [comment]
@ndom91 Ideally, we would like to avoid needing a db for the Next app, but will definitely consider that. Would it be feasible to save that info in Redis? I suspect the BE'ers would prefer we don't muck about in their DBs lol but Redis is already available so we could feasibly take advantage of that.

**Comment by ndom91** [comment]
Well the info is already in the DB if you're using one of the next-auth db adapters. You'd just need to query whats in there. But I understand its not ideal. Unfortunately I can't think of anything else off the top of my head.

**Comment by mAAdhaTTah** [comment]
There are a couple issues similar/related to this one (tagging #871), which I think is resolved by #513.
