### ISSUE TITLE
Incorrect `callbackUrl` appended when securing page with middleware withAuth

### ISSUE THREAD

**Issue by bboyz269** [nextauthjs/next-auth#4483]
### Environment

```
  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz
    Memory: 10.76 GB / 23.74 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (98.0.1108.56)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    next: 12.1.5 => 12.1.5 
    next-auth: ^4.3.3 => 4.3.3 
    react: 18.0.0 => 18.0.0 
```

### Reproduction URL

https://github.com/vercel/next.js/issues/36334 (related issue in nextjs middleware)

### Describe the issue

When middleware `withAuth` redirect user to signin page, `req.url` is appended to params as `callbackUrl`. This url is composed by set next server hostname, port, pathname and hard-coded protocol http (see [related issue in nextjs repo](https://github.com/vercel/next.js/issues/36334)).   
This is not always the url on client end (ex: next server is behind ssl proxy or load balancer).  Hence `callbackUrl` is not working as intended.
https://github.com/nextauthjs/next-auth/blob/c6903d3e857f4a0875ffe49fc634a36346bdde88/packages/next-auth/src/next/middleware.ts#L92-L95

### How to reproduce

See [related issue in nextjs repo](https://github.com/vercel/next.js/issues/36334)

### Expected behavior

Suggestion to use `req.nextUrl.pathname` as callbackUrl instead of `req.url`.   
Or reconstruct full url using NEXTAUTH_URL and `req.url`.  
Or add another callback to override default behavior when user is not authorized.

**Comment by ThangHuuVu** [comment]
Thanks for the suggestions, Small notes: 
> Or reconstruct full url using NEXTAUTH_URL and req.url.

This is not preferred since `NEXTAUTH_URL` will be removed soon.
> Or add another callback to override default behavior when user is not authorized.

We talked about this in previous PRs/issues, and this is also not preferred because redirecting to sign-in is a strong enough default behavior, and we don't want to change it yet. (until many people request it 💭)

So I think changing `req.url` to another value seems like the most sensible solution for this issue. PRs welcome!

**Comment by bboyz269** [comment]
@ThangHuuVu 
Changing `callbackUrl` to relative (req.nextUrl.pathname) would suffice, imho. Please check out the PR.
Update your host file to something like `next-auth.localhost 127.0.0.1` along with env `NEXTAUTH_URL=http://dev.cat.local:3000` to test it.  
I also added a `Middleware protected with params` link to ensure it's behavior as before.
