### ISSUE TITLE
Downgrading to Node 16.10 not possible

### ISSUE THREAD

**Issue by mschipperheyn** [nextauthjs/next-auth#4485]
### Environment

  System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.72 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
    Watchman: 2021.09.27.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 100.0.4896.127
    Safari: 15.3

### Reproduction URL

https://github.com/facebook/jest/issues/11956

### Describe the issue

Jest has a memory related issue that is caused by Node 16.13+. They suggest downgrading to Node 16.10.0. 
This is not possible because next-auth requires 16.13.x

https://github.com/facebook/jest/issues/11956

### How to reproduce

Run yarn install againat node 16.10.0

### Expected behavior

This seems like an extremely strict limitation. If this is not absolutely necessary, such a strict limitation should not be put in place.

**Comment by balazsorban44** [comment]
You can use the `--ignore-engines` flag.
