### ISSUE TITLE
This expression is not callable and has no call signatures in [...nextauth].ts

### ISSUE THREAD

**Issue by kingyousaf** [nextauthjs/next-auth#4487]
### Environment

  System:
    OS: macOS 11.2.2
    CPU: (4) x64 Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz
    Memory: 58.56 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
    Watchman: 2022.01.17.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 100.0.4896.127
    Safari: 14.0.3
  npmPackages:
    next: ^12.1.5 => 12.1.5 
    next-auth: ^4.3.4 => 4.3.4 
    react: ^18.0.0 => 18.0.0 

### Reproduction URL

https://github.com/kingyousaf/Nextjs_production_tailwind/tree/NextAuth

### Describe the issue

Hi

The issue i am encountering is when trying to add NextAuth in my application it simply breaks.

I have followed your documentation and example repo on GitHub however it doesn't fix the problem i am encountering.

The issue itself is in the [...nextauth].ts file when declaring the file in the format you provided i get this error and break in production 

"This expression is not callable.
  Type 'typeof import("/Users/farishtawazir/Desktop/template/next-auth")' has no call signatures.ts(2349)"

from this line of code which i copied fromt the repo 
```
export default NextAuth({
```

i get the breaking change here and have tried many things but none fix this.

I have provided the GitHub repo with the branch containing this issue.

### How to reproduce

Download the branch repo from https://github.com/kingyousaf/Nextjs_production_tailwind/tree/NextAuth and run yarn dev or go to the [...nextauth].js file rename it to .ts then you will see the error

### Expected behavior

I should have gotten the authentication running however it is breaking the application

**Comment by kingyousaf** [comment]
Hi

its okay i managed to fix this by moving the types into a sepeate folder

**Comment by KalanaPerera** [comment]
the workaround would be to move next-auth.d.ts from root to src/types
