### ISSUE TITLE
Intermittent Failure: request to http://localhost:3000/api/auth/session failed, reason: read ECONNRESET

### ISSUE THREAD

**Issue by mopatches** [nextauthjs/next-auth#4553]
### Environment

```
System:
    OS: Linux 5.17 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 18.63 GB / 31.20 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  npmPackages:
    next: ^12.1.6 => 12.1.6 
    next-auth: ^4.3.4 => 4.3.4 
    react: 17.0.2 => 17.0.2 
```

### Reproduction URL

None

### Describe the issue

Hello! My NextJS app works great most of the time, but intermittently fails on /api calls due to an exception in next-auth. The exception happens in dev and prod/precompiled mode. I haven't found a consistent repro to cause the exception:

```
wait  - compiling /api/.../...
wait  - compiling...
event - compiled client and server successfully in 199 ms (867 modules)
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error request to http://localhost:3000/api/auth/session failed, reason: read ECONNRESET {
  error: {
    message: 'request to http://localhost:3000/api/auth/session failed, reason: read ECONNRESET',
    stack: 'FetchError: request to http://localhost:3000/api/auth/session failed, reason: read ECONNRESET\n' +
      '    at ClientRequest.<anonymous> (/workspace/node_modules/next/dist/compiled/node-fetch/index.js:1:64142)\n' +
      '    at ClientRequest.emit (node:events:526:28)\n' +
      '    at ClientRequest.emit (node:domain:475:12)\n' +
      '    at Socket.socketErrorListener (node:_http_client:442:9)\n' +
      '    at Socket.emit (node:events:526:28)\n' +
      '    at Socket.emit (node:domain:475:12)\n' +
      '    at emitErrorNT (node:internal/streams/destroy:157:8)\n' +
      '    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:83:21)',
    name: 'FetchError'
  },
  path: 'session',
  header: {
    host: 'localhost:3000',
    connection: 'keep-alive',
    pragma: 'no-cache',
    'cache-control': 'no-cache',
    'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="101", "Google Chrome";v="101"',
    dnt: '1',
    'sec-ch-ua-mobile': '?0',
    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36',
    'sec-ch-ua-platform': '"Linux"',
    accept: '*/*',
    'sec-fetch-site': 'same-origin',
    'sec-fetch-mode': 'cors',
    'sec-fetch-dest': 'empty',
    referer: 'http://localhost:3000/...',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-US,en;q=0.9',
    cookie: '_xsrf=...'
  },
  message: 'request to http://localhost:3000/api/auth/session failed, reason: read ECONNRESET'
}
```
The browser sees this exception as a 401, but it able to retry and the second request works without issue.

Any guidance on what to try would be very welcome. Thank you!

### How to reproduce

Calling /api routes from within a setInterval seems to trigger the exception every few minutes. The exception appears more likely to trigger in dev mode with the server recompiling server-side code often.

### Expected behavior

No exception, or the ability to catch and retry server-side.

**Comment by sudo-jaa** [comment]
We've been having the same issue. As far as I can tell we only start getting this error after upgrading `next` to v12 In our case we're on `12.1.0`, so a bit behind your example but the error is the same. No such issue when rolling back to versions of our app that use next v11. 
Hopefully there's something useful in that!

**Comment by mopatches** [comment]
Hi @sudo-jaa! Yes, we're using swc. It's so fast :)

**Comment by sudo-jaa** [comment]
@mopatches I agree - SWC is definitely a great tool! Though there do seem to be situations where it can cause some issues. I remember our first stab at transition to nextjs 12 and SWC from babel had some issues where compilation was panicking due to a recursion depth limit - at least during the minification process. They did end up managing to fix it a few updates in, but it makes me think that it might, under certain circumstances, output imperfect transpiled / minified code. 

That said, the people who maintain next and swc are way smarter than I could ever hope to be, so this isn't an accusation or anything that there might be a bug there! But it might be an interesting thread to pull to see if it resolves your issue. If falling back to babel/next 11 solves your issue, then that's probably really useful information to be able to supply to the maintainers of next-auth. If not then we could rule it out. Like I said - in our case this issue only started after bumping to nextjs 12 🤔

**Comment by huksley** [comment]
I have the same issue. I also had it on NextJS 11 but less frequent.

I have custom _document.tsx and _app.tsx with SessionProvider.

**Comment by simonecervini** [comment]
I'm having a similar problem, I opened a separate issue: https://github.com/nextauthjs/next-auth/issues/4590

**Comment by royletron** [comment]
@simonecervini , @stevenspads, @huksley, @mopatches can I ask if you guys are using next-auth `v4` or `v3`? Just trying to work out where this could possibly be going wrong!

**Comment by mopatches** [comment]
Hello @royletron! I'm using next-auth v4 (currently v4.3.4).

**Comment by mopatches** [comment]
@royletron yes, my adapter is Prisma.

**Comment by stevenspads** [comment]
@royletron I'm using `next-auth` version 4 and my adapter is `Prisma`.

**Comment by huksley** [comment]
I am using nextJS 12, next-auth 4
I think it is related to using getUserSession() on the server side, as it makes additional request to /api/auth/session endpoint.

I am using a `hack` from https://github.com/nextauthjs/next-auth/discussions/3330#discussioncomment-2110190
to avoid having that additional request which is not necessary IMO

It is nice to have a unified API but server-side implementation should tap directly into backend without extra HTTP hop.

**Comment by balazsorban44** [comment]
Unfortunately, this does not sound like we can do much about it as there is no clear reproduction. #4116 might help with this in the future, depending on your use case, but without code, it's hard to tell if that's even a related problem.
