### ISSUE TITLE
Custom Table names for `adapter-prisma`

### ISSUE THREAD

**Issue by ogroppo** [nextauthjs/next-auth#4567]
### Description 📓

If there are 2 next-auth instances writing on the same DB (e.g. website + admin) it's not possible to keep the users separate because the table names are hardcoded.

Would be nice to have a config to override the names like:
```
adapter: PrismaAdapter(prisma, {user: "admin", account: "adminAccount", session: "adminSession"})
```

### How to reproduce ☕️

It's a feature request

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by ThangHuuVu** [comment]
Could you try mapping in your Prisma schema like this: https://next-auth.js.org/adapters/prisma#naming-conventions
Learn more at: https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#mapping-model-names-to-tables-or-collections
Extending the config isn't an option at the moment. Creating the schema is your application's responsibility.

**Comment by ogroppo** [comment]
Hi, thank you for the reply. I believe this has been misunderstood tho: it's not possible to map 2 tables to the same name (i.e. 2 different next-auth using 2 different sets of tables both mapping to "users"). The change seems to be quite simple, I can raise a PR if you're happy with it.

**Comment by ThangHuuVu** [comment]
> it's not possible to map 2 tables to the same name (i.e. 2 different next-auth using 2 different sets of tables both mapping to "users")

Sorry if I misunderstood, in the issue you gave an example like this:
`adapter: PrismaAdapter(prisma, {user: "admin", account: "adminAccount", session: "adminSession"})`

So I'm not sure I understand your DB setup correctly. Could you describe more about the use case? 
> it's not possible to keep the users separate because the table names are hardcoded.

The table names aren't hardcoded. They are defined by the schema files, so I don't think any changes in NextAuth.js is needed.

**Comment by ogroppo** [comment]
I'll try to rephrase the use case: there is a nextjs website that has users that can login, then there is another nextjs app that runs the admin panel or a CMS if you like to edit the content of the website. 
The aim is to store both "next-auth users" and "next-auth admins" in the same DB - so from what I see in the adapter code
```
createUser: (data) => p.user.create({ data }),  
```
 p.user is hardcoded so it will always point to the same table, whilst it would be great if in the admin adapter the config looks like this:
 `adapter: PrismaAdapter(prisma, {user: "admin", account: "adminAccount", session: "adminSession"})`
and on the website it looked like this (using the default)
`adapter: PrismaAdapter(prisma)`
and the adapter being something like this:
```
export function PrismaAdapter(p: PrismaClient, config = {}): Adapter {
...
    createUser: (data) => p[config.user || "user"].create({ data }),
```
Does it make sense?

**Comment by ThangHuuVu** [comment]
`p.user` represents the user model, not the table name. I suggest you create/change the schema for the admin app so that it maps to the desired tables:

```prisma
// table name are prefixed with "admin_"
model Account {
  id                 String  @id @default(cuid())
  userId             String  @map("user_id")
  type               String
  provider           String
  providerAccountId  String  @map("provider_account_id")
  refresh_token      String? @db.Text
  access_token       String? @db.Text
  expires_at         Int?
  token_type         String?
  scope              String?
  id_token           String? @db.Text
  session_state      String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
  @@map("admin_accounts")
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique @map("session_token")
  userId       String   @map("user_id")
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@map("admin_sessions")
}

model User {
  id            String    @id @default(cuid())
  name          String?
  email         String?   @unique
  emailVerified DateTime? @map("email_verified")
  image         String?
  accounts      Account[]
  sessions      Session[]

  @@map("admin_users")
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
  @@map("admin_verificationtokens")
}
```

You then can store the web app users and admin users separately in two tables. Would this make sense?

**Comment by ogroppo** [comment]
Hey, yes you are absolutely right, I apologise for having used the wrong term all the time 🙏  - I probably meant "model" instead of table, I see your solution would perfectly work if 2 different schemas are used, however if the 2 apps are in a monorepo it's still a bit tricky to separate the 2 generated prisma clients (they tend to override each other in the @prisma/client module). 
Another limitation would be that the admins could not be connected to other models (say for instance `model post { approvedBy admin }`).

Just let me know if this is not of interest and I'll stop bugging you 😀

**Comment by escobar5** [comment]
I also have a case for this one, I already have a model called `User` in my prisma schema, so I cannot create the models needed for the prisma adapter because I would need to rename my current User model, which I would prefer not to.

**Comment by ogroppo** [comment]
@escobar5 we have forked the package to add this https://www.npmjs.com/package/next-auth-prisma-adapter, it's so simple that I don't get why they are not interested in supporting this

**Comment by lchluk002** [comment]
Has this feature been implemented yet? @ogroppo

**Comment by ogroppo** [comment]
Hi @lchluk002, no apperently not (strange, it's a very low-maintenance change and extremely useful) - you can find a very thin wrapper around the adapter package at https://www.npmjs.com/package/next-auth-prisma-adapter tho

**Comment by lchluk002** [comment]
@ogroppo hmm yes very strange. Okay thanks very much! 👍

**Comment by vdeva** [comment]
I also have a case for this, my app is basically impossible (maybe possible with incredibly silly and dangerous workarounds) to make without this feature. I'm willing to help if needed.

**Comment by moinulmoin** [comment]
@balazsorban44 Hey pal, I think it would be a very helpful feature. Would you mind reviewing this?

**Comment by adie** [comment]
Also had the same issue, wanted to use `Account` for business needs (as in using it via `prisma.accounts...`). Did a simple wrapper around `prisma` to pass in to the adapter, maybe would be useful to someone:
```ts
// Getting only fields required for authentication, but renaming `authAccount`
// to `account` as this is what is expected by the adapter
const authPrisma = {
  account: prisma.authAccount,
  user: prisma.user,
  session: prisma.session,
  verificationToken: prisma.verificationToken,
} as unknown as PrismaClient

const authOptions: NextAuthOptions = {
  adapter: PrismaAdapter(authPrisma),
```
But would be really good to have support for custom model names in adapter itself

**Comment by burithetech** [comment]
This is so wrong. I refuse to use orignal schema for 2 reasons: 
1. It has inconsistencies in the field names (camel case used with snake case even in the same table [for example `Account model` - `providerAccountId` vs. `refresh_token`), 
2. What if we already have models like it or even domain requirement to use 'Account' model name for something else? ... Personally I prefer `UserAccount` or `UserConnectedAccount`
