### ISSUE TITLE
Amazon Cognito + next-auth -> checks.state argument is missing

### ISSUE THREAD

**Issue by z0ph** [nextauthjs/next-auth#4570]
### Provider type

Cognito

### Environment

```
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 2.07 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0
    Safari: 15.4
  npmPackages:
    next: latest => 12.1.2
    next-auth: 4.0.6 => 4.0.5
    react: ^17.0.2 => 17.0.2
```

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

I'm running an issue while creating a new user with Cognito, after the verification code, the website crashed with the following error screen.

![image](https://user-images.githubusercontent.com/20846187/168680641-35f639ec-d0b6-49ce-a4e4-0d4d33739033.png)

```
2022-05-16T20:08:28.437Z	5d144ce4-3a52-421c-80ec-89ebcc694439	ERROR	[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error checks.state argument is missing {
  error: {
    message: 'checks.state argument is missing',
    stack: 'TypeError: checks.state argument is missing\n' +
      '    at Client.callback (/var/task/chunks/117.js:12099:13)\n' +
      '    at oAuthCallback (/var/task/chunks/117.js:7600:29)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
      '    at async Object.callback (/var/task/chunks/117.js:8562:11)\n' +
      '    at async NextAuthHandler (/var/task/chunks/117.js:6424:28)\n' +
      '    at async NextAuthNextHandler (/var/task/chunks/117.js:9841:19)\n' +
      '    at async /var/task/chunks/117.js:9877:32\n' +
      '    at async Object.apiResolver (/var/task/chunks/458.js:6620:9)\n' +
      '    at async Module.<anonymous> (/var/task/chunks/458.js:5552:13)',
    name: 'TypeError'
  },
  providerId: 'cognito',
  message: 'checks.state argument is missing'
}
```

```
2022-05-16T20:08:28.439Z	5d144ce4-3a52-421c-80ec-89ebcc694439	ERROR	[next-auth][error][CALLBACK_OAUTH_ERROR] 
https://next-auth.js.org/errors#callback_oauth_error checks.state argument is missing TypeError: checks.state argument is missing
    at Client.callback (/var/task/chunks/117.js:12099:13)
    at oAuthCallback (/var/task/chunks/117.js:7600:29)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.callback (/var/task/chunks/117.js:8562:11)
    at async NextAuthHandler (/var/task/chunks/117.js:6424:28)
    at async NextAuthNextHandler (/var/task/chunks/117.js:9841:19)
    at async /var/task/chunks/117.js:9877:32
    at async Object.apiResolver (/var/task/chunks/458.js:6620:9)
    at async Module.<anonymous> (/var/task/chunks/458.js:5552:13) {
  name: 'OAuthCallbackError',
  code: undefined
```

Here is the `pages/api/auth/[...nextauth].js` file:

```js
import NextAuth from "next-auth";
import CognitoProvider from "next-auth/providers/cognito";

export default NextAuth({
  providers: [
    CognitoProvider({
      clientId: process.env.COGNITO_CLIENT_ID,
      clientSecret: process.env.COGNITO_CLIENT_SECRET,
      issuer: process.env.COGNITO_ISSUER,
      idToken: true,
    }),
  ],
  callbacks: {
    // By default NextAuth will redirect to an url of the same hostname
    // this callback allows to change that behavior and specify a custom url
    redirect({ url }) {
      return url;
    },
    async session({ session, token }) {
      // Send properties to the client, like an access_token from a provider.
      session.customerID = token.sub
      return session
    }
  },
  secret: process.env.SECRET,
  debug: process.env.NODE_ENV === "development" ? true : false
});
```

### How to reproduce

Sign up using Cognito and next-auth successfully.

### Expected behavior

Register to Cognito without the following error message.

![image](https://user-images.githubusercontent.com/20846187/168680391-afd798a9-88c0-4f7b-9f4d-4878e76c15f0.png)

**Comment by ThangHuuVu** [comment]
This error you're having is related to the `state` cookie being missing. Maybe this could help?
I suggest you try the latest next-auth version. If the issue persists, please provide a minimal reproduction repo and link it here, it would be super helpful to debug 🙏  Cognito worked fine the last time we check: https://github.com/nextauthjs/next-auth/pull/2829 So it's likely a provider configuration error.
Btw, you don't need `idToken: true` because it's the default.

**Comment by lawitschka** [comment]
I'm having the exact same issue but using the Google Auth Provider and not Cognito. The state cookie is definitely there when coming back from Google 👇🏻, yet I still get this error message.

<img width="670" alt="Screen Shot 2022-05-18 at 19 27 14" src="https://user-images.githubusercontent.com/328382/169105019-72b4d47e-33a1-4006-8083-7488d036e99a.png">
 
Judging by the log screenshots, the other user's instance is also running in AWS, just like mine: Next.js is running in a Docker container in AWS ECS and behind Cloudfront as CDN. Cloudfront by default filters out many things like headers to maximize cachability.

Could be the reason that the client side makes an API request to NextAuth when coming back from the provider, NextAuth expects the cookie to be sent along but it is filtered out by Cloudfront?

**Comment by lawitschka** [comment]
Yes, I have answered my own question. Changing my Cloudfront config made it work.

@ThangHuuVu Is there any place in the documentation where all Cookies used by NextAuth are listed? It's always trial-and-error to see if it works and would be great if there just was a list of cookie names you have to whitelist.

@z0ph I set up a dedicated cache behaviour for `api/*` allowing all HTTP methods and the following cookies.

```
allowed_methods = [
  "GET",
  "HEAD",
  "OPTIONS",
  "POST",
  "DELETE",
  "PUT",
  "PATCH",
]

forwarded_cookies_allowed_names = [
  "__Host-next-auth.csrf-token",
  "__Secure-next-auth.callback-url",
  "__Secure-next-auth.session-token",
  "__Secure-next-auth.pkce.code_verifier",
  "__Secure-next-auth.state"
]
```

**Comment by ThangHuuVu** [comment]
@lawitschka Thanks for the insight, all the cookies set by NextAuth.js can be found here: https://next-auth.js.org/configuration/options#cookies in the example section. @z0ph could you check the Cognito config then? I'll close this as it's not a NextAuth.js issue.

**Comment by z0ph** [comment]
> This error you're having is related to the `state` cookie being missing. Maybe this could help? I suggest you try the latest next-auth version. If the issue persists, please provide a minimal reproduction repo and link it here, it would be super helpful to debug 🙏 Cognito worked fine the last time we check: #2829 So it's likely a provider configuration error. Btw, you don't need `idToken: true` because it's the default.

@ThangHuuVu I've tried to remove the `idToken: true`, but then the same screen appears, and unfortunately, the sign in using Cognito was this time not working (loop). The error message in the log was different: 

![CleanShot 2022-05-19 at 09 45 48](https://user-images.githubusercontent.com/20846187/169241729-52364a35-f783-4026-ba9d-601781470f7d.png)

I've double-checked the current version of `next-auth` inside my AWS Amplify App: 4.3.4 (latest)

![CleanShot 2022-05-19 at 10 10 15](https://user-images.githubusercontent.com/20846187/169245401-75ba03b7-8901-4502-b4c1-c155cf696082.png)

I've reverted back to the `idToken: true` and now I'm sure I'm using the latest version. The same initial error appears.

![CleanShot 2022-05-19 at 10 23 54](https://user-images.githubusercontent.com/20846187/169248000-7e8cff46-c500-46cf-9c6d-f843d2970362.png)

@lawitschka I'm using AWS Amplify for this app, and the associated nextjs cloudfront distribution is already allowing all HTTP methods and All Cookies:

![CleanShot 2022-05-19 at 10 34 02](https://user-images.githubusercontent.com/20846187/169250059-757730eb-5c6e-4c59-bb0b-248edc58a83b.png)

![CleanShot 2022-05-19 at 10 34 22](https://user-images.githubusercontent.com/20846187/169250144-d6647c1c-599f-4830-b184-f255fd56df59.png)

Following the link to the documentation of different cookies, It seems that the state cookie is missing in my case. Am I right (see screenshot bellow):

![CleanShot 2022-05-19 at 10 41 17](https://user-images.githubusercontent.com/20846187/169251692-4d9ad39a-2add-4471-ac45-daf550f512b9.png)

**Comment by ThangHuuVu** [comment]
> I've tried to remove the idToken: true, but then the same screen appears, and unfortunately, the sign in using Cognito was this time not working (loop)

@z0ph That's weird because the `idToken` is true by default for Cognito 🤔  That error only happens if `idToken` is set to false. https://github.com/nextauthjs/next-auth/blob/db188b872f8efb90fc325dc60644941dc0650e92/packages/next-auth/src/providers/cognito.ts#L18 
 
> It seems that the state cookie is missing in my case. Am I right 

Look like it... Unfortunately, I'm not an Amplify expert so I'm stuck here too. Have you try [managed cache policy](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html)?

**Comment by z0ph** [comment]
I've tried different Cloudfront settings without success yet.

What I see so far:
1. I register using Cognito with an email configuration code.
2. Right after the input of the confirmation code, I got the initial error message because missing state cookie.
3. If I click on the black button (sign in using Cognito), it connects right away without issue. (the state cookie is then set).
4. Now that I have an account in Cognito, every login to the application is fine. (no error message with the missing state).

You can see in the screenshot below that the cookie is set starting with the highlighted: Cognito line

![CleanShot 2022-05-19 at 14 03 56](https://user-images.githubusercontent.com/20846187/169302356-7c8e918a-4f08-4ef2-ac9e-76458156d675.png)

---

Ok, writing these lines below makes me realize my mistake. I was not using first the app URL to allow it to set the state information, but instead directly a sign-up URL from Cognito with a false/previous state id. My mistake.

It's now solved, thanks 👍🏼

**Comment by ThangHuuVu** [comment]
No problem, happy to help @z0ph ! Thanks for posting the solution 🙏
