### ISSUE TITLE
Possible update Node 18

### ISSUE THREAD

**Issue by analuznoro** [nextauthjs/next-auth#4575]
### Provider type

Keycloak

### Environment

  System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 10.94 GB / 15.45 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.1.0 - /bin/node
    npm: 8.5.5 - /bin/npm
  Browsers:
    Chromium: 101.0.4951.64
    Firefox: 100.0

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

HI NextAuth Team!
After updating node it appears:

error next-auth@4.3.4: The engine "node" is incompatible with this module. Expected version "^12.19.0 || ^14.15.0 || ^16.13.0". Got "18.1.0"
error Found incompatible module.

Can you add compatibility to version 18 ?

### How to reproduce

Update nodejs to 18

### Expected behavior

The package should install successfully

**Comment by nexxeln** [comment]
same issue here. was just about to create an issue.

**Comment by kostadinnm** [comment]
I have the same issue. I'm using Manjaro, which comes with default node 18 at present. I am getting this error when trying to setup a project that uses `next-auth`, so be glad if you're able to bump the version to 18, if possible?!

**Comment by pfcodes** [comment]
Add `--ignore-engines` flag for install and upgrade operations to get around this for now.

**Comment by nexxeln** [comment]
> Add `--ignore-engines` flag for install and upgrade operations to get around this for now.

Thank you this works for me.

**Comment by balazsorban44** [comment]
`--ignore-engines` is the current recommendation. We are working on making `next-auth` agnostic of Next.js. (#4299)

**Comment by ar4hc** [comment]
for users of `pnpm` coming here:
The setting is [engine-strict](https://pnpm.io/npmrc#engine-strict)

Set in `.npmrc` :

```
engine-strict=false
```

**Comment by openarun** [comment]
Any  update with it please? using yarn.
error next-auth@4.12.2: The engine "node" is incompatible with this module. Expected version "^12.19.0 || ^14.15.0 || ^16.13.0". Got "18.9.1"

**Comment by yanickrochon** [comment]
My question is : If `--ignore-engines` "fixes" the problem (i.e. it ignores the warning), why not pushing a new version of this module with adding Node 18 to the engine requirements? Is there _really_ an incompatibility, or is this message simply because v18 is missing from the engines list?

Because if there is really an incompatibility, then the solution is to downgrade to Node v16 until further notice. But if everything is fine, requiring to ignore the error (this issue was created many months ago already!) is not a proper solution.

Which is it?

**Comment by barakadanny** [comment]
> Add `--ignore-engines` flag for install and upgrade operations to get around this for now.

this really saved me after 2 days trying to by pass that

**Comment by alvissraghnall** [comment]
> Any update with it please? using yarn. error next-auth@4.12.2: The engine "node" is incompatible with this module. Expected version "^12.19.0 || ^14.15.0 || ^16.13.0". Got "18.9.1"

used --ignore-engines and it worked just fine with yarn.
