### ISSUE TITLE
Discord and Twitter Banner

### ISSUE THREAD

**Issue by CertifiedRice** [nextauthjs/next-auth#4589]
### Description 📓

A way to get the image of the users Discord and Twitter banner

### How to reproduce ☕️

unfortunately I have no  code snippets

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by ThangHuuVu** [comment]
These are not in the scope of next-auth but rather how you specify the scope for the Providers. Please take a look there:
Discord: https://discord.com/developers/docs/topics/oauth2#shared-resources-oauth2-scopes
Twitter: https://developer.twitter.com/en/docs/authentication/guides/v2-authentication-mapping
