### ISSUE TITLE
Setting a baseUrl in example app's .tsconfig causes an error in vscode

### ISSUE THREAD

**Issue by nickretallack** [nextauthjs/next-auth#4598]
### Question 💬

I want to set a typescript baseUrl so I can do imports relative to the package base instead of the current file, as described here: https://nextjs.org/docs/advanced-features/module-path-aliases

### How to reproduce ☕️

* Clone the example app
* Add `"baseUrl": ".",` to the `.tsconfig.json` file
* View `[...nextauth].ts` in vscode

It's now failing to import the types for `NextAuth`.
```
import NextAuth
This expression is not callable.
  Type 'typeof import("/Users/nicholasretallack/Documents/artstream/next-auth")' has no call signatures
```

Perhaps this is because of the `next-auth.d.ts` file?

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
I could not reproduce this. Do you have a repo I can look at?

**Comment by HXavS** [comment]
Yes, this is caused by the next-auth.d.ts file. If you put  *.d.ts file inside a directory like types/next-auh.d.ts ad be sure it is included with you compiler, things should run fine.

**Comment by HXavS** [comment]
The Next-Auth Documentation recommends putting the any [Next-Auth Model Augmentation](https://next-auth.js.org/getting-started/typescript#module-augmentation)s inside of a types directory and not in the project root directory.

**Comment by Synkied** [comment]
For anyone having this same problem, I had this problem because I added "next-auth.d.ts" in the include array of the `tsconfig.json` file. Remove it and follow @HXavS instructions.
