### ISSUE TITLE
FR: Expose callbacks/parameters that update `Account` properties

### ISSUE THREAD

**Issue by timfee** [nextauthjs/next-auth#4600]
### Description 📓

Hi there!

I'm not sure if this is even the best way to go about the solution, so I'll describe my use case:

I'm using next-auth for traditional sign-in (via Google OAuth).

However, I'm also looking to allow users to allow enhanced scopes. For example, account managers can "Grant Gmail Access" to the application to allow emails to be dispatched.

Because _most_ users won't need this, I have a pretty standard Google provider defined:
```ts
  providers: [
    GoogleProvider({
      clientId: process.env.OAUTH_CLIENT_ID || '',
      clientSecret: process.env.OAUTH_CLIENT_SECRET || '',
    }),
  ],
```

I'm trying to allow users to click a button to grant extended permissions:
```tsx
        <Button
          onClick={() => {
            signIn(
              'google',
              {},
              {
                prompt: 'consent',
                access_type: 'offline',
                response_type: 'code',
                scope:
                  'https://www.googleapis.com/auth/gmail.send openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile',
              }
            )
          }}>
          Authorize Gmail
        </Button>
```

This **correctly** takes the user to a sign-in page with the additional scopes being requested, and when they complete the transaction, the `signIn` callback's `account` parameter has everything that I'd want:

```js
{
  provider: 'google',
  type: 'oauth',
  providerAccountId: '12345',
  access_token: 'ya29.•••',
  expires_at: 1653187401,
  refresh_token: '1//••',
  scope: 'https://www.googleapis.com/auth/gmail.send https://www.googleapis.com/auth/calendar openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile',
  token_type: 'Bearer',
  id_token: 'ey•••'
}
```

I tried to extend the `updateUser` / `linkAccount` functions in `PrismaAdapter`, but it doesn't look like they get called, and the `scope`, `refresh_token` (and other) fields don't get updated.

I **could** manually update the database inside of the `signIn` callback (`prisma.account.update(...)`), but I wasn't sure if that was the best way to go about this, and if the refreshing of `Account` fields should be a natively implemented solution.

Anyhoo, this is probably pushing the boundaries of what this library was intended for, but I'd love to have a central `scope` and `access_token`/`refresh_token` repository, so figured I'd see what the temperature is for a feature like this.

Thanks!

### How to reproduce ☕️

see above, ultimately want to render a UI like this:
```tsx
import AuthenticatedLayout from 'layouts/authenticated'
import { withAuthSsr } from 'lib/auth'
import prisma from 'lib/prisma'
import { InferGetServerSidePropsType } from 'next'
import Head from 'next/head'
import { signIn, SignInAuthorizationParams } from 'next-auth/react'


export default function Dashboard({
  settings,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <AuthenticatedLayout>
      <main className="max-w-2xl p-8 mx-auto my-10 bg-white rounded-md shadow-sm">
        Connect to Gmail:
        {settings &&
        settings.scope &&
        settings.scope.indexOf('gmail.send') === -1 ? (
          <button
            onClick={() => {
              signIn(
                'google',
                {},
                {
                  prompt: 'consent',
                  access_type: 'offline',
                  response_type: 'code',
                  scope:
                    'https://www.googleapis.com/auth/gmail.send openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile',
                }
              )
            }}>
            Allow outgoing email
          </button>
        ) : (
          'Gmail is connected'
        )}
      </main>
    </AuthenticatedLayout>
  )
}

export const getServerSideProps = withAuthSsr(async (ctx) => {
  const session = ctx.req.session
  const settings = await prisma.account.findUnique({
    where: { userId: session.user.id },
    select: { scope: true },
  })
  return {
    props: {
      settings,
      ...(ctx.req.session && { session: ctx.req.session }),
    },
  }
}, '/')
```

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by timfee** [comment]
btw, confirmed that this code does what I'd expect:

```tsx
  callbacks: {
    signIn: async ({ user, account, profile, email, credentials }) => {
      await prisma.account.update({
        where: {
          provider_providerAccountId: {
            provider: account.provider,
            providerAccountId: account.providerAccountId,
          },
        },
        data: { ...account },
      })
      return true
    },
```

it matches the `updateUser` signature pretty 1:1:
```tsx
updateUser: ({ id, ...data }) => p.user.update({ where: { id }, data }),
```

so maybe the distinct FR is to expose & fire a similar `updateAccount` function.

**Comment by ThangHuuVu** [comment]
Looking great! If this is working for you, then I suggest you keep this code in the application. We'll consider adding this feature if there are a majority of users also ask for this (in new issues). I'll close the issue for now.
