### ISSUE TITLE
How to implement OIDC with Facebook: token_endpoint must be configured on the issuer

### ISSUE THREAD

**Issue by gustavo-maurina** [nextauthjs/next-auth#4608]
### Question 💬

I'm trying to implement OIDC with the Facebook Provider and currently this is the error I'm receiving: 

```
[token_endpoint must be configured on the issuer](https://next-auth.js.org/errors#callback_oauth_error token_endpoint must be configured on the issuer TypeError: token_endpoint must be configured on the issuer)
```

I have tried to follow the docs on both Facebook and NextAuth on how to implement the OIDC authorization, but this error message is way too simple and I can't figure out what I'm missing.

### How to reproduce ☕️

I have made a minimal reproducible code in this repo: https://github.com/gustavo-maurina/facebook-login-troubleshoot

This is my Facebook Provider (the credentials are from a test app): 

```javascript
export default NextAuth({
  providers: [
    FacebookProvider({
      idToken: true,
      clientId: "392039059588230",
      clientSecret: "5e50ebb6b06a8ac6e380d0fb38621b1a",
      wellKnown: "https://www.facebook.com/.well-known/openid-configuration",
      token: {
        url: "https://www.facebook.com/v11.0/dialog/oauth",
        params: { scope: "openid email public_profile" },
      },
    }),
  ],
  secret: "sunSAd2RkCajg2DLR3+5MfsinFwws8ZuzfPm2C+FXkc=",
});
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by pantonie** [comment]
According to [OIDC specification](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata) `token_endpoint` is required parameter but facebook openid configuration doesn't include it. Just open https://www.facebook.com/.well-known/openid-configuration to check it yourself.

**Comment by gustavo-maurina** [comment]
> According to [OIDC specification](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata) `token_endpoint` is required parameter but facebook openid configuration doesn't include it. Just open https://www.facebook.com/.well-known/openid-configuration to check it yourself.

I found this problem too, but after reading some of NextAuth docs I thought I had it covered by using this property:

```js
token: {
     url: "https://www.facebook.com/v11.0/dialog/oauth",
     params: { scope: "openid email public_profile" },
},
```

**Comment by balazsorban44** [comment]
This is an issue with Facebook's OIDC implementation. There is nothing for us to do here.
