### ISSUE TITLE
default expose the access token to frontend

### ISSUE THREAD

**Issue by ziponia** [nextauthjs/next-auth#4628]
### Question 💬

Why not expose the access token to the frontend by default option?

I already know how to expose. Just wondering why the default is not set.

### How to reproduce ☕️

```typescript
const App = () => {
    const { data: session } = useSession();
    console.log(session) // no access token and refresh_token
}
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
We try to have a strict default set. Judging from your comment above, please never expose the `refresh_token`! Nice example to explain why we are doing this.
