### ISSUE TITLE
Username / Password Authentication

### ISSUE THREAD

**Issue by pateljoel** [nextauthjs/next-auth#4635]
### Question 💬

Does Next-Auth have support for username/password authentication, the nextjs docs suggested they do, but I can't find it anywhere?

> If you want a full-featured authentication system with built-in providers (Google, Facebook, GitHub…), JWT, JWE, email/password, magic links and more… use [next-auth](https://github.com/nextauthjs/next-auth-example). 

https://nextjs.org/docs/authentication

### How to reproduce ☕️

> If you want a full-featured authentication system with built-in providers (Google, Facebook, GitHub…), JWT, JWE, email/password, magic links and more… use [next-auth](https://github.com/nextauthjs/next-auth-example). 

https://nextjs.org/docs/authentication

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by jhylton** [comment]
its under the 'Credentials' provider
https://next-auth.js.org/providers/credentials

**Comment by balazsorban44** [comment]
Answered above.
