### ISSUE TITLE
Pass `user` object to session callback

### ISSUE THREAD

**Issue by mwildehahn** [nextauthjs/next-auth#464]
**Summary of proposed feature**
I'd like to augment the default data returned in the session payload. The session callback is a nice way to do this, but it would be more useful if you passed the user object through.

**Purpose of proposed feature**
Make it easier to customize the session payload.

**Detail about proposed feature**
Add a `user` param to the session callback.

**Potential problems**
If you're using jwt there is no user so this could complicate the function signature. 

**Describe any alternatives you've considered**
I've thought about adding a separate endpoint to get additional session data but this seems redundant since I'm already fetching the session on each page.

*Please indicate if you are willing and able to help implement the proposed feature.*
Happy to submit a PR for this if it makes sense.

**Comment by iaincollins** [comment]
Thanks for capturing this @mwildehahn! I completely agree the User object should be supplied to the Sign In, Session and JWT callback (substituted for the OAuth or other Profile object if not using a database).

This is something I plan to resolve for v3 (the last major bit of work that I think is outstanding; behaviour in v3 has been impacted by other changes and needs review).

I'm trying to work out the best API for it right now to cater for all scenarios equally - so am starting with documentation that describes how it should work then refactoring the implementation accordingly.

**Comment by mwildehahn** [comment]
Sounds good! I’m loving the library in general, let me know if I can help!

**Comment by iaincollins** [comment]
This should be resolved with the [new callbacks in version 3.0](https://next-auth.js.org/configuration/callbacks)!
