### ISSUE TITLE
Add `userId` field to default session

### ISSUE THREAD

**Issue by remorses** [nextauthjs/next-auth#4661]
### Description 📓

Every time i use next-auth i find myself adding the userId field to the session callback:
```ts
    callbacks: {
        async session({ session, token }) {
            session.user.id = token.userId
            return session
        },
```

It would be better to add this field by default, this would also make it easier for libraries built on top of `next-auth` to get the current user id without telling their users to add the code above

I would not consider this a breaking change, if someone is adding an id field to the session they will simply override the default value

### How to reproduce ☕️

.

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
We don't plan to expose other defaults at this moment.
