### ISSUE TITLE
Insufficient length for tokens (Adapter: Sequelize) (Provider: Google) (Database: Postgres)

### ISSUE THREAD

**Issue by StephenLHChan** [nextauthjs/next-auth#4665]
### Adapter type

@next-auth/sequelize-adapter

### Environment

System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 81.23 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Safari: 15.4
  npmPackages:
    next-auth: ^4.3.4 => 4.3.4 

  npmPackages:
    @next-auth/sequelize-adapter: ^1.0.2 => 1.0.2 

### Reproduction URL

localhost:3000

### Describe the issue

Provider: Google
Database: Postgres

Token Size from Google:
Authorization codes: 256 bytes
Access tokens: 2048 bytes
Refresh tokens: 512 bytes

From Sequelize:
```
DataTypes.STRING             // VARCHAR(255)
```

Code:
```JavaScript

const db = new Sequelize(
  process.env.DATABASE_URL || 'postgres://localhost:5432/myapplication',
  {
    logging: false
  }
);
db.sync()

...
{providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET
    })
  ],
  adapter: SequelizeAdapter(db)}
```

Error:
```
[next-auth][error][adapter_error_linkAccount] 
https://next-auth.js.org/errors#adapter_error_linkaccount value too long for type character varying(255) {
  message: 'value too long for type character varying(255)',
  stack: 'Error\n' +
    '    at Query.run (server/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n' +
    '    at /server/node_modules/sequelize/lib/sequelize.js:311:28\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async PostgresQueryInterface.insert (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:308:21)\n' +
    '    at async model.save (/server/node_modules/sequelize/lib/model.js:2432:35)\n' +
    '    at async Function.create (/server/node_modules/sequelize/lib/model.js:1344:12)\n' +
    '    at async linkAccount (/server/node_modules/@next-auth/sequelize-adapter/dist/index.js:96:13)',
  name: 'SequelizeDatabaseError'
}
```

### Expected behavior

no error

**Comment by balazsorban44** [comment]
You can extend/customize your model as per the docs:

https://next-auth.js.org/adapters/sequelize#using-custom-models

https://sequelize.org/docs/v6/core-concepts/model-basics/#strings
