### ISSUE TITLE
Explain rationale for M2M relationship between users and account

### ISSUE THREAD

**Issue by iMerica** [nextauthjs/next-auth#4677]
### Question 💬

According to the [docs](https://next-auth.js.org/adapters/models#account):

 > A single User can have multiple Accounts, but each Account can only have one User.

Can someone please provide a few concrete examples as to why this is. Please be as specific as possible. 

Thank you!

### How to reproduce ☕️

n/a

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
A user can log in to multiple services (eg.: Google, GitHub, etc.). Those will be Accounts. These are linked together, creating a User.
A diagram for the relations and more information about users and accounts can be found here:

https://next-auth.js.org/adapters/models
https://next-auth.js.org/adapters/models/#user
https://next-auth.js.org/adapters/models/#account
