### ISSUE TITLE
Improve documentation for callbacks and adapter methods

### ISSUE THREAD

**Issue by iMerica** [nextauthjs/next-auth#4689]
### Description 📓

Hi,

Thanks for building this. We currently have [this page](https://next-auth.js.org/tutorials/creating-a-database-adapter) showing  a custom adapter and we have [this page](https://next-auth.js.org/configuration/callbacks) showing callbacks, but we still have a big gap of undocumented behavior for how these constructs work together if at all.

For example, we currently have events, callbacks and adapters to define custom logic. In JS, the term callback refers to a function that passed to another function typically invoked after some other work is done. However that concept collides with "events" in Next-auth.  It would be great if there was one clear and documented place to put custom business logic and to clearly describe the sequence and order of execution of callback/adapter methods (like a visual sequence diagram) 

 It would also be great to see a complete demo app that uses callbacks, events and a custom adapter for a highly popular Provider like Google.

Thank you,

Michael  

### How to reproduce ☕️

n/a

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
We currently have separate documentation for:

Callbacks: https://next-auth.js.org/configuration/callbacks
Events: https://next-auth.js.org/configuration/events
Adapters: https://next-auth.js.org/adapters/models, https://next-auth.js.org/tutorials/creating-a-database-adapter#how-to-create-an-adapter, and you can have a look at any of the official adapters in this folder: https://github.com/nextauthjs/next-auth/tree/main/packages

A deployed example (including Google as a provider as well) can be found here: https://next-auth-example.vercel.app/

with the source code available as a repository template: https://github.com/nextauthjs/next-auth-example synced from the source https://github.com/nextauthjs/next-auth/tree/main/apps/example-nextjs

Weren't any of these helpful enough? Please let us know how we can make it better, concrete suggestions are welcome!

As for a diagram, I think that might be a good idea, something similar to/expansion of the diagram for our OAuth flow found here: https://next-auth.js.org/configuration/providers/oauth

Thanks for the feedback!
