### ISSUE TITLE
Global Auth with SSG

### ISSUE THREAD

**Issue by JuanM04** [nextauthjs/next-auth#470]
*Please refer to the [documentation](https://next-auth.js.org/getting-started/introduction), the [example project](https://github.com/iaincollins/next-auth-example) and existing issues before creating a new issue.*

**Your question**
Is there a way to apply NextAuth with SSG?

**What are you trying to do**
 My particular goal is doing a global auth (all pages), so I put my login in `_app`, but it broke SSG and turned on SSR.

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
There are no problems using SSG or static pages with NextAuth.js that I'm aware of. I've just tried adding an SSG page to the example project (which uses `_app.js`) and didn't have any problems building and running an SSG page.

**Comment by JuanM04** [comment]
How did you do that? As far as I know, when you use `getInitialProps` in `_app.js`, SSG gets disabled

**Comment by iaincollins** [comment]
Yes that's my understanding too, I didn't use `getInitialProps()` in `_apps.js` :-)

Using the `useSession()` hook on an SSG page seems to work fine.

**Comment by adriandmitroca** [comment]
Hmm, I am not sure if everything is good here. Generally speaking everything works, but when you enter a page via <Link> that is pre-rendered, session from `useSession` becomes `{}` and requires hard refresh to restore user details.

**Comment by adriandmitroca** [comment]
See how useSession() reacts after few <Link> clicks across the page. All static pages, dev mode.

![Pasted_Image_27_07_2020__21_50](https://user-images.githubusercontent.com/3842935/88585290-351a4b00-d053-11ea-97c1-28bbf3da48fc.png)

Suddenly, session returns undefined and loading becomes always true.

**Comment by JuanM04** [comment]
> Using the `useSession()` hook on an SSG page seems to work fine.

...that makes sense... Yeah...I'll give it a try

**Comment by JuanM04** [comment]
> Hmm, I am not sure if everything is good here. Generally speaking everything works, but when you enter a page via that is pre-rendered, session from `useSession` becomes `{}` and requires hard refresh to restore user details.

That's a problem
