### ISSUE TITLE
defaultCookies is not defined

### ISSUE THREAD

**Issue by mike-webdev** [nextauthjs/next-auth#4709]
### Question 💬

Hi I'm using next-auth version: 3.27.3 
I suddenly got this error while running my app. Anyone encountered this? Thank you.

```
error - unhandledRejection: ReferenceError: defaultCookies is not defined
    at C:\Users\MAGICSOFT Mike\Desktop\NEW MAGICSOFT\crd-prototype\node_modules\next-auth\dist\server\index.js:102:9
    at new Promise (<anonymous>)
    at NextAuthHandler (C:\Users\MAGICSOFT Mike\Desktop\NEW MAGICSOFT\crd-prototype\node_modules\next-auth\dist\server\index.js:67:10)
    at NextAuth (C:\Users\MAGICSOFT Mike\Desktop\NEW MAGICSOFT\crd-prototype\node_modules\next-auth\dist\server\index.js:299:10)
    at __WEBPACK_DEFAULT_EXPORT__ (C:\Users\MAGICSOFT Mike\Desktop\NEW MAGICSOFT\crd-prototype\.next\server\pages\api\auth\[...nextauth].js:188:128)
    at Object.apiResolver (C:\Users\MAGICSOFT Mike\Desktop\NEW MAGICSOFT\crd-prototype\node_modules\next\dist\server\api-utils.js:101:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async DevServer.handleApiRequest (C:\Users\MAGICSOFT Mike\Desktop\NEW MAGICSOFT\crd-prototype\node_modules\next\dist\server\next-server.js:775:9)
    at async Object.fn (C:\Users\MAGICSOFT Mike\Desktop\NEW MAGICSOFT\crd-prototype\node_modules\next\dist\server\next-server.js:666:37)
```

### How to reproduce ☕️

npm run dev

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by untillnesss** [comment]
I also get an error like that, even though previously the application was running fine.

![image](https://user-images.githubusercontent.com/33585758/173539891-b87faaa7-b53d-48cf-9e4f-a86772e70ad0.png)

**Comment by balazsorban44** [comment]
Hi, v3 is an unmaintained version. Please upgrade to v4 and report back if you still experience the issue.

**Comment by mike-webdev** [comment]
The solution here is a hustle to many users.

**Comment by chaudev** [comment]
> Hi, v3 is an unmaintained version. Please upgrade to v4 and report back if you still experience the issue.

I faced the same problem, my project is running fine on v3 and when I upgrade to v4 it crashes in many places. 
Why this absurdity? 
Shouldn't the old version still work?

**Comment by Fleeb** [comment]
We are expecting the old version to still work since nothing was changed - even if v3 is an unmaintained version.

**Comment by fabien** [comment]
Same error here, nothing changed on the codebase, my client just did another deploy due to CMS updates. This is unacceptable.

**Comment by hawkyre** [comment]
I've just got the same problem, can't upgrade because I'm using the firebase adapter. Downgrading to `3.29.3` works. Thanks, fabien!

**Comment by mike-webdev** [comment]
Upgrading from 3.27.3 to 3.29.3 works for me too . Thanks!

**Comment by anargiris** [comment]
I've been having problems with the same exact error (client needed updates on their site but kept getting this error). 

Changing version from ^3.29.0 to 3.29.3 fixed the issue. Would love to know more information about this and what caused the error.

**Comment by mike-webdev** [comment]
Seems to work at first try but when I clone a new project, the error is still there.

**Comment by iamharshad** [comment]
> Same error here, nothing changed on the codebase (and using older v3), my client just did another deploy due to CMS updates. This is unacceptable.
> 
> ```
> [POST] /api/auth/_log
> 20:14:15:50
> 2022-06-14T18:14:18.805Z	8563085b-526b-4d39-bb06-b37d643e1344	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"ReferenceError: defaultCookies is not defined","reason":{"errorType":"ReferenceError","errorMessage":"defaultCookies is not defined","stack":["ReferenceError: defaultCookies is not defined","    at /var/task/node_modules/next-auth/dist/server/index.js:102:9","    at new Promise (<anonymous>)","    at NextAuthHandler (/var/task/node_modules/next-auth/dist/server/index.js:67:10)","    at NextAuth (/var/task/node_modules/next-auth/dist/server/index.js:299:10)","    at /var/task/.next/server/chunks/5599.js:546:64","    at Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:185:15)","    at processTicksAndRejections (internal/process/task_queues.js:95:5)","    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:395:9)","    at async Object.fn (/var/task/node_modules/next/dist/server/base-server.js:496:37)","    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:226:36)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: ReferenceError: defaultCookies is not defined","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:412:35)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:96:32)"]}
> Unknown application error occurred
> ```
> 
> **EDIT** I downgraded `next-auth` explicitly to version `3.29.3` (was `^3.29.3` before) and now it works!

This works for me

**Comment by balazsorban44** [comment]
`3.29.6` should include this fix: https://github.com/nextauthjs/next-auth/pull/4711, still unable to reproduce anything similar in v4.

**Comment by MohammadWawan** [comment]
i'm have error of the auth, the error is like this {"message":"There is a problem with the server configuration. Check the server logs for more information."}. help me to solve it.
