### ISSUE TITLE
Email provider bug with case sensitivity & custom magic code implementation

### ISSUE THREAD

**Issue by ifightcrime** [nextauthjs/next-auth#4716]
### Provider type

Email

### Environment

N/A

### Reproduction URL

N/A

### Describe the issue

The bug looks like it actually exists in core, but impacts `EmailProvider`. When building out a custom flow to send a verification code instead of a link, I noticed that when `useVerificationToken()` is called it's not down-casing the email address. Therefore logging in doesn't work if you type any uppercase characters (e.g. on iPhone where it auto-capitalizes the first letter)

### How to reproduce

This doesn't seem like an issue with vanilla email provider as it looks like the link is generated with a downcased version here:

https://github.com/nextauthjs/next-auth/blob/2469e44572f23f709fa8c5c65c6b7a4eb2383e9f/packages/next-auth/src/core/routes/signin.ts#L38

So likely not super high priority. However, this caused a bug in my custom implementation as I was taking the email address as written from the form. My workaround is to down-case it myself before I send to next-auth, but it seems like the down-casing should be more centralized. Maybe here:

https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/core/routes/callback.ts#L205-L211

### Expected behavior

Email is always down-cased and user can login no matter how they case their email when inputting. Not sure if there are any security implications of this, but might be a nice lead-up for issues like #1465

**Comment by balazsorban44** [comment]
Thanks, do you want to open a PR? It looks like we just need to call `.toLowerCase()` before passing the `identifier` to `useVerificationToken`.
