### ISSUE TITLE
Why am I able to access /api/auth/* from the url bar ?

### ISSUE THREAD

**Issue by MathieuRegis** [nextauthjs/next-auth#4717]
### Question 💬

If I am authenticated or not, I can access from the url to `http://localhost/api/auth/session`, or `http://localhost/api/auth/providers` or all the `/api/auth/*`.

Why am I able to access it through the browser and is it a security issue or not ?
I can't find any resources and that, I looked on next-auth docs and issues / questions from this repo.

Thanks you

### How to reproduce ☕️

On [next-auth-example](https://github.com/nextauthjs/next-auth-example) for example, access `/api/auth/session` via a browser, I get an http 200 response and I can see what is inside the session.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by AngelAlexQC** [comment]
The route it's needed to check session from browser and get data.

**Comment by MathieuRegis** [comment]
> The route it's needed to check session from browser and get data.

Thanks for reply, I understood that,
But from a user point of view, it is not a problem that he can access these pages ?

I am concerned that the user may get information about the providers, or data stored in the session object that they are not supposed to see or access.

Thanks you

**Comment by balazsorban44** [comment]
The NextAuth.js client is a simple wrapper for the REST API that powers the library, which is documented here: https://next-auth.js.org/getting-started/rest-api

REST is the protocol to communicate between the client and server. There is nothing to hide here, as the client _needs_ to have access to these pages.

If used properly, you should not be concerned about the user having access, as no secret information is exposed. By default, NextAuth.js exposes a very minimal subset of user data, but you can easily control it by overriding the `session` callback method, documented here: https://next-auth.js.org/configuration/callbacks#session-callback

What you return there is essentially what you can see at `http://localhost:3000/api/auth/session`.

Hope that helps!

**Comment by MathieuRegis** [comment]
> 

That helps a lot, thanks for the answer !
