### ISSUE TITLE
Prisma Adapter documentation schema models have incorrect names

### ISSUE THREAD

**Issue by lachlansleight** [nextauthjs/next-auth#4727]
### What is the improvement or update you wish to see?

When using the Prisma adapter, the model names MUST be `account`, `session`, `user` and `verificationToken`. The Prisma Adapter page in the docs suggests using `Account`, `Session`, `User` and `VerificationToken`, which do not work. 

Either the documentation needs to be updated to reflect this, or the Prisma adapter needs to be updated to use the capitalized model names.

### Is there any context that might help us understand?

The reason that the suggested names do not work is due to these model names being hardcoded in various parts of the adapter. For example:

```ts
const { id: _, ...verificationToken } = await p.verificationToken.create({
    data,
});
return verificationToken;
```

Adding a `@@map` directive doesn't help, as this only changes the underlying table names, not the model objects on the root prisma object.

I renamed my model names to use lowercase and everything works fine.

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/adapters/prisma

**Comment by balazsorban44** [comment]
This is unrelated to NextAuth.js, please see https://www.prisma.io/docs/concepts/components/prisma-schema/data-model
