### ISSUE TITLE
Add additional parameters to sendVerificationRequest

### ISSUE THREAD

**Issue by zdila** [nextauthjs/next-auth#4729]
### Description 📓

In my use-case it is not possible to tell in `sendVerificationRequest` which is user's preferred language because I have no access to the (HTTP) request. It would be useful to access either request or a new custom argument passed to `signIn` function.

### How to reproduce ☕️

Try to get user's language (eg. from http header or URL) in `sendVerificationRequest`. Not possible.

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
I would consider this an advanced use case, in which situation you can use [Advanced Initialization](https://next-auth.js.org/configuration/initialization#advanced-initialization). You will have access to the incoming request headers where you can for example check for the user's preferred language, etc.

It's an uncommon use case, but you can use the third argument of `signIn` to pass additional parameters to the server what you can also check in the above-mentioned way. See: https://next-auth.js.org/getting-started/client#additional-parameters
