### ISSUE TITLE
Add edgedb adapter

### ISSUE THREAD

**Issue by brielov** [nextauthjs/next-auth#4730]
### Description 📓

Edgedb is an awesome graph database. It reached 1.0 not so long ago and it has a similar developer experience as prisma, with a type-safe query builder. It would be awesome to include an adapter for it. Here's a [link](https://www.edgedb.com/docs/clients/01_js/querybuilder) if you're not familiar with it.

### How to reproduce ☕️

```ts
export default function EdgedbAdapter(client, options = {}) {
  return {
    async createUser(user) {
      return client.querySingle(`insert User {
        name := <str>$name
        email := <str>$email
      }`, user)
    },
    // ...rest of the methods
  }
}
```

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
Sounds good, feel free to open a PR!

**Comment by MartinCura** [comment]
Hey! I've been wanting to migrate a project to use NextAuth + EdgeDB, would be best if this was an official adapter.

Did you get started with this, @brielov? Do you need a hand?

**Comment by MartinCura** [comment]
> @MartinCura I haven't been able to find the time yet (It's crazy at work right now), but I was thinking on taking a look at it this weekend. If you have the time, I would love the extra hand. I think the easiest way for me is to just copy whatever the prisma implementation is and just translate the queries to edgedb by accepting the raw client. What do you think?

Thought i would receive an email notification, so missed this until now. I had started doing a kind of EdgeDB adapter some months ago, i have to review it to see how far along it was. Starting from Prisma's implementation sounds like a good idea!

**Comment by johnschult** [comment]
This died on the vine... any interest still? I am pretty motivated to get this working.

**Comment by brielov** [comment]
Hey @johnschult. I started working on it a little while back, but stopped cause the edgedb team replied a tweet of mine asking them to implement it and they said sure, but I guess they didn't have the time yet. Anyways, I'm still interested and I can for sure give you a hand in whatever I can to make this happen.

**Comment by johnschult** [comment]
I'm game for a PR. Maybe we can hit up someone at EdgeDB to see if they have any interest or ability to help as well. We should be able to get this done. This is not rocket science right?

**Comment by johnschult** [comment]
@MartinCura @brielov I forked and found a really great example of a new adapter (xata #4911) that recently got merged. Along with the work that was done in https://github.com/cory-evans/next-auth-adapter-edgedb it should not be a big deal. Documentation will likely be a chore as well as maybe testing. It's all doable 💯 

If anyone wants to be added as a contributor to my fork and future `edgedb-adapter` please let me know 😄
