### ISSUE TITLE
Add Mediawiki OAuth provider

### ISSUE THREAD

**Issue by mshd** [nextauthjs/next-auth#4732]
### Description 📓

Mediawiki (connected to Wikimedia and Wikipedia) offers OAuth, which can be used to connect and give access to one's account.

https://www.mediawiki.org/wiki/Extension:OAuth

Would it be possible to implement it?

### How to reproduce ☕️

https://www.mediawiki.org/wiki/OAuth/For_Developers

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
Sounds like an OAuth provider, not a database adapter, but we are open for it, feel free to open the PR!
