### ISSUE TITLE
redirect_uri being encoded on vercel

### ISSUE THREAD

**Issue by jonrrivera** [nextauthjs/next-auth#4763]
### Question 💬

Hey!

Thanks for the great framework. I have been having trouble getting nextauth to work on vercel because my `redirect_uri` continues to be encoded. For some reason, this is only happening on the server. 

I enter it as an env variable without encoding chars, but then when nextauth runs  `authorization` the redirect_uri appears encoded in the browser.

### How to reproduce ☕️

```
export default NextAuth({
    secret: process.env.NEXTAUTH_SECRET,
    providers: [{
    authorization: `${process.env.NEXTAUTH_URL}oauth2/authorize?client_id=${process.env.NEXTAUTH_ID}&scope=publict&response_type=code&redirect_uri=${decodeURI('https://select.basic.space/api/auth/callback/select')}`,
}]
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Using NextAuth.js, you generally don't need to configure `redirect_uri` for the authorization request. When signing in, you can override where to land with the `callbackUrl`: https://next-auth.js.org/getting-started/client#specifying-a-callbackurl

If it's a different domain, you should allow it with the `redirect` callback like documented here: https://next-auth.js.org/configuration/callbacks#redirect-callback
