### ISSUE TITLE
Is there a way to make a custom model in next-auth

### ISSUE THREAD

**Issue by phichayut-pak** [nextauthjs/next-auth#4768]
### Question 💬

Hi! I wonder if I can make a custom model for next-auth
for example, if I want to add isAdmin in every document in user collection referring from the picture attached. 
![image](https://user-images.githubusercontent.com/22463788/175764805-d588bf7e-caeb-45a2-8dbc-250ca723e8cd.png)

### How to reproduce ☕️

![image](https://user-images.githubusercontent.com/22463788/175764816-d17a110e-28c0-48d1-b711-cb98f42991cf.png)

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Absolutely, please check out the documentation for the given adapter you use, and the `profile` callback on providers:

https://next-auth.js.org/adapters/models#user 

https://next-auth.js.org/adapters/overview

**Comment by Wiper-R** [comment]
> Absolutely, please check out the documentation for the given adapter you use, and the `profile` callback on providers:
> 
> https://next-auth.js.org/adapters/models#user
> 
> https://next-auth.js.org/adapters/overview

Page not found
