### ISSUE TITLE
Is there a way to update the default font used by the signIn component?

### ISSUE THREAD

**Issue by ilmoi** [nextauthjs/next-auth#4770]
### Question 💬

The title says it. Would love to be able to update the font for the signIn component to a custom one. Couldn't find anything in docs and there doesn't seem to be a custom CSS class attached that I could overwrite.

### How to reproduce ☕️

-

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
If you mean the sign-in page, I believe currently you cannot override this.

We have to draw the line somewhere what can be customized on the default pages and when should you create your own. 😅

Please see https://next-auth.js.org/configuration/pages
