### ISSUE TITLE
What outgoing requests does the api/auth/callback/<provider id> make?

### ISSUE THREAD

**Issue by prandell** [nextauthjs/next-auth#4771]
### Question 💬

Hi guys, having a lot of trouble using the AzureAD provider in production.

The TL;DR / primary question is, **what is meant to happen when I access the callback url of my oauth provider?** 

Doing so directly locally brings me to my sign in page with an error saying the callback didn't contain any id_token. This sounds reasonable to me. However, in production, there seems to be some external request made, and the only information I'm given is:

```
CALLBACK_OAUTH_ERROR {
  "name": "OAuthCallbackError",
  "message": "outgoing request timed out after 40000ms",
  "stack": <trace>
}
```

So why could this be, with every configuration the same (using containers) aside from the host?

** LONG VERSION **

Locally, I am able to sign in using my AzureAD provider which directs me to microsoft to sign in with my corporate account, and I can see that the debug logs show:

```
CREATE_STATE {
  "state": "SUZoMRIzvJuyJxEsJZBj5UELQkMDEdzi-Baf6GQSj-Q",
  "maxAge": 900
}
GET_AUTHORIZATION_URL {
  "url": "https://login.microsoftonline.com/<tenant>/oauth2/v2.0/authorize?client_id=<client>&scope=openid%20profile%20email&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fauth%2Fcallback%2Fazuread&state=SUZoMRIzvJuyJxEsJZBj5UELQkMDEdzi-Baf6GQSj-Q",
  "cookies": [
    {
      "name": "next-auth.state",
      "value": "<value>",
      "options": {
        "httpOnly": true,
        "sameSite": "lax",
        "path": "/",
        "secure": false,
        "expires": "2022-06-26T23:14:19.832Z"
      }
    }
  ]
}
```

You can see there is a step to create state. I have also tried using PKCE and there is a similar step to create the code challenge which is reflected in the authorization url

However, the app we have set up is obviously not at localhost, and the redirect_uri also expects to have the same production host. 

I am using docker containers, and the exact same image works locally at least to get us redirected to Microsoft and create the challenge, however in production I get these errors:

```
GET_AUTHORIZATION_URL_ERROR {
  "name": "RPError"
}
SIGNIN_OAUTH_ERROR {
  "error": {
    "name": "RPError"
  },
  "provider": {
    "id": "azuread",
    "name": "SSO",
    "type": "oauth",
    "wellKnown": "https://login.microsoftonline.com/<tenant>/v2.0/.well-known/openid-configuration",
    "authorization": {
      "params": {
        "scope": "openid profile email"
      }
    },
    "idToken": true,
    "checks": [
      "state"
    ],
    "tenantId": "<tenant>",
    "clientId": "<client>",
    "clientSecret": "<secret>",
    "httpOptions": {
      "timeout": 40000
    },
    "signinUrl": "https://<prod_host>/api/auth/signin/azuread",
    "callbackUrl": "https://<prod_host>/api/auth/callback/azuread"
  }
}
```

You can see that it fails to generate the code challenge and auth url despite being the exact same code. Additionally, the reason I increased the http timeout is because it actually takes the entire duration of this timeout before showing this error, which I similarly don't quite understand

Any help would be appreciated, this has been driving me mad!

### How to reproduce ☕️

Unfortunately this cannot be reproduced as it may be specific to my corporate set up, however the steps are roughly

However my api/auth/[...nextauth].js file is as such:

```
export default NextAuth({
	debug: true,
	logger: {
		error(code, metadata) {
			console.log(code, JSON.stringify(metadata, null, 2))
		},
		warn(code) {
			console.log(code)
		},
		debug(code, metadata) {
			console.log(code, JSON.stringify(metadata, null, 2))
		}
	},
	
	providers: [
		AzureADProvider({
			id: 'azuread',
			name: 'SSO',
			tenantId: process.env.AZURE_AD_B2C_TENANT_ID,
			clientId: process.env.AZURE_AD_B2C_CLIENT_ID,
			clientSecret: process.env.AZURE_AD_B2C_CLIENT_SECRET,
			checks: ['pkce'],
			httpOptions: {
				timeout: 40000
			}
		}),
	],
	session: {
		strategy: 'jwt',
		maxAge: 24 * 60 * 60
	},
	pages: {
		signIn: '/login',
		error: '/login'
	}
})
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
The OAuth flown is described here https://next-auth.js.org/configuration/providers/oauth

There might be small differences based on how you set up the sign-in process and how you configured your provider though, but should give you the idea.

> Unfortunately this cannot be reproduced as it may be specific to my corporate set up

This makes it very hard to recommend anything specific. 😕

To me it sounds like a proxy issue, maybe requests to your provider are blocked.
