### ISSUE TITLE
Changelogs for v3.29.2-6+

### ISSUE THREAD

**Issue by Half-Shot** [nextauthjs/next-auth#4773]
### What is the improvement or update you wish to see?

We got a dependabot alert through to upgrade our application from 3.29.x to 3.29.6. Usually when this happens, we like to check the changelog to see what changed, but there doesn't seem to be a tag or any changelogs to refer to. This isn't terribly good practise as it's asking developers to blankly trust that the minor release is safe. Can tags / changelogs be created for all versions published to npm?

### Is there any context that might help us understand?

https://www.npmjs.com/package/next-auth/v/3.29.6 exists, but has no corresponding GitHub entry.

**Comment by balazsorban44** [comment]
v3 is unmaintained. The last updates were purely security patches. We recommend upgrading to v4 as quickly as possible.

For the security patch descriptions, you can check out the security advisories: https://github.com/nextauthjs/next-auth/security/advisories?state=published
