### ISSUE TITLE
How to call the signOut endpoint directly

### ISSUE THREAD

**Issue by seangerrykelly** [nextauthjs/next-auth#4779]
### Question 💬

I am wondering if there's a way to call the `api/auth/signout` endpoint directly. Based on the [REST API documentation](https://next-auth.js.org/getting-started/rest-api#post-apiauthsignout), it seems like it's possible to make a POST request directly to the endpoint. However, when trying to make a POST request with a CSRF token, the only thing being returned is the HTML from the Next Auth signOut page at http://localhost:3000/api/auth/signout in my local app.

Using the `signOut` method works in my application. I tried copying the form-data after inspecting the Network tab and making the request directly from postman, but the result is the same as described earlier.

### How to reproduce ☕️

This requires a web app with `next-auth` and Postman to recreate. Here are the steps:

1. Create a new POST request in Postman. Put http://localhost:3000/api/auth/signout as the URL.
2. Generate a new CSRF token from http://localhost:3000/api/auth/csrf
3. Under Body, select _form-data_ and add the following Key-Value pairs:
- csrfToken: <the result from step 2>
- callbackUrl: <your callback URL>
- json: true

4. Send the request.
5. In the response, select "Preview". You will see the next-auth signout page.
![Postman Next Auth](https://user-images.githubusercontent.com/58237269/176032423-85cad264-c203-437c-b2ab-02c00b9e719c.png)

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Yes, this is possible, it's exactly what THE `signOut` method does as well.

See https://github.com/nextauthjs/next-auth/blob/c194261617d4bb6d553e5752565270abc30633c0/packages/next-auth/src/react/index.tsx#L255-L289
