### ISSUE TITLE
Should hash locations work in callback urls?

### ISSUE THREAD

**Issue by incompl** [nextauthjs/next-auth#4784]
### Question 💬

Not sure if this is a bug or not. I have a working implementation, but when I add a hash location to my callback URL it doesn't redirect. Instead it keeps me on the signin page.

### How to reproduce ☕️

My `signIn` call looks roughly like this:

```
await signIn('shopify', { email, password, rememberMe, callbackUrl: 'http://example.com/foo#bar' });
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by matteoxplo** [comment]
Hi,
i have the same problem, if i have a callbackUrl that contains a # it doesn't redirect, seems like it reload the same page.

**Comment by Cris21395** [comment]
I am experiencing the same issue with credentials provider.

**Comment by matteoxplo** [comment]
I have found that in a previous commit they have added this function to the code because some login provider (e.g. google) put a '#' in the url when requiring a refresh:
```
if (redirect || !isSupportingReturn) {
    const url = data.url ?? callbackUrl
    window.location.href = url
    // If url contains a hash, the browser does not reload the page. We reload manually
    if (url.includes("#")) window.location.reload()
    return
}
```
  
I have solved using those two options:
```
await signIn("credentials", {
    email: inputs.email,
    password: inputs.password,
});\
router.push(backurl);
```
or
```
await signIn("credentials", {
    email: inputs.email,
    password: inputs.password,
});
window.location.href = backurl;
```
