### ISSUE TITLE
unstable_getServerSession does not return id/sub property

### ISSUE THREAD

**Issue by bitforth** [nextauthjs/next-auth#4794]
### Question 💬

I'm not an expert on identity, but I think the method `unstable_getServerSession` should return the id of the session. 

For example, if I run this code in a server API:

```
  const session = await unstable_getServerSession(req, res, authOptions);
  console.log({ session });
```

It outputs this:
```
{
  session: {
    user: {
      name: 'Alan Chavez',
      email: 'myemail@gmail.com,
      image: undefined
    },
    expires: '2022-07-29T11:03:31.819Z'
  }
}
```

I am expecting to see either a `sub` or `id` property under the `user` object

### How to reproduce ☕️

I am using a keycloak provider, but I think it should be able to repro with any provider.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
You'll need to check up on the jwt and session callbacks. user ID is not returned by default https://next-auth.js.org/configuration/callbacks

**Comment by kasperwelbers** [comment]
Hi @balazsorban44 ,

I had the same question, because (unless I'm mistaken) the session callback only exposes the user ID. Is it also possible to get the session ID?

My current workaround is to fetch it from the DB based on the user ID and expired time, but there is probably a better way.
