### ISSUE TITLE
Traditional username/password login

### ISSUE THREAD

**Issue by muhaimincs** [nextauthjs/next-auth#481]
*Please refer to the [documentation](https://next-auth.js.org/getting-started/introduction), the [example project](https://github.com/iaincollins/next-auth-example) and existing issues before creating a new issue.*

**Your question**
Is it possible to use this package as replacement for traditional username/password login

**What are you trying to do**
Try to submit username/password to be authenticate on Laravel server

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by nyedidikeke** [comment]
> Is it possible to use this package as replacement for traditional username/password login

Yes, provided it NextAuth satisfies the minimum or core authentication requirements for your project.

> Try to submit username/password to be authenticate on Laravel server

Follow the documentation at https://next-auth.js.org/providers/credentials in order to learn more; it has examples that covers other scenarios such as YubiKey U2F and 2FA.

**Comment by ndom91** [comment]
@muhaimincs we've also recently added an example using the custom credentials provider for ldap auth. Maybe you can use that as an example going forward. 

The example is not merged yet, but you can check out the docs [here](https://github.com/nextauthjs/next-auth/blob/677db9d23cf5dfd23be31c8a78af5d9317f950ab/www/docs/tutorials/ldap-auth.md)

And if you're reading this a bit in the future, it'll probably be merged and available here also: https://next-auth.js.org/tutorials/ldap-auth

I'm going to close this issue for now as there doesn't seem to be any other open questions. If you have any other feedback or questions, feel free to reopen it!
