### ISSUE TITLE
Middleware  NextRequest params type error

### ISSUE THREAD

**Issue by terrierscript** [nextauthjs/next-auth#4817]
### What is the improvement or update you wish to see?

https://next-auth.js.org/configuration/nextjs#wrap-middleware

In this documentation, wrap middleware get `req: NextRequest & { nextauth: { token: JWT | null } }` but this code got typescript error.

```
error TS2345: Argument of type '[(req: NextRequest & { nextauth: { token: JWT; }; }) => void]' is not assignable to parameter of type 'WithAuthArgs'.
  Type '[(req: NextRequest & { nextauth: { token: JWT; }; }) => void]' is not assignable to type '[NextRequest]'.
    Type '(req: NextRequest & { nextauth: { token: JWT; }; }) => void' is not assignable to type 'NextRequest'.
```

### Is there any context that might help us understand?

I think this issue has some options.

* Improve code types: maybe like `NextMiddlewareWithJWT`
* Improve doc: append `@ts-ignore` ( for workaround )

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/configuration/nextjs#wrap-middleware

**Comment by riccardogiorato** [comment]
I'm having the same issue with a simple project with:
- next 12.2.0
- next-auth 4.8.0

**Comment by Dannyisadog** [comment]
Same here:
 - next: 12.2.1-canary.2
 - next-auth: 4.6.1

**Comment by Rhym** [comment]
Same here:
- next: 12.2.2
- next-auth: 4.10.0

**Comment by balazsorban44** [comment]
This is partially an upstream issue in Next.js, here is a PR for it https://github.com/vercel/next.js/pull/38625

I also opened #4926 which will fix this issue, without needing any workarounds.
