### ISSUE TITLE
optional 2FA

### ISSUE THREAD

**Issue by confact** [nextauthjs/next-auth#4820]
### Question 💬

Hi,

I am trying to add support 2FA and noticed it mentioned adding it as credentials. I want to make it optional, showing up as a second step if needed, as many services are doing. So I need to know if it is filled or not to the backend.

Has anyone built that with next-auth and can give me some tips?

### How to reproduce ☕️

```javascript
CredentialsProvider({
    id: "intranet-credentials",
    name: "Two Factor Auth",
    async authorize(credentials, req) {
      const user = {
        /* add function to get user */
      }
      return user
    },
    credentials: {
      email: { label: "Username", type: "text ", placeholder: "jsmith" },
      "2fa-key": { label: "2FA Key" },
    },
  }),
  ```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
You can use [Advanced Initialization](https://next-auth.js.org/configuration/initialization#advanced-initialization)
. We actually have an example for an optional provider, based on the incoming request.

**Comment by petdomaa100** [comment]
> You can use [Advanced Initialization](https://next-auth.js.org/configuration/initialization#advanced-initialization). We actually have an example for an optional provider, based on the incoming request.

Could you link the example please?

**Comment by Greko2017** [comment]
Hi @confact,
Where you able to find a solution? I want to implement the same using next-auth

**Comment by kyb3r** [comment]
anyone find the example?

**Comment by Husain010** [comment]
Any update on this? Is there a proper way to do 2FA?

**Comment by Greko2017** [comment]
I found a workaround. By restricting access to page on the middleware.ts file.
