### ISSUE TITLE
Email Provider not sending the email when hitting email endpoint via Rest API instead from react client

### ISSUE THREAD

**Issue by rishabhgarg7** [nextauthjs/next-auth#4822]
### Provider type

Email

### Environment

  System:
    OS: macOS 12.4
    CPU: (4) x64 Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz
    Memory: 57.39 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.1/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 98.0.2
    Safari: 15.5
  npmPackages:
    next: 12.1.0 => 12.1.0
    react: 17.0.2 => 17.0.2

### Reproduction URL

https://github.com/rishabhgarg7/next-auth-example

### Describe the issue

I have a NextJs app and am using next-auth with four providers: Email, Facebook, Google, and Twitter.

I want to send the Magic Link Email via hitting the REST API instead of using `signIn` function from react client of next-auth.

Here's my use case:

1. User buys one of our subscription plans using an email address.
2. Our payment provider then call our REST API which I call ping endpoint.
3. Then this ping endpoint should send a Magic link email to that user on the same email address.

Issue: Instead of sending an email, it just returns a big HTML document. Ideally, it should have sent the email.

The Code of my ping API(which is also a part of the same nextjs app) looks like this:

```
import axios from "axios";

const sendEmail = async () => {
  const csrfUrl = "http://localhost:3000/api/auth/csrf";
  const csrfResponse = await axios.get(csrfUrl);
  const { data: csrfData } = await csrfResponse;
  const csrfToken = csrfData?.csrfToken;
  const emailUrl = "http://localhost:3000/api/auth/signin/email";

  const res = await fetch(emailUrl, {
    method: "post",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: {
      email: "xyz@gmail.com",
      csrfToken: csrfToken,
      callbackUrl: "/",
      json: true,
    },
  });
  const data = await res.text();
};

export default async function subscribe(req, res) {
  try {
    await sendEmail();
    res.status(201).json({ message: "Email sent.." });
  } catch (error) {
    return res
      .status(400)
      .json({ error: `Something went wrong. Error: ${error}` });
  }
}
```

### How to reproduce

1. Use an example next-auth project.
2. Enable Email Provider.
3. Create `api/ping.js` and then use the above code. 
4. Then call `ping` endpoint and ideally it should send the email.

### Expected behavior

Expected: Should send the email after calling ping API endpoint.

What's happening: Not sending the email and just returning a big HTML file.

While it's working and sending email when I'm using `signIn` method on client-side.

**Comment by balazsorban44** [comment]
you are not passing the cookies from the client and thus the CSRF check will fail. you can just call `signIn` for this from the client though. not sure why the extra endpoint.

**Comment by rishabhgarg7** [comment]
Thanks!

It gets successful though when I hit it from Postman.

So, you mean there's no way to send Magic Link Email via calling REST endpoint and it can be only sent from the client side?

**Comment by mschipperheyn** [comment]
I'm also struggling with this. I'm creating users through the front end through an intermediary (think event and promotion people hitting up people walking around with an ipad). So I need to create a user and send an email verification email to a user that is not the current user on the server-side.

**Comment by mschipperheyn** [comment]
I suppose an intermediary solution would be to create an intermediary client side page that processes the incoming email and executes the magic link login automatically. Bit hacky, but might work. The only thing I would imagine a problem is the existence of an already logged in user, as is my case

**Comment by mschipperheyn** [comment]
Yeah, I confirm that this approach works: 
1. register a new user while logged in as another user
2. send an email with a custom landing page
3. on that landing page execute an automated signIn with the new user email using React.useEffect
4. that user will receive a login email

only downside is that the user will have to go through his email twice.

**Comment by oldo** [comment]
I came across this issue and found a work around by setting the cookies explicitly in the sign in request:

```typescript
const client = axios.create({
  withCredentials: true,
});

try {
  // get csrf token
  const { data, headers } = await client.get<{ csrfToken: string }>(
    '/api/auth/csrf'
  );
  
  // get cookies from csrf request
  const cookies = headers['set-cookie'];

  // trigger set password email sign in flow
  await client.post(
    `/api/auth/signin/email`,
    qs.stringify({
      email,
      callbackUrl: `/auth/new-user`,
      redirect: false,
      csrfToken: data.csrfToken,
      json: true,
    }),
    {
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        cookie: cookies, // set cookies here
      },
    }
  );
} catch (error) {
  console.log('error triggering new user sign in flow');
  console.error(error);
}
```
