### ISSUE TITLE
IdentityServer4 is now IdentityServer Duende

### ISSUE THREAD

**Issue by poteirard** [nextauthjs/next-auth#4830]
### What is the improvement or update you wish to see?

Change the name or add another provider with that name and fix all the links in the documentation of the provider. 

For example, the demo now is: https://demo.duendesoftware.com/

### Is there any context that might help us understand?

Duende have taken over maintenance of the IS4 libraries

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/providers/identity-server4

**Comment by always-maap** [comment]
please don't drop the support for id4

**Comment by josh-the-dev** [comment]
We're looking to use this on an upcoming project coincidentally and noticed that there was no Duende adapter. I'm happy to investigate and open a PR for this 👍
