### ISSUE TITLE
Add direct support/adapter for Planetscale

### ISSUE THREAD

**Issue by AlvaroAquijeDiaz** [nextauthjs/next-auth#4831]
### Description 📓

When reading through the docs I found the desire the team has to implement and make `next-auth` run fully on the [edge](https://next-auth.js.org/configuration/nextjs#caveats), as far as I know the db/backend with this similar runtime is [planetscale](https://planetscale.com) the serverless, vitesse-based database.

That's why it'll be nice to implement an adapter for this db, which in conjunction with next/middleware could potentially make requests like auth much faster.

### How to reproduce ☕️

no idea how to do it tho 😢 (yet)

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by dephraiim** [comment]
You can use the Prisma Adapter with PlanetScale.

Use the `datasource` in your `schema.prisma` as below and set the `DATABASE_URL` as your PlanetScale Database URL.
```prisma
datasource db {
    provider             = "mysql"
    url                  = env("DATABASE_URL")
    referentialIntegrity = "prisma"
}
```

**Comment by AlvaroAquijeDiaz** [comment]
yep I knew about this, just thought there maybe a better addition/solution for the planetscale edge runtime

**Comment by balazsorban44** [comment]
Does PlanetScale has an officially maintained ORM/client? Otherwise Prisma might be the next best solution.

For creating an adapter:

https://next-auth.js.org/tutorials/creating-a-database-adapter

or check the source code of any of the adapters in https://github.com/nextauthjs/next-auth/tree/main/packages

**Comment by AlvaroAquijeDiaz** [comment]
I guess the best solution will be using prisma, noice
