### ISSUE TITLE
email.split(...)[0].trim(...).replaceAll is not a function

### ISSUE THREAD

**Issue by Diegolm357** [nextauthjs/next-auth#4835]
### Environment

OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 7.78 GB / 15.75 GB
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.44)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    next: 12.2.0 => 12.2.0
    next-auth: ^4.8.0 => 4.8.0
    react: 18.2.0 => 18.2.0

### Reproduction URL

https://github.com/Diegolm357/bug

### Describe the issue

I'm trying to see why I get this error.. Could you help me.

### How to reproduce

when logging in

### Expected behavior

![error](https://user-images.githubusercontent.com/76498632/177224822-e05ef96d-91d4-4169-8bac-0aee2eb45d12.jpg)

**Comment by balazsorban44** [comment]
It looks like `replaceAll` haven't been appropriately transpiled.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#browser_compatibility

It is only supported Node.js 15 and up, but you seem to use 14. We intend to support Node 14, so this is a bug, thanks for reporting!

I'll soon create a patch release to fix this, but as a workaround, for now, you can try upgrading Node.js or adding a [`replaceAll` polyfill](https://vanillajstoolkit.com/polyfills/stringreplaceall/).
