### ISSUE TITLE
Middleware Documentation is out of date

### ISSUE THREAD

**Issue by mhornung-chwy** [nextauthjs/next-auth#4867]
### What is the improvement or update you wish to see?

The middleware section of the docs describes using `/pages/_middleware.js`, which is no longer supported as of NextJs 12.2.2

https://next-auth.js.org/tutorials/securing-pages-and-api-routes#nextjs-middleware

### Is there any context that might help us understand?

https://next-auth.js.org/tutorials/securing-pages-and-api-routes#nextjs-middleware
https://nextjs.org/docs/advanced-features/middleware

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/tutorials/securing-pages-and-api-routes#nextjs-middleware

**Comment by larsqa** [comment]
Documentation is either out of date or middleware needs to be updated to reflect the new middleware implementation in v12.2.0.

I would say that this issue is a bit more pressing than "good first issue", since it prevents fully using next-auth in the latest next update.

**Comment by mhornung-chwy** [comment]
I see this issue is closed, but the docs still reference 2 things that are incorrect:
This filename should not have the underscore
![image](https://user-images.githubusercontent.com/91477128/179657085-731da6d5-f8e9-46ce-88f1-f2fefd3003e0.png)
Nested middleware is not longer supported, this line can be removed:
![image](https://user-images.githubusercontent.com/91477128/179657111-29ae5158-9b82-4864-a8d9-503fe2f3af4d.png)
https://nextjs.org/docs/messages/middleware-upgrade-guide#no-nested-middleware
