### ISSUE TITLE
CONTRIBUTING is not up to date

### ISSUE THREAD

**Issue by yoannfleurydev** [nextauthjs/next-auth#4886]
### What is the improvement or update you wish to see?

I am looking forward to contribute to NextAuth, but the CONTRIBUTING.md doesn't seem to be up to date. The documentation is mentioning `yarn`, but the project is now using `pnpm`.

### Is there any context that might help us understand?

I first followed the contribution mentioned in https://github.com/nextauthjs/next-auth/blob/main/CONTRIBUTING.md but it wasn't correct. If you assign me to this issue, it will be a pleasure to do a PR to update the file.

**Comment by ThangHuuVu** [comment]
Go for it @yoannfleurydev ! 🙌
