### ISSUE TITLE
mssql, Sql server,  support 

### ISSUE THREAD

**Issue by D10221** [nextauthjs/next-auth#489]
**Summary of proposed feature**
mssql, Sql server,  support 

**Purpose of proposed feature**
Adapter support for Sql Server (mssql)  database 

**Detail about proposed feature**
TypeORM already supports mssql, 

**Potential problems**
Similar to other TypeORM supported Adapters

**Describe any alternatives you've considered**
Write the adapter, as customization, as proposed by the documentation.

**Additional context**
see ( https://github.com/nextauthjs/next-auth/pull/491)

*Please indicate if you are willing and able to help implement the proposed feature.*
see proposed  (https://github.com/nextauthjs/next-auth/pull/491)

**Comment by D10221** [comment]
BTW, thanks for the nice lib,
The above went a bit dry :).

**Comment by iaincollins** [comment]
This should be going out soon (maybe tomorrow morning), closing now while I am here.

This was really great work by @D10221  <3
