### ISSUE TITLE
Minecraft Authentication Provider

### ISSUE THREAD

**Issue by aimproxy** [nextauthjs/next-auth#4890]
### Description 📓

Minecraft has moved to Microsoft accounts! Starting December 2020, all new Accounts already use the new system, and old accounts are now required to be migrated. Mineshop team want to benefit from Microsoft Authentication Scheme to authenticate Minecraft players into Shopify Stores. We already use NextAuthJs at the Edge on Vercel to perform authentication, our team will be more than happier to implement this feature on NextAuthJs.

Documentation on Microsoft OAuth flow is available here: https://wiki.vg/Microsoft_Authentication_Scheme
Our website: https://mineshop.app

### How to reproduce ☕️

This can't be reproduced

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by aimproxy** [comment]
yup! my team will start working on that next week.

**Comment by OfficialCRUGG** [comment]
Is there any update on this / anyone who is willing to implement this?
I'd add it myself, but Microsoft's authentification flow for Minecraft is quite complicated and involves many queries required and I don't know how one would implement that with next-auth
You can find more about how their flow works [here](https://wiki.vg/Microsoft_Authentication_Scheme)

**Comment by aimproxy** [comment]
@OfficialCRUGG Hi, can I know more about your use case? You can actually see an implementation of Microsoft's authentification flow for Minecraft here: https://docs.rs/ms_auth_mc/latest/src/ms_auth_mc/lib.rs.html#1-371

**Comment by ravinggenius** [comment]
@aimproxy did you get a `MicrosoftProvider` working? I'm also interested in that as I am working on some tools for Minecraft players.

**Comment by aimproxy** [comment]
I left the project because I don't have much time for it! @ravinggenius but the integration is possible yeah!
