### ISSUE TITLE
[next-auth][error][adapter_error_getSessionAndUser] 

### ISSUE THREAD

**Issue by Onyelaudochukwuka** [nextauthjs/next-auth#4892]
### Adapter type

@next-auth/mongodb-adapter

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 67.80 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
   Microsoft Edge: 103.0.1264.51 
  npmPackages:
    next: latest => 12.2.0 
    next-auth: ^4.9.0 => 4.9.0 
    react: 18.1.0 => 18.1.0 

  npmPackages:
    @next-auth/mongodb-adapter: ^1.0.3 => 1.0.3 

### Reproduction URL

Onyelaudochukwuka/urlshortene

### Describe the issue

[next-auth][error][adapter_error_getSessionAndUser] 
https://next-auth.js.org/errors#adapter_error_getsessionanduser bad auth : Authentication failed. {
  message: 'bad auth : Authentication failed.',
  stack: 'MongoServerError: bad auth : Authentication failed.\n' +
    '    at Connection.onMessage (/Users/mac/Desktop/oauth/node_modules/mongodb/lib/cmap/connection.js:210:30)\n' +
    '    at MessageStream.<anonymous> (/Users/mac/Desktop/oauth/node_modules/mongodb/lib/cmap/connection.js:63:60)\n' +
    '    at MessageStream.emit (node:events:527:28)\n' +
    '    at processIncomingData (/Users/mac/Desktop/oauth/node_modules/mongodb/lib/cmap/message_stream.js:132:20)\n' +
    '    at MessageStream._write (/Users/mac/Desktop/oauth/node_modules/mongodb/lib/cmap/message_stream.js:33:9)\n' +
    '    at writeOrBuffer (node:internal/streams/writable:389:12)\n' +
    '    at _write (node:internal/streams/writable:330:10)\n' +
    '    at MessageStream.Writable.write (node:internal/streams/writable:334:10)\n' +
    '    at TLSSocket.ondata (node:internal/streams/readable:754:22)\n' +
    '    at TLSSocket.emit (node:events:527:28)',
  name: 'MongoServerError'
}

### How to reproduce

connecting your mongodb server to next

### Expected behavior

session should be save to my database

**Comment by darlleylzp** [comment]
same
