### ISSUE TITLE
Sequelize adapter issue with Google Provider - 

### ISSUE THREAD

**Issue by iamdebadipti** [nextauthjs/next-auth#4894]
### Adapter type

@next-auth/sequelize-adapter

### Environment

  System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 525.61 MB / 16.00 GB
    Shell: 3.5.0 - /usr/local/bin/fish
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 103.1.40.113
    Safari: 15.5
  npmPackages:
    next: 12.2.1 => 12.2.1
    next-auth: ^4.9.0 => 4.9.0
    react: 18.2.0 => 18.2.0

### Reproduction URL

N/A

### Describe the issue

I have the following in `[...nextauth].ts`

```typescript
const sequelize = new Sequelize(process.env.DATABASE_URI)

sequelize.sync() // not in production

export default NextAuth({
    providers: [
        GoogleProvider({
            clientId: process.env.GOOGLE_CLIENT_ID,
            clientSecret: process.env.GOOGLE_CLIENT_SECRET
        })
    ],
    adapter: SequelizeAdapter(sequelize)
})

```

But, when I try to sign in with Google **for the first time**, I get following error:

```bash
...
Executing (default): INSERT INTO "accounts" ("id","type","provider","provider_account_id","access_token","expires_at","token_type","scope","id_token","user_id") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING "id","type","provider","provider_account_id","refresh_token","access_token","expires_at","token_type","scope","id_token","session_state","user_id";
[next-auth][error][adapter_error_linkAccount]
https://next-auth.js.org/errors#adapter_error_linkaccount value too long for type character varying(255) {
  message: 'value too long for type character varying(255)',
  stack: 'Error\n' +
    '    at Query.run (/Users/.../node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n' +
    '    at /Users/.../node_modules/sequelize/lib/sequelize.js:311:28\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async PostgresQueryInterface.insert (/Users/.../node_modules/sequelize/lib/dialects/abstract/query-interface.js:308:21)\n' +
    '    at async model.save (/Users/.../node_modules/sequelize/lib/model.js:2432:35)\n' +
    '    at async Function.create (/Users/.../node_modules/sequelize/lib/model.js:1344:12)\n' +
    '    at async linkAccount /Users/.../node_modules/@next-auth/sequelize-adapter/dist/index.js:100:13)',
  name: 'SequelizeDatabaseError'
}
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR]
https://next-auth.js.org/errors#oauth_callback_handler_error value too long for type character varying(255) Error
```
And, I am able to see a new user in my database in `users` table. But, when I try to sign in the 2nd time, I get no errors, but it doesn't seem to be logged in. It says the following in the browser:

```
To confirm your identity, sign in with the same account you used originally.
```

### How to reproduce

- `yarn add next-auth @next-auth/sequelize-adapter sequelize`
- add database config
- `yarn dev`
- sign in with Google Provider

### Expected behavior

The user is created and stored in the database, but user is not logged in.

**Comment by balazsorban44** [comment]
> value too long for type character varying(255)

one of the returned values does not fit into your database. This is not a NextAuth.js issue, please check the Sequelize documentation.

A quick search yielded https://github.com/sequelize/sequelize/issues/3589#issuecomment-95803643
