### ISSUE TITLE
Unable to use Prisma Adapter with AzureADProvider

### ISSUE THREAD

**Issue by ThisIsRuddy** [nextauthjs/next-auth#4907]
### Adapter type

@next-auth/prisma-adapter

### Environment

System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)       
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor     
    Memory: 35.86 GB / 37.53 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 8.5.4 - ~/.nvm/versions/node/v16.13.0/bin/npm    
  npmPackages:
    next: ^12.1.6 => 12.2.0
    next-auth: ^4.9.0 => 4.9.0
    react: ^18.1.0 => 18.2.0

  npmPackages:
    @next-auth/prisma-adapter: ^1.0.3 => 1.0.3

### Reproduction URL

https://github.com/ThisIsRuddy/na-p-azad-error

### Describe the issue

Hi,

Using the Prisma adapter with Google/Email providers is working as expected but when using the AzureADProvider there seems to be an error triggered. 

The User record is created in the db but no Account record is created. If you attempt to log in again you are prompted with the message "To confirm your identity, sign in with the same account you used originally." which makes no difference unless you delete the User record again.

It is worth mentioning the AzureADProvider is working as expected for me when not paired with the adapter.

![image](https://user-images.githubusercontent.com/1761171/178500155-8abfe45f-7ecd-4d99-b3cb-b0f3ada87c84.png)
![image](https://user-images.githubusercontent.com/1761171/178500327-de73e836-ddac-444d-a226-0554bbe48097.png)

### How to reproduce

Use a Prisma adapter with a valid AzureADProvider and attempt to sign in

### Expected behavior

User & Account equivalent records should be created

**Comment by palminha** [comment]
i think i have a similar issue here: https://github.com/nextauthjs/next-auth/issues/5454

it's causing a big problem that we cannot sign in using Azure AD

**Comment by palminha** [comment]
> `ext_expires_in` is not part of the default `Account` model in the Prisma schema.
> 
> You can add `ext_expires_in String?` to it, or remove it as recommended here: [#4893 (comment)](https://github.com/nextauthjs/next-auth/pull/4893#issuecomment-1180623709)
> 
> This comes up from time to time, so we will try to come up with a better default/better documentation.

@balazsorban44 that will not work... it must be
`ext_expires_in     Int?`

**Comment by larssbr** [comment]
@palminha Yes it should be "ext_expires_in Int?"
