### ISSUE TITLE
adapter: add kysely adapter

### ISSUE THREAD

**Issue by juliusmarminge** [nextauthjs/next-auth#4922]
### Description 📓

Hello,

[Kysely](https://github.com/koskimas/kysely) is a new minimal ORM that I have been playing around with it and really like it.

Was just wondering, would you like to have an adapter for it? It hasn’t released a 1.0 yet though so maybe it is too early?

Happy to start working on this but wanted to check in first and see what you think.

### How to reproduce ☕️

Right now you have to right your own custom adapter as documented [here](https://next-auth.js.org/tutorials/creating-a-database-adapter)

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
We welcome any adapter! Feel free to work on it :wink: And let us know if you are stuck.

**Comment by mwojtul** [comment]
@juliusmarminge I started working on a Kysely adapter and then found this post. Were you working on one too or holding off?

**Comment by juliusmarminge** [comment]
> @juliusmarminge I started working on a Kysely adapter and then found this post. Were you working on one too or holding off?

I started a while ago but didn't come very far due to time.

**Comment by lawrencecchen** [comment]
I have a working (but untested) version that implements everything.
https://gist.github.com/lawrencecchen/67c55529c1a832a787bc3758b2d1f8b6

Would love to to this repo once I figure out how to add tests.

**Comment by lawrencecchen** [comment]
I'm currently using prisma for the database schema. Currently, the adapter's table names aren't configurable, and I allow a higher order function to generate ids.

Any thoughts?

**Comment by mwojtul** [comment]
Hey @lawrencecchen, nice work.

I have a branch with a pretty similar implementation + tests and docs: https://github.com/nextauthjs/next-auth/compare/main...mwojtul:next-auth:kysely-adapter

Almost ready to PR, just need to do some cleanup and add finishing touches. If you see anything missing I'd be happy to add it.

**Comment by lawrencecchen** [comment]
@mwojtul yours looks great, will definitely switch to it!
Some questions:
- is it necessary to use pgcrypto? afaik, gen_random_uuid() is built in since postgres 1, and next-auth doesn't do passwords/hashing
https://github.com/nextauthjs/next-auth/compare/main...mwojtul:next-auth:kysely-adapter#diff-6a28b4be4cb27449fadf3d8e9ced38b8ac3bf853965550c072a732a6dae2898eR114

- do you think we could allow table names to be configurable (eg snake case)? this will affect the migrations and table typings as well

**Comment by mwojtul** [comment]
@lawrencecchen thanks!

> * is it necessary to use pgcrypto? afaik, gen_random_uuid() is built in since postgres 14, and next-auth doesn't do passwords/hashing

It does seem like it might be built in, so I'll go ahead and remove.

> * do you think we could allow table names to be configurable (eg snake case)? this will affect the migrations and table typings as well

Would [Kysely's CamelCasePlugin](https://koskimas.github.io/kysely/classes/CamelCasePlugin.html) be able to handle this, or do we still need something more configurable?

**Comment by lawrencecchen** [comment]
> Would [Kysely's CamelCasePlugin](https://koskimas.github.io/kysely/classes/CamelCasePlugin.html) be able to handle this, or do we still need something more configurable?

I think this is a good idea. We shouldn't assume that the kysely instance that the user passes in has the `CamelCasePlugin()`, but I think [`withPlugin()`](https://koskimas.github.io/kysely/classes/Kysely.html#withPlugin) does the trick.

> In my idea I had type validation for the tables too, so they had to extend the minimal fields defined in https://next-auth.js.org/adapters/models/.

We also have to override the snake case fields in the account table. Something like this should work, but I haven't tested it yet:

```ts
import { CamelCasePlugin } from "kysely";

const snakeCaseSet = new Set([
  "refresh_token",
  "access_token",
  "expires_at",
  "token_type",
  "id_token",
  "session_state",
  "oauth_token_secret",
  "oauth_token",
]);

export class NextAuthCamelCasePlugin extends CamelCasePlugin {
  protected override snakeCase(str: string): string {
    if (snakeCaseSet.has(str)) {
      return str;
    }
    return super.snakeCase(str);
  }

  protected override camelCase(str: string): string {
    if (snakeCaseSet.has(str)) {
      return str;
    }
    return super.camelCase(str);
  }
}

```

**Comment by kharann** [comment]
Hyped for this :D

**Comment by Pelps12** [comment]
Is it still in review?

**Comment by mattclosson** [comment]
any updates on this?

**Comment by martinsione** [comment]
Is anyone working on this? I built one for myself and I'd happy to contribute.

**Comment by juliusmarminge** [comment]
> Is anyone working on this? I built one for myself and I'd happy to contribute.

#5464 has working implementation + documentation. Just needs a review from maintainer

**Comment by strangekai** [comment]
@balazsorban44 please could you review this?

**Comment by pingustar** [comment]
what is the status? What is the current best solution to use next-auth with kysely?

**Comment by pingustar** [comment]
> Copy the adapter in the open PR and use in your project. I've been using it in production for a while and its working flawlessly

are you using `prisma-kysely` by any chance @juliusmarminge? 

I am getting some type errors and was wondering if you could share your prisma schema with me? Would be hugely appreciated :)

**Comment by juliusmarminge** [comment]
> I am getting some type errors and was wondering if you could share your prisma schema with me? Would be hugely appreciated :)

https://github.com/juliusmarminge/acme-corp/tree/main/packages/db

**Comment by zivtamary** [comment]
> > Copy the adapter in the open PR and use in your project. I've been using it in production for a while and its working flawlessly
> 
> are you using `prisma-kysely` by any chance @juliusmarminge?
> 
> I am getting some type errors and was wondering if you could share your prisma schema with me? Would be hugely appreciated :)

Hey, did you manage to get it working? I'm also struggling to use it with prisma-kysely

**Comment by pingustar** [comment]
> > > Copy the adapter in the open PR and use in your project. I've been using it in production for a while and its working flawlessly
> > 
> > 
> > are you using `prisma-kysely` by any chance @juliusmarminge?
> > I am getting some type errors and was wondering if you could share your prisma schema with me? Would be hugely appreciated :)
> 
> Hey @pingustar, did you manage to get it working? I'm also struggling to use it with prisma-kysely

@zivtamary not yet, ended up using prisma - let me know if you figure it out :)

**Comment by pingustar** [comment]
> > > > > Copy the adapter in the open PR and use in your project. I've been using it in production for a while and its working flawlessly
> > > > 
> > > > 
> > > > are you using `prisma-kysely` by any chance @juliusmarminge?
> > > > I am getting some type errors and was wondering if you could share your prisma schema with me? Would be hugely appreciated :)
> > > 
> > > 
> > > Hey @pingustar, did you manage to get it working? I'm also struggling to use it with prisma-kysely
> > 
> > 
> > @zivtamary not yet, ended up using prisma - let me know if you figure it out :)
> 
> I fixed some typing errors and the rest ignored with // @ts-expect-error The adapter works flawlessly though, so I don't mind :)

I saw that they have added an official adapter. I'll give this a shot over the weekend 

https://authjs.dev/reference/adapter/kysely
