### ISSUE TITLE
JWTEncodeParams maxAge type definition 

### ISSUE THREAD

**Issue by roberte777** [nextauthjs/next-auth#4924]
### Question 💬

In the type definition for JWTEncodeParams, maxAge is defined as optional. 
![image](https://user-images.githubusercontent.com/33569440/178795306-8191b1de-fc6f-482a-acf2-e6654660118b.png)

```
export interface JWTEncodeParams {
    /** The JWT payload. */
    token?: JWT;
    /** The secret used to encode the NextAuth.js issued JWT. */
    secret: string | Buffer;
    /**
     * The maximum age of the NextAuth.js issued JWT in seconds.
     * @default 30 * 24 * 30 * 60 // 30 days
     */
    maxAge?: number; // line being referred to in this issue!
}
```

Since a default value is always provided by nextauth (30 days), the maxAge field is always defined, making the question mark incorrect. Ran into this while overriding the encode function. Will fix if it is decided that I am correct. Thanks!

### How to reproduce ☕️

Look at type definition for JWTEncodeParams

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Since `maxAge` is defined internally _if_ missing, it means the user could omit the value, hence it is optional.

**Comment by balazsorban44** [comment]
Judged quickly, I think you are right, this is the params you receive when overriding the `encode` function.

You are correct. A small code snippet might have made it more clear. :+1: Feel free to open a PR!
