### ISSUE TITLE
Getting "Cannot save, given value must be instance of entity class, instead object literal is given. Or you must specify an entity target to method call."

### ISSUE THREAD

**Issue by ghoshnirmalya** [nextauthjs/next-auth#493]
**Describe the bug**
I'm using the Email provider and when I'm trying to log in using an email provided, I'm getting **Cannot save, given value must be instance of entity class, instead object literal is given. Or you must specify an entity target to method call.**

[Link to my nextauth.ts file](https://github.com/ghoshnirmalya/nextjs-hasura-boilerplate/blob/master/frontend/pages/api/auth/%5B...nextauth%5D.ts).

**To Reproduce**
Try to log in using Email on production and you'll get this error. I'm using the following:
1. Heroku for hosting Hasura app
2. Vercle for hosting Next.js app

**Expected behavior**
The user should be able to log in and no error should appear.

**Screenshots or error logs**
<img width="770" alt="Screenshot 2020-07-28 at 9 42 58 AM" src="https://user-images.githubusercontent.com/6391763/88618436-ca026000-d0b6-11ea-933a-45e212d231bc.png">

**Additional context**
Using the Email provider, if you do the following, you'll also get the error:
1. Log in using an email
2. Log out
3. Log in using the same email again

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
I can confirm I'm also seeing this issue and will need a hotfix.

**Comment by iaincollins** [comment]
Thanks for reporting this issue! This is quite a *Yikes!* bug introduced in refactoring.

**[Have released a hotfix as 3.0.1 that resolves it.](https://github.com/nextauthjs/next-auth/releases/tag/v3.0.1)**
