### ISSUE TITLE
Creating additional rows on other tables during authentication❓

### ISSUE THREAD

**Issue by soloamilkar** [nextauthjs/next-auth#4943]
### Question 💬

Hello, guys! First of all, thank you for the amazing libray. I have a question that might has been answered before. Maybe you can point me to an existing closed issue, i would appreciate it a lot. 

Basically I have this model `StripeUser` on my database, what I want is that when an `User` is created also create a `StripeUser` from within the NextAuth flow and leverage the `id` to connect `StripeUser` to `User` on `User` creation.

### How to reproduce ☕️

Im using the `PrismaAdapter`. Right now what I'm doing is check if it exists an instance of `StripeUser` on the `session` callback like:

```ts
callbacks: {
    async session({ session, user, token }) {
      try {
        await prisma.stripeUser.upsert({
          where: { userId: user.id },
          create: { user: { connect: { id: user.id } } },
          update: {},
        })
      } catch (error) {
        console.log('stripeUser nextauth error => ', error)
      }
      return { ...session, user: { ...session.user, id: user.id } }
    },
  },
```
Is this a recommended approach? Or is there a thought way of doing this? 
Thank you in advance, guys! 

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
The code looks good, but I would use the `createUser` event for this

https://next-auth.js.org/configuration/events#createuser
