### ISSUE TITLE
NextAuth with AWS Cognito

### ISSUE THREAD

**Issue by jakehova** [nextauthjs/next-auth#4954]
### Question 💬

I need to integrate NextAuth with AWS Cognito.  I have two questions, both revolving around getting access to the access token returned by cognito. I enabled debugging in my NextAuthOptions so I can see the access token returned after I log in.  I can take that access token to jwt.io and verify that it is a valid jwt with all the information that I need.  This leads me to believe that I have things setup properly.  My questions are: 

1) My server side makes calls to other API back ends.  Those API endpoints need the access token to verify the user that is calling them.  In order to do that I need to pass the cognito auth token as the authorization header for the API requests to those C# API endpoints.  That API endpoint will then verify the validity of the access token to grab user information and allow/deny accordingly.  Unfortunately, I haven't been able to figure out how to access the jwt access token on the server side. When I use this sample jwt API code: 

```
// This is an example of how to read a JSON Web Token from an API route
import { getToken } from "next-auth/jwt"

const secret = process.env.COGNITO_CLIENT_SECRET

export default async (req, res) => {
  const token = await getToken({ req, secret })
  if (token) {
    // Signed in
    console.log("JSON Web Token", JSON.stringify(token, null, 2))
  } else {
    // Not Signed in
    res.status(401)
  }
  res.end()
}
```

I get a 401 response when I run that.  req is a valid request object.  I'm not sure if secret is correct, but if it isn't, I'm not sure what else it should be.  

2) I know about the callbacks for session and jwt.  In my access token back from Cognito, I have the Cognito Groups that the user belongs to.  I want to attach those groups to the session user so that my components can adapt accordingly.  I know that session gets called first and SHOULD have the access token within token.account.  However, my token.account value is always empty.  My token is valid with the expected data (name, email, sub, iat, exp, jti).  My session is also valid with the expected data (user obj, expires).  My NextAuthOptions look like this: 

```
import NextAuth, { NextAuthOptions } from 'next-auth';
import CognitoProvider from 'next-auth/providers/cognito';

// For more information on each option (and a full list of options) go to
// https://next-auth.js.org/configuration/options
export const authOptions: NextAuthOptions = {
  providers: [
    CognitoProvider({
      clientId: process.env.COGNITO_CLIENT_ID,
      clientSecret: process.env.COGNITO_CLIENT_SECRET,
      issuer: process.env.COGNITO_ISSUER,
    }),
  ],
  debug: process.env.NODE_ENV === 'development' ? true : false,
  callbacks: {
    jwt: async ({ token, user, account, profile, isNewUser }) => {
      console.log('in jwt');
      console.log(token);
      console.log(user);
      const isSignIn = (user) ? true : false
      // Add auth_time to token on signin in
      if (isSignIn) { token.auth_time = Math.floor(Date.now() / 1000) }
      return Promise.resolve(token)
    },
    session: async ({ session, token }) => {
      console.log('in session');
      console.log(token);
      console.log(session);
      if (!session?.user || !token?.account) {
        console.log("No session.user or no token.account")
        return session;
      }
      console.log("Session.user and Token.account both exist")
      session.user["id"] = token.account["id"];
      session.accessToken = token.account["accessToken"];

      return session;
    },
  },
};

export default NextAuth(authOptions);
```
My session callback code always falls into the if saying that there is no session.user or token.account.  Is there something I'm missing in my configuration or code that I need to access these values?  Is there a recommended way to parse the access token to get the role information out of the jwt (I can see the cognito.groups property in the access token when I decode it in jwt.io but if there's a library that nextauth recommends, I would use that).

Any help would be very appreciated.  Thank you!

### How to reproduce ☕️

I went to the code sandbox link below and nothing comes up in the sandbox.  I've never used code sandbox before so I'm not sure how to proceed.  To recreate this, you can use the standard template and then copy the code that I have above (with env values for the Congito provider pointing to an actual cognito user pool).  

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
If you have set `NEXTAUTH_SECRET` correctly, you don'r need to pas `secret` to `getToken`. It should anyway not be the provider's secret, because it's not for the token that we generated.

**Comment by revmischa** [comment]
I have a need to get the access token from Cognito, as I use it to authorize my app for other AWS services like AppySync (graphql).
How can I do that?

Related: #5141
