### ISSUE TITLE
Can I use absolute callbackUrl

### ISSUE THREAD

**Issue by ramiel** [nextauthjs/next-auth#496]
*Please refer to the [documentation](https://next-auth.js.org/getting-started/introduction), the [example project](https://github.com/iaincollins/next-auth-example) and existing issues before creating a new issue.*

**Your question**
I want to pass `api/auth/signin?callbackUrl=https://otherdomain.com` but i always redirect to the next-auth home page. Is it possible to redirect where I prefer on login?

**What are you trying to do**
Start login process from an external page and go back there after login ends

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by ramiel** [comment]
I found the documentation about this, thank you

**Comment by iaincollins** [comment]
No worries, great question! 

For anyone else who has this question and is reading this issue in future, yes you can.

For security reasons, the default is to only allow redirects to the same site.

This is to prevent bad actors trying to trick users into visiting their site after following a link to yours.

You can specify a custom redirect callback to determine what URLs should be allowed:

https://next-auth.js.org/configuration/callbacks#redirect-callback
