### ISSUE TITLE
Login Link is followed by emailing scanning software and link is invalidated

### ISSUE THREAD

**Issue by joelhooks** [nextauthjs/next-auth#4965]
### Provider type

Email

### Environment

  System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 6.94 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nodenv/versions/16.16.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.11.0 - ~/.nodenv/versions/16.16.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Safari: 15.3
  npmPackages:
    next: ^12.1.6 => 12.1.6 
    next-auth: =4.2.1 => 4.2.1 
    react: 17.0.2 => 17.0.2 

### Reproduction URL

https://github.com/skillrecordings/products/blob/main/apps/testingaccessibility/src/pages/api/auth/%5B...nextauth%5D.ts

### Describe the issue

Many organizations utilize various email scanning mechanism that will actively follow links in email messages. When this occurs with a next-auth email provider email, it results in the VerificationToken being used and thus instantly invalidated for the human user that clicks the link seconds, minutes, or hours later.

The link is **never** valid for the human user no matter how many times they try.

[Microsoft 365 Advanced Threat Protection](https://www.microsoft.com/security/blog/2018/05/10/enhancing-office-365-advanced-threat-protection-with-detonation-based-heuristics-and-machine-learning/)
[Bing Preview Clicks Links](https://www.drupal.org/node/2828034)

This has been previously discussed: https://github.com/nextauthjs/next-auth/discussions/4585

some additional information on stack exchange: https://security.stackexchange.com/a/211293

The "?redirect=true" approach seems very reasonable to me, so if the `follow` param is missing, render this:

```html
<!DOCTYPE html>
<html>
  <body>
    <script> 
var queryParams = new URLSearchParams(window.location.search);
queryParams.set("follow", "true");
history.replaceState(null, null, "?"+queryParams.toString());
    </script>
  </body>
</html>
```

alternatively if we could allow them to be valid for a period of time with unlimited use that would suit our needs specifically, and might help others with tradeoffs.

If this isn't an issue and should remain in the above discussion, please feel free to close it.

### How to reproduce

This is tricky. I've got a user that this occurs to consistently, but you need to setup a [Baracuda](https://www.barracuda.com/products/email-protection) or various Microsoft tools that robo-click emails.

### Expected behavior

Human users should get verification links that work.

https://github.com/nextauthjs/next-auth/blob/2725d07eb72522b3406627bcd7fdb3ade9383456/packages/next-auth/src/core/routes/callback.ts#L199

**Comment by joelhooks** [comment]
I went ahead and did a rudimentary implementation of this: 

https://github.com/skillrecordings/products/pull/341/files#r923899518

seems kind of lame and I don't know if it works.

**Comment by balazsorban44** [comment]
Thanks, this has been raised before. A proposed solution is described here: https://github.com/nextauthjs/next-auth/issues/1840#issuecomment-848791994

What I would suggest though is probably [advanced initilzation](https://next-auth.js.org/configuration/initialization#advanced-initialization), where you can intercept the request before it goes to `NextAuth`. You could implement your own assertion on the incoming request, and if it is from a bot, you just return nothing.

**Comment by balazsorban44** [comment]
Closing as the suggestions above should solve your issue. If you think the second alternative would be a nice built-in solution, feel free to open a PR and I can help it get merged. :+1:

**Comment by joelhooks** [comment]
For anybody else that might roll through here we ended up "forking" the prisma-adapter with a bit of logic to give 90 second worth dow where the link can be clicked without deleting the token.

**Comment by ekeric13** [comment]
Can we put the simplified version in the official docs? This is pretty great and i just stumbled upon it by accident trying to debug something unrelated to magic link.

**Comment by NorbertHuethmayr** [comment]
This seems to be what you are looking for @ekeric13?
https://next-auth.js.org/tutorials/avoid-corporate-link-checking-email-provider

**Comment by shennan** [comment]
@NorbertHuethmayr This seems to be what I'm looking for. But I'm not quite sure how to implement the last (more favourable) option. I currently just use the standard configuration in `pages/api/auth/[...nextauth.tsx]`:

```tsx

export const AUTH_CONFIG: NextAuthOptions = {
  // https://next-auth.js.org/providers/overview
  providers: [
    EmailProvider(EMAIL_PROVIDER_CONFIG)
  ],
  adapter: FaunaAdapter(client),
  session: {
    strategy: 'jwt',
    maxAge: TOKEN_MAX_AGE
  },
  pages: {
    signIn: '/',
    signOut: '/',
    error: '/',
    verifyRequest: '/?message=Verify'
  }
}

// For more information on each option (and a full list of options) go to
// https://next-auth.js.org/configuration/options
export default NextAuth(AUTH_CONFIG)
```

With this sort of setup, how can I hook into the request to determine if it's `req.method === 'HEAD'` and subsequently answer with a `200`, while keeping my remaining functionality in all other scenarios? It shows me code in the link, but it seems like I would have to rewrite everything else, dumping the simple, NextAuth config that I'm currently exporting.

**Comment by NorbertHuethmayr** [comment]
Hi, 
I believe you are almost where you want to be. Instead of directly exporting the `NextAuth` call, do what I did below.

```ts
export default async function auth(req: NextApiRequest, res: NextApiResponse) {
  //https://next-auth.js.org/tutorials/avoid-corporate-link-checking-email-provider
  if (req.method === 'HEAD') {
    return res.status(200).end()
  }

  // Do whatever you want here, before the request is passed down to `NextAuth`
  return await NextAuth(req, res, AUTH_CONFIG)
}
```

**Comment by shennan** [comment]
Thanks @NorbertHuethmayr, your solution seems to work nicely.

**Comment by nvegater** [comment]
anyone knows how to implement @norberthuethmayr solution in the app router?

**Comment by matt-unosquare** [comment]
I ended up just adding a confirmation page instead. So the link is used to populate a button on screen, and then that button actually logs you in. That or emailing a passcode and having an input field on the page are probably the best options. Magic Links just arent ideal as most companies have scanners that interact with said links and can break them.

**Comment by nvegater** [comment]
I also just added a confirmation Page like @balazsorban44 suggested. Outlook advanced filters cannot be avoided: The link is always clicked at least for our customers.
