### ISSUE TITLE
How do I tell typeScript that my Session is never gonna be null

### ISSUE THREAD

**Issue by hussamkhatib** [nextauthjs/next-auth#4978]
### Question 💬

I  have followed this procedure to modify the type for session.
https://next-auth.js.org/getting-started/typescript

```ts
//types/next-auth.d.ts
import NextAuth from "next-auth";

declare module "next-auth" {
  interface Session {
    user: {
      role: Role;
      email: string;
      name?: string;
      image?: string;
      branch?: string;
      validated?: string;
    };
    expires: string;
  }
}

```

However `const session = await getSession({ req });`
 Results in this type ->`const session: Session | null`
 I have a middleware to handle if the session is null and would not like to have redundant conditional inside the api routes
 ```js
 if(!session) return  // this will silent the error in case I am expecting not null values out of the object , but it will never be true in // the first place
```

### How to reproduce ☕️

The typescript example will do
https://github.com/nextauthjs/next-auth-typescript-example

1 import { getSession } from "next-auth/react";
2  const session = await getSession({ req });
3 hover over `session`  (see `const session: Session | null`)

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by peterblazejewicz** [comment]
Isn't that by design? (works as expected)
https://next-auth.js.org/getting-started/client#getsession
So it's same scenario like with `window.localStorage.getItem(key)`.
One can use non-null assertion operator `!`:
```ts
... await getSession()!;
```

**Comment by hussamkhatib** [comment]
Yes, it is by design, I was just looking at a way to modify it as I am sure session will never be null in my api routes.
But yes, it can be null as you mentioned.
This dint work
`... await getSession()!;`
However this works 
`session!.user.email`
Thanks a lot
