### ISSUE TITLE
Vercel production build 404ing on all next-auth routes

### ISSUE THREAD

**Issue by callum-gander** [nextauthjs/next-auth#4986]
### Environment

System:
    OS: Linux 5.10 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600K
    Memory: 1.05 GB / 7.64 GB
    Container: Yes
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
  npmPackages:
    next: ^12.2.2 => 12.2.2 
    next-auth: ^4.10.1 => 4.10.1 
    react: ^17.0.2 => 17.0.2 

### Reproduction URL

N/A

### The issue
I've been experienced an issue that's completely breaking my authentication solution for my app. It's been driving me insane for two days and I'd really appreciate some help and want to see if anyone else is experiencing anything similiar. I was doing some refactoring and updating npm packages when my vercel deployments stopped being able to log in and would always lead to /api/auth/error. 
- I'm only using the credentials provider
- Login works fine when in dev but not on build + start in vercel or locally
- The error Next-auth would give is CLIENT_FETCH_ERROR which is due to NEXTAUTH_URL being incorrectly set, which it wasn't
- The error message beneath CLIENT_FETCH_ERROR was `JSON.parse: unexpected character at line 1 column 1 of the JSON data` which I have no idea what it's referring to as I can't access any logs of what this character might be
- All next routes are 404ing: _log, error, and session. They show up in the Vercel logs but give nothing beyond the fact that they're 404ing
- I was getting a similar  `JSON.parse: unexpected character at line 1 column 1 of the JSON data` when using sign out in development with the callback url being `${process.env.NEXTAUTH_URL}/` as it was returning undefined but this was solved by using NEXT_PUBLIC_NEXTAUTH_URL. This issue wasn't there before I updated to the latest version, I think I was around 4.2-4.3 before
- When logging NEXTAUTH_URL in my _app, which showed it by client side and server side, it would be correctly set server side which should imply the routes would be correctly generated from the correct canonical url which they seemed to not be due to the 404ing
- When invoking the [...nextauth] function from source in vercel, it would show the canonical url of the route being the vercel generated url, not the one I set. I know that firing the [...nextauth] function in this way shouldn't do anything but this still confused me and I'm not sure if it's a vercel issue or a next auth one

### What I think the issue is
It feels like there is some issue either within nextauth or, more likely, with vercel where the nextauth_url is not being correctly assigned and the routes aren't being properly generated. This is obviously what the error states but none of the solutions suggested in those issues seemed to work. It initially felt like I'd misconfigured something but everything is setup as it should, this issue definitely stems from an update with either nextauth or nextjs and how these updates change the way my build is generated by vercel

### My tests
I read every related error I could find* and tried tons of different solutions before I started writing all of this down and trying to figure this out once I realised this wasn't going to be a quick fix. Given that this seems to revolve around the NEXTAUTH_URL, I tried changing every possible variable that seemed to be related to this in every possible combination related to this as well as turning on and off exposing system environment variables on vercel. It's not worth elaborating on every combination but it is worth stating all the variables: 
- NEXTAUTH_URL
- NEXTAUTH_URL_INTERNAL
- VERCEL_URL
- NEXT_PUBLIC_NEXTAUTH_URL
- NEXT_PUBLIC_NEXTAUTH_URL_INTERNAL
- NEXT_PUBLIC_VERCEL_URL
I know the NEXT_PUBLIC options likely aren't needed but I still tried them. None of these resolved the above issues. 

# Related issues posts*
- https://stackoverflow.com/questions/72469610/nextauth-api-auth-always-return-404-on-vercel-deployment-but-work-locally
- https://stackoverflow.com/questions/67715077/next-auth-receiving-404-after-login-attempt-in-deployed-vercel-application
- https://stackoverflow.com/questions/70515472/next-auth-receiving-404-error-after-login-attempt-via-github-in-deployed-vercel?noredirect=1
- https://github.com/nextauthjs/next-auth/discussions/4429
- https://github.com/nextauthjs/next-auth/issues/4507
- https://github.com/nextauthjs/next-auth/issues/4425
- https://github.com/nextauthjs/next-auth/issues/2668
- Not sure if this is related https://github.com/nextauthjs/next-auth/issues/4363
- Potentially this too https://github.com/nextauthjs/next-auth/issues/3419

### How to reproduce

I can't give clear steps to reproduce as my repo is private and making a reproducable repo isn't something I can do at the moment. What I can say is that this seems to be related to the versions given in the environment section, the credentials provider, vercel and the NEXTAUTH_URL

### Expected behavior

Routes shouldn't 404 and login and redirect should occur without leading to /api/auth/error.

This is a critical issue for me and I'm open to contributing if it means this can be resolved faster if it does turn out to be an issue with nextauth

**Comment by balazsorban44** [comment]
`NEXTAUTH_URL` isn't needed on Vercel as documented. You can start by dropping that, in case you misconfigured it.

https://next-auth.js.org/deployment#vercel

Unfortunately we cannot help without a reproduction, please take the time to create one. We have a deployed example on Vercel that works fine, so this issue sounds like a project-specific one. See https://next-auth-example.vercel.app

**Comment by callum-gander** [comment]
Dropping `NEXTAUTH_URL` and everything else was tried and didn't work. Tried again just now and it's still not working and producing the same errors as before. I'll try and reproduce it in a separate repo and post it here

**Comment by balazsorban44** [comment]
(Also make sure you re-deploy after removing that env. variable).

Usually, a reproduction is required for us to be able to help, as stated in the issue template, so thanks. :+1:

**Comment by callum-gander** [comment]
Sorry about all this, it _was_ a misconfiguration issue. Basically, we had a /api folder in our root dir that had just been there since we started our project despite never using it (we started with a very old next template). This never caused any problems until we updated our packages and suddenly vercel decided that it wouldn't run [...nextauth] while it was there and all the functions 404'd because they weren't generating, despite the fact they always had before. There were no logs or errors indicating that the issue was due to this. As soon as the folder was deleted everything worked. Again, sorry for wasting your time, hopefully someone else will see this and prevent them from wasting your time too :sweat_smile:

**Comment by ElisPerez** [comment]
> Sorry about all this, it _was_ a misconfiguration issue. Basically, we had a /api folder in our root dir that had just been there since we started our project despite never using it (we started with a very old next template). This never caused any problems until we updated our packages and suddenly vercel decided that it wouldn't run [...nextauth] while it was there and all the functions 404'd because they weren't generating, despite the fact they always had before. There were no logs or errors indicating that the issue was due to this. As soon as the folder was deleted everything worked. Again, sorry for wasting your time, hopefully someone else will see this and prevent them from wasting your time too sweat_smile

Thanks!! 🤯🤩🌟🌟🌟🌟🌟

**Comment by rzarroca-metary** [comment]
This saved my life (or at least 2 days as @callum-gander xP).

Thanks for sharing!!

**Comment by Iftee97** [comment]
> This saved my life (or at least 2 days as @callum-gander xP).
> 
> Thanks for sharing!!

how? what do i have to do?

**Comment by dschoon** [comment]
For me, the issue was that I had a rewrite catch-all and the `/pages/api` was no longer taking precedence. I fixed it by adding a `/api/:path*` check to my Next config...
```
  async rewrites() {
    return [
      {
        source: `/api/:path*`,
        destination: `/api/:path*`,
      },
      {
        source: `/:path*`,
        destination: `${PLATFORM_URL}/:path*`,
      },
    ];
  },
```

**Comment by Vitos8** [comment]
> For me, the issue was that I had a rewrite catch-all and the `/pages/api` was no longer taking precedence. I fixed it by adding a `/api/:path*` check to my Next config...
> 
> ```
>   async rewrites() {
>     return [
>       {
>         source: `/api/:path*`,
>         destination: `/api/:path*`,
>       },
>       {
>         source: `/:path*`,
>         destination: `${PLATFORM_URL}/:path*`,
>       },
>     ];
>   },
> ```

What is PLATFORM_URL here?

**Comment by AurelianSpodarec** [comment]
So where exactly is this meant to be located in NextJS 13.2+?

I've tried inside the app with a api/auth/[...nextauth].ts
I've tried outside the app with that
I've tried to put 'pages' before the API as well.

Nothing seem to work.

**Comment by hanishtharwani123** [comment]
yes...same with me it's not working

**Comment by netgfx** [comment]
I'm having pretty much the same issue, when I switched to next-auth github actions stopped working with error of invalid URL:
```
Error occurred prerendering page "/login". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:387:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:641:5)
    at parseUrl (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/.next/server/chunks/8107.js:1370:16)
    at Object.63370 (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/.next/server/chunks/8107.js:621:34)
    at __webpack_require__ (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/.next/server/webpack-runtime.js:25:43)
    at Module.3512 (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/.next/server/app/login/page.js:291:73)
    at __webpack_require__ (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/.next/server/webpack-runtime.js:25:43)
    at O (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:23:142)
    at ia (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:27:301)
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:387:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:641:5)
    at parseUrl (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/.next/server/chunks/8107.js:1370:16)
    at Object.63370 (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/.next/server/chunks/8107.js:621:34)
    at __webpack_require__ (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/.next/server/webpack-runtime.js:25:43)
    at Module.45829 (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/.next/server/chunks/3837.js:69:13)
    at __webpack_require__ (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/.next/server/webpack-runtime.js:25:43)
    at O (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:23:142)
    at da (/home/runner/work/frontend-app/frontend-app/relivable-admin/relivable-admin/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:20:89) {
  input: '',
  code: 'ERR_INVALID_URL'
}
```
for all routes

I have a `pages/api` as well is this a problem with next-auth? I have double checked all env variables and they are present and correct. I removed middleware `withAuth` and have done pretty much everything I found in order to fix this.
Even tried the solutions here, but with no results...

**Comment by jackkingham-au** [comment]
For anyone else that stumbles across this;

You cannot have a directory in your project ROOT, named `api` or it will clash with Next Auth, causing the behaviour described above.

**Comment by tfarhan00** [comment]
> For anyone else that stumbles across this;
> 
> You CANNOT have a directory in your project ROOT, named `api` or it will clash with Next Auth, causing the behaviour described above.

Thanks a lot dude, you just saved my app with thousands of users.

**Comment by yuggysaputra7** [comment]
> For anyone else that stumbles across this;
> 
> You CANNOT have a directory in your project ROOT, named `api` or it will clash with Next Auth, causing the behaviour described above.

what's the solution? If you rename the API folder, you get an error

**Comment by yuggysaputra7** [comment]
> > For anyone else that stumbles across this;
> > You CANNOT have a directory in your project ROOT, named `api` or it will clash with Next Auth, causing the behaviour described above.
> 
> Thanks a lot dude, you just saved my app with thousands of users.

what's the solution? If you rename the API folder, you get an error

**Comment by mwakulinski** [comment]
I think I found a solution. All i needed to to is rename my folder in app and rewrite it in vercel.json. So I ended up with:

```
├── api
│   └── hello.js
├── app
│   ├── actions.ts
│   ├── api
│   │   ├── routes ---> [provide name here]
│   │   │   └── [...nextauth]
│   │   │       └── route.ts
```

and then in vercel.json add
```
{
"rewrites": [
    {
      "source": "/api/auth/:path*",
      "destination": "/routes/auth/:path*" //change "routes" to your liking
    }]
}
```

**Comment by DWolf00** [comment]
I believe I've identified a root cause related to Next.js deployments on Vercel when using the default template and having an /api folder in the root directory.

If you navigate to {yourdomain}/api and encounter an error, this might be the culprit. To troubleshoot, consider renaming your /api folder to something else.

![Screenshot 2024-04-26 162743](https://github.com/nextauthjs/next-auth/assets/153088330/9f36cbeb-4d48-4c4c-bdf9-c2b0e168d432)

**Comment by Thornus** [comment]
A `/api` is missing in the answer above.

The `vercel.json` should be

```
{
"rewrites": [
    {
      "source": "/api/auth/:path*",
      "destination": "/api/routes/auth/:path*" //change "routes" to your liking
    }]
}
```

Thank you a lot though, it finally solved it for me!

**Comment by sKopheK** [comment]
i have this behavior time to time when running nextjs app in `dev` mode. when i restart `dev` script and it's fine even w/o removing anything. started to happen after upgrading to next16 and enabling turbopack. no `api` directory in my project whatsoever
