### ISSUE TITLE
What is the behavior of SignOut and SignIn methods?

### ISSUE THREAD

**Issue by mablds** [nextauthjs/next-auth#5005]
### Question 💬

Hello everyone! 

We are having a behavior that we weren't expecting. After use the SignOut method, we can check that the Keycloak Session is destroyed. But when we call the SignIn method again, somehow it recovers the session without asking for my credentials. 

This is the default behavior? Can we change it?

### How to reproduce ☕️

.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by mablds** [comment]
@loraineeamaral

**Comment by balazsorban44** [comment]
NextAuth.js's session is not the same as your identity provider's. You are asking about is called federated logout which isn't built-in currently, but can be achieved with OIDC providers such as Keycloak in user land. Read more at #836

**Comment by balazsorban44** [comment]
If security is not the concern you just want to re-require login, you can use the login prompt in the signIn method.

See
https://www.oauth.com/oauth2-servers/authorization/requiring-user-login/

https://next-auth.js.org/getting-started/client#additional-parameters
