### ISSUE TITLE
Example renders protected page twice if opened directly

### ISSUE THREAD

**Issue by shuntksh** [nextauthjs/next-auth#5014]
### Environment

Need to install the following packages:
  envinfo
Ok to proceed? (y) y

  System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 78.73 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.9.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Safari: 15.5
  npmPackages:
    next: latest => 12.2.3
    next-auth: latest => 4.10.2
    react: ^18.2.0 => 18.2.0

### Reproduction URL

https://next-auth-example.vercel.app/protected

### Describe the issue

When a protected page that uses `useSession` is opened via page navigation, ie clicking links, it renders correctly.

1) Open `localhost:3000/protected` by clicking a link from the Home, renders fine
<img width="779" alt="image" src="https://user-images.githubusercontent.com/19877680/180654427-a0f02b05-77b8-4799-ad9c-53a287b15cf6.png">

2) Open `localhost:3000/protected` directly by reloading or pasting URL into a new tab, renders duplicate of page contents before the actual page contents:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/19877680/180654505-9a93acf9-5fb4-4784-a6da-7084c6c153f4.png">

Run a debugger on client side confirms that whenever `useSession()` is called on fresh mount, it paints pages' HTML on the server side then paint again on the client side without replacing the HTML as if it React loses ref to DOMs that rendered on the server side.

3-1) At DOMContentLoad event, it loads the first half which should not be rendered:

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/19877680/180654720-57e45f43-a018-4f1f-9d44-550e78469434.png">

3-2) Then React takes over and paint the reset
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/19877680/180654736-0b3f23f0-71b2-48cc-b938-924e93f72197.png">

If you remove `useSession` from the page, page renders just fine. And run debugger on the server side confirms that it resulted in call to ReactDOM.RenderHTML, albeit not sure if it is intended.

### How to reproduce

1) Clone example repo and install dependencies and start dev server

```
git clone https://github.com/nextauthjs/next-auth-example.git
cd next-auth-example
npm install
npm run dev
```

2) Open [`localhost:3000/protected`](https://localhost3000/protected) in a browser window. Or open `http://localhost:3000` and click `protected` then reload the page.

* It reproduces on production build too (`npm run build && npm run start`)

### Expected behavior

Orphaned server side rendering should not happen.

**Comment by balazsorban44** [comment]
That's super strange, maybe some hydration issues. Thanks for reporting.

**Comment by balazsorban44** [comment]
This line is not ideal anyway https://github.com/nextauthjs/next-auth/blob/aedabc8d3f35e7b2b696586113c2a233ff6878c1/apps/example-nextjs/pages/protected.tsx#L24 so maybe we should resolve this by tweaking that page

**Comment by shuntksh** [comment]
@balazsorban44, thanks! That seems to be the culprit. Commenting out the line you mentioned solved the issue. Indeed weird and not sure why it resulted in rendering content on the server side though...

**Comment by balazsorban44** [comment]
This comes from prerendering at build time when window is unavailable.

**Comment by shuntksh** [comment]
Thanks @balazsorban44, it is very interesting. So theory is that server renders the content but then client immediately renders "null" while the session is loading which is different from the DOM that is returned by the server causing dereferencing and subsequent rendering to be treated as a fresh rendering resulting in duplicate content.

I am going to close this issue as the behavior seems to be unrelated to NextAuth. Thanks again @balazsorban44 for the quick look!

**Comment by balazsorban44** [comment]
We should still fix the example though, feel free to open a PR.

cc @ThangHuuVu

**Comment by shuntksh** [comment]
If I remove the "return null" line as you suggested, it results in content flashing where it renders the "Access Denied" page that the server returns first then the client renders the actual contents if a session exists. I presume the original 'if loading' clause is added to prevent specific to this behavior.

What would be the recommended implementation? I believe this is what `unstable_getServerSession` on getServerSideProps is for.

**Comment by shuntksh** [comment]
@balazsorban44 - Thanks for the suggestion. Just opened a PR to fix the behavior.
