### ISSUE TITLE
Session not correctly passed through getServerSideProps

### ISSUE THREAD

**Issue by Axiol** [nextauthjs/next-auth#5020]
### Question 💬

I'm trying to implement server side authentication following [this doc page](https://next-auth.js.org/configuration/nextjs). It all goes well until the `unstable_getServerSession` in `getServerSideProps`. If I log the session  there, I correctly have somehting

```
{
  user: {
    ...
  },
  ...
}
```

But, once it's return through the props and logged in the page component, the value shifts to `undefined`. No error in view.

### How to reproduce ☕️

[This branch](https://github.com/Axiol/ampharos/tree/feat/server-side-auth) has everything. It's in `pages/index.tsx`.

Fill the `.env` and run `prisma generate && prisma migrate deploy && next dev`

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
You never pass `session` to your page component since you are destructuring it off of `pageProps` here:

https://github.com/Axiol/ampharos/blob/e5aedd65f4e982f547e56c85f2cea7459ff89edf/pages/_app.tsx#L6

To get the session anywhere, you can just use `useSession`
