### ISSUE TITLE
Adding "paths" and "baseUrl" to tsconfig.json breaks module augmentations

### ISSUE THREAD

**Issue by nexxeln** [nextauthjs/next-auth#5024]
### Question 💬

We just had this [issue](https://github.com/t3-oss/create-t3-app/issues/254) in `create-t3-app`,It seems like the declared next-auth.d.ts is overriding the initial next-auth types instead of augmenting them.

We even tried declaring the the types from `next-auth/core/types` but doesn't seem to work still. 

Note that this problem only occurs when we use path aliases.

### How to reproduce ☕️

**To Reproduce**

1. `npx create-t3-app@next`
2. Select all packages
3. Set up path aliases like so ![path aliases](https://user-images.githubusercontent.com/3504472/180913329-1cbb182d-0161-491d-9e79-5b6c9603fcd0.png)
4. See `src/pages/api/auth/[...nextauth].ts` file

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by nexxeln** [comment]
Update: Apparently moving the `next-auth.d.ts` file to a subfolder fixes it.

**Comment by balazsorban44** [comment]
AFAIK, TypeScript does not concern itself where you declare a Module Augmentation in your project, as long as the file is included in your tsconfig's `includes` array.

**Comment by riolly** [comment]
> Update: Apparently moving the `next-auth.d.ts` file to a subfolder fixes it.
> 
> Is there a better solution?

Yeah, I do the same thing. Is there any better solution?
