### ISSUE TITLE
Add a example for callback url in docs for all providers

### ISSUE THREAD

**Issue by TakshakRamteke** [nextauthjs/next-auth#5031]
### What is the improvement or update you wish to see?

I recently noticed this while working with the auth0 provider that 

Only the docs for google provider tell us about what callback / allowed redirect to use    

while it is something pretty simple and is mentioned pretty early in the docs 

In my humble opinion I believe that it'd be so much more usefull and convenient if we could list them out on the docs for each provider

not only that but if we do this it'll make the docs look a lot more consistent as well

With all due respect, Please let me know you're thought's 
I'd be really happy to contribute this one  

### Is there any context that might help us understand?

E.g. 

Here on the doc for google provider 
in the configuration section we list what callback's to use for the allowed redirect url's

![Screenshot 2022-07-26 at 20-29-07 Google NextAuth js](https://user-images.githubusercontent.com/44837950/181041702-9c3a7eb3-bf65-4822-8010-aa3530c15d71.png)

Where as on the docs for auth0, gitlab , etc.. we didn't mention it at all

![Screenshot 2022-07-26 at 20-29-28 Auth0 NextAuth js](https://user-images.githubusercontent.com/44837950/181041716-1059febc-5a99-4f5b-978f-a0d9d3e58c09.png)

![Screenshot 2022-07-26 at 20-51-23 GitLab NextAuth js](https://user-images.githubusercontent.com/44837950/181045590-0e0b8ccd-f694-4f0d-b731-ebb7b601034d.png)

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/providers/google

**Comment by dryhurst** [comment]
@TakshakRamteke feel free to open a PR for these changes.

**Comment by joaosantos99** [comment]
If none is doing i can take this issue

**Comment by shudanshus198** [comment]
I would like to contribute on this.

**Comment by ThangHuuVu** [comment]
Go for it @shudanshus198! 🙌
