### ISSUE TITLE
Use consistent error type between doc, logger and error class

### ISSUE THREAD

**Issue by sato11** [nextauthjs/next-auth#5045]
### What is the improvement or update you wish to see?

There is an inconsistent use of two of the error codes, `OAUTH_CALLBACK_ERROR` and `CALLBACK_OAUTH_ERROR`, of which only the latter is documented as errors: https://next-auth.js.org/errors.

In https://github.com/nextauthjs/next-auth/pull/5027#issuecomment-1197053995, @ThangHuuVu has suggested that we should:

1. merge docs of the two types mentioned above,
2. rename them more generic something like `CALLBACK_ERROR`, and
3. keep from the same error logged twice.

As a result we can merit from getting rid of subtly discrepant errors, both from docs page and from the source.

In the PR mentioned above, I had attempted to use only `CALLBACK_OAUTH_ERROR`, but after that I found there is the `OAuthCallbackError` class. Consequently I'm thinking to use `OAUTH_CALLBACK_ERROR` so that documentation better represents the implementation.

### Is there any context that might help us understand?

After receiving a comment in #5027 I've researched a bit and found some things that might affect the way we sort our docs.

So currently we have in the errors page a headline that says:

> oauth_callback_error expected 200 OK with body but no body was returned

while in fact it seems this `expected 200 OK with body but no body was returned` message never happens in callback phase, but in discovery phase. That is, openid-client emits this message when (and apparently only when) `/.well-known/openid-configuration` returns no body. cf. https://github.com/panva/node-openid-client/blob/v5.1.8/lib/helpers/process_response.js#L59

In next-auth's side, things described below in order happens

1. triggers issuer discovery
2. fails to get authorization url
4. logs `SIGNIN_OAUTH_ERROR` with`expected 200 OK with body but no body was returned`

So I believe the original content which attributes this error message to `OAUTH_CALLBACK_ERROR` was not true. I guess associating it with `SIGNIN_OAUTH_ERROR` can be of help and so I'm planning to create a PR.

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/errors

**Comment by ThangHuuVu** [comment]
Thanks for the detailed issue reporting, @sato11! 🙌
> rename them more generic something like CALLBACK_ERROR, and

To be clear, here I suggested throwing `CALLBACK_ERROR` instead of `OAUTH_CALLBACK_ERROR` in `callback.ts` line 196 because at that point we can tell for sure it's no longer an OAuth error 🤔  
https://github.com/nextauthjs/next-auth/blob/a21db8950f7a0c3e568faf69cb236f21e65fa42f/packages/next-auth/src/core/routes/callback.ts#L196

**Comment by sato11** [comment]
Thanks for the info @ThangHuuVu! I've been unaware of it, but yes, I guess that makes sense. I'll be patching it as well in #5046 👍

**Comment by sato11** [comment]
Well, let me pause a bit. Do you even want me to include that in #5046 as well actually, or should that be treated as a different issue? I bet it's kind to add it in the error page as well, since `CALLBACK_ERROR` is not documented in it (which is quite natural). However, I'm not sure what to describe, since I'm still not be able to find the condition on which it might be causing `CALLBACK_ERROR`. In other words, logically I understand your idea is true, while practically I do not understand what information can be of help to those who might be facing `CALLBACK_ERROR`. Any thoughts?

**Comment by ThangHuuVu** [comment]
@sato11 Let's keep it in a separate issue for better clarity 🙌
