### ISSUE TITLE
Secure authentication page not working

### ISSUE THREAD

**Issue by gleysonabreu** [nextauthjs/next-auth#5047]
### Question 💬

After adding the Prisma Adapter in the application for a test, the system started to suffer with redirects: "too many redirects in the browser".

### How to reproduce ☕️

Code in index.tsx(login page):
```
export const getServerSideProps: GetServerSideProps = async (context: GetServerSidePropsContext) => {
  const session = await getSession(context);

  if (session) {
    return {
      redirect: {
        destination: '/account',
        permanent: false,
      }
    }
  }

  return {
    props: {}
  }
}
```

middleware:
```
import { withAuth } from "next-auth/middleware";

export default withAuth({
  pages: {
    signIn: '/',
    signOut: '/auth/signout',
    error: '/auth/error'
  },

});

export const config = { matcher: ["/account",] }
```

authOptions:
```
import NextAuth, { NextAuthOptions } from 'next-auth';
import TwitchProvider from 'next-auth/providers/twitch';
import GithubProvider from 'next-auth/providers/github';
import { PrismaAdapter } from '@next-auth/prisma-adapter';
import { prisma } from '../../../lib/prisma';

export const authOptions: NextAuthOptions = {
  providers: [
    TwitchProvider({
      clientId: process.env.NEXT_PUBLIC_TWITCH_ID as string,
      clientSecret: process.env.NEXT_PUBLIC_TWITCH_SECRET as string,
    }),
    GithubProvider({
      clientId: process.env.NEXT_PUBLIC_GITHUB_ID as string,
      clientSecret: process.env.NEXT_PUBLIC_GITHUB_SECRET as string
    }),
  ],
  adapter: PrismaAdapter(prisma),
}
export default NextAuth(authOptions);
```
So I found [this issue](https://github.com/nextauthjs/next-auth/issues/4848#issuecomment-1192811257) and downloaded the experimental version and the redirects stopped but pages that unauthenticated users cannot access, they can access.

Matcher its not working??

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Your middleware and nextauth config should have the same custom pages config, otherwise NextAuth.js doesn't know where to redirect in your middleware. We are adding a better warning/detection for this in #5000

**Comment by gleysonabreu** [comment]
> Your middleware and NextAuth config should have the same custom pages config, otherwise NextAuth.js doesn't know where to redirect in your middleware. We are adding a better warning/detection for this in #5000

still not working here.
everything seems to work normally without the prisma adapter.
I downloaded the example given from the next-auth website and added the prisma adapter and it didn't work properly either.
Could you download the template and put the prisma adapter and see if the middleware works?
