### ISSUE TITLE
Twitter provider getting error code 415: Callback URL not approved for this client application

### ISSUE THREAD

**Issue by jonidelv** [nextauthjs/next-auth#5056]
### Question 💬

When using the Twitter provider
```js
    TwitterProvider({
      clientId: process.env.TWITTER_API_KEY,
      clientSecret: process.env.TWITTER_API_SECRET,
    }),
```
I get this error

<img width="1479" alt="Screen Shot 2022-07-28 at 13 37 25" src="https://user-images.githubusercontent.com/11802102/182039241-03a2f554-1568-4e30-a6c8-6dafa8a1824c.png">

This is my Twitter app config options
<img width="398" alt="Screen Shot 2022-07-31 at 12 59 44" src="https://user-images.githubusercontent.com/11802102/182039332-840149a7-cf9d-48c2-b964-2b84eb0e1c9d.png">

My base URL is `https://guardo.io` login page `https://guardo.io/login` and callback URL `https://guardo.io/dashboard`

### How to reproduce ☕️

Just create any Twitter login.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
The callback url that is expected to be set is `http://localhost:3000/api/auth/callback/twitter`
