### ISSUE TITLE
Can't resolve '@next-auth/prisma-adapter' when cloning repository

### ISSUE THREAD

**Issue by Qetzing** [nextauthjs/next-auth#5070]
### Environment

```
  System:dev:next exited with code 0
    OS: Windows 10 10.0.19043 j
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 19.82 GB / 31.93 GBnext-auth\apps\dev>npx envinfo --system --binaries --browsers --npmPackages "next,react,next-auth"
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.77)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    next: 12.2.0 => 12.2.0
    react: ^18 => 18.2.0
```

### Reproduction URL

https://github.com/nextauthjs/next-auth/blob/main/apps/dev/pages/api/auth/%5B...nextauth%5D.ts

### Describe the issue

I am trying to fix another issue in next-auth, so I wanted to clone this repository to my local computer. I followed the  steps shown here [https://github.com/nextauthjs/next-auth/blob/main/CONTRIBUTING.md](https://github.com/nextauthjs/next-auth/blob/main/CONTRIBUTING.md) precisely, however I keep getting the same error:

```
[0] Module not found: Can't resolve '@next-auth/prisma-adapter'
[0]   39 | // Adapters
[0]   40 | import { PrismaClient } from "@prisma/client"
[0] > 41 | import { PrismaAdapter } from "@next-auth/prisma-adapter"
[0]   42 | import { Client as FaunaClient } from "faunadb"
[0]   43 | import { FaunaAdapter } from "@next-auth/fauna-adapter"
[0]   44 | import { TypeORMLegacyAdapter } from "@next-auth/typeorm-legacy-adapter"
```

Because of that, I cannot use any part of the website. I have checked wether the needed package is indeed present, and yes, it is. I can find the required package in `apps/dev/node_modules/@next-auth/prisma-adapter`. I can even find the needed function (`/src/index.ts`), however my IDE is showing me errors in this file as well. 

I am confused as to why some dependencies are not found and tried re-installing the project several times. However that didn't work for me.

### How to reproduce

I followed the same steps as explained here: [https://github.com/nextauthjs/next-auth/blob/main/CONTRIBUTING.md](https://github.com/nextauthjs/next-auth/blob/main/CONTRIBUTING.md) 

1. Clone the repo
```
git clone git@github.com:nextauthjs/next-auth.git
cd next-auth
```

2. Install packages
```
pnpm install
```

3. Populate `.env.local`
```
cd apps/dev
copy .env.local.example .env.local
```

4. Start the application
```
pnpm dev
```

### Expected behavior

The website should run without any other configuration than the one described in the guide ([https://github.com/nextauthjs/next-auth/blob/main/CONTRIBUTING.md](https://github.com/nextauthjs/next-auth/blob/main/CONTRIBUTING.md)).

Instead, the website doesn't run and can't resolve `@next-auth/prisma-adapter`

**Comment by balazsorban44** [comment]
you'll need to build the Prisma package first inside `packages/adapter-prisma`. We currently don't have watch mode set up for adapters in development.
