### ISSUE TITLE
Specify `pnpm build` in CONTRIBUTING.md?

### ISSUE THREAD

**Issue by sato11** [nextauthjs/next-auth#5078]
### What is the improvement or update you wish to see?

I'd like to propose that we specify `pnpm build` step in CONTRIBUTING.md.

### Is there any context that might help us understand?

In the current version of the doc (v4.10.3, to be precise), it tells that `pnpm dev` starts the server and makes `localhost:3000` available right away. However, `/api/auth/[...nextauth]` fails to compile on access, saying what I attach below:

```
./pages/api/auth/[...nextauth].ts:41:0
Module not found: Can't resolve '@next-auth/prisma-adapter'
  39 | // Adapters
  40 | import { PrismaClient } from "@prisma/client"
> 41 | import { PrismaAdapter } from "@next-auth/prisma-adapter"
  42 | import { Client as FaunaClient } from "faunadb"
  43 | import { FaunaAdapter } from "@next-auth/fauna-adapter"
  44 | import { TypeORMLegacyAdapter } from "@next-auth/typeorm-legacy-adapter"

https://nextjs.org/docs/messages/module-not-found
```

Just running `pnpm build` fixed it for me (which I hope is what you are expecting), but the answer wasn't pretty easy for me to find. Partly that's only because I'm not used to using pnpm and the overall mono-repo concept of the "workspace", but I'm sure just adding one line in local setup section can be a great help to those who wish to try out the latest version of this project.

So I'm glad to see the change and would like to know what you think of it. Let me know if I'm missing or misunderstanding anything 🙂 

### Does the docs page already exist? Please link to it.

https://github.com/nextauthjs/next-auth/blob/next-auth%40v4.10.3/CONTRIBUTING.md

**Comment by balazsorban44** [comment]
Thanks, but there is already a PR in the works for this: #4951 Ideally we would like to rebuild any packages in development, instead of relying on `pnpm build` on each change. As this is not related to the usage of the package, there is no need to open an issue about it.
