### ISSUE TITLE
jwt callback documentation missing info, or possible bug?

### ISSUE THREAD

**Issue by jacargentina** [nextauthjs/next-auth#508]
`https://next-auth.js.org/configuration/callbacks#jwt-callback`

With latest version, when trying to login with invalid credentials in a custom credentials provider, and doing this, as documented:

```
authorize: async () {
   // invalid credentials, return error message
    return Promise.resolve(new Error(message));
}
```

It seems the jwt callback is being called with this arguments:

```
token = { name: 'Error', email: undefined, picture: undefined }
user = Error: Identifier or password invalid. (Error Object)
account = ...
user = Error: Identifier or password invalid. (Error Object)
isNewUser = false
```

There is no documentation about that; i was getting an error `TypeError: Cannot read property 'name' of undefined`because i was following the examples:

```
jwt: async (token, user, account, profile, isNewUser) => {
    const isSignIn = (user) ? true : false
    if (isSignIn) { token.userRole = user.role.name; }. //fails here, as user is NOT the user, but an ERROR!
    return Promise.resolve(token)
  }
```

So it is a bug, or a missing documentation?
 Cheers!

**Comment by jacargentina** [comment]
I've found my error, i was doing a resolve when i needed a reject

´´´js
authorize: async () {
   // invalid credentials, return error message
    return Promise.reject(new Error(message));
}
´´´

Sorry

**Comment by iaincollins** [comment]
No worries! Thank you for following up! I appreciate this stuff is easier to trip over than it should be as the error handling for when things are wrong isn't always super helpful (making typos vexing).
