### ISSUE TITLE
Jwt callback with Google OAuth doesn't return isNewUser

### ISSUE THREAD

**Issue by SharadKumar** [nextauthjs/next-auth#509]
**Describe the bug**
Jwt with Google OAuth doesn't return isNewUser. I have setup my options correctly and signIn is working as expected. Callbacks are working, except the value for isNewUser is `undefined` when tested in Incognito mode on Chrome.

**To Reproduce**
Run incognito on Chrome.

```js
import NextAuth from 'next-auth'
import Providers from 'next-auth/providers'

const options = {
  // Configure one or more authentication providers
  providers: [
    Providers.Google({
      clientId: process.env.GOOGLE_ID,
      clientSecret: process.env.GOOGLE_SECRET
    }),
  ],
  secret: process.env.SECRET,

  session: {
    jwt: true,
  },

  jwt: {
    // A secret to use for key generation (you should set this explicitly)
    secret: 'SomeSecret',
  },
  pages: {
    // signIn: '/signin',  // Displays signin buttons
    // signOut: '/api/auth/signout', // Displays form with sign out button
    // error: '/api/auth/error', // Error code passed in query string as ?error=
    // verifyRequest: '/api/auth/verify-request', // Used for check email page
    newUser: '/account/signup' // If set, new users will be directed here on first sign in
  },
  callbacks: {
    // jwt: async (token, user, account, profile, isNewUser) => { return Promise.resolve(token) }
    jwt: async (token, user, account, profile, isNewUser) => {
      console.log('jwt', token, user, account, profile, isNewUser)
      const isSignIn = (user) ? true : false
      // Add auth_time to token on signin in
      if (isSignIn) { token.custom = 'abc' }
      return Promise.resolve(token)
    }
  },
  events: {},
}

export default (req, res) => NextAuth(req, res, options)
```

**Expected behavior**
I should get true or false for `isNewUser`.

**Screenshots or error logs**
If applicable, add screenshots or error logs to help explain the problem.

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by SharadKumar** [comment]
The `pages.newUser` is also not redirecting as a result. I am running `v3.0.1`.

**Comment by SharadKumar** [comment]
Further, I notice that documentation states different signature for callbacks:

https://next-auth.js.org/configuration/options#callbacks
```js
callbacks: {
  signIn: async (profile, account, metadata) => { },
  redirect: async (url, baseUrl) => { },
  session: async (session, token) => { },
  jwt: async (token, profile) => => { }
}
```
while...
https://next-auth.js.org/configuration/callbacks
```js
...
  callbacks: {
    signIn: async (user, account, profile) => {
      return Promise.resolve(true)
    },
    redirect: async (url, baseUrl) => {
      return Promise.resolve(baseUrl)
    },
    session: async (session, user) => {
      return Promise.resolve(session)
    },
    jwt: async (token, user, account, profile, isNewUser) => {
      return Promise.resolve(token)
    }
...
}
```

**Comment by iaincollins** [comment]
> Further, I notice that documentation states different signature for callbacks:

Thanks! The options documentation was outdated and the callbacks page was more up to date. I've updated the options documentation to match.

**Comment by iaincollins** [comment]
> Jwt with Google OAuth doesn't return isNewUser

Regarding the primary focus of the ticket (sorry, took longer to get to) are you using a database to persist users?

If using NextAuth.js without a database then the `isNewUser` value is unknown - by design, because generally we can't tell if they have signed in before without a database.

I THINK this is mentioned in SOME places in the documentation but it maybe needs to be spelled out in more places.

**Comment by SharadKumar** [comment]
Thanks @iaincollins, maybe I missed but didn't find this anywhere in documentation. Or it is not very explicit. Perhaps it should be stated next to the property in the options.
