### ISSUE TITLE
Config for setting up JWT with Hasura GraphQL service

### ISSUE THREAD

**Issue by SharadKumar** [nextauthjs/next-auth#510]
I have next-auth up and running locally with one provider, using JWT (without database session). 
Next, I want to use the Jwt with Hasura for supported authentication and authorization.

Here is a step by step guide:
https://hasura.io/docs/1.0/graphql/manual/auth/authentication/jwt.html

**Your question**
I am trying to figure out `next-auth` config for my `jwt-secret`:

```json
{
  "type": <optional-type-of-key>,
  "key": <optional-key-as-string>,
  "jwk_url": <optional-url-to-refresh-jwks>,
  "claims_namespace": <optional-key-name-in-claims>,
  "claims_namespace_path": <optional-json-path-to-the-claims>,
  "claims_format": <json|stringified_json>,
  "audience": <optional-string-or-list-of-strings-to-verify-audience>,
  "issuer": <optional-string-to-verify-issuer>
}
```

Instructions:
https://hasura.io/docs/1.0/graphql/manual/auth/authentication/jwt.html#configuring-jwt-mode

I intend to use `jwt callback` to set claims for Hasura authorization to work:

```js
"https://hasura.io/jwt/claims": {
  "x-hasura-allowed-roles": ["editor","user", "mod"],
  "x-hasura-default-role": "user",
  "x-hasura-user-id": "1234567890",
  "x-hasura-org-id": "123",
  "x-hasura-custom": "custom-value"
}
```

**Documentation feedback**
Once, I have figured and got it working, I'd be happy to contribute to next-auth docs.

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by ghoshnirmalya** [comment]
@SharadKumar I'm using NextAuth [in a Next.js and Hasura application](https://github.com/ghoshnirmalya/nextjs-hasura-boilerplate). I came across a similar solution and solved it [in this way](https://github.com/ghoshnirmalya/nextjs-hasura-boilerplate/blob/master/frontend/pages/api/auth/%5B...nextauth%5D.ts#L35-L39). Let me know if this helps you.

**Comment by SharadKumar** [comment]
Thank you @ghoshnirmalya 

I have been able to to get JWT (without database) working with Hasura role-based authorization (JWT), with help from your boilerplate. So thank you and Ian.

**Comment by williscool** [comment]
@SharadKumar what do you mean by without database?

**Comment by Manubi** [comment]
Is there somewhere a tutorial which leads to the boilerblate of @ghoshnirmalya ? thanks!

**Comment by ghoshnirmalya** [comment]
@Manubi The documentations for that boilerplate is available [here](https://nirmalyaghosh.com/guides/nextjs-hasura-boilerplate/01-index). Is there any specific part where you need help?

**Comment by Manubi** [comment]
Yeah I‘ve seen the documentation. But imho it‘s more about how to get the boilerplate running. I would need something that explains everything in a little more detail as I want to migrate from an existing firebase auth/hasura project to next-auth/hasura. As I am pretty new to next-auth and hasura I‘d love to see a more detailed documentation. Thanks for your work and help! 🙌

**Comment by ghoshnirmalya** [comment]
@manishrc I'd be happy to write a detailed article regarding how everything works in the boilerplate. However, if there're any specific points where you need help, let me know.

**Comment by manishrc** [comment]
@ghoshnirmalya I believe you meant to mention @Manubi ?

**Comment by ghoshnirmalya** [comment]
> @ghoshnirmalya I believe you meant to mention @Manubi ?

Yes. Sorry about that 😅

**Comment by Manubi** [comment]
Hi Nirmalya,
Thanks for your help! Is there a way I can contact you to chat about it if I have questions? Maybe discord(manu#7599)? I am also on the hasura server. I am going to change change from firebase to next-auth in the next couple days and a couple questions will pop up during the process. Would love to ask you about it. 
From playing around with it, I am interested on how what the pg package does and how I am able/what adds the necessary tables in hasura. 
Thanks

**Comment by ghoshnirmalya** [comment]
@Manubi You can reach out to me on [Twitter](https://twitter.com/nirmalyaghosh23).
