### ISSUE TITLE
OAuth: should a `client_id` be sent to the token endpoint?

### ISSUE THREAD

**Issue by ksnll** [nextauthjs/next-auth#5122]
### Question 💬

I'm implementing an OAuth provider, for the website lichess.org.
This provider requires a `client_id` to be sent in the token endpoint request body.
The authentication fails, as it looks like nextauth doesn't send `client_id` automatically for the token endpoint.

From a quick read of the OAuth RFC, it looks like `client_id` should be pretty standard for the token endpoint: https://www.rfc-editor.org/rfc/rfc6749#section-3.2.1, in particular: 
> In the "authorization_code" "grant_type" request to the token endpoint, an
   unauthenticated client MUST send its "client_id" to prevent itself
   from inadvertently accepting a code intended for a client with a
   different "client_id".

it looks like the [underlying library for OAuth](https://github.com/panva/node-openid-client/) used by nextauth, doesn't automatically send the `client_id`, but it supports sending arbitrary parameters from the callback, called [exchangeBody](https://github.com/panva/node-openid-client/blob/2e02d5b9dc33959f79b0f5e22b78d1a915f4ed02/lib/client.js#L603), that could be implemented when [calling the callback from nextauth](https://github.com/nextauthjs/next-auth/blob/6590993fdc4ad31d5ce4b9dc3f5ca9df5d72b793/packages/next-auth/src/core/lib/oauth/callback.ts#L115)

So I'm wondering, first of all, how is it possible that other OAuth providers are working, as it looks like the `client_id` should be a pretty commonly required parameter. So the question is if I'm missing something obvious.
Secondo of all, in case the above investigation is correct, should the parameter be added through the `exchangeBody` parameter from nextauth, or should the underlying library (node-openid-client) be fixed instead.

### How to reproduce ☕️

```ts 
const lichessHost = "https://lichess.org";
const scope = "email:read";

export default NextAuth({
  debug: true,
  providers: [
    {
      id: "lichess",
      name: "Lichess",
      type: "oauth",
      clientId: "client-id-test",
      clientSecret: "secret",
      authorization: {
        url: `${lichessHost}/oauth`,
        params: { scope },
      },
      token: `${lichessHost}/api/token`,
      userinfo: `${lichessHost}/api/account`,
      checks: ["pkce", "state"],
      profile(profile) {
        return {
          id: profile.id,
          username: profile.username,
        };
      },
    },
  ],
});

```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Please check the docs https://next-auth.js.org/configuration/providers/oauth#client-option

specifically `token_endpoint_auth_method `

https://github.com/panva/node-openid-client/blob/main/docs/README.md#client-authentication-methods

**Comment by ksnll** [comment]
thank you 🙏

**Comment by sexta13** [comment]
> thank you 🙏

where you able to configure in order to pass it to token endpoint? thanks

**Comment by reginpv** [comment]
Same issue with my app, I just noticed switching between branches remove my env.local (which I manage via Vercel).

If you have the same setup just pull your env `vercel env pull` then run dev again.

Overall the problem looks like it can not find the `client_id` make sure it is properly added on your env.

**Comment by hongjiaherng** [comment]
> > thank you 🙏
> 
> @ksnll where you able to configure in order to pass it to token endpoint? thanks

```ts
const MyCompanyProvider: OAuthConfig<any> = {
  clientId: process.env.MY_COMPANY_CLIENT_ID,
  clientSecret: process.env.MY_COMPANY_CLIENT_SECRET,
  wellKnown:
    "https://mycompany.com/oidc/.well-known/openid-configuration",
  id: "mycompany",
  name: "My Company",
  type: "oauth",
  version: "2.0",
  checks: ["pkce", "state"],
  profile: (profile) => {
    return {
      id: profile.profileid, // unique id for the user
      name: profile.preferred_username, // username in the format of Firstname_Lastname or other format
      email: profile.email, // company email
      image: null, // no image
    };
  },
  idToken: true,
  authorization: {
    params: {
      scope: "openid profile email", // This yields (openid: profileid), (profile: name, given_name, family_name, preferred_username, domain), (email: email, email_verified)
    },
  },
  client: {
    token_endpoint_auth_method: "client_secret_post", // LOOK HERE!!!
  },
};
```

**Comment by sexta13** [comment]
> > > thank you 🙏
> > 
> > 
> > @ksnll where you able to configure in order to pass it to token endpoint? thanks
> 
> ```ts
> const MyCompanyProvider: OAuthConfig<any> = {
>   clientId: process.env.MY_COMPANY_CLIENT_ID,
>   clientSecret: process.env.MY_COMPANY_CLIENT_SECRET,
>   wellKnown:
>     "https://mycompany.com/oidc/.well-known/openid-configuration",
>   id: "mycompany",
>   name: "My Company",
>   type: "oauth",
>   version: "2.0",
>   checks: ["pkce", "state"],
>   profile: (profile) => {
>     return {
>       id: profile.profileid, // unique id for the user
>       name: profile.preferred_username, // username in the format of Firstname_Lastname or other format
>       email: profile.email, // company email
>       image: null, // no image
>     };
>   },
>   idToken: true,
>   authorization: {
>     params: {
>       scope: "openid profile email", // This yields (openid: profileid), (profile: name, given_name, family_name, preferred_username, domain), (email: email, email_verified)
>     },
>   },
>   client: {
>     token_endpoint_auth_method: "client_secret_post", // LOOK HERE!!!
>   },
> };
> ```

I ended up by just setting this configuration:

```
token: {
        url: config.nextAuth.urls.token,
        request: async (context) => {
          const tokens = await context.client.callback(
            context.provider.callbackUrl,
            context.params,
            context.checks,
            {
              exchangeBody: {
                client_id: config.nextAuth.cognito.clientId,
              },
            }
          );

          return { tokens };
        },
      },
```
