### ISSUE TITLE
(0 , next_auth_react__WEBPACK_IMPORTED_MODULE_5__.singIn) is not a function

### ISSUE THREAD

**Issue by IbrahimSSEnterprise** [nextauthjs/next-auth#5143]
### Question 💬

Hi i am receiving this error when clicking on Login button & it's not showing me any error please need help 
(0 , next_auth_react__WEBPACK_IMPORTED_MODULE_5__.singIn) is not a function

### How to reproduce ☕️

https://github.com/IbrahimSSEnterprise/next-sseu-basir.git
<img width="209" alt="Screenshot 2022-08-12 025427" src="https://user-images.githubusercontent.com/110059752/184310345-2025b009-1d33-4dfd-b16f-88f4dc6e7f51.png">

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by awareness481** [comment]
I don't see the import anywhere in your codebase but based on the error message it's likely that you have a typo

```diff
- import { singIn } from "next-auth/react"
+ import { signIn } from "next-auth/react"
```

**Comment by IbrahimSSEnterprise** [comment]
Hi @balazsorban44   I am still facing same issue can please have a look 
Thanks in advance

**Comment by balazsorban44** [comment]
As suggested above, it seemed like you had a typo. your repro had no reference to `signIn` anywhere, so if you still think it's an issue, please provide a _minimal_ reproduction without unnecessary code that clearly shows the issue you are facing.

**Comment by IbrahimSSEnterprise** [comment]
@awareness481  @balazsorban44 Just pushed updates on reproduce

**Comment by awareness481** [comment]
Hi @IbrahimSSEnterprise 

Just change this line
https://github.com/IbrahimSSEnterprise/next-sseu-basir/blob/8fbe3ee53fc5798e153fecec66a22df20af6a510/pages/login.js#L5
to
`import { signIn, useSession } from 'next-auth/react';`
and this specific error will go away

**Comment by IbrahimSSEnterprise** [comment]
Solved 
Thank you so much guys  i really apricated it.

**Comment by HT-35** [comment]
I had the same problem, I fixed it by replacing : 
`import { signIn, useSession } from "next-auth/react";   ==>   import { signIn } from "@/auth";`
`"use server";

import { signIn } from "@/auth";
import { InvalidLoginError } from "@/components/auth/authErrors";

export async function authenticate(email: string, password: string) {
  try {
    const login = await signIn("credentials", {
      email: email,
      password: password,
      callbackUrl: "/",
      redirect: false,
    });

    return login;
  } catch (error) {
    if (error?.cause?.err instanceof InvalidLoginError) {
      return { error: "Incorrect username or password" };
    } else {
      return { error: "Failed to authenticate" };
    }
  }
}
`

`
import { authenticate } from "@/components/auth/action";

export async function handleLogin(email: string, password: string) {
  const result = await authenticate(email, password);
  return result;
}

`

`
"use client";
import React from "react";
import type { FormProps } from "antd";
import { Button, Checkbox, Form, Input } from "antd";

import { useRouter } from "next/navigation";

import { Bounce, toast } from "react-toastify";
import { handleLogin } from "@/components/auth/handleLogin";

type FieldType = {
  email?: string;
  password?: string;
  remember?: string;
};

const onFinishFailed: FormProps<FieldType>["onFinishFailed"] = (errorInfo) => {
  console.log("Failed:", errorInfo);
};

const FormLogin = () => {
  const router = useRouter();

  const onFinish: FormProps<FieldType>["onFinish"] = async (
    values: FieldType
  ) => {
    const { email, password } = values;
    const Login = await handleLogin(email, password);

    if (Login.error) {
      toast.error(`${Login.error}!!`, {
        position: "top-right",
        autoClose: 5000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
        theme: "light",
        transition: Bounce,
      });
    } else {
      toast.success(`Login Successfull  !!`, {
        position: "top-right",
        autoClose: 5000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
        theme: "light",
        transition: Bounce,
      });
      router.refresh();
      router.push("/");
    }
  };
  return (
    <Form
      name="basic"
      labelCol={{ span: 6 }}
      wrapperCol={{ span: 16 }}
      style={{
        maxWidth: "100%",
        margin: "20px 0",
        minHeight: "330px",
      }}
      initialValues={{ remember: true }}
      onFinish={onFinish}
      onFinishFailed={onFinishFailed}
      autoComplete="off"
    >
      <Form.Item<FieldType>
        style={{ textAlign: "left", minWidth: "86px" }}
        label="email"
        name="email"
        rules={[
          { required: true, message: "Please input your email!" },
          { type: "email", message: "Please input your email!!!" },
        ]}
      >
        <Input autoComplete="email" />
      </Form.Item>

      <Form.Item<FieldType>
        label="Password"
        name="password"
        rules={[{ required: true, message: "Please input your password!" }]}
      >
        <Input.Password />
      </Form.Item>

      <Form.Item<FieldType>
        name="remember"
        style={{ minHeight: "72px" }}
        valuePropName="checked"
        wrapperCol={{ offset: 3, span: 16 }}
      >
        <Checkbox>Remember me</Checkbox>
      </Form.Item>

      <Form.Item wrapperCol={{ offset: 10, span: 16 }}>
        <Button type="primary" htmlType="submit">
          Submit
        </Button>
      </Form.Item>
    </Form>
  );
};

export default FormLogin;

`

**Comment by HT-35** [comment]
I had the same problem, I fixed it by replacing :
import { signIn, useSession } from "next-auth/react";   ==>   import { signIn } from "@/auth";

My Code : 

`// src/server/auth.ts
"use server";

import { signIn } from "@/auth";
import { InvalidLoginError } from "@/components/auth/authErrors";

export async function authenticate(email: string, password: string) {
  try {
    const login = await signIn("credentials", {
      email: email,
      password: password,
      callbackUrl: "/",
      redirect: false,
    });

    return login;
  } catch (error) {
    if (error?.cause?.err instanceof InvalidLoginError) {
      return { error: "Incorrect username or password" };
    } else {
      return { error: "Failed to authenticate" };
    }
  }
}
`// src/errors/authErrors.ts
export class InvalidLoginError extends Error {
  code = "invalid_credentials";
}

export class UnverifiedEmailError extends Error {
  code = "email_unverified";
}
`import { authenticate } from "@/components/auth/action";

export async function handleLogin(email: string, password: string) {
  const result = await authenticate(email, password);
  return result;
}
`"use client";
import React from "react";
import type { FormProps } from "antd";
import { Button, Checkbox, Form, Input } from "antd";

import { useRouter } from "next/navigation";

import { Bounce, toast } from "react-toastify";
import { handleLogin } from "@/components/auth/handleLogin";

type FieldType = {
  email?: string;
  password?: string;
  remember?: string;
};

const onFinishFailed: FormProps<FieldType>["onFinishFailed"] = (errorInfo) => {
  console.log("Failed:", errorInfo);
};

const FormLogin = () => {
  const router = useRouter();

  const onFinish: FormProps<FieldType>["onFinish"] = async (
    values: FieldType
  ) => {
    const { email, password } = values;
    const Login = await handleLogin(email, password);

    if (Login.error) {
      toast.error(`${Login.error}!!`, {
        position: "top-right",
        autoClose: 5000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
        theme: "light",
        transition: Bounce,
      });
    } else {
      toast.success(`Login Successfull  !!`, {
        position: "top-right",
        autoClose: 5000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
        theme: "light",
        transition: Bounce,
      });
      router.refresh();
      router.push("/");
    }
  };
  return (
    <Form
      name="basic"
      labelCol={{ span: 6 }}
      wrapperCol={{ span: 16 }}
      style={{
        maxWidth: "100%",
        margin: "20px 0",
        minHeight: "330px",
      }}
      initialValues={{ remember: true }}
      onFinish={onFinish}
      onFinishFailed={onFinishFailed}
      autoComplete="off"
    >
      <Form.Item<FieldType>
        style={{ textAlign: "left", minWidth: "86px" }}
        label="email"
        name="email"
        rules={[
          { required: true, message: "Please input your email!" },
          { type: "email", message: "Please input your email!!!" },
        ]}
      >
        <Input autoComplete="email" />
      </Form.Item>

      <Form.Item<FieldType>
        label="Password"
        name="password"
        rules={[{ required: true, message: "Please input your password!" }]}
      >
        <Input.Password />
      </Form.Item>

      <Form.Item<FieldType>
        name="remember"
        style={{ minHeight: "72px" }}
        valuePropName="checked"
        wrapperCol={{ offset: 3, span: 16 }}
      >
        <Checkbox>Remember me</Checkbox>
      </Form.Item>

      <Form.Item wrapperCol={{ offset: 10, span: 16 }}>
        <Button type="primary" htmlType="submit">
          Submit
        </Button>
      </Form.Item>
    </Form>
  );
};

export default FormLogin;
`

**Comment by HT-35** [comment]
I had the same problem, I fixed it by replacing  :

import { signIn, useSession } from "next-auth/react";       ==>   import { signIn } from "@/auth";

=============================  My Code (i used AntD in LoginForm)  ========================

```javascript

"use server";

import { signIn } from "@/auth";
import { InvalidLoginError } from "@/components/auth/authErrors";

export async function authenticate(email: string, password: string) {
  try {
    const login = await signIn("credentials", {
      email: email,
      password: password,
      callbackUrl: "/",
      redirect: false,
    });

    return login;
  } catch (error) {
    if (error?.cause?.err instanceof InvalidLoginError) {
      return { error: "Incorrect username or password" };
    } else {
      return { error: "Failed to authenticate" };
    }
  }
}
===============================================================================
// src/errors/authErrors.ts
export class InvalidLoginError extends Error {
  code = "invalid_credentials";
}

export class UnverifiedEmailError extends Error {
  code = "email_unverified";
}
===============================================================================
import { authenticate } from "@/components/auth/action";

export async function handleLogin(email: string, password: string) {
  const result = await authenticate(email, password);
  return result;
}
===============================================================================
"use client";
import React from "react";
import type { FormProps } from "antd";
import { Button, Checkbox, Form, Input } from "antd";

import { useRouter } from "next/navigation";

import { Bounce, toast } from "react-toastify";
import { handleLogin } from "@/components/auth/handleLogin";

type FieldType = {
  email?: string;
  password?: string;
  remember?: string;
};

const onFinishFailed: FormProps<FieldType>["onFinishFailed"] = (errorInfo) => {
  console.log("Failed:", errorInfo);
};

const FormLogin = () => {
  const router = useRouter();

  const onFinish: FormProps<FieldType>["onFinish"] = async (
    values: FieldType
  ) => {
    const { email, password } = values;
    const Login = await handleLogin(email, password);

    if (Login.error) {
      toast.error(`${Login.error}!!`, {
        position: "top-right",
        autoClose: 5000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
        theme: "light",
        transition: Bounce,
      });
    } else {
      toast.success(`Login Successfull  !!`, {
        position: "top-right",
        autoClose: 5000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
        theme: "light",
        transition: Bounce,
      });
      router.refresh();
      router.push("/");
    }
  };
  return (
    <Form
      name="basic"
      labelCol={{ span: 6 }}
      wrapperCol={{ span: 16 }}
      style={{
        maxWidth: "100%",
        margin: "20px 0",
        minHeight: "330px",
      }}
      initialValues={{ remember: true }}
      onFinish={onFinish}
      onFinishFailed={onFinishFailed}
      autoComplete="off"
    >
      <Form.Item<FieldType>
        style={{ textAlign: "left", minWidth: "86px" }}
        label="email"
        name="email"
        rules={[
          { required: true, message: "Please input your email!" },
          { type: "email", message: "Please input your email!!!" },
        ]}
      >
        <Input autoComplete="email" />
      </Form.Item>

      <Form.Item<FieldType>
        label="Password"
        name="password"
        rules={[{ required: true, message: "Please input your password!" }]}
      >
        <Input.Password />
      </Form.Item>

      <Form.Item<FieldType>
        name="remember"
        style={{ minHeight: "72px" }}
        valuePropName="checked"
        wrapperCol={{ offset: 3, span: 16 }}
      >
        <Checkbox>Remember me</Checkbox>
      </Form.Item>

      <Form.Item wrapperCol={{ offset: 10, span: 16 }}>
        <Button type="primary" htmlType="submit">
          Submit
        </Button>
      </Form.Item>
    </Form>
  );
};

export default FormLogin;
