### ISSUE TITLE
recommendation - export client safe providers as a type

### ISSUE THREAD

**Issue by theigor** [nextauthjs/next-auth#5167]
### Question 💬

When building my own signin page, using the example here - https://next-auth.js.org/configuration/pages#oauth-sign-in, I have to implement my own `getServerSideProps` like so

```ts
export const getServerSideProps: GetServerSideProps = async (context) => {
  const providers = await getProviders();

  return {
    props: { providers },
  };
};
```

Which means that I need to define a props type for my sign in page and `providers` should have a type.

But it gets exported like 

```ts
export declare function getProviders(): Promise<Record<LiteralUnion<BuiltInProviderType, string>, ClientSafeProvider> | null>;
```

which means I have to type it like

```ts
import { BuiltInProviderType } from 'next-auth/providers';
import { ClientSafeProvider, getProviders, LiteralUnion } from "next-auth/react";

type Props = {
  providers: Record<LiteralUnion<BuiltInProviderType, string>, ClientSafeProvider>
}
```

which means I need to import a whole lot of stuff. It would be much nicer if I could type it like

```ts
import { ClientSafeProviderList } from "next-auth/react";

type Props = {
  providers: ClientSafeProviderList
}
```

_or something similar_.

### How to reproduce ☕️

See snippet above. I'm just recommending an extra type export. Thanks!

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by melanieseltzer** [comment]
I would also be interested in this 👍

FYI - TypeScript 4.5 or higher has the [Awaited type](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#the-awaited-type-and-promise-improvements), which is pretty useful here to cut down on the imports. 

This is what I'm currently doing in my app, for a reusable type:

```ts
// src/types/auth.ts

import { getProviders } from 'next-auth/react';

export type ClientSafeProviders = Awaited<ReturnType<typeof getProviders>>;
// => type ClientSafeProviders = Record<LiteralUnion<BuiltInProviderType, string>, ClientSafeProvider> | null
```

**Comment by theigor** [comment]
Oh perfect. That's exactly what I need. With `Awaited`, this becomes very much a nice to have. I'll close.
