### ISSUE TITLE
Add Custom Error Callback

### ISSUE THREAD

**Issue by BenjaminWFox** [nextauthjs/next-auth#517]
**Summary of proposed feature**
Add a new callback `error` that allows for custom handling of errors.

**Purpose of proposed feature**
In Azure B2C there is a (strange, imo) implementation where, if the user clicks the 'password reset' link in the (Azure B2C controlled) authentication form it posts back to the callback URL with an error (example below). It would be nice to have a be able to write a handler that could check for this, or any, particular error code and act accordingly.

```
    error: 'access_denied',
    error_description: 'AADB2C90118: The user has forgotten their password.\r\n' +
      'Correlation ID: 40e2100f-c43f-4dc6-a01b-4b1002861c74\r\n' +
      ...
```

I'm sure there are other situations this might be handy. One I saw was #373 where this could be used with `signInCallbackResponse` to pass along a failure message `signIn`.

Note this would require changing the signature of the `signIn` callback, which I think would be a breaking change? But could look something like this:

```
const signInCallbackResponse = await callbacks.signIn(userOrProfile, account, OAuthProfile)
if (signInCallbackResponse.success === false) {
  return callbacks.error(error, redirect, `${baseUrl}${basePath}/error?error=${signInCallbackResponse.message}`)
}
```

**Detail about proposed feature**
This is a very bare-bones example of what implementation might look like:

https://github.com/nextauthjs/next-auth/compare/main...BenjaminWFox:enhancement/explicit-error-callback

Implemented it looks like this. As long as I can figure out the structure of `error` (see potential problems) I can handle it as needed:
```
callbacks: {
  signIn: async (user, account, profile) => {
    console.log('Callback: signIn: user/account/profile', user, account, profile)

    return Promise.resolve(true)
  },
  error: async (error, redirect, redirectUrl) => {
    console.log('NEW Error callback: ', redirectUrl)

    return redirect(`https://some.custom.redirect.url/.../...`)
  }
}
```

**Potential problems**
- Error standardization/what to pass as first prop `error`? There are [areas in the code](https://github.com/nextauthjs/next-auth/blob/main/src/server/routes/callback.js#L138) that call errors that are not triggered by caught or thrown errors. [Some places](https://github.com/nextauthjs/next-auth/blob/main/src/server/routes/callback.js#L37) have a variable `error` that may or may not be an instance of `Error`. [Some places](https://github.com/nextauthjs/next-auth/blob/main/src/server/routes/callback.js#L76) are also just a bit confusing.
- Breaking changes depending on how complex the implementation gets.

**Describe any alternatives you've considered**
I am currently planning to hide the default 'reset password' element and similar to #373 will use custom link/callback. This is a perfectly fine solution for the time being.

*Please indicate if you are willing and able to help implement the proposed feature.*
Yes, I could help work on this, but would need input on method signatures & code impact/breaking changes

**Comment by iaincollins** [comment]
Thanks for raising this as a suggestion! I think this is a great idea and can see the benefits.

I can imagine this might take some time to think about.

This seems like something we could probably take an incremental approach with?

**Comment by BenjaminWFox** [comment]
I think it could be incremental, yes. Adding just the `error` callback by itself shouldn't affect anything in terms of existing functionality. It **does** change the redirects from sync to async.

In terms of integrating with the `signIn` (or other callbacks), those methods aren't used very broadly and I don't think the implementation would be challenging, but should certainly be well tested.

I also had a thought for the #373 usecase that would be non-breaking & allow for a deprecation period of the current implementation. Since the checks after the `signIn` callback are only for falsy values, a second check could be added based on a new return value. For example:

```
if (signinCallbackResponse === false || signinCallbackResponse.success === false) {
  const errorMessage = signinCallbackResponse.message || signinCallbackResponse
  return callbacks.error(errorMessage, redirect, `${baseUrl}${basePath}/error?error=AccessDenied`)
}
```

Questions:
- Is it a problem to change the current sync `return redirect(...)` to async `return callbacks.error(...)`
  - My initial experiments didn't have a problem, but I wasn't using a very extensive example.
- Is it okay to pass in whatever error already exists? Or is it better to try and standardize error messages if taking this approach? The latter being a lot more effort.

**Comment by BenjaminWFox-Lumedic** [comment]
@iaincollins I added a PR to better illustrate this idea. If it still seems like something worth pursuing let me know. I can clean up the PR & think a little more on a standard 'error'.

**Comment by BenRedmondBenham** [comment]
> **Describe any alternatives you've considered**
> I am currently planning to hide the default 'reset password' element and similar to #373 will use custom link/callback. This is a perfectly fine solution for the time being.

Did you figure out how to hide this in B2C?

**Comment by BenjaminWFox** [comment]
If you're using custom pages you should be able to add css to target that link. In the version I'm using at least it is `id="forgotPassword"`.

Then I'm adding a direct link to the 'reset password' flow below the B2C injected elements.

**Comment by balazsorban44** [comment]
possibly related #989
