### ISSUE TITLE
NextAuth URL not working on production 

### ISSUE THREAD

**Issue by mreshnaan** [nextauthjs/next-auth#5174]
### Question 💬

env.local file
NEXTAUTH_URL=https://dienft.xyz
NEXTAUTH_SECRET=somesecret

TWITTER_CONSUMER_KEY =
TWITTER_CONSUMER_SECRET =

twitter app link done 
https://dienft.xyz/api/auth/callback/twitter

why is not working can anyone help me

version 4.10.3

when i try to log in it shows 404 and in console, there are so many errors but in local it works fine 

![Screenshot_191](https://user-images.githubusercontent.com/63632473/185178509-6e6afe43-2273-493a-892c-1afb6d887ba6.png)
![Screenshot_190](https://user-images.githubusercontent.com/63632473/185178531-f2b1a2af-1a04-4f89-b099-ee5195d04730.png)

### How to reproduce ☕️

production doest work    

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by candebut** [comment]
Ran into the same issue. Works perfectly in local with NEXTAUTH_URL=http://localhost:3000 but fails in production with NEXTAUTH_URL=http://my-app.ai
