### ISSUE TITLE
NextAuth URL Production doest work  

### ISSUE THREAD

**Issue by mreshnaan** [nextauthjs/next-auth#5175]
### Environment

NEXTAUTH_URL=https://dienft.xyz  in   env.local file
https://dienft.xyz/api/auth/callback/twitter  twitter callback url done 

version 
next auth  4.10.3
next": "12.2.0

in local it works fine but after i deploy the project in firebase hosting (live) it show these errors

![Screenshot_191](https://user-images.githubusercontent.com/63632473/185181170-a562c4a0-304f-43c7-9e06-fe12859f631d.png)
![Screenshot_190](https://user-images.githubusercontent.com/63632473/185181176-5a9cdc9b-c03d-472a-a5ad-8c1ea894bff9.png)

### Reproduction URL

https://dienft.xyz/api/auth/error

### Describe the issue

production issue

### How to reproduce

deploy to production error pops up [CLIENT_FETCH_ERROR] 

### Expected behavior

login and get seession details

**Comment by balazsorban44** [comment]
Please try upgrading Next.js to the `latest` and don't forget to include your code so we can investigate.
