### ISSUE TITLE
Using the JWT Session Token on Client-Side

### ISSUE THREAD

**Issue by AmruthPillai** [nextauthjs/next-auth#5178]
### Question 💬

How do I get the JWT Session Token (undecoded) on the client?

I've tried getting the session token from the next-auth.session-token cookie, but failed to get the value of the cookie (even after using multiple libraries).

I tried passing token along with the session when forming the session object, but it seems to return the decoded token instead of the raw JWT token text.

I need the JWT token to be able to send it across to another service that I need to authenticate with (Hasura, through URQL).

### How to reproduce ☕️

Right now, I have a hack set up: I have created an API /api/me which returns the token for the currently logged in user.

```ts
import type { NextApiRequest, NextApiResponse } from "next";
import { getToken } from "next-auth/jwt";

export default async (req: NextApiRequest, res: NextApiResponse) => {
  const token = await getToken({ req, raw: true });

  res.status(200).json({ token });
};
```

and then I instantiate the `urql` client from the response of this API, but I don't want to spend precious `ms` making another fetch.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
You are not supposed to access the JWT on the client directly, as it's an HttpOnly cookie. You can proxy any request through an API route, where you have access to the raw JWT through `getToken` with the `raw:true` option. Generally though, your service should issue its own auth token that you save in the NextAuth.js session.

**Comment by itsanishjain** [comment]
@AmruthPillai I am also Using Hasura to create my client I need JWT after login and I am setting up client inside a Layout.tsx
have you figure that out I mean calling an API everytime to getToken won't seem the best solution to me.

```
const Layout = ({ children }: any) => {
  const jwt: string = useSelector((state: any) => state.account.jwt);
  const { data: session } = useSession();

  console.log({ session });

  const httpLink = createHttpLink({
    uri: apolloURI,
  });

  const authLink = setContext((_) => {
    return {
      headers: {
        'content-type': 'application/json',
        Authorization: `Bearer ${jwt}`,
      },
    };
  });

  const client = new ApolloClient({
    link: authLink.concat(httpLink),
    cache: new InMemoryCache(),
  });

  return (
    <ApolloProvider client={client}>
      <div className="flex flex-col text-white min-h-screen">
        <Pencil>
          <p className="text-button py-2.5">
            We just launched our new marketplace!
          </p>
        </Pencil>
        <NavBar />
        <main className="flex flex-col grow">{children}</main>
        <Footer />
        <ToastContainer />
      </div>
    </ApolloProvider>
  );
};

export default Layout;


 ```

**Comment by vinczebalazs** [comment]
I believe that client side requests are an absolutely valid use case, no real-world application is SSR only. 
My current use case for example is the ability to like posts on a feed. Although the feed is rendered server-side, sending a like is strictly done on the client side and those requests needs to be authenticated just like any other. 

If the auth token is stored in a HTTP only cookie, obviously you can't attach it as Bearer token on the client side. Thus having to proxy all client requests through the server just to read the cookie and send the request to the API and proxy it back again. I don't think this is a viable approach or one that would scale well for any website with medium traffic. What is the reason for using http only cookies? IMHO if someone can inject and execute JS on your site you are doomed already, cookies really don't matter.

**Comment by yvesloy** [comment]
@balazsorban44 Would love to hear your take on @vinczebalazs comment!

**Comment by balazsorban44** [comment]
> sending a like is strictly done on the client side and those requests needs to be authenticated just like any other.

The request will have to reach a server at some point where the actual auth happens. Keep in mind that Auth.js in its current form not an Authorization Server for your external APIs. it's an auth mechanism for your app, that _can_ be hooked up with third-party sources.

>  I don't think this ... approach ... would scale well for any website with medium traffic

Correct, if you have a third-party API, set up your own authorization server, which Auth.js can seemlessly integrate with. Have a read at https://authjs.dev/guides/integrating-third-party-backends

Security has layers. localStorage and non-http cookies are not something we want to popularize as it's a huge security risk as mentioned above.

If you think you are aware of the consequences, you can configure the Auth.js session cookie to not be httponly with the `cookies` config option, but I really discourage you to do so.

**Comment by ghoshan-ai** [comment]
Hey @balazsorban44 

Lets say I have a separate express server. Its not a thirdparty, but my own. Could I potentially setup authjs on that (using database provider), then somehow the httpcookie is sent over to express server to check if the auth is valid?

Or would it be better to use database stratergy, and lookup the sessionToken on either the express backend/nextjs backend to see if the user is valid?

Or is there any mechanism to implicitly login to the subscribed external services?
