### ISSUE TITLE
Middleware never runs on sign in page

### ISSUE THREAD

**Issue by snax4a** [nextauthjs/next-auth#5189]
### Environment

  System:
    OS: macOS 12.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 113.22 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 96.0.3
    Safari: 15.6.1
    Safari Technology Preview: 16.0
  npmPackages:
    next: latest => 12.2.5 
    next-auth: latest => 4.10.3 
    react: ^18.2.0 => 18.2.0 

### Reproduction URL

https://github.com/snax4a/next-auth-middleware-issue

### Describe the issue

I am trying to redirect user with middleware if he is authenticated and tries to open auth page but currently its not possible because middleware never runs on sign in page.

In the reproduction code I have added `"/api/auth/signin"` to the middleware matcher but same happens when custom sign in page is defined.

### How to reproduce

Go to the default sign in page http://localhost:3000/api/auth/signin
See that there are no console logs showing middleware was hit.

If you want you can login with these credentials:

```
test@test.com
```
```
test1234
````

### Expected behavior

Middleware should run on sign in page / custom sign in page so I will be able to redirect user if he is logged in.

**Comment by balazsorban44** [comment]
You should not need redirection on the sign-in page, otherwise you could end up in an infinite loop. `next-auth` will already redirect any matched paths to the sign-in page.

Wherever you have the signin button, you should already have the session to render a link conditionally to the actual content instead of the sign-in page.

**Comment by snax4a** [comment]
I can always protect against infinite loop with proper if statements.
This is working middleware example without `withAuth` which handles that properly without an infinite loop.
```tsx
import { ROUTES } from '@lib/constants'
import { getToken } from 'next-auth/jwt'
import type { NextRequest } from 'next/server'
import { NextResponse } from 'next/server'

export default async function middleware(req: NextRequest) {
  const token = await getToken({ req: req as any })
  const isAuthRoute = req.nextUrl.pathname.startsWith('/auth')

  // If authenticated on auth page redirect home
  if (isAuthRoute && token) return NextResponse.redirect(new URL(ROUTES.HOME, req.url))

  // If not authenticated and not on auth page redirect to login page
  if (!isAuthRoute && !token) return NextResponse.redirect(new URL(ROUTES.LOGIN, req.url))

  return NextResponse.next()
}

export const config = {
  matcher: ['/home', '/account', '/auth/:path*', '/panel/:path*'],
}
```

If its expected behavior and you don't want anyone to use middleware on sign in page then it should be documented.
