### ISSUE TITLE
Custom signin page redirect documentation issue.

### ISSUE THREAD

**Issue by yusa-imit** [nextauthjs/next-auth#5192]
### Document that was not quite helpful

In page [here](https://github.com/nextauthjs/next-auth/blob/main/docs/docs/configuration/pages.md), I can cleary see the implementation methods about custom signin page.

Also, some full [example](https://github.com/ndom91/next-auth-example-sign-in-page) was provided, which is good. But..

### What was wrong?
While implementing multi-oauth-provider next-auth custom sign-in page, I got some problems with redirection.

Custom sign in url changed correctly like `example.com/auth/signin?callbackUrl=https%3A%2F%2Fexample.com%2Flogin` which callback url is `example.com/login`.

But actually, implementing custom sign in page with documents in there, like this

```typescript
function CustomSignIn({providers}){
return (
    {providers &&
                Object.values(providers).map((provider) => (
                  <Button
                    onClick={() => {
                      signIn(provider.id);
                    }}
                  >
                    {provider.name}
                  </Button>
                ))}
    );
}
```

will not redirect you to `example.com/login`

### How to solve?

SingIn function has parameters `SingInOptions` which contains `redirect: boolean` and `callbackUrl: string`.
So, manually put in callbackUrl using useRouter like this will work
```Typescript
function CustomSignIn({providers}){
const route = useRouter();
return (
    {providers &&
                Object.values(providers).map((provider) => (
                  <Button
                    onClick={() => {
                      signIn(provider.id, { redirect: true, callbackUrl: route.query.callbackUrl });
                    }}
                  >
                    {provider.name}
                  </Button>
                ))}
    );
}
```

Now correctly works with redirect.

### Is there any context that might help us understand?

I think first of all, signIn function with not specifying SignInOption parameters will be checked.

If it doesn't have problem about redirect functionallity, then change little bit of documentation about signIn function's parameters in `pages-custom page`section will be very helpful to people who want to properly set their signIn function with redirect option.

Also, re-create or re-link full example about custom signIn page will be appreciated.

### Does the docs page already exist? Please link to it.

https://github.com/nextauthjs/next-auth/blob/main/docs/docs/configuration/pages.md

**Comment by christopherpickering** [comment]
Thanks :) found your solution after a few hours of struggling lol.

**Comment by ThangHuuVu** [comment]
Nice catch! PR is welcome for this issue 🙌

**Comment by christopherpickering** [comment]
I found that it throws a typescript error (something about `string[] | string` to string error), but can't figure it out, so instead I switched to a callback to redirect to the homepage after logging in.
I also set NEXTAUTH_URL, but not sure if it needs it.
```js
async redirect({ url, baseUrl }) {
      return baseUrl; //Promise.resolve(url)
    },
```
But don't listen to me, I just lost and wandering lol

**Comment by PaoloJN** [comment]
Thank you so much, I almost broke my computer over this problem :)
