### ISSUE TITLE
Getting PrismaClientUnknownRequestError when using Prisma adapter

### ISSUE THREAD

**Issue by shinygit** [nextauthjs/next-auth#520]
**Describe the bug**
Very often when reloading a page or when a page is refreshed when returning focus this error will print in console and it will be as if the user is not logged in but refreshing, sometimes several times, it will work as expected.

**To Reproduce**
Steps to reproduce the behavior.

Include example code (or link to public repository) which can be used to reproduce the behavior.

**Expected behavior**

For it to acquire the session normally.

**Screenshots or error logs**

```

[next-auth][error][get_session_error] PrismaClientUnknownRequestError: 
Invalid `prisma.session.findOne()` invocation in
/home/shinbox/credit_book/node_modules/next-auth/dist/adapters/prisma/index.js:317:49

  Started http server

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

    at PrismaClientFetcher.request (/node_modules/@prisma/client/runtime/index.js:1:209472)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) 
https://next-auth.js.org/errors#get_session_error
[next-auth][error][session_error] Error: GET_SESSION_ERROR
    at /node_modules/next-auth/dist/adapters/prisma/index.js:336:35
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (/node_modules/next-auth/dist/adapters/prisma/index.js:16:103)
    at _throw (/node_modules/next-auth/dist/adapters/prisma/index.js:18:291)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) 
https://next-auth.js.org/errors#session_error
```

**Additional context**
I am using the Prisma adapter.

**Comment by iaincollins** [comment]
This is not something I've experienced.

Have you followed the tip on Prisma adapter page regarding how to setup the connection?

```js
let prisma

if (process.env.NODE_ENV === "production") {
  prisma = new PrismaClient()
} else {
  if (!global.prisma) {
    global.prisma = new PrismaClient()
  }
  prisma = global.prisma
}
```

**Comment by shinygit** [comment]
Yes I have, also tried it without it.  Anything else that's unusual I can think of..
`  callbacks: {
    session: async (session) => {
      const userId = await prisma.session.findOne({
        where: { accessToken: session.accessToken },
      })
      session.userId = userId.userId
      return session
    },
  },`

I am using this callback.

My __app looks like this...
