### ISSUE TITLE
unstable_getServerSession Returns Unserializable Data

### ISSUE THREAD

**Issue by mab05k** [nextauthjs/next-auth#5200]
### Environment

Next: 12.2.3
Next-auth: 4.10.3
React 17.0.2

### Reproduction URL

--

### Describe the issue

```
  const session = await unstable_getServerSession(
    context.req,
    context.res,
    authOptions
  );
  console.log(session);
```

Output
```
{
  user: { name: 'Admin User', email: 'admin@org1.com', image: undefined },
  expires: '2022-09-20T22:56:59.316Z'
}
```

Results in 
`Error: Error serializing `.session.user.image` returned from `getServerSideProps` in "/".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.`

### How to reproduce

Call `unstable_getServerSession` with a result that returns a value of `undefined` and try to return from `getServerSideProps`

### Expected behavior

`unstable_getServerSession` should work like the previous `getSession(context)` and return below:

```
{
  user: { name: 'Admin User', email: 'admin@org1.com' },
  expires: '2022-09-20T22:56:59.316Z'
}
```

The `undefined` value should be removed by the function before being returned to the application code.

**Comment by balazsorban44** [comment]
You can do this in the session callback yourself. https://next-auth.js.org/configuration/callbacks#session-callback

The result might not only be useful for sending in `gSSP`
