### ISSUE TITLE
Client credential flow (skip authorization step)

### ISSUE THREAD

**Issue by slava-lu** [nextauthjs/next-auth#5204]
### Question 💬

I need to support client credential OAuth flow (`grant_types=client_credentials`). This basically means skipping authorization step and going directly to the `/token` POST request with the client id and secret. Is there any way to skip the authorization step with next-auth?

I found a hack to do it with credential. flow, faking signing in user with the fake username and password but I would like better solution.

I need to for the salesforce shopper API
https://developer.salesforce.com/docs/commerce/commerce-api/guide/slas-private-client.html 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
The client credentials flow is used for Machine-to-machine connection. You don't really need `next-auth` for that, just make the call to the token endpoint, as stated in the spec: https://www.oauth.com/oauth2-servers/access-tokens/client-credentials/

**Comment by kirkegaard** [comment]
We are also trying to support client credentials along with other providers. Is there a way to stick the token from client credentials into next auth? Right now we're using the credentials provider and wrapping the flow in that but its a bit of a hack
