### ISSUE TITLE
Stuck on getSession

### ISSUE THREAD

**Issue by maxschau** [nextauthjs/next-auth#5206]
### Question 💬

The problem is that is is never ending, and thus makes the Next.js page load forever. 

I am using node version 16.13.0 and nexth-auth version 4.3.4. 

Has anyone experienced this?

### How to reproduce ☕️

`const session = await getSession(context);`

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by BouarourMohammed** [comment]
did you found a fix for this issue ?
