### ISSUE TITLE
unstable_getServerSession Not Updating Session After Redirect

### ISSUE THREAD

**Issue by joepetrillo** [nextauthjs/next-auth#5223]
### Environment

  System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.42 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh

  Binaries:
    Node: 16.16.0 - ~/Library/Caches/fnm_multishells/15888_1661372974805/bin/node
    npm: 8.11.0 - ~/Library/Caches/fnm_multishells/15888_1661372974805/bin/npm

  Browsers:
    Chrome: 104.0.5112.101
    Firefox Developer Edition: 104.0
    Safari: 15.6

  npmPackages:
    next: 12.2.5 => 12.2.5 
    next-auth: ^4.10.3 => 4.10.3 
    react: 18.2.0 => 18.2.0 

### Reproduction URL

https://github.com/joepetrillo/lone-link

### Describe the issue

![issue](https://user-images.githubusercontent.com/32227357/186794015-56c9373a-1917-4638-a7f2-969d56d361a8.png)

I am using the email login provider. I need usernames for my application, so I redirect users who do not have one to a setup profile page. This page simply does some validation of input and updates the name field in my db for the currently logged in user. (null by default) A user will always be redirected here until their name is not null or empty.

Once this completes, I redirect from this setup page to the dashboard page using next router. `router.push("/dashboard");`

Both the setup page and the dashboard page are getting the session on the server using `unstable_getServerSession`.

I then pass the session as a page prop and use `useSession()` to get the session. In the get `getServerSideProps` function I logged the session retrieved before passing it as a page prop.

See this video
https://user-images.githubusercontent.com/32227357/186795104-5a7b6eaf-c095-47a3-96eb-5fc1fb0b8905.mov

As expected the first session on the setup page has a null name
![image](https://user-images.githubusercontent.com/32227357/186794791-d407113b-9d41-45dd-b33f-3bcf2d2008a2.png)

When I redirect, the dashboard session gets the proper name and session.
![image](https://user-images.githubusercontent.com/32227357/186794838-c5340853-02b1-40d3-a324-e664a8af70cd.png)

However, on the page it does not appear correctly until I refresh.
![image](https://user-images.githubusercontent.com/32227357/186794898-4a0ac798-3168-4b3d-9263-7f02b332cb24.png)

I have been trying to figure this out for a while now, any help is greatly appreciated but I am thinking it could be a bug so wanted to report here.

Thanks!

### How to reproduce

Redirect from one page to another that both retrieve the session on the server side.

### Expected behavior

The dashboard page should not have to refresh to get access to the session.

**Comment by joepetrillo** [comment]
It seems adding the following event forces the session to refresh. 

```js
  const event = new Event('visibilitychange');
  document.dispatchEvent(event);
```

If I add this right before redirecting, it seems to work as a temporary workaround. Is there a more official way to make this work? All of the existing discussions I have found have lead me nowhere unfortunately.

**Comment by fivaz** [comment]
I have the same question

**Comment by ThangHuuVu** [comment]
Thanks for the detailed bug report @joepetrillo 
This does not seem like a `unstable_getServerSession` issue though, but more like a duplicate of #371 and maybe #596 🤔

**Comment by dellwatson** [comment]
it does still exist, im using credentials + google provider, i have followed with database strategy, setup cookie from signin callback, and jwt for session but once i disabled http cookie, noticed after redirect the cookie was removed.

**Comment by AveshLutchman** [comment]
This is still an issue. I have a redirect that's done by Stripe after the webhook is finished processing and it doesn't load the correct page. The object is also not the correct one, although the session callback returns the correct object.
