### ISSUE TITLE
getToken requires request to be passed but has params as optional

### ISSUE THREAD

**Issue by JohnMarsden24** [nextauthjs/next-auth#5226]
### Question 💬

The `getToken` function requires the `req` to be passed [which can be found in this line](https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/jwt/index.ts#L84) however the [function has a TS optional type](https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/jwt/index.ts#L69) which is incorrect.

### How to reproduce ☕️

Use `getToken` without passing any arguments and it will throw `"Must pass req to JWT getToken()"` error. If `params` wasn't optional you'd be able to catch this error before running.

With `params` as optional:

<img width="664" alt="Screenshot 2022-08-26 at 16 17 03" src="https://user-images.githubusercontent.com/55828757/186937835-ba830435-c31b-4eac-b91d-9c8726efbbc1.png">

Changing `params` to not optional (expected behaviour and done in my `node_modules`):

<img width="1015" alt="Screenshot 2022-08-26 at 16 18 59" src="https://user-images.githubusercontent.com/55828757/186938302-7ff260ed-be3c-4493-8c86-364b736082c2.png">

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by rashidmya** [comment]
can I do this?

**Comment by JohnMarsden24** [comment]
> can I do this?

Hey rashidmya I was actually gonna do this myself this weekend.
