### ISSUE TITLE
getToken returns null when raw=false, but works with raw=true

### ISSUE THREAD

**Issue by SharadKumar** [nextauthjs/next-auth#523]
**Describe the bug**
getToken returns null when raw=false, but works with raw=true.

This fails:
```js
  const token = await jwt.getToken({ req, secret, raw: false })
```
This works:
```js
  const tokenRaw = await jwt.getToken({ req, secret, raw: true })
```

**To Reproduce**
I am using JWT without database, custom encoding/decoding my token using my keys and `options.secret`. I am passing `options.secret` to `getToken` and it works as expected when `{raw: true}`. I am running **v3.1.0**.

**Expected behavior**
I should be able to getToken object.

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
What happens when you don't pass the `raw` option at all?

**Comment by SharadKumar** [comment]
Still the same... ie null (with or without `{raw: false}`.

**Comment by SharadKumar** [comment]
Not sure if it is related, but on the terminal I see:
```bash
[next-auth][warn][jwt_auto_generated_signing_key]  
https://next-auth.js.org/warning#jwt_auto_generated_signing_key
```

**Comment by iaincollins** [comment]
This is working (with or without a database) in the example project.

It includes a specific example of using getToken in a API endpoint:

* https://next-auth-example.now.sh/api-example
* https://github.com/nextauthjs/next-auth-example/blob/main/pages/api/examples/jwt.js

I would start with the example project and go from there.

If you'd like help, please provide additional details so we can replicate the issue.

**Comment by iaincollins** [comment]
Just picked up on something from your description!

> custom encoding/decoding my token using my keys

As per the documentation "[You must also pass any options configured on the jwt option to the helper.](https://next-auth.js.org/configuration/options#jwt)".

With Serverless, the config isn't shared between API endpoints so things like keys and/or encode/decode routines need to be passed into it explicitly (and unfortunately there isn't much we can do about that). 

This can a little verbose and awkward to maintain and you may want to create a helper function which wraps `getToken()` if you need to pass quite a few options.

**Comment by SharadKumar** [comment]
Well, I would expect the lib to encapsulate since the options has been passed and configured centrally at [...nextAuth]. `getToken` of the lib should be aware how the lib has been configured?

I'll wait for you comments. Meantime, I will see if I can figure a way. Thanks for the hint, I missed that line of documentation.

**Comment by SharadKumar** [comment]
Hi @iaincollins, I further check and found that my custom decode function is working, but getToken is not.

```js
decode: async ({ token, secret }) => {
      const signOptions = {
        algorithms: ["RS256"],
      }

      const decodedToken = jwt.verify(
        token,
        process.env.AUTH_PRIVATE_KEY.replace(/\\n/gm, "\n") || secret,
        // @ts-ignore
        signOptions
      )
      console.log('decodedToken', decodedToken)
      return decodedToken
    }
```

Following fails:
```js
const token = await jwt.getToken({ req, secret, raw: false })
console.log('token', token)
```

What am I missing? :-/

**Comment by SharadKumar** [comment]
ok, I resolved this by having my own getToken function, using custom decode that I had passed to next-auth. Thanks for the tip @iaincollins.

**Comment by mgnanaprakash11** [comment]
@SharadKumar Can you explain how you wrote the custom getToken function?

**Comment by sara-pourabbas** [comment]
this solution give me this token , what should i do?


eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..yJ2qkbVl-Ll4Wnp6.SFpWWioVkrxwizuVHr7Fhr-RfFBoY207dBU8pOvDoXxiqI9FQDh9QvzFUfcfRcbuVheOmgsiITEh0aBXSkmBTTf3sw3dfRJFnVCG09OHnv2qaU2M9PjNPLFayVv6lsH4hw-IAMy6t4ALwK2QaWet9Lxqes1jv1F_d-GYGUg3tRd1VyBkb9VOk63ONcXgtuvPvxY2iBKKSzEcHqH6DkDZmfgduvoMjtUzVNpn2D7Y2oXRn5OQT4AlmTn34RjdbgGkO_fovU9tKBkZxpL0JfcuwsrxkIXk4nk_3-UxT-C1vu06YYvDwWFc8HdK37nPSJ82u2bpOqfk7lfo20rmFebT1j0oYSdhrRvfmMrG8dBxse3FVUmNvdWCWJA-yzzw3INd7NCZbG7GXNQW0ePoekzwE7242fqxnUBCGiHXILLeILX_9QKzDX_NK3d4lkrSkzE-H8dYAWsMs467eC9mxLYJUpCrFcOYAyNgN1oh_TAid7BS0-cbv4P_0hWmhR40TWld52kdFaXZ0TLn4R8M9aAx1mnknDEwgnG4_m50d8FSgaZeq39gdtSCtTniD6J1cUdNahnprdAo-6LgttCAwLqNRp3f94FJRGzVKLoceHFRJBl3xHZ5w91bjcgjZaHZDz03F0Sb9CckayU2Fl2rOxmE_-Kl78MUMHnbe4YKd6Xwf0nT0d_ZL1PdTsKG_7gwr7WpDWpuZtHCD7MLILTP6EaQxEEbwVDZqw8tHAsUJml7emXw7v_Olh4utjo-635RO6R1py6pXk_QxXfv8lfNulvLM-7LmoqhYAUnUgYjPzmIhXuTQbTpGr5TyvIvMP_hHYFKlPPKz1vd67LTZ1DnFeuer8E895_WDW0S3T2wmA9s7Y1Vh-isCJ2BfEBMOJyDnR4Q0CxDMTb1rLXatUygiyIHuOGT4tsrrYeGIHptmCKFHBHKZlr4d_McIp9QK_UPcT_ritQom8YH55fIZ3DY-qCXRY21iPE-89Agj55RsgQkPOO17nKOMbt9z0V1T4FulcN9NeUA9dxwcNnxzv8vu2sr5yZFk8dU1KqGfiWAsAMmfNt2mnwvIT_5RgF2OQCJIn8-lxAvMS0Slyfyy9YuvULMGzLPPtWFlUl9CWcp7PL89tdIZwjUODPpWz7cNb_vpjVQMbsMCSOyESafiCfX4yCsBdb6GNbuESbFgewqodkQNfyehwL7bmU3WgAUz8_hYh0-lgAxIgr_QMeS0SW7BpKDZL3RCZoWFi1izo9-eVCj7IogNq5asq11DHo_HrANK_dDuJxxc-UuR145IojWEM2WHcoYahOjEpnP_PK4DQPXDvAqIMA45mgT-BfDuM4XmIplP5CeaQcWdZDUCr6V7wtGASFvfWcXv24o-pgr8jtAspuKSdWwcHjNALBpatJN8KLiRknDBXeNwFEOIz2Lpw3U4boaEzBhosAk273PrQyI6avrHeFGXj9aGQ3gaavYPLKHBdcNQkjhNHZ5tGbmXQNs4F8Hsda-7XUqCE-QG04gsaHI0LD_fSiRfLAZZG5hXlWNxWRjugB6czAfUcuzHAUhQ2b19ZvhBDaMzOOObMNU0Ho6jtFG0UXEZIL1PHjwj4qh53ovFEn93cm_OfSFDpSkmqKR2bcVX1KErKaGJ2dyLQ0ArHzHhmjmDYBFNGCsN5lrrMAB1JKTIM84MKg5Xz1N3MhnsI0owyU1U4aeSI4IBBM5_UfObpzA0_YWBCvFCuQQj828WcLXQWIdIMnrsv_HyaXOBpbQu40HKlwcL1aWt5mh2q4PREQQYTxoNGEjioU4IT7V_8Vcf3MxcwkJ1pJsvkWpdn8y0ab7FtQkldwUNkccEqJspwc_SwdhS3qbLbrz2mY7Auh7gV0WP4ce_7a93fW1cDuflw51S_gV_CzCtJaZfr4HIKSYRby7znzZ0EkEFBcnHNN2wovLcjCAzF4ECcOSVSuz2jLo4q1KdLkD5dZ-A6ZwSz3uOiRqDzfx_aiJvmSyBFGF-wl4rZi43CYqJlPuY_BwHaA-8RlWD3WPXTkCn2Hg3CRF9yrpIfVOdBRsO1tZgT8Iz1fxIiodEbhWO5NJUiq8FCzWJNFrx_ooNWwqBbZtXA9LJoDyJu39UYXHxbmTu8S2mjjIFQbnlRmi_I-tEamlmyhZkRggtG-L9amO0oTv8QneAQ0OqPyleUq-K8QFUQqfJ5T-0FBdUMWWUzQ-7SKxB2wEyuHLPtj4sn6juwyQKK1VBEYGsQJAiKaL-yRB3MT56585Ylm7EMh3FYAZEbVfy8bDq28-bDeJLssJJVEyr0rrJHNuPZ1nVWZIC4MUa4f4uIt1HXbKG1bKbtbSmOxWvy4kE5hEboCXYgI4Pjrx0RmJs8k-VBw-lrivIuHlT_mbxV_BcApup2XS5f3TxBKbnwXKjh585Vr1OEtD9FolzvdBq1Wqh2g0cz6a0SQwY8NUdyDx_UZMKV2xLA6C74L9Y19Nrxl4pgFzy7K8VzMLC4vdXvSeQy4Kf7ixUg_xh63EdDiYGLvXm3UHmf4GRU2fe5J1XWPXzZoEhsm7hynZDf3RqP8m-rexLiqDC5Y2UP5lbTrrGEaSDuN-MuznGVOHD3CarhBHrlcsMaxCk-rwzW730akEZhFcywN6-XqWrStf-Qz1V9-zLbWMcRJQtyq2aOlY6SVNouMJys9kHg6mEfFvxhugctFxwAzF57rTmued9i_KdvKPfNYxkC27qNzmlUAs6oXOzZ6SxTJXGdPL4ughJTxJymE-wLDIRWOWij33s6upKDqByUBgsty1241qBnhyIDiGHEfyLT-OoGEqyVLTofIUnH0nhSd9c6jSr4GdC0esuAqGUuxTXIUYZDbJ1GmG_Xj94yHyEH7t6lj0BqfxrV3Fh_kWq94z6jMWoQMFqrAwGvsaVY01DHeNUmGTJrPtA-M10Hda91ZiJIPB4geK0CuumiGUzdfqi7v4Vv_hn4p2sb9zMFtvdS0NkXoQNaZoGSwbQGuuC6qD16umruutE7XjnGKRaAUKyMt53-iQ73sQQICj0SyBlYBqbIArpNI16Bc7r83groFIDo_EpuZMsvlJBE6LawPfQxKyJmsKz0k9xeJjUwCg6UCyYO9W7r-cPa6cNBPWfzQmnQlJiQoWnmDD9H3l3-BxdT3whh5LCQTd7sg2fgv2GAyGhaUYGINTbSQ5KQLuqiy2tL-9gIBBFt0LMSB1yeUKNFsrJUFId0jOi8wK5LjZMjysmXjTR8uMWg2IrnoqvFjpcrzz7SqF-mTCqYa4hB4jHkEbImnASnquLqzaGTUj9kJYtDEuT6ueZNaqNKBBKaNxq8Llh1FK0S2UJPBK7DeyNfeL6lac6bXkurq1XCEvBtVqCjW-TXJJ_KzGYGrVUXiMbImVt-3KNigh-MYjmllXjK3fOx4tjZqTUexG42_9--ykQu8R-327nn19zXVFafrClXGSiQ3FvVDetP2g6XnKLCdAibSXysaozqWvKKSw7A1OYC62q1bUwXwV4n4KC5I-P49O-vaUNLk0rvG5LD8C7678BqTloPAqfrAYCwP6W7TvtF0cCgykNiPVNctU-aazDWcVOQOQrmW2AUcc_MfLZGiqUiDh00WUc82w7crkENEBMBEE7z-ZzHLzYUjKknYg2jrMtqbWxDs29p_QSbC3ip8WQNefPPK_egSUnOUIp2M_pTpG24bavseUjGglPUMbjPVytqPpIHuaUncP4V3AL7enCgukrWGRGLnXC_JvyDV6wzjhTw.IEd5NE4Z262_ebCdRBMLJA

**Comment by itsanishjain** [comment]
> n how you wrote the cu

It's simple

```
import * as jsonwebtoken from "jsonwebtoken";

  let jwtEncodedToken: string  | undefined =
    context.req.cookies["next-auth.session-token"];

  const token = jsonwebtoken.verify(
    jwtEncodedToken ?? "",
    process.env.NEXTAUTH_SECRET
  );

  console.log(token);

 ```
