### ISSUE TITLE
Make Event Names Less Confusing

### ISSUE THREAD

**Issue by FredLackeyOfficial** [nextauthjs/next-auth#5249]
### Description 📓

Current event names are misleading and cause the developer to assume a completely different tense.  For example, the name `createUser` implies an action to be completed (ie "go create the user" or "user is being created") when it is actually firing after the event has taken place.  Please rename the names of the events to specifically declare what has successfully happened, is about to happen, or has failed.  For example, this ...

```
events: {
  async signIn(message) { /* on successful sign in */ },
  async signOut(message) { /* on signout */ },
  async createUser(message) { /* user created */ },
  async updateUser(message) { /* user updated - e.g. their email was verified */ },
  async linkAccount(message) { /* account (e.g. Twitter) linked to a user */ },
  async session(message) { /* session is active */ },
}
```
... would become ...
```
events: {
  async signedIn(message) { /* on successful sign in */ },
  async signedOut(message) { /* on signout */ },
  async userCreated(message) { /* user created */ },
  async userVerfiied(message) { /* user updated - e.g. their email was verified */ },
  async linkAccounted(message) { /* account (e.g. Twitter) linked to a user */ },
  async sessionIsActive(message) { /* session is active */ },
}
```
Showing an event as past tense would have saved me at least a complete day of time.  The current names imply that there is still an opportunity affect a process when, in fact, the process has already completed.

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by ThangHuuVu** [comment]
Thanks for the suggestion, although I don't think we would come through with this. These changes are considered breaking and would add friction for the users to upgrade.

**Comment by CR1AT0RS** [comment]
I actually think we should add this info. in documents. This is so important.
