### ISSUE TITLE
MFA?

### ISSUE THREAD

**Issue by testerez** [nextauthjs/next-auth#5258]
### Question 💬

Hello,
From what I understand, it's possible to configure many providers, but then the user is able to login with any one of the configured providers.
Is there any way to require multiple authentification factors to get the user logged in?
For example, ask for a login+password, then ask for TOTP.

### How to reproduce ☕️

This is a general question

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by ThangHuuVu** [comment]
Duplicated of #5257, let's continue the discussion there @testerez !
