### ISSUE TITLE
Support for TypeORM Entity class syntax as well as Entity schema.

### ISSUE THREAD

**Issue by deep-c** [nextauthjs/next-auth#527]
**Summary of proposed feature**
Support for Entity class definition. https://typeorm.io/#/entities/what-is-entity

**Purpose of proposed feature**
Allows us to use this definition format which is a benefit gained from using typescript instead of forcing us to use schema definition format. This is an issue because if we want to create relations we cant do it since we cannot mix the two formats https://github.com/typeorm/typeorm/issues/3367.

**Detail about proposed feature**
This I am not 100% sure on. Easiest method would be to include ts and js separately and we can just import as required. Furthermore since the adapter seems to have logic surrounding wrapping it in EntitySchema we would probably want to make changes there such that the user select which they would like to pass in and we dont rely on wrapping the models https://github.com/nextauthjs/next-auth/blob/main/src/adapters/typeorm/index.js#L20-L39. (This isn't very DRY though i admit and would require any changes to entities to be reflected in javascript and typescript files separately.

**Potential problems**
Rest of the adapter code can work interchangeably around both definitions? E.g Instantiation of new models.

**Describe any alternatives you've considered**
If adapter is the issue and we cant easily have it function easily between both definitions maybe we can have multiple? The current and another for class definition format. We would either require the user to specify which one to use based on their knowledge of what is being passed in or if we can programatically check based on the custom models we could switch automatically?

**Additional context**
Currently the use of plan javascript requires the use of [entity schema definition](https://typeorm.io/#/separating-entity-definition/defining-schemas). If we define custom models we need to follow the same and cant use [Entity class definition](https://typeorm.io/#/entities/what-is-entity) e.g if we choose Typescript and wish to use this model definition. After attempting to mix the two it seems like it is not possible as per [this thread](https://github.com/typeorm/typeorm/issues/3367) (ive left a comment to see if this is still the case seeing as it is from 2019).

*Willing to help.*

On an unrelated note, i just noticed that there is no relations enforced between the various tables. Is there a reason this wasnt done?

**Comment by amosbastian** [comment]
@deep-c what did you end up doing about this? I am having the same problem 😞
