### ISSUE TITLE
Dynamic routes in middleware don't work

### ISSUE THREAD

**Issue by ArkShocer** [nextauthjs/next-auth#5275]
### Environment

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 6.49 GB / 15.96 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.7.0 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.70)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    next: 12.2.5 => 12.2.5
    next-auth: ^4.10.3 => 4.10.3
    react: 18.2.0 => 18.2.0

### Reproduction URL

https://codesandbox.io/s/dazzling-volhard-0f1490

### Describe the issue

When adding an dynamic route to the middleware to require authentication when visited, it should not be accessible without authenticated.

Below my current config locally
```js
export { default } from "next-auth/middleware";

export const config = { matcher: ["/", "/release", "/release/:releaseId"] };
```

In the attached sandbox the static url is blocked as expected but the dynamic url is not.

- https://0f1490.sse.codesandbox.io/ - Blocked
- https://0f1490.sse.codesandbox.io/test/2 - Works

### How to reproduce

1. Create middleware file and setup next-auth with dynamic routes.
2. Visit the dynamic route.
3. See error.

### Expected behavior

When dynamic route is visited, redirect to auth page.

**Comment by jacktfliu** [comment]
Same here.

**Comment by ThangHuuVu** [comment]
Seems to be an upstream problem as 12.2.4 works just fine. cc @balazsorban44

**Comment by balazsorban44** [comment]
To match a dynamic URL for more than one level, you need to add the `*` or `+` as shown here: 

https://nextjs.org/docs/advanced-features/middleware#matcher

Better documentation for this is already merged, but not yet available on the Next.js docs site:

https://github.com/vercel/next.js/pull/40180/files#diff-2516f31bc91e81148f1e64f23932cc69827e7774cfa5d6de4550bede2787b77fR96-R97

**Comment by ArkShocer** [comment]
To my understanding the line "can include named parameters: `/about/:path` matches `/about/a` and `/about/b` " would mean that the sandbox config  `["/", "/test", "/test/:id"]` matches `/test/1` and `/test/2` or `/test/a` and `/test/b` since the path `/test` is static and not dynamic. So there is something wrong with next-auth no?
