### ISSUE TITLE
Ability to pass extra parameters using client signIn to server for use in callback

### ISSUE THREAD

**Issue by camsloanftc** [nextauthjs/next-auth#528]
**Summary of proposed feature**
I may be missing if this is already possible. I dug around the code/docs a bit to see, but couldn't find anything.

It would be great to be able to pass additional fields to the client `signIn` function, so they can be accessed in the `signIn` callback. 

For example, if I want to sign up a new user with custom fields other than just the email (first name, last name, billing, etc), then I could pass them into the signIn. This would probably be relevant for anyone using custom user models.

**Purpose of proposed feature**
This would avoid the need to create a separate server function to create a user outside of the framework.

**Detail about proposed feature**
It looks like that would be only need to be handled on the server [here](https://github.com/nextauthjs/next-auth/blob/8115a7c66cdb1d86b0d2a0d76b9aa33c2bfaa33b/src/server/routes/signin.js#L46-L54).

It appears that the client sign in function is [already passing all the additional params to the request](https://github.com/nextauthjs/next-auth/blob/8115a7c66cdb1d86b0d2a0d76b9aa33c2bfaa33b/src/client/index.js#L246).

**Describe any alternatives you've considered**
I have considered creating a separate "register" or "sign up" endpoint (outside of the framework) to pass in additional details upon registration. I have not fully thought this through though.

**Additional context**
Related issues:  #312, #283

*Please indicate if you are willing and able to help implement the proposed feature.*
I could help with this, but I am not sure if I understand the full scope (ex: other providers that are not "email").

**Comment by camsloanftc** [comment]
I think #543 would fix this as well (being able to access the req in the callbacks).

Being able to access the original request in the signIn callback (and other callbacks) would mean we could pass additional properties from the sign up form.

**Comment by iaincollins** [comment]
Currently it wouldn't be possible to return a user object in a way to have detailed persisted in a database - there is a fair bit of complexity associated with doing this and is tricky to support across different adapters.

If using the Credentials Provider, users are not persisted in a database by NextAuth.js anyway, so using the `signIn()` callback as it is (which is have all the data from the form) to persist the data somewhere is currently possible and should work well.

---

It can be hard to know where the tipping point is between if NextAuth.js is useful or not when you don't need OAuth or Email sign in. It can still be useful as a framework for handling sessions and abstracting JWT, but the benefits of it are more marginal if you end up needing to write a lot of the flow yourself.

To work well with social sign in (which has less friction to sign up and to sign in again) I'd usually suggest a flow where users can sign in *then* are prompted to provide billing details before they can interact with the app (e.g. by calling a custom endpoint like `/api/user` that returns a property like `{ billing: true }` or adding a flag to the session object…).

**Comment by camsloanftc** [comment]
Got it - thanks. Yeah I am still getting up to speed with the library, but I am noticing it requires a different way of thinking from what I am used to. Luckily, I am pretty early stages of this app so it is still flexible to switch the workflow to something like you're suggesting (sign up first, then provide details on a next screen). 

That said, I am eagerly watching #541 to see if there is a way I can at least keep the user in the same browser window to persist some state on the client from before the user signs up, which would also give me another way to solve the problem.

I do like the idea of using NextAuth because there will be some integration pieces with external providers as well in other parts of the application, and overall it's a nice DX, but you may be right that it's not the right fit and I can find a way to use Passport or something else instead.

Thanks for taking the time on this. We can close this out since it sounds like it is a large piece of work and not in line with the roadmap.

**Comment by iaincollins** [comment]
@camsloanftc Thanks for the feedback! I'm looking forward to getting that PR in too!

I'd be interested in any feedback if you come to any conclusions about how it might be better out of the box for a flow where you want to make sure you capture something like billing details before letting a user continue on a journey - I think that's a fairly common scenario we have had folks ask about in the past.

(Whether that ends up as a feature request to add something to make it easier, or if it just ends up just being a tutorial.)

**Comment by camsloanftc** [comment]
Yeah I think there will still be some challenges, but that PR should make it a bit easier by keeping the user in the same browser window (instead of potentially receiving the email and signing in on another device).

If that PR adds those client methods you mentioned (being able to validate the token client-side without redirects), you can be confident in maintaining state in the react side of things and sending a separate api call after registration, or doing whatever you want outside of the library, really. Without that ability, I am not really sure how I would go about this.

I will keep you posted as this comes together, and potentially make a video or blog post that could be referenced if the question keeps coming up.
