### ISSUE TITLE
Next-auth: Access token not refreshing when site is left idle

### ISSUE THREAD

**Issue by AnmolSaini16** [nextauthjs/next-auth#5281]
### Question 💬

So I am using keycloak as my provider where access token lifespan is 5 mins and refresh token is 30 mins. When I am using the application everything is working fine: Access token refreshes after every 5 mins whch in turn refreshes the refresh token each time.
The problem arises when I switch the to another tab or do some other stuff leaving the application tab, the access token stops getting called in the background, so it doesn't refresh the refresh token and throws error which in turn logs out the user when the refresh token expires.
Which shouldn't be the case, if user comes back after more than 30 mins he/she should be logged in till the session is not expired.

In [...nextauth].ts
```ts

const refreshAccessToken = async (token: JWT) => {
    try {
        if (Date.now() > token.refreshTokenExpired) {
            console.log('Error thrown');
            throw Error;
        }
        const details = {
            client_id: process.env.KEYCLOAK_AUTH_CLIENT_ID,
            client_secret: process.env.KEYCLOAK_AUTH_CLIENT_SECRET,
            grant_type: 'refresh_token',
            refresh_token: token.refreshToken
        };
        const formBody: string[] = [];
        Object.entries(details).forEach(([key, value]: [string, any]) => {
            const encodedKey = encodeURIComponent(key);
            const encodedValue = encodeURIComponent(value);
            formBody.push(encodedKey + '=' + encodedValue);
        });
        const formData = formBody.join('&');
        const url = process.env.KEYCLOAK_AUTH_TOKEN_URL || '';
        const response = await fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'
            },
            body: formData
        });
        const refreshedTokens = await response.json();
        if (!response.ok) throw refreshedTokens;
        return {
            ...token,
            accessToken: refreshedTokens.access_token,
            accessTokenExpired: Date.now() + refreshedTokens.expires_in * 1000,
            refreshTokenExpired: Date.now() + refreshedTokens.refresh_expires_in * 1000,
            refreshToken: refreshedTokens.refresh_token ?? token.refreshToken
        };
    } catch (error) {
        console.log('Token expired');
        console.log(error);
        return {
            ...token,
            error: 'RefreshAccessTokenError'
        };
    }
};

export const authOptions: NextAuthOptions = {
    providers: [
        KeycloakProvider({
            clientId: process.env.KEYCLOAK_AUTH_CLIENT_ID || '',
            clientSecret: process.env.KEYCLOAK_AUTH_CLIENT_SECRET || '',
            issuer: process.env.KEYCLOAK_AUTH_ISSUER,
            requestTokenUrl: process.env.KEYCLOAK_AUTH_TOKEN_URL,
        })
    ],
    secret: process.env.NEXTAUTH_SECRET,
    pages: {
        signIn: '/auth/signin',
        signOut: '/auth/signout',
        error: '/auth/error'
    },
    callbacks: {
        async jwt({ token, user, account }) {
            if (account && user) {
                // Add access_token, refresh_token and expirations to the token right after signin
                token.accessToken = account.access_token;
                token.refreshToken = account.refresh_token;
                token.accessTokenExpired = account.expires_at * 1000;
                token.refreshTokenExpired = Date.now() + account.refresh_expires_in * 1000;
                token.user = user;
                return token;
            }

            // Return previous token if the access token has not expired yet
            if (Date.now() < token.accessTokenExpired) {
                return token;
            }

            // Access token has expired, try to update it
            return refreshAccessToken(token);
        },
        async session({ session, token }) {
            session.user = token.user;
            session.accessToken = token.accessToken;
            session.error = token.error;
            return session;
        }
    }
};
export default NextAuth(authOptions);
```

In _app.tsx

 ```tsx
  <SessionProvider
                            session={session}
                            refetchInterval={4 * 60} // Refetch session after every 4 mins so that session doesn't expire.
                            basePath={process.env.NEXTAUTH_URL}
   >
```

### How to reproduce ☕️

Use Keycloak provider in next-auth provider, set the access token and refresh token life span. Leave the website and move to another tab. Access token will not refresh itself in background.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by AnmolSaini16** [comment]
@balazsorban44 Please look into it.

**Comment by ThangHuuVu** [comment]
We're working on the fix for this issue in https://github.com/nextauthjs/next-auth/pull/4940

**Comment by peterburgs** [comment]
Does anybody have a new update on this issue?

**Comment by Ali-hd** [comment]
> Does anybody have a new update on this issue?

Not sure if this helps but there is a prop you can add to the SessionProvider that does "A time interval (in seconds) after which the session will be re-fetched. If set to 0 (default), the session is not polled."

`<SessionProvider session={session} refetchInterval={60}>`

**Comment by HeliosAiden** [comment]
I'm having the same problem with this. Anyone has any update on this issue ?

**Comment by swag-overflow** [comment]
Still an open issue in v4.24.5.

Is this already fixed in another Issue?

**Comment by sudipta9** [comment]
Is there any update on this issue? Has a fix been implemented or is there a workaround available? Your guidance would be greatly appreciated

**Comment by hanzlahabib** [comment]
why on this earth it's not fixed yet, almost 2 years

**Comment by hanzlahabib** [comment]
```
<SessionProvider
  refetchInterval={60}
  refetchOnWindowFocus={typeof navigator !== "undefined" && navigator.onLine}
  refetchWhenOffline={false}
>
```
for future devs, read this https://github.com/nextauthjs/next-auth/issues/4935

**Comment by hanzlahabib** [comment]
Anyone still struggling to solve the issue, 
here is the gist you can use

https://gist.github.com/hanzlahabib/063abc143c768e418068625e2129493f

These are the steps to follow:
1-  Setup auth.ts file
2- Set SessionProvider refetchInterval settings
```
<SessionProvider
  refetchInterval={60}
  refetchOnWindowFocus={typeof navigator !== "undefined" && navigator.onLine}
  refetchWhenOffline={false}
>
```
3- Set AuthStatusHandler, purpose of this handler is to check for error and redirect user to home page after logging out here is the AuthStatusHandler example

```
const AuthStatus = () => {
  const { data: session, status } = useSession()

  useEffect(() => {
    if (status !== 'loading' && session?.error === 'refreshAccessTokenError') {
      console.error('Refresh access token error, signing out...')
      signOut({ callbackUrl: '/' })
    }
  }, [session, status])

  return null
}


export default AuthStatus

```
import and place this inside _app or layout file
```
                <AuthStatus />

```


last workaround for session idle time not getting updated, set SSO idle time to 1 day or 30 days, now whenever user will hit timeout, it will automatically sign out user with the help of AuthStatus component.

I hope it might help someone struggling with this issue

**Comment by AnmolSaini16** [comment]
So here is the update on the issue. After updating the next-auth to v4.5.0, polling works fine if the tab is idle. I had set the `refetchInterval={5 * 60}` for testing and the session is polled in the background even if the tab is inactive.

One thing to note is that in the development build the polling is not happening when the tab is idle/inactive, but works fine in the production build.
