### ISSUE TITLE
mikro-orm default entities generate invalid schema via SchemaGenerator

### ISSUE THREAD

**Issue by Smona** [nextauthjs/next-auth#5286]
### Adapter type

@next-auth/mikro-orm-adapter

### Environment

  System:
    OS: Linux 5.10 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 18.16 GB / 31.13 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.20.0 - /nix/store/39z22pznwgjnzapm8c5379jgvp32yphw-nodejs-slim-14.20.0/bin/node
    Yarn: 1.22.19 - /nix/store/k6iha4jjq7adinsb6zclrjphcq9cs42z-yarn-1.22.19/bin/yarn
    npm: 8.18.0 - ~/.nix-profile/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  Browsers:
    Chromium: 104.0.5112.101
    Firefox: 104.0.1
  Dependencies:
    "next-auth": "4.10.3",
    "@next-auth/mikro-orm-adapter": "2.0.1",
    "@mikro-orm/*": "5.4.0"

### Reproduction URL

https://github.com/nextauthjs/next-auth/blob/main/packages/adapter-mikro-orm/src/entities.ts

### Describe the issue

I've been migrating my project to mikro-orm, so I was very pleased to see a new mikro-orm adapter is available!

However, after setting up the adapter and adding the `defaultEntities` to my mikro-orm config, I get the following (sanitized) error when I try to register an account in Postgres:

```
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error insert into "account" ("access_token", "expires_at", "id", "id_token", "provider", "provider_account_id", "scope", "token_type", "type", "user_id") values ('...', 1662361291, '...', '...', 'google', '109203427630182308627', 'https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile openid', 'Bearer', 'oauth', '...') 
returning "id" - invalid input syntax for type smallint: "oauth"
    at PostgreSqlExceptionConverter.convertException (/home/smona/dev/syne/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
    at PostgreSqlExceptionConverter.convertException (/home/smona/dev/syne/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:42:22)
    at PostgreSqlDriver.convertException (/home/smona/dev/syne/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:192:54)
    at /home/smona/dev/syne/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:196:24
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async PostgreSqlDriver.nativeInsert (/home/smona/dev/syne/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:222:21)
    at async ChangeSetPersister.persistNewEntity (/home/smona/dev/syne/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:85:21)
    at async ChangeSetPersister.executeInserts (/home/smona/dev/syne/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:29:13)
    at async ChangeSetPersister.runForEachSchema (/home/smona/dev/syne/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:68:13)
    at async UnitOfWork.commitCreateChangeSets (/home/smona/dev/syne/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:680:9)
```

I took a look at the generated schema, and indeed the `type` field is being defined as a smallint, when it should be varchar or similar.

Looking at the [mikro-orm docs](https://mikro-orm.io/docs/defining-entities#enums), they mention that string enums must be handled specially to ensure their values can be discovered. It appears those steps weren't followed in [the entity definitions](https://github.com/nextauthjs/next-auth/blob/main/packages/adapter-mikro-orm/src/entities.ts), which might be the source of this error.

I also noticed that the `ProviderType` specified is a string union rather than an Enum. That also appears to be a problem, since when I tried overriding the default `Account` entity like so:

```
const { Account } = defaultEntities;

@Entity()
export class MyAccount extends Account {
  @Enum(() => ProviderType)
  type!: ProviderType;
}
```

Typescript complains that `2693   'ProviderType' only refers to a type, but is being used as a value here.`

### How to reproduce

1. Create a basic example next-auth project with the mikro-orm adapter on a fresh database.
2. Pass the `defaultEntities` in `mikro-config.ts#entities`, and set up the mikro cli with that config.
3. Run `npx mikro schema:update -r` to synchronize the database schema.
4. Try to login with the google provider.
5. After the auth callback is fired, you should get the same error.

### Expected behavior

The default entities provided by the adapter should work with the official mikro-orm SchemaGenerator.

I will try to patch around this and update once I find something that works, but I'm still very much a mikro noob so any help from the maintainers would be appreciated :heart:

**Comment by Smona** [comment]
Update: I ran into some trouble setting a custom `Account` entity, because it broke the `User.accounts` `mappedBy` field.

After manually updating the `type` field to "text", I get another error because "id_token" is defined as a VarChar(255), but the id_token i get back from google is longer than 255 characters. Fortunately this error would be a simple one to migrate.

Once I updated both of these fields to be of type "text", i'm successfully able to create a user, account, and session with the `GoogleProvider`.

**Comment by boredland** [comment]
As I see it, we'd have to solve multiple problems here:

1. make Account.type a string union, as the type coming from next-auth is just that and there isn't a great benefit in providing an enum there.
2. make Account.id_token a text field

Will do that in #5316
