### ISSUE TITLE
Custom OAuth Provider doesn't use the the well-known authorization_endpoint

### ISSUE THREAD

**Issue by geniusit** [nextauthjs/next-auth#5305]
### Provider type

Custom provider

### Environment

 System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 3.13 GB / 15.86 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 104.0.5112.102
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.27)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    next: 12.2.5 => 12.2.5
    next-auth: ^4.10.3 => 4.10.3
    react: 18.2.0 => 18.2.0

### Reproduction URL

https://github.com/geniusit/nextauthissue

### Describe the issue

Using a custom OAuthProvider, the wellKnown URL value doesn't seem to be used.
When I click on the SignIn button, Im redirected to the default built in custom provider login page with this URL : 
http://localhost:3000/api/auth/signin?callbackUrl=http%3A%2F%2Flocalhost%3A8080%2Foidc-redirect_uri

![image](https://user-images.githubusercontent.com/3659037/188959801-d9d629fc-28d1-4bf5-9e22-106120f03c2f.png)

 

### How to reproduce

1) Create a nextjs application and add the nextauth dependency
2) Create the [...nextauth].js file
3) Add a custom provider : 

```js
import NextAuth from "next-auth"
export default NextAuth({
  providers: [
    {
        id: 'myprovider',
        name: 'MyProvider',
        type: 'oauth',
        version: "2.0",
        wellKnown: 'https://mycustomdomain.com/openam/oauth2/IDP/.well-known/openid-configuration',
        authorization: { params: { scope: "profile", response_type: "code", client_id: "myclientid", redirect_uri: "http://localhost:8080/oidc-redirect_uri" } }
    }
  ],
})
```

4) Go to localhost:3000 and click to the signin button

### Expected behavior

For SSO, I expect when I click on the SignIn button to be redirected to the "authorization_endpoint" of the well-known json object.
After I click to authorize, I need to be redirected to the redirect_uri

**Comment by balazsorban44** [comment]
Being a custom provider should not affect this behavior. You don't need to set `response_type`, `client_id` and `redirect_uri` in the `authorization` config, those are inferred.

Example: https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/providers/auth0.ts

`callbackUrl` is documented here: https://next-auth.js.org/getting-started/client#specifying-a-callbackurl
