### ISSUE TITLE
Help on callback url

### ISSUE THREAD

**Issue by geniusit** [nextauthjs/next-auth#5308]
### Question 💬

Using custom OAuth provider, does the callback url **must** respect this format : [origin]/api/auth/callback/[provider] ?

As described [here](https://next-auth.js.org/configuration/providers/oauth#how-to)

May I use the callbackurl of my choice like http://localhost:3000/foo ?

As described [here](https://next-auth.js.org/getting-started/client#specifying-a-callbackurl)

Here is my conf : 

```js
providers: [
    {
        id: 'customprovider',
        name: 'Customprovider',
        type: 'oauth',
        wellKnown: 'https://mydomain.fr/openam/oauth2/IDP/.well-known/openid-configuration',
        authorization: { params: { scope: "profile" }},
        clientId: "myclientid",
    }
  ],
```

I have this button : 

```js
<button onClick={() => signIn("sncf", { callbackUrl: 'http://localhost:3000/oidc-redirect_uri' })}>Sign in</button>
```

When I click on it, the redirect_uri query params is : &redirect_uri=http://localhost:3000/api/auth/callback/customprovider

why not &redirect_uri=http://localhost:3000/oidc-redirect_uri

For custom oauth provider, the callback url seems to be ignored ... why ? 

### How to reproduce ☕️

Create a sample project with custom oauth provider definition

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Hi, the `callbackUrl` is the URl you want the user to be redirected to after login, and not the same as the callback URL for the Identity Provider used during the OAuth sign-in flow.

You can set `callbackUrl` to anything, by default it will return the user to the same page they started on.

See the docs: https://next-auth.js.org/getting-started/client#specifying-a-callbackurl


We might want to rename `callbackUrl` to something like `redirectTo` in the future to avoid this confusion.
