### ISSUE TITLE
How can I save user accepted language in DB

### ISSUE THREAD

**Issue by testerez** [nextauthjs/next-auth#5320]
### Question 💬

Hello,
Im using next-auth with the prisma adapter.
When a new user is created, I'd like to get the preferred language from `Accept-Language` header, and then store it to the `User` table. Ideally, I'd also like to get this `language`  back in `session.user`
I'm not sure what is the best approach to achieve that...

### How to reproduce ☕️

-

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by testerez** [comment]
I think I have a solution that could work:
1- Use [advanced-initialization](https://next-auth.js.org/configuration/initialization#advanced-initialization) so I can access the request easily
2- Override `createUser` and `getUser` from `prisma` adapter, so I can store/read the user's language
3- Update `session` callback to send the user's locale to the app

Does that seam like the right approach?

**Comment by balazsorban44** [comment]
Advanced initialization would be the way to go IMO. 👍
