### ISSUE TITLE
OAuthAccountNotLinked

### ISSUE THREAD

**Issue by lienista** [nextauthjs/next-auth#5324]
### What is the improvement or update you wish to see?

"OAuthAccountNotLinked: If the email on the account is already linked, but not with this OAuth account"

1. This explanation is super confusing as whether the account is linked where? Your documentation says linking account is  NOT automatic, but here it says it's already linked. 
2. In addition to providing an description, please describe where the issue might be related to. Nowhere in the documentation this library talks about tables "users" and "accounts", yet the explanation was that they need to be connected when I ran into this error. I still don't understand how to "connect" them. do all fields/columns have to match between the 2 tables? if so, which one? how are you linking the 2 tables together?
3. what are best practices of designing accounts table and users table? which fields are required and which fields have to be foreign key'ed
4. describe an example use case where this can happen
5. please refrain from using jargons such as "link", as it's a really broad keyword. If you mean, this email address or user id or token or whatever it is that you checked and it already exists, then just say it. Normal devs like us don't understand what you're referring to, which might be clear to you since you've been working on this project for a while. 

### Is there any context that might help us understand?

explanation terse, not clear. for someone who's a first time implementing this and running into these errors, we need a more concise way to fix the error, not just what the error is. 

### Does the docs page already exist? Please link to it.

[_https://next-auth.js.org/configuration/pages#sign-in-page_](https://next-auth.js.org/configuration/pages#sign-in-page)

**Comment by ThangHuuVu** [comment]
Thanks for the feedback! To answer your questions:

1. Account linking happens automatically if the user already has a session. I don't think it's documented anywhere, though it's hinted at in the FAQ https://next-auth.js.org/faq#security. I agree that it could be improved 🙌 PR welcomes.
2. Perhaps you were looking for this page? https://next-auth.js.org/adapters/models/ We describe the DB models in-depth here.
3. Same as 2
4. There is an explanation for this scenario in the FAQ: https://next-auth.js.org/faq#security, secondary item
5. Account linking is a pretty standard way to describe this scenario, even big IDPs use it: https://auth0.com/docs/manage-users/user-accounts/user-account-linking. So I think it's fine here 🤷‍♂️

We're in the middle of a big doc refactoring #4498, so any input is valuable ✌️ cc @lluia
