### ISSUE TITLE
Twitter OAuth1 and OAuth2 not working

### ISSUE THREAD

**Issue by treasureseth** [nextauthjs/next-auth#5342]
### Provider type

Twitter

### Environment

 System:
    OS: Linux 5.10 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900KF
    Memory: 13.96 GB / 15.54 GB
    Container: Yes
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.1 - /usr/local/bin/npm
  npmPackages:
    next: 12.3.0 => 12.3.0
    next-auth: ^4.10.3 => 4.10.3
    react: 18.2.0 => 18.2.0

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

Our code is exactly the same as the examples in the NextAuth docs.

```js
export const authOptions: NextAuthOptions = {
  // Include user.id on session
  callbacks: {
    session({ session, user }) {
      if (session.user) {
        session.user.id = user.id;
      }
      return session;
    },
  },
  // Configure one or more authentication providers
  adapter: PrismaAdapter(prisma),
  providers: [
    DiscordProvider({
      clientId: env.DISCORD_CLIENT_ID,
      clientSecret: env.DISCORD_CLIENT_SECRET,
    }),
    TwitterProvider({
      clientId: env.TWITTER_CLIENT_ID,
      clientSecret: env.TWITTER_CLIENT_SECRET,
      version: "2.0"
    }),
    // ...add more providers here
  ],
};

export default NextAuth(authOptions);
```

When we have OAuth V2 configured, we get this error:
![Twitter-auth](https://user-images.githubusercontent.com/110566281/189954186-2ce5aca9-ebc0-4820-87e6-604f6195e289.png)

And when we try OAuth V1 (by removing the `version` in the code above), we get this error log:
```
event - compiled client and server successfully in 40 ms (349 modules)
[next-auth][error][OAUTH_V1_GET_ACCESS_TOKEN_ERROR]
https://next-auth.js.org/errors#oauth_v1_get_access_token_error undefined {
  statusCode: 403,
  data: '{"errors":[{"message":"You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve","code":453}]}\n'
}
[next-auth][error][OAUTH_CALLBACK_ERROR]
https://next-auth.js.org/errors#oauth_callback_error undefined {
  statusCode: 403,
  data: '{"errors":[{"message":"You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve","code":453}]}\n'
}
```

### How to reproduce

Try Twitter OAuth V1 or OAuth V2 using the NextAuth example code

### Expected behavior

Should login successfully

**Comment by balazsorban44** [comment]
Nothing changed in recent versions. I tested this locally just now, and everything works fine.

You can test it out on the deployed version here

https://next-auth-example.vercel.app/

🤔 please double check your Twitter configuration.
