### ISSUE TITLE
how to getSession() to return full user object

### ISSUE THREAD

**Issue by daveyand** [nextauthjs/next-auth#535]
**Your question**
When i use getSession() the user part only has email, name, image. Is there a way to also get id too? 

**What are you trying to do**
I have created the users table as per your schema and i have also created a UserDetails table to store additional information about user, things like bio etc... I have a FK on the user_id on the UD table. But because i only get the email from the session i have to `select * from users where email = ''` and then `select * from userdetails` (or i can do it in a join, obvs) if i had the user_id i wouldnt need either the join or two queries. 

So, how can i get either the full user object in the session, or just add in the user_id to the session too. 

Or am i using this incorrectly? 

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ x] Could not find relevant documentation
* [x ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by daveyand** [comment]
ok, i did a deeper dive into the documentation and came acrtoss the callbacks option. 

```
callbacks: {
      /**
       * @param  {object} session      Session object
       * @param  {object} user         User object    (if using database sessions)
       *                               JSON Web Token (if not using database sessions)
       * @return {object}              Session that will be returned to the client
       */
      session: async (session, user, _sessionToken) => {
        session.user.id = user.id;
        return Promise.resolve(session);
      },
    },
```

that will do what i want.

**Comment by iaincollins** [comment]
Thanks for following up with an example of how to do it!

We still get asked this a lot as it's not obvious until you get to the callbacks page, if anyone wants to write up a tutorial to show how to do this (and consume it from an API route) that would be 🔥!

**Comment by mcavaliere** [comment]
@iaincollins Looks like this is no longer possible in 3.1.0. The session callback seems to only return `email`, `user` and `image`. I do notice that the `signIn` hook returns the user's Google id in both the `account` and `profile` variables, but these don't seem to be available to the `session` callback. 

Tested with Google as a provider, both with and without database integration. 

Do you know of another way to achieve this for 3.1.0?

**Comment by balazsorban44** [comment]
@mcavaliere please check out the jwt callback as well

https://next-auth.js.org/configuration/callbacks

**Comment by mcavaliere** [comment]
@balazsorban44 thanks! Managed to figure this out, was a configuration issue on my end.

**Comment by trivektor** [comment]
@mcavaliere how did you solve it?

**Comment by thongphamvn** [comment]
@trivektor You may want to check this https://github.com/nextauthjs/next-auth/discussions/536#discussioncomment-154389, note that the `user` object is only available on sign in

**Comment by GourabSanyal** [comment]
Just a suggestion: it depends on the provider too, as they control what kind of user information they will let you have; e.g., api keys from Twitter's free dev account will not provide the `email` of the user. It really varies from case to case.
