### ISSUE TITLE
How to get userId on api Endpoints while using next-auth

### ISSUE THREAD

**Issue by youngnishant** [nextauthjs/next-auth#536]
*Please refer to the [documentation](https://next-auth.js.org/getting-started/introduction), the [example project](https://github.com/iaincollins/next-auth-example) and existing issues before creating a new issue.*

**Your question**
How to get userID on api Endpoints while using next-auth ?
**What are you trying to do**
A description of what you are trying to do.
While fetching data from mongodb atlas i want to use populate which requires UserID.

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Found the example project helpful
* [x] Could not find relevant documentation
* [ ] Did not find the example project helpful

**Comment by yuyao17** [comment]
```
const session = await getSession({ req });

session.id // userId
```

Is this it?

**Comment by nyedidikeke** [comment]
May be related to #535.

**Comment by yuyaoiwa-houzz** [comment]
oh yeah. thats what I did as well, forgot that part.
tldr:

in [...nextauth].js:
```
callbacks: {
   session: async (session, user) => {
      session.id = user.id
      return Promise.resolve(session)
}
}
```

**Comment by youngnishant** [comment]
@yuyaoiwa-houzz  -- still getting error 

[next-auth][error][SESSION_ERROR] [
  TypeError: Cannot read property 'id' of undefined
      at Object.session (webpack-internal:///./pages/api/auth/[...nextauth].js:32:25)

**Comment by youngnishant** [comment]
@nyedidikeke I'm getting user as undefined

**Comment by ndom91** [comment]
@youngnishant can you please post the relevant code?

**Comment by youngnishant** [comment]
callbacks: {
   session: async (session, user) => {
      console.log(user)
      return Promise.resolve(session)
}
}

@ndom91

**Comment by yuyao17** [comment]
Maybe your DB isnt configured correctly?

**Comment by youngnishant** [comment]
@yuyao17 actually I'm using mongodb and checked it, it's working properly

**Comment by benoror** [comment]
Hey @youngnishant I am facing the exact same issue, can't fin the _id anywhere. Did you end up fixing it?

**Comment by benoror** [comment]
Note: If I disable `jwt` it does indeed include the `id` in the session

**Comment by youngnishant** [comment]
@benoror I've implemented my own jwt authentication by taking proper security measures ✌️

**Comment by youngnishant** [comment]
Just try to use both localstorage and cookies to verify on backend. It'll make it more secure.
