### ISSUE TITLE
what about allowing us add some searchParams to callbackUrl?

### ISSUE THREAD

**Issue by LiuN1an** [nextauthjs/next-auth#5373]
### Description 📓

We don't use email action flow first and allow users to write their username before oauth (we can promise that username is not duplicate in this step). I wanna to push the username to the callbackurl in the redirect_uri sent to oauth's authorize end point. But why it will be limited to use 'url.origin' to callbackUrl and can not be customizable.

### How to reproduce ☕️

![image](https://user-images.githubusercontent.com/22864091/190869628-ec8f65a4-f51f-4755-89e9-4288a1202385.png)

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by ThangHuuVu** [comment]
Hi there 👋 This is just the default value, we have a function called [`createCallbackUrl`](https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/core/lib/callback-url.ts) that takes care of the URL creation with params, so redirection with params will work.
