### ISSUE TITLE
Twitter Provider Access Tokens Do Not Work

### ISSUE THREAD

**Issue by rprend** [nextauthjs/next-auth#5383]
### Provider type

Twitter

### Environment

Using Chrome. 

```
  System:
    OS: macOS 11.6.6
    CPU: (8) arm64 Apple M1
    Memory: 105.61 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.4.0 - /opt/homebrew/bin/node
    npm: 8.12.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 14.1.2
  npmPackages:
    next: 12.3.0 => 12.3.0 
    next-auth: ^4.10.3 => 4.10.3 
    react: 18.2.0 => 18.2.0 
```

### Reproduction URL

https://github.com/rprend/twitter-bookmarks

### Describe the issue

I used NextAuth as described with the Client_ID and Secrets configured in the API. This signs you in correctly, redirects as expected. However, the returned access_key and access_key_secret do not work, returning 401 unauthorized when passed into a GET request. 

### How to reproduce

1. Clone the repo, run `npm install && npm run dev`. Copy `.env.local.template` to .env.local and add the CLIENT_ID and secret variables from your Twitter API dashboard. 
1. Open [http://localhost:3000](http://localhost:3000). Click log-in with Twitter. Login using NextAuth OAuth2 Twitter provider. 
2. Open [http://localhost:3000/api/twitter/search](http://localhost:3000/api/twitter/search)
3. Receive a 401 unauthorized error despite passing in the provided access token. 

### Expected behavior

The provided access token should not return unauthorized, and should populate with the data from Twitter API bookmarks.

**Comment by balazsorban44** [comment]
Your config looks correct, including the scopes. 


`twitter-lite` hasn't been updated in 2 years according to npm though: https://www.npmjs.com/package/twitter-lite

Could you try doing a simple `fetch` call following the official documentation here?: https://developer.twitter.com/en/docs/twitter-api/tweets/bookmarks/api-reference/get-users-id-bookmarks

I wonder if there is an issue with that lib.

**Comment by balazsorban44** [comment]
I just verified, it *is* the case.

```js
import { getToken } from "next-auth/jwt"

export default async function search(req, res) {
  const token = await getToken({ req })
  const response = await fetch(
    `https://api.twitter.com/2/users/${token.sub}/bookmarks`,
    { headers: { Authorization: `Bearer ${token.twitter.access_token}` } }
  )
  const data = await response.json()
  res.json(data)
}
```

will work fine, so this is not a `next-auth` issue.

**Comment by rprend** [comment]
Verified, my bad. Thanks for answering.
