### ISSUE TITLE
Type error: Property 'session' does not exist on type '{}'.

### ISSUE THREAD

**Issue by felixerdy** [nextauthjs/next-auth#5401]
### Question 💬

After upgrading to `"next": "12.3.1"` there is the following error in the `_app.tsx` during build process:
```
...
./pages/_app.tsx:10:42
Type error: Property 'session' does not exist on type '{}'.
   7 | import type { AppProps } from 'next/app'
   8 | import { SessionProvider } from 'next-auth/react'
   9 | 
> 10 | function App({ Component, pageProps: { session, ...pageProps } }: AppProps) {
     |                                          ^
  11 |   return (
  12 |     <SessionProvider session={session}>
...
```

### How to reproduce ☕️

- Create new Next.js Typescript Project with `"next": "12.3.1"`
- Setup NextAuth.js
- Run `yarn build`

This type problem is also existent in the [CodeSandbox example](https://codesandbox.io/s/next-auth-example-1kktb)

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by felixerdy** [comment]
Workaround: add `SessionProviderProps` to the `AppProps`
```
...
import type { AppProps } from 'next/app'
import { SessionProvider, SessionProviderProps } from 'next-auth/react'

function MyApp({
  Component,
  pageProps: { session, ...pageProps },
}: AppProps<SessionProviderProps>) {
  return (
    <SessionProvider session={session}>
...
```

**Comment by trungthecelestial** [comment]
We should put this on Typescript page of the document.

**Comment by voinik** [comment]
You can check out my answer discussing it here: https://stackoverflow.com/a/73708673/8221175
