### ISSUE TITLE
NEXTAUTH_URL set but still redirecting to localhost in prod

### ISSUE THREAD

**Issue by johann-arias** [nextauthjs/next-auth#5412]
### Question 💬

Hello guys, 

I'm using the Strava Provider to allow the user to log in to my website. Everything working fin on localhost.

I'm trying to deploy to Vercel, I set a NEXTAUTH_URL env variable to my domain name, it's set correctly as I tried logging it. 

But after the users logs in with Strava, the site is still redirecting me to localhost:3000 and I can't figure out why

Here's my nextauth conf : 

```
import { NextApiHandler } from 'next';
import NextAuth from 'next-auth';
import { PrismaAdapter } from '@next-auth/prisma-adapter';
import StravaProvider from 'next-auth/providers/strava';
import prisma from '../../../lib/prisma';
import type { NextAuthOptions } from 'next-auth'
import { signIn } from 'next-auth/react';


const authHandler: NextApiHandler = (req, res) => NextAuth(req, res, authOptions);
export default authHandler;

export const authOptions: NextAuthOptions = {
    providers: [
        StravaProvider({
            clientId: process.env.STRAVA_ID,
            clientSecret: process.env.STRAVA_SECRET,
            authorization: { params: { scope: "read,profile:read_all,activity:read" } },
        }),
    ],
    adapter: PrismaAdapter(prisma),
    secret: process.env.SECRET,
    callbacks: {
        async session({ session, token, user }) {
            // Send properties to the client, like an access_token from a provider.
            session.userId = user.id
            return session
        },
        async redirect({ url, baseUrl }) {
            // Allows relative callback URLs
            if (url.startsWith("/")) return `${baseUrl}${url}`
            // Allows callback URLs on the same origin
            else if (new URL(url).origin === baseUrl) return url
            return baseUrl
          }
    },
}; 
```

### How to reproduce ☕️

go to https://quiver-eight.vercel.app/ and try to log in

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Hi, I was successfully logged in via your link, so I assume this has been fixed.

Remember that `NEXTAUTH_URL` does not have to be set when deployed on Vercel:
https://next-auth.js.org/deployment#vercel

We also recommend setting the `NEXTAUTH_SECRET` instead of `secret: process.env.SECRET,` since we can automatically pick up that value without you having to pass it anywhere manually: https://next-auth.js.org/configuration/options#nextauth_secret
