### ISSUE TITLE
Not enough information to use the REST APIs

### ISSUE THREAD

**Issue by jfilby** [nextauthjs/next-auth#5422]
### What is the improvement or update you wish to see?

The REST APIs should specify which parameters are required/optional. The URLs only isn't enough information.

### Is there any context that might help us understand?

I'm trying to make REST API calls to process sign-ins, as the client and server source trees are separate.

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/getting-started/client

**Comment by balazsorban44** [comment]
I assume you meant to link to this page: https://next-auth.js.org/getting-started/rest-api

I agree this can be documented better. For now, you can look at how the `signIn` method is implemented here: https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/react/index.tsx

PRs are welcome! :pray:

**Comment by binjamil** [comment]
I can take this up. Please assign it to me

**Comment by ThangHuuVu** [comment]
Please go for it @binjamil !

**Comment by ericvrp** [comment]
Hi, I'm trying to log into my NextJS app that uses next-auth from a NodeJS script and unable to because of the lack of proper REST API examples. Would love it when there is something to make me move in the right direction.
