### ISSUE TITLE
How to link accounts

### ISSUE THREAD

**Issue by nmpribeiro** [nextauthjs/next-auth#5424]
### Question 💬

Hi,

I agree one should not link accounts by default (I would relax that rule if the user has a verified email, but fine...).

How can I make a user link other social accounts, when he is logged in already? Say setup a profile view with a table of providers, and make him link to whatever provider he wishes?

### How to reproduce ☕️

- my question is generic as of now

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
You could for example utilize the `signIn` event and your adapter's `linkAccount` method:

https://next-auth.js.org/configuration/events#signin

**Comment by nmpribeiro** [comment]
@balazsorban44 and how can I know which provider the current user is authenticated in?

**Comment by nmpribeiro** [comment]
Ok, got them by means of exploring my database. Nevermind, thanks @balazsorban44  🙏

**Comment by ozgursef** [comment]
How did you solve this?

**Comment by nmpribeiro** [comment]
Hi @ozgursef , I went to my DB and peaked at the data generated by my prisma next-auth connector. You can request all providers (from next-auth docs) and generate a list. You can get your user accounts and check for each provider if there is an account with that provider. To link just use login(‘[the_provider]’). It will link it as you are alrea logged in (otherwise it will throw a warning as linking with different providers to another account while logged out is kinda security issue).
