### ISSUE TITLE
Personal user information in Cookies for GDPR report - how to decode cookies?

### ISSUE THREAD

**Issue by manuschillerdev** [nextauthjs/next-auth#5426]
### Question 💬

For a GDPR documentation, I need to specify which cookies our applications creates and which personal user information they may contain.

Right now the application sets:
```
next-auth.session-token.1
next-auth.session-token.0
next-auth.callback-url
next-auth.csrf-token
```

I expect the following:
* `next-auth.session-token.0/1` contain the chunked return value of `callbacks.session` (https://next-auth.js.org/configuration/callbacks#session-callback)
* `next-auth.callback-url` is just the encrypted callback-url and does not contain any user data
* `next-auth.csrf-token` - not sure. 

All cookie values are encrypted via `NEXT_AUTH_SECRET` as key.

Can I get the raw, decoded values of the cookies to look into them and check where personal user data might get stored?

Thanks! 

### How to reproduce ☕️

doesn't really apply to my question since it's too general :) 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Using `getSession`, `useSession` or `unstable_getServerSession` will already give you the decoded values. For the raw JWT, you can use the `getToken` method with the `raw: true` option passed to it, server-side: https://next-auth.js.org/configuration/options#jwt-helper
