### ISSUE TITLE
Peer dependency `next` is set to fixed version

### ISSUE THREAD

**Issue by jakubmazanec** [nextauthjs/next-auth#5427]
### Environment

  ```
System:
  OS: Windows 10 10.0.19043
  CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Memory: 1.61 GB / 15.75 GB
Binaries:
  Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
  npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.50)
```

### Reproduction URL

Not needed.

### Describe the issue

Package `next-auth` has peer dependency `"next": "12.2.5"`, i.e. fixed version. Therefore, if you use npm v8 (and probably v7), you get `ERESOLVE unable to resolve dependency tree` if you're not using that exact `next` version.

### How to reproduce

Create a Node.js project depending on e.g. `next@12.3.1` and `next-auth@4.12.0` . Try running `npm install` using npm v8.

### Expected behavior

Peer dependency uses semver **range**, i.e. `"next": "^12.2.5"`, and there are no `ERESOLVE unable to resolve dependency tree` npm errors.

**Comment by TomFreudenberg** [comment]
Btw. this happens also when using yesterday release 4.11.0 as well.

4.10.3 is running without issues about peer dependencies

**Comment by balazsorban44** [comment]
True, let's fix this! Does anyone want to open a PR?

https://github.com/nextauthjs/next-auth/blob/879faf9fab29436b8b58ba44a0db0391355753b2/packages/next-auth/package.json#L81

This needs a `^`.
