### ISSUE TITLE
redis adapter

### ISSUE THREAD

**Issue by nikitapilgrim** [nextauthjs/next-auth#544]
Hi, don't you have an example of connecting a redis as a database?

**Comment by nyedidikeke** [comment]
Following the [documentation](https://next-auth.js.org/configuration/databases), you *should* be able to connect to redis as below;

```js
// pages/api/auth/[...nextauth].js
import NextAuth from 'next-auth'
import Providers from 'next-auth/providers'

const options = {
  // OAuth Service Providers and other details
  // Provide URL to redis to connect (here, from .env file)
  database: process.env.DATABASE_URL
}

export default (req, res) => NextAuth(req, res, options)
```

```
# .env
DATABASE_URL=redis://user:pass@host:port
```

You may want to check [`node-redis`](https://github.com/NodeRedis/node-redis) and [rediSQL](https://github.com/RedBeardLab/rediSQL) while experimenting and share details as redis may/is not currently be supported by default.

**Comment by iaincollins** [comment]
MySQL, Postgres, Microsoft SQL Server and MongoDB are supported.

If you want to use a Redis database you would need to write your own adapter.

Redis would be a really unconventional choice in a context like this and not something support is planned for.

**Comment by D10221** [comment]
Sorry 
I referenced this issue by mistake 
Miss typed it  :(

**Comment by JakubKoralewski** [comment]
@iaincollins 

> Redis would be a really unconventional choice in a context like this and not something support is planned for.

Isn't storing sessions in Redis a good idea? https://stackoverflow.com/a/9153199/10854888
Or do you suggest just using JWT in this case?

**Comment by designbyadrian** [comment]
@nikitapilgrim Did you get anywhere with this? Care to share your solution, pretty please?

**Comment by LubomirGeorgiev** [comment]
@designbyadrian
> @nikitapilgrim Did you get anywhere with this? Care to share your solution, pretty please?

You can use that one https://github.com/quanhua92/next-auth-ioredis-adapter-example/blob/main/lib/IORedisAdapter.ts
