### ISSUE TITLE
Could you guys release a new version please ?

### ISSUE THREAD

**Issue by fivaz1** [nextauthjs/next-auth#5478]
### Question 💬

You guys have exported SessionContext in a commit some hours after publishing the latest version, and so the latest version doesn't contain the context SessionContext exported, we need this in order to use components that uses the hook useSession inside Storybook.

Would you mind releasing a new minor version just to add your newer [commit](https://github.com/nextauthjs/next-auth/commit/97feae791630e0f38e3e26b3bd70cc77e94b3eda)  please ? It just exports a variable, nothing that might break your code.  

![image](https://user-images.githubusercontent.com/114385572/193597886-45b9be29-811b-4c91-8c11-7b66360f9ad0.png)

Thank you for your awesome lib <3

BTW: I tried to fork your lib and publish it again but since you guys use turbo repo, it didn't manage to make it work.

### How to reproduce ☕️

If we try to import SessionContext from 'next-auth/react' it shows

![image](https://user-images.githubusercontent.com/114385572/193598432-9588b707-68dc-4df1-99d8-eedd53ba23e4.png)

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by ThangHuuVu** [comment]
I will find some time this week to do the release 🙌 We are planning to do more releases and more regularly, so hopefully this won't be a pain anymore 😄

**Comment by balazsorban44** [comment]
This should be included in `4.12.3` now.

**Comment by fivaz1** [comment]
Thank you guys
