### ISSUE TITLE
Non existing page linked in the code

### ISSUE THREAD

**Issue by mkbctrl** [nextauthjs/next-auth#5489]
### Environment

-

### Reproduction URL

-

### Describe the issue

Line 69 in `node_modules/next-auth/next/middleware.d.ts` redirects to:
![image](https://user-images.githubusercontent.com/10107362/193776683-83fbd0b3-4e7f-42f6-8b03-ef668aec94b8.png)

```
* [Documentation](https://next-auth.js.org/getting-started/nextjs/middleware#api)
```

### How to reproduce

-

### Expected behavior

Link to a proper page or remove the confusing comment

**Comment by eric-hc** [comment]
Seems like it should be updated to https://next-auth.js.org/configuration/nextjs#middleware
