### ISSUE TITLE
vercel problem with NEXTAUTH_URL 

### ISSUE THREAD

**Issue by pogran** [nextauthjs/next-auth#5493]
### Question 💬

I have problem with next-auth. I set in my package.json 

 "vercel-build": "prisma generate && next build" and after this I don't understand why NEXTAUTH_URL doesn't work. I have 
 [next-auth][error][CLIENT_FETCH_ERROR] 

I think problem with vercel-build and need to set up env for vercel

### How to reproduce ☕️

![image](https://user-images.githubusercontent.com/5382042/193895488-8fe4f6e6-60c9-4d23-928b-2ddb50c4876e.png)

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
On Vercel, you don't need to set `NEXTAUTH_URL` as documented https://next-auth.js.org/deployment#vercel

**Comment by micohalvarez** [comment]
why close this when issue is not even resolvdd yet
