### ISSUE TITLE
withAuth documentation insufficient

### ISSUE THREAD

**Issue by mkbctrl** [nextauthjs/next-auth#5498]
### What is the improvement or update you wish to see?

Hey 👋 

I struggle a bit with understanding how to execute middleware wrapped withAuth for non protected pages. 

What I am currently trying to achieve is to prevent user from visiting custom registration and login pages if the token exists. 

Based on the information I read here https://next-auth.js.org/configuration/nextjs#advanced-usage I gather that the middleware is executed only if authorized returns true.

So following this information if I want logged in user to restrict from login/registration pages I should add: 

```
// middleware.ts 

{
  … execute middleware logic
  { authorized: ({token, req}) => {
    return !!token
}, pages: {
  signIn: “/auth/sign-in”
}}
}

const config = {
  matcher: [“/some/:path*”, “/auth/:path*”]
}
```

but that currently breaks my app entirely. The only solution is to remove the auth/path from the matcher.

But if I remove it how can I execute the middleware there?

### Is there any context that might help us understand?

Added as many details above. Can provide video if that helps, lemme know

**Comment by mkbctrl** [comment]
Can I run withAuth inside the middleware, like here:

https://github.com/nextauthjs/next-auth/discussions/4832

**Comment by weidezhang** [comment]
@balazsorban44 , i wonder for the nextauth.token passed into middleware, will it pass onto the getServerProps or server api handler ?  since if the api/pages are guarded by middleware, it doesn't need to check against session using getServerSession right ?
