### ISSUE TITLE
Is it possible for getSession (useSession) to be an edge function for faster response time?

### ISSUE THREAD

**Issue by Joroze** [nextauthjs/next-auth#5535]
### Question 💬

I've had no luck searching for a question similar, so please excuse me.

Is it possible for getSession (useSession) to be an edge function for faster response time?

### Context
I am currently using an external backend API, so I have to mutate the Session object with the provider's (Google) access token for the Front End to use to then make those client-side calls to my external API.

With that said, the Front End uses the access token returned from the modified Session object (useSession) to make those calls, BUT - I do notice that getSession (useSession)'s response time can lag. Is this a cold start?

Some other factors:
- I'm using Netlify to deploy my project

Any ideas? Thanks!

### How to reproduce ☕️

Invoke useSession / getSession

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
See: https://github.com/nextauthjs/next-auth/issues/5537#issuecomment-1272789242
