### ISSUE TITLE
Allow getToken to invoke jwt callback before returning token object to ensure custom refresh token logic 

### ISSUE THREAD

**Issue by Joroze** [nextauthjs/next-auth#5537]
### Description 📓

As per: https://github.com/nextauthjs/next-auth/issues/5535
### Context
As a developer who's looking to use NextAuth with external backend API's:
- I want the flexibility to proxy NextJS API requests to my external API that requires a provider's access token payload. 
- I want to use `getSession` NextJS edge functions to return an access token from Session object (currently not supported) by making my own NextJS edge function which invokes `getToken` and returns an access token. (Or the same idea to just 

We should allow getToken/getSession to optionally invoke jwt callback before returning token object to ensure custom refresh token logic.

### How to reproduce ☕️

`/api/graphql.ts`
```
import httpProxyMiddleware from 'next-http-proxy-middleware';
import { NextApiRequest, NextApiResponse } from 'next';
import { getToken } from 'next-auth/jwt';

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const token = await getToken({ req }); // this wont renew my provider's access tokens :(

  return httpProxyMiddleware(req, res, {
    target: process.env.NEXT_PUBLIC_GRAPHQL_API_URL,
    changeOrigin: true,
    secure: false,
    proxyTimeout: 5000,
    pathRewrite: [
      {
        patternStr: '^/api/graphql',
        replaceStr: '',
      },
    ],
    headers: {
      authorization: (token?.accessToken as string) || '',
    },
  });
}

export const config = {
  api: {
    // https://nextjs.org/docs/api-routes/api-middlewares#custom-config
    externalResolver: true,
    // not to use url encoded form like streaming POST request
    bodyParser: false,
  },
};
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
This is being worked on. The plan is to make NextAuth.js compatible with Web APIs, hence making it run in an Edge Runtime: https://github.com/nextauthjs/next-auth/pull/5536
