### ISSUE TITLE
Trying to send a data to client in session object in callback config, but it says Property 'x' does not exist on type 'Session'.

### ISSUE THREAD

**Issue by RakaDoank** [nextauthjs/next-auth#5538]
### Environment

OS: Linux 5.10 Ubuntu 20.04.5 LTS (Focal Fossa)
Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    next: ^12.3.1 => 12.3.1 
    next-auth: ^4.12.2 => 4.13.0 
    react: ^18.2.0 => 18.2.0

### Reproduction URL

https://github.com/RakaDoank/next-auth-example/tree/reproduction-issue

### Describe the issue

On next-auth 4.13.0 version,
i can't add any properties in session to send the client in callback config like session.accessToken or any property that likely client would use it.

Just like the example here https://next-auth.js.org/configuration/callbacks#session-callback

But now, it says
`Property 'xxx' does not exist on type 'Session'.`

Maybe, there are some changes that i missed here

### How to reproduce

in [...nextauth].ts api file, we can just add a property in session object like the example https://next-auth.js.org/configuration/callbacks#session-callback

```
callbacks: {
  async session({ session, token }) {
    if(token?.xxx) {
      session.xxx = token.xxx
    }
    return session
  },
}
```

### Expected behavior

It should be just fine like before. I just want to send some small prop through session object.

**Comment by balazsorban44** [comment]
https://next-auth.js.org/getting-started/typescript#module-augmentation

**Comment by RakaDoank** [comment]
> https://next-auth.js.org/getting-started/typescript#module-augmentation

thanks
