### ISSUE TITLE
FirebaseAdapter and Firebase giving "import" error

### ISSUE THREAD

**Issue by bcthakre** [nextauthjs/next-auth#5551]
### Adapter type

@next-auth/firebase-adapter

### Environment

**System Information.**
```

System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 135.65 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 16.0
  npmPackages:
    next: 12.3.1 => 12.3.1 
    next-auth: ^4.13.0 => 4.13.0 
    react: 18.2.0 => 18.2.0 


  npmPackages:
    @next-auth/firebase-adapter: ^1.0.2 => 1.0.2 
```

### Reproduction URL

https://github.com/bcthakre/nextjs-nextauth-2.git

### Describe the issue

I am trying to use the FirebaseAdapter and Firestore to store user information for my NextJS app. However, getting the following error. 

```

import { initializeApp } from "firebase/app";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.@next-auth/firebase-adapter (/Users/bt/Documents/nextjs/nextjs-nextauth-2/.next/server/pages/api/auth/[...nextauth].js:22:18)
    at __webpack_require__ (/Users/ct/Documents/nextjs/nextjs-nextauth-2/.next/server/webpack-api-runtime.js:33:42)

```

The issue was raised earlier but has not been fully resolved. Things I tried.

1. Adding .mjs and .cjs to package-lock and next.config file.
2. Removing and adding different firebase versions. From 9 to 11.

### How to reproduce

Copy the github link as well.

[https://github.com/bcthakre/nextjs-nextauth-2.git]

### Expected behavior

Should allow to store user and session information in Firestore. Also, need to provide a way to signIn and signOut

**Comment by mucahitkok** [comment]
i am getting the same error. did you solve it? @bcthakre

**Comment by bcthakre** [comment]
Not yet @mucahitkok . Have asked on stackoverflow as well.

**Comment by balazsorban44** [comment]
Looks like this release did not include the compiled version of the package

https://github.com/nextauthjs/next-auth/releases/tag/%40next-auth%2Ffirebase-adapter%40v1.0.2 🤔


https://github.com/nextauthjs/next-auth/actions/runs/3214540412/jobs/5255017831#step:6:101

The build was initiated but the output ilwas still wrong.

**Comment by bcthakre** [comment]
Thanks @balazsorban44 . Novice here. Shall I just revert back the next-with to version 1.0.1

**Comment by NorbertHuethmayr** [comment]
I highly advise not to use the current firebase adapter - for details please check out this link. 
https://github.com/nextauthjs/next-auth/issues/5049

**Comment by bcthakre** [comment]
Thanks @NorbertHuethmayr and @balazsorban44 . Solved the issue (seems like) by downgrading version. 

@mucahitkok happy to share the solution

**Comment by Maximilian94** [comment]
Thanks @balazsorban44, downgrading to version 1.0.1 solved for me.

**Comment by bcthakre** [comment]
@balazsorban44 Is there a specific guidance on how to change firestore security rules to add / view users with the adapter.

**Comment by RonAlmog** [comment]
having the same issue. patiently waiting for a fix, thank you ;)

**Comment by NorbertHuethmayr** [comment]
You better look at this PR - maybe you can even upvote so that we get a bit more love from the maintainers.
https://github.com/nextauthjs/next-auth/pull/5628

**Comment by alpharaoh** [comment]
downgrading doesn't work for me 🥲

**Comment by RonAlmog** [comment]
@alpharaoh , what works for me right now is this: insall @next-auth/firebase-adapter@experinental, 
and then go to your node_modules, next-auth/firebase-adapter, dist, and edit index.js
find:   if(value.toDate)
add ? after the word value.
change to if(value?.toDate)
save and run, hope it will work for you.

**Comment by MalteBoehm** [comment]
Downgrading did not work on my end. Looking forward to a fix 🙃

**Comment by yumartins** [comment]
Temporarily for this new version of firebase-adapter

In the project, use the [next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules) lib

In version 13 of next we can use it inside next.config.js

```
experimental: {
    transpilePackages: [
      '@next-auth/firebase-adapter'
    ]
  }
```

**Comment by vedantmgoyal2009** [comment]
@balazsorban44 - please create a new version fixing the issue.

**Comment by hsdonkin** [comment]
In the meantime I've had some luck by doing the following:
- Implementing a custom credentials provider:
https://next-auth.js.org/configuration/providers/credentials
- Following the firebase guides to implement auth in a web app
https://firebase.google.com/docs/auth/web/start

Here's what that code looks like:
```
import NextAuth from 'next-auth';
import CredentialsProvider from 'next-auth/providers/credentials';
import { getAuth, signInWithEmailAndPassword } from 'firebase/auth';
// aliased import
import app from '@lib/firebase';

// For more information on each option (and a full list of options) go to
// https://next-auth.js.org/configuration/options
export default NextAuth({
  // https://next-auth.js.org/providers
  providers: [
    CredentialsProvider({
      // The name to display on the sign in form (e.g. 'Sign in with...')
      name: 'Credentials',
      // The credentials is used to generate a suitable form on the sign in page.
      // You can specify whatever fields you are expecting to be submitted.
      // e.g. domain, username, password, 2FA token, etc.
      // You can pass any HTML attribute to the <input> tag through the object.
      credentials: {
        email: { label: 'Email', type: 'text', placeholder: 'jsmith' },
        password: { label: 'Password', type: 'password' },
      },
      async authorize(credentials, req) {
        const { email, password } = credentials;
        try {
          const auth = getAuth(app);
          const userCredential = await signInWithEmailAndPassword(auth, email, password);
          // If no error and we have user data, return it
          if (userCredential?.user) {
            return userCredential?.user;
          }
        } catch (error) {
          console.log(error);
        }
        // Return null if user data could not be retrieved
        return null;
      },
    }),
  ],
});
```

Then in my app I can call `signIn('credentials', { email, password, callbackUrl: '/' })`

**Comment by bcthakre** [comment]
Thanks @hsdonkin . Can you please share the nextauth piece where you have used firestore adapter to connect to firebase for storing users. And what version of adapter you have used.

**Comment by hsdonkin** [comment]
This is my replacement for the adapter entirely, the `authorize()` function uses the firebase signin functions

**Comment by bcthakre** [comment]
Let me give it a try this weekend.

**Comment by JorritWillaert** [comment]
I would like to use NextAuth with Firebase Authentication in my application, but I can't get around this issue.
@bcthakre have you found a solution or workaround?

Thanks!

**Comment by MalteBoehm** [comment]
> I would like to use NextAuth with Firebase Authentication in my application, but I can't get around this issue.
> @bcthakre have you found a solution or workaround?
> 
> Thanks!

Hey there, if you put this into your package.json it should work.

  "overrides": { 
     "next-auth": { 
       "next": "13.0.2" 
     }, 
     "@next-auth/firebase-adapter": { 
       "next": "13.0.2" 
     } 
   },

**Comment by Quelaan1** [comment]
> I would like to use NextAuth with Firebase Authentication in my application, but I can't get around this issue. @bcthakre have you found a solution or workaround?
> 
> Thanks!

Use npm install next-auth @next-auth/firebase-adapter@experimental

**Comment by JorritWillaert** [comment]
> next-auth @next-auth/firebase-adapter@experimental

Thank you for your answer!
I've tried this, with this in my [...nextauth].js file:
```
import NextAuth from "next-auth";
import GoogleProvider from "next-auth/providers/google";
import { db } from "../../../firebase";
import { FirebaseAdapter } from "@next-auth/firebase-adapter";
import {
  collection,
  query,
  getDocs,
  where,
  limit,
  doc,
  getDoc,
  addDoc,
  updateDoc,
  deleteDoc,
  runTransaction,
} from "firebase/firestore";

export const authOptions = {
  // Configure one or more authentication providers
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    }),
    // ...add more providers here
  ],
  secret: process.env.NEXTAUTH_SECRET,
  adapter: FirebaseAdapter({
    db,
    collection,
    query,
    getDocs,
    where,
    limit,
    doc,
    getDoc,
    addDoc,
    updateDoc,
    deleteDoc,
    runTransaction,
  }),

  // The standard next auth page is this:
  // theme: {
  //   logo: "https://links.papareact.com/sq0",
  //   brandColor: "#f13287",
  //   colorScheme: "auto",
  // },
  pages: {
    signIn: "/auth/signin",
  },
  callbacks: {
    async session({ session, token, user }) {
      session.user.username = session.user.name
        .split(" ")
        .join("")
        .toLowerCase();
      session.user.uid = token.sub; // Google's user ID
      return session;
    },
  },
};
export default NextAuth(authOptions);
```

But then I get the following error:
```
https://next-auth.js.org/errors#adapter_error_getsessionanduser Missing or insufficient permissions. {
  message: 'Missing or insufficient permissions.',
  stack: 'FirebaseError: Missing or insufficient permissions.',
  name: 'FirebaseError'
}
[next-auth][error][SESSION_ERROR] 
https://next-auth.js.org/errors#session_error Missing or insufficient permissions. [FirebaseError: Missing or insufficient permissions.] {
  name: 'GetSessionAndUserError',
  code: 'permission-denied'
}
```

**Comment by vedantmgoyal2009** [comment]
Instead of so many workarounds, why can't maintainers create a new patch release, and fix the bug? It has been quiet a long since the issue had been reported.

**Comment by bcthakre** [comment]
This has more to do with firestore security rules than NextJS. However, I feel that devs should go with Venkat’s approach and provide a fix through patch. Best Regards, Bhupendrasinh ThakreOn Nov 22, 2022, at 7:03 AM, Jorrit Willaert ***@***.***> wrote:﻿

next-auth @***@***.***

Thank you for your answer!
I've tried this, with this in my [...nextauth].js file:
import NextAuth from "next-auth";
import GoogleProvider from "next-auth/providers/google";
import { db } from "../../../firebase";
import { FirebaseAdapter } from ***@***.***/firebase-adapter";
import {
  collection,
  query,
  getDocs,
  where,
  limit,
  doc,
  getDoc,
  addDoc,
  updateDoc,
  deleteDoc,
  runTransaction,
} from "firebase/firestore";

export const authOptions = {
  // Configure one or more authentication providers
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    }),
    // ...add more providers here
  ],
  secret: process.env.NEXTAUTH_SECRET,
  adapter: FirebaseAdapter({
    db,
    collection,
    query,
    getDocs,
    where,
    limit,
    doc,
    getDoc,
    addDoc,
    updateDoc,
    deleteDoc,
    runTransaction,
  }),

  // The standard next auth page is this:
  // theme: {
  //   logo: "https://links.papareact.com/sq0",
  //   brandColor: "#f13287",
  //   colorScheme: "auto",
  // },
  pages: {
    signIn: "/auth/signin",
  },
  callbacks: {
    async session({ session, token, user }) {
      session.user.username = session.user.name
        .split(" ")
        .join("")
        .toLowerCase();
      session.user.uid = token.sub; // Google's user ID
      return session;
    },
  },
};
export default NextAuth(authOptions);

But then I get the following error:
https://next-auth.js.org/errors#adapter_error_getsessionanduser Missing or insufficient permissions. {
  message: 'Missing or insufficient permissions.',
  stack: 'FirebaseError: Missing or insufficient permissions.',
  name: 'FirebaseError'
}
[next-auth][error][SESSION_ERROR] 
https://next-auth.js.org/errors#session_error Missing or insufficient permissions. [FirebaseError: Missing or insufficient permissions.] {
  name: 'GetSessionAndUserError',
  code: 'permission-denied'
}

**Comment by souviksaha27** [comment]
When i try to do this, import { FirebaseAdapter } from "@next-auth/firebase-adapter"; it gives me an error that says @next-auth has no exported member FirebaseAdapter did you mean FirestoreAdapter? How do i fix this issue? I am using typescript for my project.

**Comment by Quelaan1** [comment]
> When i try to do this, import { FirebaseAdapter } from "@next-auth/firebase-adapter"; it gives me an error that says @next-Auth has no exported member FirebaseAdapter did you mean FirestoreAdapter? How do i fix this issue? I am using typescript for my project.

FirebaseAdapter is not working currently, no matter what we try. Will have to wait for next update.

**Comment by Quelaan1** [comment]
I even tried previous versions.

**Comment by vedantmgoyal2009** [comment]
> Looks like the latest release did not include the compiled version of the package
> 
> https://github.com/nextauthjs/next-auth/releases/tag/%40next-auth%2Ffirebase-adapter%40v1.0.2 🤔
> 
> https://github.com/nextauthjs/next-auth/actions/runs/3214540412/jobs/5255017831#step:6:101
> 
> The build was initiated but the output was still wrong.
> 
> reverting to `1.0.1` would be a temporary solution.

@ndom91 can we have a new release of firebase adapter published?

**Comment by vedantmgoyal2009** [comment]
cc @balazsorban44

**Comment by vedantmgoyal2009** [comment]
> Looks like the latest release did not include the compiled version of the package
> 
> https://github.com/nextauthjs/next-auth/releases/tag/%40next-auth%2Ffirebase-adapter%40v1.0.2 🤔
> 
> https://github.com/nextauthjs/next-auth/actions/runs/3214540412/jobs/5255017831#step:6:101
> 
> The build was initiated but the output was still wrong.
> 
> reverting to `1.0.1` would be a temporary solution.

@iaincollins @balazsorban44 @ndom91 @ThangHuuVu can we have a new release of the firebase adapter published?

Also, if the maintainers do not have enough time to give to the project, I would highly suggest looking for community developers (like https://github.com/Jackett/Jackett/issues/8180) who can volunteer their time to the project and prevent losing its reputation. It has been 2 months since this bug, but there has been no response, except for the quoted one. There are ~70 PRs (at the time of writing this comment) that adds new adapters, fixes several bugs and typos, etc... but again, no response. I'm monitoring this repo for updates, but except for one or two changes, there is no noteworthy progress. I also know the review process takes time, but it surely does not take months, and if it does, it clearly means that more time should be given to the project.

**Comment by vedantmgoyal2009** [comment]
Apparently, the issue comes due to https://github.com/nextauthjs/next-auth/pull/4205 (and https://github.com/nextauthjs/next-auth/pull/4780), where in https://github.com/nextauthjs/next-auth/pull/4205#pullrequestreview-913070713, he reverted @ThangHuuVu's changes and forgot to update after https://github.com/nextauthjs/next-auth/pull/3873 was merged.

Before #3873, the adapter did not work with NextAuth v4 - https://github.com/nextauthjs/next-auth/pull/3873/files#diff-8fb3de6fc92cfbf496e3b89fd0a1bf6d6560bf72591ad036a60355945a994063L8-L10 (lines 8-10 in the removed part).

**Comment by balazsorban44** [comment]
Please refrain from calling out/mass tagging maintainers, it is not helpful for the discussion and only create hostility.

Do note that most of us work on this project in their free time and should be no expectations from anyone working more on it than what their life situation can support.

As several people pointed out earlier, downgrading did work https://github.com/nextauthjs/next-auth/issues/5551#issuecomment-1284638402 so there was no imminent issue.

Furthermore, given this is a open source project with a very forgiving license, you can copy and paste the source code, create your fork, etc. if you are not satisfied with the maintenance.

I'm locking this thread to avoid being too heated, but please have another(?) look at our code of conduct https://github.com/nextauthjs/next-auth/blob/main/CODE_OF_CONDUCT.md before landing another comment like the above.

Thanks. 💚

**Comment by balazsorban44** [comment]
The fix is out in `@next-auth/firebase-adapter@1.0.3`

**Comment by bcthakre** [comment]
Thanks @balazsorban44 much appreciated. Will try this tonight

**Comment by bcthakre** [comment]
One quick question folks. Do we need to change security rules in the firestore rules. Any one has done it yet and want to share their insights

**Comment by Han-MeiM** [comment]
@balazsorban44 I still have this problem when using the v1.0.3 adapter
Error: Cannot find module 'firebase/app'
Top Stack：node_modules/.pnpm/@next-auth+firebase-adapter@1.0.3_next-auth@4.18.0/node_modules/@next-auth/firebase-adapter/dist/index.js

**Comment by vedantmgoyal2009** [comment]
```import { FirebaseAdapter } from "@next-auth/firebase-adapter";``` to ```import { FirestoreAdapter } from "@next-auth/firebase-adapter";```

**Comment by souviksaha27** [comment]
@vedantmgoyal2009 i did as you said it, changed adapter:FirebaseAdapter to adapter:FirestoreAdapter but it now highlights the next line i.e. "db" and throws the following error:
Argument of type '{ db: Firestore; collection: { (firestore: Firestore, path: string, ...pathSegments: string[]): CollectionReference<DocumentData>; (reference: CollectionReference<...>, path: string, ...pathSegments: string[]): CollectionReference<...>; (reference: DocumentReference<...>, path: string, ...pathSegments: string[]): Co...' is not assignable to parameter of type 'FirebaseOptions & FirestoreAdapterOptions'.
  Object literal may only specify known properties, and 'db' does not exist in type 'FirebaseOptions & FirestoreAdapterOptions'.

What do i do now?

**Comment by vedantmgoyal2009** [comment]
Can you paste the file here? It will help to look into the issue.

**Comment by souviksaha27** [comment]
[[...nextauth].zip](https://github.com/nextauthjs/next-auth/files/10218265/nextauth.zip)
Here is the file

**Comment by souviksaha27** [comment]
hey @vedantmgoyal2009 any updates?

**Comment by vedantmgoyal2009** [comment]
@so-uvik is the issue resolved?

**Comment by so-uvik** [comment]
> @so-uvik is the issue resolved?

No bro

**Comment by vedantmgoyal2009** [comment]
@so-uvik I'm no longer using next-auth, and also, major changes have been introduced. I hope you'll be able to find a solution on internet.
