### ISSUE TITLE
Is it possible to fetch JWT data from a separate application running on the same domain and/or store the JWT unencrypted as a cookie?

### ISSUE THREAD

**Issue by seangerrykelly** [nextauthjs/next-auth#5557]
### Question 💬

Hi there, I am currently working on migrating an existing web application to one that uses `next-auth` for authentication. The applications currently run in a "hybrid" state whereby they both run on the same domain in a production environment, with certain paths showing the new application, and other paths showing the legacy version.

When I login using `next-auth`, I want the sessionToken to be set as a cookie on the domain, so that when I go to the other application on the same domain, I have access to it and can perform a token exchange to be authorized on both applications. I believe the token is encrypted using JWT, but when I try to decode it, I am told that the payload is not a valid JSON object, and it has an invalid signature. 

I saw [on the FAQ](https://next-auth.js.org/faq#json-web-tokens) that it is possible to use JWT to store information on the client without encryption, and was wondering if you could please provide more information on how to do that? Even if it is just for testing purposes.

### How to reproduce ☕️

Here is a snippet from my configuration in `[...nextauth.ts]`:
```
    session: {
      strategy: 'jwt',
    },
    jwt: {
      secret: process.env.WEBAPP_SECRET,
    },
    cookies: {
      sessionToken: {
        name: 'kj-st',
        options: {
          domain: req.headers.host,
          httpOnly: true,
          path: '/',
          secure: true,
          sameSite: process.env.NODE_ENV === 'production' ? 'lax' : 'none',
        },
      },
    },
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
You can define your own JWT encode/decode methods. It's highly recommended that you know what you are doing:

https://next-auth.js.org/configuration/options#override-jwt-encode-and-decode-methods
