### ISSUE TITLE
Custom Provider: Epic Games - Issue Without Error Logs

### ISSUE THREAD

**Issue by aceaspades-worldspark** [nextauthjs/next-auth#5560]
### Provider type

Custom provider

### Environment

  System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1
    Memory: 26.22 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/.npm-global/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.103
    Firefox: 105.0
    Safari: 15.6.1
  npmPackages:
    next: latest => 12.3.1 
    next-auth: latest => 4.13.0 
    react: ^18.2.0 => 18.2.0 

### Reproduction URL

Repo: https://github.com/aceaspades-worldspark/next-auth-example
Live: https://next-auth-example-mu-blush.vercel.app/api/auth/signin
Callback URL (set on dev.epicgames.com): https://next-auth-example-mu-blush.vercel.app/api/auth/callback/epic

### Describe the issue

When I select "Sign In With EPIC", I'm properly redirected to the Epic Games login screen. Once I'm redirected back, I'm met with "Try signing in with a different account." No logs are presented to the console, nor to my Vercel Function logs.

### How to reproduce

1. Follow this URL: https://next-auth-example-mu-blush.vercel.app/api/auth/signin 
2. Select "Sign In With EPIC"
3. Consent to pairing with our application, Sparkadia (in development, feel free to use a dummy account)
4. You'll be redirected to the reproduction URL, with ?error=OAuthCallback appended to the params

### Expected behavior

I'd expect to be properly logged into my NextAuth application! Or, at least have something in my logs so I can better understand the issue.

**Comment by balazsorban44** [comment]
The repo is private.

**Comment by aceaspades-worldspark** [comment]
> 

Ah, my mistake. It is now public.

**Comment by balazsorban44** [comment]
Looks like you are missing the `openid` scope which is required for OIDC clients. I also tried to log in on the above link but got:

![image](https://user-images.githubusercontent.com/18369201/195585457-65bf57ab-ea84-4b05-b4af-5ae96d3cf5d9.png)

Tried creating my own client, but it does not accept localhost. :sweat:

Could you specify how you set up your client? Am I in the right place at: https://dev.epicgames.com/portal/en-US/my-org/products/my-product/settings/clients

What's the recommended flow to test this locally?

**Comment by aceaspades-worldspark** [comment]
Ah, your being restricted by Epic makes sense, we are still awaiting full approval for our application to go live to the public, so only dev accounts are allowed to sign up. Should be good to go by mid-week next week. But with a dev account, you'll see an OAuth application consent, then everything works pretty smooth following that. 

Localhost, I was just looking into this; Epic doesn't allow localhost as a Redirect URL, and they recommended using ngrok to route localhost to a custom domain; looking into that for our dev team. Described here: https://eoshelp.epicgames.com/s/feed/0D54z00007N0hA8CAJ?language=en_US

Correct client link, yes. Ours is set up with the provided GameClient policy type.

I'll add openid to the scope and see what happens, one moment...

**Comment by aceaspades-worldspark** [comment]
@balazsorban44 I've updated the config to exactly what you've provided, but I am still receiving the same error message when redirected back to my application.

**Comment by aceaspades-worldspark** [comment]
@balazsorban44 Here's the steps I followed to get a Client set up (after setting up an Organization account, Product, and Sandbox for our game, those instructions are available in the guide _one before_ this one): https://dev.epicgames.com/docs/dev-portal/client-credentials

Our Client is using the default GameClient permissions.

**Comment by balazsorban44** [comment]
So the client credentials is for machine-2-machine communication, you would likely need https://dev.epicgames.com/docs/web-api-ref/authentication

**Comment by balazsorban44** [comment]
Likely need to tweak the `token_endpoint_auth_method`. The basic is `client_secret_basic`, but I did not see one in your provider config.

See the docs: https://next-auth.js.org/configuration/providers/oauth#client-option
https://github.com/panva/node-openid-client/blob/main/docs/README.md#new-clientmetadata-jwks-options

**Comment by aceaspades-worldspark** [comment]
> Likely need to tweak the `token_endpoint_auth_method`. The basic is `client_secret_basic`, but I did not see one in your provider config.
> 
> See the docs: https://next-auth.js.org/configuration/providers/oauth#client-option https://github.com/panva/node-openid-client/blob/main/docs/README.md#new-clientmetadata-jwks-options
> 
> More likely, you forgot to set `clientSecret`?

I'll give that a look. 

Also, I'm definitely setting clientSecret (stated above a couple of times). Here's my current code: 

`{
      id: "epic",
      name: "Epic",
      type: "oauth",
      clientId: process.env.EPIC_CLIENT_ID,
      clientSecret: process.env.EPIC_CLIENT_SECRET,
      wellKnown:
        "https://api.epicgames.dev/epic/oauth/v1/.well-known/openid-configuration",
      authorization: { params: { scope: "openid basic_profile" } },
      profile(profile) {
        return {
          profile: profile,
          id: profile.id,
        };
      },
    },`

**Comment by balazsorban44** [comment]
```ts
{
  id: "epic",
  name: "Epic",
  type: "oauth",
  clientId: process.env.EPIC_ID,
  clientSecret: process.env.EPIC_SECRET,
  wellKnown:
    "https://api.epicgames.dev/epic/oauth/v1/.well-known/openid-configuration",
  authorization: { params: { scope: "openid basic_profile" } },
  profile(profile) {
    console.log(profile)
    return {
      profile: profile,
      id: profile.id,
    }
  },
}
```

This should really do it. I have to admit, setting up Epic for dev is time-consuming, I am stuck at: 
![image](https://user-images.githubusercontent.com/18369201/195940245-636b9815-0c5b-45cc-8556-cca6118049e4.png)

Which requires domain verification, etc.

**Comment by aceaspades-worldspark** [comment]
> ```ts
> {
>   id: "epic",
>   name: "Epic",
>   type: "oauth",
>   clientId: process.env.EPIC_ID,
>   clientSecret: process.env.EPIC_SECRET,
>   wellKnown:
>     "https://api.epicgames.dev/epic/oauth/v1/.well-known/openid-configuration",
>   authorization: { params: { scope: "openid basic_profile" } },
>   profile(profile) {
>     console.log(profile)
>     return {
>       profile: profile,
>       id: profile.id,
>     }
>   },
> }
> ```
> 
> This should really do it. I have to admit, setting up Epic for dev is time-consuming, I am stuck at: ![image](https://user-images.githubusercontent.com/18369201/195940245-636b9815-0c5b-45cc-8556-cca6118049e4.png)
> 
> Which requires domain verification, etc.

The exact response you'll get back, once everything is finished, would look like: 

https://mytunnel.ngrok.io/api/auth/callback/epic?code=a11563474340989bca28d11b905170ef&state=JXeMSWKe6WxDkWKHZdgYS1j1q_Y6NYhkAroH8bvI7Dk

**Comment by balazsorban44** [comment]
At this point, it's just config. You can contact me on Twitter for more help, but I would like to close this issue as this is not a NextAuth.js bug. :+1:

**Comment by aceaspades-worldspark** [comment]
Re-opening this issue, I've attempted to work with @balazsorban44 on Twitter to resolve this configuration issue, to no avail unfortunately; I believe you are occupied otherwise, perfectly understandable. 

Since this is directly an issue with configuring a custom provider using an OAuth-compliant authentication system (Epic Account Services), I'm going to attempt to re-open this issue so that it can be handled by any available member of the NextAuth team, during working hours.

**Comment by aceaspades-worldspark** [comment]
Re-opening this issue, I've attempted to work with @balazsorban44 on Twitter to resolve this configuration issue, to no avail unfortunately; I believe you are occupied otherwise, perfectly understandable. 

Since this is directly an issue with configuring a custom provider using an OAuth-compliant authentication system (Epic Account Services), I'm going to attempt to re-open this issue so that it can be handled by any available member of the NextAuth team, during working hours.

**Comment by OMaxOe** [comment]
I had the same problem like you. I was able to solve it by requesting the token endpoint itself.

The process.env.EPIC_AUTH_TOKEN in the Authorization header is a base64 encoded string in the following format ` Basic <Base64(ClientId:ClientSecret)>`

Hope this helps you.

`providers: [{
        id: 'epic',
        name: 'Epic',
        type: 'oauth',
        wellKnown: "https://api.epicgames.dev/epic/oauth/v1/.well-known/openid-configuration",
        authorization: {params: {scope: "openid basic_profile"}},
        token: {
            async request(context) {
                const response = await axios.post(process.env.EPIC_AUTH_TOKEN_URL, {
                    grant_type: "authorization_code",
                    code: context.params.code,
                    scope: "openid basic_profile",
                    state: context.params.state,
                }, {
                    headers: {
                        "content-type": "application/x-www-form-urlencoded",
                        "Authorization": `Basic ${process.env.EPIC_AUTH_TOKEN}`
                    }
                })

                return {tokens: response.data};
            }
        },
        clientId: process.env.EPIC_AUTH_CLIENT_ID,
        clientSecret: process.env.EPIC_AUTH_CLIENT_SECRET,
        profile: (profile) => {
           ...
        }
    }
    ]`

**Comment by serhii-lypko** [comment]
@OMaxOe thank you very much! While I have the same issue like @aceaspades-worldspark had, the only one work around I found so far - is what you've suggested.

**Comment by simplyzetax** [comment]
@OMaxOe First of all, thank you. Your method brought me much further than I got before, but I haven't been able to get it to work fully. Do you think I could contact you some other way, or you could help me here as you seem to know what you are doing. I'm currently just getting an error when being redirected to the callback with the valid code

```
error {
  errorCode: 'errors.com.epicgames.account.invalid_client_credentials',
  errorMessage: 'Sorry the client credentials you are using are invalid',
  messageVars: [],
  numericErrorCode: 18033,
  originatingService: 'com.epicgames.account.admin',
  intent: 'prod',
  error_description: 'Sorry the client credentials you are using are invalid',
  error: 'invalid_client'
}
[auth][error] CallbackRouteError: Read more at https://errors.authjs.dev#callbackrouteerror
[auth][cause]: Error: TODO: Handle OAuth 2.0 response body error
    at handleOAuth (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/actions/callback/oauth/callback.js:112:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.callback (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/actions/callback/index.js:37:41)
    at async AuthInternal (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/index.js:39:24)
    at async Auth (webpack-internal:///(rsc)/./node_modules/@auth/core/index.js:126:34)
    at async C:\Users\finni\Desktop\lowk\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:55038
    at async ek.execute (C:\Users\finni\Desktop\lowk\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:45808)
    at async ek.handle (C:\Users\finni\Desktop\lowk\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:56292)
    at async doRender (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\base-server.js:1377:42)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\base-server.js:1587:40)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\base-server.js:1507:28)
    at async DevServer.renderPageComponent (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\base-server.js:1931:24)
    at async DevServer.renderToResponseImpl (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\base-server.js:1969:32)
    at async DevServer.pipeImpl (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\base-server.js:816:17)
    at async C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\Users\finni\Desktop\lowk\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\lib\router-server.js:353:24)
    at async requestHandlerImpl (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\lib\router-server.js:377:13)
    at async Server.requestListener (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\lib\start-server.js:141:13)
[auth][details]: {
  "provider": "epic"
  ```
  
  The client credentials I am using are definitely working, and I'm not even sure which function the error stems from, as it's not one I defined myself.

**Comment by simplyzetax** [comment]
![image](https://github.com/user-attachments/assets/13d0b544-86e6-4feb-bf6f-17b87fb0b397)

The code is definitely being generated and returned properly, it just decides not to work for some reason

**Comment by ekimcem** [comment]
> [@OMaxOe](https://github.com/OMaxOe) First of all, thank you. Your method brought me much further than I got before, but I haven't been able to get it to work fully. Do you think I could contact you some other way, or you could help me here as you seem to know what you are doing. I'm currently just getting an error when being redirected to the callback with the valid code
> 
> ```
> error {
>   errorCode: 'errors.com.epicgames.account.invalid_client_credentials',
>   errorMessage: 'Sorry the client credentials you are using are invalid',
>   messageVars: [],
>   numericErrorCode: 18033,
>   originatingService: 'com.epicgames.account.admin',
>   intent: 'prod',
>   error_description: 'Sorry the client credentials you are using are invalid',
>   error: 'invalid_client'
> }
> [auth][error] CallbackRouteError: Read more at https://errors.authjs.dev#callbackrouteerror
> [auth][cause]: Error: TODO: Handle OAuth 2.0 response body error
>     at handleOAuth (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/actions/callback/oauth/callback.js:112:19)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async Module.callback (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/actions/callback/index.js:37:41)
>     at async AuthInternal (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/index.js:39:24)
>     at async Auth (webpack-internal:///(rsc)/./node_modules/@auth/core/index.js:126:34)
>     at async C:\Users\finni\Desktop\lowk\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:55038
>     at async ek.execute (C:\Users\finni\Desktop\lowk\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:45808)
>     at async ek.handle (C:\Users\finni\Desktop\lowk\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:56292)
>     at async doRender (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\base-server.js:1377:42)
>     at async cacheEntry.responseCache.get.routeKind (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\base-server.js:1587:40)
>     at async DevServer.renderToResponseWithComponentsImpl (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\base-server.js:1507:28)
>     at async DevServer.renderPageComponent (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\base-server.js:1931:24)
>     at async DevServer.renderToResponseImpl (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\base-server.js:1969:32)
>     at async DevServer.pipeImpl (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\base-server.js:920:25)
>     at async NextNodeServer.handleCatchallRenderRequest (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\next-server.js:272:17)
>     at async DevServer.handleRequestImpl (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\base-server.js:816:17)
>     at async C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\dev\next-dev-server.js:339:20
>     at async Span.traceAsyncFn (C:\Users\finni\Desktop\lowk\node_modules\next\dist\trace\trace.js:154:20)
>     at async DevServer.handleRequest (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
>     at async invokeRender (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\lib\router-server.js:174:21)
>     at async handleRequest (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\lib\router-server.js:353:24)
>     at async requestHandlerImpl (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\lib\router-server.js:377:13)
>     at async Server.requestListener (C:\Users\finni\Desktop\lowk\node_modules\next\dist\server\lib\start-server.js:141:13)
> [auth][details]: {
>   "provider": "epic"
> ```
> 
> The client credentials I am using are definitely working, and I'm not even sure which function the error stems from, as it's not one I defined myself.

any solution ?
