### ISSUE TITLE
getCsrfToken stops the custom sign in page to load

### ISSUE THREAD

**Issue by richard-bridgeman** [nextauthjs/next-auth#5567]
### Environment

  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 197.88 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - /usr/local/bin/node
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.103
    Firefox: 105.0.2
    Safari: 16.0
  npmPackages:
    next: ^12.2.1 => 12.3.1 
    next-auth: ^4.10.2 => 4.13.0 
    react: ^18.2.0 => 18.2.0 

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

When using a custom sign in page, The page stalls and spins if I use the getCsrfToken.  This is the code taken from the suggested Credentials sign in page:

```js
import { getCsrfToken } from "next-auth/react"

export default function SignIn({ csrfToken }) {

    console.log(csrfToken)

    return (
        <form method="post" action="/api/auth/callback/credentials">
            <input name="csrfToken" type="hidden" defaultValue={csrfToken} />
            <label>
                Username
                <input name="username" type="text" />
            </label>
            <label>
                Password
                <input name="password" type="password" />
            </label>
            <button type="submit">Sign in</button>
        </form>
    )
}

export async function getServerSideProps(context) {
    return {
        props: {
            csrfToken: await getCsrfToken(context),
        },
    }
}
```

However if I remove the getServerSideProps function from this page, and all traces of the CSRF token, the page loads prefectly fine.

What could be stopping the CSRF token from being got?

### How to reproduce

Use my environment and the template sign in page.

### Expected behavior

The page should load and get the CSRF token.

**Comment by lholiveiraa** [comment]
Same thing here... The project was working fine until I build and run "yarn dev" . After this, it started to show the follow message: 

![image](https://user-images.githubusercontent.com/5816311/197553390-88281cdb-5cfb-4e48-949f-04ae20977383.png)

**Comment by richard-bridgeman** [comment]
I dont even get an error, just spins and spins.  @lholiveiraa have you had any luck solving this issue yet?

**Comment by lucasStefanini** [comment]
> I dont even get an error, just spins and spins. @lholiveiraa have you had any luck solving this issue yet?

I cleaned my project and the cache of the browser and ran again "yarn dev". After that worked fine. I think it was a cache problem.

**Comment by lholiveiraa** [comment]
> I dont even get an error, just spins and spins. @lholiveiraa have you had any luck solving this issue yet?

I cleaned my project and the cache of the browser and ran again "yarn dev". After that worked fine. I think it was a cache problem.

**Comment by kilimchoi** [comment]
> I dont even get an error, just spins and spins. @lholiveiraa have you had any luck solving this issue yet?

could be related to this https://github.com/nextauthjs/next-auth/discussions/2728
noticing this on the first page load after not having visited the site in awhile.

**Comment by balazsorban44** [comment]
If you still have this issue, please open a bug report with a proper/minimal reproduction.
