### ISSUE TITLE
Make Session Cookie expiring on browser close

### ISSUE THREAD

**Issue by fritterhoff** [nextauthjs/next-auth#5571]
### Question 💬

Currently the session cookie is bound to a fixed timeframe of e.g. 10minutes or 8hours. I would love to have the option to make the session cookie a cookie that expires on closing the browser. As far as I understood the docs this is not possible at the moment?

### How to reproduce ☕️

At the moment I have configured `next-auth` using the following values:
```
    jwt: {
        maxAge: 10 * 60, // 10 minutes
    },
    session: {
        maxAge: 10 * 60, // 10 minutes
    },
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
There is a PR opened, but currently, browsers are horrible at respecting session cookies, so it's likely not going to happen, as right now it would actually be worse than a hard expire. See. https://github.com/nextauthjs/next-auth/pull/4693#issuecomment-1154506034
