### ISSUE TITLE
CredentialsProvider - custom backend returning only jwt tokens

### ISSUE THREAD

**Issue by h1sashin** [nextauthjs/next-auth#5575]
### Question 💬

Hello, I wanted to use NextAuthj for my app, but I already have my custom backend so I wanted to try `CredentialsProvider` and at this point I really hate its usage with TypeScript. My GraphQL backend on signIn query returns object `{ accessToken, refreshToken }`, and the authorization method  screams ALL THE TIME that 
```
Property 'id' is missing in type '{ accessToken: string; refreshToken: string; }' but required in type 'User'.
```
And first time seeing it I thought oh easy I'll pass Tokens type as an argument to that function BUT NO, THAT'S IMPOSSIBLE. Of course I can overwrite `User` interface, but why should I? Then everywhere object will think it only has these tokens, how to configure `CredentialsProvider` to work with any custom backend as it should? Is there any other way I can do that?

### How to reproduce ☕️

```
Credentials({
            name: 'credentials',
            type: 'credentials',
            authorize: async (credentials) => {
                return *anything that is not a user object*
            }
        })
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Yes, you should override the `User` type, to match your desired `User` shape. Please see https://next-auth.js.org/getting-started/typescript

**Comment by h1sashin** [comment]
> Yes, you should override the `User` type, to match your desired `User` shape. Please see https://next-auth.js.org/getting-started/typescript

XD yes, but on signIn backend returns tokens not user
