### ISSUE TITLE
GET request to requestTokenUrl endpoint

### ISSUE THREAD

**Issue by JJTech0130** [nextauthjs/next-auth#5578]
### Question 💬

I'm using a service with a slightly non-compliant OAuth v1.0 API. For whatever reason, it mandates that you MUST use a GET request to the requestTokenUrl endpoint, or it will return 405 Method Not Allowed. Is there any way to change `next-auth`'s default behavior to allow this?

### How to reproduce ☕️

Here's what I have in my file so far:
```js
import NextAuth from "next-auth"

export const authOptions = {
  // Configure one or more authentication providers
  providers: [
    {
        id: "schoology",
        name: "Schoology (SVPanthers)",
        type: "oauth",
        version: "1.0",
        authorization: "https://svpanthers.schoology.com/oauth/authorize",
        accessTokenUrl: "https://api.schoology.com/v1/oauth/access_token",
        requestTokenUrl: "http://api.schoology.com/v1/oauth/request_token",
        profileUrl: "https://api.schoology.com/v1/users/me",

        clientId: process.env.SCHOOLOGY_CONSUMER_KEY,
        clientSecret: process.env.SCHOOLOGY_CONSUMER_SECRET,
    }
  ],

  debug: process.env.NODE_ENV !== "production"
}

export default NextAuth(authOptions)
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Unfortunately, we are likely not going to fix OAuth 1 issues anymore. Our focus is on migrating away in favor of OAuth 2 and OIDC.

You can use `patch-package` to patch `next-auth`. Relevant file is likely this https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/core/lib/oauth/client-legacy.ts

**Comment by JJTech0130** [comment]
See the problem is I don’t really understand how that file even works… it’s seems circular? originalGet references oauth1.get which calls orginalGet… what’s going on?

**Comment by JJTech0130** [comment]
Nevermind, I figured it out... for now I just directly modified the file, I'll add proper patching or whatever later.
```js
oauth1Client._clientOptions.requestTokenHttpMethod = "GET";
```
