### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Oussamaosman02** [nextauthjs/next-auth#5583]
### Description 📓

I think it will be great to have these documentation in several languages as mine, Spanish.
Also i think that, thanks to the hacktoberfest, it will be easy to fill this assignment as there are more people that want to contribute than in other parts of the year.

### How to reproduce ☕️

The production it with the same page, in a new directory with the language code(es, en, it, etc...) with the same information but translated.

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by ThangHuuVu** [comment]
This should be possible, as Docusaurus supports i18n: https://docusaurus.io/docs/i18n/introduction
Do you want to open a PR to set this up? 🙌
cc @lluia our docs master 📚

**Comment by Oussamaosman02** [comment]
Okay, i have one question:
where sould i make the i18n folder? In `docs` or in `docs/docs`
