### ISSUE TITLE
[next-auth][error][INVALID_CALLBACK_URL_ERROR] 

### ISSUE THREAD

**Issue by ryan-keswick** [nextauthjs/next-auth#5585]
### Question 💬

Hi, I'm getting this when running on dev/localhost:

```
[next-auth][error][INVALID_CALLBACK_URL_ERROR] 
https://next-auth.js.org/errors#invalid_callback_url_error Invalid callback URL. Received: http://localhost:3000http://localhost:3000 InvalidCallbackUrl: Invalid callback URL. Received: http://localhost:3000http://localhost:3000
    at assertConfig (/Users/ryanbrycekeswick/minerva/frontend/node_modules/next-auth/core/lib/assert.js:62:12)
    at NextAuthHandler (/Users/ryanbrycekeswick/minerva/frontend/node_modules/next-auth/core/index.js:70:52)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async NextAuthNextHandler (/Users/ryanbrycekeswick/minerva/frontend/node_modules/next-auth/next/index.js:23:19)
    at async /Users/ryanbrycekeswick/minerva/frontend/node_modules/next-auth/next/index.js:59:32
    at async Object.apiResolver (/Users/ryanbrycekeswick/minerva/frontend/node_modules/next/dist/server/api-utils/node.js:179:9)
    at async DevServer.runApi (/Users/ryanbrycekeswick/minerva/frontend/node_modules/next/dist/server/next-server.js:381:9)
    at async Object.fn (/Users/ryanbrycekeswick/minerva/frontend/node_modules/next/dist/server/base-server.js:488:37)
    at async Router.execute (/Users/ryanbrycekeswick/minerva/frontend/node_modules/next/dist/server/router.js:213:36) {
  code: 'INVALID_CALLBACK_URL_ERROR'
}
```

I'm specifically using AWS Cognito only with usernames/passwords. I have set the `clientId`, `clientSecret` and `Issuer` 
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/16619034/196110546-dd8a4d8a-c52e-4c50-947f-300ad7a385c2.png">

I have set the env vars correctly
```
COGNITO_CLIENT_ID=********************
COGNITO_CLIENT_SECRET=****************************************
COGNITO_ISSUER=https://cognito-idp.${region}.amazonaws.com/${userPoolId)

NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=********************
```

### How to reproduce ☕️

`pages/api/auth/[...nextauth].ts`
```ts
import NextAuth from 'next-auth';
import CognitoProvider from 'next-auth/providers/cognito';
import { PrismaAdapter } from '@next-auth/prisma-adapter';
import prisma from '@/lib/prismadb';

export const authOptions = {
  adapter: PrismaAdapter(prisma),
  providers: [
    CognitoProvider({
      clientId: String(process.env.COGNITO_CLIENT_ID),
      clientSecret: String(process.env.COGNITO_CLIENT_SECRET),
      issuer: process.env.COGNITO_ISSUER,
    }),
  ],
  callbacks: {
    async session({ session, user }: any) {
      session.user.id = user.id;
      return session;
    },
  },
};

export default NextAuth(authOptions);
```

Sign in button 
```ts
<button
            className="m-5 grid h-10 w-24 place-content-center rounded-full hover:bg-dark-blue hover:text-white"
            onClick={() => signIn('cognito')}
          >
            Sign in
</button>
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by rahulmanas** [comment]
Hey i started getting this until yesterday. everything was working and suddenly this error started throwing up. Need the help asap.
<img width="860" alt="Screenshot 2022-10-20 at 8 45 38 AM" src="https://user-images.githubusercontent.com/12574496/196848119-100a44a8-31ac-459d-8209-d8fb7b1cacff.png">

**Comment by gennadiyhovrin** [comment]
> Hey i started getting this until yesterday. everything was working and suddenly this error started throwing up. Need the help asap. <img alt="Screenshot 2022-10-20 at 8 45 38 AM" width="860" src="https://user-images.githubusercontent.com/12574496/196848119-100a44a8-31ac-459d-8209-d8fb7b1cacff.png">

I got the same error, did you find a solution?

**Comment by balazsorban44** [comment]
Could anyone experiencing this add a full reproduction?

**Comment by balazsorban44** [comment]
> Received: http://localhost:3000http://localhost:3000

This is very suspicious. Can you delete your cookies and try again to log in? I wonder how this value would have ended up like that.

**Comment by anshul-techwondoe** [comment]
Facing the same issue with Netlify and Next.js runtime v4.27.3.

**Comment by balazsorban44** [comment]
@anshul-techwondoe please link to a reproduction.

**Comment by Saifadin** [comment]
@balazsorban44 so I have been having this issue the last few days too. It is happening on this url: https://dropfriends-essentials-staging.netlify.app/

When i first noticed it two days ago i cleared cache on netlify and deployed again and it worked again. When I did that this time, it keeps throwing this error. I did not touch the nextAuth files at all the last month.

**Comment by Saifadin** [comment]
> @balazsorban44 so I have been having this issue the last few days too. It is happening on this url: https://dropfriends-essentials-staging.netlify.app/
> 
> When i first noticed it two days ago i cleared cache on netlify and deployed again and it worked again. When I did that this time, it keeps throwing this error. I did not touch the nextAuth files at all the last month.

Little update from me. I updated to the newest version of `next@12.3.1` and `next-auth@4.14.0` and it worked again.
Although if you use typescript, you will get type errors in your credentials if you use `async authorize` in your `[...nextAuth].ts` file.

**Comment by Everkers** [comment]
> > @balazsorban44 so I have been having this issue the last few days too. It is happening on this url: https://dropfriends-essentials-staging.netlify.app/
> > When i first noticed it two days ago i cleared cache on netlify and deployed again and it worked again. When I did that this time, it keeps throwing this error. I did not touch the nextAuth files at all the last month.
> 
> Little update from me. I updated to the newest version of `next@12.3.1` and `next-auth@4.14.0` and it worked again. Although if you use typescript, you will get type errors in your credentials if you use `async authorize` in your `[...nextAuth].ts` file.

This worked for us, thank you 🙏🏻

**Comment by Sheldonfrith** [comment]
I was also experiencing this error, even though I had the latest versions of both next and next-auth. Deleting the cookies fixed the issue. Not sure the original cause though...

**Comment by ReangeloJ** [comment]
I had the same issue too. Deleting my cookies worked for me as well.

**Comment by jasonkuhrt** [comment]
In development I encountered this. Deleting cookies for me fixed the issue. Will report back with more detail if I have any insights.

**Comment by balazsorban44** [comment]
Anyone reporting this, could you state your `next-auth` version and add a reproduction? It's hard to guess what the problem is without seeing the code. Based on [this comment](https://github.com/nextauthjs/next-auth/issues/5585#issuecomment-1285689240):
> Little update from me. I updated to the newest version of next@12.3.1 and next-auth@4.14.0 and it worked again.

It might have been a regression that is now fixed, so please upgrade to `next-auth@latest` before reporting back here.

**Comment by s-chillo** [comment]
Hello
I still have the issue with 
```
 next-auth@4.16.4
 next@13.0.3
```

**Comment by AGuyNextDoor** [comment]
Deleting the cookie on my browser removed the error for me !

**Comment by ryan-keswick** [comment]
Closing this issue as clearing the browser data worked for me

**Comment by sylvaincodes** [comment]
SOLUTION HERE 

1- Go to inspect tools on your broswer 
2- Go to Application
3- Go to cookies
4-  Delete all cookies to be sure

**Comment by Kun-guru** [comment]
I was almost losing my mind.. Thank you for the clear cookies approach!!!!
That worked for me

**Comment by Nzanzu-Lwanzo** [comment]
I deleted all the cookies. Now going on my / redirects me to this error page : http://localhost:3000/auth/login?callbackUrl=http%3A%2F%2Flocalhost%3A3000%2Ffr&error=SessionRequired

I'm using a next-intl in the middleware
`
const middleware = withAuth(
    function middleware(req) {
        const { pathname } = req.nextUrl;
        const token = req.nextauth.token;
        const isAdmin = token?.role === Role.ADMIN;

        // Protect /admin routes
        if (pathname.startsWith('/admin')) {
            if (!isAdmin) {
                return NextResponse.redirect(new URL('/auth/login', req.url));
            }
        }

        return intlMiddleware(req);
    },
    {
        callbacks: {
            authorized() {
                return true; // allow all through, handle inside middleware
            }
        },
        pages: {
            signIn: '/auth/login'
        }
    }
);
`

Here are my versions of next and auth.JS
`
    "next": "15.1.6",
    "next-auth": "^4.24.11",
`
