### ISSUE TITLE
new provider - Mock

### ISSUE THREAD

**Issue by tomgcavanaugh** [nextauthjs/next-auth#5587]
### Description 📓

Today we are using an AzureAd provider, which requires the use of clientid/secret information.  We would prefer not to have to share this will all possible internal developers for an innerSource solution.

To streamline local development, I recommend the creation of a new provider "Mock".  

This provider would only be used for local development, with the session information effectively hard-coded as provider parameters.  We could then conditionally utilize the Mock provider instead of the AzureAd provider based on environment variables.

In addition to streamlining local development, this provider could also be utilized for automated testing.

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
You can already do this, using the Credentials provider + Advanced initalization:
