### ISSUE TITLE
Make Email Verification Token Unlimited.

### ISSUE THREAD

**Issue by dephraiim** [nextauthjs/next-auth#5588]
### Question 💬

I would like a user to login more than once with the same Verification Token sent using Email Login. Is this possible?

### How to reproduce ☕️

Send a login link to a user and try to login more than once.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
This is not possible and not recommended. If the verification token has expired, make the user create a new link instead.

**Comment by dephraiim** [comment]
I know this is not recommended but I found a work around. 

When you use the login link for the second time, you be redirected to a `/api/auth/error?error=Verification`

1. First increased the `maxAge` of the Email Provider a little. 
```js
// [...nextauth].ts
Email({
	maxAge: 7 * 24 * 60 * 60,
}),
```

2. Redirect the link using `redirects` in the `next.config.js` to the main route since the `maxAge` of the session is longer and the user will still be logged in.
```js
// next.config.js
const nextConfig = {
  async redirects() {
    return [
      {
        source: "/api/auth/error",
        has: [{ type: "query", key: "error", value: "Verification" }],
        destination: "/",
        permanent: true,
      },
    ];
  },
};
```

With this, the user will be able to use the same link more than once till the session expires
