### ISSUE TITLE
[Bug] Prisma 2 adapter return wrong User model on "getUserByProviderAccountId"

### ISSUE THREAD

**Issue by sondh0127** [nextauthjs/next-auth#559]
https://github.com/nextauthjs/next-auth/blob/07ef3d59c54c66c7397299f8bb57d02425272766/src/adapters/prisma/index.js#L81

It should return User model instead of Account like the TypeOrm adapter did
https://github.com/nextauthjs/next-auth/blob/07ef3d59c54c66c7397299f8bb57d02425272766/src/adapters/typeorm/index.js#L170

**Comment by iaincollins** [comment]
Sorry for the delay in responding to this (it's been a busy week!)

Thanks for reporting this bug.

**Comment by readywater** [comment]
Grateful that this was found. 
I think I'm getting the same error where the session's userId is referencing the AccountID instead of the User id.

```
[next-auth][error][session_error] TypeError: Cannot read property 'name' of null
    at /node_modules/next-auth/dist/server/routes/session.js:99:26
```

**Comment by iaincollins** [comment]
@readywater As a quick up date, we've merged in a fix, but it's not live yet - it will go out with some other fixes in the next release (I hope in the next few days)!

**Comment by readywater** [comment]
Now that I know what it is, I've just updated the Session entry with the appropriate userid so I can do the work. Looking forward to the fix and thank you for this awesome library. I'm actually testing it out for a larger existing application and really love what I see.

**Comment by readywater** [comment]
Hi @iaincollins, quick question: is there an easy way to pull a beta release of this fix into NPM? Or would you suggest just forking + building? Again, grateful for the work you guys are doing on this!

**Comment by madx** [comment]
Hi @iaincollins , any news about the availability of this fix? I've been bitten by the bug as well: getting a session upon signup works but once I try to sign in again it can't find the user since I switched user IDs to cuids (which is otherwise working fine by the way)

**Comment by readywater** [comment]
> Hi @iaincollins , any news about the availability of this fix? I've been bitten by the bug as well: getting a session upon signup works but once I try to sign in again it can't find the user since I switched user IDs to cuids (which is otherwise working fine by the way)

FYI i ended up forking and just importing that into NPM.
Just take a look at the commits to package, etc for the changes you'll need to make.
https://github.com/stupidsystems/next-auth/

**Comment by madx** [comment]
> FYI i ended up forking and just importing that into NPM.
> Just take a look at the commits to package, etc for the changes you'll need to make.
> https://github.com/stupidsystems/next-auth/

Thanks for your input, since the bug seems to reside mostly in the Prisma adapter I think I'm just gonna create a custom fork of the adapter to void having to maintain my own.
