### ISSUE TITLE
Public keycloak client

### ISSUE THREAD

**Issue by JosephBrooksbank** [nextauthjs/next-auth#5598]
### Question 💬

I'm attempting to build a new NextJS frontend for an _existing_ public keycloak client. I do not have the option to make it a confidential client, so it does not have a client secret. All of the documentation for [keycloak](https://next-auth.js.org/providers/keycloak) specifically states to use the 'confidential' access-type. 

Is there any way to use Keycloak with NextJS _without_ a client secret?

### How to reproduce ☕️

Example from the docs: 
```typescript
import KeycloakProvider from "next-auth/providers/keycloak";
...
providers: [
  KeycloakProvider({
    clientId: process.env.KEYCLOAK_ID,
    clientSecret: process.env.KEYCLOAK_SECRET, // this does not exist
    issuer: process.env.KEYCLOAK_ISSUER,
  })
]
...
```

Ideally I could do something like 
```typescript
import KeycloakProvider from "next-auth/providers/keycloak";
...
providers: [
  KeycloakProvider({
    clientId: process.env.KEYCLOAK_ID,
    url: process.env.KEYCLOAK_URL
    realm: process.env.KEYCLOAK_REALM
  })
]
...
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
it is possible, and I believe it has been answered before. please search through old issues I cannot find it right now, unfortunately. 🙏

**Comment by JosephBrooksbank** [comment]
I spent near to an hour looking through old issues and couldn't find anything before opening my own. I'll keep looking I guess.

**Comment by milosrs** [comment]
Have you found out how to do it?
@JosephBrooksbank

**Comment by milosrs** [comment]
@JosephBrooksbank  and to future readers. The `nextauth` docs are lying and I'll contribute more documentation on it.

I have managed to configure this with the public version of Keycloak. I'm using the latest version of Keycloak on Quarkus server (19.0.3).

This is my `.env.local`

````
NEXTAUTH_SECRET=QLncWsDaFotX4Y4lqZgatHjlug3CgotiexvU57pf0ys=
NEXTAUTH_URL=http://localhost:3000
KEYCLOAK_CLIENT_ID=spacemoon-frontend
KEYCLOAK_CLIENT_SECRET=Kafgakxk0mD2cNY5XuyrePyflQ0DEXXN <--- THIS CAN BE OF ANY VALUE!!!!! 
KEYCLOAK_ISSUER=http://localhost:8080/realms/spacemoon
KEYCLOAK_AUTHORIZATION=http://localhost:8080/realms/spacemoon/protocol/openid-connect/auth
KEYCLOAK_WELLKNOWN=http://localhost:8080/realms/spacemoon/.well-known/openid-configuration
````

This is my `[...nextauth].tsx`

````
export default NextAuth({
    providers: [
        KeycloakProvider({
            clientId: process.env.KEYCLOAK_CLIENT_ID ?? "",
            clientSecret: process.env.KEYCLOAK_CLIENT_SECRET ?? "",
            authorization: process.env.KEYCLOAK_AUTHORIZATION ?? "",
            issuer: process.env.KEYCLOAK_ISSUER ?? "",
            wellKnown: process.env.KEYCLOAK_WELLKNOWN ?? "",
        }),
    ],
    callbacks: {
        session: (data: SessionData): Awaitable<Session> => {         
            return data.session
        },
    },
})
````

Lastly, this is my `_app.tsx`

````
function MyApp({ Component, pageProps }: AppProps<SessionData>) {
  return <SessionProvider 
            session={pageProps.session}
            baseUrl="/realms/spacemoon/protocol/openid-connect/auth">
    <Component {...pageProps} />
  </SessionProvider>
}
````

Keycloak configuration:

Create a client on any realm you want. Configure the client to be public, and for now, configure the valid redirect URI-s to be `/api/auth/callback/keycloak`. 

That's it. You're now able to use keycloak.

**Comment by JosephBrooksbank** [comment]
Hi! My apologies, I should have updated this ticket when I found a solution. My solution was just to create a custom provider, but the big breakthrough for me was the same as you: that the client secret can be anything, (even null), as long as the prop is being fed to the provider. My code:


`[...nextauth.ts]`
```typescript
export const authOptions: NextAuthOptions = {
    // https://next-auth.js.org/configuration/providers/oauth
    providers: [
        {
            id: "keycloak",
            name: "Keycloak",
            wellKnown: `${process.env.KEYCLOAK_ISSUER}/.well-known/openid-configuration`,
            type: 'oauth',
            authorization: { params: { scope: "openid" } },
            checks: ["pkce", "state", "nonce"],
            idToken: true,
            clientId: process.env.KEYCLOAK_CLIENT_ID,
            clientSecret: process.env.KEYCLOAK_SECRET,
            client: {
                token_endpoint_auth_method: "none"
            },
            profile(profile) {
                return {
                    id: profile.sub,
                    name: profile.name ?? profile.preferred_username,
                    email: profile.email,
                    image: profile.picture,
                }
            }
        }
    ],
```

My `.env` file looks like 
```
KEYCLOAK_CLIENT_ID=myClientID
KEYCLOAK_ISSUER=https://keycloak-url.com/auth/realms/realmName
```
I don't even supply a value for `KEYCLOAK_SECRET` because it isn't necessary. This feels janky, and something should probably be changed so that `clientSecret` is not a required parameter for OAuth clients.

**Comment by ederparaiso** [comment]
It's a very weird behavior. I had same problem, since my keycloak client is a public one. It makes no sense to configure a secret with a random value and it works. They should consider change this property to optional. When a set as null or empty I receive this error:

```
client_secret_basic client authentication method requires a client_secret
```
Sadly, I'll take this suggested workaround

**Comment by ShyamUD** [comment]
> @JosephBrooksbank and to future readers. The `nextauth` docs are lying and I'll contribute more documentation on it.
> 
> I have managed to configure this with the public version of Keycloak. I'm using the latest version of Keycloak on Quarkus server (19.0.3).
> 
> This is my `.env.local`
> 
> ```
> NEXTAUTH_SECRET=QLncWsDaFotX4Y4lqZgatHjlug3CgotiexvU57pf0ys=
> NEXTAUTH_URL=http://localhost:3000
> KEYCLOAK_CLIENT_ID=spacemoon-frontend
> KEYCLOAK_CLIENT_SECRET=Kafgakxk0mD2cNY5XuyrePyflQ0DEXXN <--- THIS CAN BE OF ANY VALUE!!!!! 
> KEYCLOAK_ISSUER=http://localhost:8080/realms/spacemoon
> KEYCLOAK_AUTHORIZATION=http://localhost:8080/realms/spacemoon/protocol/openid-connect/auth
> KEYCLOAK_WELLKNOWN=http://localhost:8080/realms/spacemoon/.well-known/openid-configuration
> ```
> 
> This is my `[...nextauth].tsx`
> 
> ```
> export default NextAuth({
>     providers: [
>         KeycloakProvider({
>             clientId: process.env.KEYCLOAK_CLIENT_ID ?? "",
>             clientSecret: process.env.KEYCLOAK_CLIENT_SECRET ?? "",
>             authorization: process.env.KEYCLOAK_AUTHORIZATION ?? "",
>             issuer: process.env.KEYCLOAK_ISSUER ?? "",
>             wellKnown: process.env.KEYCLOAK_WELLKNOWN ?? "",
>         }),
>     ],
>     callbacks: {
>         session: (data: SessionData): Awaitable<Session> => {         
>             return data.session
>         },
>     },
> })
> ```
> 
> Lastly, this is my `_app.tsx`
> 
> ```
> function MyApp({ Component, pageProps }: AppProps<SessionData>) {
>   return <SessionProvider 
>             session={pageProps.session}
>             baseUrl="/realms/spacemoon/protocol/openid-connect/auth">
>     <Component {...pageProps} />
>   </SessionProvider>
> }
> ```
> 
> Keycloak configuration:
> 
> Create a client on any realm you want. Configure the client to be public, and for now, configure the valid redirect URI-s to be `/api/auth/callback/keycloak`.
> 
> That's it. You're now able to use keycloak.

using keycloak version 21. Tried this, but did not work.

**Comment by dh-jburke** [comment]
Adding that my issue was resolved when I changed the client secret to an empty string instead of a `null` value.
