### ISSUE TITLE
Ability to add custom data to session

### ISSUE THREAD

**Issue by ifightcrime** [nextauthjs/next-auth#5601]
### Description 📓

I built an "assume" feature in my app, so that admins can assume another user. I want to add an `assumedUserId` flag to the session table. This works fine, and I got the types all working. However, I can't actually get the value from `unstable_getServerSession` on the server due to this code:

https://github.com/nextauthjs/next-auth/blob/6deccf610fa16bb0e58675c842e2521d52b16dd4/packages/next-auth/src/core/routes/session.ts#L127-L139

Is there a good way to fetch all of the session data without having to do a second DB query? At that point I just as soon create my own version of `unstable_getServerSession`.

ISTM what we could do is decouple `unstable_getServerSession` from `NextAuthHandler`, and have it call the underlying code directly. That way on the server we get access to everything, and then we can pull the session callback up a layer into `NextAuthHandler` so it can still filter out the sensitive information before sending to client.

Thanks!

### How to reproduce ☕️

Not applicable.

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by Handfish** [comment]
I just hit this issue today when looking to add a middleware based on user roles. I am willing to contribute.

**Comment by balazsorban44** [comment]
See https://next-auth.js.org/getting-started/example#extensibility

FWIW, impersonating users without their consent might be bad practice.

**Comment by ifightcrime** [comment]
@balazsorban44 sure, but there are other valid use cases for this. As @Handfish mentions above.

**Comment by Handfish** [comment]
@ifightcrime the solution in the link does work. I have been experimenting with [Advanced Initialization](https://next-auth.js.org/configuration/initialization#advanced-initialization) to make [CredentialsProvider an option along with SSO providers as details here](https://github.com/nextauthjs/next-auth/discussions/4394#discussioncomment-3859770), and  I had forgotten I construct a seperate NextAuthOptions to be consumed by TRPC - I was having trouble with the linked documentation at first. This issue made me realize my mistake and fix my problem.

**Comment by ifightcrime** [comment]
@Handfish if I'm understanding that correctly (it's just the session callback right?) that wont work for me. The data I want to store is on the session itself, which gets filtered out prior to the callback via the code I mentioned above.
