### ISSUE TITLE
The engine "node" is incompatible with this module...

### ISSUE THREAD

**Issue by RonAlmog** [nextauthjs/next-auth#5602]
### Environment

I know this has been discussed in #4575 , but I still don't have a solution to simply install nextauth with yarn.
`yarn add next-auth`
error next-auth@4.14.0: The engine "node" is incompatible with this module. Expected version "^12.19.0 || ^14.15.0 || ^16.13.0". Got "18.9.0"
error Found incompatible module.

Any idea please?
i have edited the .npmrc file as suggested, that did not help, same result.

### Reproduction URL

yarn add next-auth

### Describe the issue

`yarn add next-auth` results in error, incompatible node version

### How to reproduce

just type in your console: yarn add next-auth

### Expected behavior

should install next-auth nicely.

**Comment by balazsorban44** [comment]
https://classic.yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-ignore-engines

**Comment by haltcase** [comment]
@balazsorban44 Node 18 will become LTS in 5 days. I don't think it should be expected of users to have to override the engine check when using latest LTS. Will next-auth soon support Node 18?

**Comment by RonAlmog** [comment]
True, but since I received a solution (within like 5 min), all I say is thank you.
