### ISSUE TITLE
Hey i started getting this until yesterday. everything was working and suddenly this error started throwing up. Need the help asap.

### ISSUE THREAD

**Issue by gennadiyhovrin** [nextauthjs/next-auth#5605]
Hey i started getting this until yesterday. everything was working and suddenly this error started throwing up. Need the help asap.
<img width="860" alt="Screenshot 2022-10-20 at 8 45 38 AM" src="https://user-images.githubusercontent.com/12574496/196848119-100a44a8-31ac-459d-8209-d8fb7b1cacff.png">

_Originally posted by @rahulmanas in https://github.com/nextauthjs/next-auth/issues/5585#issuecomment-1284857519_

**Comment by balazsorban44** [comment]
Let's keep this on the original thread, and please add a reproduction.
