### ISSUE TITLE
Request for pPostgresql adapter 

### ISSUE THREAD

**Issue by OlgitH** [nextauthjs/next-auth#5611]
### Description 📓

I would like to see a postgresql adapter added to the official adapters available. It seems someone has already created one, it just needs integrating.

The reasoning is mentioned here: https://www.jakobmaier.at/posts/next-auth-postgres-adapter/
The code: https://gist.github.com/gue-ni/39751d1122822ee6cf21f756b34c2c5a

Is there any benefits to using Prisma to connect to Postgres database instead of a more direct solution reducing number of dependencies needed? 

Happy to help if guided, I am just not experienced.

### How to reproduce ☕️

<-- n/a -->

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
Feel free to open a PR! 🙏

**Comment by jakecoppinger** [comment]
@OlgitH I've done most of the work in #4933 but I've hit an issue which I documented in #4897 - would love if you found a fix!

**Comment by bonesoul** [comment]
i'm also looking for this.
