### ISSUE TITLE
How can i add a user name to a user that signed in via email provider? 

### ISSUE THREAD

**Issue by ttoni** [nextauthjs/next-auth#562]
**Your question**
How can i add/update a user name to a user that signed in via email provider? 
Is it also possible to generate a default name for users that signed in with email for the first time 

**What are you trying to do**
I´m trying to force users to provide a username after the first signing. 
So after clicking on the confirmation link in the first verification email they should be redirected to a form where the user has to provide a username before using any other pages. 

**Documentation feedback**
* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by Linux249** [comment]
Have exactly the same question. 

After looking around I found the [callbacks](https://next-auth.js.org/configuration/callbacks) useful to redirect the new user to a page where he can enter other custom stuff for his profile (like `name`) after the `verificationRequest`.  But I also cannot found a way to add/update the information to the `user`/``profile`  

If you don't want this functionality built-in please point it out in the docs (read nearly the whole source code already XD) 

My suggestion ist to extend the `signIn('email', { email }` (client) with something like  `signIn('email', { email, name, phone }` (phone would be implying updating the model) if the user should give this stuff on signup and a built a `update()` function to change these information.

**Comment by richardkeller411** [comment]
Couldn't you extend the Models...  https://next-auth.js.org/schemas/adapters    Go  to Custom Models section..

**Comment by williscool** [comment]
looking at doing this myself ...

afterview reviewing the code the simplest solution to me seems to be to take the credentials provider

https://next-auth.js.org/configuration/providers#sign-in-with-credentials

and hack it to take email .. so I hacked this together to make so I could set a username its suuuuper ugly and hacky but it works


``` javascript
import NextAuth from "next-auth";
import Providers from "next-auth/providers";
import Adapters from "next-auth/adapters";
import Models from "../models";
import { randomBytes } from "crypto";

// Simple universal (client/server) function to split host and path
// We use this rather than a library because we need to use the same logic both
// client and server side and we only need to parse out the host and path, while
// supporting a default value, so a simple split is sufficent.
// https://raw.githubusercontent.com/nextauthjs/next-auth/main/src/lib/parse-url.js
const parseUrl = (url) => {
  // Default values
  const defaultHost = "http://localhost:3000";
  const defaultPath = "/api/auth";

  if (!url) {
    url = `${defaultHost}${defaultPath}`;
  }

  // Default to HTTPS if no protocol explictly specified
  const protocol = url.match(/^http?:\/\//) ? "http" : "https";

  // Normalize URLs by stripping protocol and no trailing slash
  url = url.replace(/^https?:\/\//, "").replace(/\/$/, "");

  // Simple split based on first /
  const [_host, ..._path] = url.split("/");
  const baseUrl = _host ? `${protocol}://${_host}` : defaultHost;
  const basePath = _path.length > 0 ? `/${_path.join("/")}` : defaultPath;

  debugger;
  return {
    baseUrl,
    basePath,
  };
};

const { basePath, baseUrl } = parseUrl(
  process.env.NEXTAUTH_URL || process.env.VERCEL_URL
);

const adapter = Adapters.TypeORM.Adapter(
  // The first argument should be a database connection string or TypeORM config object
  // Database optional. MySQL, Maria DB, Postgres and MongoDB are supported.
  // https://next-auth.js.org/configuration/database
  //
  // Notes:
  // * You must to install an appropriate node_module for your database
  // * The Email provider requires a database (OAuth providers do not)
  // The first argument should be a database connection string or TypeORM config object
  process.env.DATABASE_URL,
  // The second argument can be used to pass custom models and schemas
  {
    models: {
      User: Models.User,
    },
  }
);

// credentials will have name and email field and so === profile
const provider = Providers.Email({
  server: process.env.EMAIL_SERVER,
  from: process.env.EMAIL_FROM,
});

// For more information on each option (and a full list of options) go to
// https://next-auth.js.org/configuration/options
const myOptions = {
  adapter,
  baseUrl,
  // https://next-auth.js.org/configuration/providers
  providers: [provider],
  // Database optional. MySQL, Maria DB, Postgres and MongoDB are supported.
  // https://next-auth.js.org/configuration/database
  //
  // Notes:
  // * You must to install an appropriate node_module for your database
  // * The Email provider requires a database (OAuth providers do not)
  // The secret should be set to a reasonably long random string.
  // It is used to sign cookies and to sign and encrypt JSON Web Tokens, unless
  // a seperate secret is defined explicitly for encrypting the JWT.
  secret: process.env.SECRET,

  session: {
    // Use JSON Web Tokens for session instead of database sessions.
    // This option can be used with or without a database for users/accounts.
    // Note: `jwt` is automatically set to `true` if no database is specified.
    jwt: true,

    // Seconds - How long until an idle session expires and is no longer valid.
    // maxAge: 30 * 24 * 60 * 60, // 30 days

    // Seconds - Throttle how frequently to write to database to extend a session.
    // Use it to limit write operations. Set to 0 to always update the database.
    // Note: This option is ignored if using JSON Web Tokens
    // updateAge: 24 * 60 * 60, // 24 hours
  },

  // JSON Web tokens are only used for sessions if the `jwt: true` session
  // option is set - or by default if no database is specified.
  // https://next-auth.js.org/configuration/options#jwt
  jwt: {
    // A secret to use for key generation (you should set this explicitly)
    // secret: 'INp8IvdIyeMcoGAgFGoA61DdBglwwSqnXJZkgz8PSnw',
    // Set to true to use encryption (default: false)
    // encryption: true,
    // You can define your own encode/decode functions for signing and encryption
    // if you want to override the default behaviour.
    // encode: async ({ secret, token, maxAge }) => {},
    // decode: async ({ secret, token, maxAge }) => {},
  },

  // You can define custom pages to override the built-in pages.
  // The routes shown here are the default URLs that will be used when a custom
  // pages is not specified for that route.
  // https://next-auth.js.org/configuration/pages
  pages: {
    signIn: '/signin',  // Displays signin buttons
    // signOut: '/api/auth/signout', // Displays form with sign out button
    // error: '/api/auth/error', // Error code passed in query string as ?error=
    // verifyRequest: '/api/auth/verify-request', // Used for check email page
    // newUser: null // If set, new users will be directed here on first sign in
  },

  // Callbacks are asynchronous functions you can use to control what happens
  // when an action is performed.
  // https://next-auth.js.org/configuration/callbacks
  callbacks: {
    signIn: async (user, account, profile) => {
      console.log(user, account, profile);
      debugger;
      return Promise.resolve(true);
    },
    // redirect: async (url, baseUrl) => { return Promise.resolve(baseUrl) },
    // session: async (session, user) => { return Promise.resolve(session) },
    // jwt: async (token, user, account, profile, isNewUser) => { return Promise.resolve(token) }
  },

  // Events are useful for logging
  // https://next-auth.js.org/configuration/events
  events: {},

  // Enable debug messages in the console if you are having problems
  debug: true,
};

const options = {
  providers: [provider,
    Providers.Credentials({
      // The name to display on the sign in form (e.g. 'Sign in with...')
      name: "Credentials",
      // The credentials is used to generate a suitable form on the sign in page.
      // You can specify whatever fields you are expecting to be submitted.
      // e.g. domain, username, password, 2FA token, etc.
      credentials: {
        name: { label: "username", type: "text", placeholder: "pg" }, // I can already predict mixing name / and username is gonna get hairy... just comment with the alt every tiem
        email: { label: "email", type: "email" },
      },
      authorize: async (credentials) => {
        // Add logic here to look up the user from the credentials supplied
        // const user = { id: 1, name: 'J Smith', email: 'jsmith@example.com' }

        const {
          getUserByEmail,
          createUser,
          createVerificationRequest,
        } = await adapter.getAdapter(myOptions);

        const user = await getUserByEmail(credentials.email);

        if (user) {
          // Any object returned will be saved in `user` property of the JWT
          return Promise.resolve(user);
        } else {
          // If you return null or false then the credentials will be rejected
          if (!credentials.name || !credentials.email) {
            return Promise.reject(new Error("please enter username and email")); // Redirect to error page
          }

          await createUser(credentials);

          const identifier = credentials.email;
          const token = randomBytes(32).toString("hex");
          const secret = provider.secret || myOptions.secret;

          const url = `${baseUrl}${basePath}/callback/${encodeURIComponent(
            provider.id
          )}?email=${encodeURIComponent(
            credentials.email
          )}&token=${encodeURIComponent(token)}`;

          debugger
          await createVerificationRequest(
            identifier,
            url,
            token,
            secret,
            provider
          );

          // then we fire off email and redirect user to the check your email page
          return Promise.reject(
            "/checkYaEmail"
          );
          // You can also Reject this callback with an Error or with a URL:
          // return Promise.reject(new Error('error message')) // Redirect to error page
          // return Promise.reject('/path/to/redirect')        // Redirect to a URL
        }
      },
    }),
  ],
};

export default (req, res) => {
  return NextAuth(req, res, {...myOptions, ...options } );
};

```

ps I really wish more of the things I had to copy were exportable and the code was more decoupled but this got my project unblocked  so ¯\_(ツ)_/¯

**Comment by MrNghia123** [comment]
I have the same problem. I am using next-auth for a role-based authorization system and the verification request need to be created by the admin for the other users. Each user will then have roles attached to their account.
To implement that the closest thing we have is the signIn('email',{email}) function in which I would need to be able to extend the second parameter to include a list of roles for the user, something like signIn('email',{email, roles}). Then the roles need to be persisted into the verification_requests table, maybe by extending the model and a custom createVerificationRequest method. 
However looking at the signin route (src/server/routes/signin.js in the source code, only the email is extracted from the request body for the emailSignin function.

I think it make more sense for not just the email but all the submission data (phone, user name, roles, etc,) to be passed into the emailSignin and later on, to the createVerificationRequest so it can be persisted and later on taken out to create the user.

@iaincollins if you think it make sense I can make a pull request.

`  } else if (type === 'email' && req.method === 'POST') {
    if (!adapter) {
      logger.error('EMAIL_REQUIRES_ADAPTER_ERROR')
      return redirect(`${baseUrl}${basePath}/error?error=Configuration`)
    }
    const { getUserByEmail } = await adapter.getAdapter(options)

    // Note: Technically the part of the email address local mailbox element
    // (everything before the @ symbol) should be treated as 'case sensitive'
    // according to RFC 2821, but in practice this causes more problems than
    // it solves. We treat email addresses as all lower case. If anyone
    // complains about this we can make strict RFC 2821 compliance an option.
    const email = req.body.email ? req.body.email.toLowerCase() : null

    // If is an existing user return a user object (otherwise use placeholder)
    const profile = await getUserByEmail(email) || { email }
    const account = { id: provider.id, type: 'email', providerAccountId: email }

    // Check if user is allowed to sign in
    try {
      const signinCallbackResponse = await callbacks.signIn(profile, account, { email, verificationRequest: true })
      if (signinCallbackResponse === false) {
        return redirect(`${baseUrl}${basePath}/error?error=AccessDenied`)
      }
    } catch (error) {
      if (error instanceof Error) {
        return redirect(`${baseUrl}${basePath}/error?error=${encodeURIComponent(error)}`)
      } else {
        return redirect(error)
      }
    }

    try {
      await emailSignin(email, provider, options)
    } catch (error) {
      logger.error('SIGNIN_EMAIL_ERROR', error)
      return redirect(`${baseUrl}${basePath}/error?error=EmailSignin`)
    }

    return redirect(`${baseUrl}${basePath}/verify-request?provider=${encodeURIComponent(
      provider.id
    )}&type=${encodeURIComponent(provider.type)}`)
  } else {
    return redirect(`${baseUrl}${basePath}/signin`)
  }
`

**Comment by DeBraid** [comment]
> But I also cannot found a way to add/update the information to the user/profile

I am trying to decorate `session.user` with additional properties, like `role`.

Docs show that `user` object resolved from `authorize` fn will be `saved in user`, but my experience this NOT true for arbitrary properties added to `user` on the fly.

```
authorize: async (credentials) => {
  // Add logic here to look up the user from the credentials supplied
  let user = { id: 1, name: 'J Smith', email: 'jsmith@example.com' }
  user.foo = 'bar';
  if (user) {
    // Any object returned will be saved in `user` property of the JWT
    return Promise.resolve(user);
  }
  ...
```

In the above example, my `session.user` will NOT contain a reference to `foo`.  Can I not extend the `user` object?
