### ISSUE TITLE
Credential Provider Wrong example

### ISSUE THREAD

**Issue by jackykwandesign** [nextauthjs/next-auth#5620]
### What is the improvement or update you wish to see?

When copy from example, the return type of `authorize`, User's id is a number, which somehow againist the typing
![image](https://user-images.githubusercontent.com/46065771/197379136-7eff595a-9b0f-4008-b026-d581e6f2d160.png)

Error
![image](https://user-images.githubusercontent.com/46065771/197379191-cfc9a61a-8451-46d0-8420-223ce21010ef.png)

But when i change to string, typescript error disappear
![image](https://user-images.githubusercontent.com/46065771/197379184-4aded86f-7435-4bd0-9651-3fa09c7f8cd9.png)

### Is there any context that might help us understand?

update examples, and maybe provide example to custom User type return by `authorize` function

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/configuration/providers/credentials

**Comment by brunocrosier** [comment]
This is fixed in v4.14.0 https://github.com/nextauthjs/next-auth/commit/fe7aaeded872a5ca17c01fa835e42cedf2bc7e83#diff-67a2014246b86507577bda4b1742f4ce8dfc2728cb22a09a6a034fa73252cceb

I think we can close this issue now

**Comment by ThangHuuVu** [comment]
Good catch, the doc issue should be fixed now @jackykwandesign, thanks @brunocrosier for jumping in 🙌
