### ISSUE TITLE
Type 'string | undefined' is not assignable to type 'string'.   Type 'undefined' is not assignable to type 'string'.ts(2322) oauth.d.ts(83, 5): The expected type comes from property 'clientId' which is declared here on type 'OAuthUserConfig<any>'

### ISSUE THREAD

**Issue by temrb** [nextauthjs/next-auth#5625]
### Provider type

Google

### Environment

I get this error when using google provider:

![Screen Shot 2022-10-23 at 1 21 53 PM](https://user-images.githubusercontent.com/22056864/197409169-fc4c47e7-ebea-4702-9c1b-11d5d8598c3e.png)

Tho I think temp fix is this?: 

![Screen Shot 2022-10-23 at 1 26 37 PM](https://user-images.githubusercontent.com/22056864/197409278-0b4112b5-f474-456f-a8b5-731e8be6b7f0.png)

Unless there is a better way to do this ?

Same issue occurs without using nextauthoptions

### Reproduction URL

n/a

### Describe the issue

Getting type errors from auth options

### How to reproduce

`import NextAuth, { NextAuthOptions } from 'next-auth';
import GoogleProvider from 'next-auth/providers/google';

import { FirestoreAdapter } from '@next-auth/firebase-adapter';
import { config } from '../../../lib/firebaseConfig';

export const authOptions: NextAuthOptions = {
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID,
    }),
  ],

  adapter: FirestoreAdapter({
    ...config,
  }),
};

export default NextAuth(authOptions);
`

### Expected behavior

Correct types without type errors

**Comment by shekmeister** [comment]
You can fix this error by type casting the env variable to string by doing this:
`clientId: process.env.GOOGLE_CLIENT_ID as string`

However, i'm not sure if its the best way to fix this problem.

**Comment by temrb** [comment]
That fixed it thanks!
