### ISSUE TITLE
Appwrite adapter 

### ISSUE THREAD

**Issue by scshiv29-dev** [nextauthjs/next-auth#5636]
### Description 📓

an adapter for appwrite , which is an open source baas and is selfhostable.

### How to reproduce ☕️

purpose of the feature is to allow saving of user data to appwrite 

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by ThangHuuVu** [comment]
PR welcomes! Here's the link to writing your own adapter: https://next-auth.js.org/adapters/overview#custom-adapter

**Comment by Adarsreg** [comment]
Could you please reopen this issue?

**Comment by Chaitanya-Upadhye** [comment]
Could we re-open this issue? I am willing to contribute to help implement this feature.
