### ISSUE TITLE
Node.js 18 Support

### ISSUE THREAD

**Issue by yogarasu** [nextauthjs/next-auth#5639]
### Question 💬

Node.js 18 LTS is starting, but this repository restricts the use of Node.18 in the engine in package.json.
Bugs for Node.js 18 seem to be all closed, is there anything blocking support?

I opened a discussion before, but now that LTS has started, I'll post it here as well.
https://github.com/nextauthjs/next-auth/discussions/5329

### How to reproduce ☕️

----

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by yogarasu** [comment]
Reference: Node.js Release Schedule
https://github.com/nodejs/release#release-schedule

**Comment by panva** [comment]
v18.12.0 has not yet been released so technically this

> now that LTS has started

is not true for the next couple hours and for all previously released v18.x versions.

**Comment by ThangHuuVu** [comment]
Let's keep this open to keep track of adding Node v18 to the engine compatibility list 👀

**Comment by ryanelian** [comment]
+1 to this and allowing next-auth to be installed with the just-released Next.js 13

Right now next-auth cannot be installed with Next.js 13 using npm due to `peerDependencies` throwing errors.

**Comment by yogarasu** [comment]
Sorry for false start.
Thank you!

**Comment by daniharo** [comment]
`next-auth` won't work in Node 18 until `openid-client` dependency is updated to a new version which includes this commit: https://github.com/panva/node-openid-client/commit/9aefba30dcf0e312051e6844b35b06bc457488d5.

Current version 5.1.6 gives this error:

```
openid-client@5.1.6: The engine "node" is incompatible with this module. Expected version "^12.19.0 || ^14.15.0 || ^16.13.0". Got "18.12.1"
```

**Comment by nfts2me** [comment]
At least on Vercel using Node 18.x makes NetxAuth behave differently from 16.x branch.
