### ISSUE TITLE
API Call

### ISSUE THREAD

**Issue by iatulb** [nextauthjs/next-auth#564]
*Please refer to the [documentation](https://next-auth.js.org/getting-started/introduction), the [example project](https://github.com/iaincollins/next-auth-example) and existing issues before creating a new issue.*

**Your question**
I am trying to use RESTApi "/api/auth/signin/google" through axios post request. It is not opening Google Login page. Instead it is opening "/api/auth/signin" page, again i have to click "Sign in with Google". What is the issue?

**What are you trying to do**
const url = '/api/auth/signin/google';
                const formData = new FormData();
                formData.append('csrfToken', response.data.csrfToken)
                formData.append('callbackUrl', 'http://localhost:3000')
                const config = {
                    headers: {
                        'content-type': 'multipart/form-data'
                    }
                }
                axios.post(url, formData,config).then((response)=>{
                    console.log(response.data);
                  })

**Comment by ndom91** [comment]
Try `'Content-Type': 'application/x-www-form-urlencoded'`. Other than that nothign obvious stands out to me.

You can take a look at what the `signin()` method is doing here: https://github.com/nextauthjs/next-auth/blob/9c4e41a4c6dee7cc608f18b49bf9c1e2588fb857/src/client/index.js#L225-L256

**Comment by LoriKarikari** [comment]
@iatulb did you get it working based on @ndom91's suggestion?

**Comment by iatulb** [comment]
@LoriKarikari No :)
