### ISSUE TITLE
Next.js 13 - Middleware - Expected an instance of Response to be returned

### ISSUE THREAD

**Issue by creazy231** [nextauthjs/next-auth#5649]
### Environment

  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 1.03 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Brave Browser: 106.1.44.112
    Chrome: 106.0.5249.119
    Firefox: 104.0.2
    Safari: 16.0

### Reproduction URL

.

### Describe the issue

Implementing a middleware.js in Next.js 13 like described here (https://next-auth.js.org/tutorials/securing-pages-and-api-routes#nextjs-middleware) results in the following error:

```
Server Error
TypeError: Expected an instance of Response to be returned

Call Stack
adapter
../node_modules/next/dist/esm/server/web/adapter.js (90:0)
```

### How to reproduce

Implement Next-Auth with Next.js 13 and create a middleware.js with the following content:

```
export { default } from "next-auth/middleware";
```

### Expected behavior

No fatal error

**Comment by joaopaulomoraes** [comment]
The same here!

**Comment by joaopaulomoraes** [comment]
The same here!

In my case I protect all `/admin/*` routes and I have the same error, only on these pages, the others compile successfully. Code example:

```ts
export { default } from 'next-auth/middleware'

export const config = { matcher: ['/admin/(.*)'] }
```

**Comment by RudiPersson** [comment]
Also experiencing this. 

No issues if i remove my middleware.ts file.

Code: 
`export { default } from "next-auth/middleware";

export const config = {
  matcher: ["/((?!login|api|_next|static|favicon.ico).*)"],
};
`

**Comment by lantaozi** [comment]
I meet the same issue, and I found something interesting.

I used `withAuth` middleware by calling in the way `withAuth(req, nextAuthOption);`, and it return a function instead of Response. It causes the error.

 After review the source code, I found it doesn't recogonized the first param as NextRequest: 
`
export function withAuth(...args: WithAuthArgs) {
  if (!args.length || args[0] instanceof NextRequest) {
    // @ts-expect-error
    return handleMiddleware(...args)
  }

  if (typeof args[0] === "function") {
    const middleware = args[0]
    const options = args[1] as NextAuthMiddlewareOptions | undefined
    return async (...args: Parameters<NextMiddlewareWithAuth>) =>
      await handleMiddleware(args[0], options, async (token) => {
        args[0].nextauth = { token }
        return await middleware(...args)
      })
  }

  const options = args[0]
  return async (...args: Parameters<NextMiddleware>) =>
    await handleMiddleware(args[0], options)
}
`

Interesting, isn't is ???

I print the stack of the call potint, the result is:
`
    at Object.middleware [as handler] (webpack-internal:///(middleware)/./middleware.ts:27:24)
    at adapter (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/adapter.js:102:33)
    at __WEBPACK_DEFAULT_EXPORT__ (webpack-internal:///(middleware)/./node_modules/next/dist/build/webpack/loaders/next-middleware-loader.js?absolutePagePath=%2FUsers%2Flantaozi%2FWorkspace%2Ficecream%2Fmiddleware.ts&page=%2Fmiddleware&rootDir=%2FUsers%2Flantaozi%2FWorkspace%2Ficecream&matchers=!:19:180)
    at /Users/lantaozi/Workspace/icecream/node_modules/next/dist/server/web/sandbox/sandbox.js:73:30
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DevServer.runMiddleware (/Users/lantaozi/Workspace/icecream/node_modules/next/dist/server/next-server.js:1122:24)
    at async DevServer.runMiddleware (/Users/lantaozi/Workspace/icecream/node_modules/next/dist/server/dev/next-dev-server.js:634:28)
    at async Object.fn (/Users/lantaozi/Workspace/icecream/node_modules/next/dist/server/next-server.js:1201:38)
    at async Router.execute (/Users/lantaozi/Workspace/icecream/node_modules/next/dist/server/router.js:252:36)
`

The adapter.js is from `node_modules/next/dist/esm/server/web/adapter.js` which used to be `node_modules/next/dist/server/web/adapter.js`.  So the request is a NextRequest instance from **esm/server/web/spec-extension** package instead of **server/web/spec-extension**

It seems that there is no package with the path of `esm` in previous version of Next.js (before 13). 

I'm not familar with it, anyone know what it is can help me.

**Comment by PauloFerrazACCT** [comment]
I'm getting the same error here

**Comment by midzdotdev** [comment]
Yep same here, we're looking forward to a fix on this. Putting a pause on our migration to Next 13 until this is stable.

**Comment by ThangHuuVu** [comment]
Very good catch @lantaozi, the issue is this check
https://github.com/nextauthjs/next-auth/blob/733fd5f2345cbf7c123ba8175ea23506bcb5c453/packages/next-auth/src/next/middleware.ts#L187
With the default middleware configuration, this condition should be met, but for `next@13`, it fails. 
cc @balazsorban44 could this be an upstream issue? There's nothing related to middleware changes in [The migration doc](https://beta.nextjs.org/docs/upgrade-guide#) 🤔

**Comment by 3atharvkurdukar** [comment]
Is there any workaround for now?

**Comment by copini** [comment]
For me explicitly exporting `withAuth` with an empty options argument seems to work:

```javascript
import { withAuth } from 'next-auth/middleware'

export default withAuth({})
```

**Comment by joaopaulomoraes** [comment]
> For me explicitly exporting `withAuth` with an empty options argument seems to work:
> 
> ```js
> import { withAuth } from 'next-auth/middleware'
> 
> export default withAuth({})
> ```

But then all routes are private, including login/logout and in that case if you log out for some reason, you are in several infinite loops

**Comment by Eleanor-01** [comment]
> > For me explicitly exporting `withAuth` with an empty options argument seems to work:
> > ```js
> > import { withAuth } from 'next-auth/middleware'
> > 
> > export default withAuth({})
> > ```
> 
> But then all routes are private, including login/logout and in that case if you log out for some reason, you are in several infinite loops

it redirecting to the Sign In page for all the routes

With a little hack around exporting `config` with `withAuth` and boom It's working for me
```
import { withAuth } from "next-auth/middleware"

export const config = { matcher: ["/dashboard/:path*"] }
export default withAuth({})
```

**Comment by Lucasvo1** [comment]
I am using middleware with the following content and the oAuth is done correctly, but the page always stays on the login page, no way of going to another page. I upgraded to the last release btw. Debug is enabled but no error messages. 

`export { default } from 'next-auth/middleware';`

**Comment by jeslenbucci** [comment]
I was just having this same issue after upgrading to Next 13. I was using ` "next-auth": "^4.12.0",` and ran `yarn upgrade next-auth` and it started working with this as my middleware. My middleware is also a typescript file, if that makes a difference.

```
export { default } from 'next-auth/middleware'

export const config = { matcher: ['/dashboard/:path*'] }
```

**Comment by dawidseipold** [comment]
None of the workarounds seem to work for me. It just redirects me to either login page (doesn't matter if the user is logged in or not), or doesn't do anything at all.

**Comment by jeslenbucci** [comment]
@dawidseipold

> None of the workarounds seem to work for me. It just redirects me to either login page (doesn't matter if the user is logged in or not), or doesn't do anything at all.

Same thing ended up happening to me. This is what I eventually set my middleware file to:

```
Headers.prototype.getAll = () => []

export { default as middleware } from 'next-auth/middleware'

export const config = { matcher: ['/dashboard/:path*'] }

```

The first part is a hack because there was a breaking change when publishing to production. Not also that I'm exporting the `next-auth/middleware` as `middleware` because this update expects a function, not default, called middleware to be exported as of Next 13

**Comment by dawidseipold** [comment]
@jeslenbucci Unfortunately your solution doesn't work for me ☹️

**Comment by maitrungduc1410** [comment]
> > > For me explicitly exporting `withAuth` with an empty options argument seems to work:
> > > ```js
> > > import { withAuth } from 'next-auth/middleware'
> > > 
> > > export default withAuth({})
> > > ```
> > 
> > 
> > But then all routes are private, including login/logout and in that case if you log out for some reason, you are in several infinite loops
> 
> it redirecting to the Sign In page for all the routes
> 
> With a little hack around exporting `config` and `withAuth` and boom It's working for me
> 
> ```js
> import { withAuth } from "next-auth/middleware"
> 
> export const config = { matcher: ["/dashboard/:path*"] }
> export default withAuth({})
> ```

doesn't work for me, it all returns `307 Temporary Redirect`:
```ts
// middleware.ts
import { withAuth } from "next-auth/middleware"

export const config = { matcher: ["/api/:path*"] }
export default withAuth({})
```

**Comment by savvytitan** [comment]
@Lucasvo1 @jeslenbucci Where is the `middleware.ts` file located in your project? I put it in the project's root directory and it doesn't work.

**Comment by d9j** [comment]
nextjs 13 seems quite alpha.. middleware doesnt work at all..

**Comment by Alwurts** [comment]
I was having trouble with withAuth() where the token was being returned null

`import { withAuth } from "next-auth/middleware";

export default withAuth(
  {
    callbacks: {
      async authorized({ token }) {
        return !!token;
      },
    },
  }
);

export const config = {
  matcher: ["/app/:path*", "/api/((?!auth).*)"],
};`

What fixed it for me was to downgrade next js to 13.0.0

**Comment by BeezBeez** [comment]
Even today on nextjs 13.2.4 and nextauth 4.20.1. My middleware is not working properly. I am constantly redirected to the login page when I try to access the protected routes, even after logging in.

**Comment by viniyr** [comment]
Same error here with: 
`
"next-auth": "^4.22.1",
"next": "13.4.3"
`

middleware.ts

```js
import { withAuth } from 'next-auth/middleware'


export const config = {
  matcher: ["/((?!auth|signin|auth/signin).*)"],
};
export default withAuth({})
```

If I try to access any page it redirects me to signin page, even if I'm successfully logged in

**Comment by JuanQuiro** [comment]
I had the same error and updated nextjs to 13.4.5-canary.4, it allows me to compile, but still can't identify if the user is logged in or not.

### Commands applied
`pnpm install --save next@canary`

### Reproduction of the problem

https://github.com/nextauthjs/next-auth/assets/54697159/9c5e0d11-8c9a-4ad4-a9d3-30afb4f3c366

### middleware.ts
```
export { default } from 'next-auth/middleware';
export const config = { matcher: ['/workout'] };
```
### Versions
```
"next": "13.4.5-canary.4",
"next-auth": "4.22.1",
```

**Comment by abheist** [comment]
I'm still getting this. @balazsorban44 any updates ? 🙃

**Comment by abheist** [comment]
Following change worked for me:


`middleware.ts`
```ts
export { default } from "next-auth/middleware";

export const config = { matcher: ["/n"] };
```

`auth.ts` authOptions
- Added session strategy
- change in session callback
- change in jwt callback
```ts
import type { NextAuthOptions } from "next-auth";
import GoogleProvider from "next-auth/providers/google";
import { PrismaAdapter } from "@auth/prisma-adapter";
import { prisma } from "@/lib/prisma";

export const authOptions: NextAuthOptions = {
  // @ts-ignore
  adapter: PrismaAdapter(prisma),
  session: {
    strategy: "jwt",
  },
  providers: [
    GoogleProvider({
      clientId: "****",
      clientSecret: "****",
      authorization: {
        params: {
          prompt: "consent",
          access_type: "offline",
          response_type: "code",
        },
      },
    }),
  ],
  secret: process.env.NEXTAUTH_SECRET,
  callbacks: {
    async signIn({ user, account, profile, email, credentials }) {
      console.log("fire signin Callback");
      return true;
    },
    async redirect({ url, baseUrl }) {
      console.log("fire redirect Callback");
      return baseUrl;
    },
    async session({ session, user, token }) {
      console.log("fire SESSION Callback");
      return {
        ...session,
        user: {
          ...session.user,
          id: token.id,
          randomKey: token.randomKey,
        },
      };
    },
    async jwt({ token, user, account, profile, isNewUser }) {
      console.log("fire jwt Callback");
      if (user) {
        const u = user as unknown as any;
        return {
          ...token,
          id: u.id,
          randomKey: u.randomKey,
        };
      }
      return token;
    },
  },
};

```

**Comment by rharkor** [comment]
Still doesnt work for me..

**Comment by ronnycoding** [comment]
the following solution works for me

```javascript
export default withAuth(
  function middleware(req: NextRequestWithAuth) {
	//...
  },
  {
    pages: {
      signIn: LOGIN_ROUTE,
    },
    jwt: { decode: jwtConfig?.decode },
    callbacks: {
      authorized: async ({ req, token }) => {
        const rawToken = await getToken({
          req,
          secret: process.env.NEXTAUTH_SECRET,
          decode: jwtConfig?.decode,
          raw: true,
        });

		if (!!rawToken) {
			... validate signature 
		}
		// or
        return !!token || !!rawToken;
      },
    },
    secret: process.env.NEXTAUTH_SECRET,
  }
);
```

**Comment by joaopaulomoraes** [comment]
The following works to me in `src/middleware.ts`

```ts
export { default } from 'next-auth/middleware'

export const config = { matcher: ['/admin/(.*)'] }
```

Version `"next-auth": "^4.22.3"`

**Comment by joaopaulomoraes** [comment]
`pages/api/auth/[...nextauth].ts`

```ts
import NextAuth from 'next-auth'

export default NextAuth({
  secret: env.NEXTAUTH_SECRET
})
```

**Comment by carlosriveroib** [comment]
Still not working with app directory.... and the issue is close. This package is really difficult to use. I'm really have troubles with this

**Comment by danesto** [comment]
Had the same problem with: `"next": "13.4.9", "next-auth": "^4.23.1",`. What's weird is that it is working when deployed to Vercel, but not locally. 

It did work locally for some time, but for some reason it just stopped working, and no matter what - it would always stay on login page. 

After hours of investigation, what finally worked for me (for now) was adding:
`NEXTAUTH_URL=http://localhost:3000` inside my .env file.

And my middleware.ts file is the same as in the comments above:
```
import { withAuth } from 'next-auth/middleware';

export const config = { matcher: ['/dashboard/:path*'] };
export default withAuth({});
```

**Comment by gavinwun** [comment]
I got this working in the end - sorry a bit rough but sleeping for the night after pulling my hair out for a while lol

`import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'
import { withAuth } from "next-auth/middleware";

export default withAuth(
  {
    callbacks: {
      async authorized({ token }) {
        return !!token;
      },
    },
  }
);

// This function can be marked `async` if using `await` inside
export function middleware(request: NextRequest) {
    //   return NextResponse.redirect(new URL('/', request.url))
}

// See "Matching Paths" below to learn more
export const config = {
    matcher: '/api/books/:path*',
}`

**Comment by lucasccampos** [comment]
If you're using AuthJS v5 and next-intl

try this middleware.ts

```
import { auth } from "@/auth";
import createMiddleware from 'next-intl/middleware';
import { routing } from './i18n/routing';
import { NextResponse} from "next/server";

const intlMiddleware = createMiddleware(routing);

export const config = {
    matcher: [
        '/((?!api|_next|.*\\..*).*)'
    ]
};

export default auth((req) => {
    if (req.nextUrl.pathname.startsWith("/client") && !req.auth) {
        const loginUrl = new URL("/login", req.nextUrl.origin);
        loginUrl.searchParams.set("callbackUrl", req.nextUrl.pathname); // Store the original page

        return NextResponse.redirect(loginUrl)
    }
    return intlMiddleware(req);
})
```

**Comment by Confuze** [comment]
@lucasccampos Thanks a lot - your solution works really well but I have one problem. For whatever reason authjs insists on running its middleware on every route no matter what. Say for example, you only need auth for an admin panel:
```ts
// auth.ts
export default function middleware(req: NextRequest) {
  if (req.nextUrl.pathname.startsWith("/admin")) {
    return auth((req) => {
      const authenticated = !!req.auth;

      if (!authenticated) {
        return Response.redirect(
          new URL("/admin/login", req.nextUrl.origin),
        );
      } else return NextResponse.next();
    });
  } else {
    return intl(req);
  }
}
// this example assumes that it doesn't need i18n on the admin panel but it works the same if you use the i18n middleware there too.
```
This actually results with the same error `Expected an instance of Response to be returned` on any of the `/admin` routes. Is this expected behavior or have I discovered a bug? Seems a bit excessive to run the middleware on pages where auth is not required.
