### ISSUE TITLE
NextJS 13 Dependency Error

### ISSUE THREAD

**Issue by indralukmana** [nextauthjs/next-auth#5650]
### Environment

```
  System:
    OS: Linux 5.10 Pengwin 11 (bullseye)
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 12.19 GB / 15.61 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  npmPackages:
    next: 13.0.0 => 13.0.0
    react: 18.2.0 => 18.2.0
```

### Reproduction URL

none

### Describe the issue

I tried to upgrade my existing project to NextJS 13, but got blocker from next-auth package. The error as follows

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: next13@0.1.0
npm ERR! Found: next@13.0.0
npm ERR! node_modules/next
npm ERR!   next@"13.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^12.2.5" from next-auth@4.15.0
npm ERR! node_modules/next-auth
npm ERR!   next-auth@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

This also happens when installing on newly created project.

### How to reproduce

1. Create new NextJS project using `npm`
    
    ```shell
    npx create-next-app nextjs13
    ```
    
1. Change directory to the newly created project

    ```shell
    cd nextjs13
    ```

1. Try to install `next-auth`

    ```shell
    npm install next-auth
    ```

Then got the error mentioned above

### Expected behavior

`next-auth` can be used on NextJS 13 projects

**Comment by ThangHuuVu** [comment]
I tried the reproduction steps but didn't get any errors 🤔 I also tried to pull our example repo and install, as our example repo has specified `"next": "latest"` dependencies, I also didn't get any errors 🤷‍♂️

**Comment by igordanchenko** [comment]
@ThangHuuVu, would you mind sharing your npm version? npm install fails because next-auth@4.15.0 literally requires next@12:

https://github.com/nextauthjs/next-auth/blob/a787efc6bec26067c75ce22b2f213ddec6fbfa0d/packages/next-auth/package.json#L80-L81

```shell
% node -v
v16.18.0

% npm -v
8.19.2

% npm install next-auth
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: nextjs13@0.1.0
npm ERR! Found: next@13.0.0
npm ERR! node_modules/next
npm ERR!   next@"13.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^12.2.5" from next-auth@4.15.0
npm ERR! node_modules/next-auth
npm ERR!   next-auth@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/home/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/home/.npm/_logs/2022-10-26T15_42_37_953Z-debug-0.log
```

**Comment by igordanchenko** [comment]
It may also be helpful to make sure `npx` is using the latest `create-next-app` version:

```shell
npx create-next-app@13 nextjs13
```

**Comment by enricoros** [comment]
Same issue, next@13 is not supported by next-auth@4.15.0

**Comment by raulmarindev** [comment]
I also get the error, I believe this won't work unless the peer dependency for next in next-auth is updated.

**Comment by RyelBanfield** [comment]
Everything works fine for me using yarn but I am getting this warning:

warning " > next-auth@4.15.0" has incorrect peer dependency "next@^12.2.5".

**Comment by FullstackJack** [comment]
Sadly, I had to use `npm i next-auth --legacy-peer-deps` to get the error to "go away", but clearly we need `next-auth` to officially support Next.js 13.

**Comment by HotCustard** [comment]
Adding 
`"overrides": {
    "next-auth": {
      "next": "13.0.0"
    }
  }`
to package.json will allow installing without --force or --legacy-peer-deps

**Comment by ThangHuuVu** [comment]
Apologize, yes I can confirm this is an issue, rolling out a fix now 🙌

**Comment by sergeyzwezdin** [comment]
@ThangHuuVu when do you plan to rollout next@13 compatible release?

**Comment by cobbvanth** [comment]
When will this peer dependency be updated?

**Comment by timothymiller** [comment]
When fix release?

**Comment by sergeyzwezdin** [comment]
@balazsorban44 thank you! do you have understanding when this fix could be released?

**Comment by GabrielFerrarini** [comment]
@balazsorban44 @ThangHuuVu any ideas when the update will make it to npm?

**Comment by hireshBrem** [comment]
> @ThangHuuVu, would you mind sharing your npm version? npm install fails because next-auth@4.15.0 literally requires next@12:
> 
> https://github.com/nextauthjs/next-auth/blob/a787efc6bec26067c75ce22b2f213ddec6fbfa0d/packages/next-auth/package.json#L80-L81
> 
> ```shell
> % node -v
> v16.18.0
> 
> % npm -v
> 8.19.2
> 
> % npm install next-auth
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: nextjs13@0.1.0
> npm ERR! Found: next@13.0.0
> npm ERR! node_modules/next
> npm ERR!   next@"13.0.0" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer next@"^12.2.5" from next-auth@4.15.0
> npm ERR! node_modules/next-auth
> npm ERR!   next-auth@"*" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR! See /Users/home/.npm/eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/home/.npm/_logs/2022-10-26T15_42_37_953Z-debug-0.log
> ```

Legend!

**Comment by swe** [comment]
I fixed this just by changing these lines:
```
"peerDependencies": { 
   "next": "^12.2.5", 
```
To these:
```
"peerDependencies": { 
   "next": "latest", 
```

**Comment by ArefAhmadinezhad** [comment]
Adding
 "overrides": { "next-auth": "4.24.7" },
to package.json and delete node_modules folder and run  npm i
