### ISSUE TITLE
Mail.ru, error: missing request parameter: access_token

### ISSUE THREAD

**Issue by ivangorbunoff** [nextauthjs/next-auth#5660]
### Provider type

Mail.ru

### Environment

System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (6) x64 AMD Ryzen 5 3500X 6-Core Processor
    Memory: 21.41 GB / 31.27 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.18.0 - /usr/bin/node
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 105.0
  npmPackages:
    next: 12.2.5 => 12.2.5 
    next-auth: ^4.14.0 => 4.14.0 
    react: 18.2.0 => 18.2.0 

### Reproduction URL

https://github.com/ivangorbunoff/next-auth-example-mailru

### Describe the issue

Hello! I can’t log in through the mail.ru provider. I registered the application, but when I try to authorize, I get a missing request parameter: access_token error after I allow the application to use my account data. [screenshot](http://joxi.ru/KAxwJVptwy7732)
I did everything manually as described in the  [instructions](https://o2.mail.ru/docs) avoid a breakdown on the mail.ru server, through curl and postman, and I managed to get my data. But I got the same error {
    error: 'invalid request',
    error_code: 2
    error_description: 'missing request parameter: **access_token**'
  },
The problem was that it was necessary to wrap the query string in quotes. I think this might be the issue?
this is how I got my **access_token**:
"https://oauth.mail.ru/token?grant_type=authorization_code&code=b42019a80b7d76b388b504cc4366e98425fcbd3e37363830&redirect_uri=http://domain.net/&client_id=<client_id>&client_secret=<client_secret>"
Sorry for my English(

### How to reproduce

add MAILRU_CLIENT_ID and MAILRU_CLIENT_SECRET to .env.local and try login

### Expected behavior

authorization should occur, but it returns me to the provider selection screen

**Comment by ThangHuuVu** [comment]
Can you show the output of AUTHORIZATION_URL in your debug terminal?

**Comment by ivangorbunoff** [comment]
> Can you show the output of AUTHORIZATION_URL in your debug terminal?

Hi!
[next-auth][debug][GET_AUTHORIZATION_URL] {
  url: 'https://oauth.mail.ru/login?client_id=8f0144cc89b9424984bb58beb54bba85&scope=userinfo&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fauth%2Fcallback%2Fmailru&state=bjL2qg-zUm1YMZm-BNMiFtMYj-FELIbQ17ipqkAiBEA',

**Comment by ThangHuuVu** [comment]
It seems that the authorization request is correct 🤔 Can you turn on `debug: true` and see what's the result of `PROFILE_DATA`?  (sorry for the delayed response!)

**Comment by ivangorbunoff** [comment]
`[next-auth][debug][PROFILE_DATA] {
  OAuthProfile: {
    error: 'invalid request',
    error_code: 2,
    error_description: 'missing request parameter: access_token'
  }
}
`
I think it happens at the stage of receiving the token. 
[screenshot](http://joxi.ru/5mdEB01uJR1ng2) 
[documentation](https://o2.mail.ru/docs)
Thanks )

**Comment by ivangorbunoff** [comment]
[call stack screenshot](http://joxi.ru/8AnwbGatKZ0xPr)

**Comment by reklamafia** [comment]
The problem is still relevant

**Comment by gosvoh** [comment]
> The problem is still relevant

You can create custom provider and at works for me
```typescript
{
  id: "mailru",
  name: "Mail.ru",
  type: "oauth",
  clientId: process.env.MAILRU_CLIENT_ID,
  clientSecret: process.env.MAILRU_SECRET,
  authorization: "https://oauth.mail.ru/login",
  token: "https://oauth.mail.ru/token",
  userinfo: {
    async request(context) {
      const res = await fetch(
        `https://oauth.mail.ru/userinfo?access_token=${context.tokens.access_token}`
      );
      return await res.json();
    },
  },
  profile: (profile) => profile,
},
```

**Comment by iMuromec** [comment]
> > The problem is still relevant
> 
> You can create custom provider and at works for me
> 
> ```ts
> {
>   id: "mailru",
>   name: "Mail.ru",
>   type: "oauth",
>   clientId: process.env.MAILRU_CLIENT_ID,
>   clientSecret: process.env.MAILRU_SECRET,
>   authorization: "https://oauth.mail.ru/login",
>   token: "https://oauth.mail.ru/token",
>   userinfo: {
>     async request(context) {
>       const res = await fetch(
>         `https://oauth.mail.ru/userinfo?access_token=${context.tokens.access_token}`
>       );
>       return await res.json();
>     },
>   },
>   profile: (profile) => profile,
> },
> ```

Thanks, it's worked for me

**Comment by zjanybek** [comment]
> Hello there! I modified mail.ru provider as described here and I'm still having
> 
> ```
> [next-auth][debug][PROFILE_DATA] {
>   OAuthProfile: {
>     error: 'invalid request',
>     error_code: 2,
>     error_description: 'missing request parameter: access_token'
>   }
> }
> ```
> 
> Any help? Thank you in advance!
> 
> > > The problem is still relevant
> > 
> > 
> > You can create custom provider and at works for me
> > ```ts
> > {
> >   id: "mailru",
> >   name: "Mail.ru",
> >   type: "oauth",
> >   clientId: process.env.MAILRU_CLIENT_ID,
> >   clientSecret: process.env.MAILRU_SECRET,
> >   authorization: "https://oauth.mail.ru/login",
> >   token: "https://oauth.mail.ru/token",
> >   userinfo: {
> >     async request(context) {
> >       const res = await fetch(
> >         `https://oauth.mail.ru/userinfo?access_token=${context.tokens.access_token}`
> >       );
> >       return await res.json();
> >     },
> >   },
> >   profile: (profile) => profile,
> > },
> > ```

Were you able to solve it?

**Comment by targetss** [comment]
I haven't looked through the code much. It seems that the problem is only with getting user information. In the file @auth/core/lib/actions/callback/oauth/callback.js on line 103, we get nothing from the o.userInfoRequest function, although all data is transferred there correctly. Please check whether all requests comply with the authorization specification for mail.ru
