### ISSUE TITLE
issue with email provider / typeorm legacy adapter + jwt

### ISSUE THREAD

**Issue by andrew310** [nextauthjs/next-auth#5661]
### Question 💬

Not sure if this is intended behavior, but when using the email strategy, at least with the typeorm adapter,  you don't get the email returned inside the token, which can be problematic if you like to do stuff with permissions etc inside your sessions.

I have figured out the disconnect...

1) user is being assigned as the response from `updateUser` here:  https://github.com/nextauthjs/next-auth/blob/733fd5f2345cbf7c123ba8175ea23506bcb5c453/packages/next-auth/src/core/lib/callback-handler.ts#L102

The function is only getting `id` and `emailVerified` as object params.

2) As you can see here, the typeorm `save` function returns the same object you give it:
(https://github.com/typeorm/typeorm/blob/cdabaa30287d357c0ae994209e573f97f92dad22/src/entity-manager/EntityManager.ts#L438)

The result is that inside your default jwt callback, the user email doesn't end up getting stuck inside the token. It is a pretty easy workaround to define a custom jwt callback:

```
    jwt: async ({ token, account }) => {
      if (token?.email == null) {
        token.email = account?.providerAccountId
      }
      return token
    },
```
just wasn't sure if this was intended for some reason? Been using next-auth for over a year with only Google oauth, and when I added the email option we ran into issues in where the user email wasn't found when using getSession etc. Happy to use the workaround since it is simple, but wouldn't want others to run into unexpected problems like I did...

### How to reproduce ☕️

use basic email + typeorm setup...

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by ThangHuuVu** [comment]
I see, this seems to be specific to TypeORM. For now, I suggest you stick with the current workaround until we find more requests to change this 👍

**Comment by benpetsch** [comment]
+1 on this. The custom entities are should be reflected in the returned user attributes
