### ISSUE TITLE
FIDO Passkeys (WebAuthn)

### ISSUE THREAD

**Issue by DestroyerXyz** [nextauthjs/next-auth#5663]
### Description 📓

FIDO recently announced the new [Passkeys](https://fidoalliance.org/passkeys/) authentication standard which would soon be supported cross-platform by Apple, Microsoft, and Google as a more secure replacement for username/password auth.
Dev Docs: https://passkeys.dev

Will there be support for this in NextAuth or is it possible using the Credentials auth option? If the latter, can a guide be added to the docs on how to implement it?

### How to reproduce ☕️

NA

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by ThangHuuVu** [comment]
Indeed, we plan to have Webauthn support in the near future 🙌
cc @ndom91

**Comment by DestroyerXyz** [comment]
Is the work underway or planned?

**Comment by ndom91** [comment]
> Is the work underway or planned?

Just planned as of now 👍

**Comment by DestroyerXyz** [comment]
Gr8, really looking forward to it 😊 👍

**Comment by KevinPy** [comment]
It seems like started #6065

**Comment by ndom91** [comment]
> It seems like started #6065

Yeah I've started experimenting in the above referenced PR. Feel free to comment / chip in there 😊

**Comment by renchris** [comment]
Does the launch of Google Sign-In allowing for passkeys for public users affect the development of this? Using basic services such as YouTube now prompts for passkeys by default but when I checked the Next Auth example with Google Sign-In it only prompts password still.

**Comment by renchris** [comment]
Oh, I tried it again logging out of my Google Account and re-login in and it prompts the passkey
