### ISSUE TITLE
Testing Next-Auth with Next 13

### ISSUE THREAD

**Issue by benbagley** [nextauthjs/next-auth#5664]
### Question 💬

Hi all,

I'm giving Next 13 a shot and have it working, however, when running my test it seems that the session isn't being wrapped.

Here's what I have.

`AuthContext`
```ts
'use client';

import { SessionProvider } from 'next-auth/react';

export interface AuthContextProps {
  children: React.ReactNode;
}

export default function AuthContext({ children }: AuthContextProps) {
  return <SessionProvider>{children}</SessionProvider>;
}
```

`page.tsx`
```ts
'use client';

import Counter from '@/components/UserTest';
import { signIn } from 'next-auth/react';
import Image from 'next/image';
import styles from './page.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <main className={styles.main}>
        <a
          href={`/api/auth/signin`}
          onClick={(e) => {
            e.preventDefault();
            signIn();
          }}
        >
          Sign in
        </a>

        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js 13!</a>
        </h1>

        <Counter />

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>app/page.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://beta.nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js 13</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Explore the Next.js 13 playground.</p>
          </a>

          <a
            href="https://vercel.com/templates/next.js/app-directory?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>Deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
```

`userTest`
```ts
'use client';

import { useSession } from 'next-auth/react';

export default function UserTest() {
  const { data } = useSession();

  return (
    <>
      {console.log(data?.user)}
      <h1>Hi {data?.user?.name}</h1>
    </>
  );
}
```

`pages/api/[...nextauth].js`
```js
import NextAuth from 'next-auth';
import CredentialsProvider from 'next-auth/providers/credentials';

export const authOptions = {
  providers: [
    CredentialsProvider({
      name: 'Sign in',
      // generate a suitable form on the sign in page.
      credentials: {
        username: {
          label: 'Email',
          type: 'email',
          placeholder: 'hello@example.com'
        },
        password: { label: 'Password', type: 'password' }
      },
      async authorize(credentials, req) {
        // const res = await fetch('/your/endpoint', {
        //   method: 'POST',
        //   body: JSON.stringify(credentials),
        //   headers: { 'Content-Type': 'application/json' }
        // });

        // const user = await res.json();

        // If no error and we have user data, return it
        // if (res.ok && user) {
        //   return user;
        // }

        // return test user
        return { id: 1, name: 'J Smith', email: 'jsmith@example.com' };

        // Return null if user data could not be retrieved
        // return null;
      }
    })
  ],
  theme: {
    colorScheme: 'dark'
  }
};

export default NextAuth(authOptions);
```

When running my tests  I get the following:
```
yarn run v1.22.19
$ jest --runInBand --silent --coverage
warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

 FAIL  app/page.spec.tsx
  ● Index.js › that the title Welcome to Next.js! exists on the page

    [next-auth]: `useSession` must be wrapped in a <SessionProvider />

      4 |
      5 | export default function UserTest() {
    > 6 |   const { data } = useSession();
        |                              ^
      7 |
      8 |   return (
      9 |     <>

      at useSession (node_modules/next-auth/react/index.js:115:11)
```

Here is the test
```
import React from 'react';
import { fireEvent, render, screen } from '@testing-library/react';
import Home from '@/app/page';
import '@testing-library/jest-dom';

describe('Index.js', () => {
  test('that the title Welcome to Next.js! exists on the page', () => {
    render(<Home />);

    const title = screen.getByRole('heading', {
      name: /welcome to next\.js 13!/i,
      level: 1
    });

    expect(title).toBeInTheDocument();
  });
```

### How to reproduce ☕️

NA

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by Gerald12344** [comment]
Hi so in my app root layout file I have found a solution:
```ts
'use client';
import { SessionProvider } from 'next-auth/react';

function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html>
            <head></head>
            <body>
                <SessionProvider refetchOnWindowFocus={false}>
                        <>{children}</>
                </SessionProvider>
            </body>
        </html>
    );
}

export default RootLayout;
```

You have have "use client" cause it use React.createContext and by default Next13 components are server side, I want to be able to SSR the session though

**Comment by ThangHuuVu** [comment]
Closing in favor of #5647 please continue the discussion there to avoid noise 🙏

**Comment by leodebarros** [comment]
Facing the same issue here but I think I might have found a workaround. Although I struggled a bit because it appears there is no documentation for NextJS 13 + next-auth yet.

This is how my **layout.jsx** looks
`'use client'

import './globals.css'
import { SessionProvider } from 'next-auth/react'
import App from './components/App'

export default function RootLayout({ children }) {

  return (
    <SessionProvider>
          <App children={children}/>          
    </SessionProvider>
  )
}`

And this is what I did differently: created a component that I called **App.jsx** and wrap it with **SessionProvider** tags in the main layout file.
`'use client'

import styles from './components.module.css'
import { useSession } from 'next-auth/react'
import Login from './Login'
import Navigation from '../components/Navigation'


export default function App({ children }) {
    const { data: session } = useSession()

  return (
            <>          
            {session ? 
                <html lang="en">
                    <body>
                        <sidebar>
                            <Navigation/>
                        </sidebar>
                        <main>
                            <h1>Ryanair</h1>
                            {children}
                        </main>
                    </body>
                </html> 
                : 
                <html lang="en">
                    <body className={styles.body}>
                        <Login/>
                    </body>
                </html>     
            }
            </>
  )
}`

And this is how my **Login.jsx** component looks like in case you are wondering
`'use client'

import { signIn } from "next-auth/react"
import styles from "./components.module.css"

export default function Component() {

  return (
    <>
      Not signed in <br />
      <button className={styles.mainBtn} onClick={() => signIn()}>Sign in</button>
    </>
  )
}`

I'm still experiencing a small delay upon sign in. I'm being taken to the previous screen (the one with the Sign in button) just for a couple of seconds before being allowed in the actual app. If someone knows how to avoid this flaw please shout.

**Comment by paulwongx** [comment]
Don't wrap. Just have a file called `session.ts` with the following
```js
import { unstable_getServerSession } from "next-auth/next"

import { authOptions } from "@/pages/api/auth/[...nextauth]"

// Getting the session in Next13 app/ directory
// https://next-auth.js.org/configuration/nextjs#in-app-directory
export async function getSession() {
  return await unstable_getServerSession(authOptions)
}

export async function getCurrentUser() {
  const session = await getSession()
  return session?.user
}
```

Call it like this:
```js
const user = await getCurrentUser()
```
Source: shadcn and nextauth reference above

**Comment by danilocecilia** [comment]
hey @leodebarros were you able to figure it out a solution to your issue? I'm having the same problem and I've followed your solution and it worked for me, however, I'm having the same delaying issue as you mentioned.

**Comment by leodebarros** [comment]
@danilocecilia I ended up using the following repo as a starter and it literally solved all my problems. It is the best decision I could make for building with NextJS 13
[](https://github.com/shadcn/taxonomy)

**Comment by danilocecilia** [comment]
@leodebarros Oh ok, I'm glad it solved your problems, I will take a look on this repo, thank you for the reply!
