### ISSUE TITLE
Mastodon as provider

### ISSUE THREAD

**Issue by Jak2k** [nextauthjs/next-auth#5669]
### Description 📓

Because Elon Musk now owns Twitter, lot's of people switched to mastodon. Adding mastodon as auth-provider would be great.

[Mastodo docs for oauth](https://docs.joinmastodon.org/client/token/) 

Mastodon is a federated service, so the app has to be registered at login-time.

### How to reproduce ☕️

-

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by KyleTryon** [comment]
I am also hoping for this! This should enable support for not just mastodon but quite a few clones and forks which are compatible too.

**Comment by Jak2k** [comment]
Please don't close the issue.

**Comment by Jak2k** [comment]
What's the current progress?

**Comment by klerpi** [comment]
I would love this. Please keep it alive.

**Comment by jibla** [comment]
I have published an article about Auth.js, showing how it can be used outside its supported frameworks, purely with Node & Express. I show this with Mastodon OAuth example. If anyone is interested you can check it here: https://medium.com/@jibla/auth-js-exploration-1b6c27cf076f

**Comment by rod2ik** [comment]
I would love this too , please keep it alive

**Comment by Jak2k** [comment]
It's still relevant.

**Comment by airone01** [comment]
It's still relevant

**Comment by rod2ik** [comment]
It's still relevant, thanks to keep considering
