### ISSUE TITLE
signin error codes can be used to retrieve random object attributes

### ISSUE THREAD

**Issue by oren-z0** [nextauthjs/next-auth#5670]
### Environment

  System:
    OS: macOS 12.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 38.36 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.10.0 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.npm-packages/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Safari: 16.0
  npmPackages:
    next: ^12.3.1 => 12.3.1 
    next-auth: ^4.14.0 => 4.14.0 
    react: 17.0.2 => 17.0.2 

### Reproduction URL

https://next-auth-example.vercel.app/api/auth/signin?error=toString

### Describe the issue

The error string to display uses the `errors` object as a map, meaning any attribute can be fetched.

https://github.com/nextauthjs/next-auth/blob/733fd5f2345cbf7c123ba8175ea23506bcb5c453/packages/next-auth/src/core/pages/signin.tsx#L74

### How to reproduce

Enter https://next-auth-example.vercel.app/api/auth/signin?error=toString and see the error message for yourself.

### Expected behavior

Show the default error message when the error code not found.

**Comment by balazsorban44** [comment]
This seems to already be handled in `@auth/core` and its derivatives:

https://sveltekit-auth-example.vercel.app/auth/signin?error=toString

Since this does not seem to be a critical issue, NextAuth.js won't be updated.
