### ISSUE TITLE
Anonymous sessions

### ISSUE THREAD

**Issue by Delimer** [nextauthjs/next-auth#568]
How can anonymous sessions be used? It is necessary that before the user is authorized, it is possible to collect the data associated with him. For example, the items in the cart. Without sessions, I will not be able to add products on the server side, first I will need to store them on the client side and send them to the server side only after authorization.

**Comment by iaincollins** [comment]
For items in a shopping cart a good approach is probably to use `localStorage` to store a JSON object with the content of their shopping cart as it will still be there after they sign in (and will be extremely fast for the user).

Once they sign in, you could take this further and assign an ID to the JSON object and take advantage of `localStorage` events to sync the cart with server side storage so that users can access the same cart on another computer / device they are signed into.

**Comment by dackers86** [comment]
This would be an extremely useful feature.

Not everyone will want to create multiple solutions depending on authentication. 

Firebase is one fo the few providers that shows a great example of this https://firebase.google.com/docs/auth/web/anonymous-auth.

The only drawback would be a cleanup of data for the Users table, should a session expire?

**Comment by luisrudge** [comment]
for ecommerce, it's super important to have anonymous sessions. I'm working on a Commerce Tools ecommerce in Next.js and we need the ability to create a session for guest checkouts and things like this. I'd be happy to contribute a Commerce Tools provider with this support if anyone points me in the right direction.

**Comment by MRezaSafari** [comment]
isn't this possible in a new version with firebase adapter?

**Comment by jasperzeinstra** [comment]
> for ecommerce, it's super important to have anonymous sessions. I'm working on a Commerce Tools ecommerce in Next.js and we need the ability to create a session for guest checkouts and things like this. I'd be happy to contribute a Commerce Tools provider with this support if anyone points me in the right direction.

@luisrudge did you find any solution for the commercetools guest checkout and having a token? Did you resolve it with NextAuth or did you move to something else?

**Comment by luisrudge** [comment]
@jasperzeinstra sorry, it's been a while 😬  I moved on to another company, but we did get it working with CT and Next Auth. If I remember correctly, we had two credential providers - one for anonymous sessions and the other for authenticated users. It worked reasonably well. Just remember to convert the anonymous sessions into actual sessions when the user authenticates, so the cart/order that was created is 'attached' to the user.

**Comment by MRezaSafari** [comment]
> @jasperzeinstra sorry, it's been a while 😬 I moved on to another company, but we did get it working with CT and Next Auth. If I remember correctly, we had two credential providers - one for anonymous sessions and the other for authenticated users. It worked reasonably well. Just remember to convert the anonymous sessions into actual sessions when the user authenticates, so the cart/order that was created is 'attached' to the user.

do you have any example repo by any chance ?

**Comment by luisrudge** [comment]
@MRezaSafari sorry, I don't :( 
But the important bits were something like this:

```js
[
  CredentialsProvider({
    name: "anon",
    credentials: {},
    async authorize(credentials, req) {
      //no need to check anything here, just create a new CT anonymous session and return the token
      const authResult = await createAnonymousSession();
      /**
       * https://docs.commercetools.com/tutorials/anonymous-session#creating-a-token-with-a-new-anonymous-session
       * {
           "access_token": "vkFuQ6oTwj8_Ye4eiRSsqMeqLYNeQRJi",
           "token_type": "Bearer",
           "expires_in": 172800,
           "refresh_token": "{projectKey}:OWStLG0eaeVs7Yx3-mHcn8iAZohBohCiJSDdK1UCJ9U",
           "scope": "view_products:{projectKey} manage_my_orders:{projectKey} manage_my_profile:{projectKey}"
         }
       */
      return { token: authResult.accessToken };
    },
  }),
  CredentialsProvider({
    name: "auth",
    credentials: {
      username: { label: "Username", type: "text" },
      password: { label: "Password", type: "password" },
    },
    async authorize(credentials, req) {
      //check for username password
      const authResult = await authenticateUserInCommerceTools(
        credentials.username,
        credentials.password
      );
      /**
         * https://docs.commercetools.com/api/authorization#password-flow
         * {
             "access_token": "v-dZ10ZCpvbGfwcFniXqfkAj0vq1yZVI",
             "expires_in": 172800,
             "scope": "view_published_products:{projectKey} manage_my_orders:{projectKey} manage_my_profile:{projectKey} customer:{id}",
             "refresh_token": "{projectKey}:OWStLG0eaeVs7Yx3-mHcn8iAZohBohCiJSDdK1UCJ9U",
             "token_type": "Bearer"
           }
         */

      //https://docs.commercetools.com/api/projects/me-profile
      const customerInfo = await getCustomerInformation(
        authResult.access_token
      );
      return { token: authResult.accessToken, ...customerInfo };
    },
  }),
];
```

**Comment by Nhollas** [comment]
> isn't this possible in a new version with firebase adapter?

How would it be possible? Have you got a repo bro? :)

**Comment by showduhtung** [comment]
> @MRezaSafari sorry, I don't :( But the important bits were something like this:
> 
> ```js
> [
>   CredentialsProvider({
>     name: "anon",
>     credentials: {},
>     async authorize(credentials, req) {
>       //no need to check anything here, just create a new CT anonymous session and return the token
>       const authResult = await createAnonymousSession();
>       /**
>        * https://docs.commercetools.com/tutorials/anonymous-session#creating-a-token-with-a-new-anonymous-session
>        * {
>            "access_token": "vkFuQ6oTwj8_Ye4eiRSsqMeqLYNeQRJi",
>            "token_type": "Bearer",
>            "expires_in": 172800,
>            "refresh_token": "{projectKey}:OWStLG0eaeVs7Yx3-mHcn8iAZohBohCiJSDdK1UCJ9U",
>            "scope": "view_products:{projectKey} manage_my_orders:{projectKey} manage_my_profile:{projectKey}"
>          }
>        */
>       return { token: authResult.accessToken };
>     },
>   }),
>   CredentialsProvider({
>     name: "auth",
>     credentials: {
>       username: { label: "Username", type: "text" },
>       password: { label: "Password", type: "password" },
>     },
>     async authorize(credentials, req) {
>       //check for username password
>       const authResult = await authenticateUserInCommerceTools(
>         credentials.username,
>         credentials.password
>       );
>       /**
>          * https://docs.commercetools.com/api/authorization#password-flow
>          * {
>              "access_token": "v-dZ10ZCpvbGfwcFniXqfkAj0vq1yZVI",
>              "expires_in": 172800,
>              "scope": "view_published_products:{projectKey} manage_my_orders:{projectKey} manage_my_profile:{projectKey} customer:{id}",
>              "refresh_token": "{projectKey}:OWStLG0eaeVs7Yx3-mHcn8iAZohBohCiJSDdK1UCJ9U",
>              "token_type": "Bearer"
>            }
>          */
> 
>       //https://docs.commercetools.com/api/projects/me-profile
>       const customerInfo = await getCustomerInformation(
>         authResult.access_token
>       );
>       return { token: authResult.accessToken, ...customerInfo };
>     },
>   }),
> ];
> ```

say a guest leaves the page (possibly accidentally) and wants to reopen the page. How would you revalidate a previous guest?

**Comment by luisrudge** [comment]
@showduhtung you save the token result in the user session (via cookie or something else) so that browser will always reference the same guest.

**Comment by cleverlight** [comment]
@luisrudge I've had a go at reconstituting a full example based on the helpful snippets you provided.

https://github.com/lightenna/nextjs-app-auth-anon-logins-example

I followed the two-provider model you eluded to:

```javascript
export const authOptions: AuthOptions = {
    providers: [
        CredentialsProvider({
            name: "anonymous",
            credentials: {},
            async authorize(credentials, req) {
                return createAnonymousUser();
            },
        }),
        GithubProvider({
            clientId: process.env.GITHUB_CLIENT_ID as string,
            clientSecret: process.env.GITHUB_CLIENT_SECRET as string,
        }),
    ],
    callbacks: {
        async jwt({token, account, profile}: {token: JWT, account: Account | null, profile?: Profile}): Promise<JWT> {
            if (account && account?.expires_at && account?.type === 'oauth') {
                // at sign-in, persist in the JWT the GitHub account details to enable brokered requests in the future
                token.access_token = account.access_token;
                token.expires_at = account.expires_at;
                token.refresh_token = account.refresh_token;
                token.refresh_token_expires_in = account.refresh_token_expires_in;
                token.provider = 'github';
            }
            if (!token.provider) token.provider = 'anonymous';
            return token;
        },
        async session({session, token, user}: {session: Session, token: JWT, user: AdapterUser}): Promise<Session> {
            // don't make the token (JWT) contents available to the client session (JWT), but flag that they're server-side
            if (token.provider) {
                session.token_provider = token.provider;
            }
            return session;
        },
    },
    events: {
        async signIn({user, account, profile}: {user: User, account: Account | null, profile?: Profile}): Promise<void> {
            debug(`signIn of ${user.name} from ${user?.provider || account?.provider}`);
        },
        async signOut({session, token}: {session: Session, token: JWT}): Promise<void> {
            debug(`signOut of ${token.name} from ${token.provider}`);
        },
    },
    session: {
        // use default, an encrypted JWT (JWE) store in the session cookie
        strategy: "jwt" as SessionStrategy,
    },
}
const handler = NextAuth(authOptions);

export {handler as GET, handler as POST}

```

Also, I've written up a short explanation of the crucial parts in a [blog post](https://www.lightenna.com/tech/2023/use-nextauth-with-nextjs-app-router-for-anonymous-logins/).
