### ISSUE TITLE
Middleware acts on entire app even if config is set

### ISSUE THREAD

**Issue by radudalbea** [nextauthjs/next-auth#5686]
### Environment

basic setup. it's the current install for the website. nothing is custom except a login page

### Reproduction URL

not the case

### Describe the issue

The auth middleware acts on the entire app even if the config is exported just for a single folder.

This is the most basic example of how this middleware can be used on an app that can be used with both public and protected routes.

If I try to go to homepage which is "/" I am being redirect to the login page.

This is the most complicated and full of problems package that I have seen related to auth. Nothing is working out of the book even though all my flows are the most common ones: authenticate and secure a path. Not event the documentation is written the normal way. 

For example you get this as the basic usage:

export { default } from "next-auth/middleware"
export const config = { matcher: ["/dashboard"] }

The next chapter are the options like callbaks, pages, etc. Where are those supposed to be set? You need to scroll to the bottom of the page to see an advanced usage to figure it out how you can use those options :)

### How to reproduce

// middleware.js

export default withAuth({
    pages: {
      signIn: '/admin/login'
    }
  }
);

export const config = {
  matcher: [
    '/admin/:path*',
    '/((?!assets).*)',
  ]
};

### Expected behavior

I should be allowed to view the pages outside "admin" path.

**Comment by radudalbea** [comment]
apparently this was the issue: '/((?!assets).*)'. I will close this issue but keep in mind my comments about the setup and docs please.

**Comment by ThangHuuVu** [comment]
Hey @radudalbea, we always welcome contributors to change the docs 🙌 Tag me if you open a PR!
