### ISSUE TITLE
Can not verify access token 

### ISSUE THREAD

**Issue by kidp2h** [nextauthjs/next-auth#5688]
### Environment

  System:
    OS: Linux 5.19 Arch Linux
    CPU: (12) x64 AMD Ryzen 5 5600H with Radeon Graphics
    Memory: 725.50 MB / 5.65 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Firefox: 105.0.3
  npmPackages:
    next: ^12.2.5 => 12.2.5
    next-auth: ^4.10.3 => 4.10.3
    react: 18.2.0 => 18.2.0

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

i can't verify ( decode ) access token in cookie

### How to reproduce

1. Clone https://github.com/nextauthjs/next-auth-example
2. Sign in and copy access token in cookie 
3. Access jwt.io then paste access token and secret

### Expected behavior

Can verify access token

**Comment by HaNdTriX** [comment]
Just to add some more context here.

If have debugged the issue und it seems, that `getToken` (`decode`) from  `next-auth/jwt` doesn't seems to work in the next 13 `experimental-edge` environment.

## Node.js Example (Works)

```ts
import type { NextApiRequest, NextApiResponse } from "next";
import { getToken } from "next-auth/jwt";

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const token = await getToken({ req, secret: process.env.NEXTAUTH_SECRET });
  res.status(200).json({ token });
}
```

This code returns the correct token.

## Edge Example (Doesn't work)

```ts
import type { NextRequest } from "next/server";
import { getToken } from "next-auth/jwt";

export const config = {
  runtime: "experimental-edge",
};

export default async function handler(req: NextRequest) {
  const token = await getToken({ req, secret: process.env.NEXTAUTH_SECRET });
  return new Response(
    JSON.stringify({
      token,
    }),
    {
      status: 200,
      headers: {
        "content-type": "application/json",
      },
    }
  );
}
```

This code always return `null`.

**Comment by ThangHuuVu** [comment]
@HaNdTriX Could you open a separate issue for to track it easier? 🙌

**Comment by ThangHuuVu** [comment]
@kidp2h I can't seem to reproduce your issue. If you login into https://next-auth-example.vercel.app/ and go to /api-example, you can see that the JWT is decoded correctly. 🤔
