### ISSUE TITLE
Works with "next export"?

### ISSUE THREAD

**Issue by all-the-rice** [nextauthjs/next-auth#570]
Excuse me if I'm missing something simple.  Is it possible to use next-auth when using `next export`?

Maybe I just need a dynamic routing stub in `next.congig.js`?

Not having any luck yet. Looking really good other than that. Thank you!

**Comment by all-the-rice** [comment]
Current behavior is it builds and exports fine but then 404 on /api/auth/signin even when I ```'/api/auth/signin': {
        page: '/api/auth/[...nextauth]',
      },``` to ```exportPathMap``` in ```next.config.js```

**Comment by shaunchander** [comment]
If I'm not mistaken, `next export` **only** works for when all pages on your website can be pre-rendered (generated to static HTML). Because Next Auth requires some level of server-side rendering for the signin pages, I _don't_ believe `next export` would work.

**Comment by ElanHasson** [comment]
Hi @balazsorban44,

 To clarify, next-auth isn't appropriate to use when using `next export`? I'm able to get my jwt token returned for my client-side only app by using `response_type = id_token token`, `access_type = 'online'`.

Should I change my redirect URI to point to my own page with client side logic?
