### ISSUE TITLE
Support Next.js Version 13.0.1

### ISSUE THREAD

**Issue by HaNdTriX** [nextauthjs/next-auth#5701]
### Description 📓

Next.js 13.0.1 introduces the following breaking change: https://github.com/vercel/next.js/pull/41526

**TLTR:** Before `request.cookies.get(<name>)` returned the cookie value. Now this invocation returns the following object: 

```js
{ name: <name>, value: <value>}
```

resulting in `jwt.getToken` to always return `null`

#### Node.js Example (Works)

```ts
import type { NextApiRequest, NextApiResponse } from "next";
import { getToken } from "next-auth/jwt";

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const token = await getToken({ req, secret: process.env.NEXTAUTH_SECRET });
  res.status(200).json({ token });
}
```

This code returns the correct token.

#### Edge Example (Doesn't work)

```ts
import type { NextRequest } from "next/server";
import { getToken } from "next-auth/jwt";

export const config = {
  runtime: "experimental-edge",
};

export default async function handler(req: NextRequest) {
  const token = await getToken({ req, secret: process.env.NEXTAUTH_SECRET });
  return new Response(
    JSON.stringify({
      token,
    }),
    {
      status: 200,
      headers: {
        "content-type": "application/json",
      },
    }
  );
}
```

This code always returns `token: null`.

### System Info

- *Used Next.js Version:*  `13.0.1`

### Related Code

https://github.com/nextauthjs/next-auth/blob/30ad639d163147841a096211e1db2c9f10c34cb7/packages/next-auth/src/core/lib/cookie.ts#L143-L151

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by goliney** [comment]
I've just encountered the same issue. I upgraded `next` to `13.0.1` and faced the issue in `middleware.ts`:
```typescript
import { getToken } from 'next-auth/jwt';

export default async function middleware(req) {
  const token = await getToken({ req });
  console.log(token); // always null
}
```

Downgraded to `next@13.0.0` and the issue is gone.

**Comment by sandervspl** [comment]
This patch will temporarily fix it https://gist.github.com/sandervspl/269e3900b7e4de6ff6f480e476942272

**Comment by jack-szeto** [comment]
> 



> I've just encountered the same issue. I upgraded `next` to `13.0.1` and faced the issue in `middleware.ts`:
> 
> ```ts
> import { getToken } from 'next-auth/jwt';
> 
> export default async function middleware(req) {
>   const token = await getToken({ req });
>   console.log(token); // always null
> }
> ```
> 
> Downgraded to `next@13.0.0` and the issue is gone.

@goliney you saved my day!
