### ISSUE TITLE
Add an email parameter to the verifyRequest page

### ISSUE THREAD

**Issue by dsaltares** [nextauthjs/next-auth#5703]
### Description 📓

At the moment, one cannot display the email the magic link was sent to (Email provider) in the `verifyRequest` page, like so.

![image](https://user-images.githubusercontent.com/570314/199285683-fdb5ea26-6a42-4027-a19a-68910053712a.png)

It would be great if the page got an `email` prop or query param.

### How to reproduce ☕️

NA

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
You can use the `redirect: false` option of `signIn` for this: https://next-auth.js.org/getting-started/client#using-the-redirect-false-option. This way, you can avoid the whole redirection on the page where you still have the e-mail address of the user.

**Comment by adopstarliu** [comment]
I tried to solve this when using a custom verify page too, and because there isn't a built in function, and the page refreshes since it is a redirect, so using state isn't an option either. I resorted to storing the user email in local storage and then read it from the custom verify page
