### ISSUE TITLE
Error when custom jwt method

### ISSUE THREAD

**Issue by kidp2h** [nextauthjs/next-auth#5704]
### Environment

  System:
    OS: Linux 5.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (12) x64 AMD Ryzen 5 5600H with Radeon Graphics
    Memory: 123.65 MB / 5.65 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  npmPackages:
    next: ^13.0.0 => 13.0.0
    next-auth: ^4.15.0 => 4.15.0
    react: 18.2.0 => 18.2.0

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

I follow [this tutorial](https://next-auth.js.org/configuration/nextjs#custom-jwt-decode-method) in official document next-auth, when i custom jwt method ( encode, decode )

> NextAuthOptions: pages/api/auth/[...nextauth].ts

  ```js
jwt: {
    maxAge: 60 * 60 * 24 * 14,
    async encode({ token: payload, secret }) {
      return jwt.sign(payload, secret);
    },
    async decode({ token, secret }) {
      return jwt.verify(token, secret) as any;
    },
  }
```

and pass decode method above to middleware 

> middleware.ts

and i got error
![image](https://user-images.githubusercontent.com/40386174/199291396-a415370f-4332-43e2-9ce1-6b4c999ae991.png)

### How to reproduce

1. Clone https://github.com/nextauthjs/next-auth-example
2. Replace jwt options with above options and pass jwt decode to middleware
3. Access localhost:3000 and login

### Expected behavior

Can get token in middleware when use custom jwt method

**Comment by kidp2h** [comment]
i read some similar issue, possibly due to missing env NEXTAUTH_SECRET, but i'm sure that i passed secret

**Comment by kevinsmouts** [comment]
After being stuck on this issue for a few hours, here's what I found (still stuck):
- the oidc lib uses `process.version`, this is where the reference to `substr` fails
- NextJS Middleware runs on their Edge Runtime, which DOES NOT include the V8 Primitive `process`
- NextJS clearly says that their Edge Runtime is 'not having access to native Node.js APIs'

So my understanding is that if we need custom encode/decode function, we need something that can run without the Node.js APIs unsupported by the Edge Runtime.

Now what I don't understand is why this issue seems to happen only now. Middleware has been out for quite some time, the problem should have been there at the time of writing the guide for NextJS.

**Comment by kevinsmouts** [comment]
Here's my code

The custom encoder decoder split out as a separate function
```
// in api/auth/[...nextauth].ts

export const decode = async (data: any) => {
  const { secret, token } = data;
  const decodedToken = jwt.verify(token, secret, {
    algorithms: ["HS256"],
  });
  return decodedToken as JWT;
};

export const encode = (data: any) => {
  const { secret, token } = data;
  const encodedToken = jwt.sign(token, secret, {
    algorithm: "HS256",
  });
  return encodedToken;
};
```

the middleware

```
// in middleware.ts

import { withAuth } from "next-auth/middleware"
import { decode } from "./pages/api/auth/[...nextauth]"

export const config = { matcher: ["/:path?"] }
export default withAuth({
  jwt: { decode: decode },
  callbacks: {
    authorized: ({ token }) => {
      console.log(token)
      return !!token
    },
  },
})
```

the error message as usual

![image](https://user-images.githubusercontent.com/1415547/199934560-78ee3c52-2e68-4e11-9583-6a79489bb588.png)

![image](https://user-images.githubusercontent.com/1415547/199934581-b1b94494-4166-42c0-9ea0-1cbef78e1943.png)

**Comment by stephane-segning** [comment]
Hello, @kevinsmouts. Did you did find something? I'm having the same issue?

**Comment by kevinsmouts** [comment]
I recommend not using middleware. This was never fixed.

**Comment by el-buku** [comment]
whaaat

**Comment by Husain010** [comment]
Is this still a problem in v4? I am trying to use middleware now but have a custom JWT and now I cannot read the token as it's always null!
