### ISSUE TITLE
Getting discord discriminator

### ISSUE THREAD

**Issue by sadboilogan** [nextauthjs/next-auth#571]
Is it possible to easily get things such as Discord discriminator?

I want to be able to get the 4 numbers at the end of your name, however it doesnt seem like next-auth exposes it as a value that can be used, is there any simple way of going about this? Thanks

**Comment by shaunchander** [comment]
It does expose this value as part of the `profile` parameter on the sign in callback.

**Comment by sadboilogan** [comment]
yeah, i found that out not long after, but its still annoying how that and even the discord id arent passed into `getSession` or so, even when the discordid is in the avatar image url

**Comment by dotangad** [comment]
Did you guys figure out how to get the discriminator?

**Comment by balazsorban44** [comment]
Please have a look at the jwt and session callbacks jn the documentation: https://next-auth.js.org/configuration/callbacks
