### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by paragopinath** [nextauthjs/next-auth#572]
I'm trying to add Social login buttons to a custom login page

I've imported the signIn function as follow 
```
import { getSession, signIn } from 'next-auth/client'
```

and then used the it on a custom button as follow
```
<button className="auto-signup auto-signup--fb" onClick={() => signIn('Facebook')}>
          {btnIcon('icon-btn__icon auto-signup__icon', '/icon-sprite.svg#icon-fb-sm')}
         <span className="auto-signup__label">Sign up with Facebook</span>
</button>
```

and when i click the button, i'm getting `TypeError: Object(...) is not a function` error. i'm using following versions of the packages
"react": "^16.13.0",
"react-dom": "^16.13.0",
"next": "^9.3.6",
"next-auth": "^2.2.0",

Can anyone let me know where the issue might be ? Thank you!

**Comment by iaincollins** [comment]
Hi there! I'm happy to have questions option, but please use the templates and don't use the bug flag for things that are not replicable bugs in NextAuth.js as it creates work for maintainers.

**Comment by bshawnd** [comment]
@paragopinath I was having the same issue this afternoon, I reviewied the `dist/client.js` file and saw that the correct case for the exports was `signin` and `signout`.  Once I change my imports and the function called onClick, it worked.  Hope this helps

**Comment by bcrave** [comment]
I actually did. I just changed the versions of node and next-auth that I
was using and it started to work. Thanks!

**Comment by adamduncan** [comment]
> I actually did. I just changed the versions of node and next-auth that I was using and it started to work. 

Good to hear, @bcrave. Which version of each worked for you in the end?

**Comment by vgeorge** [comment]
I got this error after adding `"type": "module"` to package.json, before that, it was working fine. I solved this by explicitly calling `NextAuth.default(...` as suggested. Versions: next-auth 4.16.4, Node.js 18.12.1. I hope it helps.

**Comment by sherrylia0hy** [comment]
> Edit: FWIW we found ourselves being able to resolve this by explicitly calling `NextAuth.default(...` and `GoogleProvider.default(...` — which makes us think this is a webpack v5/Next.js v12/React v17-18 versioning peculiarity. Any pointers on what that would be?

I had same problem with next 13.1.1, next-auth 4.18.7, react 18.2.0. This comment saved my day. Thank you.

**Comment by blockspector** [comment]
Edit: FWIW we found ourselves being able to resolve this by explicitly calling NextAuth.default(... and GoogleProvider.default(... — which makes us think this is a webpack v5/Next.js v12/React v17-18 versioning peculiarity. 


I also had the same issue I was following this guide "https://www.youtube.com/watch?v=A5ZN--P9vXM&list=PLNBstBbanNo-urO14JTnv7Jezq4XjOG_e&index=1&t=699s" 

I am using the following versions. 

    "next": "13.2.3",
    "next-auth": "^4.22.1"


I updated my file @ /pages/api/auth/[...nextauth].js
From 

`NextAuth({`
`GoogleProvider`

To 

`NextAuth.default({...`
`GoogleProvider.default({...`

This solved my issue thank you! 🥹

**Comment by epicmau5time** [comment]
Hi, @blockspector or @adamduncan. 

Could either of you provide a snippet of your solution? I have the same issue and am having a hard time replicating with typescript as ".default" does not seem to exist on providers.

next-auth: "next-auth": "^4.24.5"

**Comment by adamduncan** [comment]
@epicmau5time  Here's where we landed (using `next-auth@4.7.0` at the time) — bear in mind we were just using JS, so didn't encounter TS errors:

```js
import NextAuth from 'next-auth';
import GoogleProvider from 'next-auth/providers/google';

export default NextAuth.default({
  providers: [
    GoogleProvider.default({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    }),
  ],
});

```

**Comment by UmizDemud** [comment]
It's next-auth 5, still the same issue?

Server action that calls the signOut errors out:
"""
 @ signOut
 ⨯ TypeError: (0 , next_auth_react__WEBPACK_IMPORTED_MODULE_2__.signOut) is not a function
    at $$ACTION_0 (./actions/logout.ts:16:67)
"""

Is Clerk behind this :D I know this is fixable

**Comment by ekeneamah** [comment]
Thank you @adamduncan your solution just saved me
changed from 
`import AzureADProvider from "next-auth/providers/azure-ad";

export default NextAuth({
  debug: true,
  providers: [
    AzureADProvider({
      clientId: process.env.NEXT_PUBLIC_CLIENT_ID,`

to 

`import AzureADProvider from "next-auth/providers/azure-ad";

export default NextAuth.default({
  debug: true,
  
    providers: [  
      AzureADProvider.default({
      clientId: process.env.NEXT_PUBLIC_CLIENT_ID,`

as you said. Thank you so much
