### ISSUE TITLE
Passing state to OAuth provider does nothing

### ISSUE THREAD

**Issue by jasonkuhrt** [nextauthjs/next-auth#5726]
### Environment

 System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 260.97 MB / 32.00 GB
    Shell: 3.5.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.17.0 - ~/Library/pnpm/node
    npm: 8.15.0 - ~/Library/pnpm/npm
    Watchman: 2022.10.10.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 107.0.5304.87
    Safari: 16.0

### Reproduction URL

N/A

### Describe the issue

While working on this issue https://github.com/nextauthjs/next-auth/discussions/5717#discussioncomment-4051762 I discovered that passing a custom state does nothing. 

### How to reproduce

<img width="1021" alt="CleanShot 2022-11-04 at 08 18 47@2x" src="https://user-images.githubusercontent.com/284476/199971050-3f0effbc-4167-43fd-82a7-a0cda5f2511d.png">

You can see state is a valid field in the current API.

### Expected behavior

Either it should not be a valid field or it should do something.

**Comment by balazsorban44** [comment]
Closing in favor of #5727 since that would fix this issue too.
