### ISSUE TITLE
NextAuth should allow empty scope for Twitch provider

### ISSUE THREAD

**Issue by techygrrrl** [nextauthjs/next-auth#5738]
### Provider type

Twitch

### Environment

  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Safari: 15.6
  npmPackages:
    next: 12.2.5 => 12.2.5 
    next-auth: ^4.15.1 => 4.15.1 
    react: 18.2.0 => 18.2.0 

### Reproduction URL

https://command-showcaserrr.vercel.app/

### Describe the issue

The above link is functioning without the issue I'm about to describe because I am using the scopes `openid user:read:email`.

Twitch allows developers to specify no scope (as an empty string `''`) in order to support login with Twitch.

My application does not require me to collect the user's email. I would like to avoid asking for this permission. With Next-Auth's Twitch provider, I cannot. 

This is my provider configuration:

```ts
    TwitchProvider({
      authorization: {
        params: {
          scope: 'openid user:read:email'
        }
      },
      clientId: process.env.TWITCH_CLIENT_ID as string,
      clientSecret: process.env.TWITCH_CLIENT_SECRET as string,
    }),
```

Ideally I'd like to change to:

```diff
    TwitchProvider({
      authorization: {
        params: {
-          scope: 'openid user:read:email'
+          scope: ''
        }
      },
      clientId: process.env.TWITCH_CLIENT_ID as string,
      clientSecret: process.env.TWITCH_CLIENT_SECRET as string,
    }),
```

When I specify an empty string `''`, I get the following error:

```text
[next-auth][error][OAUTH_CALLBACK_ERROR]
https://next-auth.js.org/errors#oauth_callback_error id_token not present in TokenSet {
  error: TypeError: id_token not present in TokenSet
      at Client.validateIdToken (/path/to/project/node_modules/openid-client/lib/client.js:735:15)
      at Client.callback (/path/to/project/node_modules/openid-client/lib/client.js:486:18)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async oAuthCallback (/path/to/project/node_modules/next-auth/core/lib/oauth/callback.js:127:16)
      at async Object.callback (/path/to/project/node_modules/next-auth/core/routes/callback.js:52:11)
      at async NextAuthHandler (/path/to/project/node_modules/next-auth/core/index.js:201:28)
      at async NextAuthNextHandler (/path/to/project/node_modules/next-auth/next/index.js:23:19)
      at async Object.apiResolver (/path/to/project/node_modules/next/dist/server/api-utils/node.js:184:9)
      at async DevServer.runApi (/path/to/project/node_modules/next/dist/server/next-server.js:403:9) {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'twitch',
  message: 'id_token not present in TokenSet'
}
```

When I specify only the scope `'openid'` I get the following error for insufficient scope:

```text
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR]
https://next-auth.js.org/errors#oauth_callback_handler_error insufficient_scope {
  error: {
    message: 'insufficient_scope',
    stack: 'Error: insufficient_scope\n' +
      '    at oAuthCallback (/path/to/project/node_modules/next-auth/core/lib/oauth/callback.js:39:19)\n' +
      '    at Object.callback (/path/to/project/node_modules/next-auth/core/routes/callback.js:52:39)\n' +
      '    at NextAuthHandler (/path/to/project/node_modules/next-auth/core/index.js:201:41)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async NextAuthNextHandler (/path/to/project/node_modules/next-auth/next/index.js:23:19)\n' +
      '    at async Object.apiResolver (/path/to/project/node_modules/next/dist/server/api-utils/node.js:184:9)\n' +
      '    at async DevServer.runApi (/path/to/project/node_modules/next/dist/server/next-server.js:403:9)\n' +
      '    at async Object.fn (/path/to/project/node_modules/next/dist/server/base-server.js:493:37)\n' +
      '    at async Router.execute (/path/to/project/node_modules/next/dist/server/router.js:222:36)',
    name: 'Error'
  },
  error_description: 'The scope of the authorization is insufficient for the id token claims requested',
  providerId: 'twitch',
  message: 'insufficient_scope'
}
```

Twitch does not require the scopes you've required in order to implement OAuth—they allow me to specify an empty string so that I do not have to collect the user's email.

Below are screenshots of 2 separate applications:

1. An app built with Next Auth
2. An app built with another OAuth library on a different tech stack

With Next Auth, users are required to provide their email and other information resulting in a warning sign to the user.

![SCR-20221105-jvp](https://user-images.githubusercontent.com/88961088/200141784-93d42e41-6e22-4809-9efa-4de73e63972b.png)

A different OAuth implementation I made does not require any scopes and the user can use the app without providing any personal information.

![SCR-20221105-jub](https://user-images.githubusercontent.com/88961088/200141791-fcc29d9a-c1f5-459c-ae0c-5c97b8d4be0c.png)

### How to reproduce

This error can be reproduced by configuring a Twitch provider with an empty string as the scope param. Provided you have the environment variables specified below, you can use this snippet to easily reproduce.

```ts
    TwitchProvider({
      authorization: {
        params: {
          scope: ''
        }
      },
      clientId: process.env.TWITCH_CLIENT_ID as string,
      clientSecret: process.env.TWITCH_CLIENT_SECRET as string,
    }),
```

### Expected behavior

I would expect to be able to provide an empty scope string without Next Auth throwing an error since this is a valid configuration for working with Twitch's OAuth API.

In another application, I am not requesting scopes `openid` nor `user:email:read`. I expect the same behaviour from Next Auth.

That other library is in another language and stack, but if you are curious, you can check it out [here](https://docs.rs/oauth2/latest/oauth2/).

**Comment by balazsorban44** [comment]
You need to set `authorization: { params: { scope: "openid", claims: { id_token: {} } } }`.

For more context, by default, we do ask for the email claim as shown here: https://github.com/nextauthjs/next-auth/blob/27a0b70d8710b11b5ba2d0c937527cf6981ca815/packages/next-auth/src/providers/twitch.ts#L22-L26

On the other hand, `openid` is a required scope by the OIDC spec: https://openid.net/specs/openid-connect-core-1_0.html#AuthorizationEndpoint so if Twitch does not require it, it is actually a bug in their implementation and should be reported there.

**Comment by balazsorban44** [comment]
**Update**: [Their docs](https://dev.twitch.tv/docs/authentication/getting-tokens-oidc#oidc-authorization-code-grant-flow:~:text=to%20code.-,scope,-Yes) docs actually say you *MUST* include `openid` so their implementation seems to be fine.

**Comment by techygrrrl** [comment]
With regards to your suggestion @balazsorban44: 

> Thanks for reporting. You need to set `authorization: { params: { scope: "openid", claims: { id_token: {} } } }`.

Implementing your suggestion still results in the following error—did you test it before suggesting it? Because it does not work:

```text
[next-auth][error][OAUTH_CALLBACK_ERROR]
https://next-auth.js.org/errors#oauth_callback_error insufficient_scope
```

It doesn't appear to be possible to do as you suggest. Is there another implementation suggestion I can use that works so I don't need to request email?

You can implement OAuth with Twitch without specifying the `openid` scope. Here are their docs for that: https://dev.twitch.tv/docs/authentication/getting-tokens-oauth and  here's an example URL that is valid and works with my other application:

```
https://id.twitch.tv/oauth2/authorize?response_type=code&client_id=XXX&state=XXXX&code_challenge=XXXXX&code_challenge_method=S256&redirect_uri=http%3A%2F%2Flocalhost%3A7000%2Ftwitch%2Fauth%2Fcallback
```

The `openid` scope with Twitch is optional—the OIDC flow is an option but it isn't the only option available through Twitch. 

Is there another implementation suggestion I can use that works so I don't need to request email? I do not wish to use OpenID with Twitch OAuth.

Thanks

**Comment by balazsorban44** [comment]
I did test it locally, yes. We implement OIDC for Twitch by default, but it's totally fine to use plain OAuth too. 
Check out the docs or the above-linked default provider for details.

**Comment by Karpfador** [comment]
The provided example did not work and caused the exact behavior techygrrrl described: `insufficient_scrope`

Could you provide clearer instructions on where to look in said docs or what there is to be found in the default provider?

I experimented with a few options but they always lead me to the email scope error  or `id_token not present in TokenSet`

**Comment by maxeth** [comment]
> The provided example did not work and caused the exact behavior techygrrrl described: `insufficient_scope`
> 
> Could you provide clearer instructions on where to look in said docs or what there is to be found in the default provider?
> 
> I experimented with a few options but they always lead me to the email scope error or `id_token not present in TokenSet`

Same problem. Did you find a solution?

**Comment by she11sh0cked** [comment]
> > The provided example did not work and caused the exact behavior techygrrrl described: `insufficient_scope`
> > Could you provide clearer instructions on where to look in said docs or what there is to be found in the default provider?
> > I experimented with a few options but they always lead me to the email scope error or `id_token not present in TokenSet`
> 
> Same problem. Did you find a solution?

The problem lies in the need to also override `authorization.params.claims.id_token`, which doesn't seem to be achievable through the `options: OAuthUserConfig` parameter for some reason.
I managed to make it work by overriding the return value of  `Twitch([...])` instead:
```ts
{
  ...Twitch({
    clientId: TWITCH_ID,
    clientSecret: TWITCH_SECRET
  }),
  authorization: {
    params: {
      scope: 'openid',
      claims: {
        id_token: { picture: null, preferred_username: null }
      }
    }
  }
}
```
This solution, of course, isn't flawless, but *it does work*.
