### ISSUE TITLE
How to use NextAuth.js with Strapi?

### ISSUE THREAD

**Issue by alfieqashwa** [nextauthjs/next-auth#574]
*Please refer to the [documentation](https://next-auth.js.org/getting-started/introduction), the [example project](https://github.com/iaincollins/next-auth-example) and existing issues before creating a new issue.*

**Configure using Strapi ??**
If can, is there any example ?

**What are you trying to do**
A description of what you are trying to do.

**Comment by iaincollins** [comment]
Hi there! This has come up before in #474 #276 and #411.

tl;dr This is a good question to ask the Strapi folks about.

It's commercial software and they have a larger team so are better placed to be a starting point to ask about this.

From what I understand, Strapi has it's own authentication system but it seems NextAuth.js might be a really good fit for it the built-in authentication system isn't as full featured (as it's not a primary selling point). I think it should be able to integrate them and we just need an example and/or tutorial we can point folks to.

I'm really happy to collaborate with folks from Strapi if they want to get in touch.

**Comment by alfieqashwa** [comment]
I hope their response [#7477](https://github.com/strapi/strapi/issues/7477)
