### ISSUE TITLE
Invalid JWT session cookie

### ISSUE THREAD

**Issue by alexalannunes** [nextauthjs/next-auth#5744]
### Environment

System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 9.81 GB / 15.50 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 106.0.2
  npmPackages:
    next: 13.0.2 => 13.0.2 
    next-auth: ^4.15.1 => 4.15.1 
    react: 18.2.0 => 18.2.0 

![image](https://user-images.githubusercontent.com/16847836/200180939-775a219f-4b66-4ab2-923a-3741b608a3dc.png)

### Reproduction URL

https://user-images.githubusercontent.com/16847836/200180939-775a219f-4b66-4ab2-923a-3741b608a3dc.png

### Describe the issue

next-auth.session-token provides an invalid jwt value with two dots separator

eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..qHgYt9VlX-SzT9Gq.ZiLfbNgxFOlKDfLJ13uEsP5xe0ifgHqGWuLqVaL8mST8vpDH8OQVz7wjWiplkFADFwWL7ManNoQ4BpGJmjUtyNLqtuRzbrC5Gf7PRyB1SP4Ui6xB58EMSyGRKRxXyTKu1JRHKKsAc8qzIVekxP_J8CaSsIeEAQNgecb1thhgEekChYgXglTYirTK9A48pTP-Myf87pSZzVf7CBqElYjGDMSE7Rnx_0GPYtw3rQIQzf579AbmYAgJvSTGmj0CmXg1dk-tdh_4xgUnlcsuTRFJz-B0ENBnK1kYA0wRLnxRV-_ZH10xoVe1LrW9vtNRafKT-ISULUUR8vdWJT01a6A3qCJ0Kc2ifPBo_NEniXuM_w.5M0N1EEKhmbBwdh3QT1znA

### How to reproduce

with any provider.

### Expected behavior

jwt should be only one dot separator

**Comment by balazsorban44** [comment]
It is not invalid. The JWT is encrypted (JWE). You can see the exact encryption method here:

https://github.com/nextauthjs/next-auth/blob/52a2bf3e28aad08937b58346a6ee6824e6e0d888/packages/next-auth/src/jwt/index.ts#L17-L26

**Comment by alexalannunes** [comment]
@balazsorban44 so I shouldn't worry about this point anymore?
