### ISSUE TITLE
Connection GRPC stream error. Code: 7 Message: 7 PERMISSION_DENIED: Permission denied

### ISSUE THREAD

**Issue by scshiv29-dev** [nextauthjs/next-auth#5749]
### Adapter type

@next-auth/firebase-adapter

### Environment

deployed on vercel

### Reproduction URL

na

### Describe the issue

The app works perfectly on gitpod and on localhost but on vercel it gives this error when i sign in .

### How to reproduce

have firestore adapter and deploy on vercel

### Expected behavior

user saved in firestore or if exists then sign in the user.

**Comment by vedantmgoyal2009** [comment]
Can you please mention more specific steps to reproduce the issue? For example, a part of your code that you're using?

**Comment by vedantmgoyal2009** [comment]
ah well, please try using the latest version of the adapter which is released today.

**Comment by scshiv29-dev** [comment]
@vedantmgoyal2009  yeah the new version works perfectly thanks.
