### ISSUE TITLE
Can't use google signin  in localhost

### ISSUE THREAD

**Issue by thanhtutzaw** [nextauthjs/next-auth#5751]
### Question 💬

![Screenshot (78)](https://user-images.githubusercontent.com/71011043/200315116-ba4b9e5b-a330-4014-8277-8748c7cc410d.png)

![Screenshot (79)](https://user-images.githubusercontent.com/71011043/200315374-f532de1c-a752-4a11-98bb-7d561aff1c19.png)

**in api/auth callback**
![in auth callback](https://user-images.githubusercontent.com/71011043/200316018-4a51ee91-922b-4072-9eca-7f3ef3623346.png)

### How to reproduce ☕️

First time use with google auth

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by ThangHuuVu** [comment]
Hi there, please try this suggestion: https://github.com/nextauthjs/next-auth/issues/3920#issuecomment-1037572935
