### ISSUE TITLE
Reassign import binding issue

### ISSUE THREAD

**Issue by Arodlives** [nextauthjs/next-auth#5752]
### Environment

  npmPackages:
    next: 13.0.0 => 13.0.0
    next-auth: ^4.16.3 => 4.16.3
    react: 18.2.0 => 18.2.0

### Reproduction URL

https://github.com/Arodlives/spotify

### Describe the issue

<img width="832" alt="error" src="https://user-images.githubusercontent.com/46770499/200395809-f657e747-6e89-43d3-a231-d8e262ceacf1.PNG">

### How to reproduce

by running to localhost 3000 then append "/login" to url

### Expected behavior

comes up with a binding erro

**Comment by balazsorban44** [comment]
Line 31 should be:

```diff
- export default NextAuth = ({
+ export default NextAuth({
```
