### ISSUE TITLE
IP address during sign in request

### ISSUE THREAD

**Issue by nandox5** [nextauthjs/next-auth#5756]
### Description 📓

Include the ip address of the person attempting to login weather sucessful or not.
or be able to access the req at any point in time during any callback or event.

### How to reproduce ☕️

nothing to reproduce

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Check out https://next-auth.js.org/configuration/initialization#advanced-initialization
