### ISSUE TITLE
Email server URL format

### ISSUE THREAD

**Issue by ericvrp** [nextauthjs/next-auth#577]
**Describe the bug**
I use an email server where the full email address is used as username and it looks like the nodemailer parsen doesn't know what to do with the extra @-sign

**Steps to reproduce**
`EMAIL_SERVER=smtp://user@domain:password@smtpserver:465`
Please note port 465 which required secure=true later on

**Expected behavior**
Email will be sent

**Additional context**
email.js contains this line
`    _nodemailer.default.createTransport(server).sendMail({`

when I replace that with this then things work (note the additional secure: true setting)
```_nodemailer.de
fault.createTransport({
      host: "<smtp server>",
      secure: true,
      auth: { user: "<username>@<domain>", pass: "<my password>" }
    }).sendMail({
```

But this would require extra settings apart from the EMAIL_SERVER string.

**Feedback**

*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
IIRC I think you might need to URL encoded the `@` as `%40` e.g. `user%40domain`

**Comment by iaincollins** [comment]
I just checked and we are using unencoded at in the example project so I don't think that's the problem.

You can use `smtps://` as the protocol if the issue it is needs to be secure.

**Comment by ericvrp** [comment]
perfect - smtps (for port 465) did the trick. It had nothing to doe with the @ sign in the username.

**Comment by iaincollins** [comment]
We really need to add these to the docs, but for reference for anyone who finds this in future, here are some example strings for some SMTP providers that I've tested:

```
EMAIL_SERVER=smtps://abc:123@email-smtp.us-east-1.amazonaws.com:465
EMAIL_SERVER=smtps://user@example.com:123@smtp.gmail.com:465
EMAIL_SERVER=smtp://abc:123@smtp.sendgrid.net:587
EMAIL_SERVER=smtp://user@example.com:123@smtp-pulse.com:587
EMAIL_SERVER=smtp://user@example.com:123@smtp-relay.sendinblue.com:587
```

* SendInBlue was the quickest to sign up for and get working and was the least friction. It also provides useful metrics out of the box.
* Gmail works well if you have a dedicated account for handling this (e.g. a user on a business account) and explicitly enable SMTP access.
* AWS SES is good option for production- you can get it working right away on your own domain but has some lead time to be activated before you can email other domains.
* Other providers listed had longer lead times to get going / or more cumbersome processes and took much longer (in some cases days) to activate before they could be used (I was a fan of Send Grid but I didn't have a great experience with them).

**Comment by PaulKushch** [comment]
@iaincollins I am trying to use AWS SES with next-auth and use your suggestion:
**smtps://USER:PASSWORD@email-smtp.eu-west-1.amazonaws.com:465**

But I keep getting 
**InvalidClientTokenId: The security token included in the request is invalid.**

See my example code below:
```
    Providers.Email({
      server:
        'smtps://USER:PASSWORD@email-smtp.eu-west-1.amazonaws.com:465',
      from: process.env.EMAIL_FROM,
      sendVerificationRequest: customSendVerificationRequest,
    }),
```
```
let nodemailer = require('nodemailer');
const AWS = require('aws-sdk');

const customSendVerificationRequest = ({
  identifier: email,
  url,
  baseUrl,
  provider,
}) => {
  // create Nodemailer SES transporter
  const { server, from } = provider;
  const site = baseUrl.replace(/^https?:\/\//, '');
  (async () => {
    try {
      let transporter = nodemailer.createTransport(server);
      await transporter.sendMail({
        from,
        to: email,
        subject: `Log in to ${site}`,
        html: html({ url, site, email }),
      });
    } catch (error) {
      console.error(error);
      if (error.response) {
        console.error(error.response.body);
      }
    }
  })();
};
```
Any suggestions what I am doing wrong? I tried to recreate credentials, but get same error. Emails / domain verified in AWS as well.
