### ISSUE TITLE
How to handle provider returning OAuth profile without email

### ISSUE THREAD

**Issue by msbeeman** [nextauthjs/next-auth#5771]
### Question 💬

Hi good morning. I had a question on how to handle user sign up when the provider doesn't return an email in the users OAuth profile.

If possible, I'd like some sort of way to pause the next-auth process when the
[next-auth][adapter_createUser] adapter function receives a OAuth profile without an email and force the user to provide an email before continuing with the [adapter_createUser] function. Is something like this possible? 

It looks like callbacks wouldn't work here because I think they get executed after the adapter functions finish. 

Example) This provider does not return an email to me, so when the [createUser] adapter function is triggered no email is passed in causing issues in the database.
![image](https://user-images.githubusercontent.com/59752826/200838723-5ec4b032-cf22-4e6f-a5a2-47be422690ef.png)
![image](https://user-images.githubusercontent.com/59752826/200839091-f886162a-1796-4633-8825-b551855d5ed7.png)

### How to reproduce ☕️

- Clone the next-auth sample app
- Navigate to [...nextauth].ts file
- - **Import strava as a provider** 
`import StravaProvider from "next-auth/providers/strava";`
- - **In the NextAuthOptions object set debug mode to true so you can observe the args being passed in to each adapter function**
`NextAuthOptions = {............debug: true}`
- Observe the profile passed back by Strava [next-auth][debug][PROFILE_DATA]

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
You could use a combination of [Advanced Initialization](https://next-auth.js.org/configuration/initialization#advanced-initialization), the [Provider's profile callback](https://next-auth.js.org/adapters/models#user), and a client-side form with backend validation that requires the user to [pass an e-mail](https://next-auth.js.org/getting-started/client#additional-parameters).
