### ISSUE TITLE
Allow additional scopes in LinkedIn auth

### ISSUE THREAD

**Issue by anonrose** [nextauthjs/next-auth#5773]
### Description 📓

The LinkedIn Auth is limited to only two scopes [r_liteprofile and r_emailaddress](https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/providers/linkedin.ts#L31). This limits the amount of data that applications providing OAuth to users can request on behalf of the users.

Add additional, and optional, scopes including [`r_1st_connections`](https://learn.microsoft.com/en-us/linkedin/shared/integrations/people/connections-api?context=linkedin%2Fcompliance%2Fcontext&view=li-lms-unversioned&preserve-view=true#permissions) so that apps may optionally request information from users.

I would suggest adding options when creating the LinkedInProvider provider in the [...nextaut].ts file. This may pour over into other connections as it doesn't appear that many connections offer this as an option.

### How to reproduce ☕️

Attempt to make a request on behalf of a user with the scope of `r_1st_connections`.

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
See the docs: https://next-auth.js.org/configuration/providers/oauth#override-default-options

**Comment by anonrose** [comment]
whoops, ty
