### ISSUE TITLE
Breaking change in Session, User, and Profile typing. Documentation suggests unintentional

### ISSUE THREAD

**Issue by simonjduff** [nextauthjs/next-auth#5797]
### Environment

 System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M2
    Memory: 54.03 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 106.0.5
    Safari: 16.1
  npmPackages:
    next: ^12.3.1 => 12.3.1
    next-auth: ^4.16.4 => 4.16.4
    react: ^18.2.0 => 18.2.0

### Reproduction URL

https://github.com/PaceCCS/next-auth-session/

### Describe the issue

PR #4953 introduced a [breaking change](https://github.com/nextauthjs/next-auth/pull/4953/files?diff=unified&w=0#diff-4a09ba4be6baf319f19fb95085e3c72cb52ab694f013b67ddb8861042a0f9b69L423), where Session, User, and Profile no longer extend `Record`.

```
- export interface DefaultSession extends Record<string, unknown> {
+ export interface DefaultSession {
```

[The documentation](https://next-auth.js.org/configuration/callbacks#session-callback) shows the intention of being able to set arbitrary values into session:
```
callbacks: {
  async session({ session, token, user }) {
    // Send properties to the client, like an access_token and user id from a provider.
    session.accessToken = token.accessToken
    session.user.id = token.id
    
    return session
  }
}
```

but now that session is not a `Record`, instead a typescript compiler error is generated
```
npm run build

> next-auth-session@0.1.0 build
> next build

info  - Linting and checking validity of types .Failed to compile.

./pages/api/auth/[...nextauth].ts:25:15
Type error: Property 'accessToken' does not exist on type 'Session'.

  23 |   callbacks: {
  24 |     session({ session, token }) {
> 25 |       session.accessToken = token.accessToken;
     |               ^
  26 |       return session;
  27 |     },
  28 |   },
```

### How to reproduce

Scaffold a new nextjs app
Install next-auth
Add a [credentials provider](https://next-auth.js.org/configuration/providers/credentials)
Add a session callback setting an `accessToken` property.
npm run build
observe compiler error

### Expected behavior

Arbitrary data should be able to be set and retrieved from the `Session` type.
Or, the documentation should be updated, showing how to set and retrieve arbitrary data from Session a different way.

**Comment by balazsorban44** [comment]
See https://next-auth.js.org/getting-started/typescript#module-augmentation
