### ISSUE TITLE
Example of cross domain login with iFrame and postMessage

### ISSUE THREAD

**Issue by ericvrp** [nextauthjs/next-auth#580]
**Summary of proposed feature**
As suggested by issue #402 this solution would be for websites in transition to NextJS/next-auth by providing identity that can be transferred to the new site.

We are building a version 2 site with NextJS and next-auth is a great fit for us. However it will take time to have this feature complete in production and for the current version 1 (plain html/javescript) we already need to use the same authentication system.

So the plan is to have version 2 in production with just the next-auth features and have v1 use this cross domain.
BTW v1 is already on a subdomain so my guess is that creating a custom cookie as described in #405 will not work?

**Purpose of proposed feature**
Ease transition of old to new sites using next-auth

**Describe any alternatives you've considered**
We’re wondering if it would work if on top of the first site we would run a reverse proxy of the /api/auth routes to the new NextJS site?

**BTW what makes external login to Auth0 work**
With auth0 the user gets also redirected to another domain. What is the key difference and reason why it work with their setup?

I would be willing to test any example.

**Comment by mikestopcontinues** [comment]
Have you made any progress on this? I'm thinking of using NextAuth, and I have a very similar use case. What did you come up with?

**Comment by ericvanular** [comment]
Any progress here? This could be very useful
