### ISSUE TITLE
MongoDBAdapater is not a function error

### ISSUE THREAD

**Issue by DjamelAbbou** [nextauthjs/next-auth#5800]
### Adapter type

@next-auth/mongodb-adapter

### Environment

  System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i3-2370M CPU @ 2.40GHz
    Memory: 1007.90 MB / 3.74 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash

  Binaries:
    Node: 19.0.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm

  Browsers:
    Chromium: 107.0.5304.87
    Firefox: 106.0.4

  npmPackages:
    next: 12.3.1 => 12.3.1 
    next-auth: ^4.16.4 => 4.16.4 
    react: 18.2.0 => 18.2.0 

  npmPackages:
    @next-auth/mongodb-adapter: ^1.1.1 => 1.1.1 

### Reproduction URL

https://github.com/DjamelAbbou/trying-auth

### Describe the issue

Whilst learning how to use next-auth with mongo database, i imported the function **signIn** from **next-auth/react** and set up a basic div element with a onClick function which calls the signIn function when the div is clicked, however, nextauth gives the following error concerning MongoDBAdapter
![2022-11-11-213430_1138x264_scrot](https://user-images.githubusercontent.com/109722310/201432488-ff0b1cb9-2039-4697-950a-ae15a72a0909.png)

which is weird and odd, because, the MongoDBAdapter code is from the docs.

### How to reproduce

1.run yarn create next-app
2.remove the ui of the index page and replace it with the following
```
import { signIn } from "next-auth/react"

export default function HomePage() {
  return (
      <div
        className="border-sky-800 border-2 rounded-lg w-1/3 flex justify-center items-center text-xl cursor-pointer"
        onClick={() => signIn()}
      >
        click here to use the next-auth sign in function
      </div>
)
```

3.add a **modules folder** in the project folder and make a db.js file in it with the following code
```
import { MongoClient } from "mongodb";

const uri = process.env.MONGODB_URI;
const options = {
  useUnifiedTopology: true,
  useNewUrlParser: true,
};

let client;
let clientPromise;

if (!process.env.MONGODB_URI) {
  throw new Error("Please add your Mongo URI to envs");
}

if (process.env.NODE_ENV === "development") {
  if (!global._mongoClientPromise) {
    client = new MongoClient(uri, options);
    global._mongoClientPromise = client.connect();
  }
  clientPromise = global._mongoClientPromise;
} else {
  client = new MongoClient(uri, options);
  clientPromise = client.connect();
}

export function jsonify(val) {
  return JSON.parse(JSON.stringify(val));
}

export default clientPromise;
```

4.add a **auth** folder in api folder and add a **[...nextauth].js** file in it with the following code
```
import NextAuth from "next-auth";
import { MongoDBAdapater } from "@next-auth/mongodb-adapter";
import clientPromise from "@/modules/db";
import CredentialsProvider from "next-auth/providers/credentials";

export default NextAuth({
  adapter: MongoDBAdapater(clientPromise),
  session: {
    strategy: "jwt",
  },
  pages: {
    signIn: "/",
    signOut: "/",
  },
  providers: [
    CredentialsProvider({
      type: "credentials",
      credentials: {},
      async authorize(credentials, req) {
        const { username, password } = credentials;
        const user = await (await clientPromise)
          .db()
          .collection("users")
          .find({ username, password });

        if (user) {
          return user;
        } else {
          return null;
        }
      },
    }),
  ],
});
```
5.set up a mongo atlas database and get the MONGODB_URI to connect to it and add it to .env file.

thats it, this should lead to the same issue.

### Expected behavior

it shouldve redirected me to the signIn with credentials page, but it instead gave a internal server error instead

**Comment by ThangHuuVu** [comment]
It seems like you had a typo there
MongoDBAdapater -> MongoDBAdapter

**Comment by DjamelAbbou** [comment]
Well my bad! Thanks for letting me know.
