### ISSUE TITLE
Possible memory leak from version 4.4.0

### ISSUE THREAD

**Issue by M4tT3d** [nextauthjs/next-auth#5807]
### Environment

```
Binaries:
    Node: 18.12.1 - /usr/bin/node
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Firefox: 106.0.5
  npmPackages:
    next: ^13.0.2 => 13.0.3 
    next-auth: ^4.16.4 => 4.16.4 
    react: 18.2.0 => 18.2.0
``` 

### Reproduction URL

\

### Describe the issue

Hello everyone.
I found out that there is a possible memory leak from the version 4.4.0. In my project I use OAuth2 with google. When I try to login in my website, the node process consumes around 1.1-1.3 GB of RAM. I already checked that I'm not using some `unstable_getServerSession()` in any client side component and I found out that a commit with the version 4.3.4 doesn't consume so much RAM. I get this problem in the production build

### How to reproduce

Create a project with a version of next auth >= 4.4.0.
Build the project and see how much RAM the node process uses

### Expected behavior

the node process doesn't have to consume that much ram

**Comment by balazsorban44** [comment]
Could you add a reproduction? We will also need more info, as it's unlikely a NextAuth.js issue. Node.js, Next.js version, any other changes (something like a specific commit that proves that simply bumping the version caused the issue)

**Comment by M4tT3d** [comment]
After some investigations, I found out that maybe it's fault of my client that I use to send requests at my backend. But I don't understand because with the version 4.3.4 I don't have such a huge consummation of ram. Problems start from version 4.4

**Comment by balazsorban44** [comment]
still, we'll need a reproduction. closing for now, until it's proven to be a NextAuth.js bug.
