### ISSUE TITLE
Getting error message from NextAuth response

### ISSUE THREAD

**Issue by MarioStojcevski** [nextauthjs/next-auth#5839]
## Question
I am using strapi v4 as a backend and I can't seem to get the error responses strapi sends on my Next.JS application. Previously, before I used NextAuth I was able to fetch them. Now, after NextAuth intercepts the response from strapi, it then sends me a response on the frontend with just a default error message "Internal server error" whereas I would like to get the real strapi error message.

### How to reproduce ☕️

`[...nextauth].ts`
```ts
const authOptions: NextAuthOptions = {
    providers: [
        CredentialsProvider({
            name: "Credentials",
            credentials: {
                username: { label: "Username", type: "text", placeholder: "" },
                password: { label: "Password", type: "password" },
            },
            async authorize(credentials) {
                return login(credentials as LoginUserCredentials);
            },
        }),
    ],
    secret: "somesecret",
    session: {
        strategy: "jwt",
    },
};

const Auth = (req: NextApiRequest, res: NextApiResponse) =>
    NextAuth(req, res, authOptions);

export default Auth;
```

`login.ts`
```ts

export async function login({ username, password }: LoginUserCredentials) {
    const loggedInUserResponse = await axios.post(`${API_URL}/auth/local`, {
        identifier: username,
        password,
    });

    if (loggedInUserResponse.status === 200) {
        return {
            id: "1", // additionally i don't know what to do with this, i cant fetch the user id and return it correctly
            ...loggedInUserResponse,
        };
    }

    throw Error("An error has occured.");
}
```

If i `console.log` the `loggedInUserResponse` and it is an error response, I get a generic error instead of a concrete strapi error. Please help

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
You should handle any authorization error in the `authorize` callback and not forward information to the client about why authorization failed. This is explained in the docs: https://next-auth.js.org/providers/credentials#example---username--password
