### ISSUE TITLE
Handle email not sending in sendVerificationRequest

### ISSUE THREAD

**Issue by linearshift** [nextauthjs/next-auth#5847]
### Question 💬

Hello :-)

I encountered a problem with NodeMailer once deploying a working solution to Vercel for testing. I am using Email links for signing and have written a custom 'sendVerificationRequest' to send the mails. A few google searches later I realised that a better solution would be to just use the SendGrid API, and abandon NodeMailer altogether... and this works absolutely fine. Yay!

But...

How can I discover if an error does occur when attempting to send the email? I have trawled through the docs and source code, discussion and issues - but can't find any pointers on this. Wondering what I am missing here?

### How to reproduce ☕️

Not a full repo, but you should get the idea:

```
               EmailProvider({			
			from: process.env.EMAIL_FROM,
			sendVerificationRequest({ identifier, url, provider }) {
				CustomSendVerificationRequest({ identifier, url, provider });
			},
		}),
```

And then here's the function:

```
const sgMail = require('@sendgrid/mail');
export async function CustomSendVerificationRequest(params) {
	sgMail.setApiKey(process.env.SENDGRID_API_KEY);

	const { identifier, url, provider, theme } = params;
	const { host } = new URL(url); 

	const content = {
		to: identifier,
		from: provider.from,
		subject: `Sign in`,
		text: text({ url, host }),
		html: html({ url, host, theme }),
	};

	try {
		await sgMail.send(content);
		console.log('Email sent');
	} catch (error) {
		console.log('ERROR', error);
                // Here I want to redirect to the error callback
	}
}
```
I can force the function to error by not supplying the API key, and see the error logged, but can't figure out how to pass back this message. At present the custom 'verifyRequest' page is just loaded, no matter what I happens.

So to be clear, everything is working fine - I just want to be able to detect an error when it occurs.

Thanks in advance for pointing me to the obvious answer that I have somehow missed :-)

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
You should already be redirected if an error occurs as shown here:

https://github.com/nextauthjs/next-auth/blob/0d1757814f6a8bc8b7d98cb0f21532bca3348529/packages/next-auth/src/core/routes/signin.ts#L95-L96

The error will be logged via `logger`, which defaults to `console` or you can forward it to your third-party service via [`logger`](https://next-auth.js.org/configuration/options#logger)

**Comment by isaacdarcilla** [comment]
Got the same problem here. Console does not display any errors but still can't receive an email.
