### ISSUE TITLE
How to get more information back from Azure using the Graph API?

### ISSUE THREAD

**Issue by Lucasvo1** [nextauthjs/next-auth#5848]
### Question 💬

I would like to get extra information from the login through Azure (it's an internal platform) where I have to get the company name, preferred language, manager and location. I am using the Prisma adapter. 

### How to reproduce ☕️

GET https://graph.microsoft.com/v1.0/me

Normally this request gives back more fields:

HTTP/1.1 200 OK
Content-type: application/json

```
{
  "businessPhones": [
       "+1 425 555 0109"
   ],
   "displayName": "Adele Vance",
   "givenName": "Adele",
   "jobTitle": "Retail Manager",
   "mail": "AdeleV@contoso.onmicrosoft.com",
   "mobilePhone": "+1 425 555 0109",
   "officeLocation": "18/2111",
   "preferredLanguage": "en-US",
   "surname": "Vance",
   "userPrincipalName": "AdeleV@contoso.onmicrosoft.com",
   "id": "87d349ed-44d7-43e1-9a83-5f2406dee5bd"
}
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Via providing the `scope` option: https://next-auth.js.org/configuration/providers/oauth#authorization-option

The default is purposefully limited: https://github.com/nextauthjs/next-auth/blob/0d1757814f6a8bc8b7d98cb0f21532bca3348529/packages/next-auth/src/providers/azure-ad.ts#L31
