### ISSUE TITLE
Silent Signin

### ISSUE THREAD

**Issue by BenRedmondBenham** [nextauthjs/next-auth#586]
**Your question**
Does Next Auth JS have an option for silent signin like oidc-client does? 

**What are you trying to do**
When you have multiple websites on a shared domain (one.example.com, two.example.com) silent sign in allows you to sign in without user interaction in a hidden iframe. So if you login to one.example.com and then browse to two.example.com you will be automatically signed in.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
For updates on this please see #439
