### ISSUE TITLE
[next-auth][error][CLIENT_FETCH_ERROR]  Unexpected token '<', "<!DOCTYPE "... is not valid JSON 

### ISSUE THREAD

**Issue by mrseankumar25** [nextauthjs/next-auth#5861]
### Provider type

Credentials

### Environment

  env:
    NEXTAUTH_SECRET="SECRET"
    NEXTAUTH_URL_INTERNAL=http://localhost:8888
    NEXTAUTH_URL=http://localhost:8888/api/auth

  System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 5.77 GB / 15.77 GB
  Binaries:
    Node: 18.8.0 - \nodejs\node.EXE
    npm: 8.18.0 - \nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.35)
    Internet Explorer: 11.0.22621.1        
  npmPackages:
    next: ^13.0.4 => 13.0.4
    next-auth: ^4.16.4 => 4.16.4
    react: 18.2.0 => 18.2.0

![image](https://user-images.githubusercontent.com/43328839/202920882-76264f0b-c016-4dc1-8bf5-039b7aa578a9.png)
![image](https://user-images.githubusercontent.com/43328839/202921240-54405800-890b-42ee-9a98-fdf81b18ed91.png)

### Reproduction URL

http://localhost:8888/

### Describe the issue

Hello there,

I'm trying to implement sign-in option in my next js app, however, it's not working as it should be. Whenever I tried to signin it give "there is a problem with the server configuration.  check the server logs for more information." error I have attached screenshots of errors.

### How to reproduce

I just added next-auth in my existing nextjs app.

### Expected behavior

I just want to implement CredentialsProvider in my nextjs app.

**Comment by aledovskikh** [comment]
@mrseankumar25 Did you fix this error?

**Comment by mrseankumar25** [comment]
> http://localhost:8888/ is not a reproduction URL. please link to your source code. Server logs are not the same as the browser console. Check the logs in your terminal, it should explain the issue. 👍

I am trying to run it on "netlify dev", however, when I run it with npm run dev and cleared the cookies it's working fine, but I want to run it with "ntl dev" or "netlify dev"

**Comment by mrseankumar25** [comment]
> @mrseankumar25 Did you fix this error?

I tried it with "npm run dev" and cleaned cookies then it's working fine.

**Comment by hanibat8** [comment]
I am getting the same error. Have been trying to fix for a long time and it is not working.

**Comment by Mo-Aziz** [comment]
I have the same error as well and i have been trying all solutions for almost a day now and still unable to fetch any data from google provider

**Comment by Shahidxyt** [comment]
same error didn't found any solution for google provider

**Comment by Shahidxyt** [comment]
> I have the same error as well and i have been trying all solutions for almost a day now and still unable to fetch any data from google provider

you found any solution bro?

**Comment by Mo-Aziz** [comment]
@Shahidxyt No, but i am still looking for any solutions as i can not move forward with the project without the google provider data. I hope if anyone finds a solution for the same bug, let us know.

**Comment by Shahidxyt** [comment]
> @Shahidxyt No, but i am still looking for any solutions as i can not move forward with the project without the google provider data. I hope if anyone finds a solution for the same bug, let us know.

found the solution
first remove all the dependencies
npm uninstall next-auth
and then install this version it works for me
npm i next-auth@4.22.1

**Comment by prashantskywave** [comment]
How we can use in Next 14 ?

**Comment by hmttelange** [comment]
23-49aaaa699609f25a.js:1 [next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error Unexpected token '<', "<!DOCTYPE "... is not valid JSON 
{error: {…}, url: '/api/auth/session', message: `Unexpected token '<', "<!DOCTYPE "... is not valid JSON`}
client
: 
true
error
: 
{message: `Unexpected token '<', "<!DOCTYPE "... is not valid JSON`, stack: `SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON`, name: 'SyntaxError'}
message
: 
"Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON"
url
: 
"/api/auth/session"
[[Prototype]]
: 
Object
541-6ab3e0ed64b8ef1e.js:1 
 POST https://timesheet-v1.vercel.app/api/auth/_log 405

I am also getting this issue on production env (working in local environment)
