### ISSUE TITLE
Prisma Adapter doesn't work with unstable_getServerSession in RSC

### ISSUE THREAD

**Issue by ReinhardtR** [nextauthjs/next-auth#5865]
### Adapter type

@next-auth/prisma-adapter

### Environment

    "next": "13.0.4"
    "next-auth": "4.17.0"
    "react": "18.2.0"
    "@next-auth/prisma-adapter": "^1.0.5"

### Reproduction URL

https://github.com/ReinhardtR/task-master

### Describe the issue

Usage
```ts
export async function AuthHeaderSection() {
  const session = await unstable_getServerSession();

  console.log(session); // is always null

  return (
    <>
      {session?.user ? (
        <SignOutButton name={session.user.name!} />
      ) : (
        <SignInButton />
      )}
    </>
  );
}
```

Error
```
[next-auth][error][JWT_SESSION_ERROR] 
https://next-auth.js.org/errors#jwt_session_error Invalid Compact JWE {
  message: 'Invalid Compact JWE',
  stack: 'JWEInvalid: Invalid Compact JWE\n' +
    '    at compactDecrypt (webpack-internal:///(sc_server)/./node_modules/.pnpm/jose@4.
    '    at jwtDecrypt (webpack-internal:///(sc_server)/./node_modules/.pnpm/jose@4.11.0
    '    at Object.decode (webpack-internal:///(sc_server)/./node_modules/.pnpm/next-autn' +
ession.js:25:34)\n' +
    '    at async NextAuthHandler (webpack-internal:///(sc_server)/./node_modules/.pnpm/s:157:37)\n' +
    '    at async unstable_getServerSession (webpack-internal:///(sc_server)/./node_moduxt/index.js:89:21)\n' +
    '    at async AuthHeaderSection (webpack-internal:///(sc_server)/./components/AuthHe
  name: 'JWEInvalid'
}
```

### How to reproduce

1. Sign in with Google
2. Session is logged as null

### Expected behavior

Session should not be null when signed in.

Getting the session with `useSession` in a Client Component works as expected.

**Comment by balazsorban44** [comment]
When using an adapter, you'll need to pass `authOptions` to `unstable_getServerSession`, otherwise, it does not know where the session is (more precisely falls back to the default which is JWT, and that will return `null`). @davidkapuza please add a reproduction in a new issue.
