### ISSUE TITLE
`experimental-edge` fails with NextAuth & Next.js

### ISSUE THREAD

**Issue by eli-front** [nextauthjs/next-auth#5870]
### Environment

``` 
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 97.42 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 105.0.3
  npmPackages:
    next: 12.3.1 => 12.3.1 
    next-auth: ^4.15.2 => 4.16.3 
    react: 18.2.0 => 18.2.0 
```

### Reproduction URL

https://github.com/eli-front/nextauth-edge-issue

### Describe the issue

Bug on `next build` (yarn build)
```
Failed to compile.

./node_modules/@babel/runtime/regenerator/index.js
Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Edge Runtime
Learn More: https://nextjs.org/docs/messages/edge-dynamic-code-evaluation

Import trace for requested module:
./node_modules/@babel/runtime/regenerator/index.js
./node_modules/next-auth/core/errors.js
./node_modules/next-auth/utils/logger.js
./node_modules/next-auth/core/index.js
./node_modules/next-auth/next/index.js
./node_modules/next-auth/index.js


> Build failed because of webpack errors
error Command failed with exit code 1.
```

### How to reproduce

1. Clone repo (https://github.com/eli-front/nextauth-edge-issue)[https://github.com/eli-front/nextauth-edge-issue] 
2.  run `yarn install && yarn build`

OR

1. create a next.js app
2. add basic next-auth integration
3. set `	experimental: {
		runtime: 'experimental-edge',
	}` in `next.config.js` 

### Expected behavior

be able to build / use next auth on edge

**Comment by chyzwar** [comment]
I have the same issue. 

I think dropping support for IE11 would help to resolve above issue ? I

**Comment by eli-front** [comment]
> I have the same issue. 
> 
> 
> 
> I think dropping support for IE11 would help to resolve above issue ? I 

Possibly, but my gut assumption is that because the edge code isn't running on the browser it shouldn't be directly correlated.

**Comment by chyzwar** [comment]
I rase pr that would fix above regenerator issue. Tested locally with my project. Unfortunatly there is anotrher issue  this time with openid

```
./node_modules/openid-client/lib/helpers/keystore.js:1:11
Module not found: Can't resolve 'v8'

Import trace for requested module:
./node_modules/openid-client/lib/helpers/issuer.js
./node_modules/openid-client/lib/issuer.js
./node_modules/openid-client/lib/index.js
./node_modules/openid-client/lib/index.mjs
./node_modules/next-auth/core/lib/oauth/callback.js
./node_modules/next-auth/core/routes/callback.js
./node_modules/next-auth/core/routes/index.js
./node_modules/next-auth/core/index.js
./node_modules/next-auth/next/index.js
./lib/session.ts
./app/builder/layout.tsx
```

**Comment by balazsorban44** [comment]
This is known. We are working on it. See https://github.com/nextauthjs/next-auth/pull/5536
