### ISSUE TITLE
follow the providers:apple document cannot start

### ISSUE THREAD

**Issue by geminiyellow** [nextauthjs/next-auth#5876]
### What is the improvement or update you wish to see?

`Testing on a development server`not working, when i follow what it said.

what i do is follow the doc's step,

- add dev.example.com to etc/host
    - but the doc not tell me why should i add this, and it not be used after this line.

- creat ceritificate, yes it working

- deploy to server not working
    - i copy the code from doc, and use `node server.js` start it
    - then i got the error
    
```
error - ../node_modules/next/dist/esm/server/web/next-url.js (7:0) @ parseURL
error - Invalid URL: https://undefined:undefined/default/default?__nextDefaultLocale=default&__nextLocale=default
null
```

<img width="480" alt="スクリーンショット 2022-11-24 14 44 01" src="https://user-images.githubusercontent.com/929878/203703466-e4bf1e7a-685b-4eef-944d-d96179735b01.png">

what should i do?
    

### Is there any context that might help us understand?

no

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/providers/apple#testing-on-a-development-server

**Comment by balazsorban44** [comment]
Can you add a reproduction repository?
