### ISSUE TITLE
The schema must be one of the following: public, storage, graphql_public

### ISSUE THREAD

**Issue by scshiv29-dev** [nextauthjs/next-auth#5884]
### Environment

 npx envinfo --system --binaries --browsers --npmPackages "next,react,next-auth"

  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 7.41 GB / 15.93 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.56)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    next: 13.0.5 => 13.0.5
    next-auth: ^4.17.0 => 4.17.0
    react: 18.2.0 => 18.2.0

### Reproduction URL

na

### Describe the issue

getting the above mentioned issue when using supabase adapter. 

### How to reproduce

Add supabase adapter and try to sign in 

### Expected behavior

User account creation.

**Comment by thisfrontenddev** [comment]
For future reference, restarting Supabase locally with `supabase stop && supabase start` does fix the issue. If you're working with the remote Supabase instance, there's a button in the dashboard to restart the database.

✍🏼 More details

This happened by following the instructions properly for the Supabase adapter, leading to this error in the terminal :

```
# this is returned even though the `next_auth` schema is exposed on supabase
# but the database instance has not been restarted

[next-auth][error][adapter_error_getSessionAndUser]
https://next-auth.js.org/errors#adapter_error_getsessionanduser The schema must be one of the following: public, storage, graphql_public
{
    code: 'PGRST106',
    details: null,
    hint: null,
    message: 'The schema must be one of the following: public, storage, graphql_public'
}
```

💡 [PGRST106](https://postgrest.org/en/stable/errors.html#group-1-api-request) : The schema specified when switching schemas is not present in the db-schemas configuration variable.

I can make a PR explaining this for the supabase adapter docs if you feel this is useful @balazsorban44 ?

**Comment by balazsorban44** [comment]
Yeah, clarifying the docs is welcome.

**Comment by rbrueckner** [comment]
Hi, for me restarting Supabase does not solve the issue! I'm having Supabase self-hosted - is this a limitation?

**Comment by scshiv29-dev** [comment]
@rbrueckner  so go to your project settings>API>  add next_auth schema u created from the docs here
![image](https://user-images.githubusercontent.com/68141773/224561923-5c2173cc-7d53-45ac-a105-58f2e311e813.png)

**Comment by rbrueckner** [comment]
Where do I find "project settings" in a self-hosted Studio?

**Comment by scshiv29-dev** [comment]
@rbrueckner  aah that's something I don't know, maybe in the project section ? can you send a screenshot of the ui?

**Comment by thiras** [comment]
@rbrueckner you can use your local `config.toml` of supabase

**Comment by nicolefranc** [comment]
> If you're working with the remote Supabase instance, there's a button in the dashboard to restart the database.

Hey, does anyone know where exactly this is? I've added next_auth to the exposed schema but still getting this error. I can't find the button to restart the database.

**Comment by LuanPianeli07** [comment]
I had the same error, in my case editing table setting in Supabase table editor worked. I unchecked "Enable Row Level Security (RLS)".

**Comment by LuanPianeli07** [comment]
> > If you're working with the remote Supabase instance, there's a button in the dashboard to restart the database.
> 
> Hey, does anyone know where exactly this is? I've added next_auth to the exposed schema but still getting this error. I can't find the button to restart the database.

I had the same error, in my case editing table setting in Supabase table editor worked. I unchecked "Enable Row Level Security (RLS)".

**Comment by farid98** [comment]
> @rbrueckner so go to your project settings>API> add next_auth schema u created from the docs here ![image](https://user-images.githubusercontent.com/68141773/224561923-5c2173cc-7d53-45ac-a105-58f2e311e813.png)

This works. Thanks.

**Comment by SrDouglax** [comment]
@farid98 There is no settings option in self-hosted projects

**Comment by swingislee** [comment]
@SrDouglax Have you found a way to expose the schema in a self-hosted project?

**Comment by nietsmmar** [comment]
> @farid98 There is no settings option in self-hosted projects

normally you have a `config.toml` where you set your schemas:

```
[api]
schemas = ["public", "storage", "graphql_public", ...]
```

**Comment by kayaayberk** [comment]
For those who might not be familiar with local development with docker, the following might be helpful:

once you pull your public schemas, supabase cli recommends another command like:
> The auth and storage schemas are excluded. Run `supabase db pull --schema auth,storage` again to diff them.

try to add "next_auth" to this command: `supabase db pull --schema auth,storage,next_auth`

once the new migration files are generated, you can push them to your local by running: `supabase db push --local`

otherwise, next_auth schema won't show up in your local studio. 

additionally, you can generate types by running: 
`supabase gen types typescript --local --schema next_auth > types_auth_db.ts`

this will create a file called `types_auth_db.ts` with next_auth schema types in it.

Note: I'm new to NextAuth so I'm not so sure if the last part is fully safe.

**Comment by Cansiano** [comment]
I have changed config.toml and restarted docker, I have still same error. Is there solution for that?

**Comment by jetset1989** [comment]
@nietsmmar thanks a lot

**Comment by g-wozniak** [comment]
Don't forget to modify the custom schemas in `config.toml` if you're talking about the local instance. The migration won't fix it for you.

**Comment by UdaraWanasinghe** [comment]
@swingislee Append your schema to the `PGRST_DB_SCHEMAS` env variable and recreate the docker containers.
```
docker compose stop
docker compose up -d
```

**Comment by JetUni** [comment]
> normally you have a `config.toml` where you set your schemas:
> 
> ```
> [api]
> schemas = ["public", "storage", "graphql_public", ...]
> ```

I added my new schema here as I was developing locally and it was working locally, but when I pushed the changes to the remote, it didn't update the api to use the schemas that I defined here. Did I miss a command that I was supposed to run after pushing my code?

**Comment by CX330Blake** [comment]
> [@rbrueckner](https://github.com/rbrueckner) 因此，請前往您的專案設定> API>新增您從此處的文件建立的 next_auth 模式 ![image](https://user-images.githubusercontent.com/68141773/224561923-5c2173cc-7d53-45ac-a105-58f2e311e813.png)

I love u
