### ISSUE TITLE
Opening the sample /server does not show session information.

### ISSUE THREAD

**Issue by dmdragon** [nextauthjs/next-auth#5891]
### Environment

  System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700F
    Memory: 20.75 GB / 31.79 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.1.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.56)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    next: latest => 13.0.5
    next-auth: latest => 4.17.0
    react: ^18.2.0 => 18.2.0

### Reproduction URL

https://github.com/nextauthjs/next-auth/blob/main/apps/example-nextjs/pages/server.tsx

### Describe the issue

In the exsample /apps/example-nextjs, after following the README instructions, starting the application with `npm run dev` and signing in, opening the SSR sample, `http://localhost:3000/server`, the contents of the session are not displayed.

In this case, changes the name of the variable `session` to another name (e.g., `s_session`) in server.tsx, the session contents will be displayed.

### How to reproduce

1. Run as per [README](https://github.com/nextauthjs/next-auth-example/blob/main/README.md)
2. Start with `npm run dev`.
3. Sign in.
4. Open `http://localhost:3000/server`.

Session information that should appear is not displayed. If changes the variable `session` in server.tsx to another name (e.g. `s_session`), the session information will be displayed.

### Expected behavior

Displays session information at `http://localhost:3000/server` while signed in.

**Comment by balazsorban44** [comment]
Here is the fix: https://github.com/nextauthjs/next-auth-example/pull/75 but the PR author hasn't addressed the comment. https://github.com/nextauthjs/next-auth-example/pull/75#issuecomment-1327436038 feel free to open the PR against this repo. :+1:

**Comment by 7suyash7** [comment]
Hey, is this still open? I would like to work on this if possible @balazsorban44
