### ISSUE TITLE
How to restrict access to pages if there is no session?

### ISSUE THREAD

**Issue by eliezra236** [nextauthjs/next-auth#5897]
### Question 💬

Hi,

I am trying to implement Next Auth in my Nextjs application, login works fine but I have issues with vlidating that there is a session and render the page / redirect to Login page.

I tried doing validation with the `useSession` hook but it still often redirect to login page when there is session active but it take some time to load.
I put in inside my MainLayout that is being used in all the pages.

Is there a better way to do that?

### How to reproduce ☕️

```js
const router = useRouter();
const {data: session, status} = useSession();

    if (
        !session
        && status !== 'loading'
        && router.pathname !== '/login'
    ) {
        void router.push('/login');
        return null;
    }
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by Eduard-Hasa** [comment]
If you use jwt token method you can use middleware.

**Comment by balazsorban44** [comment]
There are various ways, Middleware is probably the easiest, as suggested above. See https://next-auth.js.org/configuration/nextjs#middleware
