### ISSUE TITLE
Cloudflare D1 database adapter

### ISSUE THREAD

**Issue by mackenly** [nextauthjs/next-auth#5918]
### Description 📓

I'd like to add Cloudflare's D1 database service as a DB adapter.

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by mackenly** [comment]
I'll open a PR from here once I get some progress made: https://github.com/mackenly/next-auth

**Comment by mackenly** [comment]
I'm probably missing something, but would there be any reason that all the adapters using the ```next-auth/adapters``` types module would be unable to find the module? I'm pretty much right out of the box after forking and running the pnpm install script.

**Comment by ThangHuuVu** [comment]
@mackenly what issue are you running to?

**Comment by mackenly** [comment]
> @mackenly what issue are you running to?

To eliminate any issues on my local system, I opened it up in a codespace and am having the same issue. After following the "Setting up local environment" steps in the contributing doc, when I try to open any of the existing adapter packages, their index.ts files can't find the adapters from next-auth/adapters.

I'm not super experienced in typescript; however, I feel like this probably isn't the expected behavior. Do the same things happen to you or am I doing something wrong? Thank you!

<details>
<summary>
Open for screenshots
</summary>
In this codespace all I've done is clone/open it, run ```corepack enable pnpm```, ```pnpm --version```, and ```pnpm install```. 

This screenshot is from the index.ts in the adapter-firebase package.

![image](https://user-images.githubusercontent.com/53151058/205188097-0421edcb-36ea-49f1-a99e-f9cd8a788d9a.png)

The same issue is present in that package's test. It's not finding next-auth. 
![image](https://user-images.githubusercontent.com/53151058/205189275-86099eb4-b759-4d3a-b2cc-9c887754c181.png)

This error is thrown when I tried to run pnpm install in the adapter-firebase directory.
```
@mackenly ➜ /workspaces/next-auth/packages/adapter-firebase (main ✗) $ pnpm install
Scope: all 20 workspace projects
 ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE  In : No matching version found for @next-auth@* inside the workspace
```
</details>

**Comment by jokester** [comment]
Hello @mackenly 

Running `pnpm run build` in the repo root should fix the "Cannot find module" error. 

Explanation: when everything goes right the import in adapter-firebase would be from `REPO_ROOT/packages/adapter-firebase/node_modules/next-auth/adapters.d.ts`, which (via symlink) goes to `REPO_ROOT/packages/next-auth/adapters.d.ts`, which is created by the `build` script.

------

I couldn't reproduce the ` ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE ` error but I'm guessing we don't need to `pnpm install` in `packages/adapter-firebase`. In a monorepo, `pnpm install` in repo root should be enough.

Hope it helps 👍

**Comment by jschlesser** [comment]
I opened a PR, the adapter works.  It passes the adapter-test test suite, it works in a demo site I built locally based on the sveltekit framework dev app and I was able to deploy it to a cloudflare pages site.

There are 2 things that need resolving.
1.  Docs.  Should they be for next-auth or authjs?   If I could model the docs on an existing adapter is there one that is an ideal model?
2. The tests use @miniflare/d1 as a mock for the d1 database.  There is a bug in the currently published npm package.  They merged a fix I made for it but haven't published it yet.  Currently this PR is referencing a 'fixed' version (their current main branch) but on my personal npm scope @jschlesser.   That's not ideal, but I'm not sure when they will publish it. We can go forward like this and change to the @miniflare scope when they publish or we can use patch-package or we can just put this on hold till they publish.

It would be great to get some feedback on using it from someone else like the OP @mackenly.
You can test the current code by cloning this [project](https://github.com/jschlesser/authjs-sveltkit-cloudflare-pages)

**Comment by mackenly** [comment]
Awesome, @jschlesser! Will definitely test and follow up with any feedback.

**Comment by jschlesser** [comment]
Good news, the miniflare maintainer finally published the fix to NPM today.  I can fix #2 of the issues that need resolving ☝️ .  I'll get to that this week. For #1,  I'm going to move forward on the docs too vs waiting for a response from a maintainer.  Im going to assume that the docs should be for next-auth for now.

**Comment by rozenmd** [comment]
Hey @jschlesser / @mackenly, 

I'm a Systems Engineer on the D1 team, this looks awesome! I'll add it to https://developers.cloudflare.com/d1/platform/community-projects/ once it gets merged

**Comment by jschlesser** [comment]
@rozenmd , sounds good!

**Comment by markdembo** [comment]
Hey! I am a Solutions Architect from Cloudflare (and love to code in my free time). Would love to see D1 support. Is there anything I/we from the Cloudflare side can do to support?

**Comment by ThangHuuVu** [comment]
@markdembo @jschlesser I've just left some review comments in the PR, we can continue our discussion there!

**Comment by mackenly** [comment]
#6953 was merged earlier in the month, adding D1 as an adapter. Thank you to all the contributors! Closing this issue.

See D1 adapter docs at: https://authjs.dev/reference/adapter/d1

**Comment by jschlesser** [comment]
Thank you everyone!On Sep 28, 2023, at 6:30 PM, Mackenly Jones ***@***.***> wrote:﻿
#6953 was merged earlier in the month, adding D1 as an adapter. Thank you to all the contributors! Closing this issue.
See D1 adapter docs at: https://authjs.dev/reference/adapter/d1
