### ISSUE TITLE
Possibly to pass custom param to NextAuth config to received it after signIn in function params

### ISSUE THREAD

**Issue by prinq** [nextauthjs/next-auth#5921]
### Question 💬

Hello. I would like to create something like "referral system" using Google Provider (oauth).

I am trying to pass parameter by query to Next auth config without result. When someone are login with parameter in url i would receive it on signIn callback

I'm trying to pass it in callbackUrl, as a Autorization -> params -> state in config but without any reason 

Version -> v4

### How to reproduce ☕️

Here is my current code

// Url when i want to signIn
`http://host:1111/?code=123456`

// Login logic
`signIn("google")`

// [...nextauth].js
```
import NextAuth from "next-auth";
import GoogleProvider from "next-auth/providers/google";

export const authOptions = {
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_SECRET,
    }),
  ],
  secret: "secret-pass",
  callbacks: {
    async signIn({ user }) {
      // HERE I WANT TO received this param.

      return true;
    },
  },
};

export default NextAuth(authOptions);

```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by prinq** [comment]
I

**Comment by prinq** [comment]
I using cookie to store grab this value, but I am not sure that is the best solution.

**Comment by jaekunchoi** [comment]
> I using cookie to store grab this value, but I am not sure that is the best solution.

can u give some code example?
