### ISSUE TITLE
unstable_getServerSession setup in Next13

### ISSUE THREAD

**Issue by Alek07** [nextauthjs/next-auth#5923]
### Question 💬

Hi, I'm working with Nextjs 13 app directory to try the new features and decide to implement `unstable_getServerSession` inside a Server Component. However, when I log my current session it doesn't show all the properties I set up inside the session callback in my NextAuth config.

this is what I log from the unstable_getServerSession
![image](https://user-images.githubusercontent.com/35198616/204684560-c3336f58-6f10-4ce0-8218-747cc4fa3664.png)

this is what I log from my session callback 
![image](https://user-images.githubusercontent.com/35198616/204684681-ea348a5a-e941-499f-9810-28941ec1dc64.png)

I'm missing the access and refresh token properties which I need.

here is also my NextAuth config
```typescript
export default NextAuth({
    providers: [
        SpotifyProvider({
            authorization: `https://accounts.spotify.com/authorize?${queryParams.toString()}`,
            clientId: process.env.SPOTIFY_CLIENT_ID,
            clientSecret: process.env.SPOTIFY_CLIENT_SECRET,
        }),
    ],
    secret: process.env.NEXTAUTH_SECRET,
    callbacks: {
        async jwt({ token, account, user }) {
            if (account && user) {
                return {
                    ...token,
                    accessToken: account.access_token,
                    refreshToken: account.refresh_token,
                    userName: account.providerAccountId,
                    accessTokenExpires: account.expires_at * 1000
                }
            }

            if (Date.now() < token.accessTokenExpires) {
                return token
            }

            return await refreshAccessToken(token)
        },
        async session({ session, token }) {
            session.user.accessToken = token.accessToken
            session.user.refreshToken = token.refreshToken
            return session
        },
    },
});
```

I'm new working with Next Auth so idk if I need to do some additional setup in order to use the `unstable_getServerSession` properly

### How to reproduce ☕️

I'm using the Spotify provider, but pretty much I'm just calling the unstable_getServerSession in a basic `page.tsx` Server Component.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by AugusteQuimper** [comment]
Hello, new to the framework as well, but found this sample app provided, may help you figure it out;
https://github.com/nextauthjs/next-auth-refresh-token-example

**Comment by rxflame** [comment]
You need to pass your authOptions into unstable_getServerSession for the callbacks to work properly

`const session = await unstable_getServerSession(authOptions)`

**Comment by cravend** [comment]
The documentation needs to be update for the app directory: https://next-auth.js.org/configuration/nextjs#in-app-directory

It doesn't say to pass in `authOptions`, but I had the same issue and passing them in fixed it.

**Comment by Alek07** [comment]
I try it and it works, thanks, guys. They definitely need to update the documentation so it can be more clear on how to use it inside the app directory.

**Comment by cravend** [comment]
Yeah, I submitted a PR to update the documentation :) it’s waiting on review now!
