### ISSUE TITLE
What am I suppose to do If user email exist on db that coming from provider? How to handle error?

### ISSUE THREAD

**Issue by violetbee** [nextauthjs/next-auth#5926]
### What is the improvement or update you wish to see?

I couldn't find any information about handling errors when user email (signed up with credentials) and provider email matches. How do I handle like "There is a user that you are providing from Discord" etc.

### Is there any context that might help us understand?

There is not

**Comment by violetbee** [comment]
Any solution?

**Comment by noclat** [comment]
Answer in the FAQ: https://next-auth.js.org/faq#security

**Comment by violetbee** [comment]
@noclat thank you for answer. I want to put a callback error like "This account has been created in another provider" when user signed up wtih credentials and then tried to sign in with oauth provider.

**Comment by noclat** [comment]
You should receive the error code `OAuthAccountNotLinked` as a query parameter after the redirect (or as the error parameter of the `signIn` promise if you've used `redirect: false`). Check https://next-auth.js.org/configuration/pages#sign-in-page for the error codes. These should help you display a specific message for each specific case :).

**Comment by thomasmost** [comment]
Hey, since this is related to a question I have, I'm jumping on the existing thread. I'm getting this error (the `OAuthAccountNotLinked` error) but in the FAQ, it says:

> If the user first signs in using Email and then tries to sign in again using an OAuth provider, NextAuth.js default behavior is to allow account linking even if the OAuth account's email address does not match the previous email address of the user.

My app has, up to this point, only supported magic links. So emails are confirmed. Based on this addendum to the FAQ, I'd expect a matching Google Oauth authentication to auto-link, but I'm getting the `OAuthAccountNotLinked` error instead...

What am I misunderstanding?

Thanks in advance

**Comment by noclat** [comment]
Your user has to log in first, and only then, you can call `signIn('google')` to link the account. If you're using JWT, account linking relies on the `token.sub` property. Also, make sure you're calling `signIn('google')` from a page/component wrapped in a `<SessionProvider>`.

**Comment by thomasmost** [comment]
oh, amazing! No, I totally missed that nuance—thank you!

**Comment by kibria-shaped** [comment]
@KevinKra Thanks for the solution. Is there any way to to know existing email belongs to which provider? eg. Google, Github etc.

**Comment by ergors** [comment]
@KevinKra Thanks, very useful
