### ISSUE TITLE
Pass context to create session to track the user agent

### ISSUE THREAD

**Issue by wenerme** [nextauthjs/next-auth#5939]
### Description 📓

When listing session to user, I'd like to tell the user more about the session, like userAgent, ip address, this requires pass context down to createSession and updateSession

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
You can do this via https://next-auth.js.org/configuration/initialization#advanced-initialization
