### ISSUE TITLE
Session Cookie with knex.js

### ISSUE THREAD

**Issue by codelover2k** [nextauthjs/next-auth#595]
I am trying to switch to Next.js and before that I used Express.

For authentication I used **express-session** and **connect-session-knex**.
The great thing about **connect-session-knex** is that it creates the data table for you and if something changes or if you delete that table, it just creates a fresh one for you.

Furthermore it automatically deletes sessions from the database if they are not valid anymore, so you can set the time how many times the database should be checked for dead sessions.
In my case these modules check the database every 60 minutes and deletes sessions to keep the table small and fast as possible.

I would like to know if you have these features also in next-auth?

- Will the required data table be created automatically and also updated if needed? (for example if a new version is there)

- can you also use knex.js? (if yes an example would be nice)

- does it also check the database and clean dead sessions if it find any?

Would be great if someone could help me with that :)

**Comment by iaincollins** [comment]
> * Will the required data table be created automatically and also updated if needed? (for example if a new version is there)

[If the `synchronize` option is set to true in the database options](https://next-auth.js.org/configuration/databases#setting-up-a-database) NextAuth.js will automatically create or update any tables needed (this is handled by TypeORM), however enabling this option is not currently recommended in production as it does not actually perform a migration and could lead to data loss between releases.

The `synchronize` option is intended to make it easier to get started, but SQL schema changes need to be handled manually currently - with this in mind, we generally avoid making changes to the schema (until we have improved support for handling migrations). There are some changes I would like to make that require an SQL schema change, but I'm currently not focusing on them for that reason. I anticipate we will have migration support at some point, for either TypeORM, Prisma or both.

Note: We also maintain SQL schemas (e.g. [MySQL schema](https://next-auth.js.org/schemas/mssql), [Postgres schema](https://next-auth.js.org/schemas/postgres)) for the current version.

> * can you also use knex.js? (if yes an example would be nice)

NextAuth.js ships with adapters that use [TypeORM](https://github.com/typeorm/typeorm) and [Prisma](https://www.prisma.io) and supports MySQL, Postgres, Microsoft SQL Server, MongoDB (and other databases compatible with them). To use another database or ORM you can create a [custom adapter](https://next-auth.js.org/tutorials/creating-a-database-adapter).

You can also pass a database connection string to NextAuth.js and let it handle it's own connection without worrying about it, and connect to the database from your own application using whatever method you want.

> * does it also check the database and clean dead sessions if it find any?

Not currently. I expect this will be something we will add to the default database adapter fairly soon.
