### ISSUE TITLE
Adding fields to Credentials

### ISSUE THREAD

**Issue by sudo-sand** [nextauthjs/next-auth#5971]
### Question 💬

I want to add fields to data object in credentials.

Currently this the data object
```json
{
  "user": {
    "email": "user1@example.com"
  },
  "expires": "2023-01-05T11:32:14.149Z"
}
```

I want to add `role` and `status` fields when I do `fetch` (They already come from the API)

### How to reproduce ☕️

n/a

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
https://next-auth.js.org/getting-started/example#extensibility
