### ISSUE TITLE
4.18.1 causes app to render in a <pre> tag when using `unstable_getServerSession`

### ISSUE THREAD

**Issue by EvHaus** [nextauthjs/next-auth#5986]
### Environment

  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 25.39 GB / 31.32 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 17.8.0 - ~/.nvm/versions/node/v17.8.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v17.8.0/bin/npm
  npmPackages:
    next: 13.0.6 => 13.0.6
    next-auth: 4.18.1 => 4.18.1
    react: 18.2.0 => 18.2.0

### Reproduction URL

https://stackblitz.com/edit/github-61ga3k-prdgby?file=pages%2Fserver.tsx

### Describe the issue

After upgrading from 4.18.0 to 4.18.1 I'm seeing a very strange issue where my app no longer renders. Instead, Next renders the HTML of my app in a `<pre>` tag, so it looks like this:

![image](https://user-images.githubusercontent.com/226640/206368050-04f0dade-b995-4b96-bd9a-ede33300f73e.png)

What I've determined so far:

- 4.18.0 doesn't have this bug
- 4.18.1 and 4.18.3 have this bug
- The issue only happens when using `unstable_getServerSession`
- The issue only happens when you have logged in and have a session defined

### How to reproduce

Check out the Stackblitz link I created. The issue is somewhat reproducible there. The "server" page there has a `unstable_getServerSession` used in `getServerSideProps`.

To reproduce the bug:

- Run that Stackblitz example
- Go to the "Server" page in the UI
- Click on "Sign in" and try to sign in to one of the providers (doesn't mattern if you complete this or not)
- Press the browser Back button to go back to the app
- BUG: The UI no longer renders. Instead you get a `<pre>` tag with all the code of your app

### Expected behavior

Bug doesn't happen. Next Auth should render the app as normal.

**Comment by balazsorban44** [comment]
I have an experimental release you can test out! `pnpm add next-auth@0.0.0-pr.5991.5c72424c`

**Comment by balazsorban44** [comment]
A fix should be out for this in `4.18.4`.

**Comment by EvHaus** [comment]
Confirmed 4.18.4 fixes the issue! Thanks for the fast fix. I found a new, different bug with 4.18.x though. Will open a new ticket shortly.
