### ISSUE TITLE
Set-Cookie header is split in half by comma in Expires section

### ISSUE THREAD

**Issue by pekarja5** [nextauthjs/next-auth#5989]
### Environment

System:
    OS: Linux 6.0 Arch Linux
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 10.86 GB / 31.10 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chromium: 108.0.5359.94
    Firefox: 107.0.1
  npmPackages:
    next: 13.0.6 => 13.0.6 
    next-auth: 4.18.3 => 4.18.3 
    react: 18.2.0 => 18.2.0

### Intŕoduced by

https://github.com/nextauthjs/next-auth/commit/7e91d7df54f9d8ca782c93a63f583ce89c2d178d#r92403804

### Describe the issue

`set-cookie` header is split in Expires section containing comma resulting in incomplete cookie being rejected

![image](https://user-images.githubusercontent.com/11211597/206426961-0ee6f304-c9a2-4849-886a-cb0f1d19bb84.png)

### How to reproduce

call client `signIn` method

### Expected behavior

`set-cookie` header is not split in half in Expires section of the cookie

**Comment by guswls1846** [comment]
next-auth version rollback 4.18.0

**Comment by balazsorban44** [comment]
Thanks, I identified the issue. it's related to https://github.com/whatwg/fetch/issues/973 Working on a fix, and will release a patch for this today.

**Comment by balazsorban44** [comment]
I have an experimental release you can test out! `pnpm add next-auth@0.0.0-pr.5991.5c72424c`

**Comment by balazsorban44** [comment]
A fix should be out for this in `4.18.4`.

**Comment by pekarja5** [comment]
Seems to be working. 
Thanks
