### ISSUE TITLE
OAuth Error: Database Contains Users but Error "OAuthAccountNotLinked" on creating new user accounts

### ISSUE THREAD

**Issue by Slap-a-tha-Bass** [nextauthjs/next-auth#6017]
### Environment

  System:
    OS: macOS 13.0
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 800.90 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /usr/local/bin/node
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Safari: 16.1
  npmPackages:
    next: 13.0.2 => 13.0.2 
    next-auth: 4.17.0 => 4.17.0 
    react: 18.2.0 => 18.2.0 

### Reproduction URL

https://whispurr.vercel.app

### Describe the issue

Using the t3 stack, which comes preconfigured with next-auth. 

I have connected a planetscale database to the project. The **User** table contains the accounts that have attempted to sign in to the page. But on submission of the "Authorize" button on the login screen, the below error popups up:

/api/auth/error?error=OAuthAccountNotLinked

<img width="417" alt="Screenshot 2022-12-10 at 11 24 16 AM" src="https://user-images.githubusercontent.com/65183264/206867438-cd77a104-368f-4f9b-9f09-7975ab632ec4.png">

See below _prisma.schema_ and associated files with the login / logout flow:

```
model Account {
  id                String  @id @default(cuid())
  userId            String
  type              String
  provider          String
  providerAccountId String
  refresh_token     String? // @db.Text
  access_token      String? // @db.Text
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String? // @db.Text
  session_state     String?
  user              User    @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
  @@index([userId])
}
```
```
model User {
  id            String    @id @default(cuid())
  name          String?
  email         String?   @unique
  emailVerified DateTime?
  image         String?
  accounts      Account[]
  sessions      Session[]
  messages      Message[]
  likes         Like[]
}
```
/pages/api/[...nextauth].ts
```import DiscordProvider from "next-auth/providers/discord";
import GoogleProvider from "next-auth/providers/google";
// Prisma adapter for NextAuth, optional and can be removed
import { PrismaAdapter } from "@next-auth/prisma-adapter";
import NextAuth, { type NextAuthOptions } from "next-auth";

import { env } from "../../../env/server.mjs";
import { prisma } from "../../../server/db/client";

export const authOptions: NextAuthOptions = {
  // Include user.id on session
  callbacks: {
    session({ session, user }) {
      if (session.user) {
        session.user.id = user.id;
      }
      return session;
    },
  },
  // Configure one or more authentication providers
  adapter: PrismaAdapter(prisma),
  providers: [
    GoogleProvider({
      clientId: env.GOOGLE_CLIENT_ID,
      clientSecret: env.GOOGLE_CLIENT_SECRET,
    }),
    DiscordProvider({
      clientId: env.DISCORD_CLIENT_ID,
      clientSecret: env.DISCORD_CLIENT_SECRET,
    }),
  ],
  secret: env.JWT_SECRET,
};

export default NextAuth(authOptions);
```

### How to reproduce

Locally, this issue is not reproducible.

For some reason, only in production.

Create a new t3 app
[https://create.t3.gg/en/installation](url)
```
npm create t3-app@latest
```
Create a planetscale db 
[https://planetscale.com/](url)

Make changes to prisma.schema 
```
generator client {
  provider = "prisma-client-js"
}
datasource db {
  provider = "mysql"
  url = env("DATABASE_URL")
  relationMode = "prisma"
}
```
Link up database via URL in "prisma" option
<img width="528" alt="Screenshot 2022-12-10 at 11 47 54 AM" src="https://user-images.githubusercontent.com/65183264/206868412-ea1824d2-6259-400c-9cc6-423c2a1fc106.png">

Save URL as a .env var
```
DATABASE_URL=db-connection-string-from-above
```
Push up prisma changes to the database
```
npx prisma db push
```

Setup basic login / logout page using _next-auth_

Configure OAuth settings in Google and Discord (can link to both if necessary)

Insert Client_IDS and Client_SECRETS from both Google and Discord as env vars

Push to Vercel for production && don't forget env vars

### Expected behavior

I would expect multiple users to be stored in the database (which currently works).

I also expect the user to become logged in (which only works locally).

### Important
Currently in production, the only user that can be logged in properly is the first user I logged in with on my device (using the Discord provider)
It is as if that user is only user allowed to have an active session?

I hope all of this info is useful and I will be more than happy to provide more information, if needed.

**Comment by balazsorban44** [comment]
> Currently in production, the only user that can be logged in properly is the first user I logged in with on my device (using the Discord provider)

This is the key. It's unclear from the reproduction steps, but when you log in with a user via Discord, a few things happen.

You create a user in your NextAuth.js app and also create a session for your user in that app (via NextAuth.js) and one for Discord.

Say you now want to log in with a different user. If your NextAuth.js session is still active, and try to log in with a new Discord user, it will fail because NextAuth.js is detecting that you already have an active session with a different Discord account, and will ask you to use that instead.

You need to make sure that you are not logged in with the previous Discord account before logging in via the new one in your app.
