### ISSUE TITLE
calling signOut function doesn't force page reload

### ISSUE THREAD

**Issue by Kozie1337** [nextauthjs/next-auth#603]
**Describe the bug**
Calling the signOut function from the [nextauth Client API](https://next-auth.js.org/getting-started/client#signout) doesn't force a page-reload which makes it look like the user's still signed in.

**Steps to reproduce**
1. Sign in on https://next-auth-example.now.sh/ (with Google)
2. Press 'Sign out' 

**Expected behavior**
Page reloads after clicking 'Sign out' (calling signOut function)

as the Client AP states:
> [...] It reloads the page in the browser when complete.

* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by PaulKushch** [comment]
I got the same issue, what helped me is to remove e.preventDefault() from onClick handlers (commented out below):

`                onClick={() => {
                  // e.preventDefault();
                  signIn();
                }`

**Comment by SharadKumar** [comment]
#532 this is a duplicate, I suppose.

**Comment by Kozie1337** [comment]
I added `e.preventDefault(); ` to the onClick function and it still didn't work.

Then I noticed that I was getting the error from #552 during production.  

Adding
  `"peerOptionalDependencies": {
  "mongodb": "^3.6.0"
},`
to my package.json fixed both errors.

Everything seems to be working now.

**Comment by samuelgoldenbaum** [comment]
This should not be closed as the issue still persists in Google and Facebook providers as per #532
