### ISSUE TITLE
releasing packages should respect the dependency graph

### ISSUE THREAD

**Issue by pjlast** [nextauthjs/next-auth#6068]
### Environment

```
  System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 12.55 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.0.0 - ~/.asdf/installs/nodejs/19.0.0/bin/node
    npm: 8.19.2 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 108.0.5359.98
    Firefox: 107.0
    Safari: 16.0
  npmPackages:
    @auth/core: latest => 0.1.4
    @auth/sveltekit: latest => 0.1.5
```

### Reproduction URL

https://github.com/nextauthjs/sveltekit-auth-example

### Describe the issue

The `@auth/sveltekit` package version 0.1.5 on npm is using the wrong `@auth/core` version. When trying to work with any project using this package, you'll receive a `Cannot read properties of undefined (reading 'AuthHandler')` error.

To confirm the issue, go to the npm registry and check the files of the `@auth/sveltekit` package: https://www.npmjs.com/package/@auth/sveltekit?activeTab=explore 

On line 36 you'll see the `@auth/core` version is 0.1.3 instead of 0.1.4.

Changing the version to 0.1.4 in my `node_modules` folder and updating the dependencies fixed the issue in my local environment.

### How to reproduce

1. Clone the repository at https://github.com/nextauthjs/sveltekit-auth-example
2. Run `npm install`
3. Run `npm run dev`
4. Click on Sign in

You will be met with a `Cannot read properties of undefined (reading 'AuthHandler')` error.

### Expected behavior

Be redirected to the auth provider.

**Comment by KoljaL** [comment]
i got this after cloning the [sveltekit-auth-example](https://github.com/nextauthjs/sveltekit-auth-example) & `pnpm i`

```
 WARN  Issues with peer dependencies found
.
└─┬ @auth/sveltekit 0.1.5
  └── ✕ missing peer svelte-kit@^1.0.0
Peer dependencies that should be installed:
  svelte-kit@^1.0.0
```

**Comment by pjlast** [comment]
@KoljaL yeah I guess that dependency should be `@sveltejs/kit` instead of `svelte-kit`, but I have not dug into that yet

**Comment by balazsorban44** [comment]
@KoljaL that's going to be fixed here: https://github.com/nextauthjs/next-auth/pull/6066

For the original issue, I'll need to figure out a way to publish packages respecting the dependency graph.

https://github.com/balazsorban44/monorepo-release currently is not aware.

**Comment by theetherGit** [comment]
@balazsorban44 is it possible to patch it as soon as possible? I understand the part monorepo and dependency graph for now if you can release a patch version it will be very helpful

**Comment by balazsorban44** [comment]
It's out!

**Comment by balazsorban44** [comment]
Help is appreciated if anyone wants to have a look: https://github.com/balazsorban44/monorepo-release/issues/6

**Comment by pjlast** [comment]
I submitted a PR in that linked issue, can keep discussion there 👍

**Comment by balazsorban44** [comment]
@pjlast Looks like your change worked!

Core was indeed released before SvelteKit Auth here:
https://www.npmjs.com/package/@auth/sveltekit?activeTab=explore
https://www.npmjs.com/package/@auth/core?activeTab=explore
