### ISSUE TITLE
@auth/sveltekit: PrismaAdapter causing callback errors

### ISSUE THREAD

**Issue by v-erse** [nextauthjs/next-auth#6076]
### Adapter type

@next-auth/prisma-adapter

### Environment

  System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M2
    Memory: 239.27 MB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.0.0 - ~/.nvm/versions/node/v19.0.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v19.0.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0.1
    Safari: 16.1

  npmPackages:
    @auth/core: ^0.1.4 => 0.1.4 
    @auth/sveltekit: ^0.1.6 => 0.1.6 
    @next-auth/prisma-adapter: ^1.0.5 => 1.0.5 

### Reproduction URL

https://github.com/v-erse/authjs-sveltekit

### Describe the issue

After introducing `PrismaAdapter`, I'm getting `CALLBACK_EMAIL_ERROR` and `OAUTH_CALLBACK_ERROR` errors when attempting to authenticate with SvelteKit

The error message is `Value of "this" must be of type Crypto`

@balazsorban44 suggested switching to `adapter-node`, but this doesn't seem to fix it

### How to reproduce

- clone into https://github.com/v-erse/authjs-sveltekit
- run `yarn` and then `yarn dev`
- add env variables for GitHub auth and a database url for Prisma
- auth should fail with a callback error

If you comment out the PrismaAdapter line in `hooks.server.ts`, auth should succeed

### Expected behavior

No callback errors when using PrismaAdapter

**Comment by LasarKolja** [comment]
same here: #https://github.com/nextauthjs/next-auth/discussions/6074 :-(

**Comment by oofdere** [comment]
Fixed this issue by doing the following:

1. This might not be necessary, but I copied `@next-auth/prisma-adapter`'s [`index.ts`](https://github.com/nextauthjs/next-auth/blob/main/packages/adapter-prisma/src/index.ts) to `$lib/server/PrismaAdapter`, and changed the import to use `@auth/core`.
```diff
-import type { Adapter, AdapterAccount } from "next-auth/adapters"
+import type { Adapter, AdapterAccount } from "@auth/core/adapters"
```
2. Generate the session token manually.
```ts diff
import prisma from "$lib/server/prisma";
import { PrismaAdapter } from "$lib/server/PrismaAdapter";

export const handle = SvelteKitAuth({
    adapter: PrismaAdapter(prisma),
    session: {
        strategy: "database",
        generateSessionToken: () => { 
            return crypto.randomUUID();
        }
    },
    // whatever other fields you're using
})
```

UUID generation seems to be the main issue, no idea what's breaking it but moving it here seems to work fine.

**Comment by LasarKolja** [comment]
Thanks a lot, I got it working :-)

But I had to change the import of the prisma-client

```
-import prisma from "$lib/server/prisma";
+import { PrismaClient } from "@prisma/client"
+const prisma = new PrismaClient()
```

**Comment by sharmapukar217** [comment]
> Thanks a lot, I got it working :-)
> 
> But I had to change the import of the prisma-client
> 
> ```
> -import prisma from "$lib/server/prisma";
> +import { PrismaClient } from "@prisma/client"
> +const prisma = new PrismaClient()
> ```
> 
> edit: how are you highlighting the lines with `+` and `-`?

Use backticks diff instead of plain backticks
i.e: 
```diff
```diff
++
--
```

**Comment by oofdere** [comment]
> Thanks a lot, I got it working :-)
> 
> But I had to change the import of the prisma-client
> 
> ```
> -import prisma from "$lib/server/prisma";
> +import { PrismaClient } from "@prisma/client"
> +const prisma = new PrismaClient()
> ```

Ah yeah I just set up the `PrismaClient` globally in `$lib/server/prisma` and import from there, forgot to mention it:

```ts
// src/lib/server/prisma.ts
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

export default prisma;
```
