### ISSUE TITLE
TS: PrismaAdapter does not accept prisma client that has client extensions

### ISSUE THREAD

**Issue by kennykingdev** [nextauthjs/next-auth#6078]
### Question 💬

When using the new prisma client extensions that they introduced in 4.7.0, the type of the prisma client changes with whatever extensions you apply.

If you try to pass your extended prisma client into PrismaAdapter, TS complains about the types not matching what it expects.

For now I have both a standard prisma client and an extended client.  I pass the standard client into PrismaAdapter and use the extended client where needed in callbacks and events.

I would prefer that PrismaAdapter accept an extended client so that I don't have import and use both clients in [...nextAuth].ts

### How to reproduce ☕️

```
const prisma = new PrismaClient().$extends({
  name: 'fullName',
  result: {
    user: {
      fullName: {
        needs: { firstName: true, lastName: true },
        compute(user) {
          return `${user.firstName} ${user.lastName}`;
        },
      },
    },
  },
});

export const authOptions: NextAuthOptions = {
  adapter: PrismaAdapter(prisma),
  providers: [
    GoogleProvider({
      clientId: 'GOOGLE_CLIENT_ID',
      clientSecret: 'GOOGLE_CLIENT_SECRET',
    }),
  ],
};
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Technically you should not be using v4 yet: https://github.com/nextauthjs/next-auth/blob/1e6daa8304aa98858f8e27eef092fbeb2f34f436/packages/adapter-prisma/package.json#L40

Happy to add support though, so is this just a TS issue? :thinking:

**Comment by kennykingdev** [comment]
Yes.

**Comment by tacomanator** [comment]
Temporary work around until supported:
```ts
import { PrismaClient } from "@prisma/client";
export const authOptions: NextAuthOptions = {
  adapter: PrismaAdapter(prisma as unknown as PrismaClient),
  ...
}
```

If necessary could replace `PrismaClient` with a type extracted from your extended client, as described in [this article](https://echobind.com/post/extending-types-for-prisma-extensions-in-nextjs).

**Comment by benjamin-guibert** [comment]
Any update on this?

**Comment by alvesvaren** [comment]
This is still an issue I think in the latest version of the adapter

**Comment by ImamAlfariziSyahputra** [comment]
still facing an error using prisma.$extends. can you help why this is happen? @balazsorban44 , thank you.
<img width="315" alt="image" src="https://github.com/nextauthjs/next-auth/assets/63343105/73757535-b62c-44c9-b181-9d7cb9e17e71">

here is my code:
<img width="402" alt="image" src="https://github.com/nextauthjs/next-auth/assets/63343105/e293b139-cb36-4f61-9fef-cf7819d85eb8">

all of this working fine, if i'm not using prisma extension.

**Comment by zhanlarr-ww** [comment]
Fixed by https://github.com/nextauthjs/next-auth/pull/9798 it seems, for others who arrive here
