### ISSUE TITLE
sveltekit auth how do you auth with an external backend?

### ISSUE THREAD

**Issue by Nisthar** [nextauthjs/next-auth#6086]
### Question 💬

So i am using directus cms. It is similar to supabase and others. I will explain how these cms works. Backends like supabase, directus handles the server side authentication themselves. They generate the jwt tokens and return it to the client via cookie or json. The client only needs to store the same tokens in both server side (via hooks) and client side. And refresh it whenever its expired. 

Is it possible to do this with sveltekit auth library?

https://docs.directus.io/reference/authentication.html 

### How to reproduce ☕️

no code needed

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
You can use the Credentials provider for this case, as it seems to be a non-comformant OAuth flow.

https://next-auth.js.org/providers/credentials#example---username--password

**Comment by Nisthar** [comment]
> You can use the Credentials provider for this case, as it seems to be a non-comformant OAuth flow.
> 
> https://next-auth.js.org/providers/credentials#example---username--password

does it keep track of the tokens in both server and client side?

**Comment by Nisthar** [comment]
can i make authenticated requests from the client and the server?

**Comment by Nisthar** [comment]
@balazsorban44 How does it work? what do you provide if you are using a oauth provider?
