### ISSUE TITLE
auth/signin?error=Callback @vercel, working on localhost

### ISSUE THREAD

**Issue by KoljaL** [nextauthjs/next-auth#6094]
### Provider type

GitHub

### Environment

I'm working on a MacOS with VSCode, Node18, SvelteKit 1.0, AuthJS 0.1.4.

Repo: https://github.com/KoljaL/SK-AuthJS

Vercel: https://sveltekit-authjs-prisma.vercel.app

### Reproduction URL

https://sveltekit-authjs-prisma.vercel.app

### Describe the issue

If you try to authenticate on the deployed version, you will be redirected to this URL:

`https://sveltekit-authjs-prisma.vercel.app/auth/signin?error=Callback`

### How to reproduce

Try to authenticate here: https://sveltekit-authjs-prisma.vercel.app

### Expected behavior

No Error ;-)

It works on localhost (with different GH OAuth credentials), so why not on vercel?

**Comment by balazsorban44** [comment]
what does your logs show?

**Comment by balazsorban44** [comment]
Might be related https://github.com/nextauthjs/next-auth/issues/6076

**Comment by KoljaL** [comment]
> Might be related #6076

Yes and no, after generating the session token manually it works on localhost

I did not know about the realtime logs on vercel, great :-)

This is the first line:
` the database: unable to open database file: /var/task/vercel/path0/node_modules/.pnpm/@prisma+client@4.7.1_prisma@4.7.1/node_modules/.prisma/client/./dev.db\n' +`

But now it is not an AuthJS issue anymore.
