### ISSUE TITLE
JSON.stringify of custom adapter to generate secret

### ISSUE THREAD

**Issue by BANOnotIT** [nextauthjs/next-auth#6095]
### Environment

  System:
    OS: Linux 5.4 Ubuntu 18.04.6 LTS (Bionic Beaver)
    Container: Yes
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm

### Reproduction URL

https://github.com/BANOnotIT/next-secret-error-reproduction

### Describe the issue

In development if you pass non serializable adapter and provide no secret it'll try to generate secret by stringifiyng options and fail.

### How to reproduce

Pass complex adapter to options and provide no secret

### Expected behavior

It should not use adapter as a source for random secret

**Comment by balazsorban44** [comment]
This is currently the expected behavior and documented here https://next-auth.js.org/configuration/options#description-1

indeed it's very volatile, so we are making it mandatory in `@auth/core` going forward.

**Comment by BANOnotIT** [comment]
Documentation do not state that adapter is used also. And it's kinda strange that you try to hash functions content using json stringify, don't you think so?..

**Comment by BANOnotIT** [comment]
Might be better to just exclude adapter from entropy source?

**Comment by balazsorban44** [comment]
> Documentation do not state that adapter is used also

It does, here:

> If no value is specified in development (and there is no NEXTAUTH_SECRET variable either), it uses a hash for all configuration options, including OAuth Client ID / Secrets for entropy.

> Might be better to just exclude adapter from entropy source?

Yes, plus it causes confusion when publishing, people often forget setting `NEXTAUTH_SECRET`,  that's why we are making it mandatory everywhere as stated: https://github.com/nextauthjs/next-auth/issues/6095#issuecomment-1355774410

For now, just set `NEXTAUTH_SECRET` in dev too.
