### ISSUE TITLE
Locale support for Providers

### ISSUE THREAD

**Issue by nbouvrette** [nextauthjs/next-auth#6096]
### Description 📓

I saw several existing issues around i18n - this is not about this at all. I actually don't think `next-auth` should try to support localized strings because this is something the app can do (the way they want to). And as we can tell from Next.js 13, getting i18n right for everyone is probably better left to external libraries.

Having said this, some providers support the concept of `locale`, meaning if a user is browsing your site in a specific locale, it would make sense that the provider continues in the same locale. Google Oauth is [one example](https://stackoverflow.com/questions/24474493/change-language-for-google-authentication-request-oauth-2-0) that can use a parameter to specify the locale of their OAuth screen.

As far as I can tell, there is no way to pass this context to the provider, and even to handle the [pages](https://next-auth.js.org/configuration/pages) in the correct locale, the only way to do this is using the [advance initialization](https://next-auth.js.org/configuration/initialization#advanced-initialization).

### How to reproduce ☕️

If you have a multilingual site using `next-auth`, the following problems can occur:

- the provider's screen is in a different locale than the one you were in before doing the authentication
- there is no easy way to configure error handling to be pointed back to the correct localized page without using advanced initialization and extra parameters

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
You have multiple options

https://next-auth.js.org/getting-started/client#additional-parameters

https://next-auth.js.org/configuration/providers/oauth#authorization-option

**Comment by toggm** [comment]
@balazsorban44 And how should this work if within an application we support multiple languages and multiple providers expecting the locale information i.e. in a different query parameter? The next-auth config doesn't allow to lookup current requests locale when generating the authorization url.
