### ISSUE TITLE
Recommendation to use cuid instead of autonumber for Prisma adapter schema ID columns

### ISSUE THREAD

**Issue by SharadKumar** [nextauthjs/next-auth#610]
**Summary of proposed feature**
Lets face it, there are some issues with using autoincrement/autonumber for Identifier columns. This is a well discussed topic, so I probably don't need to write a lot:
- https://blog.codinghorror.com/primary-keys-ids-versus-guids/
- https://github.com/ericelliott/cuid

**Purpose of proposed feature**
I recommend a refinement to use `cuid()` (not `guid`) for identifier columns. They are web/url/slug friendly. They serve the same purpose as autonumber 'Int' but better. 

**Detail about proposed feature**
Imagine showing int userId in url versus showing a lowercase slug-friendly CUID in url.

This is not something we can handle through adapter, since it is hard-wired with schema. String is more flexible than Int, for ID columns.

CUID are implemented at Prisma level and supported. Autoincrement is implemented at database level. It means, using autoincrement Int leaves less flexibility for next-auth consumers. This is significant.
- https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/data-model#defining-a-default-value
- https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/data-model#using-functions

**Potential problems**
Migration for existing users. Prisma `migrate`?

**Comment by iaincollins** [comment]
This has been asked about before, it is not something I'm are actively considering at the moment.

Using CUID and GUID's is also my preference in schemas personally, but they are not without performance and operational implications on some databases and having different default behaviour across databases and/or adapters adds to the complexity when it comes to support.

Using an integer in SQL is still the dominant convention people expect for an SQL schema, and is the simplest thing that still works everywhere. When using MongoDB schema uses Mongo Object ID as that's the convention there.

Most OAuth providers, Twitter, Facebook and Google all use integer values for user account IDs.



However, if you want to use a GUID or CUID you can absolutely do that with NextAuth.js.

We might introduce using a GUID as an option in future, but having different behaviour across databases and built-in adapters is something I try very hard to avoid as it's not sustainable to support in an open source project.

**Comment by iaincollins** [comment]
BTW, regarding another issue where you talked about developing a custom adapter - if you did want to do share a custom Prisma adapter that did this out of the box, I'd be more than happy to link to it (that's very much the intent of them, even if how to use them is not extensively documented right now).

The reason we are not considering changes like this right now is that we are at the limit of what we can currently support, at least until we can get make some headway on some outstanding issues, and there are things like relational mapping and database migration (and all the tests that go with that) that we really need to have in place first.

**Comment by SharadKumar** [comment]
Thanks for the clarification @iaincollins 
I understand your position.

The project that I am trying to lift up is making me think of these things, so I added the recommendation. Yes, I've gone to the custom adapter approach for now. (multi-tenant postgres)
