### ISSUE TITLE
prisma adapter types error

### ISSUE THREAD

**Issue by OrJDev** [nextauthjs/next-auth#6106]
### Adapter type

@next-auth/prisma-adapter

### Environment

  System:
    OS: Windows 10 10.0.19045
    Memory: 991.97 MB / 5.95 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.16.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.54)   
    Internet Explorer: 11.0.19041.1566

  npmPackages:
    @next-auth/prisma-adapter: ^1.0.5 => 1.0.5 

### Reproduction URL

https://github.com/OrJDev/nextauth-error-repro

### Describe the issue

```
Type 'Adapter<boolean>' is not assignable to type 'Adapter<boolean> | undefined'.
  Type 'DefaultAdapter' is not assignable to type 'Adapter<boolean> | undefined'.
    Type 'DefaultAdapter' is not assignable to type 'DefaultAdapter & { createVerificationToken: (verificationToken: VerificationToken) => Awaitable<VerificationToken | null | undefined>; useVerificationToken: (params: { ...; }) => Awaitable<...>; }'.
      Type 'import("c:/Users/\u05D0\u05D5\u05E8/Desktop/my-app/node_modules/next-auth/adapters").DefaultAdapter' is not assignable to type 'import("c:/Users/\u05D0\u05D5\u05E8/Desktop/my-app/node_modules/@auth/core/adapters").DefaultAdapter'.
        Types of property 'linkAccount' are incompatible.
          Type '(account: import("c:/Users/\u05D0\u05D5\u05E8/Desktop/my-app/node_modules/next-auth/adapters").AdapterAccount) => Promise<void> | import("c:/Users/\u05D0\u05D5\u05E8/Desktop/my-app/node_modules/next-auth/core/types").Awaitable<import("c:/Users/\u05D0\u05D5\u05E8/Desktop/my-app/node_modules/next-auth/adapters").Adapt...' is not assignable to type '(account: import("c:/Users/\u05D0\u05D5\u05E8/Desktop/my-app/node_modules/@auth/core/adapters").AdapterAccount) => Promise<void> | import("c:/Users/\u05D0\u05D5\u05E8/Desktop/my-app/node_modules/@auth/core/lib/types").Awaitable<import("c:/Users/\u05D0\u05D5\u05E8/Desktop/my-app/node_modules/@auth/core/adapters").Ada...'.
            Types of parameters 'account' and 'account' are incompatible.
              Type 'import("c:/Users/\u05D0\u05D5\u05E8/Desktop/my-app/node_modules/@auth/core/adapters").AdapterAccount' is not assignable to type 'import("c:/Users/\u05D0\u05D5\u05E8/Desktop/my-app/node_modules/next-auth/adapters").AdapterAccount'.
                Types of property 'type' are incompatible.
                  Type 'import("c:/Users/\u05D0\u05D5\u05E8/Desktop/my-app/node_modules/@auth/core/providers/index").ProviderType' is not assignable to type 'import("c:/Users/\u05D0\u05D5\u05E8/Desktop/my-app/node_modules/next-auth/providers/index").ProviderType'.
                    Type '"oidc"' is not assignable to type 'ProviderType'.ts(2322)
```

### How to reproduce

run 

```bash
npm create jd-app@latest
```

select prisma and nextauth
go to src/routes/api/auth/[...solidauth].ts
the error will be there

### Expected behavior

shouldn't throw any type errors with a normal prisma client (no extension)

**Comment by rgodha24** [comment]
I was playing around with sveltekit auth, and when I added the prisma adapter I got the same bug. The reason is that the prisma adapter has a nullable email field, while the new Adapter type has a nonnullable email type.

**Comment by L-Mario564** [comment]
Had this same issue in a SvelteKit project. Type assertion worked for me and didn't get errors on runtime, should be a good temporary solution.

```ts
import SvelteKitAuth from '@auth/sveltekit'; // Using SvelteKit as an example
import type { Adapter } from '@auth/core/adapters';

export const handle = SvelteKitAuth({
  adapter: PrismaAdapter(prismaClient) as Adapter<boolean>,
  providers: [
    // ...
  ]
});
```

**Comment by califlower** [comment]
> Had this same issue in a SvelteKit project. Type assertion worked for me and didn't get errors on runtime, should be a good temporary solution.
> 
> ```ts
> import SvelteKitAuth from '@auth/sveltekit'; // Using SvelteKit as an example
> import type { Adapter } from '@auth/core/adapters';
> 
> export const handle = SvelteKitAuth({
>   adapter: PrismaAdapter(prismaClient) as Adapter<boolean>,
>   providers: [
>     // ...
>   ]
> });
> ```

this works for now

**Comment by OrJDev** [comment]
resolved in 0.2.2

```bash
npm install @auth/core@latest
```

**Comment by kalm42** [comment]
I got the feedback that `Type 'Adapter' is not generic.`

```typescript
export const handle = SvelteKitAuth({
	adapter: PrismaAdapter(prisma) as Adapter,
	providers: [
		...
	]
});
```

**Comment by ryoppippi** [comment]
@kalm42  me too

**Comment by TurtIeSocks** [comment]
+1

**Comment by YuraD** [comment]
try this 
`import type { Adapter } from 'next-auth/adapters';`
....
`adapter: TypeORMAdapter(connection) as Adapter,`

P.S. No matter which adapter you have, it should help with every adapters

**Comment by ShriPunta** [comment]
Hi @YuraD can you please explain with more context.
I am not able to understand what is `connection` here? Also what do you mean by `TypeORMAdapter`? where can I import this function?

**Comment by verdverm** [comment]
@ShriPunta this is more about the `Adapter` and typescript types I think. Adding the `Adapter` worked for prisma as well

```
import type { Adapter } from 'next-auth/adapters';

...

export const authConfig: NextAuthOptions = {
	adapter: PrismaAdapter(db) as Adapter,

...
```

**Comment by MaKTaiL** [comment]
> ![image](https://user-images.githubusercontent.com/74648201/246859078-1827ca81-53b9-4c4e-8c63-4005471ebf99.png) got no issues in this case
> 
> * import { PrismaAdapter } from "@next-auth/prisma-adapter";  -> had no issue
> * import { PrismaAdapter } from "@auth/prisma-adapter";  -> had issue  (This was in the official docs of next-auth)

Which Schema should I use with "@next-auth/prisma-adapter"? The one shown in the v3 version or the one shown for "@auth/prisma-adapter"?

@next-auth v3: https://next-auth.js.org/v3/adapters/prisma
@auth: https://authjs.dev/reference/adapter/prisma

**Comment by LeonardoTrapani** [comment]
Looks like the module @next-auth/adapters is no longer existing, so the only solution is using @next-auth/prisma-adapter. I would suggest fixing the docs, or fixing the package

**Comment by OrJDev** [comment]
use `@auth/prisma-adapter` to solve this issue

**Comment by Puetz** [comment]
Why was this issue closed? 
I just set up my Next JS project with   
`"@auth/prisma-adapter": "^1.0.1"`  
`"next-auth": "^4.22.5"`  
and I'm having the exact same problems as everyone mentioned.  
So I installed  `"@next-auth/prisma-adapter": "^1.0.7"` which works for me.

Please fix either your [documentation](https://authjs.dev/reference/adapter/prisma) about the prisma adapter or fix the type error for the newest versions of `next-auth` and `@auth/prisma-adapter`.

**Comment by nickjanssen** [comment]
@Puetz as @next-auth is becoming @auth that's probably not the right way.

@OrJDev please re-open. Also using ` as Adapter` is a hack, not a solution.

**Comment by adammetal** [comment]
> Why was this issue closed? I just set up my Next JS project with
> 
> ```
> "@auth/prisma-adapter": "^1.0.1"
> "next-auth": "^4.22.5"
> ```
> 
> and I'm having the exact same problems as everyone mentioned. So I installed `"@next-auth/prisma-adapter": "^1.0.7"` which works for me.
> 
> Please fix either your [documentation](https://authjs.dev/reference/adapter/prisma) about the prisma adapter or fix the type error for the newest versions of `next-auth` and `@auth/prisma-adapter`.

This fixed my problem either. I think they should update a documentation a bit. Maybe we can help them? Open a pr? Because right now i feel a bit lost.

**Comment by maltesa** [comment]
I can confirm that I'm still having type errors with the latest versions:

Using [this Schema](https://authjs.dev/reference/adapter/prisma#naming-conventions).

```json
    "@auth/prisma-adapter": "^1.0.1",
    "next-auth": "^4.23.1",
```

```ts
export const authOptions: NextAuthOptions = {
  adapter: PrismaAdapter(db),
// ^~~~~   TypeError           
  providers: [getEmailProvider()],
//...
}
```

Error:
```
ype 'import("/workspace/node_modules/.pnpm/@auth+core@0.9.0/node_modules/@auth/core/adapters").Adapter' is not assignable to type 'import("/workspace/node_modules/.pnpm/next-auth@4.23.1_next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/adapters").Adapter'.
  Types of property 'linkAccount' are incompatible.
    Type '((account: import("/workspace/node_modules/.pnpm/@auth+core@0.9.0/node_modules/@auth/core/adapters").AdapterAccount) => Promise<void> | import("/workspace/node_modules/.pnpm/@auth+core@0.9.0/node_modules/@auth/core/types").Awaitable<import("/workspace/node_modules/.pnpm/@auth+core@0.9.0/node_modules/@auth/core/adapt...' is not assignable to type '((account: import("/workspace/node_modules/.pnpm/next-auth@4.23.1_next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/adapters").AdapterAccount) => Promise<...> | import("/workspace/node_modules/.pnpm/next-auth@4.23.1_next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/types").Awaita...'.
      Type '(account: import("/workspace/node_modules/.pnpm/@auth+core@0.9.0/node_modules/@auth/core/adapters").AdapterAccount) => Promise<void> | import("/workspace/node_modules/.pnpm/@auth+core@0.9.0/node_modules/@auth/core/types").Awaitable<import("/workspace/node_modules/.pnpm/@auth+core@0.9.0/node_modules/@auth/core/adapte...' is not assignable to type '(account: import("/workspace/node_modules/.pnpm/next-auth@4.23.1_next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/adapters").AdapterAccount) => Promise<...> | import("/workspace/node_modules/.pnpm/next-auth@4.23.1_next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/types").Awaitab...'.
        Types of parameters 'account' and 'account' are incompatible.
          Type 'import("/workspace/node_modules/.pnpm/next-auth@4.23.1_next@13.4.12_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/adapters").AdapterAccount' is not assignable to type 'import("/workspace/node_modules/.pnpm/@auth+core@0.9.0/node_modules/@auth/core/adapters").AdapterAccount'.
            Types of property 'type' are incompatible.
              Type 'ProviderType' is not assignable to type '"email" | "oidc" | "oauth"'.
                Type '"credentials"' is not assignable to type '"email" | "oidc" | "oauth"'.ts(2322)
types.d.ts(106, 5): The expected type comes from property 'adapter' which is declared here on type 'AuthOptions'
```

No errors when using latest `@next-auth/prisma-adapter`

**Comment by FabioCingottini** [comment]
Not sure if it can help someone, but I solved it by using:
```
import { Adapter } from 'next-auth/adapters';
import { PrismaAdapter } from '@auth/prisma-adapter';

const nextAuthOptions = {
  ...,
  adapter: <Adapter>PrismaAdapter(prismaClient),
  ...,
```

With versions:
```
...
"next-auth": "^4.24.5",
"@auth/prisma-adapter": "^1.3.3",
...
```

**Comment by AlfredMadere** [comment]
casting the adapter to `Adapter` is still necessary to avoid type errors with 

```json
    "@auth/prisma-adapter": "^2.4.2",
    "next-auth": "5.0.0-beta.4",
```

**Comment by baitangxiaoyu** [comment]
"@auth/prisma-adapter": "^2.4.2",
    "next-auth": "5.0.0-beta.4",
![image](https://github.com/user-attachments/assets/1a74208d-1598-41e8-bd4f-da5ff47d6926)
If I adopt this approach, there will be no problem.

**Comment by pantharshit007** [comment]
<img width="774" alt="image" src="https://github.com/user-attachments/assets/12484c26-7fd3-4510-942f-41f2ff697531">

getting this error only workaround I can find right now is adding `type: module`
they should make this a dual module (works in both CommonJS and ESM).
