### ISSUE TITLE
How can I extend the Session type in this scenario to add another property?

### ISSUE THREAD

**Issue by slawton3** [nextauthjs/next-auth#6109]
### Question 💬

I have a function like this in my ```[...nextauth].ts``` file.

```
return await NextAuth(req, res, {
    providers,
    session: {
      strategy: "jwt",
    },
    secret: process.env.NEXTAUTH_SECRET,
    callbacks: {
      // after a user is logged in, we can keep the address in session
      async session({ session, token }) {
        session.address = token.sub;  //<-- this is where I am getting the "address does not exist on type Session" type error
        session.user!.name = token.sub;
        return session;
      },
    },
  });

```

Wondering how I can extend the Session type to accommodate the address property? Apologies if this has already been asked, I have not been able to find a solid resource on this.

### How to reproduce ☕️

Try to add a new property to the session callback in [...nextauth].ts

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
https://next-auth.js.org/getting-started/typescript#module-augmentation
