### ISSUE TITLE
Sign in with Credentials - SvelteKit

### ISSUE THREAD

**Issue by KoljaL** [nextauthjs/next-auth#6127]
### Environment

```JSON
	"devDependencies": { 
		"@sveltejs/adapter-auto": "^1.0.0",
		"@sveltejs/kit": "^1.0.0", 
                ...
	},
	"dependencies": {
		"@auth/core": "^0.1.4",
		"@auth/sveltekit": "^0.1.6",
		"@prisma/client": "^4.7.1"
	}
```

### Reproduction URL

https://github.com/KoljaL/SK-AuthJS

### Describe the issue

In my repo I use the authentication via Github and want to extend via the Credentials provider.

I added this: https://next-auth.js.org/providers/credentials#example---username--password in the `hooks.server.ts`

After submit I'm not logged in.
The cookies were set, but `$page.data.session`is still empty.

### How to reproduce

Clone the repo and run `bash resetdb.sh`

### Expected behavior

After the Login, I expect, that I am logged in as user `J Smith`.

**Comment by balazsorban44** [comment]
On the same page you can see this:

> It comes with the constraint that users authenticated in this manner are not persisted in the database, and consequently that the Credentials provider can only be used if JSON Web Tokens are enabled for sessions.
