### ISSUE TITLE
SvelteKit: Azure-AD throw Client is public so neither 'client_assertion' nor 'client_secret' should be presented

### ISSUE THREAD

**Issue by xmlking** [nextauthjs/next-auth#6133]
### Provider type

Azure Active Directory

### Environment

System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 36.15 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.2.0 - /opt/homebrew/bin/node
    npm: 8.19.3 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.2

### Reproduction URL

N/A

### Describe the issue

I followed https://next-auth.js.org/providers/azure-ad and registered an app with  (mobile & desktop) mode.

in my SvelteApp hooks 

```ts
import {
	AZURE_AD_CLIENT_ID,
	AZURE_AD_CLIENT_SECRET,
	AZURE_AD_TENANT_ID,
	GITHUB_ID,
	GITHUB_SECRET,
	GOOGLE_ID,
	GOOGLE_SECRET
} from '$env/static/private';
import AzureAD from '@auth/core/providers/azure-ad';
import GitHub from '@auth/core/providers/github';
import Google from '@auth/core/providers/google';
import SvelteKitAuth from '@auth/sveltekit';

export const authjs = SvelteKitAuth({
	providers: [
		Google({ clientId: GOOGLE_ID, clientSecret: GOOGLE_SECRET }),
		AzureAD({ clientId: AZURE_AD_CLIENT_ID, clientSecret: AZURE_AD_CLIENT_SECRET, tenantId: AZURE_AD_TENANT_ID }),
		GitHub({ clientId: GITHUB_ID, clientSecret: GITHUB_SECRET })
	]
});

```

when I hit http://localhost:5173/auth/signin and click `Sign in with Azure` I got this server-side error 
> "AADSTS700025: Client is public so neither 'client_assertion' nor 'client_secret' should be presented.\r\n" 

I also registered app at https://portal.azure.com/ as SPA/Web. both case it resulted same error

<img width="1277" alt="Screenshot 2022-12-20 at 6 41 53 PM" src="https://user-images.githubusercontent.com/627951/208809041-dde328a6-bd9b-49d5-a55c-0b52a632e22d.png">

> GitHub and Google login buttons works perfectly 

### How to reproduce

N/A

### Expected behavior

N/A

**Comment by balazsorban44** [comment]
As per the [docs] (https://learn.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app#configure-platform-settings), you should choose "Web". 🤔


[Googling](https://learn.microsoft.com/en-us/answers/questions/898979/aadsts700025-client-is-public-so-neither-39client.html) the error code sends you to a forum where they imply that when using the PKCE flow together with SPA mode isn't allowed, which is correct. The interesting part is thta you state you tried with Web as well.

PKCE and client_secret are not mutually exclusive so if that's the case in azure, it would be a wrong implementation of the spec on their side. See:



The reason for you seeing this error in case Azure implements the spec wrongly is that we now use PKCE by default. Again, Azure should not choke on that, if they don't support it, and just ignore the extra parameters https://www.rfc-editor.org/rfc/rfc7636#section-5

As a quick fix, you can pass `checks: ["state"] to the provider config and make sure you actually chose Web as the application type.

If these not help, you might want to turn to Azure Support.

**Comment by xmlking** [comment]
thanks @balazsorban44   switching to **Web**  platform fixed my issue. 
I was trying **SPA** and **Mobile and Desktop** platform options before. 

It would be nice if we highlight choose **Web** platform option in the doc: https://next-auth.js.org/providers/azure-ad

<img width="570" alt="image" src="https://user-images.githubusercontent.com/627951/208836275-06e09948-eb04-4ee6-bdc0-e68226610165.png">

**Comment by balazsorban44** [comment]
We could, but technically there is a direct link to the provider's configuration https://next-auth.js.org/providers/azure-ad#configuration, and you did write that you tried "Web" too. 🤔. Will see if  we can improve anyway! 👍
