### ISSUE TITLE
Sveltekit: Twitter Provider error

### ISSUE THREAD

**Issue by JohnRSim** [nextauthjs/next-auth#6135]
### Question 💬
Tested github auth worked without issue - 
However; using https://github.com/nextauthjs/sveltekit-auth-example and swapping from github to the twitter provider in hooks.server. 

I'm getting the following error res from twitter:

https://api.twitter.com/2/oauth2/authorize?code_challenge=AR-xxxxx&code_challenge_method=S256&client_id=xxxxx&redirect_uri=http%3A%2F%2F127.0.0.1%3A5173%2Fauth%2Fcallback%2Ftwitter&response_type=code&scope=users.read%20tweet.read%20offline.access
```
{
	"errors": [
		{
			"error": "invalid_request",
			"error_description": "Redirect is requested.",
			"redirect_uri": "http://127.0.0.1:5173/auth/callback/twitter?error=invalid_request&state="
		}
	]
}
``` 
![image](https://user-images.githubusercontent.com/364208/208889600-6ac5be4e-6ed6-4b4d-8715-28d3982c4c03.png)

### How to reproduce ☕️

```
import SvelteKitAuth from "@auth/sveltekit";
import Twitter from "@auth/core/providers/twitter"
import { TWITTER_CLIENTID, TWITTER_CLIENTSECRET } from '$env/static/private';

export const handle = SvelteKitAuth({
	providers: [ Twitter({ 
		clientId: TWITTER_CLIENTID, 
		clientSecret: TWITTER_CLIENTSECRET,
		//version: "2.0", // opt-in to Twitter OAuth 2.0
	}) ],
});
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by JohnRSim** [comment]
@balazsorban44 do you need me to create a quick sandbox - happy to quickly set one up - noticed the incomplete toggles :)

Thanks

**Comment by balazsorban44** [comment]
The `verion` option is not necessary anymore, `@auth/core` only supports OAuth 1+.

The issue is that Twitter 2.0 now requires both `pkce` and `state` as part of the authorization request: https://developer.twitter.com/en/docs/authentication/oauth-2-0/authorization-code

Opening a PR soon, for now you can pass `checks: ["pkce", "state"]` to your Twitter config.

**Comment by JohnRSim** [comment]
Thanks @balazsorban44 

I'm guessing no chance of an exception for twitter provider to support oAuth1?

The issue is -
"OAuth 2.0 can be used with the Twitter API v2 only."

The problem with this is that v2 api still only has limited support - alot of Devs still use v1 twitter APIs for alot of the tasks - as twitter are making slow progress on V2.

**Comment by balazsorban44** [comment]
No current plans for adding back support at this moment. I'm not interested in implementing an OAuth 1.0 compliant client. The package we use in `next-auth` https://github.com/ciaranj/node-oauth is Node.js only and would need to be ported to standard Web APIs. Even then, I'm not sure it would become part of the core, as the spec is quite old.
