### ISSUE TITLE
Unsure how to get data from scopes other than the default ones

### ISSUE THREAD

**Issue by pandaniell** [nextauthjs/next-auth#614]
Using the Discord provider I added a `scope` option to include "guilds", I am not sure how I can access the guilds after they have been allowed, below is my attempt, I also tried to just add a new property `guilds` with the same value outside of the profile property

```typescript
const options = {
  providers: [
    Providers.Discord({
      clientId: process.env.DISCORD_CLIENT_ID,
      clientSecret: process.env.DISCORD_CLIENT_SECRET,
      scope: "identify guilds",
      profile: {
        guilds: "https://discordapp.com/api/users/@me/guilds",
      },
    }),
  ],
};
```

**Comment by GiampaoloF95** [comment]
You'll need to expand your session using next-auth's callbacks.

You can add data to your JWT using the JWT callback:
https://next-auth.js.org/configuration/callbacks#jwt-callback
then you can get your data from the sign in objects you see in the documentation and pass them on to the token to make them persistent through the session.

Then to expand the session you can do the same using the session callback:
https://next-auth.js.org/configuration/callbacks#session-callback

**Comment by shaunchander** [comment]
> You'll need to expand your session using next-auth's callbacks.
> 
> You can add data to your JWT using the JWT callback:
> https://next-auth.js.org/configuration/callbacks#jwt-callback
> then you can get your data from the sign in objects you see in the documentation and pass them on to the token to make them persistent through the session.
> 
> Then to expand the session you can do the same using the session callback:
> https://next-auth.js.org/configuration/callbacks#session-callback

I've tried this but to no avail?

I've changed the `profile` method on my provider (Discord) to this:

```
profile: (profile) => {
	return {
		...profile,
	}
},
```

And changed my `jwt` to be like this
```
jwt: async (token, user, account, profile, isNewUser) => {
 token.profile = profile
	return Promise.resolve(token)
},
```

However, in the browser returns the JWT with the original `user` object, only this time the `name` and `image` fields are null (email exists as a property in `...profile` so it's already assigned back to `token` like normal).

**Comment by pandaniell** [comment]
Would be nice to have a working example

**Comment by pbshgthm** [comment]
This happens because on subsequent invocation (every time session is called), profile is not passed to jwt callback.

```js
jwt: async (token, user, account, profile, isNewUser) => {
    if (profile) { token.profile = profile}
    return Promise.resolve(token)
  }
```

This should hopefully solve the problem

**Comment by archywillhe** [comment]
hmm I'm getting some really strange behavior for users that already have accounts created in the db:

when `jwt: async (token, user, account, profile, isNewUser) ` is called with account, etc (i.e. signin happens), I'm able to inject something based on the account to my token (e.g. `token.prop = account.prop`), get it to be encoded in `jwt.encode` and pass it to session (e.g. `session.prop = token.prop`) in the session callback. 

but after the user logs in and gets directed to the landing page, when i check session (in the broswer) sometimes the prop is there, sometimes it is not i.e. as if in a quantum state. 

anyone running into similiar things?

**Comment by nodgear** [comment]
Guys, the id is called sub as user prop:
```js
  callbacks: {
    session: async (session, user) => {
      session.user.id = user.sub
      console.log("CALLBACK SESSION", session, user)
      return Promise.resolve(session)
    }
  }
  ```
  this will add ID to the session user object, which is available site-wise.

**Comment by ddiablou** [comment]
> Guys, the id is called sub as user prop:
> 
> ```js
>   callbacks: {
>     session: async (session, user) => {
>       session.user.id = user.sub
>       console.log("CALLBACK SESSION", session, user)
>       return Promise.resolve(session)
>     }
>   }
> ```
> 
> this will add ID to the session user object, which is available site-wise. Then we can use the normal endpoints + token data to fetch everything else. (Except that i can't recover the token either..)

Well, how it's possible to fetch user's guilds with it?

**Comment by nodgear** [comment]
> > Guys, the id is called sub as user prop:
> > ```js
> >   callbacks: {
> >     session: async (session, user) => {
> >       session.user.id = user.sub
> >       console.log("CALLBACK SESSION", session, user)
> >       return Promise.resolve(session)
> >     }
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this will add ID to the session user object, which is available site-wise. Then we can use the normal endpoints + token data to fetch everything else. (Except that i can't recover the token either..)
> 
> Well, how it's possible to fetch user's guilds with it?

Discord API
