### ISSUE TITLE
Google provider passing custom params to sign in callback

### ISSUE THREAD

**Issue by jaekunchoi** [nextauthjs/next-auth#6154]
### Question 💬

Hi,

There isn't any way I can find where I can pass in custom params to sign in callback?

I need this because I use Google Auth to login user then there is another connect button where I get user to consent but that doesn't involve a checkbox so user doesn't have to click on it.

### How to reproduce ☕️

Use below

```
signIn('google', {}, { 
      scope: 'https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/webmasters.readonly', 
      authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&response_type=code&prompt=consent',
      redirect_uri: URL,
      loginType: 'connect'
});
```

I can't get any callback `loginType` in the callback:

```
callbacks.signIn = async (user, account, profile) => {
  if(account.provider === 'google' && profile.verified_email === true) {
    console.log('user', user);
    console.log('account', account);
    console.log('profile', profile);
  }
});
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
You can actually do this in multiple places:

- https://next-auth.js.org/getting-started/client#additional-parameters
- https://next-auth.js.org/configuration/providers/oauth#authorization-option

**Comment by jaekunchoi** [comment]
I ended up using Cookies https://github.com/nextauthjs/next-auth/discussions/4094

**Comment by balazsorban44** [comment]
Not sure of the use case there, but make sure to upgrade to at least v4, as v3 is unmaintained.
