### ISSUE TITLE
Link to SvelteKit example broken on https://next-auth.js.org/faq

### ISSUE THREAD

**Issue by robhyrk** [nextauthjs/next-auth#6157]
### Environment

N/A

### Reproduction URL

https://next-auth.js.org/faq

### Describe the issue

Link to SvelteKit example broken on https://next-auth.js.org/faq under "Can I use NextAuth.js with a framework different than Next.js?"

### How to reproduce

go to site, click the SveltKit link

### Expected behavior

should link to correct page

**Comment by balazsorban44** [comment]
There's an edit button at the bottom, want to fix? Please open a PR against the `v4` branch. Thanks!

**Comment by iamr-kumar** [comment]
Seems the Gatsby link is broken too.
What would be the correct links that these should point to?

**Comment by balazsorban44** [comment]
Probably: https://sveltekit.authjs.dev and https://github.com/nextauthjs/next-auth/tree/main/apps/playground-gatsby respectively.

**Comment by SoyebSarkar** [comment]
Hey @balazsorban44 , I want to fix this issue

**Comment by iamr-kumar** [comment]
Hey @SoyebSarkar, are you taking up this issue?

**Comment by robhyrk** [comment]
changed the links and opened a PR!

ps. excited to take this out for a test drive soon
