### ISSUE TITLE
useSession server side (during build): any way to silence errors ?

### ISSUE THREAD

**Issue by jacargentina** [nextauthjs/next-auth#616]
**Your question**
In a given page, I have `useSession()` to know when to show an Edit button or not, depending on the user having authorization on that: during `next build` I get this error.

<img width="1086" alt="Captura de Pantalla 2020-08-27 a la(s) 16 15 08" src="https://user-images.githubusercontent.com/517228/91485034-87cc6a00-e880-11ea-8f8f-49ba535e9504.png">

Which is basically right on what it says: it could not get the "real auth response" because that site is actually running other web app, so the error is about trying to parse HTML to JSON.

**What are you trying to do**
That call will works just fine on the browser once I deploy the app, so I was looking for a way to simply avoid the error during build time (it can cause confusion on other "real" errors on build) 

**Feedback**

* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
Hi there.

Hmm, I'd like to help but I don't quite get how this behaviour is being triggered.

Can you give any other info for context, like where `useSession` is being called form and/or about the build process, are you doing a static export of the site (etc)?

**Comment by jacargentina** [comment]
@iaincollins I'll close this, as was a very specific thing on my migration from a react normal app to a next one, and the errors just came when I was on the "migration time"; now that it was finished, the error is not there anymore.

**Comment by iaincollins** [comment]
@jacargentina Oh! Thanks you for the follow up! I'm glad it's working now!

I really wasn't sure how this was being triggered but that's one less thing to keep me up at night. 😂
