### ISSUE TITLE
`SvelteKitAuth` has no call signatures

### ISSUE THREAD

**Issue by Fermain** [nextauthjs/next-auth#6170]
### Environment

  System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 155.72 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 15.5

### Reproduction URL

https://github.com/nextauthjs/sveltekit-auth-example

### Describe the issue

```bash
sveltekit-auth-example/src/hooks.server.ts:5:23
Error: This expression is not callable.
  Type 'typeof import("/Users/User/sveltekit-authjs-example/node_modules/@auth/sveltekit/index")' has no call signatures. 

export const handle = SvelteKitAuth({
  providers: [GitHub({ clientId: GITHUB_ID, clientSecret: GITHUB_SECRET })],
```

### How to reproduce

1. Clone the repo
2. Install the repo
3. `npm run build`

### Expected behavior

Expect build to complete without errors.

**Comment by Fermain** [comment]
Suggested solution: Add `default` to import at `index`:

```js
export default function SvelteKitAuth(options) {
```

**Comment by xmlking** [comment]
blocked with this bug.  though recent release fixed this 

```
TypeError: __vite_ssr_import_4__.default is not a function
    at /Users/schintha/Developer/Work/SPA/svelte-starter-kit/src/lib/server/middleware/authjs.ts:17:36
    at async instantiateModule (file:///Users/schintha/Developer/Work/SPA/svelte-starter-kit/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:52198:9)
```

**Comment by asrvd** [comment]
getting the same error

**Comment by octavio-vercetti** [comment]
`import { SvelteKitAuth } from '@auth/sveltekit';`

**Comment by asrvd** [comment]
> for `"@auth/sveltekit": "^0.1.9"` do `import { SvelteKitAuth } from '@auth/sveltekit';`

throws a new error

![image](https://user-images.githubusercontent.com/68690233/209440209-27b4d23f-4da3-4f18-b2d8-d1af7010b40b.png)

**Comment by balazsorban44** [comment]
Fixed in https://github.com/nextauthjs/next-auth/commit/65defc709e5acc06df40f4e99c1ade46cf12d7be. We are trying to go away from default imports.
