### ISSUE TITLE
Incorrect Peer Dependency

### ISSUE THREAD

**Issue by jaitaiwan** [nextauthjs/next-auth#6172]
### Adapter type

@next-auth/supabase-adapter

### Environment

  System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC 7601 32-Core Processor
    Memory: 1.46 GB / 3.84 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.9.1 - ~/.nodenv/versions/18.9.1/bin/node
    npm: 8.19.1 - ~/.nodenv/versions/18.9.1/bin/npm
  npmPackages:
    next: 13.0.2 => 13.0.2 
    next-auth: ^4.18.3 => 4.18.7 
    react: 18.2.0 => 18.2.0 

  npmPackages:
    @next-auth/prisma-adapter: ^1.0.5 => 1.0.5 
    @next-auth/supabase-adapter: ^0.2.0 => 0.2.0 

### Reproduction URL

https://github.com/nextauthjs/next-auth

### Describe the issue

When attempting to install the supabase adapter the following issue happens:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: dobetter.3@0.1.0
npm ERR! Found: next-auth@4.18.7
npm ERR! node_modules/next-auth
npm ERR!   next-auth@"^4.18.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next-auth@"4.16.4" from @next-auth/supabase-adapter@0.2.0
npm ERR! node_modules/@next-auth/supabase-adapter
npm ERR!   @next-auth/supabase-adapter@"^0.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps

### How to reproduce

Simply have next-auth@4.18.7 installed and then attempt to install @next-auth/supabase-adapter

### Expected behavior

The package should be setup with the correct peer dependencies

**Comment by balazsorban44** [comment]
Fixed it, the issue was that it was set to `workspace:*` which bumped the required version on each publish. Make sure you are on at least `4.18.7`, and from now on it should work in the future.
