### ISSUE TITLE
Remove the shackles from CredentialsProvider

### ISSUE THREAD

**Issue by thislooksfun** [nextauthjs/next-auth#6177]
### The problem

Currently the CredentialsProvider is pretty aggressively restricted. It only works with JWT sessions (which have [inherent problems](https://redis.com/blog/json-web-tokens-jwt-are-dangerous-for-user-sessions/)), and there isn't an obvious way to allow new users to sign up with a username/password.

In theory this is a good thing. The reason given [in the docs](https://next-auth.js.org/providers/credentials) makes sense. After all, you can't have a password breach if you don't store any passwords!

However, I argue that this decision actually does **more harm than good**. Consider the following examples:

### It makes seeding test databases unnecessarily difficult.

I am using Prisma in my latest project, and I want to set up [database seeding](https://www.prisma.io/docs/guides/database/seed-database) to make development and testing faster. The problem is that all the complex test data I want to automate the creation of either directly or indirectly links to a user id. This means that in order to seed my database fully I _need_ a user in there. However, the only ways I can find to seed the user are 1) create a stub user that you can't log in to, 2) hardcode (or otherwise externally store) OAuth access tokens, 3) require the developer to log in before running the rest of the seeder, or 4) use Credentials. In any other project option 4 would be the easy choice, since I just make a test user with a simple password (it doesn't need to be secure after all), but with Auth.js that's proving to be a headache.

### It causes confusion

There are lots of examples of developers getting confused because the CredentialsProvider isn't working the way they expect ([1](https://github.com/nextauthjs/next-auth/issues/6127), [2](https://github.com/nextauthjs/next-auth/discussions/5911), [3](https://github.com/nextauthjs/next-auth/discussions/4457), and [probably more](https://github.com/nextauthjs/next-auth/discussions?discussions_q=credentialsprovider+session+database)). This increases friction and makes it way more difficult to get what we need done.

### Last but not least: *people will do it anyway, but worse*

I firmly believe that while this "just don't use it" stance is good in theory, in practice it doesn't work. There are [discussions](https://github.com/nextauthjs/next-auth/discussions/4394) and [blog posts](https://branche.online/next-auth-credentials-provider-with-the-database-session-strategy/) that discuss ways to force Auth.js to work with credentials. Plus devs could always make their own entirely custom login solution that either replaces or sits next to the Auth.js system. I don't think it's possible to make developers stop providing username/password login, but by imposing restrictions on the CredentialsProvider all you're really doing is forcing developers to use janky workarounds. Workarounds that are inherently less secure and more error-prone than a first-party Auth.js solution, because each one will end up being unique.

### The solution

I argue that CredentialsProvider should be a fully-featured part of the Auth.js system. If we make it an equal member of the system then NextAuth can provide a well-tested solution that meets (or exceeds) industry best practices (salting, hashing, etc.) to help future developers from falling into those traps themselves. It should still have a giant warning on it saying "don't use this unless you really know what you're doing", as many developers can easily get away with just using OAuth. You could even make it its own package, or hide it behind an "unsafe" config option (there's already a [precedent for this](https://next-auth.js.org/configuration/providers/oauth#allowdangerousemailaccountlinking-option)), so devs need to do extra work to enable it. It doesn't eliminate the risks associated with using credential auth, but at least it minimizes it as much as possible.

An alternate solution would be adding a generic provider mechanism (essentially an abstraction layer on top of th existing provider structure) so devs can define their own fully custom provider using whatever implementation fits their needs. This would at least allow those of us who need full credential auth to still work within the bounds of NextAuth's system, while still making it 100% in the hands of the individual developer to ensure their implementation is correct. While I would be satisfied with this solution, I still think it's leaving a massive footgun lying around unnecessarily.

The final solution is to leave things as they are. This is, in my opinion, the biggest footgun of them all. It means that new developers will keep getting confused when their auth doesn't work as expected (see above) while simultaneously forcing developers who _need_ username/password auth to make their own (probably flawed) solution.

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
Not planning to add support for this any time soon.

The documentation already mentions why, in many cases, developers have been confused because they just did not read the documentation. If you have suggestions on how to imrpvoe that, I'm happy to. 

Feel free to create a guide/third-party package with best practices.

We might reconsider this in the distant future, but right now it's very low priority.
