### ISSUE TITLE
Github docs moved, links broken.

### ISSUE THREAD

**Issue by 1337cookie** [nextauthjs/next-auth#6190]
### What is the improvement or update you wish to see?

In this commit https://github.com/nextauthjs/next-auth/commit/36f44a869a85a03ebe6e03d879615b352e0ef0b9 some files were deleted/moved.  
CONTRIBUTING.MD for example has moved to 
https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md 
There are still several references to the old file.

 https://github.com/nextauthjs/next-auth/blob/511f66b0a8e4119e2e31ba16dcaf369488c9bca5/packages/next-auth/README.md?plain=1#L250 
 
 https://github.com/nextauthjs/next-auth/blob/511f66b0a8e4119e2e31ba16dcaf369488c9bca5/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L32
 
https://github.com/nextauthjs/next-auth/blob/511f66b0a8e4119e2e31ba16dcaf369488c9bca5/docs/README.md?plain=1#L62

There are other files and links that need to be updated. I'm happy to open a PR if its just a matter of updating all the references to the new locations. 

### Is there any context that might help us understand?

This looks like a bug but perhaps is being fixed by some tooling or automation process not yet implemented. I'm not familiar with some the tooling used here.

**Comment by iswarmondal** [comment]
Let me take a look at this issue
