### ISSUE TITLE
Invalid Compact JWE message using Prisma Adapter and Google Provider

### ISSUE THREAD

**Issue by tommulkins** [nextauthjs/next-auth#6195]
### Adapter type

@next-auth/prisma-adapter

### Environment

  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 522.58 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.2
  npmPackages:
    next: 13.0.6 => 13.0.6 
    next-auth: ^4.18.7 => 4.18.6 
    react: 18.2.0 => 18.2.0 

  npmPackages:
    @next-auth/prisma-adapter: ^1.0.5 => 1.0.5 

### Reproduction URL

https://github.com/tommulkins/next-auth-example

### Describe the issue

Using the Prisma adapter and Google Provider, then attempting to get the session using `unstable_getServerSession`as described here:

https://next-auth.js.org/getting-started/example#backend---api-route
```
import { unstable_getServerSession } from "next-auth/next"
import { authOptions } from "./auth/[...nextauth]"
export default async (req, res) => {
  const session = await unstable_getServerSession(req, res, authOptions)
```  

I get the `Invalid Compact JWE` error when using it in this endpoint https://github.com/tommulkins/next-auth-example/blob/session-bug/pages/api/account/verify.ts.  I read the resolution as described here but uncertain if this pertains to this situation:

https://next-auth.js.org/errors#jwt_session_error

I used the example for generating the secret `NEXTAUTH_SECRET` as follows: `openssl rand -base64 32`

I provided an example of how I'm trying to use Next Auth @ https://github.com/tommulkins/next-auth-example.  I'm using Postgres locally with the required schema viewable in `prisma/schema.prisma`.

Did I miss a step from the documentation maybe?  The only area I had to customize was to also get the refresh token from `pages/api/auth/[...nextauth].ts` along with the needed schema change:

```
const GOOGLE_AUTHORIZATION_URL = `https://accounts.google.com/o/oauth2/v2/auth?${new URLSearchParams(
  {
    prompt: 'consent',
    access_type: 'offline',
    response_type: 'code',
  }
)}`
```
....
```
 providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_ID,
      clientSecret: process.env.GOOGLE_SECRET,
      authorization: GOOGLE_AUTHORIZATION_URL,
    }),
  ],
  ```

### How to reproduce

A .env file with a valid `NEXTAUTH_SECRET`, `NEXTAUTH_URL`, `GOOGLE_SECRET`, `GOOGLE_ID`, and `DATABASE_URL`.  Run with `npx prisma db push`, then `npm run dev`.  Login with a valid Google account and the redirect to `/` homepage will call a `fetch` to `pages/api/account/verify` in a `useEffect` call @ https://github.com/tommulkins/next-auth-example/blob/85d2957f7a9a09cb25e05a2af412726673b5ae19/pages/index.tsx#L36

In the console you should get the following:

```
[next-auth][error][JWT_SESSION_ERROR] 
https://next-auth.js.org/errors#jwt_session_error Invalid Compact JWE {
  message: 'Invalid Compact JWE',
  stack: 'JWEInvalid: Invalid Compact JWE\n' +
    '    at compactDecrypt (/Users/tommulkins/Projects/Lokalyst/google-grader-v2/node_modules/jose/dist/node/cjs/jwe/compact/decrypt.js:16:15)\n' +
    '    at jwtDecrypt (/Users/tommulkins/Projects/Lokalyst/google-grader-v2/node_modules/jose/dist/node/cjs/jwt/decrypt.js:8:61)\n' +
    '    at Object.decode (/Users/tommulkins/Projects/Lokalyst/google-grader-v2/node_modules/next-auth/jwt/index.js:64:34)\n' +
    '    at async Object.session (/Users/tommulkins/Projects/Lokalyst/google-grader-v2/node_modules/next-auth/core/routes/session.js:40:28)\n' +
    '    at async AuthHandlerInternal (/Users/tommulkins/Projects/Lokalyst/google-grader-v2/node_modules/next-auth/core/index.js:125:27)\n' +
    '    at async AuthHandler (/Users/tommulkins/Projects/Lokalyst/google-grader-v2/node_modules/next-auth/core/index.js:335:28)\n' +
    '    at async unstable_getServerSession (/Users/tommulkins/Projects/Lokalyst/google-grader-v2/node_modules/next-auth/next/index.js:123:20)\n' +
    '    at async handler (webpack-internal:///(api)/./pages/api/account/verify.ts:11:21)\n' +
    '    at async Object.apiResolver (/Users/tommulkins/Projects/Lokalyst/google-grader-v2/node_modules/next/dist/server/api-utils/node.js:363:9)\n' +
    '    at async DevServer.runApi (/Users/tommulkins/Projects/Lokalyst/google-grader-v2/node_modules/next/dist/server/next-server.js:474:9)',
  name: 'JWEInvalid'
}
```

### Expected behavior

Expected to get the server session and contents shown on the console.log.

**Comment by balazsorban44** [comment]
You are importing the whole `NextAuth` handler, instead of just the config on this line https://github.com/tommulkins/next-auth-example/blob/85d2957f7a9a09cb25e05a2af412726673b5ae19/pages/api/account/verify.ts#L4

Please refer to the docs https://next-auth.js.org/configuration/nextjs#unstable_getserversession

**Comment by tommulkins** [comment]
> You are importing the whole `NextAuth` handler, instead of just the config on this line https://github.com/tommulkins/next-auth-example/blob/85d2957f7a9a09cb25e05a2af412726673b5ae19/pages/api/account/verify.ts#L4
> 
> Please refer to the docs https://next-auth.js.org/configuration/nextjs#unstable_getserversession

Thanks!

**Comment by Gyurmatag** [comment]
@tommulkins have you managed to solve this? I have the same error.
