### ISSUE TITLE
I have to redirect to the sign out link or I can't sign out completely

### ISSUE THREAD

**Issue by jsun969** [nextauthjs/next-auth#6198]
### Provider type

Custom provider

### Environment

  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx
    Memory: 4.37 GB / 6.73 GB
    Container: Yes
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 18.12.1 - ~/.local/share/nvm/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.local/share/nvm/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.local/share/nvm/v18.12.1/bin/npm
  npmPackages:
    next: 13.0.2 => 13.0.2
    next-auth: ^4.18.3 => 4.18.7
    react: 18.2.0 => 18.2.0

### Reproduction URL

https://github.com/jsun969/uwall/blob/fd6aa78710a964e387c1a74bc67de15364b92c94/src/pages/index.tsx#L16-L18

### Describe the issue

I am using [Authing](https://www.authing.cn/)'s OIDC auth service.
This is my custom provider

```ts
{
  id: 'authing',
  name: 'AuthingProvider',
  type: 'oauth',
  wellKnown: env.AUTHING_WELL_KNOWN,
  clientId: env.AUTHING_APP_ID,
  clientSecret: env.AUTHING_APP_SECRET,
  authorization: { params: { scope: 'openid email profile' } },
  idToken: true,
  profile: (profile) => ({
    id: profile.sub,
    email: profile.email,
    name: profile.name,
    image: profile.picture,
  }),
},
```

And my well-known url is https://jsun-uwall.authing.cn/oidc/.well-known/openid-configuration
It have provided an `end_session_endpoint` for sign out

However, when I use `signOut()` only. If I try to sign in again, it don't redirect to the auth page but auto sign in as the previous account. This means the `signOut()` didn't trigger the `end_session_endpoint` link.

My solution is

```ts
signOut();
window.location.href = env.NEXT_PUBLIC_AUTHING_SIGN_OUT;
//                         ^ end_session_endpoint
```

If I redirect the sign out link **manually**, it can sign out properly.

### How to reproduce

Remove `window.location.href = env.NEXT_PUBLIC_AUTHING_SIGN_OUT;`

### Expected behavior

`signOut()` can trigger the `end_session_endpoint`

**Comment by balazsorban44** [comment]
We don't currently support federated logout. More info here https://github.com/nextauthjs/next-auth/discussions/3938
