### ISSUE TITLE
On `response_type: 'token'` it should get `access_token` from URI fragment, not query params

### ISSUE THREAD

**Issue by LLCampos** [nextauthjs/next-auth#6204]
### Environment

```
  System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 76.92 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2
    Yarn: 1.22.19
    npm: 9.2.0
  npmPackages:
    next: latest => 13.1.1 
    next-auth: latest => 4.18.7 
    react: ^18.2.0 => 18.2.0 
```

### Reproduction URL

https://github.com/LLCampos/next-auth-example

### Describe the bug

My `[...nextauth].ts` looks like the following:

```ts
import NextAuth, { NextAuthOptions } from "next-auth"

export const authOptions: NextAuthOptions = {
  providers: [
    {
      id: 'rails',
      name: 'Rails',
      type: 'oauth',
      idToken: false,
      clientId: '348d26c2-c077-453b-9339-6a401d94598a',
      wellKnown: 'http://localhost:3000/.well-known/openid-configuration',
      authorization: {
        params: { response_type: 'token' },
      },
      checks: [],
      profile(profile) {
        return {
          id: '1234',
          name: 'name',
          email: 'email@email.com',
          image: undefined,
        }
      },
    },

  ],
}

export default NextAuth(authOptions)

```

Note that `response_type: 'token'` is being used!

After request to the authorization URl, browser is redirected to something like `http://localhost:4005/api/auth/callback/rails#access_token=myAccessToken&token_type=Bearer&expires_in=7200`

Looking [here](https://datatracker.ietf.org/doc/html/rfc6749#section-4.2.2), I think this looks like what it should be. But I get an error like the following:

```
https://next-auth.js.org/errors#oauth_callback_error access_token not present in TokenSet {
  error: TypeError: access_token not present in TokenSet
      at Client.requestResource ((...)/node_modules/openid-client/lib/client.js:1117:15)
      at Client.userinfo ((...)/node_modules/openid-client/lib/client.js:1235:33)
      at oAuthCallback ((...)/node_modules/next-auth/core/lib/oauth/callback.js:149:30)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.callback ((...)/node_modules/next-auth/core/routes/callback.js:52:11)
      at async NextAuthHandler ((...)/node_modules/next-auth/core/index.js:201:28)
      at async file://(...)/.nuxt/dev/index.mjs:628:24
      at async Object.handler (file://(...)/node_modules/h3/dist/index.mjs:723:19)
      at async Server.toNodeHandle (file://(...)/node_modules/h3/dist/index.mjs:798:7) {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'rails',
  message: 'access_token not present in TokenSet'
}
```

I can make the flow finish and make the user authenticated if I replace the `#` with `?`, as such:

`http://localhost:4005/api/auth/callback/rails?access_token=myAccessToken&token_type=Bearer&expires_in=7200`

I think this might be a bug because it is looking for the `access_token` in the query params, not in the URI fragment?

### How to reproduce

Here's me reproducing this against a real backend that supports OAuth implicit flow.

![Screen Recording 2022-12-27 at 17 55 48](https://user-images.githubusercontent.com/12008784/209705153-0d3dcfa8-f9ed-4757-93a2-4aa7fb970372.gif)

But the issue is reproducible even without the backend.

Start the example app [here](https://github.com/LLCampos/next-auth-example) and go to `http://localhost:4005/api/auth/callback/rails#access_token=myAccessToken&token_type=Bearer&expires_in=7200`

You should see a `access_token not present in TokenSet` error in the logs.

Now go to `http://localhost:4005/api/auth/callback/rails?access_token=myAccessToken&token_type=Bearer&expires_in=7200`.

You should see a `invalid_token (The access token is invalid)` error in the logs, which means it extracted the token from the URL. 

### Expected behavior

I expect the `access_token` to be extracted from the URI frament, as specified [here](https://datatracker.ietf.org/doc/html/rfc6749#section-4.2.2).

**Comment by balazsorban44** [comment]
You are linking to the Implicity Grant section. The correct spec for the authorization code flow is: https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.4

Which expects the response body to contain those values. Implicit grant is not supported by `next-auth`
