### ISSUE TITLE
How to link oauth account to existing account?

### ISSUE THREAD

**Issue by iamanam** [nextauthjs/next-auth#621]
**Your question**
If user sign in using email provider for first time and later try to sign in using facebook provider,why it shows OAuthAccountNotLinked error? I think it should be linked automatically. Am i doing anything wrong?

**What are you trying to do**
i want other oauth provider account to be linked automatically after user sign in with email first time. 

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
NextAuth.js does not support automatic account linking as it can allow for account hijacking. Official support for secure account linking and unlinking (which was supported in version 1.x but not in the re-write for version 2.x) is planned.

**Comment by Melvynx** [comment]
@iaincollins any news for 2024 ?
