### ISSUE TITLE
Facebook Provider always includes `scope=email` query parameter, even when passed specific `params` value.

### ISSUE THREAD

**Issue by Tenkir** [nextauthjs/next-auth#6213]
### Provider type

Facebook

### Environment

  System:
    OS: Linux 6.0 Arch Linux
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 48.75 GB / 62.59 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.volta/tools/image/node/18.12.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.19.2 - ~/.volta/tools/image/npm/8.19.2/bin/npm
  Browsers:
    Firefox: 108.0.1

### Reproduction URL

https://1hcb4g-3000.preview.csb.app/signup

### Describe the issue

The FacebookProvider always includes a `scope=email` query parameter in login URLs despite the param object being included in the configuration.

### How to reproduce

1. Add FacebookProvider to [...nextauth].ts
2. Include following authorization object
```typescript
      authorization: {
        url: 'http://www.facebook.com/v15.0/dialog/oauth',
        params: {
          display: 'page',
          extras: '{"setup":{"channel":"IG_API_ONBOARDING"}}',
          response_type: 'token',
        }
      }
```
3. Observe when logging into facebook via next-auth it adds `scope=email` query paramter

### Expected behavior

When passing an `authorizaton` object to the Facebook Provider, I would expect it to only include the parameters I have specified. This blocks the ability to use Facebook Login for Business as it error when a scope=email is included in the request.

**Comment by balazsorban44** [comment]
We are using this deep merge method to combine the user config with the default one, so if you want a different scope, you need to set it to something else

https://github.com/nextauthjs/next-auth/blob/554ec439c9c5153b1da061da9534071d1e4da7c0/packages/next-auth/src/utils/merge.ts#L8

**Comment by Tenkir** [comment]
> We are using this deep merge method to combine the user config with the default one, so if you want a different scope, you need to set it to something else
> 
> https://github.com/nextauthjs/next-auth/blob/554ec439c9c5153b1da061da9534071d1e4da7c0/packages/next-auth/src/utils/merge.ts#L8

`scope` should not be a forced property, some Oauth providers do not use scope as a paramter.

**Comment by Tenkir** [comment]
For anyone who might stumble upon this, I was able to remove scope from the query parameters entirely, and support Facebook Login for Business through the following configuration

```typescript
  providers: [
    FacebookProvider({
      clientId: process.env.FACEBOOK_CLIENT_ID || '', 
      clientSecret: process.env.FACEBOOK_CLIENT_SECRET || '',
      authorization: {
        url: 'http://www.facebook.com/v15.0/dialog/oauth',
        params: {
          client_id: process.env.FACEBOOK_CLIENT_ID || '',
          display: 'page',
          extras: '{"setup":{"channel":"IG_API_ONBOARDING"}}',
          response_type: 'token',
          config_id: '1182438162692201',
          scope: undefined
        }
      }
    })
  ],
```
