### ISSUE TITLE
Not use Credentials provider for totally new project?

### ISSUE THREAD

**Issue by ManuRodgers** [nextauthjs/next-auth#6214]
### Question 💬

Based on the documentation, it says that "The functionality provided for credentials based authentication is intentionally limited to discourage use of passwords due to the inherent security risks associated with them and the additional complexity associated with supporting usernames and passwords". 

So you guys strongly recommend to not use traditional username(email)/password authentication method?

### How to reproduce ☕️

unnecessary

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
yes. we believe using a common OAuth provider or passwordless login gives a very good base. that said, nothing stops you from starting off with the credentials provider either, you just have to be aware that there are risks to consider when you roll your own passwords in a database.
