### ISSUE TITLE
Error 400: Invalid Request when using Google OAuth2 on Vercel builds (works in localhost)

### ISSUE THREAD

**Issue by SushritPasupuleti** [nextauthjs/next-auth#622]
**Describe the bug**
I built a basic project using the example repo. Everything is configured (environment variables, authorized domains etc) and even included the environment variables on vercel too. But for some reason, even after it works perfectly on localhost the login fails when on vercel.

**Steps to reproduce**
- You can head to my live site here: [link to site](https://nextjs-test-rose-tau.vercel.app/)

- Press sign in in the top nav bar.

- Use google sign in

- You're greeted by the error message.

**Expected behavior**
The signin should be succesful and you should be redirected to the home page. And the nav bar should show your gmail details.

**Screenshots or error logs**
![Capture1](https://user-images.githubusercontent.com/14891901/91663770-8a40f500-eb08-11ea-8af5-52e6d1b34eea.PNG)

**Additional context**

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by SushritPasupuleti** [comment]
Updating to the latest version fixed this issue, without changing any other configs.

**Comment by tamlth0595** [comment]
@SushritPasupuleti 
Could you guide me how to make google signin on the vercel?

**Comment by tamlth0595** [comment]
@SushritPasupuleti 
If you have time, please help me.
I have urgent task.

**Comment by SushritPasupuleti** [comment]
@tamlth0595 sure, let me know what it is ?

**Comment by tamlth0595** [comment]
ok, I will send you the url.
https://funding-index.vercel.app/

**Comment by tamlth0595** [comment]
![image](https://user-images.githubusercontent.com/79301182/122005787-106eb500-cd84-11eb-97fd-e8ad5e27e78c.png)
when I click the "sign in" button, why the url is redirected to the different url?
I am not why this happens.

**Comment by tamlth0595** [comment]
How do you set the environment variables on vercel?
