### ISSUE TITLE
Prevent use of disposable emails when using the email provider via domain blacklist or similar?

### ISSUE THREAD

**Issue by lassegit** [nextauthjs/next-auth#6221]
### Description 📓

Is it or would it be possible to have a `validateEmail` function where you can check the email and return a boolean depending on wether the user should receive a sign in email?

### How to reproduce ☕️

If you setup email provider you can use disposable emails without issue.

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
https://next-auth.js.org/configuration/callbacks#sign-in-callback
