### ISSUE TITLE
Possibility to not update expiration time for cookie session?

### ISSUE THREAD

**Issue by vwatel** [nextauthjs/next-auth#6223]
### Question 💬

Hi everyone,

We are currently looking at using this library which looks very solid & clean, coming with the entire OpenID connect flow we need along with built-in security measures.
We have a corporate identity service we use where they provide the tokens (access_token, refresh_token and id_token) as part of the OpenID connect flow.
We have some security requirements to comply with, one of them being the user must re-login after 12 hours.
Therefore, our idea is to:
- access_token has 15min ttl, refresh_token has 12 hours ttl
- create session cookie with 12 hours ttl
- whenever a call is made to the API, a silent refresh token would need to be made to get a new access token in case the access_token has expired (_part to be implemented as not provided by this library_)
- when the refresh token will expire (after 12 hours), the user will be logged out and will need to re-login

We have seen that whenever a page is refreshed or activity occurs in the next-auth example application [here](https://github.com/nextauthjs/next-auth-example), where we managed to create our own Provider using our identity service, the expiration time for the cookie is updated.
We have found this implementation in the _session_ function of the file _packages/core/src/lib/routes/session.ts_.

1. What is the reason to always increase and update the expiration time of the cookie?
2. Is it possible to override this behavior to NOT update the expiration time of the cookie?

Thank you very much for your help, I'm looking forward to reading from you!

### How to reproduce ☕️

See description, nothing to reproduce

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Session expiry rotation is an included default behavior to ensure that a user is less likely to loose access in the middle of an action, which might be very frustrating. If you would be OK with this, then you can implement some logic in your app that tracks the session creation and invalidates it after the expiry date of your choice.

If your refresh_token is one-time only, you can check out https://next-auth.js.org/tutorials/refresh-token-rotation. The only difference would be that you simply don't do a silent signin on behalf of the user.

**Comment by vwatel** [comment]
Hi @balazsorban44 

Thank you for your reply.
I'm currently almost done with the implementation you suggested above.
I have one more question where you might be able to guide me with the best approach regarding **invalidating the session**.
Upon my logic that is there in the jwt callback to check expiration time of the access token and refresh token, I would like to make sure once the refresh token is also expiring that I would trigger the invalidation of the session.
What's the best way to do this and where?

Thank you very much for your help! Very appreciated :)

**Comment by vwatel** [comment]
@balazsorban44 Would you please be able to help me here? thank you 🙏🏻

**Comment by balazsorban44** [comment]
Not sure what provider you use, but some of them return a `refresh_token_expires_in` value that you could use to track when a refresh token is not valid anymore. Although your refresh endpoint will likely fail the refresh anyway if an old token is sent, so you could just invalidate the session then.

**Comment by vwatel** [comment]
The issue is not how to know when it expires, this part is fine and I implemented our own business logic.
The question is what to do to "invalidate the session" manually?
Can we somehow redirect to sign out endpoint, is there a method we can call to invalidate the session, etc

Thank you for your help!

**Comment by balazsorban44** [comment]
Currently, you can just return an empty object from the `jwt` callback, or an error code, which you can use to sign the user out or execute other logic: https://next-auth.js.org/tutorials/refresh-token-rotation#client-side

**Comment by vwatel** [comment]
Ok, I will check this out.
Thank you again @balazsorban44 for your help on this, this is very appreciated and help us delivering the project on time (very tight deadline).

**Comment by ekeric13** [comment]
I also would like to avoid having the cookie maxAge/expires attribute be updated every time there is a call to the jwt callback.

> you can implement some logic in your app that tracks the session creation and invalidates it after the expiry date of your choice.

So I implemented some logic with redis that would just setEx the cookie for x seconds and I check redis in the jwt callback. If redis returns null I know the cookie has expired. 

> you can just return an empty object from the jwt callback, or an error code,

So I throw an error if there is nothing in redis and then when I refresh the page i get redirected back to the sign-in page. Is there a way to grab the error I threw and have that available as a prop? Usually the errors are added as query params and in `getServerSideProps` I can do context.query.error... but that doesn't seem to be the case here.
