### ISSUE TITLE
releasing packages should respect the dependency graph

### ISSUE THREAD

**Issue by xmlking** [nextauthjs/next-auth#6226]
### Question 💬

is there any specify reason @auth/sveltekit  depends on older version for ` @auth/core 0.2.2` ?
```shell
pnpm why @auth/core
```
<img width="474" alt="image" src="https://user-images.githubusercontent.com/627951/210030160-40be9531-4a7a-46aa-8d05-0cc9e4ee114a.png">

### How to reproduce ☕️

```shell
pnpm why @auth/core
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Looks like #6068 was not fixed after all.

In this: https://github.com/nextauthjs/next-auth/actions/runs/3772067552/jobs/6412870247 SvelteKit Auth got released first.

**Comment by xmlking** [comment]
I will take a look, 
While researching find this options 
https://github.com/changesets/changesets/issues/238#issuecomment-614286787

**Comment by xmlking** [comment]
Temp Workaround: Add to package.json
```json
	"pnpm": {
		"overrides": {
			"@auth/core": "latest"
		}
	},
``` 

https://github.com/xmlking/svelte-starter-kit/blob/main/package.json#L100-L104

**Comment by jameswoodley** [comment]
I've just hit this today, nigh on a year later, anything an outsider can do to help resolve this?

**Comment by balazsorban44** [comment]
I have a PR for this, tested locally: https://github.com/balazsorban44/monorepo-release/pull/9

will do some more testing.

Check out that PR's description to understand how it should work.
