### ISSUE TITLE
Unable to GET providers endpoint in local production build

### ISSUE THREAD

**Issue by karmaniverous** [nextauthjs/next-auth#6229]
### Environment

  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 4.64 GB / 15.76 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    next: ^12.2.2 => 12.3.4
    next-auth: ^4.18.4 => 4.18.4
    react: ^18.2.0 => 18.2.0

### Reproduction URL

https://github.com/karmaniverous/nextjs-template/tree/dev-nextauth-bug

### Describe the issue

This is a comprehensive Next.js project template.

NextAuth runs fine in dev (i.e. `next dev`) and when deployed to Vercel or AWS, but login fails when I run a local production build (i.e. `next build && next start`).

On investigation it turned out that the `/api/auth/providers` query is failing. 

### How to reproduce

1. Clone the bug branch with 
    ```bash
    git clone -b dev-nextauth-bug https://github.com/karmaniverous/nextjs-template.git
    ``` 

2. Open the repo dir & install dependencies with
    ```bash
    npm install
    ```

3. Create `.env.production.local` as described [here](https://karmanivero.us/blog/nextjs-template/#create-local-environment-variable-files). You only need to populate the `NEXTAUTH_SECRET` value. Any value will do.

4. Run `npm run dev` and [click here](http://localhost:3000/api/auth/providers) to run the providers endpoint on localhost. You should see:
    ```js
    {
      cognito: {
        id: "cognito",
        name: "Cognito",
        type: "oauth",
        signinUrl: "http://localhost:3000/api/auth/signin/cognito",
        callbackUrl: "http://localhost:3000/api/auth/callback/cognito"
      }
    }
    ```

    I added some code to expose the query headers & params, so you'll see those logged on the server side. This code also wraps the `NextAuth` function in a `try/catch` to intercept any errors, but there won't be any here.

5. [Click here](https://nextjs-template-preview.karmanivero.us/api/auth/providers) to run the providers endpoint in prod. You should see:
    ```js
    {
      cognito: {
        id: "cognito",
        name: "Cognito",
        type: "oauth",
        signinUrl: "https://nextjs-template-preview.karmanivero.us/api/auth/signin/cognito",
        callbackUrl: "https://nextjs-template-preview.karmanivero.us/api/auth/callback/cognito"
      }
    }
    ```

6. Now `Ctrl-C` to stop the dev server & create & run a local production build with 
    ```bash
    npm run build
    npm run start
    ```

7. [Click here](http://localhost:3000/api/auth/providers) to try the local providers endpoint again. Query headers & params will still get logged, but the endpoint will return a 400 error.

    Query headers & params are still getting logged, and the `NextAuth` function is NOT throwing an error. It's just returning a 400 response in local `prod`.

### Expected behavior

I should see the same response in local `prod` that I am seeing in local `dev`:

```js
{
  cognito: {
    id: "cognito",
    name: "Cognito",
    type: "oauth",
    signinUrl: "http://localhost:3000/api/auth/signin/cognito",
    callbackUrl: "http://localhost:3000/api/auth/callback/cognito"
  }
}
```

**Comment by balazsorban44** [comment]
Please simplify the reproduction, I am not able to run in easily.

**Comment by karmaniverous** [comment]
Simpler than THAT?? I spent an hour organizing this so you could do it in 5 minutes. 🙄

**Comment by balazsorban44** [comment]
There's a ton of unnecessary dependencies, code, modules etc that likely don't contribute to the issue but mKes the reproduction bloated.

I could not even get to run the build script successfully, as webpack was not installed when it's imported in the next Next.js config (which is likely a mistake anyway).

Please eliminate anything that does not contribute to the issue.
