### ISSUE TITLE
Email authentication

### ISSUE THREAD

**Issue by tuan-m-ng** [nextauthjs/next-auth#623]
When using **next-auth-example**, I provided my credentials in the file `.env`. After typing in an email in the sign-in page, I got the message **Check your email address** indicating success. However, I got the following message from the server: `https://next-auth.js.org/errors#signin_email_error`, and moreover, Gmail sent me a security alert. 

I think there should be no indication of success in whichever case when an email could not be sent. 

By the way, if you have any comment about the Gmail security alert I'd really appreciate it.

**Comment by iaincollins** [comment]
This indicates an issue with your SMTP account.

We already display an error message to the client and in the logs if the SMTP relay service returns an error.

Please use the issue template to submit issues in future.

**Comment by tuan-m-ng** [comment]
Thanks for the suggestion about the issue template!

I still think it's a bug since an email was not sent but the frontend ui still showed the message **Check your email address**. 

I'm trying to get more familiar with **next-auth** and I'll report more in case.
