### ISSUE TITLE
Session value for SessionProvider is not defined anywhere.

### ISSUE THREAD

**Issue by cristianbuta** [nextauthjs/next-auth#6233]
### Question 💬

I was going through the official docs for getting started with this https://next-auth.js.org/getting-started/example and it looks like there is some magic happening here with session being passed to _app.tsx out of nowhere.

```
import { SessionProvider } from "next-auth/react"
export default function App({
  Component,
  pageProps: { session, ...pageProps },
}) {
  return (
    <SessionProvider session={session}>
      <Component {...pageProps} />
    </SessionProvider>
  )
}
```

Can someone clarify where is the value for session being defined and how App function has access to it?

### How to reproduce ☕️

https://github.com/nextauthjs/next-auth-example/blob/main/pages/_app.tsx

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
https://next-auth.js.org/getting-started/client#sessionprovider 

> This only works on pages where you provide the correct pageProps, however. This is normally done in getInitialProps or getServerSideProps...

Funnily enough, if you search issues with the word "magical", https://github.com/nextauthjs/next-auth/issues/1130#issuecomment-761689414 and https://github.com/nextauthjs/next-auth/issues/1132#issue-787565643 will come up, saying it's nothing magical

**Comment by cristianbuta** [comment]
> https://next-auth.js.org/getting-started/client#sessionprovider
> 
> > This only works on pages where you provide the correct pageProps, however. This is normally done in getInitialProps or getServerSideProps...
> 
> Funnily enough, if you search issues with the word "magical", [#1130 (comment)](https://github.com/nextauthjs/next-auth/issues/1130#issuecomment-761689414) and [#1132 (comment)](https://github.com/nextauthjs/next-auth/issues/1132#issue-787565643) will come up, talking exactly about this, and how it's nothing magical.

Thank you, that clarified it & should be added to the oficial docs to make it more explicit.

**Comment by balazsorban44** [comment]
I did link to the original documentation as well. If you have a suggestion on how to improve it, please open a PR.

As for the issues, please don't ignore maintainer's advice when opening new issues. This is pinned on the [top of the issues](https://github.com/nextauthjs/next-auth/issues): 
![image](https://user-images.githubusercontent.com/18369201/210220413-f215fee6-f56c-4727-b834-0b5904f6c53c.png)
