### ISSUE TITLE
Fetching the session in api routes and app directory

### ISSUE THREAD

**Issue by janrtvld** [nextauthjs/next-auth#6267]
### Question 💬

Hey,

So i have a question about working with the `unstable_getServerSession` in Next 13. 

In server components you can call it like this ([docs](https://next-auth.js.org/configuration/nextjs#in-app-directory)):
`const session = await unstable_getServerSession(authOptions)`

While in the api routes directory you have to call it with the request and response objects ([docs](https://next-auth.js.org/configuration/nextjs#in-api-routes)):
`const session = await unstable_getServerSession(req, res, authOptions)`

What is the reason for this difference? They are both happening on the server so why does the api route also needs the request and response objects?

I have a function that gets the user session and fetches data based on the user id. But i can not share this function between server components and the api routes as the process of getting the session is different. 

Thanks in advance!

### How to reproduce ☕️

-

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Both needs the same info, but we get them from different contexts:

https://github.com/nextauthjs/next-auth/blob/39657bf06c89f314673406f760f782e183287392/packages/next-auth/src/next/index.ts#L136

**Comment by janrtvld** [comment]
Thanks for the answer! 

So, why aren't api routes just normal server components? i.e. why the difference in fetching the session?

**Comment by balazsorban44** [comment]
They are different concepts with different goals.:

https://beta.nextjs.org/docs/rendering/server-and-client-components

https://beta.nextjs.org/docs/data-fetching/api-routes
