### ISSUE TITLE
Twitter provider sign in not working in production

### ISSUE THREAD

**Issue by poweroutlet2** [nextauthjs/next-auth#6304]
### Provider type

Twitter

### Environment

  System:
    OS: Linux 5.10 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 5.66 GB / 7.71 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.9.1 - /home/linuxbrew/.linuxbrew/bin/node
    Yarn: 1.22.17 - /mnt/c/Users/{Redacted}/AppData/Roaming/npm/yarn
    npm: 9.2.0 - /home/linuxbrew/.linuxbrew/bin/npm
  npmPackages:
    next: ^13.0.6 => 13.1.1 
    next-auth: ^4.15.0 => 4.18.7 
    react: ^18.2.0 => 18.2.0 

### Reproduction URL

https://github.com/nextauthjs/next-auth-example/blob/main/pages/api/auth/%5B...nextauth%5D.ts

### Describe the issue

Hello NextAuth team (or Authjs team I guess). This is my first time creating an issue, so please excuse any rookie mistakes. I've been having a problem with getting the Twitter provider working in my Next app, and it seems that the NextAuth example is having the same issue. I have my TwitterProvider setup just like the example [here](https://github.com/nextauthjs/next-auth-example/blob/main/pages/api/auth/%5B...nextauth%5D.ts), and I have an app set up on the Twitter Developer Portal with User authentication: 

![image](https://user-images.githubusercontent.com/32393047/210956866-4d28af75-4ca2-4a77-ae91-32b2e8e7a360.png)

I have environment variables for the `TWITTER_CLIENT_ID` and `TWITTER_CLIENT_SECRET` set to the API key and secret provided by Twitter, and have set the `NEXTAUTH_URL` in production to my [Vercel deployment URL](https://threads-app.vercel.app/). Now, this works great in development on http://localhost:3000/. I'm able to click the sign button which redirects me to the Twitter page asking me to authorize the app. However, in production I'm not redirected to Twitter at all and instead get sent to a page with this message: 

![image](https://user-images.githubusercontent.com/32393047/210958022-6fdb234c-13a5-4c0f-9d5a-44cebbf31a0c.png)

Accompanied by this function log in Vercel:
![image](https://user-images.githubusercontent.com/32393047/210958451-28b2dff0-64d4-4e31-8210-a8690fb6c226.png)

I've tried a few things like regenerating my keys, supplying a `NEXTAUTH_SECRET`, using the OAuth2 keys supplied by Twitter, and playing around with different Twitter accounts that are signed in/out. Then I noticed that the NextAuth and Authjs example apps have the same issue when logging in via Twitter, which makes me think it's an issue with NextAuth or with the Twitter Developer Portal. Please let me know if I'm missing something, I can provide more information and would like to help out any way I can.

### How to reproduce

My Next app: 
1. Navigate to https://threads-app.vercel.app/
2. Click "sign in with twitter" on the top right.

NextAuth example app:
1. Navigate to https://next-auth-example.vercel.app/
2. Click "Sign In" on the top right.
3. Click "Sign in with Twitter (Legacy)"

### Expected behavior

Clicking the sign in with twitter button should redirect to the Twitter authentication page and then back to the app after authenticating.

**Comment by balazsorban44** [comment]
Indeed, @erhankaradeniz is correct, check your credentials, and that your callback URL is set correctly.  We updated the credentials on https://next-auth-example.vercel.app, but it's now fixed, and the login works fine.

**Comment by poweroutlet2** [comment]
I was so sure that I had copied over my keys over correctly... But sure enough, I re-copied them over to Vercel and it works! I was also not redeploying after environment variable changes when I was initially troubleshooting, which looks like is necessary. Thanks for the quick responses :)

**Comment by shaikharfan7** [comment]
@poweroutlet2 , I have a similar issue. Would love to connect over DMs. Where can we connect?

**Comment by Ezzmahdi** [comment]
I have the same issue, I tried to change the env variables, but nothing worked, anyone could help?

**Comment by cupid20103** [comment]
Yeah, my project working well on the local but not in production.
I think, this is issue for auth.js for now 😢
