### ISSUE TITLE
Provider Logos links broken

### ISSUE THREAD

**Issue by jodok** [nextauthjs/next-auth#6313]
### Environment

```
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M2
    Memory: 94.48 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Brave Browser: 108.1.46.144
    Chrome: 108.0.5359.124
    Firefox: 104.0.2
    Safari: 16.2
  npmPackages:
    next: 12.2.5 => 12.2.5
    next-auth: ^4.18.7 => 4.18.7
    react: 18.2.0 => 18.2.0
```

### Reproduction URL

https://raw.githubusercontent.com/nextauthjs/next-auth/main/packages/next-auth/provider-logos/twitter-dark.svg

### Describe the issue

it seems the links to the provider logos are all broken:
e.g.: twitter is referenced here: https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/providers/twitter.ts#L123 and points to: 
https://raw.githubusercontent.com/nextauthjs/next-auth/main/packages/next-auth/provider-logos/twitter-dark.svg

which can't be found. the same applies for all other providers.

### How to reproduce

just open the url

### Expected behavior

i expect to see the twitter logo

**Comment by balazsorban44** [comment]
Could you upgrade to 4.18.8? It should be fixed there.

**Comment by balazsorban44** [comment]
For context, logos have been moved to https://github.com/nextauthjs/next-auth/tree/main/docs/static/img/providers so they scale better.

**Comment by xmlking** [comment]
same issue for `auth/sveltekit`  
should we wait for next release?  @balazsorban44

**Comment by balazsorban44** [comment]
oh yeah, I forgot to release core and frameworks.

The source is already updated https://github.com/nextauthjs/next-auth/blob/3539a356010b952fefcad2a02ae3d60e2cba992d/packages/core/src/lib/pages/signin.tsx#L62

**Comment by pavinduLakshan** [comment]
> For context, logos have been moved to https://github.com/nextauthjs/next-auth/tree/main/docs/static/img/providers so they scale better by serving them from Vercel. Example https://authjs.dev/img/providers/twitter.svg

@balazsorban44 it would be great if you update the [docs](https://next-auth.js.org/configuration/providers/oauth#adding-a-new-built-in-provider) as well :)

**Comment by xmlking** [comment]
I am using latest aurhjs/svelteKit and the generated routes still pointing to old images
Thinking @balazsorban44 has to tag and release svelteKit module

**Comment by balazsorban44** [comment]
Pinning this as people don't seem to care about searching issues before opening a new one. <picture data-single-emoji=":sad_parrot:" title=":sad_parrot:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..G6BvTGFnosIlQ1bG.Oqxou9rmAHZ_fNpaUaLpoM8PB8wEpZBahvCCN330W0DgN9jyO5zjR5iUfn2BC6i1_PrxqiMgS-HRQM9OLQP6EjYLqukrtLtu-MZMgbvXCNwmox02Lcc2Z4ja.lg9BRn2eOqmvCDOyTgeruA" alt=":sad_parrot:" align="absmiddle"></picture>

**Comment by idc77** [comment]
It's next week, just saying :D no pressure

**Comment by dannycallaghan** [comment]
Still not working for me in 4.20.1

**Comment by halpetr** [comment]
I have the same issue with v4.2.0 using google provider and PrismaAdapter.

**Comment by Robokishan** [comment]
using ^4.24.5 but same issue [https://upload.wikimedia.org/wikipedia/commons/5/53/Google_%22G%22_Logo.svg](https://upload.wikimedia.org/wikipedia/commons/5/53/Google_%22G%22_Logo.svg)

**Comment by KishorJena** [comment]
> For context, logos have been moved to https://github.com/nextauthjs/next-auth/tree/main/docs/static/img/providers so they scale better by serving them from Vercel. Example https://authjs.dev/img/providers/twitter.svg

Given path `(...static/img/providers)` is 404 now
now its `...public/img/providers`
