### ISSUE TITLE
Custom signIn documentation is misleading

### ISSUE THREAD

**Issue by colin4554** [nextauthjs/next-auth#6316]
### What is the improvement or update you wish to see?

Include a note that explicitly says the id must be the same and specified for the custom signIn function and in the providers.

I would include this note at the bottom of this page: https://next-auth.js.org/configuration/pages#credentials-sign-in. 

### Is there any context that might help us understand?

Other documentation surrounding credentials uses different IDs without mentioning their impact, implying it is just an internal measure to distinguish providers. For instance here: https://next-auth.js.org/providers/credentials.  Or not even included like here: https://next-auth.js.org/configuration/providers/credentials. 

Other people have run into this error: https://stackoverflow.com/questions/69424685/custom-sign-in-page-not-redirecting-correctly-in-next-auth.

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/configuration/pages

**Comment by balazsorban44** [comment]
You don't need to change anything about the default `id` which is defined here:

https://github.com/nextauthjs/next-auth/blob/03881bf98f62fb95b811287ee19aa3c0602003ec/packages/next-auth/src/providers/credentials.ts#L38

`name` does not affect how you call the `signIn` method.
