### ISSUE TITLE
Captcha and validation in the email provider, magic link

### ISSUE THREAD

**Issue by Barbieroalex** [nextauthjs/next-auth#6318]
### Description 📓

Is there a way to add extra validation with zod and a capcha?

### How to reproduce ☕️

the purpose of the feature:
Prevent some malicious user from wanting to overload the database.

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
as for captcha, that would require a custom sign in page, but you can validate email addresses already:

Normalize emails:
https://next-auth.js.org/providers/email#normalizing-the-email-address

Disallow emails (before sending):
https://next-auth.js.org/configuration/callbacks#sign-in-callback
