### ISSUE TITLE
How to have custom UX after route `verify-request` for Email provider after email form POST

### ISSUE THREAD

**Issue by SharadKumar** [nextauthjs/next-auth#632]
**Your question**
I have custom signin email form, posting through the client. After POST, I want to show custom UX and not the next-auth UI/route.

**What are you trying to do**
For production use, I need to have custom page or dialog/modal to confirm the email form submission.

![image](https://user-images.githubusercontent.com/5488144/91971513-ab018880-ed5c-11ea-8247-c4ceaf1f9992.png)

I notice the following has the route result hardcoded and not configurable. Is there an existing way or it requires change?

Last line:
https://github.com/nextauthjs/next-auth/blob/main/src/server/routes/signin.js#L34-L73

**Feedback**

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
Hmm the documentation says there is a [verifyRequest ](https://next-auth.js.org/configuration/pages) custom page.

I actually had to check as I couldn't remember if that was supported, but it's in the documentation and there seems to be code to support the option (the intent is certainly that all pages can be overridden so it's fully customisable).

So, if you specify a custom URL for the `verifyRequest` page (e.g. `pages: { verifyRequest: '/email-verified' }` in your options) it should do what you want.

**Comment by SharadKumar** [comment]
Damn! I am sorry, I should have found it.
Thank you @iaincollins
