### ISSUE TITLE
Cookies are not handled properly in the SolidStart integration

### ISSUE THREAD

**Issue by gabor-boros** [nextauthjs/next-auth#6321]
### Environment

```
  System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 173.56 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Brave Browser: 108.1.46.144
    Firefox Developer Edition: 109.0
    Safari: 16.2
```

### Reproduction URL

https://github.com/nextauthjs/solid-start-auth-example

### Describe the issue

Due to a [SolidJS bug](https://github.com/solidjs/solid-start/issues/293) that prevents setting multiple `Set-Cookie` headers, the SolidStart integration [cannot be used](https://github.com/nextauthjs/next-auth/blob/3539a356010b952fefcad2a02ae3d60e2cba992d/packages/frameworks-solid-start/src/index.ts#L25-L43) with any provider that requires the `state` query parameter based on [RFC-6819](https://www.rfc-editor.org/rfc/rfc6819#section-4.4.1.8) to avoid CSRF attack against `redirect-uri`.

Although this is primarily a SolidJS bug, it would worth to _at least_ note this in the documentation, though it may would worth a joined effort to fix the issue as suggested in a [comment](https://github.com/solidjs/solid-start/issues/293#issuecomment-1283406131) on the tracked SolidJS issue.

Please ping me if more details or a better reproduction is needed. I did not create a separate repo for reproduction as the linked bug and code are both acknowledge that this issue exists.

### How to reproduce

1. Create a new SolidStart project
2. Add Auth.js integration
3. Add a provider with the `checks: ["state"]` option
4. Try to sign in

The following error should be raised:

```
CallbackRouteError: State was missing from the cookies.
    at Module.callback (********/node_modules/@auth/core/lib/routes/callback.js:243:23)
    at async AuthInternal (********/node_modules/@auth/core/lib/index.js:52:38)
    at async Auth (********/node_modules/@auth/core/index.js:95:30)
    at async ********/node_modules/@auth/solid-start/index.js:39:17
    at async Object.GET [as handler] (********/node_modules/@auth/solid-start/index.js:61:14)
    at async eval (/node_modules/solid-start/api/middleware.ts:21:16)
    at async eval (/node_modules/solid-start/entry-server/StartServer.tsx:45:12)
    at async devFetch (********/node_modules/solid-start/dev/server.js:45:12)
    at async startHandler (********/node_modules/solid-start/dev/server.js:112:20)
[auth][error][CallbackRouteError]: Read more at https://errors.authjs.dev#callbackrouteerror
```

### Expected behavior

The `next-auth.state` cookie should be set everywhere it is needed and the sign in flow should not raise any issues related to missing state cookie.

**Comment by balazsorban44** [comment]
This is a growing pain in any library that tries to be spec compliant and is super annoying to deal with, indeed

I wonder is something like this method could be used in SolidJS to deal with the issue.

https://github.com/nextauthjs/next-auth/blob/3539a356010b952fefcad2a02ae3d60e2cba992d/packages/next-auth/src/utils/node.ts#L73

cc @OrJDev

**Comment by balazsorban44** [comment]
For what it's worth, PKCE should work in the SolidStart Auth, as there is some custom code for it. Most modern providers will support this OAuth 2 extension to prevent attacks during the auth flow.

**Comment by OrJDev** [comment]
> This is a growing pain in any library that tries to be spec compliant and is super annoying to deal with, indeed
> 
> 
> 
> I wonder is something like this method could be used in SolidJS to deal with the issue.
> 
> 
> 
> https://github.com/nextauthjs/next-auth/blob/3539a356010b952fefcad2a02ae3d60e2cba992d/packages/next-auth/src/utils/node.ts#L73
> 
> 
> 
> cc @OrJDev

I will discuss this with Nikhil and Ryan, for now please try avoiding using anything that appends more cookies. I will try to play a few tricks but for now -  https://github.com/solidjs/solid-start/issues/293

**Comment by OrJDev** [comment]
fixed  https://github.com/nextauthjs/next-auth/pull/6248/commits/a743a4d9e46f0e2a080d838ef28e131d28fd33aa
wait for @balazsorban44 to merge this pr https://github.com/nextauthjs/next-auth/pull/6248

**Comment by balazsorban44** [comment]
the above patch is nice but it's not scalable as it does not count for  session cookie chunking (when the cookie size exceeds 4kb, split it), and custom cookie names via https://authjs.dev/reference/core/interfaces/main.AuthConfig#cookies

IMO this should be fixed in SolidStart as soon as possible.

**Comment by OrJDev** [comment]
Ye i see what you mean, i want to keep it as is for now until its fixed in solid-start (either that or mark things as not supported - which is something we don't want). Should be useful in most cases.

**Comment by OrJDev** [comment]
@balazsorban44  added support for nonce aswell and reduced the array length by 2, i think it now supports all defaults?
https://github.com/nextauthjs/next-auth/pull/6248/commits/c47f065f23cefdce590fd9f9f2b5b3d4fbf85d74

**Comment by OrJDev** [comment]
this was fixed by the solid-start team - in https://github.com/solidjs/solid-start/commit/dcdb547fc27aeebe403b809e0baa8163fd3caedc

and https://github.com/nextauthjs/next-auth/pull/6248/commits/20bc4325ad33580902469068aaa43262a1797c3e

can be closed.
