### ISSUE TITLE
Why is the prisma client excluded from production environment when following the prisma adapter setup code provided in the docs?

### ISSUE THREAD

**Issue by jgbijlsma** [nextauthjs/next-auth#6324]
### Question 💬

I've used [this](https://next-auth.js.org/adapters/prisma) code to setup a prisma client for my nextauth app. 

```
import { PrismaClient } from "@prisma/client"

declare global {
  var prisma: PrismaClient | undefined
}

const client = globalThis.prisma || new PrismaClient()
if (process.env.NODE_ENV !== "production") globalThis.prisma = client

export default client
```

The client is explicitly excluded from the production environment.
Why?

I need prisma in my production environment just as much as I need it in another environment. Is there a specific extra step to deploy to production with the prisma adapter that I've missed? Right now I've just removed the if statement to provide the client on globalThis in production. Is this a bad practise?

[Here is a repo](https://github.com/jgbijlsma/nextauth-prismaAdapter-issue) showing a test project with this issue as described below in *How to reproduce*

### How to reproduce ☕️

1. Create a new NextJS app with typescript using npx create-next-app
2. Add nextAuth as described in [the docs](https://next-auth.js.org/getting-started/example)
3. Add and setup prisma as described in [the docs](https://next-auth.js.org/adapters/prisma)
4. Make an API endpoint that uses prisma:

**/pages/api/users.ts**
```
import { NextApiRequest, NextApiResponse } from "next";

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const users = await prisma?.user.findMany();

  res.send(users);
}
```
5. Run the app in development with `npm run dev`
6. Use /api/auth/signin to create a new user (i used github for this test)
7. Prisma works when requesting the custom endpoint `/api/users`.
8. Run the app in production by building with `npm run build` and then running with `npm run start` 
9. Prisma is not defined when requesting `/api/users`. You will instead get the following error message: 
```
{
  "error": "prisma is not defined"
}
```

10. Remove `if (process.env.NODE_ENV !== "production")` from **lib/prismaClient.ts**, build and run again, and now prisma works in a production env.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
See https://www.prisma.io/docs/guides/database/troubleshooting-orm/help-articles/nextjs-prisma-client-dev-practices

**Comment by jgbijlsma** [comment]
Thanks! I did not realize that you are supposed to import the instantiated prisma client and not actually use the global.prisma instance. The global prisma is only there to ensure hot reloading does not create new PrismaClient instances.
