### ISSUE TITLE
Demo link in Identity Server 4 doesn't work

### ISSUE THREAD

**Issue by judicaelandria** [nextauthjs/next-auth#6349]
### What is the improvement or update you wish to see?

We have this link on the Identity Server page but it doesn't work ```https://demo.identityserver.io``` perhaps replacing it with a working link would be much appreciated

### Is there any context that might help us understand?

no, I think that's all

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/providers/identity-server4

**Comment by balazsorban44** [comment]
IdentityServer 4 is deprecated, they likely have stopped the demo server. Not much we can do, feel free to remove the link in a PR.

**Comment by judicaelandria** [comment]
@balazsorban44 the PR https://github.com/nextauthjs/next-auth/pull/6354
