### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by CITGuru** [nextauthjs/next-auth#636]
I am trying to setup Next Auth with MongoDB and I have everything set up, but I keep getting the errors below when I tried to visit the sign-in page or page auth pages:

```bash
UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
```
<img width="979" alt="Screen Shot 2020-09-03 at 11 38 43 AM" src="https://user-images.githubusercontent.com/16475846/92104973-07ef5400-edda-11ea-804c-a3baa9b260e0.png">

Any help why this is happening and how to fix it.

**Comment by iaincollins** [comment]
Hi there!

Do you have a file called `[...nextauth].js` in `pages/api/auth`?

I suspect not that is causing the error (maybe it's called something else?)

We could definitely handle this error better!

**Comment by aksperiod** [comment]
ughhhhh I just spent a while because it was called `[...nextAuth].js`

**Comment by iaincollins** [comment]
@aksperiod Ugh! Thanks for the feedback. That sounds like something we should catch, especially if multiple folks are running into it. Would be good to leave this open until there is PR or a ticket to capture the work to resolve it.

(e.g. display error / warning on console)

**Comment by CITGuru** [comment]
@iaincollins Yh I got it fixed. Thanks.

**Comment by iaincollins** [comment]
Awesome!

I've written this up as a feature request in #647 so we can help folks avoid running into this in future.
