### ISSUE TITLE
Re-open #2294: Make auth js vanilla js / front end framework agnostic 

### ISSUE THREAD

**Issue by vic-cekvenich** [nextauthjs/next-auth#6360]
### Description 📓

Re-open #2294: Make auth js vanilla js / front end framework agnostic 

### How to reproduce ☕️

Docs are for 3 FW/

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
This is what `@auth/core` is. Check out https://authjs.dev/reference/core/modules/main.
