### ISSUE TITLE
Overwrite default params

### ISSUE THREAD

**Issue by TheHellTower** [nextauthjs/next-auth#6366]
### Question 💬

Hello,

I seen that [default params(discord)](https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/providers/discord.ts#L29) already have a value, so I wanted to know, can we overwrite them by any way ?

Regards.

_I'm not really good at TS so I can't really help in maintaining this even if I would love to I would not like to make stupid mistakes._

### How to reproduce ☕️

None

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
https://next-auth.js.org/configuration/providers/oauth#override-default-options
