### ISSUE TITLE
NextAuth uses https://localhost:3000, when the production URL is different

### ISSUE THREAD

**Issue by Nemika-Haj** [nextauthjs/next-auth#6371]
### Question 💬

Hello!
I am having an issue with NextAuth, where when I try to sign in or sign out, it redirects me to `https://localhost:3000/api/auth/signin` and `https://localhost:3000/api/auth/signout`, even though the server's URL is different. I have set `NEXTAUTH_URL` in .env, but no luck. In fact, I still get a `[next-auth][warn][NEXTAUTH_URL]`, even after attempting to set a custom env property in `next.config.js` like so:
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  env: { NEXTAUTH_URL: "https://production-url.com" },
}

module.exports = nextConfig
```
The weird thing is that the entire code can read `NEXTAUTH_URL`, but NextAuth itself cannot.
In a nutshell, my goal is to find a way to change the URL NextAuth uses.

Here's my current code:
```typescript
import { NextAuthOptions } from "next-auth"
import NextAuth from "next-auth/next"
import DiscordProvider from "next-auth/providers/discord"
import { NextApiRequest, NextApiResponse } from "next/types"
import DotEnv from "dotenv"

DotEnv.config() // added this one to see if it would read NEXTAUTH_URL afterwards, but it doesn't work either.

function validateUser(userID: string | undefined) {
    const allowedUsers = (process.env.ALLOWED_AUTH_IDS as string).split(",")
    return userID && allowedUsers.includes(userID)
}

export const authOptions: NextAuthOptions = {
    providers: [
        DiscordProvider({
            clientId: "client-id",
            clientSecret: "client-secret",
        }),
    ],

    jwt: {
        secret: process.env.SECRET_KEY,
        maxAge: 30 * 24 * 60 * 60,
    },

    session: {
        strategy: "jwt"
    },

    secret: process.env.SECRET_KEY,

    callbacks: {
        async jwt(props) {

            return props.token
        },

        async session(props) {
            if(props.token && props.session) {
                props.session.user.authorized = validateUser(props.token.sub) as boolean
            }

            return props.session
        },

        async signIn(props) {
            if(props.user) {
                if(validateUser(props.user.id)) return true
            }

            return "/error/auth-not-allowed"
        },
    },
}

export default async function Auth(req: NextApiRequest, res: NextApiResponse) {

    return await NextAuth(req, res, authOptions)
}
```

### How to reproduce ☕️

Head over to https://bytestobits.dev/api/auth/signin and try to login

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by Nemika-Haj** [comment]
So - you won't be able to reproduce it unfortunately, because I edited next-auth in node_modules for the server to instead always use the production url. However I am still interested in why the issue exists in the first place.

**Comment by Nemika-Haj** [comment]
Yep figured it out 🤝
I had `AUTH_TRUSTED_HOST` specified in .env
It appears that if it is defined, there is a conflict, and NEXTAUTH_URL is ignored.
So removing it fixed it :)

**Comment by Nemika-Haj** [comment]
Yep figured it out 🤝
I had `AUTH_TRUSTED_HOST` specified in .env
It appears that if it is defined, there is a conflict, and NEXTAUTH_URL is ignored.
So removing it fixed it :)

**Comment by buinghiep-ptit** [comment]
have you solved it yet?

**Comment by Nemika-Haj** [comment]
@buinghiep-ptit https://github.com/nextauthjs/next-auth/issues/6371#issuecomment-1379657543

**Comment by piotr-blue-square** [comment]
I had similar issue on local machine when **SignIn** page was forcing forms to use **https** despite `NEXTAUTH_URL=http://localhost:3000`  set.
It was working well before I set up a Vercel deployment. I found out that when you pull Vercel envs on local machine it sets `VERCEL="1"` and it makes NextAuth use **https**. 
I have just commented it out and SignIn page works well (on just http).

**Comment by marcklingen** [comment]
Thanks @piotr-blue-square, had the same issue. Removing `VERCEL="1"` fixed it. As I pull secrets via `vercel env pull` it would be great if VERCEL=1 does not have this effect on localhost

**Comment by FrBosquet** [comment]
@marcklingen that solved the issue for me! I looked around to see what does "VERCEL" states for, as this is going to break development environment every time I pull vars. Any insights on this?

**Comment by whelamc** [comment]
@piotr-blue-square so thankfull.Removing the params in env can fixed it,and make me hate it.

**Comment by davidlygagnon** [comment]
Thanks I ran into the same issue and commenting out `VERCEL` worked for now.

**Comment by nidhish-srivastava** [comment]
`
export const authConfig = {
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID ?? "",
      clientSecret: process.env.GOOGLE_CLIENT_SECRET ?? "",
    })
  ],
    callbacks: {
      async session({ session}) {
        let id = await userExists(session.user.email);
        if (id==null) {
          id = await createUser(session.user)
        }
        session.id = id;
        return session
      }
    },
};

export const {
  handlers: { GET, POST },
  auth,
  signIn,
  signOut,
} = NextAuth(authConfig);`

**Comment by brunogcarneiro** [comment]
I have the same problem when deploying to Amplify. However, I don't have AUTH_TRUSTED_HOST specified anywhere. I'm believe that I will be forced to use [Amplify Auth System](https://docs.amplify.aws/react/build-a-backend/auth/set-up-auth/)

**Comment by NedxLab** [comment]
I have the same issue with amplify, what's funny is that when I change my env locally and try to login, it still takes in my local env value
