### ISSUE TITLE
Missing logo images on /api/auth/signin/email

### ISSUE THREAD

**Issue by lassegit** [nextauthjs/next-auth#6375]
### Environment

Logos are missing on the sign in form, example: https://aihelperbot.com/api/auth/signin/email

 I run `"next-auth": "4.18.7"`.

### Reproduction URL

https://aihelperbot.com/api/auth/signin/email

### Describe the issue

Images are missing.

### How to reproduce

Go to the URL.

### Expected behavior

Should display logo images for the different providers or no images at all.

**Comment by balazsorban44** [comment]
Duplicate of #6313
