### ISSUE TITLE
Use `useSession` in a monorepo setup

### ISSUE THREAD

**Issue by der-daniel** [nextauthjs/next-auth#6378]
### Question 💬

Hi,

I have a monorepo setup with multiple `next.js` frontends. I want to use the `useSession` hooks inside an api package that make web calls via `axios`.

Inside this package I have installed `next-auth` as a peer dependency. This code looks like this:

```ts
getAllItems: async () => {
  const { data } = useSession()
  return (await axios.get(endpoint)).data
},
```

Importing this package into my `next.js` frontend gives me the error 

```Error: [next-auth]: `useSession` must be wrapped in a <SessionProvider />```

My `_app.ts` implements this `SessionProvider` correctly as this error does not occur if I use `useSession` directly in my frontend.

Somehow `useSession` cannot pick up the context from the frontend if it is abstracted into a separate package.

Any ideas or hints how to make this work in a monorepo setup?

JMJ

**Comment by der-daniel** [comment]
Thanks for the reply.

I also expect it to be a wrong setup somehow.

Can you elaborate why axios is a bad choice for making an authenticated web request.

Moreover, why should `getSession` be a good fit, if in the end, I would need to make a second web request via `getSession` before I actually make a web request to my backend.

**Comment by balazsorban44** [comment]
Personal opinion, but axios is generally a bad choice, IMO. We have `fetch` now.

Usually, you won't even need `getSession` if you are making requests to the app's backend, where you can read the session already. Otherwsie staying in react with `useSession` is probably better. Hard to tell without your code though what the most ideal thing would be.
