### ISSUE TITLE
Cannot login when using custom page with credentials provider

### ISSUE THREAD

**Issue by ilyaryabchinski** [nextauthjs/next-auth#6384]
### Provider type

Credentials

### Environment

 System:
    OS: macOS 13.0
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 86.11 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 2022.05.23.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 103.0.2
    Safari: 16.1
  npmPackages:
    next: 13.1.2 => 13.1.2 
    next-auth: ^4.18.8 => 4.18.8 
    react: 18.2.0 => 18.2.0 

### Reproduction URL

https://github.com/ilyaryabchinski/next-auth-credentials-custom-page-issue

### Describe the issue

When trying to log in, the page got refreshed and the auth cookie was set and cleared after a couple of seconds. Redirect to the index page and authentication doesn't work properly.

### How to reproduce

1. Navigate to the index page
2. Press the "Sign In" button
3. Enter a random email and password and press the login button

### Expected behavior

I expect to be redirected back to the index page and the auth cookie to be set and NOT cleared

**Comment by balazsorban44** [comment]
the issue is this line. you need to call `event.preventDefault()`

See https://reactjs.org/docs/handling-events.html

**Comment by ilyaryabchinski** [comment]
But I use react-hook-form, which prevents the default behavior of the event. So it's NextAuth that makes the redirect. Could you please double check that @balazsorban44 🙏

**Comment by balazsorban44** [comment]
Have you tried removing `react-hook-form` to see if that works? If so, the issue might be with your lib setup.

**Comment by ilyaryabchinski** [comment]
Yes, I tried removing `react-hook-form` and the issue still remains. You can find it in the last commit in the example repo I created: https://github.com/ilyaryabchinski/next-auth-credentials-custom-page-issue

**Comment by ilyaryabchinski** [comment]
I also tried commenting `pages` section in the `[...nextauth].ts` and tested it with the default Next-Auth page. The result is the same :( @balazsorban44 Could you please check the repo?
