### ISSUE TITLE
Twitter provider - OAuth 2.0 - Authorise app page keep asking for Authorisation

### ISSUE THREAD

**Issue by spavlovic77** [nextauthjs/next-auth#6386]
### Environment

Hello, i have successfully implemented NextAuth/Twitter using v2.

I have only one problem which I can not solve. After Log out and trying to Log in again, I am still forced to click on Authorise app button.

Steps:
1. Log in
2. Authorise app - clicked on Authorise app
3. Log out
4. Log in
5. Authorise page keeps asking for Authorisation (as if all credentials have been revoked, probably)

### Reproduction URL

https://github.com/nextauthjs/next-auth

### Describe the issue

Hello, i have successfully implemented NextAuth/Twitter using v2.

I have only one problem which I can not solve. After Log out and trying to Log in again, I am still forced to click on Authorise app button.

Steps:
1. Log in
2. Authorise app - clicked on Authorise app
3. Log out
4. Log in
5. Authorise page keeps asking for Authorisation (as if all credentials have been revoked, probably)

### How to reproduce

Steps:
1. Log in
2. Authorise app - clicked on Authorise app
3. Log out
4. Log in
5. Authorise page keeps asking for Authorisation (as if all credentials have been revoked, probably)

### Expected behavior

Likewise in v1, I do not need to Authorise app every login.

**Comment by balazsorban44** [comment]
This is an upstream issue, nothing we can do. I've already reached out to Twitter about it, with the recent events, not sure when/if they will look into it.
