### ISSUE TITLE
Custom Session Callback type

### ISSUE THREAD

**Issue by jahirfiquitiva** [nextauthjs/next-auth#6392]
### Question 💬

Hi, I'm trying to modify the session callback so that it includes the current user id, just as explained in [the docs](https://next-auth.js.org/configuration/callbacks#session-callback)

![Shot 2023-01-14 at 11 15 25@2x](https://user-images.githubusercontent.com/10360816/212482846-8c14b4f5-02ff-489c-af86-a4e39374ae97.png)

Anyway, when accessing the user id like `session?.user?.id` TypeScript complains that field/property does not exist.

How could I make sure that TypeScript recognizes it correctly?

### How to reproduce ☕️

Overwrite the session callback
```typescript
...

  callbacks: {
    session: async ({ session, user }) => {
      if (session?.user) {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        session.user.id = user.id
      }
      return session
    },
  },
...
```

Then try accessing the user id, example:
```typescript
const { data: session } = useSession()
const { user } = session || {}
const { id } = user
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
https://next-auth.js.org/getting-started/typescript
