### ISSUE TITLE
next-auth with node 19.4.0

### ISSUE THREAD

**Issue by SomiDivian** [nextauthjs/next-auth#6404]
### Question 💬

```js
error next-auth@4.18.8: The engine "node" is incompatible with this module. Expected version "^12.19.0 || ^14.15.0 || ^16.13.0 || ^18.12.0". Got "19.4.0"
```

I added this to `package.json` but still not working

```json
  "engines": {
    "node": ">=14"
  }
```

### How to reproduce ☕️

`yarn add next-auth`

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by moigamijunior** [comment]
It sounds like the issue is with your node installed on the computer. Try `node --version`. If it's a truly different version, you can try to upload/downgrade it to the specific version.

**Comment by balazsorban44** [comment]
this comes from https://github.com/nextauthjs/next-auth/blob/ba2711d2794f3743ae655c56286903f0a989191d/packages/next-auth/package.json#L132

care to open a PR to add node 19 there?

**Comment by ancoleman** [comment]
I can report the same exact issue, I'm running node 19.4.0 and next-auth reports back it is not supported.
