### ISSUE TITLE
Unable to use @auth/core with node.js frameworks like express/hapi

### ISSUE THREAD

**Issue by sirajulm** [nextauthjs/next-auth#6417]
### Environment

System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 68.06 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
    Safari: 16.2

### Reproduction URL

NA

### Describe the issue

I'm trying to use it with Node.Js frameworks like Express or Hapi.
Unfortunately, I am not able to proceed further due to error finding `crypto` API. If I'm not mistaken the current implementation works only on Edge workers which probably have `lib-dom` available to access the `crypto` API.

Below is a bare minimum code for reproduction

```javascript
import { Auth } from "@auth/core";
import Github from "@auth/core/providers/github";

export const test = async () => {
  const request = new Request("http://www.example.org/signin");
  const response = await Auth(request, {
    providers: [
      Github({
        clientId: "Test",
        clientSecret: "Test",
      }),
    ],
    secret: "test",
    trustHost: true,
  });

  console.log("@here", response);
};

test();
```

The above code throws the below error, since in node.js crypto mode need to be imported explicitly, which unfortunarely cannot be done since the error is within the library.

```log
node_modules/@auth/core/lib/init.js:53
            generateSessionToken: crypto.randomUUID,
                                  ^
ReferenceError: crypto is not defined
```
Let me know if there is a work around for this or will this be fixed in the future release?

### How to reproduce

Minimal code example provided above

### Expected behavior

Since the library is intended to be Runtime agnostic, this is a potential bug.

<img width="339" alt="image" src="https://user-images.githubusercontent.com/2260996/212752835-950ed90b-4fee-4d97-9545-23b87114f74a.png">

**Comment by balazsorban44** [comment]
You'll need at least Node 18 that includes the crypto web API in `globalThis` or polyfill it yourself. Polyfills are out of scope for this package.

**Comment by sirajulm** [comment]
Thank you. I got it fixed by moving to node 19 and work without issues. 

With current lts version it is not possible even to use `require('node:crypto').webcrypto`, I'd have to do something ugly otherwise like `globalThis.crypto ||=require('node:crypto').webcrypto`.

I'm fine with upgrading to 19 for th timebeing, and hope by the time Authjs releases first stable version, node 20 would be released.

**Comment by balazsorban44** [comment]
It's not ugly, `globalThis.crypto ??= require('node:crypto').webcrypto` is likely the cleanest way to get the Web Crypto API that ships with Node.js on the global object.

Much better than random third-party polyfills out there. :wink:

**Comment by sirajulm** [comment]
Node.js flag look better. I didn't knew about it. Thanks!

I agree `globalThis` is better than polyfilling the module. I had a very hard time trying to make that line of code to work in typescript. the compiler consistently kept complaining about type mismatch between `require('node:crypto')` and `Crypto`

I'm happy that with that it is working fine with the flag or nodejs:current 🙂
