### ISSUE TITLE
Cannot POST /api/auth/callback/credentials

### ISSUE THREAD

**Issue by dzinks2009** [nextauthjs/next-auth#642]
**Your question**
Cannot POST /api/auth/callback/credentials

**What are you trying to do**
Whenever I try to log in, I get the post error.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [X] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [X] Did not find the example project helpful

```
<form method='post' action='/api/auth/callback/credentials' className="account-form">
```

For example, when I try to get the csrf token, it works fine.

NextAuth config:
```
const options = {
    site: 'http://localhost:3000/api/auth',
    providers: [
        Providers.Credentials({
            name: 'Credentials',
            credentials: {
                username: { label: "Username", type: "text", placeholder: "" },
                password: {  label: "Password", type: "password" }
            },
            authorize: async (credentials) => {
                const user = { id: 1, name: 'J Smith', email: 'jsmith@example.com' }

                if (user) {
                    return Promise.resolve(user)
                } else {
                    return Promise.resolve(null)
                }
            }
        })
    ],
    callbacks: {
        signIn: async (user, account, profile) => {
            return Promise.resolve(true)
        },
        session: async (session, user) => {
            session.foo = 'bar' // Add property to session
            return Promise.resolve(session)
        },
        credentials: async( user,acount,profile) => {
          return Promise.resolve(true)
        },
        redirect: async (url, baseUrl) => {
            return url.startsWith(baseUrl)
                ? Promise.resolve(url)
                : Promise.resolve(baseUrl)
        }
    },
    session: {
        jwt: true,
    },
    jwt: {
        secret: "secret",
        encryption: true
    },
    database: {
        type: 'mysql',
        host: process.env.DB_HOST,
        port: 3306,
        username: process.env.DB_USER,
        password: process.env.DB_PASS,
        database: process.env.DB_TABLE
    },
    debug: true,
}
```

I tried everything, and also the documentation doesn't help since I can't find what I'm looking for particularly.

**Comment by iaincollins** [comment]
You can find a couple of examples of ways you can create a custom credentials sign in page:
https://next-auth.js.org/configuration/pages#credentials-sign-in

**Comment by dzinks2009** [comment]
> You can find a couple of examples of ways you can create a custom credentials sign in page:
> https://next-auth.js.org/configuration/pages#credentials-sign-in

In my nextauth config I have
```
    pages: {
        signIn: '/login',
    }
```
and I have that page located in pages/login.js, is that correct?
The form looks like this:
```
                          <form method='post' action='/api/auth/callback/credentials' className="account-form">
                              <div className="form-group">
                                  <label htmlFor="sign-up">Email lub Nazwa Użytkownika</label>
                                  <input type="text" placeholder="Email lub Login" name="username"/>
                              </div>
                              <div className="form-group">
                                  <label htmlFor="pass">Hasło</label>
                                  <input type="password" placeholder="Hasło" name="password"/>
                                      <span className="sign-in-recovery">
                                          <a href="reset-password.html">Zapomniałeś hasła?</a>
                                      </span>
                              </div>
                              <div className="form-group text-center">
                                  <button type="submit" className="mt-2 mb-2">Zaloguj</button>
                              </div>
                          </form>
```

**Comment by iaincollins** [comment]
That looks like broadly the right approach - we'd need the full source and the specific error to be able to help if you are getting an error. Have you tried copying and pasting the example page, and seeing if that works for you?

**Comment by kyrelldixon** [comment]
I was having the same issue, but I found a solution today. Here are the general steps I took:

1. Add an `id` property to the Credential provider
2. Use `signIn` in my form instead of `action` and `method`

Example `pages/api/[...nextAuth].js`

```js
const options = {
  // Configure one or more authentication providers
  providers: [
    Providers.Credentials({
      id: "username-login", // <- add this line
      name: "Login",
      authorize: async (credentials) => {
        const user = {};
        return Promise.resolve(user);
      },
      credentials: {
        username: { label: "Username", type: "text ", placeholder: "username" },
        password: {
          label: "Password",
          type: "password",
          placeholder: "a-really-long-password",
        },
      },
    }),
  ],
  pages: {
    signIn: "/login",
  },
};
```

Then in `pages/login.js`:

```jsx
import { useState } from "react";
import Layout from "@components/layout";
import { signIn, getSession } from "next-auth/client";

export default function Login() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");

  const handleSubmit = (e) => {
    e.preventDefault();
    // "username-login" matches the id for the credential
    signIn("username-login", { username, password });
  };

  return (
        <form onSubmit={handleSubmit}>
          <div>
            <label htmlFor="username">Username</label>
            <input
              id="username"
              name="username"
              type="text"
              placeholder="Username"
              onChange={(e) => setUsername(e.target.value)}
              value={username}
            />
          </div>
          <div>
            <label htmlFor="password">Password</label>
            <input
              id="password"
              name="password"
              type="password"
              placeholder="Password"
              onChange={(e) => setPassword(e.target.value)}
              value={password}
            />
          </div>
          <button type="submit">
            Login
          </button>
        </form>
  );
}
```

**Comment by dzinks2009** [comment]
> That looks like broadly the right approach - we'd need the full source and the specific error to be able to help if you are getting an error. Have you tried copying and pasting the example page, and seeing if that works for you?

I will try now as the solution @kyrelldixon has provided hasn't worked for me.

**Comment by dzinks2009** [comment]
Could the issue be that my website is on a custom express server? But I'm still getting the providers and the csrf token so I don't know if I'm right here.

**Comment by kobuchin1** [comment]
I'm using a custom express server with next-auth.
It works now.

### 1. add route for post method and hand it to next.js
```javascript
// server.js
       :
  const nextApp = next({ dev });
  const handle = nextApp.getRequestHandler();
       :
  app.get('*', (req, res) => {
    return handle(req, res);
  });
  // ↓↓↓ add route for post method
  app.post('*', (req, res) => {
    return handle(req, res);
  });
  // ↑↑↑ add route for post method
       :
```

### 2. set jwt: true
```javascript
// /pages/api/auth/[...nextauth].js
         :
  session: {
    // ↓↓↓ add 
    jwt: true,
    // ↑↑↑ add
  },
         :
```

### 3. set bodyParser: false
```javascript
// /pages/api/auth/[...nextauth].js
         :
// ↓↓↓ add config export
export const config = {
  api: {
    bodyParser: false,
  },
}
// ↑↑↑ add config export
export default (req, res) => NextAuth(req, res, options)
```
because I already use bodyParser on express.
```javascript
// server.js
       :
  app.use(bodyParser.urlencoded({extended: true}));
  app.use(bodyParser.json());
       :
```

**Comment by kobuchin1** [comment]
@gyto Oh..you are right.
I tried to narrow down the tolerances to just next-auth api.
```javascript
  app.post('/api/auth', (req, res) => {
    return handle(req, res);
  });
```
But I don't have security knowledge much. 
Can someone please correct me?

**Comment by JamesMAWalker** [comment]
I'd also be curious to know if this narrowing down of the url path is sufficient to prevent any security issues. 

> @gyto Oh..you are right.
> I tried to narrow down the tolerances to just next-auth api.
> 
> ```js
>   app.post('/api/auth/*', (req, res) => {
>     return handle(req, res);
>   });
> ```
> 
> But I don't have security knowledge much.
> Can someone please correct me?

**Comment by evshiron** [comment]
I would like to add, that if you have set an `id` in your credentials provider options, use `/api/auth/callback/${provider_id}` and `signIn($providerId, ...options)` instead.

**Comment by dangluan343** [comment]
After I fixed the issue by adding the following code:

`javascript
app.post('*', (req, res) => {
    return handle(req, res);
});`

I encountered a new error: **POST /api/auth/callback/credentials 500**. The error message is:

`⨯ TypeError: Response body object should not be disturbed or locked
`

**Comment by sarmad006** [comment]
For anyone encountering this issue when deploying to Vercel, try disabling Vercel's authentication feature. After I disabled it, everything worked as expected.
![image](https://github.com/user-attachments/assets/15e1afea-5461-45f6-b5e4-d5ee335bae34)

**Comment by vidjg** [comment]
> For anyone encountering this issue when deploying to Vercel, try disabling Vercel's authentication feature. After I disabled it, everything worked as expected. ![image](https://github.com/user-attachments/assets/15e1afea-5461-45f6-b5e4-d5ee335bae34)

Thank you! Same problem, solved by this solution.
