### ISSUE TITLE
Working example for Corporate sign in with Outlook/Safelinks

### ISSUE THREAD

**Issue by bgribbin** [nextauthjs/next-auth#6436]
### Question 💬

Hi,

I've tried following the advice from the documentation here: https://authjs.dev/guides/corporate-proxies/avoid-corporate-link-checking-email-provider

in order to prevent the token not being used up by Microsoft Outlook but having no success. Is there a working example anywhere I can follow?

Many thanks

### How to reproduce ☕️

I'm using TRPC and the T3 Create App. Here is my setup:

export const authOptions: NextAuthOptions = {
 .... 
}

export default async function auth(req: NextApiRequest, res: NextApiResponse) {
  if (req.method === 'HEAD') {
    return res.status(200)
  }

  return NextAuth(req, res, authOptions)
}

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Thanks! Upon re-reading, NextAuth.js actually doesn't even care about `HEAD` requests, so we should upgrade the tutorial to return early based on the incoming user agent or similar. Do you have a clue on how to detect if a request is sent by a "SafeLink" bot?

https://github.com/nextauthjs/next-auth/blob/ba2711d2794f3743ae655c56286903f0a989191d/packages/next-auth/src/core/index.ts#L148

https://github.com/nextauthjs/next-auth/blob/ba2711d2794f3743ae655c56286903f0a989191d/packages/next-auth/src/core/index.ts#L231

https://github.com/nextauthjs/next-auth/blob/ba2711d2794f3743ae655c56286903f0a989191d/packages/next-auth/src/core/index.ts#L294

**Comment by magicspon** [comment]
@bgribbin did you manage to resolve this issue.

i've updated my nextauth route:

```
export default async function auth(req: NextApiRequest, res: NextApiResponse) {
  if (req.method === 'HEAD') {
    return res.status(200)
  }

  return await NextAuth(req, res, authOptions({ req, res }))
}

```

alas, safe links are still busted.

**Comment by ndom91** [comment]
Yeah so as Balazs mention, next-auth doesn't care about `HEAD` requests. So those shouldn't be caught by and processed by the `[...nextauth].js` catch-all API route anyway.

We can skip these "pre-check" Outlook requests in some of the places Balazs mentioned above, for example, but we need to know how best to identify these Outlook requests. Are they using a specific hard-coded `user-agent`?

**Comment by ndom91** [comment]
Theres a longer thread in the `fusion-auth` github about this issue as well. Looks like they did two things:

> 1. We handle `HEAD` requests for these verification flows so we don't "use" the code ahead of time.
> 2. The new stock templates will add `&postMethod=true` to the URL we build to indicate that we should render the page, and then submit a `POST` request back to ourselves to complete the flow instead of performing it on a `GET` request.
This is for backwards compatibility, existing templates w/out the `&postMethod=true` will still use a `GET` method.

Source: https://github.com/FusionAuth/fusionauth-issues/issues/629#issuecomment-832778247

**Comment by DarrylBrooks97** [comment]
I've followed the docs listed [here](https://next-auth.js.org/tutorials/avoid-corporate-link-checking-email-provider) however I'm still getting an error. I've read some threads mentioning the safelinks bot opens the url before the user but it seems that the protection has malformed my callback url shown below that is causing my application to error upon verification:

![CleanShot 2023-04-04 at 21 53 54](https://user-images.githubusercontent.com/24500251/229969431-24fe45f4-5b3c-44ba-b115-60e0d9992115.png)

**Comment by jrusk** [comment]
I tired the bot detection recommended by [DarrylBrooks97](https://github.com/DarrylBrooks97) but after a while Google marked all my API auth routes as suspicious (in particular "Deceptive Site Ahead"). Check out this comment for more info https://github.com/nextauthjs/next-auth/discussions/6393#discussioncomment-6332430.

**Comment by nvegater** [comment]
> This solution worked for me! The safelink bot uses the `user agent` listed below to check links before users click them
> 
> ```ts
> export default async function auth(req: NextApiRequest, res: NextApiResponse) {
> 	if (req.method === 'HEAD' || /lua-resty-http.+ngx_lua/.test(req.headers['user-agent'])) {
> 		console.log('Bot detected');
> 		return res.status(200).end();
> 	}
> 
> 	return await NextAuth(req, res, options);
> }
> ```

Did this work for anyone else?

**Comment by YannHulot** [comment]
Same here, I added an extra confirmation page. Is it ideal? No but the alternative is users sending me emails because they can't log into their accounts so it's worth the extra friction.

**Comment by balazsorban44** [comment]
We had something related in our old docs https://next-auth.js.org/tutorials/avoid-corporate-link-checking-email-provider

it should be migrated to the new one as well, under /guides. Want to PR maybe? 

FWIW, I started working on a "cleaner" way, where you can configure the email provider to send you to a page first where you must click a link instead.

OTP is trickier without rate limiting. We are an auth library, so that's harder to do because we would have to make the user aware that its security will depend on their infra. I still want to support it somehow
