### ISSUE TITLE
Auth.js for SvelteKit doesn't work with Vercel Edge Functions

### ISSUE THREAD

**Issue by evangelos-ch** [nextauthjs/next-auth#6439]
### Environment

npx envinfo --system --binaries --browsers --npmPackages "@sveltejs/kit,@sveltejs/adapter-vercel,@auth/core,@auth/sveltekit" 

  System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 72.55 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Firefox Developer Edition: 110.0
    Safari: 16.2
  npmPackages:
    @auth/core: ^0.2.5 => 0.2.5 
    @auth/sveltekit: ^0.1.12 => 0.1.12 
    @sveltejs/adapter-vercel: ^1.0.5 => 1.0.5 
    @sveltejs/kit: ^1.0.0 => 1.1.1 

### Reproduction URL

https://github.com/evangelos-ch/sveltekit-auth-example

### Describe the issue

I'd like to use Vercel's Edge Functions, which SvelteKit does support as demonstrated in this example project: <https://vercel.com/templates/svelte/sveltekit-edge-functions>.

When I set up my project that way though and I also use Auth.js for Discord authentication, deployment breaks on Vercel, whereas it works just fine before and also just fine if I use `@sveltejs/adapter-auto` and do not set the edge flag.

The error from Auth.js is `Host must be trusted`, which breaks the entire site and not just any auth flow stuff. I tried to resolve this error with `AUTH_TRUST_HOST` or `NEXTAUTH_HOST` env variables to no avail. But after all I shouldn't need them on Vercel, right?

Then I tried deploying your SvelteKit example to Vercel and modifying it for Discord auth, and voila it worked just fine with the same variables as my other project. Then when I changed it over to Edge Functions, it broke with the same behaviour: Host must be trusted errors.

### How to reproduce

1. Deploy the project from my Reproduction URL to Vercel
2. Set the env variables `DISCORD_CLIENT_SECRET`, `DISCORD_CLIENT_ID` and `AUTH_SECRET` (or change them around to e.g. GitHub and then modify the appropriate files in the repo for another provider to test)
3. Redeploy since the build would've failed the first time due to the missing variables

### Expected behavior

The deployment should work, unless Edge incompatibility is some intended or unavoidable limitation of Auth.js, which should then be documented somewhere.

**Comment by jdgamble555** [comment]
I am having the same problem. It seems to work on Vercel, but NOT on Vercel Edge Functions.  I get this error:

```html
Error: There was a problem with the server configuration. Check the server logs for more information.
    at (../../../../.svelte-kit/output/server/chunks/hooks.server.js:18:8)
    at (../../../../.svelte-kit/output/server/entries/pages/_layout.server.ts.js:3:13)
    at (../../../../.svelte-kit/output/server/index.js:520:17)
    at (../../../../.svelte-kit/output/server/index.js:1551:17)
```

```html
[GET] /
18:32:26:09
[auth][error][Bp]
: Read more at https://errors.authjs.dev#bp
```

However, when I turn off edge functions, my app works as expected:

```js
  kit: {
    adapter: adapter({
	//edge: true
    })
  }
```

J

**Comment by ThangHuuVu** [comment]
Seems to be a problem with `@auth/sveltekit` using `$env/dynamic/private` on Vercel which is against [recommendation](https://kit.svelte.dev/docs/adapter-vercel#environment-variables). I'm investigating a solution 🔍

> Since all of these variables are unchanged between build time and run time when building on Vercel, we recommend using $env/static/private — which will statically replace the variables, enabling optimisations like dead code elimination — rather than $env/dynamic/private. If you're deploying with edge: true you must use $env/static/private, as $env/dynamic/private and $env/dynamic/public are not currently populated in edge functions on Vercel.

Our code: https://github.com/nextauthjs/next-auth/blob/main/packages/frameworks-sveltekit/src/lib/index.ts#L193

**Comment by jdgamble555** [comment]
https://github.com/sveltejs/kit/issues/7556

Related

J

**Comment by ThangHuuVu** [comment]
So a workaround for now is to set `trustHost` to true and define `secret` manually in the `authConfig`:
```ts

export const handle = SvelteKitAuth({
  providers: [GitHub({ clientId: GITHUB_ID, clientSecret: GITHUB_SECRET })],
  trustHost: true,
  secret: "secret",
})
```

Internally we'll have to use `$env/static/private` somehow.

**Comment by ThangHuuVu** [comment]
See upstream issue: https://github.com/sveltejs/kit/pull/9942

**Comment by symbolicsorcerer** [comment]
Think this might be close-able now. I see the referenced issue has been closed/merged, and I was able to get an app running in Vercel edge functions that successfully authenticates.
