### ISSUE TITLE
help: how to use next-auth with custom backend (golang + graphql)

### ISSUE THREAD

**Issue by yeganathan18** [nextauthjs/next-auth#6449]
### Summary

We're currently building a platform where we would like to integrate social logins such as GitHub, GitLab, etc.

Tech stack we use: Go (backend) + GraphQL API + NextJS  + PostgreSQL as db

So we need an authentication where we are supposed to retrieve user information and access user details in platforms such as GitHub. 

Initially, we thought to use `next-auth` in the Next.js frontend and get the `access_token` of the user after successfully authentication of the user in GitHub. From that point, we do a mutation in our backend and generate JWT to use it for further requests.

### Question

I see the newer version of `next-auth` doesn't provide `access_token` explicitly, is there any way could do this? Maybe better idea, we can handle this whole social login situation for our custom backend stack?

P.S. We primarily use GitHub and GitLab OAuth and I have looked upon resources on this topic but unfortunately couldn't find anything useful as well as secure practice 😕

### How to reproduce ☕️

None

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
NextAuth.js does provide you with the access_token obtained from your provider and you can use that to send request against the provider's api

Check out https://next-auth.js.org/getting-started/example#extensibility

for custom backends, you can use the Credentials provider

https://next-auth.js.org/providers/credentials

**Comment by yeganathan18** [comment]
Thanks for the reply @balazsorban44 

I think `accessToken` has been depreciated from `Session` schema, so when I the examples mentioned in the doc it shots error saying that `Session doesn't have accessToken type on it`

I tried the [example](https://next-auth.js.org/getting-started/example) provided in `getting-started` 

Is there anything to add in the code in order to access the token?

**Comment by yeganathan18** [comment]
@balazsorban44 thanks for the help, I really appreciate your time and effort!

**Comment by stdNullPtr** [comment]
> NextAuth.js does provide you with the access_token obtained from your provider and you can use that to send request against the provider's api
> 
> Check out https://next-auth.js.org/getting-started/example#extensibility
> 
> for custom backends, you can use the Credentials provider
> 
> https://next-auth.js.org/providers/credentials

We have access_token from our provider, but how would you use that token to secure your custom backend requests? 
The backend doesn't know about it, so how can you use it? 
With the credentials provider it's straightforward, but can we do the same with the external providers?
Is there a pattern to this? I just really want to use the provider(Github) to secure both my frontend and backend.

**Comment by fschossler** [comment]
> > NextAuth.js does provide you with the access_token obtained from your provider and you can use that to send request against the provider's api
> > Check out https://next-auth.js.org/getting-started/example#extensibility
> > for custom backends, you can use the Credentials provider
> > https://next-auth.js.org/providers/credentials
> 
> We have access_token from our provider, but how would you use that token to secure your custom backend requests? The backend doesn't know about it, so how can you use it? With the credentials provider it's straightforward, but can we do the same with the external providers? Is there a pattern to this? I just really want to use the provider(Github) to secure both my frontend and backend.

At least I'm not the only one with the same question of how to use the same access_token to secure both front and backend.

**Comment by OsamaQureshi147** [comment]
https://github.com/nextauthjs/next-auth/issues/6449#issuecomment-1754624358

> > NextAuth.js does provide you with the access_token obtained from your provider and you can use that to send request against the provider's api
> > Check out https://next-auth.js.org/getting-started/example#extensibility
> > for custom backends, you can use the Credentials provider
> > https://next-auth.js.org/providers/credentials
> 
> We have access_token from our provider, but how would you use that token to secure your custom backend requests? The backend doesn't know about it, so how can you use it? With the credentials provider it's straightforward, but can we do the same with the external providers? Is there a pattern to this? I just really want to use the provider(Github) to secure both my frontend and backend.

This question is still valid but still unanswered. Anyone knows a workaround?

**Comment by cerrorism** [comment]
My understanding of this is that usually you don't need to expose access token and use that explicitly in your custom backend. The access token that auth.js received is just for the website and should keep the scope like that.
Depends on the framework you are using (next.js, Qwik, or others), if you are using SSR, you can implement a reverse proxy route which talks to backend, and the route itself is protected by auth.js. When deploying the website, usually you need a node server running in the private network, which can then talk to the custom backend without explicit auth, but using other approaches like network security, gateway security, mTLS, or other layers to keep the connection secure.
