### ISSUE TITLE
How to catch email signin errors in the client with redirect property set to 'false'?

### ISSUE THREAD

**Issue by egurb** [nextauthjs/next-auth#6458]
### Question 💬

I added Email provider to my app, and having issues with catching signIn errors in the client. According to [documentation](https://next-auth.js.org/configuration/providers/oauth#options), when using signIn with 'redirect: false' it will return a Promise, that resolves to the following:

```
{
  error: string | undefined
  status: number
  ok: boolean
  url: string | null
}
```

In case of errors, however, the 'error' property of the response object has only 'EmailSignin' value, and contains no other information about the kind of error. Instead, more detailed errors are printed in the console.

![image](https://user-images.githubusercontent.com/16966144/213910933-82a0b9e2-810e-4427-a62d-7743e34bbf08.png)

I was wondering if there is a way to catch signIn errors and send them to the client for better error handling?

### How to reproduce ☕️

So far I have minimal configuration, just the basic setting in the email provider to send an email, and a sign in form with input for user to provide an email.

[...nextauth].js

```
    EmailProvider({
      name: "Email",
      server: {
        host: "smtp.gmail.com",
        port: "587",
        auth: {
          user: "myusername",
          pass: "mypassword",
        },
      },
      from: "My App",
    }),
```

Custom Sign In form:

```
  const handleSignInClick = async () => {
    const { email } = formData;

    const response = await signIn("email", {
      redirect: false,
      email,
    });
    ...
    ...
    ...
  };
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
you generally don't want a more specific error kn the client since it could expose sensitive details of your backend. you can just ask the user to reenter their email and if it fails, contact support, or something similar. if the error occurs because of a backend error, your monitoring should catch that already.

**Comment by egurb** [comment]
> you generally don't want a more specific error on the client since it could expose sensitive details of your backend. you can just ask the user to reenter their email and if it fails, contact support, or something similar. if the error occurs because of a backend error, your monitoring should catch that already.

I generally handle errors in the backend. Let's say if user does not provide email, or provides incorrect email, I want to send different errors for each case. This seems not to be possible at all.  When I used Credentials provider, I could throw an error, and would receive in the client. Why not add this functionality to Email as well?

**Comment by egurb** [comment]
@balazsorban44  this is perfectly working example of authorize method of Credentials provider:

```
if (!username && !password) {
  throw new Error(
    JSON.stringify([
      { field: "username", reason: "required" },
      { field: "password", reason: "required" },
    ])
  );
}
```

**Comment by balazsorban44** [comment]
Actually, I would rather limit the credentials case than open up the email one. We could probably allow through specific type of errors that you could import but not any generic ones to avoid footguns.

**Comment by egurb** [comment]
My main issues is that when I use redirect false, anytime input provided incorrectly, logger logs this errors. Which I'd personally avoid somehow. I read in the documentation that it can actually be disabled, but that's also not ideal as it could potentially lead to missing other important errors. I see you point though. Well ok. I'll try to come up with something else.

**Comment by balazsorban44** [comment]
you have two options currently:

1. try adding a basic client-side validation to catch common user errors before even sending the request, if that's an option.

2. if it's noisy, override the correct logger method, filtering the messages you don't want printed

**Comment by egurb** [comment]
Yep, second option is what I currently doing. I also found that 'signIn' callback can throw errors which are sent to client. The only case when it's not triggered, is when no email provided at all. So combination of this two should do the job.

**Comment by PrabeenGautam** [comment]
> Yep, second option is what I currently doing. I also found that 'signIn' callback can throw errors which are sent to client. The only case when it's not triggered, is when no email provided at all. So combination of this two should do the job.

can you provide any reference on how you implemented? I am being stuck in this for a week.

**Comment by ImBIOS** [comment]
Add this to migration guide:

Before:
```
        return `/login?error=${err}&param2=${isBoolean ? 1 : 0}`

```

After:
```
class CustomAuthError extends AuthError {
            static type = `${e as string}&param2=${isBoolean ? 1 : 0}`
          }

          throw new CustomAuthError(e)
```

Something like this, you can hack as you like. but keep in mind, it's not a best practice to pass information from server to client if you're not sure.

**Comment by enisze** [comment]
@ImBIOS I would like to do the same, for the nodemailerProvider in v5. As e.g. my email provider could fail sending an email or something and I would like to let the user know that something went wrong. But I cannot get the error to the client is there any possibility?
