### ISSUE TITLE
broken link "Guide deep-dive" in Email Provider Options reference page 

### ISSUE THREAD

**Issue by rawbinary** [nextauthjs/next-auth#6466]
### What is the improvement or update you wish to see?

Actual page where the "Guide deep-dive" link leads to in Email Provider options reference page. 

URL: https://authjs.dev/reference/providers/email

### Is there any context that might help us understand?

In https://authjs.dev/reference/providers/email, 

at the bottom there's link "Guide deep-dive" which is broken.

### Does the docs page already exist? Please link to it.

https://authjs.dev/reference/providers/email

**Comment by rawbinary** [comment]
Is that link supposed to redirect back to: https://authjs.dev/guides/providers/email ??

Or maybe to email provider module at: https://authjs.dev/reference/core/modules/providers_email ??

**Comment by balazsorban44** [comment]
Should go to https://authjs.dev/guides/providers/email

care to open a PR?

**Comment by rawbinary** [comment]
Sure.
