### ISSUE TITLE
Handling properly Success/Failure status in Credentials SignIn API

### ISSUE THREAD

**Issue by rafaelpizzo** [nextauthjs/next-auth#648]
**Your question**
version: "^3.1.0"
How to properly check for a successful Sign-In or thrown errors from (Credentials) Sign-In API's callback.

**What are you trying to do**
Making a full promise-based Sign-In with no redirects. If a Sign-In attempt fails for whatever reason, Promise.catch() would display the error message from the  callback. If the Promise was successful, I could continue any logic with a Promise.then().

We are currently using next-auth v3.1.0 with Credentials provider to authenticate through our Backend (Hasura/GraphQL), so it returns the auth-token properly. We already managed to make authentication somewhat work, except for the following issue that arose.

In `Providers.Credentials().authorize()` method, we use `Promise.reject(<error message>)` to throw an error, so API's callback could forward them.

```js
Providers.Credentials({
    name: 'Credentials',
    credentials: {
        email: { label: 'E-Mail', type: 'text' },
        password: { label: 'Password', type: 'password' },
    },
    authorize: async (credentials: any) => {
        if ('email' in credentials && 'password' in credentials) {
            //returns Promise.resolve(token) or Promise.reject(<error message>);
            return await loginByCredentials(credentials.email, credentials.password);
        } else {
            //Generic error message
            return Promise.reject('Invalid');
        }
    },
}),
session: {
    jwt: true,
},
jwt: {
    encryption: false,
}
```

Then on our custom Sign-In page, we use the following method:

```js
const signIn = async (args = {}, redirectUrl: any) => {
    const baseUrl = "http://localhost:3000"; //or WebsiteDomain
    await fetch(baseUrl + '/api/auth/callback/credentials', {
            method: 'post',
            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
            body: _encodedForm({
                ...args, //includes CRSF Token
                json: true,
            }),
        })
        .then((response) => { return response.json(); })
        .then((data) => {
            if (data) {
                //Do some logic here
                        
                    if(redirectUrl) {
                        window.location = redirectUrl;
                    }
            } else {
                return Promise.reject(t('common:' + data.url));
            }
        });
};
```

However, in case Sign-In fails, we receive a HTTP 200 response with the following object:

`POST http://localhost:3000/api/auth/callback/credentials :: Status 200 OK`
```json
{
	"url": "E-Mail or Password invalid"
}
```

...and if it succeeds the first time, we once again receive a HTTP 200 response with same object structure:

`POST http://localhost:3000/api/auth/callback/credentials :: Status 200 OK`
```json
{
	"url": "http://localhost:3000"
}
```

...and after a few SignIn/SignOut attempts, the successful response becomes same as before but with all ":" replaced with "."

```json
{
	"url": "http.//localhost.3000"
}
```

I was expecting  HTTP 200 reponses from the API to be used only in success Sign-In cases, and for failed ones something with a HTTP 403 or some other "error" key.

Currently, I cannot know the Sign-In status (success or failed) when for both cases its the same object struct. and HTTP response.

I tried a workaround by checking if the response matched with the RedirectURL I provided initially, but due to ":" being replaced with "." issue the check also fails.
```
fetch(baseUrl + '/api/auth/callback/credentials', {
	...
        .then((data) => {
            if (data && data.url && data.url == baseUrl) {
                window.location = redirectUrl;
            } else {
                return Promise.reject(t('common:' + data.url));
            }
        });
```

Am I currently setting something wrong for these API calls?
Or Is it possible to have something like this?

SUCCESS
`POST http://localhost:3000/api/auth/callback/credentials :: Status 200`
```json
{
	"url": "<Redirect URL>"
}
```

ERROR
`POST http://localhost:3000/api/auth/callback/credentials :: Status 403`
```json
{
	"error": "<Error Message>"
}
```

Thank you!

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by iaincollins** [comment]
Hmm I'm not entirely sure what is going on here, but I would start with updating the `Promise.reject()` response from the `authorize()` callback (this includes possibly not directly returning from `loginByCredentials()`, depending on what it returns when it rejects credentials). That might make things easier to debug.

The reject should container either:

1. An error object: `return Promise.reject(new Error('error message'))`
2. A URL `return Promise.reject('/path/to/redirect')`

But it shouldn't be a string that isn't a URL as that will cause odd behaviour.

Note: If you return an Error object it will direct to the error page with the message encoded as a query parameter.

You can set the error page to be your sign up page if you want (e.g. `pages: { error: '/signin' }` but you might also find it easier just to return a URL from the `authorize()` callback when rejecting the sign in (e.g. `/signin?error=invalid_credentials`).

I'm not sure off hand if NextAuth.js supports returning a JSON response for errors. It's currently a poorly documented internal API created to work around browser limitations of no being able to read location responses, which is likely why it's loose with HTTP error types in this scenario, but I can see how it would it be useful to support that.

**Comment by jacklimwenjie** [comment]
Is there any recommendation to handle this?

It's not a pleasant UX to redirect the user to a new error page on sign in fail.

**Comment by FrimJo** [comment]
Hi there!

 I have the same problem, when returning either `throw new Error('auth_failed')` or `throw 'http://localhost:3000/auth/signin?error=auth_failed'` I get the same result `{error: "auth_failed", status: 200, ok: true, url: null}` but I would expect `ok` to be `false` and not a `status` of `200`.

Note: I've sett `pages.error` to my sign in page `/auth/signin`

The goal is to present server errors in sign in form.

**Comment by balazsorban44** [comment]
@FrimJo the reason for 200 is that we don't really know the reason for why the error occurred, should it be 401 or 500? but in theory you could just check if error exists on the response of `signIn`

**Comment by FrimJo** [comment]
> @FrimJo the reason for 200 is that we don't really know the reason for why the error occurred, should it be 401 or 500? but in theory you could just check if error exists on the response of `signIn`
> 
> I don't recommend throwing a string. (even though we support it right now, it's not a conventional thing to do and will be removed in a later major release).
> 
> You could try just returning it. But it has to be a valid url. (I think relative is fine)

I see, but can’t we have the authenticate callback reject an object containing message and status?

**Comment by cyanerd** [comment]
i have the same issue. do anyone find the solution? :(

**Comment by adamcanray** [comment]
> > @FrimJo the reason for 200 is that we don't really know the reason for why the error occurred, should it be 401 or 500? but in theory you could just check if error exists on the response of `signIn`
> > I don't recommend throwing a string. (even though we support it right now, it's not a conventional thing to do and will be removed in a later major release).
> > You could try just returning it. But it has to be a valid url. (I think relative is fine)
> 
> I see, but can’t we have the authenticate callback reject an object containing message and status?

2024 need this
