### ISSUE TITLE
Error serializing .session.user.image returned from getServerSideProps using AzureADProvider and unstable_getServerSession

### ISSUE THREAD

**Issue by unknownsoldier08** [nextauthjs/next-auth#6482]
### Provider type

Azure Active Directory

### Environment

>   System:
>     OS: Windows 10 10.0.22621
>     CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
>     Memory: 16.28 GB / 31.92 GB
>   Binaries:
>     Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
>     Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
>     npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
>   Browsers:
>     Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.61)
>     Internet Explorer: 11.0.22621.1
>   npmPackages:
>     next: 13.1.4 => 13.1.4
>     next-auth: ^4.18.8 => 4.18.8
>     react: 18.2.0 => 18.2.0
>

### Reproduction URL

https://github.com/unknownsoldier08/next-auth-aad

### Describe the issue

I have setup a fresh project using the AzureADProvider that is setup as follows (following https://next-auth.js.org/providers/azure-ad and https://next-auth.js.org/tutorials/securing-pages-and-api-routes#server-side

**/pages/api/[...nextauth].ts**
```ts
import NextAuth from 'next-auth'
import AzureADProvider from 'next-auth/providers/azure-ad'
import { NextApiRequest, NextApiResponse } from 'next'

export const authOptions = {
  providers: [
    AzureADProvider({
      clientId: process.env.AZURE_AD_CLIENT_ID,
      clientSecret: process.env.AZURE_AD_CLIENT_SECRET,
      tenantId: process.env.AZURE_AD_TENANT_ID,
      authorization: {params: {scope: 'openid profile user.Read email'}},
    }),
  ],
  debug: true,
}

export default (req: NextApiRequest, res: NextApiResponse) => NextAuth(req, res, authOptions)
```

**/pages/admin/index.tsx**
```ts
import { unstable_getServerSession } from 'next-auth'
import { authOptions } from 'pages/api/auth/[...nextauth]'
import { signIn, useSession } from 'next-auth/react'
import { GetServerSidePropsContext, InferGetServerSidePropsType } from 'next'

export default function Admin({session}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const {data: sessionData} = useSession()

  if (sessionData) {
    return (
      <>
        <p className={'text-3xl'}>Logged in</p>
      </>
    )
  }

  return (
    <>
      <p className={'text-3xl'}>Not logged in</p>
      <p onClick={() => signIn()}>Click here to sign in!</p>
      
    </>
  )
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  return {
    props: {
      session: await unstable_getServerSession(context.req, context.res, authOptions),
    },
  }
}
```

### How to reproduce

1. Clone https://github.com/unknownsoldier08/next-auth-aad
2. Setup env.local with Azure AD Client token/secrets
3. Start server and browse to localhost:3000
4. Click Sign in
5. After successful sign in, browse to server page ([http://localhost:3000/server](http://localhost:3000/server))

![image](https://user-images.githubusercontent.com/96962453/214135402-2310afad-d6f2-4ff7-b117-79f3183c8058.png)

### Expected behavior

The provider should handle the event when session.user.image is undefined when authenticating via getServerSideProps

**Comment by balazsorban44** [comment]
Fixed in 4.18.9, please upgrade!
