### ISSUE TITLE
How do I use next-auth with nextjs 13 that has a base path?

### ISSUE THREAD

**Issue by mastoj** [nextauthjs/next-auth#6485]
### Question 💬

I have a nextjs 13 application where we use the app folder as well as having a base path. When calling `signIn` it seems like the base path isn't respected by next auth even though I've set the NEXTAUTH_URL variable. 

### How to reproduce ☕️

Create an application using nextjs 13. Use a basepath for the application and then add a SignIn page that use `getProviders` to get the providers and uses a simple signInComponent that the one below. It seems like the call to `signIn` below is to the wrong url endpoint.

```
"use client";
import { getProviders, signIn } from "next-auth/react";
import React from "react";

type Props = {
    providers: Awaited<ReturnType<typeof getProviders>>;
};

const SignInComponent = ({ providers }: Props) => {
    return (
        <div>
            {Object.values(providers!).map((provider) => {
                return (
                    <div key={provider.name}>
                        <button
                            onClick={() =>
                                signIn(provider.id, {
                                    callbackUrl: "/admin",
                                    redirect: true,
                                })
                            }
                        >
                            Sign in with {provider.name}
                        </button>
                    </div>
                );
            })}
        </div>
    );
};

export default SignInComponent;
``` 

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by mastoj** [comment]
I tried to remove the base path to check if that helped and then it redirects to my provider, but that isn't what I want though.

**Comment by balazsorban44** [comment]
`NEXTAUTH_URL` is not detected client-side as it's not prefixed with `NEXT_PUBLIC_`. See: https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser

You can use the `SessionProvider's` `basePath` config option to match the path as documented here: https://next-auth.js.org/getting-started/client#custom-base-path

**Comment by mastoj** [comment]
Thank you @balazsorban44 , I'll try prefixing the end variable. Are there any good docs or examples on how to use the session provider in 13? To my understanding I should wrap the whole app in such a provider, but maybe I've misunderstood something.

**Comment by balazsorban44** [comment]
>  I'll try prefixing the end variable

This is not going to work, as we don't detect `NEXT_PULIC_NEXTAUTH_URL`. Please check out the second link I sent you.

If you are talking about the app directory (which is not a requirement in Next.js 13 and is currently in beta, you can keep using pages as before), you can check out https://next-auth.js.org/configuration/nextjs#in-app-directory

**Comment by harisraharjo** [comment]
@balazsorban44 hi, the docs that you are referencing to says that the expires value is stripped away from session in Server Components. What does it really means? Does it means that the session will always true until ~30 days?
