### ISSUE TITLE
It's impossible to pass session as props to RootLayout 

### ISSUE THREAD

**Issue by lironsfadia** [nextauthjs/next-auth#6499]
### Provider type

Credentials

### Environment

 System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
    Memory: 19.05 GB / 31.89 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    next: ^13.1.5 => 13.1.5
    next-auth: ^4.18.8 => 4.18.8
    react: ^18.2.0 => 18.2.0

### Reproduction URL

https://github.com/lironsfadia/next-js-site/blob/main/app/layout.tsx

### Describe the issue

It's impossible to pass the session (which it's next-auth session) in the rootLayout of my project. I'm trying to pass it as props and pass it to the session provider.
The error message that I got: "session" is not a valid layout prop.

export default function RootLayout({ children, session }: { children: React.ReactNode; session: Session }) {
  return (
    <html lang='he' className='h-100'>
      <head />
      <body className='h-100 d-flex flex-column'>
        <SessionProvider session={session}>
          <Navbar />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}

### How to reproduce

try to put session in the props of your rootLayout.

### Expected behavior

No errors.

**Comment by balazsorban44** [comment]
You can use the `unstable_getServerSession` method as documented here: https://next-auth.js.org/configuration/nextjs#in-app-directory
