### ISSUE TITLE
Allow overriding specific error pages / export `renderPage`

### ISSUE THREAD

**Issue by MonstraG** [nextauthjs/next-auth#6503]
### Description 📓

A need has arisen to show a custom error page but only if error is `OAuthCallback`. For other cases default error page was fine.

The following is a sketch of how I attempted to solve this:
```tsx
import renderPage from "next-auth/core/pages";

const AuthErrorPage = ({ query, cookies, locale }) => {
	if (query.error == "OAuthCallback") {
		return <MyCustomPage />
	}

	// otherwise render default error page
	return renderPage({
		query,
		cookies
	});
};
```

The only problem with that is that I get the following error:
```
Module not found: Package path ./core/pages is not exported from package /...yarn path here.../node_modules/next-auth/
```

Therefore I cannot actually import `renderPage` and would have to copy-paste it I guess?

So, in order to achieve my goal, it seems that I need either 
- for `renderPage` to be exported
- for `pages` config to be more precise and allow me to add a custom page specifically for `OAuthCallback` error.

To avoid XY problem, I want to override `OAuthCallback` specifically because I in this case I want to call `signIn()` on my only provider, because we have this error happen exactly as described in https://github.com/auth0/express-openid-connect/issues/43 
(Second tab overrides `state` cookie).

If you have any alternative solutions to this problem, that would be welcome too.

### How to reproduce ☕️

see above I guess

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by MonstraG** [comment]
Upd: I think I got confused a bit, and the page I need to override is signin page, with error query in it, not the error page, but it doesn't change much

**Comment by balazsorban44** [comment]
You can already do this by changing the [`pages` option](https://next-auth.js.org/configuration/pages) combined with [Advanced Initialization](https://next-auth.js.org/configuration/initialization#advanced-initialization)

**Comment by MonstraG** [comment]
Sorry, not quite.

I'm asking to be able to override the page for specific query.

**Comment by balazsorban44** [comment]
exactly. you check if a request has a certain query param, if it does, you do whatever you want, otherwise you let the request through to the `NextAuth` call

**Comment by socketopp** [comment]
I currently have a similar problem #9475 

My issue is that the redirect from Github sends me to the wrong error page. There is no way of intercepting the incoming request unfortunately.
