### ISSUE TITLE
Some code is missing in the compiled code compared to the source code?

### ISSUE THREAD

**Issue by StringKe** [nextauthjs/next-auth#6511]
### Question 💬

https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/core/index.ts#L298-L306

Search for `X-Auth-Return-Redirect` in the compiled code bing

I'm having a problem with requests for OAuth SignIn, and I'm finding that no matter what, the request always bounces and doesn't return the json needed for the signIn method

1.  Need to return json
https://github.dev/nextauthjs/next-auth/blob/0204766e0f2c7b2f3b2a83a28fb87d808dbfba9e/packages/next-auth/src/react/index.tsx#L254
2. Checking `node_modules` reveals no code for `X-Auth-Return-Redirect` in `next-auth`

Related discussions: https://github.com/nextauthjs/next-auth/discussions/6510

### How to reproduce ☕️

```bash
mkdir SOME_DIR/test
cd test
npm add next-auth
grep -r "X-Auth-Return-Redirect"
./node_modules/@auth/core/index.js:    if (request.headers.has("X-Auth-Return-Redirect") && redirect) {
./node_modules/@auth/core/src/index.ts:  if (request.headers.has("X-Auth-Return-Redirect") && redirect) {
```

There is nothing related to `X-Auth-Return-Redirect` in next-auth

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by StringKe** [comment]
The reason has been found https://github.com/nextauthjs/next-auth/pull/5938

**Comment by balazsorban44** [comment]
The code for `next-auth` is on https://github.com/nextauthjs/next-auth/tree/v4

**Comment by StringKe** [comment]
@balazsorban44 There seems to be no further refinement in the new version regarding #5938 either, what other factors need to be considered here?

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth/pull/5938#issuecomment-1404910714
