### ISSUE TITLE
Throwing in authorize leads to CallbackRouteError instead of custom error

### ISSUE THREAD

**Issue by Psy-Kai** [nextauthjs/next-auth#6512]
### Provider type

Credentials

### Environment

-

### Reproduction URL

-

### Describe the issue

When throwing as described in [Example - Username/Password](https://authjs.dev/guides/providers/credentials#example---username--password) the `error`-route receives `CallbackRouteError` instead of the thrown error.

Regression from https://github.com/nextauthjs/next-auth/commit/83c6bfe237ca5b801ae2d33cea07ad1687aa4dfa#diff-34764726f8865be5a9cc1e76b1c3b7407f024a45678781abbbac0e4901a0c34fL258. Here the `try-catch` passing the error message as parameter to the `error`-route was just thrown away. Now only the catch in https://github.com/nextauthjs/next-auth/commit/83c6bfe237ca5b801ae2d33cea07ad1687aa4dfa#diff-34764726f8865be5a9cc1e76b1c3b7407f024a45678781abbbac0e4901a0c34fR332 is used. 

### How to reproduce

-

### Expected behavior

The described behaviour of the [documentation](https://authjs.dev/guides/providers/credentials#example---username--password).

**Comment by balazsorban44** [comment]
This was introduced on purpose in #6259. Letting the user throw errors this way might actually expose more information than necessary to the client (ie. a common mistake is to throw an error like "wrong password" which gives an attacker a lever to try a brute force attack, or enumerate the users of an app).

The expected action is now to just return `null` if the user authentication was not successful, and we will redirect to the sign-in page with the `CredentialsSignin` code: https://authjs.dev/guides/basics/pages#sign-in-page:~:text=verification%20token%20failed-,CredentialsSignin,-%3A%20The%20authorize%20callback

The docs need updating around this, feel free to open a PR.

**Comment by gnllucena** [comment]
@balazsorban44 , I understand the ideia behind this, but I don't think it's a good decision.

We are using the CredentialProvider because we want full control of the authentication.

In my case I want to display custom fields depending on which user is authenticating and if it's the first user authentication (authentication code by cognito, for example)

Is there a way for the server to custom communicate with the cliente using CredentialsProvider?

**Comment by shgrth** [comment]
I have been using next-auth v4 for my company's web portal. I upgraded to v5 to test it out and have been facing this issue where I can't throw a custom error message to the front-end. No I am not going to tell my user specific information like "Your password's last character is incorrect"

If this is by design in v5, then we might have to find an alternative auth library because in our Sign In flow, the server sometimes responds with "User not activated" and we automatically render the OTP page on the front-end.

**Comment by shgrth** [comment]
So am I right to assume Next-Auth will no longer allow custom error messages to be thrown from the authorize() function back to front-end with signIn call using redirect: false?

**Comment by michaelzadra1** [comment]
This is a pretty serious deal-breaker for our team. We understand exceptions like `UsernameExistsException` shouldn't be surfaced to the client, but there are so many other error messages that are not security concerns we'd want to surface to the client when logins fail.

**Comment by shgrth** [comment]
> This is a pretty serious deal-breaker for our team. We understand exceptions like `UsernameExistsException` shouldn't be surfaced to the client, but there are so many other error messages that are not security concerns we'd want to surface to the client when logins fail.

Exactly. 100%.

Our backend throws a signin error for new users that need email verification. Now there's literally no way to implement our MFA form with a signin error. All signin errors are the same "CallbackRouteError"

We will wait with Next-Auth V4, and then try an alternative solution if V5 will not implement this.

**Comment by A7med3bdulBaset** [comment]
> Our backend throws a signin error for new users that need email verification. Now there's literally no way to implement our MFA form with a signin error. All signin errors are the same "CallbackRouteError"
> We will wait with Next-Auth V4, and then try an alternative solution if V5 will not implement this.

Agree 100%

**Comment by OleksandrYermak** [comment]
You may workaround like this:
1) in your `authorize` you throw an error
```
async authorize(credentials, req) {
  const user = await getUser(credentials);
  if (!user) {
    throw new Error("custom error")
  }
  return user;
}
```
2) in your action you check if error was caused by another error and return a message
```
try {
  await signIn('credentials', credentials);
} catch (error) {
  if (error instanceof AuthError) {
    if (error.cause?.err instanceof Error) {
      return error.cause.err.message; // return "custom error"
    }
    switch (error.type) {
      case 'CredentialsSignin':
        return 'Invalid credentials';
      default:
        return 'Something went wrong';
    }
  }
  throw error;
}
```

**Comment by A7med3bdulBaset** [comment]
> You may workaround like this:
> 
> 1. in your `authorize` you throw an error
> 
> ```
> async authorize(credentials, req) {
>   const user = await getUser(credentials);
>   if (!user) {
>     throw new Error("custom error")
>   }
>   return user;
> }
> ```
> 
> 2. in your action you check if error was caused by another error and return a message
> 
> ```
> try {
>   await signIn('credentials', credentials);
> } catch (error) {
>   if (error instanceof AuthError) {
>     if (error.cause?.err instanceof Error) {
>       return error.cause.err.message; // return "custom error"
>     }
>     switch (error.type) {
>       case 'CredentialsSignin':
>         return 'Invalid credentials';
>       default:
>         return 'Something went wrong';
>     }
>   }
>   throw error;
> }
> ```

That's not right

Auth.js internally `try/catch` and throw only one error for the entire sign in process:

https://github.com/nextauthjs/next-auth/blob/1f28f00cacbc9162e94222b388bdc1b06e510708/packages/core/src/lib/actions/callback/index.ts#L304-L308

https://github.com/nextauthjs/next-auth/blob/1f28f00cacbc9162e94222b388bdc1b06e510708/packages/core/src/lib/actions/callback/index.ts#L369-L374

Previously we had a special `try/catch` around `callbacks.authorize()` that return its errors to the client.

**Comment by balazsorban44** [comment]
Please see my proposal for a fix: https://github.com/nextauthjs/next-auth/issues/9099#issuecomment-1913754338

**Comment by nimeshmaharjan1** [comment]
this is so trash

**Comment by barrynorman** [comment]
Why is this closed?
What is the solution for this problem?

**Comment by jjonasramos** [comment]
Where is the solution? Guys, it's really important!

**Comment by mehrwarz** [comment]
If error like "wrong password" which gives an attacker a lever to try a brute force attack,  how can throw an error message like " account blocked for 15 minuets" or 'You account is blocked. contact your system administrator for further help.".

**Comment by davidhellsing** [comment]
As a workaround, you can just export the `authorize` method and call it to return a custom error message (or call whatever database method you’d like to use for validation), before calling `signIn`:

```
// auth.js

export const authorizeCredentials = async ({ email, password }: any) => {
  return await getUser(email, password)
}

export const { handlers, signIn, signOut, auth } = NextAuth({
  providers: [
    Credentials({
      // You can specify which fields should be submitted, by adding keys to the `credentials` object.
      // e.g. domain, username, password, 2FA token, etc.
      credentials: {
        email: {},
        password: {},
      },
      authorize: authorizeCredentials,
    }),
  ],
})
```

```
// action.ts

'use server'

import { authorizeCredentials, signIn } from '@/app/auth'

export default async function action(previousState: any, formData: FormData) {
  const { email, password } = Object.fromEntries(formData.entries())
  const user = await authorizeCredentials({ email, password })
  if (!user) {
    return 'Invalid email or password'
  }
  await signIn('credentials', {
    redirectTo: '/protected',
    email,
    password,
  })
}
```

```
// page.tsx

'use client'

import { useFormState } from 'react-dom'
import action from './action'

export default function Login() {
  const [error, formAction] = useFormState(action, null)
  return (
    <div>
      {error ? <p>{error}</p> : null}
      <form action={formAction}>
      {/* ... */}
      </form>
    </div>
  )
}

**Comment by AhmedBaset** [comment]
> As a workaround, you can just export the `authorize`...

1. This workaround won't work 
2. No need for workarounds at all. See #9871

**Comment by Shtekata** [comment]
You can write something like this:

try {
  await signIn('credentials', credentials);
} catch (error) {
  if (error instanceof AuthError) {
    switch (error.cause?.err?.code) {
      case 'credentials':
        return 'Invalid credentials';
      default:
        return 'Something went wrong';
    }
  }
  throw error;
}

 So as not to raise an error for .code you need to fix the interface of Error object, by adding 'code?: string'.

**Comment by lukecheng** [comment]
I still got the same error. I need detail error more than CallbackRouteError!

**Comment by AhmedBaset** [comment]
> I still got the same error. I need detail error more than CallbackRouteError!

See #9871

**Comment by mehrwarz** [comment]
This work for me
https://stackoverflow.com/questions/78627862/next-auth-signin-return-errorconfiguration-in-responce-for-invalid-credenti/78673275#78673275

**Comment by iamvinny** [comment]
How does it make sense to throw a generic error for authentication fail? There could be many reasons, don't be digging and making decisions for everyone, buddy.

**Comment by mehrwarz** [comment]
Thank you for your reply.

I wanted to share my approach and would appreciate any feedback or corrections. My intention was not to impose my solution or act authoritative. I apologize if my message came across that way.

I’m eager to learn and grow as a developer, especially with Next.js, which I started exploring recently. I’m not in the programming industry; coding is a passion project for me.

If you could point out any errors in my code, I would be very grateful.

Thank you again for your time and expertise.



________________________________

**Comment by kusiewicz** [comment]
/I figured out that when CredentialsSignin error is throwed then its in a way converted into CallbackRouteError. (why???)

Instead of checking if `error.type === "CredentialsSignin"` you can do this: `error.cause.err.code === 'credentials'`
