### ISSUE TITLE
Using creadential provider and defining custom pages will lead to different behaviour than documented

### ISSUE THREAD

**Issue by Psy-Kai** [nextauthjs/next-auth#6514]
### Environment
```
  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 5600H with Radeon Graphics
    Memory: 17.61 GB / 27.27 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.13.0 - /usr/local/share/nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.3 - /usr/local/share/nvm/versions/node/v18.13.0/bin/npm
  npmPackages:
    @auth/sveltekit: ^0.2.0 => 0.2.0 
    @sveltejs/kit: ^1.0.0 => 1.2.10 
    svelte: ^3.54.0 => 3.55.1
```

### Reproduction URL

https://github.com/Psy-Kai/authjs_credential_provider_custom_pages_bug

### Describe the issue

When using credential provider and setting custom pages the behavior is different than documented.

* calling `signIn` with `redirect: redirect: false` will return a response with different content that [documented](https://authjs.dev/reference/utilities/#using-the-redirect-false-option)
* calling `signIn` without setting `redirect` the configured [`signIn`-page](https://authjs.dev/guides/basics/pages) is called with a `?callbackUrl=` parameter

### How to reproduce

1. Clone https://github.com/Psy-Kai/authjs_credential_provider_custom_pages_bug
1. `npm update`
1. `npm run dev` (or `npm run dev -- --host` if using devcontainer)
1. go to page page for error
1. submit credentials

For `Login with CallbackUrl` see how the browsers url changes. 
For `Login without redirect` the returned `json` will be shown at the page. 

### Expected behavior

When using the `redirect: false` I would expect that the returned `json` is as [documented](https://authjs.dev/reference/utilities/#using-the-redirect-false-option)

When using the `callbackUrl` I would expect that I just the `callbackUrl` is opened instead of passing as parameter. Thats how I interpret the [documentation](https://authjs.dev/reference/utilities/#specifying-a-callbackurl).

**Comment by balazsorban44** [comment]
See https://github.com/nextauthjs/next-auth/pull/6575#issuecomment-1411327557
