### ISSUE TITLE
@auth/core email provider. handleAuthorized adds /error to the path even in successful email verification 

### ISSUE THREAD

**Issue by acoreyj** [nextauthjs/next-auth#6518]
### Provider type

Email

### Environment

  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 2.25 GB / 15.57 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  npmPackages:
    @auth/core: ^0.3.0 => 0.3.0 
    next-auth: ^4.18.10 => 4.18.10 
    react: ^18.2.0 => 18.2.0 

### Reproduction URL

https://vsle.io/auth/signin

### Describe the issue

[`handleAuthorized`](https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/lib/routes/shared.ts#L10) gets passed options from https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/lib/routes/signin.ts#L41 and always gets the url from options and appends /error like so `url.pathname += "/error"`.

That same options is then used to construct ursl like so [```const _url = `${url}/callback/${provider.id}?${params}` ```](https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/lib/email/signin.ts#L23)

and
https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/lib/email/signin.ts#L43-L44
```
  return `${url}/verify-request?${new URLSearchParams({
    provider: provider.id,
    type: provider.type,
  })}`
```

 `${url}` at this point always ends in /error

Resulting in urls like

http://localhost:8788/auth/error/verify-request
and
http://localhost:8788/auth/error/callback/email

when using email verification

### How to reproduce

Load any code using the AuthJS email provider such as https://vsle.io/auth/signin and enter an email and submit. 

See you are redirected to https://vsle.io/auth/error/verify-request?provider=email&type=email

Code for this is at https://github.com/geniejs/vsle, I wasn't able to get email to work with the current examples but I can't see why it wouldn't be the same

### Expected behavior

Successful redirects should not have /error in the path

Try here and notice this issue does not occur.

https://3950924a.vsle.pages.dev/auth/signin

The only difference is this patch

https://github.com/geniejs/vsle/blob/dev/patches/%40auth%2Bcore%2B0.3.0.patch

Which has the code implemented in this PR

https://github.com/nextauthjs/next-auth/pull/6492

**Comment by ThangHuuVu** [comment]
Now with the example I see where it went wrong - thanks for the detailed bug report 🙌 Let's reopen the PR and merge it
