### ISSUE TITLE
improve Adapter methods' documentation

### ISSUE THREAD

**Issue by jorgenboganes** [nextauthjs/next-auth#6521]
### What is the improvement or update you wish to see?

Coding examples for passwordless auth with custom adapter in typescript

### Is there any context that might help us understand?

I already have my backend set up with the endpoints to createVerificationToken() and useVerificationToken(). 

However: Why do I need functions like getUser() when I am trying to make a passwordless-only auth with my own database? I cannot find any examples of people who have done this before online, and am struggling a bit to understand the docs without a coding example of sorts.

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/tutorials/creating-a-database-adapter

**Comment by balazsorban44** [comment]
We can probably relax the `Adapter` interface. The `getUser` method indeed does not seem to be called when you *only* have a single Email provider:

https://github.com/nextauthjs/next-auth/blob/1bde7cc8df8d56a37de5f575efa4b11a7c7de488/packages/core/src/lib/routes/callback.ts#L184

However, keep in mind if you add any other provider, you would get an error. We would in that case need to make sure that we assert your config and show a configuration error to make sure it does not happen in production.

If you are OK with "cheating", for now, you can just ignore the TS error about the missing Adapter methods.

**Comment by balazsorban44** [comment]
Adapter methods do need better documentation in any case, so we can leave this issue open to track.

We could add JSDoc comments to each of these methods with thorough explanations and examples of what they are used for.

https://github.com/nextauthjs/next-auth/blob/1bde7cc8df8d56a37de5f575efa4b11a7c7de488/packages/core/src/adapters.ts#L129-L177

**Comment by balazsorban44** [comment]
You can definitely use plain `fetch`! GraphQL adapter are actually just fethc wrappers. Example:

https://github.com/nextauthjs/next-auth/blob/326eadf0edad2a49a92545df44623304cc521958/packages/adapter-dgraph/src/client.ts#L69-L73

Think of an adapter as a mapping of your data to a common CRUD interface that we call internally. That's an adapter. It does not care if its from an ORM, or HTTP calls. :wink:
