### ISSUE TITLE
Hosting Next Auth behind a proxy (Cloudflare Worker) - the OAuth "redirect_uri" is incorrectly set

### ISSUE THREAD

**Issue by zlwaterfield** [nextauthjs/next-auth#6526]
### Question 💬

- I have an application hosted at `frontend.domain.com` (fake domain for privacy reasons) on Vercel.
- I have my website hosted on another provider at `site.domain.com`
- I have my root domain running on a Cloudflare worker at `domain.com` that will proxy some requests to `site.domain.com` and some to `frontend.domain.com` based on the path. 
- The frontend application is using Next Auth for authentication with 3 providers (credentials, Google, LinkedIn) - credentials is working fine, the issue is with the OAuth ones (Google and LinkedIn)

My entire application is working correctly except the `redirect_uri` on the OAuth providers. For some reason the `redirect_uri`'s host is always `frontend.domain.com`. 

I've scoured previous Next Auth issues and Stackoverflow and have not been able to find a solution that works. 

I've tried:
- toggling the `trustHost` option
- all combinations of `NEXTAUTH_URL` and `NEXTAUTH_URL_INTERNAL`
  - `NEXTAUTH_URL=domain.com`
  - `NEXTAUTH_URL=domain.com` and `NEXTAUTH_URL_INTERNAL=frontend.domain.com`
  - `NEXTAUTH_URL=frontend.domain.com` and `NEXTAUTH_URL_INTERNAL=domain.com`
- setting the callbackUrl directly from the client
- I've also added `https://frontend.domain.com/api/auth/callback/linkedin` and `https://domain.com/api/auth/callback/linkedin` to the "Authorized redirect URLs for your app" in LinkedIn.
  
 No matter what I do, the `redirect_uri`'s host doesn't change.

### How to reproduce ☕️

Here is the client request to `domain.com/api/auth/signin/linkedin` from `domain.com/auth/login`
![Screenshot 2023-01-27 at 12 51 26 PM](https://user-images.githubusercontent.com/6392501/215161056-897c7a41-7c47-4fda-85d8-7d965b2fe4d5.png)
![Screenshot 2023-01-27 at 12 51 29 PM](https://user-images.githubusercontent.com/6392501/215161062-def6f882-72dc-4725-9cfd-a14c51c0fd32.png)

And here is the `/authorization` request to LinkedIn from Next Auth
![Screenshot 2023-01-27 at 12 51 37 PM](https://user-images.githubusercontent.com/6392501/215162029-7072f9bf-abc5-4d8b-ae9f-758714a2858c.png)
![Screenshot 2023-01-27 at 12 51 41 PM](https://user-images.githubusercontent.com/6392501/215162038-e5ff6c55-8b99-4964-96f4-b00a97b685ff.png)

I'd expect when I set `NEXTAUTH_URL` to `domain.com` that the `redirect_uri`'s host should be `domain.com`.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by zlwaterfield** [comment]
I found the problem. Next Auth doesn't listen for `NEXTAUTH_URL` when the app is deployed on Vercel. This doesn't make sense and is a bad practice IMO because there are a lot of apps that host behind a proxy and need to customize the `NEXTAUTH_URL`.

Here is the solution I used to get around it: 
```
export default (req, res) => {
  if (process.env.VERCEL) {
    // prefer NEXTAUTH_URL, fallback to x-forwarded-host
    req.headers["x-forwarded-host"] = process.env.NEXTAUTH_URL || req.headers["x-forwarded-host"]
  }
  return NextAuth(req, res, options) // eslint-disable-line new-cap
}
```

from: https://github.com/nextauthjs/next-auth/pull/4509#issuecomment-1119768049 (thanks to @ jjorissen52).

**Comment by balazsorban44** [comment]
As per documentation you don't need to, set NEXTAUTH_URL on Vercel https://next-auth.js.org/deployment#vercel

**Comment by balazsorban44** [comment]
Thanks, this has come up in https://github.com/nextauthjs/next-auth/discussions/6647 newly, so we might revisit this issue.

For context, the intention was not to break proxied deployments, but an observation where people were deploying to Vercel with a wrongly set `NEXTAUTH_URL`, and such, I decided to prefer the platform value over the user-defined one. 

As you noted, this doesn't really make sense, but seemed to be the solution for most people at the time. We could re-visit #4509 and add this, and document that you only need to add `NEXTAUTH_URL` on Vercel, when you have a proxy in front of it. :+1:
