### ISSUE TITLE
Change API catch all

### ISSUE THREAD

**Issue by bastolen** [nextauthjs/next-auth#6528]
### Question 💬

Currently the `AuthHandlerInteral` function ends with the following catch all:
```typescript
return {
  status: 400,
  body: `Error: This action with HTTP ${method} is not supported by NextAuth.js` as any,
}
``` 
This "exposes" the fact that your project uses NextAuth.js, but according to [security through obscurity](https://en.wikipedia.org/wiki/Security_through_obscurity) it can be smart to hide what underlying technology you use for your project.  Following this principle, it might be a good feature to be able to change the body and maybe even change the status code to 404 if you want to.

An option to implement this, might be to add a new property to the callbacks in `AuthOptions` called "catchAll" (or something like that), that receives the request. If the callback is configured and provides a response with the same structure (currently using interface `ResponseInternal`, that is shown below), it will return this response otherwise it will still use the current response. 

```typescript
export interface ResponseInternal<
  Body extends string | Record<string, any> | any[] = any
> {
  status?: number
  headers?: Record<string, string>
  body?: Body
  redirect?: string
  cookies?: Cookie[]
}
```

### How to reproduce ☕️

Not necessary a.t.m.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
No matter what the message would be, you can easily match it with what's inside this repo, public to anyone.

There are other open endpoints (eg.: `/api/auth/session`) that we cannot easily hide anyway, so I don't see much value in this suggestion. What we do to protect you is for example we do not re-use your DB's auto-generated id, to not leak the DB type you are using.
