### ISSUE TITLE
Error on signing in through email

### ISSUE THREAD

**Issue by uinstinct** [nextauthjs/next-auth#653]
**Describe the bug**

I got this error on **email verification**:
```console
[next-auth][error][callback_email_error] SyntaxError: Unexpected token d in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/instinct/Desktop/authset/frontend/node_modules/next-auth/dist/lib/jwt.js:50:65)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/instinct/Desktop/authset/frontend/node_modules/next-auth/dist/lib/jwt.js:22:103)
    at _next (/home/instinct/Desktop/authset/frontend/node_modules/next-auth/dist/lib/jwt.js:24:194)
    at /home/instinct/Desktop/authset/frontend/node_modules/next-auth/dist/lib/jwt.js:24:364
    at new Promise (<anonymous>)
    at Object.<anonymous> (/home/instinct/Desktop/authset/frontend/node_modules/next-auth/dist/lib/jwt.js:24:97)
    at Object.encode (/home/instinct/Desktop/authset/frontend/node_modules/next-auth/dist/lib/jwt.js:64:17)
    at /home/instinct/Desktop/authset/frontend/node_modules/next-auth/dist/server/routes/callback.js:225:41 
https://next-auth.js.org/errors#callback_email_error
```
I went to the above url and read the documentation. But I still could resolve the problem.

**Steps to reproduce**

- I just copied the [example project](https://next-auth-example.now.sh/) in the documentation.
- I set up MongoDB for connecting to the database and it is working fine as read/write in the mongoDB is also working (I checked it)
- I set up an Email Service (which is also working fine) as I am getting the email.
- Now when I click the Signin button on the email. I redirects me to the _/api/auth/signin_ page saying **Try signing with a different account**

- _Another thing to notice_ -> That user with email was created in the database and even in the verificationrequest model, data was added and deleted.

**Expected behavior**
I expected on clicking the _signin button on the email_ to redirect me to homepage (since that is where I called the /api/auth/sigin button).
 
**Screenshots or error logs**

![image](https://user-images.githubusercontent.com/61635505/92604502-371c2e80-f2ce-11ea-9c3f-c48dd38e2c22.png)

**Additional context**
I have attached the whole screenshot of the signing in process which I think should be very helpful for further understanding.

**Comment by iaincollins** [comment]
Hi, this is working on the live demo of the [example project](https://next-auth-example.now.sh) and cannot replicate this issue with it locally (that also works). Can you share your configuration and any custom sign in pages you have?

**Comment by uinstinct** [comment]
Yeah sure.

Here is the code for the **[...nextauth].js** in **pages/api/auth**

```js
import NextAuth from 'next-auth'
import Providers from 'next-auth/providers'


const options = {
  providers: [
    Providers.Email({
      server: {
        host: 'smtp.sendgrid.net',
        port: '25',
        auth: {
          user: process.env.FRONT_EMAIL_USER,
          pass: process.env.FRONT_EMAIL_PASSWORD
        }
      },
      from: process.env.FRONT_EMAILER
    }),
    Providers.Google({
      clientId: process.env.FRONT_GOOGLE_CLIENTID,
      clientSecret: process.env.FRONT_GOOGLE_CLIENTSECRET
    }),
  ],
  database: process.env.FRONT_DB_URL,

  secret: process.env.FRONT_SESSION_SECRET,

  session: {
    jwt: true,     
  },

  jwt: {
    
    signingKey: process.env.JWT_SIGNING_PRIVATE_KEY,
    secret: process.env.FRONT_JWT_SECRET, 
    
  },

  pages: {
  },

  callbacks: { 
  },

  events: { },

  debug: true,
}

export default (req, res) => NextAuth(req, res, options)
```

I have not changed other things and went accordingly with the [example](https://next-auth-example.now.sh/)

**Comment by iaincollins** [comment]
It sounds like the environment variable for `signingKey` is invalid.

It needs to be a JSON Web Key (JWK). I would check that value is set correctly.

Things to check for included leading/trailing spaces and new line characters as they may cause problems. If you remove the `signingKey` option it will generate a key automatically, which should you should be able to confirm that's the issue.

**Comment by uinstinct** [comment]
Yeah, I can confirm that that's the issue.

That works. 
**Removing the `signingKey` from the `jwt` object** makes the app work perfectly fine.

But, now it gives me a warning like _auto generated signingKey_. 

I will try using a JSON Web Key for that.
We can add a better `console.log` message for this error.
I can work on this if you want.

**Comment by melanieseltzer** [comment]
In case this helps someone - was also getting this error, and it was indeed due to a malformed `signingKey`. 

In my case, the output from `jose newkey -s 256 -t oct -a HS512` (the command used to generate the `signingKey`) had a random linebreak inserted, which I didn't notice when I copied it over into my `.env.local` file. After removing the linebreak, it's all good 👍
