### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@auth/core'

### ISSUE THREAD

**Issue by maietta** [nextauthjs/next-auth#6547]
### Environment

System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 4.43 GB / 15.86 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (109.0.1518.69)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    next-auth: ^4.19.0 => 4.19.0

### Reproduction URL

This repo fails in production, but works great locally.
https://github.com/nextauthjs/sveltekit-auth-example

### Describe the issue

I can build an run perfectly find using `npm run dev` including building and previewing `npm run preview`.

HOWEVER:

When I deploy to a NodeJS hosting environment using the @sveltekit/adaptor-node instead of the default @sveltekit/adaptor-auto.

### How to reproduce

Taking the exact example and running it, works locally.

Deploying using the @sveltekit/adaptor-node instead of the default @sveltekit/adaptor-auto is the only thing I change and then I get the following error:

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@auth/core' imported from  /server/chunks/hooks.server-68132b6a.js

I am using node:18-alpine docker container to run this.

### Expected behavior

I expect the app to run in production the same way as it runs locally.

**Comment by balazsorban44** [comment]
The repo doesn't represent your project, please add a reproduction with your custom Docker/vite/svelte config, so we can investigate properly.
