### ISSUE TITLE
Missing TS example of custom signin page

### ISSUE THREAD

**Issue by f98pno** [nextauthjs/next-auth#6549]
### What is the improvement or update you wish to see?

Would it be possible to get the example of pages/auth/signin.js provided on this page:
https://next-auth.js.org/configuration/pages
in Typescript as well?

### Is there any context that might help us understand?

I am working on my first full application using https://create.t3.gg/ and would like to create my own NextAuth signing page in a typesafe way, but found the documentation about this just to cover JS.

**Comment by shubhamku044** [comment]
Hey, can I take this issue? I will write the example in typescript as well.

**Comment by balazsorban44** [comment]
I would just prefer if we convert the code examples on https://next-auth.js.org/configuration/pages to TS

for simplicity, there's even an `Edit this page` button at the bottom.

**Comment by shubhamku044** [comment]
Hey @balazsorban44, I went through the `next-auth/react` folder. I found a few things 
![Screenshot 2023-01-30 at 9 38 03 PM](https://user-images.githubusercontent.com/77788249/215530567-e8ea2ec6-974d-4eb1-854e-3c9cd1f80b2c.jpg)

To convert, the code examples to TS we first have to create a proper type variable and then export the type variable. Please let me know if I am wrong.

**Comment by balazsorban44** [comment]
This is the only file needing an edit: https://github.com/nextauthjs/next-auth/edit/v4/docs/docs/configuration/pages.md

To be honest, @f98pno could you clarify exactly which block on that page caused issues for you with TypeScript? Most are very straightforward snippets.

**Comment by balazsorban44** [comment]
Yeah, let's do that then, if OP does not comment on anything else, I'm inclined to close this issue with the above suggestion merged.

**Comment by rawbinary** [comment]
i guess, this issue is applicable for new docs as well (main branch) on https://authjs.dev/guides/basics/pages .
@balazsorban44 Should I create a PR for that as well, linking on this issue ?

**Comment by balazsorban44** [comment]
Not necessary, as the new docs are being rewritten from scratch. :+1:
