### ISSUE TITLE
Sponsor

### ISSUE THREAD

**Issue by guiaramos** [nextauthjs/next-auth#655]
**Your question**
Is there anyway to sponsor the project? Ex. GitHub Sponsors

**What are you trying to do**
Sponsor the project

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Hi there! So good to here you would like to sponsor the project! Very appreciated!
I don't think we currently have anything set up. I am going to note it for discussion, and check back when I have some information.
