### ISSUE TITLE
unstable_getServerSession type is broken in 4.19.0

### ISSUE THREAD

**Issue by joulev** [nextauthjs/next-auth#6556]
### Environment

* `next-auth` 4.19.0
* I believe all other system info are irrelevant, but I'm happy to share if needed

### Reproduction URL

N/A

### Describe the issue

The type of `unstable_getServerSession` is broken from 4.19.0.

```ts
import { getServerSession, unstable_getServerSession } from "next-auth";

const session1 = await getServerSession();
const session2 = await unstable_getServerSession();

session1?.user;
// Working fine as expected
session2?.user;
// Property 'user' does not exist on type '{}'.
```

### How to reproduce

See above.

### Expected behavior

`unstable_getServerSession` should still work as before, until maybe v5.0.0? when it can finally be removed in a breaking change.

**Comment by balazsorban44** [comment]
yeah, looks like we need to copy over the generic too:

https://github.com/nextauthjs/next-auth/blob/2311be75897ebd0d112a4916ed38b2d710286cdf/packages/next-auth/src/next/index.ts#L93

https://github.com/nextauthjs/next-auth/blob/2311be75897ebd0d112a4916ed38b2d710286cdf/packages/next-auth/src/next/index.ts#L173

Want to open a PR? (against the `v4` branch)

**Comment by joulev** [comment]
Sure, done!

**Comment by balazsorban44** [comment]
Thanks, I merged it! Will be released shortly, waiting a few days to see if we can add something else in the next patch. :pray: Feel free to ping me if I don't come back this week. :green_heart:
