### ISSUE TITLE
Module not found: Can't resolve 'v8'

### ISSUE THREAD

**Issue by socketopp** [nextauthjs/next-auth#6558]
### Question 💬

Environment
```
  System:
    OS: Windows 10 10.0.19045
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
    Memory: 5.93 GB / 15.95 GB
  Binaries:
    Node: 18.12.1 - C:\node\node.EXE
    npm: 9.2.0 - C:\node\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (109.0.1518.70)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    next: ^13.1.2 => 13.1.2
    next-auth: ^4.19.0 => 4.19.0
    react: ^18.2.0 => 18.2.0
```
When importing the authOptions needed to call getServerSession I get the following issue. 
Not sure why. Can't exactly pinpoint what in my config that causes the issue. Only using Google as a provider. 

**Do I need to install v8 for this to work? **

I also get this error when I install v8 and ty to call getServerSession
```
TypeError: (0 , next_auth_react__WEBPACK_IMPORTED_MODULE_4__.getServerSession) is not a function
```

```

https://nextjs.org/docs/messages/module-not-found
wait  - compiling...
error - ./node_modules/openid-client/lib/helpers/deep_clone.js:1:33
Module not found: Can't resolve 'v8'

Import trace for requested module:
./node_modules/openid-client/lib/issuer.js
./node_modules/openid-client/lib/index.js
./node_modules/next-auth/core/lib/oauth/callback.js
./node_modules/next-auth/core/routes/callback.js
./node_modules/next-auth/core/routes/index.js
./node_modules/next-auth/core/index.js
./node_modules/next-auth/next/index.js
./node_modules/next-auth/index.js
./pages/api/auth/[...nextauth].js
```

### How to reproduce ☕️

Just import authOptions and on that page it will require v8.

`import { authOptions } from '../../pages/api/auth/[...nextauth]';`

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by acc-nicholas** [comment]
I'm also experiencing this issue.

**Comment by balazsorban44** [comment]
@acc-nicholas https://github.com/nextauthjs/next-auth/issues/6558#issuecomment-1407785409

**Comment by acc-nicholas** [comment]
I have very little experience with auth or nextauth, so i'm really just trying to follow the docs to get started on a new app.

What i've done:
- installed `next-auth` on version `4.18.10`
- added a custom oauth provider at `src/pages/api/auth/[...nextauth].ts`
```ts
import NextAuth from "next-auth";
import type { NextAuthOptions } from "next-auth";

export const authOptions: NextAuthOptions = {
  // Configure one or more authentication providers
  providers: [
    {
      id: process.env.OIC_CLIENT_ID || "unknown",
      name: process.env.OIC_CLIENT_ID || "unknown",
      type: "oauth",
      clientId: process.env.CLIENT_ID,
      clientSecret: process.env.CLIENT_SECRET,
      authorization: process.env.OIC_ISSUER + "/authorize",
      token: process.env.OIC_ISSUER + "/token",
      userinfo: process.env.OIC_ISSUER + "/user-info",
      profile(profile) {
        return {
          id: profile.id,
          token: profile.token,
        };
      },
    },
  ],
  callbacks: {
    async jwt({ token, account }) {
      // Persist the OAuth access_token to the token right after signin
      if (account) {
        token.accessToken = account.access_token;
      }
      return token;
    },
    async session({ session, token, user }) {
      // Send properties to the client, like an access_token from a provider.
      return session;
    },
  },
};
export default NextAuth(authOptions);

```
- update `_app.ts` with the session.
```ts
import { authOptions } from "./api/auth/[...nextauth]";

...

export const getInitialProps: GetServerSideProps = async ({ req, res }) => {
  const session = await getServerSession(req, res, authOptions);

  if (!session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }
  return {
    props: {
      serviceName: process.env.SYSTEM_NAME,
      stack: process.env.STACK,
      session,
    },
  };
};
```

**Comment by balazsorban44** [comment]
`getInitialProps` is called both on the server and in the browser, so it won't have the Node.js-only `v8` module, hence the error. Please refer to the [Next.js docs](https://nextjs.org/docs/api-reference/data-fetching/get-initial-props#:~:text=For%20the%20initial%20page%20load%2C%20getInitialProps%20will%20run%20on%20the%20server%20only.%20getInitialProps%20will%20then%20run%20on%20the%20client%20when%20navigating%20to%20a%20different%20route%20via%20the%20next/link%20component%20or%20by%20using%20next/router) So that is not a valid reproduction.

**Comment by erbaafidotama** [comment]
Hello, i have same issue. How to solving?

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth/issues/6558#issuecomment-1407785409

**Comment by balazsorban44** [comment]
Closing, as I am fairly confident in my comment here: https://github.com/nextauthjs/next-auth/issues/6558#issuecomment-1410220853

Feel free to open a new issue with a reproduction.

**Comment by jokester** [comment]
The [SessionProvider example](https://next-auth.js.org/getting-started/client#sessionprovider) used `pageProps.session` in `_app.tsx`, but not pointing out how the initial `session` could be provided. The only solution I found is to `getServerSideProps` in (every) Page Component.

The document follows:

> If every one of your pages needs to be protected, you can do this in getInitialProps in _app, otherwise you can do it on a page-by-page basis

If this can really be done in a `App.getInitialProps()`, maybe we should be document it.
