### ISSUE TITLE
support throwing custom errors from `signIn` callback

### ISSUE THREAD

**Issue by rolanday** [nextauthjs/next-auth#6563]
### Description 📓

Sign-in callback promise (at least for Svelekit provider) resolves to boolean, which is too blunt for providing feedback to the end-user in error case (i.e., returns `false`). Please change return type to `number` or `boolean | number` so client can provide more actionable response to end-user in event of sign-in failure (e.g., duplicate account, account suspended, no such email, etc.)

Thank you!

```
    signIn: (params: {
        user: User | AdapterUser;
        account: A | null;
        profile?: P;
        email?: {
            verificationRequest?: boolean;
        };
        credentials?: Record<string, CredentialInput>;
    }) => Awaitable<boolean>;
```

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
Hi, something similar was discussed in https://github.com/nextauthjs/next-auth/issues/6458.

You can currently throw an error with a custom message that will be the content of the `error` query parameter, instead of the default `AccessDenied`.

I recommend being very careful about the information you want to expose to the client though. In the future, I would like the user to be able to throw specific errors, but not generic ones, to avoid exposing too much.

**Comment by rolanday** [comment]
Thank you! 100% hear you re: info to surface. Appreciate the quick response.

**Comment by rolanday** [comment]
Hi @balazsorban44 
I tried throwing an error inside the sign-in callback...

```
  signIn: async ({ account, profile, user }) => {
      throw new Error("test");
```
... and redirects to: `http://localhost:5173/auth?error=Configuration`

I'm routing to a custom error page, but even if I use the standard authjs error page, same deal. Maybe this is SvelteKit specific issue?

**Comment by balazsorban44** [comment]
unlikely sveltekit specific. a reproduction would help a lot though.

**Comment by rolanday** [comment]
Here is the repro:
https://github.com/appyture/sveltekit-t3-bootstrap-nextauth-6563-repo

The file where throwing error in callback:
https://github.com/appyture/sveltekit-t3-bootstrap-nextauth-6563-repo/blob/main/src/lib/auth/handle.ts

You'll, of course need to rename .env.example to .env and provide your own github id & secret, then just `npm run dev` and try to sign in, and note the error page URL. Thanks!

**Comment by rolanday** [comment]
Hi @balazsorban44 , please let me know if anything else is needed from me. Thanks again for your attention to this.

**Comment by rolanday** [comment]
fwiw, this the behavior is correct on next.js, so does appear this issue is specific to SvelteKit (or @auth/core). Thanks.

**Comment by balazsorban44** [comment]
Yeah, I meant `@auth/core`, `next-auth` is a different package and does not share code with SvelteKit Auth.

Hmm, so I checked, and we actually stopped supporting to throw an error already: https://github.com/nextauthjs/next-auth/blob/28ae5d463958cf72349c925b57ef0fae3425254a/packages/core/src/lib/routes/shared.ts#L18-L24

I think the way to solve this would be to expose a `SignInError` that you as the developer can throw and we could attach `code=` or similar to the error URL when we detect that.

Let's discuss this further. :+1:

**Comment by rolanday** [comment]
"I think the way to solve this would be to expose a SignInError that you as the developer can throw and we could attach code= or similar to the error URL when we detect that."

This would suit my needs quite well, and better approach IMO than letting the developer throw any error where not clear what value to include in query param. E..g, `throw new SignInError(403)` => /error?code=403.

Thanks for getting back 👍

**Comment by nash-an** [comment]
It doesn't seem like there is any support for custom errors still (on @auth/core or sveltekit). I might be doing something wrong, but throwing errors doesn't work, returning strings doesn't work (#8422), and the docs do not mention anything that might allow this.

**Comment by ImBIOS** [comment]
Add this to migration guide:

Before:
```
        return `/login?error=${err}&param2=${isBoolean ? 1 : 0}`

```

After:
```
class CustomAuthError extends AuthError {
            static type = `${e as string}&param2=${isBoolean ? 1 : 0}`
          }

          throw new CustomAuthError(e)
```

Something like this, you can hack as you like. but keep in mind, it's not a best practice to pass information from server to client if you're not sure.

**Comment by tylermcrobert** [comment]
@ImBIOS where is the variable `i` coming from? I'm not clear on your response.

**Comment by JoaoPedroCamargo** [comment]
Did you solve this issue? I'm having the same problem on my project, but wasn't able to hadle the error returning from SignIn callback.

**Comment by tylermcrobert** [comment]
@JoaoPedroCamargo No, unfortunately not.

**Comment by JoaoPedroCamargo** [comment]
> Add this to the migration guide:
> 
> Before (next-auth v4):
> 
> ```
>         return `/login?error=${err}&param2=${isBoolean ? 1 : 0}`
> ```
> 
> After (next-auth v5):
> 
> ```
> catch (e) {
> class CustomAuthError extends AuthError {
>             static type = `${e as string}&param2=${isBoolean ? 1 : 0}`
>           }
> 
>           throw new CustomAuthError(e)
> // would be almost the same `/login?error...`
> ```
> 
> NOTE: The difference is that the string from `static type` will be URL parsed for safety reasons. You need to parse the params yourself and create a workaround, I also use search params parsing workaround to migrate to the new v5 beta.
> 
> Something like this, you can hack as you like. but remember that it's not a best practice to pass information from server to client if you're not sure.

I didn't understand where is this file that you did the catch. Is it inside the SignI callback? where can I catch this error?

**Comment by sooperjos** [comment]
Great package this...
