### ISSUE TITLE
Use Next-auth to handle session but ALSO to handle normal OAuth

### ISSUE THREAD

**Issue by Khaaz** [nextauthjs/next-auth#6577]
## Context
I am already using next-auth to authenticate with Oauth, handle session and so on.
In my app, I allow poeple to sign in with different account (discord, twitch, twitter, youtube...). That's good, no problem here.

## Issue
But I would also like to use normal OAuth to allow user to sign-in to a different account to retrieve information and data from this account.
Basically I want to use next-auth as the session / login provider, as well as just a tool to make Oauth easy.

Is that possible? Or would I have to use separates packages / handle Oauth myself for every provider I could want to use?

## Practical use-case
In practice:
- A User login with discord
- He can click on a button to start connection with another account (for instance twitter).
- This should not login-in / log-out the user in this case. We just retrieve information and a token from user connection, that we can then use as we want.
- The use can now resume to normal activity, including log-in with yet another provider

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
This is already possible.

You can use a database adapter to connect different provider accounts. This is already handled for you out of the box. Check out the docs https://next-auth.js.org/adapters/overview

**Comment by Khaaz** [comment]
@balazsorban44 
I am very sorry, but I don't understand how that would help my case.

How should I use adapter?
If I was not clear enough in my original issue, I can try to add more precision if there is something that isn't understandable.

**Comment by Khaaz** [comment]
@balazsorban44 Hello,
I am adding a comment to clarify my question. I figured it might not have been quite right.

I want a way to start the Oauth process (get the oauth token, and the Oauth data) for a Provider WITHOUT authentication.
Basically fetch a Profile for a specific Provider in itself.

In fact I also want the authentication (so the normal next-auth use_case) which work great. But I would like to be able to make Oauth request independantly (for example when clicking on a button), fetching the oauth token (and then do subsequent request to the API I am talking to) without starting the authentication process and so on.

Currently, the way I understand how next-auth work, I would have to implement Oauth request myself, or use other libraries but I don't understand how to use next-auth to do that (which is a shame considering all OAuth process is already implemented in the lib).

Is it possible? What am I missing?

**Comment by rmonnier9** [comment]
Hi Khaaz,

Have you found a way to use NextAuth for your needs ?

I have the same question as you have, I don't understand if NextAuth can just handle an OAuth flow without authentication.

Thanks for your help !
