### ISSUE TITLE
NextJs decode provider token from Mobile app

### ISSUE THREAD

**Issue by Trudgedy** [nextauthjs/next-auth#6578]
### Question 💬

``Hi All

I am struggling to set up a NextJs RestApi + Admin Portal (with Next Auth + Cognito as a provider ). With a React Native frontend calling the Next servers APIs. I have both the NextServer secured as well as the mobile app but I cannot figure out how to get a correct token on react native to send with the Api calls to the next server.
I have tried for a while now to get this right but feel like I am either missing something basic or this is not possible.

I have tried generating a token from the React Native side using aws-amplify as well as other auth packages, but only get null for the token in my Api.

I have confirmed that I can add the token to Bearer headers but I am assuming that Next-Auth signs the JWT differently.

Is there a correct way to implement this? 

I have done something similar before however using .Net5 as a standalone API and Angular + aws-amplify
The code was simple to add to startup.cs the correct Authority and the .net API was able to decode the tokens

```
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options =>
			{
				options.Authority = Configuration["AWSSettings:CognitoAuthority"];
				options.Audience = Configuration["AWSSettings:CognitoAudience"];
			});
```

Then from the angular, I sent the bearer header from Auth.currentSession().getIdToken().getJwtToken() (amplify)
This worked well for me but I cannot figure out how to achieve something similar using NextJs

### How to reproduce ☕️
The project is pretty new so its currently up to date on most of the packages, Next 13.1.1, and the latest next-auth.

Next config:
```
CognitoProvider({
            clientId: process.env.COGNITO_CLIENT_ID,
            clientSecret: null,
            issuer: process.env.COGNITO_ISSUER,
            client: {
                token_endpoint_auth_method: 'none',
            },
            // debug: true,
        }),
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by Trudgedy** [comment]
I found a solution, however, could not get the Next-Auth middleware to fire when the token was sent using the Bearer token in headers. Which is my ideal way of handling the routes.

I wrapped the getToken({req}) call so that if there is no JWT Web token it would try encode the token separately
Lastly ChatGpt somehow got me onto the package aws-jwt-verify which has everything you need to verify a token generated by aws-amplify/auth, in my case from react-native.

components/utils/auth.utils.ts
```
import { NextApiRequest } from 'next'
import { CognitoJwtVerifier } from 'aws-jwt-verify'
import { getToken } from 'next-auth/jwt'

// Verifier that expects valid token:
const verifier = CognitoJwtVerifier.create({
    userPoolId: process.env.COGNITO_USERPOOL_ID ?? '',
    tokenUse: 'id',
    clientId: process.env.COGNITO_CLIENT_ID ?? '',
    issuer: process.env.COGNITO_ISSUER ?? '',
})

export async function getMobileToken(req: NextApiRequest) {
    let token = null
    try {
        token = await getToken({ req })
    } catch (error) {
        console.log('Could not get JWT Web Token')
    }
    try {
        if (!token)
            token = await getToken({
                req,
                async decode({ token }) {
                    if (!token) return null
                    const decoded = await verifier.verify(token)
                    return decoded
                },
            })
    } catch (error) {
        return null
    }
    console.log('Mobile Token:', token)
    return token
}

```

**Comment by smehdux** [comment]
Hi

I'm in the same scenario with Keycloak, I'm getting NULL  with `getToken({ req }` function, now I can get it from headers `(req.headers.get('authorization')`) but still unable to decode and validate it, ideally I'd prefer an agnostic lib to do that. Anyone have an idea ?

**Comment by smehdux** [comment]
Hi

I'm in the same scenario with Keycloak, I'm getting NULL  with `getToken({ req }` function, now I can get it from headers `(req.headers.get('authorization')`) but still unable to decode and validate it, ideally I'd prefer an agnostic lib to do that. Anyone have an idea ?
