### ISSUE TITLE
Will next auth auto create a mongodb collection when user logs in to store user info?

### ISSUE THREAD

**Issue by kevinmachstudio** [nextauthjs/next-auth#659]
## Context

I was able to hook up mongodb with next auth such that a user is able to login via email. When I check my database though, I don't see any data regarding the user (e.g. the email I just used to sign in). 

## Question

Where is the info about the user stored when users login? Does nextjs handle this or is this info something I'd have to write to the database via my own API (i.e. when a user logins, send the info to my own backend API which will write to the mongodb database)?  

## More Details

I was able to connect to the mongodb database without specifying a database name so not sure if next auth knows what database to store the data in.

`mongodb://username:password@127.0.0.1:27017`

**Comment by iaincollins** [comment]
> I was able to connect to the mongodb database without specifying a database name so not sure if next auth knows what database to store the data in.

Hmm I would guess that is probably the issue.

Something like `mongodb://username:password@127.0.0.1:27017/your-database-name` should work.

You may need to enable the NextAuth.js option `debug: true` to see errors - in fairness it ought to pre-emptively error in a case like this regardless of that setting, but it might not unless you enable debug right now.

**Comment by kevinmachstudio** [comment]
@iaincollins i forgot to mention I was getting `MongoError: Authentication failed` when i specified a database name. the full error is here

```
[next-auth][error][adapter_connection_error] MongoError: Authentication failed.
    at MessageStream.messageHandler (/usr/src/app/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:315:20)
    at processIncomingData (/usr/src/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/usr/src/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at MessageStream.Writable.write (_stream_writable.js:318:11)
    at Socket.ondata (_stream_readable.js:716:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12) {
  ok: 0,
  code: 18,
  codeName: 'AuthenticationFailed'
} 
https://next-auth.js.org/errors#adapter_connection_error
(node:19) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'manager' of 'connection' as it is null.
    at Object.<anonymous> (/usr/src/app/node_modules/next-auth/dist/adapters/typeorm/index.js:102:9)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/usr/src/app/node_modules/next-auth/dist/adapters/typeorm/index.js:28:103)
    at _next (/usr/src/app/node_modules/next-auth/dist/adapters/typeorm/index.js:30:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:19) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kevinmachstudio** [comment]
@iaincollins i just noticed that a `test` mongodb database was created (when I didn't specify a database name in the uri when connecting in next auth) and there are 3 collections: `sessions`, `users`, and `verificationRequests`. I see the user login inside `users`, is the `test` database name expected?

**Comment by kevinmachstudio** [comment]
found out that i was using my root user to access the database so that's why the authentication failed, so I created a new user and that let me connect to the database, i'm guessing `test` database will be created if no database was specified

**Comment by tobiasriemenschneider** [comment]
>i'm guessing test database will be created if no database was specified

@kevinmachstudio I think that this is a kind on "Mongo standard behaviour".

**Comment by PawelPyc154** [comment]
Make sure your password does not include $

**Comment by reply2sagar** [comment]
Yes it creates the tables automatically in mongodb database. tested and passed. Please contact me for any more questions on this.
