### ISSUE TITLE
Property "expires" missing in type import("next-auth")

### ISSUE THREAD

**Issue by hagenek** [nextauthjs/next-auth#6599]
### Question 💬

TS2741: Property 'expires' is missing in type 'import("next-auth").Session' but required in type /next-auth/core/types").Session'.

Also getting this error in [...nextAuth].ts

`TS2305: Module '"next-auth"' has no exported member 'NextAuthOptions'.`

In use: 

```
const MyApp: AppType<{ session: any }> = ({ Component, pageProps: { session, ...pageProps } }) => {
  return (
    <SessionProvider session={session}>
      <CssBaseline>
        <ThemeProvider theme={darkTheme}>
          <DashboardLayout>
            <ReactQueryDevtools initialIsOpen={true} />
            <Component {...pageProps} />
          </DashboardLayout>
        </ThemeProvider>
      </CssBaseline>
    </SessionProvider>
  )
}
```

Any suggestions how to fix?

### How to reproduce ☕️

on next-auth 4.18.6.
Using prisma adapter.

```
const MyApp: AppType<{ session: any }> = ({ Component, pageProps: { session, ...pageProps } }) => {
  return (
    <SessionProvider session={session}>
      <CssBaseline>
        <ThemeProvider theme={darkTheme}>
          <DashboardLayout>
            <ReactQueryDevtools initialIsOpen={true} />
            <Component {...pageProps} />
          </DashboardLayout>
        </ThemeProvider>
      </CssBaseline>
    </SessionProvider>
  )
}
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by Mayvis** [comment]
Maybe you should use `useSession` from `next-auth/react`. 

```tsx
import { useSession } from 'next-auth/react'

const Home = () => {
  const { data } = useSession()

  // data.expries <----- and you can get the expires value
}
```
I gave you the typescript hint when I using `useSession` method.

![截圖 2023-02-02 下午9 13 13](https://user-images.githubusercontent.com/12667910/216334481-d58d7e7d-3bc2-4a02-89fa-61ec0add6d96.png)
