### ISSUE TITLE
Callbacks documentation is incorrect for session()

### ISSUE THREAD

**Issue by domharrington** [nextauthjs/next-auth#6602]
### What is the improvement or update you wish to see?

The [docs](https://next-auth.js.org/configuration/callbacks#session-callback) say that the callback is passed the following values:

```js
callbacks: {
  async session({ session, token, user }) {
    // Send properties to the client, like an access_token and user id from a provider.
    session.accessToken = token.accessToken
    session.user.id = token.id
    
    return session
  }
}
```

This implies you can add the access token to your session by fetching it out of the provided token argument.

Looking at the code though, this isn't the case: https://github.com/nextauthjs/next-auth/blob/fb43c5da053c757b085ae86af87bc32aa0de5f61/packages/core/src/lib/routes/session.ts#L125-L137

It does appear as though the token is passed in if you're using JWT though: https://github.com/nextauthjs/next-auth/blob/fb43c5da053c757b085ae86af87bc32aa0de5f61/packages/core/src/lib/routes/session.ts#L54. But then in that case, you're just passing in `{ session, token }` and the user is missing.

### Is there any context that might help us understand?

Unclear how to implement a custom session({}) callback from the docs. Unclear examples. 

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/configuration/callbacks#session-callback

**Comment by balazsorban44** [comment]
From the docs section you linked:

> When using database sessions, the User object is passed as an argument.
> When using JSON Web Tokens for sessions, the JWT payload is provided instead.

I clarified that the former refers to `user` and the latter to `token`: https://github.com/nextauthjs/next-auth/commit/0bc4fcb51a02667363722a01fcfd3b9243f57cfd

**Comment by domharrington** [comment]
Thanks! That's much clearer. Would love to see some more e2e examples of setting up NextAuth, an oauth provider and a database adapter. It's so extensible (which is great!) but it can be a little tough to piece together the moving parts...

- Where is the access token? Should the access token ever be on the session, or is that accessible client side?
- Is it saved in the database, or just in JWT? What are the pros and cons to each strategy?
- If i'm using mongodb + prisma, should I use the MongoDB adapter or the prisma adapter? What are the pros and cons? 
- Why is the jwt() callback called with different values on login vs after login?

I think I've got a solution that seems to work well now for NextAuth + GitHub Oauth + MongoDB:

```js
export const authOptions = {
  providers: [
    GithubProvider({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET,
    }),
  ],
  session: {
    strategy: "jwt",
  },
  callbacks: {
    async jwt({ token, account, }) {
      if (account?.access_token) {
        token.accessToken = account.access_token;
      }
      return token;
    },
    async session({ session, token }) {
      session.user.id = token.sub;
      return session;
    },
  },
  adapter: MongoDBAdapter(clientPromise),
};
```

But it was definitely a bit of a struggle to piece together all of these different components. Thanks for the library, it seems great! I hope this doesnt come across too negative.

**Comment by balazsorban44** [comment]
Most of your questions are answered in the docs at https://next-auth.js.org, we have a search field, that hopefully helps. That said, the new docs at http://authjs.dev/ is getting a bit of an overhaul, which hopefully will be an easier-to-understand structure.

We will have dedicated guides for common use cases, dedicated concepts pages for auth-related terms, and all API reference documentation will be inferred from the source code, with an example on most of the properties and how to use them, available both on our website as well as in modern IDEs (like VSCode), linking to guides/concepts as well. This is work in progress! :pray:
