### ISSUE TITLE
[...nextauth].ts not exporting during Next Export

### ISSUE THREAD

**Issue by chasechow7** [nextauthjs/next-auth#6604]
### Question 💬

Currently I can login fine when using localhost but for the deployed version of my site, I am having trouble accessing the login page on sign-in. I notice [...nextauth] does not exist as one of my .html pages when i export to the /out folder before deploying/uploading to S3.

Is there a way I can get [...nextauth] to export?

Found a similar issue here but no resolution: https://github.com/nextauthjs/next-auth/issues/570

### How to reproduce ☕️

Next export and deploy.

Try to login

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by chasechow7** [comment]
I've set NEXTAUTH_URL= to my url/test/ui in .env.local

rebuilt and redeployed.

My base path has been modified. Heres my next.config:
```
const withTM = require('next-transpile-modules')(['@cloudscape-design/components']);

const STAGE = 'test';
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: { unoptimized: true },
  basePath: `/${STAGE}/ui`,
};

module.exports = withTM(nextConfig);
```

**Comment by balazsorban44** [comment]
Hi, `next-auth` requires a server runtime (API routes), meaning that it's not compatible with `next export`. See https://nextjs.org/docs/advanced-features/static-html-export#unsupported-features
