### ISSUE TITLE
JWS, JWE

### ISSUE THREAD

**Issue by vincentserpoul** [nextauthjs/next-auth#6613]
### Question 💬

any reason why the embedded JWT in the JWE is unsigned by default? (referrring to this core [piece of code](https://github.com/nextauthjs/next-auth/blob/2cbf81544523044596125d2c87175ee4ec61df06/packages/core/src/jwt.ts))

It would bring non-repudiation brought by JWS on top of the JWE properties.

I know it's possible to override the encode and decode funcs, but it would probably be a better default, wouldn't it?

### How to reproduce ☕️

its the default behaviour.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by vincentserpoul** [comment]
answering my own question after thinking 2mn...
it is not bringing anything as it would be the same key for signature and encryption.

**Comment by balazsorban44** [comment]
Yes, it was considered before, but it would bring an unnecessary overhead. In previous versions, we only signed by default, but since v4, we changed to encryption instead.
