### ISSUE TITLE
Database migration guide (from v3) for SQLite

### ISSUE THREAD

**Issue by djyde** [nextauthjs/next-auth#6618]
### What is the improvement or update you wish to see?

Can someone provide a database migration guide for SQLite? I use SQLite with next-auth 3. But the documentation only provide pgsql/mysql migration sql.

### Is there any context that might help us understand?

FYI

**Comment by balazsorban44** [comment]
Since v3 has been unsupported for a very long time, it's unlikely we will work on this, unfortunately, so closing! :pray:
