### ISSUE TITLE
How to return Error instead of 'null' in the 'authorized' function callback?

### ISSUE THREAD

**Issue by einKnuffy** [nextauthjs/next-auth#6619]
### Question 💬

I think, my question is pretty self-explanatory.
How to return Error instead of 'null' in the 'authorized' function callback?

I don't know, because I want then the sign in/sign up page not to have an error like how it currently is: "Your credentials are wrong or sth". I want to give better errors and feedback (like name already taken, etc.). But how to do that?

### How to reproduce ☕️

https://next-auth.js.org/providers/credentials

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
You can throw an `Error`, and the message will be part of the URL like: `/error?error=message`.

Disclaimer: Be careful how specific you are though.

Common practice is to not let the user know if their email or password is wrong specifically, to avoid helping a hacker enumerate your user list or brute force through a common password list. Something like "Invalid credentials" is more appropriate.

**Comment by einKnuffy** [comment]
@balazsorban44 Yeah, I did. But weirdly have another issue that simply is that, when logging with credentials, and logging the values, first time they are right and in the second line, they are undefined.

That's why the values are then undefined.
