### ISSUE TITLE
Page protection documentation

### ISSUE THREAD

**Issue by niikeec** [nextauthjs/next-auth#6624]
### What is the improvement or update you wish to see?

Could we include this function in the docs, which DRY's [this pattern](https://next-auth.js.org/configuration/nextjs#in-getserversideprops).

```
export const requireAuth =
  (
    func: (
      ...args: [...Parameters<GetServerSideProps>, ...[session: Session]]
    ) => ReturnType<GetServerSideProps>
  ) =>
  async (ctx: GetServerSidePropsContext) => {
    const session = await getServerAuthSession(ctx);

    if (!session) {
      return {
        redirect: {
          destination: `/api/auth/signin?callbackUrl=${encodeURIComponent(
            ctx.resolvedUrl
          )}`,
          permanent: false,
        },
      };
    }

    return await func(ctx, session);
  };
```

And then you can use it to protect a page like this
```
// page.tsx
export const getServerSideProps = requireAuth(async (ctx, session) => {
  return { props: {} };
});
```

### Is there any context that might help us understand?

N/A

**Comment by balazsorban44** [comment]
Thanks, but it's mostly stylistic opinion. You are obviously free to do abstracting away the logic as you see fit in your codebase, but for the documentation, I think it's best to keep it simple. 👍
