### ISSUE TITLE
How can i replace signin route after signin successfully ?

### ISSUE THREAD

**Issue by zwelhtetyan** [nextauthjs/next-auth#6626]
### Question 💬

It is allow to go back the previous signin route after signin successfully. How do i replace this route.

I use signIn method like below.

`onClick={() => signIn('google')}` 

### How to reproduce ☕️

https://github.com/zwelhtetyan/tiktok

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
https://next-auth.js.org/getting-started/client#specifying-a-callbackurl

**Comment by zwelhtetyan** [comment]
> https://next-auth.js.org/getting-started/client#specifying-a-callbackurl

I'v  tried callbackURL but it still allow to go back previous loginRoute after redirect .
