### ISSUE TITLE
Refresh token rotation

### ISSUE THREAD

**Issue by aquamoth** [nextauthjs/next-auth#6634]
### What is the improvement or update you wish to see?

The documentation describes how to use refresh tokens if the provider supports them. 

However, relying on refresh tokens for online applications is far from good practice.

I'd like to see a clear example how to make the browser do a re-sign-in before/when the access token expires to fetch a new token as long as the user is still logged in.

### Is there any context that might help us understand?

I'd especially like an example how to do this in the background in case of a SPA, so I dont lose the current state.

Can auth.js do a fetch request that supports a redirect-chain, and in case of not completing silently it can force the user to save his work and manually log in again?

### Does the docs page already exist? Please link to it.

https://authjs.dev/guides/basics/refresh-token-rotation

**Comment by balazsorban44** [comment]
Hi, currently this is tricky due to the fact that most refresh tokens can only be used once. There's a discussion at https://github.com/nextauthjs/next-auth/discussions/3940 with more details and an idea would be to use [Web Locks API](https://caniuse.com/?search=web%20 locks) which has come a long way in terms of browser support since I checked.

> However, relying on refresh tokens for online applications is far from good practice.

Could you explain what you mean by this?

**Comment by aquamoth** [comment]
Thanks for the reference, @balazsorban44. I will check it out.

My concern about refresh tokens is all about user consent and offline access. For example:

As an end user,
when I login to a third party website,
I may login using Google's OIDC server 
with scopes that allow the website to read my documents.

I will however not allow the "offline_access" scope, because the website could then keep accessing my documents after I leave. Now I can keep working with my documents until the access token expires, after which the website needs to request a new token. 

Without a refresh token, this can be done by:
1. redirecting the browser back to the oidc servers token endpoint.
2. provided I am still logged in and have not de-authed the website, follow the 302 redirect back to the websites callback endpoint with a new code.
3. wait for the website to fetch a new access token using said code.
4. finally return to the page the user was working on.

In case the website is a single page application, redirecting the entire browser breaks the user experience.  Thus I wonder if this can be achieved another way, for example with a javascript `fetch()` that redirects as long as the user is still logged in to Google, and in case of a `401` falls back to redirect the browser so the user can properly login again?

**Comment by cloudnothings** [comment]
It sounds like you're concerned about storing the refresh token on the webserver, is this correct? Have you considered using the JWT callback to store the encrypted access and refresh tokens using the encrypted cookie next-auth provides instead? The web server will server will be unable to make any requests to the server if you browser is storing the JWE.

**Comment by balazsorban44** [comment]
Hi, I am closing this issue, per https://github.com/nextauthjs/next-auth/commit/862a505782588a0760721eafb6a3bb905f3e383f. It shows how you can trigger a re-authentication in case of an expired access_token.

In the future, we would like to make this a seamless experience, and figure out how to do this in the background, without disrupting the user flow. For now, the above is our best recommendation.
