### ISSUE TITLE
Augmenting session type doesn't seem to work on Auth.js anymore

### ISSUE THREAD

**Issue by evangelos-ch** [nextauthjs/next-auth#6640]
### Question 💬

I want to pass the user ID to the `session.user` object. I can do this by using the session callback in the auth config:

```ts
callbacks: {
	async session({ session, user }) {
		if (session.user) {
			session.user.id = user.id;
		}
		return Promise.resolve(session);
	}
}
```

However, this throws a TypeScript error as `session.user` doesn't have an ID field. To fix this, I followed the instructions [here](https://next-auth.js.org/getting-started/typescript) and created the following `auth.d.ts` file:

```ts
import type { DefaultSession } from '@auth/core/types';

declare module '@auth/core/types' {
	interface Session {
		user: {
			id: string;
		} & DefaultSession['user'];
	}
}
```

This worked just fine until I updated `@auth/core` to 0.4.0 and `@auth/sveltekit` to 0.2.1. Now no matter what I try (such as augmenting the CallbackOptions interface amongst other things), I cannot get TypeScript to know about the id field in `session.user`.

While normally I'd just `@ts-expect-error` and go about my day, this issue is quite major for me as I am accessing `session.user.id` in most of my backend routes to make appropriate DB calls and the like.

### How to reproduce ☕️

I'm reusing the [minimal reproduction repo](https://github.com/evangelos-ch/sveltekit-auth-example) I posted in my previous issue on edge functions and SvelteKit. I added a new commit to it that reproduces the issues I just talked about. Simply cloning, npm installing and opening in vscode reproduces the typescript errors for me in hooks.server.ts.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by OllieJT** [comment]
I'm experiencing this in a SvelteKit app, but not a NextJS app.

Augmenting "next-auth" seems fine, but not "@auth/core"

**Comment by evangelos-ch** [comment]
That is why I put "Auth.js" in the title as I suspect this might not be a "NextAuth.js" issue. Also the augment worked just fine on `@auth/core` 0.3.0 and `@auth/sveltekit` 0.2.0, so it must've been a recent change that broke it.

**Comment by ThangHuuVu** [comment]
It seems that since `0.4.0`, there is a nested dependency in `node_modules`:
<img width="299" alt="Screen Shot 2023-02-11 at 22 20 29" src="https://user-images.githubusercontent.com/31528554/218266484-15dd0e7c-697d-4663-8aed-91a26fd13560.png">
While on `0.3.0` it doesn't have this issue

Here is a possible workaround for you while waiting for us to patch this:
```
declare module '@auth/sveltekit/node_modules/@auth/core/types' {
	interface Session {
		user: {
			id: string;
		} & DefaultSession['user'];
	}
	interface User {
		foo: 'bar'
	}
}
```

**Comment by evangelos-ch** [comment]
Thanks for taking a look. Can confirm this workaround does work (all that's needed is changing `@auth/core/types` to `@auth/sveltekit/node_modules/@auth/core/types` actually, the second interface augmentation doesn't seem to be necessary since I'm not adding custom fields, just including the id in the session).

**Comment by JonathonRP** [comment]
> It seems that since `0.4.0`, there is a nested dependency in `node_modules`: <img alt="Screen Shot 2023-02-11 at 22 20 29" width="299" src="https://user-images.githubusercontent.com/31528554/218266484-15dd0e7c-697d-4663-8aed-91a26fd13560.png"> While on `0.3.0` it doesn't have this issue
> 
> Here is a possible workaround for you while waiting for us to patch this:
> 
> ```
> declare module '@auth/sveltekit/node_modules/@auth/core/types' {
> 	interface Session {
> 		user: {
> 			id: string;
> 		} & DefaultSession['user'];
> 	}
> 	interface User {
> 		foo: 'bar'
> 	}
> }
> ```

does this work with pnpm? I don't see a `@auth/sveltekit/node_modules/@auth` mine only has `@auth/sveltekit/node_modules/.bin` and I am not sure what to do with that.

**Comment by JonathonRP** [comment]
also seems like sveltekit has a dependency on 0.3.0 instead of .0.4.0 which could be source of problem

**Comment by fawaz-alesayi** [comment]
> > It seems that since `0.4.0`, there is a nested dependency in `node_modules`: <img alt="Screen Shot 2023-02-11 at 22 20 29" width="299" src="https://user-images.githubusercontent.com/31528554/218266484-15dd0e7c-697d-4663-8aed-91a26fd13560.png"> While on `0.3.0` it doesn't have this issue
> > Here is a possible workaround for you while waiting for us to patch this:
> > ```
> > declare module '@auth/sveltekit/node_modules/@auth/core/types' {
> > 	interface Session {
> > 		user: {
> > 			id: string;
> > 		} & DefaultSession['user'];
> > 	}
> > 	interface User {
> > 		foo: 'bar'
> > 	}
> > }
> > ```
> 
> does this work with pnpm? I don't see a `@auth/sveltekit/node_modules/@auth` mine only has `@auth/sveltekit/node_modules/.bin` and I am not sure what to do with that.

For PNPM users with `@authjs/sveltekit: 0.21` add this to your declaration `.d.ts` file:

```
import { DefaultSession } from "@auth/core";

declare module "<relative-path-to-node_modules>/.pnpm/@auth+core@0.3.0/node_modules/@auth/core/types" {
  /**
   * Returned by `useSession`, `getSession` and received as a prop on the `SessionProvider` React Context
   */
  interface Session {
    // All of the Pages have SSR auth, so we can assume that the user is logged in (no need for optional type)
    user: {
      id: string;
    } & DefaultSession["user"];
  }
}
```

for my case, my folder structure was like this:
```
|
| node_modules
| src
| ── src/types
| ──── src/types/auth.d.ts
```

so I put this in auth.d.ts
```
import { DefaultSession } from "@auth/core";

declare module "../../node_modules/.pnpm/@auth+core@0.3.0/node_modules/@auth/core/types" {
  /**
   * Returned by `useSession`, `getSession` and received as a prop on the `SessionProvider` React Context
   */
  interface Session {
    // All of the Pages have SSR auth, so we can assume that the user is logged in (no need for optional type)
    user: {
      id: string;
    } & DefaultSession["user"];
  }
}
```

**Comment by JonathonRP** [comment]
Also for pnpm not package name could be different, in my case I have latest nodemailer and so my package instead of @auth+core@0.3.0 is @auth+core@0.3.0_nodemailer@6.9.1 best way to figure out package is looking in lock file for the package related to @auth/core as a dependency of @auth/sveltekit.

**Comment by w3cj** [comment]
Version `0.5.1` fixes this. You should now be able to override the module directly:

```ts
declare module '@auth/core/types' {
    // your codes here
}
```

**Comment by brendanmatkin** [comment]
See also discussion https://github.com/nextauthjs/next-auth/discussions/6914

**Comment by evangelos-ch** [comment]
> Version `0.5.1` fixes this. You should now be able to override the module directly:
> 
> ```ts
> declare module '@auth/core/types' {
>     // your codes here
> }
> ```

Yup works fine for me after updating to @auth/core 0.5.1 and @auth/sveltekit 0.3.0. Thanks!

**Comment by arlyon** [comment]
This is still broken with next-auth

**Comment by OllieJT** [comment]
Not sure if this is a regression, or if I'm missing something - but I'm having this issue again. Can anyone else confirm?

```json
{
	"@auth/core": "^0.8.1",
	"@auth/sveltekit": "^0.3.1",
	"@next-auth/prisma-adapter": "^1.0.7"
}
```

**Comment by Sharknoon** [comment]
Can confirm, I have the same issue

**Comment by OllieJT** [comment]
@lluia @balazsorban44 apologies for the ping. I'm not sure how notifications work for closed PR's.

Do you mind reopening this issue?

**Comment by SasaHrgovic** [comment]
I also have the same issue, but as a workaround, instead of trying to augment the session type from the library, I implemented all my types in app.d.ts until the issue is fixed again.

```ts
declare namespace App {
  interface User {
    id: string;
    name: string;
    email: string;
    image: string;
    roleId: string;
    organizationId: string;
  }
  interface Session {
    user?: User;
    expires: string;
    accessToken?: string;
  }
  interface Locals {
    getSession(): Promise<Session | null>
  }
  interface PageData {
    session: Session | null;
  }
}
```

Not sure if I could do any better workaround, but this one works, so I don't have errors and I don't need to cast session as any to access the additional properties. I've initially posted this in #7496

**Comment by Sdocquir** [comment]
Experiencing this same issue here as well.

**Comment by Sharknoon** [comment]
With the latest update from a couple of hours ago, it seems to be fixed for me.

This is my solution now:
```ts
import { DefaultSession } from '@auth/core/types';

declare module '@auth/core/types' {
	interface Session {
		user: {
			id: string;
			role: string;
		} & DefaultSession['user'];
	}
}

```

**Comment by ArcadeArchie** [comment]
it seems to be broken again on `@auth/core@0.9.0`  and  `@auth/sveltekit@0.3.3`
for now i've used the workaround mentioned by @fawaz-alesayi as that still works
my `src/types/auth.d.ts` look like this
```ts
import type { DefaultSession } from "@auth/core/types";
import type { JWT } from "@auth/core/jwt";

declare module "../../node_modules/.pnpm/@auth+core@0.9.0/node_modules/@auth/core/types" {
  interface Session {
    user?: {
      id: string;
    } & DefaultSession['user'];
    accessToken: string | undefined;
  }
}
declare module "../../node_modules/.pnpm/@auth+core@0.9.0/node_modules/@auth/core/jwt" {
  interface JWT {
    id: string;
    accessToken: string | undefined;
  }
}
```

**Comment by ArcadeArchie** [comment]
seemed to be an issue caused by a version mismatch between the @auth/core of @auth/sveltekit and @auth/core of my project,
I've fixed by using pnpm's override feature to force a single version of @auth/core

**Comment by sillvva** [comment]
As @ArcadeArchie said, it seems to be a version mismatch with pnpm. This fixed it for me as well.

In `package.json`

```json
{
	"dependencies": {
		"@auth/core": "^0.9.0",
		"@auth/sveltekit": "^0.3.5"
	},
	"pnpm": {
		"overrides": {
			"@auth/core": "^0.9.0"
		}
	}
}
```

**Comment by brendanmatkin** [comment]
Seems to work ok without the override now using:
```json
{
  "dependencies": {
    "@auth/core": "^0.10.0",
    "@auth/sveltekit": "^0.3.6"
  },
}
```
Although I had to remove @auth/core then re-add it to get it to update with pnpm. 

Just in case anyone had the same issue as me in the future: I also had to update my `src/lib/types/auth.d.ts` to match yours 
from:
```ts
export declare module "@auth/core/types" {
	interface Session {
		user: {
			nickname?: string;
			projects?: string[];
			permissions?: string[];
		} & DefaultSession["user"];
	}
}
```
to:
```ts
import type { DefaultSession } from "@auth/core/types";

declare module "@auth/core/types" {
	interface Session {
		user?: {
			nickname?: string;
			projects?: string[];
			permissions?: string[];
		} & DefaultSession["user"];
	}
}
```

**Comment by konstantinblaesi** [comment]
Add this to your .d.ts file
```
// needed otherwise ts module augmentation breaks, see https://www.youtube.com/watch?v=USi8khln7YI
export {}
```
