### ISSUE TITLE
`openid-client` warnings on Node 18

### ISSUE THREAD

**Issue by nbouvrette** [nextauthjs/next-auth#6650]
### Environment

It looks like https://github.com/nextauthjs/next-auth/pull/6137 was closed but Next 16 will be end of support in 7 months. Vercel also moved to Node 18 as the default version.

Can `next-auth` update [openid-client](https://github.com/panva/node-openid-client) so that we can stop having the warnings when installing `next-auth`?

### Reproduction URL

N/A

### Describe the issue

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/6453322/217616763-43575c44-f405-43d6-9a00-d03d88f75689.png">

### How to reproduce

Just run `npm install` when using Node 18 and using `next-auth`

### Expected behavior

There should be no warning.

**Comment by balazsorban44** [comment]
Thought we addressed this already via https://github.com/nextauthjs/next-auth/commit/f54424c216b2099f291baabdebff023374433511

https://github.com/nextauthjs/next-auth/blob/f2e85c21133218a3369168c3735d0a7d5e6221bc/packages/next-auth/package.json#L75 should just be bumped.

**Comment by nbouvrette** [comment]
@balazsorban44 hmm https://github.com/nextauthjs/next-auth/commit/f54424c216b2099f291baabdebff023374433511 seems completely different, this is the change for `next-auth`'s engine - the error in this issue is caused by `openid-client`'s engine which they removed back last September in https://github.com/panva/node-openid-client/commit/9aefba30dcf0e312051e6844b35b06bc457488d5.

Next-auth should use `"openid-client": "^5.1.10", ` (not `5.1.0`) or greater.

**Comment by balazsorban44** [comment]
I get it. :slightly_smiling_face:  I just wasn't aware we were behind on `openid-client` that still had `engines`.

**Comment by nbouvrette** [comment]
Awesome, thanks for the quick turnaround!
