### ISSUE TITLE
How to integrate googles built in authentication button

### ISSUE THREAD

**Issue by brosand** [nextauthjs/next-auth#6651]
### Description 📓

Is there a good way to integrate buttons like these: https://developers.google.com/identity/gsi/web/guides/personalized-button -- they look much better and have some good interactivity

### How to reproduce ☕️

https://developers.google.com/identity/gsi/web/guides/personalized-button

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
This is outside the scope of the library. You can use regular CSS to recreate the style described in the page you linked.
