### ISSUE TITLE
refreshInterval in <SessionProvider /> not working?

### ISSUE THREAD

**Issue by Aman-Godara-RIA** [nextauthjs/next-auth#6658]
### Question 💬

I want to refresh accessToken once every 300 seconds, I came across `refreshInterval` in docs [here](https://next-auth.js.org/getting-started/client#options).

For testing purposes, I set the `refreshInterval` to 2 secs and then opened up my `networks` tabs in chrome expecting a `getSession` call once every 2 seconds, but to my surprise that wasn't the case. I also verified `session` to be NOT null (I know this to be true also because I have logged in)

````js
<SessionProvider session={session} refetchInterval={2} refetchOnWindowFocus={false}>
          <ContextProvider>
                    <Component {...pageProps} />
          </ContextProvider>
</SessionProvider>
````

I was going through the codebase and was wondering if this expression will ever evaluate to true 🤔 https://github.com/nextauthjs/next-auth/blob/d72296220623ba9ff17eaff4792a5bd880c9cd9a/packages/next-auth/src/react/index.tsx#L379

If `_lastSync` is set to `0` or `now()` only,  it will never be greater than `now()` because `now()` keeps on increasing.

Do I need to take some rest or is this a genuine mistake?

### How to reproduce ☕️

pass `refreshInterval` as 2 as shown above and open up your `networks` tab of chrome to find that no `getSession` call is made once every 2 seconds.

### Contributing 🙌🏽

Yes, I would be celebrating for days if I get the opportunity to resolve this (if this really is any issue)

**Comment by Aman-Godara-RIA** [comment]
sorry my bad, there's a check which says that if `accesstoken` hasn't expired then `getSession` should not be triggered and the `accesstoken` I am using has 5 minutes of expiration time.

https://github.com/nextauthjs/next-auth/blob/d72296220623ba9ff17eaff4792a5bd880c9cd9a/packages/next-auth/src/react/index.tsx#L379

**Comment by Aman-Godara-RIA** [comment]
I am not facing the issue anymore, for some reason when I set the `refetchInterval` to `process.env.NEXTAUTH_REFRESH_ACCESS_TOKEN_IN_SECONDS` it wasn't picking up the integer `2`, but when I passed it directly to `<SesssionProvider />` it started to work.

But my question remains, will now() < _lastSync ever be `true` unless we set some future value into `_lastSync`

**Comment by balazsorban44** [comment]
`NEXTAUTH_REFRESH_ACCESS_TOKEN_IN_SECONDS` is not prefixed with `NEXT_PUBLIC_` hence will be undefined. See https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser

**Comment by Aman-Godara-RIA** [comment]
@balazsorban44 yeah realised that but can you answer the question?

**Comment by balazsorban44** [comment]
I'm on mobile, so not from the top of my head but we have tested the current behavior, so if you experience something is incorrect, please open a new issue with a reproduction. 🙏

**Comment by Aman-Godara-RIA** [comment]
I gave raising a bug a thought but it's not actually a bug or a way to reproduce anything, it's just a question I thought about. Can you guide me on where to raise a question?
