### ISSUE TITLE
Typo in diagram on https://next-auth.js.org/configuration/providers/oauth#using-a-custom-provider

### ISSUE THREAD

**Issue by anguskeatinge** [nextauthjs/next-auth#6663]
### What is the improvement or update you wish to see?

The typo in this diagram just caused me to pour 2 hours of my life down the drain because I copied and pasted this path into my GitHub OAuth setup

- `api/auth/github/callback` - **_WRONG_**
- `api/auth/callback/github` - **_RIGHT_**

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/5662066/217857812-874c36ca-3e74-40dd-a23c-ad6e77af1ca0.png">

### Is there any context that might help us understand?

No extra context required, see above

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/configuration/providers/oauth#using-a-custom-provider

**Comment by balazsorban44** [comment]
Thanks, fixed. To be fair, it is correct right below: https://github.com/nextauthjs/next-auth/blob/v4/docs/docs/configuration/providers/oauth.md#how-to
