### ISSUE TITLE
getServerSession returns null on initial request in API route even though a user is logged in

### ISSUE THREAD

**Issue by shadeemerhi** [nextauthjs/next-auth#6664]
### Question 💬

Hi there,

I am working on a project using Next 13's `app` directory and I have a question about how `getServerSession` works, specifically in API routes.

When the user visits the home page of my app, a request is made to an API endpoint that generates the home feed content for the logged-in user. I am using a Server Component to SSR the data, and inside of this component I make a request to my API endpoint:

```
const data = await fetchPosts(
    `${process.env.BASE_URL}/api/posts/timeline`
  );
```

At the API route, I am using the `session` from `getServerSession` so I can generate the feed for this specific user:

```
const session = await getServerSession(req, res, authOptions);

if (session) {
   // build logged-in user home feed
}
else {
 // build generic, non-logged-in user home feed
}
```

The issue I am having is on the first request (when the user visits the page for the first time or refreshes the page) the `session` is `null`, even though the user is signed in. This causes the incorrect feed to be generated as the server does not think they're signed in on this first request. On subsequent requests, it works fine, but since I am using SSR, I would ideally want access to the session on the first request.

Perhaps this is the desired functionality of `getServerSession` or there is a gap in my understanding, so any help or feedback would be greatly appreciated!

Versions:
"next-auth": "^4.19.2"
"next": "13.1.6"

Thank you.

### How to reproduce ☕️

Server Component:

```
import { getServerSession } from "next-auth";
import { authOptions } from "../../../pages/api/auth/[...nextauth]";
import { fetchPosts } from "../../../util/queries/posts";
import TimelineContentWrapper from "./TimelineContent";

const TimelineFetch = async () => {
  const session = await getServerSession(authOptions);
  console.log("timeline fetch session", session);
  const data = await fetchPosts(
    `${process.env.BASE_URL}/api/posts/timeline`
  );

  return <TimelineContentWrapper session={session} data={data} />;
};

export default TimelineFetch;

```

API route `/api/posts/timeline`:

```
import type { NextApiRequest, NextApiResponse } from "next";
import { getServerSession } from "next-auth/next";
import {
  buildGeneralTimeline,
  buildUserTimeline,
} from "../../../util/dbHelpers/posts";
import { FeedContentItems } from "../../../util/types";
import { authOptions } from "../auth/[...nextauth]";

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const session = await getServerSession(req, res, authOptions);

  if (req.method === "GET") {
    try {
      let items: FeedContentItems = [];

      if (session?.user) {
        items = await buildUserTimeline(session?.user.id);
      } else {
        items = await buildGeneralTimeline();
      }

      res.status(200).json({ items });
    } catch (error: any) {
      res.status(500).end();
    }
  }
}

```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Hard to tell what `fetchPosts` is doing for example, maybe you are not forwarding the cookies to the request, hence we cannot retrieve the session, or something similar. Please add a full reproduction.

**Comment by ahmedsbai1995** [comment]
did you find what is causing the problem?

**Comment by ahmedsbai1995** [comment]
did you find what is causing the problem? I have the same here

**Comment by davecarlson** [comment]
I've seen this too. I've looked at the cookie and on first request after login, the cookie is 'shorter' than 2nd request.
I can reproduce it more if there was a previous session that was logged out first.

I imagine its a race condition where the frontend page is requesting stuff too early, before the cookie is set post login. Going to debug the login flow a little more - i'm assuming this is a side effect of how we are using it, rather  than the library itself.

**Comment by symbiot-india** [comment]
@shadeemerhi @davecarlson have you been able to find a workaround? I'm facing the same issue.

**Comment by notHuman9504** [comment]
facing the same issue ? @symbiot-india @shadeemerhi @davecarlson @ahmedsbai1995 .have anyone found solution?
