### ISSUE TITLE
Problem with site URL resulting in "HTTP POST is not supported"

### ISSUE THREAD

**Issue by simonwidjaja** [nextauthjs/next-auth#667]
**Your question**
I am trying to deploy the raw sample application with nextjs. Locally everything is working fine, but as soon as I deploy to vercel I get the following error, when trying to sign up with email.

`Error: HTTP POST is not supported for /api/auth/tmp-nextjs-with-next-auth-app-duw5xxh03.vercel.app/api/auth/signin/email?nextauth=tmp-nextjs-with-next-auth-app-duw5xxh03.vercel.app%2Fapi%2Fauth%2Fsignin%2Femail`

The URL is:
https://tmp-nextjs-with-next-auth-app-duw5xxh03.vercel.app/api/auth/tmp-nextjs-with-next-auth-app-duw5xxh03.vercel.app/api/auth/signin/email

That URL doesn't look right. It's the same path twice...
I have just added the VERCEL_URL environment variable for the deployment.

Is this a bug or am I missing something?

**Comment by simonwidjaja** [comment]
Seems like next-auth is handling the VERCEL_URL (generated by vercel on the fly) wrong.

The vercel documentation hints that the value is relative (without "https://"):
(https://vercel.com/docs/build-step#system-environment-variables)

**VERCEL_URL**
The URL of the deployment. Example: my-site-7q03y4pi5.vercel.app.


So I circumvented the VERCEL_URL by hardcoding the deployment URL in the options as follows. Now it's working.
Am I missing something in my setup or is this a bug? If so it would be great to see support the current vercel deployment workflows or an updated example / documentation... 

`import NextAuth from 'next-auth'
import Providers from 'next-auth/providers'

const options = {
  **// site: process.env.VERCEL_URL,
  site: 'https://tmp-nextjs-with-next-auth-app.vercel.app/',**
  providers: [
    Providers.Email({
      // SMTP connection string or nodemailer configuration object https://nodemailer.com/
      server: process.env.EMAIL_SERVER,
      // Email services often only allow sending email from a valid/verified address
      from: process.env.EMAIL_FROM,
    }),
//...
}

const Auth = (req, res) => NextAuth(req, res, options)

export default Auth`

**Comment by simonwidjaja** [comment]
Update
Just saw the env var "NEXTAUTH_URL" in the docs. Will try that next. May be that solves the problem. I used the nextjs official example "with-next-auth". There was just NEXT_URL mentioned not NEXTAUTH_URL.

**Comment by LoriKarikari** [comment]
@simonwidjaja is it working now?

**Comment by simonwidjaja** [comment]
Yes it's working now.

**Comment by Abderrahmenla** [comment]
how did it work?I'm facing the same issue,locally everything works fine,but when I deployed to vercel,github authentication or facebook or google doesn't work,I've changed the redirected uri in these apps to https://minority-programmers-mern-form-test.vercel.app/api/auth/callback and still doesn't work

**Comment by balazsorban44** [comment]
@Abderrahmenla the callback url's must end with the id of the provider.
So:
- https://minority-programmers-mern-form-test.vercel.app/api/auth/callback/facebook
- https://minority-programmers-mern-form-test.vercel.app/api/auth/callback/google
Respectively.

See: https://next-auth.js.org/getting-started/rest-api#post-apiauthsigninprovider

**Comment by harsh-vish14** [comment]
@balazsorban44 This worked thankyou for this
