### ISSUE TITLE
Issue with token rotation in Azure AD, multiple calls to refresh token function

### ISSUE THREAD

**Issue by liamlows** [nextauthjs/next-auth#6675]
### Question 💬

Hello!

So we recently switched from using the azure MSAL react package to next-auth as it seemed to make more sense given we use next and also it allows us to query for the azure id token JWT on the next API (MSAL did not provide this feature). One thing to note that is different with our approach from other approaches is that we utilize the **ID TOKEN** and not the access token. Regardless, the issue should still be present when either using the access token or the id token.

We are using callbacks to attach the Azure AD `id_token` to the session for use in API requests.

The issue we have observed is that when a token expires (1 hour for AD ID tokens) and we use the refresh token to fetch a new one, we see the refresh token get called multiple times (in our case 3 times). This results in 3 new tokens being acquired from AD with unique values for `access_token`, `refresh_token`, and `id_token`. Its a guessing game as to which of the three actually gets saved off and used later in the requests.

We really have no idea why it's called multiple times, we tried looking at what could be causing it but are a bit confused as of now. Anyway, our code implementation for the next-auth api endpoint is below in addition to some logs...

Refresh Token Rotation Docs: https://next-auth.js.org/tutorials/refresh-token-rotation 

### How to reproduce ☕️

`/api/auth/[...nextauth].ts`:
```import NextAuth, { Account, AuthOptions, Session } from 'next-auth';
import { JWT } from 'next-auth/jwt';
import AzureADProvider from 'next-auth/providers/azure-ad';

async function refreshAccessToken(token: JWT) {
  try {
    const url = `https://login.microsoftonline.com/${global.process.env.AZURE_AD_TENANT_ID}/oauth2/v2.0/token`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body:
        `grant_type=refresh_token` +
        `&client_secret=${global.process.env.AZURE_AD_CLIENT_SECRET}` +
        `&refresh_token=${token.refreshToken as string}` +
        `&client_id=${global.process.env.AZURE_AD_CLIENT_ID}`,
    });

    const refreshedTokens = (await response.json()) as {
      token_type: string;
      scope: string;
      expires_in: number;
      ext_expires_in: number;
      access_token: string;
      refresh_token: string;
      id_token: string;
    };

    console.log('############# REFRESH REFRESH HOT HOT HOT ###########', refreshedTokens);

    if (!response.ok) throw refreshedTokens;

    return {
      ...token,
      idToken: refreshedTokens.id_token,
      idTokenExpires: Date.now() + 3595000, // use 1 hour in milliseconds since no id token values are provided by endpoint
      refreshToken: refreshedTokens.refresh_token ?? token.refreshToken, // Fall back to old refresh token
    };
  } catch (error) {
    console.log(error);
    return {
      ...token,
      error: 'RefreshAccessTokenError',
    };
  }
}

export const authOptions: AuthOptions = {
  debug: true,
  providers: [
    AzureADProvider({
      clientId: global.process.env.AZURE_AD_CLIENT_ID,
      clientSecret: global.process.env.AZURE_AD_CLIENT_SECRET,
      tenantId: global.process.env.AZURE_AD_TENANT_ID,
      authorization: {
        params: {
          scope: 'offline_access openid profile email',
        },
      },
    }),
  ],
  pages: {
    signIn: '/',
  },
  callbacks: {
    async jwt({ token, account }: { token: JWT; account?: Account | null }): Promise<JWT> {
      // Persist the Azure id_token to the token right after signin
      console.log('ACCT: ', account);
      console.log('TOKEN: ', token);
      if (account) {
        token.idToken = account.id_token;
        token.idTokenExpires = Date.now() + 3595000;
        token.refreshToken = account.refresh_token;
        return token;
      }
      // THIS IS WHERE WE CHECK THE EXPIRY OF THE TOKEN 
      if (token.idTokenExpires && Date.now() < token.idTokenExpires) {
        return token;
      }
      console.log('########### WE ARE ABOUT TO REFRESH ########## ', token.idTokenExpires);
      return await refreshAccessToken(token);
    },
    session({ session, token }: { session: Session; token: JWT }): Session {
      // Send properties to the client, like an access_token from a provider.
      session.idToken = token.idToken;
      return session;
    },
  },
  secret: global.process.env.NEXTAUTH_SECRET,
};

export default NextAuth(authOptions);
```
Sample of console output (including debug flag turned on):
```
ACCT:  undefined
TOKEN:  {
  idToken: ...,
  refreshToken: ...,
  ...
}
########### WE ARE ABOUT TO REFRESH ##########  1675980032450
ACCT:  undefined
TOKEN:  {
  idToken: ...,
  refreshToken: ...,
  ...
}
########### WE ARE ABOUT TO REFRESH ##########  1675980032450
ACCT:  undefined
TOKEN:  {
  idToken: ...,
  refreshToken: ...,
  ...
}
########### WE ARE ABOUT TO REFRESH ##########  1675980032450
############# REFRESH REFRESH HOT HOT HOT ########### {
  token_type: 'Bearer',
  scope: 'profile openid email User.Read',
  expires_in: 5077,
  ext_expires_in: 5077,
  access_token: ...,
  refresh_token: ...,
  id_token: ...
}
############# REFRESH REFRESH HOT HOT HOT ########### {
  token_type: 'Bearer',
  scope: 'profile openid email User.Read',
  expires_in: 4454,
  ext_expires_in: 4454,
  access_token: ...,
  refresh_token: ...,
  id_token: ...
}
[next-auth][debug][CHUNKING_SESSION_COOKIE] {
  message: 'Session cookie exceeds allowed 4096 bytes.',
  emptyCookieSize: 163,
  valueSize: 5360,
  chunks: [ 4096, 1590 ]
}
[next-auth][debug][CHUNKING_SESSION_COOKIE] {
  message: 'Session cookie exceeds allowed 4096 bytes.',
  emptyCookieSize: 163,
  valueSize: 5360,
  chunks: [ 4096, 1590 ]
}
############# REFRESH REFRESH HOT HOT HOT ########### {
  token_type: 'Bearer',
  scope: 'profile openid email User.Read',
  expires_in: 5376,
  ext_expires_in: 5376,
  access_token: ...,
  refresh_token: ...,
  id_token: ...
}
[next-auth][debug][CHUNKING_SESSION_COOKIE] {
  message: 'Session cookie exceeds allowed 4096 bytes.',
  emptyCookieSize: 163,
  valueSize: 5360,
  chunks: [ 4096, 1590 ]
}
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
There's likely multiple calls from the client to the backend happening at the same time via getSession or using `getServerSession`. Make sure it's not the case.



Tip: You likely didn't want to expose the `id_token` via the session callback! Send the (already parsed) user data that you actually need instead. refresh and id tokens are best to keep server-side

**Comment by liamlows** [comment]
@balazsorban44 I am making 3 API requests on the page in question and each use `getServerSession` so you are correct there. However, I wouldn't assume this issue closed yet...

That being said, our Next.JS API queries our C# API which requires the idToken to be present in the headers of the request for authentication purposes. Every API call from the server to the C# API makes use of `getServerSession` which is where we extract the idToken and attach it in. This is all done server side, the only time we access the session on the client side is to determine if a user is authenticated on one page that is not protected by the next-auth middleware.

Is this not the correct approach given our use case? How are we meant to query our C# API with the idToken if the session callback cannot contain this information? Furthermore, if our API uses the `getServerSession` function in every request how would we limit the calling of this function to prevent multiple refresh tokens from being obtained?

**Comment by liamlows** [comment]
ok @balazsorban44 I may have proven my ignorance, is utilizing the `getToken()` function in the next API the better way to handle this? I see that it returns everything stored in the token object and this way i could avoid storing the idToken in the session object and avoid hitting the session entirely. 

My mistake was I initially assumed that the `getToken` function would return the next-auth session token only thinking it wasn't doing anything different from `getServerSession`, combined with the way that the docs recommended using `getServerSession` made me think i did it right.

I assume that when needed, the `getToken` function will utilize the refresh token to obtain a new one when expiry is hit correct?

**Comment by dmitryfd** [comment]
I am facing the same issue, @fitzvinicius.
Are you using Next.js 13 with app directory enabled by any chance?

My sneaking suspicion is that this has to do with readonly cookies:

![image](https://user-images.githubusercontent.com/2302043/225765152-31aa4988-0a40-4fc8-b712-7aa4914df6b3.png)

**Comment by dmitryfd** [comment]
^-- Seems to be the case in my experimentation indeed.

I've got a _very_ dirty workaround working by fetching `/api/auth/session` in the Next.js middleware whenever access token is expired and forwarding resulting `Set-Cookie` header to the response, but that's just sad...

@balazsorban44, any thoughts on better ways to make this use case work with /app dir? Thanks in advance!

**Comment by liamlows** [comment]
@fitzvinicius 

Hey so I'll clarify the solution I found to the problem when using Azure AD as our login auth. Not sure if this is technically correct so I'm open to any recommendations. NOTE: In our implementation we use the id_token to authenticate rather than the access token thus the azure id_token gets refreshed every hour.

Before we process any data on any call to our Next.JS API we call the `getToken` function to obtain the valid id_token from the session. `getToken` will then run through the JWT function in the `nextauth` API endpoint. In our JWT function we check if it was the first sign in using the `account` parameter (to add the id token, refresh token, and expiry), we check if the id token has expired, and if it has expired to call the refresh token function. Below is our code implementation of this...

With this setup I have noticed that the refresh token function is only called when the expiry is hit and only once.

```
import NextAuth, { Account, AuthOptions } from 'next-auth';
import { JWT } from 'next-auth/jwt';
import AzureADProvider from 'next-auth/providers/azure-ad';

async function refreshAccessToken(token: JWT) {
  try {
    const url = `https://login.microsoftonline.com/${ ... }/oauth2/v2.0/token`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body:
        `grant_type=refresh_token` +
        `&client_secret=${ ... }` +
        `&refresh_token=${token.refreshToken as string}` +
        `&client_id=${ ... }`,
    });

    const refreshedTokens = (await response.json()) as {
      token_type: string;
      scope: string;
      expires_in: number;
      ext_expires_in: number;
      access_token: string;
      refresh_token: string;
      id_token: string;
    };

    if (!response.ok) throw refreshedTokens;

    return {
      ...token,
      idToken: refreshedTokens.id_token,
      idTokenExpires: Date.now() + 3595000, // use 1 hour in milliseconds since no id token values are provided by endpoint
      refreshToken: refreshedTokens.refresh_token ?? token.refreshToken, // Fall back to old refresh token
    };
  } catch (error) {
    console.log(error);
    return {
      ...token,
      error: 'RefreshAccessTokenError',
    };
  }
}

export const authOptions: AuthOptions = {
  // debug: true,
  providers: [
    AzureADProvider({
      clientId: ...,
      clientSecret: ...,
      tenantId: ...,
      authorization: {
        params: {
          scope: 'offline_access openid profile email',
        },
      },
    }),
  ],
  pages: {
    signIn: '/login',
  },
  callbacks: {
    async jwt({ token, account }: { token: JWT; account?: Account | null }): Promise<JWT> {
      // Persist the Azure id_token to the token right after signin
      if (account) {
        token.idToken = account.id_token;
        token.idTokenExpires = Date.now() + 3595000;
        token.refreshToken = account.refresh_token;
        return token;
      }

      if (token.idTokenExpires && Date.now() < token.idTokenExpires) {
        return token;
      }

      return await refreshAccessToken(token);
    },
  },
  secret: ...,
};

export default NextAuth(authOptions);
```
