### ISSUE TITLE
Session refetches and causes rerenders on current tab when a new one is opened

### ISSUE THREAD

**Issue by colis** [nextauthjs/next-auth#6682]
### Environment

System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 102.98 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 110.0.5481.77
    Firefox: 106.0.1
    Safari: 16.3
  npmPackages:
    next: 13.0.6
    next-auth: 4.19.2
    react: 18.2.0

### Reproduction URL

-

### Describe the issue

When opening a link in a new tab, the session gets refetched on the active page and causes its components to rerender, as you can see from the screen recording.

The `refetchOnWindowFocus` option is set to `false`.

Is this the expected behaviour?

Thanks.

https://user-images.githubusercontent.com/9059716/218096058-1a4baa1b-3235-472e-9c7a-5679a8eb2552.mp4

### How to reproduce

-

### Expected behavior

The session should not be refetched on the current page.

**Comment by balazsorban44** [comment]
Tab syncing is not controlled by `refetchOnWindowFocus`.

https://github.com/nextauthjs/next-auth/blob/9e423f32528e0bee9c178a61c039d97f27261d3e/packages/next-auth/src/react/index.tsx#L406-L417

Hard to say more since there is no reproduction/code.
