### ISSUE TITLE
In production on Vercel, calling getCsfrToken() in authorize() gets a different token to the cookie

### ISSUE THREAD

**Issue by JonCognioDigital** [nextauthjs/next-auth#6686]
### Environment

System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz   
    Memory: 8.31 GB / 31.94 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 108.0.5359.125
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566

### Reproduction URL

Not possible as this is a private project

### Describe the issue

I am writing my own credentials provider and as part of that I have to override the authorize() method.

Inside here I am using getCsfrToken() so that I can check that an action performed during the login process was done using the CSFR token exposed on the client.

On localhost this works every time, the client and CSFR token are the same. 

However, when deployed to Vercel the client side token stays the same, I can see it in dev tools as a cookie and I can see that it is passed correctly each time to the /credentials endpoint in both the payload and the request cookies. The server side version is a new token every time the authorize method is called though.

Unfortunately the whole setup is a bit too complicated for me to easily provide a whole reproduction and also, it's specific to the hosting environment, but hopefully there's a simple explanation.

I don't think it is anything to do with the environment variables because the cookie seems to be working perfectly. I have provided a NEXTAUTH_SECRET though.

### How to reproduce

Just call getCsfrToken() inside of the authorize() method and check to see if it is the same. Locally they should be, on Vercel they will not be.

### Expected behavior

The CSFR Token should be the same on back end and front end.

**Comment by zlwaterfield** [comment]
This might be related to https://github.com/nextauthjs/next-auth/issues/6685. Seems multiple people are having issues on Vercel tonight.

**Comment by ThangHuuVu** [comment]
I believe this issue is fixed now, please redeploy your project to get the fix. Related: https://github.com/nextauthjs/next-auth/issues/6685#issuecomment-1426614378

**Comment by JonCognioDigital** [comment]
@ThangHuuVu - Unfortunately for me it hasn't fixed the issue but it has changed!

Now, the CSRF token is always the same on the server, even if I deploy several times and try different preview URLs or the main production one it is always the same, which wasn't happening yesterday.

However, each different deployment (and session if I delete all cookies) has a different token in the client. 

On localhost the client and server are always in sync and if I delete my cookies on localhost the same CSRF token is generated when next-auth gives me a new cookie. I'm not sure under which conditions the token is supposed to change but on localhost neither seem to re-generate. I'm sure this is the expected behavior because my login works perfectly on localhost. It's only on Vercel that the client ones keeps changing.

**Comment by sync-adm** [comment]
Hello @JonCognioDigital I'm facing the same problem here, it's been a few hours. Did you manage to find any solution for this?

**Comment by JonCognioDigital** [comment]
> Hello @JonCognioDigital I'm facing the same problem here, it's been a few hours. Did you manage to find any solution for this?

No yet, I've had to park it for now and hoping somebody from next-auth or vercel will figure it out at some point.
