### ISSUE TITLE
Should docs for auth.js start replacing docs for next-auth?

### ISSUE THREAD

**Issue by marcinplatek** [nextauthjs/next-auth#6702]
### What is the improvement or update you wish to see?

I've noticed that e.g. Typescript docs (https://authjs.dev/getting-started/typescript) are absolutely unhelpful when it comes to dealing with authjs. I'd be happy to contribute, but as there is no separation between authjs and next-auth docs, I'm not sure if I should make a PR with an updated version, or would it break the next-auth docs? What's the current recommendation for this? Should I make a PR that includes both versions?

### Is there any context that might help us understand?

I'm using Sveltekit, so next-auth docs can be confusing at times.

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/typescript

**Comment by balazsorban44** [comment]
Yes, it should. We are continuously working on this.

The idea is that as we are rewriting guides on the new docs page, the old one should [redirect](https://github.com/nextauthjs/next-auth/blob/9e423f32528e0bee9c178a61c039d97f27261d3e/docs/vercel.json#L31), unless it's some `next-auth`-specific documentation.

The API Reference documentation is going to be fully generated from the source code, i.e.:

Docs: https://authjs.dev/reference/core
Source: https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/index.ts

In the old docs, this roughly is what you have under:

- https://next-auth.js.org/configuration/*
- https://next-auth.js.org/providers
- https://next-auth.js.org/adapters/*
- https://next-auth.js.org/warnings
- https://next-auth.js.org/errors

So these pages are "moved" by adding proper JSDoc documentation to the source packages in https://github.com/nextauthjs/next-auth/tree/main/packages

It is very welcome if you would like to help with that!

Any adapter/framework package in https://github.com/nextauthjs/next-auth/tree/main/packages is fairly straightforward to contribute to. For providers, a good example is [Auth0](https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/providers/auth0.ts) or [GitHub](https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/providers/github.ts).

Any article (like the TypeScript one you mentioned) will need to be written in a way so it's easy to change between frameworks. We are thinking of a tab UI where you choose the framework and we remember your choice across pages. (similar to the npm/yarn/pnpm install commands)

I'll close this as it does track a specific issue, but I'll pin it so it's easy to find for those who would like to help out! :green_heart:
