### ISSUE TITLE
Typescript: getProviders example for custom signin page throwing errors

### ISSUE THREAD

**Issue by wsfuller** [nextauthjs/next-auth#6704]
### Question 💬

[OAuth Sign in Typescript example](https://next-auth.js.org/configuration/pages#examples) throws the following errors:

<img width="813" alt="Screenshot 2023-02-12 at 10 41 17 AM" src="https://user-images.githubusercontent.com/3144419/218330332-a27a308d-452f-4e8c-9901-360c9fc133e9.png">

<img width="834" alt="Screenshot 2023-02-12 at 10 43 14 AM" src="https://user-images.githubusercontent.com/3144419/218330427-7f48c9c8-92a2-454c-868a-0966da9501ad.png">

Page is set in the correct directory, code is directly copied from example 

### How to reproduce ☕️

Simply use the [OAuth Sign in example](https://next-auth.js.org/configuration/pages#examples)

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Thanks! Merged your PR!
