### ISSUE TITLE
No sign-in options are passed as query string params at all?

### ISSUE THREAD

**Issue by khteh** [nextauthjs/next-auth#6716]
### Provider type

Identity Server 4

### Environment

  System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
    Memory: 49.72 GB / 62.48 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 19.6.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.96
    Firefox: 109.0.1

### Reproduction URL

http://localhost:3000

### Describe the issue

Manage to reach my auth server but the logs show there is no sign-in options passed as query string at all. Without the query string the auth server wouldn't know where to redirect to after login.

### How to reproduce

Run the example app

### Expected behavior

Send sign-in options as query string to auth server.

**Comment by balazsorban44** [comment]
https://next-auth.js.org/getting-started/client#specifying-a-callbackurl

**Comment by khteh** [comment]
> https://next-auth.js.org/getting-started/client#specifying-a-callbackurl

The callbackUrl specifies to which URL the user will be redirected after signing in. **Defaults to the page URL the sign-in is initiated from** but the authentication server does NOT receive this?

**Comment by balazsorban44** [comment]
The AS does not need to receive it either. The expected URL you have to set in the AS is defined here:

https://next-auth.js.org/getting-started/rest-api#getpost-apiauthcallbackprovider

For example for GitHub, it would be `http://localhost:3000/api/auth/callback/github`

Then, when you are redirected back, NextAuth.js will make sure you land on the page you defined in `callbackUrl`.

If you want to pass other params to the authorization endpoint, you can pass them through via the third `signIn` argument https://next-auth.js.org/getting-started/client#additional-parameters.
