### ISSUE TITLE
How to refresh token without applying jwt strategy

### ISSUE THREAD

**Issue by ChiuMungZitAlexander** [nextauthjs/next-auth#6717]
### Question 💬

As the title, how to refresh token without applying jwt strategy

### How to reproduce ☕️

According to the refresh-token-rotation docs (https://authjs.dev/guides/basics/refresh-token-rotation), the `refresh token` should be returned from the callback of jwt.

```
callbacks: {
  async jwt({ token, account }) {
    if (account) {
      // Save the access token and refresh token in the JWT on the initial login
        return {
          access_token: account.access_token,
          expires_at: Date.now() + account.expires_in * 1000,
          refresh_token: account.refresh_token,
        }
    }
    // other logic
  }
}
```

As I started a demo project with mongodb adapter, but not jwt, I found that the jwt callback will never be called. Therefore, the refresh token won't be returned and appended to session. When the access token expires, in this case I cannot refresh it because I cannot get refresh token in session callback.

```
  adapter: MongoDBAdapter(clientPromise),
  callbacks: {
    jwt: async ({ token, account, user }) => {
      // here will never be executed
    },
    // @ts-ignore
    session: async ({ session, token }: SessionType) => {
      // thus refresh token can never be appended to token in arguments
      // and there's no way to refresh access token
    },
```

But I solved this problem by forcing to set session strategy `jwt`. 
```
adapter: MongoDBAdapter(clientPromise),
session: {
  strategy: "jwt",
},
```

I am curious to ask the question - could I do the same if I am not using `jwt` session strategy.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
It's right below :) https://authjs.dev/guides/basics/refresh-token-rotation#database-strategy

**Comment by ChiuMungZitAlexander** [comment]
> It's right below :) https://authjs.dev/guides/basics/refresh-token-rotation#database-strategy

I should have refreshed the page:joy::joy:
