### ISSUE TITLE
Logo missing from Default Signin Page

### ISSUE THREAD

**Issue by raulmarindev** [nextauthjs/next-auth#6727]
### Environment

System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 13.64 GB / 31.85 GB
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 110.0.5481.77
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.41)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    next: ^13.0.0 => 13.1.6
    react: ^18.2.0 => 18.2.0
    next-auth: ^4.19.1 => 4.19.1

### Reproduction URL

https://github.com/raulmarindev/default-signin-logo-missing

### Describe the issue

A custom logo won't appear anymore in the default SignIn page. In next-auth@4.19.1 the logo was removed from the default SignIn page as can be seen in the image below (line 91 was removed).

![image](https://user-images.githubusercontent.com/26367595/218999520-b80c6da6-4453-479e-92ae-725d8d2b0452.png)

### How to reproduce

In a nextjs app go to pages\api\auth\[...nextauth].ts] and add a logo property with an image url to the theme:

![image](https://user-images.githubusercontent.com/26367595/219004929-8fb7bffa-b4fb-4159-8ccf-8f0958052aee.png)

Start the web app and go to the SignIn page. The logo won't be rendered.

### Expected behavior

The logo should be rendered.

**Comment by raulmarindev** [comment]
I created a PR to fix this: https://github.com/nextauthjs/next-auth/pull/6728

**Comment by zenflow** [comment]
@ThangHuuVu This is still an issue in the latest version of `next-auth` (version 4.19.2).
Any idea when the fix will be released?
I noticed that 2 days ago (February 24th) there were releases for a bunch of packages, but it seems this package was missed
