### ISSUE TITLE
pnpm run build in apps/dev/sveltekit fails (can't resolve crypto)

### ISSUE THREAD

**Issue by jschlesser** [nextauthjs/next-auth#6732]
### Environment

  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 53.50 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Firefox: 105.0.1
    Safari: 16.2

### Reproduction URL

no url, its a build error

### Describe the issue

When trying to run `pnpm run build` in the apps/dev/sveltekit app, the build fails.  Note that running `pnpm run dev` seems to work fine.   When the build fails, it complains that it can't resolve the crypto module.    Note that running `npm install` and `npm run build` in the corresponding apps/examples/sveltekit directory runs just fine.   Also running `pnpm run dev` on the same code outside of the next_auth library seems to run fine.   As far as I can tell it only happens when the package dependencies for core and sveltekit framework are "workspace:*".

I'm running into this in the course of preparing a PR that will enable usage of authjs in cloudflare pages / workers.   The good news is that it works, with some minor improvements.  However, It's difficult to test inside of the next_auth repo to demonstrate that it works.

### How to reproduce

1.  Make sure you have an up to date main of the next_auth repo.
2. Make sure that you have built the main repo, `pnpm run build`
3. `cd apps/dev/sveltekit`
4. `pnpm run build`
5. Observe the error message about not being able to resolve the crypto module.

### Expected behavior

When the build of the sveltekit app succeeds, no errors should be present in the terminal and some assets should be generated in the .sveltekit/[generated|output]/server directories in the sveltekit application.

**Comment by ThangHuuVu** [comment]
I see, the problem seems to be related to a dependency in our adapter-pouchdb:
https://github.com/nextauthjs/next-auth/blob/main/packages/adapter-pouchdb/package.json#L38
Removing this dependency solves the issue. We shouldn't use this dependency anymore anyway, so let's remove it 💪

**Comment by balazsorban44** [comment]
Not sure how that adapter is tied to this framework package though, but nonetheless we can remove it.

**Comment by gamebox** [comment]
I'm really failing to see how a dependency package (with no code), in an adapter my project is not using could cause the implementation of crypto to change.  I double checked my `pnpm-lock.yml` and found no references to that package.  But i'm seeing a very similar issue, but with `dev`.  The `crypto` global only has `getRandomValues` defined on it.  `subtle` as well as `webcrypto` are both undefined when running `dev`.

Here is logs, first line is the node version followed by a console.log'd version of `crypto`, the rest is the error I'm getting:

```
v16.16.0 { getRandomValues: [Function: getRandomValues] }
 error   Cannot read properties of undefined (reading 'digest')
  File:
     error   Cannot read properties of undefined (reading 'digest')
  File:
  <REDACTED>/node_modules/.pnpm/@auth+core@0.5.0/node_modules/@auth/core/lib/web.js:86:38
  Code:
    85 |     const data = new TextEncoder().encode(message);
    > 86 |     const hash = await crypto.subtle.digest("SHA-256", data);
         |                                      ^
      87 |     return Array.from(new Uint8Array(hash))
      88 |         .map((b) => b.toString(16).padStart(2, "0"))
      89 |         .join("")
  Stacktrace:
TypeError: Cannot read properties of undefined (reading 'digest')
```

System:
OS: macOS 12.3
CPU: (8) arm64 Apple M1
Memory: 32.00GB
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 16.16.0 
pnpm: 7.27.1
Browsers:
Arc: Version 0.91.1 (37373) - Chromium Engine Version 110.0.5481.177
