### ISSUE TITLE
[FATAL] Firebase adapter is broken

### ISSUE THREAD

**Issue by maxprilutskiy** [nextauthjs/next-auth#6740]
### Adapter type

@next-auth/firebase-adapter

### Environment

```
  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 218.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.n/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.3.1 - ~/.n/bin/npm
    Watchman: 2023.02.06.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 16.2
```

### Reproduction URL

https://github.com/maxprilutskiy/next-auth-bug

### Describe the issue

Firebase/Firestore Adapter is broken. Attempts to have even a minimal code that does imports from `@next-auth/firebase-adapter` result in errors:

```
Server Error
Error: Cannot find module '/Users/maxprilutskiy/Enprimal/asyncrun/node_modules/@next-auth/firebase-adapter/utils' imported from /Users/maxprilutskiy/Enprimal/asyncrun/node_modules/@next-auth/firebase-adapter/index.js

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
new NodeError
node:internal/errors (399:5)
finalizeResolution
node:internal/modules/esm/resolve (326:11)
moduleResolve
node:internal/modules/esm/resolve (945:10)
defaultResolve
node:internal/modules/esm/resolve (1153:11)
nextResolve
node:internal/modules/esm/loader (163:28)
ESMLoader.resolve
node:internal/modules/esm/loader (838:30)
ESMLoader.getModuleJob
node:internal/modules/esm/loader (424:18)
ModuleWrap.<anonymous>
node:internal/modules/esm/module_job (77:40)
link
node:internal/modules/esm/module_job (76:36)
```

### How to reproduce

In order to reproduce the issue, it's enough to just do the following:

1. `yarn create next-app test`
2. `yarn add next-auth @next-auth/firebase-adapter firebase-admin` - btw the docs page has a typo and says `@next-auth/firebase-admin-adapter` instead of `@next-auth/firebase-adapter`. The references are broken everywhere, so I couldn't find the corresponding GitHub source of truth to fix it, sorry;
3. import anything from `@next-auth/firebase-adapter`, for example - [https://github.com/maxprilutskiy/next-auth-bug/blob/master/src/pages/api/hello.ts](https://github.com/maxprilutskiy/next-auth-bug/blob/master/src/pages/api/hello.ts):
```typescript
// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from 'next'
import { FirestoreAdapter } from "@next-auth/firebase-adapter"

type Data = {
  name: string
}

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<Data>
) {
  console.log(FirestoreAdapter);
  res.status(200).json({ name: 'John Doe' })
}
```

### Expected behavior

I expect the documentation to work as described and not to throw errors.

**Comment by mrtgm** [comment]
I lowered the @next-auth/firebase-adapter version 2.00 to 1.03 and it worked

**Comment by hoklenghak** [comment]
@mrtgm Thank to you, this works for me. But, I'm curious as to why the error occurs with version 2.0.0.

**Comment by maxprilutskiy** [comment]
Not exactly - `1.0.3` version has a completely different API than `2.0.0`: `1.0.3` relies on client-side config, while `2.0.0` works with service account credentials.

The problem is there, and unfortunately the adapter does not work.

**Comment by balazsorban44** [comment]
We identified the issue, it was a relatively minor one with some ESM resolving in the output. Releasing a patch soon.

**Comment by suitux** [comment]
Same here

**Comment by suitux** [comment]
@balazsorban44 Do you know when this will be fixed?

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth/releases/tag/%40next-auth%2Ffirebase-adapter%402.0.1

🎉

**Comment by HigorAlves** [comment]
This doesnt fix the problem yet

**Comment by callumbirks** [comment]
Bump. I'm having the same problem, using 2.0.1
