### ISSUE TITLE
Debug logs not displayed when database connection cannot be made

### ISSUE THREAD

**Issue by JLHasson** [nextauthjs/next-auth#675]
**Describe the bug**
I am getting an error during sign in that results in landing at `/api/auth/signin?error=Callback` after the call. I have narrowed this down to being a database connection issue (if I remove `database: {...}` from my `options` I am able to sign in successfully). I have `debug: true` in my `options` yet when I get returned back to `/api/auth/signin?error=Callback` there are no debug logs. If I disable the database connection (as mentioned above) I do see the debug logs, so it would appear that when I am unable to make a db connection something is preventing the error logs from being logged.

**Steps to reproduce**
Steps to reproduce the behavior.

1. Navigate to /api/auth/signin
2. Click "Sign in with Github"
3. Authorize Github Oauth application
4. Be returned back to /api/auth/signin?error=Callback

**Expected behavior**

I should see the debug logs for the failed db connection in the console.

**Screenshots or error logs**
If applicable add screenshots or error logs to help explain the problem.

Instead I only get a status 200:
![image](https://user-images.githubusercontent.com/2087380/93165198-433e2c80-f6d0-11ea-8146-612820ebc3e4.png)

**Additional context**

This is on a Vercel deployment attempting to connect to a postgres hosted on Digital Ocean. The issue doesn't exist when developing locally.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by JLHasson** [comment]
Actually, if I narrow my database instance "allow IP ranges" to something really restrictive (i.e. _only_ my local machine's IP) I get a 502 bad gateway error (similar to mentioned here: https://github.com/nextauthjs/next-auth/issues/660). If I open the instance up to all IPs, then I get the issue I've described above. So I guess what I really want to know is how to get debug info when I land at `/api/auth/signin?error=Callback`? Because right now I don't get any info in the server logs or in the console

**Comment by JLHasson** [comment]
Ok, an update. The issue was indeed due to a poorly configured database connection. Once I resolved the database connection issue I was able to login without the error. My particular issue was that I was passing the wrong `ssl: {...}` config. I think I would still consider this a bug, as the docs say that next-auth should pass the error up and log it in the console, but for my issue there were no logs surfaced and I just ended up at `signin?Error=Callback` with no other info.

**Comment by iaincollins** [comment]
Thanks for the report.

I agree we need additional debug error handling for authentication flows, as mostly it's just around database interactions right now (which also assumes you are using a database, and doesn't help with debugging oAuth problems).
