### ISSUE TITLE
Database Sessions: How to View User Granted Scopes?

### ISSUE THREAD

**Issue by msbeeman** [nextauthjs/next-auth#6754]
### Question 💬

First off, I want to take a moment to apologize because I asked a similar question but it was assumed I was using JWT's, not database sessions, because I did not provide appropriate enough context, so this time I will be asking specifically about database sessions while providing better context and examples.

**Business Context**: I am using **database sessions**, **not JWT's.**. I have a business use case where I request additional **optional** scopes from the user when they sign in with a particular provider, so that I can make a request to the provider downstream and retrieve data on behalf of the user. If the user does not grant the additional scopes, then there is no point in attempting to make requests to the API on behalf of the user to get this data, since it will be unauthorized and fail. I am trying to figure out how to know what scopes/permissions the user ended up granting to me, so that I don't make any unauthorized requests.

**Question**: Is it possible **while using database sessions**, to find out if the user granted an optional scope/permission? If so, how?

**Visual Generic Example**: Here is a generic example scenario using a picture from Google's sign in page. User John Doe is brought to the providers page where some scopes are required and some scopes are optional. We want to figure out if John Doe granted the optional "see calendar" scope. If John Doe didn't check the box to grant it to us, then we do not want to make an unauthorized request to the provider to get this data, since John Doe did not approve it. But how do I know if John Doe approved it or not when I am using database sessions?
![image](https://user-images.githubusercontent.com/59752826/219826254-bc171628-79f2-4da6-aaa1-375439b69e57.png)

### How to reproduce ☕️

```
export const authOptions = {
  ...,
  providers: [
       GenericProvider({
            authorization: {
                  scope:"profile:read_all, chats:read_all, etc..."
             }
       })
  ],
  session: {
        strategy: "database",
 }, 
...
}```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Usually the scopes are encapsulated in the access_token you are given, so you cannot make unauthorized requests.

But the scopes are usually also saved plainly as the `scope` property on the Account model as shown own in the docs here: https://next-auth.js.org/adapters/models

**Comment by msbeeman** [comment]
> Usually the scopes are encapsulated in the access_token you are given, so you cannot make unauthorized requests.
> 
> But the scopes are usually also saved plainly as the `scope` property on the Account model as shown own in the docs here: https://next-auth.js.org/adapters/models

Oh okay I understand, thank you for the reply. I think the problem is that the provider I'm using doesn't pass back the scopes then for some reason. I tried adding another provider (Google), and signing in and confirm that I received scopes from Google.
