### ISSUE TITLE
Duplicate page warning when running Next.js with authentication

### ISSUE THREAD

**Issue by wiscaksono** [nextauthjs/next-auth#6755]
### Environment

  **System:**
>    OS: Windows 10 10.0.22621
>     CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
>     Memory: 7.06 GB / 15.93 GB

  **Binaries:** 
>  Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
>     Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
>     npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD

  **Browsers:**
>    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.46)
>     Internet Explorer: 11.0.22621.1

**Here is my `package.json`**
```json
  "dependencies": {
    "@emailjs/browser": "^3.10.0",
    "@headlessui/react": "^1.7.11",
    "@react-icons/all-files": "^4.1.0",
    "@tailwindcss/forms": "^0.5.3",
    "@tailwindcss/line-clamp": "^0.4.2",
    "@types/react": "18.0.28",
    "@vercel/analytics": "^0.1.10",
    "eslint": "8.34.0",
    "eslint-config-next": "13.1.6",
    "framer-motion": "^9.0.4",
    "next": "^13.1.7-canary.8",
    "next-auth": "^4.19.2",
    "react": "18.2.0",
    "react-code-blocks": "^0.0.9-0",
    "react-dom": "18.2.0",
    "tailwind-scrollbar": "^2.1.0",
    "typescript": "4.9.5",
    "typewriter-effect": "^2.19.0"
  },
  "devDependencies": {
    "@types/node": "18.14.0",
    "autoprefixer": "^10.4.13",
    "postcss": "^8.4.21",
    "prettier": "^2.8.4",
    "prettier-plugin-tailwindcss": "^0.2.3",
    "tailwindcss": "^3.2.7"
  }
  ```
  
 **Here is my folder structure**
![image](https://user-images.githubusercontent.com/63142229/219849549-a856b7ca-78e2-409e-be2d-1ded06c786af.png)

**Additional information:**
I have tried the following steps to resolve the issue:

- Upgrading all the packages
- Checking my code for any duplicate pages
- Restarting my development server
- None of these steps have resolved the issue.

### Reproduction URL

https://github.com/wiscaksono/wiscaksono-next

### Describe the issue

I am encountering a problem with Next.js where I am receiving a "Duplicate page detected" warning when running `yarn dev`. Specifically, the following warnings are appearing in my console:

```
warn - Duplicate page detected. src\pages\api\api.ts and src\pages\api\api.ts resolve to /api/api
warn - Duplicate page detected. src\pages\api\auth\[...nextauth].ts and src\pages\api\auth\[...nextauth].ts resolve to /api/auth/[...nextauth]
warn - Duplicate page detected. src\pages\api\auth\[...nextauth].ts and src\pages\api\auth\[...nextauth].ts resolve to /api/auth/[...nextauth]
warn - Duplicate page detected. src\pages\api\auth\[...nextauth].ts and src\pages\api\auth\[...nextauth].ts resolve to /api/auth/[...nextauth]
```

I have checked my code and I am confident that there are no duplicate pages in my project. I believe that this issue is related to the Next.js authentication configuration that I have set up using `next-auth`.

### How to reproduce

1. Clone the project from this repository
2. Run `yarn install`
3. Run `yarn dev`
4. Observe the duplicate page warnings in the console

### Expected behavior

I expect that when running yarn dev with next-auth authentication enabled, I should not receive any "Duplicate page detected" warnings.

I believe that this issue may be related to a bug in Next.js or next-auth, or it may be related to a configuration issue with my project.

Thank you for your assistance in resolving this issue.

**Comment by balazsorban44** [comment]
This warning comes from Next.js, so it's likely related to that.

can you upgrade your `canary` version here

https://github.com/wiscaksono/wiscaksono-next/blob/bbe180f7044d7118a2e8c1b47576bcb30de6f408/package.json#L22

and if the issue still happens, open this on the Next.js repo? 🙏


Tip: try removing all unnecessary dependencies/code until you are left with the most minimal code that still reproduces the issue.

**Comment by mattroeske** [comment]
Was this resolved?  I'm getting the exact same error even when using nothing but a direct copy of the next-auth-example.

Example error from yarn dev:
yarn run v1.22.19
$ next
- info Loaded env from /Users/matthewroeske/code/next-auth-example/.env
- ready started server on [::]:3000, url: http://localhost:3000
- event compiled client and server successfully in 71 ms (20 modules)
- wait compiling...
- event compiled client and server successfully in 77 ms (20 modules)
- info Loaded env from /Users/matthewroeske/code/next-auth-example/.env
- warn Duplicate page detected. pages/api/auth/[...nextauth].ts and app/api/auth/[...nextauth]/route.ts resolve to /api/auth/[...nextauth]
- warn Duplicate page detected. pages/api/auth/[...nextauth].ts and app/api/auth/[...nextauth]/route.ts resolve to /api/auth/[...nextauth]
- info Loaded env from /Users/matthewroeske/code/next-auth-example/.env
- warn Duplicate page detected. pages/api/auth/[...nextauth].ts and app/api/auth/[...nextauth]/route.ts resolve to /api/auth/[...nextauth]
- warn Duplicate page detected. pages/api/auth/[...nextauth].ts and app/api/auth/[...nextauth]/route.ts resolve to /api/auth/[...nextauth]
- wait compiling /_error (client and server)...

localhost:3000 throws a similar error

Failed to compile
Conflicting app and page file was found, please remove the conflicting files to continue:
  "pages/api/auth/[...nextauth].ts" - "app/api/auth/[...nextauth]/route.ts"
This error occurred during the build process and can only be dismissed by fixing the error.

**Comment by valente** [comment]
Also getting this issue when trying out the example.

**Comment by sebastiannordby** [comment]
Can confirm that i also get this issue by just cloning the repository and trying to run the application.
