### ISSUE TITLE
Docusaurus Auth.js support

### ISSUE THREAD

**Issue by dmarkbreiter** [nextauthjs/next-auth#6758]
### Description 📓

Currently, there isn't a clear solution to serve part of a Docusaurus documentation site behind authentication. Auth.js could be a clear and easy way to add that feature. If this is of interest to the team, could there be an example on your documentation site?

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
Docusaurus is a statically generated site, and Auth.js requires a server, so it's not a clear and easy feature to add.

You could host Auth.js on the same domain though, and create a Next.js app for example, and use a Middleware for routing, based on auth state. Check out https://next-auth.js.org/configuration/nextjs#middleware

**Comment by wade-liwei** [comment]
> to

how's going?
