### ISSUE TITLE
proxy, google oauth, and connection refusal 

### ISSUE THREAD

**Issue by archywillhe** [nextauthjs/next-auth#676]
**Your question**

How not to run into `ECONNREFUSED` for google oauth when on a local server on top of proxychain i.e. a proxy conection?

**Details**

I have tested my set up with Github OAuth and it works wonderfully. But for Google OAuth I keep getting `ECONNREFUSED` directly from Google server at `216.58.200.45`.

```
https://next-auth.js.org/errors#oauth_get_access_token_error
[next-auth][error][callback_oauth_error] Error: connect ECONNREFUSED 216.58.200.45:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '216.58.200.45',
  port: 443
}
https://next-auth.js.org/errors#callback_oauth_error
``` 

My VPN is deployed on an AWS EC2 instance. And locally I have set up a http proxy for my proxychains that connect to my VPN's client. I'm inside the GFW at the moment so without proxychains I will get timeout error instead.

I did some googling and this appears to be a known issue with testing google oauth locally behind a proxy. Just wondering if anyone knows any way to solve it. Thanks!

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by archywillhe** [comment]
related: https://github.com/jenkinsci/google-oauth-plugin/issues/62 https://github.com/jaredhanson/passport-google-oauth/issues/54

**Comment by archywillhe** [comment]
also related: https://github.com/googleapis/google-api-nodejs-client/issues/1943, https://github.com/googleapis/google-api-nodejs-client/issues/2345

**Comment by archywillhe** [comment]
Interesting! Setting this in my proxychains.conf works!

```
strict_chain

tcp_read_time_out 15000
tcp_connect_time_out 8000

localnet 127.0.0.0/255.0.0.0

[ProxyList]
http {your proxy ip address} {your proxy port}
```

**Comment by mathewtrivett** [comment]
@iaincollins I'm having a similar issue here. My next application is deployed behind a corporate proxy. I learned that node doesn't recognise `http_proxy` or `https_proxy` environment variables.

I need a way for requests made to Google by next-auth to go via the proxy.

@archywillhe Could you share how you are starting the next server using proxychains? Are you using a custom server for next? Are you using pm2 or something like `proxychains yarn next start`?
