### ISSUE TITLE
IdentityServer4 unexpected JWT alg received, expected RS256, got: RS512

### ISSUE THREAD

**Issue by khteh** [nextauthjs/next-auth#6760]
### Provider type

Identity Server 4

### Environment

  System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Memory: 47.02 GB / 70.39 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 19.6.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Firefox: 110.0

### Reproduction URL

https://localhost:3000

### Describe the issue

I configure Identity Server 4 to use `RsaSha512` algo. Does the latest version of next-auth support it? If yes, how to get it to work? Thanks.

### How to reproduce

Configure Identity Server 4 to use `RsaSha512` algo

### Expected behavior

Works with `RsaSha512` algo

**Comment by balazsorban44** [comment]
Note, ID4 is deprecated and you should avoid using it as it does not receive security updates anymore. https://identityserver4.readthedocs.io/en/latest/

That said, you can configure most OIDC options via the `client` config option of the provider. Check out: https://next-auth.js.org/configuration/providers/oauth#client-option
