### ISSUE TITLE
No user details returned from IdentityServer4 provider

### ISSUE THREAD

**Issue by khteh** [nextauthjs/next-auth#6762]
### Provider type

Identity Server 4

### Environment

  System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Memory: 47.05 GB / 70.39 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 19.6.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Firefox: 110.0

### Reproduction URL

localhost:3000

### Describe the issue

```
session: {
  user: { name: undefined, email: undefined, image: null },
  expires: '2023-03-22T08:05:46.476Z'
}
user: undefined
token: {
  picture: null,
  sub: 'GUID',
  userRole: 'admin',
  iat: 1676880346,
  exp: 1679472346,
  jti: 'GUID'
}
```
I configure and use `openid email profile` scopes in both server and client.

### How to reproduce

```
  providers: [
    IdentityServer4Provider({
      id: "buyerportal",
      name: "buyerportal",
      authorization: {
        params: { scope: "openid email profile buyerportal", protection: "pkce" },
      },
      issuer: process.env.IdentityServer4_Issuer || config.get('IdentityServer4_Issuer'),
      clientId: process.env.IdentityServer4_CLIENT_ID || config.get('IdentityServer4_CLIENT_ID'),
      clientSecret: process.env.IdentityServer4_CLIENT_SECRET || config.get('IdentityServer4_CLIENT_SECRET'),
    }),
  secret: process.env.SECRET || config.get('SECRET'),
  jwt: { secret: process.env.SECRET || config.get('SECRET') },
  callbacks: {
    jwt: async ({ token }) => {
      console.log(`token: ${token}`)
      token.userRole = "admin"
      return token
    },
    session: async ({ session, user, token }) => {
      console.log('session:', session)
      console.log('user:', user)
      console.log('token:', token)
      return session;
    }
  },
```

### Expected behavior

User details extracted from returned token.

**Comment by balazsorban44** [comment]
Please refer to the docs: https://next-auth.js.org/configuration/callbacks#jwt-callback

**Comment by khteh** [comment]
```
callbacks: {
  async jwt({ token, account, profile }) {
    // Persist the OAuth access_token and or the user id to the token right after signin
    if (account) {
      token.accessToken = account.access_token
      token.id = profile.id
    }
    return token
  }
}
```
property `id` does not exist in `profile`.

**Comment by balazsorban44** [comment]
It's an example. The profile shape is determined by what your IdP returns, it might be called `sub`

**Comment by adrifer** [comment]
I've been having the same issue. I'm setting up AuthJS with Identity Server 4, and user claims like (name, email, image/picture) are always null. 

After debugging a little bit I've found the reason why we don't get the user info.

If you look at this code: https://github.com/nextauthjs/next-auth/blob/92a0fc42fafbe8495eb201a726fd1f952be422a9/packages/core/src/lib/oauth/callback.ts#LL128C2-L166C2
```Typescript
  if (provider.type === "oidc") {
    const nonce = await checks.nonce.use(cookies, resCookies, options)
    const result = await o.processAuthorizationCodeOpenIDResponse(
      as,
      client,
      codeGrantResponse,
      nonce ?? o.expectNoNonce
    )

    if (o.isOAuth2Error(result)) {
      console.log("error", result)
      throw new Error("TODO: Handle OIDC response body error")
    }

    profile = o.getValidatedIdTokenClaims(result)
    tokens = result
  } else {
    tokens = await o.processAuthorizationCodeOAuth2Response(
      as,
      client,
      codeGrantResponse
    )
    if (o.isOAuth2Error(tokens as any)) {
      console.log("error", tokens)
      throw new Error("TODO: Handle OAuth 2.0 response body error")
    }

    if (userinfo?.request) {
      profile = await userinfo.request({ tokens, provider })
    } else if (userinfo?.url) {
      const userinfoResponse = await o.userInfoRequest(
        as,
        client,
        (tokens as any).access_token
      )
      profile = await userinfoResponse.json()
    } else {
      throw new TypeError("No userinfo endpoint configured")
    }
  }
```

when the provider type is "oidc" we are not calling to userinfo, instead we are getting profile from:
`profile = o.getValidatedIdTokenClaims(result)`

What I saw is, that line doesn't get profile info, just token information like:
```json
claims {
  nbf: 123123123,
  exp: 123123123,
  iss: 'https://hodor.trackseries.tv',
  aud: 'trackseries.web.svelte',
  iat: 123123123,
  at_hash: 'string',
  sid: 'string',
  sub: 'guid',
  auth_time: 1682964317,
  idp: 'local',
  amr: [ 'pwd' ]
}
```

I didn't try to repro it yet with another OIDC provider, but I'll try to see if I get same results.

**Comment by adrifer** [comment]
After some more investigation, I saw other providers like Slack were including user claims inside the IdToken. So I think a good workaround for this issue would be enabling:
"Always include user claims in IdToken" on the token client setting on IdentityServer4. That makes idToken to contain needed user claims. 

On AuthJS maybe a good solution could be to check if idToken contains user claims and if not to call userinfo.
