### ISSUE TITLE
Add MySQL Adapter

### ISSUE THREAD

**Issue by xyba1337** [nextauthjs/next-auth#6770]
### Description 📓

I'm curious why NextAuth v4 doesn't support MySQL, especially since v3 isn't compatible with the current version of Next.js. MySQL is widely recognized as one of the top relational database systems available, so it seems surprising that support would be dropped.

### How to reproduce ☕️

no.

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
MySQL is supported via multiple adapters like Prisma, TypeORM, Sequelize. Check out https://next-auth.js.org/adapters/overview

You can also write your own adapter if you like to.

See: https://next-auth.js.org/tutorials/creating-a-database-adapter and https://github.com/nextauthjs/next-auth/tree/main/packages for implementation examples
