### ISSUE TITLE
https://docs.duendesoftware.com/identityserver/v6 provider?

### ISSUE THREAD

**Issue by khteh** [nextauthjs/next-auth#6775]
### Provider type

Identity Server 4

### Environment

  System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Memory: 63.05 GB / 70.39 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 19.6.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Firefox: 110.0

### Reproduction URL

http://localhost:3000

### Describe the issue

I use https://docs.duendesoftware.com/identityserver/v6 Do you have the equivalent Provider if IdentityServer4Provider is not appropriate?

### How to reproduce

Use next-auth-example with IdentityServer4 provider against https://docs.duendesoftware.com/identityserver/v6

### Expected behavior

IdentityServer4 provider works with the new Identity Server 4 replacement or provide equivalent new `Provider`

**Comment by balazsorban44** [comment]
Yes, it just wasn't properly documented. #4850 tried to add it, but it was added in the wrong place. Here, I added it: https://next-auth.js.org/providers/duende-identityserver6
