### ISSUE TITLE
Github provider does not sign back in after signing out

### ISSUE THREAD

**Issue by atridadl** [nextauthjs/next-auth#6791]
### Provider type

GitHub

### Environment

System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1
    Memory: 143.25 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Safari: 16.3

### Reproduction URL

https://sprintpadawan.atridad.dev

### Describe the issue

It seems like the Github provider has some issues here. Well, I am unsure if this is isolated to this provider, me being a doofus, or the sveltekit version of authjs.

Hosting environment: Vercel
Framework: SvelteKit
Provider: Github
Adapter: Prisma
Repo: https://github.com/atridadl/sprintpadawan

Issue:
Signing in on anything but localhost works on the first attempt. Once you log out, and try to log back in, it does not appear to log you back in. Oddly enough, I do see sessions in my DB getting created. To fix this, I would need to delete the ```next-auth.callback-url``` from my cookies and re-load. This is puzzling me.. seemingly I made no auth changes. I do occasionally update the packages, but downgrading didn't help either.

### How to reproduce

- Go to https://sprintpadawan.atridad.dev
- Sign in with GitHub (should work)
- Sign out
- Try to sign back in (won't work)
- Delete the ```next-auth.callback-url``` cookie
- Try to sign back in (should work)

### Expected behavior

- Go to https://sprintpadawan.atridad.dev
- Sign in with GitHub (should work)
- Sign out
- Try to sign back in (should work)

**Comment by canastro** [comment]
Not sure if its related, but its weird. Your POST to github signin has two cookies in set-cookie, being one of them the `callback-url`:

![image](https://user-images.githubusercontent.com/1267623/221196981-8d0ad1c9-d514-4451-85cd-c368fc8fbb96.png)

**Comment by atridadl** [comment]
@canastro Exactly!!! Yeah I saw your discussion! It happens ONLY when deployed. Works fine locally. Got angry and am re-writing with Next.js unless I can figure it out lol

**Comment by atridadl** [comment]
I should add that this may not be correctly tagged now. I reproduced in Auth0 as well. So a larger issue vs just the Github provider. Anyways I'm (likely) going to just move on to Next.js since it appears to work. That being said, I still use Svelte for other things and it would be nice if we can figure this one out!

**Comment by canastro** [comment]
@atridadl 

This double cookie in a single set-cookie doesn’t occur in your nextjs version? Do you still use @auth/core in that version?

**Comment by atridadl** [comment]
No not at all. Latest nextauth has no issues but auth/core does

**Comment by Spikeysanju** [comment]
@atridadl Same happened to me as well. It works fine on local environment. Any fix for this issue?

**Comment by atridadl** [comment]
Not as far as I know..

**Comment by atridadl** [comment]
@canastro Hey! Try updating sveltekit and deploying. Seems to work.
