### ISSUE TITLE
Icon not found for Keycloak provider 

### ISSUE THREAD

**Issue by sergiuturus** [nextauthjs/next-auth#6808]
### Provider type

Keycloak

### Environment

*

### Reproduction URL

https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/providers/keycloak.ts

### Describe the issue

The icon provided is not found on the server: https://raw.githubusercontent.com/nextauthjs/next-auth/main/packages/next-auth/provider-logos/keycloak.svg

### How to reproduce

Default behaviour when you set up a simple next-auth with keycloak provider, it gets the default svg icon which is not found on the server: https://raw.githubusercontent.com/nextauthjs/next-auth/main/packages/next-auth/provider-logos/keycloak.svg

### Expected behavior

It would be helpful if we could change that icon with a custom one. Any ideas how to do that?

**Comment by balazsorban44** [comment]
It's served from https://github.com/nextauthjs/next-auth/blob/main/docs/static/img/providers/keycloak.svg

make sure you are on `next-auth@latest`
