### ISSUE TITLE
Confusion about options.secret and options.jwt.secret?

### ISSUE THREAD

**Issue by dpyzo0o** [nextauthjs/next-auth#681]
**Your question**
I'm just confused by the two secrets in the options, should I set them to the same value? Which one should I pass to `jwt.getToken` function?

**What are you trying to do**
The only way it works for me is to set the two secrets the same value, otherwise `jwt.getToken` would return null. Thus I wonder why there are two places to set the secret.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by janus-reith** [comment]
I agree that this is confusing.
If you look at https://github.com/nextauthjs/next-auth/blob/main/src/server/index.js#L122:L126, you can see that it uses `options.secret` in `jwtOptions`, and then overrides with values from `options.jwt`. So in the end, if you set both values, the actual JWT would only make use of `options.jwt.secret` and I think the only leftover usecase for `options.secret` would be to create and verify the `csrfToken`, and if enabled, as salt for the hashed token in the email link signin flow
(Would need to verify that it's just these, only had a quick look).

I'm currently using separate values for `options.secret` and `options.jwt.secret` successfully, but also have `options.jwt.encryption` enabled. I had to provide a separately generated JWK for `options.jwt.signingKey` for some reason, but with a quick look at the code of this project, I don't see a connection from that to the fact that `options.secret` and `options.jwt.secret` are not the same value.

**Comment by donpark** [comment]
Of all the combinations I tried, only way to get `getToken()` working without causing breakage in other parts later (like `JWTs must be decrypted first`) was to set `options.secret` without setting anything in `options.jwt`.
