### ISSUE TITLE
NextAuth Supabase adapter error with "Content-Type not acceptable" message

### ISSUE THREAD

**Issue by robin-wiillus** [nextauthjs/next-auth#6813]
### Question 💬

Hi, I'm currently working on a Next.js project and using the NextAuth Supabase adapter for authentication. However, I'm encountering an issue where the adapter is returning an error with the message "Content-Type not acceptable: application/json, text/plain". The error code is "PGRST102" which seems to indicate a Postgres-related issue.

I follwed [NextAuth document](https://next-auth.js.org/adapters/supabase) exactly, google login had issue with Google sign-in.

Has anyone encountered a similar issue with the NextAuth Supabase adapter? If so, how did you resolve it? Any help or suggestions would be greatly appreciated. Thanks in advance!

Error message:
```

[next-auth][error][adapter_error_createUser] 
https://next-auth.js.org/errors#adapter_error_createuser Content-Type not acceptable: application/json, text/plain {
  code: 'PGRST102',
  details: null,
  hint: null,
  message: 'Content-Type not acceptable: application/json, text/plain
}

```

### How to reproduce ☕️

I followed the [next-auth-example](https://github.com/nextauthjs/next-auth-example) from the [official documentation](https://next-auth.js.org/adapters/supabase).

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by thorwebdev** [comment]
@robin-wiillus are you using Node 18.1.0? If so, could you try upgrading to Node to 18.14.0+? See https://github.com/supabase/supabase-js/issues/691#issuecomment-1423133055 for more details.

**Comment by balazsorban44** [comment]
It's unrelated to NextAuth.js, so I'm closing it as per the above comment. Thanks, Thor!
