### ISSUE TITLE
Resend verification email with email provider

### ISSUE THREAD

**Issue by JonBernardHealia** [nextauthjs/next-auth#6816]
### Question 💬

I'm looking for the best way to trigger a resend of the verification email for the Email provider. I've made a custom `signIn` and `verifyRequest` pages, and would like to add the ability to resend the email from the `verifyRequest` page, and retain the email address and `callbackUrl` from the signIn page.

Anyone have some insights into the best way to do this?

### How to reproduce ☕️

Create a custom `verifyRequest` page and have a button to resend the verification email.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
You can just call the `signIn("email", { email})` method.

**Comment by barrynorman** [comment]
I was looking exactly for this "feature"
Thanks @balazsorban44
