### ISSUE TITLE
faunadb adapter 

### ISSUE THREAD

**Issue by s-kris** [nextauthjs/next-auth#682]
I wanted to use faunadb with next-auth and saw that it's not yet supported. I saw some discussions around it.
So sharing this fauna-adapter here in case if someone wants to quickly integrate faunadb with next-auth.

https://gist.github.com/s-kris/fbb9e5d7ba5e9bb3a5f7bd11f3c42b96

**Comment by LoriKarikari** [comment]
Looks good @s-kris! You can open a PR to add this adapter if you want.

**Comment by s-kris** [comment]
Thank you @LoriKarikari 
Raised PR: #686

**Comment by s-kris** [comment]
#708 was merged tentatively
