### ISSUE TITLE
Expired sessions are not being deleted from DB

### ISSUE THREAD

**Issue by venetc** [nextauthjs/next-auth#6821]
### Question 💬

Prisma + MySQL + Google provider

I am new to backend development and NextAuth, and need some clarification
Is this a bug or expected behavior?

I am using default Prisma adapter setup from [documentation](https://next-auth.js.org/adapters/prisma), with some modifications for testing purposes.

Adapters/models page  [states](https://next-auth.js.org/adapters/models#session) that:

> When a Session is read, we check if it's expires field indicates an invalid session, and delete it from the database. You can also do this clean-up periodically in the background to avoid our extra delete call to the database during an active session retrieval. This might result in a slight performance increase in a few cases.

but currently my database being cluttered with expired sessions.

Here what happens with ```{ strategy: "database", maxAge: 60 }```:
1) Logging in Google provider
2) ```next-auth.session-token``` appears in browser cookies with valid ```Expires / Max-Age``` value
3) Wait for 60s to let token to expire,  ```Expires / Max-Age``` cookie disappeared
4) Prisma studio states, that expired session still exists in ```Sessions``` table
5) Logging in Google provider again, new session being added to db, old session still exists
6) Wait for 60s again, log in again, now i have 3 sessions

But it works like a charm if i call ```signOut()``` method from client, deleting last session. But only last session.

Am i understand something wrong or i encountered a bug?

### How to reproduce ☕️

Versions:
- prisma:  _4.10.1_
- @next-auth/prisma-adapter:  _1.0.5_
- next-auth:  _4.19.2_

<details>
<summary>Auth options</summary>

```typescript
export const authOptions: NextAuthOptions = {
  secret: "***",
  adapter: PrismaAdapter(prisma),
  providers: [
    GoogleProvider({
      clientId: env.GOOGLE_CLIENT_ID,
      clientSecret: env.GOOGLE_CLIENT_SECRET,
    }),
  ],
  session: {
    strategy: "database",
    maxAge: 60, // 60s for testing purposes
    updateAge: 30, // 30s for testing purposes
  },
};
```

</details>

<details>
<summary>Prisma schema</summary>

``` 
generator client {
    provider = "prisma-client-js"
}

datasource db {
    provider = "mysql"
    url      = env("DATABASE_URL")
}

model Account {
    id                String  @id @default(cuid())
    userId            String
    type              String
    provider          String
    providerAccountId String
    refresh_token     String? @db.LongText
    access_token      String? @db.LongText
    expires_at        Int?
    token_type        String?
    scope             String?
    id_token          String? @db.LongText
    session_state     String?

    user User @relation(fields: [userId], references: [id], onDelete: Cascade)

    @@unique([provider, providerAccountId])
}

model Session {
    id           String   @id @default(cuid())
    sessionToken String   @unique
    userId       String
    expires      DateTime
    user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model User {
    id            String    @id @default(cuid())
    name          String?
    email         String?   @unique
    emailVerified DateTime?
    image         String?
    accounts      Account[]
    sessions      Session[]
}

model VerificationToken {
    identifier String
    token      String   @unique
    expires    DateTime

    @@unique([identifier, token])
}
```

</details>

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
If the cookie expires, the reference to the session (session id) in the database is lost, and cannot be deleted automatically anymore. You'll need to make sure to clean up stray sessions like that yourself.
