### ISSUE TITLE
Session with all null values on user with jwt, how does it work ?

### ISSUE THREAD

**Issue by Mautriz** [nextauthjs/next-auth#683]
**Your question**
I'm using JWT, the object return by useSession is always empty (it exists, but with all null values on the user object ex: { name: null, email: null, picture: null } even tho the debug logs everything correctly. 

**What are you trying to do**
I customized the callbacks to return the user, I expected it to this by default, it took me a while to realize how to to it

this is my code 
```typescript
import NextAuth, { InitOptions } from 'next-auth'
import Adapters from 'next-auth/adapters'
import Providers from 'next-auth/providers'
import { prismaClient } from '../../../../graphql/configs/prismaClient'

const options: any = {
  providers: [
    Providers.Facebook({
      clientId: process.env.FACEBOOK_CLIENT_ID,
      clientSecret: process.env.FACEBOOK_CLIENT_SECRET,
    }),
  ],
  database: process.env.DATABASE_URL,
  jwt: {
    encryption: true,
    // secret: process.env.AUTH_SECRET,
  },
  session: {
    jwt: true,
    updateAge: 1000 * 60 * 60 * 24,
  },
  secret: process.env.AUTH_SECRET,
  useSecureCookies: process.env.NODE_ENV === 'production',
  adapter: Adapters.Prisma.Adapter({ prisma: prismaClient }),
  debug: true,
 // these callbacks are what makes the user work as expected, otherwise it returns empty values
  callbacks: {
    session(session, payload) {
      if (payload.account) session.user = payload.account
      return session
    },
    jwt(token, account, user, userInfo) {
      if (userInfo) token.account = userInfo
      return token
    },
  },
}

export default (req, res) => {
  return NextAuth(req, res, options)
}

// _app.tsx
 <Provider session={pageProps.session} options={{ keepAlive: TEN_MINUTES, clientMaxAge: ONE_WEEK }}>
        <Component {...pageProps} />
   </Provider>

// index.tsx

function Home() {
  const { data, loading: queryLoading } = useMyQueryQuery({ ssr: true, fetchPolicy: 'cache-first' })
  const [session, sessionLoading] = useSession()
  return (
    <Layout>
      <Head>
        <title>Next.js × Nexus Todo App</title>
      </Head>
      {session && JSON.stringify(session)}
      {sessionLoading}
      <a href="/api/auth/signin">Sign in</a>
      <a href="/api/auth/signout">Sign out</a>
    </Layout>
  )
}
```

**Feedback**
* [-] Found the documentation helpful // meh, kinda, the callbacks doc surely helped, but took me a while to realize I had to use them
* [x] Found documentation but was incomplete
* [] Could not find relevant documentation
* [] Found the example project helpful
* [x] Did not find the example project helpful // it didnt have callbacks, but worked fine appearently

Seems like a great library btw ! :D, I probably just misunderstood something I suppose

**Comment by iaincollins** [comment]
Hi @Mautriz 

Thanks for sharing your issue and config!

This should actually work out of the box for name, email and picture, as per the example:

https://next-auth-example.now.sh/api-example

![Facebook API](https://user-images.githubusercontent.com/595695/93891239-22cf2d00-fce3-11ea-8ded-3c7afa9024b9.png)

I wonder what the trigger is for this issue.

**Comment by ChristoRibeiro** [comment]
@iaincollins I get the same issue and seems to be related with Prisma adapter. If I remove it the adapter, everything works great without callback.

**Comment by ChristoRibeiro** [comment]
The issue come up If you have both the `database` and `adapter` with Prisma. Keep the `adapter` and remove the `database` and no need of callbacks anymore:

```js
// this doesn't work
database: process.env.DATABASE_URL,
adapter: Adapters.Prisma.Adapter({ prisma }),

// this work
// database: process.env.DATABASE_URL,
adapter: Adapters.Prisma.Adapter({ prisma }),
```

Maybe the documentation should be more clear with these 2 options together @iaincollins?

**Comment by ChristoRibeiro** [comment]
[This line](https://github.com/nextauthjs/next-auth/blob/v3.1.0/src/server/lib/callback-handler.js#L108) throw an error:

```
Invalid `prisma.account.findOne()` invocation:


  write EPIPE
    at PrismaClientFetcher.request (/Users/christophe/Code/mynextjsproject/node_modules/@prisma/client/runtime/index.js:78121:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {code: 'EPIPE', clientVersion: '2.13.0', meta: undefined, stack: 'Error: 
Invalid `prisma.account.findOne()` in…ctions (internal/process/task_queues.js:97:5)', message: '
Invalid `prisma.account.findOne()` invocation:
```

**Comment by ChristoRibeiro** [comment]
I found the error. 

The function [getUserByProviderAccountId](https://github.com/nextauthjs/next-auth/blob/85b859231c6948d68749d60d861d65bcbcede6c2/src/adapters/prisma/index.js#L81) from the Prisma adapter return a row from the Account table instead of the User table. 

Based on the wrong data, the JWT payload data will not be filled correctly. The [`user` variable](https://github.com/nextauthjs/next-auth/blob/85b859231c6948d68749d60d861d65bcbcede6c2/src/server/routes/callback.js#L84) contains data from the table Account, not from the User data.

**Comment by ChristoRibeiro** [comment]
in the [Prisma adapter](        return prisma[Account].findOne({ where: { compoundId: getCompoundId(providerId, providerAccountId) } })), this should fix the issue:

```js
const account = await prisma[Account].findOne({ where: { compoundId: getCompoundId(providerId, providerAccountId) } })
if (!account) { return null }
return prisma[User].findOne({ where: { id: account.userId } })
```

**Comment by balazsorban44** [comment]
Hi, @ChristoRibeiro could you please create a PR with your recommended fix so 8ta easier to evaluate? Thank you!

**Comment by ChristoRibeiro** [comment]
The issue doesn't appear anymore on [the canary branch](https://github.com/nextauthjs/next-auth/blob/28ce71d99e2e2ad72896e854bc00a8ad470843e1/src/adapters/prisma/index.js#L81) and the deprecated prisma method `findOne` has been updated to `findUnique`. I'm not sur a PR is required. Do you plan to make a release soon @balazsorban44?

**Comment by balazsorban44** [comment]
Yes, hopefully this month.

**Comment by balazsorban44** [comment]
Canary has been out for a while now, try it out with `npm i next-auth@canary` 🎉

**Comment by lommaj** [comment]
Are we sure this is working?  I am not sure if its just me but I cant seem to get JWT to work with prisma adapter, using canary.

**Comment by balazsorban44** [comment]
@lommaj please open a new issue or a discussion with a reproduction of your problem.
