### ISSUE TITLE
Keycloak custom signin page

### ISSUE THREAD

**Issue by Webbrother** [nextauthjs/next-auth#6836]
### Question 💬

Hello! I use `next-auth` with `keycloak` provider. 
At the moment when user click "Login" button the user I call `signIn(...)` function so user redirected to Keycloak authorization page where the user enters his credentials.

BUT:
I want to have custom signin page to have more control of it, so I defined custom signIn page:

```typescript
export default NextAuth({
  pages: {
    signIn: '/signin',
  },
  providers: [
    KeycloakProvider({
      clientId,
      clientSecret,
      issuer,
    }),
  ],
});
```

... and implemented that page.

**The problem**: 

I have no idea how to pass user credentials to keycloak to authorize him.

I tried to call `signIn` method with credentials but didn't succeed.

```typescript
import { signIn } from 'next-auth/react';

const credentials = {
  username: 'admin',
  password: 'admin'
};

signIn('keycloak', credentials);
```

Is it possible to implement custom login page with Keycload provider? If so, please share the best and correct way to do it.
Thanks in advance.

### How to reproduce ☕️

.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
The Keycloak sign-in page is not part of the same app, so you are actually looking into customizing Keycloak, not the Next.js app. Quick google tells me there are Keycloak themes that you can use to do this: https://www.keycloak.org/docs/latest/server_development/#_themes

**Comment by Webbrother** [comment]
@balazsorban44 thank you for your answer.
Yes, I know that I can customize Keycloak theme, but it is not what I want.
I assume that I can interact with Keycloak API without visiting the signing page, but I don't know the correct what of how to do it.

**Comment by Webbrother** [comment]
Why this ticket is closed?
What about Keycloak using of direct grant flow?

**Comment by balazsorban44** [comment]
This is out of scope for the project currently, as it's not part of the OAuth spec and not clear how it can be supported across most of our providers.

Havent heard of direct flow before, do you have a docs link?

**Comment by Nmohyieddine** [comment]
I agree with @Webbrother's point, and it's relevant to my situation as well. I intend to replace Keycloak's default authentication form with a custom one. The idea is that instead of redirecting to the Keycloak authentication page, Next-auth should handle sending the credential data of the custom form via the Keycloak API for authentication, eliminating the need to interact directly with the Keycloak API.

**Comment by nightvision04** [comment]
Our team is strongly considering using Keycloak due to its security, but I'm disappointed we can't use our own React UI and simply pass authentication to Keycloak via api.

I understand styling UI is not the main priority of this project, but we are building a B2C app, and the strict HTML/CSS styling is fairly outdated. @Nmohyieddine, what did you end up going with?

**Comment by sanchayan721** [comment]
@nightvision04, I am facing the same issue with my application as well. It is really strange but I can understand the security concerns. Redirecting to another page is not an option for me. I do not know but is it possible to embed those forms in my app say with iframes or alike?

**Comment by thribhu** [comment]
According the official [documentation](https://www.keycloak.org/docs/latest/server_development/#creating-a-theme) of the keycloak, We can build our own custom onboarding themes using [freemarker](https://freemarker.apache.org). 

They are quite old. Also it  forces us  to download a few apache resources to build one. It is not wise approach for developers who do not have enough storage on their machines like me.
@Webbrother did ever solve this problem of ours.

**Comment by nightvision04** [comment]
Yup, keycloakify was the answer.
