### ISSUE TITLE
Fetch Cache Error on session's cookies

### ISSUE THREAD

**Issue by trpipher** [nextauthjs/next-auth#6839]
### Question 💬

Since Next 13.2 I've been getting this error `Failed to set fetch cache http://localhost:3000/api/auth/session TypeError: cookies is not iterable` 

### How to reproduce ☕️

[here is my minimum repo](https://github.com/trpipher/next-auth-sessions-error)
You see the error in the server terminal on page load

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
The reproduction is missing a sign-in page, and it does not reproduce the described issue.

Nonetheless, for server components, the recommended way to receive the session is `getServerSession`. https://next-auth.js.org/configuration/nextjs#in-app-directory

Therefore, you also don't need `SessionProvider` within the app directory.

**Comment by balazsorban44** [comment]
:warning: Unless you are aware, you should **immediately** replace `FACEBOOK_CLIENT_SECRET`, `GOOGLE_CLIENT_SECRET` as they have been compromised! You should not commit secrets in public github repositories :grimacing:

**Comment by trpipher** [comment]
Well stupid me I thought i put my .env in my .gitignore

**Comment by trpipher** [comment]
I do have a question it's warning me that I am using getServerSession in a server react component 
`[next-auth][warn][EXPERIMENTAL_API] getServerSession is used in a React Server Component.`
so I thought I should I not be doing that. I can just ignore that?

**Comment by trpipher** [comment]
Okay I hopefully have a better repo for you [here](https://github.com/trpipher/debug)
I'm getting an Invalid Compact JWE bug whenever I have my Prisma Adapter Uncommented inside of [...nextauth].ts

**Comment by balazsorban44** [comment]
the whole App Router (`app/`) is under development and opt-in via the `experimental.appDir` flag in Next.js, hence the experimental warning.
