### ISSUE TITLE
Add Custom Fields to User Model via Additional Fields in User Profile

### ISSUE THREAD

**Issue by Navbryce** [nextauthjs/next-auth#684]
**Your question**
How do I add custom fields to my user model through the user profile provider? I added the fields to the profile objects passed by the provider function and updated the user model with the fields. Nonetheless, these custom fields are not populated in the DB (they're null). Not sure if this is supported.

**What are you trying to do**
I'm passing additional fields to the "profile" object from my provider. I want to save those additional fields in my User model.
**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by LoriKarikari** [comment]
You can add custom fields as shown here https://next-auth.js.org/tutorials/typeorm-custom-models.

**Comment by smaktacular** [comment]
@LoriKarikari how would i do this if I don't use any DB? passing null to the typeorm adapter yields an error ...

currently I'm misusing the image property to pass my whole user profile, which feels kinda hacky ...

![grafik](https://user-images.githubusercontent.com/52958977/93590458-da480480-f9ae-11ea-9086-55df5d098fed.png)

**Comment by Navbryce** [comment]
When I pass additional fields to in my profile and add them to my model (following the guide), none of the fields are populated. They are all null in the database.

It looks like the codebase doesn't even pass any additional fields to the user constructor. It just passes those fixed 4 fields:
https://github.com/nextauthjs/next-auth/blob/main/src/adapters/typeorm/index.js#L121-L130
