### ISSUE TITLE
getCsrfToken() for svelte 

### ISSUE THREAD

**Issue by franklovefrank** [nextauthjs/next-auth#6842]
### Description 📓

Hello! I am an engineer at [Spruce ID](https://spruceid.com/) currently working on integrating the new Auth.js package with our own SDK. It would be great to have a svelte-compatible `getCsrfToken({req})` server-side function, as I have not been able to find anything in SvelteKit that satisfies the argument type `CtxOrReq.req` required by the current implementation. Otherwise the new changes are looking great :))  Thank you 

### How to reproduce ☕️

For our React package, we are currently using `const nonce = await getCsrfToken({ req });` to pass to a session provider. We would like to have a Svelte package with the same functionality. 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Since SvelteKit has builtin CSRF protection, we are actually planning to migrate away from using Auth.js' CSRF protection by utilizing the `skipCSRF` framework-specific config option.

https://authjs.dev/reference/core#skipcsrfcheck

See #4992 for more details
