### ISSUE TITLE
getServerSession does not include custom fields (such as roles)

### ISSUE THREAD

**Issue by jazzypants1989** [nextauthjs/next-auth#6843]
### Environment

System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
    Memory: 8.60 GB / 15.69 GB
  Binaries:
    Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.57)
    Internet Explorer: 11.0.19041.1566

### Reproduction URL

https://github.com/jazzypants1989/nextjs-test/tree/next-auth

### Describe the issue

So, I know that credential-based access is not the preferred method, but it's essential to my application's structure and I don't want to have to change the entire thing any more than I've already had to in order to move it to the app directory.

Here's what I get from a console.log on the server: user { name: 'b@b.com', email: 'b@b.com', image: null }

Here's what I get from a console.log on the client: 
email: "b@b.com"
image: null
isEmployee: true
name: "b@b.com"
newsletter: true
_id: "63fe52f3e40f5b80bf1b870a"

### How to reproduce

1.) Add an .env file with these fields:
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=*whatever*
MONGODB_URI=*whatever*

2.) Run the dev server and register a user

3.) Look at the console.logs when you go the admin page.

### Expected behavior

I expect my session to be exactly the same between the client and the server.

**Comment by balazsorban44** [comment]
https://github.com/jazzypants1989/nextjs-test/blob/391741b3ef6e5ccc08e6136b9cce19c8c44d1da2/src/Auth/session.ts#L4

wrong import. You need to pass the auth config, not the whole handler. extract the config object into a variable and export/import that to use in `getServerSession` instead.
