### ISSUE TITLE
Unable to run the next-auth application on Azure Web App Service

### ISSUE THREAD

**Issue by ometett** [nextauthjs/next-auth#6847]
### Question 💬

Hi next-auth team, 

I have an existing next.js application that's run on prod using Azure App service(running as a azure web app). I have implemented authentication using next-auth, and like many of the other users experienced, everything is working fine on local, but I am having a 404 error displayed in console for GET /api/auth/session when I try to start my authentication flow. At first I thought my NEXTAUTH_URL wasn't configured for production because the error type I was gettin
![Screenshot 2023-02-28 at 6 07 29 PM](https://user-images.githubusercontent.com/68041481/222004510-93eed1e7-bf89-4e99-99ca-aa7c78273d55.png)
g was [CLIENT-FETCH-ERROR] but I have double checked that my environment variables are okay and the problem is different. I have done some research and found out that because Azure Web App Service is forcing the user to use the commands "next build && next export" to deploy a nextjs app to Azure App Service(see: https://learn.microsoft.com/en-us/azure/static-web-apps/nextjs), the catch-all api route that I use for authentication [...nextauth].ts becomes unavailable. Is there any way to avoid this? In other words, can next-auth work in Azure Web App Service? In that article I attached, it mentions that a "hybrid" next.js app is possible, but I just could not wrap my head around what changes I should make to be able to use that api route which is essential part of the authentication.

### How to reproduce ☕️

using "build": "next build && next export", command to be able to deploy a nextjs app to Azure App Service. 
next export creates the folder "out" and I use that to make the deployment. However, next-export makes all the pages static HTML which blocks me from using my [...nextauth].ts which uses Server Side Rendering at run-time.  
I have found a microsoft azure tutorial link about deploying hybrid next.js apps, but it does not give much help. 
https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid#adding-an-api-route

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
NextAuth.js is incompatible with the output of `next export` as it needs a backend to run, which is API Routes. See https://nextjs.org/docs/advanced-features/static-html-export#unsupported-features

Standalone mode is claimed to be supported though, but this is a hosting issue and outside the scope of this project.

**Comment by ometett** [comment]
> NextAuth.js is incompatible with the output of `next export` as it needs a backend to run, which is API Routes. See https://nextjs.org/docs/advanced-features/static-html-export#unsupported-features
> 
> Standalone mode is claimed to be supported though, but this is a hosting issue and outside the scope of this project.

Could you elaborate what you mean by the standalone mode? like the application running by itself on Azure web app services?

**Comment by rdwnThouc** [comment]
@ometett Were you able to figure your way out of this, we've run into the same issue and not sure how to get around this.

**Comment by balazsorban44** [comment]
This is not possible with `next export`, please see the link in: https://github.com/nextauthjs/next-auth/issues/6847#issuecomment-1452309851

**Comment by ometett** [comment]
@rdwnThouc yes, I was able to figure it out! As @balazsorban44  mentioned, this is not a bug on the next-auth side. I initially tried to implement the next export, but it was only allowing static web apps that don't have server-side rendering. To get around that issue, I had to add a server.js and a web. config file and I think this is the only way to fix this issue. You can research online to get the default structure of the files, and then simply mention server.js in your package.json to start your application. I hope this helps.. good luck!
