### ISSUE TITLE
## Description 🐜

### ISSUE THREAD

**Issue by yxw770** [nextauthjs/next-auth#6851]
## Description 🐜

Took me a bit of time but I think I finally understood why we were seeing so many errors related to refreshing the token in our app.

I'm following the suggested setup to refresh tokens https://next-auth.js.org/tutorials/refresh-token-rotation which works fine.

The issue is the broadcasting that if you have more than 1 tab open with your web app, it will trigger a session check for EVERY tab and then you end up triggering the `refreshAccessToken()` function multiple times simultaneously with the same set of parameters (same `refresh_token`)

This creates an issue because the first request will be successful and obtain a new `access_token` paired with a `refresh_token` while all the other calls that were made will get a 400 since the old `refresh_token` has just been invalidated by the first successful call.

Simplest way to fix this would be to have the option to disable broadcasting and let each tab try to refresh the session only when focused.

EDIT: 3 scenarios where this is a problem
- broadcasting `getSession` event when a session refresh is already in flight
- opening a new page when a session refresh is already in flight
- focusing a different tab when a session refresh is already in flight

Check here for a lock mechanism proposed solution:
https://github.com/nextauthjs/next-auth/issues/2071#issuecomment-874249385

## How to reproduce ☕️

In the app try to set a `clientMaxAge` of 10 seconds
```js
      <AuthProvider
        session={pageProps.session}
        options={{
          clientMaxAge: 10,
        }}
      >
```
Then add a log in `[...nextauth].js` `jwt` callback
```js
    async jwt(token, user, account, profile) {
      console.log('JWT')
```

Open 2 tabs and move between them, you will notice that every 10 seconds there are 2 calls being made to refresh the session and 2 console logs
```
JWT
JWT
```

I can create a codesandbox later after I finish work if needed but it's pretty simple to verify I believe 😄 

I'm using `"next-auth": "3.23.3"`

_Originally posted by @mtt87 in https://github.com/nextauthjs/next-auth/discussions/3940_

**Comment by balazsorban44** [comment]
This is known and discussed in the discussion you are coming from. Disabling broadcasting would potentially end up causing out-of-sync tabs, so I don't think that's the best solution. <picture data-single-emoji=":thinking:" title=":thinking:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..-04fi6Z_3Os2ukIR.mXlkSR_aPbklLqjTRGVieMguGCAXULYhnOX1VkktPDnfCQNHtv5TXE118ppBg74FxXKrWw9HF1Fk3dG8jNoHSdTIEv1hoQLgjV8Ppxn6sfCGQfdddeK0z4oB.XzEo3KpRjJ-tWakPtYn_tg" alt=":thinking:" align="absmiddle"></picture> 

We might be able to address this easier with the new App Router in Next.js, where you could dedupe the session request that would trigger the token refresh.

_(Sidenote: `next-auth@3` is unmaintained. You should upgrade to v4)_
