### ISSUE TITLE
SvelteKitAuth Custom Provider fails to invoke token endpoint set with custom options

### ISSUE THREAD

**Issue by aakash14goplani** [nextauthjs/next-auth#6852]
### Provider type

Custom provider, Salesforce

### Environment

 ```
 System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 5.66 GB / 15.41 GB

  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD

  Browsers:
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.57)
    Internet Explorer: 11.0.22621.1
```

### Reproduction URL

Snippet provided below for best reference:

### Describe the issue

When we configure custom provider to have `request()` callback within *token* and *userinfo* end-points, the callback is not triggered!

```ts
const configuration: SvelteKitAuthConfig = {
  providers: [{
    id: 'salesforce',
    name: 'Salesforce',
    type: 'oauth',
    authorization: 'https://test.sandbox.my.site.com/identity/idplogin',
    token: {
      url: 'https://test.sandbox.my.site.com/identity/services/test/custom/token',
      async request(context) {
        console.log('token CONTEXT: ', context);  // <- this does not gets logged
        try {
          const formData = new URLSearchParams();
          formData.append('code', context.params.code);
          formData.append('client_id', 'CLIENT_ID');
          formData.append('client_secret', 'CLIENT_SECRET');
          formData.append('redirect_uri', 'http://localhost:4200/auth/callback/salesforce');
          formData.append('grant_type', 'authorization_code');

          const requestHeaders: HeadersInit = new Headers();
          requestHeaders.set('Content-Type', 'application/x-www-form-urlencoded');
  
          const response = await fetch('https://test.sandbox.my.site.com/identity/services/test/custom/token', {
            method: 'POST',
            headers: requestHeaders,
            body: formData.toString()
          });
          console.log('tokens response: ', response);  // <- this does not gets logged
          const tokens = await response.json();
          console.log('tokens: ', tokens);  // <- this does not gets logged
          return { tokens };
        } catch (error) {
          console.log('token CONTEXT ERROR: ', context, error);  // <- this does not gets logged
          throw error;
        }
      }
    },
    userinfo: {
      url: 'https://test.sandbox.my.site.com/identity/services/test/custom/userinfo',
      async request({ provider, tokens }) {
        try {
          console.log('userinfo CONTEXT: ', { provider, tokens }); // <- this does not gets logged
          const requestHeaders: HeadersInit = new Headers();
          requestHeaders.set('access_token', tokens.access_token || '');
          requestHeaders.set('authorization', 'Bearer ' + tokens.access_token);
          const response = await fetch('https://test.sandbox.my.site.com/identity/services/test/custom/userinfo', {
            method: 'GET',
            headers: requestHeaders
          });
          console.log('USERINFO: ', response); // <- this does not gets logged
          return response.json();
        } catch (error) {
          console.log('ERROR in userinfo: ', error);  // <- this does not gets logged
          throw error;
        }
      }
    },
    clientId: CLIENT_ID,
    clientSecret: CLIENT_SECRET,
    checks: ['none']
  }],
  debug: true,
  secret: SECRET
};

export const handle = SvelteKitAuth(configuration) satisfies Handle;
```

Once I hit the localhost -> I am redirected to custom provider's page for authentication -> Once authenticated, I am redirected back as per callbackUrl configured along with Authorize code -> I see error:

![image](https://user-images.githubusercontent.com/13452115/222132545-de96b44a-7cc9-476d-8eca-f3d5eeb4503d.png)

Error Stack:
> error {
      error_description: 'Invalid authentication. Only client_secret_post is supported',
      error: 'invalid_client'
    }
[auth][error][CallbackRouteError]: Read more at https://errors.authjs.dev#callbackrouteerror
[auth][cause]: Error: TODO: Handle OAuth 2.0 response body error
    at handleOAuth (/node_modules/.pnpm/@auth+core@0.4.0/node_modules/@auth/core/lib/oauth/callback.js:91:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Module.callback (/node_modules/.pnpm/@auth+core@0.4.0/node_modules/@auth/core/lib/routes/callback.js:14:41)
    at async AuthInternal (/node_modules/.pnpm/@auth+core@0.4.0/node_modules/@auth/core/lib/index.js:64:38)
    at async Proxy.Auth (/node_modules/.pnpm/@auth+core@0.4.0/node_modules/@auth/core/index.js:100:30)
    at async Module.respond (/node_modules/.pnpm/@sveltejs+kit@1.9.1_svelte@3.55.1+vite@4.1.4/node_modules/@sveltejs/kit/src/runtime/server/respond.js:248:20)
    at async /node_modules/.pnpm/@sveltejs+kit@1.9.1_svelte@3.55.1+vite@4.1.4/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:500:22
[auth][details]: {
  "provider": "salesforce"
}

### How to reproduce

1. Configure application with correct callback Url pattern.
2. Create a custom providers and populate necessary properties. Focus on `token` and `userinfo` option.
3. Configure those 2 properties such a way that they have option for `request()` callback () (Ref.: option 3 https://authjs.dev/reference/providers/oauth#token-option)
4. Verify that callback function is not getting triggered, no logs are printed

### Expected behavior

Callback function should be triggered and logic within callback must be executed!

**Comment by aakash14goplani** [comment]
Also, is there any way where we could tap the request that was made by `SvelteKitAuthConfig` to `token` and `userinfo` endpoints. I want to validate if correct endpoint with correct payload was initiated. How can we do that?

**Comment by balazsorban44** [comment]
The linked documentation seems to be outdated.

We plan to tighten the OAuth conformity of providers we support. The `request` method has been renamed to `conform`. See https://github.com/nextauthjs/next-auth/issues/6365

From the snippet you provided, both `request()` overrides seem to be completely unnecessary.
