### ISSUE TITLE
refreshing access token with battlenet provider & invalid expiration duration for battlenet.

### ISSUE THREAD

**Issue by bonesoul** [nextauthjs/next-auth#6853]
### Question 💬

I'm using next-auth with blizzard's oauth (https://develop.battle.net/documentation/guides/using-oauth) and it does only support issuing new access tokens but not refresh endpoint/functionality is provided.

https://develop.battle.net/documentation/guides/using-oauth/client-credentials-flow

Within this case, how should I be creating my logic that I can detect expired tokens and update them?

within my jwt callback, i can determine i do have an expired token:

```
      console.dir("=================");
      console.dir("jwt");
      console.dir(`current: ${getUnixTime(new Date())}`);
      console.dir(`expires: ${token.exp}`);
      console.dir(
        `expired: ${(token.exp as number) > getUnixTime(new Date())}`
      );
      console.dir("=================");
```

now how can i force next-auth to get a new token?

### How to reproduce ☕️

https://develop.battle.net/documentation/guides/using-oauth/client-credentials-flow

my current implementation is: 
[...nextauth].ts

```
/* eslint-disable lodash/prefer-is-nil */
/* eslint-disable lodash/prefer-constant */

import { frontend_config } from "lib/helpers/env";
import NextAuth, { NextAuthOptions } from "next-auth";
import BattleNetProvider from "next-auth/providers/battlenet";
import { BnetData, getBattlenetData } from "wowtrack-common/wow/account/index";

export const authOptions: NextAuthOptions = {
  pages: { signIn: "/account/signin" },
  providers: [
    BattleNetProvider({
      clientId: frontend_config.api.battlenet.community.client_id,
      clientSecret: frontend_config.api.battlenet.community.client_secret,
      // @ts-ignore: ok.
      issuer: `https://${frontend_config.api.battlenet.community.region}.battle.net/oauth`,
      authorization: {
        params: {
          scope: "openid wow.profile", // include wow.profile in scopes.
        },
      },
    }),
  ],
  callbacks: {
    async jwt({ token, account }) {
      // get the access token and save it in jwt.
      if (
        account !== undefined &&
        account !== null &&
        account.access_token !== undefined
      )
        token.access_token = account.access_token;

      // if token has battle.net data, just skip the rest.
      if (token.battlenet !== undefined) return token;

      // set battle.net account data if it isn't there yet.
      const battlenet_data = await getBattlenetData(
        token.name as string,
        token.access_token as string
      );

      if (battlenet_data !== undefined) token.battlenet = battlenet_data;
      return token;
    },
    async session({ session, token }) {
      // make the session carry the battlenet account data if possible.
      if (token.battlenet !== undefined)
        session.user.battlenet = token.battlenet as BnetData;

      return session;
    },
  },
};

export default NextAuth(authOptions);

```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by bonesoul** [comment]
According to blizzard docs the access tokens are only valid for 24 hours.

`Access tokens last for 24 hours. A user changing their password, removing the authorization for an application's account, or getting their account locked for any reason, results in the expiration of their current access tokens. Developers should always check the response and request a new access token if the current one fails to work.`

But according to my tests, the expiration is set to 1 month.

```
'now(): 1677677695'
'Mar 1, 2023, 4:34:55 PM'
'expires: 1680269528'
'Mar 31, 2023, 4:32:08 PM'
'iat: 1677677528'
'Mar 1, 2023, 4:32:08 PM'
```

I think there may be a bug here with battlenet provider.

**Comment by bonesoul** [comment]
further details:

initial token data by battlenet:

'initial token'
{
  provider: 'battlenet',
  type: 'oauth',
  providerAccountId: '145232',
  access_token: '*************',
  token_type: 'bearer',
  expires_at: 1677766961,
  scope: 'wow.profile openid',
  sub: '145232',
  id_token: '********'
}

```
'token valid'
{
  access_token: '*****',
  expires_at: 1677766961,
  iat: 1677680563,
  exp: 1680272563,
  jti: '72afc869-c699-4ad9-b7e4-42a6a9b772e6'
}
```

**Comment by bonesoul** [comment]
i have improved the debug data:

```
'======================================================'
'initial token'
{
  provider: 'battlenet',
  type: 'oauth',
  providerAccountId: '145232',
  access_token: '***',
  token_type: 'bearer',
  expires_at: 1677767512,
  scope: 'wow.profile openid',
  sub: '145232',
  id_token: '***'
}
1677681114.63
1677767512
{
  access_token: '***',
  expires_at: 1677767512,
  refresh_token: undefined
}
'======================================================'
'token valid'
{
  access_token: '***',
  expires_at: 1677767512,
  iat: 1677681114,
  exp: 1680273114,
  jti: '6349bb9f-29fa-4576-a05f-6ec1a014db4b'
}
'now(): 1677681116057'
'Mar 1, 2023, 5:31:56 PM'
'expires_at: 1677767512000'
'Mar 2, 2023, 5:31:52 PM'
'exp: 1680273114000'
'Mar 31, 2023, 5:31:54 PM'
'======================================================'
'token valid'
{
  access_token: '***',
  expires_at: 1677767512,
  iat: 1677681114,
  exp: 1680273114,
  jti: '6349bb9f-29fa-4576-a05f-6ec1a014db4b'
}
'now(): 1677681116083'
'Mar 1, 2023, 5:31:56 PM'
'expires_at: 1677767512000'
'Mar 2, 2023, 5:31:52 PM'
'exp: 1680273114000'
'Mar 31, 2023, 5:31:54 PM'
```

**Comment by balazsorban44** [comment]
Battlenet does support refresh tokens, at least it claims so:
https://oauth.battle.net/.well-known/openid-configuration

You likely need the `offline_access` for a `refresh_token` to be returned. Then, you can follow https://authjs.dev/guides/basics/refresh-token-rotation

**Comment by bonesoul** [comment]
@balazsorban44 there is also an issue with battlenet provider where it's expiration date is set incorrectly as I did explained above. Should i create a new bug report for it?

**Comment by balazsorban44** [comment]
`expires_at` is set by the underlying library, based on the `expires_in` value to convert it to an absolute point in time.

https://github.com/panva/node-openid-client/blob/d3642296a08da05c1c2ecce8a3145b2096df20f4/lib/token_set.js#L14-L20

It's unlikely a bug in `next-auth`, you can open a discussion instead.

Honestly, it sounds like a docs issue on https://develop.battle.net/documentation/guides/using-oauth. They likely respond with a `expires_in` value of 1 month.

**Comment by bonesoul** [comment]
welll according to their docs, it should be 1 day:

https://develop.battle.net/documentation/guides/using-oauth/client-credentials-flow

`{"access_token": "USVb1nGO9kwQlhNRRnI4iWVy2UV5j7M6h7", "token_type": "bearer", "expires_in": 86399, "scope": "example.scope"}`

anyway ill be checking the response to the actual response and will report back here.

**Comment by Chipinators** [comment]
@balazsorban44 / @bonesoul did you ever figure out what the issue was with this and how to fix it? I've opened a discussion here about this issue.

https://github.com/nextauthjs/next-auth/discussions/11590
