### ISSUE TITLE
expiredAt value in JWT callback is different than decoded accessToken.exp

### ISSUE THREAD

**Issue by JoshuaPerk** [nextauthjs/next-auth#6855]
### My auth setup:
- Vue/Nuxt frontend
- Express backend (separate server)
- Auth0 for IAM provider
- NuxtAuth (wrapper around NextAuth)

### Desired outcome
I want users to be able to login using Auth0 and get access to to hit a separate backend API (that we own) by requesting the Auth0 Audience for that API during login request.

### Issue
Since I need a bearer access token to hit my Express API, I'm using the AuthHandler jwt callback to copy the `account.access_token` to the `token` then to the `session` so I can access it on the front end for requests. The problem is when I log the token, I notice the exp field will be valid, in the future, but the accessToken I've appended to the token, when decoded, has a different, past expiration date. This results in the user being able to "appear" logged in but not be able to access data that's retrieved from the API. Ideally, I'd like to identify when that Audience API access token has expired and refresh it silently.

Code below.

### How to reproduce ☕️

```
import { NuxtAuthHandler } from '#auth'
import { processExpression } from '@vue/compiler-core';
import Auth0Provider from "next-auth/providers/auth0";
export default NuxtAuthHandler({
  pages: {
    signIn: '/' // I have middleware on the index route that automatically redirects to Auth0
  },
  secret: process.env.AUTH_SECRET,
  providers: [
    Auth0Provider.default({
      clientId: process.env.AUTH0_CLIENT_ID,
      clientSecret: process.env.AUTH0_CLIENT_SECRET,
      issuer: process.env.AUTH0_ISSUER,
      scope: 'openid profile email offline_access',
      token: {
        params: {
          audience: process.env.AUTH0_AUDIENCE // This is where I'm requesting access to the backend express server API
        }
      },
      authorization: {
        params: {
          audience: encodeURI(process.env.AUTH0_AUDIENCE)
        }
      },
      idToken: true,
      profile(profile) { // Custom reconstruction of the profile object so I can append our custom RBAC / OrgIds that are set during Auth0's middleware functions
        return {
          id: profile.sub,
          name: profile.nickname,
          email: profile.email,
          image: profile.picture,
          roles: profile['vector/roles'],
          organization: profile['vector/organization']
        }
      },
      checks: 'both'
    })
  ],
  callbacks: {
    async jwt({ token, user, account }) {
      if (user) {
        token.roles = user.roles
        token.organization = user.organization
      }
      if (account) {
        token.accessToken = account.access_token // Persist the OAuth access_token to the token right after signin
      }
      console.log(token.exp) // PROBLEM: This exp will be in the FUTURE
      console.log(token.accessToken) // PROBLEM: When this JWT is decoded it's exp will be in the PAST
      return token
    },
    async session({ session, token }) {
      // Send properties to the client, like an access_token from a provider.
      session.roles = token.roles
      session.organization = token.organization
      session.accessToken = token.accessToken
      return session
    },
  }
})
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
The access token provided by your provided is different from the one NextAuth.js sets since they are meant for two different scenarios. (the one from the IdP is to communicate with APIs, the one NextAuth.js sets is for the active session),

**Comment by martinmckenna** [comment]
This is an old issue, but you guys really need to document this. The fact that the decoded JWE has its own `exp` and `iat` values that match the cookie and not the actual JWT is unbelievably confusing and added an extra 3 days of debugging time to implementing refresh tokens

**Comment by ConnorBP** [comment]
Wow this is stupid

**Comment by mrleblanc101** [comment]
How did you solve the problem ?
Did you overwrite `token.exp` with the value from the decoded JWT ?
Did you change the expiration to a very small value ?
