### ISSUE TITLE
Invalid Compact JWE with Firebase Adapter

### ISSUE THREAD

**Issue by J4mez** [nextauthjs/next-auth#6856]
### Adapter type

@next-auth/firebase-adapter

### Environment

 System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 19.45 GB / 31.91 GB

Binaries:
    Node: 19.7.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD

Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.57)
    Internet Explorer: 11.0.19041.1566

npmPackages:
    @next-auth/firebase-adapter: ^2.0.1 => 2.0.1

### Reproduction URL

streamrec-git-dev-new-j4mez.vercel.app

### Describe the issue

I am using Next JS 13 and next-auth with the firebase adapter

When using the firebase adapter, an error occurs when logging in with the oauth provider google (see below) and prevents the login. 
The error does not occurs if the adapter is commented out and you can login normally. 

In firestore the collections "accounts", "users" and "sessions" are created and populated. I tried using a new firebase project with no luck.
I also cloned the Next Js 13 example here [https://github.com/balazsorban44/nextjs-13-next-auth-app] and just added the firebase adapter to the same outcome. 

Error message emitted when finishing the oauth with google:
```
message: 'Invalid Compact JWE',
  stack: 'JWEInvalid: Invalid Compact JWE\n' +
    '    at compactDecrypt (webpack-internal:///(sc_server)/./node_modules/jose/dist/node/esm/jwe/compact/decrypt.js:20:15)\n' +
    '    at jwtDecrypt (webpack-internal:///(sc_server)/./node_modules/jose/dist/node/esm/jwt/decrypt.js:12:100)\n' +
    '    at Object.decode (webpack-internal:///(sc_server)/./node_modules/next-auth/jwt/index.js:44:53)\n' +
    '    at async AuthHandler (webpack-internal:///(sc_server)/./node_modules/next-auth/core/index.js:157:37)\n' +
    '    at async getServerSession (webpack-internal:///(sc_server)/./node_modules/next-auth/next/index.js:86:21)\n' +
    '    at async Page (webpack-internal:///(sc_server)/./app/user/login/page.tsx:13:21)',
  name: 'JWEInvalid'
```

### How to reproduce

clone https://github.com/balazsorban44/nextjs-13-next-auth-app. 
Add the firebase adapter like https://authjs.dev/reference/adapter/firebase#1-google_application_credentials-environment-variable
Try to login with the google oauth provider. (I didn't test it with other providers) 

### Expected behavior

After the oauth login, the user should be redirected without error in the console.

**Comment by balazsorban44** [comment]
See https://next-auth.js.org/configuration/nextjs#in-app-directory

the linked repo does not use an adapter so it does not need to pass the `adapter` via `authOptions`. Since you added firebase though, you'll have to.
