### ISSUE TITLE
Lost example

### ISSUE THREAD

**Issue by TheHellTower** [nextauthjs/next-auth#6857]
### Question 💬

I remember there was a old [mongodb example](https://github.com/nextauthjs/next-auth-example/tree/main/examples/mongodb) but it's not here anymore, is there a place where I can get it ?

### How to reproduce ☕️

None

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
The linked repository has always been a mirror of the [default Next.js example](https://github.com/nextauthjs/next-auth/tree/main/apps/examples/nextjs).


On how to add MongoDB, check out: https://next-auth.js.org/adapters/mongodb
