### ISSUE TITLE
refreshing token when provider doesn't support  grant_type: "refresh_token"

### ISSUE THREAD

**Issue by bonesoul** [nextauthjs/next-auth#6868]
### Question 💬

So https://authjs.dev/guides/basics/refresh-token-rotation#database-strategy page explains the rotation when the provider allows 
`grant_type: "refresh_token"`

but the provider that I use -- battle.net doesn't support it.

How can I force next-auth to get a new token once I determine the previous one is expired -- without requiring user to logout and login?

### How to reproduce ☕️

https://authjs.dev/guides/basics/refresh-token-rotation#database-strategy

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
It's not possible to refresh a token without the provider supporting it. Your best option is to detect when the token expires and call `signIn("battlenet")` silently.

**Comment by bonesoul** [comment]
@balazsorban44 

I followed your guidance but the problem is that after I call signIn("battlenet"), the my database adapter is not triggered for updating expires_at of account table.

so it just enters a loop of calling signIn("battlenet").

any suggestions?
