### ISSUE TITLE
Discord Scopes being ignored in params

### ISSUE THREAD

**Issue by Bewinxed** [nextauthjs/next-auth#6873]
### Provider type

Discord

### Environment

System:
    OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 63.91 GB / 125.78 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 9.6.0 - ~/Downloads/GuardianGeckoBot/templates/SolMarket/node_modules/.bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 106.0.5

### Reproduction URL

.

### Describe the issue

providers: [
		Discord({
			clientId: DISCORD_ID,
			clientSecret: DISCORD_SECRET,
			authorization: { params: { scope: 'identify email guilds' } })]

when I click sign in using signIn() the auth URL is 'identify email', it's ignore "guilds" and anything else I specify...

https://discord.com/oauth2/authorize?scope=identify+email&response_type=code&client_id=1081488309290815488&redirect_uri=http%3A%2F%2F127.0.0.1%3A5173%2Fauth%2Fcallback%2Fdiscord&code_challenge=S8oyKBSjhcimzwkx3a9j90BUD2by6X49Vfx31sRlJYU&code_challenge_method=S256

### How to reproduce

.

### Expected behavior

It should take me to 
https://discord.com/oauth2/authorize?scope=identify+email+guilds&response_type=code&client_id=1081488309290815488&redirect_uri=http%3A%2F%2F127.0.0.1%3A5173%2Fauth%2Fcallback%2Fdiscord&code_challenge=S8oyKBSjhcimzwkx3a9j90BUD2by6X49Vfx31sRlJYU&code_challenge_method=S256

**Comment by orangekiwi-io** [comment]
I too am having similar issues (with a different provider).

I originally started with an express app to get familiar with Trello and OAuth. I moved to the nextjs/react/component world (more suitable for my ultimate goal) once I got the data and proof working.

## Describe the issue

Passing the params that Trello allows to be changed (in my case: `scope` and `expiration`) works in the dependency node module of [node-oauth](https://github.com/ciaranj/node-oauth) (v0.10.0) in my express app.

Using `next-auth` and a Trello provider, Trello is not receiving the params of `scope` and `expiration` and using its defaults (see **Actual result** below).

[Authorizing With Trello's REST API](https://developer.atlassian.com/cloud/trello/guides/rest-api/authorization/)
[Trello glitch](https://glitch.com/edit/#!/trello-oauth)

It looks like the issues comes from authorization-url file where it checks OAuth versions. In the installed node_module (`node_modules/next-auth/core/lib/oauth/authorization-url.js`) when I hardcode the params I need (and restart the dev server), Trello is happy. Obviously, hardcoded is a no-no, but it shows that the params get lost/ignored somewhere along the way.

## Provider
Trello

```
{
      id: "trello",
      name: "Trello",
      type: "oauth",
      version: "1.0",  // try both 1.0 and 1.0A
      authorization: authorizeURL,
      // authorization: {
      //   url: authorizeURL,
      //   params: {
      //     scope,
      //     expiration
      //   },
      // },
      accessTokenUrl: accessURL,
      requestTokenUrl: requestURL,
      profileUrl,
      profile: (profile) => {
        return {
          id: profile.id,
          avatarUrl: profile.avatarUrl,
          fullname: profile.fullname,
          username: profile.username
        }
      },
      clientId: process.env.TRELLO_APIKEY,
      clientSecret: process.env.TRELLO_APISECRET
    }
```
## How to reproduce

Switching out the `authorization` string for the object in the above **provider** will get the `next-auth` debug error in the **Actual result** section below.

## Environment
- Windows 10 Pro
- node: v18.14.2
- npm: 9.5.0
- browsers:
  - Firefox: 110.0.1
  - Firefox: 112.0a1
  - Chome: 110.0.5481.178

## Github repository
https://github.com/orangekiwi-io/next-auth-trello-oauth1-issue

## [next-auth][debug]
You can see below that the `authorization` string as been expanded to an object with `url` and `params` properties. Despite this, it is not possible to use an `authorization` object in the custom provider in `[/pages/api/auth...nextauth].js`. See the `[...nextauth].js` file in the repository.

```
[next-auth][debug][GET_AUTHORIZATION_URL] {
  url: 'https://trello.com/1/OAuthAuthorizeToken?oauth_token={token}&oauth_token_secret={secret}&oauth_callback_confirmed=true',
  provider: {
    id: 'trello',
    name: 'Trello',
    type: 'oauth',
    version: '1.0',
    authorization: { url: 'https://trello.com/1/OAuthAuthorizeToken', params: {} },
    accessTokenUrl: 'https://trello.com/1/OAuthGetAccessToken',
    requestTokenUrl: 'https://trello.com/1/OAuthGetRequestToken',
    profileUrl: 'https://api.trello.com/1/members/me/',
    profile: [Function: profile],
    clientId: 'xxxKey',
    clientSecret: 'xxxSecret',
    signinUrl: 'http://localhost:8080/api/auth/signin/trello',
    callbackUrl: 'http://localhost:8080/api/auth/callback/trello'
  }
}
```
## Expected result

![Authorize-Trello-expected](https://user-images.githubusercontent.com/71761813/223775186-ba96f932-2cf9-4c19-970a-08a100ac2683.png)
This image shows the expected result from this url: `https://trello.com/1/OAuthAuthorizeToken?oauth_token={token}&name=bbTrello%20OAuth&scope=read,write&expiration=1hour` (with valid token).

## Actual result

Using `authorization` as a string, Trello uses its default values for scope and expiration, namely `read` for scope and `30days` for expiration.

Using `authorization` as an object, generates a `[next-auth][error][SIGNIN_OAUTH_ERROR]` in the terminal:

```
[next-auth][error][SIGNIN_OAUTH_ERROR] 
https://next-auth.js.org/errors#signin_oauth_error undefined {
  error: { statusCode: 400, data: 'Invalid Signature' },
  providerId: 'trello',
  message: undefined
}
```

**Comment by LordMerc** [comment]
Can confirm having same issue.
