### ISSUE TITLE
Get Request object in Custom Model of TypeORM

### ISSUE THREAD

**Issue by iatulb** [nextauthjs/next-auth#688]
How to get "req" object in Custom model of TypeORM?

So in this below constructor, I would like to fetch some properties of request such browser name used for request.

export default class User extends Adapters.TypeORM.Models.User.model {
  // You can extend the options in a model but you should not remove the base
  // properties or change the order of the built-in options on the constructor
  constructor(name, email, image, emailVerified) {
    
    super(name, email, image, emailVerified)
    console.log('====================================User model')
    //console.log(this)
  }
}

in [...nextauth].js, I can do this, so how to achieve this in custom model above?

export default (req, res) => {
  //client ip
  var ip = requestIp.getClientIp(req);
  if (ip == '::1') {
    ip = '127.0.0.1'
  }

  //client browser
  var browser = req.headers['user-agent'];

  //custom attributes of request
  options.myAttributes = {
    ClientIP: ip, //IPv6 Address
    Browser: browser
  }

  return NextAuth(req, res, options)
}

**Comment by karpawich** [comment]
@iatulb see #613 - I believe your Issue has already been surfaced there. If so, feel free to close this issue & point to the earlier one.

**Comment by abeluck** [comment]
This isn't the same as #613. This issue is about getting a handle on the node incoming message request object.
