### ISSUE TITLE
Can't access the extended properties of User in the session returned by the useSession hook

### ISSUE THREAD

**Issue by Pamboli** [nextauthjs/next-auth#6882]
### Question 💬

I have this type extension:

```
import "next-auth";

declare module "next-auth" {
  interface User {
    id: number;
    username: string;
    name: string;
    image: string;
    email: string;
    userToken: string;
  }
  export interface Session {
    user: User;
  }
}
```

And it works perfect for the authorize method on the provider objetc. But when I access the session using the useSession hook, those properties are not there.

This is my authorize method:

```
authorize: async function (credentials) {
        if (!credentials) {
          return null;
        }
        const token = await login(credentials.email, credentials.password);
        if (token) {
          const response = await getUser(token);
          if (!response) return null;
          const { imageProfile, ...user } = response;
          const finalUser: User = {
            ...user,
            image: imageProfile.url,
            userToken: token,
          };
          return finalUser;
        }
        return null;
      },
```

I followed all the steps in https://next-auth.js.org/getting-started/typescript

### How to reproduce ☕️

Create the extension type file and use the useSession hook to see if the new properties are there

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Given your reproduction, this works for me:

![image](https://user-images.githubusercontent.com/18369201/224378475-63b6085a-c2a0-4377-9770-39c1ffb2b429.png)

It's hard to tell because there was no reproduction given.
