### ISSUE TITLE
Handle JWT and Session Callbacks when using Credentials provider and Azure Active Directory provider

### ISSUE THREAD

**Issue by matthewpavia99** [nextauthjs/next-auth#6890]
### Question 💬

Hi! I have implemented a sign in page with the option of logging in with either Email + Password (Credentials Provider) or with Azure AD. The credentials provider works using a custom endpoint to perform the login and also to refresh the access tokens. Much of this logic was implemented in the JWT callback. (Similar to the docs here https://authjs.dev/guides/basics/refresh-token-rotation)

However the issue is that when logging in with Azure AD, the same JWT callback is hit, running the same logic intended for the Credentials provider.

My question is if there is a way to determine which provider is being used for the sign in and hence be able to separate the logic in the callbacks. Thanks!

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Yes. The `jwt` callback gives you `account`, which will have a `provider` property at the time of sign-in, telling you if it's `azure-ad` or `credentials`.

This will be better documented in the new site:

https://authjs.dev/reference/core/types#provider
