### ISSUE TITLE
Status of refreshing tokens

### ISSUE THREAD

**Issue by eatrocks** [nextauthjs/next-auth#690]
What is the status of adding the ability to refresh tokens to the next-auth library?

We use OAuth in a two-party authentication scenario. The application and the IDP are under our control. Therefore, that third-party of Facebook, Twitter, Google, and Apple for example, are never involved. We are using the token expiration and token refresh features of OAuth to drive the length of the users' session with the application. Therefore tokens expire relatively quickly (minutes and hours, not weeks/months/indefinitely). Therefore we need our apps to be able to refresh the tokens. We wouldn't use next-auth with a database; only with JWT's enabled.

Besides reading the docs, looking at some of your source, and having next-auth up and running in a test application I have read through these related to token refreshing...
* [Your token refresh status from July](https://github.com/nextauthjs/next-auth/issues/402#issuecomment-655196037)
* [PR 425 regarding token endpoints](https://github.com/nextauthjs/next-auth/pull/425#issuecomment-658136722)
* [PR 513 the continuation of PR 425](https://github.com/nextauthjs/next-auth/pull/513)

**Comment by eatrocks** [comment]
I am willing to help with this token refresh feature. I have helped write and maintain a non-public library for Next.js with an Express.js custom server using a single, internal IDP in the situation I described above.

**Comment by geraldnolan** [comment]
@iaincollins I keep coming back to check status as well. Everything is working great with the library minus the refresh token piece.  I am not a huge fan of using the JWT callback.  (It was refreshing the token way too much). It's also not updating the secure cookie.

@eatrocks which IDP are you using? I am a little hesitant to post the workaround here until @iaincollins  comments.

**Comment by eatrocks** [comment]
@geraldnolan I'm interested in your workaround. Are you willing to share it? Seems like @iaincollins is busy lately, and that's understandable considering this is an open source project that is contributed to with spare time. 
I also found out that I may not be able to submit a PR for the token refresh feature without approval from my management and likely the legal department :( which will likely be a slow process with questionable outcome.

**Comment by elilambnz** [comment]
I understand that a robust solution is required to refresh tokens for all services, however I've provided a basic workaround for refreshing tokens when using the credentials provider and callbacks [here](https://github.com/nextauthjs/next-auth/issues/371#issuecomment-723696414).

I look forward to official support for refreshing tokens and any critiques to this approach are more than welcome!

**Comment by guido4000** [comment]
This has not been resolved.

**Comment by balazsorban44** [comment]
As the OP asks for only JWT token rotation, I am going to close this as there are user-land solutions for this.
My approach would be something similar to this:
https://github.com/nextauthjs/next-auth/discussions/871#discussioncomment-152412


Until we have a built-in solution (for that #951 is the most up-to-date one), it has to be handled by the user.

A relevant issue as well:
https://github.com/nextauthjs/next-auth/issues/1079
