### ISSUE TITLE
how should altering the User table be done?

### ISSUE THREAD

**Issue by vgrafe** [nextauthjs/next-auth#692]
**Question**
When modifying the `User` TypeORM following [this documentation](https://next-auth.js.org/tutorials/typeorm-custom-models#creating-custom-models), and re-running the app, I do not see the changes in the database schema. What did I miss?

**What I am trying to do**
I am trying to extend the User schema with a custom field.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by vgrafe** [comment]
I found a solution - dropping all the tables from my schema. I was expecting a migration to be done but I guess there's more to this scenario.

**Comment by iaincollins** [comment]
> I found a solution - dropping all the tables from my schema. I was expecting a migration to be done but I guess there's more to this scenario.

Yikes! You are right, this is a scenario where migration would be really handy.

We haven't had to support migrations of the internal schema so far (though it seems obviously like we will need it at some point in the future), but this is certainly a scenario where it would be useful.

Thanks for coming back and updating this.
