### ISSUE TITLE
upstash redis integration, store users as a json and store user id in the session

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [nextauthjs/next-auth#6920]
### Description 📓

Hi :wave: 

Upstash redis integration stores the user as a string, making it hard to work with the redis json package. 

![image](https://user-images.githubusercontent.com/15908060/224487047-c8162639-eaff-417e-accc-133b472ba531.png)

Would it be possible to store is as a json?

Moreover, the `user.id` that next auth stores in the session is not the id that upstash redis uses internally 

The id uses in next auth is the user id from GitHub (the provider I am using) 

![image](https://user-images.githubusercontent.com/15908060/224487104-f2ba5149-de1d-46d2-b3e5-149fc25f5d47.png)

Would it be possible to store the actual stored user's id instead?

Thanks a lot :heart: 

Cheers,

Fra

### How to reproduce ☕️

Use the following code and sing in once

```typescript

import NextAuth from "next-auth";
import GithubProvider from "next-auth/providers/github";
import type { NextAuthOptions } from "next-auth";
import { UpstashRedisAdapter } from "@next-auth/upstash-redis-adapter";

import logger from "@/lib/logger";
import { Redis } from "@upstash/redis";

const redis = new Redis({
  url: process.env.UPSTASH_REDIS_URL,
  token: process.env.UPSTASH_REDIS_TOKEN,
});

export const authOptions: NextAuthOptions = {
  adapter: UpstashRedisAdapter(redis),
  providers: [
    GithubProvider({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET,
    }),
  ],
  ```

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
I'll admit I don't know what "redis json package" is referring to, but AFAIK, Redis is a key-value store, and you cannot store JSON data in it directly. <picture data-single-emoji=":thinking:" title=":thinking:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..NNSA_MPQjRFUG4Kr.d8hlDVKh9nndAHaWGwmlwCFUUwAFIjAW4gW8rSXBd8tmPB9CRSGRlYkz7CH6AN8uhNuaRuQIAT2tYGU1dLNNDXKJi0z7SY8EDP6L2pIQBhnZAc9yFGRVXdjf.Peo27a1wTW-XLTkfLxTT_Q" alt=":thinking:" align="absmiddle"></picture>

As such, I'm not sure if we can/should change the current implementation, but have a look at the source code, if you want to create your own adapter based on the official one. If you can show me how it would look like, we might consider adding it/a config option to the official adapter.

https://github.com/nextauthjs/next-auth/blob/main/packages/adapter-upstash-redis/src/index.ts

> The id uses in next auth is the user id from GitHub (the provider I am using)

Regarding account ids, looks like it was implemented using the `providerAccountId`.

If you are seeing a bug related to this, please open a bug report.

Changing this now would be a breaking change, unfortunately:

https://github.com/nextauthjs/next-auth/blob/c580f0db22e2cae5aa84e3b7bf2e945fa5ed7688/packages/adapter-upstash-redis/src/index.ts#L246

Maybe we could change it via a major version bump in the future, to not rely on the provider's id, but use something like `uuid()`. You can definitely do this in your own implementation if you decide to create a custom adapter.

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @balazsorban44 , thanks a lot for the reply :) Okay, so yeah I got it. The main issue is that they indeed use that id to store the provider information but the whole user is stored under another id, that can be retrieved with the email that has to be retrieved by the first provider id - thus double the call :) I guess I can just ask them directly, thank you a lot :)
