### ISSUE TITLE
Multiple middlewere in nextjs

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [nextauthjs/next-auth#6922]
### Description 📓

Hi :wave: 

I would like to have the possibility to add next-auth into an existing nextjs middlewere, e.g.

```typescript
// middleware.ts

import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

export function middleware(request: NextRequest) {
  if (request.nextUrl.pathname.startsWith('/about')) {
    return NextResponse.rewrite(new URL('/about-2', request.url))
  }

  if (request.nextUrl.pathname.startsWith('/protected')) {
     # next-auth here
  }
}
```

Currently, is not possible.

Thanks.

Cheers,

Fra

### How to reproduce ☕️

Try to add next-auth logic inside an existing middleware like 

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
You can wrap your middleware with `withAuth` as shown here: https://next-auth.js.org/configuration/nextjs#wrap-middleware

Or you can call `withAuth(...config)(request)` if it's not going to be on the top.

**Comment by Shiti** [comment]
@balazsorban44 I have a similar requirement where I need to proxy some calls to an external API. I tried the following based on your suggestion and the [tests](https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/tests/middleware.test.ts)

```typescript
//middleware.ts
import type { NextMiddleware, NextRequest } from "next/server";
import { NextFetchEvent, NextResponse } from "next/server";
import { NextAuthMiddlewareOptions, withAuth } from "next-auth/middleware";

export function middleware(request: NextRequest, event: NextFetchEvent) {
  // rewrite requests to external-api
  if (request.nextUrl.pathname.startsWith(EXTERNAL_API_PREFIX)) {
     // do something else
  } else if(request.nextUrl.pathname.startsWith('/myprotectedpage')){
    const options: NextAuthMiddlewareOptions = {
      secret: process.env.NEXTAUTH_SECRET
    }
    const handleMiddleware = withAuth(options) as NextMiddleware
    return handleMiddleware(request,event)
  }
}
```

This code runs and but I'm now stuck in an infinite loop when I try going to the protected page. It keeps redirecting to `http://localhost:3000/api/auth/signin?callbackUrl=%2Fmyprotectedpage` even after signing in.

Would appreciate any pointers on what I may have missed or done incorrectly.

**Comment by FrancescoSaverioZuppichini** [comment]
+1 from my side, I have experience the infinite loop as well. @balazsorban44 could you please reopen this issue since it's **clearly** not solved. Thank you for everything
