### ISSUE TITLE
Property 'accessToken' does not exist on type 'Session'.

### ISSUE THREAD

**Issue by Leprekus** [nextauthjs/next-auth#6923]
### Question 💬
`"next-auth": "^4.20.1"`

Assigning a value to the accessToken property in session raises the following error: 
[Property 'accessToken' does not exist on type 'Session'.ts(2339)](url)

### How to reproduce ☕️

```
import NextAuth, { AuthOptions } from "next-auth"
export const authOptions:AuthOptions = {
  providers: [
    // ...add more providers here
  ],
  secret: process.env.NEXT_SECRET,
  callbacks: {
    async jwt({ token, account }) {
      if(account) {
        token.accessToken = account.access_token
      }
      return token
    },
    async session({ session, token, user }) {
       //warning raised here
      session.accessToken = token.accessToken
      return session
    }
  }
}
export default NextAuth(authOptions)
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
https://next-auth.js.org/getting-started/typescript

**Comment by yekta-yengi** [comment]
This might work 
//[...nextauth].ts
`callbacks: {
    async jwt({ token, user, account, profile }) {
      if (user) {
        token.access_token = user.access_token;
      }
      return token
    },
    async session({ session, token, user }) {
      session.user.access_token = token
      return session
    }  
  },`
//  /types/next-auth.d.s
`declare module "next-auth" {
  /**
   * Returned by `useSession`, `getSession` and received as a prop on the `SessionProvider` React Context
   */
  interface Session {
    user:{
      access_token: any & DefaultSession["user"];
    }
  }

  interface User {
      access_token: any
     & DefaultSession["user"];
  }
}

declare module "next-auth/jwt" {
  /** Returned by the `jwt` callback and `getToken`, when using JWT sessions */
  interface JWT {
    /** OpenID ID Token */
    access_token?: string;
  }
}`

Depending on how access token passed you can call it in the in component
`const { data } = useSession();
  console.log(data?.user?.access_token?.access_token)`

**Comment by ranbena** [comment]
This is what worked for me:

```ts
// next-auth.d.ts
import { DefaultSession } from 'next-auth';

declare module 'next-auth' {
  interface Session extends DefaultSession {
    accessToken: string;
    refreshToken: string;
  }
}
```

**Comment by IsmailKemmoune** [comment]
> This is what worked for me:
> 
> ```ts
> // next-auth.d.ts
> import { DefaultSession } from 'next-auth';
> 
> declare module 'next-auth' {
>   interface Session extends DefaultSession {
>     accessToken: string;
>     refreshToken: string;
>   }
> }
> ```

where should I use this next?

**Comment by ranbena** [comment]
> where should I use this next?

The file can be named `next-auth.d.ts` and you can put it anywhere in the project.
I put it in `src/lib/types/next-auth.d.ts`.

**Comment by Rob--** [comment]
This is the type of `Session`:
https://github.com/nextauthjs/next-auth/blob/7770f2ba4ff188a74ff96de7904b7ea62ebba07e/packages/core/src/types.ts#L248-L254

Why do their own code examples[1][2] not conform to the type they define?
```typescript
async session({ session, token }) {
    if (token?.accessToken) {
        session.accessToken = token.accessToken
    }
    return session
},
```

[1] https://github.com/nextauthjs/next-auth-example/blob/main/auth.ts#L111-L115
[2] https://next-auth.js.org/getting-started/example
