### ISSUE TITLE
Spotify login button icon URLs give 404

### ISSUE THREAD

**Issue by oshibka404** [nextauthjs/next-auth#6924]
### Provider type

Spotify

### Environment

Doesn't matter. Same on localhost and vercel deployment

### Reproduction URL

https://music-discovery-lime.vercel.app/api/auth/signin?callbackUrl=https%3A%2F%2Fmusic-discovery-lime.vercel.app%2F

### Describe the issue

Spotify login button has a broken icon.

Both `https://raw.githubusercontent.com/nextauthjs/next-auth/main/packages/next-auth/provider-logos/spotify.svg` and `https://raw.githubusercontent.com/nextauthjs/next-auth/main/packages/next-auth/provider-logos/spotify.svg` (normal and dark) return 404.

<img width="331" alt="Screenshot 2023-03-12 at 01 22 09" src="https://user-images.githubusercontent.com/1549756/224517459-27fce83d-119e-4dc5-b717-d71e35802e6b.png">

### How to reproduce

Open login page for any service offering login using Spotify.
For instance, https://music-discovery-lime.vercel.app/api/auth/signin?callbackUrl=https%3A%2F%2Fmusic-discovery-lime.vercel.app%2F

### Expected behavior

Icon is displayed

**Comment by balazsorban44** [comment]
see #6313 or provide a reproduction.

**Comment by oshibka404** [comment]
Thank you. Yes, upgrade resolved the problem.
