### ISSUE TITLE
How to use `getCsrfToken()` method in SvelteKit?

### ISSUE THREAD

**Issue by aakash14goplani** [nextauthjs/next-auth#6926]
### Question 💬

How do I use [`getCsrfToken()`](https://next-auth.js.org/getting-started/client#getcsrftoken) in SvelteKit (client side)?

As of now approach I am following is
```
const tokenCall = await fetch('/auth/csrf');
const csrfTokenResponse = await tokenCall.json();
const csrfToken = csrfTokenResponse.csrfToken;

// now use csrfToken...
```

### How to reproduce ☕️

Use [`getCsrfToken()`](https://next-auth.js.org/getting-started/client#getcsrftoken) in SvelteKit (client side) and you will see error that no such method exists!

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Hi, we are working kn making this obsolete with SvelteKit Auth, as SvelteKit has builtin CSRF protection. Follow the PR #6874
