### ISSUE TITLE
NewUser redirect does not work in production

### ISSUE THREAD

**Issue by Taosit** [nextauthjs/next-auth#6931]
### Overview
I'm trying to redirect a user to /account when they sign in for the first time. In the documentation, it says this can be achieved by setting newUser to the redirect url under pages in [...nextAuth].js. It works fine on localhost (both in dev mode and the build version), but when deployed to Vercel, instead of replacing the original url, the redirect url is appended to the original url, and it ends up looking something like /signin?callbackUrl=...account%3FcallbackUrl%3D...blogs.

Despite the failure to redirect, the user is still successfully signed in. There are no issues on subsequent signins.

### Versions
"next": "13.2.3",
"next-auth": "^4.20.1",
"react": "18.2.0",

Specifically, I'm using the /app directory for pages. However, for api routes, I'm still using /pages/api.

### Providers
Google and email. Both work on localhost but fail on Vercel.

### Sign In Config
`{
    redirect: true,
    callbackUrl: searchParams?.get("callbackUrl") || "/blogs",
  }`

### Middleware
/account and /profile are protected (not sure if it's relevant)

### How to reproduce ☕️

https://blog-9owjtb2og-taosit.vercel.app/
Click on the avatar at the top-right corner to go to the sign in page. Once the redirect fails, you can navigate back to /blogs (by typing the url) and see your username and avatar (or User if you used email to sign in)

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by ra8ga** [comment]
> ### Question 💬
> ### Overview
> I'm trying to redirect a user to /account when they sign in for the first time. In the documentation, it says this can be achieved by setting newUser to the redirect url under pages in [...nextAuth].js. It works fine on localhost (both in dev mode and the build version), but when deployed to Vercel, instead of replacing the original url, the redirect url is appended to the original url, and it ends up looking something like /signin?callbackUrl=...account%3FcallbackUrl%3D...blogs.
> 
> Despite the failure to redirect, the user is still successfully signed in. There are no issues on subsequent signins.
> 
> ### Versions
> "next": "13.2.3", "next-auth": "^4.20.1", "react": "18.2.0",
> 
> Specifically, I'm using the /app directory for pages. However, for api routes, I'm still using /pages/api.
> 
> ### Providers
> Google and email. Both work on localhost but fail on Vercel.
> 
> ### Sign In Config
> `{ redirect: true, callbackUrl: searchParams?.get("callbackUrl") || "/blogs", }`
> 
> ### Middleware
> /account and /profile are protected (not sure if it's relevant)
> 
> ### How to reproduce ☕️
> https://blog-9owjtb2og-taosit.vercel.app/ Click on the avatar at the top-right corner to go to the sign in page. Once the redirect fails, you can navigate back to /blogs (by typing the url) and see your username and avatar (or User if you used email to sign in)
> 
> ### Contributing 🙌🏽
> No, I am afraid I cannot help regarding this

Hey, did you managed to solve the problem?

**Comment by balazsorban44** [comment]
Closing as no reproduction was added. If you have one, please open a new issue.
