### ISSUE TITLE
Text content inside feature->description->li overlaps it's  neighbour.

### ISSUE THREAD

**Issue by azeek21** [nextauthjs/next-auth#6933]
### What is the improvement or update you wish to see?

at https://authjs.dev/  li tags inside `class="section-features features_cAfv"` containing text content overlap its neighbor. 

one of them: https://github.com/nextauthjs/next-auth/blob/7ba986b01e3cf019048054e9cc891eb979f61705/docs/src/pages/index.js#L23

screenshot: [Imgur link](https://imgur.com/ADkJrkx.png). 

Cause: Must be caused by https://github.com/nextauthjs/next-auth/blob/7ba986b01e3cf019048054e9cc891eb979f61705/docs/src/pages/index.module.css#L93

Fix: changing `white-space: nowrap;` to `white-space: break-spaces;` or `white-space: pre-line;` will fix it. Totally removing `white-space` property also doesn't break anything. 

### Is there any context that might help us understand?

I think, I explained everything above clearly. Just in case: setting `white-space: nowrap;` disables text wrapping which makes text content inside li tags overflow.

 Here's a better image: [imgur link](https://imgur.com/kB6291V.png). as you can see text content definitely not respecting li tag's borders.
 
 Fixed image: [imgur link](https://imgur.com/TySt6Af.png) I added `white-space: break-space;` now text gets wrapped in case of overflow-y. 

### Does the docs page already exist? Please link to it.

https://authjs.dev/

**Comment by azeek21** [comment]
is there any change for me to create a PR fixing the issue ? :pleading_face:

**Comment by balazsorban44** [comment]
Can you open a PR for tbis? 🙏
