### ISSUE TITLE
announcementBar announcement close button invisible. 

### ISSUE THREAD

**Issue by azeek21** [nextauthjs/next-auth#6935]
### What is the improvement or update you wish to see?

The button to close the announcement is being invisible as background color of announcementBar and color of close button are the same. 

Screenshot: [imgur link](https://imgur.com/a/QxcP8vl) 

Not sure if this is intended or not. Color for close button comes from Docusaurus and I think can be overwritten by custom global css. 

### Is there any context that might help us understand?

 [imgur link](https://imgur.com/a/QxcP8vl) 

### Does the docs page already exist? Please link to it.

https://authjs.dev/

**Comment by azeek21** [comment]
I actually have the fix ready. Can't decide on style. What color do you want close the announcement button to be ? I would recommend red.

**Comment by ndom91** [comment]
Yeah if you have a PR you can put up, we'd be happy to take a look.

I think `color: white` would suffice here :+1: 

Something like this:
![image](https://user-images.githubusercontent.com/7415984/226206199-8ab0ffe7-56a4-45f9-9221-a1090d64d3ba.png)
