### ISSUE TITLE
The step by step guide link with costume backend not working

### ISSUE THREAD

**Issue by kifah1989** [nextauthjs/next-auth#6947]
### What is the improvement or update you wish to see?

The documentation for using ayth.js with a costume backend has a broken link.
Guide link: https://arunoda.me/blog/add-auth-support-to-a-next-js-app-with-a-custom-backend
Step by step guide broken link: https://getstarted.sh/bulletproof-next/add-social-authentication.

### Is there any context that might help us understand?

Might be helpful if there is a section in the guide that explains how to implement auth.js in node.js/expressjs server.

**Comment by balazsorban44** [comment]
That blog is not authored by us.

The core Auth.js library is currently intended for framework authors or non-beginners.

See the docs here https://authjs.dev/reference/core#usage

The core expects a Web standard Request and returns a Web standard Response.

You'll need create the "glue" for Node.js/Express handlers for now, transforming an `IncomingMessage` to `Request` and the `Response` to `ServerResponse`.
