### ISSUE TITLE
Auth0 callback url

### ISSUE THREAD

**Issue by waptik** [nextauthjs/next-auth#695]
**Your question**
What should be the callbackUrl to set?

**What are you trying to do**
I'm trying to use nextauth with auth0 as a provider. I followed the [guide](https://next-auth.js.org/providers/auth0) as suggested and set callback url as `http://localhost:3000/api/auth/callback` in my application settings at auth0 because i'm testing it locally.
But when i click on the login button and select auth0, I'm being redirected to their error page saying `Callback URL mismatch`.
The docs doesn't make mention of how to setcallbacks.
A [snapshot](https://web.archive.org/web/20200910061218/https://next-auth.js.org/providers/auth0) of it.
Any help with that?

Edit: I finally fixed my issues after changing callbackUrl  several times. So the correct callbackUrl is `http://localhost:3000/api/auth/callback/auth0`. I just needed to append `/auth0` at the end.

* [x] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
> Edit: I finally fixed my issues after changing callbackUrl several times. So the correct callbackUrl is http://localhost:3000/api/auth/callback/auth0. I just needed to append /auth0 at the end.

Thanks for coming back and updating with the resolution, always apprecaited!

**Comment by spsaucier-bakkt** [comment]
@waptik How were you able to set localhost as your callback URL? Auth0 appears to block that domain in the "Application Login URI" field.

**Comment by waptik** [comment]
> @waptik How were you able to set localhost as your callback URL? Auth0 appears to block that domain in the "Application Login URI" field.
> 
> **EDIT** : I was using the wrong field -- it should instead be `Allowed Callback URLs`

So it's working now?

**Comment by spsaucier-bakkt** [comment]
Yes, it is, thanks.

**Comment by waptik** [comment]
No problem. I'm glad it works

**Comment by ChrisCates** [comment]
@iaincollins, could you add this to the documentation on the npm module `README.md`.

Would be handy to newcomers.
Thank you.

**Comment by scarstens** [comment]
Just echoing that this would be useful on the Auth0 provider documentation as its not noted anywhere right now.
