### ISSUE TITLE
UPDATE THE SESSION FROM THE CLIENT SIDE

### ISSUE THREAD

**Issue by Danztee** [nextauthjs/next-auth#6952]
### Description 📓

I am working on a project, in the settings page i can update the name, username e.t.c after updating, it updates in the database but the session won't change until i log out and log in back then  the new data from the database will now be updated. we need a way to update the session from the client when updates like this happen. the database is sending me the updated data after successful update. so we need a way to pass the updated data to the session from the client so that we did not need to log out and login again for the changes to be made

### How to reproduce ☕️

no one for now

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by magicspon** [comment]
it's a bit of hack, but this seems to do the job:

```
function useReloadSession() {
  const reloadSession = () => {
    const event = new Event('visibilitychange')
    document.dispatchEvent(event)
  }

  return reloadSession
}
```

then once you've updated your user data:

```
const reloadSession = useReloadSession()

... 
onSuccess = () => reloadSession()

```

**Comment by Danztee** [comment]
> it's a bit of hack, but this seems to do the job:
> 
> ```
> function useReloadSession() {
>   const reloadSession = () => {
>     const event = new Event('visibilitychange')
>     document.dispatchEvent(event)
>   }
> 
>   return reloadSession
> }
> ```
> 
> then once you've updated your user data:
> 
> ```
> const reloadSession = useReloadSession()
> 
> ... 
> onSuccess = () => reloadSession()
> ```

where will i put all these code? which file?

**Comment by magicspon** [comment]
ignore the code...

after you update your username/name/whatever

call this:

```
const event = new Event('visibilitychange')
document.dispatchEvent(event)
```

**Comment by Danztee** [comment]
my problem is dat how can i pass the newly updated user data to the session. if i log out and log in back, it gets the newly updated data from d backend that is normal but how can i pass the new data to the session without logging out and logging in...

that code u provided just reload the session not update d session

_____
THIS IS MY ISSUE
i updated my username in d frontend and it has been updated in the DB and the API sent a response with the newly updated data. so i want to pass the new updated data to the session. of course, if i log out and log in, it'll get the new data. but how can i pass the new data to the session without logging out and logging in after updating in the frontend

**Comment by magicspon** [comment]
this is where i got the code snippet from:
https://github.com/nextauthjs/next-auth/issues/596#issuecomment-943453568

**Comment by balazsorban44** [comment]
See the related discussion here: https://github.com/nextauthjs/next-auth/discussions/3941 Might have some good pointers.

Unfortunately, the discussion got flooded by unrelated comments and I stopped iterating on the feature, but we could revisit and add something in the future.

It would be nice to have a built-in solution, but updating the session makes little sense for JWT sessions for example, so we might need to think about the right API.
