### ISSUE TITLE
OpenID Connect jwt claim 'azp' is mandatory not optional

### ISSUE THREAD

**Issue by matf3en** [nextauthjs/next-auth#6955]
### Environment

System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 451.27 MB / 7.75 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.69)
    Internet Explorer: 11.0.19041.1566

### Reproduction URL

private

### Describe the issue

A provider (Oracle Netsuite) is returning a jwt that does not contain the 'azp' claim. 

Reading the RFCs etc, the azp claim is *optional*.

Next-Auth however checks for the presence of the azp claim and fails if none is found.

The error produced is 

`https://next-auth.js.org/errors#oauth_callback_error missing required JWT property azp {
  error: RPError: missing required JWT property azp`

So this bug is : that Next-Auth (or OpenId-Client) makes an optional claim into a required claim, which it should not.

### How to reproduce

Connect via a standard OAuth2 OIDC flow with Oracle Netsuite from an external app. Observe the error

https://next-auth.js.org/errors#oauth_callback_error missing required JWT property azp {
  error: RPError: missing required JWT property azp

### Expected behavior

If the azp claim was optional not required, this error would not occur.

**Comment by balazsorban44** [comment]
Hard to say much without a reproduction or any more information. Usually `azp` defaults to `client_id`, but in your case the AP might be sending multiple `aud` values, causing the check to be activated for a valid `azp` value. See the code for the underlying library

https://github.com/panva/node-openid-client/blob/ae1222c60541a87c650ce9bff8cc3ab5af9b413d/lib/client.js#L968
