### ISSUE TITLE
Access code from callback uri

### ISSUE THREAD

**Issue by CavalcanteLeo** [nextauthjs/next-auth#6957]
### What is the improvement or update you wish to see?

After I succeed login, the auth0 returns me a code on the `redirect_uri`, I need to access that code

In my example, my callback is: 
```
http://localhost:3000/api/auth/callback/auth0?code=XXXXXXXXXXX&state=ZZZZZZZZZZ 
```

I need to store that code in the user session, and retrieve that sometimes

<img width="1552" alt="Screenshot 2023-03-15 at 11 53 07" src="https://user-images.githubusercontent.com/1735944/225349126-72a3eddc-59c1-43b7-9eda-597fd2189fe7.png">

I can't find it on documentation

**Comment by balazsorban44** [comment]
That code is part of the OAuth flow and is going to be used to exchange it for an access_token. You don't actually need to save it in the session, we handle the whole exchange for you. You can however save the access_token via the jwt callback.

https://next-auth.js.org/configuration/callbacks#jwt-callback

**Comment by CavalcanteLeo** [comment]
Hey @balazsorban44, 
I need to forward it to an internal API of my application

**Comment by wowczarczyk** [comment]
Hey @CavalcanteLeo. Have you found a way to access this redirect query param or any other param sent in the callback URL?

**Comment by CavalcanteLeo** [comment]
Couldn't find a way, I dropped this library
