### ISSUE TITLE
Update session with changed data

### ISSUE THREAD

**Issue by andrewscofield** [nextauthjs/next-auth#6959]
### Question 💬

If my user updates their name or profile image, how can I for an update to the session? I'm using JWT and credentials provider and it seems to be updating just fine, its just that I don't see the changes until I refresh the page. This is with using `<SessionProvider>` and `const { data, status } = useSession()` and I guess I'm wanting to somehow trigger `useSession` again to get the latest data, the way it does when you first load the page. 

### How to reproduce ☕️

I don't have a link for this

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
See https://github.com/nextauthjs/next-auth/issues/6952#issuecomment-1471751706
