### ISSUE TITLE
Collections not being created on MongoDB hosted on Atlas

### ISSUE THREAD

**Issue by clowNay** [nextauthjs/next-auth#696]
I see absolutely no data or collections created when using Credentials as the provider. I've tried with the default credentials as described in the documentation.

The API is working with the same connection, without any issues.
Below is my options.

```
const options = {
    providers: [
        Providers.Credentials({
            // The name to display on the sign in form (e.g. 'Sign in with...')
            name: 'Credentials',
            // The credentials is used to generate a suitable form on the sign in page.
            // You can specify whatever fields you are expecting to be submitted.
            // e.g. domain, username, password, 2FA token, etc.
            credentials: {
                email: { label: "E-mail", type: "email", placeholder: "example@example.com" },
                password: {  label: "Password", type: "password" }
            },
            authorize: async credentials => {
                const user = credentials => {
                    // You need to provide your own logic here that takes the credentials
                    // submitted and returns either a object representing a user or value
                    // that is false/null if the credentials are invalid.
                    // e.g. return { id: 1, name: 'J Smith', email: 'jsmith@example.com' }
                    return null
                }

                if (user) {
                    // Any user object returned here will be saved in the JSON Web Token
                    return Promise.resolve(user)
                } else {
                    return Promise.resolve(null)
                }
            }
        })
    ],
    jwt: {
        secret: process.env.JWT_SECRET,
    },
    session: {
        jwt: true
    },
    // A database is optional, but required to persist accounts in a database
    database: {
        type: 'mongodb',
        useNewUrlParser: true,
        url: process.env.DATABASE_URL
    },
    debug: true
}
```

DATABASE_URL
```
DATABASE_URL=mongodb+srv://admin:<password>@cluster0.gvdh7.mongodb.net/<database>?synchronize=true&retryWrites=true&w=majority
```

Setting `debug: true`, doesn't give me any information on why nothing is being stored.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
Ah! Sorry if this is not clear in the documentation. The **Credentials Provider** is an exception to the other providers, in that with the Credentials Provider users are not persisted to a database. The Credentials Provider is intended for compatibility for legacy services (and/or internal/corporate authentication flows) only.

It is intended to support cases only where there is an existing database of usernames and passwords  (or other credentials) already stored somewhere (e.g. LDAP, Active Directory, Oracle, etc).

**Comment by clowNay** [comment]
I see! Then it makes a lot more sense to me now.
I think the documentation could take a bit more explanation, when it differs that much.

Thank you for clarifying.
By the way keep up the good work 👍
