### ISSUE TITLE
Passwordless Auth0 flow throws missing cookie error

### ISSUE THREAD

**Issue by jonlambert** [nextauthjs/next-auth#6963]
### Provider type

Auth0

### Environment

  System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 155.03 MB / 16.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.14.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.3.1 - /usr/local/bin/npm
    Watchman: 2023.01.23.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 110.1.48.171
    Chrome: 111.0.5563.64
    Firefox: 109.0.1
    Safari: 16.1

dependencies:
next 13.1.6
next-auth 4.20.1
react 18.2.0

### Reproduction URL

N/A - Unable to share provider

### Describe the issue

I have `next-auth` configured in my application like so:

```ts
export default NextAuth({
  providers: [
    Auth0({
      clientId: AUTH0_CLIENT_ID,
      clientSecret: AUTH0_CLIENT_SECRET,
      issuer: AUTH0_ISSUER,
    }),
  ],

  callbacks: {
    async jwt({ token, account }) {
      if (account?.id_token) {
        token.idToken = account.id_token;
      }
      return token;
    },

    async session({ session, token }) {
      session.idToken = token.idToken as string;
      return session;
    },
  },
});

```

The standard flow works fine - I can login via the redirect flow with Auth0 using `signIn('auth0')`.

However, if I trigger a passwordless email to be sent via Auth0's API: 

```http
POST https://example.eu.auth0.com/passwordless/start

{
  "client_id": "<redacted>",
  "client_secret": "<redacted>",
  "connection": "email",
  "email": "myemail@example.org",
  "send": "link",
  "authParams": {
    "redirect_uri": "http://localhost:3030/api/auth/callback/auth0"
  }
}

```

The link in the email correctly redirects to Auth0, then back to the app. But I receive the following error: 

```
{
  error: {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'auth0',
  message: 'State cookie was missing.'
}
```

I believe the session is being correctly setup with Auth0 - the issue seems to be in the way that token is received at the callback stage.

### How to reproduce

* Setup and configure a basic, Auth0 tenant, as per provider/next-auth instructions
* Setup NextAuth per the config listed above
* Follow the [Auth0 guide on configuring a passwordless login flow](https://auth0.com/docs/authenticate/passwordless/implement-login/embedded-login/webapps)
* [Trigger](https://auth0.com/docs/authenticate/passwordless/implement-login/embedded-login/webapps) the email request via API
* Observe email arriving, and magic link not working

### Expected behavior

The session should be created within Next Auth, in the same way as the standard login redirect flow with Auth0.

**Comment by balazsorban44** [comment]
The Auth0 provider is configured as a conforman OIDC provider by default, using `state` for CSRF protection. Since you are triggering a login outside NextAuth.js' control, the state CSRF protection is going to be missing.

You *can* configure the provider with `checks: ["none"]`, but make sure you only do so when you detect that you are triggering a login via the passwordless flow to not leave yourself vulnerable.

Maybe a shared secret and advanced initialization to conditionally set `checks` https://next-auth.js.org/configuration/initialization#advanced-initialization
