### ISSUE TITLE
How to use with Steam openid

### ISSUE THREAD

**Issue by SunriseM** [nextauthjs/next-auth#697]
**Your question**
Steam uses OpenID 2.0 (older than OpenID Connect) and apparently is not supported by this library, so is there any way to make it work? If it's there no way to do it, Can I update the next-auth session if I authorize the user outside next-auth?

**What are you trying to do**
I want to let clients sign in with their steam account.

**Comment by iaincollins** [comment]
[At a glace of the docs](https://partner.steamgames.com/doc/webapi_overview/oauth) yes it should be possible to add Steam as a custom provider, even if it doesn't support OpenID! It would be great to add as a built-in provider.

It seems it returns ID, name and avatar in a fairly conventional way, but I think possibly not email - which isn't a problem and just means they won't be able to use email as a fallback to sign in.

There isn't a built in way to link them without doing this, though if you find it easier, you could create your own database table to store this info against the Users ID, and create a custom API endpoint that accesses the Users session (and look up the User ID from the session secure) and then returns information from that table, using the User ID as a key.

**Comment by Maykin-99** [comment]
I have the same issue and unfortunately this library does not support OpenID 2.0.
The docs, @iaincollins refers to, is exclusively for Steamworks Partners.
Those who aren't part of the Steamworks club need to use the [Steam Web API and OpenID 2.0](https://steamcommunity.com/dev).

I forked this library, added a new `type: "openid"` and added a Steam Provider. It works for my use case. I'm not sure if the maintainers of next-auth are interested in supporting a legacy protocol, though.
