### ISSUE TITLE
Contributing -> pnpm downloading various typescript versions.

### ISSUE THREAD

**Issue by azeek21** [nextauthjs/next-auth#6972]
### Question 💬

I was following contribution guide and noticed pnpm downloading a bunch of different typescript versions. I am not really experienced with pnpm but, is it normal ?

Screenshot: [Imgur link](https://imgur.com/01iTzTv)

### How to reproduce ☕️

Follow contribution guides.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
There are quite a few instances of `typescript` references: https://github.com/search?q=repo%3Anextauthjs%2Fnext-auth+%22typescript%22+path%3A**%2F**%2F*package.json&type=code

Ideally, we could make them all the same.
