### ISSUE TITLE
annoucementBar doesn't respect color scheme. 

### ISSUE THREAD

**Issue by azeek21** [nextauthjs/next-auth#6976]
### What is the improvement or update you wish to see?

When page color scheme changed, top announcementBar stays in dark theme.

Screenshot: [imgur link](https://imgur.com/027lySA.png) .

Comes from: 
https://github.com/nextauthjs/next-auth/blob/80c1f375b86d40d3650e4d3120a9aaddd869f230/docs/docusaurus.config.js#L128
and 
https://github.com/nextauthjs/next-auth/blob/80c1f375b86d40d3650e4d3120a9aaddd869f230/docs/docusaurus.config.js#L129

I am willing to fix :hand: 

### Is there any context that might help us understand?

play with color theme of [docs website](https://authjs.dev/) and watch announcemetBar color not changing.

**Comment by balazsorban44** [comment]
Thanks, but this is kind of intentional, a stylistic choice.

**Comment by azeek21** [comment]
Looks like [https://next-auth.js.org/](next-auth.js.org/) if affected.
Now I am wondering maybe this is the default expected behavior.

**Comment by azeek21** [comment]
> Thanks, but this is kind of intentional, a stylistic choice.

yeah, I was wondering so. Thanks.
