### ISSUE TITLE
How to link user data from second provider to the active user?

### ISSUE THREAD

**Issue by ranlix** [nextauthjs/next-auth#7006]
### Question 💬

I create a project with nextjs + nextauth + prisma.
I need user sign in with one custom provider, which contains uid from 3rf party app, and then this user is active and have a session now.
And then the user should signIn with discord provider, and then merge the discord user data to the active user?

### How to reproduce ☕️

```js
import NextAuth, { TokenSet } from "next-auth";
import prisma from "@/lib/prisma";
import { Provider } from "next-auth/providers";
import DiscordProvider from "next-auth/providers/discord";

import { MyTokens } from "types/auth";
import { DISCORD_OAUTH2_SCOPES } from "constants/auth/discord";

const myOAuthProvider: Provider = {
  id: 'my',
  name: 'MyOauth',
  type: 'oauth',
  checks: ['state'],
  authorization: {
    url: process.env.MY_OAUTH_AUTHORIZATION_URL || '',
    params: { scope: 'user:read' },
  },
  token: {
    url: process.env.MY_OAUTH_TOKEN_URL || '',
  },
  userinfo: {
    url: process.env.MY_OAUTH_USERINFO_URL || '',
  },
  profile: async (profile, tokens: MyTokens) => {
    const { user } = profile || {}
    let existed = await prisma.user.findUnique({
      where: {
        uid: user.userId,
      },
    });
    if (!existed) {
      existed = await prisma.user.create({
        data: {
          uid: user.userId,
        }
      })
    }
    const {
      accessToken,
      accessTokenExpiresAt,
      refreshToken,
      refreshTokenExpiresAt,
    } = tokens as Record<string, string>
    await prisma.user.update({
      where: {
        id: existed.id
      },
      data: {
        myToken: {
          upsert: {
            update: {
              accessToken,
              accessTokenExpiresAt,
              refreshToken,
              refreshTokenExpiresAt,
            },
            create: {
              accessToken,
              accessTokenExpiresAt,
              refreshToken,
              refreshTokenExpiresAt,
            }
          }
        }
      }
    })
    return {
      id: profile.user.userId,
      name: profile.user.name,
      email: "",
      image: profile.user.image,
    };
  },
  clientId: process.env.MY_OAUTH_CLIENT_ID || '',
  clientSecret: process.env.MY_OAUTH_CLIENT_SECRET || '',
}

const scope = DISCORD_OAUTH2_SCOPES.join(',')
const discordProvider: Provider = DiscordProvider({
  authorization: { params: { scope } },
  token: {
    url: "https://discord.com/api/oauth2/token",
  },
  profile: async (profile, tokens: TokenSet) => {
    return profile
  },
  clientId: process.env.DISCORD_CLIENT_ID || '',
  clientSecret: process.env.DISCORD_CLIENT_SECRET || '',
})

export default NextAuth({
  providers: [
    myOAuthProvider,
    discordProvider,
  ],
  session: { strategy: "jwt" },
});

```

1. sign in with `myOAuthProvider`;
2. sign in with `discord`;
3. get discord user data and merge it into active current user which is signed in with `myOAuthProvider`

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Users are automatically linked if you are logged in with one of the providers and call `signIn("other provider")`.

We don't link accounts if the user is not logged in with either of the providers, for security reasons. If you trust your providers, you can check out https://next-auth.js.org/configuration/providers/oauth#allowdangerousemailaccountlinking-option

**Comment by cguagenti** [comment]
> Users are automatically linked if you are logged in with one of the providers and call `signIn("other provider")`.
> 
> We don't link accounts if the user is not logged in with either of the providers, for security reasons. If you trust your providers, you can check out https://next-auth.js.org/configuration/providers/oauth#allowdangerousemailaccountlinking-option

This solved the problem for me.

**Comment by ranlix** [comment]
> 



> Users are automatically linked if you are logged in with one of the providers and call `signIn("other provider")`.
> 
> We don't link accounts if the user is not logged in with either of the providers, for security reasons. If you trust your providers, you can check out https://next-auth.js.org/configuration/providers/oauth#allowdangerousemailaccountlinking-option

I see, but what about two providers in this case:
1. one provider return profile has no email field, I use another uid as an unique key;
2. sign in with discord provider again.

So I don't think enable `allowdangerousemailaccountlinking-option` could auto link two providers since there is only one provider returns email.

Here is my current solution:
1. Sign in with custom provider, to get or create User from prisma and mysql;
2. override discordProvider's callback api, just like add a file named `/api/auth/callback/discord.ts`;
3. when sign in with discord while custom provider session is active, I can get session in `discord.ts` by `const session = await getToken({ req })`, and get `code` from `req.query`, exchange `access_token` by `code` and get user profile by `access_token`;
4. after that, I can link discord userId to the active user via prisma.

**Comment by p2pskins** [comment]
> > 
> 
> > Users are automatically linked if you are logged in with one of the providers and call `signIn("other provider")`.
> > We don't link accounts if the user is not logged in with either of the providers, for security reasons. If you trust your providers, you can check out https://next-auth.js.org/configuration/providers/oauth#allowdangerousemailaccountlinking-option
> 
> I see, but what about two providers in this case:
> 
> 1. one provider return profile has no email field, I use another uid as an unique key;
> 2. sign in with discord provider again.
> 
> So I don't think enable `allowdangerousemailaccountlinking-option` could auto link two providers since there is only one provider returns email.
> 
> Here is my current solution:
> 
> 1. Sign in with custom provider, to get or create User from prisma and mysql;
> 2. override discordProvider's callback api, just like add a file named `/api/auth/callback/discord.ts`;
> 3. when sign in with discord while custom provider session is active, I can get session in `discord.ts` by `const session = await getToken({ req })`, and get `code` from `req.query`, exchange `access_token` by `code` and get user profile by `access_token`;
> 4. after that, I can link discord userId to the active user via prisma.

Have exactly the same issue. Do you still use your current solution?
