### ISSUE TITLE
MongoDB Adapter: Unsupported BSON version, bson types must be from bson 5.0 or later

### ISSUE THREAD

**Issue by yahavf6** [nextauthjs/next-auth#7022]
### Adapter type

@next-auth/mongodb-adapter

### Environment

 System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 1.80 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/WebstormProjects/intail-mono/node_modules/.bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
    Watchman: 2023.03.13.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.3

### Reproduction URL

http://localhost:3000

### Describe the issue

I have this issue when trying to use the adapter:

```
[next-auth][error][adapter_error_createUser] 
https://next-auth.js.org/errors#adapter_error_createuser Unsupported BSON version, bson types must be from bson 5.0 or later {
  message: 'Unsupported BSON version, bson types must be from bson 5.0 or later',
  stack: 'BSONVersionError: Unsupported BSON version, bson types must be from bson 5.0 or later\n' +
```

### How to reproduce

Just copy and paste the example from the docs

### Expected behavior

To work

**Comment by yahavf6** [comment]
I've solved this by downgrading MongoDB to the legacy version.
I think it is important to mention that version 5 is not yet supported.

**Comment by dlamprey** [comment]
+1 with emphasis! I hate having to downgrade just to accommodate one package! 😠 please fix!

![image](https://user-images.githubusercontent.com/48389685/232466082-1739f4ec-1950-417c-88a5-10074dda8f6a.png)

**Comment by ryx** [comment]
I have the same error with the latest combination of mongoose, next-auth, next-auth/email-provder, and mongodb-adapter:

```
[next-auth][error][adapter_error_createVerificationToken]
https://next-auth.js.org/errors#adapter_error_createverificationtoken Unsupported BSON version, bson types must be from bson 6.x.x {
  message: 'Unsupported BSON version, bson types must be from bson 6.x.x',
```

It feels somewhat unsatisfying to downgrade to an old mongodb version to have this problem fixed, so maybe the adapter could be upgraded to include a newer mongodb version? Thanks in advance
