### ISSUE TITLE
Allow the session callback to return null

### ISSUE THREAD

**Issue by KieronWiltshire** [nextauthjs/next-auth#7035]
### Description 📓

I am using the credentials provider to authenticate a user's login to an API, the API returns a JWT itself which I am just storing inside the JWT generated by Next-Auth itself. Then when I retrieve the session, I am just making calls with that JWT. However, the API JWT could expire and so the next-auth JWT would also technically be invalid. 

Due to the lack of a server-side sign out mechanism, I am using an approach like this:
```typescript
         async session({session, user, token}) {
            try {
                session.isAuthenticated = false;

                if (token) {
                    const {accessToken} = token;
                    const user = await getUser({accessToken});

                    if (user) {
                        session.user = user;
                        session.auth = {accessToken};
                        session.isAuthenticated = true;
                    }
                }
            } catch (error) {
                // Unauthenticated
            }

            return session;
        },
        async jwt({token, user, account, profile, isNewUser}) {
            const {id, ...rest} = user || {};
            return {...token, ...rest};
        }
```

Then in my app directory (server component) I am using something like this:
```typescript
let session = await getServerSession(authOptions);
session = (session && session.isAuthenticated) ? session : null
```

It would be much easier if I could do this check in the session callback itself as shown below:
```typescript
        async session({session, user, token}) {
            try {
                session.isAuthenticated = false;

                if (token) {
                    const {accessToken} = token;
                    const user = await getUser({accessToken});

                    if (user) {
                        session.user = user;
                        session.auth = {accessToken};
                        session.isAuthenticated = true;
                    }
                }
            } catch (error) {
                // Unauthenticated
            }

            return (session && session.isAuthenticated) ? session : null; // this line here
        },
```

I believe there are valid reasons why you may want to return null in the session callback. I know what I am presenting is a very specific use case, but I don't see why this shouldn't be allowed.

### How to reproduce ☕️

No reproduction needed.

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by KieronWiltshire** [comment]
It seems removing the try/catch in my session code and throwing an error has the same effect, it would still be nice to allow something like this though.

**Comment by balazsorban44** [comment]
I actually like the idea of invalidating the session by retuning `null`

The only caveat is that the `/api/auth/session` currently always return an object (empty one if signed out), so it would be a bit weird/might break some cases in user land 

In `@auth/core` though we could still change this. 👍

**Comment by daviddecorso** [comment]
This would be a really nice feature I think.

**Comment by dever23b** [comment]
Jumping on the bandwagon here.  I haven't been able to figure out how to invalidate an existing session. 

In my case, I'm using the Credentials Provider against an existing API I've already developed.  The API returns an authorization response that, if successful, contains access and refresh tokens along with the user object.  I'm running into an issue where the timing is off between when the tokens expire and when NextAuth's JWT/sessions expire.  Despite all the code I've written that can identify this gap, I can't find any way to command NextAuth to invalidate the session.

It seems like the best place to invalidate the session would be in the session callback.  It would be consistent with the behavior of the signIn callback, which allows us to abort an otherwise successful authentication.

**Comment by dever23b** [comment]
This isn't a solution, but I might have a viable workaround.  It's ugly but, pending further testing, I think it works.

Since I can't find a way to convince NextAuth to terminate the session, I've added a flag to the `Session` interface indicating to terminate the session.  When the front end receives it, it triggers a signout.

Example:
```typescript
// options.ts
const authOptions: NextAuthOptions = {
  //...
  callbacks: {
    session: async ({ session, token }) => {
      const state = authService.getState();

      if (state.isValid) {
        session.accessToken = state.accessToken;
        session.user = state.user;
      }

      if (state.mustReauthenticate) {
        session.terminate = true;
        session.expires = new Date().toDateString();
      }

      return session;
    },
  }
}
```

```typescript
// next-auth.d.ts
interface Session {
  user?: User;
  terminate?: boolean;
}
```

```typescript
// app/page.tsx
const Auth: React.FC = () => {
  const { data: session } = useSession();

  useEffect(() => {
    if (session?.terminate === true) {
      signOut();
    }
  }, [session]);

  return (
    <div>...</div>
  );
};

**Comment by KieronWiltshire** [comment]
For anyone wondering how I solved this, I just wrap my actual session details within the next-auth session callback, if it's invalid then I just literally ignore it. Then on my pages I just check for my wrapped session. I do however still think returning null should logout the session.

**Comment by curtisburns** [comment]
Hi, I've probably missed something so apologies in advance. While it might be obvious to many, it would be great if it was documented that throwing an error in the jwt/session callbacks is enough/required to unauthenticate a user. I've gone down the rabbit hole of wondering why returning

```  
return {
      ...token,
      error: "RefreshAccessTokenError",
    }
```

...when failing to refresh a token, as suggested in the example (https://next-auth.js.org/v3/tutorials/refresh-token-rotation) wasn't enough to unauthenticate a user. I need to ensure the user is correctly authenticated on the initial load, and it turns out that checking `token && token.access` or `session.status.authenticated` doesn't actually mean they're authenticated after returning the above following a failed token refresh. Just thought it was worth mentioning in case it's likely to trip some people up (like me).

**Comment by deelo55** [comment]
> Hi, I've probably missed something so apologies in advance. While it might be obvious to many, it would be great if it was documented that throwing an error in the jwt/session callbacks is enough/required to unauthenticate a user. I've gone down the rabbit hole of wondering why returning
> 
> ```
> return {
>       ...token,
>       error: "RefreshAccessTokenError",
>     }
> ```
> 
> ...when failing to refresh a token, as suggested in the example (https://next-auth.js.org/v3/tutorials/refresh-token-rotation) wasn't enough to unauthenticate a user. I need to ensure the user is correctly authenticated on the initial load, and it turns out that checking `token && token.access` or `session.status.authenticated` doesn't actually mean they're authenticated after returning the above following a failed token refresh. Just thought it was worth mentioning in case it's likely to trip some people up (like me).

Can you explain what you mean? My understanding is the user stays authenticated when adding the error as you describe?

**Comment by deelo55** [comment]
> This isn't a solution, but I might have a viable workaround. It's ugly but, pending further testing, I think it works.
> 
> Since I can't find a way to convince NextAuth to terminate the session, I've added a flag to the `Session` interface indicating to terminate the session. When the front end receives it, it triggers a signout.
> 
> Example:
> 
> ```ts
> // options.ts
> const authOptions: NextAuthOptions = {
>   //...
>   callbacks: {
>     session: async ({ session, token }) => {
>       const state = authService.getState();
> 
>       if (state.isValid) {
>         session.accessToken = state.accessToken;
>         session.user = state.user;
>       }
> 
>       if (state.mustReauthenticate) {
>         session.terminate = true;
>         session.expires = new Date().toDateString();
>       }
> 
>       return session;
>     },
>   }
> }
> ```
> 
> ```ts
> // next-auth.d.ts
> interface Session {
>   user?: User;
>   terminate?: boolean;
> }
> ```
> 
>  ```ts
> // app/page.tsx
> const Auth: React.FC = () => {
>   const { data: session } = useSession();
> 
>   useEffect(() => {
>     if (session?.terminate === true) {
>       signOut();
>     }
>   }, [session]);
> 
>   return (
>     <div>...</div>
>   );
> };
> ```

Is this secure? My understanding is the user is still authenticated but you are relying on the front end to sign out which the user can prevent?

**Comment by deelo55** [comment]
> I actually like the idea of invalidating the session by retuning `null`
> 
> The only caveat is that the `/api/auth/session` currently always return an object (empty one if signed out), so it would be a bit weird/might break some cases in user land
> 
> In `@auth/core` though we could still change this. 👍

Has this feature been implemented? I can’t see anything in the docs but if I return null the session is un authenticated and the token is deleted.

**Comment by flawnson** [comment]
> This isn't a solution, but I might have a viable workaround. It's ugly but, pending further testing, I think it works.
> 
> Since I can't find a way to convince NextAuth to terminate the session, I've added a flag to the `Session` interface indicating to terminate the session. When the front end receives it, it triggers a signout.
> 
> Example:
> 
> // options.ts
> const authOptions: NextAuthOptions = {
>   //...
>   callbacks: {
>     session: async ({ session, token }) => {
>       const state = authService.getState();
> 
>       if (state.isValid) {
>         session.accessToken = state.accessToken;
>         session.user = state.user;
>       }
> 
>       if (state.mustReauthenticate) {
>         session.terminate = true;
>         session.expires = new Date().toDateString();
>       }
> 
>       return session;
>     },
>   }
> }
> // next-auth.d.ts
> interface Session {
>   user?: User;
>   terminate?: boolean;
> }
> // app/page.tsx
> const Auth: React.FC = () => {
>   const { data: session } = useSession();
> 
>   useEffect(() => {
>     if (session?.terminate === true) {
>       signOut();
>     }
>   }, [session]);
> 
>   return (
>     <div>...</div>
>   );
> };

Can confirm that this is indeed suboptimal but it works! Unfortunately it seems the user still needs to refresh the page or navigate to another to trigger the behaviour.
