### ISSUE TITLE
Move Providers' documentation into source code

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#7041]
### What is the improvement or update you wish to see?

Old location: https://github.com/nextauthjs/next-auth/tree/v4/docs/docs/providers
New location: https://github.com/nextauthjs/next-auth/tree/main/packages/core/src/providers

- OIDC example: https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/providers/auth0.ts
- OAuth example: https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/providers/github.ts

### Is there any context that might help us understand?

Similar to what we did with adapters in https://github.com/nextauthjs/next-auth/pull/7023

We should do the same with our providers.

This will make sure that we have a single source of truth (source code) for providers that also give useful hints in IDEs (thanks to JSDoc+IntelliSense)

### Does the docs page already exist? Please link to it.

https://authjs.dev/reference/core

**Comment by munnokd** [comment]
Can I work on this issue?

**Comment by munnokd** [comment]
Can I work on this issue?

**Comment by balazsorban44** [comment]
@munnokd Absolutely! Feel free to not do it in one go/PR so it's easier to review (but please don't open 60+ PRs at the same time either :sweat_smile:)

**Comment by munnokd** [comment]
Okay @balazsorban44
