### ISSUE TITLE
Fastify app not compiling `Package subpath './providers/github' is not defined by "exports" in .../@auth/core/package.json`

### ISSUE THREAD

**Issue by AlvaroAquijeDiaz** [nextauthjs/next-auth#7049]
### Provider type

GitHub

### Environment

System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.47 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    npm: 9.5.1 - /opt/homebrew/bin/npm
    Watchman: 2023.01.16.00 - /opt/homebrew/bin/watchman
  Browsers:
    Safari: 16.3

### Reproduction URL

https://github.com/AlvaroAquijeDiaz/next-auth-bug-report

### Describe the issue

I'm using `fastify-next-auth` to glue together next-auth and fastify due to current needs, but I'm getting this error everytime I try to start the server.

- Complete Log
```
Error: Package subpath './providers/github' is not defined by "exports" in /Users/a3tech/Developer/.../packages/api-v2/node_modules/@auth/core/package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:266:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:597:13)
    at resolveExports (node:internal/modules/cjs/loader:579:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:648:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1076:27)
    at Function.Module._load (node:internal/modules/cjs/loader:934:27)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/.../packages/api-v2/index.ts:2:1)
[ERROR] 16:45:30 Error: Package subpath './providers/github' is not defined by "exports" in /Users/a3tech/Developer/.../packages/api-v2/node_modules/@auth/core/package.json
ELIFECYCLE  Command failed.
```

### How to reproduce

start the server

- pnpm i && pnpm dev

### Expected behavior

it should compile and actually work as when using it directly on Next.js

**Comment by balazsorban44** [comment]
The package does have the correct export field, the issue is somewhere else. See https://github.com/nextauthjs/next-auth/blob/aadefc6fbdb9622edc549332a4f222b94302640e/packages/core/package.json#L56

supbath patterns have been supported in  Node.js for a while, so it might be an issue with your tooling somewhere. 🤔

https://nodejs.org/api/packages.html#subpath-patterns

**Comment by AlvaroAquijeDiaz** [comment]
> The package does have the correct export field, the issue is somewhere else. See https://github.com/nextauthjs/next-auth/blob/aadefc6fbdb9622edc549332a4f222b94302640e/packages/core/package.json#L54-L57
> 
> 
> 
> supbath patterns have been supported in  Node.js for a while, so it might be an issue with your tooling somewhere. 🤔
> 
> 
> 
> https://nodejs.org/api/packages.html#subpath-patterns


So it's probably an issue with the library itself? I'll forward this to it then, thanks

**Comment by wanjas** [comment]
@AlvaroAquijeDiaz 
I bumped into the same issue. Looks like it's ES modules problem in CJS. 

I've managed to import the library like this:

```javascript
  const AuthPlugin = (await import('fastify-next-auth')).default;
  const GoogleProvider = (await import('@auth/core/providers/google')).default;
```
