### ISSUE TITLE
Doesn't work within an iFrame?

### ISSUE THREAD

**Issue by khteh** [nextauthjs/next-auth#7051]
### Environment

  System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Memory: 61.20 GB / 70.39 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 19.8.1 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Firefox: 111.0.1

### Reproduction URL

Internal github repo

### Describe the issue

My client application needs to run inside an iFrame of an external website (SAP Ariba Network). When I tried redirecting from https://www.mydomain.io to https://iam.mydomain.io to do the OAuth, it just doesn't get through. Clicking the "Sign in" button just doesn't bring the application over to https://iam.mydomain.io. There is no error logs in the browser debugger console as well as the OAuth application. What could be the problem and how to solve this?

### How to reproduce

https://github.com/nextauthjs/next-auth-example runs inside an iFrame

### Expected behavior

Should be able to redirect between different subdomains inside an iFrame.

**Comment by balazsorban44** [comment]
It's likely caused by the default cookie policy that doesn't allow this:

https://github.com/nextauthjs/next-auth/blob/a7601d0b453348a4e5f9c32876807d64c7663cf1/packages/next-auth/src/core/lib/cookie.ts#L56


Read more:

https://medium.com/trabe/cookies-and-iframes-f7cca58b3b9e

You can change the defaults at your own riks https://next-auth.js.org/configuration/options#cookies

(sending certain cookies to any domain might obviously have security implications)

**Comment by khteh** [comment]
It works but it fails to redirect back to the original application after successful login in the same iFrame. How should I configure the callback?

**Comment by khteh** [comment]
Is it possible to have different cookies configuration? One for the SAP Ariba with relaxed rules, and one with default rules depending on where the user accesses the web application from?

**Comment by khteh** [comment]
The redirection back to the original website after successful login doesn't work. When Ariba Network first "punch out" to our web application it appends `?sid=<GUID>` to the URL which the website uses to communicate with Ariba Network. This information is missing when redirecting back to the original website.
