### ISSUE TITLE
How to authenticate an external React app so it can access protected with NextAuth.js API routes?

### ISSUE THREAD

**Issue by marek-baranowski** [nextauthjs/next-auth#7052]
### Question 💬

I’ve got a NextJS app that serves mainly as a REST API for getting data, with API routes being protected with next-auth authentication (Credentials and Google providers & Prisma adapter). The project uses built-in next-auth UI pages for the given providers.

This works fine as long as API routes are being used by pages within the same NextJS project. However, I need to access those protected routes from the separate React SPA, served from a different domain. How to authenticate this app in the NextJS app to be able to make successful, authorized API requests?

Is it possible to make use of the built-in UI pages from NextJS app?

### How to reproduce ☕️

https://codesandbox.io/p/sandbox/twilight-mountain-i1ikpt

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
see https://github.com/nextauthjs/next-auth/issues/5904
