### ISSUE TITLE
@next-auth/neo4j-adapter using  old neo4j-driver version

### ISSUE THREAD

**Issue by AliHaidar110** [nextauthjs/next-auth#7068]
### Adapter type

@next-auth/neo4j-adapter

### Environment

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 261.83 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2022.08.08.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 111.0.5563.110
    Firefox: 106.0.2
    Safari: 16.3

  npmPackages:
    @next-auth/neo4j-adapter: ^1.0.5 => 1.0.5 

### Reproduction URL

https://github.com/abdallahmoubarak/nextjs-neo4j-backend

### Describe the issue

when trying to install neo4j-adapter using npm:
`npm install @next-auth/neo4j-adapter`

the following error occurs

<img width="596" alt="image" src="https://user-images.githubusercontent.com/64657659/227771429-2ab8361c-cfc9-4738-8d8c-03833af20072.png">

the following packages are installed

<img width="387" alt="image" src="https://user-images.githubusercontent.com/64657659/227771803-f7bdaafe-ffe8-4660-9563-f8a7b9aba5bf.png">

### How to reproduce

install `"neo4j-driver": "^5.6.0"` than try installing `@next-auth/neo4j-adapter`

### Expected behavior

should install the package with no errors

**Comment by balazsorban44** [comment]
#6148 should address this, but the author haven't checked back on my comment. https://github.com/nextauthjs/next-auth/pull/6148#pullrequestreview-1228356055

do you know the answer?

**Comment by AliHaidar110** [comment]
if there is no migration required from `"neo4j-driver": "^4.0.0"` to `"neo4j-driver": "^5.6.0"` we can just change the version number I guess

**Comment by nina-alin** [comment]
was corrected in #7392. Can someone closes this issue?
