### ISSUE TITLE
Supabase adapter 404

### ISSUE THREAD

**Issue by martinchristov** [nextauthjs/next-auth#7075]
### What is the improvement or update you wish to see?

https://next-auth.js.org/adapters/supabase

The page has recently disappeared. I need it back to finalize my integration :/

### Is there any context that might help us understand?

-

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/adapters/supabase

**Comment by balazsorban44** [comment]
Docs has moved, looks like the redirect did not get properly deployed. Will have a look.

Anyways, it's here:  https://authjs.dev/reference/adapter/supabase
