### ISSUE TITLE
Possible to configure cookies dynamically based on where the web application is accessed from?

### ISSUE THREAD

**Issue by khteh** [nextauthjs/next-auth#7077]
### Question 💬

Some of my users access my web application from within an iFrame and some don't. For the iFrame users, it needs to relax the cookie configuration based on https://next-auth.js.org/configuration/options#cookies Is it possible to configure the cookie dynamically based on where  my web application is accessed from if I have a way to identify the source of access?

https://github.com/nextauthjs/next-auth/issues/7051

### How to reproduce ☕️

https://github.com/nextauthjs/next-auth-example runs inside an iFrame

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Yes https://next-auth.js.org/configuration/initialization#advanced-initialization

**Comment by khteh** [comment]
The source where iFrame is used has `?sid=<GUID>`. How do I check this query string param?

**Comment by khteh** [comment]
Doesn't work reliably. The log shows one of the request was without the required parameter.
```
[buyerportal-0 buyerportal]   "referer": "https://www.kyberlife.io/?sid=<GUID>", 
[buyerportal-0 buyerportal]   "referer": "https://www.kyberlife.io/?sid=<GUID>", 
[buyerportal-0 buyerportal]   "referer": "https://www.kyberlife.io/?sid=<GUID>", 
[buyerportal-0 buyerportal]   "referer": "https://www.kyberlife.io/",
[buyerportal-0 buyerportal]   "referer": "https://www.kyberlife.io/?sid=<GUID>", 
[buyerportal-0 buyerportal]   "referer": "https://www.kyberlife.io/?sid=<GUID>", 
```

**Comment by eibrahimov** [comment]
Hello @khteh, I am experiencing the same issue as you. Have you found any solution yet?
