### ISSUE TITLE
next_auth + fb provider, only returns profile pic and name

### ISSUE THREAD

**Issue by mainaani** [nextauthjs/next-auth#7078]
### Question 💬

Hello currently I have next_auth + fb provider in my app. I need to add user to database after users signin through fb, for this I also need either email or mobile num. Currently, the user session only returns the pic and user name.

```
 FacebookProvider({
      clientId: process.env.FACEBOOK_CLIENT_ID,
      clientSecret: process.env.FACEBOOK_CLIENT_SECRET,
      scope: 'email,user_friends,user_gender,user_age_range,user_phone_number'
    })
```

 "next": "13.2.4",
    "next-auth": "^4.20.1",

### How to reproduce ☕️

just create new next-app with above versions,
next_auth with above setup.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by jobajuba** [comment]
Facebook - next auth app can only access the user's name and profile picture by default. 

You'll have to request additional information from the user's Facebook profile, such as their email address, date of birth, and gender, etc.

You can do this in your app settings via the Facebook Developer Console.

Alternatively, you can gain access using Facebook's GraphAPI.

**Comment by mainaani** [comment]
@jobajuba thanks mate. We did enabled email in developer console, but i don't know why we aren't getting it. Also is there a way I can reject login through it if there is no email in the payload? Also I had to ask, it asks me for access everytime i try to relogin, is it normal?

**Comment by balazsorban44** [comment]
Check out https://authjs.dev/reference/adapters#user

You likely want to tweak the `profile()` method on the Facebook provider, as by default only id, name, email and picture is saved.
