### ISSUE TITLE
next-auth credential provider signs me in/creates session even with incorrect detail or errors

### ISSUE THREAD

**Issue by mainaani** [nextauthjs/next-auth#7082]
### Question 💬

Hello I am sick of this error. So, next-auth credential provider, signs me in even with errors/unsuccessful logins. It creates session for me.

session:

{user: {…}, expires: '2023-04-26T03:59:46.157Z'} expires : "2023-04-26T03:59:46.157Z" user : message : "Wrong Password" status : "error" : Object : Object

my next-auth is as below:
```
export default async function auth(req, res) {
  const providers = [
    CredentialsProvider({
      name: "credentials",
      credentials: {},
      async authorize(credentials) {
        try {
          const config = {
            headers: {
              Authorization: `Bearer ${process.env.USER_TOKEN}`
              //'Content-Type': 'application/x-www-form-urlencoded'
            },
          }
          const users = await axios.post(`https://brp.io/api/users/signin`, {
            user_email: credentials.email,
            user_password: credentials.password
          }, config); 

          if(users.data.status !== 'error') {
            const user = users.data.message;
            return { user }
          } else {
            return null
          }
        } catch(error) {
          return error.response.data
        }
      },
    }),
    GoogleProvider({
      ..................
    }),
    FacebookProvider({
      ........
    })
  ]
  return await NextAuth(req, res, {
    providers,
    session: {
      strategy: "jwt",
    },
    secret: process.env.NEXTAUTH_SECRET,
     callbacks: {
    async session({ session, token }) {
      session.user = token.user;
      return session;
    },
    
    async jwt({ token, user }) {
      if (user) {
        token.user = user;
      }
      return token;
    },
  },
  })
}
```

versions: "next": "13.2.4", "next-auth": "^4.20.1",

### How to reproduce ☕️

create new next-app with above mentioned versions and configure the nextauth as shown above

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
You are returning the error response in `authorize` as if it was the user data. 

```
return error.response.data
```

Please read the docs. You can either throw an error, or use the `signIn` callback to verify if you want the user to be able to be logged in.

https://next-auth.js.org/providers/credentials#options
https://next-auth.js.org/configuration/callbacks#sign-in-callback
