### ISSUE TITLE
`req.headers.referer` in advanced initialization code shows inconsistent values

### ISSUE THREAD

**Issue by khteh** [nextauthjs/next-auth#7084]
### Environment

  System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Memory: 52.00 GB / 70.39 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 19.8.1 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Firefox: 111.0.1

### Reproduction URL

https://github.com/nextauthjs/next-auth-example runs inside an iFrame

### Describe the issue

I try to configure cookie according to https://next-auth.js.org/configuration/initialization#advanced-initialization
I need to configure the cookie only if request object has referrer with `sid=<GUID>` query string parameter. However, it doesn't work reliably as the log shows request with inconsistent referrer:
```
[buyerportal-0 buyerportal]   "referer": "https://www.kyberlife.io/?sid=<GUID>", 
[buyerportal-0 buyerportal]   "referer": "https://www.kyberlife.io/?sid=<GUID>", 
[buyerportal-0 buyerportal]   "referer": "https://www.kyberlife.io/?sid=<GUID>", 
[buyerportal-0 buyerportal]   "referer": "https://www.kyberlife.io/", 
[buyerportal-0 buyerportal]   "referer": "https://www.kyberlife.io/?sid=<GUID>", 
[buyerportal-0 buyerportal]   "referer": "https://www.kyberlife.io/?sid=<GUID>", 
[buyerportal-0 buyerportal]   "referer": "https://www.kyberlife.io/?sid=<GUID>", 
[buyerportal-0 buyerportal]   "referer": "https://www.kyberlife.io/?sid=<GUID>", 
[buyerportal-1 buyerportal]   "referer": "https://www.kyberlife.io/", 
[buyerportal-1 buyerportal]   "referer": "https://www.kyberlife.io/", 
[buyerportal-0 buyerportal]   "referer": "https://www.kyberlife.io/?sid=", 
[buyerportal-0 buyerportal]   "referer": "https://www.kyberlife.io/?sid=", 
```
https://github.com/nextauthjs/next-auth/issues/7077

### How to reproduce

https://github.com/nextauthjs/next-auth-example runs inside an iFrame

### Expected behavior

`request` object with consistent `referrer`.

**Comment by balazsorban44** [comment]
This is not related to `next-auth`. We do not use/modify the `referrer` header in any way.

When using the advanced initialization method, you are opting into using a general Next.js API route, for which the documentation can be found at https://nextjs.org/docs/api-routes/introduction

Second reminder: https://github.com/nextauthjs/next-auth/issues/6768#issuecomment-1448041542

Please stop using the issue tracker for personal project-related questions.

Check out https://github.com/vercel/next.js/discussions or http://nextjs.org/discord to get help with your project.
