### ISSUE TITLE
NextAuth JWT/API Implementation

### ISSUE THREAD

**Issue by frosty0x** [nextauthjs/next-auth#7089]
### Question 💬

I am wondering if it is possible to have an implementation of NextAuth using JWT like this:
A user goes to the login page and enters their phone number. The server then calls POST to a backend api to send the code, and the user is prompted to enter the OTP code sent to their phone number. After they enter the code another POST request is made to the server containing the verification code, and if it is valid, it returns a JWT token.

After they get the JWT token, it should save that (create a session) (I assume it would use `signIn` to sign them in using that JWT token). Then it will redirect them to the homepage, and they will be signed in. There is a route on the server which you can POST to to validate the JWT token, which it uses whenever the token needs to be validated. To get user information or anything else requiring authentication it uses the jwt token which is saved in the session.

I also have a url, `/callback` which takes `token` as a URL query parameter, and it validates the JWT token. If it is valid, I want to log them in using it and create a session, redirecting them to the homepage. I have been researching for about a week now and have tried a lot of implementations. If anyone has any ideas on how I could do this now or how I would go about implementing it please let me know.

### How to reproduce ☕️

This is a question.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
The naming is not ideal, but yes, you can achieve this via the Email provider's `sendVerificationRequest` method.

You can check out this guide: https://authjs.dev/guides/providers/email-http

and instead of a service that sends e-mails, you can do the same with a phone number.

We plan to have a dedicated "Token" provider that would be a more generic version of the Email provider. #6927 You can see, it's basically just about naming.

**Comment by frosty0x** [comment]
What about for my callback page?
It takes a query parameter, `code` which is a JWT token, and should log in the user using this. Is this possible with next-auth, something like `logIn(jwt token)` which would check it then create the session? If so, how would I go about doing this? If not, do you have any other recommended library?

**Comment by valandex4** [comment]
I am in the same situation , have an implementation similar to yours . Hopefully we can find some way to implement it !
