### ISSUE TITLE
Magic for X-Auth-Return-Redirect removed

### ISSUE THREAD

**Issue by SoftMemes** [nextauthjs/next-auth#7092]
### Environment

  System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900KF
    Memory: 25.13 GB / 62.58 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 3.5.0 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Brave Browser: 111.1.49.120
    Chrome: 111.0.5563.64
    Firefox: 111.0.1

Next-auth versions: v4.18.6 vs v4.20.1

### Reproduction URL

Code change, see below

### Describe the issue

For admittedly obscure reasons, our project relies on the ability to trigger a sign in, but explicitly handling the redirect, rather than relying on a redirect HTTP response from Next-auth. This was accomplished by setting a custom header 'X-Auth-Return-Redirect': '1' when making a call to the signin endpoint.

The behaviour was possible never officially supported or documented, but worked perfectly for our needs.

It appears that this was then later removed in https://github.com/nextauthjs/next-auth/commit/a83573ed2f696108ad2294a1892aa204cfaf7c71 and this custom header is no longer used.

Was this removed intentionally, and is there another way of achieving the same thing of starting a login flow but not having the browser immediately follow the redirect?

### How to reproduce

Manually start the sign in flow from a browser, specifying a custom header of  'X-Auth-Return-Redirect': '1'

### Expected behavior

Observe that next-auth no longer uses this header and returns a redirect response code instead of a JSON document containing the intended target URL.

**Comment by balazsorban44** [comment]
Setting `json: true` in the body is the equivalent. https://github.com/nextauthjs/next-auth/blob/40261834111156b0df1318f5a9d8bd652387ff7f/packages/next-auth/src/react/index.tsx#L250

For the email and credentials provider though, there is an official way: https://next-auth.js.org/getting-started/client#using-the-redirect-false-option
