### ISSUE TITLE
Email codes instead of "Magic links"

### ISSUE THREAD

**Issue by martinchristov** [nextauthjs/next-auth#7099]
### Description 📓

The magic links solution doesn't provide a good UX and the developer has too little control over it.
The user attempting to login loses their state in the app and their flow is disrupted.
Additionally, for PWA and mobile apps developers need to do extra work so that email login links be handled through the app.

An alternative solution is to send email with a 6 digit code displayed to the user and no link.
The UI shows the user an input and the FE posts the inputted code to the auth api for validation and finalising authentication.

### How to reproduce ☕️

Issues:
- user's flow is disrupted and their state in the app is lost
- after login the app is reopened in a new window
- too little control over the UI
- additional work for linking to apps / PWAs

Desired functionality:
- enable sending a 6-digit code in the email message - displayed, not in a link
- a function for validating the code in the /auth endpoint and logging the user in

End result:
Undisrupted user flow through more control at the FE

### Contributing 🙌🏽

I would like to help, but won't be able to do this on my own.

**Comment by balazsorban44** [comment]
Already possible, see https://github.com/nextauthjs/next-auth/issues/4965#issuecomment-1189094806

Would you be interested in turning this into a guide in our docs under https://github.com/nextauthjs/next-auth/tree/main/docs/docs/guides/providers?

**Comment by martinchristov** [comment]
Wonderful!

**Comment by martinchristov** [comment]
@balazsorban44 there seems to be one part missing though:
I do not find a way to make a POST request to validate the code and log the user in - without a redirect.

**Comment by martinchristov** [comment]
@balazsorban44 ?

**Comment by balazsorban44** [comment]
Looks like it needs to be implemented in core to make it proper. Will have a look some time if nobody picks this up.

**Comment by dieterpankratz** [comment]
Hi @balazsorban44 I would like to take this if you could give me a quick hint on what needs to be done?

**Comment by dieterpankratz** [comment]
Hi @lluia, just saw that this ticket has been assigned to you. May I support you on that?

**Comment by witto13** [comment]
Hello everyone. Yesterday we had the big launch of our product and sadly some of our users said that the login magiclink didn't work. When they open it it was expired already. We don't want to ask our users to deactivate safe links in outlook so we are looking for some solutions. The solutions that you present work also for the new outlook? the one that says "new" in the icon?

**Comment by martinchristov** [comment]
The problem most certainly would have been solved with few-digit codes instead of magic links. It is an alternative used by many platforms due to higher reliability and compatibility with mobile apps & PWAs, as well providing a much better user experience.
