### ISSUE TITLE
Isn't there a faster way to check if user in authenticated or not?

### ISSUE THREAD

**Issue by LupuC** [nextauthjs/next-auth#7101]
### Question 💬

So, I'm new to NextJS, and this is the first libary I had contact with. I've made a little website, with your auth library, and work 99% as expected. However, that 1% was this little "problem":

I wanted to render items in my navigation bar, based on the status (if auth or not). My approach was something like:

if auth => display item 1
if not auth => display item 2.

There, I found out that, on page refresh, none of the items were rendered (since it took some time to check if user is authenticated or not), and added
if loading => display item1

But, the catch is that, even if I'm logged in, first (for a couple of seconds) it will display item 1 (because of loading) then item 2.

Next thing, I've decided to use the original repo from NextJS that has auth premade with NextAuth: https://github.com/nextauthjs/next-auth-example

And it does the same thing (but has a fancy transition, so isn't that noticeable..)

Isn't there any other way, to check if user is authenticated, faster?

### How to reproduce ☕️

https://github.com/nextauthjs/next-auth-example

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
To avoid a flash of unauthenticated content even when the user is logged in, usually you will need some server logic that can render the content based on request headers (like the session cookie).

Currently, there is `getServerSideProps` in `pages`, or if you want to try out the new App Router (beta) in Next.js 13, React Server Components will solve this (among many other similar) issues.

Ref:
- https://next-auth.js.org/configuration/nextjs#in-getserversideprops
- https://next-auth.js.org/configuration/nextjs#in-app-directory
  - https://beta.nextjs.org/docs/guides/authentication (Note, this page as of writing is empty)

If you go with `getServerSideProps`, remember to pass `session` to `SessionProvider`, to actually avoid the flash: https://next-auth.js.org/getting-started/client#sessionprovider

Another option could be to use Next.js Middleware to redirect the user to a different landing page if they are not logged in for example. Check out https://next-auth.js.org/configuration/nextjs#middleware

Hope this helps!

**Comment by LupuC** [comment]
Ok, I added this to the Header component:

`export async function getServerSideProps({ req, res }) {
  return {
    props: {
      session: await getServerSession(req, res, authOptions)
    }
  }
}`

Now, I get this error: Binding element 'req' (& res) implicitly has an 'any' type.ts(7031)

**Comment by LupuC** [comment]
Update. This is how my code looks like so far:
//components/header
```
export default function Header({ session }: {session:any} ) {
     console.log(session)
}
```

//components/layout
```
export default function Layout({ children, session }: { children: ReactNode, session: any }) {
  return (
    <>
      <Header session={session} />
      <main>{children}</main>
      <Footer />
    </>
  )
}
```

//pages/index
```
export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  return {
    props: {
      session: await getServerSession(req as NextApiRequest, res as NextApiResponse, authOptions),
    },
  };
};

export default function IndexPage({ session }: { session: any }) {
  return (
    <Layout session={session}>
      <h1>NextAuth.js Example</h1>
      <p>
        This is an example site to demonstrate how to use{" "}
        <a href="https://next-auth.js.org">NextAuth.js</a> for authentication.
      </p>
    </Layout>
  )
}
```

and still doesn't work (it doesn't log anything in header file)

**Comment by LupuC** [comment]
Fixed it! Looks like it works like this:

index
```
export default function IndexPage({ session }: { session: Session }) {
  console.log(session)
  return (
    <Layout>
      <h1>NextAuth.js Example</h1>
      <p>
        This is an example site to demonstrate how to use{" "}
        <a href="https://next-auth.js.org">NextAuth.js</a> for authentication.
      </p>
    </Layout>
  )
}

// Export the `session` prop to use sessions with Server Side Rendering
export async function getServerSideProps(context: GetServerSidePropsContext) {
  return {
    props: {
      session: await getServerSession(context.req, context.res, authOptions),
    },
  }
}
```

**Comment by balazsorban44** [comment]
The recommended way to access the session is using the `useSession()` hook. https://next-auth.js.org/getting-started/client#usesession

You _can_ pass the session as a prop, but if you followed https://next-auth.js.org/getting-started/client#sessionprovider

Make sure that `session` is also propagated to the page component in `_app` as such: `<Component session={session} {...pageProps} />`

**Comment by karlhorky** [comment]
> * [beta.nextjs.org/docs/guides/authentication](https://beta.nextjs.org/docs/guides/authentication) (Note, this page as of writing is empty)

Ohh would love to hear some official recommendations on creating auth manually from the Next.js team! 👀
