### ISSUE TITLE
getServerSession returns unserializable data

### ISSUE THREAD

**Issue by bkiac** [nextauthjs/next-auth#7119]
### Environment

**System:**
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 185.28 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh

**Binaries:**
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm

**Browsers:**
    Chrome: 111.0.5563.110
    Firefox: 109.0.1
    Safari: 16.3

### Reproduction URL

https://github.com/bkiac/unserializable-getserversession

### Describe the issue

If my User schema has no `image` and `name`, then `getServerSession` returns `undefined` for them instead of `null` or omitting the fields, which means I can't pass the `session` object returned from `getServerSession` in `getServerSideProps`

### How to reproduce

1. Run Docker
2. Clone the reproduction repo
3. Install dependencies
4. Run `npm run dev` to start Next.js and database
5. Run `npm run db:migrate:dev` to migrate the database
6. Navigate to `http://localhost:3000`
7. Sign in with any email
8. Go to `https://ethereal.email`, log in with credentials: `adela.cassin57@ethereal.email`, `juHgHFHWvxC4wsZxAK` 
9. Click the sign in link in the received email
10. After redirect the page will crash with this error
  ```
Error: Error serializing `.session.user.name` returned from `getServerSideProps` in "/".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
```

### Expected behavior

I'm fairly new to NextAuth.js so this might be an error in the Prisma Adapter, but I think it should not be required to have an `image` and `name` for my User schema but even then `getServerSession` shouldn't return an unserializable object.

I did not find documentation about how to overwrite the session object, I could overwrite the `image` and `name` fields with `null`, but then TypeScript will complain because in the type augmentation my user does not have those fields.

**Comment by bkiac** [comment]
yeah but then my type needs to be
```ts
interface Session extends DefaultSession {
		user: {
			id: string;
			email: string | null;
			image: null;
			name: null;
		};
	}
```

then do 

```ts
session({session, user}) {
			if (session.user) {
				session.user.id = user.id;
				session.user.email = user.email ?? null;
				session.user.image = null;
				session.user.name = null;
			}
			return session;
		},
```

which seemed unnecessary.

This is what I ended up doing anyway, but I was hoping for a cleaner solution. Thanks anyway!

**Comment by fidalgodev** [comment]
This still happens with Firestore adapter when you login via the EmailProvider.

If you login via an email provider, your user model won't have a `name`.
So then when you do:

```
export const getServerSideProps = async ({ req, res }) => {
  const session = await getServerSession(req, res, authOptions)

  return {
    props: {
      serverSession: session,
    },
  }
}
```

Error: Error serializing `serverSession.user.name` returned from `getServerSideProps` in "/".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
```

This can be fixed by doing:
```
callbacks: {
  session({ session }) {
    if (session.user) {
      session.user.name = session.user.name ?? null
    }
    return session
  },
},
```

But feels like the package should handle this?
