### ISSUE TITLE
Getting Discord ID

### ISSUE THREAD

**Issue by prinkee** [nextauthjs/next-auth#7122]
### Question 💬

Is it possible to get the Discord ID, discriminator, and other info? I am only able to get the image and name.

### How to reproduce ☕️

Try to get the user ID or discriminator with `session.user.id`. It will return as undefined.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
https://next-auth.js.org/getting-started/example#extensibility

**Comment by prinkee** [comment]
Following the extensibility documentation, I am still getting errors here.

[...nextauth].ts:
```typescript
import NextAuth from "next-auth"
import DiscordProvider from "next-auth/providers/discord"
import { Profile, Session } from "next-auth"

export default NextAuth({
  providers: [
    DiscordProvider({
      clientId: process.env.DISCORD_CLIENT_ID!,
      clientSecret: process.env.DISCORD_CLIENT_SECRET!,
    }),
  ],
  callbacks: {
    async jwt({ token, account, profile }) {
      if (account) {
        token.accessToken = account.access_token
      }

      if (profile) {
        token.id = profile.id
        token.discriminator = profile.discriminator
      }

      return token
    },

    async session({ session, token, user }) {
      session.accessToken = token.accessToken
      session.id = token.id
      session.discriminator = token.discriminator

      return session
    }
  }
})
```

The errors I'm getting are: 
Property 'id' does not exist on type 'Profile'.
Property 'discriminator' does not exist on type 'Profile'.
Property 'accessToken' does not exist on type 'Session'.
Property 'id' does not exist on type 'Session'.
Property 'discriminator' does not exist on type 'Session'.

What exactly am I doing wrong?

**Comment by balazsorban44** [comment]
https://next-auth.js.org/getting-started/typescript

**Comment by TMachadoDev** [comment]
Still what we need to do?

**Comment by WilckerK** [comment]
I know this is probably not the best solution, but the DiscordProvider callback returns undefined. Luckily, the token has a property called sub which contains the discord id.

```js
import NextAuth from "next-auth";
import DiscordProvider from 'next-auth/providers/discord'

export default NextAuth({
  providers:[
    DiscordProvider({
      clientId: process.env.DISCORD_ID,
      clientSecret:process.env.DISCORD_SECRET
    }),
  ],
  callbacks: {
    async session({session, token, user}) {
      if (token) {
        if (token?.picture?.includes("discord")) {
          session.user.id = token.sub;
        }
      }
      return session;
    },
  },
})
```

**Comment by RimuruOtter** [comment]
A slightly better solution to this is by using the user ID provided by the user's image. I've tried looking at the previous fix using the sub property but does not actually report the discord user's id (possibly did before but I guess not anymore?).

Here is the fixed version which correctly reports the discord user's ID. Not the greatest but at least its correct! All be it, there are some things you can probably add to make sure its more safe instead of splitting then taking the second index.
```js
import NextAuth from "next-auth"
import Discord from "next-auth/providers/discord"

export const { handlers, signIn, signOut, auth } = NextAuth({
    providers: [ Discord ],
    callbacks: {
        async session({ session }) {
            if(session.user.image == null || session.user.image == undefined) return session
            const url = new URL(session.user.image)
            const userId = url.pathname.split("/")[2]

            session.user.id = userId

            return session
        }
    }
})
```
