### ISSUE TITLE
MongoDB Adapter release - MongoDB v5 support

### ISSUE THREAD

**Issue by armandodlvr** [nextauthjs/next-auth#7126]
### Question 💬

When do you plan to release a new version of the MongoDB adapter? I saw in the repository that it is already compatible with MongoDB v5 but the version that is currently released is not.

### How to reproduce ☕️

When do you plan to release a new version of the MongoDB adapter? I saw in the repository that it is already compatible with MongoDB v5 but the version that is currently released is not.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by MTGPROD** [comment]
I'm using mongodb with the adapter and that works. Except that it doesn't update data like Session and User even if you logged out and logged in.

**Comment by boredland** [comment]
Ya, shouldn't those releases be semi automatic?

**Comment by Gregor23021** [comment]
> ### Pregunta
> ¿Cuándo planea lanzar una nueva versión del adaptador MongoDB? Vi en el repositorio que ya es compatible con MongoDB v5 pero la versión que se lanza actualmente no lo es.
> 
> ### como reproducir
> ¿Cuándo planea lanzar una nueva versión del adaptador MongoDB? Vi en el repositorio que ya es compatible con MongoDB v5 pero la versión que se lanza actualmente no lo es.
> 
> ### Aportando 🙌🏽
> Sí, estoy dispuesto a ayudar a responder esta pregunta en un PR

**Comment by Jared-Dahlke** [comment]
I'm curious about this too. I have `"@next-auth/mongodb-adapter": "^1.1.1",` 
`"mongodb": "^5.2.0",`

and `"next-auth": "^4.21.1",` but does not work because they require `mongodb v4` as peer dependency

**Comment by boredland** [comment]
is there anything we need to do @balazsorban44 so we could fast-track this?

**Comment by boredland** [comment]
also related: https://github.com/nextauthjs/next-auth/issues/7022

**Comment by boredland** [comment]
what is going on here? this is really frustrating.

**Comment by Jared-Dahlke** [comment]
I ended up just converting to using Prisma with CockroachDB and Postgres instead of MongoDB. Was having other connection issues anyway. `@next-auth/prisma-adapter` works fine with latest

**Comment by dlamprey** [comment]
+1 with emphasis! I hate having to downgrade just to accommodate one package! 😠 please fix!

![image](https://user-images.githubusercontent.com/48389685/232466429-aae45740-b52a-48cd-91c5-927574929251.png)

**Comment by balazsorban44** [comment]
If it's just npm complaining, you can fix it by the force flag. Should not be blocking. Will look into this soon 🔜. My focus has been elsewhere.

**Comment by dlamprey** [comment]
> If it's just npm complaining, you can fix it by the force flag. Should not be blocking. Will look into this soon 🔜. My focus has been elsewhere.

Understood. Just wanted to make sure it was on the radar. Thanks.

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth/releases/tag/%40next-auth%2Fmongodb-adapter%401.1.2 is out, please upgrade
