### ISSUE TITLE
Typescript type unknown in code example for SignIn page

### ISSUE THREAD

**Issue by TheDesertKing** [nextauthjs/next-auth#7134]
### What is the improvement or update you wish to see?

In this page: https://next-auth.js.org/configuration/pages#examples
appears a block of code that has the following typescript error/warning:
" 'provider' is of type 'unknown' .ts(18046)"
I believe that is due to the `InferGetServerSidePropsTypes` interface making the `providers` prop's type "never", but I am quite new to typescript and this might not be an issue.

### Is there any context that might help us understand?

Any way, this is confusing to me, as someone who is less experienced with TS and so I believe it would be best to change the example to one that contains no errors or warnings.
![image](https://user-images.githubusercontent.com/57393961/229375861-609b5616-56d3-4cac-b368-0d9860ddd47c.png)

### Does the docs page already exist? Please link to it.

In this page: https://next-auth.js.org/configuration/pages#examples

**Comment by balazsorban44** [comment]
Can you add a reproduction? I get no such error :thinking:

![image](https://user-images.githubusercontent.com/18369201/229461842-d7c16044-fad8-4dec-ac1d-879f2bbfa5e1.png)

**Comment by TheDesertKing** [comment]
Yeah I just tested it on Stackblitz and there's no error, I don't understand why I get it on my machine but I'll work around it for now, thank you!
