### ISSUE TITLE
Callback URL being ignored

### ISSUE THREAD

**Issue by the-new-kai-lu** [nextauthjs/next-auth#7135]
### Question 💬

I have this for api/auth/[...nextauth].ts:

```
import NextAuth from 'next-auth'
import GoogleProvider from "next-auth/providers/google";
import {NextApiRequest, NextApiResponse} from "next";

export const authOptions = {
    debug: true,
    providers: [
        GoogleProvider({
            clientId: process.env.GOOGLE_AUTH_CLIENT_ID as string,
            clientSecret: process.env.GOOGLE_AUTH_CLIENT_SECRET as string
        })
    ]
}

export default (req: NextApiRequest, res: NextApiResponse) => NextAuth(req, res, authOptions)
```

I have NEXTAUTH_URL in .env as `NEXTAUTH_URL = 'http://localhost:3000'`

I have a signin button with the following onClick in index: 
`onClick={() => signIn(undefined, {callbackUrl: '/signin'})}`

This gives me a redirect_uri_mismatch consistently when using Google; the URI Google seems to get is the default callback (/api/auth/callback/google). 

The URL seems to be set correctly in cookies: there is a request to /api/auth/signin/google with this cookie: `next-auth.callback-url=http%3A%2F%2Flocalhost%3A3000%2Fsignin;`.

### How to reproduce ☕️

Just having a button on index.tsx and the above for the auth page produces this error for me.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by the-new-kai-lu** [comment]
Nevermind; I discovered that the callback URL takes effect after the redirect to the api page.

**Comment by brinux** [comment]
@the-new-kai-lu may you show how you managed to handle the redirect? I have the same issue...

**Comment by brinux** [comment]
Nevermind, I solved it as well! I had customized my redirect() callback and because of this it wasn't working.
Thanks anyway!

**Comment by the-new-kai-lu** [comment]
For the sake of anyone in the future:

Set the redirect URI (in Google console) to `/api/auth/callback/google`; the redirect URI set in the signin request takes place immediately *after* that page
