### ISSUE TITLE
UseSession update function does not appear to exist

### ISSUE THREAD

**Issue by fotoflo** [nextauthjs/next-auth#7153]
### What is the improvement or update you wish to see?

the next auth docs at  https://next-auth.js.org/getting-started/client#updating-the-session show an update session method but earlier in the page at https://next-auth.js.org/getting-started/client#usesession it says 

"useSession() returns an object containing two values: data and status"

My direct experience shows that the update method is not available:
![image](https://user-images.githubusercontent.com/1642357/230041623-85cd7e5c-bbf5-4c23-bd6b-802c18356ee9.png)

### Is there any context that might help us understand?

Using next-auth 4.19.2 

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/getting-started/client#usesession

**Comment by DiegoGonzalezCruz** [comment]
hi @fotoflo !  you need to update next-auth to 4.21

**Comment by balazsorban44** [comment]
please upgrade
