### ISSUE TITLE
`apiBaseUrl` resolves incorrectly, resulting in inability to use an external server

### ISSUE THREAD

**Issue by pixelpax** [nextauthjs/next-auth#7160]
### Environment

  System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 8.93 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Firefox: 107.0
    Safari: 16.3

### Reproduction URL

private

### Describe the issue

```
export function apiBaseUrl(__NEXTAUTH: AuthClientConfig) {
  if (typeof window === "undefined") {
    // Return absolute path when called server side
    return `${__NEXTAUTH.baseUrlServer}${__NEXTAUTH.basePathServer}`
  }
  // Return relative path when called client side
  return __NEXTAUTH.basePath
}
```

should probably be rewritten as 

```
export function apiBaseUrl(__NEXTAUTH: AuthClientConfig) {
  if (typeof window === "undefined") {
    // Return absolute path when called server side
    return `${__NEXTAUTH.baseUrlServer}${__NEXTAUTH.basePathServer}`
  }

  return `${__NEXTAUTH.baseUrl}${__NEXTAUTH.basePath}`
}
```

So that requests resolve correctly when using an external server.

This is absolutely essential for when a client is using next-auth to access an external api running next-auth on a different server.

### How to reproduce

Try to hit a backend running on a server with a different URL than the client.

### Expected behavior

This should *just work* when NEXTAUTH_URL is provided correctly

**Comment by pixelpax** [comment]
https://github.com/nextauthjs/next-auth/pull/7161

**Comment by pixelpax** [comment]
PR here: https://github.com/nextauthjs/next-auth/pull/7161

**Comment by balazsorban44** [comment]
See https://github.com/nextauthjs/next-auth/pull/7161#issuecomment-1498272796
