### ISSUE TITLE
Allow diacritics/accents characters for User schema in SQL Server DB - TypeORM

### ISSUE THREAD

**Issue by jiriludvik** [nextauthjs/next-auth#718]
**Summary of proposed feature**
Hello, recently I discovered a problem when working with database sessions stored in SQL Server (TypeOrm adapter). My setup uses Azure Active Directory (oauth2.0) to sign users in. The thing is that as I have there user with name "Jiří" - this creates new record in DB table "users" with name = "JiYí". 

Having checked the [docs for MS SQL schema](https://next-auth.js.org/schemas/mssql) seems the problem is that column "name" is of type varchar. Another problem could be in [schema definition](https://github.com/nextauthjs/next-auth/blob/main/src/adapters/typeorm/models/user.js) which states the same.

**Purpose of proposed feature**
Would it be possible to update required definitions to use nvarchar instead of varchar to handle accented characters?

**Potential problems**
Not sure about potential problems as I'm quite new in Javascript and Next.JS field ;)

**Comment by iaincollins** [comment]
Oh no! Sorry you ran into this issue and thank you for raising it.

Yes that change seems sensible, if it's mangling names that's a bug.

**Comment by ndom91** [comment]
Re: diacritics and other special latin characters, usually you want to set the db charset to utf-8. I did a bit of digging on what to do there with typeorm and came across this: https://github.com/typeorm/typeorm/issues/390

**Comment by balazsorban44** [comment]
@ndom91 is there anything to do here in the adapter code?

**Comment by ndom91** [comment]
I believe you can define the `utf8` character set when defining the db. 

Might make sense to append to our seed file. 

EDIT: after some research, it seems this is the default character set with mysql8 👍 

So nothing to do as far as I see, should be supported out of the box
