### ISSUE TITLE
Error with NextJS 13.3.0

### ISSUE THREAD

**Issue by zajqn** [nextauthjs/next-auth#7189]
### Environment

I am using NextAuth and setting up login with Google in my project. It works fine on NextJS version 13.2.4, but when I update to NextJS 13.3.0, I get the error shown below.
![error](https://user-images.githubusercontent.com/77799145/230605902-8d0548ce-0777-4201-ba80-9b7ef9e517db.png)

### Reproduction URL

https://google.com

### Describe the issue

I am using NextAuth and setting up login with Google in my project. It works fine on NextJS version 13.2.4, but when I update to NextJS 13.3.0, I get the error shown below.
![error](https://user-images.githubusercontent.com/77799145/230605902-8d0548ce-0777-4201-ba80-9b7ef9e517db.png)

### How to reproduce

https://google.com

### Expected behavior

https://google.com

**Comment by essuraj** [comment]
@zajqn how did u fix this?

**Comment by essuraj** [comment]
downgrade fixed it, issue with Next.js 13.3... development mode on windows
