### ISSUE TITLE
Signout from API in v3?

### ISSUE THREAD

**Issue by bscaspar** [nextauthjs/next-auth#719]
**Your question**
Is it possible to signout from REST API in v3? I am attempting to do so with the following but it doesn't quite seem to be working:

```js
const csrf = await getCsrfToken({ req });
      const logoutRes = await fetch(`${process.env.NEXT_PUBLIC_SITE}/api/auth/signout`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: _encodeForm({
          csrfToken: csrf,
          callbackUrl: '/login',
        }),
      });
      res.end();
```

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
It should be! I think we need some better documentation for the REST endpoints.

This is the code the client uses for the `signOut` method:
https://github.com/nextauthjs/next-auth/blob/main/src/client/index.js#L259

**Comment by bscaspar** [comment]
I'm sure it was an issue on my end, I've ended up going a different path at this point, thanks for answering!
