### ISSUE TITLE
Getting CLIENT_FETCH_ERROR in production intermittently

### ISSUE THREAD

**Issue by nmaties** [nextauthjs/next-auth#7207]
### Environment

```
  System:
    OS: macOS 13.2.1
    CPU: (8) x64 Apple M1
    Memory: 86.57 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 8.17.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Safari: 16.3
```

### Reproduction URL

https://github.com

### Describe the issue

I am getting the following error from the screenshot attached intermittently, this is in a production env.

<img width="670" alt="Screenshot 2023-04-10 at 11 50 54" src="https://user-images.githubusercontent.com/16613184/230889680-3d252e95-b96e-4774-82b1-0bd2fe2a6438.png">
<img width="330" alt="image" src="https://user-images.githubusercontent.com/16613184/230889930-63039c28-3386-4cd8-bce9-b670289fbe8e.png">

**I cannot give you access to the code, it's a private repo**, I followed the integration steps available in NextAuth documentation, and I do have integration with the following providers: IG, Google, FB.

The above screenshots are from Log Rocket.

I noticed that this error happens only on mobile IOS devices. 

I do have the `NEXTAUTH_URL` key/value set in my config correctly.

[...nextAuth].js

```
export const authOptions = {
  providers: [
    FacebookProvider({
      clientId: process.env.FACEBOOK_CLIENT_ID,
      clientSecret: process.env.FACEBOOK_CLIENT_SECRET
    }),
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET
    }),
    InstagramProvider({
      clientId: process.env.INSTAGRAM_CLIENT_ID,
      clientSecret: process.env.INSTAGRAM_CLIENT_SECRET
    })
  ],
  pages: {
    newUser: '/example',
  },
  secret: process.env.JWT_SECRET,
  callbacks: {
    async session({ session, user }) {
      return {
        ...session,
        user
      };
    },
  },
  adapter: MongoDBAdapter(clientPromise)
}
export default NextAuth(authOptions)
```

### How to reproduce

Just randomly navigating in the app.

### Expected behavior

To not get this error at all.

**Comment by Crazypersonalph** [comment]
Hello,
Could you clone your repo, remove the private information from the repo, and make a new repo so that we can see how your code is working?
Thanks

**Comment by Crazypersonalph** [comment]
From these details, it looks like it may be a CORS issue
https://stackoverflow.com/questions/71280168/javascript-typeerror-load-failed-error-when-calling-fetch-on-ios

**Comment by Gr33nLight** [comment]
Hey, how did you manage to fix this issue? @nmaties

**Comment by nmaties** [comment]
@Gr33nLight I haven't managed to fix it at all.

**Comment by davl3232** [comment]
Getting this exact error with Safari and next auth, it worked before, then it suddenly started failing. It works ok on Chrome. For some reason, setting `NEXTAUTH_URL` to `127.0.0.1` instead of `localhost` appears to fix this for me, but I'm probably just hiding the problem.

Safari (Version 16.5.2 (18615.2.9.11.10))

next-auth 4.24.4

next 14.0.0

![Screenshot 2024-01-22 at 2 36 16 PM](https://github.com/nextauthjs/next-auth/assets/4100566/8fa6e756-5e26-4267-b120-ca9d6c148d95)

**Comment by sohaha** [comment]
I feel it's a bug in next-auth

**Comment by vitorcont** [comment]
Any updates on this? @nmaties you managed to fix this?

**Comment by youngheart12** [comment]
Any one working on this facing same
