### ISSUE TITLE
'trigger' not valid property for session and jwt callback

### ISSUE THREAD

**Issue by anonrose** [nextauthjs/next-auth#7223]
### What is the improvement or update you wish to see?

 `"next-auth": "^4.19.0",`

In the documentation the example for updating properties on a session object implies that there is a `trigger` property on the object passed into the session callback when using `strategy: database`. This however is not true

![image](https://user-images.githubusercontent.com/8890675/231299971-f75fd154-595a-47e1-bc2c-4e593b7cfc13.png)

![image](https://user-images.githubusercontent.com/8890675/231299893-ef1b6128-f1ca-4ec1-84a0-f8e03578163c.png)

### Is there any context that might help us understand?

Looking to add additional attributes to the auth session so I don't have to refetch that data when doing authenticated api requests.

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/getting-started/client#example-2

**Comment by akremer** [comment]
Upgrade to 4.21, which introduces this functionality.

https://github.com/nextauthjs/next-auth/releases/tag/next-auth%404.21.0

**Comment by anonrose** [comment]
Tank u 🙇 @akremer
