### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by rechandler** [nextauthjs/next-auth#723]
**Your question**
Are there any examples or is it possible to set up a custom provider with Firebase Auth?

**What are you trying to do**
This library seems awesome and I'd love to user firebase auth but I'm not sure its possible. I can get Next to work with Firebase, but I'd prefer to use this library. Currently its set up to validate the firebase token on the server, but this means my entire app is now server side and not a mixture of static and ssr.

**Comment by revskill10** [comment]
I need firebase authentication to leverage firebase storage, too.

**Comment by CodenameCookie** [comment]
Did you ever find a good example of how to make NextAuth work with Firebase. I may be able to write the Firebase functions to work but its not going to be easy.

**Comment by rechandler** [comment]
You can follow the firebase docs and get it working, however its going to prevent pre rendering of every page  that needs authentication, which in my app was every page.
