### ISSUE TITLE
Defining providers inside default exported function (...nextauth.ts) redirecting back to sign in page

### ISSUE THREAD

**Issue by RobinBertilsson** [nextauthjs/next-auth#7231]
### Environment

  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 287.48 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Edge: 112.0.1722.39
    Firefox: 110.0.1
    Safari: 16.4

### Reproduction URL

https://github.com/RobinBertilsson/next-auth-provider-in-func-issue

### Describe the issue

According to the documentation ([Configuration > Advanced initialization](https://next-auth.js.org/configuration/initialization#advanced-initialization)) you should be able to wrap `NextAuth()` with a async function that accepts the request and response. This is very handy, beacuse we need the request in order to grab the host header, since we need that as the callbackUrl for our custom provider.

By doing just like the documentation suggest (see below), we're just redirected back to `/api/auth/signin?csrf=true` without any errors at all.

```ts
export default async function auth(req: NextApiRequest, res: NextApiResponse) {
  const options = { providers: [...] }
  return await NextAuth(req, res, options)
}
```

However, if we instead move the options outside the default exported function (see below) it works fine, but then we have the problem that we cannot access the `req` variable, meaning - we cannot get the request host header.

```ts
const options = { providers: [...] }

export default async function auth(req: NextApiRequest, res: NextApiResponse) {
  return await NextAuth(req, res, options)
}
```

### How to reproduce

1. Clone the repository specified above
2. Copy `.env.local.example` to `.env.local` and update the `OAUTH_BASE_URL` to a valid URL, which doesn't matter, because you won't get there either way. 
2. Run `npm install`
3. Run `npm run dev`
4. Go to `http://localhost:3000`
5. Press the "Sign in" button, then "Sign in with Custom"

### Expected behavior

To be redirected to `${OAUTH_BASE_URL}/oauth/authorize`

**Comment by RobinBertilsson** [comment]
After doing some more digging, it's seems to be about using `req` as a part of the option provided.
I've created two working examples inside [[...nextauth.ts]](https://github.com/RobinBertilsson/next-auth-provider-in-func-issue/blob/main/pages/api/auth/%5B...nextauth%5D.ts) and one that doens't work, it's really strange 👀

**Comment by RobinBertilsson** [comment]
In my example repository above, i'm using a custom provider, because that's where i thought the issue was at first, but i've now realised that the same thing applies when using built in providers such as GitHub and Google as well...

```typescript
GoogleProvider({
  clientSecret: '...',
  clientId: '...',
  authorization: {
    params: {
      // Using `req.headers.origin` as a template literal like this causing the "redirect issue"?
      redirect_uri: `${req.headers.origin}/api/auth/callback/google`
    }
  }
})
```

**Comment by balazsorban44** [comment]
we always override the `redirect_uri`.

If you want to control where the user should return, check out https://next-auth.js.org/getting-started/client#specifying-a-callbackurl
