### ISSUE TITLE
Scrambled/encoded callback url when using @auth/core and sveltekitauth

### ISSUE THREAD

**Issue by thomasmol** [nextauthjs/next-auth#7232]
### Provider type

Email

### Environment

  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 169.27 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.4.0 - /opt/homebrew/bin/node
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 111.0.1
    Safari: 16.4

Environment of production is node 16.x 

### Reproduction URL

https://github.com/thomasmol/interview-processor

### Describe the issue

Sometimes I get this error on my server (in production): ```[auth][error][InvalidCallbackUrl]: Invalid callback URL. Received: VNdGt://PIYjwRPcY.ztc/ByCFJ.``` 
I am using the latest @auth/core and sveltekit framework libraries with the email provider. Most of the time the login/signup flow works fine. But sometimes I receive the above error. The docs are unclear to me what or where the problem exactly is. The strange thing: the callback url that is received seems to be scrambled: it is the correct length and format. The url should be https://audiogest.app/login . 

This is how I am creating the provider in hooks.server.ts in sveltekit: 
```
providers: [
//@ts-expect-error issue ??
  EmailProvider({
    server: EMAIL_SERVER,
    from: EMAIL_FROM
  })
]
```

### How to reproduce

Deploy the github repo I provided and try to login.
I do not know how to get the error consistently though.

### Expected behavior

No errors and a successful login. The correct callback url should be sent to the user.

**Comment by balazsorban44** [comment]
It sounds like that someone is trying to mess with your users, intercepting and modifying the callback URL, but failing to do so, due to our handling.

This was handled in https://github.com/nextauthjs/next-auth/security/advisories/GHSA-g5fm-jp9v-2432

**Comment by thomasmol** [comment]
That might be what is happening.
However, for one user a row in the user table was created correctly, and for the other time it happened a row in the user table was not created, but I do see a row in the verification token table for that user. They look like normal users (email addresses do not look like spam) and the scrambled/encoded ```Received callback url``` was the exact same for both cases, but from two different login attempts (two different email addresses) on different days.
I understand that the handling should fail if the callback url is altered, but i am wondering if the url that is generated by Authjs might be wrong. I saw in the code that the url is retrieved from the window object? I am not sure but maybe this has something to do with users using a VPN?
