### ISSUE TITLE
Best practice for using getServerSession with next 13.2 layouts

### ISSUE THREAD

**Issue by powderham** [nextauthjs/next-auth#7244]
### Question 💬

I have a layout in Next 13.2 which implements client side providers.

In order to provide a session to my session provider from the server, I want to pass it to the layout.

The docs suggest using `getServerSession` inside `getServerSideProps` but inside a layout we don't have access to the context.

I could wrap each page individually with the `SessionProvider`, and make the call to get the session on the server, but wanted to ascertain if there's a better way of doing this, leveraging the `Layout.tsx` pattern.

Greatly appreciated if anyone can point me in the right direction, or correct any wrong assumptions I might have.

### How to reproduce ☕️

From my mental model of how layouts work, I should fetch the session and pass it to the layout, which in turn would pass it to `Providers` but I can't see a straightforward way of doing this

```
# app/layout.tsx
const Layout = () => {
  <Providers>
    {children}
  </Providers>
}


# components/providers.tsx
'use client'
const Providers = () => {
  <SessionProvider>
    {children}
  </SessionProvider>
}

```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
There is a limited use case for `SessionProvider` in the App Router (working towards removing the need at all, but you probably already should be fine without it), it's fine to access the session wherever you need it via `getServerSession`.

**Comment by kneza23** [comment]
> There is a limited use case for `SessionProvider` in the App Router (working towards removing the need at all, but you probably already should be fine without it), it's fine to access the session wherever you need it via `getServerSession`.

I was wondering...

Is it better to use `getServerSession` on parent (layout/page) server component and pass it to the child client component or just call `useSession` inside client component directly?

**Comment by dutchsociety** [comment]
For me it is working! I don't have an RootLayout but working from an Segment Layout.

By using getServerSession am able to log the user data from authOptions. And then wrap my entire route from that layout in an if statement. 

@kneza23 my personal preference is wrapping an entire route that is behind an auth route in a server component instead of wrapping the page or component in an "use client".

> Just as an side note, make sure you call your callback properly. Without a proper setup, you might end up returning an NULL object.

`import { getServerSession } from "next-auth/next";

import { UserNav } from "@/components/shared/user.nav"
import { authOptions } from "@/lib/auth";

export default async function DashboardLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const data = await getServerSession(authOptions);
    console.log(data)

    // if (typeof window === "undefined") return null

    if (data) {
        return (
            <main className="py-32 container">
                <div className="container">
                    <div className="bg-white py-8">
                        <div className="max-w-7xl mx-auto px-4">
                            <UserNav />
                            {children}
                        </div>
                    </div>
                </div>
            </main>
        )
    } else {
        return (<p>Access denied</p>)
    }
}`
