### ISSUE TITLE
NextJS 13 Canary Releases Dependency Error

### ISSUE THREAD

**Issue by paurosellfarre** [nextauthjs/next-auth#7246]
### Environment

  System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 14.88 GB / 23.94 GB
  Binaries:
    Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 111.0.5563.148
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.39)
    Internet Explorer: 11.0.19041.1566

### Reproduction URL

none

### Describe the issue

<html>
<body>

npm ERR! code ERESOLVE
--
23:39:39.645 | npm ERR! ERESOLVE could not resolve
23:39:39.645 | npm ERR!
23:39:39.645 | npm ERR! While resolving: next-auth@4.19.2
23:39:39.646 | npm ERR! Found: next@13.3.1-canary.4
23:39:39.646 | npm ERR! node_modules/next
23:39:39.646 | npm ERR!   next@"^13.3.1-canary.4" from the root project
23:39:39.646 | npm ERR!
23:39:39.646 | npm ERR! Could not resolve dependency:
23:39:39.646 | npm ERR! peer next@"^12.2.5 \|\| ^13" from next-auth@4.19.2
23:39:39.646 | npm ERR! node_modules/next-auth
23:39:39.646 | npm ERR!   next-auth@"^4.19.2" from the root project
23:39:39.646 | npm ERR!   peer next-auth@"^4" from @next-auth/prisma-adapter@1.0.5
23:39:39.646 | npm ERR!   node_modules/@next-auth/prisma-adapter
23:39:39.646 | npm ERR!     @next-auth/prisma-adapter@"^1.0.5" from the root project
23:39:39.647 | npm ERR!
23:39:39.647 | npm ERR! Conflicting peer dependency: next@13.3.0
23:39:39.647 | npm ERR! node_modules/next
23:39:39.647 | npm ERR!   peer next@"^12.2.5 \|\| ^13" from next-auth@4.19.2
23:39:39.647 | npm ERR!   node_modules/next-auth
23:39:39.647 | npm ERR!     next-auth@"^4.19.2" from the root project
23:39:39.647 | npm ERR!     peer next-auth@"^4" from @next-auth/prisma-adapter@1.0.5
23:39:39.647 | npm ERR!     node_modules/@next-auth/prisma-adapter
23:39:39.647 | npm ERR!       @next-auth/prisma-adapter@"^1.0.5" from the root project
23:39:39.647 | npm ERR!
23:39:39.647 | npm ERR! Fix the upstream dependency conflict, or retry
23:39:39.648 | npm ERR! this command with --force, or --legacy-peer-deps
23:39:39.648 | npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
23:39:39.648 | npm ERR!
23:39:39.648 | npm ERR! See /vercel/.npm/eresolve-report.txt for a full report.

</body>
</html>

### How to reproduce

1. Create new NextJS project using npm and install canary release
npm install next@13.3.1-canary.4

2. Try to install next-auth
npm install next-auth

### Expected behavior

next-auth can be used on NextJS 13 canary release projects.

NextJS have solved a big bug on 13.3.1 canary release about generating static / server for nested routes. (It was working until 13.1 but not on 13.2

So I do personaly need canary release.

**Comment by balazsorban44** [comment]
You can simply ignore this via the `--force, or --legacy-peer-deps` flags. `next@canary` is not necessarily semver compliant (for a reason) so it can introduce breaking changes, so we likely won't add it to accepted peer dependencies officially. That said, I expect it to work in 95+% of the times, the only time it might be an issue if before bigger releases (like major version bumps) when iteration is quicker.
