### ISSUE TITLE
Access Patreon Pledge data in session

### ISSUE THREAD

**Issue by floppey** [nextauthjs/next-auth#7260]
### Question 💬

I'm trying to use next-auth to verify that people are subscribed to my patreon page before they access some restricted content.

I have the PatreonProvider set up like this, which seems to work when I try to log in using patreon.

```ts
import NextAuth from "next-auth";
import PatreonProvider from "next-auth/providers/patreon";

export const authOptions = {
  // Configure one or more authentication providers
  providers: [
    PatreonProvider({
      clientId: process.env.PATREON_ID,
      clientSecret: process.env.PATREON_SECRET,
      authorization: {
        params: { scope: "identity identity[email] identity.memberships" },
      },
    }),
  ],
  secret: process.env.NEXTAUTH_SECRET,
};

export default NextAuth(authOptions);
```

Specifying the scopes changes the default message from Patreon which usually only requests your public profile and email address, but now also asks for "your pledges".

![image](https://user-images.githubusercontent.com/6537326/232164501-838f7e01-aabc-468a-9e1a-895bc236fdae.png)

However I can't find any way to access this information again.  The data object from useSession only contains the users name, email and image.

```tsx
const { data, status } = useSession();

data.user.name; // John Doe
data.user.email; // john@example.com
data.user.identity; // undefined
data.user.memberships; // undefined

JSON.stringify(data);
/*
{
  "user": {
    "name": "John Doe",
    "email": "john@example.com",
    "image": "[valid img url]"
  },
  "expires": "[valid date]"
}
*/
```

### How to reproduce ☕️

Authenticate with the PatreonProvider and specify these scopes in the config:
 
```
authorization: {
  params: { scope: "identity identity[email] identity.memberships" },
},
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by floppey** [comment]
"Yes, I am willing to help answer this question in a PR" - But I have no idea where to start looking to make a change in this repo 🙈

**Comment by balazsorban44** [comment]
https://next-auth.js.org/getting-started/example#extensibility

https://next-auth.js.org/configuration/callbacks
