### ISSUE TITLE
defer setting cookies until login

### ISSUE THREAD

**Issue by leptonite** [nextauthjs/next-auth#7266]
### Description 📓

I want to be as conservative as possible when it comes to setting cookies. Therefore I used to set the session cookie after a successful login, and not already after the first page visit. Before login I didn’t need cookies at all.

Is this behavior possible with next-auth? Client side calls to `useSession` or `getSession` send GET requests to /api/auth/session and the response sets two cookies `next-auth.callback-url` and `next-auth.csrf-token` even if there’s no session. I didn’t find a way to disable this.

My feature request is to set cookies on successful login and not before. I don’t mind if it’s not the default behavior, but I’d like to be able to configure it this way. Or are there any security related reasons for doing it the way it’s currently done?

The reason I care about this is that I hate these cookie banners and popups that pollute the web nowadays. Without setting cookies there’s no need for them. It may be enough to display something like “We use cookies, but just for login. By logging in you agree.” next to the login button. This has to do with European law and may be different outside the EU.

### How to reproduce ☕️

It’s a feature request so there’s nothing to reproduce besides observing that using `useSession` leads to cookies.

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
These cookies are essential for the login process and need to be set before the login request. You can mark them as essential for the site to work correctly.

Read more here:

https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#double-submit-cookie

> When a user visits (even before authenticating to prevent login CSRF), the site should generate a (cryptographically strong) pseudorandom value and set it as a cookie on the user's machine separate from the session identifier.

**Comment by leptonite** [comment]
Thank you for clarification. Login CSRF is the issue I wasn’t aware of.

https://crashtest-security.com/csrf-login-attack/

> Since application developers assume that a cross-site request forgery attack is not feasible before the application server has authenticated a user, they commonly miss implementing CSRF defenses at the site’s login form. [...]

I have been one of these developers a few minutes ago and I’m glad to have been enlightened!

**Comment by yuis-ice** [comment]
I have the same need. The cookie concern increasing significantly in not only the EU but here and the world. 

The OP says, 
> My feature request is to set cookies on successful login and not before

but I, we don't need the cookies to be set after the successful login, I believe. Setting the cookies in the sign-in page visit (e.g. /api/auth/signin) is enough. Or buy clicking a button, or requesting to the API endpoint manually (programmatically) perhaps. 

I can't believe that it's not possible...

**Comment by yuis-ice** [comment]
Any progress? I think this is a serious issue.

**Comment by yuis-ice** [comment]
I worked around with `const { data: session } = (() => { try { return useSession() } catch { return { data: null } } })();` but this time I get `data' of '(intermediate value)(...)' as it is undefined.` error on the build time while development server is working..... can't get it.
