### ISSUE TITLE
Authorization error 403 : disallowed_useragent

### ISSUE THREAD

**Issue by Teyik0** [nextauthjs/next-auth#7269]
### Question 💬

I publish my project on linkedin, the problem is that when opening the link from the linkedin app, users get an authorization error and can't use the application. How to fix that ?

(I know that they can copy past the url directly to their browser to make it work but I prefer a solution for that problem)

Here is my repo : https://github.com/Teyik0/Enhanced-ChatGPT-Clone

Thanks in advance.

### How to reproduce ☕️

Go to Linkedin from the mobile app by clicking on the chatgpt clone project from my linkedin account : https://www.linkedin.com/in/th%C3%A9o-samarasinghe/

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
This is a Google limitation and unfortunately not something we can do anything about.

**Comment by felixcarmona** [comment]
I've recently encountered the same issue where some users reported being unable to complete their registration using Google login on my website after accessing the link through an app like LinkedIn. This only occurs on iOS. I've written a brief post explaining why this happens and how we can solve it. I hope you find it helpful: https://felixcarmona.com/solving-google-login-issues-linkedin-ios/
