### ISSUE TITLE
Unclear Documentation

### ISSUE THREAD

**Issue by yourcodesnotworking** [nextauthjs/next-auth#7271]
### What is the improvement or update you wish to see?

**I wanna see code examples for Next.js 13.2+**
Once you codes copied from your get started page, it should work.

Also, if you are trying give example for Next.js 13.2+,
- Please don't use `pages` directory, as it will be outdated in the future for sure.
- Please use `app` directory for API, as Office Documentention gave you complete example how to use API in `app` directory, don't scary to use.

1. Getting Started ??
  [Getting Started Page](https://authjs.dev/getting-started/introduction)
  NO CODE EXAMPLE WHATSOEVER!

3. "Credentials Provider is as simple as initializing it in the Auth.js configuration file" ?
  [Credentials authentication](https://authjs.dev/getting-started/credentials-tutorial)
  What about Next.js 13.2+? NO NEED? or anyone should understand your code automatically after seen your code example?

4. Ok next link: Database ??
  [Databases](https://authjs.dev/getting-started/databases)
  Do you mean those first two steps should definitely works, so we should choose if using database?
  Do I need come back to [next-auth page](https://next-auth.js.org/)? It's a kind of scary choice, cause you're saying "NextAuth.js is becoming Auth.js! 🎉 "

It seems your https://authjs.dev is for advanced developers to read. 
Does that mean if you're not advanced developers you should be abandoned on default?
  

### Is there any context that might help us understand?

1. Getting Started ??
  [Getting Started Page](https://authjs.dev/getting-started/introduction)

2. "Credentials Provider is as simple as initializing it in the Auth.js configuration file" ?
  (Credentials authentication)[https://authjs.dev/getting-started/credentials-tutorial]

3. Ok next link: Database ??
  [Databases](https://authjs.dev/getting-started/databases)

### Does the docs page already exist? Please link to it.
See above links, thanks.

**Comment by Dav3whit3** [comment]
There are maaaany 404 among the docs links as well

**Comment by balazsorban44** [comment]
Hmm. Upon re-reading, I actually think https://authjs.dev/getting-started/databases could be kept, but I cleaned it up and fixed a broken link. https://github.com/nextauthjs/next-auth/commit/9018939ee754304e802186809894a3728fc140f3
