### ISSUE TITLE
Next auth with next 13 app dir and Google provider

### ISSUE THREAD

**Issue by enyelsequeira** [nextauthjs/next-auth#7276]
### Environment

```
  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 60.53 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.7.0 - ~/.volta/tools/image/node/19.7.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 9.5.1 - ~/.volta/tools/image/npm/9.5.1/bin/npm
  Browsers:
    Brave Browser: 112.1.50.114
    Chrome: 112.0.5615.121
    Firefox: 111.0.1
    Safari: 16.3
```

### Reproduction URL

https://github.com/enyelsequeira/test-auth-13

### Describe the issue

I am trying to setup google provide with next-auth and prisma, following the example in the docs, and after a while of try and error I am not getting anywhere, 

```js
import { PrismaAdapter } from "@next-auth/prisma-adapter";
import NextAuth, { NextAuthOptions } from "next-auth";
import GithubProvider from "next-auth/providers/github";
import { prisma } from "../../../../server/db/client";
import { env } from "@/env/server.mjs";
import EmailProvider from "next-auth/providers/email";
import GoogleProvider from "next-auth/providers/google";

export const authOptions: NextAuthOptions = {
  secret: env.NEXTAUTH_SECRET,

  pages: {
    error: "/", 
    signIn: "/",
  },
  adapter: PrismaAdapter(prisma),

  providers: [
    GithubProvider({
      clientId: env.GITHUB_CLIENT_ID,
      clientSecret: env.GITHUB_CLIENT_SECRET,
      allowDangerousEmailAccountLinking: true,
    }),
    GoogleProvider({
      clientId: env.GOOGLE_CLIENT_ID,
      clientSecret: env.GOOGLE_CLIENT_SECRET,
    }),

    // EmailProvider({...workd fines })
  ],
  callbacks: {
    async signIn({ user, account, profile, email, credentials }) {
      console.log({
        signInUser: user,
        signInAccount: account,
        signInProfile: profile,
        signInEmail: email,
        signInCredentials: credentials,
      });
      if (account?.provider === "google") {
        console.log("Google sign-in detected.");
        console.log("User email:", user.email);
        console.log("Profile:", profile);
        console.log("Account:", account);
      }

      return true;
    },
    async jwt({ token, user, account, profile, isNewUser }) {
      console.log("jwt callback");
      if (user) {
        token.id = user.id;
        token.email = user.email;
      }
      console.log({ token, user, account, profile, isNewUser });
      return token;
    },

    async session({ session, user, token, newSession }) {
      console.log("session callback");

      console.log({ YESESSIONHERE: session, YESUSER: user, token, newSession });
      if (session.user) {
        session.user.id = user.id;
        session.user.email = user.email;
        // (session.user.id = token.sub as string),
        //   (session.user.email = token.email as string);
      }
      return session;
    },
  },
};
const handler = NextAuth(authOptions);
export { handler as GET, handler as POST };
```

All my providers work fine only the google one set up of google is here 
![image](https://user-images.githubusercontent.com/50872387/232338966-90afb9cc-1e33-4d3d-9287-06a774c36e13.png)

the only callback I am getting is the `signIn` and everything else for some reason gets ignored 

### How to reproduce

[REPRODUCTION_REPO](https://github.com/enyelsequeira/test-auth-13
)

all the code is in this repo clone and 
some env you might need, I am using planetscale for it 

```
DATABASE_URL=
SHADOW_DATABASE_URL=

NEXTAUTH_SECRET=
NEXTAUTH_URL=http://localhost:3000
# Githb
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
# Google
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
```

### Expected behavior

The expected behavior i should be able to sign in and create the user successfully on the db

**Comment by yourcodesnotworking** [comment]
After complete 2days of research on Google, I decided to give up Next-Auth.js Anyone have alternatives suggestion?

**Comment by enyelsequeira** [comment]
> After complete 2days of research on Google, I decided to give up Next-Auth.js Anyone have alternatives suggestion?

you could try clerk

**Comment by balazsorban44** [comment]
Hi, @enyelsequeira could you explain what the error is/provide more details? I was successfully logged in using your reproduction. <picture data-single-emoji=":thinking:" title=":thinking:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/thinking/a89918a57b536d5b.gif" alt=":thinking:" align="absmiddle"></picture>

User is also correctly created:

![image](https://user-images.githubusercontent.com/18369201/232449114-02a71858-9674-4390-8e95-8d453316c122.png)

**Comment by enyelsequeira** [comment]
> Hi, @enyelsequeira could you explain what the error is/provide more details? I was successfully logged in using your reproduction. <img alt=":thinking:" width="20" height="auto" src="https://camo.githubusercontent.com/c413cf9209c60ec34b1d99a356cbec4bb5fb80ea177d27a0f1344789315c1ee8/68747470733a2f2f656d6f6a692e736c61636b2d656467652e636f6d2f5430434151303054552f7468696e6b696e672f613839393138613537623533366435622e676966">
> 
> User is also correctly created:
> 
> ![image](https://user-images.githubusercontent.com/18369201/232449114-02a71858-9674-4390-8e95-8d453316c122.png)

Hello, sure. so the error I guess is when running the `callbacks` for some reason I am not seeing the session callback and also when console.log the session, you can see that is null, for some reason it does create the user though

and the url after the flow with google i get this 
`http://localhost:3000/?callbackUrl=http%3A%2F%2Flocalhost%3A3000%2F&error=OAuthAccountNotLinked`

![image](https://user-images.githubusercontent.com/50872387/232453374-c20d6c0a-e60c-480b-8fac-c66ba1c468e6.png)

![image](https://user-images.githubusercontent.com/50872387/232453468-d12e160b-27cc-44eb-a44b-329fa0a03feb.png)
![image](https://user-images.githubusercontent.com/50872387/232452884-6bc89db0-fd98-43a0-91c1-61b4d9cf4731.png)

**Comment by balazsorban44** [comment]
> I am wondering if you were able to sign in successfully and get the session or create the user-only thinking

Yes, I **was** logged in correctly.

`OAuthAccountNotLinked` is the key here that I was missing. It can happen for two reasons:

https://github.com/nextauthjs/next-auth/blob/e97b27414a5f7a4ca5192ed5ab014df549758d96/packages/next-auth/src/core/lib/callback-handler.ts#L137-L139

https://github.com/nextauthjs/next-auth/blob/e97b27414a5f7a4ca5192ed5ab014df549758d96/packages/next-auth/src/core/lib/callback-handler.ts#L197-L199

Can you check your logs to see which was it is?

I [see](https://github.com/enyelsequeira/test-auth-13/blob/c710f9b5c485ee949f809b68907d9c3a9e120c90/app/api/auth/%5B...nextauth%5D/route.ts#L23) you are using `allowDangerousEmailAccountLinking: true` for GitHub, but not for Google. Is that on purpose? It's likely related.

Could you explain the exact flow you expect to be supported here to understand the issue more?

**Comment by enyelsequeira** [comment]
> > I am wondering if you were able to sign in successfully and get the session or create the user-only thinking
> 
> Yes, I **was** logged in correctly.
> 
> In your case, `OAuthAccountNotLinked` is the key here that I was missing from the reproduction. It can happen for two reasons:
> 
> https://github.com/nextauthjs/next-auth/blob/e97b27414a5f7a4ca5192ed5ab014df549758d96/packages/next-auth/src/core/lib/callback-handler.ts#L137-L139
> 
> https://github.com/nextauthjs/next-auth/blob/e97b27414a5f7a4ca5192ed5ab014df549758d96/packages/next-auth/src/core/lib/callback-handler.ts#L197-L199
> 
> Can you check your logs to see which one was it?
> 
> I [see](https://github.com/enyelsequeira/test-auth-13/blob/c710f9b5c485ee949f809b68907d9c3a9e120c90/app/api/auth/%5B...nextauth%5D/route.ts#L23) you are using `allowDangerousEmailAccountLinking: true` for GitHub, but not for Google. Is that on purpose? It's likely related.
> 
> Could you explain the exact flow you expect to be supported here to understand the issue more?
> 
> Note: Since you are using a custom error page, you have to make sure to give the user visual feedback on errors, or handle them yourself.

I also thought that the issue could be with the link of accounts, so tried removing it from github provider and still the error occurs, however when i add the ` allowDangerousEmailAccountLinking: true` I get another error, at this point, not sure if the error is with `prisma` 

regarding the flow I want to support would be if the user logs in with github and the email is the same as the google the accounts should be linked 


![image](https://user-images.githubusercontent.com/50872387/232458205-7f9b1784-31fe-4d44-8ad2-17beb38148da.png)

**Comment by balazsorban44** [comment]
The new error comes from the fact that one of the values in the DB is longer than what your Prisma schema allowed. Likely `access_token` or `id_token`.

**Comment by balazsorban44** [comment]
So you expect the user to register (first sign-in) with Google and then, later on, be able to connect GitHub to it, right?

The way I can reproduce the issue is if I first sign in with GitHub (which will create the user), then sign out, then use Google to sign-in with the same email address.

Based on your code, this would be expected though, as you did not allow linking the google account explicitly with `allowDangerousEmailAccountLinking`.

I'm unable to reproduce the issue in another way.

**Comment by enyelsequeira** [comment]
> The new error comes from the fact that one of the values in the DB is longer than what your Prisma schema allowed. Likely `access_token` or `id_token`.

regarding this, I was following the schema provided in the example 
![image](https://user-images.githubusercontent.com/50872387/232463215-1441f295-3e88-4833-8ede-bfce6894f9dc.png)

**Comment by enyelsequeira** [comment]
> Based on your code, this would be expected though, as you did not allow linking the Google account explicitly with `allowDangerousEmailAccountLinking`.

Yeah this part makes sense to me

**Comment by enyelsequeira** [comment]
@balazsorban44  I am closing the issue, found the mistake, sorry about that

```js
model Account {
  id                String  @id @default(cuid())
  userId            String
  type              String
  provider          String
  providerAccountId String
refresh_token     String? @db.Text
  access_token      String? @db.Text
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String? @db.Text
  session_state     String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
  @@index([userId])
}
```

**refresh_token     String? @db.Text
  access_token      String? @db.Text
  id_token          String? @db.Text**

**Comment by balazsorban44** [comment]
Seems like `id_token` was missing `@db.Text`, indeed. :+1:

Glad that it worked out! Let me know if you need more help or have any other feedback! :pray:
