### ISSUE TITLE
Signin session exposed between browser windows

### ISSUE THREAD

**Issue by khteh** [nextauthjs/next-auth#7280]
### Environment

  System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Memory: 59.74 GB / 70.39 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 19.8.1 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.6.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 112.0.5615.121
    Firefox: 112.0

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

Build and start `next-auth-example`, signin successfully with a credential. Change `CLIENT_ID` and `CLIENT_SECRET` to different set of valid values, build and start a `next-auth-example` on a different port#. Try to sign in in a separate browser window and it will show `"signed in as"` the credential of the previous signed in user.

### How to reproduce

Build and start `next-auth-example`, signin successfully with a credential. Change `CLIENT_ID` and `CLIENT_SECRET` to different set of valid values, build and start a `next-auth-example` on a different port#. Try to sign in in a separate browser window and it will show `"signed in as"` the credential of the previous signed in user.

### Expected behavior

The second signin should start afresh, redirecting to the provider for the user to input credentials instead of showing being "signed in"

**Comment by balazsorban44** [comment]
This is the intended behavior. It avoids a user accidentally staying logged in in one tab.

We sync tab/window states by sending an event that will refetch the session in those other tabs/windows

**Comment by khteh** [comment]
It happens for different applications with different `NEXTAUTH_URL`

**Comment by khteh** [comment]
I really test with totally different set of values. Do you want to have a second look?
