### ISSUE TITLE
Please update the NextAuth docs typescript link as current link is outdated

### ISSUE THREAD

**Issue by k3ithloh** [nextauthjs/next-auth#7288]
### What is the improvement or update you wish to see?

The link to the NextAuth Typescript example on https://next-auth.js.org/getting-started/typescript is outdated.

The current Repo link on the site is https://github.com/nextauthjs/next-auth-typescript-example and should be changed to https://github.com/nextauthjs/next-auth-example instead

### Is there any context that might help us understand?

The NextAuth Docs link for the typescript example is linked to a deprecated example

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/getting-started/typescript

**Comment by balazsorban44** [comment]
Updated, thanks! https://github.com/nextauthjs/next-auth/commit/cb916f4848511b458f5cf20ea5b614943681530d
