### ISSUE TITLE
Does `NEXTAUTH_URL` make any difference on port#?

### ISSUE THREAD

**Issue by khteh** [nextauthjs/next-auth#7296]
### Question 💬

Starting 2 different instances of https://github.com/nextauthjs/next-auth-example on different port numbers behaves strangely. The second instance logs out the first and redirects to http://localhost:3000/api/auth/signin?csrf=true

### How to reproduce ☕️

Starting 2 different instances of https://github.com/nextauthjs/next-auth-example on different port numbers behaves strangely. The second instance logs out the first and redirects to http://localhost:3000/api/auth/signin?csrf=true

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by sixdjango** [comment]
me to, how to do fix it
