### ISSUE TITLE
Using next-auth in the middleware causes problems in standalone mode

### ISSUE THREAD

**Issue by meesvandongen** [nextauthjs/next-auth#7300]
### Environment

next@13.3.0
next-auth@4.22.0

### Reproduction URL

https://github.com/meesvandongen/next-auth-repro-standalone-middleware

### Describe the issue

Including `export { default } from "next-auth/middleware"` causes an error in standalone mode: 
```sh
warn  - Compiled with warnings

./node_modules/next/dist/server/web/spec-extension/image-response.js
A Node.js API is used (process.turbopack at line: 47) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime

Import trace for requested module:
./node_modules/next/dist/server/web/spec-extension/image-response.js
./node_modules/next/server.js
./node_modules/next-auth/next/middleware.js
./node_modules/next-auth/middleware.js
```

This will in turn lead to these modules not being found by nextjs runtime.

It seems that because of the bundling strategy? ImageResponse is somehow included in the import. Doing so manually
```ts
import { NextResponse, ImageResponse } from "next/server"

export default function middleware(req, res) {
  const response = NextResponse.next()
  ImageResponse;
  return response
}
```

Will cause a similar error.

If we inspect the output of the bundler, we can see the following, which is likely the cause:
```
var _server = require("next/server");
```

An option would be to swap babel for `tsup` or just `tsc` to produce esm modules.

### How to reproduce

Add a middleware.js file
```
export { default } from "next-auth/middleware"
```

set next.config.js
```
/** @type {import('next').NextConfig} */
module.exports = {
  output: 'standalone',
}
```

run the build

### Expected behavior

The modules which are not supported are not included in the build.

**Comment by TrevorThomp** [comment]
I had the same issue with Nextjs-auth0 middleware and it looks like this auth as well. I have an open issue in Nextjs for this same error that you can track as well:

https://github.com/vercel/next.js/issues/48302

**Comment by balazsorban44** [comment]
Closing in favor of https://github.com/vercel/next.js/issues/48302
