### ISSUE TITLE
The new `update` function from `useSession` triggers infinite re-renders

### ISSUE THREAD

**Issue by HamedBahram** [nextauthjs/next-auth#7307]
### Environment

  "dependencies": {
    "next": "^12.3.4",
    "next-auth": "^4.22.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
  },

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

The new `update` function from the `useSession` hook triggers an infinite loop when used inside `useEffect` 

### How to reproduce

Try the `update` function inside an effect.

### Expected behavior

Should only reload the session, without causing infinite re-renders

**Comment by luisjuniorj** [comment]
> ### Environment
> "dependencies": { "next": "^12.3.4", "next-auth": "^4.22.1", "react": "17.0.2", "react-dom": "17.0.2", },
> 
> ### Reproduction URL
> https://github.com/nextauthjs/next-auth-example
> 
> ### Describe the issue
> The new `update` function from the `useSession` hook triggers an infinite loop when used inside `useEffect`
> 
> ### How to reproduce
> Try the `update` function inside an effect.
> 
> ### Expected behavior
> Should only reload the session, without causing infinite re-renders

did you solve this?

**Comment by HamedBahram** [comment]
Avoid calling the `update` function in `useEffect,` and it won't cause re-renders. My workaround was to call the `update` function in response to a button click.
