### ISSUE TITLE
Using `getServerSession` with the Advanced initialization

### ISSUE THREAD

**Issue by HamedBahram** [nextauthjs/next-auth#7308]
### What is the improvement or update you wish to see?

How should we use the new `getServerSession` function when I'm using the advanced initialization to access the `req` object inside my authOptions (specifically in callbacks); since we need to export the `authOptions` separately to be used in `getServerSession` function calls? 

/pages/api/auth/[...nextauth].js
```
import NextAuth from 'next-auth'

export const authOptions = {
 providers: [],
 callbacks: {
  async jwt({token}) {
      const {query} = req.query
  }
}

export default async function auth(req, res) {
  return await NextAuth(req, res, authOptions)
}
```

### Is there any context that might help us understand?

Trying to access the request object inside my authOptions — callbacks, to be specific. With the new way of exporting the authOptions to be used when using `getServerSession`, how should I go about exporting the `authOptions` while also being able to access the `req` object inside the `callbacks` option?

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/configuration/nextjs#getserversession

**Comment by balazsorban44** [comment]
Hi, I wonder what would be the use case here since now you can update the session programmatically?

https://next-auth.js.org/getting-started/client#updating-the-session

**Comment by HamedBahram** [comment]
> Hi, I wonder what would be the use case here since now you can update the session programmatically?

Hi @balazsorban44, 

Thank you for your response, and contribution to this library. 

My use case is actually related to updating the session, mainly for two reasons:

1. The new `update` function causes infinite re-renders if used inside effects
2. How would you update the session on the server, say in `getServerSideProps` or in server components?

Thank you

**Comment by pbell23** [comment]
Hey, I think it has been answered here : [](https://github.com/nextauthjs/next-auth/discussions/6912#discussioncomment-6025442)

**Comment by HamedBahram** [comment]
> Hey, I think it has been answered here : [#6912 (comment)](https://github.com/nextauthjs/next-auth/discussions/6912#discussioncomment-6025442)

Thanks!

**Comment by ThangHuuVu** [comment]
closing this since it's answered as @pbell23 mentioned.
