### ISSUE TITLE
Simplify code/examples

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#731]
I have seen this many places, like [this example code](https://next-auth.js.org/configuration/callbacks#sign-in-callback):

```js
signIn: async (user, account, profile) => {
  const isAllowedToSignIn = true
  if (isAllowedToSignIn) {
    return Promise.resolve(true)
  } else {
    // Return false to display a default error message
    return Promise.resolve(false)
    // You can also Reject this callback with an Error or with a URL:
    // return Promise.reject(new Error('error message')) // Redirect to error page
    // return Promise.reject('/path/to/redirect')        // Redirect to a URL
  }
}
```

When defining an async function, the returned value is automatically resolved, meaning one could refactor the above code. (Notice that throwing an Error would probably also feel more natural):

```js
async signIn(user, account, profile) {
  const isAllowedToSignIn = true
  if (isAllowedToSignIn) {
    return true
  } else {
    // Return false to display a default error message
    return false
    // You can also Reject this callback with an Error or with a URL:
    // throw new Error('error message')) // Redirect to error page
    // return Promise.reject('/path/to/redirect')        // Redirect to a URL
  }
}
```

This may be only a personal preference, but I think it would also be easier to parse the code for newcomers. With the rise of "async/await", maybe there is lesser need of using `Promise`s all-together. Any special reason I am unaware for using `Promise.resolve()` everywhere?

**Comment by iaincollins** [comment]
> Any special reason I am unaware for using Promise.resolve() everywhere?

Good question! This has been asked before and yes, actually it is deliberate.

Internally, we try and avoid this in the library (and there are linter rules configured to discourage this) but the intent is that it's helpful re-enforcing to people that these functions are async and you can consequently do interesting things inside them.

The virtue of doing this is debatable, but a primary driver of the documentation is to reduce the amount of support overhead - as that is where the majority of time is spent by contributors on this project.

**Comment by balazsorban44** [comment]
I would argue, that #897 just proved that this encourages using callbacks over `async/await`, which created the issue there.
