### ISSUE TITLE
When OAuth Provider userinfo create a noop function, unable to assign void type

### ISSUE THREAD

**Issue by blan19** [nextauthjs/next-auth#7312]
### Question 💬

As introduced in [userinfo](https://next-auth.js.org/configuration/providers/oauth#userinfo-option), I tried the noop function, but I got a type error (Type 'void' is not assignable to type 'Awaitable<Profile>').

I'm updating and using it according to the code below.
Is there a best practice?

```typescript
// next-auth/providers/oauth.ts
// before update

declare type EndpointRequest<C, R, P> = (context: C & {
    /** `openid-client` Client */
    client: Client;
    /** Provider is passed for convenience, ans also contains the `callbackUrl`. */
    provider: OAuthConfig<P> & {
        signinUrl: string;
        callbackUrl: string;
    };
}) => Awaitable<R>;
```

```typescript
// next-auth/providers/oauth.ts
// after update

declare type EndpointRequest<C, R, P> = (context: C & {
    /** `openid-client` Client */
    client: Client;
    /** Provider is passed for convenience, ans also contains the `callbackUrl`. */
    provider: OAuthConfig<P> & {
        signinUrl: string;
        callbackUrl: string;
    };
}) => Awaitable<R> | void ;
```

### How to reproduce ☕️

[CodeSandbox](https://codesandbox.io/s/bold-murdock-6fz09w?file=/pages/api/auth/%5B...nextauth%5D.ts)

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by ThangHuuVu** [comment]
sounds good, do you want to open a PR?

**Comment by blan19** [comment]
> sounds good, do you want to open a PR?

thank you for the reply, yes want to open a PR

**Comment by ThangHuuVu** [comment]
@blan19 go for it!
