### ISSUE TITLE
Cypress.Cookies.defaults already removed

### ISSUE THREAD

**Issue by ImBIOS** [nextauthjs/next-auth#7315]
### What is the improvement or update you wish to see?

https://github.com/nextauthjs/next-auth/blob/039a14d99261955be3b0d3433dd603f639a6efe6/docs/docs/guides/testing/testing-with-cypress.md?plain=1#L113

this method already removed in the Cypress.

### Is there any context that might help us understand?

https://docs.cypress.io/api/cypress-api/cookies

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/tutorials/testing-with-cypress

**Comment by dan-mba** [comment]
I would like to work on this issue.

Should I just remove the deprecated `Cookies.default` function call?
The cypress docs mention using `cy.session` to cache & restore cookies.
But it takes a [setup function](https://docs.cypress.io/api/commands/session#Usage) and I am not sure how that would relate to the current test.

From a brief reading of the docs, putting all of the function inside `it` as the `cy,session` setup function might be the correct solution.
