### ISSUE TITLE
Combined Auth

### ISSUE THREAD

**Issue by BadCoder1337** [nextauthjs/next-auth#732]
**Your question**
How to implement combined auth in JWT mode?

**What are you trying to do**
My app needs google and discord auth at the same time, but with JWT callback as below when i logins other service first service data gets replaced.

Which callback should i tweak to get things work?
```ts
switch (account.provider) {
    case "discord": {
        const jwt = { 
            expires: token.expires,
            google: token.google,
            discord: {
                id: account.id,
                tag: `${profile.username}#${profile.discriminator}`,
                av: user.image,
                accessToken: account.accessToken
            }
        }        
        return Promise.resolve(jwt)
    }
    case "google": {
        const jwt = { 
            expires: token.expires,
            discord: token.discord,
            google: {
                name: profile.name,
                email: profile.email,
                av: user.image,
                accessToken: account.accessToken
            }
        }        
        return Promise.resolve(jwt)
    }

    default: return Promise.resolve(token)
}
```

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
Hi there!

The short answer is, without a database, unfortunately this isn't supported (only the details for the last provider are saved) and I don't think it's possible with the callbacks alone. This is a limitation and something that would make a good feature request though - there isn't any technical reason it isn't possible to persist JWT data when signing in with an additional provider; though at some point the size of the JWT will become an issue (as total cookie size for a domain is 4 KB in most browsers).

For some providers, like Google, you may in practice need a database (e.g. as Refresh Tokens are only issued on first sign in and need to be saved somewhere), that would certainly make things easier. Currently multiple provider sign in is supported, just not very explicitly (e.g. the data model and API for linking works fine, though there are no API endpoints for unlinking accounts and the built in sign in page doesn't currently indicate if you are already signed in). Improved functionality for this is expected to drop in the next release.

As a way around it in the mean time, you could use an API call in your app to read the JWT and persist data from it in *your own* JWT and keep adding providers to it, but I would advocate persisting data to a database in this kind of context.
