### ISSUE TITLE
Prisma: GitHub token link account error

### ISSUE THREAD

**Issue by SkippyHub** [nextauthjs/next-auth#7321]
### Adapter type

@next-auth/prisma-adapter

### Environment

docker VSC instance
{
	"name": "Node.js & TypeScript",
	"image": "mcr.microsoft.com/devcontainers/typescript-node:0-18"
}

```
node ➜ /workspaces/nextauthtest $ pnpx envinfo --system --binaries --browsers --npmPackages "next,react,next-auth,@auth/*"
../.pnpm-store/v3/tmp/dlx-55533          |   +1 +
../.pnpm-store/v3/tmp/dlx-55533          | Progress: resolved 1, reused 0, downloaded 1, added 1, done

  System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (5) arm64 unknown
    Memory: 2.67 GB / 7.67 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm

```

### Reproduction URL

https://github.com/SkippyHub/next-auth-test-t3-github

### Describe the issue

Adapter issue can't use schema @map to handle data transform, I can't update the GH provider import, but updating prisma adapter linked works. see expected behavior for temp fix. Is there a correct method how to do transforms for token handling?

```
Unknown arg `refresh_token_expires_in` in data.refresh_token_expires_in for type AccountUncheckedCreateInput. Did you mean `refresh_token_expires_at`? Available args:
type AccountUncheckedCreateInput {
  id?: String
  userId: String
  type: String
  provider: String
  providerAccountId: String
  refresh_token?: String | Null
  access_token?: String | Null
  refresh_token_expires_at?: Int | Null
  token_type?: String | Null
  scope?: String | Null
  id_token?: String | Null
  session_state?: String | Null
}
```

### How to reproduce

I'm using a VSC container so you can add the vsc docker addon and clone gh
pnpm i 
update your .env with github auth app
pnpm dev
login with your github on the browser

### Expected behavior

expected behavior no issue with linking accounts with GH token, 
the prisma adapter doesn't work using schema updated mapping,  ( commented out for debug work around).

    expires_at        Int? //@map("refresh_token_expires_in")
    
```
    model Account {
    id                String  @id @default(cuid())
    userId            String
    type              String
    provider          String
    providerAccountId String
    refresh_token     String? // @db.Text
    access_token      String? // @db.Text
    expires_at        Int? //@map("refresh_token_expires_in")
    token_type        String?
    scope             String?
    id_token          String? // @db.Text
    session_state     String?
    user              User    @relation(fields: [userId], references: [id], onDelete: Cascade)
    @@unique([provider, providerAccountId], name: "provider_providerAccountId")
}
```

here is the fix expected behavior, I am changing the adapter code to transform the expected GH token. 

/workspaces/nextauthtest/node_modules/.pnpm/@next-auth+prisma-adapter@1.0.6_mj4zmq54qgbwr7klxt7lbfwdhu/node_modules/@next-auth/prisma-adapter/dist/index.js:221:42
```
  linkAccount:  (data) => { 
            data.expires_in = data.refresh_token_expires_in || 0;
            if (data.refresh_token_expires_in) {
              delete data.refresh_token_expires_in
            }
             p.account.create({ data })
        },
        // linkAccount: (data) => p.account.create({ data }),
```

**Comment by SkippyHub** [comment]
I am partly uploading this work around (see expected behavior) for others to see as other solutions are not clear or difficult, please not you can likely change this simple code snippet to modify/swap/transform other errors relating to token mapping

**Comment by balazsorban44** [comment]
You can add `refresh_token_expires_in` to your `Account` model in the Prisma schema.

Mentioned in the docs: https://next-auth.js.org/providers/github

**Comment by SkippyHub** [comment]
I tried this method of adding the role, and also the map method
    expires_at        Int? //@map("refresh_token_expires_in")
, I also tried to use the inverse 
   refresh_token_expires_in        Int? //@map("expires_at")

**Comment by balazsorban44** [comment]
refresh_token_expires_in and expires_at are not the same values. You should not map one to the other.

But yes, the linked comment is a better solution, if you don't need the `refresh_token_expires_in` value.

I'm working on a better API for this.
