### ISSUE TITLE
Login and Issue User Session via Custom page API route

### ISSUE THREAD

**Issue by kamerondotcom** [nextauthjs/next-auth#733]
Hello,

Love the package. I'm trying to make create an AJAX login flow with my Next 9 / Next Auth setup. I've got everything setup including my csrf verification, etc. But I can't seem to create the session that get's stores as a JWT token on the front end. I realize I need to probably pass some kind of token back to the front end via JSON with the result of a login attempt fetch request but I'm not sure what to pass back down to the Front end and how to initiate that session as a cookie, etc.

I'm using Next 9.5.3 and Next Auth 3.1.0.

Any insight?

**Comment by iaincollins** [comment]
From this description I don't understand what you are trying to do.

Please use the issue template and update the subject so we can help.
