### ISSUE TITLE
How to handle expired token in middleware?

### ISSUE THREAD

**Issue by serg06** [nextauthjs/next-auth#7336]
### Question 💬

Hello!

I'm using NextAuth, I have a middleware to protect some routes behind auth, and I have token refreshing set up.

If the token expires overnight, then I navigate directly to a protected route, it triggers middleware **before** refreshing the token! What are we supposed to do in that case, allow the user through even though it's expired?

This seems like a really common situation, but I can't find anything in [docs](https://next-auth.js.org/configuration/nextjs#middleware) or online! Would love to understand what we're supposed to do. Thanks!

### How to reproduce ☕️

```ts
// [...nextauth].ts
export const authOptions: NextAuthOptions = {
  pages: {
    signIn: '/auth/signin',
  },
  providers: [
    ...
  ],
  callbacks: {
    async jwt({token, account}) {
      if (account) {
        token.accessToken = account.access_token!;
        token.accessTokenExpires = account.expires_at! * 1000;
        token.refreshToken = account.refresh_token!;
      }

      // Not expired
      if (Date.now() < token.accessTokenExpires) {
        return token;
      }

      // Refresh the token
      const refreshed_token = await refreshTwitchToken(token.refreshToken);

      return {
        ...token,
        accessToken: refreshed_token.access_token,
        accessTokenExpires: refreshed_token.expires_in * 1000 + Date.now(),
        refreshToken: refreshed_token.refresh_token,
      };
    },
    async session({session, token}) {
      session.user.accessToken = token.accessToken;
      session.user.accessTokenExpires = token.accessTokenExpires;
      return session;
    },
  },
};
```

```ts
// middleware.ts
export default withAuth(
  async function middleware(req: NextRequestWithAuth) {
    // PROBLEM: If this function is hit before `jwt()` , the token is expired!

    // Get the token from the request
    const token = req.nextauth?.token;

    // Verify auth
    if (isAdminRoute(req)) {
      if (!token) {
        // Redirect to unauthorized
        return NextResponse.redirect(new URL('/error/unauthorized', req.url));
      }
      if (Date.now() < token.accessTokenExpires) {
        // PROBLEM: What am I supposed to do here?
      }
    }

    return NextResponse.next();
  }
);
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
This is currently expected, the implementation does not update the session. We are working on a solution for the upcoming `@auth/nextjs` library that will handle session token rotation via middleware.

**Comment by Tobi-mmt** [comment]
I have the exact same issue. Is there a workaround for that? 
Returning a `false` in the `authentication` callback does not work for me. Looks like it is redirecting in a loop.

```tsx
export default withAuth({
  callbacks: {
    authorized: ({ req, token }) => {
      const isTokenExpired =
        !token || !token?.expiresAt || new Date() > new Date(token.expiresAt * 1000)

      if (isTokenExpired) {
       // this does NOT work
        return false
      }

      if (!!token) return true

      return false
    },
  },
})
```

Any idea how to refresh the token or redirect to the login page manually here?

**Comment by DanTheManWillis** [comment]
Hi all, did anyone ever solve this?

I'm currently running into the exact same issue where the middleware allows the site to load despite the token being expired. Every attempt I've made to check for expired tokens and handle these within the middleware have just resulted in an endless redirect loop.
