### ISSUE TITLE
The useSession method does not monitor session changes in real time

### ISSUE THREAD

**Issue by zhenujt** [nextauthjs/next-auth#7338]
### Question 💬

If the customer has been operating, I will run getSession() to get the latest accessToken before the request, and then update the valid duration of the accesstoken in the JWT callback function, and then I use useSession in the client component to get the session, but he is in subsequent operations It has not been triggered again. What should I do to get the latest time duration on the client page in real time? I am implementing the front-end countdown pop-up function when the customer does not operate for a long time

### How to reproduce ☕️

  const { data: session, update: updateSession, status }: SessionContextValue =
    useSession();
    
    Requested /api/auth/session, accessTokenExpires has changed, but useSession did not monitor it, so I can't get the latest accessTokenExpires

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
You can trigger a session revalidation, check out https://next-auth.js.org/getting-started/client#updating-the-session
