### ISSUE TITLE
How can I pass extra headers to the signIn and signOut methods

### ISSUE THREAD

**Issue by jrmdayn** [nextauthjs/next-auth#7340]
### Question 💬

Is it possible to pass extra headers to the `signIn` and `signOut` methods that would be added to the POST request?
I have a Blitzjs app which requires a csrf token to be present as a header in order to talk to the api routes.

Happy to send a PR if it is not possible at the moment 😄 

### How to reproduce ☕️

```
<button 
  onClick={()=> signIn('google', {headers: {'anti-csrf': blitzCsrfToken}})}>
  Signin with Google
</button>

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
NextAuth.js has built-in CSRF protection, using the [double submit method](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#double-submit-cookie).


See https://github.com/nextauthjs/next-auth/blob/7c44d916eda921aad68923841d6c1689c00f94d3/packages/next-auth/src/react/index.tsx#L212-L289

If you feel this method is insufficient, you can re-implement the `signIn` function in a few lines, but we would like to keep the API limited.

**Comment by jrmdayn** [comment]
Yes I saw that there's already csrf protection with NextAuth. I can't go around it for Blitz either, so I have to find a way. What you suggest is totally acceptable, so will do it this way, thanks.

**Comment by balazsorban44** [comment]
Thanks for understanding! :green_heart:
