### ISSUE TITLE
Does next-auth support Next 13 apps with SSG pages?

### ISSUE THREAD

**Issue by netsrikc** [nextauthjs/next-auth#7341]
### Question 💬

Next 13 now supports `output: export` which unblocks SSG. However, after I installed next-auth and added [...nextauth].ts inside pages/api/auth file, starting the server gives me the following error
```
API Routes cannot be used with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export
```

Should I configure a project differently to utilize next auth? I was able to use next auth and have SSG pages in next 12.

### How to reproduce ☕️

- Clone the [next-auth-typescript-example](https://github.com/nextauthjs/next-auth-typescript-example)
- Add next.config.ts to root with the following:
```
/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'export',
};

module.exports = nextConfig;
```
- Run `npm run dev`
- Encounters the error above

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by netsrikc** [comment]
An update - I have downgraded the version of next in app to v12.3.4 and everything appears to be working, is it on the roadmap to support next 13 apps with SSG?

**Comment by balazsorban44** [comment]
As the [documentation page](https://nextjs.org/docs/advanced-features/static-html-export#unsupported-features) in the error message shows, API Routes (and Route Handlers) require a server, which NextAuth.js uses for a secure operating environment.

It is therefore unfeasible for NextAuth.js to support an environment where a server is not available.

**Comment by tebuevd** [comment]
Hi @balazsorban44 !

What would you recommend for a website that has both SSR parts (https://example.com/app) and SSG parts (https://example.com/blog) that share a NavBar with an Avatar component?

The Avatar component uses `useSession()` to check if the user is signed in and either displays a "Sign In" button or an avatar of the user.

What I'm finding right now in my project is when a signed-in user navigates from /dashboard to /blog, the Avatar component no longer knows that it is signed in.

Is this something that is fixable on my sides?

Note: not sure if this is important, but /dashboard is built using Next 13 Pages Router and the /blog is using Next 13 App Router
