### ISSUE TITLE
BattleNet battlenet?error=unsupported_response_type

### ISSUE THREAD

**Issue by APegram** [nextauthjs/next-auth#735]
**Your question**
Has anyone else experienced this and know how to fix this? Currently just setting up a NextJS application using Next-Auth.

**What are you trying to do**
Just trying to get the login to work, but never get to login, and get redirected straight to the error page.

**Comment by APegram** [comment]
Ah, I see a related ticket.

**Comment by mtt87** [comment]
@APegram how did you solve this error?

I've just added the code mentioned in the docs and I get the same error

```js
  providers: [
    Providers.BattleNet({
      clientId: process.env.BATTLENET_CLIENT_ID,
      clientSecret: process.env.BATTLENET_CLIENT_SECRET,
      region: process.env.BATTLENET_REGION,
    }),
  ],
```

**Comment by mtt87** [comment]
Update: I found that for some reason even if I have the latest version installed `"next-auth": "^3.1.0",` the fix that added `?response_type=code` is not there 🤔 

That said, even with this when I get to the exchange auth code step, it fails.

Did you manage to get to the end of this?

**Comment by mtt87** [comment]
Ok I managed to make it work, I installed another package after I made the change and it overwrote the `battlenet.js` changes I've made.

The change I'm talking about is the one in this PR
https://github.com/nextauthjs/next-auth/pull/637/files

I'm investigating now why the latest version of the package doesn't have this fix

**Comment by APegram** [comment]
Yeah, unfortunately when you update your npms or install new ones, you’ll
need to fix it again ;(

**Comment by BrennenRocks** [comment]
Before next-auth 3.2.0 comes out this is my next-auth options for BattleNet. I am only using the US region at the moment with mongodb and mongoose. You don't need to update the battlenet.js in the package. This will spread the object into the provider and overwrite it with your options and keep the rest of the defaults.

```
const options: InitOptions = {
  providers: [
    Providers.BattleNet({
      clientId: process.env.BATTLENET_CLIENT_ID!,
      clientSecret: process.env.BATTLENET_CLIENT_SECRET!,
      region: 'us',
      scope: 'openid wow.profile',
      authorizationUrl: "https://us.battle.net/oauth/authorize?response_type=code"
    })
  ],
  database: process.env.MONGODB_URI,
  callbacks: {
    signIn: async (user, account, profile) => {
      // Next-Auth does not update the access token if the user has revoked Raidy Check then relogs in

      // We manually update the access token
      // BattleNet currenlty does not have a refresh token. No need to update it as well

      await dbConnect();
      await Account.findOneAndUpdate({ providerAccountId: account.id }, { accessToken: account.accessToken });

      return Promise.resolve(true);
    }
  }
};
```
