### ISSUE TITLE
`signIn()` error/cancel ends up in `api/auth/signin?error=Callback#_=_`

### ISSUE THREAD

**Issue by khteh** [nextauthjs/next-auth#7359]
### Question 💬

How to properly handle errors on `signin()`? For example, cancelling the signIn operation from the provider should redirect back to the login or home page instead of ending up at `api/auth/signin?error=Callback#_=_`

### How to reproduce ☕️

Launch https://github.com/nextauthjs/next-auth-example and then cancel the signin or provide invalid credentials. How to properly handle signin error so that it could redirect to proper page?

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by ThangHuuVu** [comment]
When checking our deployed example https://next-auth-example.vercel.app/, I only see api/auth/signin?error=Callback 
we are going to need a proper reproduction with steps to follow to check the issue. I'm going to close this for now, but happy to reopen if you could provide one 👀 
you could also check https://next-auth.js.org/configuration/pages#sign-in-page for how to customize your login page handle different errors.
