### ISSUE TITLE
How do you prevent new signups?

### ISSUE THREAD

**Issue by jesperordrup** [nextauthjs/next-auth#736]
How do you prevent new signups?

Im creating a setup where you should not be able to create a new user. Im using email magic links provider.

**Feedback**

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x ] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by Xodarap** [comment]
> TIP
If you only want to allow users who already have accounts in the database to sign in, you can check for the existance of a user.id property and reject any sign in attempts from accounts that do not have one.

> If you are using NextAuth.js without database and want to control who can sign in, you can check their email address or profile against a hard coded list in the signIn() callback.

https://next-auth.js.org/configuration/callbacks

**Comment by LoriKarikari** [comment]
@jesperordrup were you able to make it work?

**Comment by jschuur** [comment]
Based on the update in #1737, that checking user.id is not reliable, it looks like you can look for the presence of any custom field that is in your local user schema, but not any of the providers you use. Just set a default for that field in your schema definition. I'm using the recommended [Prisma schema](https://next-auth.js.org/schemas/adapters#prisma-schema) as a basis, so I could look for createdAt, as long as that doesn't get returned by the provider I use.

If you wanted to avoid possible conflicts better, you can set a custom field in your user schema that is so unique, it's not likely to be used by any external provider.

Not ideal. It would be great if isNewUser() was supported by database logins. This has been brought up before (#558). but it looks like that issue became stale and was closed.

**Comment by dan-kwiat** [comment]
My use case is different but worth noting here as it's related and @jschuur 's suggestion doesn't apply.

My app allows authentication (sign in + sign up) from certain providers only (`email` and `google`). Once a user is signed in however, they can authenticate with other providers (e.g. `strava`) to link those accounts to the existing user in the db.

There are two problems with the above approach:

1. When a signed in user tries to link an account for the first time, the `user` object does not contain the custom fields.
2. If an account is already linked, the `user` object will always have the custom fields, even if `signIn` is called by an un-authenticated user

For this use case I think we have to resort to getting the session:

```js
// [...nextauth].js

const getOptions = (req, res) => ({
  callbacks: {
    async signIn(user, account, profile) {
      if (account.provider === "strava") {
        // Prevent signin/signup, but allow linking
        const session = await getSession({ req })
        return session ? true : false
      }
      return true
    },
  },
  ...
})

export default (req, res) => NextAuth(req, res, getOptions(req, res))
```

**Comment by manentai** [comment]
Well, a user already registered in the db will give you this in the signin callback
    `console.log(user)`
    `{`
       `id: '6293281c41aadb2809a0195e',`
      `email: 'some@email.com',`
      `emailVerified: 2022-05-30T11:42:11.886Z`
   `}`

while a new user won't have the emailVerified attribute, so that's the requirement I look for to allow to signin

**Comment by mschipperheyn** [comment]
Is there any configurable way to avoid a sign in email to be sent to an unregistered user. Following the approach above, I can prevent a user from successfully logging in through email, but they do get the login email, which is weird. It should not be sent. I could of course, load the user using the email before executing a sign in, but I would expect this to be a configuration option.

**Comment by voinik** [comment]
> Is there any configurable way to avoid a sign in email to be sent to an unregistered user. Following the approach above, I can prevent a user from successfully logging in through email, but they do get the login email, which is weird. It should not be sent. I could of course, load the user using the email before executing a sign in, but I would expect this to be a configuration option.

@mschipperheyn I just tested the following login callback (in the `authOptions`):
```ts
signIn({ user }) {
    return Boolean(user.somePropertyAUserInYourDbHas);
},
```

I tried logging in with an email that doesn't exist in my db and I got the 
"Access Denied
You do not have permission to sign in." page. I didn't get an email on the email address I filled in. Hopefully this'll be of some use.

**Comment by shizz-x** [comment]
u can just prevent get requests to /api/auth/singin by redirect in middleware 
src/middleware.jsx
`export async function middleware(request) {
  const userAgent = request.headers.get("user-agent");
  const isMobile =
    /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
      userAgent
    );
  if (request.method === "GET") {
    if (request.nextUrl.pathname === "/api/auth/signin") {
      return NextResponse.redirect(request.nextUrl.origin);
    }
    if (request.nextUrl.pathname === "/api/auth/signout") {
      return NextResponse.redirect(request.nextUrl.origin);
    }
  }

  return NextResponse.next();
}
export const config = {
  matcher: "/api/:path*",
};
`
