### ISSUE TITLE
Send ui_locales to external provider trough login

### ISSUE THREAD

**Issue by cmolendijk** [nextauthjs/next-auth#737]
Our external provider (Identity server 4) supports multiple languages. Therefore we would like to send the parameter `ui_locales ` to the provider.

Think the nices way is when we can add extra query params to the login function. Like this:

`signIn('provider', params: { ui_locales : "en-US" });`

**Comment by balazsorban44** [comment]
We could use the same, only to send `login: prompt` to ask the user to always log in:

https://tools.ietf.org/id/draft-hunt-oauth-v2-user-a4c-01.html#Authentication_Request
