### ISSUE TITLE
Redirect for providers is not working

### ISSUE THREAD

**Issue by kouji-dev** [nextauthjs/next-auth#7375]
### Provider type

Discord, Google

### Environment

Windows PowerShell

  System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 11.69 GB / 31.71 GB
  Binaries:
    Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (112.0.1722.58)
    Internet Explorer: 11.0.22000.120

### Reproduction URL

https://github.com/kouji-dev/boost

### Describe the issue

i'm currently switched to the new experimental appDir and made the necessessary changes to make the app work. The issue is with the authentication with any social provider like: discord.

The problem is when the button of sign as discord is clicked ther are two senarios:

- sometimes it works and i get redirected to discord sign in portal
- sometimes the pages gets reloaded and thats all (it doesnt matter whether i have already a next session in my cookie or not), its basically a simple window.href.reload();

I think there is a race condition somewhere within next-auth library which i couldnt figure out.

### How to reproduce

simpley navigate to /login, and click on sign in with discord.

### Expected behavior

clicking on sign in with discord should redirect to the discord login page and not reload the page only.

**Comment by balazsorban44** [comment]
Could you clarify if this is production/dev/deployed (where)/`next start`? 

https://github.com/kouji-dev/boost/blob/1eab14e7b8be18c7e8c6699c744cc88901269676/src/middleware.ts#L10

On the first look, I've found at least a few places where there are unnecessary promises.

In the Middleware:
```diff
- const token = await getToken({ req });
+ const { token } = req.nextauth
```

In the Route Handler:

https://github.com/kouji-dev/boost/blob/1eab14e7b8be18c7e8c6699c744cc88901269676/src/app/api/auth/%5B...nextauth%5D/route.ts#L54-L58

It's unclear why this extra user query is added, `dbUser` is equal to `user` here.

It might also be that the provider is slow to respond/times out, can you verify it's not the case?

Are there any logs that might help to debug here?

A common issue for slowdown might also occur if you are importing a huge number of icons that need to be compiled (usually something like MUI), but I cannot see this in your case. It would also only affect development, so knowing the environment you encounter the problem would help a lot. :pray:

**Comment by kouji-dev** [comment]
I have removed the all callbacks for jwt session and signIn, also made changes you recommended to the middleware but still not working, you can find a new push i made.

The issue is not related to the callbacks, as I told you the page doesnt redirect to the discord portal.

After activating the debug mode of next-auth it shows that GET_AUTHORIZATION_URL] is called but nothing happens later.

One work arround to make it work is to hold ctrl and click on sign in with discord, this will open the discord portal on the same page and opens a redirect url in a new tab.

**Comment by kouji-dev** [comment]
I figured the issue. it is soo dump from my side. Acctually the button was inside a form and therefore any click on a button would assume it as a submit. replacing the form with a div solves the issue.
