### ISSUE TITLE
Module '"next-auth"' has no exported member 'NextAuthOptions'.ts(2305)

### ISSUE THREAD

**Issue by fbryo21** [nextauthjs/next-auth#7377]
### What is the improvement or update you wish to see?

I followed the tutorial which is in the **next-auth-example** repository, after that it showed a typescript error, said:

> Module '"next-auth"' has no exported member 'NextAuthOptions'.ts(2305)

What do I have to do? please fix it

### Is there any context that might help us understand?

TypeScript Implementation

### Does the docs page already exist? Please link to it.

https://github.com/nextauthjs/next-auth-example

**Comment by balazsorban44** [comment]
Could you add a reproduction? It _is_ exported, see the source:

https://github.com/nextauthjs/next-auth/blob/ddffa57d00664bc6ba7990a9b6c3bfe2f131ebe6/packages/next-auth/src/index.ts#L2

**Comment by ygit1** [comment]
Using next-auth@latest

When I 
npm run build

```
Type error: Module '"next-auth"' has no exported member 'NextAuthOptions'.

  1 | 
  2 | 
> 3 | import NextAuth, { NextAuthOptions } from "next-auth"
```

**Comment by moorage** [comment]
For some reason, changing `import NextAuth, { NextAuthOptions } from 'next-auth'` to `import NextAuth, { NextAuthOptions } from 'next-auth/index'`helped resolve the issues that were popping up in vscode

**Comment by mihaiicey** [comment]
> For some reason, changing `import NextAuth, { NextAuthOptions } from 'next-auth'` to `import NextAuth, { NextAuthOptions } from 'next-auth/index'`helped resolve the issues that were popping up in vscode

yup, same error...fiex with  'next-auth/index'

**Comment by moorage** [comment]
Unfortunately 'next-auth/index' caused error in my prod build.  Moving `./next-auth.d.ts` to `./types/next-auth.d.ts` fixed things iirc

**Comment by dieduro** [comment]
Same: fixed it using `import type { NextAuthOptions } from 'next-auth/index';` and my definitions file's path is `src/types/next-auth.d.ts`

**Comment by Kydollar** [comment]
export next-auth.d.ts `export declare module 'next-auth' {}`, no need to change the import, and still `import { NextAuthOptions } from 'next-auth'`, for me it's resolved

**Comment by sgwanlee** [comment]
@Kydollar it works for me. I forgot to `export` it

**Comment by iamvinny** [comment]
> export next-auth.d.ts `export declare module 'next-auth' {}`, no need to change the import, and still `import { NextAuthOptions } from 'next-auth'`, for me it's resolved

Hi, @Kydollar, could you please elaborate on where to export `next-auth.d.ts`? Thanks.

**Comment by CarstenHS** [comment]
I got past it just by adding forward slash: import NextAuth, { NextAuthOptions } from 'next-auth/'
"next-auth": "^4.24.11"

**Comment by u-iDaniel** [comment]
With Auth.js v5 or next-auth v5, NextAuthOptions will be deprecated so now you only need to pass in an object to NextAuth()

**Comment by achyu-dev** [comment]
> For some reason, changing `import NextAuth, { NextAuthOptions } from 'next-auth'` to `import NextAuth, { NextAuthOptions } from 'next-auth/index'`helped resolve the issues that were popping up in vscode

this did not work for me.

Anny other way to fix this issue?

**Comment by achyu-dev** [comment]
> With Auth.js v5 or next-auth v5, NextAuthOptions will be deprecated so now you only need to pass in an object to NextAuth()

This is my code - 

```jsx
//import { NextAuthOptions } from 'next-auth/index';
import type { NextAuthOptions } from 'next-auth';
import AuthOptions from "next-auth";
import AzureADProvider from "next-auth/providers/microsoft-entra-id";
import { PrismaAdapter } from "@next-auth/prisma-adapter";
import prisma from "@/lib/prisma";
import { scheduleEmails } from "@/cron/scheduler_peers";

export const options: NextAuthOptions = {
    adapter: PrismaAdapter(prisma),
  providers: [
    AzureADProvider({
      clientId: process.env.AZURE_AD_CLIENT_ID,
      clientSecret: process.env.AZURE_AD_CLIENT_SECRET,
      tenantId: process.env.AZURE_AD_TENANT_ID,
      //redirectUri: process.env.AZURE_AD_REDIRECT_URI,
    }),
  ],
  callbacks: {
    async jwt({
      token,
      account,
      user,
    }: {
      token: any;
      account: any;
      user: any;
    }) {
      if (account && user) {
        token.role = user.role;
      }
      return token;
    },
    async session({ session, token }: { session: any; token: any }) {
      // console.log("token", token);
      console.log(scheduleEmails);
      if (token?.role) {
        session.user.role = token.role;
      }
      return session;
    },
  },
  session: {
    strategy: "jwt",
  },
}
```

how should i modify according to this?

my next-auth version - ```"next-auth": "^5.0.0-beta.20",```

**Comment by Elanrif** [comment]
For me i put / at the end, like this : `import NextAuth, { NextAuthOptions } from "next-auth/";

`import NextAuth, { NextAuthOptions } from "next-auth/";
import CredentialsProvider from "next-auth/providers/credentials";
import type { JWT } from "next-auth/jwt";
import environment from "@/config/environment.config";

const {
  baseUrl,
  api: {
    rest: {
      endpoints: { users: usersUrl, userstats: usersStatsUrl },
    },
  },
} = environment;

async function refreshToken(token: JWT): Promise<JWT> {
  const res = await fetch(baseUrl + "/auth/refresh", {
    method: "POST",
    headers: {
      authorization: `Refresh ${token.backendTokens?.refreshToken}`,
    },
  });

  if (!res.ok) {
    throw new Error("Failed to refresh token");
  }
  const response = await res.json();
  console.log("token of refresh: ", response);
  console.log("token refreshed: ", {
    ...token,
    backendTokens: response,
  });
  return {
    ...token,
    backendTokens: response,
  };
}
`

**Comment by achyu-dev** [comment]
> Version "next": "15.2.3", "next-auth": "^4.24.11" I put **/** at the end of import, like this : import NextAuth, { NextAuthOptions } from "next-auth/";
> 
> > import NextAuth, { NextAuthOptions } from "next-auth/";
> > import CredentialsProvider from "next-auth/providers/credentials";
> > import type { JWT } from "next-auth/jwt";
> > import environment from "@/config/environment.config";
> 
> `import NextAuth, { NextAuthOptions } from "next-auth/";
> 
> `

This did not work for me too, I checked

**Comment by anunknowperson** [comment]
If anyone's wondering how to fix this. Put this in your config:

```typescript

/**
 * Module augmentation for `next-auth` types. Allows us to add custom properties to the `session`
 * object and keep type safety.
 *
 * @see https://next-auth.js.org/getting-started/typescript#module-augmentation
 */
declare module "next-auth" {
  interface Session extends DefaultSession {
    user: {
      id: string;
      // ...other properties
      // role: UserRole;
    } & DefaultSession["user"];
  }

  // interface User {
  //   // ...other properties
  //   // role: UserRole;
  // }
}

/**
```

From T3 example app.
