### ISSUE TITLE
On iOS and Android (all mobile devices) initiating twitter auth opens the twitter mobile app

### ISSUE THREAD

**Issue by Jmyerzzz** [nextauthjs/next-auth#7387]
### Question 💬

Is there a way to prevent twitter auth from opening the browser inside the twitter app? This completely breaks the UX for mobile devices

### How to reproduce ☕️

try initiating twitter auth from a mobile device, it opens in the twitter app which make's it impossible to save the session variables in the mobile system browser like safari or chrome

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by Jmyerzzz** [comment]
I found this other issue from last fall, potentially related.

https://github.com/nextauthjs/next-auth/issues/5747

**Comment by balazsorban44** [comment]
From the looks of it, that is a bit different. I assume that there the state cookie was set in the main browser, but since the user was redirected to the in-app browser, the cookie was not found anymore when the sign-in process was finishing up.

**Comment by balazsorban44** [comment]
![Screenshot_20230429-115527.png](https://user-images.githubusercontent.com/18369201/235296708-50f6d341-2621-491e-aa5c-7f21aee49313.png)

I found that on Android, you can actually force the app to not open the Twitter link, which makes the login successful in the browser.

So this sounds like out of our control, unnecessary. I'm closing this we probably cannot do anything here. 😕
