### ISSUE TITLE
EmailProvider flow

### ISSUE THREAD

**Issue by y-nk** [nextauthjs/next-auth#7389]
### Question 💬

I've successfully implemented the EmailProvider with nodemailer and a PrismaAdapter. In order to have the reference to the user object in my prisma schema, I went with the [advanced implementation](https://authjs.dev/reference/adapter/prisma#create-the-prisma-schema-from-scratch).

I've also created the sign in form, for which i call `signIn('email', { email })` and this works fine too. It triggers the email, I can receive it and click on the link.

The problem I have is with the end of the flow. The server throws an error about `prisma.session.create` with a unique constraint being undefined. The log isn't super clear, but _logically_ it has to be the `userId` which is empty. Since the error is about `prisma.session`, the error seems to be related to the prisma adapter usage and the session model.

I tried to change a bit the prisma schema like this: 

```diff
model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
-  userId       String
+  userId       String?
  expires      DateTime
-  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}
```

the error changes now and i get:

```
Invalid `prisma.session.findUnique()` invocation:

{
  where: {
    sessionToken: 'xxx'
  },
  include: {
    user: true,
    ~~~~
  }
}
```

so the session was created, but since now the userId can be undefined (`String?`) i can't make the `User user` relation anymore.

I'm wondering what i'm doing wrong, and if there was any further documentation regarding the EmailProvider flow (with chart). It's not clear to me if the user is created. Maybe the payload of the `signIn` call is not proper, and so the user isn't created before the redirection?

I couldn't find any documentation on the payload of the signIn method when calling with 'email'. Is the 2nd parameter `{ email }`? Any other param mandatory?

Thanks for your help and guidance

### How to reproduce ☕️

Reproduction is quite difficult (it requires a smtp server, a planetscale account). Question is rather generic.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
> Reproduction is quite difficult (it requires a smtp server, a planetscale account). Question is rather generic.

This might be the assumption, but without seeing your project or a minimal reproduction (preferred), it's hard to guess what the issue is.

Can probably reproduce with SQLite and a fake smtp if you attach your code and there is an actual issue. 🙏
