### ISSUE TITLE
Link on NPM page is a 404

### ISSUE THREAD

**Issue by olafurw** [nextauthjs/next-auth#7393]
### Environment

No applicaple

### Reproduction URL

https://www.npmjs.com/package/@auth/core

### Describe the issue

https://www.npmjs.com/package/@auth/core links to https://authjs.dev/reference/core/modules/main which doesn't exist.

Possibly should link to https://authjs.dev/reference/core

### How to reproduce

Click that beautiful link on the NPM page.

### Expected behavior

Not a 404

**Comment by balazsorban44** [comment]
Thanks, already fixed in #7334 just not released yet!
