### ISSUE TITLE
Docs: Request to Add to Sign In Callback Documentation

### ISSUE THREAD

**Issue by JSMarsh813** [nextauthjs/next-auth#7401]
### What is the improvement or update you wish to see?

Description 🐜

Request to add to the documentation for the Sign In Callback to show how a magic link can be sent to only existing users in a database.

Although this answer helped me figure out how to do this, I would rather add it to the documentation so its clear how to accomplish this for future next-auth users. https://github.com/nextauthjs/next-auth/issues/1229

Why its important: If new users can sign in with the magic link, this can lead to deformed user objects in the database. Instead, this code makes it possible to check your database and force new users to go to the registration page if they do not exist in the database.

Is this a bug in your own project?
No 

How to reproduce ☕️
N/A

Screenshots / Logs 📽
N/A

Link to the original documentation:
https://authjs.dev/guides/basics/callbacks

Link to the pull request:
https://github.com/JSMarsh813/next-auth/pull/1

Visual of what my commit would look like:
![image](https://user-images.githubusercontent.com/101692334/236629369-e9d2e7e3-c3fd-4c0f-b836-541ab3ae562b.png)
Environment 🖥
N/A

Contributing 🙌🏽

Yes, I am willing to help solve this in a PR. Thanks!

### Is there any context that might help us understand?

I want to help make the documentation clearer about how to use signin callback to limit which users will receive a magic login link.

### Does the docs page already exist? Please link to it.

https://authjs.dev/guides/basics/callbacks

**Comment by balazsorban44** [comment]
Closing as fixed in #7663
