### ISSUE TITLE
Auth0 Provider `user.name` field map to `profile.nickname`, proposition to use the `profile.name` field

### ISSUE THREAD

**Issue by MatteoGauthier** [nextauthjs/next-auth#7402]
### Question 💬

Currently, the ﻿user.name field in Auth0 is mapped to the ﻿profile.nickname field by default. However, we propose to use the ﻿profile.name field instead, as it better aligns with our application’s requirements.

This change would ensure that the user’s full name is stored in the ﻿name field in our application, instead of a potentially incomplete or irrelevant nickname.

I can make the change in a PR if needed

### How to reproduce ☕️

Use Auth0 provider

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
This is now fixed in `@auth/core`: https://github.com/nextauthjs/next-auth/blob/e3bdb38df2d20495bc4798c33d59396b0f2911f4/packages/core/src/lib/providers.ts#L98

It will respect `user.name` by default. Will also be fixed in the next major release of `next-auth`.

**Comment by MatteoGauthier** [comment]
Thanks !
