### ISSUE TITLE
session authentication with next-auth like express-session

### ISSUE THREAD

**Issue by codelover2k** [nextauthjs/next-auth#7404]
### Question 💬

Hi!

in all my servers I am using express and express-session.
Since I started some pure next.js and tRPC apps I want to use next-auth.

My question is if it is possible to use next-auth like express-session?
express-session allows you crazy customization for your session and session-cookie like the way you want to protect it with a secret to sign it, maxAge and so on.

My flow looks like this with express-session that I want to have in next-auth.
1. I check if the req has a session
2. I get the session and from my database/redis I get the session and its data
3. I use req.session.userId to fetch my database to fetch user informations like the name, its permissions, if the user is locked by the admin or not and many more for every request
4. return the requested data to the user or return a "NOT AUTHENTICATED" respond to the client

is this possible with next-auth?
It looks and feels like you have to use an authentication service like google and that only JWT are supported?

### How to reproduce ☕️

---

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
"Crazy customization" is kind of vague, but we do have a lot of configuration options. Check the docs https://next-auth.js.org/configuration/options

We also support database sessions out of the box, Redis included.

https://authjs.dev/reference/adapter/upstash-redis

You can also, create your custom database adapter.

https://authjs.dev/guides/adapters/creating-a-database-adapter

https://github.com/nextauthjs/next-auth/blob/main/packages/adapter-upstash-redis/src/index.ts
