### ISSUE TITLE
Provider Oauth Login Cancel Callback

### ISSUE THREAD

**Issue by Hyodori04** [nextauthjs/next-auth#7407]
### Question 💬

I am using next-auth for login. When I use provider oauth login (ex : discord), cancel of discord login redirect to (/api/auth/signin?error=Callback). But considering user experience, it is good to redirect origin url. So I wonder why OAUTH_CALLBACK_HANDLER_ERROR redirect to signin error page. And OAUTH_CALLBACK_HANDLER_ERROR is related to another error excepting Cancel. If not I want to add some options in provider that go back to origin url if user just cancel Oauth login

### How to reproduce ☕️

related next-auth code

```
 if ((error as Error).name === "AccountNotLinkedError") {
          // If the email on the account is already linked, but not with this OAuth account
          return {
            redirect: `${url}/error?error=OAuthAccountNotLinked`,
            cookies,
          }
        } else if ((error as Error).name === "CreateUserError") {
          return { redirect: `${url}/error?error=OAuthCreateAccount`, cookies }
        }
        logger.error("OAUTH_CALLBACK_HANDLER_ERROR", error as Error)
        return { redirect: `${url}/error?error=Callback`, cookies }
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by Hyodori04** [comment]
I think this is edited well by main contributer. Thanks so much!

**Comment by G-Bazan** [comment]
Hello @balazsorban44, I need exactly this fix, 
sorry for the silly question but how can I install it in my project?

I tried
`npm i https://github.com/nextauthjs/next-auth.git#8e29b4df0c20e0f29758b1f1b6f6c05f16c8f24e`


and that added on my package.json the line
"root": "github:nextauthjs/next-auth#8e29b4df0c20e0f29758b1f1b6f6c05f16c8f24e"

but the error persist

Thanks

**Comment by G-Bazan** [comment]
Hello @balazsorban44, sorry for the silly but how can I apply this fix commit?

I tried

npm install git+https://github.com/nextauthjs/next-auth#8e29b4df0c20e0f29758b1f1b6f6c05f16c8f24e

with and without git+, this command update my package.json and package-lock.json with following:

"root": "github:nextauthjs/next-auth#8e29b4df0c20e0f29758b1f1b6f6c05f16c8f24e"

that does not sound good, indeed I still got Cancel Issue.

Thanks
