### ISSUE TITLE
Google Sign-in with Prisma adapter, returning the wrong user from the database

### ISSUE THREAD

**Issue by Miloshinjo** [nextauthjs/next-auth#741]
Hi,
I am trying to add Oauth with next-auth and Prisma. When using Email or Github, all good. 
When loggin in with google, I am getting the wrong user from the database in the sesssion.

eg. I try to log in with mj@gmail.com, I get back sp@gmail.com in the session as the logged in user.

Does anyone know why that might happen?

[edit]
Seems like this is happening with Discord as well. For example, if Discord account has account ID of 4, and there is a user signed up with email, with userId of 4. When I log in with the user who as accountId of 4 (userID 8), Session is registered for the user of the ID 4.

**Comment by junaid33** [comment]
@Miloshinjo Hey I was facing a similar issue with Github and also using Prisma. Were you able to fix it?

**Comment by Miloshinjo** [comment]
Yes, but you won't like it. I copied the entire library into my project folder and then made a fix manually in their code. Then I loaded the lib from my src instead od node_modules. I can post the change I made in their code that did the trick.
