### ISSUE TITLE
discord session.user.image problem

### ISSUE THREAD

**Issue by wesleezz** [nextauthjs/next-auth#7418]
### Environment

yes i have lackages next, react, next-auth i use windows 10 arm: x64 nodejs: 18.16.0 for today 1 may 2023 latest browser google chrome

### Reproduction URL

localhost:3000

### Describe the issue

i have a problem with getting discord user image it's looking like this

<Image
  src={session?.user.image}
  width="50"
  height="50"
/>

### How to reproduce

when i login and check localhost i have a error

Error: Invalid src prop (https://cdn.discordapl.com/avatars/(userid)/(avatarid).png) on /next/image, hostname cdn.discordapp.com is not configured under images in your next.config.js

### Expected behavior

image from discord should be showing in header

**Comment by balazsorban44** [comment]
This is unrelated to NextAuth.js. See https://nextjs.org/docs/api-reference/next/image#remote-patterns

**Comment by wesleezz** [comment]
fixed i restarted pc

**Comment by wesleezz** [comment]
fixed i restarted pc
