### ISSUE TITLE
Next-Auth version 3.29 - cannot find [...nextauth].js

### ISSUE THREAD

**Issue by sbf-ChrisAbbott** [nextauthjs/next-auth#7425]
### Question 💬

I'm working on pulling out an old authentication system in favour of introducing next-auth, the node version of the repo is v9 so i'm unable to upgrade next-auth to v4. 

I'm getting the following error when trying to login as a user: 
https://next-auth.js.org/errors#missing_nextauth_api_route_error Cannot find [...nextauth].js in pages/api/auth. Make sure the filename is written correctly.

However, the api/auth/[...nextauth].js file exists as it should inside of the /pages directory
![image](https://user-images.githubusercontent.com/116665144/235667950-faaeb01a-86f2-495a-947b-dd74dff40d3b.png)

### How to reproduce ☕️

"next": "9.0.4",
"next-auth": "^3.29.10",

Using a basic Providers.Credentials provider:

import NextAuth from 'next-auth';
import Providers from 'next-auth/providers';

const nextAuthOptions = (req, res) => ({
    providers: [
        Providers.Credentials({
            name: 'Credentials',
            credentials: {
                email: { label: 'Email', type: 'text' },
                password: { label: 'Password', type: 'password' },
            },
            authorize: async (credentials) => {
                // Add your custom authorization logic here
                if (
                    credentials.email === 'admin' &&
                    credentials.password === 'password'
                ) {
                    return Promise.resolve({ email: 'admin' });
                } else {
                    return Promise.resolve(null);
                }
            },
        }),
    ],
});

export default (req, res) => NextAuth(req, res, nextAuthOptions(req, res));

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
By node version, I assume you actually meant Next.js.

https://nextjs.org/blog/next-9-2#catch-all-dynamic-routes

Catch-all routes were introduced in `next@9.2` so `9.0.4` won't have support for it.

Note, `next-auth@3` is unmaintained too.
