### ISSUE TITLE
docs request: explain "advanced" section in prisma adapter

### ISSUE THREAD

**Issue by mmkal** [nextauthjs/next-auth#7426]
### What is the improvement or update you wish to see?

Hi! I'm looking to use the prisma adapter and reading the docs at https://authjs.dev/reference/adapter/prisma I'm not 100% sure what I need to do.

The `Setup` section is simple enough, but the schema is under "Advanced usage". Does this mean it's optional? Will the adapter auto-create the tables necessary for the adapter to work if I _don't_ copy-paste the models to my `schema.prisma` file? Are there pros/cons? A simple sentence would probably be more than enough to give an indication.

### Is there any context that might help us understand?

I'm hoping to avoid copy-pasted code that I'll have to fence off to protect - for example, I'd need to make sure that nobody on my team accidentally "fixes" the snake-case/camel-case inconsistency by adding a CI check making sure it matches next-auth docs etc. I also might need to worry about if next-auth updates the model in the future, etc. Totally fine to copy paste it in, if that's the requirement, but I don't want to do it before knowing what the pros and cons are, or whether it's actually necessary.

Also, if it is necessary, it might be sensible not to call the section `Advanced usage` anymore.

### Does the docs page already exist? Please link to it.

https://authjs.dev/reference/adapter/prisma

**Comment by balazsorban44** [comment]
There was an extra heading that slipped in. Ignore `Advanced usage`, it's just `Setup`. I pushed a fix to remove it.
