### ISSUE TITLE
"Try signing in with a different account" when using the prisma adapter

### ISSUE THREAD

**Issue by vincentteyssier** [nextauthjs/next-auth#7441]
### Adapter type

@next-auth/prisma-adapter

### Environment

System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 10.67 GB / 15.63 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm

  npmPackages:
    @next-auth/prisma-adapter: ^1.0.6 => 1.0.6 

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

I've cloned the starting example and made it work with the GitHub provider.
It is working fine when I do not have any adapter.

Now I'm adding the prisma adapter.
I created the schema file using the provided template, added the 3 missing fields as indicated in a previously closed issue:
```
oauth_token_secret String?
  oauth_token        String?
  refresh_token_expires_in        Int?
```
Then ran generate and migrate and verified that the tables and all columns are successfully added to the mysql db.

Here is my auth file:

```
import NextAuth, { NextAuthOptions } from "next-auth"
import GithubProvider from "next-auth/providers/github"
import { PrismaAdapter } from "@next-auth/prisma-adapter";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();


// For more information on each option (and a full list of options) go to
// https://next-auth.js.org/configuration/options
export const authOptions: NextAuthOptions = {
  adapter: PrismaAdapter(prisma),
  debug: true,
  // https://next-auth.js.org/configuration/providers/oauth
  providers: [
    GithubProvider({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET,
    })
  ],
  callbacks: {
    async jwt({ token }) {
      token.userRole = "admin"
      return token
    },
  },
}

export default NextAuth(authOptions)
```

I can see in the debug logs that GitHub returns the right payload,  and after that, the last line in the logs is:
`[next-auth][debug][adapter_getUserByAccount] { args: [ { providerAccountId: 'xxxxxxxx', provider: 'github' } ] }`

Nothing happens after that in the logs.

In the frontend, I get the following error:

> Try signing in with a different account.

I check the db and all tables are empty.
Connection string is correct as I can login with it from my local terminal:
`DATABASE_URL="mysql://xxxxxusername:xxxpassword@localhost:3306/dbname?allowPublicKeyRetrieval=TRUE"`

### How to reproduce

Clone the example https://github.com/nextauthjs/next-auth-example
npm i
Add the prisma adapter according to the documentation.
Add the extra variables missing in the Account table for GitHub response.
Try to login 

### Expected behavior

The user should be logged in and prisma adapter would create a record in the db

**Comment by balazsorban44** [comment]
```
oauth_token_secret String?
oauth_token        String?
```

These are OAuth 1.0-related rows that GitHub does not require.

I could not reproduce the issue, could you please add a reproduction?

**Comment by vincentteyssier** [comment]
Apologies, I've just figured out that the error was thrown, but since I run on pm2, I was only tailing the out file, and forgot it writes it to error file.
Now I see that it uses the wrong .env file, correcting that and it works.
Thanks for the awesome library!

**Comment by whcender** [comment]
Same issue, I changed my prisma schema, problem solved for now, so don't forget to check your prisma schema.

**Comment by pablojsx** [comment]
yes, I forgot to npx prisma db push..

**Comment by FeuGuillaume186** [comment]
prisma adapter work only with @prisma/client@12.5.0 or above
for more information: [https://authjs.dev/getting-started/adapters/prisma](url)
