### ISSUE TITLE
Get Server Session in Server Actions

### ISSUE THREAD

**Issue by EliasGcf** [nextauthjs/next-auth#7460]
### Question 💬

How to get the session inside a [Server Actions](https://nextjs.org/blog/next-13-4#server-actions-alpha)?

Show this error:

![image](https://user-images.githubusercontent.com/50633599/236581387-ce1e8a88-e913-4467-90aa-ff738f9b82c7.png)

### How to reproduce ☕️

```ts
export async function create(formData: FormData) {
  'use server';

  const session = await getServerSession();

  console.log(session);
}
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by EliasGcf** [comment]
It worked sending it via the function param. Is it a good solution/alternative to the code I first provided for now?

Like this:

```html
<form action={(formData) => create(formData, session)}>
```

In the network tab:

**Comment by Talent30** [comment]
I can reproduce this

**Comment by ThangHuuVu** [comment]
this is an upstream issue with Next.js that is linked above. Please try `next@13.4.2-canary.2`, thanks 🙏

**Comment by mr-schulz** [comment]
> It worked sending it via the function param. Is it a good solution/alternative to the code I first provided for now?
> 
> Like this:
> 
> ```
> <form action={(formData) => create(formData, session)}>
> ```
> 
> In the network tab:
> 
> ![image](https://user-images.githubusercontent.com/50633599/236582530-288b204c-af30-49dc-958c-e05fbf268110.png)

i think this is unsecure and everybody should avoid it!
server actions are basicly post requests, a attacker could manipulate or create the session part in `create(formData, session)}`  

maybe it only make sence if there is encrypted token in the session, which can be checked on server side (server action body)

correct me please if i am wrong

**Comment by mcapodici** [comment]
This worked for me (source: https://www.reddit.com/r/nextjs/comments/13eb1vj/comment/jjptpkx/?utm_source=reddit&utm_medium=web2x&context=3)

> Your component must be async and function awaited. Also u need to pass authOptions from NextAuth config. Here an example from https://next-auth.js.org/configuration/nextjs with NextJS >13.2 and NextAuth >4.22.0:

```

import { getServerSession } from "next-auth/next"
import { authOptions } from "@/api/auth/[...nextauth]/route.ts"

export default async function Page() {
  const session = await getServerSession(authOptions)
  return <pre>{JSON.stringify(session, null, 2)}</pre>
}
```

My server action looks like this:

```
export async function addNewChatAgent(data: Values) {
    const session = await getServerSession(authOptions)
    if (!session) {
        throw Error("oops");
    }
    const { userId } = session as any;
    const agent: NewChatAgent = {
        model: data.model,
        name: data.name,
        user_id: session.user.id,       
    }
    await db.insert(chatAgent).values(agent);
}
```

**Comment by liuhe2020** [comment]
> An adaptation of this worked for me (source: https://www.reddit.com/r/nextjs/comments/13eb1vj/comment/jjptpkx/?utm_source=reddit&utm_medium=web2x&context=3)
> 
> My server action looks like this:
> 
> ```
> export async function addNewChatAgent(data: Values) {
>     const session = await getServerSession(authOptions)
>     if (!session) {
>         throw Error("oops");
>     }
>     const { userId } = session as any;
>     const agent: NewChatAgent = {
>         model: data.model,
>         name: data.name,
>         user_id: session.user.id,       
>     }
>     await db.insert(chatAgent).values(agent);
> }
> ```

Works a treat, thank you!
