### ISSUE TITLE
`getServerSession` not forwarding extra properties passed in from `jwt` callback

### ISSUE THREAD

**Issue by AlvaroAquijeDiaz** [nextauthjs/next-auth#7474]
### Environment

System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 2.80 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    npm: 9.5.1 - /opt/homebrew/bin/npm
    Watchman: 2023.01.16.00 - /opt/homebrew/bin/watchman
  Browsers:
    Safari: 16.4

### Reproduction URL

https://github.com/AlvaroAquijeDiaz/regiftt

### Describe the issue

my `auth.ts`

```ts
export const authOptions: NextAuthOptions = {
  callbacks: {
    jwt: ({ account, token, user }) => {
      if (account && user) {
        token.accessToken = account.access_token;
        token.id = user.id;
        token.username = user.username;
      }

      return token;
    },

    session: ({ session, token }) => ({
      ...session,
      user: {
        ...session.user,
        id: token.id,
        username: token.username,
      },
    }),
  },
  session: {
    strategy: "jwt",
  },
  pages: {
    newUser: "/new-user",
  },
  adapter: PrismaAdapter(db),
  providers: [
    DiscordProvider({
      clientId: env.DISCORD_CLIENT_ID,
      clientSecret: env.DISCORD_CLIENT_SECRET,
    }),
    /**
     * ...add more providers here.
     *
     * Most other providers require a bit more work than the Discord provider. For example, the
     * GitHub provider requires you to add the `refresh_token_expires_in` field to the Account
     * model. Refer to the NextAuth.js docs for the provider you want to use. Example:
     *
     * @see https://next-auth.js.org/providers/github
     */
  ],
};
```

as you can see the `jwt` is forwarding more properties like `id` and `username` however when using `getServerSession` inside a RSC in the `app dir` only the base properties are available.

```log
user: {
      name: 'Liltripple_reid',
      email: 'alvarodevcode@outlook.com',
      image: 'https://cdn.discordapp.com/avatars/690296795976564838/56a30b9f758099df7f610a729440f558.png'
    }
  }
```

### How to reproduce

1. go to the repo
2. authenticate 
3. go to `/me`
4. see the next.js console for the bug

### Expected behavior

`getServerSession` should forward those extra properties as when using `useSession` on the client

**Comment by AlvaroAquijeDiaz** [comment]
update: it actually returns the expected data if `authOptions` is passed, so not sure if it's a bug or a feature

**Comment by balazsorban44** [comment]
It is the expected behaviour, as without `authOptions` being passed, we wouldn't know how you configured the `jwt` and `session` callbacks.
