### ISSUE TITLE
Callback for SignIn in SvelteKitAuth allows unauthorized access

### ISSUE THREAD

**Issue by adibkadir** [nextauthjs/next-auth#7477]
### Environment

  System:
    OS: Windows 10 10.0.23451
    CPU: (8) x64 Microsoft SQ2 @ 3.15 GHz
    Memory: 5.34 GB / 15.47 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.23451.1000.0), Chromium (113.0.1774.35)
    Internet Explorer: 11.0.23451.1000

### Reproduction URL

https://github.com/adibkadir/auth-bug-example/blob/main/src/hooks.server.ts

### Describe the issue

Documentation says you can use callbacks to do further authorization checks.

The following works correctly since the fail case return false. The user is prevented from gaining access to sensitive data.
```
callbacks: {
    async signIn({ user, account, profile, email, credentials }) {
      const isAllowedToSignIn = false
      if (isAllowedToSignIn) {
        return true
      } else {
        return false
      }
    }
  }
```
  
However the doc also says you can return '/unauthorized' instead to redirect the user to another page. However this actually allows the user to gain access to the sensitive data:
  ```
  callbacks: {
    async signIn({ user, account, profile, email, credentials }) {
      const isAllowedToSignIn = false
      if (isAllowedToSignIn) {
        return true
      } else {
        return '/unauthorized'
      }
    }
  }
 ```

### How to reproduce

Add the following callback to the SvelteKitAuth() config :

```
export const handle = SvelteKitAuth({
  providers: [
    GoogleProvider({
      clientId: GOOGLE_ID,
      clientSecret: GOOGLE_SECRET,
      authorization: { params: { prompt: 'consent' } },
    }),
  ],


  callbacks: {
    async signIn({ user, account, profile, email, credentials }) {
      const isAllowedToSignIn = false
      if (isAllowedToSignIn) {
        return true
      } else {
        return '/unauthorized'
      }
    }
  }
})
```

### Expected behavior

isAllowedToSignIn is set to false... and the code path returns '/unauthorized'... however the user is sent to the logged in state with full access to protected pages and content.

Expectation is that the user is redirected to the provided path and does not have access to protected routes or data.

**Comment by adibkadir** [comment]
For context, I had copied this code from the documentation: https://next-auth.js.org/configuration/callbacks

**Comment by balazsorban44** [comment]
This is currently expected. The SvelteKit Auth package does not implement the same redirect logic, as it is not based on `next-auth`

Correct docs: https://authjs.dev/reference/core/types#signin
