### ISSUE TITLE
Email provider should import nodemailer only when needed

### ISSUE THREAD

**Issue by GeoffreyBooth** [nextauthjs/next-auth#7483]
### Environment

  System:
    OS: macOS 13.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 19.23 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.1.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 9.6.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Chrome Canary: 115.0.5757.0
    Firefox: 76.0.1
    Firefox Developer Edition: 94.0
    Safari: 16.4

### Reproduction URL

https://stackblitz.com/edit/svelte-kit-5v36gw

### Describe the issue

I’m building a SvelteKit app that’s using `@authjs/core` and `@authjs/sveltekit` to implement a passwordless email login flow. I’m also using `@sveltejs/adapter-cloudflare` to deploy the app to Cloudflare Pages. For Cloudflare, sending emails is done via a `fetch` call, per https://blog.cloudflare.com/sending-email-from-workers-with-mailchannels/; therefore I’m overriding `sendVerificationRequest` with a custom function to make this `fetch` call rather than let the default version use `nodemailer` to send an email via an SMTP server.

The issue is that `nodemailer` cannot run in a Cloudflare environment because of its dependencies on Node internal modules; the `npm run build` command fails. Here’s a portion of the errors printed in the build log:

```
✘ [ERROR] Could not resolve "stream"

    node_modules/nodemailer/lib/mime-node/last-newline.js:3:26:
      3 │ const Transform = require('stream').Transform;
        ╵                           ~~~~~~~~

  The package "stream" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

error during build:
Error: Build failed with 55 errors:
node_modules/nodemailer/lib/base64/index.js:3:26: ERROR: Could not resolve "stream"
node_modules/nodemailer/lib/dkim/index.js:9:28: ERROR: Could not resolve "stream"
node_modules/nodemailer/lib/dkim/index.js:10:19: ERROR: Could not resolve "fs"
node_modules/nodemailer/lib/dkim/index.js:11:21: ERROR: Could not resolve "path"
node_modules/nodemailer/lib/dkim/index.js:12:23: ERROR: Could not resolve "crypto"
...
    at failureErrorWithLog (file:///home/projects/svelte-kit-5v36gw/node_modules/esbuild/lib/main.js:1626:15)
```

This happens because of this line: https://github.com/nextauthjs/next-auth/blob/b96f01319c751c7d62433c24fdb9f3f8f1e572c1/packages/core/src/providers/email.ts#L1

What’s happening here is that `nodemailer` is imported whether or not it’s being used. Even locally, I can’t run the app without having `nodemailer` installed, even though I override the only `sendVerificationRequest` function where `nodemailer` is used. As a workaround I can delete this line, via a command like `sed -i '' 's/import { createTransport } from \"nodemailer\";//' ./node_modules/@auth/core/providers/email.js`, but it’s brittle to edit the source code of my dependencies.

I think a proper solution would be to remove this static `import` and rewrite the file to dynamically import `nodemailer` on first use:

```js
let nodemailer
export default function Email(config: EmailConfig): EmailConfig {
  return {
    // ...
    async sendVerificationRequest(params) {
      nodemailer ??= await import('nodemailer')
```

Then apps like mine which don’t use it won’t need to depend on it, and my build would succeed.

### How to reproduce

Open https://stackblitz.com/edit/svelte-kit-5v36gw and run `npm run build`.

### Expected behavior

`npm run build` should succeed.

**Comment by balazsorban44** [comment]
In this case, you don't really need to import the EmailProvider at all. Check out https://authjs.dev/guides/providers/email-http

I think we want to keep the default email provider using `nodemailer` to be service agnostic, but we could add more built-in email providers in the future, that does not have this import problem.

**Comment by chungweileong94** [comment]
> In this case, you don't really need to import the EmailProvider at all. Check out https://authjs.dev/guides/providers/email-http

Yeah, but unfortunately this will throw type errors, but I can put in some dummy value to make the TS happy.
![image](https://github.com/nextauthjs/next-auth/assets/15154097/54fa99fb-8bf1-4e51-ae82-9cd88ac019dd)

**Comment by chungweileong94** [comment]
Just realized it only available in the new Auth.js core, I guess we just have to wait🙂
