### ISSUE TITLE
Google Provider *accessToken* expiry

### ISSUE THREAD

**Issue by erikash** [nextauthjs/next-auth#7493]
### Question 💬

I'm using the Google provider and the default returned `accessToken` expiry is 1 hour. 
(regardless of the `next-auth` default session expiry is 30 days).

I've come across this post that states you can set the access token expiry to up to 12 hours. 

Is there a way to extend the expiry of the `accessToken`? something in the line of passing `expires_in` to Google API? (without using offline access and etc...)

### How to reproduce ☕️

Any use of the Google Provider.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by ThangHuuVu** [comment]
You could try adding the authorization params:
```js
 const options = {
    providers: [
      GoogleProvider({
        clientId: process.env.GOOGLE_ID,
        clientSecret: process.env.GOOGLE_SECRET,
        authorization: {
          params: {
            expire_in: 43200 // 12 hours
          }
        }
      })
    ],
  }
```

Hope that helps
