### ISSUE TITLE
How to use Email provider for magicLinks with sveltekit

### ISSUE THREAD

**Issue by olmohake** [nextauthjs/next-auth#7495]
### What is the improvement or update you wish to see?

I am trying to setup a form for a sveltekit ui and a postgres database. I managed to write an adapter and am able to login via github. Now i am trying to setup up a magic link login form. I included the email provider but have no idea how to call it and there are no explanations and the svetltekit example does not implement the magic link login.

### Is there any context that might help us understand?

implementing a magic link login form in sveltekit

**Comment by cd-slash** [comment]
Also trying to set up magic link / Email provider with Sveltekit. Have tried using the Nextjs code in the docs for Email provider, but it generates immediate type errors with SvelteKit.

**Comment by balazsorban44** [comment]
The Email provider should work the same way as for NextAuth.js. Please open a bug report if you have issues. Probably worth following #9714
