### ISSUE TITLE
Don't set the global `App['PageData']['session']` by default in @auth/sveltekit

### ISSUE THREAD

**Issue by kaleabmelkie** [nextauthjs/next-auth#7496]
### Question 💬

This is regarding the global type declarations of @auth/sveltekit written here: 
https://github.com/nextauthjs/next-auth/blob/b96f01319c751c7d62433c24fdb9f3f8f1e572c1/packages/frameworks-sveltekit/src/lib/index.ts#L291-L301

---

In line 298, @auth/sveltekit is assuming there definitely is a '+layout.server.ts' (or '+page.server.ts') `load` function that returns a data with a key matching exactly "`session`", as follows:

```ts
async function load(event) {
  return {
    session: await event.locals.getSession() // <--- this "session" key is written/decided by the user
  }
}
```

However, the session could be passed to the front-end as data using a different name than "`session`" (it could be "`mySession`", etc.).

We don't need to manually type out the `PageData` section at the library level, because:

1. SvelteKit automatically types out what ever is passed from these `load` functions to be available at **the correct nesting level** of `PageData` (the right `export let data`) based on the router's nesting level.

2. This also uses the right key, and the users won't have to use exactly the "`session`" key (otherwise risk wrong typings provided by this library in their app code).

3. To make them available in the `$page.data.whateverIDecidedToNameMySessionKey`, users can add it to the `PageData` of their app's 'src/app.d.ts' file as follows (as [detailed in SvelteKit the docs](https://kit.svelte.dev/docs/types#app-pagedata)):

```ts
// SvelteKit's 'src/app.d.ts'

import type { Session } from '@auth/core/types'

declare global {
  namespace App {
    interface PageData {
      whateverIDecidedToNameMySessionKey: Session | null // <-- most likely just "session"
    }
  }
}

export {}

```

---

Another major issue caused by the library setting the `PageData['session']` by default is when customizing the Session object using the [core Callback functions](https://authjs.dev/guides/basics/callbacks).

For example, let's say we used the `session()` callback to add `id`, `role`, & `plan` fields to the user object (in addition to the already set `email`, `name` and `email` fields). Since this is app specific, to make it available in SvelteKit we can do:

```ts
// SvelteKit's 'src/app.d.ts'

import type { Session } from '@auth/core/types'

declare global {
  type MyEnhancedSessionType = Session & {
    user: Session['user'] & {
      id: number
      role: 'admin' | 'user'
      plan: 'free' | 'paid'
    }
  }

  namespace App {
    interface Locals {
      getSession(): Promise<MyEnhancedSessionType | null>
    }

    interface PageData {
      session: MyEnhancedSessionType | null
    }
  }
}

export {}

```

However, the library has already provided the `App['Locals']['getSession']` and `PageData['session']`, and the end result of `event.locals.getSession()` and `$page.data.session` would be **overloaded** function & value types.

This causes issues, especially in the HTML part of typed Svelte components (because typescript is not allowed in the HTML template parts yet).

We'd occasionally get errors like the following because sometimes the definition in [packages/frameworks-sveltekit/src/lib/index.ts#L291-L301](https://github.com/nextauthjs/next-auth/blob/b96f01319c751c7d62433c24fdb9f3f8f1e572c1/packages/frameworks-sveltekit/src/lib/index.ts#L291-L301) override the one defined in the user's `src/app.d.ts`:

<img width="1006" alt="Screenshot 2023-05-09 at 6 07 45 PM" src="https://github.com/nextauthjs/next-auth/assets/29814842/6c5d2a9e-d382-4bd4-824a-869b22703070">

---

I think the best option here would be to delete the `App['PageData']` (& maybe `App['Locals']` too?) declarations from this library, and let the users set the `App['Locals']['getSession']` (this one must be exactly `getSession` because it's written in the library), and the session data response object (with whatever key they want) manually in the `src/app.d.ts` of their app.

Please let me know if I'm missing something, or if there is a workaround for this issue (especially the `App['PageData']['session']['user']` customization issue).

### How to reproduce ☕️

.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by SasaHrgovic** [comment]
I have the exact same issue, the second part at least. For the first part in my case 'session' key is fine.
For the second part, I've tried many options, including Module Augmentation as suggested here in [Auth.js documentation](https://authjs.dev/getting-started/typescript#module-augmentation).

There's also an existing issue regarding this: #6640. I've tried some options from there, but none of them worked.

In order to avoid having errors and not having to cast everything as `any` type, I've implemented the app.d.ts file like this:

```ts
declare namespace App {
  interface User {
    id: string;
    name: string;
    email: string;
    image: string;
    roleId: string;
    organizationId: string;
  }
  interface Session {
    user?: User;
    expires: string;
    accessToken?: string;
  }
  interface Locals {
    getSession(): Promise<Session | null>
  }
  interface PageData {
    session: Session | null;
  }
}
```

Ie. I basically 'reimplemented' the Session type from Auth.js library, because it has just a few properties anyways. Please note that I don't use `declare global` and `export {}`, this is basically the entire content of the file.

In `hooks.server.ts` file though, in those callback functions where I define the SvelteKitAuth object, I still need to cast as any to add those additional fields to auth session, but this is expected since augmenting doesn't work, and it's still only that one file where I need to do stuff like that

**Comment by kaleabmelkie** [comment]
Seems to fixed now

See: https://github.com/nextauthjs/next-auth/issues/6640#issuecomment-1633159323
