### ISSUE TITLE
How to set cookie in response object using Nextjs 13 route handlers?

### ISSUE THREAD

**Issue by DoronTorangy** [nextauthjs/next-auth#7497]
### Question 💬

I have a NestJS backend that exposes an API for authentication, that returns 2 jwt tokens: access and refresh token.

In next-auth i am able to get these tokens from Nest, I set the access token to the session object so it is returned to the client.

Now I want to set the refresh token as a http only cookie, but i dont have access to the response object. im exporting the auth api like so:

```ts
import NextAuth from "next-auth"

const handler = NextAuth({
  ...
})

export { handler as GET, handler as POST }
```

How can I set a cookie with route handlers?

### How to reproduce ☕️

```ts
import NextAuth from "next-auth"

const handler = NextAuth({
  ...
})

export { handler as GET, handler as POST }
```

Here, i dont have access to the response object in order to set a cookie

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
https://next-auth.js.org/configuration/initialization#advanced-initialization

The syntax is just slightly different.

You could eg.:

```ts
export { handler as POST }

export async function GET(request) {
  const authResponse = await handler(request)
  // add/mutate the response as you wish
  return authResponse
}
