### ISSUE TITLE
Doesn't getSession cache responses?

### ISSUE THREAD

**Issue by ari-al** [nextauthjs/next-auth#7502]
### Question 💬

On one page, we're calling getSession() to hold a token in the authentication header for each API call.

I thought that if I had called getSession() before, the response would be cached and subsequent requests would return the cached response, but in the browser network tab I keep seeing new requests for /api/auth/session. 

Am I misunderstanding or is there an option I need to set regarding caching?

### How to reproduce ☕️

```
axiosInstance.interceptors.request.use(async config => {
  const session = await getSession();

  if (session?.accessToken) {
    config.headers['Authorization'] = `Bearer ${session.accessToken}`;
    config.headers['withCredentials'] = true;
  }

  return config;
});
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
`getSession()` is essentially just a `fetch("/api/auth/session").then(res => res.json())` call, there is no caching involved.
