### ISSUE TITLE
SvelteKit: Provider Type

### ISSUE THREAD

**Issue by bmw2621** [nextauthjs/next-auth#7509]
### Question 💬

I am setting a new project to match the template example for the SvelteKit framework.

When setting up hooks, there are type errors on the core providers not matching the `SvelteKitAuth` provider option type.

`@auth/sveltekit` is resolving its core dependency to 0.5.1, while adding the latest `@auth/core` resolves. 0.7.1.

Is there a reason this is happening I dont understand?

![image](https://github.com/nextauthjs/next-auth/assets/20196494/f3630901-8f96-41bc-ac53-c438bbaadc23)

### How to reproduce ☕️

Replicated in codesandbox

https://codesandbox.io/p/sandbox/cool-babbage-nbsfks

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by etiennelenhart** [comment]
Any updates? I'm seeing the same and the SvelteKit integration is basically unusable. Or is there any workaround?

**Comment by bmw2621** [comment]
This appears to be resolved as `@auth/sveltekit` dependency of `@auth/core` and the project dependency are both resolving to `0.9.0`
