### ISSUE TITLE
signIn callback does nothing when returning an object

### ISSUE THREAD

**Issue by eak12913** [nextauthjs/next-auth#751]
**Describe the bug**
In the documentation for `signIn` callback (https://next-auth.js.org/configuration/callbacks#sign-in-callback) I see that it should be possible to return 
>@return {boolean}         Return `true` (or a modified JWT) to allow sign in

This leads me to believe that if I return some kind of object:

```
return { foo: "bar" }
```

Then this would get propagated the the jwt. This does not appear to be the case if you look at the code:
https://github.com/nextauthjs/next-auth/blob/main/src/server/routes/callback.js#L71

The only thing that happens with the result is that it's checked to see if it's `false`

**Steps to reproduce**
1. sign in a user
1. return an object with some sample property (`foo: "bar"`) from the `signIn` callback
1. place a log method in the `jwt` callback method

**Expected behavior**
`foo: "bar"` should appear as one of the properties in the `jwt` callback

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by eak12913** [comment]
@iaincollins If you have a moment - could you please comment here. Is this an issue, an issue with docs or just an issue with me doing something wrong. Thanks!

**Comment by balazsorban44** [comment]
I believe this is an issue with the documentation. We should probably update it to reflect the real behavior.

Or do the opposite and make the code do what the docs says.

**Comment by eak12913** [comment]
@balazsorban44, it _would_ be convenient to be able to return a set of properties that get appended to the JWT. Right now, I get around by appending a new property to the `req` object in my `signIn` callback and then in the `JWT` callback, I check the `req` object and, if present, copy that property to the JWT.

**Comment by balazsorban44** [comment]
All right, I guess it should not be hard to forward the response from line 71 to the jwt callback. We only check if the response is explicitly false or an error anyway. I'm going to make a PR for this, and discuss with the others. I'll keep you updated

**Comment by balazsorban44** [comment]
Updated the code to handle returned strings correctly, and changed the docs that wrongly suggested that you can return a modify JWT. To reiterate, all JWT modifications should be done in the `jwt` callback.
