### ISSUE TITLE
Support setting cookies from server components?

### ISSUE THREAD

**Issue by dmitryfd** [nextauthjs/next-auth#7512]
### Description 📓

It looks like from v13.4 onwards, Next.js now supports [setting cookies](https://nextjs.org/docs/app/api-reference/functions/cookies#cookiessetname-value-options) using dynamic `cookies()` function.

With that, can `getServerSession()` method from `/app` directory be updated accordingly?

<img width="748" alt="image" src="https://github.com/nextauthjs/next-auth/assets/2302043/054a20a3-68cc-4e4f-8a05-bb57958d999f">

### How to reproduce ☕️

https://github.com/nextauthjs/next-auth/blob/cca94bfe83db84282f41d0e843d19a5526c39e84/packages/next-auth/src/next/index.ts#LL188C3-L202C4

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by PaulWild** [comment]
> This method is only available in a [Server Action](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions) or [Route Handler](https://nextjs.org/docs/app/building-your-application/routing/router-handlers).

The ability to do it from a page is still missing I believe

**Comment by PaulWild** [comment]
> This method is only available in a [Server Action](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions) or [Route Handler](https://nextjs.org/docs/app/building-your-application/routing/router-handlers).

The ability to do it from a page is still missing I believe

**Comment by balazsorban44** [comment]
The answer is similar to https://github.com/nextauthjs/next-auth/issues/7522#issuecomment-1544027242

As also mentioned above, `cookies().set` support in Server Components is not currently planned. Server Component rendering cannot have side effects like setting cookies.
