### ISSUE TITLE
How to access request object in provider custom token request?

### ISSUE THREAD

**Issue by sheiman-pavlo** [nextauthjs/next-auth#7518]
### Question 💬

I have a custom OAuth-based provider, which depends on some data from the request. Basically, I want to initiate sign-in process with some extra parameter, and the pick it up in the provider's token/profile request handlers. Note: I'm not using built-in sign-in page, and my goal to skip it completely, so I initiate sign-in programmatically.

Here is a simplified example.

I initiate a sign-in process with extra parameter:

```ts
    await signIn('my-provider', { callbackUrl, extraParameter });
```

Then, I have access to it in the API route handler:

```ts
router.all((req, res) => {
  const { nextauth: nextAuthQuery } = req.query;

  if (nextAuthQuery?.includes('signin') && nextAuthQuery?.includes('my-provider')) {
    // here, the extra parameter is present and I want it to either pass to provider, or somehow access request object in the provider to pull it
  }

  // eslint-disable-next-line @typescript-eslint/no-unsafe-return
  return NextAuth(req, res, authOptions);
});
```

But there is no way I can pass this into provider's token.request to use it in the API call. I have tried defining prop in the provider and assigning it in the API route handler, like this:

API route:
```ts
router.all((req, res) => {
  const { nextauth: nextAuthQuery } = req.query;

  if (nextAuthQuery?.includes('signin') && nextAuthQuery?.includes('my-provider')) {
    myProvider.extraParameter = (req.body.extraParameter as string) ?? undefined;
  }

  // eslint-disable-next-line @typescript-eslint/no-unsafe-return
  return NextAuth(req, res, authOptions);
});
```

Provider:
```ts
return {
    //...base-fields
    extraParameter: undefined, // my extraParameter, which is being set in the route handler
    authorization: {
      url: //...baseUrl?code=not-used, // not used in my flow, so I replace it with dummy url and auth code
    },
    token: {
      async request({ provider }) {
        // here I want to access extraParameter OR request object to pull extraParameter
      },
    },
    userinfo: {
      request: async ({ provider }): Promise<IUserInfoProfileBackendEntity> => {
        // here I want to access extraParameter OR request object to pull extraParameter
      }
    },
    profile(profile: IUserInfoProfileBackendEntity): User {
      // here I want to access extraParameter OR request object to pull extraParameter
    },
  };
```

The approach with custom prop in provider (as described above) does work, but have some nehative side-effects. For example, sometimes parameter is being overwritten and provider receives undefined.

What is correct way to handle this? Is there a way to access whole request object in the provider's request handlers?

### How to reproduce ☕️

@TBD

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
The `signIn` method initiated the OAuth sign-in process, by creating the authorization URL the client (browser) will redirect the user to. Passing extra parameters to `signIn` cannot be passed to the token request, which happens from the server-side during the token exchange.

With other words, `token.request` is not invoked at the same time when `extraParameter` is available. It's a different invocation of the whole `[...nextauth]` endpoint.

Without a reproduction or a more intricate description of what you are trying to achieve though, it's hard to give a more helpful answer.
