### ISSUE TITLE
Getting oAuthCallback error even though I don't have any callbacks

### ISSUE THREAD

**Issue by Xodarap** [nextauthjs/next-auth#752]
**Describe the bug**
I've been sporadically getting redirected to `/api/auth/error?error=oAuthCallback` when logging in. While trying to debug this, I removed all of my callbacks, but I still get this problem. I turned on debug mode but the logs don't provide any more information. I'm kind of confused about how this could happen because [the redirect](https://github.com/nextauthjs/next-auth/blob/8115a7c66cdb1d86b0d2a0d76b9aa33c2bfaa33b/src/server/routes/signin.js#L29) seems to have a log statement right before it. I am getting debug statements from my session API call.

I noticed that if I manually GET `/api/auth/callback/google` I get 302 redirected to `/api/auth/error?error=oAuthCallback`. So possibly it's related to will not providing the right response?

It's possible that the underlying issue is me doing something wrong here, but I think it's a bug that the error message is about callbacks given that I don't have any.

**Steps to reproduce**
This only happens me on mobile, which is quite confusing. Because of this it's hard for me to do more debugging. Here's my configuration:

```
class User extends Adapters.TypeORM.Models.User.model {
  constructor(name, email, image, emailVerified) {
    super(name, email, image, emailVerified)
  }
}

const UserSchema = {
  name: "User",
  target: User,
  columns: {
    ...Adapters.TypeORM.Models.User.schema.columns,
    admin: {
      type: "bool",
      nullable: true,
    },
    pro: {
      type: "bool",
      nullable: true,
    },
  },
}

const UserWrapper = { model: User, schema: UserSchema }


const options = {
  // Configure one or more authentication providers
  providers: [
    Providers.Google({
      clientId: process.env.GOOGLE_ID,
      clientSecret: process.env.GOOGLE_SECRET
    }),
    // ...add more providers here
  ],

  // A database is optional, but required to persist accounts in a database
  adapter: Adapters.TypeORM.Adapter(
    // The first argument should be a database connection string or TypeORM config object
    process.env.DB_URL,
    // The second argument can be used to pass custom models and schemas
    {
      models: {
        User: UserWrapper
      },
    }),
  pages: {
    newUser: '/authentication/new_user'
  },
  events: {
    createUser: createProfile
  },
  debug: true
}
```

**Expected behavior**
ideally this should work, but at least it should give me a helpful error message.

**Screenshots or error logs**
my logs just look like this, even though debugging is turned on:
```
[GET] /api/auth/error?error=oAuthCallback
20:31:08:71
[POST] /api/auth/signin/google
20:31:06:28
```

**Additional context**

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by Xodarap** [comment]
I fixed the problem by switching from this:
`<button color="inherit" onClick={() => signin('google')}>Sign in</button>`
To this:
`<button color="inherit" onClick={() => signin()}>Sign in</button>`
I don't understand why this mattered – Google is my only provider – and I can't get this to replicate in a standalone project. But keeping the issue up in case others run into it.

**Comment by aidankinzett** [comment]
Has there been any progress on this issue? I am experiencing the same thing every time a user signs up for the first time.

**Comment by balazsorban44** [comment]
Without a proper reproduction, it is quite hard to guess the real issue here.

**Comment by PseudoCodeNerd** [comment]
Some users on my webapp have consistently reported of experiencing this issue on signing up (through disord). I've tried pinpointing the culprit through the debug mode and also removing all my modified callbacks. 

The interesting part is that it works without an error on my system, both in production and development while certain users encounter this.

I'd really appreciate some progress on this issue.

Thank you

**Comment by balazsorban44** [comment]
@PseudoCodeNerd as I mentioned earlier, without a proper reproduction we are as helpless as you are. Once someone can reproduce us the problem and verifies that the problem is with `next-auth` we can have a closer look.

**Comment by Rashmi-278** [comment]
Hello , I am facing the same issue

**Comment by znwhite** [comment]
same. Locally I am able to sign into my app with Google but on the live link I am consistently seeing `/error?error=Callback#`

**Comment by jpcmf** [comment]
I'm facing the same issue with Github when deploy application to Vercel.

**Comment by balazsorban44** [comment]
The OP said they fixed the problem. Anyone else please open a bug report with  A PROPER REPRODUCTION, otherwise we cannot help you.
