### ISSUE TITLE
Calling `getServerSession` in Server Action triggers error "Invariant: Method expects to have requestAsyncStorage, none available"

### ISSUE THREAD

**Issue by lukevers** [nextauthjs/next-auth#7523]
### Environment

```
  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 798.67 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 3.2.4 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Firefox Developer Edition: 114.0
    Safari: 16.3
```

### Reproduction URL

https://github.com/lukevers/next-644

### Describe the issue

I came across this issue https://github.com/vercel/next.js/issues/46356 and thought the issue was nextjs with cookies, and confirmed that on the most recent release of next. I updated to `13.4.2-canary.5` and saw the issue subsided with cookies directly. I tested with next-auth as a replacement to see if that resolved the issues, and saw the same issue here while the next cookie example was no longer an issue.

Bringing over my comment from [here](https://github.com/vercel/next.js/issues/46356#issuecomment-1544059894):

> OK so I initially had cookies().get('anything'); which did cause issues, but not on 13.4.2-canary.5. I do still get these errors, but not with cookies directly, I get them when I'm using getServerSession from import { getServerSession } from 'next-auth/next'; -- I'm not sure if this is a nextjs issue or a [next-auth](https://github.com/nextauthjs/next-auth) issue since cookies directly seem to work OK.
>
> I have two pages that define two situations:
>
> * /issue1 - "individual server components" - The main issue here is that when we access cookies through a server component imported from a client component, it does not work. It works if we import it in a server component (page layout here) and pass it to the client component as a prop.
> * /issue2 - "shared server component" - The issue here is that when we access cookies through a server component imported from a client component, it does not work. It also does not work even if it was passed through to the client component if the server component is the same component

### How to reproduce

Download my example repo, run it, and follow the instructions.

### Expected behavior

Instead of causing an error, it should let me get access to the session (in the repo example it's null, but that's fine/expected in that example)

**Comment by lukevers** [comment]
@balazsorban44 Is there a timeline for v5? In the meantime do you have a workaround example?

**Comment by balazsorban44** [comment]
NextAuth.js v5 is planned for this or the coming week. Maybe `getToken` could be used if you do not use a database session.

**Comment by lukevers** [comment]
@balazsorban44 OK, yeah, this feels odd. https://github.com/lukevers/next-644/commit/ca99b9ed6bb89de1fd2a19af7f493db2761ca627

On there if you navigate to `/local` both of buttons will work, but the `/issue1` and `/issue2` routes that still pull from the library are not working.

**Comment by mwawrusch** [comment]
So ran into this as well. Is there a pre release of NextAuth.js v5  - this is blocking us right now.

**Comment by subvertallchris** [comment]
You can work around this by passing the server action as a prop from a server component into a client component.

**Comment by lsagetlethias** [comment]
In a server action, you can trick `getServerSession` to not detect RSC by building yourself the request and the response object, (reproducing internal next-auth code btw):

```ts
const req = {
headers: Object.fromEntries(headers()),
cookies: Object.fromEntries(
  cookies()
    .getAll()
    .map(c => [c.name, c.value]),
  ),
} as any;
const res = {
	getHeader() {
	  /* empty */
	},
	setCookie() {
	  /* empty */
	},
	setHeader() {
	  /* empty */
	},
} as any;
const session = await getServerSession(req, res, authConfig);
```

Maybe in the future, Next will give access somehow to server action's request and response, but in a meanwhile, that's what worked for me.

**Comment by YashTotale** [comment]
@lsagetlethias This was the only solution that worked for me!

**Comment by rodolfoag** [comment]
@lsagetlethias this solution worked for me to. Thx!
