### ISSUE TITLE
Support new Next route handlers in App dir

### ISSUE THREAD

**Issue by filipesmedeiros** [nextauthjs/next-auth#7529]
### Description 📓

Right now, `NextAuth(authOptions)` is not valid inside the App dir, as a [route handler](https://nextjs.org/docs/app/building-your-application/routing/router-handlers). It shouldn't be a hard change.

I guess I just wanted to make an issue to track progress on this.

### How to reproduce ☕️

Try to `export default NextAuth(authOptions)` inside `app/api/auth/[...nextAuth]/route.ts` and see errors.

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
It's already supported. See: https://next-auth.js.org/configuration/initialization#route-handlers-app

**Comment by filipesmedeiros** [comment]
Oh boy, I'm so sorry for wasting your time. Thank you.
