### ISSUE TITLE
NextJS middleware does not work with Prisma Adapter

### ISSUE THREAD

**Issue by logan-anderson** [nextauthjs/next-auth#7535]
### Environment

System:
    OS: macOS 13.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 96.46 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: 2023.03.13.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 112.1.50.121
    Chrome: 113.0.5672.92
    Firefox: 109.0.1
    Safari: 16.4
    
  (Latest version of next, react, next-auth, etc)

### Reproduction URL

https://github.com/logan-anderson/next-auth-bug-example

### Describe the issue

When using the Prisma Adapter and nextjs middleware to protect certain routes the nextjs middle does not work and the user is stuck in an infinite login loop.

See this video for more info: https://www.loom.com/share/3d8906bd2ac74ce2b6b0ab3519ed58bb

### How to reproduce

- Pull down [Reproduction repo](https://github.com/logan-anderson/next-auth-bug-example)
- Run `yarn install`
- Add discord provider env variables and all other necessary env vars. 
```env
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=***

DISCORD_CLIENT_ID=***
DISCORD_CLIENT_SECRET=***
DATABASE_URL=file:./dev.db
```
- Run `yarn dev`
-  See login loop on `/`
- Comment out  Prisma Adapter

```ts
// pages/api/auth/[...nextauth].ts

const prisma = new PrismaClient();

// import AppleProvider from "next-auth/providers/apple"
// import EmailProvider from "next-auth/providers/email"

// For more information on each option (and a full list of options) go to
// https://next-auth.js.org/configuration/options
export const authOptions: NextAuthOptions = {
  // adapter: PrismaAdapter(prisma),
  //...
```

See that it now works as expected

### Expected behavior

It should not be an infinite login loop. It should login the user once and then the middleware should not redirect them to the login page (how it behaves without the prisma adapter)

**Comment by thadeubrito** [comment]
adding this in the authOptions at `[...nextauth].js` worked to me, but I'm not sure yet about the impacts of this change.
```
  session: {
    strategy: "jwt",
  },
```

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth/issues/7535#issuecomment-1546357813 This is the correct solution. See: https://next-auth.js.org/configuration/nextjs#caveats

**Comment by willredington** [comment]
![image](https://github.com/nextauthjs/next-auth/assets/29963214/f3e0f37f-1e25-4f7b-a6ac-0898577d145e)

Seeing the same issue here, the changing the session strategy to JWT caused the prisma adapter to fail

**Comment by anasmohammed361** [comment]
I've been using credential provider , so my provider has a instance of a db involved so it basically sucks and there is not way to get around this , one small work around is to opt in for JWT authentication and to manually decrypt the jwt token in the middleware

```
// import { auth } from '@/lib/auth'
import { getToken } from 'next-auth/jwt';
import { NextRequest, NextResponse } from 'next/server';

export async function middleware(req: NextRequest) {
  const token = await getToken({
    req,
    secret: process.env.AUTH_SECRET!,
    salt: "authjs.session-token"
  });
  const session = token?.id
  if (req.nextUrl.pathname.startsWith('/api/uploadthing')) {
    return NextResponse.next()
  }
  if (req.nextUrl.pathname.startsWith('/api/socket')) {
    return NextResponse.next()
  }
  if (req.nextUrl.pathname.startsWith('/signin') && session) {
    const url = req.nextUrl.clone();
    url.pathname = '/';
    return NextResponse.redirect(url)
  } else if (req.nextUrl.pathname.startsWith('/signin') && !session) {
    return NextResponse.next()
  }
  if (!session) {
    const url = req.nextUrl.clone();
    url.pathname = '/signin';
    return NextResponse.redirect(url)
  }
  return NextResponse.next();
}


export const config = {
  matcher: ["/((?!api|_next/static|_next/image|favicon.ico).*)"],
}
```

this is my middleware function , tbh even though this might not be the safest approach this will work as long as the cookie name match , 

> The cookie name with change if you are using secure cookies in auth js/ next auth https://github.com/nextauthjs/next-auth/discussions/9133#discussioncomment-9120827
