### ISSUE TITLE
Return an error message to client in the same page

### ISSUE THREAD

**Issue by natsathorn** [nextauthjs/next-auth#754]
**Your question**
How to return the message to the login form?

**What are you trying to do**
I'm using Credentials provider which will just fire a request to another server for login. It's work fine when everything go as plan. In the case that login is not success, I can only send the error message via querystring which make the page reloaded.
Is there any other way to send the errorMessage back to the form without reload it.

FYI. I used `signIn('myAuth', { ...data })` on my login form.

**Feedback**
In this [section](https://next-auth.js.org/providers/credentials#example), it only shows these two options.
```
// You can also Reject this callback with an Error or with a URL:
return Promise.reject(new Error('error message')) // Redirect to error page
return Promise.reject('/path/to/redirect')        // Redirect to a URL
```

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by bdub9** [comment]
I'm having the same issue.  Desired use case to skip a redirect:

1. Check if a user/password combo exists or password match.
2. They don't. Would like to Promise.reject with an error code or error message WITHOUT redirecting. Doesn't seem like there's a way to skip the redirect, even Promise.reject('/login?errorMessage=tryAgain') here reloads the page. How can we just send down a simple error message in a response so our client can handle it?

**Comment by mdesilva** [comment]
I'm having the same issue as well. Would be nice if we can just do the login RESTfully and do the redirection ourselves.

**Comment by MateuszWawrzynski** [comment]
*bump*
@iaincollins 

I'm looking for the answer for exactly the same problem.
Any ideas?

Is there any way to handle error code on the signin page without redirecting to "error" page and just show the error under the login form?

**Comment by mdesilva** [comment]
You can return the error as a query parameter to the login page
