### ISSUE TITLE
wrong type on signOut event

### ISSUE THREAD

**Issue by altsst** [nextauthjs/next-auth#7544]
### Question 💬

The signOut event (https://next-auth.js.org/configuration/events)

has a wrong typescript type, because instead with the typed structure of `{ session: { user: {  id: "abc"  }} }` it looks like this `{ session: { id: "abc" } }`

### How to reproduce ☕️

    signOut: (data) => {
      console.log(data)
    }
    
    compare the output of this event with the type `signOut: (message: { session: Session; token: JWT }) => Awaitable<void>`

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by altsst** [comment]
it's still an issue

**Comment by jamesbruice** [comment]
it's still an issue
