### ISSUE TITLE
Keycloak session and tokens are not 

### ISSUE THREAD

**Issue by mrbodich** [nextauthjs/next-auth#7550]
### Question 💬

When I use Keycloak provider, Next-Auth does not care about the Keycloak session and tokens itself.
It keeps it's own session, but I need to authenticate relying on the Keycloak. Keycloak is the main source of truth in my project.

What I mean, Keycloak is the tokens issuer for my REST API service, with next-auth I can get only first token which expires in 5 minutes, and that's all.

1. After 5 minutes I have long-live session from Next-Auth and no any tokens refresh
2. If I kill Keycloak session, Next-Auth does not check that.

How to keep everything in sync or proxy Keycloak session directly?
Or maybe how can I configure Next-Auth to acquire everything like token, refresh token from Keycloak based on Keycloak session, like client-side oidc client does?

### How to reproduce ☕️

Authenticate with Keycloak and kill session from Keycloak admin panel.
OR
Authenticate with Keycloak, take it's token. In 5 minutes Next-Auth will keep that expired token that is useless already, it will not ask issuer for the new token.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by kreonix** [comment]
Hi, have you found solution? I have same problem with sync session useSession and keyloack after kill session.
