### ISSUE TITLE
Custom JWE Code : Do not see the Token but it works

### ISSUE THREAD

**Issue by rcritt** [nextauthjs/next-auth#7551]
### Question 💬

I made a custom JWE encryption to make it easier for other apps to use/decode the token.
The good news is everything works with sign-on in my Next.js app!
The thing I am puzzed by is a diagnostic script I have.

That script, with the customized encryption, shows the raw token but does not show the token in "presentation" form.
So now I get null for the following.
`const token = await getToken({ req })
res.send(JSON.stringify(token))`

I still get data for this call however.
`const token2 = await getToken({ req: req, raw: true })
res.send(token2); `

I assume there is some other part of the system I need to patch into?

### How to reproduce ☕️

I have the following in the [..nextauth].ts script...

imports
````
import { EncryptJWT, jwtDecrypt, base64url } from "jose";
import { JWT } from "next-auth/jwt";
import { v4 as uuid } from "uuid";`
````

core code:
````
jwt: {
    async encode(params: {
        token?: JWT
        secret: string | Buffer
        maxAge?: number
    }): Promise<string> {
        const secret = base64url.decode(params.secret);
        const now = () => (Date.now() / 1000) | 0;
        const jwt = await new EncryptJWT(params.token!)
            .setProtectedHeader({ alg: "dir", enc: "A256GCM" })
            .setIssuedAt()
            .setExpirationTime(now() + params.maxAge!)
            .setJti(uuid())
            .encrypt(secret);
        console.log(\'SECRET===> ${params.secret}, JWT===> ${params.token?.email}, jwt===>${jwt}\`);
        // return a custom encoded JWT string
        return jwt; 
    },
    async decode(params: {
        token?: string
        secret: string | Buffer
    }): Promise<JWT | null> {
        console.log("DECRIIIP{T")
        console.log(`JWT STring=${params.token}`)
        const secret = base64url.decode(params.secret)
        // return a `JWT` object, or `null` if decoding failed
        const decrypedResult = await jwtDecrypt(params.token!, secret, {});
        console.log(`Email= ${decrypedResult.payload["email"]}, ${decrypedResult.payload["exp"]}`);
        return decrypedResult.payload;
    },
}
````

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
you'll have to pass the same decode method and secret to  `getToken`, otherwise it'll fall back to the default decode method and secret

https://github.com/nextauthjs/next-auth/blob/f62c016725bf65e80a3cf5b6c59293120492fc4e/packages/next-auth/src/jwt/index.ts#L79-L81
