### ISSUE TITLE
PrismaAdapter: 'Argument `user` is missing.' with twitter oauth 1.0a

### ISSUE THREAD

**Issue by pedrommarquesm** [nextauthjs/next-auth#7553]
### Adapter type

@next-auth/prisma-adapter

### Environment

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 662.30 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 113.1.51.114
    Chrome: 113.0.5672.92
    Safari: 16.3

### Reproduction URL

N/A

### Describe the issue

Been using twitter oauth 2.0 with no issues. trying to switch to the version 1.0a, I get an error from prisma adapter, after twitter oauth is successful:

```
[next-auth][error][adapter_error_linkAccount] 
https://next-auth.js.org/errors#adapter_error_linkaccount 
Invalid `prisma.account.create()` invocation:

{
  data: {
    provider: "twitter",
    type: "oauth",
    providerAccountId: "--",
    oauth_token: "--",
    oauth_token_secret: "--",
    userId: "--",
+   user: {
+     create: UserCreateWithoutAccountsInput | UserUncheckedCreateWithoutAccountsInput,
+     connectOrCreate: UserCreateOrConnectWithoutAccountsInput,
+     connect: UserWhereUniqueInput
+   }
  }
}
...
 'Argument `user` is missing.\n' +
    '    at bn (/.../node_modules/@prisma/client/runtime/library.js:164:1259)\n' +
    '    at Pn.handleRequestError (/.../node_modules/@prisma/client/runtime/library.js:171:6669)\n' +
    '    at Pn.handleAndLogRequestError (/.../node_modules/@prisma/client/runtime/library.js:171:6358)\n' +
    '    at Pn.request (/.../node_modules/@prisma/client/runtime/library.js:171:6237)',
  name: 'Error'
```

Although it creates a User, no Account is created (due to this error).

### How to reproduce

Have Next Auth configured with Prisma adapter + PostgreSQL database, with twitter legacy provider

### Expected behavior

To simply register/sign in user with no issues

**Comment by pedrommarquesm** [comment]
After trying with another boilerplate project, eventually I got the error referring to the missing field in the database: "oauth_token" and "oauth_token_secret". Although there is a warning in the next-auth documentation, all prisma.schema examples don't refer this.
Also, the message wasn't really clear about what was failing.

Closing since it was my fault not reading the docs with attention

**Comment by pedrommarquesm** [comment]
After trying with another boilerplate project, eventually I got the error referring to the missing field in the database: "oauth_token" and "oauth_token_secret". Although there is a warning in the next-auth documentation, all prisma.schema examples don't refer this.
Also, the message wasn't really clear about what was failing.

Closing since it was my fault not reading the docs with attention

**Comment by johnson-jesse** [comment]
@pedrommarquesm What was the solution to the error referring to the missing field in the database: "oauth_token" and "oauth_token_secret"?

**Comment by pedrommarquesm** [comment]
@johnson-jesse please refer to the "note" right in the beginning of the twitter provider docs: https://next-auth.js.org/providers/twitter
I missed it too... you need to add those field to your database schema, table "Account"
