### ISSUE TITLE
OAuthAccountNotLinked Error when using different provider accounts with same email as EmailProvider

### ISSUE THREAD

**Issue by dlamprey** [nextauthjs/next-auth#7562]
### Environment

This took me 3 hours to troubleshoot after thinking it was me, but then finding what appears to be a bug or at least provides a solution that will help others...

I have not researched the inner workings of Next Auth, but I suspect the root cause of the problem is that it is keying off of email address when looking up an existing user and not the combination of email address AND provider. I noticed that the user record does not have a foreign key to "accounts" but accounts does have a FK to "users." I would have expected there to be a unique user for each provider, regardless of whether they have the same email address. This would prevent problems caused by someone changing their email address with a third-party provider. It would also make it easier to show the provider name as part of the session data and display to the user.  I feel strongly that account "linking" should NOT be passive. It could be an optional feature that may also include an option to "collapse" multiple users with the same email address.

### Reproduction URL

Private Repo

### Describe the issue

Authentication with third-party providers such as Google and Facebook does not work if those accounts have the same email as previously authenticated using the EmailProvider

### How to reproduce

├─┬ @next-auth/mongodb-adapter@1.1.3
│ └── next-auth@4.22.1 deduped
└── next-auth@4.22.1

With these providers: EmailProvider, FacebookProvider, GoogleProvider

1. Start with a clean database (I used MongoDB)
2. Login using EmailProvider using an email address used with another provider (in my case I have a Facebook and Google account using the same email address)
3. Log out
4. Login using a different provider that has the same email address (e.g. Facebook)
5. Next Auth error

### Expected behavior

No error. A user with the same email address associated with different providers should be able to use any combination of providers to login. I would expect a separate user record to be created for each provider for such a user (regardless of there being a common email address.

**Use Case that DOES Work:**

1. Start with a clean database (I used MongoDB)
2. Login using a third-party provider (e.g. Facebook)
3. Log out
4. Log in using the EmailProvider using the email address associated with the account previously used to login using a third-party provider

**Comment by dlamprey** [comment]
@balazsorban44 i fully understand that sample code would make it easier to validate this issue. Unfortunately, my app will be private for a couple more weeks until it launches. Any chance that the EmailProvider could be added to the working example: https://next-auth-example.vercel.app/api/auth/signin?callbackUrl=https%3A%2F%2Fnext-auth-example.vercel.app%2F

**Comment by pyrexfm** [comment]
I think you might be facing this: ["When I sign in with another account with the same email address, why are accounts not linked automatically?"](https://authjs.dev/concepts/faq#feature-requests)

**Comment by dlamprey** [comment]
@balazsorban44 i created a codebase for which I was able to consistently reproduce the issue reported: https://github.com/dlamprey/nextauth 

I also have a public URL for a project hosted at Vercel that I can share privately with this codebase deployed.

are you able to re-open this issue or do I need to create a new one?
