### ISSUE TITLE
Type Error: Argument of type '[Request]' is not assignable to parameter of type 'GetServerSessionParams<GetServerSessionOptions>'

### ISSUE THREAD

**Issue by HRNPH** [nextauthjs/next-auth#7569]
### Question 💬

Did I do it wrong is this not the correct practice? (but it worked) any Idea on how to solve this?
Seem like there's no example of using this method on ts either
I followed [This Tutorial](https://www.youtube.com/watch?v=BXyDKfIe-es)
![image](https://github.com/nextauthjs/next-auth/assets/51855316/d85da929-654f-44c1-8072-b152092f08e5)

```bash
Argument of type '[Request]' is not assignable to parameter of type 'GetServerSessionParams<GetServerSessionOptions>'.
  Type '[Request]' is not assignable to type '[GetServerSessionOptions]'.
    Type 'Request' has no properties in common with type 'GetServerSessionOptions'.ts(2345)
```

### How to reproduce ☕️

Reproduce
```js
import { getServerSession } from "next-auth";
// create a POST function with Request type in Api route
export async function POST(request: Request) {
    const session = await getServerSession(request);
    return null
}
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by HRNPH** [comment]
In case of using this notation
```js
const session = await getServerSession({req: request});
```
Error
```bash
Argument of type '[{ req: Request; }]' is not assignable to parameter of type 'GetServerSessionParams<GetServerSessionOptions>'.
  Type '[{ req: Request; }]' is not assignable to type '[GetServerSessionOptions]'.
    Type '{ req: Request; }' is not assignable to type 'GetServerSessionOptions'.
      Object literal may only specify known properties, and 'req' does not exist in type 'GetServerSessionOptions'.ts(2345)
```

**Comment by balazsorban44** [comment]
Route Handlers are not currently supported by `getServerSession`. See the official docs https://next-auth.js.org/configuration/nextjs#getserversession

We are working on it though, expect a solution very soon... ™️

**Comment by HRNPH** [comment]
# Temporary Solution
Just for anyone facing the same issue but still! need to port to production by now

by adding ignore build errors for typescript it will still work as it does in development

next.config.js
```js
const nextConfig = {
    typescript: {
        ignoreBuildErrors: true,
    }
}
```
you can skip the type error
use with caution cause it will also skip the one you should've fixed it

**Comment by johannbuscail** [comment]
any update ?

**Comment by mistercorea** [comment]
Still not working why was this closed?
```
Type error: Argument of type '[NextRequest, NextResponse<unknown>, any]' is not assignable to parameter of type 'GetServerSessionParams<any>'.
  Type '[NextRequest, NextResponse<unknown>, any]' is not assignable to type '[IncomingMessage & { cookies: Partial<{ [key: string]: string; }>; }, ServerResponse<IncomingMessage>, any] | [...]'.
    Type '[NextRequest, NextResponse<unknown>, any]' is not assignable to type '[IncomingMessage & { cookies: Partial<{ [key: string]: string; }>; }, ServerResponse<IncomingMessage>, any]'.
      Type at position 0 in source is not compatible with type at position 0 in target.
        Type 'NextRequest' is not assignable to type 'IncomingMessage & { cookies: Partial<{ [key: string]: string; }>; }'.
          Type 'NextRequest' is missing the following properties from type 'IncomingMessage': aborted, httpVersion, httpVersionMajor, httpVersionMinor, and 51 more.

   6 | 
   7 | async function handler(req: NextRequest, res: NextResponse) {
>  8 |   const session = await getServerSession(req, res, authOptions);
     |                                          ^
   9 | 

```

**Comment by patilanz** [comment]
updates?

**Comment by ItzCrazyKns** [comment]
Its not a good practice to disable typescript build errors that can cause trouble, maybe should try

```ts
 const session = await getSession({ req: req as any as IncomingMessage })
 ```

> # Temporary Solution
> Just for anyone facing the same issue but still! need to port to production by **now**
> 
> by adding ignore build errors for typescript it will still work as it does in development
> 
> next.config.js
> 
> ```js
> const nextConfig = {
>     typescript: {
>         ignoreBuildErrors: true,
>     }
> }
> ```
> 
> you can skip the type error use with caution cause it will also skip the one you should've fixed it

**Comment by mxswat** [comment]
I can confirm that this is still an issue

**Comment by FlorianWendelborn** [comment]
@mistercorea don’t use `ignoreBuildErrors`, just add a `// @ts-expect-error` or if needed `// @ts-ignore` above the line that’s erroring.

**Comment by turnerhayes** [comment]
The linked docs don't seem to guide use for Route Handlers, although it mentions Route handlers:

> When calling from the server-side i.e. in Route Handlers, React Server Components, API routes or in getServerSideProps, we recommend using this function instead of getSession to retrieve the session object. 

This seems to suggest that the code presented there should work for Route Handlers, but it doesn't.

How do we get a session in Route Handlers? If we're using a DB adapter, we could query the DB directly, but it would be nice if we didn't have to.

**Comment by vousmeevoyez** [comment]
facing same issue here...

**Comment by rainnfx** [comment]
Any updates guys..?
