### ISSUE TITLE
getUserByAccount is not a function

### ISSUE THREAD

**Issue by KacperPaszkowski** [nextauthjs/next-auth#7578]
### Adapter type

@next-auth/prisma-adapter

### Environment

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
    Memory: 14.96 GB / 31.79 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.42)
    Internet Explorer: 11.0.19041.1566

  npmPackages:
    @next-auth/prisma-adapter: ^0.4.4-canary.81 => 0.4.4-canary.81+0d39d43

### Reproduction URL

https://github.com/KacperPaszkowski/next-auth-prisma

### Describe the issue

Using the latest `next-auth` and `prisma-adapter` with quickstart on next-auth page, I'm getting `getUserByAccount is not a function` error,

### How to reproduce

1. Clone the repository, set .env tokens and run server.
2. Open `localhost:3000` and click login button.
3. Click login with Google account.
4. Error thrown.

### Expected behavior

It shouldn't throw error.

**Comment by balazsorban44** [comment]
`@next-auth/prisma-adapter: ^0.4.4-canary.81 => 0.4.4-canary.81+0d39d43`

This is an outdated version of the adapter. Please upgrade to `@next-auth/prisma-adapter@latest`.

You can verify that the method is there https://www.npmjs.com/package/@next-auth/prisma-adapter?activeTab=code in `dist/index.js`

Can you point to where you found the quickstart? Was it a third-party tutorial/page or some of our official documentation?

**Comment by imnoahcook** [comment]
https://next-auth.js.org/v3/adapters/prisma
I had got the same errors just by following this tutorial. Maybe its outdated. It says to use the canary

**Comment by a-nasseur** [comment]
hi everyone i would need your precious help i have upgraded to the latest version of the prisma adapter. when i login using the google provider the prisma adapter get everything write in the database however the call back gets me back to login page instead of redirecting to the home page.

i am using:

## packages
- @next-auth/prisma-adapter": "^1.0.7
- @prisma/client": "^5.2.0
- next-auth": "^4.23.1

## middleware 
export { default } from 'next-auth/middleware';

## options
```
import type { NextAuthOptions } from "next-auth";
import GitHubProvider from 'next-auth/providers/github';
import CredentialsProvider from "next-auth/providers/credentials";
import { PrismaAdapter } from "@next-auth/prisma-adapter"
import { PrismaClient } from "@prisma/client"
import GoogleProvider from "next-auth/providers/google";

const prisma = new PrismaClient();

export const options: NextAuthOptions = {
    debug: true,
    adapter: PrismaAdapter(prisma),
    providers: [
        GoogleProvider({
            clientId: process.env.GOOGLE_ID as string,
            clientSecret: process.env.GOOGLE_SECRET as string
        }),
        GitHubProvider({
            clientId: process.env.GITHUB_ID as string,
            clientSecret: process.env.GITHUB_SECRET as string
        }),
     ],
}
```
on debug i have no errors, however no redirection to the home page i cannot understand exactly where the issue lies would need you support. 

thanks you for the help

**Comment by xencodes** [comment]
i am getting the same error on Firebase adapter

**Comment by tpompon** [comment]
Hello, the error is still present on `@next-auth/prisma-adapter@latest`
