### ISSUE TITLE
Missing default_phone Field in User Profile Data with Yandex Provider

### ISSUE THREAD

**Issue by shahriyor-sharifjonov** [nextauthjs/next-auth#7579]
### Provider type

Yandex

### Environment

System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 2700 Eight-Core Processor
    Memory: 7.19 GB / 15.93 GB
Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.42)
    Internet Explorer: 11.0.19041.1566

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

NextAuth.js is a powerful authentication library for Next.js applications. It provides an easy way to integrate with various third-party authentication providers, including Yandex. However, when using Yandex provider, the default_phone field is not being provided in the user profile data returned after successful authentication, even though it's expected to be part of the user profile data according to Yandex's OAuth 2.0 API documentation.

### How to reproduce

Set up a new Next.js application.
Install and configure NextAuth.js, using Yandex as the OAuth provider.
Make sure to include the default_phone field in the scope of the OAuth request.
Run the application, and log in using Yandex.
Check the user profile data returned after successful authentication. Notice that the default_phone field is not present.

### Expected behavior

When using Yandex as the OAuth provider in NextAuth.js and including default_phone in the scope of the OAuth request, the default_phone field should be included in the user profile data returned after successful authentication. This phone number field is crucial for certain applications where user's phone number might be necessary for contact or verification purposes.

**Comment by balazsorban44** [comment]
It won't be, by default. Please refer to the docs: https://next-auth.js.org/getting-started/example#extensibility https://next-auth.js.org/configuration/callbacks#jwt-callback https://next-auth.js.org/configuration/callbacks#session-callback

**Comment by EvgGitHub198** [comment]
It helped me to pull out the scope for the phone number just like that:

```
  providers: [
    Yandex({
      clientId: process.env.AUTH_YANDEX_ID!,
      clientSecret: process.env.AUTH_YANDEX_SECRET!,
      authorization: {
        url: "https://oauth.yandex.ru/authorize?scope=login:info+login:email+login:avatar+login:default_phone",
      }
    }),
  ]
```
