### ISSUE TITLE
Improve handler function arguments types for next route

### ISSUE THREAD

**Issue by mattiaz9** [nextauthjs/next-auth#7589]
### Question 💬

I'm parsing data from the request to create the config for next auth, so my `route.ts` looks like this:
```ts
export function GET(req: NextRequest, ctx: RouteContext<RouteParams>) {
  return NextAuth(req, ctx, reqAuthOptions(req, ctx))
}
export function POST(req: NextRequest, ctx: RouteContext<RouteParams>) {
  return NextAuth(req, ctx, reqAuthOptions(req, ctx))
}
```

Now, passing req and ctx are perfectly correct params as i looked here: https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/next/index.ts#L67

The problem is that the `NextAuth` handler wants the first argument to be `NextApiRequest` and the secon `NextApiReesponse` which were the pages arguments.

### How to reproduce ☕️

Just exporting `GET` and `POST` like this:

```ts
type RouteContext<T = {}> = {
  params: T
}
type RouteParams = {
  nextauth: string[]
}

export function GET(req: NextRequest, ctx: RouteContext<RouteParams>) {
  return NextAuth(req, ctx, {...})
}
export function POST(req: NextRequest, ctx: RouteContext<RouteParams>) {
  return NextAuth(req, ctx, {...})
}
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Thanks, closing in favor of #7443
