### ISSUE TITLE
Auth0: expected 200 OK, got: 404 Not Found

### ISSUE THREAD

**Issue by hobadams** [nextauthjs/next-auth#7591]
### Provider type

Auth0

### Environment

System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 556.48 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/Work/frontend/node_modules/.bin/yarn
    npm: 9.6.4 - /opt/homebrew/bin/npm
    Watchman: 2023.05.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 113.0.5672.126
    Safari: 15.6.1

### Reproduction URL

private

### Describe the issue

```
 "next": "13.4.1",
 "next-auth": "^4.22.1"
```

When signing in using the Auth0 provider I get the following error:

```
[next-auth][error][SIGNIN_OAUTH_ERROR] 
https://next-auth.js.org/errors#signin_oauth_error expected 200 OK, got: 404 Not Found {
  error: {
    message: 'expected 200 OK, got: 404 Not Found',
    stack: 'OPError: expected 200 OK, got: 404 Not Found\n' +
      '    at processResponse (webpack-internal:///(sc_server)/./node_modules/openid-client/lib/helpers/process_response.js:37:15)\n' +
      '    at Issuer.discover (webpack-internal:///(sc_server)/./node_modules/openid-client/lib/issuer.js:143:26)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async openidClient (webpack-internal:///(sc_server)/./node_modules/next-auth/core/lib/oauth/client.js:12:18)\n' +
      '    at async getAuthorizationUrl (webpack-internal:///(sc_server)/./node_modules/next-auth/core/lib/oauth/authorization-url.js:88:20)\n' +
      '    at async Object.signin (webpack-internal:///(sc_server)/./node_modules/next-auth/core/routes/signin.js:21:30)\n' +
      '    at async AuthHandler (webpack-internal:///(sc_server)/./node_modules/next-auth/core/index.js:259:36)\n' +
      '    at async NextAuthRouteHandler (webpack-internal:///(sc_server)/./node_modules/next-auth/next/index.js:49:30)\n' +
      '    at async NextAuth._args$ (webpack-internal:///(sc_server)/./node_modules/next-auth/next/index.js:83:24)\n' +
      '    at async eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:244:37)',
    name: 'OPError'
  },
  providerId: 'auth0',
  message: 'expected 200 OK, got: 404 Not Found'
}
```

I've checked the note [here](https://next-auth.js.org/errors#signin_oauth_error) but these don't seem to have an impact.

Other providers work fine but auth0 does not.

**side note**

Using the the credentials but the [nextjs-auth0 package](https://github.com/auth0/nextjs-auth0) works fine so it's **unlikely** to be a configuration issue.

Any help would be incredible!

Thanks

### How to reproduce

1. Create a next 13.4.1 app
2. Follow the normal setup steps
3. Click login

### Expected behavior

To be redirected to auth0 to login.

**Comment by balazsorban44** [comment]
From the looks of it, your issue is that the issuer endpoint is misconfigured.

You can see Auth0 working fine deployed here: https://next-auth-example.vercel.app

Cannot tell more without a reproduction, unfortunately.

**Comment by hobadams** [comment]
I've fixed this issue.
