### ISSUE TITLE
Cannot get user name from AppleProvider

### ISSUE THREAD

**Issue by CarstenHoyer** [nextauthjs/next-auth#7596]
I am upgrading this to an issue. I suspect it might be related to the string "name email" (see fx https://developer.apple.com/forums/thread/118209)

--- 

Hi, I use the standard AppleProvider setup. I can sign in and I do see my email in the response, but not my name. I have tried updating the authorization params, but even if I just ask for the name, it does not come back from the response.

I go into https://appleid.apple.com/account/manage and stop using "Sign in with Apple" on the relevant app - because i have read that Apple only returns the name on the first sign in.

How can I get the name in my sign in response?

_Originally posted by @CarstenHoyer in https://github.com/nextauthjs/next-auth/discussions/7560_

**Comment by CarstenHoyer** [comment]
So I wanted to inject a name into signIn. I figured it would show up in the request in AppleProvider. But actually the result from Apple show up here, and first name and last name are two separate fields:

`AppleProvider({
      clientId: ...,
      clientSecret: ...,
      async profile(profile) {
        console.log(req.body)
        return {
             ....
        }
      }
    }),`
    
    
    will give me: 
    `{ code: '...., user: '{"name":{"firstName":"Carsten","lastName":"Hoyer"},"email":"..."}
    `

**Comment by azeek21** [comment]
Hi, thanks for keeping the issue open. First of all, I think you can not get username because it is not added to scope. Below is source of the default scopes for AppleProvider. https://github.com/nextauthjs/next-auth/blob/a47b4ce6d33e74bb15c46e7994f27d352569d6a0/packages/next-auth/src/providers/apple.ts#L108
I guess next team does this because they want to keep the scope as minimum as possible. 

Secondly, looking at the source code I also found out Apple provider profile lacking some type definitions. But I think you found a workaround.

@balazsorban44  I can investigate in this more if you tell me where, and how to get started.

**Comment by balazsorban44** [comment]
Any default option can be overridden/extended. See https://next-auth.js.org/configuration/providers/oauth#override-default-options and https://next-auth.js.org/providers/apple#options

**Comment by CarstenHoyer** [comment]
Thanks @balazsorban44 I think it would be nice, if it was documented here https://next-auth.js.org/providers/apple

**Comment by manik-yml** [comment]
Hey @CarstenHoyer , thanks for the workaround, can you maybe help with example code, not able to figure out where the `req` is coming from and how to use it. I am working on next 13.4.2.

**Comment by ChrGrb** [comment]
@manik-yml The name and email are only returned on the first authorization request. To receive them again you will have to delete the Sign-In with Apple entry on appleid.apple.com.

**Comment by sml99** [comment]
@CarstenHoyer Can you please share how did you get access to the request body I'm using next-auth 4.24 and I'm having the exact same problem, I can see the user object in the browser developer tools but next auth is returning undefined

**Comment by BuhayovA** [comment]
> To keep things tidy, we are closing this issue for now. If you think your issue is still relevant, leave a comment and we might reopen it. Thanks!

Still relevant
Cant get user name from idToken, from profile and etc...

maybe i missed somthing ?
```
 AppleProvider({
    clientId: clientId,
    clientSecret: clientSecret,
    idToken: true,
    authorization: {
      params: {
        scope: "name email",
        response_type: "code",
        response_mode: "form_post",
      },
    },
  });
```
