### ISSUE TITLE
[CLIENT_FETCH_ERROR] in AWS Amplify

### ISSUE THREAD

**Issue by erwinagpasa** [nextauthjs/next-auth#7599]
### Environment

312-6f2da978d46d64b5.js:1 
 GET https://app.ikns.info/api/auth/session 500
139-601a8d7b508ad4e1.js:1 [next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error There is a problem with the server configuration. Check the server logs for more information. 
{error: {…}, url: '/api/auth/session', message: 'There is a problem with the server configuration. Check the server logs for more information.'}
client
: 
true
error
: 
{message: 'There is a problem with the server configuration. Check the server logs for more information.'}
message
: 
"There is a problem with the server configuration. Check the server logs for more information."
url
: 
"/api/auth/session"
[[Prototype]]
: 
Object

### Reproduction URL

https://app.ikns.info/

### Describe the issue

I have deployed a Next.js app on AWS Amplify and set the NEXTAUTH_URL environment variable to https://app.ikns.info/.

However, I'm encountering an error [next-auth][error][CLIENT_FETCH_ERROR] with the following details: 139-601a8d7b508ad4e1.js:1.

### How to reproduce

access https://app.ikns.info/

### Expected behavior

can access the sign in

**Comment by balazsorban44** [comment]
Can you also paste in your logs as the error message says?

> There is a problem with the server configuration. Check the server logs for more information.

**Comment by laurenswuyts** [comment]
How did you solve this?

**Comment by Ranjanlc** [comment]
> How did you solve this?

IK its late, and i'm not the OP but if you still have problem, feel free to reach out.

**Comment by Abdoallah-Badr** [comment]
i am faced the same error how solve it please

**Comment by Shariaty** [comment]
Same issue on AES Amplify

**Comment by Ranjanlc** [comment]
> i am faced the same error how solve it please



> Same issue on AES Amplify

Do you guys have set up next.config.js for environment variables?
