### ISSUE TITLE
Adding default fields to the user upon user login

### ISSUE THREAD

**Issue by kevinmachstudio** [nextauthjs/next-auth#760]
**Your question**
How can I add more fields to the user when a user logs in for the first time via email authentication? For example, once a user is created in MongoDB with the following fields (`_id`, `email`, `emailVerified`, `createdAt`, `updatedAt`), is there a way to add another field such as `name` upon user creation? The `name` field could be an empty string as long as the field exists in the database

Could this be done instantly when the user is first created or does there need to be another request to the backend server to add those fields in the database?

**What are you trying to do**
- Add more default fields to a user when it is created inside the `users` table/collection in the database.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by kevinmachstudio** [comment]
@iaincollins is there anyone here that can help with this question?

**Comment by esteban89** [comment]
Did you find any solution?

**Comment by kevinmachstudio** [comment]
@esteban89 nope not yet

**Comment by nikitalk** [comment]
Hi, @kevinmachstudio ! Firstly you need to create custom model. See [here](https://next-auth.js.org/tutorials/typeorm-custom-models). Then use ```createUser``` [event](https://next-auth.js.org/configuration/events) to add information to your database.

**Comment by kevinmachstudio** [comment]
thanks @nikitalk i'll try it out

**Comment by kevinmachstudio** [comment]
@nikitalk I see the fields I added in the debug statements, but when I check the database, the fields are not there, any ideas why?

### debug statements

```
[next-auth][debug][typeorm_create_session] User {
  email: 'myemail@gmail.com,
  emailVerified: 2020-11-11T22:45:37.822Z,
  createdAt: 2020-11-11T22:45:37.822Z,
  updatedAt: 2020-11-11T22:45:37.822Z,
  name: null,
  image: null,
  username: null,
  id: 5fac699112cf54001a6fc166
}
```

### User.js

```
import Adapters from "next-auth/adapters"

export default class User extends Adapters.TypeORM.Models.User.model {
	constructor(name, email, image, emailVerified) {
		super(name, email, image, emailVerified)
	}
}

export const UserSchema = {
	name: "User",
	target: User,
	columns: {
		...Adapters.TypeORM.Models.User.schema.columns,
		username: {
			type: "string",
			nullable: false,
			default: "",
		}
	}
}
```

### [...nextauth].js
```
  events: { 
    createUser: async (message) => {
      console.log("USER CREATEDDDDDD")
      console.log(message)
    }
  },
```

**Comment by kevinmachstudio** [comment]
not sure why doing this works but adding the field in `UserSchema` didn't do anything

export default class User extends Adapters.TypeORM.Models.User.model {
	constructor(name, email, image, emailVerified, username) {
		super(name, email, image, emailVerified)
		if (!username) {
			this.username = ""
		}
	}
}

**Comment by nikitalk** [comment]
Try this: 
``` import Adapters from 'next-auth/adapters';

// Extend the built-in models using class inheritance
export default class User {
  constructor(name, email, image, emailVerified) {
    if (name) {
      this.name = name;
    }
    if (email) {
      this.email = email;
    }
    if (image) {
      this.image = image;
    }
    if (emailVerified) {
      const currentDate = new Date();
      this.emailVerified = currentDate;
    }
  }
}

export const UserSchema = {
  name: 'User',
  target: User,
  columns: {
    id: {
      primary: true,
      type: 'int',
      generated: true,
    },
    name: {
      type: 'varchar',
      nullable: true,
    },
    email: {
      type: 'varchar',
      unique: true,
      nullable: true,
    },
    emailVerified: {
      type: 'timestamp',
      nullable: true,
    },
    image: {
      type: 'varchar',
      nullable: true,
    },
    createdAt: {
      type: 'timestamp',
      createDate: true,
    },
    updatedAt: {
      type: 'timestamp',
      updateDate: true,
    },    
    username: {
      type: "varchar",
      nullable: false,     
    },  
  },
};
```

And show your` adapter` in `options const` and result of `console.log(message)`.

**Comment by kevinmachstudio** [comment]
@nikitalk didn't work for me

Here's my `adapter` and what printed out for `console.log(message)`

```
  adapter: Adapters.TypeORM.Adapter(
    "mongodb://someuser:somepass@mongodb:27017/mydb",
    {
      models: {
        User: Models.User,
      },
    }
  )
```

```
USER CREATEDDDDDD
User {
  email: 'myemail@gmail.com',
  emailVerified: 2020-11-16T17:42:39.832Z,
  createdAt: 2020-11-16T17:42:39.832Z,
  updatedAt: 2020-11-16T17:42:39.832Z,
  name: null,
  image: null,
  id: 5fb2ba0f53d87700131edf4c
}
```

`username` wasn't in the `message` variable

**Comment by nikitalk** [comment]
In `createuser `event try to update `username` field. For example with MongoDB client:

```
import { MongoClient } from 'mongodb';

........

 createUser: async (message) => {
      const client = new MongoClient(process.env.DATABASE_URL, {
        useNewUrlParser: true,
        useUnifiedTopology: true,
      });

      if (!client.isConnected()) await client.connect();
    
      const dbName = process.env.DATABASE_URL.split('/')
        .pop()
        .split('?')
        .shift();

      let usersCollection = client.db(dbName).collection('users');
      usersCollection.updateOne(
        { _id: message.id },
        {
          $set: {
            username: 'username'',
          },
        }
      ); 
}
```

**Comment by kevinmachstudio** [comment]
@nikitalk i forgot about needing to manually adding the fields in the `createuser` event, it works now, thanks :)

**Comment by Sliffcak** [comment]
@kevinmachstudio I am having a similar issue. Do you think you can share you full code snippet around your adapter and creating custom fields?
