### ISSUE TITLE
is instagram authentication even permitted by Instagram API?

### ISSUE THREAD

**Issue by kingjulien1** [nextauthjs/next-auth#7603]
### Question 💬

Building a web-app where users can sign in with their Instagram Account.

Looking at the official [Instagram Basic Display API](https://developers.facebook.com/docs/instagram-basic-display-api/) I found a disclaimer: 

>Data returned by the API cannot be used to authenticate your app users or log them into your app. If your app uses API data to authenticate users, it will be rejected during App Review. If you need an authentication solution, use Facebook Login instead.

After some research, It seems really as though applications **using the API for authentication in any way whatsoever will be rejected during verification process**.

This makes me wonder: why does next-auth provide a Instagram authentication solution, if this is not permitted by Instagram API? Am I missing something here?

### How to reproduce ☕️

-

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
I wonder if the wording has changed recently. FWIW https://developers.facebook.com/docs/instagram-basic-display-api#limitations does not show me the

> If your app uses API data to authenticate users, it will be rejected during App Review.

part. 🤷‍♂️ The Instagram provider was a community addition, and assumingly worked fine at the time. Feel free to check out if it works nowadays, and open a bug report if not.

**Comment by mishrasatyapriya9** [comment]
Yeah for my company i am using next-auth for Instagram authentication in our signup page , but it seems like signup using instagram getting hard and hard to implement using next-auth but how to code for this and how to get instagram_client_id and instagram-secret-secret is not sort yet ,,,

If anyone can help me please help me , i did the code shows  by next-auth documentation but i donot know how to get id and secret for it , please help me 
![Screenshot 2024-10-23 162120](https://github.com/user-attachments/assets/a6531de2-2c7a-46d8-a72d-cebf7aea16ef)
