### ISSUE TITLE
Support for Next js App router??

### ISSUE THREAD

**Issue by ChetSocio** [nextauthjs/next-auth#7606]
### Question 💬

Hey next-auth team, does the present version of next-auth support nextjs 13.4 and above ? The complete change in routing system of nextjs after 13.4 has been released for production and I want to know if your package already supports it or you are working on it ? 

### How to reproduce ☕️

Just create a new nextjs project of latest version using : `npx create-next-app@latest`

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by kapitalistn** [comment]
Next-Auth supports new App router. 

Check out docs:  [https://next-auth.js.org/configuration/initialization](url)

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth/issues/7606#issuecomment-1555890248

**Comment by ChetSocio** [comment]
Then please update your documentation. Your documentation is highly polluted. Make separate documentation for pages routes and app routes as well as typescript or javascript like mui.com does.  Having only one piece of documentation for app route doesnot work.  Also properly explain the callbacks part. You have written its very powerful feature and havenot written a single line for it.  if we are fetching multiple datas from api after login then how to include access token (from api) in session data of next-auth, profile data (of api) in user data of next-auth ????????,
