### ISSUE TITLE
CLIENT_FETCH_ERROR, although session data is in /api/auth/session.

### ISSUE THREAD

**Issue by developedbytoby** [nextauthjs/next-auth#7616]
### Environment

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 84.70 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.6 - /opt/homebrew/bin/npm
  Browsers:
    Firefox: 113.0.1
    Safari: 16.4
Arc: 0.104.0

### Reproduction URL

https://github.com/developedbytoby/website

### Describe the issue

Within my /pages/api/guestbook route, I'm trying to call `getSession()`, with a req param. However, I'm constantly getting this error: 
```
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error undefined {
  error: {},
  url: 'http://localhost:3000/api/auth/session',
  message: undefined
}
```
I've been using NextAuth on this project for a really long time and haven't ever run into this. However, what's really bizarre is that when I visit `http://localhost:3000/api/auth/session`, there's session metadata - which looks like this: 
```
{
  "user": {
    "name": "Toby",
    "email": "hi@tobyb.dev",
    "image": "https://avatars.githubusercontent.com/u/77097223?v=4"
  },
  "expires": "2023-06-20T17:13:26.552Z"
}
```
I've been trying to debug for hours, but to no avail. According to the documentation, it's down to me not set a NEXTAUTH_URL environment variable, but I do have one set. Any help would be really appreciated!

### How to reproduce

Try sending a POST request to `/api/guestbook`, with the required params. (See https://github.com/developedbytoby/website/blob/main/pages/api/guestbook.ts#L36-L40).

### Expected behavior

I expect for the server to detect a session and throw a http 200 code.

**Comment by developedbytoby** [comment]
That worked! Thank you so much for the help.

**Comment by oojoseph67** [comment]
> Could you try using `getServerSession` instead? It' the recommended way forward anyway, over `getSession`. https://next-auth.js.org/configuration/nextjs#in-api-routes

Can I use this solution in my nodejs environment?

**Comment by oojoseph67** [comment]
I have the same issue but it’s not in my react app, i face this issue in my nodejs environment, any fix?
