### ISSUE TITLE
How do I protect API route using the new @auth/core ?

### ISSUE THREAD

**Issue by geekyayush** [nextauthjs/next-auth#7618]
### Question 💬

How do I protect my API route using the new @auth/core?

I know there's `getSession` in `next-auth`.
but is there something similar for `@auth/core` also?

### How to reproduce ☕️

None

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Keep an eye on #7443
