### ISSUE TITLE
bug: lost asyncLocalStorage in server actions

### ISSUE THREAD

**Issue by juliusmarminge** [nextauthjs/next-auth#7633]
### Environment

  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 926.67 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/Library/Caches/fnm_multishells/3962_1684784742591/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/3962_1684784742591/bin/yarn
    npm: 9.5.1 - ~/Library/Caches/fnm_multishells/3962_1684784742591/bin/npm
  Browsers:
    Safari: 16.4

### Reproduction URL

coming soon

### Describe the issue

<img width="969" alt="CleanShot 2023-05-23 at 13 41 32@2x" src="https://github.com/nextauthjs/next-auth/assets/51714798/d20c0180-8396-4af8-8b79-5674ba1cec19">

### How to reproduce

Call `getServerSession` inside a server action

### Expected behavior

session retrieval to be successful

**Comment by juliusmarminge** [comment]
hmm cannot repro in another app. will investigate further

**Comment by juliusmarminge** [comment]
I'll leave this here if anyone got any ideas why it's not working: https://github.com/juliusmarminge/t3-app/blob/main/src/app/actions.ts

Couldn't repro on a new repo though - strange...

**Comment by SvemirskiHod** [comment]
@juliusmarminge I can repro this by calling `getServerSession` anywhere inside of a server action that is defined in a separate file that declares `user server` at the top.

**Comment by rexfordessilfie** [comment]
@juliusmarminge could this help you? I think a temporary solution was found somewhere in here: https://github.com/nextauthjs/next-auth/issues/7523
