### ISSUE TITLE
Website: Add Vue3 / Nuxt3 example on the frontpage

### ISSUE THREAD

**Issue by JPustkuchen** [nextauthjs/next-auth#7636]
### What is the improvement or update you wish to see?

https://authjs.dev/ shows wonderful examples for Next.js, SvelteKit and Solidstart, but Nuxt3 (Vue3) is missing on the frontpage as one of the major frameworks.

Wouldn't it make sense to add such an example to attract Vue / Nuxt developers?

### Is there any context that might help us understand?

Marketing and simple getting started with the major frameworks.

Sorry this isn't really real "docs", but seems most close to.

**Comment by zenflow** [comment]
@JPustkuchen There is no Nuxt3 integration package yet, so it's not just a missing example ☹️

**Comment by JPustkuchen** [comment]
> @JPustkuchen There is no Nuxt3 integration package yet, so it's not just a missing example ☹️

@zenflow sorry -.- I thought I had seen that, but I was wrong and you're right. My appologies. :(

**Comment by zenflow** [comment]
@JPustkuchen Actually there is this unofficial integration: https://github.com/sidebase/nuxt-auth
But no official integration from Auth.js team that would go on the frontpage

**Comment by JPustkuchen** [comment]
@zenflow thank you very much for the link, I'll have a link there! Of course an official integration would be best and most trusted in terms of authentication.

**Comment by septatrix** [comment]
Also see #6825 for the discussion about Nuxt 3 support.

> There is no Nuxt3 integration package yet, so it's not just a missing example

There actually is an example in this repo for Nuxt 3 though it is not mentioned anywhere in the docs and only covers the bare minimum, i.e. no middleware etc.: [apps/playgrounds/nuxt](https://github.com/nextauthjs/next-auth/tree/a79774f6e890b492ae30201f24b3f7024d0d7c9d/apps/playgrounds/nuxt)

**Comment by balazsorban44** [comment]
Hi, Nuxt Auth is planned. For now, check out the community alternatives!

https://authjs.dev/reference#integrations

**Comment by reslear** [comment]
Does anyone know of an alternative for pure vue?
