### ISSUE TITLE
Crendtials provider with redirect:false - next-auth/react signIn returns status:200 ok:true with failed authentication.

### ISSUE THREAD

**Issue by OdifYltsaeb** [nextauthjs/next-auth#7638]
### Provider type

Credentials

### Environment

Using dockerised environment FROM node:18-alpine so
- node 18 latest,
- next 13.4.1
- next-auth 4.22.1
- react 18.2

### Reproduction URL

https://github.com/OdifYltsaeb/next-auth-bug-report

### Describe the issue

I'm following the most basic setup described here https://medium.com/@tom555my/strapi-next-js-email-password-authentication-a8207f72b446 and the next-auth/react signIn (see `console.log('stuff in handlesubmit', stuff);` in the code below) resolves into `{ error: "CredentialsSignin", status: 200, ok: true, url: null }` when authentication fails due to incorrect email/password. The strapi request returns with error 400, and thus the error message in the object that singIn resolves to, but the status is 200, while it should probably be something else.

// app/api/auth/[...nextauth]/route.js

```
import NextAuth from 'next-auth';
import { authOptions } from '../../../../lib/auth';

const handler = NextAuth(authOptions);
export { handler as GET, handler as POST };
```

// lib/auth.js

```
import CredentialsProvider from "next-auth/providers/credentials";
import axios from "../utils/axios";

const signIn = async function({ email, password }) {
    const res = await axios.post(`${process.env.STRAPI_URL}/api/auth/local`, {
        identifier: email,
        password
    });
    return res;
};

const authOptions = {
    session: {
        strategy: "jwt"
    },
    providers: [
        CredentialsProvider({
            name: "Sign in with Email",
            credentials: {
                email: { label: "Email", type: "text" },
                password: { label: "Password", type: "password" }
            },
            async authorize(credentials, req) {
                if (credentials == null) return null;
                try {
                    const { user, jwt } = await signIn({
                        email: credentials.email,
                        password: credentials.password
                    });
                    return { ...user, jwt };
                } catch (error) {
                    console.log('FAIL!', Object.keys(error));
                    // Sign In Fail
                    return null;
                }
            }
        })
    ],
    callbacks: {
        session: async ({ session, token }) => {
            session.id = token.id;
            session.jwt = token.jwt;
            return Promise.resolve(session);
        },
        jwt: async ({ token, user }) => {
            const isSignIn = user ? true : false;
            if (isSignIn) {
                token.id = user.id;
                token.jwt = user.jwt;
            }
            return Promise.resolve(token);
        }
    }
};

export { authOptions, signIn };

```

// components/forms/LoginForm.js

```
...
import { signIn } from 'next-auth/react';
...

const LoginForm = withFormik({
    mapPropsToValues: () => ({
        email: '',
        password: '',
    }),
    validationSchema: Yup.object().shape({
        email: Yup.string().email('Invalid email address').required('Email is required'),
        password: Yup.string().required('Password is required'),
    }),

    handleSubmit: async (values, { props, ...formik }) => {
        await signIn('credentials', {
            redirect: false,
            email: values.email,
            password: values.password,
        }).then((stuff) => {
            console.log('stuff in handlesubmit', stuff);
        });
    },

    displayName: 'LoginForm', // helps with React DevTools
})(Login);
```

### How to reproduce

- clone project, make sure you have docker + docker compose and make commands available
- use `make build-dev` to set stuff u p
- use `make start-dev` to run docker compose
- navigate to http://localhost:8000/login
- open console
- enter random email and password and observe the console printout.

### Expected behavior

I would expect that the status is not OK and code is not 200.

**Comment by xTankky** [comment]
Hey,
Have you fond a fix yet ? I'm running the same issue, I think I'm going insane

**Comment by OdifYltsaeb** [comment]
> Hey, Have you found a fix yet ? I'm running the same issue, I think I'm going insane

Nope. No fix. I just chose to ignore the "status: 200 and ok: true". It seems they have created 3 values for the same thing. As long as the first one of them works, it's Ok, I Guess. It might not be OK in the long run when you have more authentication options, but for starting and for me, it's fine. I wish they would change it, though and allow to pass more information to the data that singIn resolves to... but yeah.

**Comment by igordanchenko** [comment]
I ran into the exact same issue. As far as I can tell, this is happening only under the `app` router. 

I fixed this issue with the following [patch-package](https://www.npmjs.com/package/patch-package) patch.

patches/next-auth+4.22.1.patch

```
diff --git a/node_modules/next-auth/next/index.js b/node_modules/next-auth/next/index.js
index c592ca5..fc9f2e9 100644
--- a/node_modules/next-auth/next/index.js
+++ b/node_modules/next-auth/next/index.js
@@ -87,6 +87,7 @@ async function NextAuthRouteHandler(req, context, options) {
     return new Response(JSON.stringify({
       url: redirect
     }), {
+      status: internalResponse.status,
       headers: response.headers
     });
   }
```

**Comment by ssatriya** [comment]
Been having this problem for few weeks, guess ill just wait the official fix.

**Comment by nima-ca** [comment]
Same issue here

**Comment by hearthole** [comment]
same issue

**Comment by bu-geon** [comment]
same issue

**Comment by ezeparziale** [comment]
Is there no PR for this issue?

**Comment by aaronoceanx** [comment]
i have the same issue as well

**Comment by marcosbrasil** [comment]
+1 same issue here

**Comment by marcosbrasil** [comment]
Looks the same as #7725

**Comment by davialcantaraa** [comment]
> I ran into the exact same issue. As far as I can tell, this is happening only under the `app` router.
> 
> I fixed this issue with the following [patch-package](https://www.npmjs.com/package/patch-package) patch.
> 
> patches/next-auth+4.22.1.patch
> 
> ```
> diff --git a/node_modules/next-auth/next/index.js b/node_modules/next-auth/next/index.js
> index c592ca5..fc9f2e9 100644
> --- a/node_modules/next-auth/next/index.js
> +++ b/node_modules/next-auth/next/index.js
> @@ -87,6 +87,7 @@ async function NextAuthRouteHandler(req, context, options) {
>      return new Response(JSON.stringify({
>        url: redirect
>      }), {
> +      status: internalResponse.status,
>        headers: response.headers
>      });
>    }
> ```

@igordanchenko I did it, but won't work

**Comment by marcellobonini** [comment]
I have managed to do a workaround by adding `throw new Error(""+res.status);` inside authorize function `if(response.status !== 200)` And then in my login page I have
 `SignIn("credentials", {email: values.email, password: values.password, redirect: false}).then((response:SignInRresponse | undefined) => {
  if(response?.error !== null) {
    if(response?.error === "401") form.setError("password", {message:"Incorrect password"});
  }
  console.log(response ;
});` this works for me and doesn't create empty session but throws an error on the form and doesn't sign in. Hope it helps, can provide more code if needed.

**Comment by igordanchenko** [comment]
@davialcantaraa the above patch works fine with the latest next-auth version. You can verify the patch was successfully applied with the following command - `grep "internalResponse.status" node_modules/next-auth/next/index.js` (if you see empty output - that means you didn't apply the patch)

**Comment by ldelia** [comment]
+1 same issue here. Any idea when it will receive an official fix?

**Comment by dieduro** [comment]
+1 same issue. I'm completely regretting of choosing nextauth as my auth library. It's giving me headache after headache

**Comment by ssatriya** [comment]
> +1 same issue. I'm completely regretting of choosing nextauth as my auth library. It's giving me headache after headache

Check lucia auth for alternative or just use clerk.

**Comment by yousuf4you** [comment]
same
![nextauth1](https://github.com/nextauthjs/next-auth/assets/60110696/b4eb5fb3-2782-4516-b4d0-8b60685f889c)

![nextauth2](https://github.com/nextauthjs/next-auth/assets/60110696/0d63d554-421b-4c58-b203-e2e369f1565d)

**Comment by dyspop** [comment]
This may kill next-auth tbh

**Comment by OdifYltsaeb** [comment]
Nah, not that bleak tbh, probably. But I decided not to use NextAuth completely and instead started using session-based httpOnly cookies. I found my life much simpler after that.

**Comment by ThangHuuVu** [comment]
Hello folks, please try the below patch for the fix. I basically take the code from @igordanchenko for my PR. If all is good we will merge the PR soon, thanks!


🎉 Experimental release [published 📦️ on npm](https://npmjs.com/package/next-auth/v/0.0.0-pr.8775.a98a849e)!
 ```sh
pnpm add next-auth@0.0.0-pr.8775.a98a849e
```
 ```sh
yarn add next-auth@0.0.0-pr.8775.a98a849e
```
 ```sh
npm i next-auth@0.0.0-pr.8775.a98a849e
```

**Comment by balazsorban44** [comment]
Closed via: https://github.com/nextauthjs/next-auth/pull/8775

Please note that commenting "same issue" and such comments are immensely unhelpful.

> This may kill next-auth tbh

This statement is ridiculous.

"+1" and "same issue" comments may kill open-source on the other hand. Please use the upvote :+1: feature on the issue description, or subscribe to the issue for updates instead. Or better yet. This is an open-source project, meaning the source is open, and you are free to contribute via a PR. There is no need to wait for maintainers if this is a blocker for you. A fix was pointed out already here: https://github.com/nextauthjs/next-auth/issues/7638#issuecomment-1599319687

Let us all do better 💚
