### ISSUE TITLE
Add attributes to user during authorization

### ISSUE THREAD

**Issue by danjamesmedia** [nextauthjs/next-auth#764]
Whenever I try to add more attributes to the user object in a custom authorization call, it seems I can only set the name, email and image. I would like to add an Id field based on a value retrieved in the call made to my external API during the call.

I see the other way to set this is using the session callback, but this would involve an additional API call to get the info.

Is there any way that more attributes can be added to the user object/session during the authorization process?

**Comment by dimbslmh** [comment]
I was having the same issue, but it has been documented here https://next-auth.js.org/configuration/callbacks#session-callback:

> When using JSON Web Tokens for sessions, the JWT payload is provided instead.

> ### Tip
> When using JSON Web Tokens the jwt() callback is invoked before the session() callback, so anything you add to the JSON Web Token will be immediately available in the session callback.

**Comment by MateuszWawrzynski** [comment]
I had the same problem, but resolved it.
That thread helped me so much.
Thanks for answer @dimbslmh 👍 

Explanation here:
https://stackoverflow.com/a/64595973/14536846
