### ISSUE TITLE
How to properly add both `id` and `accessToken` from `SpotiyfProvider` to the created session

### ISSUE THREAD

**Issue by joaocasarin** [nextauthjs/next-auth#7642]
### Question 💬

Basically the `SpotifyProvider` is only returning this data in the `session` object:
```json
{
    "user": {
        "name": "MyName",
        "email": "MyEmail@email.com",
        "image": "MyImageURL"
    },
    "expires": "2023-06-23T16:29:31.728Z"
}
```

And that's all it gives me.
I tried adding these callbacks to the provider function:
```ts
callbacks: {
    async jwt({token, account}) {
      if (account) {
        token.id = account.providerAccountId
        token.accessToken = account.access_token
      }
      return token
    },
    async session({session, token}) {
      console.log('token', token);
      return session
    }
  }
```

After adding them and doing the `console.log(token)`, I can see those data as shown below:
```json
{
  name: 'MyName',
  email: 'MyEmail',
  picture: 'MyPhoto',
  sub: 'MySub',
  id: 'MyUserId',
  accessToken: 'MyAccessToken',
  iat: 1684945736,
  exp: 1687537736,
  jti: 'JTI'
}
```

But if I try to access those fields in the code, this is all I can access:
<img width="920" alt="image" src="https://github.com/nextauthjs/next-auth/assets/48847394/a29b39ad-4e7e-41b8-8c2d-74b794facb12">

At the same time, if I was able to access those fields within `token`, I couldn't set them to the session, once there is no field for those data in `session` neither in `session.user` as shown below:
<img width="942" alt="image" src="https://github.com/nextauthjs/next-auth/assets/48847394/919e06ea-96cd-43b3-aca4-79ca52cc0085">

<img width="996" alt="image" src="https://github.com/nextauthjs/next-auth/assets/48847394/1f949ba6-9035-4ff3-87a2-ecae2b68e4c5">

How should I correctly set those two values `id` and `accessToken` to the session and be able to access them both from API and client?

### How to reproduce ☕️

Clone [this repo](https://github.com/joaocasarin/repnplay)

Edit the file `.env.example` according to your spotify application, renamed it to either `.env` or `.env.local`

Run it

Click the button `Sign in`, use your spotify credentials

When you get redirected to home, go to `Client Side Protected Page` using the other button

You will see each of the session key/value pairs listed on the screen, but if you try to handle them in the code you can't, and in the server side console, you can see the `token` which contains all data I want, but cannot be passed to neither `session` object nor `session.user` object.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
https://next-auth.js.org/getting-started/typescript#module-augmentation
https://next-auth.js.org/getting-started/example#extensibility
