### ISSUE TITLE
Session Gets Expired Repeatively

### ISSUE THREAD

**Issue by AnshSinghSonkhia** [nextauthjs/next-auth#7643]
### Question 💬

The issue is that while Google login, the session gets expired repeatedly in a very short span of time.
So, kindly provide the solution regarding the same, to increase the time of the session.

### How to reproduce ☕️

The issue is that while Google login, the session gets expired repeatedly in a very short span of time.
So, kindly provide the solution regarding the same, to increase the time of the session.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
https://next-auth.js.org/configuration/options#session
