### ISSUE TITLE
Vanilla setup

### ISSUE THREAD

**Issue by stychu** [nextauthjs/next-auth#7647]
### What is the improvement or update you wish to see?

Are there any docs prepared for Vanilla setup of Auth.js??
Particullarly I would like some guide to be able to setup Auth.js with Express

### Is there any context that might help us understand?

Nothing for core

https://authjs.dev/getting-started/oauth-tutorial?frameworks=core

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/oauth-tutorial?frameworks=core

**Comment by balazsorban44** [comment]
There is not much setup to be done. Auth.js communicates via the standard Web APIs `Request` and `Response`. You can use it in Express.js, but you'll have to handle the "glue" code between Node.js' `(req, res) => void` and Auth.js' `Request => Response` signature.

See the docs: https://authjs.dev/reference/core#usage

**Comment by rexfordessilfie** [comment]
For anyone interested, I have a demo repo for this here! Hope it helps: 

* https://github.com/rexfordessilfie/authjs-express-demo

Also there is this one which does similar and with a custom Mastodon provider, but disables csrf (last I checked):

* https://github.com/jibla/authjs-node-example
