### ISSUE TITLE
Prisma adapter for keycloak provider : remove not-before-policy before linking account

### ISSUE THREAD

**Issue by Kephas3** [nextauthjs/next-auth#7655]
### Description 📓

Hi,

Here's a problem i encountered while integrating the prisma adapter (nuxt 3.5.1 with Sidebase 0.5.0)

Keycloak JWT may contain "not-before-policy", but Dash6 is not allowed in Prisma and failed in error while linking.

Apparently, it's not possible to remove this tag in jwt from keycloak.

### How to reproduce ☕️

I could bypass the error generated by prisma by directly modifying in index.js the following :
```js
linkAccount: (data) => {
            delete data['not-before-policy'];
           return p.account.create({ data })},
```

Then account where well linked in my postGre DB.

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
This will be solved in #7443. See #7369 for more context.

Your current "workaround" is fine.

You can also just extend the Prisma Schema with the extra field, if you need to use it somewhere

**Comment by kac487** [comment]
If you are using T3 and don't want to modify your index.js  you can make these changes in your auth.ts to work around this issue

```ts
/** IMPORTANT FOR INTEGRATING KEYCLOAK 
 * - Prisma has issue with field names with dashes
 */
const prismaAdapter = PrismaAdapter(db) as Adapter;
prismaAdapter.linkAccount = (data) => {
  delete data["not-before-policy"];
  return (db as PrismaClient).account.create({ data }) as unknown as AdapterAccount;
};

/**
 * Options for NextAuth.js used to configure adapters, providers, callbacks, etc.
 *
 * @see https://next-auth.js.org/configuration/options
 */
export const authOptions: NextAuthOptions = {
  callbacks: {
    session: ({ session, user }) => ({
      ...session,
      user: {
        ...session.user,
        id: user.id,
      },
    }),
  },
  adapter: prismaAdapter,
  providers: [
    KeycloakProvider({
      clientId: "next",
      clientSecret: "wyFnP3vMVV7ID6Ty5h1ePBZBWaQkpjgv",
      issuer: "http://localhost:8083/realms/next",
    }),
    /**
     * ...add more providers here.
     *
     * Most other providers require a bit more work than the Discord provider. For example, the
     * GitHub provider requires you to add the `refresh_token_expires_in` field to the Account
     * model. Refer to the NextAuth.js docs for the provider you want to use. Example:
     *
     * @see https://next-auth.js.org/providers/github
     */
  ],
};
```

**Comment by Download** [comment]
> You can also just extend the Prisma Schema with the extra field, if you need to use it somewhere

How? It contains dashes which are not allowed in Prisma schema right?
