### ISSUE TITLE
oAuth access token not passed to typeorm database

### ISSUE THREAD

**Issue by jvonasek** [nextauthjs/next-auth#766]
**Describe the bug**
When using Battle.Net provider with PostgreSQL database, accessToken is `undefined` when saving to database after auth and random hex string is saved instead.

**Steps to reproduce**
Default setup of Battle.Net provider, when inspecting accessToken in database, it's just random string.
When debugging, in `src/adapters/typeorm/models/session.js`, the accessToken is  `undefined`.
When debugging in `src/server/lib/oauth/callback.js` in `getOAuthAccessToken` method, correct accessToken is returned.

**Expected behavior**
Save correct accessToken to database instead of random one

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
Thanks for this bug report! We MIGHT have a fix for this issue in #637 (which is merged but not released yet).

If [you can check out the changes in that PR](https://github.com/nextauthjs/next-auth/pull/637/files), and try overriding the `authorizationUrl` accordingly it would be really great to have feedback on if that resolves the issue or not.

If not happy to investigate what is going on, would be good to know either way.

**Comment by jvonasek** [comment]
I already overriden authorizationUrl with the same fix, as per Battle.Net API documentation. Forgot to mention that, sorry about that. Otherwise the auth won't work.

After that fix, the auth works, sessions work, but accessToken in database is wrong.

I think this problem might occur with any OAuth Provider + typeorm database

**Comment by fel1xw** [comment]
I'm currently facing the same issue with the GitLab Provider. 
After sign in with my gitlab provider I tried to call the gitlab api after receiving the accessToken from `const session = await getSession({ req })` (server side) but I'm always `401 - Unauthorized`. 
And I also found out what  @jvonasek already mentioned: the correct accessToken is not passed to the database and instead the fallback inside the `Session` class [`randomBytes(32).toString('hex')`](https://github.com/nextauthjs/next-auth/blob/ab6ef8a19c9d1bec6354fc7676212e7d8386fbd4/src/adapters/typeorm/models/session.js#L7) is executed instead which obviously is wrong. I could also find out that inside the `signIn`-callback inside `account` the right accessToken is also present.

**Comment by iaincollins** [comment]
I think there is some confusion here.

The `accessToken` in the session is not a provider specific Access Token, it's a NextAuth.js Access Token (which, unlike the the Session Token, which is secure, is exposed client side). It is auto-generated for convenience but is not used directly by NextAuth.js.

The Access Tokens for each provider are stored in the Accounts table/collection and associated with a specific provider account, which in turn is associated with a particular user account (via the `userId` column); each user account can in turn have multiple OAuth accounts.

Access Token rotation for third party OAuth services is not currently a feature of NextAuth.js, though there is a pull request in flight that adds that functionality. Currently, Refresh Tokens and Access Tokens for OAuth accounts are saved to the database (if a database is configured), if not using a database they can be saved in a JSON Web Token in the `jwt` callback.

**Comment by fel1xw** [comment]
@iaincollins you are completely right (at least for my case), I was confused but indeed it makes a lot of sense after I read your comment. 👍

**Comment by iaincollins** [comment]
Thanks for confirming that makes sense to you!

I think we have some work to do on the docs (and probably a diagram or two would be helpful) as it's super confusing and trips a lot of folk up. I'll close this but will roll feedback about this into future documentation.

(I think this issue will go away once we officially support rotating and returning access tokens as will have a nice clearly documented API then!)

**Comment by fel1xw** [comment]
@iaincollins Yeah, having a helper function to return access token for the providers would help a lot as it seems like right now ppl would need to use some other third party library to access the database tables and fetch the access tokens there on there own (As I'll do it for now). It would simply make the whole flow a little easier when you want to access e.g. the github or gitlab api in favor of the user (what I need currently :) ).

Thanks anyway, I now know how to continue. :D
