### ISSUE TITLE
getServerSession null when fetching Next API route server side

### ISSUE THREAD

**Issue by hobadams** [nextauthjs/next-auth#7661]
### Environment

System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.07 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    Yarn: 1.22.19 - ~/Work/AtlasFundingPortal/frontend/node_modules/.bin/yarn
    npm: 9.6.4 - /opt/homebrew/bin/npm
    Watchman: 2023.05.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 113.0.5672.126
    Safari: 15.6.1

### Reproduction URL

N/A

### Describe the issue

I have an API route

**api/session/route.ts**
```
import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';

export async function GET(request: Request) {
  const session = await getServerSession(authOptions);

  return NextResponse.json({
    authenticated: !!session,
    session,
  });
}
```

If i visit this in the browser or log the session it works perfectly.

---

**The issue**

If I try to get the session by hitting that URL in an async method in page it's null

**app/page.tsx**

```
const getSession = async () => {
  const data: any = await fetch(`${process.env.NEXT_PUBLIC_URL}/api/session`, { method: 'GET' });
  const session = await data.json();
  return session;
};

export default async function Dashboard() {
  const session = await getSession();

  console.log('log session', { session });

  return <>page</>;
}
``` 

If I use `getServerSession` in the page component (`app/page.tsx`) it works fine too.

### How to reproduce

1. Create `app/page.tsx` and `app/api/session/route.tsx` (content of files above).
2. Make sure you're signed in and have a valid session
3. Visit the page you created. 
4. You will see this hit the `app/api/session` route and come back with no session.

### Expected behavior

I would expect the session to be available in the API route regardless of how it's visited.  I'm sure i'm missing something silly, thanks for any help.

**Comment by giuseppejaripappalardo** [comment]
Hello, I'm also experiencing the same issue.
I'm currently using Next.js version 13.4.3 and Next-Auth version 4.
It seems that the problem occurs with getServerSession, getToken, as well as getSession.
I'd like to add that I'm actively seeking a possible solution.

Regards,
Jari

**Comment by hobadams** [comment]
@giuseppejaripappalardo - so it works for you completely now? I've just run `yarn upgrade`, cleared the `.next` folder and the `node_modules` and no luck for me.  Do you have any idea what upgraded when you ran yarn update?

**Comment by giuseppejaripappalardo** [comment]
@hobadams  False alarm, unfortunately. It appears that I can only retrieve the session if the API is of type GET; if it's of type POST, the session is null.

**Comment by balazsorban44** [comment]
Duplicate. See: https://github.com/nextauthjs/next-auth/issues/7423#issuecomment-1531064680

**Comment by hobadams** [comment]
Thanks @balazsorban44  very helpful. I'll give it a go tomorrow.
