### ISSUE TITLE
How do you getServerSession on edge runtime?

### ISSUE THREAD

**Issue by phind-justin** [nextauthjs/next-auth#7669]
### Question 💬

I've been looking for a while and I just can't find how to use getServerSession() on an edge runtime. The issue is that you need to pass req and res to getServerSession but you only have req during an edge runtime handler as a parameter. Also the type of the edge runtime `req` param seems be to different (NextRequest vs. NextApiRequest).

Is it just not possible at the moment or is Typescript just a bit confusing here? Also why does getServerSession() need the res param to get the session? Seems like the relevant cookies can be accessed just from req.

Relevant:
Protect backend api route example
https://next-auth.js.org/getting-started/example

Edge function handler params.
https://vercel.com/docs/concepts/functions/edge-functions/quickstart

### How to reproduce ☕️

Code does not compile

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
`getServerSession` is currently not compatible with the edge runtime. You can follow #7443 instead

**Comment by phind-justin** [comment]
I managed to get the JWT token in the edge runtime as a check for login. What is the difference between getToken and getServerSession for this purpose?

**Comment by smultar** [comment]
> I managed to get the JWT token in the edge runtime as a check for login. What is the difference between getToken and getServerSession for this purpose?

What are you doing to get next auth to work in the edge at all?!

**Comment by phind-justin** [comment]
Might be a violation of typescript but it manages to get the cookie from req. Is this undefined behavior?

```javascript

export const config = {
  runtime: 'edge',
};

export default async function handler(
  req: NextRequest,
): Promise<NextResponse> {
  // snip
  const jwtDecryptedToken = await getToken({ req });
  // send token to other servers
```

**Comment by rizexor** [comment]
Bump above question ^

**Comment by dmarcucci** [comment]
@phind-justin Great find!

**Comment by tiagoefreitas** [comment]
So there is no way to currently get the session in edge server? Is there another way to use prisma and connect to db?

**Comment by kirtirajsinh** [comment]
> I managed to get the JWT token in the edge runtime as a check for login. What is the difference between getToken and getServerSession for this purpose?

I'm using next-auth with Prisma Adapter and I'm getting a token as null. I guess it had to do something with the callback. are you familiar with that?

**Comment by niudai** [comment]
> > I managed to get the JWT token in the edge runtime as a check for login. What is the difference between getToken and getServerSession for this purpose?
> 
> I'm using next-auth with Prisma Adapter and I'm getting a token as null. I guess it had to do something with the callback. are you familiar with that?

Running into the same problem

**Comment by riricardoMa** [comment]
> I just noticed that getToken only needs `req` which we do have on edge handler. Might be a violation of typescript (I don't think it is actually?) but it manages to get the cookie from req. Is this undefined behavior?
> 
> ```js
> export const config = {
>   runtime: 'edge',
> };
> 
> export default async function handler(
>   req: NextRequest,
> ): Promise<NextResponse> {
>   // snip
>   const jwtDecryptedToken = await getToken({ req });
>   // send token to other servers
> ```
> 
> In the types for `getToken()` I noticed in line ` req: GetServerSidePropsContext["req"] | NextRequest | NextApiRequest`
> 
> ```js
> export interface GetTokenParams<R extends boolean = false> {
>   /** The request containing the JWT either in the cookies or in the `Authorization` header. */
>   req: GetServerSidePropsContext["req"] | NextRequest | NextApiRequest
>   /**
>    * Use secure prefix for cookie name, unless URL in `NEXTAUTH_URL` is http://
>    * or not set (e.g. development or test instance) case use unprefixed name
>    */
>   secureCookie?: boolean
>   /** If the JWT is in the cookie, what name `getToken()` should look for. */
>   cookieName?: string
>   /**
>    * `getToken()` will return the raw JWT if this is set to `true`
>    * @default false
>    */
>   raw?: R
>   /**
>    * The same `secret` used in the `NextAuth` configuration.
>    * Defaults to the `NEXTAUTH_SECRET` environment variable.
>    */
>   secret?: string
>   decode?: JWTOptions["decode"]
>   logger?: LoggerInstance | Console
> }
> ```

For people who's `getToken` returns null: 

In your `authOptions`, you need to switch session strategy to `jwt` if you were using others before

```
  session: {
    strategy: "jwt",
  },
```
