### ISSUE TITLE
signIn still redirects on SvelteKit eventhough redirect: false

### ISSUE THREAD

**Issue by thomasmol** [nextauthjs/next-auth#7670]
### Environment

  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 85.77 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.4.0 - /opt/homebrew/bin/node
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 111.0.1
    Safari: 16.4

### Reproduction URL

github.com/thomasmol/interview-processor

### Describe the issue

I am using the latest @auth/core and @auth/sveltekit packges to use the Email provider to sign in.

I don't want the page to redirect to another page when the `signIn` function is called so I provide the option of `redirect: false `. (I am trying to implement OTP instead of the magic link). However, the page still redirects to the verify-request page.

### How to reproduce

```javascript
const handleSignIn = async () => {
	loading = true;
	const response = await signIn('email', { redirect: false, email });
	loading = false;
};
```
use this code with the Email provider in any sveltekit project

### Expected behavior

For the page not to redirect and the response variable to not be `undefined`

**Comment by Sharknoon** [comment]
I have the same issue. After some debugging I found the error:
![Screenshot 2023-06-11 194008](https://github.com/nextauthjs/next-auth/assets/16149608/600f991d-5d2f-4adc-b35e-2f05aec8d6a3)
`error` is `null` and `!error` equals to `true`

The original source code is located [here](https://github.com/nextauthjs/next-auth/blob/c7dec376a1272a0877c7e6fb2fc4173f08369f9f/packages/frameworks-sveltekit/src/lib/client.ts#L66)

A possible solution:
```ts
if (redirect || !isSupportingReturn || error === null) {
```
