### ISSUE TITLE
After session check Next-Auth redirects back to wrong URL

### ISSUE THREAD

**Issue by JPilawka** [nextauthjs/next-auth#7671]
### Environment

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 81.59 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.4.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 110.1.48.158
    Chrome: 113.0.5672.126
    Edge: 113.0.1774.57
    Firefox: 111.0.1
    Safari: 16.4

### Reproduction URL

Private repository

### Describe the issue

Project in Nextjs, using `/app` directory and dynamic routes.
Custom provider.

When two or more tabs are opened with different slugs values, refreshing previously opened tabs causes next-auth redirection back to app to URL that was provided for the last tab opened.

When checked, at first, server returns proper URL, then next-auth requests session and, when authenticated, redirects back and server component returns wrong URL.

Issue was isolated from every other context provider and occurs only with next-auth.

### How to reproduce

1. Open two (or more) tabs for page with dynamic routes. Any URL structure with dynamic routes are affected. 
 example:
route: [lang]/report
first opened : /en-US/report
then, in separate tab: /de-DE/report.

2. Go back to first tab: /en-US/report
3. Refresh | reload page 
4. Page URL is now /de-DE/report

### Expected behavior

For multiple tabs opened with dynamic routes, on page refresh, next-auth should redirect back to proper URL.

**Comment by balazsorban44** [comment]
The callback URL cookie is set based on the `callbackURL` option of the `signIn` method, which is by default set to the same page from which you initiated the sign-in process. See https://next-auth.js.org/getting-started/client#specifying-a-callbackurl

**Comment by JPilawka** [comment]
SignIn is done automatically, I don't provide callbackUrl directly in my code for each tab, it's set by next-auth provider. Cookie is set for ALL tabs exactly the same like last singIn process provides. This is why it, after reload, sets ALL tabs to exactly the same URL page to wrong page address instead of redirect back to where each tab pointed to originally.
So, it works fine for static URL or for last opened tab but not for multiple tabs with dynamic URL.

This should not be stored in shared storage (cookie) but separate for the tab's specific storage.
Is it possible to implement or make it work?
