### ISSUE TITLE
TypeError: next_auth_providers_credentials__WEBPACK_IMPORTED_MODULE_1__ is not a function

### ISSUE THREAD

**Issue by OmkarKamble1** [nextauthjs/next-auth#7681]
### Question 💬

I am new to Next.js, 
I created a project and then tried to integrate the next-auth. But facing the error "TypeError: next_auth_providers_credentials__WEBPACK_IMPORTED_MODULE_1__ is not a function". I created a new nextjs project to check if there is any problem in my environment. next-auth successfully ran in that new project. I think I have something in my project that is throwing this error. 
I created a repo to regenerate the same https://github.com/OmkarKamble1/ulink-next-auth

Please help, Thank you ❤️ 

### How to reproduce ☕️

https://github.com/OmkarKamble1/ulink-next-auth

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by MichaelBalla** [comment]
@OmkarKamble1 Hey did you ever find a fix to this issue? I am facing this same problem and it is quite annoying.

**Comment by OmkarKamble1** [comment]
> @OmkarKamble1 Hey did you ever find a fix to this issue? I am facing this same problem and it is quite annoying.

So basically it was a silly mistake, I was importing the function from wrong package. so check your imports. I am sorry I don't really remember the code to fix it. but you can check the working code on my [repo](https://github.com/OmkarKamble1/uLink).

**Comment by MichaelBalla** [comment]
> > @OmkarKamble1 Hey did you ever find a fix to this issue? I am facing this same problem and it is quite annoying.
> 
> So basically it was a silly mistake, I was importing the function from wrong package. so check your imports. I am sorry I don't really remember the code to fix it. but you can check the working code on my [repo](https://github.com/OmkarKamble1/uLink).

Looks like I got ahead of myself and hadn't wrapped my app with the <SessionProvider> tag. Thanks for sharing your repo!

**Comment by nwebaza** [comment]
I was just having the same problem and it came down to my RootLayout function's return statement not be correctly indented.... Thank's for the help though, I wouldn't have found something so simply in hours of agonizing head spinning.

**Comment by allenarduino** [comment]
Kindly show me the function you were importing from the wrong package.

**Comment by codergautam** [comment]
I was using type: module in my package.json and got this error after switching. I had to change my functions to use `.default` then they started working. Idk why

So like:

```
import NextAuth from "next-auth";
import GoogleProvider from "next-auth/providers/google";

export default NextAuth.default({
  providers: [
    GoogleProvider.default({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    }),
  ],
...
```

**Comment by rubyvidhya** [comment]
Thanks a lot.... Now auth login is working fine with type: module

**Comment by tapz** [comment]
I have really hard time understanding why is the .default needed. Does NextAuth have a mix of CJS and ESM? Why is the .default not mentioned in the documentation?

**Comment by fabriciob-ciandt** [comment]
> I was using type: module in my package.json and got this error after switching. I had to change my functions to use `.default` then they started working. Idk why
> 
> So like:
> 
> ```
> import NextAuth from "next-auth";
> import GoogleProvider from "next-auth/providers/google";
> 
> export default NextAuth.default({
>   providers: [
>     GoogleProvider.default({
>       clientId: process.env.GOOGLE_CLIENT_ID,
>       clientSecret: process.env.GOOGLE_CLIENT_SECRET,
>     }),
>   ],
> ...
> ```
I experienced the same problem, and the fix is indeed correct, and @tapz mentioned an important think,  Why is the .default not mentioned in the documentation?

**Comment by fadonascimento** [comment]
> I was using type: module in my package.json and got this error after switching. I had to change my functions to use `.default` then they started working. Idk why
> 
> So like:
> 
> ```
> import NextAuth from "next-auth";
> import GoogleProvider from "next-auth/providers/google";
> 
> export default NextAuth.default({
>   providers: [
>     GoogleProvider.default({
>       clientId: process.env.GOOGLE_CLIENT_ID,
>       clientSecret: process.env.GOOGLE_CLIENT_SECRET,
>     }),
>   ],
> ...
> ```

I experienced the same problem, and the fix is indeed correct, and @tapz mentioned an important note, Why is the .default not mentioned in the documentation?
