### ISSUE TITLE
Invalid URL TypeError with call to signIn()

### ISSUE THREAD

**Issue by Radicitus** [nextauthjs/next-auth#7694]
### Environment

  System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 103.73 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    npm: 9.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Safari: 16.5

### Reproduction URL

https://github.com/Radicitus/next-ecommerce/tree/add-nav

### Describe the issue

Opening this with I'm new to open source, so apologies if this is formatted wrong or not properly descriptive.

When I leave in a button element in some JSX code that has an onClick listener with an arrow function call to signIn() from next-auth/react, I get an error message as follows:

- error TypeError [ERR_INVALID_URL]: Invalid URL
    at __webpack_require__ (/Users/camcam/Documents/Code/Personal/Ecommerce App/next-ecommerce/.next/server/webpack-runtime.js:33:42)
    at eval (./app/components/Nav.tsx:7:73)
    at (sc_client)/./app/components/Nav.tsx (/Users/camcam/Documents/Code/Personal/Ecommerce App/next-ecommerce/.next/server/app/page.js:624:1)
    at __webpack_require__ (/Users/camcam/Documents/Code/Personal/Ecommerce App/next-ecommerce/.next/server/webpack-runtime.js:33:42)

When I comment out that line, I no longer get the error. I'm not sure what causes this as I haven't really changed my code much and don't see why that line of code would have an error. Changing package versions for NextJS and next-auth doesn't do anything.

I have also hosted the site on vercel and do not see the error message in logs on the live host.

### How to reproduce

Refresh page where that line is used in a React component.
Error occurs.
Comment out line.
Error goes away.

### Expected behavior

There should be no error.

**Comment by balazsorban44** [comment]
Hi, thanks for opening this, but the reproduction worked fine for me, no error occurred, and the browser successfully redirected to the login page.

FWIW, the reproduction link points to a non-existent `add-nav` branch, so I tested it on the `dev` branch instead.

If you still think this is an issue, please open a new one with a proper reproduction. :pray:

**Comment by Radicitus** [comment]
Thanks for testing! I'll try a fresh pull of the repo and see if that fixes the issue.

**Comment by Radicitus** [comment]
I did a fresh install of my project and I still see the error showing up. It doesn't affect the functionality of anything but it's odd that it's there.

**Comment by miguelc1221** [comment]
I am seeing the same error ```- error TypeError [ERR_INVALID_URL]: Invalid URL``` when calling signIn
