### ISSUE TITLE
API Auth error with Google Provider

### ISSUE THREAD

**Issue by sergical** [nextauthjs/next-auth#7695]
### Environment

```  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 131.30 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.4 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 113.1.51.118
    Chrome: 113.0.5672.126
    Safari: 16.4
```

### Reproduction URL

https://github.com/sergical/nextauth-test

### Describe the issue

Run the app, click sign in, get redirected to: 

<img width="1680" alt="Screenshot 2023-05-31 at 8 26 41 PM" src="https://github.com/nextauthjs/next-
auth/assets/3760543/74a0e70c-c4e6-4888-8a76-372e71ff281d">

### How to reproduce

* Configured an auth client 
* Removed all other providers except for Google
* Clicked Sign In

<img width="632" alt="Screenshot 2023-05-31 at 8 47 12 PM" src="https://github.com/nextauthjs/next-auth/assets/3760543/d91683c9-8ca7-43dc-b20f-ce3485e6e330">

### Expected behavior

Should redirect to google auth account screen or popup?

**Comment by balazsorban44** [comment]
The screenshot is unavailable, so I cannot tell what the error was.

In your Google console though, the redirect URI also must be configured to `http://localhost:3000/api/auth/callback/google`

You can see a working google login here: https://next-auth-example.vercel.app so this is unlikely a NextAuth.js bug.
