### ISSUE TITLE
What does the UntrustedHost error means and what "trustHost: true" option to overcome it does exactly?

### ISSUE THREAD

**Issue by VirgileD** [nextauthjs/next-auth#7715]
### Question 💬

Using @auth/core:0.7.1 and @auth/sveltekit:0.3.1 I got to use the trustHost option set to true to avoid the UntrustedHost  error.
Using the azureAD provider but not sure it's relevant here.

Can someone explain the error and the implication of setting the trustHost option to true?

The documentation (https://authjs.dev/reference/core/errors/#untrustedhost) is still TODO on this and I couldn't find something on www

### How to reproduce ☕️

hard to reproduce or give a snippet, it would require a new tenant for an azuread declared function.

But if someone give me a hint here I'm more than willing to update the documentation accordingly.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Some hosting platforms do not rewrite the host header which can be manipulated into malicious redirects. Setting the `trustHost` header, you acknowledge this risk, if you know for certain that your provider is not affected.

**Comment by symbolicsorcerer** [comment]
Where can folks read about the host header rewrite issue?

**Comment by symbolicsorcerer** [comment]
Btw - @balazsorban44 should we keep this open until we get the docs updated? I'm happy to write a doc patch if you can share a bit more about the issue here on this issue. I've been googling quite a bit and am not turning up much information, other than folks saying to set trustHost to true, and wondering if it's safe 😅.

**Comment by balazsorban44** [comment]
It depends on your hosting platform. There is an issue already opened for docs #8237

**Comment by symbolicsorcerer** [comment]
My guess is it might be something like these:

* https://medium.com/@iamxali/unveiling-vulnerabilities-host-header-injection-in-oauth-functionality-4ec80557ada7
* https://hackerone.com/reports/317476

If I understand correctly, an attacker can give someone a specially-crafted link that looks like an oauth-style form for a given provider, but actually sends the token to an attacker-controlled domain.

So does this mean basically that the oauth provider should be validating the host? And therefore you just need to confirm whether the provider does this or not, e.g. Google probably does validation?

**Comment by symbolicsorcerer** [comment]
@balazsorban44 ah thanks, sorry just saw your message while I was typing my earlier comment. Will move any further discussion there.
