### ISSUE TITLE
No index signature with a parameter of type 'string' was found on type 'Adapter'.

### ISSUE THREAD

**Issue by seeratawan01** [nextauthjs/next-auth#7721]
### Environment

 System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 66.55 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.90
    Firefox: 113.0.2
    Safari: 16.1

### Reproduction URL

n/a

### Describe the issue

![image](https://github.com/nextauthjs/next-auth/assets/26021449/1d285d15-f2db-42f0-9223-57e88f3c561a)

 "next-auth": "^4.20.1",

### How to reproduce

Just rebuilt my project to vercel now it's not working

### Expected behavior

should work as before

**Comment by sliceem88** [comment]
Have the same error:

System:
OS: Ubuntu 22.04
CPU: AMD® Ryzen 7 5800h with radeon graphics × 16
Memory: 32.00 GB
Node: 18.16.0

"next-auth": "^4.22.1"

![image](https://github.com/nextauthjs/next-auth/assets/43166842/99541d7c-b73a-40b9-bdc8-9f81511e5148)

**Comment by baunov** [comment]
Same. Prod build is failing
<img width="1132" alt="Screenshot 2023-06-20 at 17 50 22" src="https://github.com/nextauthjs/next-auth/assets/54023692/b4147db8-7de7-4104-9d91-32236d4fa3bc">

```
"next": "13.4.3",
"next-auth": "^4.22.1",
"typescript": "^5.2.0-dev.20230620", // upgraded due to some other issues

node: v19.8.1
```

**Comment by baunov** [comment]
FYI, my issue was due to wrong import where I imported from `next-auth/src/..` instead of `next-auth/..`

**Comment by guangzhengli** [comment]
> FYI, my issue was due to wrong import where I imported from `next-auth/src/..` instead of `next-auth/..`

Thanks, after fixing the `import {AuthOptions} from "next-auth/src";` to `import {AuthOptions} from "next-auth";` It works now.

**Comment by fdrouet** [comment]
Thanks for your comment, I had the same problem due to the same cause 

```
import NextAuth, {DefaultSession} from "next-auth"
import {ISODateString} from "next-auth/src/core/types";
```
instead of 
```
import NextAuth, {DefaultSession, ISODateString} from "next-auth"
```
You save my day 🙇
