### ISSUE TITLE
CredentialsProvider authorize function returns status 200 and response ok when Error is thrown

### ISSUE THREAD

**Issue by kikky7** [nextauthjs/next-auth#7725]
### Provider type

Credentials

### Environment

System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 6.52 GB / 15.75 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.50)
    Internet Explorer: 11.0.22621.1

### Reproduction URL

no-repo-easy-to-reproduce

### Describe the issue

When throwing Error inside authorize method the response is 200 (which presents success).

### How to reproduce

app\api\auth\\[...nextauth]\route.ts file
```
import NextAuth from "next-auth/next";
import CredentialsProvider from "next-auth/providers/credentials";

const providers = [
  CredentialsProvider({
    credentials: {
      email: { label: "Email", type: "text" },
      password: { label: "Password", type: "password" },
    },
    async authorize(credentials) {
      // Throw error to test the response
      throw new Error("This is error message.");
      
      // Do login stuff and return user object...
      return null;
    },
  }),
];

export { handler as GET, handler as POST };
```

This is reponse:
```
{
    "error": "This is error message.",
    "status": 200,
    "ok": true,
    "url": null
}
```

### Expected behavior

To get response with error status code. Even though it contains error param, status code should be the one which represents an error, instead of success status code.

**Comment by WeissAzura** [comment]
Was implementing a custom login page and having this exact error :+1:

**Comment by Abdullah-Jamshed** [comment]
facing the same issue

**Comment by cdennis121** [comment]
> Was implementing a custom login page and having this exact error 👍 this bug happen only when using Route Handler.

getting the same error with the same implementation of a custom login page and route handler

**Comment by Ferraresir** [comment]
having the same error with both next auth generated and custom login page

**Comment by xyashino** [comment]
same problem :/

**Comment by wzpfish** [comment]
+1, now I can only check if error message exists..

**Comment by igordanchenko** [comment]
Here is a workaround I'm using for the time being - https://github.com/nextauthjs/next-auth/issues/7638#issuecomment-1599319687

**Comment by BerenBoden** [comment]
Having the exact same issue.

**Comment by wzpfish** [comment]
> 

Actually, I check both the error and response status as a workaround now.

**Comment by rodolfoag** [comment]
Same thing here. Doing the same workaround as @wzpfish for now.

**Comment by serkancagman** [comment]
Still same errorr i think it's not bad idea using nextauth with app router

**Comment by ashishsah1000** [comment]
experience the same issue

**Comment by AlexisKenAlvarez** [comment]
having the same issue D:

**Comment by edilson258** [comment]
I'm having the issue D:

**TRICK**: verifying the error attribute in the signIn response if its null the login was done successful

**Comment by mprync** [comment]
> I'm having the issue D:
> 
> **TRICK**: verifying the error attribute in the signIn response if its null the login was done successful

This is actually the easiest way to get around this issue until the fix has been released.

**Comment by necm1** [comment]
> 

May I ask where to put this code? Should it be placed into the `CredentialsProvider` or in my POST request?

**Comment by necm1** [comment]
> > I'm having the issue D:
> > **TRICK**: verifying the error attribute in the signIn response if its null the login was done successful
> 
> This is actually the easiest way to get around this issue until the fix has been released.
> 
> ```js
> return await signIn('credentials', {
>       username: username,
>       password: password,
>       redirect: false, // Using custom auth flow
>     }).then(res => {
>       if (res?.error === null) {
>         // Handle successful login
>       } else {
>         // Handle error
>       }
>     });
> ```

May I ask where to put this code? Should it be placed into the CredentialsProvider or in my POST request?

**Comment by mprync** [comment]
> > > I'm having the issue D:
> > > **TRICK**: verifying the error attribute in the signIn response if its null the login was done successful
> > 
> > 
> > This is actually the easiest way to get around this issue until the fix has been released.
> > ```js
> > return await signIn('credentials', {
> >       username: username,
> >       password: password,
> >       redirect: false, // Using custom auth flow
> >     }).then(res => {
> >       if (res?.error === null) {
> >         // Handle successful login
> >       } else {
> >         // Handle error
> >       }
> >     });
> > ```
> 
> May I ask where to put this code? Should it be placed into the CredentialsProvider or in my POST request?

This code is calling next-auth signIn directly, so this will be called from the client UI.

**Comment by necm1** [comment]
> > > > I'm having the issue D:
> > > > **TRICK**: verifying the error attribute in the signIn response if its null the login was done successful
> > > 
> > > 
> > > This is actually the easiest way to get around this issue until the fix has been released.
> > > ```js
> > > return await signIn('credentials', {
> > >       username: username,
> > >       password: password,
> > >       redirect: false, // Using custom auth flow
> > >     }).then(res => {
> > >       if (res?.error === null) {
> > >         // Handle successful login
> > >       } else {
> > >         // Handle error
> > >       }
> > >     });
> > > ```
> > 
> > 
> > May I ask where to put this code? Should it be placed into the CredentialsProvider or in my POST request?
> 
> This code is calling next-auth signIn directly, so this will be called from the client UI.

I checked the docs and it's kinda funny that this one seems to work perfectly. Thanks for sharing it! :)

**Comment by matheusggds** [comment]
Anyone knows if is possible to edit the `signIn` response? It always response the same object, I need to add a custom object inside it

**Comment by marcosbrasil** [comment]
+1 I'm having the exact problem. Same as on #7638

**Comment by Maclinz** [comment]
I am getting the error whether my login details correct or not
![image](https://github.com/nextauthjs/next-auth/assets/19819005/01f46a2c-35e0-47fd-b3a0-2303ec7173ef)

**Comment by hammad2030** [comment]
getting same error

**Comment by davialcantaraa** [comment]
Same here

**Comment by dyspop** [comment]
Same!

**Comment by Xxsource98** [comment]
Same here

**Comment by ldelia** [comment]
+1 same issue here. Any idea when it will receive an official fix?

**Comment by rasvanjaya21** [comment]
+ 1 same here

**Comment by ldelia** [comment]
I ended up doing this to temporality fix it:

This is my partial authOptions definition:
```
const authOptions = {
  ....
  providers: [
    CredentialsProvider({
      name: 'Credentials',
      credentials: {},
      async authorize(credentials): Promise<any> {
        try {
          const userCredential = await signInWithEmailAndPassword(
            auth,
            (credentials as any).email || '',
            (credentials as any).password || ''
          );
          if (userCredential.user) {
            return userCredential.user;
          }
          return null;
        } catch (error) {
          if (error instanceof FirebaseError) {
            throw new Error(error.code);
          }
        }
      },
    }),
  ],
};
```

Then, in my sign-in form, I have:

```
const result = await signIn('credentials', {
  email: formModel.email,
  password: formModel.password,
  redirect: false,
});
    
if (result?.error) {
  switch (result.error) {
    case 'auth/wrong-password':
      // do some stuff
      break;
    case 'auth/user-not-found':
      // do some stuff
      break;
    case 'auth/user-disabled':
      // do some stuff
      break;
    default:
      // do some stuff
  }
} else {
  push('/dashboard');
}
```

**Comment by donttouchmylancable** [comment]
I have the same error.
http://localhost:3000/api/auth/signin works as expected, but using signIn in my own custom Login page, **always** gives me a status:'authenticated'

**Comment by mustansirgodhrawala** [comment]
Why has no one taken a look at this issue yet, it's been open since about 3 months?????

**Comment by umair-mirza** [comment]
Really surprised to see that such a major issue is still **Open** after so many months. What are you doing @balazsorban44 @iaincollins

**Comment by balazsorban44** [comment]
Closed via: https://github.com/nextauthjs/next-auth/pull/8775

Please note that commenting "same issue" and such comments are immensely unhelpful.

@umair-mirza This is not how open-source works...

Please use the upvote :+1: feature on the issue description, or subscribe to the issue for updates instead. Or better yet. This is an open-source project, meaning the source is open, and you are free to contribute via a PR. There is no need to wait for maintainers if this is a blocker for you.

Let us all do better 💚
