### ISSUE TITLE
Redirect after new user login

### ISSUE THREAD

**Issue by ramiel** [nextauthjs/next-auth#773]
**Your question**
If the user logins and the `newUser` page is setup there's not way to know what callbackUrl the login process has setup. Maybe I'm missing something

**What are you trying to do**
After the user first login, I show them a welcome page to setup seom account detail. After this, there's no way to redirect him to the callbackUrl

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by jan-wilhelm** [comment]
any news on this? Is it somehow possible at the moment?

**Comment by ramiel** [comment]
I made a pull request #790, but I'm not sure about its status

**Comment by ndom91** [comment]
@ramiel #790 has been merged now! Sorry for the delay!

**Comment by balazsorban44** [comment]
This has been fixed through #790, and available in `next-auth@canary`.
