### ISSUE TITLE
Best practice for JWT Sessions with accessToken & refreshToken

### ISSUE THREAD

**Issue by BenjaminWFox-Lumedic** [nextauthjs/next-auth#774]
**Background/Context**
In my application, my initial sign-in flow looks like:
1. User signs in with Azure AD B2C user flow
2. Application adds the accessToken & refreshToken to the NextAuth JWT in the callback
3. Application decrypts the NextAuth JWT in the API to retrieve the accessToken for downstream API call

Per [this question in the FAQ](https://next-auth.js.org/faq#how-do-i-get-refresh-tokens-and-access-tokens-for-an-oauth-account) my understanding is that 'Access Token rotation' refers to the process of checking the accessToken `iat` vs `exp` myself, and then if it is expired, using the `refreshToken` to get a new `accessToken` - so I need to handle that myself, or risk a situation where there is a valid NextAuth session but the users `accessToken` is no longer valid.

**Your question**
- Is my above understanding of 'Access Token rotation' correct?
- There is an `accessTokenExpires` property on the `account` during initial signin - this looks like it's specifically for database adapters? Does it have any other purpose?

**What are you trying to do**
Make sure I correctly handle scenarios not covered by NextAuth without doing unnecessary work due to misunderstanding terminology or functionality.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by EthanNC** [comment]
I'm looking for an answer to this question, but more specifically when the provider doesn't use refreshTokens. I know the user will have to re-link their account. But how do I force that in my code that with next-auth without removing the `account` record from my database.

**Comment by abeluck** [comment]
I found this issue when searching for details on the refresh, access tokens, and expiry time in the database adapter implementation.

These 3 values seem to be unused. As per the linked FAQ

> Note: NextAuth.js does not current handle Access Token rotation for OAuth providers for you, if this is something you need, currently you will need to write the logic to handle that yourself. 

These values are here for you to use if you need them, it seems.

1. If your provider supports refresh tokens, you'll have to manually refresh them before the expiry period (which isn't captured explicitly)
2. If your provider does not support refresh tokens or your refresh token has expired.. then this is where things get dicey

If the user comes back and still has a session token in their cookie, then everything will be ok. next-auth will re-link the account https://github.com/nextauthjs/next-auth/blob/64084d634b0c71d37143be83e50601a0a4f773a6/src/server/lib/callback-handler.js#L138-L149

However, if the user does not have a session token, then things will break, as a user record will already exist with the email address, triggering this code path:
https://github.com/nextauthjs/next-auth/blob/64084d634b0c71d37143be83e50601a0a4f773a6/src/server/lib/callback-handler.js#L160-L186

You cannot delete the `account` record from the database without also deleting the `user` record, or you will hit the same code path.

This is related to https://github.com/nextauthjs/next-auth/issues/876
