### ISSUE TITLE
getServerSession: [TypeError]: Cannot read properties of undefined (reading 'cookies')

### ISSUE THREAD

**Issue by mcnaveen** [nextauthjs/next-auth#7752]
### Environment

```
 System:
    OS: Linux 5.19 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 5.03 GB / 15.52 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.18.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Brave Browser: 108.1.46.144
    Chrome: 108.0.5359.124
    Firefox: 113.0.2
```

### Describe the issue

I have this in the getServerSideProps. Basically, wants to get the session and pass it as props

But when I do this. I'm getting the below error. 

![image](https://github.com/nextauthjs/next-auth/assets/8493007/92600c67-68cd-4896-bd19-1f4736161074)

```
export async function getServerSideProps({
  context,
}: {
  context: {
    req: NextApiRequest;
    res: NextApiResponse;
  };
}) {
  const session = await getServerSession(
    context?.req,
    context?.res,
    authOptions
  );

  console.log(session); // This is returning undefined

  return {
    props: {
      session: session,
    },
  };
}

```

### How to reproduce

- Have a basic setup of Nextauth
- Add the above-shared code in getserversideprops

### Expected behavior

It's supposed to return the session.

**Comment by mcnaveen** [comment]
It was my mistake. I was trying to destruct the params and context separately.

You have to destruct the params from the context itself.

This is the right way to do it. 👇 

```tsx
export async function getServerSideProps(context: GetServerSidePropsContext) {
  const session = await getServerSession(
    context?.req,
    context?.res,
    authOptions
  );

  const { params } = context ?? {};
  const { id } = params ?? {};

  console.log(session); 
  console.log(id);

  return {
    props: {
      id: id,
      session: session,
    },
  };
}

```

**Comment by clxrityy** [comment]
> It was my mistake. I was trying to destruct the params and context separately.
> 
> You have to destruct the params from the context itself.
> 
> This is the right way to do it. 👇
> 
> ```tsx
> export async function getServerSideProps(context: GetServerSidePropsContext) {
>   const session = await getServerSession(
>     context?.req,
>     context?.res,
>     authOptions
>   );
> 
>   const { params } = context ?? {};
>   const { id } = params ?? {};
> 
>   console.log(session); 
>   console.log(id);
> 
>   return {
>     props: {
>       id: id,
>       session: session,
>     },
>   };
> }
> ```

I'm still getting this issue:

![image](https://github.com/nextauthjs/next-auth/assets/97744702/4c1cb252-7373-47bc-9a4e-9472bece04d9)

**Comment by kumard3** [comment]
> > It was my mistake. I was trying to destruct the params and context separately.
> > You have to destruct the params from the context itself.
> > This is the right way to do it. 👇
> > ```tsx
> > export async function getServerSideProps(context: GetServerSidePropsContext) {
> >   const session = await getServerSession(
> >     context?.req,
> >     context?.res,
> >     authOptions
> >   );
> > 
> >   const { params } = context ?? {};
> >   const { id } = params ?? {};
> > 
> >   console.log(session); 
> >   console.log(id);
> > 
> >   return {
> >     props: {
> >       id: id,
> >       session: session,
> >     },
> >   };
> > }
> > ```
> 
> I'm still getting this issue:
> 
> ![image](https://private-user-images.githubusercontent.com/97744702/244780296-4c1cb252-7373-47bc-9a4e-9472bece04d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNTAxODgsIm5iZiI6MTcwNDA0OTg4OCwicGF0aCI6Ii85Nzc0NDcwMi8yNDQ3ODAyOTYtNGMxY2IyNTItNzM3My00N2JjLTlhNGUtOTQ3MmJlY2UwNGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDE5MTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMDE5ZmU2OGJkNjczNzc0MTc0YjlhNTMyMTRkYzgxZDkxMWVmZjBlZmEwZjQwZWJhMmQ3ZmQzNzI1YTQxMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mY2ALaL_0B5FtMUhwa0HSpOZZXGgJQascBDvK5fjokw)

did you find the solution?

**Comment by mcnaveen** [comment]
> It was my mistake. I was trying to destruct the params and context separately.
> 
> You have to destruct the params from the context itself.
> 
> This is the right way to do it. 👇
> 
> ```tsx
> export async function getServerSideProps(context: GetServerSidePropsContext) {
>   const session = await getServerSession(
>     context?.req,
>     context?.res,
>     authOptions
>   );
> 
>   const { params } = context ?? {};
>   const { id } = params ?? {};
> 
>   console.log(session); 
>   console.log(id);
> 
>   return {
>     props: {
>       id: id,
>       session: session,
>     },
>   };
> }
> ```

This worked for me.

**Comment by ALIRAZA17** [comment]
Guys 

> > > It was my mistake. I was trying to destruct the params and context separately.
> > > You have to destruct the params from the context itself.
> > > This is the right way to do it. 👇
> > > ```tsx
> > > export async function getServerSideProps(context: GetServerSidePropsContext) {
> > >   const session = await getServerSession(
> > >     context?.req,
> > >     context?.res,
> > >     authOptions
> > >   );
> > > 
> > >   const { params } = context ?? {};
> > >   const { id } = params ?? {};
> > > 
> > >   console.log(session); 
> > >   console.log(id);
> > > 
> > >   return {
> > >     props: {
> > >       id: id,
> > >       session: session,
> > >     },
> > >   };
> > > }
> > > ```
> > 
> > 
> > I'm still getting this issue:
> > ![image](https://private-user-images.githubusercontent.com/97744702/244780296-4c1cb252-7373-47bc-9a4e-9472bece04d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNTAxODgsIm5iZiI6MTcwNDA0OTg4OCwicGF0aCI6Ii85Nzc0NDcwMi8yNDQ3ODAyOTYtNGMxY2IyNTItNzM3My00N2JjLTlhNGUtOTQ3MmJlY2UwNGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDE5MTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMDE5ZmU2OGJkNjczNzc0MTc0YjlhNTMyMTRkYzgxZDkxMWVmZjBlZmEwZjQwZWJhMmQ3ZmQzNzI1YTQxMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mY2ALaL_0B5FtMUhwa0HSpOZZXGgJQascBDvK5fjokw)
> 
> did you find the solution?

Any progress?

**Comment by ALIRAZA17** [comment]
Guys I found the Answer so you dont have to pass context.req and context.res inside getServerSession. Only pass authOptions and it will work. Worked for me!!

```
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/prisma';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '../[...nextauth]/authOptions';

export async function PUT(request: Request) {
  const { name, email, phone_number, username, spaceId } = await request.json();
  const session = await getServerSession(authOptions);
  console.log(session)
  try {
    const updatedUser = await prisma.user.update({
      where: { username_spaceId: { username, spaceId } },
      data: { name, email, phone_number },
    });

    return NextResponse.json(updatedUser);
  } catch (error) {
    console.error('Error updating user:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}

```

**Comment by davidawad** [comment]
The above worked for me, I was working with t3 stack, I finally switched `return getServerSession(ctx.req, ctx.res, authOptions)` with  `return getServerSession(authOptions)` and it worked. 

ugh
