### ISSUE TITLE
Sessions are not being deleted from database

### ISSUE THREAD

**Issue by PGabriel20** [nextauthjs/next-auth#7759]
### Adapter type

@auth/prisma-adapter

### Environment

System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 79.08 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh

Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm

Browsers:
    Brave Browser: 113.1.51.118
    Safari: 16.4
 
npmPackages:
    @next-auth/prisma-adapter: ^1.0.5 => 1.0.7 

### Reproduction URL

https://github.com/PGabriel20/T3-Features

### Describe the issue

Im not sure if this is how it was intended to work, but i haven't found anyone with the same problem, so i decided to open a new issue in hopes of getting some clarification. 

I created a new project using the t3 stack that uses next auth with Prisma adapter (using SQLite) and discord provider (the standard setup for t3 stack).

After setting up the auth, I noticed that whenever I wipe all my browser cookies, the session related to the ```next-auth.session-token``` cookie still remains in the database, and if I log in again with the same user account, another session is created, and the previous one is never removed.

This basically creates infinite session rows related to the same user in the database table.

### How to reproduce

To reproduce this issue you need to be using the Prisma adapter with the database session strategy as well as the discord or GitHub provider.

After logging in using the discord provider, go to your browser developer tools, on the ```Application``` tab, click on the option ```Clear all cookies```.

<img width="1220" alt="Captura de Tela 2023-06-08 às 14 43 56" src="https://github.com/nextauthjs/next-auth/assets/62361896/2dc98115-35ab-4bf8-875f-8f4dc104e318">

After wiping the cookies, log in again and go to the ```Sessions``` table in the database and you will see that the first session is still there (even if the expiration time was reached)

This is what the table should look like after wiping the cookies and login in multiple times, note that all was done with the same user:

<img width="1065" alt="Captura de Tela 2023-06-08 às 14 50 46" src="https://github.com/nextauthjs/next-auth/assets/62361896/1e5f1a68-4958-4ad3-8862-41269f25aed0">

### Expected behavior

I might be wrong but is it not a best practice to have only one session tied to a user? Plus if those sessions are not being deleted, they might end up generating additional costs in the long run.

Summing everything up, the sessions table should only have one session per user.

**Comment by balazsorban44** [comment]
Hi, session cookies - when used with an adapter - are tied to the session row in the database. In this case, the session cookie only contains a random token to look up the session. If we detect that the session expired when accessed, it gets deleted from the database, and the cookie is cleared.

See https://github.com/nextauthjs/next-auth/blob/c7dec376a1272a0877c7e6fb2fc4173f08369f9f/packages/core/src/lib/routes/session.ts#L95-L102

However when you delete the cookie manually (unintended), the reference to the now stale session entry in the DB is gone, and we don't have a way to know that the session is not in use anymore.

Keeping the database clean is out of scope for this library, but you can create a cron job that periodically goes through the session and verification token tables and cleans up expired entries.

Ref: https://authjs.dev/reference/adapters#models

> I might be wrong but is it not a best practice to have only one session tied to a user?

One user can have multiple sessions (ie. logged in from different contexts)

**Comment by 5amfung** [comment]
I noticed that the browser would delete the cookie when the cookie expires.  So you left with the dangling session in the database table.
