### ISSUE TITLE
How to use SessionProvider, with Next.js App Router mode

### ISSUE THREAD

**Issue by kamaslau** [nextauthjs/next-auth#7760]
### Question 💬

I'm migrating from Page Router pattern to App Router, during which I fond no docs on how to initiate an SessionProvider in `/app/layout.js`, so I improvised half-way there with following code:

``` javascript
import { SessionProvider } from "next-auth/react";

export default function RootLayout({
  children,
  params: { session, ...params},
}) {
  return (
    <html>
      <body>
        <SessionProvider session={session}>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
```

Problem is, apparently the session value wouldn't be extracted from the undefined `params.session` variable, so how could I solve the problem then?

### How to reproduce ☕️

Try migrating the Pages Router mode [code sample](https://next-auth.js.org/getting-started/client#sessionprovider) to App Router would rise the question.

[This Next.js doc link](https://nextjs.org/docs/getting-started/react-essentials#rendering-third-party-context-providers-in-server-components) offered some info.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by asselinpaul** [comment]
would look at using `getServerSession` (https://next-auth.js.org/configuration/nextjs#in-app-directory)

```ts
const session = await getServerSession(authOptions);
...
return (
    <>
<pre>{JSON.stringify(session, null, 2)}</pre>
</>
  );
```

can look in this repo as well for next-auth usage in app router ctx: https://github.com/shadcn/taxonomy

**Comment by balazsorban44** [comment]
Using `SessionProvider` should be unnecessary in most cases in App Router. You can follow #7443 for more info and the plan for the future of NextAuth.js and App Router.

**Comment by kamaslau** [comment]
Thank you @asselinpaul  for your navigation, [shadcn/taxonomy](https://github.com/shadcn/taxonomy) is one neat and advanced project for exploring next next.js.

@balazsorban44 Yes I've ran into some Server/Client errors, but problem solved afterall, thanx.

> would look at using `getServerSession` (https://next-auth.js.org/configuration/nextjs#in-app-directory)
> 
> ```ts
> const session = await getServerSession(authOptions);
> ...
> return (
>     <>
> <pre>{JSON.stringify(session, null, 2)}</pre>
> </>
>   );
> ```
> 
> can look in this repo as well for next-auth usage in app router ctx: https://github.com/shadcn/taxonomy

**Comment by goerlitz** [comment]
I came here because I had the same issue.
I'm creating a dashboard that should show a typical user account dropdown menu with an avatar of the currently logged in user. The menu is a client component because it is interactive and has state.

Since the above comments only refer to `getServerSession()`, my first workaround was to define the user avatar as a server component and pass it as child into the menu. But this is awkward and also needs a `Suspense` Wrapper around the avatar component. Otherwise, as it will throw lazy loading errors.

But then I found this solution for getting the session data in the client component: https://github.com/nextauthjs/next-auth/issues/5647#issuecomment-1291898265

I'd appreciate if the documentation would give official examples for how to use sessions in client components when using App Router.

**Comment by goerlitz** [comment]
I'm using Material UI to create an [AccountMenu](https://mui.com/material-ui/react-menu/#account-menu) with a user avatar that shows the user's profile picture after login.

The AccountMenu must be a client component because it has state and event handlers. The nested UserAvatar is preferably a client component as well. Thus it needs the client session to get the user's profile picture.

My working solution looks like this:

```typescript
// file: AccountMenu.tsx
'use client';

import { SessionProvider } from 'next-auth/react';
import UserAvatar from './UserAvatar';
import [...]

export default function AccountMenu() {
  [...] // anchor and click handler code as in https://mui.com/material-ui/react-menu/#account-menu

  return (
    <SessionProvider>. // SessionProvider needs to wrap this client component
      <Tooltip title="Account settings">
        <IconButton
          onClick={handleClick}
        >
          <UserAvatar /> // a separate client component to set the Avatar picture
        </IconButton>
      </Tooltip>
      <Menu [...]>
        [...]
      </Menu>
    </SessionProvider>
  );
}


// file: UserAvatar.tsx
'use client'; // not necessary for nested client components but helpful

import { Avatar } from '@mui/material';
import { deepPurple } from '@mui/material/colors';
import { useSession } from 'next-auth/react';

export default function UserAvatar() {
  const { data: session } = useSession();  // get the client session
  const image = session?.user?.image || undefined;
  const name = session?.user?.name || undefined;

  return (
    <Avatar
      src={image}
      alt={name}
      sx={{ width: 32, height: 32, bgcolor: deepPurple[500] }}
    >
      {name}
    </Avatar>
  );
}
```

**Comment by p2pskins** [comment]
> I'm using Material UI to create an [AccountMenu](https://mui.com/material-ui/react-menu/#account-menu) with a user avatar that shows the user's profile picture after login.
> 
> The AccountMenu must be a client component because it has state and event handlers. The nested UserAvatar is preferably a client component as well. Thus it needs the client session to get the user's profile picture.
> 
> My working solution looks like this:
> 
> ```ts
> // file: AccountMenu.tsx
> 'use client';
> 
> import { SessionProvider } from 'next-auth/react';
> import UserAvatar from './UserAvatar';
> import [...]
> 
> export default function AccountMenu() {
>   [...] // anchor and click handler code as in https://mui.com/material-ui/react-menu/#account-menu
> 
>   return (
>     <SessionProvider>. // SessionProvider needs to wrap this client component
>       <Tooltip title="Account settings">
>         <IconButton
>           onClick={handleClick}
>         >
>           <UserAvatar /> // a separate client component to set the Avatar picture
>         </IconButton>
>       </Tooltip>
>       <Menu [...]>
>         [...]
>       </Menu>
>     </SessionProvider>
>   );
> }
> 
> 
> // file: UserAvatar.tsx
> 'use client'; // not necessary for nested client components but helpful
> 
> import { Avatar } from '@mui/material';
> import { deepPurple } from '@mui/material/colors';
> import { useSession } from 'next-auth/react';
> 
> export default function UserAvatar() {
>   const { data: session } = useSession();  // get the client session
>   const image = session?.user?.image || undefined;
>   const name = session?.user?.name || undefined;
> 
>   return (
>     <Avatar
>       src={image}
>       alt={name}
>       sx={{ width: 32, height: 32, bgcolor: deepPurple[500] }}
>     >
>       {name}
>     </Avatar>
>   );
> }
> ```

so is it best practice to wrap every client component in a SessionProvider?

**Comment by goerlitz** [comment]
> so is it best practice to wrap every client component in a SessionProvider?

Only if your client component has `const { data: session } = useSession()`.

However, I recently changed the code above to use a server session instead of a client session to retrieve the user data. It seems to be faster and more elegant. My changed code looks like this now:

```ts
// file ServerComponent.tsx
import { getServerSession } from 'next-auth';
import { authOptions } from '@/app/api/auth/[...nextauth]/authOptions';

export default async function ServerComponent() {
  const session = await getServerSession(authOptions);
  return (
    <>
      ...
      {session?.user && <AccountMenu user={session.user} />}
    </>
  )
};

// file: AccountMenu.tsx
'use client';

import { User } from 'next-auth';
import [...]

// pass the serialized user details from the server component
export default function AccountMenu({ user }: { user: User }) {
  [...] // anchor and click handler code as in https://mui.com/material-ui/react-menu/#account-menu

  return (
    <>
      <Tooltip title="Account settings">
        <IconButton
          onClick={handleClick}
        >
          <UserAvatar {...user}/> // pass user to separate Avatar component
        </IconButton>
      </Tooltip>
      <Menu [...]>
        [...]
      </Menu>
    </>
  );
}

// file: UserAvatar.tsx
import { Avatar } from '@mui/material';
import { deepPurple } from '@mui/material/colors';
import { User } from 'next-auth';

export default function UserAvatar({ user }: { user: User }) {

  return (
    <Avatar
      src={user.image || undefined}
      alt={user.name || undefined}
      sx={{ width: 32, height: 32, bgcolor: deepPurple[500] }}
    >
      {user.name}
    </Avatar>
  );
}
```

Actually, the Server Component could also pass the rendered UserAvatar to the Client Component instead of just the user object. But that depends on personal preference and what makes most sense in the app.

**Comment by altairyash** [comment]
Simply let NEXT know that it's a client component 
`
'use client'
import { SessionProvider } from 'next-auth/react'
export default SessionProvider;
`

**Comment by TommyLeong** [comment]
> Simply let NEXT know that it's a client component `'use client' import { SessionProvider } from 'next-auth/react' export default SessionProvider;`

[Sample link](https://stackoverflow.com/questions/75902311/next-js-13-and-next-auth-issues-with-usesession-and-sessionprovider) with code reference to guide everyone better

**Comment by DRealCharlesXavier** [comment]
> I came here because I had the same issue. I'm creating a dashboard that should show a typical user account dropdown menu with an avatar of the currently logged in user. The menu is a client component because it is interactive and has state.
> 
> Since the above comments only refer to `getServerSession()`, my first workaround was to define the user avatar as a server component and pass it as child into the menu. But this is awkward and also needs a `Suspense` Wrapper around the avatar component. Otherwise, as it will throw lazy loading errors.
> 
> But then I found this solution for getting the session data in the client component: [#5647 (comment)](https://github.com/nextauthjs/next-auth/issues/5647#issuecomment-1291898265)
> 
> I'd appreciate if the documentation would give official examples for how to use sessions in client components when using App Router.

You don't need to use App Router if you are using Next Js. You route your pages using the component folder. and an example of how to use session is thus; 

"use client";

import { SessionProvider } from 'next-auth/react';

const Provider = ({ children, session }) => {
  return (
   <SessionProvider  session={session}>
     {children}
    </SessionProvider>
  )
}

export default Provider

**Comment by DRealCharlesXavier** [comment]
If you are using the App Router, you can use [Server Components](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating) or [Route Handlers](https://nextjs.org/docs/app/building-your-application/routing/route-handlers) instead of API Routes.

**Comment by JuanSpada** [comment]
> Using `SessionProvider` should be unnecessary in most cases in App Router. You can follow #7443 for more info and the plan for the future of NextAuth.js and App Router.

I dont understand, if it is unnecessary how can I update the session on the server? Because I can only update the session on the client session, and If I use the session from the server then I have 2 different sessions when I update the session coming from the client.

**Comment by raolak** [comment]
I solved this way,

Steps

1. Create a AppContextProvider
2. Wrap AppContextProvider inside layout and pass initial user values from session
3. useAppContext to use the value in the cliend code

###AppContextProvider
'use client';
import React, { createContext, useContext, useState, useEffect } from 'react';

// Define the shape of the context
interface AppContentContextProps {
  userId: string;
  userName: string;
  tenantId?: string;
  tenantName?: string;
  appId: string;
  appName: string;
  [key: string]: any; // Flexible to add more fields
}

// Create the context
const AppContentContext = createContext<AppContentContextProps | undefined>(
  undefined
);

// Custom hook to use the context
export const useAppContext = () => {
  const context = useContext(AppContentContext);
  if (!context) {
    throw new Error('useAppContent must be used within an AppContentProvider');
  }
  return context;
};

// Component to provide the context
export const AppContentProvider: React.FC<AppContentContextProps> = ({
  userId: initialUserId,
  userName: initialUserName,
  tenantId: initialTenantId,
  tenantName: initialTenantName,
  appId: initialAppId,
  appName: initialAppName,
  children,
}) => {
  const [contextValue, setContextValue] = useState<AppContentContextProps>({
    userId: initialUserId,
    userName: initialUserName,
    tenantId: initialTenantId,
    tenantName: initialTenantName,
    appId: initialAppId,
    appName: initialAppName,
  });

  // Update context when props change
  useEffect(() => {
    setContextValue({
      userId: initialUserId,
      userName: initialUserName,
      tenantId: initialTenantId,
      tenantName: initialTenantName,
      appId: initialAppId,
      appName: initialAppName,
    });
  }, [
    initialUserId,
    initialUserName,
    initialTenantId,
    initialTenantName,
    initialAppId,
    initialAppName,
  ]);

  return (
    <AppContentContext.Provider value={contextValue}>
      {children}
    </AppContentContext.Provider>
  );
};


#2. In your layout code
  const session = await auth();
const userId = session?.user.id;
  const userName = session?.user.name;
<AppContentProvider
      userId={userId || ''}
      userName={userName || ``}
    ....>
#3  Client code
 const { userId, userName, ....} = useAppContent();

**Comment by hirad** [comment]
@goerlitz I have a setup very similar to yours, and I'm trying to follow the pattern you used. The problem is that when the user logs in, the server component doesn't immediately re-render, which means my nav bar content is stale. Did you ever encounter something like that?

The only way I've found of fixing it is by wrapping it in a session provider, but I'm reading all these comments saying it's not needed with App Router.

**Comment by baba43** [comment]
I just came across this thread and still have no idea what to do. My simple use case is that I have a `AppNav` component that must read the user role from the session. Is it correct that I have to wrap at least the `AppNav` within a `SessionProvider` to make it work?

**Comment by jeremysmitherman** [comment]
Y'all lost the plot with he documentation on this one.  This is not a serious project.

**Comment by johnphilipp** [comment]
I got it to work the following way:


Create a custom SessionProvider that uses client:
```tsx
// providers/SessionProvider.tsx

"use client";

import { SessionProvider } from "next-auth/react";

export default SessionProvider;
```

Export RootLayout as async, set session, wrap the custom SesisonProvider (make sure to import the one you just created, not the default one):
```tsx
// app/layout.tsx

import { getServerSession } from "next-auth";
import SessionProvider from "@/providers/SessionProvider";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en" className="h-full">
      <body className={"h-full"}>
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}
```

Use as you would expect once you have your api set up:
```tsx
// app/login/page.tsx

"use client";

import { signIn, signOut, useSession } from "next-auth/react";

export default function LoginPage() {
  const { data: session } = useSession();

  if (session) {
    return (
      <>
        {session?.user?.email}
        <br />
        <button onClick={() => signOut()}>Sign out</button>
      </>
    );
  }

  return (
    <>
      Not signed in
      <br />
      <button onClick={() => signIn()}>Sign in</button>
    </>
  );
```

The docs were not clear at all.

**Comment by bocklucas** [comment]
> I got it to work the following way:
> 
> Create a custom SessionProvider that uses client:
> 
> ```tsx
> // providers/SessionProvider.tsx
> 
> "use client";
> 
> import { SessionProvider } from "next-auth/react";
> 
> export default SessionProvider;
> ```
> 
> Export RootLayout as async, set session, wrap the custom SesisonProvider (make sure to import the one you just created, not the default one):
> 
> ```tsx
> // app/layout.tsx
> 
> import { getServerSession } from "next-auth";
> import SessionProvider from "@/providers/SessionProvider";
> 
> export default async function RootLayout({
>   children,
> }: Readonly<{
>   children: React.ReactNode;
> }>) {
>   const session = await getServerSession();
> 
>   return (
>     <html lang="en" className="h-full">
>       <body className={"h-full"}>
>         <SessionProvider session={session}>{children}</SessionProvider>
>       </body>
>     </html>
>   );
> }
> ```
> 
> Use as you would expect once you have your api set up:
> 
> ```tsx
> // app/login/page.tsx
> 
> "use client";
> 
> import { signIn, signOut, useSession } from "next-auth/react";
> 
> export default function LoginPage() {
>   const { data: session } = useSession();
> 
>   if (session) {
>     return (
>       <>
>         {session?.user?.email}
>         <br />
>         <button onClick={() => signOut()}>Sign out</button>
>       </>
>     );
>   }
> 
>   return (
>     <>
>       Not signed in
>       <br />
>       <button onClick={() => signIn()}>Sign in</button>
>     </>
>   );
> ```
> 
> The docs were not clear at all.

This saved me thank you so much @johnphilipp :tada:

**Comment by mrsiclorena12** [comment]
> I got it to work the following way:
> 
> Create a custom SessionProvider that uses client:
> 
> ```tsx
> // providers/SessionProvider.tsx
> 
> "use client";
> 
> import { SessionProvider } from "next-auth/react";
> 
> export default SessionProvider;
> ```
> 
> Export RootLayout as async, set session, wrap the custom SesisonProvider (make sure to import the one you just created, not the default one):
> 
> ```tsx
> // app/layout.tsx
> 
> import { getServerSession } from "next-auth";
> import SessionProvider from "@/providers/SessionProvider";
> 
> export default async function RootLayout({
>   children,
> }: Readonly<{
>   children: React.ReactNode;
> }>) {
>   const session = await getServerSession();
> 
>   return (
>     <html lang="en" className="h-full">
>       <body className={"h-full"}>
>         <SessionProvider session={session}>{children}</SessionProvider>
>       </body>
>     </html>
>   );
> }
> ```
> 
> Use as you would expect once you have your api set up:
> 
> ```tsx
> // app/login/page.tsx
> 
> "use client";
> 
> import { signIn, signOut, useSession } from "next-auth/react";
> 
> export default function LoginPage() {
>   const { data: session } = useSession();
> 
>   if (session) {
>     return (
>       <>
>         {session?.user?.email}
>         <br />
>         <button onClick={() => signOut()}>Sign out</button>
>       </>
>     );
>   }
> 
>   return (
>     <>
>       Not signed in
>       <br />
>       <button onClick={() => signIn()}>Sign in</button>
>     </>
>   );
> ```
> 
> The docs were not clear at all.

Is there a reason why you're not passing authOptions to getServerSession()? Should they be passed in or are they automatically picked up from the config?

I'm having an issue where session from useSession is not updated upon login (session callback in authOptions gets called only on tab change) and I still haven't found the cause, nor the issue... This only happens on prod.
