### ISSUE TITLE
No HTTP methods exported on [...nextauth] route but eveything works fine

### ISSUE THREAD

**Issue by reza-ebrahimi** [nextauthjs/next-auth#7773]
### Environment

```json
{
  "next-auth": "^4.22.1",
  "@next-auth/prisma-adapter": "^1.0.7",
}
```

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

Using nextjs app router, commented `export` line in `app/api/auth/[...nextauth]/route.ts` route handler, but everything is working fine.

- `getServerSession` returns session object.
- Following error logged into console:

```
- error No HTTP methods exported in '.../app/api/auth/[...nextauth]/route.ts'. Export a named export for each HTTP method.
```

### How to reproduce

Comment export line in `app/api/auth/[...nextauth]/route.ts`:

```typescript
export const authOptions: NextAuthOptions = {
    debug: false,
    adapter: PrismaAdapter(prisma),
    secret: process.env.NEXTAUTH_SECRET,
    providers: [
        googleProvider,
    ],
    session: {
        strategy: "database",
    },
};

const handler = NextAuth(authOptions);
//export { handler as GET, handler as POST }
```

### Expected behavior

Returning `null` with calling  `getServerSession` function since there is no exposed http method on `auth` route handler.

**Comment by balazsorban44** [comment]
Once logged in, a session cookie is created and saved in the browser. `getServerSession` does not visit the `/api/auth/session` endpoint, in comparison to `useSession` or `getSession`, which is the whole point of this method, avoiding extra network calls.

**Comment by reza-ebrahimi** [comment]
@balazsorban44 What happens when the next-auth is completely an isolated service? In this case `getServerSession` will not have access to next-auth object.

Is there any workaround to use `getServerSession` with isolated auth service using its api?
