### ISSUE TITLE
[email provider] invalidate previous login links

### ISSUE THREAD

**Issue by slaivyn** [nextauthjs/next-auth#779]
**Summary of proposed feature**
Any call to signIn function/REST API endpoint of the email provider should invalidate any previously created login link.

**Purpose of proposed feature**
The goal is to increase the security level of this provider.

**Potential problems**
I can't see any issue with that change proposal

**Describe any alternatives you've considered**
I can't find any alternative

**Additional context**
This is a recommendation from a security auditor based on WASP guidelines.

I am a bit busy right now but later I could try to implement it myself if the feature is accepted

**Comment by iaincollins** [comment]
Thanks for raising this feature!

I think this is a good suggestion and we should take it into account when working on the email provider - probably adding it at the same time as we look at rate limiting and/or adding support for short validation codes (in addition to the links).

**Comment by balazsorban44** [comment]
In #2361, I am going to make it required for the user to delete the previous token used for signin, no matter if the signin was successful or not.

See `useVerificationToken`:

https://github.com/nextauthjs/next-auth/blob/79b3ab73d145be5e87a1845b0cf2106cb2ef2303/src/server/routes/callback.js#L182

If I understand the proposal here, that, should be addressed jn that PR.

**Comment by slaivyn** [comment]
that sounds great!

**Comment by balazsorban44** [comment]
This has been released in `4.0.0-next.22`! From that version and up, adapters are expected to only return the verification token once, and delete it from the database after usage. See the `useVerificationToken`
