### ISSUE TITLE
Adaptor with custom TypeORM model doing custom CRUD will run into `EntityMetadataNotFoundError`  "No metadata for "User" was found",  in a serverless setting 

### ISSUE THREAD

**Issue by archywillhe** [nextauthjs/next-auth#780]
**Background**

This is working very well locally as well as on Heroku too. It just fails to work in a serverless setting such as Vercel. So quite a curious thing.

**What I'm doing**

I'm doing some customsiation on top of Next Auth where I take Next Auth's typeORM adaptor out and uses it in another API to do custom CRUD for my user table.

Basically I have this:
```
export const adapterSingleton = ():any=>{
  return Adapters.TypeORM.Adapter(
     process.env.NEXT_ACCOUNT_DATABASE_URL,
     {
       models: Models,
     }
    )
}
```
and I will take it out like this `const adapter = await adapterSingleton().getAdapter()` and uses it.  

But after deloying into a serverless setting (Vercel) I keep getting `EntityMetadataNotFoundError` when I'm trying to do custom CRUD. Somehow it can't derive the entity for `User`?

**Questions**

1) Does anyone know what's going on? Can it be related to this: https://github.com/typeorm/typeorm/issues/1327 ? Will using an ormconfig.yml and doing something like
```
entities: [__dirname + '/**/*.entity.{js,ts}'
```
fixes it? How do I use ormconfig.yml in this case?

2) What can I do in order to be able to do custom CRUD using NextAuth's Adaptor without running into this error in a serverless setting? (Was working so well locally!)

3) Or should I give up trying to get this work in TypeORM cuz TypeORM is not really designed to work in this scenaior if it is serverless?

Any tips on this will be appreicated!  Thanks!

**What are you trying to do**
custom CRUD

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by archywillhe** [comment]
One solution I tried is to copy `adapters/typeorm/index.js` into my project with the corresponding dependecines, and uses it instead of `Adapters.TypeORM.Adapter` and modefies its models directly (i.e. using it to boostrap a custom Adapter.) 

And I will run into this error instead:  `QueryFailedError: relation "user__users" does not exist"` https://github.com/nextauthjs/next-auth/issues/710

Also note: this errors only show up in a serverless setting. If I'm doing it locally everything works perfecto!

**Comment by archywillhe** [comment]
I've also opened a discussion of this here: https://github.com/vercel/vercel/discussions/5299

I think I know what's the main problem now. Probably something to do with how Entity metadata is derived in TypeORM (which appers to be fileName specific? Or something like that.)  

So there is also this bug in TypeORM: _**code minify causes "Entity metadata for e#activities was not found"**_  https://github.com/typeorm/typeorm/issues/4714 

So my bet is that vercel build process for serverless functions somehow messes up the name of custom models used in this manner and the models are safe iff the code & filenames have been prebuilt into a node_module like in NextAuth.

So my final solution is to use NextAuth as a local dependency and have my custom models inside NextAuth. And that gets rid of the errors in the serverless setting (Vercel).

**Comment by iaincollins** [comment]
@archywillhe  Thanks for the insights and work around you have posted!

I have not been able to replicate this issue but I've tagged it with a bug so we are tracking it.

Feedback, even anecdotal, from anyone else seeing or not seeing this bug is appreciated.

**Comment by alex-munayyer** [comment]
@iaincollins Quick question. 

I've gone through all the documentation and the threads in here. I have only seen CRUD operations mentioned in an old version of next auth here: https://www.npmjs.com/package/next-auth/v/1.1.3 with a file called next-auth.functions.js.

What is the best way to do CRUD operations with say a MongoDB connection with Next Auth? Are there still built-in functions to do this? I have been unable to figure this last part out to deploy my application.

**Comment by followbl** [comment]
@iaincollins just bumping this here - am getting ready to release our conversion to `next-auth` from passport-js and am thrilled with how it's working and how easy it has been to integrate with what we have. Am running in to this exact bug mentioned above here...

```QueryFailedError: relation "user__users" does not exist```

gonna look in to it and will report back. we are on vercel serverless as well.

**Comment by dsmabulage** [comment]
Can Import entities directly to the data source options.

```
import { FamilyEntity } from '../family/entities/family.entity';
import { PatientEntity } from '../patient/entities/patient.entity';

entities: [PatientEntity, FamilyEntity]
```
