### ISSUE TITLE
How do i update the session with changes in the information stored in the session.

### ISSUE THREAD

**Issue by santbob** [nextauthjs/next-auth#7814]
### Question 💬

My application uses 3rd party apps access token and its stored in the session. i store that during login.

```
callbacks: {
    async jwt({ token, user }) {
      if (user) {
        // when user logs in, user object will be present, lets add required information to the session.
        token.accessToken = user.tokenData?.token;
        token.userName = user.userName;
        token.thirdPartyTokenExpiry = user.tokenData?.expires;
      }
      return token;
    },

    async session({ session, token }) {
      session.accessToken = token.accessToken;
      session.thirdPartyTokenExpiry = token.thirdPartyTokenExpiry;
      session.userName = token.userName;
      return session;
    },
 }  
 ```
 
 Now Although my Next-auth session is valid, the third party token expires in an hour and I could renew it and want to know how can I update the session with the updated value for `accessToken`, `thirdPartyTtokenExpiry` etc. in the session.

### How to reproduce ☕️

Setup up NextAuth callback option in the authoptions and try to update the same during launch of a page.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Have a look at the docs:

https://authjs.dev/guides/basics/refresh-token-rotation


This can also be combined with https://next-auth.js.org/getting-started/client#updating-the-session to trigger an update from the client-side on demand.

**Comment by santbob** [comment]
Thank you @balazsorban44
