### ISSUE TITLE
FirestoreAdapter is broken with the official example

### ISSUE THREAD

**Issue by m-j-g** [nextauthjs/next-auth#7825]
### Adapter type

@auth/firebase-adapter

### Environment

    "@auth/firebase-adapter": "^1.0.0",
    "@radix-ui/react-popover": "^1.0.2",
    "@radix-ui/react-tooltip": "^1.0.2",
    "@types/node": "20.2.5",
    "@types/react": "18.2.8",
    "@types/react-dom": "18.2.4",
    "autoprefixer": "10.4.14",
    "classnames": "^2.3.2",
    "encoding": "^0.1.13",
    "eslint": "8.41.0",
    "eslint-config-next": "13.4.4",
    "firebase": "^9.22.1",
    "focus-trap-react": "^10.1.4",
    "framer-motion": "^10.12.16",
    "lucide-react": "0.105.0-alpha.4",
    "next": "13.4.4",
    "next-auth": "^4.22.1",
    "postcss": "8.4.24",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-firebase-hooks": "^5.1.1",
    "react-markdown": "^8.0.7",
    "react-wrap-balancer": "^0.5.0",
    "sharp": "^0.32.1",
    "tailwindcss": "3.3.2",
    "typescript": "5.1.3"

System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 163.44 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Safari: 16.5

### Reproduction URL

https://authjs.dev/reference/adapter/firebase#firebaseadapterconfig

### Describe the issue

When just using the example from here: https://authjs.dev/reference/adapter/firebase#firebaseadapterconfig the adapter property is incompatible with the FirestoreAdapter stating:
  
TS2322: Type 'Adapter' is not assignable to type 'Adapter | undefined'.   Type 'Adapter' is not assignable to type 'DefaultAdapter & { createVerificationToken: (verificationToken: VerificationToken) => Awaitable<VerificationToken | null | undefined>; useVerificationToken: (params: { ...; }) => Awaitable<...>; }'.     Type 'Adapter' is not assignable to type 'DefaultAdapter'.       Types of property 'createUser' are incompatible.         Type '((user: Omit<AdapterUser, "id">) => Awaitable<AdapterUser>) | undefined' is not assignable to type '(user: Omit<AdapterUser, "id">) => Awaitable<AdapterUser>'.           Type 'undefined' is not assignable to type '(user: Omit<AdapterUser, "id">) => Awaitable<AdapterUser>'.  types.d.ts(106, 5): The expected type comes from property 'adapter' which is declared here on type 'AuthOptions'

<img width="990" alt="Screenshot 2023-06-17 at 8 47 20 AM" src="https://github.com/nextauthjs/next-auth/assets/10711395/bc1e36ca-53d1-4888-af47-469a8d4ab99c">

### How to reproduce

Try to use the example: https://authjs.dev/reference/adapter/firebase#firebaseadapterconfig

### Expected behavior

For the example to work.

**Comment by balazsorban44** [comment]
Hi, this is in preparation for the new version of NextAuth.js. With v4, you can keep using `@next-auth/firebase-adapter`

**Comment by m-j-g** [comment]
Thanks for the explanation. How can I correctly implement the new version?

**Comment by msalahz** [comment]
Using `import { FirestoreAdapter } from '@next-auth/firebase-adapter'` worked

**Comment by byroncoetsee** [comment]
All very well this is in preparation for a new version but the official docs should always work.
Using the old import with the adapter doesn't work.
Should we be using the old providers too?
