### ISSUE TITLE
Expires_in vs expires_at in production AdapterError

### ISSUE THREAD

**Issue by matej-kotrba** [nextauthjs/next-auth#7829]
### Question 💬

In my SvelteKit application I use Auth.js with Google Oauth provider and Prisma and Planetscale, in development it works just fine (after replacing expires_at for expires_in in Prisma schema) but in the production (hosted on Vercel) it throws this error when user tries to login: 
"[31m[auth][error][AdapterError][0m: Read more at https://errors.authjs.dev#adaptererror
[31m[auth][cause][0m: Error: Unknown arg `expires_at` in data.expires_at for type AccountUncheckedCreateInput. Did you mean `expires_in`?".
Login in the production works only if the user has already logged in while in development enviroment (because all DB tables were succesfully filled) otherwise only User record is added, error page "/auth/error?error=CallbackRouteError" is displayed and Account and Session are empty. Replacing the expires_in for expires_at only breaks develompent but doesn't fix anything in production.

I guess that is all, I hope the description isn't super confusing (if so I will gladly clarify) and I appreciate any help.

### How to reproduce ☕️

Package version:
```JSON
"@auth/core": "^0.8.2",
"@auth/prisma-adapter": "^1.0.0",
"@auth/sveltekit": "^0.3.1",
```

Env variables:
```ENV
GOOGLE_ID=xxxxx
GOOGLE_SECRET=xxxxx
AUTH_SECRET=xxxxx
```

Here is the auth initialization:

./src/hooks.server.ts
```TypeScript
const handleAuth: Handle = SvelteKitAuth({
  // Created PrismaAdapter with the Prisma client instance
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  adapter: PrismaAdapter(prisma),
  providers: [
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    Google({ clientId: GOOGLE_ID, clientSecret: GOOGLE_SECRET })
  ],
  secret: AUTH_SECRET,
  callbacks: {
    session: async ({ session, user }: { session: UpdatedSession, user: User | AdapterUser }) => {

      if (session?.user && user) {
        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
        session.user!.id = user.id as string;
      }

      return session;
    },
    signIn: async ({ account }) => {
      console.log(account)
      return Promise.resolve(true)
    }
  },
})
```

And here the schema model for the Account:

./prisma/schema.prisma
```Prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider     = "mysql"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}

model Account {
  id                String  @id @default(cuid())
  userId            String
  type              String
  provider          String
  providerAccountId String
  refresh_token     String? @db.Text
  access_token      String? @db.Text
  expires_in        Int?
  token_type        String?
  scope             String?
  id_token          String? @db.Text
  session_state     String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
  @@index([userId])
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@index([userId])
}

model User {
  id            String    @id @default(cuid())
  name          String?
  email         String?   @unique
  emailVerified DateTime?
  image         String?
  accounts      Account[]
  sessions      Session[]
  tests         Test[]
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by tempo22** [comment]
I have the exact same issues,

I tried to force the @auth/core version using yarn resolution and I'm still having the issue

**Comment by ThangHuuVu** [comment]
we return `expires_at` for the `Account` for convenience - in this case, it seems like Prisma is complaining that you are missing `expires_at` in your schema. I suggest adding it back. Hope this help
