### ISSUE TITLE
Discord oauth - safari and apple devices issue.

### ISSUE THREAD

**Issue by Miloshinjo** [nextauthjs/next-auth#783]
Question:
Hi, I am having an issue with Discord provider and next-auth. I am not sure if it is next-auth issue, but I need to ask somewhere since hours of googling produced nothing.

What am I trying to do:
I am trying to log users in via discord. All is working fine and well.. In all browsers except Safari and Apple devices (for example Chrome on Iphone). Not sure why, but user is not being logged in after authorizing discord, but they are being shown an error screen. (/api/auth/error?error=oAuthCallback). It only happens in production, and it all works well on localhost and dev. (PWA is enabled in production, maybe that is the reason).

When enabling PWA mode in development, I get the error again, with this message ```[next-auth][error][callback_oauth_error] Error: Invalid state returned from oAuth provider```

Has anyone come across this one and maybe has some solution? :) 

Thanks.

**Comment by ocean90** [comment]
@Miloshinjo I'm curious if you have found the reason for this? I noticed the same with GitHub OAuth in my app. It works in all browsers except in Safari and Mobile Safari. Though, it works in Safari Technology Preview 115.

**Comment by Miloshinjo** [comment]
@ocean90 Hey, I haven't found it, but yea, Discord doesn't work on Safari or Mobile Safari  (maybe even chrome on ios, don;t have iphone to test). 
I haven't found the solution, I only closed the issue cause no one responded, so I thought I was taking up space or smth :)
But I do have the issue with Iphone users, they basicly have a lot of trouble using the app. Also, they have to log in every time (like for example, with email).

**Comment by rodilo** [comment]
@Miloshinjo  did you manage to fix this? Facing the same issue with `Auth0`.

**Comment by Miloshinjo** [comment]
> @Miloshinjo did you manage to fix this? Facing the same issue with `Auth0`.

Nope, still having issues with Safari. Maybe it's due to cookie policy that apple implements. Haven't looked at this in a long time.

**Comment by Deekor** [comment]
Having this issue as well with discord on safari ios and mac

Error says safari cant establish a secure connection with discord.com

**Comment by codiamoac-hub** [comment]
> Having this issue as well with discord on safari ios and mac
> 
> Error says safari cant establish a secure connection with discord.com

did you fix it ?
