### ISSUE TITLE
Auto redirect to azure signin in Next 13.

### ISSUE THREAD

**Issue by mildfuzz** [nextauthjs/next-auth#7832]
### Question 💬

I am trying to figure out the best way to remove the interstitial screen and go straight to the Azure signin page. I think the way to do it is to implement a custom sign in page that handles the redirect.

```tsx
// /auth/signin/page.tsx

export default async function SignIn() {
  const providers = await getProviders()

  return <SigninClient providers={providers} />
}

// signClient.tsx
'use client'

export const SigninClient = ({
  providers,
}: {
  providers: Record<string, ClientSafeProvider>
}) => {
  useEffect(() => {
    signIn(providers['azure-ad'].id)
  }, [providers])

  return <>Sign In</>
}

// /api/auth/[...nextauth]/route.ts
export const authOptions: AuthOptions = {
  pages: {
    signIn: '/auth/signin',
  },
  providers,
  callbacks,
}
```

Out of the box with default middleware, I get into a redirect loop:
<img width="677" alt="image" src="https://github.com/nextauthjs/next-auth/assets/196705/4fd0c3cb-5fff-4349-bf7b-778e3ae385b5">

To fix that, I filter the auth directory out of the middleware scope:

```ts
export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with auth
     */
    '/((?!/auth/.*))',
  ],
}
```

But now, I get odd redirect behaviour where when I hit the root URL, I correctly get redirected to the signin page, but after sign in, I do not get sent back to the root URL I started on.

Have I missed a step? I am expecting to be redirected back to the initial URL before the auth redirect started.

**Comment by balazsorban44** [comment]
There's no reproduction, so just guessing, but make sure that your middleware config is also aware of the custom signin page

https://next-auth.js.org/configuration/nextjs#pages

**Comment by RicardoAvans** [comment]
@mildfuzz  how did you fixed this eventually?
