### ISSUE TITLE
signIn w/ redirect: false redirects (app dir)

### ISSUE THREAD

**Issue by XMadFoX** [nextauthjs/next-auth#7837]
### Environment

OS: Linux 6.3 undefined
CPU: (16) x64 AMD Ryzen 9
Container: Yes
Shell: 3.6.1 - /bin/fish
Binaries:
Node: 18.16.0 - /run/user/1000/fnm_multishells/4145581_1685979402524/bin/node
npm: 9.5.1 - /run/user/1000/fnm_multishells/4145581_1685979402524/bin/npm
Browsers:
Chromium: 113.0.5672.126
Firefox: 114.0.1

### Reproduction URL

https://github.com/XMadFoX/sila-next/tree/auth-reprod

### Describe the issue

I'm using credentials provider, to sign in, I call:
```js
signIn('credentials', {
							refirect: false,
							email: d.email,
							...(isRegister && { name: d.name }),
							password: d.password,
							register: isRegister,
						});
```

when authorize returns null (error) I got redirected to `api/auth/error?error=CredentialsSignin&provider=credentials`
and success redirects to previous page e.g. /

I also get `redirect: 'false'` (yes, as string) in authorize req.body. Might it be the problem?
Also I tried [similar here](https://github.com/XMadFoX/next-auth-reproduction/tree/no-redirect) (pages version) and it works as expected. So it might also be issue with app dir.

### How to reproduce

```
git clone -b auth-reprod https://github.com/XMadFoX/sila-next/ na-redirect-with-appdir
cd na-redirect-with-appdir
pnpm i
cd apps/web
pnpm dev:next
```
Go to http://localhost:3000/login
Paste `test@example.com` and anything in second field -> success
Anything else will return null
Both will redirect, altho redirect srt to false

* form at `packages/ui/auth/Auth.tsx`
next auth config at `apps/web/app/api/auth/[...nextauth]/route.ts`
authorize at `packages/api/user.ts`

### Expected behavior

To not redirect

**Comment by igordanchenko** [comment]
> refirect: false

Looks like you have a typo in the `redirect` prop.

**Comment by XMadFoX** [comment]
@igordanchenko can't belive I missed it, thanks!
Maybe having it as separated typed argument would save me
