### ISSUE TITLE
How to getting user's guilds from Discord provider?

### ISSUE THREAD

**Issue by thisisroi** [nextauthjs/next-auth#785]
How can I get the user's guilds from Discord provider?

**Comment by pandaniell** [comment]
Similair issues: https://github.com/nextauthjs/next-auth/issues/666, https://github.com/nextauthjs/next-auth/issues/614 it's not documented yet which is kind of holding me back from using the lib, maybe you understand the replies though.

**Comment by thisisroi** [comment]
thanks
