### ISSUE TITLE
NextAuth + Segment Analytics

### ISSUE THREAD

**Issue by jmif** [nextauthjs/next-auth#7861]
### Question 💬

Hi there,

We're trying to setup Segment analytics (analytics.js) with Next 13 app router and NextAuth.  The next auth flow is straightforward but we can't find a way to get a `signIn` callback on the client side that would allow us to call `analytics.identify` and make sure that the Segment JS SDK has the proper user ID associated with it.

The only thing we can think to do so far is use `useSession` to pull the user ID and call. identify on every page load, or something hacky that stores the last identified user ID and only identifies when `useSession` returns a different user ID.  Either way, we need to run this on every page load which feels like a hack.

Anyone know how to get a sign in callback on the client after a user authenticates or somewhere we could detect an auth change that isn't run on every single page load?

Thanks!

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
You can use `useSession` to detect a change in the session state https://next-auth.js.org/getting-started/client#usesession

server-side, you could use the signIn event also https://next-auth.js.org/configuration/events#signin

**Comment by twilio-jyoung** [comment]
im running into the same issue.  events can be raised server-side, but to properly call analytics.identify, i need the event on the client side.
