### ISSUE TITLE
Unable to deploy on node.js receiving error: [auth][error][UntrustedHost] when trying to deploy

### ISSUE THREAD

**Issue by benquan** [nextauthjs/next-auth#7866]
### Environment

OS: MacOS Ventura 13.4 
Node: v19.4.0

"@sveltejs/adapter-node": "^1.2.4",
"@sveltejs/kit": "^1.20.4",
"svelte": "^3.59.2",
"@auth/core": "^0.8.4",
"@auth/sveltekit": "^0.3.3"

### Reproduction URL

https://github.com/benquan/authJsTest

### Describe the issue

I recreated the basic sveltekit example shown in the Auth JS documentation using gitHub.

The only change i did was telling sveltekit to use the node adapter.
`import adapter from '@sveltejs/adapter-node';`

I generated the necessary .env file and added:
```
GITHUB_ID=XXX
GITHUB_SECRET=XXX

AUTH_SECRET=XXX

AUTH_TRUST_HOST=true
```

The app runs fine with **`pnpm run dev`**
I then proceeded to build the app.
when running **`pnpm run preview`** everything still works fine, but if I go to the node **`build`** folder and run **`node index.js`**, I get the following error:

[auth][error][UntrustedHost]: Host must be trusted. URL was: https://localhost:3000/api/auth/session.

### How to reproduce

Clone the github: [https://github.com/benquan/authJsTest](https://github.com/benquan/authJsTest)

modify **.env** file with your credentials

pnpm run build
cd build
node index.js

### Expected behavior

To view the page, instead I get a 500 internal error and on the server I get 

**[auth][error][UntrustedHost]: Host must be trusted. URL was: https://localhost:3000/api/auth/session.**

**Comment by benquan** [comment]
Sveltkit adapter-node was the culprit. you must run: **`node -r dotenv/config build`** according to: https://kit.svelte.dev/docs/adapter-node#environment-variables so that .env files get copied over.

**Comment by vuongtrunghieu** [comment]
You can use `import.meta.env.VITE_SOME_KEY` with `VITE_SOME_KEY` defined in your `.env`, works in production build.
https://vitejs.dev/guide/env-and-mode#env-files
```ts
export const { handle } = SvelteKitAuth({
  trustHost: import.meta.env.VITE_AUTH_TRUST_HOST,
  secret: import.meta.env.VITE_AUTH_SECRET,
  ...
}
```
