### ISSUE TITLE
Url/Hostname in signIn callback

### ISSUE THREAD

**Issue by msahajwani** [nextauthjs/next-auth#7867]
### Question 💬

Hi,

Is it possible to get the current url/hostname in the signIn callback?

I have a wildcard subdomain setup, and after signin, depending on the current wildcard subdomain the user is on, i want to perform some logic. But neither url, nor req is available on signIn callback. How do  handle this?

Thanks!

### How to reproduce ☕️
```
async signIn({ user, account, profile, email, credentials }) {

  // How to I get the current url over here?

 return true
},
```
### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
yes, using advanced initialization, you can read the request headers https://next-auth.js.org/configuration/initialization#advanced-initialization

Make sure that you host on a platform where it's safe to read the host header, or you validate it.
