### ISSUE TITLE
Cannot log in with old version Microsoft Edge

### ISSUE THREAD

**Issue by li3939108** [nextauthjs/next-auth#787]
**Describe the bug**
https://next-auth-example.now.sh/
This demo site can open with no errors, but after I tried to log in with Facebook, it went to FB authentication page, and then was redirected back still showing "you are not signed in", 
which was supposed to be "signed in as ..."

Versions:
Microsoft Edge 42.17134.1098.0
Microsoft EdgeHTML 17.17134

OS: 
Edition: Windows 10 Enterprise
Version: 1803
OS build: 17134.1726

**Steps to reproduce**

**Expected behavior**
Should be able to sign in

**Screenshots or error logs**

**Additional context**
After that , I tried with twitter. It showed "To confirm your identity, sign in with the same account you used originally."
The URL was 
https://next-auth-example.now.sh/api/auth/signin?error=OAuthAccountNotLinked
**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
Thanks for raising this, I'll see if I can replicate.

**Comment by iaincollins** [comment]
Hi there,

I think you are on an old version of Microsoft Edge somehow (it should be auto updating!)

I've tested [using the current version](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel) Microsoft Edge | 86.0.622.51 (Official build) (64-bit) and don't have any issues using Facebook with the example site.

If anyone else reading encounters this please do open a new ticket (so it's not missed) and link back to this one.

**Comment by IRediTOTO** [comment]
hi. did you solve this? Can you show me how ? Thank you
