### ISSUE TITLE
How to get session from redirect callback?

### ISSUE THREAD

**Issue by basememara** [nextauthjs/next-auth#7883]
### Question 💬

I would like to redirect a user to different URLs based if they are a new user or not, as well if from other values in their session. I think the place to do this is in the callback redirect method of the auth options.

However, when I try to call `getServerSession` from `callback.redirect`, I get this error in the server logs: `'getServerSession' is used in a React Server Component. Invariant: Method expects to have requestAsyncStorage, none available`. How can I get the session from the redirect callback to do some custom redirects?

### How to reproduce ☕️

```typescript
callbacks: {
  async redirect({ url, baseUrl }) {
    const token = await getServerSession();
    console.log('redirect.token', token);
    return baseUrl
  }
}
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
For this purpose, you can define a `newUser` page. See the docs: https://next-auth.js.org/configuration/pages
