### ISSUE TITLE
typeorm cache

### ISSUE THREAD

**Issue by guiaramos** [nextauthjs/next-auth#789]
**Your question**
Is cache available on the typerorm queries?

**What are you trying to do**
Enable cache on typeorm

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by iaincollins** [comment]
All options supported by TypeORM can be passed through to it.

This is documented at https://next-auth.js.org/schemas/adapters#typeorm-adapter

If you wanted to add cache to specific queries you would currently need to fork the adapter / use your own adapter. there is no way to add them to specific queries.

The default TypeORM adapter does not cache queries - and it wouldn't make sense to do so in most cases, as you'd almost always want the very latest information and would not want to use stale results for authentication related queries - in this respect it's a little different from something like product database or forum, etc.

There are cases where it would make sense to support this it would provide some performance boost for sessions and isn't a bad idea - however it's probably not worth the trouble given the complexity of getting the implementation right as there are other options.

If you are experiencing performance or scaling challenges, the best way to mitigate that is probably to use a database for users in conjunction with a JWT for sessions. That way the user database is only queried at sign in / sign out and is not relied on when returning session state to the client and there is very little load on the database.
