### ISSUE TITLE
Bump Svelte version to ^4.0.0

### ISSUE THREAD

**Issue by Artur-Galstyan** [nextauthjs/next-auth#7908]
### Description 📓

Currently, AuthJS's dependencies will work with any version of svelte that is 3.X.X. But since version 4 is out and per the Svelte authors:

> Most apps and libraries that are compatible with Svelte 3 should be compatible with Svelte 4. Library authors will need to update the version range to include Svelte 4 if svelte is specified in the peerDependencies. For application authors, the most common change required will be updating tooling to meet the new minimum version requirements such as Node.js 16. Many other migration steps can be handled with npx svelte-migrate@latest svelte-4.

See [the migration guide](https://svelte.dev/docs/v4-migration-guide) and the announcement [here](https://svelte.dev/blog/svelte-4). 

I'll continue testing it on my side, but from I can see, there shouldn't be an issue.

Cheers!

### How to reproduce ☕️

npm create svelte@latest myApp

npm i

npm install @auth/core @auth/sveltekit

Realise that the dependencies expect you to have Svelte 3.X.X.

npm install @auth/core @auth/sveltekit --force 

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by eirik-k** [comment]
Question: Does `@auth/sveltekit` need `svelte` as a peer-depency at all?
I understand that `@sveltejs/kit` is needed, but I'm sure it would be safe to remove `svelte` as a peerdependy or move it to `optionalDependencies`, unless there are plans to ship svelte components or actions in the future.

**Comment by balazsorban44** [comment]
good point @eirik-k. fixed in #7989

**Comment by tank104** [comment]
@Artur-Galstyan have you got this working with version 4?  I tried forcing the packages as you did, but when I run it I am getting the below error.
I am using svelte@4.2.7.

I couldn't tell about the change above if its in latest npm packages, but I still needed to force it.  Perhaps it only accepts 4.0.0 and not higher versions?


[vite] Error when evaluating SSR module /node_modules/@auth/sveltekit/index.js: failed to import "@auth/core"
|- Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import 'C:\git\Website\node_modules\@auth\core\lib\actions' is not supported resolving ES modules imported from C:\git\Website\node_modules\@auth\core\lib\index.js
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:319:17)
    at moduleResolve (node:internal/modules/esm/resolve:945:10)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36)

**Comment by rbozan** [comment]
Have the same problem @tank104
