### ISSUE TITLE
Missing js extension in import of Mikro Orm Adapter

### ISSUE THREAD

**Issue by ShaitanLyss** [nextauthjs/next-auth#7916]
### Adapter type

@auth/mikro-orm-adapter

### Environment

System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 11.80 GB / 23.93 GB
  Binaries:
    Node: 18.6.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - D:\Program Files\nodejs\yarn.CMD
    npm: 8.13.2 - D:\Program Files\nodejs\npm.CMD
    pnpm: 7.5.0 - D:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.1848.0), Chromium (114.0.1823.58)
    Internet Explorer: 11.0.22621.1

### Reproduction URL

https://github.com/ShaitanLyss/app

### Describe the issue

A js extension is missing in the mikro orm adapter package. More precisely it's missing in the index.js file line2 : 
`import * as defaultEntities from "./lib/entities";`

This is causing my build to fail. It works when adding the js extension.

### How to reproduce

Clone the project and try to build the project with npm run build or yarn build.

A module not found error will happen at the end.

### Expected behavior

Build should complete successfully.

**Comment by balazsorban44** [comment]
Want to open a PR?

https://github.com/nextauthjs/next-auth/blob/a79774f6e890b492ae30201f24b3f7024d0d7c9d/packages/adapter-mikro-orm/src/index.ts#L27
