### ISSUE TITLE
How can I get the raw decoded token?

### ISSUE THREAD

**Issue by firatoezcan** [nextauthjs/next-auth#792]
**Your question**
As in title, I want the raw token before it gets mangled into the `profile` function because at that point there are already tons of fields removed. I am using a custom provider for Microsoft and I want the actual token contents and not the default made profile.

I tried out custom `encode`/`decode` functions but I get errors when decoding that the algorithm is wrong and the documentation didn't help there.

**What are you trying to do**
I just want the contents of the token, nothing more nothing less

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [X] Found documentation but was incomplete
* [X] Could not find relevant documentation
* [ ] Found the example project helpful
* [X] Did not find the example project helpful

**Comment by iaincollins** [comment]
We've had this come up before and there is some worked planned to improve this so it's easier to work with some platforms - including specifically Microsoft services and other Open ID services -  but would be curious about any feedback on this (e.g. if you were able to resolve it with existing callback options, or if you could not and went another route, etc).
