### ISSUE TITLE
Test mode similar the one Clerk has

### ISSUE THREAD

**Issue by GermanJablo** [nextauthjs/next-auth#7924]
### Description 📓

It would be nice to have a "test mode" in emailProvider in which it is not required to go to the email to access the verification token. This would ease the flow in automated tests like Playwright or Cypress.

I think we could use the Clerk implementation for inspiration, which looks very interesting:

> Every development instance has "test mode" enabled by default. If you need to use "test mode" on a production instance, you can enable it...
> Any email with the `+clerk_test` subaddress is a test email address. No emails will be sent, and they can be verified with the code "424242"

source: https://clerk.com/docs/testing/e2e-testing

I tried to implement something similar as follows:

```typescript
    EmailProvider({
      server: env.EMAIL_SERVER,
      from: env.EMAIL_FROM,
      generateVerificationToken:
        env.NODE_ENV === "development"
          ? () => return "424242"
          : undefined,
      sendVerificationRequest:
        env.NODE_ENV === "development"
          ? () => console.log("we don't send emails in test mode")
          : undefined,
    }),
```

It works on the first try, but on the second try it fails because the DB schema constraint that the verification token must be unique is violated.

I didn't want to modify that restriction for security reasons.
I was thinking of using something like a timestamp in generateVerificationToken but the user on the frontend has no way to receive it.
Another option would be to create an api endpoint that searches the DB and returns the last verification token for that user. But we would no longer be talking about a built-in functionality.

Maybe someone has a way to get around that problem?

### How to reproduce ☕️

this is a feature request

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by GermanJablo** [comment]
Edit: I changed the title because I don't see why this functionality should be limited to email provider only.

**Comment by balazsorban44** [comment]
The above code looks good to me, I'm not sure it's worth adding it to the lib though. About the DB constraint, you could call the `adapter. useVerificationToken(params)` method between test runs to clear the database.
