### ISSUE TITLE
Error 400: redirect_uri_mismatch when using authjs with Sveltekit 

### ISSUE THREAD

**Issue by hossammenem** [nextauthjs/next-auth#7927]
### Question 💬

I was following the authjs svektekit official tutorial [here](https://github.com/nextauthjs/sveltekit-auth-example/tree/main), and when I tried to do it on my own I faced many issues,
first one is an error in the `+layout.server.ts` file when I do `import type { LayoutServerLoad } from "./$types"`, I get an error, that it cannot find the `./$types` folder, but I'm kinda sure that there is something that I didn't configure for this issue, but this is not the main issue, the issue is actually with authentication when I use google's oAuth provider, I get Error 400: redirect_uri_mismatch, here is the error message.

![google_error_msg](https://github.com/nextauthjs/next-auth/assets/88946630/716672d6-a56e-4e1b-8e5d-96d38f204d01)

And those are both  my authorized redirect URIs
 and JS origins.
 
![google_console](https://github.com/nextauthjs/next-auth/assets/88946630/5b09f9f8-d1bb-42ea-8f2c-8f491c2e83e4)

Here is my `hooks.server.ts` file.

![hooks_server_ts](https://github.com/nextauthjs/next-auth/assets/88946630/f5be90dd-e7ff-463b-b049-c597edd09ec8)

And my `package.json`.

![package_json](https://github.com/nextauthjs/next-auth/assets/88946630/49af3a85-a907-4a0c-b756-7c32f0bc8082)

And finally, this is my file structure

![file_structure](https://github.com/nextauthjs/next-auth/assets/88946630/8023feb1-bc96-4299-b673-5ccac70e2eff)

### How to reproduce ☕️

Pushed my code to github, here is the [repo link](https://github.com/hossammenem/svelte-auth)

Thanks in advanced.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by hossammenem** [comment]
just changed the redirect uri back to /auth/callback/google and everything just worked, prop it was an issue from google

**Comment by USA19** [comment]
just changed the redirect uri back to /api/auth/callback/googleand everything just worked, prop it was an issue from google
