### ISSUE TITLE
"authorize" giving error/typo mistake/bug.... in phpstrom

### ISSUE THREAD

**Issue by vipertecpro** [nextauthjs/next-auth#7928]
### Question 💬

How do i get rid of this error ?

### How to reproduce ☕️

I am using phpstrom

![Screenshot 2023-07-01 180030](https://github.com/nextauthjs/next-auth/assets/11619188/044f2c4c-f6cf-4775-83b0-1508a8838041)
![Screenshot 2023-07-01 180121](https://github.com/nextauthjs/next-auth/assets/11619188/50c2fa8d-bd1f-4f3a-a464-4f1f2e0d4e32)
It says
The expected type comes from property 'authorize' which is declared here on type 'UserCredentialsConfig<{ email: { label: string; type: string; placeholder: string; }; password: { label: string; type: string; }; }>'

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Check out the docs https://next-auth.js.org/getting-started/typescript#module-augmentation
