### ISSUE TITLE
i am trying to put login page in a iframe. I made it work for email authentication but not working for social login

### ISSUE THREAD

**Issue by iamanam** [nextauthjs/next-auth#793]
**Your question**
How can i show social login page inside a iframe? Is it possible?

**What are you trying to do**

i put my login page in iframe and it works as expected for email login. But when i try to do social login with facebook i get this error

>  Refused to display 'https://www.facebook.com/v7.0/dialog/clear_history_restricted/?app_id=291348875539536&redirect_uri=https%3A%2F%2Fwww.facebook.com%2Fv.......................' in a frame because it set 'X-Frame-Options' to 'deny'.

I think i need to change X-frame-options header but i don't know how? Is there any solution or workaround for this problem?

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by umerjaved178** [comment]
hey @iamanam 
Have you found its solution? as Login within iframe is not supported by next-auth, how did you get work around to this
