### ISSUE TITLE
Invalid scheme in redirect_uri for qwik-auth and auth.js

### ISSUE THREAD

**Issue by Nefcanto** [nextauthjs/next-auth#7931]
### Environment

  System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (3) x64 Intel Xeon Processor (Skylake, IBRS)
    Memory: 646.05 MB / 7.76 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm

### Reproduction URL

I can't create

### Describe the issue

I'm using Qwik with Auth.js.

This is my configuration:

```
// @ts-nocheck

import { serverAuth$ } from '@builder.io/qwik-auth'
import type { Provider } from '@auth/core/providers'
import Keycloak from '@auth/core/providers/keycloak'

export const { onRequest, useAuthSession, useAuthSignin, useAuthSignout } = serverAuth$(
    ({ env }) => ({
        secret: env.get("AUTH_SECRET"),
        trustHost: true,
        callbacks: {
            async session({
                session, 
                token,
            }){
                session.user.guid = token.sub
                return session
            }
        },
        providers: [
            Keycloak({
                clientId: 'Site',
                clientSecret: env.get('KEYCLOAK_CLIENT_SECRET') as string,
                issuer: env.get('KEYCLOAK_ISSUER') as string
            }),
        ] as Provider[],
    })
);
```

When I press the login button in my app, I would be redirected to `https://accounts.example.com` correctly, but the `redirect_uri` is incorrectly formatted as `http://` instead of `https://`.

I have also reported this problem to [the Qwik team](https://github.com/BuilderIO/qwik/issues/4685).

### How to reproduce

- Create a Qwik app
- Server it on HTTPS
- Create a config for `Keycloak`
- Press login
- See that `redirect_uri` is using HTTP, not HTTPS

### Expected behavior

Auth.js should read the incoming protocol/scheme as the main scheme to create `redirect_uri`.

**Comment by balazsorban44** [comment]
the Qwik integration is not maintained by us as of now. I see the linked issue is closed as completed, so closing this too. Please report issues there first.
