### ISSUE TITLE
Can't resolve 'next-auth/react' on development sever.

### ISSUE THREAD

**Issue by stylessh** [nextauthjs/next-auth#7934]
### Environment

  System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 4.50 GB / 13.86 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.23.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (114.0.1823.41)
    Internet Explorer: 11.0.22000.120

### Reproduction URL

https://github.com/nextauthjs/next-auth/blob/main/apps/dev/pages/_app.js

### Describe the issue

I'm planning to add a new feature to the next-auth/middleware package. In repo's dev application, 'next-auth/react' is not recognized when I pnpm install all the packages and follow all the steps. 

```sh
next-auth-app:dev: error - ./pages/_app.js:1:0
next-auth-app:dev: Module not found: Can't resolve 'next-auth/react'
next-auth-app:dev: > 1 | import { SessionProvider } from "next-auth/react"
next-auth-app:dev:   2 | import "./styles.css"
next-auth-app:dev:   3 | 
next-auth-app:dev:   4 | export default function App({ Component, pageProps }) {
next-auth-app:dev: 
next-auth-app:dev: https://nextjs.org/docs/messages/module-not-found
```

### How to reproduce

I followed every step on the Contribution guide: https://github.com/nextauthjs/next-auth/blob/main/CONTRIBUTING.md
Including using **corepack** to use the exact pnpm version in the repo.

Clone the repo

```sh
git clone git@github.com:nextauthjs/next-auth.git
cd next-auth
```

Corepack
```sh
corepack enable pnpm
```

Install packages

```sh
pnpm install
Populate .env.local
```
Copy env vars
```
cd apps/dev
copy .env.local.example .env.local
```

Start the application
```sh 
pnpm dev 
```

### Expected behavior

The development server should run without any issue, as planted in the docs. Instead it doesn't recognize the package.

**Comment by balazsorban44** [comment]
You miggt need to run `pnpm build` first.

**Comment by stylessh** [comment]
I did, and still doesn't work. I don't what it might be

**Comment by GermanJablo** [comment]
I'm coming from here: https://github.com/nextauthjs/next-auth/issues/7942

Exactly the same problem.

`pnpm build` also fails in the project root and in `apps/dev/nextjs` for the same reason: `Can't resolve 'next-auth/react'`

**Comment by stylessh** [comment]
Yes, I believe there's an issue while running on Windows. I'm gonna try using WSL, I suggest you the same
