### ISSUE TITLE
Incomplete list in package.json "exports" section

### ISSUE THREAD

**Issue by pavelsvitek** [nextauthjs/next-auth#7941]
### Environment

  **System**:
    OS: macOS 12.6.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 112.05 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  **Binaries**:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    pnpm: 8.6.5 - ~/Library/pnpm/pnpm
  **Browsers**:
    Brave Browser: 114.1.52.126
    Chrome: 114.0.5735.198
    Chrome Canary: 117.0.5867.0
    Safari: 16.4.1

### Reproduction URL

https://blitzjs-next-auth-bug.vercel.app/

### Describe the issue

I'm running NextAuth with BlitzJS framework - https://blitzjs.com/docs/next-auth

However, when I try to call `/api/auth/[github,google,linkedin]/login`, I see the following error

```log
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './core/init' is not defined by "exports" in /var/task/node_modules/.pnpm/@blitzjs+auth@2.0.0-beta.29_blitz@2.0.0-beta.29_next-auth@4.22.1_next@13.3.0_secure-password@4.0.0/node_modules/next-auth/package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:366:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:702:9)
    at resolveExports (node:internal/modules/cjs/loader:565:36)
    at Module._findPath (node:internal/modules/cjs/loader:634:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
    at mod._resolveFilename (/var/task/node_modules/.pnpm/next@13.3.0_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

It seems that `package.json` in `next-auth` is missing the following in the `"exports"` section:

```
"exports": {
    ...
    "./core/init": "./core/init.js",
    "./core/lib/oauth/authorization-url": "./core/lib/oauth/authorization-url.js",
    "./core/lib/oauth/callback": "./core/lib/oauth/callback.js",
    ...
},
```

### How to reproduce

* Go to https://blitzjs-next-auth-bug.vercel.app/
* Click on "Sign in with Google" or "Sign in with Github"
  * You will see only HTTP 400, you will need to run this locally to see error log

### Expected behavior

**Expected:**
The sign in screen of Google or Github is shown

**Solution:**
=> After I add those lines to `package.json`, the workflow works normally!

**Comment by balazsorban44** [comment]
Hi, these are internal modules and are not meant to be imported. This is an issue with Blitz.js and seems to have been patched here already https://github.com/blitz-js/blitz/pull/4153

See the corresponding issue https://github.com/blitz-js/blitz/issues/4143

Longer term, Blitz.js should stop monkey patching `next-auth` and rather use `@auth/core`, where we might expose some of these paths for lib authors who are building on top of Auth.js.

I offered my help if they were interested https://twitter.com/balazsorban44/status/1618626954730835968
