### ISSUE TITLE
What does `OAuthAccountNotLinked: Another account already exists with the same e-mail address` mean

### ISSUE THREAD

**Issue by marwie** [nextauthjs/next-auth#7944]
### Question 💬

Hello,

I started using auth/core few weeks ago and recently started getting the following error.
I'm actually not sure where the error is because it even happens in a new test database when I create the user for the first time

This is when using a custom database adapter. 

```ts
[auth][error][OAuthAccountNotLinked]: Read more at https://errors.authjs.dev#oauthaccountnotlinked
[auth][cause]: OAuthAccountNotLinked: Another account already exists with the same e-mail address
    at handleLogin (file:///C:/git/<myproject>/node_modules/@auth/sveltekit/node_modules/@auth/core/lib/callback-handler.js:162:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Module.callback (file:///C:/git/<myproject>/node_modules/@auth/sveltekit/node_modules/@auth/core/lib/routes/callback.js:56:50)
    at async AuthInternal (file:///C:/git/<myproject>/node_modules/@auth/sveltekit/node_modules/@auth/core/lib/index.js:65:38)
    at async Proxy.Auth (file:///C:/git/<myproject>/node_modules/@auth/sveltekit/node_modules/@auth/core/index.js:100:30)
    at async Module.respond (C:/git/<myproject>/node_modules/@sveltejs/kit/src/runtime/server/respond.js:274:20)
    at async file:///C:/git/<myproject>/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:505:22
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by marwie** [comment]
I can reproduce this error when I have two oauth providers where both use the same email address (e.g. github and google)

- Login with github with email `myemail@test.com` 
- Logout
- Login with google with email `myemail@test.com` 
- Observe error `Another account already exists` 

Isn't that the whole point where a user can be logged in using multiple different accounts? As far as I can tell there's no call to `linkAccount`

![image](https://github.com/nextauthjs/next-auth/assets/5083203/f9d83e7d-648e-4d1c-9c98-90c0250964a5)

**Comment by marwie** [comment]
Checking the relevant sections in the code the error makes sense. Perhaps the documentation page could be updated with the information in the comment here: https://github.com/nextauthjs/next-auth/blob/a79774f6e890b492ae30201f24b3f7024d0d7c9d/packages/core/src/lib/callback-handler.ts#L200
(I know i've seen it somewhere in your docs but not in the section that is linked with the error message)

How would account linking with auth.js work? I don't think I have seen that being mentioned in the docs (will check again now)

**Comment by ThangHuuVu** [comment]
hi @marwie, this error is intentional as you discovered through the docs. You could pass `allowDangerousEmailAccountLinking` in the provider configuration to opt-in to email linking: https://authjs.dev/reference/core/providers_oauth#allowdangerousemailaccountlinking

The error page is still WIP, we hope to improve it soon 🙏 Closing this as not an issue with Auth.js.

**Comment by marwie** [comment]
Thanks @ThangHuuVu thanks, yep that's how I did it for now

Do you happen to have more information for me on how it should be done "properly"? Is there a way to handle the case and prompt an already authenticated user to handle the account linking myself? (without automatic account linking)

**Comment by ThangHuuVu** [comment]
> Thanks @ThangHuuVu thanks, yep that's how I did it for now
> 
> Do you happen to have more information for me on how it should be done "properly"? Is there a way to handle the case and prompt an already authenticated user to handle the account linking myself? (without automatic account linking)

Unfortunately I don't think its out-of-the-box supported right now, we either reject or automatically link the accounts, there is no middle ground here :)

**Comment by zimonitrome** [comment]
There should really be an option to display an error message for this.
