### ISSUE TITLE
Clicking on magic link from a different browser than the one used to send the magic link email

### ISSUE THREAD

**Issue by NazCodeland** [nextauthjs/next-auth#7945]
### Description 📓

Hey everyone, on my current project, I am using the magic link (Email Provider) as a way for new users to sign up and for existing users to log in.

I've noticed that if I click on the magic link sent to my email address from a different browser than where I input my email address, the magic link does not sign me up/sign me in. I've noticed that in the Application panel in dev tools, a `next-auth.callback-url` and `next-auth.csrf-token` cookies get stored in my browser. So, I am assuming that is why I can't click on the "Sign in" link sent to my email from a different browser.

Being able to click on the link from my phone while signing up from my desktop is a flow that I commonly do. I am wondering if that makes sense and if this use case can be achieved without a huge effort?

Thank you in advance, and thank you for this awesome library!

### How to reproduce ☕️

N / A

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
This is the default behavior and should be working already the way you describe it. Can you add a reproduction?
