### ISSUE TITLE
Not Enough Information About Custom Adapters in Typescript

### ISSUE THREAD

**Issue by LuckyMcBeast** [nextauthjs/next-auth#7947]
### What is the improvement or update you wish to see?

The next auth documentation about custom adapters for typescript is exceptionally lacking.

![image](https://github.com/nextauthjs/next-auth/assets/19576746/c9339459-1d2e-4a0a-bd92-99f31b1dc924)

Please provide more information context and information about the associated types. Documentation around custom adapters in general ([here](https://authjs.dev/guides/adapters/creating-a-database-adapter) and [here](https://next-auth.js.org/getting-started/typescript)) should be expanded to offer a better explanation of what each adapter method should return, with at least one code example of each method's potential implementation.

### Is there any context that might help us understand?

I'm using NextAuth.js to implement email authentication and using a restful microservice (written in Kotlin with Spring) to manage customers. There is a PostgreSQL database behind that, but I don't want my frontend and edge applications to "know" it exists. In part, the microservice is behaving as a data abstraction layer, while also performing other actions on request.

With the limited documentation, it is challenging to understand how this is to be achieved with a custom database adapter. I have seen a few examples through a google search, mostly from Youtubers, on how to implement one in Javascript, but none that I have found are using Typescript. Though I did eventually find some useful comments and gain a better understanding by looking at the type definition source code, the primary documentation should provide some sort of spec online so that it's more accessible.

This [repo](https://github.com/nextauthjs/next-auth-example) also does not show a clear example of implementing a custom adapter. One example with the adapter methods implemented would go a long way.

I am willing to update the docs later on this week after I complete my task related to this, but I will need some direction on the process of contributing to it.

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/getting-started/typescript

**Comment by balazsorban44** [comment]
Hi, this is addressed in the new documentation. API reference is generated from the source code, so it always matches on the website.

See https://authjs.dev/reference/core/adapters

**Comment by LuckyMcBeast** [comment]
@balazsorban44 , thanks! Not sure how I missed that....

**Comment by balazsorban44** [comment]
Admittedly the docs is in this intermittent/overlapping state, totally understandable. New content will always be available on authjs.dev from now on, and we only fix small typos etc. on the old one. We are always open for feedback!

**Comment by LuckyMcBeast** [comment]
Maybe there should just be a link on the ["Creating a database adapter"](https://authjs.dev/guides/adapters/creating-a-database-adapter) page to the API reference, but I'm not sure I would have missed that if I had started on the new auth.js site. Changes like this definitely come with there challenges, but I'm happy the project is branching out. I really appreciate the quick response and wish you the best!
