### ISSUE TITLE
Invalid URL error and not redirecting to provider

### ISSUE THREAD

**Issue by radonyizsolt** [nextauthjs/next-auth#7956]
### Question 💬

Hi!
I have a Nuxt 3 application and I am using it with a keycloak adapter. Now when I open the sign in page I only want to see the keycloak login page and done the configuration accordingly. But in the  
`- next-auth@4.21.1_next@13.4.8_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/default-callbacks.js`
file in the redirect function sometimes I get an error saying [500] Invalid URL , which is happening because sometimes the url passed to this function is undefined. So my application actually does not redirect to the correct page. 
If I comment out the else if part of this line:

`if (url.startsWith("/")) return `${baseUrl}${url}`;else if (new URL(url).origin === baseUrl) return url;`

All things start to work.  What can I do about this issue. Is there a way to have a hotfix so this is checking if the url parameter is actually there before passing it to the new URL method?

Thank you!

### How to reproduce ☕️

Just asking if there is a possibility to have an extra check in one of the code snippets

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Hi, this project does not officially support Nuxt (yet), assuming you wanted to post this in https://github.com/sidebase/nuxt-auth instead. :pray:
