### ISSUE TITLE
action/method no-match on AuthHandler message customization

### ISSUE THREAD

**Issue by gaberankin** [nextauthjs/next-auth#7958]
### Question 💬

Thanks very much for the work in this library.  it's been working great for us.  I do have a question about an edge case, however.

Our manager is very security minded, and one thing he's found when poking around in our app is that when going to a nonexistent route under `/api/auth`, he gets an error message that looks like:

```
Error: This action with HTTP GET is not supported by NextAuth.js
```

He's raised this as 2 issues - one being that it's a sub-optimal user experience (because it's just text and there's no way to guide users to the home page of our application) and the second being that it's identifying the provider of authentication-handling (with NextAuth.js being directly in the error text), which he considers to be a potential security risk.

To address this, he's asked that we create a custom error page with different text and access to the layout of our application.  We're using Next.js, and creating error pages is fairly painless using it.  Unfortunately though, it seems that the mechanism behind next-auth's error in this case seems to happen outside of the next.js app's routing.  perhaps this is a configuration mistake on our end, but when we hit `/api/auth/some-page-that-doesnt-exist`, the above error is returned regardless of the custom error page we set up for our application.

Is there a way to change the error message that returns from `AuthHandler` when the action and/or method fails to match anything?  My digging in the code to try to understand the mechanism more is currently telling me "not at this time" but i may be missing something.

Fortunately my manager's understanding that this may be the case but I wanted to make sure that I haven't missed anything.  Thank you very much for any help that can be provided.

### How to reproduce ☕️

in browser, go to any nonexistent route under `/api/auth`, such as `/api/auth/foo`

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by ThangHuuVu** [comment]
Thanks for the detail question, so I think there is a way that you can try that is Advanced Initialization
```ts

export default async function (req: NextApiRequest, res: NextApiResponse) {
  await NextAuth(req, res, authOptions)

  if (res.statusCode === 400) {
    // Override the default behavior here
    return res.end()
  }

  return res
}
```

As you might already know, because we will return 400 error if none of the methods/actions match at https://github.com/nextauthjs/next-auth/blob/v4/packages/next-auth/src/core/index.ts#L318-L322, there is no way to configure this in `next-auth` yet. 

Since this is the first time I see this request, I'm going to close - if we get more similar requests in the future, I would be happy to reopen and consider a configuration for this.

**Comment by gaberankin** [comment]
@ThangHuuVu , thank you very much for the suggestion.  I am ashamed to say that I did some additional searching in the docs for next-auth and found an example of your suggestion with full code (https://next-auth.js.org/configuration/initialization#advanced-initialization), which turned out to be exactly what I needed.  I should have posted back on this issue to enable closing earlier, and for that I apologize.
