### ISSUE TITLE
Support wechat login

### ISSUE THREAD

**Issue by evanlong0926** [nextauthjs/next-auth#7960]
### Description 📓

This is a very important way to open the Chinese market.

Hope to support. 🤓

### How to reproduce ☕️

This is WeChat documentation：

https://developers.weixin.qq.com/doc/oplatform/Website_App/WeChat_Login/Wechat_Login.html

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
There have been a few PRs but all staled or the author has closed them. See https://github.com/nextauthjs/next-auth/pulls?q=is%3Apr+wechat+is%3Aclosed

Feel free to reuse the code in those PRs, and eventually open a new PR if you want it built-in.

**Comment by evanlong0926** [comment]
@balazsorban44 I see it's already been submitted, it's just never been reviewed.

![image](https://github.com/nextauthjs/next-auth/assets/52912949/1b2f6e6b-6372-4df0-bdf1-ad2749cefaec)
