### ISSUE TITLE
Next 13.4 denies returning values from API handlers

### ISSUE THREAD

**Issue by nick4fake** [nextauthjs/next-auth#7963]
### Environment

---

### Reproduction URL

https://github.com/nextauthjs/next-auth/tree/main

### Describe the issue

New NextJS shows this notification

````
API handler should not return a value, received object.
````

### How to reproduce

Basically just use nextauth

````typescript
import NextAuth from "next-auth";

export const authOptions = {
  providers: [.......],
};

export default NextAuth(authOptions);
````

### Expected behavior

No notifications printed. I think the issue is in the following lines:
https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/next/index.ts#L58

**Comment by nick4fake** [comment]
Relevant discussion:
https://github.com/vercel/next.js/discussions/48951

**Comment by nick4fake** [comment]
BTW, fix is trivial for client code:

````typescript
const authHandler = NextAuth(authOptions);

export default async function handler(...params) {
  await authHandler(...params);
}
````

Though I think it be fixed on the library side.

**Comment by haozhangzyb** [comment]
I meet the same issue when signout.
