### ISSUE TITLE
Google Provider keeps redirecting to http://localhost:3000/api/auth/signin?error=OAuthCallback even on vercel deployment with NEXTAUTH_URL set

### ISSUE THREAD

**Issue by Dank-del** [nextauthjs/next-auth#7964]
### Provider type

Google

### Environment

 System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 1.34 GB / 11.43 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.5.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.1928.0), Chromium (114.0.1823.67)
    Internet Explorer: 11.0.22621.1

### Reproduction URL

https://github.com/Dank-del/idea-hub

### Describe the issue

I always get redirected to [this](http://localhost:3000/api/auth/signin?error=OAuthCallback) even when logging in from prod and selecting google account.
![image](https://github.com/nextauthjs/next-auth/assets/63096193/0c521db2-a52d-4267-b894-82369f776e4a)

I tried debugging the code with prints of env vars
![image](https://github.com/nextauthjs/next-auth/assets/63096193/46cf5027-cec7-473c-8408-08a33a9df5f0)

### How to reproduce

- deploy the repo to vercel
- setup the env vars
- try to login

### Expected behavior

It should have redirected to the actual prod url: https://ideahub.sayanbiswas.in

**Comment by iambstha** [comment]
Make sure to set the redirect url to your actual live deployed application
![image](https://github.com/nextauthjs/next-auth/assets/85658373/3d94c479-9446-43cb-ae8c-074a5ec9d0e5)

**Comment by Dank-del** [comment]
> Make sure to set the redirect url to your actual live deployed application ![image](https://user-images.githubusercontent.com/85658373/251549236-3d94c479-9446-43cb-ae8c-074a5ec9d0e5.png)

![image](https://github.com/nextauthjs/next-auth/assets/63096193/b1ad39f4-bfda-4e46-bd3d-85d64b04cf32)
I do have it configured with proper redirect urls in the google dev console

**Comment by balazsorban44** [comment]
As per the docs, you should not need to set `NEXTAUTH_URL` On Vercel https://next-auth.js.org/deployment#vercel

(make sure to follow the rest of the steps on that page)

You can see a working deployment with Google login here https://next-auth-example.vercel.app/

**Comment by balazsorban44** [comment]
You are also on an experimental version of `next-auth`, which might break unexpectedly. The best you can do is keep it up to date by checking `experimental` at https://www.npmjs.com/package/next-auth?activeTab=versions

and follow #7443

**Comment by iambstha** [comment]
If this helps, https://github.com/iambstha/next-auth-implementation

**Comment by Dank-del** [comment]
thanks guys, it got fixed when i switched to v4 of next-auth 
![image](https://github.com/nextauthjs/next-auth/assets/63096193/26c958ea-0e2f-406a-8eb8-4ecf8732b1cc)

**Comment by I-am-vishalmaurya** [comment]
I also faced this issue, with AuthJS Version 5 from the example app, what helped was setting the Redirect Callback URL to this: 
<img width="613" alt="Screenshot 2024-10-27 at 3 01 03 PM" src="https://github.com/user-attachments/assets/29a4ee1b-c3e6-444e-b0a3-dd1041f3596c">

http://localhost:3000/auth/callback/google

After doing this I was able to login
