### ISSUE TITLE
Is it safe to store access token in next-auth session?

### ISSUE THREAD

**Issue by JeremyXXXuuu** [nextauthjs/next-auth#7976]
### Question 💬

What I want is to access the protected data from resource provider, so I need to pass the access token to the backend API 

Using next-auth, I was able to store the access token to the session. And I find out this official example: https://github.com/nextauthjs/next-auth-refresh-token-example/tree/57f84dbc50f30233d4ee389c7239212858ecae14.
Actually,  put access_token in next-auth session, thats great, we can use `getServerSession()` to get our access token and fetch protected resourse in server side, but I found out that every time when we called `useSession()` in client side, it triggers a `get `request on the client side ( your_api_url/auth/session ) to retrieve the session information, including the access token. This means that the access token could potentially be exposed in the client-side network traffic. 
![image](https://github.com/nextauthjs/next-auth/assets/71556252/1383bfad-327d-486f-b21d-a90d4cffe1f2)
![image](https://github.com/nextauthjs/next-auth/assets/71556252/2515e7e8-a3e7-48ca-8799-ec7ee8dacadf)

Does access token exposed in the client mean that there is some security risk? Authorization code flow requires the completion of code and token exchange in the server side is to protect the token in the server side rather than the client.

Is there some other way to store access token in nextauth?

### How to reproduce ☕️

/api/[...nextauth]/route.ts
```ts
  callbacks: {
    async jwt({ token, user, account }) {
      // Initial sign in
      if (account && user) {
        return {
          accessToken: account.access_token,
          accessTokenExpires: Date.now() + account.expires_in * 1000,
          refreshToken: account.refresh_token,
          user
        }
      }

      // Return previous token if the access token has not expired yet
      if (Date.now() < token.accessTokenExpires) {
        return token
      }

      // Access token has expired, try to update it
      return refreshAccessToken(token)
    },
    async session({ session, token }) {
      session.user = token.user
      session.accessToken = token.accessToken
      session.error = token.error

      return session
    }
  }
})
```
/index.ts
```ts
export default function Home() {
  const { data: session } = useSession()

```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
you don't have to expose the access token to the client, see the docs https://next-auth.js.org/configuration/callbacks#session-callback

This callback decides what's exposed of the session via the `/api/auth/session` endpoint.

You can proxy API requests through the Next.js backend where you can safely read the whole content of the session, including your access_token

**Comment by waza-ari** [comment]
Dear @balazsorban44 , sorry for reopening this issue. I wonder if you could give any guidance on how to `safely read the whole content of the session` in the Next.js backend? I've been trying to do that for some time but haven't found a way to retrieve this information.

**Comment by HaseebAhmed456** [comment]
@waza-ari I believe you can do so with the help of next-auth getServerSession method. https://next-auth.js.org/configuration/nextjs#getserversession

**Comment by waza-ari** [comment]
@HaseebAhmed456 I tried that, it returns the same attributes that are exposed to the client session using the session callback.

**Comment by HaseebAhmed456** [comment]
@waza-ari You need to call getServerSession inside your next backend i.e API routes which provides as public end point and you can route your requests through that endpoint

**Comment by waza-ari** [comment]
I understand. I'm using server components and server data fetching already, so I don't need the data on the client. running `getServerSession` on server side also only returns whatever is exposed by the session callback. I'm looking for a way to get the AT on server side without exposing it to the client session.

**Comment by HaseebAhmed456** [comment]
@balazsorban44 Is there any other solution to this other than routing your requests through next backend proxy api. As we need access_token in our client components but getting this info via useSession exposes the access_token in network calls

**Comment by waza-ari** [comment]
if you need it in your client components it has to be sent to the client somehow, there is no way around it. That's different from our use case, as we only want to get the AT on the server side.

**Comment by HaseebAhmed456** [comment]
> I understand. I'm using server components and server data fetching already, so I don't need the data on the client. running `getServerSession` on server side also only returns whatever is exposed by the session callback. I'm looking for a way to get the AT on server side without exposing it to the client session.

Well in your case you can use server actions which are basically functions that only run on the server. https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations

**Comment by waza-ari** [comment]
I fully understand and were using them. Again, I'm looking for a way to get the AT in the server actions without exposing them to the client. `getServerSession` doesn't include the AT unless added via the session callback, but that's adds the AT ALSO to the client which we want to avoid.

**Comment by HaseebAhmed456** [comment]
> I fully understand and were using them. Again, I'm looking for a way to get the AT in the server actions without exposing them to the client. `getServerSession` doesn't include the AT unless added via the session callback, but that's adds the AT ALSO to the client which we want to avoid.

https://github.com/vercel/next.js/discussions/52006 
You may want to look at this. They discussed the problem in great detail. I think we may need to encrypt the access_token ourselves and then decrypt it before sending to secure API's

**Comment by rafaelalvesmartins** [comment]
Hello! I am using version 5.0.0-beta.4 of NextAuth. To retrieve the session on the server-side, I used the following code:

javascript
Copy code
import { auth } from "@/auth";

export default async function Page() {
  const session = await auth();
  const token = session.accessToken;

  return (<p>Welcome {session?.user.name}!</p>);
}
I found this code at: https://authjs.dev/getting-started/migrating-to-v5

**Comment by olems** [comment]
The only clean way I have found to do this in v5 without exposing the access token client side is to use getToken() from next-auth/jwt to decode the jwt token cookie serverside, even though the v5 docs says using this is not recommended. This requires the authjs secret and the hashing salt. The latter is undocumented but you can find the details in https://github.com/nextauthjs/next-auth/discussions/9133

**Comment by andrew-stratyfy** [comment]
@waza-ari I am assuming you don't mind the access token being present in the encrypted JWT, as long as the client can't access the decrypted version.  Obviously if you don't even want the client to get the encrypted access token you can't store it in the JWT, period.

I eventually figured out that while you have to pass a `config` both when setting up the next-auth endpoints and sign-in / sign-out functions, and when getting the `auth()` function, _it doesn't have to be exactly the same_.  Hence:

```javascript
const baseConfig = {
  callbacks: {
    async jwt(...) { ... },
    // no session(), or your custom session() that does not add the access token
  },
  ...,
};

const serverConfig = {
  ...baseConfig,
  callbacks: {
    ...baseConfig.callbacks,
    async session({ session, token }) {
      session.accessToken = token.accessToken;
      // etc
      return session;
    },
  },
};

// The GET handler doesn't get the access token, so neither does the client
const { handlers, signIn, signOut } = NextAuth(baseConfig);

// This will get the access token for use server-side
const { auth } = NextAuth(serverConfig);
```

We are on 5.0.0beta, so this example does not use the removed `getServerSession()`, but I imagine it's similar.

**Comment by internalG** [comment]
Anyone tried this solution? It's not documented but promising. Is it the best practice to hide sensitive data from client but available on server? Since v5 is still beta I don't want to be broken later.

> @waza-ari I 
> ```js
> const baseConfig = {
>   callbacks: {
>     async jwt(...) { ... },
>     // no session(), or your custom session() that does not add the access token
>   },
>   ...,
> };
> 
> const serverConfig = {
>   ...baseConfig,
>   callbacks: {
>     ...baseConfig.callbacks,
>     async session({ session, token }) {
>       session.accessToken = token.accessToken;
>       // etc
>       return session;
>     },
>   },
> };
> 
> // The GET handler doesn't get the access token, so neither does the client
> const { handlers, signIn, signOut } = NextAuth(baseConfig);
> 
> // This will get the access token for use server-side
> const { auth } = NextAuth(serverConfig);
> ```

**Comment by gregpica** [comment]
Just adding here what worked for me, just in case it is not clear to others. The answer is muddled above in different answers.

My use case is that I want my proxy API to gain access securely to the accessToken so that I can make API requests to a third party. 

The key is to NOT include the accessToken in the session object... so either do not use the session callback altogether, or just make sure not to mutate the object to include the accessToken like so many of the docs and examples do. This takes care of the 'api/auth/session' issue. 

Just include the accessToken in the JWT callback return, then in your proxy API / sever use getToken() from 'next-auth/jwt'.

**Comment by HaseebAhmed456** [comment]
> Just adding here what worked for me, just in case it is not clear to others. The answer is muddled above in different answers.
> 
> My use case is that I want my proxy API to gain access securely to the accessToken so that I can make API requests to a third party.
> 
> The key is to NOT include the accessToken in the session object... so either do not use the session callback altogether, or just make sure not to mutate the object to include the accessToken like so many of the docs and examples do. This takes care of the 'api/auth/session' issue.
> 
> Just include the accessToken in the JWT callback return, then in your proxy API / server use getToken() from 'next-auth/jwt'.

Yes I think this is the solution one should go for. I have a few concerns with this approach:

- You need to proxy each API through your next server which adds more complexity and impacts performance
- We need to implement error handling on both server side while rerouting API call to a third party and also on client side in case request fails (network or other server issue). 
 
Would love to hear everybody's thoughts on this.

**Comment by VictorPrins** [comment]
The following works for me as of next-auth version `5.0.0-beta.29`. 
This example makes the access token **available to server-side code, without exposing it to client-side** code.

Add the following snippet to your `NextAuth()` initialization:
```ts
callbacks: {
  jwt({ token, account }) {
    if (account) {
      token.accessToken = account.access_token;
    }
    return token;
  }
}
```

You can now get the access token in any server-side component:

```ts
import { headers } from 'next/headers';
import { getToken } from 'next-auth/jwt';

export default async function Component() {

  const secureCookie = process.env.AUTH_URL!.startsWith("https://")
  // Alternative:
  // const secureCookie = process.env.NODE_ENV === "production"
  // Or any other identifier of your preference which can separate production from local development
  // See more explanation below

  const token = await getToken({ 
    req: { headers: await headers() },
    secret: process.env.AUTH_SECRET!,
    secureCookie
  });

  console.log('Access token:', token?.accessToken);

  // .. remainder of the component ..
}
```

Explanation of `secureCookie`:

Authjs by default uses 'secure cookies' if your website URL uses `https://`. This should always be the case in your production environment . The only exception is when you're developing locally, on `http://localhost:3000`. You can check whether Authjs uses 'secure cookies' by inspecting the cookies in your browser devtools. Look specifically for the following cookies:
- If the session cookies are called `authjs.session-token`, `authjs.session-token.0` or `authjs.session-token.1`, then you should set `secureCookie` to `false`.
- If the session cookies are called `__Secure-authjs.session-token`, `__Secure-authjs.session-token.0`, or `__Secure-authjs.session-token.1` (note the prefix **`__Secure-`**), then you should set `secureCookie` to `true`.

**Comment by bertramakers** [comment]
> you don't have to expose the access token to the client, see the docs https://next-auth.js.org/configuration/callbacks#session-callback
> 
> This callback decides what's exposed of the session via the `/api/auth/session` endpoint.
> 
> You can proxy API requests through the Next.js backend where you can safely read the whole content of the session, including your access_token.
> 
> By default, we already only expose name, image and email for presentational purposes.

@balazsorban44 While implementing this library we ran into the same question as OP.
On the one hand we understand your explanation here to not include the access token in the session endpoint, and instead proxy API calls through the Next.js backend, but on the other hand we see that in the official documentation there is an example how to expose the access token in the session endpoint: https://next-auth.js.org/configuration/callbacks#session-callback

So now we're wondering, what is the security impact of doing this? And if we shouldn't do this, should the docs be updated to not suggest that it's okay to return the access token in the session endpoint?

(cc @brampauwelyn)
