### ISSUE TITLE
publish feat/nextjs-auth

### ISSUE THREAD

**Issue by zwhitchcox** [nextauthjs/next-auth#7980]
### Description 📓

Regarding #7953, it looks like the `feat/nextjs-auth` branch is necessary to use the App Router, which is the default recommendation of NextJS.

It might be helpful for that branch should be published so we can use the recommended feature, or could you provide some clarity on how we should use this repo in coordination with NextJS? Unless you guys are not coordinating the repos together?

### How to reproduce ☕️

Following the examples at 

https://github.com/nextauthjs/next-auth/tree/790f7617083d055b94d05c5c815749258da84852/apps/examples/nextjs

and https://github.com/nextauthjs/next-auth/tree/790f7617083d055b94d05c5c815749258da84852/apps/dev/nextjs

I get the errors:

```
- error app/page.tsx (7:28) @ auth
- error TypeError: (0 , _auth__WEBPACK_IMPORTED_MODULE_1__.auth) is not
 a function
    at Home (./app/page.tsx:19:70)
    at async Promise.all (index 0)
   5 | 
   6 | export default async function Home() {
>  7 |   const session = await auth();
     |                            ^
   8 |   return (
   9 |     <>
  10 |       <Head>
```
  
and

```
  31 | 
  32 | export const {
> 33 |   handlers: { GET, POST },
     |              ^
  34 |   auth,
  35 |   CSRF_experimental,
  36 | } = NextAuth(authOptions)
  ```

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by zwhitchcox** [comment]
Ok, this was hard to find, but there's a [guide](https://auth-docs-git-feat-nextjs-auth-authjs.vercel.app/guides/upgrade-to-v5) on upgrading to V5 that I guess we're supposed to use?

And looking at the npm repo, there's a version [0.0.0-manual.83c4ebd1](https://www.npmjs.com/package/next-auth/v/0.0.0-manual.83c4ebd1), which I guess is the build from `feat/nextjs-auth` branch that I guess we're supposed to use as well?

It was quite hard to find both of these, so that's why I'm not sure...still better than building from source.

**Comment by pschaub** [comment]
I would also like to use next-auth in a new NextJS project with app router and don't understand the current documentation. I also looked at the examples above and I am unsure if they are up to date. I have opened an issue to update the documentation here: https://github.com/nextauthjs/next-auth/issues/7981

**Comment by zwhitchcox** [comment]
Ok, this is the only working example of next-auth v5 I've found that's fully functional, that I intend to copy.

It's using all the things I've mentioned, plus next.js canary. I think it's a good project to emulate:

https://vercel.com/templates/next.js/nextjs-ai-chatbot

**Comment by zwhitchcox** [comment]
cc @Yedidya10

**Comment by pschaub** [comment]
Have you seen this part in the v4 documentation?
> If you're using [Next.js 13.2](https://nextjs.org/blog/next-13-2#custom-route-handlers) or above with the new App Router (app/), you can initialize the configuration using the new [Route Handlers](https://nextjs.org/docs/app/building-your-application/routing/router-handlers) by following our [guide](https://next-auth.js.org/configuration/initialization#route-handlers-app).

Source: https://next-auth.js.org/getting-started/example#add-api-route

There is an example how to use next-auth v4 with Next.js 13.2 app router (route handlers) here: https://next-auth.js.org/configuration/initialization#route-handlers-app

Have you tried this?

**Comment by balazsorban44** [comment]
#7443 has all the information for those who want to try it out. It's not ready for the general public yet, we are currently dogfooding it in some projects. Please keep feedback on the PR, thanks.

**Comment by barqco** [comment]
> Ok, this is the only working example of next-auth v5 I've found that's fully functional, that I intend to copy.
> 
> It's using all the things I've mentioned, plus next.js canary. I think it's a good project to emulate:
> 
> https://vercel.com/templates/next.js/nextjs-ai-chatbot

Still looking for an example with Suspense and Next-auth v5 haha.
