### ISSUE TITLE
Add server version of client-side "signIn" function

### ISSUE THREAD

**Issue by babyccino** [nextauthjs/next-auth#7986]
### Description 📓

If you want to automatically redirect a user to an OAuth sign in the best current solution is to create a page and run the client-side 'signIn' function when the page loads (as per [this discussion](https://github.com/nextauthjs/next-auth/discussions/4078)). This is a pretty clunky and slow solution. There should be an analogue of this function which you can run on the server. This function could either return the OAuth sign in url or automatically redirect

### Example of how it could work

```
import { NextApiHandler } from "next"
import { getServerSession, serverSignIn } from "next-auth"

const handler: NextApiHandler = async (req, res) => {
  if (req.method !== "GET") {
    return res.status(405).end()
  }

  const session = await getServerSession(req, res, authOptions)
  if (session) return res.redirect(302, "/")

  // this would automatically redirect a user to Google's OAuth sign in flow
  void serverSignIn(req, res, { provider: "google", redirect: true })

  // alternatively you could intercept the redirect url
  const url = await serverSignIn(req, res, { provider: "google", redirect: false })
  res.redirect(302, url)
}
export default handler
```

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
Generally, I would suggest that a signin intent should be made by a user (ie click a button). That said, we might add something similar to #7443

**Comment by babyccino** [comment]
My initial motivation for this was that a third party using my application needs a link which will automatically start the OAuth workflow. An API route which serves this purpose would also work, something like `.../sso/[providerId]`
