### ISSUE TITLE
maxAge based on condition

### ISSUE THREAD

**Issue by vinitgundeti** [nextauthjs/next-auth#8000]
### Question 💬

I am encountering an issue with my website related to the parameters deviceType and maxAge. The deviceType parameter can have values like "Mobile," "Web," or "Adv." I would like to set the maxAge value based on the deviceType parameter.

If the deviceType is set to "Mobile," then the maxAge should be one day, which is equivalent to 24 * 60 * 60 seconds. Otherwise, if the deviceType is not "Mobile," the maxAge should be set to 10 minutes, or 10 * 60 seconds.

However, I'm facing a problem in accessing the router in the nextAuth.js file. Due to this limitation, I'm unable to determine how to achieve this functionality. Is it possible to set the maxAge value in the session callback function, or is there another solution available?

I would appreciate any assistance or guidance on resolving this issue. Thank you.

### How to reproduce ☕️

`session: {
    maxAge: 10*60
}`

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
There is no `deviceType` setting in `next-auth`. However you _can_ access the full request for advanced use cases, see the documentation https://next-auth.js.org/configuration/initialization#advanced-initialization

**Comment by vinitgundeti** [comment]
Hi @balazsorban44, My website opens through application in webview. so from application I will receive deviceType

for eg: https://www.abc.com/something?deviceType=Mobile

my usecase is in website I will return to sign in page when session expires. but I cannot return to sign in page in mobile application. so that is why I want to increase the maxAge when I receive deviceType as Mobile

so as per the documentation link you shared, can i set like below ?

`// Get a custom cookie value from the request
  const someCookie = req.cookies["maxAge"]

  return await NextAuth(req, res, {
    ...
    callbacks: {
      session({ session, token }) {
        // Return a cookie value as part of the session
        // This is read when `req.query.nextauth.includes("session") && req.method === "GET"`
        session.someCookie = token.deviceType === "Mobile" ? 24*60*60 : 10*60;
        return session
      }
    }
  })`
