### ISSUE TITLE
createCSRFToken in /next-auth/core/lib/csrf-token.ts

### ISSUE THREAD

**Issue by dbstjrrb12** [nextauthjs/next-auth#8008]
### Question 💬

Hello, and thank you for creating such a great library. I'm encountering an error while implementing login with Next-auth and I have a question.

Currently, when I clear the cache in Safari or Chrome mobile browsers and try to log in with OAuth providers like Naver (e.g., calling signIn('naver') from the client), I'm redirected to "/signin?csrf=true" with a 302 HTTP status.

Upon examining the related logic, I found that in the `AuthHandler`, when handling a POST signin request, it checks the value of `options.csrfTokenVerified`. If this value is falsy, it triggers the redirect.

In the `init` function, `options.csrfTokenVerified` is updated with the return value of the `createCSRFToken` function. However, this function only returns `{ cookie, csrfToken }` when issuing a new CSRF token and does not return **csrfTokenVerified**. Shouldn't csrfTokenVerified also be set to a truthy value if a new token is generated? It seems like the newly generated token should always be considered valid. Could you clarify this?

```js
export function createCSRFToken({
  options,
  cookieValue,
  isPost,
  bodyValue,
}: CreateCSRFTokenParams) {
  if (cookieValue) {
    const [csrfToken, csrfTokenHash] = cookieValue.split("|")
    const expectedCsrfTokenHash = createHash("sha256")
      .update(`${csrfToken}${options.secret}`)
      .digest("hex")
    if (csrfTokenHash === expectedCsrfTokenHash) {
      // If hash matches then we trust the CSRF token value
      // If this is a POST request and the CSRF Token in the POST request matches
      // the cookie we have already verified is the one we have set, then the token is verified!
      const csrfTokenVerified = isPost && csrfToken === bodyValue

      return { csrfTokenVerified, csrfToken }
    }
  }

  // New CSRF token
  const csrfToken = randomBytes(32).toString("hex")
  const csrfTokenHash = createHash("sha256")
    .update(`${csrfToken}${options.secret}`)
    .digest("hex")
  const cookie = `${csrfToken}|${csrfTokenHash}`

  return { cookie, csrfToken } // here!
}
```

```js
export async function init({...}){
   ...
   const {
    csrfToken,
    cookie: csrfCookie,
    csrfTokenVerified,
  } = createCSRFToken({
    options,
    cookieValue: reqCookies?.[options.cookies.csrfToken.name],
    isPost,
    bodyValue: reqCsrfToken,
  })

  options.csrfToken = csrfToken
  options.csrfTokenVerified = csrfTokenVerified // here!!
   
   ...
}
```

### How to reproduce ☕️

After clearing the cache and cookies in a mobile browser using Next Auth, I call the signIn function.

![스크린샷 2023-07-10 오후 3 47 43 복사본](https://github.com/nextauthjs/next-auth/assets/49303508/13536ccf-b07d-4475-be8a-81fbe28f0c93)

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
The CSRF token needs to be set before any login attempts, as per the OWASP CSRF guide: https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#naive-double-submit-cookie So only the second attempt should be valid in this case.

**Comment by dbstjrrb12** [comment]
Is there any way to simultaneously call the signIn function and pass the csrfToken from the Client API provided by Next Auth? [In this link](https://github.com/nextauthjs/next-auth/issues/656#issuecomment-764501912), He is explicitly passing the csrfToken using a form tag. If I want to solve the above problem, should I follow the approach mentioned in the link?
