### ISSUE TITLE
Inconsistent `error` declaration in `signIn()` function

### ISSUE THREAD

**Issue by rentalhost** [nextauthjs/next-auth#8010]
### Environment

```
  System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 2700 Eight-Core Processor
    Memory: 19.31 GB / 31.92 GB
  Binaries:
    Node: 20.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.3.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.7.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.6 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.1928.0), Chromium (114.0.1823.51)
    Internet Explorer: 11.0.22621.1
```

### Describe the issue

Hello,

I'm reaching out to report an issue I encountered while using the `signIn({ redirect: false, ... })` method of `next-auth` on the client-side, specifically when handling credentials. Below is a code snippet for reference:

```ts
const response = await signIn("credentials", {
  redirect: false,
  username: referenceUsername.current?.value,
  password: referencePassword.current?.value,
});

if (response!.error !== null) { // error here is string | undefined, but actually it is string | null
  // error logic
  return;
}
```

According to the documentation, the `signIn()` function should return a `Promise<SignInResponse>`. Currently, the declaration of the `error` property is of type `string | undefined`. However, I noticed that when no error occurs, the returned value is `null` instead of `undefined`.

I suggest adjusting the declaration of the [`error`](https://github.com/nextauthjs/next-auth/blob/8cee24d4abba58de4c0a86fa1e184392118f809f/packages/next-auth/src/react/types.ts#L38) property to the type `string | null`, as when using the [`URLSearchParams.get()`](https://github.com/nextauthjs/next-auth/blob/8cee24d4abba58de4c0a86fa1e184392118f809f/packages/next-auth/src/react/index.tsx#L277) method, an undefined value is returned as `null` rather than `undefined`. This change would bring greater consistency and coherence to error handling in the `signIn()` function.

**Comment by decidev22** [comment]
Is this the issue where you get redirected to api/auth/error page?

**Comment by rentalhost** [comment]
@decidev22 No, in short, it's just a mismatch in the declared type of `error`.
