### ISSUE TITLE
Using signIn() in a custom signin page with redirect: false throws error on redirect

### ISSUE THREAD

**Issue by craigmcc** [nextauthjs/next-auth#8027]
### Environment

```
  System:
    OS: macOS 13.4.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 26.65 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
```

The NPM versions were not returned, so documented manually:
* "next": "13.4.9"
* "next-auth": "4.22.1"
* "react": "18.2.0"

### Reproduction URL

https://github.com/craigmcc/bookcase

### Describe the issue

I am writing a custom sign in page for next-auth, and trying to call the provided signIn() function like this:

```ts
    async function onSubmit(values: z.infer<typeof formSchema>) {
        const result = await signIn<"credentials">("credentials", {
            callbackUrl: callbackUrl,  // Comes from the searchParams "callbackUrl" parameter
            password: values.password,
            redirect: false,
            username: values.username,
        });
```

What I want to do is manually perform the redirect if signin was successful, but stay here and show a "please try again" if (for example) authentication failed.

This works as desired when authentication fails, but authentication succeeds and I try the redirect, it throws a NEXT_REDIRECT error even though the callbackUrl value is correct.

```ts
        if (result) {
            if (!result.error) {
                try {
                    return redirect(callbackUrl);
                } catch (error) {
                    alert(`Caught error ${JSON.stringify(error)}`);
                }
            } else {
                alert("Authentication failed.  Please try again");
            }
        }
```

### How to reproduce

Using  a signIn() method call with redirect:false
* Authentication fails - stay on the sign in page and can display an appropriate error.
* Authentication succeeds - always throws on the redirect call.

My current workaround is to use redirect: true, which does indeed do the redirect on the "authentication succeeds" case, but silently stays on the sign in page in case of an error.

### Expected behavior

The redirect call should succeed, transferring the user to the specified URL.

**Comment by FlorianLeChat** [comment]
I can also confirm this issue on AuthJS v5 (beta 4). Similar issue with Google provider: https://github.com/nextauthjs/next-auth/issues/9230.

**Comment by balazsorban44** [comment]
`NEXT_REDIRECT` is an error thrown when `redirect()` is called. It is supposed to propagate to a Redirect ErrorBoundary in Next.js, which will then execute the redirection. It is not related to this library (neither NextAuth.js v4 or v5).

You should not be catching those errors and let Next.js handle them.

Ref: https://nextjs.org/docs/app/api-reference/functions/redirect#server-component
