### ISSUE TITLE
Outdated Clone and Installation Commands in Readme

### ISSUE THREAD

**Issue by serdarsen** [nextauthjs/next-auth#8029]
### What is the improvement or update you wish to see?

I noticed that the documentation for NextAuth.js has outdated clone and installation commands in the readme file. The current commands instruct users to clone the repository from https://github.com/nextauthjs/docs.git, but the correct location has been moved to https://github.com/nextauthjs/next-auth.git.

Additionally, the readme suggests using `npm install` and `npm start` for installation and starting the project, respectively. However, it seems that the correct commands should be `pnpm install` and `pnpm dev:docs` or `cd docs && pnpm start`.

I have tested the new commands and they worked for me, but I wanted to raise this issue to discuss and propose the necessary updates to the documentation. I'm not entirely certain about the correctness of the new commands, so it would be great to have the input and confirmation from the project maintainers.

Please let's discuss and find a suitable solution to update the documentation accordingly. I'm also more than willing to contribute by submitting a pull request with the proposed changes. Thank you for your attention to this matter!

### Is there any context that might help us understand?

- Visit the documentation at https://github.com/nextauthjs/next-auth/blob/main/docs/README.md.
- Scroll to the "Getting Started" section in the readme file.
- Observe that the clone command is `git clone https://github.com/nextauthjs/docs.git`.
- Note that the installation command is `npm install` and the start command is `npm start`.

### Does the docs page already exist? Please link to it.

https://github.com/nextauthjs/next-auth/blob/main/docs/README.md#getting-started

**Comment by balazsorban44** [comment]
Right. We've been using a monorepo setup for a while now. You can check out https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md

To develop the docs, you can run `pnpm dev:docs`

To edit pages, you generally don't need to set up a local dev environment though, most docs pages will have a "edit this page" button towards the end.

Feel free to open a PR to clear this up, I'll close the issue as you are the first person in 1+ year who notices this, so it's unlikely a popular problem. 😅
