### ISSUE TITLE
getSession dont return me custom things in payload

### ISSUE THREAD

**Issue by DETLIXX** [nextauthjs/next-auth#8035]
### Question 💬

Hello, in callback (this photo down there) i am setting apiKey, and id to jwt.

![image](https://github.com/nextauthjs/next-auth/assets/43766321/b7dde431-6b88-422a-ab7e-b0e9eaa647ce)
When i am using useSession on Client Side, it show me everything in log, but i need to know user apiKey in middleware, so i need to get that from that jwt somehow. 

![image](https://github.com/nextauthjs/next-auth/assets/43766321/5a5f1b03-a441-46d5-8faf-d86be18693e4)

Thanks 

### How to reproduce ☕️

Up there is screen

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Check out https://next-auth.js.org/configuration/nextjs#middleware

Note, database sessions (eg when using an adapter by default) is not supported in Middleware currently.

**Comment by DETLIXX** [comment]
What ? i am asking about getting all data from JWT 

This is what i get when i call useSession() and this is what i want
![Screenshot 2023-07-14 at 12 03 34](https://github.com/nextauthjs/next-auth/assets/43766321/3336c092-07b5-4909-9c92-efafbecd887f)

And this is what i get from getToken, i dont uderstant it, its not same token ? or what ? because i want all that data from useSession, but in some way like getToken 
<img width="916" alt="Screenshot 2023-07-14 at 12 05 08" src="https://github.com/nextauthjs/next-auth/assets/43766321/bcd2ada3-777f-4b55-818e-1f9aec8970cd">
