### ISSUE TITLE
next-auth CredentialsProvider for Next.js 13.4 not working with external backend

### ISSUE THREAD

**Issue by SphrGhfri** [nextauthjs/next-auth#8041]
### Environment

System:
    OS: Windows 10 10.0.22000
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 3.35 GB / 15.94 GB
  Binaries:
    Node: 16.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 114.0.5735.199
    Edge: Spartan (44.22000.120.0), Chromium (114.0.1823.82)
    Internet Explorer: 11.0.22000.120

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

I have a project that uses an external backend for authentication. After a successful login, cookies are sent back. On the signIn page, I used 'use client.' It worked fine when I was using Next.js version 13.2, and the cookies were set correctly.

In the Next project, the route of the next-auth file is located at :
`\pages\api\auth\[...nextauth].js`

here is code i used:

```
import NextAuth from 'next-auth'
import CredentialsProvider from 'next-auth/providers/credentials'

import { postAuthLogin } from '@/lib/requests/auth'

export const options = (req, res) => {
  return {
    providers: [
      CredentialsProvider({
        // The name to display on the sign in form (e.g. 'Sign in with...')
        name: 'credentials',
        // The credentials property is used to generate a suitable form on the sign in page.
        credentials: {
          username: { label: "Username", type: "text", placeholder: "jsmith", value: "" },
          password: { label: "Password", type: "password", value: "" }
        },
        async authorize(credentials) {
          try {
            const login_resp = await postAuthLogin(
              {
                "email": credentials.username,
                "password": credentials.password
              });


            const user = login_resp.data.user;

            const cookies = login_resp.headers['set-cookie']

            res.setHeader('Set-Cookie', cookies)
            
            return user;

          } catch (e) {
            throw new Error(e?.response?.data?.detail || "There was an error on user authentication");
          }
        }
      })
    ],
    pages: {
      signIn: '/signin',
      error: '/error', 
    },
    callbacks: {
      async signIn({ user, account, profile, email, credentials }) {
        return true
      },
      async redirect({ url, baseUrl }) {
        return Promise.resolve(baseUrl)
      }
    },

  }
}

const nextAuth = (req, res) => {
  return NextAuth(req, res, options(req, res))
}

export default nextAuth
```

When I updated Next.js to version 13.4.10, I encountered an error: "setHeader is not a function."

### How to reproduce

To make next-auth work in Next.js 13.4, I created a next-auth file in the following route:
`\app\api\auth\[...nextauth]\route.js `

However, I encountered an error stating "setHeader is not a function." In response to this error, I made the following code changes:

```
import axios from "axios";
import NextAuth from "next-auth";

import CredentialsProvider from "next-auth/providers/credentials";
import { NextResponse } from "next/server";


export const next_options = (req, res) => {
    return {
        providers: [
            CredentialsProvider({
                name: 'Credentials',
                credentials: {
                    username: { label: "Username", type: "text", placeholder: "jsmith", value: "" },
                    password: { label: "Password", type: "password", value: "" }
                },
                async authorize(credentials) {
                    try {
                        const login_resp = await postAuthLogin(
                            {
                                "email": credentials.username,
                                "password": credentials.password
                            });

                        const user = login_resp.data.user;

                        const backend_cookies = login_resp.headers['set-cookie']


                        
                        const newHeaders = new Headers(req.headers)
                        newHeaders.append('Set-Cookie', backend_cookies)


                        const response =  NextResponse.next({
                            request: {
                              // New request headers
                              headers: newHeaders,
                            },
                          });


                        const a = newHeaders.get('Set-Cookie')
                        console.log("NewHeader", a)
                        
                        return user;

                    } catch (e) {

                        console.log('Error', e, e?.response?.data)
                        throw new Error(e?.response?.data?.detail || "There was an error on user authentication");
                    }
                }
            })
        ],
        pages: {
        },
        callbacks: {
            async signIn({ user, account, profile, email, credentials }) {
                return true
            },
            async redirect({ url, baseUrl }) {
                return Promise.resolve(baseUrl)
            }
        },
    }
}

export { nextAuth as GET, nextAuth as POST };

export const postAuthLogin = async (body) => {
    const res = await axios.post("http://localhost:8001/auth/login", body, {
        withCredentials: true,
    })
    return res
}

const nextAuth = (req, res) => {
    return NextAuth(req, res, next_options(req, res))
}
```

I didn't receive any errors, but the cookies haven't been set.

### Expected behavior

I want to ensure that authenticated user requests include the 'Set-Cookie' header that I've set. Upon inspecting the browser's developer tools in the "Application" tab, specifically the "Cookies" section, I can confirm that the cookies are visible. Furthermore, all secured endpoints of the external backend successfully receive these cookies. It's important to note that the backend has been thoroughly tested and is functioning properly, specifically with the code provided earlier in Next.js 13.2.

**Comment by milukukoz** [comment]
+1 same issue, thank you for the question

**Comment by balazsorban44** [comment]
Please see my answer here https://github.com/vercel/next.js/issues/52701#issuecomment-1636723107

**Comment by SphrGhfri** [comment]
@balazsorban44 
The link you provided is not the answer to the problem. The problem lies in integrating the new Next.js documentation for setting headers (as you mentioned) and the way CredentialsProvider works.), and it is as follows:
```
import { cookies } from 'next/headers'
 
export async function GET(request: Request) {
  const cookieStore = cookies()
  const token = cookieStore.get('token')
 
  return new Response('Hello, Next.js!', {
    status: 200,
    headers: { 'Set-Cookie': `token=${token.value}` },
  })
}
```
The CredentialsProvider in next-auth needs to return the user as the return of CredentialsProvider function. On the other hand, the method of setting headers in the app Router (mentioned above) also needs to be in return of function; otherwise, the header won't be set in CredentialsProvider function. I tried using other methods in CredentialsProvider function to set headers, like:
```
const newHeaders = new Headers(req.headers)
newHeaders.append('Set-Cookie', backend_cookies)

```
or
```
const response =  NextResponse.next({
    request: {
      // New request headers
      headers: newHeaders,
    },
  });

```
But it didn't work.

How can I combine these two returns into one function in order to set new headers in CredentialsProvider ?
