### ISSUE TITLE
Custom IDP callback to support Cognito + Vercel Previews

### ISSUE THREAD

**Issue by ankrgyl** [nextauthjs/next-auth#8043]
### Question 💬

I'm hoping to support logging into my Vercel previews, but Amazon Cognito does not support wildcard callbacks.

Is there a workaround that enables you to redirect to some common URL and forward along the token to the original (preview) URL? I see some references to custom callbacks/redirects but these do not seem to be the actual redirect URL (which appears to be hardcoded to `/api/auth/callback/cognito`.

### How to reproduce ☕️

Use `CognitoProvider` + vercel preview links

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
This is going to be supported in the upcoming major release. Check out #7443 if you want to test it out.
