### ISSUE TITLE
Cannot read session while debugging on VS code.

### ISSUE THREAD

**Issue by juancavallotti** [nextauthjs/next-auth#8048]
### Environment

  System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 65.39 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.4.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1

### Reproduction URL

https://github.com/you_have_it_down_there

### Describe the issue

Whenever I try to use ``getServerSession()`` on a page route using the App Router (it works okay in API routes and the pages router) and the debugger is attached on VS code, I get the following error.

```error Error: Invariant: Method expects to have requestAsyncStorage, none available```

Sample code to reproduce:
```javascript
import { authOptions } from "@/pages/api/auth/options";
import { getServerSession } from "next-auth";

export default async function Home() {

  const session = await getServerSession(authOptions);
  
  const isLoggedIn = (session?.user?.email) != null;

  return (
    <main>
        <div>Am I in? {isLoggedIn}</div>
    </main>
  );
}
```

If I detach the debugger using this button, it works as expected.
<img width="217" alt="image" src="https://github.com/nextauthjs/next-auth/assets/1139592/a7472146-d5da-4272-87ad-684837e13968">

### How to reproduce

* Create a page that uses the server session using the app router.
* run `npm run dev` within VS code to attach the debugger.
* Open the browser to navigate to the page.

### Expected behavior

It, of course, should work with or without a debugger attached.

**Comment by chrxmvtik** [comment]
Bumping this, besides that I am also getting error in the console as

```
[next-auth][error][CLIENT_FETCH_ERROR]   
https://next-auth.js.org/errors#client_fetch_error undefined {
  error: {},
  url: 'http://localhost:3000/api/auth/session',
  message: undefined
}
```

but when I actually visit http://localhost:3000/api/auth/session I recieve this

```
{"user":{"email":"xxx@gmail.com","role":"ADMIN"},"expires":"2023-08-14T23:40:07.501Z"}
```

Pretty weird, because it worked all the time before and recently stopped working.

``
next-auth: 4.22.1
``
