### ISSUE TITLE
Unable to use middleware.ts with app directory.

### ISSUE THREAD

**Issue by naeem-qv** [nextauthjs/next-auth#8060]
### Environment

   "next": "13.1.6",
    "next-auth": "^4.22.1",
    "react": "18.2.0",
    "react-dom": "18.2.0"

OS: Windows 10
tested browsers: Microsoft edge, firefox, waterfox, chrome

### Reproduction URL

/

### Describe the issue

I tried using the simplest example of middleware.ts with the app directory placing middleware.ts at the root / of the project like we used to do before the app directory. it is working fine as it has to do but I'm seeing this warning in my terminal:

`
/middleware.ts
export { default } from "next-auth/middleware"

export const config = {matcher:["/dashboard"],}`

Error:
`warn  - Statically exporting a Next.js application via `next export` disables API routes and middleware.
This command is meant for static-only hosts, and is not necessary to make your application static.
Pages in your application without server-side data dependencies will be automatically statically exported by `next build`, including pages powered by 
`getStaticProps`.
Learn more: https://nextjs.org/docs/messages/api-routes-static-export`

and placing middleware.ts into app directory like app/middleware.ts does not do anything. yes, the warning is gone so is the purpose of middleware.ts . Now I can see /dashboard without logging in...
please resolve this issue.

### How to reproduce

just create a middleware.ts file at the root level of the project.

### Expected behavior

It does not have to give warning which comes from `next export` command.

**Comment by balazsorban44** [comment]
This is not related to `next-auth` or the App Router specifically.

The export mode of Next.js does not support Middleware as documented: https://nextjs.org/docs/pages/building-your-application/deploying/static-exports#unsupported-features
