### ISSUE TITLE
Missing Nodemailer option types

### ISSUE THREAD

**Issue by gamedevsam** [nextauthjs/next-auth#807]
**Summary of proposed feature**
When using typescript we cannot set all node mailer options without resorting to typecasting to any.

**Purpose of proposed feature**
Enable setting other node mailer options like `secure`, `authMethod`, `tls` options, etc.

**Detail about proposed feature**
Either add secure type, or better yet, extend the `ProviderEmailServer` type to extend `SMTPConnection.Options type`:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/623f3889f0fac1ed3284066f990cebf3d86d1d64/types/nodemailer/lib/smtp-connection/index.d.ts#L131

**Potential problems**
N/A

**Describe any alternatives you've considered**
I casted the `server` field to `any`. A suboptimal solution.

**Additional context**
Any other context, screenshots, etc.
![image](https://user-images.githubusercontent.com/420996/97512896-1af94d00-1961-11eb-8a81-ccac7083efe4.png)

*Please indicate if you are willing and able to help implement the proposed feature.*
Probably, if time allows.

**Comment by iaincollins** [comment]
This sounds like a good issue for the DefinitelyTyped repo, where TypeScript definitions for NextAuth.js currently live:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/next-auth/providers.d.ts
