### ISSUE TITLE
How do I integrate Azure Active Directory roles into a Next Auth application?

### ISSUE THREAD

**Issue by andrewbanonis** [nextauthjs/next-auth#8070]
### Question 💬

We are building an internal company application and want to use Azure AD for SSO into the application. There's two parts of the application:

1. The normal dashboard that everyone can access
2. An admin page that allows supervisors to change things

How do we use retrieve roles setup in Azure AD and read it within our application? Only certain pages will need to be restricted to the roles. I was unable to find any documentation on Azure AD roles within Next Auth.

### How to reproduce ☕️

N/a

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by TheMagoo73** [comment]
It may not be pretty - I literally just hacked it into existance, but this is the config I'm using.

```javascript
export const authConfig = {
  session: {
    strategy: "jwt"
  },
  providers: [
    AzureADProvider({
      clientId: process.env.AAD_APP_ID,
      clientSecret: process.env.AAD_CLIENT_SECRET,
      tenantId: process.env.AAD_TENANT_ID,
    })
  ],
  callbacks: {
    jwt: async ({token, account}) => {
      console.log(`Token: ${account}`)
      console.log(`Account: ${account}`)

      if(account?.id_token) {
        const [header, payload, sig] = account.id_token.split('.')
        const idToken = JSON.parse(Buffer.from(payload, 'base64').toString('utf8'))
  
        token.roles = [...idToken.roles]
      }

      return token
    },
    session: async ({ session, token }) => {
      session.roles = [...token.roles]

      return session
    }
  }
}
```

In the AAD App Registration I set the ID Token to be sent in both available flow types.

HTH!

**Comment by andrewbanonis** [comment]
@TheMagoo73 Thank you so much!

Could you share your Azure app registration config just so I can confirm ours is the same?

Also, could you verify that I am checking for roles properly with the following code?

```
"use client";
import { useSession } from "next-auth/react"

export default function Test() {
  const { data: session, status } = useSession()

  if (session?.user.roles === "admin") {
    return <p>You are an admin, welcome!</p>
  }

  return <p>You are not authorized to view this page!</p>
}
```

Thanks once again!

**Comment by andrewbanonis** [comment]
Thanks for the help!

So rather than this code working:

```"use client";
import { useSession } from "next-auth/react"

export default function Test() {
  const { data: session, status } = useSession()

  if (session?.roles === "admin") {
    return <p>You are an admin, welcome!</p>
  }

  return <p>You are not authorized to view this page!</p>
}
```

...this works:

```
"use server";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]";

export default async function Test() {
  const session = await getServerSession(authOptions)

  if (session?.roles.includes("admin")) {
    return <p>You are an admin, welcome!</p>
  }

  return <p>You are not authorized to view this page!</p>
}
```

`if (session?.user.roles === "admin")` should be replaced to ` if (session?.roles.includes("admin"))`.

**Comment by balazsorban44** [comment]
https://authjs.dev/guides/basics/role-based-access-control
