### ISSUE TITLE
Error handling with Google authentication coming from the backend

### ISSUE THREAD

**Issue by rokas-bendikas** [nextauthjs/next-auth#8073]
### Question 💬

Hi, I have a custom google authentication system implemented, where I obtain the tokens on the frontend, send them to the backend, where the user is authenticated and added to the database. The backend returns my custom access_token that is used to query the backend API. However, I am a little confussed about the handling the error in next-auth. When my backend returns an error I try to throw it in the next-auth, however on the client I get redirected to: signin?error= Callback and I have no idea how to obtain the error message.

### How to reproduce ☕️

[...nextauth].tsx:

    async jwt({ token, user, account, profile, trigger, session }) {
      // If update() is called, the token is updated
      if (trigger === 'update' && session) {
        token = { ...token, ...session };
      }

      // After signin, the user object is serialized to JSON and stored
      if (user) {
        // If the user is signing in with credentials
        if (account && account.provider === 'credentials') {
          const { accessToken, refreshToken, ...partialUser } = user;
          token = {
            user: partialUser,
            accessToken,
            refreshToken,
          };
        }
        // If the user is signing in with Google
        else if (account && account.provider === 'google') {
          // Get the Google access and id tokens
          const { access_token: accessTokenGoogle, id_token: idTokenGoogle } =
            account;

          // Throw an error if the tokens are not present
          if (!accessTokenGoogle || !idTokenGoogle) {
            throw new Error('Google login failed');
          }
          try {
            // Get the access and refresh tokens from the backend
            const { accessToken, refreshToken } = await loginGoogleBackend(
              idTokenGoogle,
              accessTokenGoogle
            );
            // Get the user from the backend
            const user = await getUser(accessToken);
            // Form a token object
            token = {
              user,
              accessToken,
              refreshToken,
            };
          } catch (error: any) {
            console.log(error);
            throw error;
          }
        }
      }

      // Check if the token is expired
      else if (checkIfTokenExpired(token.accessToken)) {
        console.log('Refreshing token...');
        try {
          const [accessToken, refreshToken] = await getNewTokens(
            token.refreshToken
          );
          token = { ...token, accessToken, refreshToken };
        } catch (err: any) {
          console.error(err);
          throw new Error(err);
        }
      }
      return token;
    },

    export async function loginGoogleBackend(
      idTokenGoogle: string,
      accessTokenGoogle: string
    ) {
      try {
        const response = await axios.post(
          process.env.BACKEND_API + '/auth/google/',
          {
            access_token: idTokenGoogle,
            id_token: accessTokenGoogle,
          }
        );
        const { access_token: accessToken, refresh_token: refreshToken } =
          response.data;
        return { accessToken, refreshToken };
      } catch (err: any) {
        console.error(err.response.data);
        throw new Error(JSON.stringify(err.response.data));
      }
    }

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by calebpitan** [comment]
Hi, did you figure this out?

**Comment by PauloMello99** [comment]
@rokas-bendikas Did you get any solution for your scenario? I find myself in the same situation and I still don't know how to define the error

**Comment by PrabeenGautam** [comment]
> @rokas-bendikas Did you get any solution for your scenario? I find myself in the same situation and I still don't know how to define the error

Did you solve this?

**Comment by RonnenPodolsky** [comment]
Any suggestions?
