### ISSUE TITLE
Type '"oidc"' is not assignable to type '"oauth" | "email" | "credentials

### ISSUE THREAD

**Issue by kjetilge** [nextauthjs/next-auth#8082]
### Provider type

Custom provider

### Environment

  System:
    OS: macOS 13.4.1
    CPU: (10) x64 Apple M1 Max
    Memory: 10.25 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.4.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.7.2 - /usr/local/bin/npm
    pnpm: 8.6.7 - ~/.nvm/versions/node/v19.9.0/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.2

### Reproduction URL

https://github.com/kjetilge/cred-and-oauth-login/tree/dev

### Describe the issue

In the documentation found here: [https://authjs.dev/guides/providers/custom-provider](url) it says to use type: "oidc" when using a fully OIDC-compliant provider like so:

```
import type { OIDCConfig } from "@auth/core/providers"

providers: [
  {
    id: "my-oidc-provider",
    name: "My Provider",
    type: "oidc",
    issuer: "https://my.oidc-provider.com",
    clientId: process.env.CLIENT_ID,
    clientSecret: process.env.CLIENT_SECRET
  } satisfies OIDCConfig
]
```

However, when I try this in my own code I get a type error:
```
import type { NextAuthOptions } from 'next-auth'
import CredentialsProvider from 'next-auth/providers/credentials'
import type { OIDCConfig } from "@auth/core/providers"

const FEIDE_API_BASE_URL = 'https://auth.dataporten.no';


export const options: NextAuthOptions = {
    providers: [
        {
          id: "feide",
          name: "Feide",
          type: "oidc",
          issuer: "https://auth.dataporten.no",
          clientId: process.env.FEIDE_ID,
          clientSecret: process.env.FEIDE_SECRET,
        }
      ]
}


```

The error reads: Type '"oidc"' is not assignable to type '"oauth" | "email" | "credentials"'.ts(2322)

### How to reproduce

Clone this repo and have a look at the file: src/api/auth/[...nextauth]/options

In this file you can se the code above and if opened in vs code you will see the type error.

### Expected behavior

There should be no type error.

**Comment by ThangHuuVu** [comment]
hey @kjetilge for the `oidc` type please use the `next-auth@v5` or `experimental`. You can get it by running `npm i next-auth@experimental` which should give you the correct type.

**Comment by kjetilge** [comment]
Hi! Me again.

Should I also use experimental for HTTP-based Email Provider ? In the following code I get a type error for type:'email'
```
export const authOptions: NextAuthOptions = {
  adapter: PrismaAdapter(prisma),
  providers: [
    {
      id: 'sendgrid',
      type: 'email',
      async sendVerificationRequest({identifier: email, url}) {
      }
    }
  ],
}
```

This happens when using version 4 but not in experimental. However, I can se from the source code that middleware is removed in experimental, and I don't know what to substitute it with.

What is the most appropriate version to use if I want to use both a custom oidc and HTTP-based Email provider  ?

**Comment by huotarih** [comment]
I have the same question as above. Just added a few providers but obviously can't leave out email link login, that's just basic stuff. @ThangHuuVu any ideas? Also we need some example on how to do custom login pages with nextjs app router and v5.

**Comment by tomatac** [comment]
I have the same issue.
