### ISSUE TITLE
Next js cookies has method set

### ISSUE THREAD

**Issue by eposha** [nextauthjs/next-auth#8094]
### What is the improvement or update you wish to see?

The documentation says that 

<img width="971" alt="image" src="https://github.com/nextauthjs/next-auth/assets/54452472/d5e6bc50-4219-4713-8cfc-e217ab454efd">

But this is not the case anymore, does this mean that the expires value will now work as expected and the user will not be required to sign in again?

### Is there any context that might help us understand?

https://nextjs.org/docs/app/api-reference/functions/cookies#cookiessetname-value-options

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/configuration/nextjs

**Comment by balazsorban44** [comment]
No, this still stands. Cookies can only be updated from Route Handlers, Server Actions, or Middleware.

In the next version of next-auth, we will be using Middleware to achieve this. You can try it out by following #7443
