### ISSUE TITLE
Problems With Prisma Adapter

### ISSUE THREAD

**Issue by Pedromdsn** [nextauthjs/next-auth#8103]
### Adapter type

@auth/prisma-adapter

### Environment

  System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 5600 6-Core Processor
    Memory: 9.52 GB / 15.57 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.16.0 - /run/user/1000/fnm_multishells/34002_1689966799066/bin/node
    Yarn: 1.22.19 - /run/user/1000/fnm_multishells/34002_1689966799066/bin/yarn
    npm: 9.5.1 - /run/user/1000/fnm_multishells/34002_1689966799066/bin/npm

  npmPackages:
    @next-auth/prisma-adapter: ^0.4.4-canary.81 => 0.4.4-canary.81+0d39d43 

### Reproduction URL

Nome

### Describe the issue

With the adapter it gives this error, and the authentication stops working, without this it works without problems.

```
- event compiled client and server successfully in 2.3s (775 modules)
[next-auth][warn][EXPERIMENTAL_API] 
`getServerSession` is used in a React Server Component. 
https://next-auth.js.org/configuration/nextjs#getServerSession} 
https://next-auth.js.org/warnings#EXPERIMENTAL_API
[next-auth][warn][NEXTAUTH_URL] 
https://next-auth.js.org/warnings#nextauth_url
[next-auth][error][SESSION_ERROR] 
https://next-auth.js.org/errors#session_error getSessionAndUser is not a function {
  message: 'getSessionAndUser is not a function',
  stack: 'TypeError: getSessionAndUser is not a function\n' +
    '    at Object.session (webpack-internal:///(sc_server)/./node_modules/next-auth/core/routes/session.js:71:40)\n' +
    '    at AuthHandler (webpack-internal:///(sc_server)/./node_modules/next-auth/core/index.js:161:50)\n' +
    '    at async getServerSession (webpack-internal:///(sc_server)/./node_modules/next-auth/next/index.js:129:21)\n' +
    '    at async Home (webpack-internal:///(sc_server)/./src/app/page.tsx:26:21)',
  name: 'TypeError'
}
[next-auth][error][SESSION_ERROR] 
https://next-auth.js.org/errors#session_error getSessionAndUser is not a function {
  message: 'getSessionAndUser is not a function',
  stack: 'TypeError: getSessionAndUser is not a function\n' +
    '    at Object.session (webpack-internal:///(sc_server)/./node_modules/next-auth/core/routes/session.js:71:40)\n' +
    '    at AuthHandler (webpack-internal:///(sc_server)/./node_modules/next-auth/core/index.js:161:50)\n' +
    '    at async getServerSession (webpack-internal:///(sc_server)/./node_modules/next-auth/next/index.js:129:21)\n' +
    '    at async RootLayout (webpack-internal:///(sc_server)/./src/app/layout.tsx:20:21)',
  name: 'TypeError'
}
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: invalid distance code
null
```

### How to reproduce

Just add the prism adapter as instructed in the tutorial: https://authjs.dev/reference/adapter/prisma

![image](https://github.com/nextauthjs/next-auth/assets/57453260/be2059e8-396a-4d87-952a-260701622a81)

### Expected behavior

Login normally.

**Comment by balazsorban44** [comment]
You are using a very old version of the adapter, please upgrade. if you stil have problems then, please open a new issue and don't skip the reproduction url step. we cannot help without seeing your code.
