### ISSUE TITLE
getSession not working

### ISSUE THREAD

**Issue by oojoseph67** [nextauthjs/next-auth#8110]
### Environment

```
[next-auth][error][CLIENT_FETCH_ERROR]
https://next-auth.js.org/errors#client_fetch_error undefined {
  error: {},
  url: 'http://localhost:3000/api/auth/session',
  message: undefined
}
```

I get this error when I try calling getSession in the backend of my code 

### Reproduction URL

https://github.com/oojoseph67/iMessage_clone

### Describe the issue

When I make a request from the front end, I also want to get the user session details so I can make changes to the database but for some reasons I can’t

### How to reproduce

Run the front end and also the backend, connect a google account and try inputing a name in the field that shows, then check your server terminal for update 

### Expected behavior

The getSession should return the user logged in

**Comment by balazsorban44** [comment]
Check out `getServerSession` instead, which also, has a much better performance https://next-auth.js.org/configuration/nextjs#getserversession
