### ISSUE TITLE
Custom provider with "plain" code_challenge_method

### ISSUE THREAD

**Issue by Neo-Ciber94** [nextauthjs/next-auth#8116]
### Question 💬

Currently code_challenge_method `plain` is not supported as read in the discussion https://github.com/nextauthjs/next-auth/discussions/4459

But I want to implement my own with that requeriment, but I can't think information about in the docs: [Adding a new provider](https://next-auth.js.org/v3/configuration/providers#adding-a-new-provider)

Any guide I could use to create a custom provider with "plain" code_challenge_method?

**Comment by ThangHuuVu** [comment]
hi @Neo-Ciber94 you can maintain your own fork and change the code_challenge_method to `plain` here: https://github.com/search?q=repo%3Anextauthjs%2Fnext-auth%20code_challenge_method&type=code

After that, you can add your custom provider and use it. Let me know if this help
