### ISSUE TITLE
Component tab of React Devtools becomes empty after successful signin .

### ISSUE THREAD

**Issue by mohdsauood** [nextauthjs/next-auth#812]
**Describe the bug**
- Component tab of React devtools becomes empty after signing in . No contexts or  state is visible .
-  After signingout everything goes back to normal .
- This only happens in chrome . Firefox works fine .

**Steps to reproduce**
- clone the official [next auth js example](https://github.com/nextauthjs/next-auth-example)
- add google client and secret key
- open dev tools -> component tab
- signin using google account
- component tab becomes empty

Link to public repository which can be used to reproduce the behaviour.
https://github.com/nextauthjs/next-auth-example

**Expected behavior**
After successful login i wanted the components tab to not become empty and function normally , so i can inspect session data in my state .

**Additional context**
i'm only using google provider here .

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
Thanks for the bug report!

This doesn't sound like an issue with NextAuth.js, rather with the React Dev Tools browser extension.

There is an open issue that seems to relate to it here.
https://github.com/facebook/react/issues/16495
