### ISSUE TITLE
Types of NextAuth are not up to date for Route Handlers

### ISSUE THREAD

**Issue by yarinsa** [nextauthjs/next-auth#8120]
### Question 💬

I am migrating my next-auth to the route handlers. It seems like they accept type of "NextApiRequest" but we have "NextRequest" in the route handler. Functionality wise it works perfecet, like the [docs declare ](https://next-auth.js.org/configuration/initialization#advanced-initialization). 
It's only a typescript error, I would expect NextAuth to accept `request: NextRequest | NextApiRequest` since the internal logic does a type check. 

I am willing to contribute this change if one of the maintainers here will agree with that change :) 

### How to reproduce ☕️

![Screenshot 2023-07-23 at 13 19 00](https://github.com/nextauthjs/next-auth/assets/44482362/435ad42f-3043-4f88-b4dd-0ea39e5aa04b)

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Looks like you are correct. awe are missing an overload function here

https://github.com/nextauthjs/next-auth/blob/465644f9e489321bffce6289234957c8e4bd6d2e/packages/next-auth/src/next/index.ts#L110

Can you open a PR against the v4 branch? Thanks!

**Comment by ThangHuuVu** [comment]
Should be fixed via #8236
