### ISSUE TITLE
SvelteKit: Using handle is not complete solution to authz - it only triggers for ssr

### ISSUE THREAD

**Issue by symbolicsorcerer** [nextauthjs/next-auth#8121]
### What is the improvement or update you wish to see?

According to https://github.com/sveltejs/kit/issues/3897#issuecomment-1039317946 and lived experience, we can't rely on just the `hooks.server.ts` handler to authorize requests to a SvelteKit app.

I'm not sure what should be the proper approach, but maybe we can iron it out here and update the docs. In the interim we might want to update the docs to warn folks that there's something missing.

### Is there any context that might help us understand?

https://github.com/sveltejs/kit/issues/3897#issuecomment-1039317946

### Does the docs page already exist? Please link to it.

https://authjs.dev/reference/sveltekit

**Comment by rbozan** [comment]
Can't we call the invalidate function of Svelte?

https://learn.svelte.dev/tutorial/invalidation

**Comment by rbozan** [comment]
Can be fixed by adding `data-sveltekit-reload` as an attribute to a `<a>` tag which goes to sign in / sign out API pages.

**Comment by ndom91** [comment]
We recently shipped a new docs site and hopefully made this more clear!

Check out https://authjs.dev/getting-started/session-management

Basically on [SvelteKit's "implications for authentication"](https://kit.svelte.dev/docs/load#implications-for-authentication) section, we also recommended checking the session separately in each `+page.server.ts`, for example.
