### ISSUE TITLE
Unable to get accessToken after signin('google')

### ISSUE THREAD

**Issue by deep-vaibhav** [nextauthjs/next-auth#8124]
### Question 💬

After configuring NextAuth options with Google OAuth provider (with an additional scope), getToken() for even getServerSession() on the callback route always returns null. 

### How to reproduce ☕️

Setup [...nextauth].ts as follows - 
```export const authOptions = {
  providers: [
    GoogleProvider({
      clientId: getGoogleCredentials().clientId,
      clientSecret: getGoogleCredentials().clientSecret,
      authorization: {
        params: {
          prompt: "consent",
          access_type: "offline",
          response_type: "code",
          scope: "https://www.googleapis.com/auth/gmail.readonly",
        },
      },
    }),
  ],
  callbacks: {
    async session({ session, token }: any) {
      return {
        ...session,
        ...token
      }
    },
    async jwt({ token, account, user }: any) {
      if (account && user) {
        token.accessToken = account.access_token;
        token.refreshToken = account.refresh_token;
        token.user = user;
      }
      return token;
    },
  },
};

export default NextAuth(authOptions);
```

PS: Add an additional scope of `gmail.readonly`.

In the callback route  (api/auth/callback/google), use `getToken()` or `getServerSession()` to get the access token returned by this OAuth request.

```
const auth = await getToken({
      req,
      secret: process.env.NEXTAUTH_SECRET,
      raw: true,
    });
console.log({ auth });
```

To my surprise, the value of `auth` is always null. I believe I'm missing something here. Do I need to do additional configuration here or on the Google console? 

I've been stuck on this for quite some time, any help is much appreciated. 

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by wa12rior** [comment]
Have you tried signIn callback? It should be in an account param.

**Comment by deep-vaibhav** [comment]
@wa12rior Haven't tried this callback. Can you provide a full example that worked for you?

**Comment by deep-vaibhav** [comment]
Don't know why but the same `getToken()` works in a `getServerSideProps()` but on the callback route `api/auth/callback/google`. Any idea why?

**Comment by balazsorban44** [comment]
@deep-vaibhav That endpoint is controlled by NextAuth.js and is unlikely you want to override it, unless you know what you are doing.

See the docs for the suggested callback here: https://next-auth.js.org/configuration/callbacks#sign-in-callback

**Comment by deep-vaibhav** [comment]
@balazsorban44 I understand that endpoint is controlled by NextAuth.js. But if not that, how to I get access token on the server side callback?
