### ISSUE TITLE
HTTP-based email provider: type `"email"` is not assignable to type `"oauth" | "credentials"`

### ISSUE THREAD

**Issue by mcevoypeter** [nextauthjs/next-auth#8125]
### Provider type

Email

### Environment

System:
    OS: Linux 6.4 Arch Linux
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 26.16 GB / 31.06 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.4.0 - /usr/bin/node
    Yarn: 3.3.0 - /usr/bin/yarn
    npm: 9.8.1 - /usr/bin/npm
    pnpm: 8.6.10 - /usr/bin/pnpm

### Reproduction URL

https://github.com/mcevoypeter/next-auth-issue-repro

### Describe the issue

I'm attempting to configure an HTTP-based email provider following the [guide from the docs](https://authjs.dev/guides/providers/email-http). When I add a stubbed-out provider object to the `providers` object key, I get the following error when running `npm run build`:
```console
> build
> next build

- info Linting and checking validity of types ...Failed to compile.

./pages/api/auth/[...nextauth].ts:35:5
Type error: Type '{ id: string; type: "email"; sendVerificationRequest({ identifier: email, url }: { identifier: any; url: any; }): Promise<void>; }' is not assignable to type 'Provider'.
  Types of property 'type' are incompatible.
    Type '"email"' is not assignable to type '"oauth" | "credentials"'.

  33 |       version: "2.0",
  34 |     }),
> 35 |     {
     |     ^
  36 |       id: 'mailgun',
  37 |       type: 'email',
  38 |       async sendVerificationRequest({identifier: email, url}) {
```

### How to reproduce

1. `git clone https://github.com/mcevoypeter/next-auth-issue-repro`
2. `cd next-auth-issue-repro`
3. `npm install`
4. `npm run build`

### Expected behavior

I expect `npm run build` to cleanly compile.

**Comment by balazsorban44** [comment]
The code itself looks fine, it's just the types that are incorrect.

**Comment by mcevoypeter** [comment]
I was able to get the code to typecheck by adding the `name`, `server`, and `options` keys:
```typescript
{
  id: 'mailgun',
  type: 'email',
  name: 'Email',
  server: null,
  options: {},
  async sendVerificationRequest({identifier: email, url}) {
    // <snip>
  }
}
```

**Comment by mcevoypeter** [comment]
Actually, the code snippet above only typechecks if I use a local version of `next-auth`. Not sure if it's a red herring or not.

The following fails to typecheck:
```console
rm -rf node_modules
yarn add next-auth       # ^4.22.3 in package.json
yarn run build
```
The error it produces:
```console
Type error: Type '{ id: string; type: "email"; name: string; server: null; options: {}; sendVerificationRequest({ identifier: email, url }: { identifier: any; url: any; }): Promise<void>; }' is not assignable to type 'Provider'.
  Types of property 'type' are incompatible.
    Type '"email"' is not assignable to type '"oauth" | "credentials"'.
```

The following typechecks:
```console
rm -rf node_modules
yarn remove next-auth
yarn add path/to/next-auth/packages/next-auth     # the repo is checked out to next-auth@4.22.3
yarn run build
```

**Comment by ken-muturi** [comment]
has this been fixed ? am also having issues
![image](https://github.com/nextauthjs/next-auth/assets/3158605/752d6731-b967-4722-8e3d-e14016ad487a)

**Comment by itsalam** [comment]
Seems to be broken from this change here: 
https://github.com/nextauthjs/next-auth/commit/1e886b97bcd76b0679a00d6d03e9cc0a68ca9407

While this can be easily fixed by allowing the `EmailConfig.server` field to be optional again, that seems to null the changes made. 

Looking through the `next-auth` code, it seems like the intended fix should be:
```
...
import Email from "next-auth/providers/email"
...

    // {
    //   id: 'mailgun',
    //   type: 'email',
    //   async sendVerificationRequest({identifier: email, url}) {
    //     console.log(email)
    //   }
    // },
    Email({
      type: 'email',
      async sendVerificationRequest({identifier: email, url}) {
        console.log(email)
      }
    }),
  ],
```

It seems the current Email provider doesn't allow overwriting the id field however, which seems problematic. 

Can you chime in on what changes should happen @balazsorban44?

**Comment by KingXP-Pythoner** [comment]
Really need a fix for this, having the same issue

**Comment by wahidrahim** [comment]
Strange, I have to add whole bunch of other properties, to effectively only use the `sendVerificationRequest` method

```ts
providers: [
    {
      id: 'email',
      type: 'email',
      from: 'asdf@asdf.ca',
      server: {},
      maxAge: 24 * 60 * 60,
      name: 'Email',
      options: {},
      sendVerificationRequest: (params) => {
        console.log({ params });
      },
    },
  ],
```

The other option seems to be use to he EmailProvider from `next-auth/providers/email` but that requires installing `nodemailer`, which is not necessary at all for my needs; I am using a separate service for sending emails to users.

Is this a TS definitions issue, or something perhaps can we just use EmailProvider, but without requiring `nodemailer` somehow (this seems best)?

**Comment by lnikell** [comment]
Getting same error too. Hack by @wahidrahim worked fine.

**Comment by MattRey** [comment]
Still getting this type error with a new install of next/next-auth using T3:
```
Types of property 'type' are incompatible.
    Type '"email"' is not assignable to type '"oauth" | "credentials"'.
```
Workaround above doesn't work for me 🤨 - any ideas? 🙏

**Comment by basememara** [comment]
Why is the `id` and `name` hardcoded in the `EmailConfig` type? I'm stuck on `4.22.1` because I have multiple email providers that do different things:

```ts
const authOptions = {
    ...,
    providers: [
      GoogleProvider({...}),
      EmailProvider({
        server: smtp1,
        sendVerificationRequest: async ({ identifier: email, url, provider: { server, from } }) => {...}
      }),
      EmailProvider({
        id: 'invite-member',
        name: 'Invite Member',
        server: smtp2,
        maxAge: 3 * 24 * 60 * 60,
        sendVerificationRequest: async ({ identifier: email, url, provider: { server, from } }) => {...}
      })
    ],
    ...
} satisfies AuthOptions
```

Then elsewhere in code:

```ts
await signIn('email', {
  callbackUrl: `${window.location.origin}/profile`,
  email
});

// or

await signIn('invite-member', {
  callbackUrl: `${window.location.origin}/auth/new-invite`,
  email
});
```

Each email provider is doing something different. How can I have multiple email providers and call sign-in to each one?

**Comment by basememara** [comment]
I created PR #8941 that exposes `id` and `name` to the email provider config while still allowing it to be optional. What are your thoughts on it?

**Comment by lveillard** [comment]
> this worked for me:
> 
> ```ts
> import EmailProvider from "next-auth/providers/email";
> 
>  EmailProvider({
>       async sendVerificationRequest({ identifier: email, url }) {
>         await sendVerificationRequest({ identifier: email, url });
>       },
>     }),
> ```

Ain't ugly if it works! Thanks 🙏

**Comment by tomatac** [comment]
Why is this closed?
It looks like is still an issue in next-auth 5.0.0-beta.13

**Comment by renardeinside** [comment]
Resend example doesn't work too with the same problem - https://authjs.dev/getting-started/providers/resend#configuration

**Comment by kiknaio** [comment]
Still same problem here!

**Comment by tomatac** [comment]
why close, if it is still an issue?
