### ISSUE TITLE
NextAuth on Vercel redirects to localhost even 

### ISSUE THREAD

**Issue by jackpeck2004** [nextauthjs/next-auth#8129]
### Environment

  System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i7-1365U
    Memory: 5.35 GB / 7.43 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.0 - /run/user/1000/fnm_multishells/1203_1690216418166/bin/node
    npm: 9.6.7 - /run/user/1000/fnm_multishells/1203_1690216418166/bin/npm

### Reproduction URL

https://github.com/jackpeck2004/next-auth-example

### Describe the issue

When using vercel, for deployment or in development using ```vercel dev```, the next auth providers point to localhost even when ```NEXTAUTH_URL``` or ```VERCEL_URL``` are set to a different address.

This issue came using a google provider but i've seen works event with any other provider.

### How to reproduce

set in **.env.local** ```NEXTAUTH_URL``` to a website different from localhost (i.e. ```https://test.giacomopasin.com```).

When calling ```/api/auth/providers``` all providers point to localhost.

### Expected behavior

When ```NEXTAUTH_URL``` is set to a website (i.e. ```https://test.giacomopasin.com```), the endpoint ```/api/auth/providers``` should how that ```signinUrl``` and ```callbackUrl``` point to the set website.

**Comment by balazsorban44** [comment]
As per https://next-auth.js.org/deployment#vercel, you can drop `NEXTAUTH_URL` on Vercel. You can see a working example here: https://next-auth-example.vercel.app/api/auth/providers
