### ISSUE TITLE
How can i authenticate using curl?

### ISSUE THREAD

**Issue by ehudkaldor** [nextauthjs/next-auth#8139]
### Question 💬

Hi,
i have a web app of nextjs using API routes to a backend API (with bearer token), both auth'd by azure-ad SSO. i want to allow users/processes access to the API routes directly. for that, i need to authenticate somehow over command line. can this be done?

to be more precise, is there something link `curl https://...../api/auth/signin/ --user 'username:pass'` that i can use to get a token to access the frontend's api routes, and through them to the backend API?

### How to reproduce ☕️

NA

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
The OAuth authorization flow is designed to identify a user, which `next-auth` is intended for. for Machine-to Machine connection, you can look into the Client Credentials flow: https://www.oauth.com/oauth2-servers/access-tokens/client-credentials/
