### ISSUE TITLE
Widen peer dependency range to include React 17

### ISSUE THREAD

**Issue by billyjanitsch** [nextauthjs/next-auth#814]
**Summary of proposed feature**

[React 17](https://reactjs.org/blog/2020/10/20/react-v17.html) was released recently with minimal breaking changes. `next-auth` currently supports only `^16.13.1`:

https://github.com/nextauthjs/next-auth/blob/5126f4e3428f2b4b8ebdd38b10066edfdd4ea2fa/package.json#L57-L60

Could this be widened to `^16.13.1 || ^17.0.0`?

**Purpose of proposed feature**

Allows apps using React 17 to also use `next-auth` without peer dependency warnings.

**Detail about proposed feature**
n/a

**Potential problems**
There are [subtle differences](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#changes-to-event-delegation) between React 16 and React 17, so it's worth reviewing to see if any of them might affect the library's functionality.

**Describe any alternatives you've considered**
You could alternatively release a new major version of `next-auth` that peer-depends only on React `^17.0.0`, but since the changes are minimal, you may not want to deprecate support for React 16 going forward.

**Additional context**
n/a

*Please indicate if you are willing and able to help implement the proposed feature.*
Yes.

**Comment by foaadnami** [comment]
+1

**Comment by skiabox** [comment]
Please see that issue, because NextJS is using React 17 now, so we can't use your library with NextJS any more!
Thank you!

**Comment by billyjanitsch** [comment]
@skiabox that's not correct. You can use React 16 or React 17 with even the latest version of Next.js. See its [peer dependencies](https://github.com/vercel/next.js/blob/ac54573b74d50469c826d438d72929cfc34ad369/packages/next/package.json#L108-L111). It's up to you which one you install.

**Comment by foaadnami** [comment]
next-auth doesnt seem to install out of the box on a clean node15/npm7/react17 setup and I wonder if its related to this issue
What am I missing and should this be added to the documentation ?

npm i next-auth
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: myproject@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1" from next-auth@3.1.0
npm ERR! node_modules/next-auth
npm ERR!   next-auth@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by billyjanitsch** [comment]
@foaadnami the error is saying that there's a peer dependency conflict, because you've installed React 17 but next-auth currently requires React 16. You can fix it by using React 16 until next-auth expands its peer dependency range to include React 17, which is what this issue is about.

I don't think there's anything to be added to the documentation; this is the error that you'll get if you try to install any two incompatible packages.

**Comment by foaadnami** [comment]
@billyjanitsch I think what @skiabox  means is that new installs of Next.Js via say npx create-next-app will default to react 17 which next-auth 3.1 will not install on top of
