### ISSUE TITLE
Can auth.js be used with vite + node.js express backend?

### ISSUE THREAD

**Issue by Temzin** [nextauthjs/next-auth#8158]
### Question 💬

I'd like to use this on a vite SPA without SSR, using a plain old node.js express back end. Is it possible? I can't find any documentation on using it with node.js despite authjs.dev saying it's possible. Does anyone have any examples of a similar setup or a relevant blog post? Thanks!

### How to reproduce ☕️

No code to reproduce yet. Ill post it as I experiment.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Yes, this is possible, but there is no official package/example for it yet.

Some pointers:

https://authjs.dev/reference/core#usage

You'll need to write some logic to turn Express.js' req/res to the web standard `Request`/`Response` APIs, and create a catch-all route at `/api/auth/*`, and let Auth.js handle all `GET` and `POST` requests.
