### ISSUE TITLE
Email login does not working in mobile devices

### ISSUE THREAD

**Issue by peguimasid** [nextauthjs/next-auth#816]
**Describe the bug**
I implemented an authentication following the documentation tutorial, it only worked on the computer, on my mobile device it doesn't log in

**Steps to reproduce**
Go to this link in desktop and mobile and see one login and other not:

https://yelpcamp-nextjs-mongodb.vercel.app/

Repository: https://github.com/peguimasid/YelpCamp-Nextjs-MongoDB

**Expected behavior**
I expect the implementation works in mobile too, not just un desktop

**Additional context**
To implement in typescript it was a little bit more complex, and i use `getServerSideProps` to make the login, maybe its the cause, but i dont know

**Comment by peguimasid** [comment]
Now i try to implement follow completly the tutorial:
```
import React from 'react'
import { useSession, signin, signout } from 'next-auth/client'

export default function myComponent() {
  const [session, loading] = useSession()

  return (
    <p>
      {!session && (
        <>
          Not signed in <br />
          <button onClick={signin}>Sign in</button>
        </>
      )}
      {session && (
        <>
          Signed in as {session.user.email} <br />
          <button onClick={signout}>Sign out</button>
        </>
      )}
    </p>
  )
}
```

and not more using `getServerSideProps`:

```
import React from 'react'
import NextAuth from 'next-auth/client'
import { GetServerSideProps } from 'next'

interface IUser {
  name?: string
  email: string
  image?: string
}

interface ISession {
  accessToken: string
  expires: string
  user: IUser
}

interface SessionProps {
  session: ISession
}

const Home: React.FC<SessionProps> = ({ session }) => {
  return (
    <p>
      {!session && (
        <>
          Not signed in <br />
          <button onClick={() => NextAuth.signin()}>Sign in</button>
        </>
      )}
      {session && (
        <>
          Signed in as {session.user.email} <br />
          <button onClick={() => NextAuth.signout()}>Sign out</button>
        </>
      )}
    </p>
  )
}

export const getServerSideProps: GetServerSideProps<SessionProps> = async ({
  req
}) => {
  const session = await NextAuth.session({ req })

  return {
    props: {
      session
    }
  }
}

export default Home
```
and still not working on mobile devices

**Comment by iaincollins** [comment]
I'm not sure what is meant by mobile devices in this context (iOS, Android phones?) but this appears to be a bug in your application and not in NextAuth.js.

The service at https://yelpcamp-nextjs-mongodb.vercel.app does not seem to be configured with a working email server, I cannot sign in at all on any platform.

The example site at https://next-auth-example.now.sh is working.

**Comment by peguimasid** [comment]
Thanks Iain, i'm sorry if the bug is in my application, and i waste your time here, is not my intention, i'm using mailgun as SMTP server, i'm going try to change!

**Comment by iaincollins** [comment]
Getting mail servers working in production can be tricky as the debug options aren't ideal and getting the settings right (`smtps://` vs `smtp://` and getting the port right) for a provider can be tricky as they vary quite a bit between different mail service providers.

This is something I hope we can improve the experience of in future.

As a general rule, if you have an `smtps://` URL (secure SMTP) for the mail server that works locally, it should also work in production on a service like Vercel or AWS, but `smtp://` URLs (not encrypted) may work locally but get blocked in production.

Most providers use Port 465 or Port 587; unfortunately the standard was a bit of mess for a few years and specific options for different providers ended up quite different.

**Comment by iaincollins** [comment]
Will close this now, but with a note that we need to update the documentation for the email provider to show what the configuration for different providers should to look like.
