### ISSUE TITLE
TypeORM adapter hangs nextjs

### ISSUE THREAD

**Issue by NyakoFox** [nextauthjs/next-auth#8170]
### Adapter type

@auth/typeorm-adapter

### Environment

  System:
    OS: Windows 10 10.0.25905
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Memory: 1.38 GB / 11.84 GB
  Binaries:
    Node: 17.4.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (115.0.1901.188)
    Internet Explorer: 11.0.25905.1000
  npmPackages:
    @auth/typeorm-adapter: ^1.0.1 => 1.0.1

### Reproduction URL

https://github.com/v6cord/niveaux-neo

### Describe the issue

Whenever I run `npm run dev`, it always hangs on the following line:

`- wait compiling /api/auth/[...nextauth]/route (client and server)...`

This ONLY happens when I import `TypeORMAdapter` in that file.

### How to reproduce

Run `npm run dev` and wait.

### Expected behavior

It should finish compiling instead of hanging.

**Comment by balazsorban44** [comment]
The `typeorm` package has some complex `require` statements, which makes it hard for Next.js/webpack to analyze the module graph, which is necessary in the App Router. You can hint webpack to avoid this work by adding the following to your `next.config.js`:

```js
module.exports = {
  experimental: {
    serverComponentsExternalPackages: ["typeorm"],
  },
};
```

Closing, as this is not a NextAuth.js bug.
