### ISSUE TITLE
How to get CSRF token on the server

### ISSUE THREAD

**Issue by swport** [nextauthjs/next-auth#8171]
### What is the improvement or update you wish to see?

So far I've seen this from the docs: https://next-auth.js.org/configuration/pages#credentials-sign-in
```typescript
import { getCsrfToken } from "next-auth/react"

///

export async function getServerSideProps(context: GetServerSidePropsContext) {
  return {
    props: {
      csrfToken: await getCsrfToken(context),  // isn't it client side function with a fetch call
    },
  }
}
```

Which I don't understand, because `getCsrfToken` is a client side function with a fetch call. Why do I want to make a fetch call to my own server from my own server?

### Is there any context that might help us understand?

Which I don't understand, because `getCsrfToken` is a client side function with a fetch call. Why do I want to make a fetch call to my own server from my own server?

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/configuration/pages#credentials-sign-in

**Comment by balazsorban44** [comment]
There is currently no direct API for this. This will be addressed in the upcoming version: #7443
