### ISSUE TITLE
[next-auth][error][CLIENT_FETCH_ERROR], *DESPITE* Environmental Variables Being Present

### ISSUE THREAD

**Issue by machineghost** [nextauthjs/next-auth#8174]
### Environment

  System:
    OS: Linux 5.15 Linux Mint 21.1 (Vera)
    CPU: (8) x64 Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz
    Memory: 8.78 GB / 23.38 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.3.0 - /usr/local/bin/node
    npm: 9.6.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.198

### Reproduction URL

None; if I can't get the starting instructions to even work, I certainly won't deploy it live :)

### Describe the issue

There seems to be several variations (see https://github.com/nextauthjs/next-auth/issues/3560), but the core idea is that when you get the `CLIENT_FETCH_ERROR`:

> client.js:1 [next-auth][error][CLIENT_FETCH_ERROR] 
> https://next-auth.js.org/errors#client_fetch_error Unexpected token '<', "<!DOCTYPE "... is not valid JSON {error: {…}, url: '/api/auth/session', message: `Unexpected token '<', "<!DOCTYPE "... is not valid JSON`}

it directs you to a URL telling you to set an environmental variable ... but that variable isn't the issue.

### How to reproduce

I was just following the tutorial and I ran into it.  Presumably, any number of things could go wrong with setting up the route, including forgetting to set it up entirely.

### Expected behavior

Instead of getting an error message with a URL that directs the user to set the environmental variable, the URL should explain that the route handler is not working, and suggest several things to check for what could be making it not work.

**Comment by marquez138** [comment]
getting a similar error with the fauna adapter

**Comment by machineghost** [comment]
Repro is very simple: follow the basic starting instructions on your website, get anything wrong with the server-side route (eg. forget to make the [...nextauth]/route.js file, put it in the wrong place, have a typo in it, etc.), and get the error:

> client.js:1 [next-auth][error][CLIENT_FETCH_ERROR]
> https://next-auth.js.org/errors#client_fetch_error Unexpected token '<', "<!DOCTYPE "... is not valid JSON {error: {…}, url: '/api/auth/session', message: Unexpected token '<', "<!DOCTYPE "... is not valid JSON}

That error links to https://next-auth.js.org/errors#client_fetch_error, which falsely suggests that the problem is an environmental variable ... when the actual problem has nothing to do with any environment variable (the problem is the route setup).

**Comment by balazsorban44** [comment]
Clarified in the docs: https://github.com/nextauthjs/next-auth/commit/dcb11da2e2e64bd8e7b39c894d47cb8c4e059723

**Comment by machineghost** [comment]
While the new language is a lot better, it still doesn't clarify that the fundamental problem is that the `/api/auth/session` endpoint doesn't exist :(

Why not just explain that in the message?
