### ISSUE TITLE
app directory route handler redirects without processing credentials provider

### ISSUE THREAD

**Issue by willisplummer** [nextauthjs/next-auth#8177]
### Environment

 ```
 System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 73.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    npm: 9.7.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 16.3

Packages
next: 13.3.4
next-auth: 4.22.3
react: 18.2.0
```

### Reproduction URL

https://github.com/willisplummer/nextauth-repro

### Describe the issue

I recently moved my next auth config over to the new app directory route handler setup. It works locally running `npm dev` which calls `next dev`, but when I try to build my application in a docker container and run it (`docker-compose up --build`), I can load the sign-in screen (`/api/auth/signin`) but when I type in my credentials and submit, I am redirected to the `/api/auth/signin?csrf=true` and the authorize callback hasn't run.

Everything works correctly with the docker container and the old pages directory structure

### How to reproduce

clone the repo [here](https://github.com/willisplummer/nextauth-repro)

copy `.env.example` to new `.env` file

checkout the `appdir` branch

run `docker-compose up --build`

navigate to localhost:3000/admin, type in credentials and click the submit button. (You will be redirected and the request not processed)

On the `main` branch, `docker-compose up --build` works as expected.

[branch diff ](https://github.com/willisplummer/nextauth-repro/compare/appdir?expand=1)

### Expected behavior

I submit the credentials, the authorize callback fires, i'm logged in -- see how it works on main branch.

**Comment by nulfrost** [comment]
I get this same behaviour when running locally and using any of the OAuth providers. I've noticed that using node 16.x works but anything higher than that and it does not work.

**Comment by willisplummer** [comment]
Docker image is being built on node 16. Potentially related, when securing api route handlers, `getServerSession` doesn't work for me (always returns null) but `getToken` does work

**Comment by balazsorban44** [comment]
> getServerSession doesn't work for me (always returns null) 

you are likely hitting this: https://github.com/nextauthjs/next-auth/issues/7423

Otherwise, your reproduction works for me, I'm able to log in. I see you are on an older version of `next`, make sure to upgrade.

**Comment by willisplummer** [comment]
Thanks - upgrading to next 13.4.12 fixed for me

**Comment by machouz** [comment]
I had the same issue. I was using Next 13.4.16
After noting @willisplummer's comment, I switched from Next 13.4.16 to 13.4.12, and the issue was resolved for me.

> Thanks - upgrading to next 13.4.12 fixed for me

**Comment by bottxiang** [comment]
Thanks! I just downgrade from next@13.4.13 to next@13.4.12 and it works normally

**Comment by miguelc1221** [comment]
I am having a similar issue using EmailProvider. When I log in it seems `sendVerificationRequest` never gets called. I downgraded from next@13.4.19 to next@13.4.12 and that fixed the issue. Any idea what can be causing this?

```
import { env } from "@/env.mjs"
import { DrizzleAdapter } from "@auth/drizzle-adapter"
import { eq } from "drizzle-orm"
import { NextAuthOptions } from "next-auth"
import EmailProvider from "next-auth/providers/email"
import { Resend } from "resend"
import { db } from "@/lib/db"
import { users } from "./db/schema"
import LoginEmail from "./emails/login-email"


const resend = new Resend(env.RESEND_API_KEY)

export const authOptions: NextAuthOptions = {
  secret: env.NEXTAUTH_SECRET,
  adapter: DrizzleAdapter(db),
  session: {
    strategy: "jwt",
  },
  pages: {
    signIn: "/login",
  },
  providers: [
    EmailProvider({
      from: env.SMTP_FROM,
      sendVerificationRequest: async ({ identifier, url, provider }) => {
        const data = await resend.emails.send({
          from: "onboarding@resend.dev",
          to: "delivered@resend.dev",
          subject: "Hello world",
          react: LoginEmail({}),
        })
      },
    }),
  ],
  callbacks: {
    async session({ token, session }) {
       if (token) {
         session.user.id = token.id
         session.user.name = token.name
         session.user.email = token.email
         session.user.image = token.picture
       }

      return session
    },
   .....
  },
}

(src/app/api/auth/[...nextauth]/route.ts)

import NextAuth from "next-auth"

import { authOptions } from "@/lib/auth"

const handler = NextAuth(authOptions)

export { handler as GET, handler as POST }

```

**Comment by rahul-reveation** [comment]
I have a custom sign-in page that takes user to 'api/auth/signin/identity-server4'  which in turn redirects to '/api/auth/signin?csrf=true'. So I  am back to the login page. I am on next v13.4.12 and next-auth v4.23.1.  It works fins if I use the signIn() utility method which requires a client component. I was just trying if we can achieve same with complete server side rendering. 

My login page code:

```
import { getCsrfToken } from 'next-auth/react';

async function Login() {
  const csrfToken = await getCsrfToken();

  return (
    <div>
      <form action="/api/auth/signin/identity-server4" method="POST">
        <input type="hidden" name="csrfToken" defaultValue={csrfToken} />
        <button type="submit">
          <span>Sign in with IdentityServer4</span>
        </button>
      </form>
    </div>
  );
}

export default Login;

```
