### ISSUE TITLE
where to follow docs from? next-auth.js.org or authjs.dev?

### ISSUE THREAD

**Issue by terlan4** [nextauthjs/next-auth#8190]
### Question 💬

Sorry for such silly question, but next-authjs homepage tells that go to authjs for newer docs and authjs homepage is flagged as experimental. I am not sure from which path I should read the docs? (using with pages directory)

### How to reproduce ☕️

-

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by ThangHuuVu** [comment]
Please keep using https://next-auth.js.org/ for v4, we are migrating the doc to v5 at https://authjs.dev
