### ISSUE TITLE
feat: add request param to sendVerificationRequest for next-auth/providers/email

### ISSUE THREAD

**Issue by matthewlynch** [nextauthjs/next-auth#8193]
### Description 📓

Access to the `request` inside of the `sendVerificationRequest` method for the email provider would be helpful when building custom sign up / login forms.

This feature has been added to the [@auth/core@0.10.0](https://github.com/nextauthjs/next-auth/releases/tag/%40auth%2Fcore%400.10.0) package in #8071.

I've managed to get this working locally for `next-auth/providers/email`.

Would you be open to me creating a PR to add this feature?

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
Thanks, we would not like to backport this to `next-auth@4`. Although this will be part of `next-auth@5` as it relies on `@auth/core`. You can see #7443.
