### ISSUE TITLE
SvelteKit base path not used in client side signIn/signOut

### ISSUE THREAD

**Issue by jonek** [nextauthjs/next-auth#8230]
### Environment

Node: 18.17.0
OS: Ubuntu 22.04
"@auth/core": "^0.10.0",
"@auth/sveltekit": "^0.3.6",
provider: Auth0

### Reproduction URL

https://github.com/jonek/next-auth/commits/example-fix-base-path/apps/examples/sveltekit

### Describe the issue

Client side `signIn` and `signOut` functions fail in a SvelteKit app using @auth/sveltekit if the `svelte.config.js` contains a base path configuration as documented by https://kit.svelte.dev/docs/configuration#paths

### How to reproduce

1. Add a `kit.paths.base` value to your `svelte.config.js` like this:
```
// ...
const config = {
  // ...
  kit: {
    // ...
    paths: {
      base: '/foo',
    },
  },
}

export default config
```
2. Start your development example app (in my case using an Auth0 provider) and trigger the signIn.
3. In the browser console you will see something like:
```
GET http://localhost:5173/auth/csrf 404 (Not Found)
Uncaught (in promise) SyntaxError: Unexpected token 'T', "The server"... is not valid JSON
```
with a stack trace like:
```
window.fetch @ fetcher.js?v=5e3e0935:54
signIn @ client.js:19
login @ +page.svelte:7
```
4. The error is caused by `http://localhost:5173/auth/csrf` returning `The server is configured with a public base URL of /foo - did you mean to visit <a href="/foo/auth/csrf">/foo/auth/csrf</a> instead?` which is not valid JSON and causes the crash.

### Expected behavior

When the client side `signIn` is executed, the implementation should take the SvelteKit configuration into account to call the `/auth/csrf` and later the `/auth/signin/auth0` endpoints under the base path specified by `config.kit.paths.base`.
I.e. the URL to call should be `http://localhost:5173/foo/auth/csrf` and `http://localhost:5173/foo/auth/signin/auth0` in my example described above.

**Comment by aakash14goplani** [comment]
@jonek - did the latest release solved your problem? I am in similar situation now and I adding "prefix" does not fix problem for me. I am still seeing 404 for csrf request!

```ts
const config: SvelteKitAuthConfig = {
  providers: [...],
  prefix: '/hello',
}
```

```
Request URL: http://localhost:4200/hello/auth/csrf
Request Method: GET
Status Code: 404 Not Found
```
