### ISSUE TITLE
Property `prisma` doesn't exist on `Global & typeof globalThis`

### ISSUE THREAD

**Issue by awey95** [nextauthjs/next-auth#824]
**Your question**
When setting up the PrismaClient I used the following code in my `[...nextauth].ts` file

```typescript
export let prisma: PrismaClient

if (process.env.NODE_ENV === 'production') {
  prisma = new PrismaClient()
} else {
  if (!global.prisma) { <--
    global.prisma = new PrismaClient() <--
  }
  prisma = global.prisma <--
}
```

I keep getting this error/warning tho.
`Property 'prisma' does not exist on type 'Global & typeof globalThis'.ts(2339)`

Trying to understand how to get rid of this error. It seems to work anyways since the client doesn't keep opening new connections, but I'm a bit annoyed with the error. 

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by stephlow** [comment]
Took me a while to figure this one out too, but finally found a solution.
I added this to the same file, adding it to my `types.d.ts` didn't work for some reason:
```ts
declare global {
  namespace NodeJS {
    interface Global {
      prisma: any;
    }
  }
}
```

**Comment by mingcenwei** [comment]
You can use the following typescript code

```typescript
import {PrismaClient} from "@prisma/client";

import Adapters from "next-auth/adapters";

type GlobalThisWithPrisma = typeof globalThis & {
	"__prevent-name-collision__prisma": PrismaClient;
};

const getPrismaClient = () => {
	if (process.env.NODE_ENV === `production`) {
		return new PrismaClient();
	} else {
		const newGlobalThis = globalThis as GlobalThisWithPrisma;
		if (!newGlobalThis[`__prevent-name-collision__prisma`]) {
			newGlobalThis[
				`__prevent-name-collision__prisma`
			] = new PrismaClient();
		}
		return newGlobalThis[`__prevent-name-collision__prisma`];
	}
};
const prisma = getPrismaClient();

export default Adapters.Prisma.Adapter({prisma});
```

**Comment by fdlmhmd29** [comment]
> ```ts
> export let prisma: PrismaClient
> 
> if (process.env.NODE_ENV === 'production') {
>   prisma = new PrismaClient()
> } else {
>   if (!global.prisma) { <--
>     global.prisma = new PrismaClient() <--
>   }
>   prisma = global.prisma <--
> }
> ```
> 
> I keep getting this error/warning tho.
> `Property 'prisma' does not exist on type 'Global & typeof globalThis'.ts(2339)`

For anyone who came here getting the same error as @ghost and still hasn't got a solution. I found the solution here: [Prisma best practice for instantiating PrismaClient with Next.js.](https://www.prisma.io/docs/support/help-articles/nextjs-prisma-client-dev-practices) and this is very simple, what we need to do is **_declare the prisma variable as a global variable_**.

Like this:
```
declare global {
  var prisma: PrismaClient
}
```

I hope it helps.

**Comment by bhatvikrant** [comment]
If adding the declaration to `types.d.ts` file doesn't work then add it to your `next-env.d.ts`

`next-env.d.ts` ---->

```ts
/// <reference types="next" />
/// <reference types="next/types/global" />

declare global {
    namespace NodeJS {
        interface Global {
            prisma: any;
        }
    }
}

export { }
```

**Comment by dot4qu** [comment]
For those using node 16.x+: 
```js
declare global {
    var prisma: PrismaClient;
}
```

From: https://stackoverflow.com/questions/68322578/recent-updated-version-of-types-node-is-creating-an-error-the-previous-versi

**Comment by timfee** [comment]
> If adding the declaration to `types.d.ts` file doesn't work then add it to your `next-env.d.ts`
> 
> `next-env.d.ts` ---->
> 
> ```ts
> /// <reference types="next" />
> /// <reference types="next/types/global" />
> 
> declare global {
>     namespace NodeJS {
>         interface Global {
>             prisma: any;
>         }
>     }
> }
> 
> export { }
> ```

Newer versions of Next automatically wipe out changes to this file, so please don't add it there :)

**Comment by mr-chidex** [comment]
This works for me. For a node js code.
create a file say` types.d.ts`

in `types.d.ts`
```
import { PrismaClient } from '@prisma/client';

declare global {
  var prisma: PrismaClient | undefined;
}

```

Remember to add files in `tsconfig.json`
```
},
"files": ["src/types/types.d.ts"],
}
```

**Comment by leggant** [comment]
> This works for me. For a node js code. create a file say` types.d.ts`
> 
> in `types.d.ts`
> 
> ```
> import { PrismaClient } from '@prisma/client';
> 
> declare global {
>   var prisma: PrismaClient | undefined;
> }
> ```
> 
> Remember to add files in `tsconfig.json`
> 
> ```
> },
> "files": ["src/types/types.d.ts"],
> }
> ```

this worked for me 👍

**Comment by AdnanShah** [comment]
Try this

```
const client = (globalThis as any).prisma || new PrismaClient()
if (process.env.NODE_ENV !== 'production') (globalThis as any).prisma = client

```

**Comment by aidanwardman** [comment]
> Try this
> 
> ```
> const client = (globalThis as any).prisma || new PrismaClient()
> if (process.env.NODE_ENV !== 'production') (globalThis as any).prisma = client
> ```

This worked for!
