### ISSUE TITLE
How to use withAuth middleware with my own custom middleware.

### ISSUE THREAD

**Issue by 0xRaduan** [nextauthjs/next-auth#8240]
### Question 💬

Having trouble figuring out, how to make a middleware, which would work after and only if the user passed the authentication middleware.

Question from discord:
I want to create another auth middleware, which should be executed ONLY after the next auth middleware.

Now, when I try to define that:
```ts
import { withAuth } from "next-auth/middleware";
import { validateIfOnboardingNeeded } from "@/lib/validation";
import { BASE_PATH } from "@/lib/constants";
import { NextRequest, NextResponse } from "next/server";

export const config = { matcher: ["/dashboard/:path*", "/onboarding/:path*"] };
export default withAuth(async function middleware(req: NextRequest) {
  const onboardingNeeded = await validateIfOnboardingNeeded();
  if (onboardingNeeded) {
    return NextResponse.redirect("/onboarding/welcome");
  } else if (req.nextUrl.pathname.startsWith("/onboarding")) {
    return NextResponse.redirect(BASE_PATH);
  } else {
    return NextResponse.next();
  }
});
```

It doesn't work, unfortunately. What I am doing wrong here?

### How to reproduce ☕️

Next Js 13 app router.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
The function execution is reverse, going from the inside out. So you would need to wrap `withAuth` with your own middleware to make sure you handle the end response last.

Preferably, you can just put the on boarding needed logic into the `authorized` callback. See https://next-auth.js.org/configuration/nextjs#description
