### ISSUE TITLE
EmailProvider going against Vercel guidelines -- Not using email APIs and SMTP blocked on port 25

### ISSUE THREAD

**Issue by almog-co** [nextauthjs/next-auth#8247]
### Description 📓

The EmailProvider sends magic links using SMTP. I ran into an issue on Vercel where my EmailProvider wasn't working because all SMTP traffic on port 25 is blocked. In addition, [Vercel docs](https://vercel.com/guides/serverless-functions-and-smtp) do not recommend sending emails using SMTP and instead recommends using email API's. The [NextAuth docs](https://authjs.dev/getting-started/email-tutorial) goes against this and recommends using SendGrid with SMTP.

EmailProvider should be updated to support SendGrid, and other platforms, APIs for sending email instead of SMTP.

### Current AuthJS SMTP Approach:

```
export default NextAuth({
  providers: [
    Email({
      server: {
        host: process.env.SMTP_HOST,
        port: Number(process.env.SMTP_PORT),
        auth: {
          user: process.env.SMTP_USER,
          pass: process.env.SMTP_PASSWORD,
        },
      },
      from: process.env.EMAIL_FROM,
    }),
  ],
})
```

### Proposed AuthJS SMTP Approach:

```
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

export default NextAuth({
  providers: [
    Email({
        client: sgMail.send
    }),
  ],
})
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Hi, you can use any http-based email provider as well, check out our guide https://authjs.dev/guides/providers/email-http
