### ISSUE TITLE
Nextjs 13 App directory set cookies

### ISSUE THREAD

**Issue by apetta** [nextauthjs/next-auth#8248]
### What is the improvement or update you wish to see?

The docs state `Currently, the underlying Next.js cookies() method [only provides read access](https://beta.nextjs.org/docs/api-reference/cookies) to the request cookies. This means that the expires value is stripped away from session in Server Components. Furthermore, there is a hard expiry on sessions, after which the user will be required to sign in again. (The default expiry is 30 days).`

However the cookies docs for nextjs that is linked to shows that cookies can be set now. So is this still the case? Is it not possible to avoid the user being signed out when using the app directory?

### Is there any context that might help us understand?

Nextjs docs [here](https://nextjs.org/docs/app/api-reference/functions/cookies) 

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/configuration/nextjs

**Comment by balazsorban44** [comment]
This is still correct, and a duplicate issue. See the explanation here https://github.com/nextauthjs/next-auth/issues/8094#issuecomment-1645796581
