### ISSUE TITLE
Add official Express.js support to auth/core

### ISSUE THREAD

**Issue by hillac** [nextauthjs/next-auth#8257]
### Description 📓

I've seen several issues / posts related to support for express.js and want to use it myself. I would like to propose adding express as an officially supported framework. Given the intention to support more frameworks, I think it would be worthwhile bringing direct support for Auth.js to the most popular back end javascript framework.

Here is an example implementation: [rexfordessilfie/authjs-express-demo](https://github.com/rexfordessilfie/authjs-express-demo), which implements a translation layer for the web standard api request/response to express requests/responses, and express middleware for JWT authentication. So support seems quite straightforward.

I'd be willing help with this / add documentation for using express. If this feature is not accepted, I'm also happy to just write docs for using it like in authjs-express-demo if anyone else considers that worthwhile.

### Some links to related issues:

- https://github.com/nextauthjs/next-auth/issues/8158

- https://github.com/nextauthjs/next-auth/issues/7647
- https://github.com/nextauthjs/next-auth/issues/6417

#### For older versions:
- https://github.com/nextauthjs/next-auth/issues/554
- https://github.com/nextauthjs/next-auth/issues/531

#### On reddit:
- [React NextJS next-auth with custom Express backend??](https://www.reddit.com/r/expressjs/comments/mta5lg/react_nextjs_nextauth_with_custom_express_backend/)
- [How to use Next-Auth with a separate backend (ExpressJs)?](https://www.reddit.com/r/nextjs/comments/rri1js/how_to_use_nextauth_with_a_separate_backend/)
- [Next-Auth with express server, is it applicable?](https://www.reddit.com/r/nextjs/comments/n3ie2x/nextauth_with_express_server_is_it_applicable/)

### How to reproduce ☕️

https://github.com/rexfordessilfie/authjs-express-demo

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by rexfordessilfie** [comment]
Thanks for putting this issue together @hillac! As the creator of the demo repository I would also love to see official support and community efforts on the logic required to translate between Web Request/Response APIs and Express' APIs. I have brought it to a working state in my repository, but more hands and eyes on it would improve its quality and make it more useful to the community.

I think being added as a `frameworks-express` (e.g exposing a router that could be plugged into Express) could be the best path towards this, but also docs/a guide, or even a stand-alone library could also achieve similar! I would appreciate thoughts from maintainers and the community on this! 

Thanks!

**Comment by balazsorban44** [comment]
As far as I can tell, all we need is a wrapper around `@auth/core` that transforms `Request` -> `Response` to Node.js' `req` and `res`. The linked demo has that already, nice work!

If someone opens a PR, we could discuss further there.

As for documentation, we prefer JSDoc, that we can then use to auto-generate our docs site.

See https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/index.ts for an example. Rendered here: https://authjs.dev/reference/core

**Comment by rexfordessilfie** [comment]
Thank you for the comments and guidance @balazsorban44 🙌! You’re right, the translation wrapper should be all that is needed, and is taken care of in the demo! 

@hillac, what do you say to pairing together to put together a PR for review and discussion?

We can follow closely, the standard setup in frameworks-x directories, and follow the approach from the demo.

Also @balazsorban44, there were some more specific pieces such as having a body parser middleware in the app to make the translation fully possible. I will call these out in the JSDoc and PR to make sure we’d be taking the right approach there. 

Thanks to you both again 👍!

**Comment by binaryartifex** [comment]
cant' tell you how much im looking forward to drop kicking passportjs in my nestjs application in favor of this....

**Comment by matmar-91** [comment]
Thank you for working on this! ❤️
Any progress so far?🤞
