### ISSUE TITLE
Trivial but Frustrating: Cannot find module 'next-auth/next' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by eyeHORUSdotETH** [nextauthjs/next-auth#8263]
### Question 💬

I'm using NextJS 13.4.7 with Typescript and I simply cannot find or import next-auth/next to use `getServerSession()`

Any help would be greatly appreciated, I'm completely at a loss for where to look or what to try at this point. 

Thanks!

### How to reproduce ☕️

<img width="640" alt="Screen Shot 2023-08-08 at 11 23 15 AM" src="https://github.com/nextauthjs/next-auth/assets/20019464/270d12a9-cd1a-4c9b-a9c6-6ca602fa32ec">

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth/blob/124be4fb1f55bed46413a0ba941fc067671e07ce/packages/next-auth/package.json#L29-L38

Likely we should expose the type declarations here. See https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing

**Comment by eyeHORUSdotETH** [comment]
@ericvoshall when I try that I get `Module '"next-auth"' has no exported member 'getServerSession'.ts(2305)`

@balazsorban44 my next-auth exports and file structure are a bit different it seems, for example it appears im missing the next directory?
<img width="505" alt="Screen Shot 2023-08-09 at 7 01 46 PM" src="https://github.com/nextauthjs/next-auth/assets/20019464/2c5eaeda-c3f1-4b46-a25a-26fe9620f0b5">
<img width="751" alt="Screen Shot 2023-08-09 at 7 01 22 PM" src="https://github.com/nextauthjs/next-auth/assets/20019464/a808645a-f72d-400c-9d48-90b9f4e932d8">

**Comment by balazsorban44** [comment]
@eyeHORUSdotETH this is not an issue then. You installed `next-auth@experimental` which is a major release bump. See #7443 for more info/migration/documentation.

**Comment by eyeHORUSdotETH** [comment]
@ericvoshall  @balazsorban44 thanks so much for your help 🙏

**Comment by SamuelOliveira-M** [comment]
How was the problem resolved?
I'm using version 5.0.0-beta.5 of next-auth and I'm facing the same problem.

**Comment by SamuelOliveira-M** [comment]
How was the problem resolved?
I'm using version 5.0.0-beta.5 of next-auth and I'm facing the same problem.

**Comment by SamuelOliveira-M** [comment]
How was the problem resolved?
I'm using version 5.0.0-beta.5 of next-auth and I'm facing the same problem.

**Comment by gerhat** [comment]
@SamuelOliveira-M you need to use the auth() function instead.
Check this link: https://authjs.dev/getting-started/migrating-to-v5#details

```jsx
import { auth } from '@/lib/auth';

const Page = async () => {
  const session = await auth();
  console.log(session);

  return <p>Welcome to admin page!</p>;
};

export default Page;
```

**Comment by SamuelOliveira-M** [comment]
Thank you, I hadn't found this page containing some changes from version 5.

**Comment by SamuelOliveira-M** [comment]
How can I add a token from a custom API to the NextAuth v5 session when I authenticate a user using the authorize method with the Credentials provider? When performing authentication, the authorize method returns an object with the structure:

```
{
  user: {
    email: 'sam123456@gmail.com'
  },
  expires: '2024-05-29T23:55:06.026Z'
}

```
How can I extract the token from this custom API and save it in the NextAuth session for later use, such as authorizing requests?

**Comment by AleksaRistic216** [comment]
> [@SamuelOliveira-M](https://github.com/SamuelOliveira-M) you need to use the auth() function instead. Check this link: https://authjs.dev/getting-started/migrating-to-v5#details
> 
> import { auth } from '@/lib/auth';
> 
> const Page = async () => {
>   const session = await auth();
>   console.log(session);
> 
>   return <p>Welcome to admin page!</p>;
> };
> 
> export default Page;

This one worked. Not sure why few people gave it thumbs down. Should elaborate.
