### ISSUE TITLE
SalesforceProvider doesn't allow scope configuration

### ISSUE THREAD

**Issue by ianschmitz** [nextauthjs/next-auth#8264]
### Provider type

Salesforce

### Environment

  System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 43.77 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.0/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.5.1
  npmPackages:
    @auth/core: ^0.10.0 => 0.10.0 
    @auth/prisma-adapter: ^1.0.1 => 1.0.1 

### Reproduction URL

https://github.com/ianschmitz/auth-js-bug-salesforce-params/blob/main/pages/api/auth/%5B...nextauth%5D.ts

### Describe the issue

I am unable to set properties on `authorization.params` such as `scope` or `prompt` when using the SalesforceProvider. I suspect this issue might exist for other providers as well.

May be related to https://github.com/nextauthjs/next-auth/pull/2842

### How to reproduce

Create a Salesforce provider with the following config:

```ts
    SalesforceProvider({
      authorization: {
        params: {
          prompt: "consent",
          scope: "openid profile email offline_access",
        },
      },
      clientId: env.SALESFORCE_CLIENT_ID,
      clientSecret: env.SALESFORCE_CLIENT_SECRET,
    })
```

Note that the URL that we are redirected contains the default `scope` value, and does not contain `prompt` param.

### Expected behavior

`params` should be respected when the provider configures `authorization`, `token` and `userinfo` properties. If i hack the config to the following then `params` is respected:

```ts
    {
      ...SalesforceProvider({
        authorization: {
          params: {
            prompt: "consent",
            scope: "openid profile email offline_access",
          },
        },
	    clientId: env.SALESFORCE_CLIENT_ID,
	    clientSecret: env.SALESFORCE_CLIENT_SECRET,
      }),
      // HACK: get rid of default endpoint configuration and use `issuer` instead.
      authorization: undefined,
      token: undefined,
      userinfo: undefined,
      issuer: "https://login.salesforce.com",
    }
```

**Comment by fracarma** [comment]
> ```js
> {scope: "id api full refresh_token openid"},
> ```

I have the same issue. This didn't work. The URL still contains the `&scope=openid+profile+email` params.

**Comment by saeedezzati** [comment]
A better workaround I found for this is setting the scope by overriding the authorization URL directly:
```
Salesforce({
      authorization: `${process.env.SALESFORCE_ISSUER}/services/oauth2/authorize?scope=id+profile+email+api+refresh_token+offline_access+chatter_api&response_type=code`,
      issuer: process.env.SALESFORCE_ISSUER,
      .....
})
```

**Comment by balazsorban44** [comment]
This should be working in newer versions. Please give it a try!
