### ISSUE TITLE
4.22.3 for app router?

### ISSUE THREAD

**Issue by harrywang** [nextauthjs/next-auth#8275]
### Question 💬

https://github.com/vercel-labs/ai-chatbot is using App router and "next-auth": "0.0.0-manual.83c4ebd1" - I have another project using "next-auth": "4.22.3", I wonder whether I can use 4.22.3 with app router project so that I can integrate the two projects - it seems I cannot authenticate users across two websites with different versions of next-auth 0.0.0-manual.83c4ebd1 and 4.22.3.

### How to reproduce ☕️

try to integrate two website login one using next-auth 0.0.0-manual.83c4ebd1 and another one use 4.22.3.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
The one there is using #7443. If you are not into experimenting, `4.22.3` already supports the App Router, check out the docs:

https://next-auth.js.org/configuration/nextjs

https://next-auth.js.org/configuration/initialization#route-handlers-app
