### ISSUE TITLE
Passkey support (FIDO / WebAuthn)

### ISSUE THREAD

**Issue by fabian-michael** [nextauthjs/next-auth#8279]
### Description 📓

Hi, I did not find an issue in regards.

Are there any plans on supporting passkey authentication? That would be awesome.

### How to reproduce ☕️

/

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
#6065 started working on it, although it's right now a bit outdated. It is still planned though. Will close this issue for now, you can upvote https://github.com/nextauthjs/next-auth/discussions/3937
