### ISSUE TITLE
Solid-start framework is importing types from "next-auth/react"

### ISSUE THREAD

**Issue by tsdevau** [nextauthjs/next-auth#8301]
### Environment

 System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 237.02 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.config/nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.config/nvm/versions/node/v18.17.1/bin/yarn
    npm: 9.6.7 - ~/.config/nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.6.12 - ~/.config/nvm/versions/node/v18.17.1/bin/pnpm
  Browsers:
    Brave Browser: 115.1.56.20
    Chrome: 114.0.5735.198
    Edge: 115.0.1901.203
    Safari: 16.6

### Reproduction URL

https://github.com/nextauthjs/next-auth/blob/main/packages/frameworks-solid-start/src/client.ts

### Describe the issue

Framework for solid-start is attempting to import the following types from `next-auth/react` which is not included as a dependency (or otherwise required) for the solid-start framework.

```tsx
import { LiteralUnion, SignInOptions, SignInAuthorizationParams, SignOutParams } from 'next-auth/react';
```
I suspect this is related to the issue I'm having where a redirect included in a `signOut({ callbackUrl: "/", redirect: true })` call does not occur.

### How to reproduce

Refer to the `client.ts` [file](https://github.com/nextauthjs/next-auth/blob/main/packages/frameworks-solid-start/src/client.ts) in the next-auth repo.

<img width="1271" alt="Screenshot 2023-08-12 at 08 43 19" src="https://github.com/nextauthjs/next-auth/assets/93500023/6af53bba-3dcb-46e9-9751-8ee2231e56f2">

### Expected behavior

The required interfaces should be declared and exported from `@auth/core` or `@auth/solid-start` .  Then imports should reference the interfaces/types from those included within `@auth/core` or `@auth/solid-start`.

**Comment by balazsorban44** [comment]
It's only imported for the types, and as such, it is included as a dev dependency only:

https://github.com/nextauthjs/next-auth/blob/f29a1f27783819f84c61a17ea4041b16fcff50eb/packages/frameworks-solid-start/package.json#L34

It should not affect runtime behavior, so this is not a bug. I do agree that there is room to improve the import though, it should not come from `next-auth`.
