### ISSUE TITLE
error 504 on Vercel after sometimes from the deployment

### ISSUE THREAD

**Issue by Filpin011** [nextauthjs/next-auth#8307]
### Environment

System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 84.76 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Safari: 16.5

### Reproduction URL

i don't have a public repository of the project :(

### Describe the issue

After sometimes I deploy in production my next's project the login form start to bug and don't send the post request to my FastAPI backend deployed on fly.io, I enable the cors on FastAPI, for some hours after the deploy of my nextjs project the login works very well but after sometime it stop to give me an error and don't make the request.
Vercel give me error 504 from the url: /api/auth/callback/credentials
I use it as PWA in an iPhone and the UA is: Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1

![image](https://github.com/nextauthjs/next-auth/assets/64793842/b761de6e-83c3-41f5-85b3-4337b1ff5821)
### How to reproduce

_My authoptions.ts_

![image](https://github.com/nextauthjs/next-auth/assets/64793842/0b02976e-74af-4787-956d-f1fc027bcaab)

_my authmodal.ts where I handle the login_

![image](https://github.com/nextauthjs/next-auth/assets/64793842/cb95c2f0-3f4c-4b8a-882e-efaaf4ac26de)

### Expected behavior

Should login as normal after the axios request, but its slow and continue to loading...

**Comment by stechx1** [comment]
Was it solved?

**Comment by Filpin011** [comment]
i changed server for the backend, and now is deployed on heroku, before on fly, this fixed the problem.
