### ISSUE TITLE
`getToken` from "@auth/core/jwt" includes `process.env` and breaks usage in non-node env.

### ISSUE THREAD

**Issue by nicksrandall** [nextauthjs/next-auth#8308]
### Environment

Latest version of @auth/core

### Reproduction URL

n/a

### Describe the issue

I can not use `getToken` from "@auth/core/jwt" in a Cloudflare worker because it includes `process.env` calls.

### How to reproduce

Try to use the `getToken` function in any environment besides Node like Cloudflare workers or Deno and it breaks because process is not defined. 

### Expected behavior

I should be able to use this function in Cloudflare workers.

**Comment by balazsorban44** [comment]
this should not be the case anymore.

See https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/jwt.ts
