### ISSUE TITLE
Rest Api (maybe an issue?)

### ISSUE THREAD

**Issue by ccorreia64** [nextauthjs/next-auth#8319]
### Question 💬

Hi, 
I want to logout via rest api in a server component, but it is giving me an invalid url error.

This is the snippet

```
  // response from api external
  if (response.status === 401) {
    await fetch('/api/auth/signout?callbackUrl=/api/auth/session', {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      body: await fetch('/api/auth/csrf').then((rs) => rs.text()),
    });
    // redirect('/login');
  }
```

And the error is 
```
    input: '/api/auth/csrf',
    code: 'ERR_INVALID_URL'
```
The env file contain this
NEXTAUTH_URL=http://frontend.demo.test

I have commented out the variable NEXTAUTH_URL, adding http://frontend.demo.test/api/auth and still get the same error...

**Comment by balazsorban44** [comment]
This is not related to `next-auth`. Server-side `fetch` calls need to be absolute. You can see a solution for this here: https://github.com/nextauthjs/next-auth/blob/1815cd1c934a94ecd5068941c778573acf5ae815/packages/next-auth/src/index.tsx#L339-L349
