### ISSUE TITLE
custom LoginPage get stuck in loop until "431 Request Header Fields Too Large" (NextJS)

### ISSUE THREAD

**Issue by J4v4Scr1pt** [nextauthjs/next-auth#8332]
### Environment

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
    Memory: 5.89 GB / 31.71 GB
  Binaries:
    Node: 20.5.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.12 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.203)
    Internet Explorer: 11.0.19041.1566

### Reproduction URL

-

### Describe the issue

I have created a basic NextJS application with test pages and wanted to utilize AuthJS with it. 
I have been looking at the documentation on AuthJS page but also the [example ](https://vercel.com/templates?framework=next.js&auth=nextauth.js)pages from NextJS.

When using a custom login page the callback gets stuck in some kind of loop that adds dublicate parameters until it gets `431 Request Header Fields Too Large`. Have not figured out what's wrong and can't find anything regarding this issue. I think this is a bug but I could be wrong. 
If I use the original page from AuthJs everything works as expected.

If there is any extra information needed let me know and I will provide it!

Auth route file:
```
import NextAuth from 'next-auth';
import type { AuthOptions } from 'next-auth';
import CredentialsProvider from 'next-auth/providers/credentials';

export const authOptions: AuthOptions = {
	providers: [
		CredentialsProvider({
			// The name to display on the sign in form (e.g. 'Sign in with...')
			name: 'Credentials',
			// The credentials is used to generate a suitable form on the sign in page.
			// You can specify whatever fields you are expecting to be submitted.
			// e.g. domain, username, password, 2FA token, etc.
			// You can pass any HTML attribute to the <input> tag through the object.
			credentials: {
				username: { label: 'Username', type: 'text', placeholder: 'jsmith' },
				password: { label: 'Password', type: 'password' },
			},
			async authorize(credentials, req) {
				// You need to provide your own logic here that takes the credentials
				// submitted and returns either a object representing a user or value
				// that is false/null if the credentials are invalid.
				// e.g. return { id: 1, name: 'J Smith', email: 'jsmith@example.com' }
				// You can also use the `req` object to obtain additional parameters
				// (i.e., the request IP address)
				const res = await fetch('/your/endpoint', {
					method: 'POST',
					body: JSON.stringify(credentials),
					headers: { 'Content-Type': 'application/json' },
				});
				const user = await res.json();

				// If no error and we have user data, return it
				if (res.ok && user) {
					return user;
				}
				// Return null if user data could not be retrieved
				return null;
			},
		}),
	],
	session: { strategy: 'jwt' },
	// If I remove below pages object everything works
	pages: {
		signIn: '/auth/Login',
	},
};

const handler = NextAuth(authOptions);

export { handler as GET, handler as POST };

```

Middleware.ts:
`export { default } from 'next-auth/middleware';`

Custom login page:

```
const SignInPage = () => {
	return (
		<div className="flex h-[calc(100vh-theme(spacing.16))] items-center justify-center py-10">
			<button />
		</div>
	);
};

export default SignInPage;
```

package.json:

```
{
	"name": "test",
	"version": "0.1.0",
	"private": true,
	"scripts": {
		"dev": "next dev",
		"build": "next build",
		"start": "next start",
		"lint": "next lint"
	},
	"dependencies": {
		"next": "13.4.16",
		"next-auth": "^4.23.0",
		"postcss": "8.4.28",
		"react": "18.2.0",
		"react-dom": "18.2.0"
	},
	"devDependencies": {
		"@types/node": "20.5.0",
		"@types/react": "18.2.20",
		"@types/react-dom": "18.2.7",
		"autoprefixer": "10.4.15",
		"eslint": "8.47.0",
		"eslint-config-next": "13.4.16",
		"eslint-config-prettier": "^9.0.0",
		"prettier": "3.0.2",
		"prettier-plugin-tailwindcss": "^0.5.3",
		"tailwindcss": "3.3.3",
		"typescript": "5.1.6"
	}
}
```

Not working (custom login):
![image](https://github.com/nextauthjs/next-auth/assets/5929055/2ef46820-b311-4118-b867-5072fff4bf8e)
![image](https://github.com/nextauthjs/next-auth/assets/5929055/94f33b39-6749-42f8-ae4a-67d091539468)
![image](https://github.com/nextauthjs/next-auth/assets/5929055/d58bd8d6-826e-4a0e-89a2-2c8290bd016c)

Working (standard login):
![image](https://github.com/nextauthjs/next-auth/assets/5929055/dbcc1d3b-0327-4f8c-8f0e-57dca4864088)

Folder structure:
![image](https://github.com/nextauthjs/next-auth/assets/5929055/7b8d74ef-1d4a-42a8-954e-3fca0c9843bd)

### How to reproduce

Create a basic nextjs project and install/setup authJS.
Create a custom Login page and add it to options.

### Expected behavior

Should redirect to the custom login-page

**Comment by balazsorban44** [comment]
Missing the pages config from middleware. See the docs https://next-auth.js.org/configuration/nextjs#pages

**Comment by J4v4Scr1pt** [comment]
Ahh yes **sorry** missed that, thanks! 
But unfortunately this do not fix the issue :/.

This is how the middleware look now:

```
export { default } from 'next-auth/middleware';
export const config = { pages: { signIn: ''/auth/Login'' } };
```

**Comment by J4v4Scr1pt** [comment]
The callBack cookie gets filled for every loop of request.
Something is really fishy here.. 🤔
![image](https://github.com/nextauthjs/next-auth/assets/5929055/cc596b91-605b-4f4a-918f-8792efafd93e)

**Comment by J4v4Scr1pt** [comment]
Ok I fixed the issue using the middleware but not by putting it in the config object, but by adding it to the withAuth method.
Based on the awnser [here](https://github.com/nextauthjs/next-auth/discussions/4136).
```
import { withAuth } from "next-auth/middleware";

export default withAuth({
  pages: {
    signIn: "/auth/Login",
  },
});
```
