### ISSUE TITLE
Drizzle adapter - `relation t3turbo_account does not exist`

### ISSUE THREAD

**Issue by pegak** [nextauthjs/next-auth#8333]
### Environment

  System:
    OS: Windows 10 10.0.25300
    CPU: (16) x64 AMD Ryzen 7 6800HS with Radeon Graphics
    Memory: 12.51 GB / 31.26 GB
  Binaries:
    Node: 20.5.1 - ~\AppData\Local\Volta\tools\image\node\20.5.1\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\Volta\tools\image\yarn\1.22.19\bin\yarn.CMD
    npm: 9.6.5 - ~\AppData\Local\Volta\tools\image\npm\9.6.5\bin\npm.CMD
    pnpm: 8.6.3 - ~\AppData\Local\Volta\tools\image\pnpm\8.6.3\bin\pnpm.CMD
  Browsers:
    Edge: Spartan (44.25300.1000.0), Chromium (115.0.1901.203)
    Internet Explorer: 11.0.25300.1000

### Reproduction URL

https://next-web-nextjs.vercel.app/

### Describe the issue

I used Create-T3-Turbo and changed from MySQL (as I didn't want to use Planetscale) to Postgres. After some changes necessary, it seems to work, I can start Drizzle Studio, but when I try to log in it fails in the last step with a callback to Next-auth.

I even went to docs to check the schema if it is not outdated in T3 Turbo, but it doesn't seem to be.
https://authjs.dev/reference/adapter/drizzle

### How to reproduce

1. Go to the URL
2. Sign in with Discord
3. Authorise Discord
4. Get an error `Error
 [next-web-nextjs.vercel.app](https://next-web-nextjs.vercel.app/)` on URL https://next-web-nextjs.vercel.app/api/auth/error?error=CallbackRouteError
5. In the logs I can see this:
```
@acme/nextjs:dev: [auth][error][AdapterError]: Read more at https://errors.authjs.dev#adaptererror
@acme/nextjs:dev: [auth][cause]: error: relation "t3turbo_account" does not exist
@acme/nextjs:dev:     at D:\Work\edution\node_modules\.pnpm\pg-pool@3.6.1_pg@8.11.2\node_modules\pg-pool\index.js:45:11
@acme/nextjs:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
@acme/nextjs:dev:     at async eval (webpack-internal:///(rsc)/../../node_modules/.pnpm/drizzle-orm@0.28.2_@planetscale+database@1.10.0_@types+pg@8.10.2_@vercel+postgres@0.4.1_pg@8.11.2/node_modules/drizzle-orm/node-postgres/index.mjs:54:28)
@acme/nextjs:dev:     at async getUserByAccount (webpack-internal:///(rsc)/../../node_modules/.pnpm/@auth+drizzle-adapter@0.3.1/node_modules/@auth/drizzle-adapter/lib/pg.js:112:31)
@acme/nextjs:dev:     at async acc.<computed> (webpack-internal:///(rsc)/../../node_modules/.pnpm/@auth+core@0.0.0-manual.59d8da33/node_modules/@auth/core/lib/init.js:157:24)
@acme/nextjs:dev:     at async Module.callback (webpack-internal:///(rsc)/../../node_modules/.pnpm/@auth+core@0.0.0-manual.59d8da33/node_modules/@auth/core/lib/routes/callback.js:58:39)
@acme/nextjs:dev:     at async AuthInternal (webpack-internal:///(rsc)/../../node_modules/.pnpm/@auth+core@0.0.0-manual.59d8da33/node_modules/@auth/core/lib/index.js:103:38)
@acme/nextjs:dev:     at async Auth (webpack-internal:///(rsc)/../../node_modules/.pnpm/@auth+core@0.0.0-manual.59d8da33/node_modules/@auth/core/index.js:120:30)
@acme/nextjs:dev:     at async eval (webpack-internal:///(rsc)/../../node_modules/.pnpm/next@13.4.16_@babel+core@7.22.10_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/future/route-modules/app-route/module.js:254:37)
@acme/nextjs:dev: [auth][details]: {}
@acme/nextjs:dev: [auth][error][AdapterError]: Read more at https://errors.authjs.dev#adaptererror
@acme/nextjs:dev: [auth][cause]: error: relation "t3turbo_account" does not exist
@acme/nextjs:dev:     at D:\Work\edution\node_modules\.pnpm\pg-pool@3.6.1_pg@8.11.2\node_modules\pg-pool\index.js:45:11
@acme/nextjs:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
@acme/nextjs:dev:     at async eval (webpack-internal:///(rsc)/../../node_modules/.pnpm/drizzle-orm@0.28.2_@planetscale+database@1.10.0_@types+pg@8.10.2_@vercel+postgres@0.4.1_pg@8.11.2/node_modules/drizzle-orm/node-postgres/index.mjs:54:28)
@acme/nextjs:dev:     at async getUserByAccount (webpack-internal:///(rsc)/../../node_modules/.pnpm/@auth+drizzle-adapter@0.3.1/node_modules/@auth/drizzle-adapter/lib/pg.js:112:31)
@acme/nextjs:dev:     at async acc.<computed> (webpack-internal:///(rsc)/../../node_modules/.pnpm/@auth+core@0.0.0-manual.59d8da33/node_modules/@auth/core/lib/init.js:157:24)
@acme/nextjs:dev:     at async Module.callback (webpack-internal:///(rsc)/../../node_modules/.pnpm/@auth+core@0.0.0-manual.59d8da33/node_modu
```
Where the main part is `[auth][cause]: error: relation "t3turbo_account" does not exist`.

### Expected behavior

Normally working login with official Drizzle Adapter.

Here is the repository with the code:
https://github.com/edution-org/next-web/blob/main/packages/db/schema/auth.ts

**Comment by balazsorban44** [comment]
This doesn't seem to be an issue in our package. There is nothing called `t3turbo_account` in our documentation either. Maybe forgot to run a migration or something similar.

**Comment by pegak** [comment]
The code is 100 % from the official documentation - https://authjs.dev/reference/adapter/drizzle - so that it matches the structure. Migration was also run. I was about to give a screenshot and it seems like I have a typo somewhere. The error says `t3turbo_account`, but I have a table `t3turbo_accounts`.

<img width="145" alt="image" src="https://github.com/nextauthjs/next-auth/assets/12586960/2f8c4f57-399a-43ae-96cb-23d019adc990">

**Comment by pegak** [comment]
I found it!

All I had to do was copy the DB structure from Drizzle Docs - https://authjs.dev/reference/adapter/drizzle#postgres

There was a difference between T3 Turbo and Drizzle Docs with the naming of the tables (here is not `s` appended).

**Comment by jaaneh** [comment]
Just leaving this here for future people passing by, as I crossed the same issue.

Make sure you're passing the tableCreator const to the DrizzleAdapter.

Using postgres:
```js
// server/db/schema.ts
export const pgTable = pgTableCreator(name => `myTable_${name}`)
```
```js
// server/auth.ts
import { pgTable } from "./db/schema"

export const authOptions: NextAuthOptions = {
  adapter: DrizzleAdapter(db, pgTable) as Adapter,
  // ...
}
```
