### ISSUE TITLE
signIn callback `user` modifications don't carry over to session callback's `user` param

### ISSUE THREAD

**Issue by keepri** [nextauthjs/next-auth#8336]
### Environment

System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 849.70 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    Watchman: 2023.08.07.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.2

### Reproduction URL

https://github.com/keepri/mono.git

### Describe the issue

Hello,

As the title is saying, I'm setting some fields in the `signIn`'s callback `user` object, the user's roles, but, in the `session` callback these don't seem to carry over. I am using PrismaAdapter so the session strategy is "database", if this info helps in any way.

Am I doing something wrong or is this a bug?

I am using next-auth@4.22.1 and this is my `callbacks` configuration:
`    callbacks: {
        session(params) {
            if (params.session.user) {
                params.session.user.id = +params.user.id; // this is actually a number but the types are annoying
                params.session.user.roles = params.user.roles;
            }

            return params.session;
        },
        async signIn(params) {
            try {
                RoleManager.assign(+params.user.id, RoleName.user);
                params.user.roles = await RoleManager.getUserRoles(+params.user.id);

                return true;
                // eslint-disable-next-line @typescript-eslint/no-explicit-any
            } catch ({ message }: any) {
                console.error("sign in callback", message);
                return "failed signing in";
            }
        },
    },`

That comment is the `session` callback is also an issue that I'm having. I have tried modifying the `User` interface through an `auth.d.ts` file but no dice, it still remains as a string.

### How to reproduce

Try adding info stuff to the `user` object inside of the signIn callback and then try accessing it from the `session` callback.

### Expected behavior

Modifying the `user` object inside of the `singIn` callback should (?) carry over to the `session` callback.

**Comment by balazsorban44** [comment]
The `signIn` callback is not intended to mutate the params (none of the callbacks do), so this is expected.

**Comment by keepri** [comment]
> The `signIn` callback is not intended to mutate the params (none of the callbacks do), so this is expected.

I understand. Is there any way I could do this other than calling `getUserRoles` from the `session` callback?
