### ISSUE TITLE
DrizzleAdapter with Vercel Postgres not supported yet?

### ISSUE THREAD

**Issue by SimonPrammer** [nextauthjs/next-auth#8339]
### Question 💬

Trying the new DrizzleAdapter with 
vercel
 postgres gives me:
``` Error: Unsupported database type in Auth.js Drizzle adapter.```

I tried different ways to initialize the db but to no success.

Am I doing something wrong or is it actually not supported yet?

### How to reproduce ☕️

Use drizzle + sveltekit + vercel postgres. Try using the adapter: DrizzleAdapter(drizzleDb) in a hooks.ts file

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by lakeesiv** [comment]
Hi I am using ` "next-auth": "0.0.0-manual.024ba3e6",` and Drizzle works with vercel pg

```ts
import { sql } from "@vercel/postgres";
import { drizzle } from "drizzle-orm/vercel-postgres";
import * as schema from "./schema";

export const db = drizzle(sql, { schema });
```

**Comment by lakeesiv** [comment]
Although I get the same error when using Neon, which is odd as vercel pg uses neon under the hood?

**Comment by lakeesiv** [comment]
```ts
if (isMySqlDatabase(db)) {
    // We need to cast to unknown since the type overlaps (PScale is MySQL based)
    return mySqlDrizzleAdapter(db, table as MySqlTableFn);
  }

  if (isPgDatabase(db)) {
    return pgDrizzleAdapter(db, table as PgTableFn);
  }

  if (isSQLiteDatabase(db)) {
    return SQLiteDrizzleAdapter(db, table as SQLiteTableFn);
  }

  throw new Error("Unsupported database type in Auth.js Drizzle adapter.");
```
Not sure if this is the best way for drizzle adapter to handle it. Would adding an extra param saying dbType = "pg"|"mysql"|"sqlite" as a way of overriding the if statements be a good idea?
