### ISSUE TITLE
SignIn function always returns "ok", even if the authorization returns null

### ISSUE THREAD

**Issue by elpablazo** [nextauthjs/next-auth#8340]
### Provider type

Credentials

### Environment

  System:
    OS: Linux 6.4 Fedora Linux 38 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 9.47 GB / 15.40 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
    pnpm: 8.6.12 - ~/.local/share/pnpm/pnpm

### Reproduction URL

https://github.com/elpablazo/checador-front/

### Describe the issue

If you use @auth/sveltekit and try to use the `signIn() ` function with the credentials provider and set redirect: false so that you can handle the error on the client sade, you always get a response with a status code of 200 and `ok: true`. Doesn't matter if the actual authorization process has a successfull response from the backend or not. This only happens when redirect: false, since when it's set on true it will lead you to the error message. However, the error cannot be customized either, as it states [here](https://authjs.dev/guides/providers/credentials#example---username--password)

### How to reproduce

Example configuration: 

`await signIn('credentials', {
	redirect: false,
	...values
});`

On the authorizize function:

`async authorize({ email, password }) {
    throw new Error("This should be a custom error")
}`

(or even if you just return null)

However, when you try to console.log the signin() response, you get:

`ok: true
​
redirected: false
​
status: 200
​
statusText: "OK"
​
type: "basic"`

My local terminal however, prints this:

`[auth][error][CallbackRouteError]: Read more at https://errors.authjs.dev#callbackrouteerror
[auth][cause]: Error: This should be a custom error.
[auth][details]: {
  "provider": "credentials"
}
`

### Expected behavior

It should return the same error that i threw on Throw new error ("message") or, at least, return an `ok: false`

**Comment by sarathkumarps17** [comment]
Can I work on the issue?

**Comment by kwonth211** [comment]
I am experiencing the same issue. How can we resolve this?

**Comment by Frikki** [comment]
@kwonth211 Please don’t respond with a “me, too.” It just overloads the maintainers with responses that don’t bring anything to the table. The issue has already been acknowledged. If you want to show your support, you can add a reaction to the original post with a thumps-up 👍🏻 

Comments should add information to the issue, e.g., other ways to reproduce it or what needs to be corrected in the source code.

**Comment by sarathkumarps17** [comment]
The same issue exists in next-auth with next13 app router implimentation
Provider type
 - Credentials
Environment
 - wsl2 Ubuntu 22.04LTS
 - node 18.17
 - next: 13.4.19 (using app router)
 - next-auth : 4.23.1
 Issue:
 - The SignIn() function returns ok:true even if the signinfails (wrong credentials or some other internal error). The function sometimes return ok:true and error:'some error' (eg CredetialError). That is confusing.

**Comment by aaronksaunders** [comment]
is there a suggested workaround for this issue?

**Comment by DarkAbhi** [comment]
Isn't this a priority issue? Or is there a workaround?

**Comment by balazsorban44** [comment]
Closed via: https://github.com/nextauthjs/next-auth/pull/8775

Please note that commenting "same issue" and such comments are immensely unhelpful.

"+1" and "same issue" comments may kill open-source on the other hand. Please use the upvote :+1: feature on the issue description, or subscribe to the issue for updates instead. Or better yet. This is an open-source project, meaning the source is open, and you are free to contribute via a PR. There is no need to wait for maintainers if this is a blocker for you.

@Frikki gets it. https://github.com/nextauthjs/next-auth/issues/8340#issuecomment-1708848160

Let us all do better 💚
