### ISSUE TITLE
Add a way to cancel `signIn` API calls

### ISSUE THREAD

**Issue by nbouvrette** [nextauthjs/next-auth#8348]
### Description 📓

As far as I know, today if you have multiple providers it's not possible to cancel a `signIn` API call. What I mean is:

1) You have 2 sign-in buttons with different APIs and loaders
2) Users click on the first provider, realizes its a mistake and clicks on the second provider
3) The first `signIn` call gets processed before, and the login page of the first provider show up to the user

Desired behavior:

When the user clicks on the second provider, we could cancel the first action and make sure that the second providers shows up, all the time.

I think that if we could send an `AbortController` as an option it could work?

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by rinvii** [comment]
Is there anything preventing you from just programmatically disabling all buttons when you click one until you get an API response back? In this way, the user cannot initiate another API call because all buttons are disabled.

**Comment by nbouvrette** [comment]
@rinvii from a UX perspectives, if you click on the wrong option and want to change provider, your only option is to wait for the wrong login page to load and press the back button which is not great.

**Comment by balazsorban44** [comment]
I would consider this a very niche use case indeed and would have a look at https://github.com/nextauthjs/next-auth/blob/b20182c5fecf6997ad544a8069d2383bddfdcd2b/packages/next-auth/src/react/index.tsx#L212-L289 to reimplement this for now.

Note that in the upcoming version of `next-auth` we won't be recommending the `fetch`-based sign-in method (but keeping it for backwards compatibility), but will rather rely on Server Actions instead, so I'm hesitant to expand the current API surface, hope you understand!

**Comment by nbouvrette** [comment]
@balazsorban44 If I understand correctly there will be 2 version of `signIn` ? the current one and the new server-action based one?

I'm not up to speed with server actions unfortunately but are you saying that this issue is going to be "abortable" using server-actions or is this just not a use case you are planning to support even in the future?

**Comment by balazsorban44** [comment]
> there will be 2 version

Yes.

For the second question, I actually don't think you can abort a form submission, but React might come up with a way. I don't know yet if it will be supported.

Identity Providers already have a builtin mechanism for canceling login though, so that might be the best wah to handle this. The only downside is that you wouldn't cancel it in your app but in their login screen instead.

**Comment by balazsorban44** [comment]
See https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions

what I would like to avoid is that one method supports it, while the other could not, to keep the api as similar as possible.

**Comment by nbouvrette** [comment]
Ok I couldn't find anything on that topic in the documentation - we'll see if I can get more details here: https://github.com/vercel/next.js/discussions/54516
