### ISSUE TITLE
404 Not found on /api/auth/*

### ISSUE THREAD

**Issue by vinaybedre** [nextauthjs/next-auth#835]
**Describe the bug**
next-auth's authentication routes are returning 404, when the api folder is moved to root from `pages`
I am using `vercel dev` for local testing

**Steps to reproduce**
Steps to reproduce the behavior.
Pull the repo, `npm i`, `npm run dev` and goto http://localhost:3000/api/auth/signin
https://github.com/vinaybedre/nextauth

**Expected behavior**
To see the sign-in page visible and the rest of the authentication routes to work

**Screenshots or error logs**
![image](https://user-images.githubusercontent.com/2630384/98420140-87d0bd80-20ac-11eb-9254-3bc4edbed360.png)

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [X] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [X] Could not find relevant documentation
* [X] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
Thanks for taking the time to raise an issue!

This is not a bug in NextAuth.js but a feature of Next.js, which requires the API directory to be inside the /pages directory.

If you are using s different path than /api/auth (eg using a proxy or gateway routing) you can specify a custom path on the end of NEXTAUTH_URL.

**Comment by shuzootani** [comment]
in NextJS 13-beta, with App dir fashion, /api directory is placed under /app by default, which was a bit confusing for me.
Thanks now it works.

**Comment by DavidForDev** [comment]
I placed api dir under pages but I still get a 404 error when I try to sign in, I don't have any idea why this happens, I spent a lot of hours but, I am still in one place. 

please let me know if you have solutions

**Comment by konami99** [comment]
@DavidForDev if you're using next-auth": "^5.0.0-beta.4, can you try downgrading to "4.24.5"

**Comment by konami99** [comment]
I have integrated a Next.js app with AWS Cognito, and the authentication is placed under /api/auth/

https://github.com/konami99/nextjs-dashboard/tree/cognito

Branch name: "cognito"

Hope this helps @andreycmartins

**Comment by pTinosq** [comment]
In case people are still struggling with this, the following solution worked:
[https://next-auth.js.org/configuration/initialization#route-handlers-app](https://next-auth.js.org/configuration/initialization#route-handlers-app)

I created `/app/api/auth/[...nextauth]/route.ts` and used the sample above which did work.

My final code looks like this:
```
import NextAuth from "next-auth";
import AzureADProvider from "next-auth/providers/azure-ad";

...

export const authOptions = {
  providers: [
    AzureADProvider({
      clientId: AZURE_AD_CLIENT_ID,
      clientSecret: AZURE_AD_CLIENT_SECRET,
      tenantId: AZURE_AD_TENANT_ID,
    }),
  ],
  secret: process.env.SECRET, 
};

const handler = NextAuth(authOptions);

export { handler as GET, handler as POST }; // <- THIS IS WHAT WORKED
```
