### ISSUE TITLE
EmailProvider + nodemailer fails with Vercel Edge Runtime due to Node.js 'stream' dependency

### ISSUE THREAD

**Issue by madhurjain** [nextauthjs/next-auth#8357]
### Environment

  System:
    OS: Linux 5.19 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i7-10600U CPU @ 2.80GHz
    Memory: 1.86 GB / 16.00 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    pnpm: 8.6.10 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 108.0.5359.124

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

Due to nodemailer's dependency on Node.js 'stream' module, it doesn't work with vercel's edge runtime.
Since `EmailProvider` has `nodemailer` as peer dependency importing it in a route marked as edge runtime throws below error -

```
The edge runtime does not support Node.js 'stream' module.
Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime
```
https://nextjs.org/docs/messages/node-module-in-edge-runtime

### How to reproduce

- In a Next.js 13.4 project, install Auth.js and peer dependency `nodemailer`
- Import `EmailProvider` in a route.ts that's marked as edge runtime using ` export const runtime = 'edge'`
- Build NextJS project using `pnpm run build`

### Expected behavior

Decouple EmailProvider and `nodemailer` so it doesn't throw an error

**Comment by madhurjain** [comment]
Tried raising an  issue with `nodemailer` thinking `stream` was the only dependency causing this issue but it was closed saying - 
```
Edge functions only work with front end modules. 
None of the backend Node apis that Nodemailer requires and can’t function without are supported there.
```

https://github.com/nodemailer/nodemailer/issues/1563#issuecomment-1684858106

Given this, can `nodemailer` be made a soft-dependency to Auth.js?

**Comment by madhurjain** [comment]
For now, I can probably use HTTP-based Email Provider to get around the issue

https://authjs.dev/guides/providers/email-http

**Comment by balazsorban44** [comment]
This is expected. `nodemailer` - as the name suggests - is a Node.js-focused library. You can see alternatives above via the http-based email provider guide

**Comment by fristyr** [comment]
Why this was closed  @balazsorban44 ? Maybe documentation needs to be updated at least ? It's kinda weird when you see nodemailer there with next.js, but when you try it you see the error

**Comment by brandonfake69** [comment]
Yes, this should be reopened. Given that in the docs you explicitly support nodemailer.

**Comment by iAmKrug** [comment]
> Yes, this should be reopened. Given that in the docs you explicitly support nodemailer.

Agreed, this should be reopened. Following the official Email Provider docs for Nodemailer and next.js it produces the same error: 

https://authjs.dev/getting-started/authentication/email

Error: The edge runtime does not support Node.js 'stream' module.
Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime

**Comment by SaltyRain** [comment]
so basically nodemailer cannot be used in any nextjs apps + nextauth? That's kind of weird while by default nextjs uses nodejs runtime. Or am I missing something?

**Comment by martinappo** [comment]
This seems to be exactly the case of [edge-compatibility](https://authjs.dev/getting-started/migrating-to-v5#edge-compatibility).

In the current state of getting-started repository, middleware.ts imports the NextAuth object from auth.ts, but middleware is run in edge environment.

Nodemailer is not edge-compatible library, so you have to split up the configuration and use only edge-compatible parts in edge environments (such as middleware). 

Just follow the example in given link and avoid using Nodemailer provider in edge environments.

**Comment by csyedbilal** [comment]
1+ same issue i'm facing

**Comment by Gustavohps10** [comment]
Pode ser o arquivo `middleware.ts` que usa o edge runtime. Da uma lida em https://authjs.dev/guides/edge-compatibility#split-config. 
Se for o caso, basta usar o recurso [“lazy initialization”](https://authjs.dev/reference/nextjs#lazy-initialization) separando a configuração em 2 arquivos, `auth.config.ts` e `auth.ts`, assim você pode instanciar um cliente sem o adaptador ou provedor (Nodemailer) para middleware.

```ts
//auth.config.ts

import type { NextAuthConfig } from 'next-auth'

export default {
  providers: [],
  pages: {
    signIn: '/signin',
    verifyRequest: '/verify-request',
    error: '/error',
    newUser: '/new-user',
    signOut: '/signout',
  },
  callbacks: {
    authorized: async ({ auth, request }) => {
      return true
    },
  },
} satisfies NextAuthConfig
 
```

```ts
//auth.ts

import authConfig from './auth.config'
import NextAuth from 'next-auth'
import { PrismaAdapter } from '@auth/prisma-adapter'
import { prisma } from '@/lib/prisma'
import Nodemailer from 'next-auth/providers/nodemailer'
 
export const { handlers, signIn, signOut, auth } = NextAuth({
  ...authConfig,
  adapter: PrismaAdapter(prisma),
  providers: [
    Nodemailer({
    /*... ...*/
    })
 ],
})

```
```ts
//middleware.ts

import NextAuth from "next-auth"
import authConfig from "./auth.config"
 
export const { auth: middleware } = NextAuth(authConfig)
```

**Comment by phamquocbuu** [comment]
1+ same issue i'm facing

this should be reopened

**Comment by balazsorban44** [comment]
Hi, 

This, is not a bug in NextAuth.js. The underlying `nodemailer` package isn't compatible with the Edge runtime.

> Yes, this should be reopened. Given that in the docs you explicitly support nodemailer.

>  basically nodemailer cannot be used in any nextjs apps + nextauth? 

It can be. But because of an upstream/framework-level limitation, you'll need to configure it a bit differently. See our dedicated documentation on this here:

https://authjs.dev/guides/edge-compatibility 

But good news, Next.js has plans to support Node.js as a runtime in Middleware!

https://x.com/balazsorban44/status/1842189615223984189

**Comment by iyk2h** [comment]
I ran into the issue where using the email provider with Nodemailer in the default NextAuth configuration resulted in errors because Nodemailer requires a Node.js environment (it isn’t Edge-compatible). To solve this, I split the configuration so that the email provider (Nodemailer) is only used in a Node.js API route. Specifically, I moved the provider configuration into my NextAuth setup and explicitly set the runtime to "nodejs", ensuring that Nodemailer is never loaded in an Edge environment. This resolved the error, and my final setup looks like this:

``` js 
import NextAuth from "next-auth";
import Nodemailer from "next-auth/providers/nodemailer";

export const { handlers, auth, signIn, signOut } = NextAuth({
  providers: [
    Nodemailer({
      server: {
        host: process.env.EMAIL_SERVER_HOST,
        port: process.env.EMAIL_SERVER_PORT,
        auth: {
          user: process.env.EMAIL_SERVER_USER,
          pass: process.env.EMAIL_SERVER_PASSWORD,
        },
      },
      from: process.env.EMAIL_FROM,
    }),
  ],
  // other options...
});

// Ensure this API route runs on Node.js:
export const runtime = "nodejs";
```

This approach ensures that all email-sending logic runs in the proper Node.js environment, effectively avoiding the Node-specific module errors in the Edge runtime.

This worked perfectly for my setup!
