### ISSUE TITLE
Logout from the app does not log me out of Auth0

### ISSUE THREAD

**Issue by georgy** [nextauthjs/next-auth#8386]
### Provider type

Auth0

### Environment

"next" : N/A
"react": N/A
"@auth/core": "0.12.0"
"@auth/sveltekit": "0.3.1"

### Reproduction URL

N/A (it is a basic setup)

### Describe the issue

After I implement the basic setup for Auth0, login sends me to the Auth0 login page where I have several configured ways to login. After I logout and login again I do not see Auth0 page (the part of the auth flow where I am presented with possible ways to login into Auth0 is skipped) and I am logged in without any password promts

### How to reproduce

* Get a basic Auth0 setup and try: login, logout, login again

### Expected behavior

When I logout I expect to be logged out from Auth0 as well (or at least have a config option to enable this feature) so that I can go through whole login process (including selection of the provider) on next login

**Comment by balazsorban44** [comment]
It's expected. NextAuth.js does not currently implement federated logout See #3938

**Comment by georgy** [comment]
hmmm, ok. Auth0 in our use case serves one app so I would not call it federated login, but I get the point

**Comment by balazsorban44** [comment]
When you log into your Identity Provider (in this case Auth0), you create a session with them, while it delegates access to your app at the same time. Logging out your app won't automatically log you out of the Identity Provider. It doesn't matter if your setup only has a single app connected to the provider or not. It's possible to solve this in user land though, see the thread above to get the idea.
