### ISSUE TITLE
Failed to fetch rsc payload while using NextAuth

### ISSUE THREAD

**Issue by imprakharshukla** [nextauthjs/next-auth#8389]
### Environment

  System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor             
    Memory: 9.22 GB / 31.94 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.1 - ~\AppData\Roaming\npm\npm.CMD
    pnpm: 8.6.12 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (116.0.1938.54)
    Internet Explorer: 11.0.22000.120

### Reproduction URL

-

### Describe the issue

Hey! I am using NextAuth+Google for auth and it's working super well on other devices except iOS safari and the other webkit browsers. All I get is this error-

ERRORFailed to fetch RSC payload. Falling back to browser navigation. TypeError: Load failed.

Was having the same error with Discord.

Will appreciate any help. Thank you.

Possibly related issue- https://github.com/vercel/next.js/issues/48677

### How to reproduce

Using Providers on a browser based on webkit.

### Expected behavior

Should open up the OAuth Consent screen of the provider.

**Comment by imprakharshukla** [comment]
Hey @balazsorban44! Sorry, but why was this issue closed?

**Comment by balazsorban44** [comment]
Because you haven't read the issue template.

**Comment by DeclanKBrown** [comment]
Same issue, @imprakharshukla was there a fix??
