### ISSUE TITLE
Failed to fetch rsc payload while using NextAuth

### ISSUE THREAD

**Issue by imprakharshukla** [nextauthjs/next-auth#8398]
### Environment

OS: Windows 10 10.0.22000
CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
Memory: 9.22 GB / 31.94 GB
Binaries:
Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
npm: 9.8.1 - ~\AppData\Roaming\npm\npm.CMD
pnpm: 8.6.12 - ~\AppData\Roaming\npm\pnpm.CMD
Browsers:
Edge: Spartan (44.22000.120.0), Chromium (116.0.1938.54)
Internet Explorer: 11.0.22000.120

### Reproduction URL

https://github.com/imprakharshukla/next-auth-js-rsc-payload-issue-test

### Describe the issue

Hey! I am using NextAuth+Google for auth and it's working super well on all devices except mobile. All I get is this error-

ERROR Failed to fetch RSC payload. Falling back to browser navigation. TypeError: Load failed.

Was having the same error with Discord.

Will appreciate any help. Thank you.

Possibly related issue- https://github.com/vercel/next.js/issues/48677

### How to reproduce

Try to login from a mobile to reproduce.

### Expected behavior

Should open up the OAuth Consent screen of the provider but it just loads and stays on the sign in page.

**Comment by imprakharshukla** [comment]
Vercel Preview- https://next-auth-js-rsc-payload-issue-test-web.vercel.app/dashboard

**Comment by appusvivek** [comment]
@imprakharshukla , can you mention how you managed to resolve it?

**Comment by appusvivek** [comment]
Hehe cool, the reason I asked was I'm using clerk at the moment and had the same error at some particular scenario. Couldn't spot what it was exactly. 

Anyhow thanks for the update, cheers mate.

**Comment by hocgin** [comment]
I encountered the same problem 

<img width="859" alt="image" src="https://github.com/nextauthjs/next-auth/assets/16535610/d39c76bc-bba1-4f48-bda8-73fc4caea2cd">
