### ISSUE TITLE
Is there any way to use NextAuth in class based component?

### ISSUE THREAD

**Issue by MateuszWawrzynski** [nextauthjs/next-auth#840]
**Your question**
Is there any way to use NextAuth in class based component? Maybe through props passing or something?

**What are you trying to do**
My app components are made using ES6 classes. As we know - we can't use hooks there. I have to implement this library to make auth system in this app, but that makes me to rebuild most of my app to function components.

**Feedback**
*-*

* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by balazsorban44** [comment]
You could maybe create a HOC (Higher Order Component) that sends them as props to your class component?:

```jsx
const withSession = ClassComponent => props => {
  const session = useSession()
  
  if(ClassComponent instanceof React.Component) {
    return <ClassComponent session={session} {...props}/>
  }
 
  throw new Error("You passed a function component, this wrapper is probably not needed. you can use ``useSession` directly in your component.")
}
```
