### ISSUE TITLE
Decrypting a secure cookie on an external server

### ISSUE THREAD

**Issue by Geuni620** [nextauthjs/next-auth#8401]
### Question 💬

Hi, I was wondering if this is not possible.

Here is my current situation.

- I have created a next.js client, express.js server.
- I am trying to use google oauth login.
- When I log in, I get a next-auth-session token in the cookie. 
- This token is encrypted, and I want to use this cookie to authenticate to the API.

In other words, when I request the API, I want to get the cookie from the express server, decrypt it, figure out the user information, and return the corresponding information from the DB.

It seems to be working fine locally. But after deploying, I couldn't interpret the secured cookie value as getToken.

Is it impossible because of the cookie policy? After all, I need to create a JWT token on the server and pass it to the client...?

### How to reproduce ☕️

```
// express.js
import { Request, Response, NextFunction } from 'express';
import { getToken } from 'next-auth/jwt';


export const requireAuth = async (
  req: Request,
  res: Response,
  next: NextFunction,
) => {
  const token = await getToken({
    req,
    secret: process.env.NEXTAUTH_SECRET,
  });

  console.log('token:', token); // null 
};
```

However, cookies have the following properties
`__Secure-next-auth.session-token` / `__Secure-next-auth.callback-url` / `__Host-next-auth.csrf-token`

I use HTTPS, and the domain is different for each server client.

Thank you. 🙇‍♂️

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
It's possible to define your own encode/decode methods and match your external service's, but it's considered an advanced use case. do it at your own risk

https://next-auth.js.org/configuration/options#jwt
