### ISSUE TITLE
Drizzle Adapter - wrong import file.

### ISSUE THREAD

**Issue by devdatkumar** [nextauthjs/next-auth#8406]
### What is the improvement or update you wish to see?

[DrizzleAdapter()](https://authjs.dev/reference/adapter/drizzle#drizzleadapter) 
In file `pages/api/auth/[...nextauth].ts` on line: 4, the  `{ db }` is imported from the wrong file `"./schema"`, because the `function db` doesn't exsist in that file. 

### Is there any context that might help us understand?

Normally in a nextjs folder structure:
It should import from `src/db/index.js` file, instead of `src/db/schema.js`.  
where the contents of `src/db/index.js` are mostly: 

```
import { drizzle } from 'drizzle-orm/postgres-js'
import postgres from 'postgres'

const connectionString = process.env.DATABASE_URL!
const client = postgres(connectionString)
export const db = drizzle(client);```

### Does the docs page already exist? Please link to it.

https://authjs.dev/reference/adapter/drizzle

**Comment by Vivek7038** [comment]
hey i would like to pick this issue if there is only need to fix the import .Just need to confirm it from maintainers

**Comment by ndom91** [comment]
Hey I'm going to close this issue since the Drizzle adapter docs have been rewritten and there is a total rewrite of the Drizzle adapter [about to be merged](https://github.com/nextauthjs/next-auth/pull/10479) as well. If you still see an issue, feel free to open a new issue :pray:
