### ISSUE TITLE
Logout without userconsent from IdP site (front-channel logout)

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#841]
**Your question**
How can I log the user out from an iframe from another page?
(Using OIDC Front-channel logout https://openid.net/specs/openid-connect-frontchannel-1_0.html#RPLogout)

**What are you trying to do**

So this is what I am trying to do:

The user decides to log out of their Next.js app. I would like them to be logged-out from the Identity Provider, because of several reasons, but most importantly because the users are expected to use the application on a computer accessible by several others.Therefore, when the user is finished with the app, they are expected to log out from the IdP as well.

The way it works with out OIDC compliant IdP (Identity Server 4), is that when the user is sent to the IdP's `/connext/endsession` [endpoint](https://identityserver4.readthedocs.io/en/latest/endpoints/endsession.html), the user is logged out of the IdP and on the same page an `iframe` is generated for each apps that are currently logged in, and they will be invoked on their respective front channel logout url. (This is predefined in the IdP client for security).

I have created an /api endpoint in my app that should trigger a logout, but I have a problem. TO be able to log out without the user's consent (remember, we are in an invisible iframe here), I need to have a CSRF token, which is stored in a cookie. This cookie is unfortunatelly not available in the iframe, so I cannot log the user out.

Here is my code:

```ts
import log from "utils/server-logger"
import { getCsrfToken } from "next-auth/client"
import { getToken } from "next-auth/jwt"


const frontChannelLogout = async (req, res) => {
  try {
    // const { sid: tokenSid } = await getToken({req}) // cannot actually access the token, since req does not have the cookie, because it is in an iframe on a different site
    const { query: {sid, iss} } = req.query
    if (
      `https://${process.env.IDP_HOST}` === iss && sid
      //&& sid === tokenSid // cannot actually compare, since tokenSid is undefined, see above
    ) {
      await logout()
    }
  } catch (error) {
    log.error(error, "FrontChannelLogoutError: {message}")
  } finally {
    res.setHeader("Cache-Control", "no-cache, no-store")
    res.setHeader("Pragma", "no-cache")
    res.end()
  }
}

export default frontChannelLogout

async function logout() {
  const res = await fetch(`${process.env.NEXTAUTH_URL}/api/auth/signout`, {
    method: "post",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: new URLSearchParams({
      csrfToken: await getCsrfToken(), // This will not return a correct token, since we don't have the right cookie inside the iframe.
      json: "true",
    }),
  })
  return await res.json()
}

```

Favorably I should also be able to get hold of the user's `sid`. I have an idea for it, but it would require access to the JWT token cookie. With #837, I can send the idToken to the `jwt` callback, and after decoding it with something like `jwt-decode`, I can save the `sid` of the user in the token, which I could in return compare with the `sid` sent by the IdP in my front-channel logout endpoint, by accessing the token with `getToken()`. The problem is the same though, `getToken()` needs to access the cookie by passing `req` to it, but since we are in an iframe on a different site, that cookie is not accessible. Although comparing the `sid` is an optional step, and I think I can leave without it.

So can I solve this problem - log the user out on another site, inside an `iframe` by calling a backend API endpoint - without introducing security concerns?

My only idea is to somehow loosen the restrictions on the cookie's and make them available if the URL equals to the IdP's, but I am no expert here, and don't know if someone can explicitely allow certain URL's for cookies, outside of the one the app is deployed on. (Found `Same-Site`, but did not see anything to create an allowed urls list of sort)

Thanks for the answer in advance!

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [x] Found documentation but was incomplete (https://next-auth.js.org/configuration/options#cookies found this section in the docs, but I am not certain how to configure it for my usecase, without exposing user's to some kind of security hole)
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

Related: #836, #837

**Comment by TommySorensen** [comment]
@balazsorban44 Can'y you just use the event `signOut` from here https://next-auth.js.org/configuration/events to get the token and then do the redirect?

**Comment by balazsorban44** [comment]
See #836

**Comment by davek-eql** [comment]
@balazsorban44 How were you able to do this?  We're running into the exact same issue trying to implement Azure AD B2C with NextAuth.  I do  not see solution in #836.
