### ISSUE TITLE
MongoDB Adapter with non-persistent connections

### ISSUE THREAD

**Issue by oren-z0** [nextauthjs/next-auth#8411]
### Description 📓

Please add an option that instead of accepting a `clientPromise` will accept a function generating a `clientPromise` - each handler should create its own client and close it at the end.

Many lambda/cloud-functions environments don't handle the persistent connections very well (i.e Vercel).

### How to reproduce ☕️

https://github.com/orgs/vercel/discussions/1211

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by marcspataru** [comment]
Hey, any updates? I think I am experiencing the same issue.
I am creating a new connection and closing it every time an endpoint is called.
I think the extra connection are opened and never closed because of the MongoDB adapter. I cannot pass an already connected mongo client into it since I only connect/disconnect on endpoints.

I'm not even sure when the connection is opened by the adapter, but am I correct in saying that opening one connection in `_document.tsx` and re-using that (for both the adapters and the endpoints) will minimise the number of connections being opened and never closed?

Using Next.js 13 without experimental app directory.
Next-auth 4, mongodb 6, @auth/mongodb-adapter 2.0.0

I am a beginner, so I might be completely off.

**Comment by boredland** [comment]
> Hey, any updates? I think I am experiencing the same issue. I am creating a new connection and closing it every time an endpoint is called. I think the extra connection are opened and never closed because of the MongoDB adapter. I cannot pass an already connected mongo client into it since I only connect/disconnect on endpoints.
> 
> I'm not even sure when the connection is opened by the adapter, but am I correct in saying that opening one connection in `_document.tsx` and re-using that (for both the adapters and the endpoints) will minimise the number of connections being opened and never closed?
> 
> Using Next.js 13 without experimental app directory. Next-auth 4, mongodb 6, @auth/mongodb-adapter 2.0.0
> 
> I am a beginner, so I might be completely off.

Not a solution per se, but: we switched to MongoDB Atlas Serverless which has been a huge improvement.

**Comment by marcspataru** [comment]
> > Hey, any updates? I think I am experiencing the same issue. I am creating a new connection and closing it every time an endpoint is called. I think the extra connection are opened and never closed because of the MongoDB adapter. I cannot pass an already connected mongo client into it since I only connect/disconnect on endpoints.
> > I'm not even sure when the connection is opened by the adapter, but am I correct in saying that opening one connection in `_document.tsx` and re-using that (for both the adapters and the endpoints) will minimise the number of connections being opened and never closed?
> > Using Next.js 13 without experimental app directory. Next-auth 4, mongodb 6, @auth/mongodb-adapter 2.0.0
> > I am a beginner, so I might be completely off.
> 
> Not a solution per se, but: we switched to MongoDB Atlas Serverless which has been a huge improvement.

I managed to mitigate the issue by actually following instructions. I wasn't actually sharing the same connection between different parts of the code. In order to fix my issue, I exported the actual promise of the client, and not an already connected Mongo client.

**Comment by boredland** [comment]
> I managed to mitigate the issue by actually following instructions. I wasn't actually sharing the same connection between different parts of the code. In order to fix my issue, I exported the actual promise of the client, and not an already connected Mongo client.

well, we're using the promise. we even try to ensure the promise is only returned [once](https://ramdajs.com/docs/#once).

**Comment by oren-z0** [comment]
@marcspataru @boredland Check out my implementation: "Volatile MongoDB Adapter"

https://github.com/nextauthjs/next-auth/pull/8753

I implemented something similar inside my project, and now had some time to make this PR (similar to my code).
The idea is to replace all the `clientPromise` with a `createClient` function, which returns a promise to a wrapper with two fields:

- `client` which is the connected client.
- `close` which is a custom function that the adapter will call at the end of each adapter api.

The `createClient` could simply create a new client each time with a `close` function to close it, but it could support complicated caching logics too. For example, it could create a cached client and maintain a counter that is increased on every call to `createClient` and decreased on every call to `close`. Then, close and delete the cached client only if the counter has reduced back to zero and stayed zero for X seconds.
