### ISSUE TITLE
A bit weird looking regex

### ISSUE THREAD

**Issue by JohnPhoto** [nextauthjs/next-auth#842]
https://github.com/nextauthjs/next-auth/blob/8115a7c66cdb1d86b0d2a0d76b9aa33c2bfaa33b/src/lib/parse-url.js#L13

The regex `/^http?:\/\//` will match `http://` but also `htt://`.
Is this really intended, or should the `?` be removed on this line? (It is ofcourse needed later in the `https?` replace regex.)

**Comment by balazsorban44** [comment]
It probably misses an `s` before that question mark

**Comment by JohnPhoto** [comment]
Yes that sounds like a good idea

**Comment by Zertz** [comment]
`URL` wasn't always available as a global in Node nor browsers so I would guess manually parsing the string is the best way to ensure the best compatibility without adding dependencies.

**Comment by JohnPhoto** [comment]
Ah ok, yeah sounds fair. but then it's just a matter of removing the `?` in that specific line?

**Comment by balazsorban44** [comment]
https://nodejs.org/api/url.html#url_class_url

If I understand this correctly, `URL` is supported since Node 10, which is the lowest supported node version anyway, so I think it is safe to use now. Am I wrong?

**Comment by Zertz** [comment]
Good point! In browsers however, people who need to support Internet Explorer would have to include a polyfill.

**Comment by balazsorban44** [comment]
Next.js includes polyfills for IE11, I assume URL is no different. Or wouldn't that cut it, even though this package will always be used together with `next`?
