### ISSUE TITLE
@auth/core lacks ability to return strings/routes in signIn callback (as opposed to next-auth and docs)

### ISSUE THREAD

**Issue by nash-an** [nextauthjs/next-auth#8422]
### Environment

```
  System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 7.00 GB / 15.69 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.69)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @auth/core: ^0.12.0 => 0.12.0
    @auth/sveltekit: ^0.3.6 => 0.3.7
    @sveltejs/kit: ^1.20.4 => 1.24.1
    svelte: ^4.0.5 => 4.2.0
    vite: ^4.4.2 => 4.4.9
```

### Reproduction URL

https://github.com/nash-an/authjs-issue-example 

### Describe the issue

[authjs-issue-example.vercel.app](https://authjs-issue-example.vercel.app/)

The Auth.js docs [show the ability to return](https://authjs.dev/guides/basics/callbacks#sign-in-callback) a string (rather than a boolean) to redirect to a different page inside of the signIn callback. 

This functionality doesn't seem to work at all, authjs evaluates the string as a truthy value and proceeds with authentication even when the intention was for it to fail.

```js
// Regular callback
async signIn({ user, account, profile, email, credentials }) {
  return true
}

// Example callback, both have identical results and will always proceed with authentication and not redirect
async signIn({ user, account, profile, email, credentials }) {
  if (example_whitelist.includes(profile.email)) {
    return true
  }

  return '/failed'
}
```

### How to reproduce

Return a string rather than a boolean inside of the [`signIn()`](https://authjs.dev/guides/basics/callbacks#sign-in-callback) callback inside of hooks.server.ts on SvelteKit.

### Expected behavior

The page should redirect to `/failed`, but instead it proceeds with normal authentication as if the return value was `true`.

**Comment by chukwumaijem** [comment]
I'm having the same issue. Except I get an invalid URL error.
```
TypeError: Failed to construct 'URL': Invalid URL
```

And when I provide a full url with host, then the error disappears and authentication proceeds instead of redirecting..

```
"next-auth": "^4.22.3"
```

**Comment by nash-an** [comment]
For SvelteKit specifically, it seems like this functionality is not even remotely implemented. I'm assuming the documentation is just out of date, so I think it's necessary to either add this feature or update the documentation.


No functionality for handling strings:
https://github.com/nextauthjs/next-auth/blob/57f75c7839cf67323e67b7f09ddaa01749891e12/packages/core/src/lib/routes/shared.ts#L4-L7

`signIn` callback return type is only boolean, no strings:
https://github.com/nextauthjs/next-auth/blob/57f75c7839cf67323e67b7f09ddaa01749891e12/packages/core/src/types.ts#L216-L218

**Comment by chukwumaijem** [comment]
Looks like I spoke too soon. Turns out a teammate disabled redirect on the signin function and I didn't notice. Redirect works as expected now. Q

**Comment by nash-an** [comment]
### This is a feature in `next-auth` but not in `@auth/core`.

Strings are properly handled as a string and not as a boolean: ([`@auth/core` counterpart](https://github.com/nextauthjs/next-auth/blob/57f75c7839cf67323e67b7f09ddaa01749891e12/packages/core/src/lib/routes/shared.ts#L4-L7))
https://github.com/nextauthjs/next-auth/blob/0e6c51adecc54d3102ef3cda57f909400bc99c29/packages/next-auth/src/core/routes/signin.ts#L78-L82

The type is properly `Awaitable<string | boolean>` rather than just `Awaitable<boolean>` ([`@auth/core` counterpart](https://github.com/nextauthjs/next-auth/blob/57f75c7839cf67323e67b7f09ddaa01749891e12/packages/core/src/types.ts#L216-L218))
https://github.com/nextauthjs/next-auth/blob/0e6c51adecc54d3102ef3cda57f909400bc99c29/packages/next-auth/src/core/types.ts#L295-L297
