### ISSUE TITLE
Custom pages ability as function

### ISSUE THREAD

**Issue by CRGavrila** [nextauthjs/next-auth#843]
**Summary of proposed feature**
Instead of strict string, it would be great to be a function | string for https://next-auth.js.org/configuration/pages

**Purpose of proposed feature**
For some reasons I have multiple routes for sign-in and I would like to add for each route a custom page

**Detail about proposed feature**
This function should have the next-auth route as first parameter and current route of app as second parameter

**Potential problems**
I don't think there will be any problems

**Additional context**

![image](https://user-images.githubusercontent.com/23153291/98794098-4ffda900-2411-11eb-8a39-b378cf6fea2b.png)

*Please indicate if you are willing and able to help implement the proposed feature.*
Yes

**Comment by CRGavrila** [comment]
Also for signUp callback, should be another parameter called options and should be a forward of the second argument.
call: signIn('google', { callbackUrl: url, ...otherProps })
callback: signIn: async (user:, account, profile, options)

**Comment by balazsorban44** [comment]
Hi, there could you please elaborate a bit more on your use case?
