### ISSUE TITLE
Issue with SvelteKit augmented/extended DefaultSession User types

### ISSUE THREAD

**Issue by thomasmol** [nextauthjs/next-auth#8431]
### Question 💬

I am using Authjs with Sveltekit and the Prisma adapter and am struggling to get augmented types right.

I have augmented the user type like it says in the documentation like so in `types.d.ts` in my `src/lib` dir:
```typescript
import type { DefaultSession } from '@auth/core/types';
declare module '@auth/core/types' {
	interface Session {
		user: {
			id: string;
			stripeCustomerId: string | null;
			credits: number;
			suspended_at: Date | null;
			api_key: string | null;
		} & DefaultSession['user'];
	}
}

```
This works fine if I get the session like so:
```typescript
const session: Session = await event.locals.getSession();
```

However, I get an typescript error when I use the sveltekit $page module like so:
```typescript 
const credits = $page.data.session?.user?.credits ?? 0;
```

It seems the type is DefaultSession, but it should be just Session, since that is the augmented type.
<img width="597" alt="Screenshot 2023-08-27 at 12 43 26" src="https://github.com/nextauthjs/next-auth/assets/6241551/ac0c673a-71dc-4d0a-b564-6f785fa36d17">

<img width="813" alt="Screenshot 2023-08-27 at 12 44 16" src="https://github.com/nextauthjs/next-auth/assets/6241551/0ca1a2e5-756c-471f-9e4c-0ed7508c840d">

Any ideas what I am doing wrong here?

### How to reproduce ☕️

1. setup authjs with prisma in sveltekit
2. augment/extend the DefaultSession type

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by thomasmol** [comment]
Okay I guess this is related to issues #6640 #6174 and discussion #6914. Sorry for opening another issue on this!

**Comment by balazsorban44** [comment]
Yeah, this is related to the mismatching, which causes TypeScript module augmentation to not work properly. A related issue is already open at #6226.

You can add the following (or the equivalent of other package managers) to your `package.json`:

```json
"pnpm": {
  "overrides": {
    "@auth/core": "0.12.0"
  }
}
```
