### ISSUE TITLE
Why is getServerSession in the experimental API ?

### ISSUE THREAD

**Issue by vegandiet705** [nextauthjs/next-auth#8434]
### Question 💬

Hello, 

I'm building an app with Next.js 13+ and I see that NextAuth's getServerSession is in the experimental API. Why ? How to do in prod to get the NextAuth session in server components while getServerSession in the experimental API ?

Thanks in advance

### How to reproduce ☕️

No code to reproduce.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
It has not been experimental for a while. Make sure you are on the latest version of `next-auth`.
