### ISSUE TITLE
bug: can't use `@auth/prisma-adapter` in next-auth projects

### ISSUE THREAD

**Issue by juliusmarminge** [nextauthjs/next-auth#8435]
### Adapter type

@auth/prisma-adapter

### Environment

  System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 184.33 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/Library/Caches/fnm_multishells/45960_1693158926872/bin/node
    npm: 9.6.7 - ~/Library/Caches/fnm_multishells/45960_1693158926872/bin/npm
    pnpm: 8.6.2 - ~/Library/Caches/fnm_multishells/45960_1693158926872/bin/pnpm
  Browsers:
    Safari: 16.5.2

  npmPackages:
    @next-auth/prisma-adapter: ^1.0.7 => 1.0.7
    @auth/prisma-adapter: ^1.0.1 => 1.0.1

### Reproduction URL

https://github.com/juliusmarminge/auth-core-prisma-adapter-in-next-auth

### Describe the issue

Getting a type-mismatch when using `@auth/prisma-adapter` in `next-auth`.

Not sure if this should be considered a bug or not, considering there is a `@next-auth/prisma-adapter` package that works fine, but I don't think they are getting updated anymore?

The `@auth/drizzle-adapter` works fine so don't see how the prisma adapter should be any different?

### How to reproduce

https://github.com/nextauthjs/next-auth/assets/51714798/e741b1d6-3437-40dc-a808-b29b510f518f

### Expected behavior

No type-errors when using either of the 2 adapters

**Comment by balazsorban44** [comment]
After some debugging, this is a result of the existing issue #6226

You can add the following (or the equivalent of other package managers) to your `package.json`:

```json
"pnpm": {
  "overrides": {
    "@auth/core": "0.12.0"
  }
}
```

This was fixed in https://github.com/nextauthjs/next-auth/pull/8294
