### ISSUE TITLE
SSR + useSession causes an extra network call and render cycle

### ISSUE THREAD

**Issue by joeltg** [nextauthjs/next-auth#844]
**Describe the bug**

If you use `getSession` to return a `session` prop from `getServerSideProps` and then use `useSession` in the component, the `useSession` hook will cause the page to re-render twice (three times total) even though it returns the valid session object all three times.

In addition, the hook will still cause the client to make a network request to the server after its first render, even though it already has the session object.

**Steps to reproduce**

You can observe this behavior by adding a console log to the render method of /server in [next-auth-example](https://github.com/nextauthjs/next-auth-example/) and watching network requests that it makes.

**Expected behavior**

**As far as I can tell**, the expected behavior would go like this for a server-side rendered page:

1. the incoming request causes nextjs to to call `getServerSideProps`, which calls `getSession` and returns the session in `pageProps.session` which is passed into the context provider in _app.tsx
2. nextjs renders the page on the server, where `useSession` returns `[session, false]` since it is able to retrieve the session object from the Provider context
3. the client hydrates and renders for the first time, and `useSession` again returns `[session, false]` since it is able to retrieve the session object from the Provider context
4. no additional renders or network requests are triggered

I could definitely be mistaken about what's expected - but my understanding from the [Provider documentation](https://next-auth.js.org/getting-started/client#provider) is that there should _not_ be an extra network request. 

**Screenshots or error logs**

What instead happens is that the client renders three times:

1. on the first render, useSession returns `[session, true]` (where `session` is the full valid session object)
2. the client dispatches a network request to `/session`
3. the client re-renders, useSession returns `[session, true]` (the same as the first render)
4. the network request resolves
5. the client re-renders again, useSession returns `[session, false]`

<img width="878" alt="E16F1738-F7C5-4250-8BEA-31C85B6EFB70-658-000107070BB4C866" src="https://user-images.githubusercontent.com/8454646/98854863-20f33180-2429-11eb-8a58-c66ab4e116f8.png">

<img width="1156" alt="AAD5D18A-7144-4A4F-B89C-DD71D87F0208-658-00010708B7239CDB" src="https://user-images.githubusercontent.com/8454646/98854871-251f4f00-2429-11eb-9d9a-3770605772ce.png">

As another example, if you block network requests to `/session`, then the page first renders a logged-in view (once), and then a logged-out view (twice):

<img width="422" alt="06364797-9E09-4CF4-955C-B195C73806CC-658-00010753FBBEAA16" src="https://user-images.githubusercontent.com/8454646/98855378-e5a53280-2429-11eb-9023-914740b04ec7.png">

These were tested on both development and production builds, **without** un-focusing or re-focusing the window. I can't think of anything else that could be causing the re-renders.

**Additional context**

I think that #487 originally encountered the same root problem, although their complaint was about the session _callback_ (on the sever) getting triggered several times and the discussion ended up addressing ways to avoid using the session callback altogether.

Adding a session callback with a console log to the example will show that it is invoked twice on every /server page request - once during SSR and then again when the client makes its network request after rendering once.

**Feedback**

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

Thanks so much for all your work on this project! Overall it's been a joy to use.

**Comment by amanb014** [comment]
Did you ever find the fix for this or does it absolutely require a fix on next-auth side?

**Comment by joeltg** [comment]
I think doing it "right" does require some kind of fix or re-structuring on the next-auth side, but I can share a workaround I've been using in the meantime.

The basic goal is to write our own context that provides the `session` object.

The naive approach looks like this in `_app.tsx`:

```typescript
import { getSession, Session } from "next-auth/client";

type ExpandedAppProps = AppProps & { session: Session };

const App = ({ Component, pageProps, session }: ExpandedAppProps) => {
	return (
		<MyCustomContext.Provider value={{ session }}>
			<Component {...pageProps} />
		</MyCustomContext.Provider>
	);
};

App.getInitialProps = async ({ ctx }: AppContext) => {
	const session = await getSession(ctx);
	return { session };
};
```

The problem with this is that there's no way to access the session from `getServerSideProps`, since `getServerSideProps` is only passed a `ctx: GetServerSidePropsContext` object. I don't _think_ this `ctx` is always the same (`===`) one that is passed to `App.getInitialProps`, but the request object `ctx.req` definitely is the same for both.

What does this mean? It means this is a perfect place to use a `WeakMap`!

In some common file `utils.ts`:

```typescript
import { Session, getSession } from "next-auth/client";

const sessionCache = new WeakMap<NextApiRequest, Session | null>()

export async function getCachedSession({ req }: { req: NextApiRequest }): Session | null {
  const session = sessionCache.get(req)
  if (sessionCache.has(req)) {
    return sessionCache.get(req)!
  } else {
    const session = await getSession({ req })
    sessionCache.set(req, session)
    return session
  }
}
```

then you can call `await getCachedSession(ctx)` from both `App.getInitialProps` and from `getServerSideProps` and it'll only end up calling `getSession` once.

Hope this helps! It's pretty hacky - it'd be really great if the next-auth provider could encapsulate this.

(you might have to mess around with the types a little bit since I think `ctx.req` is a `NextApiRequest` when it's in `App.getInitialProps` but just a plain `IncomingMessage` when it's in `getServerSideProps` or something...)

**Comment by balazsorban44** [comment]
Hi there! A reproduction repo with a link would be extremely helpful to debug your issue. 🙂

In your `getServerSideProps`, you should return the `session` in `props`. 
Please see the [Next.js docs](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering).

Then in  your `_app`, you should pass `pageProps.session` to the `Provider` (`{ Provider } from 'next-auth/client'`)

If you could verify the behavior you are describing with a minimal reproduction, then maybe it is something in `next-auth`.

**Comment by balazsorban44** [comment]
So I found something, which might be a bug on our end:

https://github.com/nextauthjs/next-auth/blob/cec46b0d67f8c2e2e7462da68db3209b62eff02b/src/client/index.js#L221

The `useEffect` hook has no dependency array, which makes it effectively worthless, and could be the reason that the /session API is called several times.

Also, there is something weird in the `useSession` implementation. It takes a `session` parameter, but it is not even documented.
https://github.com/nextauthjs/next-auth/blob/cec46b0d67f8c2e2e7462da68db3209b62eff02b/src/client/index.js#L145

So this might be some kind of a leftover, I think.

To check out the `useEffect` issue, would you @joeltg be comfortable with trying to go to your `node_modules/next-auth/dist/client.js`, and add an empty `[]` to the `useEffect` that needs it, and see if you get different results?

**Comment by joeltg** [comment]
The file `node_modules/next-auth/dist/client.js` is minified or something, so I'm not _100%_ sure that I'm doing it right, but as far as I can tell, adding the empty dependency array doesn't change anything in the behavior of the server-side-rendered page.

**Comment by balazsorban44** [comment]
thanks, I'll keep digging then

**Comment by ivan-kleshnin** [comment]
@balazsorban44  would be really helpful to see your opinion on the above.

Next-Auth is an amazing tool but I wish it positioned itself as primarily a BE library, with maybe few low-level FE helpers. Do you agree that higher-level FE tools, like the above `useSession`, immediately clash and compete with everything else in the ecosystem.

**Comment by EgonBolton** [comment]
Does the fact that this thread is closed mean that there are no plans to fix the provider or hook? Could it be opened again?

**Comment by thilllon** [comment]
> @[3li7u](https://github.com/3li7u) it's a classic case of "The road to hell is paved with good intentions". React and Next-Auth try to help us a bit too much...
> 
> 1. Disable strict mode of React.
> 2. `useSession` does not deduplicate queries. Don't use `SessionProvider` and `useSession` and write your own `useSession` hook like https://github.com/nextauthjs/react-query/blob/main/index.js
>    It can be based on **React-Query** or **Apollo-Client** or **URQL** or whatever you prefer.
> 
> 👉 You really want to fetch & cache all data with a single "state-management-and-fetcher" tool (of your choice):
> 
> * to rely on a single [devtools](https://react-query.tanstack.com/devtools) and see all data there!
> * to rely on a single cross-tab sync tool!
> * to not rehydrate in 2 different ways after SSR!
> 
> To me, using an out-of-the-box `useSession` feels like using an out-of-the-box `signin` form. It's approapriate as a one-off, dev-mode solution but it's not intended to be a final code.
> 
> _I especially question the design decision to have a `SessionProvider` that triggers the first fetch. In my mind no component named like `*Provider*` should ever fetch or do other effects._

Thanks, @ivan-kleshnin 
Why should we `Disable strict mode of React.` ?

**Comment by ilia-os** [comment]
@thilllon 
> Thanks, @ivan-kleshnin However, for what reasons should we `Disable strict mode of React.` ? https://reactjs.org/docs/strict-mode.html

The reason is React 18 with strict mode enabled will render components twice in dev environment.
https://beta.reactjs.org/learn/keeping-components-pure#detecting-impure-calculations-with-strict-mode

**Comment by ivan-kleshnin** [comment]
> The reason is React 18 with strict mode enabled will render components twice in dev environment.
> https://beta.reactjs.org/learn/keeping-components-pure#detecting-impure-calculations-with-strict-mode

Which doesn't help all that much in practice but surely wastes a lot of CPU, reducing your laptop battery life 😨

**Comment by gavinthomas-valtech** [comment]
> useSession does not deduplicate queries. Don't use SessionProvider and useSession

is this still the case?

Does it not cache the session information rather than calling /api/session each time?

**Comment by gautamsarawagi** [comment]
@balazsorban44  I was still experincing the issue. And this got resolved by creating a custom useMemo hook.

It would be great to get your input on this,

```
"use client";

import "@stream-io/video-react-sdk/dist/css/styles.css";
import { Room } from "../../../db/schema";
import {
  Call,
  CallControls,
  SpeakerLayout,
  StreamCall,
  StreamTheme,
  StreamVideo,
  StreamVideoClient,
} from "@stream-io/video-react-sdk";
import { useSession } from "next-auth/react";
import { useEffect, useMemo, useState } from "react";
import { generateTokenAction } from "./actions";
import { useRouter } from "next/navigation";

const apiKey = process.env.NEXT_PUBLIC_GET_STREAM_API_KEY!;

function useStableSession(){
  const {data:sessionData,status} = useSession()

  return useMemo(() => {
   return {
    session : sessionData,
    status,
    isAuthenticated: status === "authenticated"
   }
  },[sessionData?.user?.id, status])
}

export function DevFinderVideo({ room }: { room: Room }) {
  
  const {session} = useStableSession()

  const [client, setClient] = useState<StreamVideoClient | null>(null);
  const [call, setCall] = useState<Call | null>(null);

  const router = useRouter();

  useEffect(() => {
    if (!room) return;
    if (!session) {
      return;
    }
    const userId = session.user.id;
    const client = new StreamVideoClient({  
      apiKey,
      user: {
        id: userId,
        name: session.user.name ?? undefined,
        image: session.user.image ?? undefined,
      },
      tokenProvider: () => generateTokenAction(),
    });
    const call = client.call("default", room.id);
    call.join({ create: true });
    setClient(client);
    setCall(call);

    return () => {
      call
        .leave()
        .then(() => client.disconnectUser())
        .catch(console.error);
    };
  }, [session, room]);

  return (
    client &&
    call && (
      <StreamVideo client={client}>
        <StreamTheme>
          <StreamCall call={call}>
            <SpeakerLayout />
            <CallControls 
            onLeave={() => {
              router.push('/')
            }}
            />
          </StreamCall>

        </StreamTheme>
      </StreamVideo>
    )
  );
}
```
