### ISSUE TITLE
Why don't you have a tutorial for NextJS 13?

### ISSUE THREAD

**Issue by tianangthang7** [nextauthjs/next-auth#8454]
### What is the improvement or update you wish to see?

I cannot follow your document and it's very hard to understand the concept of adpter, callback. 
Can you update the tutorial for latest NextJS version using App Router? 

### Is there any context that might help us understand?

Missing the code example for App Router

### Does the docs page already exist? Please link to it.

https://authjs.dev/guides/adapters/using-a-database-adapter

**Comment by balazsorban44** [comment]
Hi, there is no fundamental difference between how you use an adapter with Next.js 13. If you are having a specific issue, please open a bug report with a minimal reproduction.

As for the example, #7443 is going to update it, for now, the relevant documentation is at:

https://next-auth.js.org/configuration/nextjs
https://next-auth.js.org/configuration/initialization
