### ISSUE TITLE
Signout doesn't ACTUALLY sign user out of Cognito

### ISSUE THREAD

**Issue by donkee** [nextauthjs/next-auth#8462]
### Provider type

Cognito

### Environment

```
  System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 198.22 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
  Browsers:
    Chrome: 116.0.5845.110
    Safari: 16.5.2
```

### Reproduction URL

N/A

### Describe the issue

When using the `signout()` method, it doesn't actually sign the user out. What I mean is, the cookie is correctly removed from the browser for the site, but the Cognito hosted UI still has its own copy of the cookie, so it will automatically log the user back in.

### How to reproduce

Use the Cognito provider with the hosted UI.

### Expected behavior

The user gets logged out and has to re-enter their credentials to log back in

**Comment by donkee** [comment]
Is the only option to use Credentials sign-in? Is that anti-OAuth, though? How would we handle MFA in that case?

**Comment by balazsorban44** [comment]
This is expected. Logging out of your app won't log you out of the Identity Provider. See #3938 for more details/possible solutions.

**Comment by Ryanv030** [comment]
@donkee I'm just running into this same issue now. Curious, which direction did y'all end up going?

**Comment by alaksana96** [comment]
@Ryanv030 I encountered this today and I ended up following a comment on a different [issue](https://github.com/nextauthjs/next-auth/discussions/3938#discussioncomment-8251898), which worked for me

**Comment by adrfinance** [comment]
Have you found a solution? I am stuck with that issue and can't logout from Cognito.
