### ISSUE TITLE
Nextauth trying to use HTTPS URLs when running on localhost.

### ISSUE THREAD

**Issue by mruhlin** [nextauthjs/next-auth#8467]
### Environment

```
  System:
    OS: macOS 13.2.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 223.08 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.5.1 - /opt/homebrew/bin/node
    npm: 9.8.0 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 116.1.57.53
    Chrome: 116.0.5845.140
    Safari: 16.3
```

### Reproduction URL

https://github.com/mruhlin/the-challenge-vercel/tree/69e714404128d672f9dba1723e32315c977acffa

### Describe the issue

I'm trying to build a CRUD app using NextAuth (following [this tutorial](https://vercel.com/guides/nextjs-prisma-postgres#step-6.-set-up-github-authentication-with-nextauth)), just running it on my dev machine at `http://localhost:3000` for now, but can't get the login piece working.

When I go to my sign in URL and click the "login with github" button, I'm redirected to `https://localhost:3000/api/auth/signin/github` and get an SSL error.  Looks like almost the right url, but I can't figure out what's switching it to HTTPS instead of plain old HTTP.

The rendered HTML for that button looks like:
```
<form action="https://localhost:3000/api/auth/signin/github" method="POST">
  <input type="hidden" name="csrfToken" value="03b1b1b8156cd12d0e63b7ed9f2404b62668fc449e976edfecfa530385fc6272">
  <input type="hidden" name="callbackUrl" value="https://localhost:3000">

  <button type="submit" class="button" style="--provider-bg: #fff; --provider-dark-bg: #000; --provider-color: #000; --provider-dark-color: #fff;">
    <img loading="lazy" height="24" width="24" id="provider-logo" src="https://authjs.dev/img/providers/github.svg">
    <img loading="lazy" height="24" width="24" id="provider-logo-dark" src="https://authjs.dev/img/providers/github-dark.svg">
    <span>
      Sign in with GitHub
    </span>
  </button>
</form>
```

As you can see, both the form `action` prop and the hidden `callbackUrl` input are pointing to https URLs.  
(Should that callbackUrl also point to the `/api/auth` path, not just the root path?)

I've tried this with both GitHub and Google providers, and seen the same result with either.

My `.env` file sets `NEXTAUTH_URL` to `NEXTAUTH_URL=http://localhost:3000/api/auth`

My auth handler code is pretty straightforward:
```
import { NextApiHandler } from 'next';
import NextAuth from 'next-auth';
import { PrismaAdapter } from '@next-auth/prisma-adapter';
import GitHubProvider from 'next-auth/providers/github';
import GoogleProvider from 'next-auth/providers/google';
import prisma from '../../../lib/prisma';

const options = {
  providers: [
    GitHubProvider({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET,
    }),
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET
    })
  ],
  adapter: PrismaAdapter(prisma),
  secret: process.env.SECRET
};

const authHandler: NextApiHandler = (req, res) => NextAuth(req, res, options);
export default authHandler;
```

### How to reproduce

- Build a new app, following the linked tutorial.
- run in localhost using `npm run dev`
- Go to `http://localhost:3000/api/auth/signin` to get to a login page
- Click "sign in with GitHub" link (or any other oauth provider)

### Expected behavior

Go to a github login page, not an SSL error.

**Comment by mruhlin** [comment]
(sorry, I just realized the linked repo was set to private.  Made it public just now)

**Comment by balazsorban44** [comment]
FWIW, you don't need to set NEXTAUTH_URL for local development or when deployed to Vercel.

A common issue with local https we've seen is if you have `VERCEL=1` set in your env file. We use this value in production to determine that you are hosting on Vercel, but it interferes locally. You can comment it out.

**Comment by hamirmahal** [comment]
I just ran into the `ERR_SSL_PROTOCOL_ERROR` issue a few minutes ago and fixed it by commenting out `VERCEL="1"` in `.env`. Thanks for the suggestion.

I think I got `VERCEL="1"` from `vercel env pull .env`, which is what https://vercel.com/guides/nextjs-prisma-postgres#step-2-set-up-your-vercel-postgres-database said to do.

**Comment by Jdruwe** [comment]
I don't have a VERCEL env. variable set, also none of the others:

>>> VERCEL undefined
>>> NEXTAUTH_URL undefined
>>> AUTH_URL undefined

Still don't get why this happens
