### ISSUE TITLE
[middleware] Protected routes working in local, but not in production

### ISSUE THREAD

**Issue by juskek** [nextauthjs/next-auth#8469]
### Environment

  System:
    OS: macOS 13.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 89.79 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: 2023.08.07.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 106.1.44.112
    Chrome: 116.0.5845.140
    Edge: 114.0.1823.67
    Safari: 16.2

### Reproduction URL

https://github.com/Theodo-UK/OmniLog/tree/fix/login-feature-not-protecting-routes/front

### Describe the issue

I have the following file `./src/middleware.ts` on the same level as my `app/` dir:
```typescript
export { default } from "next-auth/middleware";
```
---
In local, routes are protected, see following GIF
![local](https://github.com/nextauthjs/next-auth/assets/57725347/875f558f-715d-489d-abe8-0de87a8b1837)

---
In production, sign in api is working, but routes are not protected, see following GIF
![prod](https://github.com/nextauthjs/next-auth/assets/57725347/34f96017-dfac-409c-ae23-828c6fc48b69)

### How to reproduce

You can follow the steps in the [README](https://github.com/Theodo-UK/OmniLog/tree/fix/login-feature-not-protecting-routes/front) to deploy locally and in staging, although you will need an AWS account!

### Expected behavior

Routes should be protected in production, as they are in local

**Comment by balazsorban44** [comment]
Could you verify if it works when deployed to something like Vercel? It might be a platform issue rather than a library bug. :thinking:

**Comment by juskek** [comment]
hey @balazsorban44 , thanks for the clue! 

Managed to fix it now :) 
- I found this issue with [OpenNext not being able to deploy serverless functions + middleware with Next 13.4.13+](https://github.com/sst/open-next/issues/176),
- Downgraded to 13.4.12 until this issue with OpenNext is fixed
- redeployed and it's working! 

For anyone checking this solution, the stack we were having issues with was:
- NextJS
- NextAuth + middleware
- OpenNext
