### ISSUE TITLE
Invalid `profile` type on `callbacks.signIn`

### ISSUE THREAD

**Issue by nbouvrette** [nextauthjs/next-auth#8472]
### Environment

N/A

### Reproduction URL

N/A

### Describe the issue

The[ current type](https://github.com/nextauthjs/next-auth/blob/f62162791497f7273f5854c3283f2c1d09493b4b/packages/next-auth/src/core/types.ts#L101) for the profile parameter when using the `signIn` `callbacks` is set to `Profile`.

This is the default user profile type:

```ts
export interface Profile {
  sub?: string
  name?: string
  email?: string
  image?: string
}
```

But in fact what is returned is the profile from Providers, for example `LinkedInProfile` which does not even have a `sub` property but that includes an `id` property.

All provider seem to use whichever type they want for their profile.

I'm not sure what would be the best solution for this situation but maybe in the meantime the type for profile should be updated to `Record<string, unknown>` until a better solution is found?

### How to reproduce

Just follow the types in the code and it will be easy to spot the issue.

### Expected behavior

I would expect ideally to have the correct type of the object being passed, but if it's too complex it would be great to at least fix the incorrect type by using something more generic.

**Comment by balazsorban44** [comment]
The default values are based on the standard OAuth claims, but marked optional because as you say, sometimes providers don't correctly follow these either.

To change/augment the profile type you can check out https://next-auth.js.org/getting-started/typescript#popular-interfaces-to-augment
