### ISSUE TITLE
Custom Sign in page callbackurl error

### ISSUE THREAD

**Issue by Butterfnger** [nextauthjs/next-auth#8476]
### Question 💬

I use nextjs with next-auth as login solution. 
Everything works fine until the point where I use a custom login page. I have changed the following things for this:

- added my custom page to AuthOptions
- setup middleware with export { default } ...

Kind regards

### How to reproduce ☕️

This is my code:

`./src/app/api/auth/[...nextauth]/route.ts`

```
import NextAuth from "next-auth";
import { authOptions } from "@/lib/auth";

const handler = NextAuth(authOptions);

export { handler as GET, handler as POST };
```

`./src/app/lib/auth.ts`

```
import { NextAuthOptions } from "next-auth";
import GoogleProvider from "next-auth/providers/google";

export const authOptions: NextAuthOptions = {
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID as string,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET as string,
    }),
  ],
  pages: {
    signIn: "/signin",
  },
};
```

`./src/middleware.ts`

```
export { default } from 'next-auth/middleware'
```

Login button:
`<button onClick={() => signIn('google')}>Sign in</button>`

<img width="1728" alt="Screenshot 2023-08-28 at 18 01 06" src="https://github.com/nextauthjs/next-auth/assets/134048992/c549e1d9-42f9-4560-b89f-d5f619d7b2c3">
<img width="497" alt="Screenshot 2023-08-28 at 18 14 15" src="https://github.com/nextauthjs/next-auth/assets/134048992/03f2c521-5ccb-44c5-a8ce-482a86a07c8b">
<img width="1215" alt="Screenshot 2023-09-02 at 12 32 32" src="https://github.com/nextauthjs/next-auth/assets/134048992/06a9ad04-2e32-4c6f-98b6-8f020e31055f">

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
https://next-auth.js.org/configuration/nextjs#pages

**Comment by Butterfnger** [comment]
@balazsorban44 

I don't know if you read my code above, but I use the app router and have added the pages exactly as shown in the docs.
