### ISSUE TITLE
How to extend the Session interface definition for `@auth/sveltekit`?

### ISSUE THREAD

**Issue by hollg** [nextauthjs/next-auth#8479]
### Question 💬

I'm using `@auth/sveltekit` to enable Spotify login for my application. I need access to the `access_token` from Spotify for features of my application which call Spotify's API. Therefore, I'd like to add it to the session object. Can anyone explain how to do that? I've tried adding a custom `.d.ts` file but must be approaching it incorrectly.

### How to reproduce ☕️

I'm adding the `access_token` to the session object here:

```ts
SvelteKitAuth({
  secret: AUTH_SECRET,
  providers: [
    Spotify({
	clientId: SPOTIFY_CLIENT_ID,
	clientSecret: SPOTIFY_CLIENT_SECRET
    })
  ],
  callbacks: {
    jwt: async ({ token, account }) => {
      if (account?.access_token) {
	token.access_token = account.access_token;
      }
      return token;
    },
    session: async ({ session, token }) => {
      
      if (session.user && token.access_token) {
        // @ts-ignore
	session.user.accessToken = token.access_token;
      }
      return session;
    }
  }
});
``` 

And I have added the following to `types/@auth/core/types.dts`:

```ts
import type { Session, DefaultSession } from '@auth/core/types';

declare module '@auth/core/types' {
  interface Session {
    user?: {
      accessToken?: string;
    } & DefaultSession['user'];
  }
}

```

As far as I can tell, `@auth/sveltekit` gets the `Session` definition from `@auth/core` which is why I've written it this way. But it doesn't work! The TS compiler isn't recognising my new version of `Session` in the code where I add `accessToken` to `session.user` or in any code where I try to read it.

I got this far by reading the docs for TypeScript in `next-auth` and assuming that the same thing applies in `@auth/sveltekit`: https://next-auth.js.org/getting-started/typescript. I notice that in those docs, the custom type file targets the definition from the same module that is used directly in code, which in my case would be `@auth/sveltekit`, but that didn't work for me either.

Can anyone explain the correct way to go about this?

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by darowsluk** [comment]
Some additional info:
1. The `session` callback uses module:
`@auth/sveltekit/node_modules/@auth/core/types` and not `@auth/core/types`
2. session parameter is of type `DefaultSession` instead of `Session`

The following snippet fixes points above, but does not augment `user` parameter.
```typescript
declare module '@auth/sveltekit/node_modules/@auth/core/types' {
  interface DefaultSession {
    user?: {
      accessToken?: string;
    } & DefaultSession['user'];
  }
}

``` 
Unfortunately I am not an expert in typescript module augmenting, so I am stuck here.

**Comment by michaelcontento** [comment]
I have the same issue. 

💻 **Code I use**

```javascript
import type { DefaultSession } from '@auth/core/types'

declare module '@auth/core/types' {
    interface Session {
        user?: {
            id: string
        } & DefaultSession['user']
    }
}
```

It's basically the same idea / trick as @hollg is using


✅ **Everything fine with**

| Package | Version |
|------------|--------|
| @auth/core | 0.10.0 |
| @auth/sveltekit | 0.3.6 |

❌ **No longer working**

As soon as I either upgrade `@auth/core` to `0.10.1` **or** `@auth/sveltekit` to `0.3.7` TypeScript starts complaining.




A solution would be awesome, as I think this is a quite common thing / pattern. Or am I doing something completely wrong? 🤔

**Comment by jameswoodley** [comment]
If you're using `pnpm` you can add this to your package json, and hopefully you'll find this falls into place

```
"pnpm": {
    "overrides": {
        "@auth/core": "latest"
    }
}
```

**Comment by simbazzczz** [comment]
> If you're using `pnpm` you can add this to your package json, and hopefully you'll find this falls into place
> 
> ```
> "pnpm": {
>     "overrides": {
>         "@auth/core": "latest"
>     }
> }
> ```

Not working for me

**Comment by dlbnco** [comment]
I also extending my `Session`, but so far I only need to access it from `getServerSession`, so I just created a reference to such function with my custom session object as type parameter:

```ts
import { Session, getServerSession } from 'next-auth';

type CustomSession = Session & {
  user?: {
    id?: string
  }
}

export const getServerCustomSession = getServerSession<{}, CustomSession>
```

**Comment by simpros** [comment]
I also have that issue, a fix would be great :)

**Comment by arackaf** [comment]
After upgrading to @auth/core 0.19.0, and most importantly, making sure there was no old versions hanging around - check the lock file - if you have instances of 0.18, either just remove it from package.json and run npm i, and then re-run npm i @auth/core, or add an override.

With that done, this works for me 

```ts
import { DefaultSession } from "@auth/core/types";

declare module "@auth/core/types" {
  interface Session {
    userId: string;
    provider: string;
    legacySync: boolean;
    user: DefaultSession["user"];
  }
}
```

**Comment by ndom91** [comment]
Yeah with `"@auth/sveltekit": "^0.5.0"` and `"@auth/core": "^0.19.0"` this seems to be working for me:

```ts
// /src/app.d.ts
// See https://kit.svelte.dev/docs/types#app
// for information about these interfaces
// and what to do when importing types
declare namespace App {
  interface Locals {
    getSession: () => Promise<Session>
  }
  // interface Platform {}
  // interface PrivateEnv {}
  // interface PublicEnv {}
}

declare module "@auth/core/types" {
  interface Session {
    user: {
      userId?: string;
    } & DefaultSession['user'];
  }
}
```

**Comment by HalfdanJ** [comment]
This snippet above worked well for me in version `0.5.0` but broke in `0.5.1`, anyone find a new workaround?

**Comment by ndom91** [comment]
This shuold do the trick with `0.5.1+`. `0.8.0` has been working well for me..

```ts
// Requires @auth/sveltekit@0.5.1+
declare module "@auth/sveltekit" {
  interface User {
    userId: string
  }
}
```

Also you shouldn't need to install the `@auth/core` package as a consumer at all, the `@auth/sveltekit` package reexports all providers as well as additional types. Some random examples:

```ts
import { GitHub } from "@auth/sveltekit/providers"
import type { AdapterAccount } from "@auth/sveltekit/adapters" // just merged, will ship soon
import type { Account, Session } from "@auth/sveltekit"
```

**Comment by balazsorban44** [comment]
https://authjs.dev/getting-started/typescript?frameworks=sveltekit
