### ISSUE TITLE
Accessing OAuth state post sign-in

### ISSUE THREAD

**Issue by TejasQ** [nextauthjs/next-auth#848]
**Your question**
Hi, I love the great work done on this project. Thank you all very, very much. 

My question is about the [`state` parameter](https://tools.ietf.org/html/rfc6749#section-4.1.1) from the OAuth spec. Traditionally, one would pass it to an OAuth provider, say Google like so

```
https://accounts.google.com/o/oauth2/v2/auth
  ?prompt=consent
  &access_type=offline
  &response_type=code
  &state=hello
```

After login, Google redirects to the callback URL with the state attached to the querystring, ready to be processed by the client. 

I have searched a lot for a way to access this parameter with next-auth, but have not yet found out how. 

My question is twofold:

1. Is it currently possible?
1. Where can I add it if not? I'd love to make a PR.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [x] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by callamwilliams** [comment]
Something like

```jsx
export async function getServerSideProps(ctx) {
    const { query: { state} } = ctx;
    const response = await fetch(`https://accounts.google.com/o/oauth2/v2/auth
      ?state=${state}`);
    const data = await response.json();

    return {
        props: {
            data
        },
    };
}
```

Can see the state key in the ctx, so imagine thats what you need
