### ISSUE TITLE
SequelizeAdapter types mismatch

### ISSUE THREAD

**Issue by mp3por** [nextauthjs/next-auth#8480]
### Adapter type

@auth/sequelize-adapter

### Environment

  System:
    OS: macOS 13.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 67.72 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.10.0 - ~/.nvm/versions/node/v18.10.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.10.0/bin/npm
    pnpm: 8.7.0 - /opt/homebrew/bin/pnpm
    Watchman: 2023.08.28.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 116.1.57.57
    Chrome: 116.0.5845.96
    Safari: 16.6

### Reproduction URL

https://laughing-doodle-jp4x59jrr2pp.github.dev/

### Describe the issue

Typescript complains that there is a missmatch between the expected from NextAuth Adapter and the SequelizeAdapter as shown by the error.

### How to reproduce

Just install the dependencies and try to configure NextAuth with SequelizeAdapter.

### Expected behavior

I can compile the project.

**Comment by balazsorban44** [comment]
should be good in the latest version, please upgrade. if the problem persists, please open a ne issue and add a reproduction. note, the one you linked was private.
