### ISSUE TITLE
Can NextAuthJS be used by `static build`

### ISSUE THREAD

**Issue by ARiyou2000** [nextauthjs/next-auth#8503]
### Question 💬

I'm developing an embedded system UI for an IoT device using NextJS and NGINX, with the following `next.config.js`:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  output: "export",
  images: {
    unoptimized: true,
  },
module.exports = nextConfig;
```

so I have no access to the next.js server, `API routes`, and `Route handlers`. [read more here.](https://nextjs.org/docs/app/building-your-application/deploying/static-exports#unsupported-features)

Can I use NextAuthJS together with `static build`

by the way, it wasn't supposed to build staticly. but we are short on CPU and memory on our devices so we have no choice.

### How to reproduce ☕️

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  output: "export",
  images: {
    unoptimized: true,
  },
module.exports = nextConfig;
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
No. NextAuth.js needs a secure server to be able to function. You will find this to be the case with any other secure auth solutions.
