### ISSUE TITLE
Does logging in via fetch or axios store session as it does with signIn hook?

### ISSUE THREAD

**Issue by amunim** [nextauthjs/next-auth#8505]
### Question 💬

The problem I have is that I have a custom axios instance and my login response reads the cookies from my back-end server and sets the cookies on my response header.

If I use the `signIn` hook, this obviously defeats the purpose because the credentials are lost and I don't have access to those headers.
Is there a way I use my own custom axios instance to make a request to `api/auth/login` this way I get my cake but how to share it with next-auth that I am authenticated and make it store in the session my JWT and the user details as usual.

### How to reproduce ☕️

Create a new project...

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
You should not make a request to another API route. Just import the logic that this endpoint runs for better performance by skipping a network call. this is the official Next.js recommendation as well when you might want to make a request to the same app on the server-side.

hard to say more without seeing your code.
