### ISSUE TITLE
Logout initiated by IdentityServer

### ISSUE THREAD

**Issue by johannasvovu** [nextauthjs/next-auth#8509]
### Question 💬

I have three applications that participate in a Single Sign-On architecture, all authenticating through a common IdentityServer:

Application A uses next-auth.
Applications B and C do not use next-auth.

While the application that leverages next-auth enables seamless login and federated logout, logging out from the other applications does not trigger a federated logout in the next-auth application. 

Currently, a user can initiate a logout from any of the three applications. When logout is initiated from Application A (which uses next-auth), federated logout works as expected. However, initiating logout from Applications B or C doesn't notify Application A, leaving the user in a potentially authenticated state there.

I have tried to directly call the /api/auth/signout endpoint, but this is proving challenging because this endpoint returns HTML content requesting consent to sign out. Attempting to manually delete cookies from Application A did not work, the cookies persisted.

How can I effectively notify Application A to perform a logout when the logout is initiated from Applications B or C?
Is there a way to programmatically invoke the logout functionality available in next-auth from other applications?

### How to reproduce ☕️

I do not believe code snippets would be helpful in this situation. Please correct me if I'm wrong :)

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
#3938
