### ISSUE TITLE
Extract types into a separate package for Custom Adapters

### ISSUE THREAD

**Issue by mp3por** [nextauthjs/next-auth#8526]
### Description 📓

I need only the types related for the adapters to be use them as base interfaces for my models in my custom backend. 

Use Case:
I have a separate backend which is responsible for the business logic and I use NextJS only as a FrontEnd application - it holds the presentation logic, but basically all the calls in the `app/api` folder are redirects to the backend. I have implemented my custom adaptor to connect NextAuth to my BackEnd and have created the required database models based on the [models](https://authjs.dev/reference/adapters#models). 

In my Backend code I have copy-pasted the model's definitions from the AdapterUser, AdapterAccount ... types. However this is very problematic because if you ever change something in the models I will not know. So I was thinking of installing the next-auth package with the same version on my BE and extending the model's types with my own definitions to ensure that if something ever changes my app will not compile and I will know.

However next-auth does not compile using normal tsc (obviously since it is designed to work with nextjs and not a simple nodejs server) and thus I can not use the types from `next-auth` package. 

I believe the ability to import in the custom backend those types will make life easier for anyone who is implementing custom adapters to connect to currently running systems, because it will be easier to be consistent with the library.

`auth.controller.ts`
```
// what the FE sends
import {AdapterAccount, AdapterSession, AdapterUser, VerificationToken} from 'next-auth/adapters';

// my custom models
import {AuthUser} from '../../models/user/auth-user.model';
import {AuthAccount} from '../../models/account/auth-account.model';
import {AuthSession} from '../../models/session/auth-session.model';
import {AuthVerificationToken} from '../../models/verification-token/auth-verification-token.model';

export interface IAuthenticationController {
  createUser(data: Omit<AdapterUser, 'id'>): Promise<AuthUser>;
  getUserByEmail(data: Pick<AdapterUser, 'email'>): Promise<AuthUser | null>;
  getUserByAccount(data: Pick<AdapterAccount, 'provider' | 'providerAccountId'>): Promise<AuthUser | null>;
  getUser(data: Pick<AdapterUser, 'id'>): Promise<AuthUser | null>;
  updateUser(data: Partial<AdapterUser> & Pick<AdapterUser, 'id'>): Promise<AuthUser>;
  deleteUser(data: Pick<AdapterUser, 'id'>): Promise<AuthUser | null>;
  linkAccount(data: AdapterAccount): Promise<AuthAccount>;
  unlinkAccount(data: Pick<AdapterAccount, 'provider' | 'providerAccountId'>): Promise<AuthAccount | null>;
  createSession(data: Pick<AdapterSession, 'sessionToken' | 'userId' | 'expires'>): Promise<AuthSession>;
  getSessionAndUser(data: Pick<AdapterSession, 'sessionToken'>): Promise<{session: AuthSession; user: AuthUser} | null>;
  updateSession(data: Partial<AdapterSession> & Pick<AdapterSession, 'sessionToken'>): Promise<AuthSession | null>;
  deleteSession(data: Pick<AdapterSession, 'sessionToken'>): Promise<AuthSession | null>;
  createVerificationToken(verificationToken: VerificationToken): Promise<AuthVerificationToken>;
  useVerificationToken(data: Pick<VerificationToken, 'identifier' | 'token'>): Promise<AuthVerificationToken | null>;
}
```

`auth-user.model.ts`
```
import {AdapterUser} from 'next-auth/adapters';
import {fbAssertType} from '../../../../shared/utils/asserts/assert-type.utils';
import {OptionalToNullable} from '../../../../shared/utils/types/optional-to-nullable';


export interface AuthUserAttributes extends Omit<OptionalToNullable<AdapterUser>, 'id'> {
  id: number;
}

export interface AuthUserConstructorParameters extends AuthUserAttributes {}

export class AuthUser implements AuthUserAttributes {
  email: string;
  emailVerified: Date | null;
  id: number;
  image: string | null;
  name: string | null;

  constructor(parameters: AuthUserConstructorParameters) {
    fbAssertType('parameters.email', parameters.email, String);
    fbAssertType('parameters.emailVerified', parameters.emailVerified, [null, Date]);
    fbAssertType('parameters.id', parameters.id, Number);
    fbAssertType('parameters.image', parameters.image, [null, String, undefined]);
    fbAssertType('parameters.name', parameters.name, [null, String, undefined]);

    this.email = parameters.email;
    this.emailVerified = parameters.emailVerified;
    this.id = parameters.id;
    this.image = parameters.image ?? null;
    this.name = parameters.name ?? null;
  }
}

```

### How to reproduce ☕️

not relevant

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
you can import types only using the `type` import modifier, for example:

`import type {AdapterAccount} from "next-auth/adapters"`.

This should not compile `next-auth`.

We would actually recommend `@auth/core/adapters` for types though.

**Comment by mp3por** [comment]
@balazsorban44 what is the difference between `next-auth/adapters` and `@auth/core/adapters` ?
