### ISSUE TITLE
getProviders doesn't return up to date values

### ISSUE THREAD

**Issue by PedroCarreiras** [nextauthjs/next-auth#8530]
### Environment

System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 13.54 GB / 15.59 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 9.7.1 - ~/.nvm/versions/node/v16.15.1/bin/npm

### Reproduction URL

N/A

### Describe the issue

The getProviders() function doesn't return up to date values, further explanation can be found on discussion #8528.

### How to reproduce

Create a custom sign in page using getProviders (server side) to generate each login button accordingly. Access the login page through the browser. Implement a new provider. Visit the sign in page again.

### Expected behavior

Using getProviders() should return all providers. (Caching should probably only happen in production?)

**Comment by EggsLeggs** [comment]
I had a similar issue. Weirdly enough, sticking getProviders in a suspense tag solved the issue

**Comment by balazsorban44** [comment]
sounds like a caching issue. no repro, so canot do much. please open a new issue with one.
