### ISSUE TITLE
Access and Refresh tokens not updating

### ISSUE THREAD

**Issue by sdan** [nextauthjs/next-auth#854]
**Describe the bug**
Access and refresh tokens aren't updating in the DB if the following scenario happens in twitter:

User revokes application via Twitter settings, user signs in / authorizes the application again, but access/refresh tokens aren't

**Steps to reproduce**
Try it with the example project. Although it doesn't use refresh/access tokens, you can see in the DB it doesn't update.

**Expected behavior**
Access and refresh tokens should update every time a user logs in

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by EthanNC** [comment]
I have this problem with Battlenet also. My solution is to override the `signIn` callback and use a provided api route to check if the token has expired and if so get a new one and update it. Here is my code:
```
    signIn: async (user, account, profile) => {
      console.log(account.accessToken);
      const checkRes = await fetch(
        `https://us.battle.net/oauth/check_token?token=${account.accessToken}`,
        {
          method: "POST",
        }
      );
      console.log("Status:", checkRes.status);
      if (checkRes.status === 200) {
        const res = await prisma.account.update({
          where: { id: user.id },
          data: {
            accessToken: account.accessToken,
          },
        });
      }
      return Promise.resolve(true);
    },
```
My issue now is if the user doesn't already exist (I.E. its a new user) this code bugs and the none of the tables update with the new user. Still have to figure this out, but hopefully this points you in the right direction.

**Comment by BrennenRocks** [comment]
This is my solution to this problem and the problem in #735 

```
const options: InitOptions = {
  providers: [
    Providers.BattleNet({
      clientId: process.env.BATTLENET_CLIENT_ID!,
      clientSecret: process.env.BATTLENET_CLIENT_SECRET!,
      region: 'us',
      scope: 'openid wow.profile',
      authorizationUrl: "https://us.battle.net/oauth/authorize?response_type=code"
    })
  ],
  database: process.env.MONGODB_URI,
  callbacks: {
    signIn: async (user, account, profile) => {
      // Next-Auth does not update the access token if the user has revoked the token then relogs in

      // We manually update the access token
      // BattleNet currenlty does not have a refresh token. No need to update it as well

      await dbConnect();
      await Account.findOneAndUpdate({ providerAccountId: account.id }, { accessToken: account.accessToken });

      return Promise.resolve(true);
    }
  }
};
```

**Comment by glockjt** [comment]
This is still an issue any updates on it?
