### ISSUE TITLE
Is there any way we can disable redirecting to Authjs UI and receive the error messages ourselves?

### ISSUE THREAD

**Issue by Aslemammad** [nextauthjs/next-auth#8541]
### Question 💬

First of all, Thank you so much for the amazing library.

I'm using Authjs and the [qwik integration](https://qwik.builder.io/docs/integrations/authjs/). When calling `signin.submit` with the credentials provider for example, I don't want the user to be redirected to the `http://localhost:5173/api/auth/error?error=CallbackRouteError` page. Instead, I want to have the error as the returning value from the `submit` function so I can show it in our own Sign in/up modal.

### How to reproduce ☕️

It's just a question, I don't find the documentation for it.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
That integration is not maintained by us currently. Please open an issue at https://github.com/BuilderIO/qwik
