### ISSUE TITLE
Jwt not found when using custom cookie name

### ISSUE THREAD

**Issue by ghs** [nextauthjs/next-auth#8543]
### Environment

Latest version of node, npm, next, react and next-auth. Mac OS Ventura with any browser.

### Reproduction URL

localhost and anywhere next-auth-example can be deployed

### Describe the issue

The current documentation about cookies states:
"You can override the default cookie names and options for any of the cookies used by NextAuth.js.".
https://next-auth.js.org/configuration/options#description-12

This is not the case when JWT is used because there are hard-coded lines for specific cookie names:
https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/jwt.ts#L119

If the cookies names are changed, no cookie will be found with the expected from the code, thus the token will not be returned.

### How to reproduce

Change cookie names for NextAuthOptions for your nextauth instance and try to retrieve the token.

### Expected behavior

Using `getToken` should return correctly when custom cookie names are used.

**Comment by balazsorban44** [comment]
That's a default value if you did not pass `cookieName`. See right above

https://github.com/nextauthjs/next-auth/blob/b9e9722b7445ec3781b5e64b6564ea01ab3abe95/packages/core/src/jwt.ts#L118
