### ISSUE TITLE
OAuth 1.0 expects "oauth token secret" when requesting the access_token (for trello authenticatino)

### ISSUE THREAD

**Issue by boertel** [nextauthjs/next-auth#855]
**Describe the bug**
When trying to use Trello OAuth 1.0 flow, it returns: 
```
[next-auth][error][oauth_v1_get_access_token_error] [ { statusCode: 400, data: 'Invalid Signature' }, undefined ]
```

**Steps to reproduce**
Here is the custom provider that I'm using:
```
{
      id: "trello",
      name: "Trello",
      type: "oauth",
      version: "1.0",  // try both 1.0 and 1.0A
      scope: "read,write,account",
      accessTokenUrl: 'https://trello.com/1/OAuthGetAccessToken',
      requestTokenUrl: 'https://trello.com/1/OAuthGetRequestToken',
      authorizationUrl: 'https://trello.com/1/OAuthAuthorizeToken',
      profileUrl: 'https://api.trello.com/1/members/me/',
      params: { expiration: 'never' },
      profile: (profile) => ({}),
      clientId: process.env.TRELLO_CLIENT_ID,
      clientSecret: process.env.TRELLO_CLIENT_SECRET,
    }
```
You can get your own credentials get here: https://trello.com/app-key/

**Expected behavior**
Being able to connect with trello authentication

**Investigation**
After digging into the code, I think I found what is missing to make Trello OAuth 1.0 and probably other oauth1.0 working. It isn't clear why twitter works (knowing how every company interprets OAuth spec, that is probably why :) )

In order to make sure that my credentials and configuration were correct, I used: https://github.com/adunkman/node-trello to get a user token, and it worked! They both use `oauth` so that made it easy to spot the difference. Here it is:

https://github.com/nextauthjs/next-auth/blob/5126f4e3428f2b4b8ebdd38b10066edfdd4ea2fa/src/server/lib/oauth/callback.js#L108

When calling: `client.getOAuthAccessToken` the second argument needs to be the `oauth token secret` generated when calling: `client.getOauthRequestToken`
https://github.com/nextauthjs/next-auth/blob/5126f4e3428f2b4b8ebdd38b10066edfdd4ea2fa/src/server/lib/signin/oauth.js#L33
The 3rd argument of `getOauthRequestToken` is `oauth_token_secret`
 
https://github.com/ciaranj/node-oauth/blob/a7f8a1e21c362eb4ed2039431fb9ac2ae749f26a/lib/oauth.js#L551

Now I'm a bit unclear to know how I would fix that:
1. store that secret in the session? is that safe? do I even have access to the session in these 2 functions?
2. rely on a key-value store like redis to store that?

**Comment by nikitalk** [comment]
I have the same issue with Etsy provider:
``` {
      id: 'etsy',
      name: 'etsy',
      type: 'oauth',
      version: '1.0',
      scope: 'email_r',
      accessTokenUrl: 'https://openapi.etsy.com/v2/oauth/access_token',
      requestTokenUrl:
        'https://openapi.etsy.com/v2/oauth/request_token',
      authorizationUrl: 'https://www.etsy.com/oauth/signin',
      profileUrl: 'https://openapi.etsy.com/v2/users/__SELF__',
      profile: (profile) => {
        return {
          id: profile.id,
          /*  email: profile.primary_email,
          name: profile.login_name, */
        };
      },
      clientId: process.env.ETSY_ID,
      clientSecret: process.env.ETSY_SECRET,
    },```

**Comment by nikitalk** [comment]
Hi, friends! Are there any solutions of this issue?

**Comment by mjewell** [comment]
I ran into this same problem too. Is it insecure to send the token secret back here `https://github.com/nextauthjs/next-auth/blob/5126f4e3428f2b4b8ebdd38b10066edfdd4ea2fa/src/server/lib/signin/oauth.js#L37`

And then send it back in the query params here https://github.com/nextauthjs/next-auth/blob/5126f4e3428f2b4b8ebdd38b10066edfdd4ea2fa/src/server/lib/oauth/callback.js#L19

**Comment by aksanoble** [comment]
I finally found this solution to this. NextAuth incorrectly referred to accessTokenSecret as refreshToken. There is no refreshToken for oAuth1.0. Please use the value present in refreshToken as accessTokenSecret. I've also raised an issue #1321 for this.

**Comment by joe-bell** [comment]
@nikitalk hey, did you find a solution to your custom `etsy` provider?

**Comment by balazsorban44** [comment]
@mjewell I am curious what you meant by being insecure. Do you see any problems with the currently merged PR at https://github.com/nextauthjs/next-auth/pull/1322 ? I checked it with Twitter and it did seem to work.

**Comment by mjewell** [comment]
I'm not sure, I was just asking if it's ok to expose the token/secret that way since I'm not super familiar with this stuff. If the maintainers of this repo merged it then I assume you're good?

**Comment by balazsorban44** [comment]
I'm (one of) the maintainer of this repo. 👀😄 But it's always good with external feedback.

https://oauth1.wp-api.org/docs/basics/Auth-Flow.html

Followed this for implementation.

**Comment by mjewell** [comment]
Oh, haha! Yeah it looks like that's ok then. Thanks for the repo, it's great
