### ISSUE TITLE
How to implement Reddit [Possible Solution]

### ISSUE THREAD

**Issue by afoyer** [nextauthjs/next-auth#856]
**Your question**

Do any of you know how to make [Reddit](https://www.reddit.com/dev/api/oauth) work?

**What are you trying to do**

I am trying to authenticate but once I authorize get_access_token fails and returns a 401 error

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [X] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by afoyer** [comment]
After looking into it I may have found the problem.
In /server/lib/oauth/callback.js the authorization header was not creating a clientID:password pair then encoding it in base64

Line 242
`if (!headers['Client-ID']) {
      headers['Client-Id'] = provider.clientId;
}`

I changed it to this in the meantime and I can now access the token and my profile! This is only a quick fix so maybe there is already a base64 encoder somewhere in there that I did not notice.
`if (!headers['Client-ID']) {
      headers['Client-Id'] = provider.clientId;
      let buff = new Buffer(provider.clientId + ":" + provider.clientSecret);
      headers['Authorization'] = 'Basic ' + buff.toString('base64');
    }`

**Comment by LoriKarikari** [comment]
@afoyer thanks for looking into this! We were having this issue with Reddit but also some other providers (can't remember them by heart). We can test if this fix also works for the other providers and implement this @iaincollins?

**Comment by balazsorban44** [comment]
@LoriKarikari

It looks like this has been added already:
https://github.com/nextauthjs/next-auth/blob/ad791ea45c9cba11397bf3d50400f5c9cc68aee4/src/server/lib/oauth/client.js#L127-L129

Is the Reddit provider https://github.com/nextauthjs/next-auth/blob/canary/src/providers/reddit.js
still unfinished? ( The profile callback is commented out and there is a comment at the top
> // Logging in works but trying to retrieve the profile results in 401 unauthorized

)


There is no documentation page for it though, and not mentioned anywhere in the docs page. Other than that, if someone can confirm it work, we could close this issue?

**Comment by afoyer** [comment]
@balazsorban44 I am about to create a reddit.md file for the doc page. The last time I checked (which was two months ago) everything seemed to be working including what was indicated in the commented profile section. I can also uncomment the callback and remove the top comment since the solution I provided was an answer to that.

**Comment by balazsorban44** [comment]
Awesome news! Could you please check if `3.2.0-canary-22`still works please? 😊 made some internal changes, but hopefully nothing is broken.

**Comment by afoyer** [comment]
#1094 I got it to work but with a hack.
I had to add the Reddit provider to the index.js file in providers. I can't seem to find it on Github but it's there, somewhere.
Do you know why there's an index.js file when installing through npm but not in the repo (in src/providers)?
