### ISSUE TITLE
EmailProvider is not working

### ISSUE THREAD

**Issue by songhobby** [nextauthjs/next-auth#8572]
### Environment
Framework: 
    Next.js 13.4.19 (App router)
Packages: 
    next-auth 4.23.1
    @auth/mongodb-adapter 2.0.0
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 382.22 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.0/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.17.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.5.2

### Reproduction URL

https://venture.dev.percapita.io

### Describe the issue

Can not login with email. Nither first time email login or login with email after using Google login works

### How to reproduce

login with email

### Expected behavior

Server log:
https://next-auth.js.org/errors#callback_email_error Cannot read properties of undefined (reading 'valueOf') {
  message: "Cannot read properties of undefined (reading 'valueOf')",
  stack: "TypeError: Cannot read properties of undefined (reading 'valueOf')\n" +
    '    at Object.callback (webpack-internal:///(rsc)/./node_modules/next-auth/core/routes/callback.js:179:61)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async AuthHandler (webpack-internal:///(rsc)/./node_modules/next-auth/core/index.js:202:38)\n' +
    '    at async NextAuthRouteHandler (webpack-internal:///(rsc)/./node_modules/next-auth/next/index.js:50:30)\n' +
    '    at async NextAuth._args$ (webpack-internal:///(rsc)/./node_modules/next-auth/next/index.js:84:24)\n' +
    '    at async eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:254:37)',
  name: 'TypeError'
}

Browser error message: Try signing in with a different account.

**Comment by songhobby** [comment]
Next Auth config
```
    EmailProvider({
      server: emailTransportConfig,
      from: process.env.EMAIL_FROM!,
      sendVerificationRequest,
    }),
```

**Comment by balazsorban44** [comment]
cannot tell much without a reproduction. please open a new issue with one. make it minimal, removing unnecessary dependencies/code etc. don't just link to your production code, thanks! :green_heart:

**Comment by songhobby** [comment]
> cannot tell much without a reproduction. please open a new issue with one. make it minimal, removing unnecessary dependencies/code etc. don't just link to your production code, thanks! 💚

I found the bug in the mongodb adapter 
```
    async useVerificationToken(identifier_token) {
      const verificationToken = await (
        await db
      ).V.findOneAndDelete(identifier_token)

      if (!verificationToken) return null
      const { _id, ...rest } = verificationToken;// Wrong it should be `const {_id, ...rest} = verificationToken.value`
      return rest;
    },
  }
  ```

**Comment by robahtou** [comment]
I'm getting this issue when creating my own adaptor. I'm not really sure where to begin debugging this. I create the tokens successfully, but when I click the link from the email I get the same error as @songhobby

what is the processes that is suppose to happen when a user clicks the email link to verify?

 ```
providers: [
  EmailProvider({
    server: {
      host: process.env.EMAIL_SERVER_HOST,
      port: process.env.EMAIL_SERVER_PORT,
      auth: {
        user: process.env.EMAIL_SERVER_USER,
        pass: process.env.EMAIL_SERVER_PASSWORD
      }
    },
    from: 'no-reply@example.com',
    maxAge: 15 * 60,
    async generateVerificationToken() {
      return 'ABC123';
    },
    async sendVerificationRequest(params) {
      console.log({ params });
      const { identifier, url, provider, theme } = params;

      const result = await resend.emails.send({
        from: provider.from,
        to: [identifier],
        subject: 'verify email',
        react: EmailTemplate({ firstName: 'John', url }),
      });

      console.log('result', result);
    }
  })
  ],
  adapter: MyAdapter({
  url: process.env.MY_ADAPTOR_URL
  secret: process.env.MY_ADAPTOR_SECRET
  }),
```

**Comment by imyuanli** [comment]
I also have this issue. The program did not report any errors, and I was able to send verification emails normally and successfully verify, but I was unable to obtain a successful login status

This is my configuration item
`
export const authOptions: any = {
    adapter: PrismaAdapter(prisma),
    providers: [
        Email({
            server: {
                host: process.env.SMTP_HOST,
                port: Number(process.env.SMTP_PORT),
                auth: {
                    user: process.env.SMTP_USER,
                    pass: process.env.SMTP_PASSWORD,
                },
            },
            from: process.env.EMAIL_FROM,
            maxAge: 5 * 60,
            normalizeIdentifier: (email) => email.toLowerCase(),
            sendVerificationRequest: async ({ identifier: email, url, token, provider }) => {
                const transport = nodemailer.createTransport(provider.server)
                try {
                    await transport.sendMail({
                        from: `"Done 👻" ${provider.from}`,
                        to: email,
                        subject: `Done Account verification`,
                        html: `<p><a href="${url}">Verify Now</a>，It is valid for 5 minutes</p>`,
                    });
                } catch (error: any) {
                    throw new Error(error.message);
                }
            },
        }),
        Google({
            clientId: process.env.AUTH_GOOGLE_ID,
            clientSecret: process.env.AUTH_GOOGLE_SECRET,
        }),
        Github({
            clientId: process.env.AUTH_GITHUB_ID,
            clientSecret: process.env.AUTH_GITHUB_SECRET,
        }),
    ],
    secret: process.env.NEXTAUTH_SECRET,
    // pages: {
    //     signIn: '/login',
    // },
    // callbacks:{
    //     async signIn({user, account, email}: any) {
    //         console.log("email",email)
    //         const userExists = await prisma.user.findUnique({
    //             where:{
    //                 email: user.email
    //             },  //the user object has an email property, which contains the email the user entered.
    //         });
    //         if (userExists) {
    //             return true;   //if the email exists in the User collection, email them a magic login link
    //         } else {
    //             return "/register";
    //         }
    //     },
    // }
}
`
The following is an example image of my MySQL database
![image](https://github.com/nextauthjs/next-auth/assets/75649798/2b40ed33-b031-467f-a60e-9394d6e7edbd)
![image](https://github.com/nextauthjs/next-auth/assets/75649798/19062994-5c21-4e7a-b2eb-e7e1abaa831e)

**Comment by TomNes94** [comment]
I dont seem to be able to login using EmailProvider either. 0 console errors, a session is created but no token created so being redirected to the sign in page every time.

```
config.ts

import EmailProvider from "next-auth/providers/email";
import { PrismaAdapter } from "@auth/prisma-adapter";
import { PrismaClient } from "@prisma/client";
import { NextAuthOptions } from "next-auth";

const prisma = new PrismaClient();

const config = {
  adapter: PrismaAdapter(prisma),
  secret: process.env.NEXTAUTH_SECRET,
  providers: [
    EmailProvider({
      server: process.env.EMAIL_SERVER,
      from: process.env.EMAIL_FROM,
    }),
  ],
} as NextAuthOptions;

export default config;

middleware.ts

export { default } from "next-auth/middleware";

export const config = { matcher: ["/dashboard"] };

src/app/api/auth/[...nextauth]/route.ts

import NextAuth from "next-auth";
import config from "@/config";

const handler = NextAuth(config);

export { handler as GET, handler as POST };
``` 

I have set NEXTAUTH_URL and NEXTAUTH_SECRET

Users/Sessions/Accounts are created in the database. The callback url contains a valid token.

What am I doing wrong here?
