### ISSUE TITLE
307 Status Code(Temporary Redirect) on Logo in singin Page

### ISSUE THREAD

**Issue by fakharnia** [nextauthjs/next-auth#8578]
### Environment

System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 6.54 GB / 15.84 GB
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (116.0.1938.76)
    Internet Explorer: 11.0.22621.1

### Reproduction URL

https://github.com/fakharnia/nextAuthTest

### Describe the issue

Hi 
================
I have an issue with display logo in sign in page, the problem is in the default sign in page the logo.svg file that places in "project-name/public/logo.svg" don't display and request to image get 307 status code response.

here is my NextAuth.js options:
    
```js
import GithubProvider from "next-auth/providers/github";
import CredentialsProvider from "next-auth/providers/credentials";

const NextAuthOptions = {
    secret: process.env.NEXTAUTH_SECRET,
    providers: [
        GithubProvider({
            clientId: process.env.GITHUB_ID,
            clientSecret: process.env.GITHUB_SECRET
        }),
        CredentialsProvider({
            name: "Username and Password",
            credentials: {
                username: { label: "Username", type: "text", placeholder: "Enter your username" },
                password: { label: "Username", type: "password", placeholder: "Enter your username" }
            },
            async authorize(credentials, req) {
                console.log(credentials);
                const res = await fetch("http://localhost:5000/api/login", {
                    method: "POST",
                    body: JSON.stringify({ username: credentials.username, password: credentials.password }),
                    headers: {
                        "Content-Type": "application/json"
                    }
                });
                return res.json();
            }
        })
    ],
    session: {
        maxAge: 5 * 60,  // 5 minutes
        updateAge: 2.5 * 60, // 2.5 minutes
    },
    pages: {
        "signin": "/signin"
    },
    theme: {
        logo: "/logo.svg"
    }
};

export default NextAuthOptions;

```
I also try to create a custom signin page but stiil I got 307 redirect on <img /> tag or next <Image /> element in component.

### How to reproduce

1. create Next.js app
2. Add NextAuth.js into the project
3. Define NextAuth.js options(Providers, secret, them etc.)
4. Define the root folder to use NextAuth.js in "api/auth/[...nextauth]/root.js" path and use the options to define NextAuth.js handler
5. Add default NextAuth.js middleware to the project to protect all the link to project.
6. Add AuthProvider component to get the session state from the NextAuth.js and use it page.tsx in root folder.

### Expected behavior

Display the logo or any other files placed in public folder without issue.

**Comment by JasperAlexander** [comment]
Your issue is caused by the middleware. It you don't specify a config in `middleware.ts`, it will check if the user is authenticated on all routes (except authentication paths and favicon path). Currently, the middleware can't check what logo is defined in the authOptions, so it also checks if the user is authenticated on that route. You can exclude the route of your logo.png by adding the following code to your `middleware.ts`.

```ts
export const config = {
    matcher: [
      '/((?!logo.png).*)',
    ],
  }
```

**Comment by epenflow** [comment]
**Facing issue when using nextAuth. server responding with 307 temporary redirect status when trying to sign in** 

`
///midleware.ts
import authConfig from '@/auth.config';
import {
    API_AUTH_PREFIX,
    AUTH_ROUTES,
    DEFAULT_LOGIN_REDIRECT_URL,
    PUBLIC_ROUTES,
} from '@/routes';
import NextAuth from 'next-auth';
import { NextResponse } from 'next/server';

const { auth } = NextAuth(authConfig);
export default auth((request): any => {
    const { nextUrl } = request;
    let isLoggedIn = !!request.auth;

    const isApiAuthRoute = nextUrl.pathname.startsWith(API_AUTH_PREFIX);
    const isPublicRoute = PUBLIC_ROUTES.includes(nextUrl.pathname);
    const isAuthRoute = AUTH_ROUTES.includes(nextUrl.pathname);

    if (isApiAuthRoute) {
        return null;
    }
    console.log(isLoggedIn);
    if (isAuthRoute) {
        if (isLoggedIn) {
            return NextResponse.redirect(
                new URL(DEFAULT_LOGIN_REDIRECT_URL, nextUrl),
            );
        }
        return null;
    }
    if (!isLoggedIn) {
        return NextResponse.redirect(new URL('/auth/login', nextUrl));
    }
    return null;
});
export const config = {
    matcher: ['/((?!.+\\.[\\w]+$|_next).*)', '/', '/(api|trcp)(.*)'],
};

///auth.ts
import { db } from '@/lib/db';
import NextAuth from 'next-auth';
import { PrismaAdapter } from '@auth/prisma-adapter';
import authConfig from '@/auth.config';
import { getUserById } from '@/data/user';
export const { handlers, auth, signIn, signOut } = NextAuth({
    pages: {
        signIn: '/auth/login',
    },
    events: {
        async linkAccount({ user }) {
            await db.user.update({
                where: {
                    id: user.id,
                },
                data: {
                    emailVerified: new Date(),
                },
            });
        },
    },
    callbacks: {
        async signIn({ user, account }) {
            if (account?.provider !== 'credentials') return true;
            const existingUser = await getUserById(user.id);
            if (!existingUser?.email) return false;
            return true;
        },
        async jwt({ token }) {
            return token;
        },
    },
    adapter: PrismaAdapter(db),
    session: { strategy: 'jwt' },
    ...authConfig,
    secret: process.env.AUTH_SECRET,
});

///
auth.config.ts
import { getUserByEmail } from '@/data/user';
import { LoginSchema } from '@/schema';
import { NextAuthConfig } from 'next-auth';
import Credentials from 'next-auth/providers/credentials';
import bcrypt from 'bcryptjs';
export default {
    providers: [
        Credentials({
            async authorize(credentials, request) {
                const validatedFields = await LoginSchema.safeParse(
                    credentials,
                );
                if (validatedFields.success) {
                    const { email, password } = validatedFields.data;
                    const user = await getUserByEmail(email);
                    if (!user || !user.password) return null;
                    const passwordMatch = await bcrypt.compare(
                        password,
                        user.password,
                    );
                    if (user && passwordMatch) return user;
                }
                return null;
            },
        }),
    ],
} satisfies NextAuthConfig;

///login.ts
'use server';
import * as z from 'zod';
import { LoginSchema } from '@/schema';
import { getUserByEmail } from '@/data/user';
import { signIn } from '@/auth';
import { AuthError } from 'next-auth';
import { DEFAULT_LOGIN_REDIRECT_URL } from '@/routes';

type ReturnLogin = {
    error?: string;
    success?: string;
};
export async function login(values: z.infer<typeof LoginSchema>) {
    const validatedFields = await LoginSchema.safeParseAsync(values);

    if (!validatedFields.success) {
        return { error: 'Something went wrong!' };
    }
    const { email, password } = validatedFields.data;
    const existingUser = await getUserByEmail(email);
    if (!existingUser || !existingUser?.email) {
        return { error: 'Email does not exist!' };
    }
    try {
        await signIn('credentials', {
            email,
            password,
            redirectTo: DEFAULT_LOGIN_REDIRECT_URL,
            redirect: true,
        });
    } catch (error) {
        if (error instanceof AuthError) {
            switch (error.type) {
                case 'CredentialsSignin':
                    return { error: 'Invalid Credentials!' };
                case 'CallbackRouteError':
                    return { error: error.cause?.err?.message };
                default:
                    return { error: 'Something went wrong!' };
            }
        }
    }
    return { success: 'Login success' };
}


`
