### ISSUE TITLE
How to get accessToken from session

### ISSUE THREAD

**Issue by afoyer** [nextauthjs/next-auth#858]
**Your question**

I know the key is optional but is there any way to get the accessToken for further API requests?
**What are you trying to do**

I want to call more requests on Reddit.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by callmephilip** [comment]
@afoyer have you seen this tutorial - found it very helpful: https://arunoda.me/blog/add-auth-support-to-a-next-js-app-with-a-custom-backend (found it here: https://next-auth.js.org/tutorials)

**Comment by afoyer** [comment]
Thank you so much!
