### ISSUE TITLE
Types for HTTP-based Email Provider Seem Unhappy

### ISSUE THREAD

**Issue by askkaz** [nextauthjs/next-auth#8601]
### Question 💬

The type changes from version 4.22.1 to version 4.22.2 seem to not be compatible with https://authjs.dev/guides/providers/email-http
<img width="655" alt="Screenshot 2023-09-15 at 8 53 24 AM" src="https://github.com/nextauthjs/next-auth/assets/7975721/0195bbcc-6a85-4644-aa5d-34e726302ebc">

Does `email` need to be added as a valid type or am I typescripting wrong?

### How to reproduce ☕️

Use the code sample from https://authjs.dev/guides/providers/email-http with typescript running.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by andrew-r-thomas** [comment]
I'm having the same issue

**Comment by samtgarson** [comment]
Me too, seems that a temporary fix is possible by filling in the missing empty options https://github.com/nextauthjs/next-auth/discussions/8487#discussioncomment-6948757

**Comment by balazsorban44** [comment]
This will be fixed in the upcoming v5 release. see #9753

**Comment by alexevladgabriel** [comment]
@balazsorban44 I use the next-auth@beta and I would like to use the http approach. Is there a ETA?
