### ISSUE TITLE
next-auth and @auth/core derive different JWT encryption keys from the same secret

### ISSUE THREAD

**Issue by NilSet** [nextauthjs/next-auth#8607]
### Environment

next-auth: 4.23.1
@auth/core: 0.14.0

node: v20.3.1

### Reproduction URL

https://gist.github.com/NilSet/bdab421c8c4c3845f407138b5accb059

### Describe the issue

`next-auth` and `@auth/core` derive different JWT encryption keys from the same secret, because they pass different strings for `info` to `hkdf`. This means they cannot decode tokens encoded with the same secret in the other lib.

### How to reproduce

run the gist

### Expected behavior

Apps in the same domain using different frameworks or no framework should be able to share authjs sessions, so next-auth and @auth/core should be able to decode eachothers tokens.

**Comment by balazsorban44** [comment]
The two are distinct libraries, so it's unclear why they should be sharing each other's sessions. This is expected.

You can however control the JWT encode/decode method if you want to: https://authjs.dev/reference/core/jwt#encode
https://authjs.dev/reference/core/jwt#decode
https://next-auth.js.org/configuration/options#override-jwt-encode-and-decode-methods
