### ISSUE TITLE
Typescript errors when creating a custom User model

### ISSUE THREAD

**Issue by betfix** [nextauthjs/next-auth#861]
How to make a custom User model in Typescript and add it to NextAuth options?

I am trying to make a custom user model (following the tutorial https://next-auth.js.org/tutorials/typeorm-custom-models), but the app won't build because of typescript errors. It runs with "yarn dev" command and works ok with this model, but it throws errors with "yarn build" command.

The first error is in the custom model User.ts which I created, in the class definition:
```
export default class User extends Adapters.TypeORM.Models.User.model {
...
}
```

The string "**Adapters.TypeORM.Models.User.model**" is underlined in red and the error says: "**Type 'TypeORMUserModel' is not a constructor function type**"

The second typescript error is in pages/api/auth/[...nextauth].ts in options:

```
import Models from '../../../backend/models'
const options = {
  ......
  adapter: Adapters.TypeORM.Adapter(
    {
      type: 'postgres',
      ......
    },
    {
      models: {
        User: Models.User,
      },
    }
  ),
}
```

The string "**User:**" is underlined in red and the error says:

```
"Type '{ model: typeof User; schema: { name: string; target: typeof User; columns: { phoneNumber: { type: string; nullable: boolean; }; name?: EntitySchemaColumnOptions; email?: EntitySchemaColumnOptions; image?: EntitySchemaColumnOptions; emailVerified?: EntitySchemaColumnOptions; }; }; }' is not assignable to type '{ model: any; schema: EntitySchemaOptions<any>; }'.
  The types of 'schema.columns' are incompatible between these types.
    Type '{ phoneNumber: { type: string; nullable: boolean; }; name?: EntitySchemaColumnOptions; email?: EntitySchemaColumnOptions; image?: EntitySchemaColumnOptions; emailVerified?: EntitySchemaColumnOptions; }' is not assignable to type '{ [x: string]: EntitySchemaColumnOptions; }'.
      Property 'phoneNumber' is incompatible with index signature.
        Type '{ type: string; nullable: boolean; }' is not assignable to type 'EntitySchemaColumnOptions'.
          Types of property 'type' are incompatible.
            Type 'string' is not assignable to type 'ColumnType'.ts(2322)
adapters.d.ts(77, 17): The expected type comes from property 'User' which is declared here on type '{ Account?: { model: any; schema: EntitySchemaOptions<any>; }; User?: { model: any; schema: EntitySchemaOptions<any>; }; Session?: { model: any; schema: EntitySchemaOptions<...>; }; VerificationRequest?: { ...; }; }'"
```

My custom User model (copied from the tutorial):
```
import Adapters from "next-auth/adapters"
export default class User extends Adapters.TypeORM.Models.User.model {
   constructor(name, email, image, emailVerified) {
    super(name, email, image, emailVerified)
  }
}
export const UserSchema = {
  name: "User",
  target: User,
  columns: {
    ...Adapters.TypeORM.Models.User.schema.columns,
    phoneNumber: {
      type: "varchar",
      nullable: true,
    },
  },
}
```

**Comment by PaulPCIO** [comment]
I'm getting exactly the same errors on a new project.

**Comment by xangxiong** [comment]
Using `TypeORMUserModel` seems to throw undefined.  What seems to work for me was:

`
import Adapters from 'next-auth/adapters';

export default class User extends (<any>Adapters.TypeORM.Models.User.model) {
    constructor(name, email, image, emailVerified) {
        super(name, email, image, emailVerified);
    }
}
`

**Comment by sebastianplsim** [comment]
So - it's not pretty, but this works for me. FYI I'm adding a `username` - not `telephone`.

Let me know if you know a way to tidy this up a little.

`User.ts`
```ts
import Adapters from 'next-auth/adapters'
import { EntitySchemaColumnOptions } from 'typeorm'

export default class User extends (<any>Adapters.TypeORM.Models.User.model) {
  constructor(name, email, image, emailVerified) {
    super(name, email, image, emailVerified)
  }
}

type UserSchema = {
  name: string
  target: typeof User
  columns: {
    username?: {
      type: 'varchar'
      nullable: boolean
    }
    name?: EntitySchemaColumnOptions
    email?: EntitySchemaColumnOptions
    image?: EntitySchemaColumnOptions
    emailVerified?: EntitySchemaColumnOptions
  }
}

export const UserSchema: UserSchema = {
  name: 'User',
  target: User,
  columns: {
    ...Adapters.TypeORM.Models.User.schema.columns,
    username: {
      type: 'varchar',
      nullable: true,
    },
  },
}

```

**Comment by jaretburkett** [comment]
This appears to work for me and allows for proper type completions. 

```typescript
import Adapters, {TypeORMUserModel} from 'next-auth/adapters';

export default class User extends (Adapters.TypeORM.Models.User.model as typeof TypeORMUserModel)  {
```

**Comment by serdarsavas** [comment]
> This appears to work for me and allows for proper type completions.
> 
> ```ts
> import Adapters, {TypeORMUserModel} from 'next-auth/adapters';
> 
> export default class User extends (Adapters.TypeORM.Models.User.model as typeof TypeORMUserModel)  {
> ```

<img width="1496" alt="Screenshot 2021-05-26 at 11 25 20" src="https://user-images.githubusercontent.com/44787241/119636704-2e946580-be15-11eb-936f-0e116832358e.png">


Asks me to convert type to unknown

**Comment by chimson** [comment]
I got it working with the following code, I specified each model needed for Adapter: `Account` `Session` `VerificationRequest`:

`[...nextauth].ts`

```javascript
adapter: Adapters.TypeORM.Adapter(process.env.MONGODB_URI!, {
  models: {
    Account: Adapters.TypeORM.Models.Account,
    Session: Adapters.TypeORM.Models.Session,
    VerificationRequest: Adapters.TypeORM.Models.VerificationRequest,
    User: Models.User,
   },
})
```

`Models/User.ts`

```javascript
export default class User extends (<any>Adapters.TypeORM.Models.User.model) {
  constructor(
    name: string,
    email: string,
    image: string,
    emailVerified: Date | undefined
  ) {
    super(name, email, image, emailVerified);
    if (!this.username) this.username = this.name;
    if (!this.isFollowed) this.isFollowed = false;
  }
}

type UserSchema = {
  name: string;
  target: typeof TypeORMUserModel;
  columns: {
    username?: {
      type: "varchar";
      nullable: boolean;
    };
    isFollowed?: {
      type: "boolean";
    };
    name?: EntitySchemaColumnOptions;
    email?: EntitySchemaColumnOptions;
    image?: EntitySchemaColumnOptions;
    emailVerified?: EntitySchemaColumnOptions;
  };
};

export const UserSchema: UserSchema = {
  name: "User",
  target: User,
  columns: {
    ...Adapters.TypeORM.Models.User.schema.columns,
    username: {
      type: "varchar",
      nullable: true,
    },
    isFollowed: {
      type: "boolean",
    },
  },
};
```

**Comment by hademo** [comment]
> I'm getting exactly the same errors on a new project. As a temp fix, I updated the import method:
> 
> ```ts
> import Adapters, {TypeORMUserModel} from 'next-auth/adapters'
> 
> export default class User extends TypeORMUserModel {
>   ...
> }
> ```

Gives me following error "TypeError: Class extends value undefined is not a constructor or null" at local dev

**Comment by hademo** [comment]
> Using `TypeORMUserModel` seems to throw undefined. What seems to work for me was:
> 
> ```
> import Adapters from 'next-auth/adapters';
> 
> export default class User extends (<any>Adapters.TypeORM.Models.User.model) {
>     constructor(name, email, image, emailVerified) {
>         super(name, email, image, emailVerified);
>     }
> }
> ```

Not really pretty, but works perfect
