### ISSUE TITLE
Fetch to `localhost` fails?

### ISSUE THREAD

**Issue by SansPapyrus683** [nextauthjs/next-auth#8611]
### Question 💬

I was following [this](https://github.com/hillmark/next-auth-django) repo and trying to implement it in my own Next project/Django REST framework. However, it seems that even when all the settings have been set correctly, a `fetch` request to `localhost` results in a "Fetch Failed" error.

### How to reproduce ☕️

I followed the instructions on the repository but also did the following:

1. Specified the host as `localhost:8000` for the Django `runserver` command.
2. Replaced all instances of `127.0.0.1` with `localhost` in `api/auth/[...nextauth].js` in the Next project.

The site says that I can't sign in due to invalid login credentials. After removing the try-catch block, it results in a Fetch Failed page.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Hi, maybe you could ask in that repo, it's not maintained by us.

**Comment by Vette1123** [comment]
@balazsorban44 i have the same issue, using latest next-auth beta, and i can't login with local backend (localhost:8000), any solution?
