### ISSUE TITLE
Override X-Frame-Options for certain pages

### ISSUE THREAD

**Issue by ziming-yuan** [nextauthjs/next-auth#8613]
### Question 💬

I am using next-auth with the app directory. And I am using middleware.js to protect most of my routes:
```
export { default } from "next-auth/middleware";
export const config = {
    matcher: ["/dashboard", "/edit/:path*"...],
};
```
I want to allow other users to embed some of my web pages (`/calendar/:path`) to their website using iframe. What is the safest way to achieve that? I am guessing I can remove the X-Frame-Options which can be achieved by this nextjs middleware
```
import { NextResponse } from "next/server";
export function middleware(request) {
    const response = NextResponse.next();
    if (request.nextUrl.pathname.startsWith("/calendar/")) {
        response.headers.delete("X-Frame-Options");
    }
    return response;
}
```
But when I put these two together in the same middleware.js and deploy them to Vercel, next-auth route protection failed. 
I was wondering what the best practice is to override X-Frame-Options and how to combine these two logics. 

### How to reproduce ☕️

Try out this middleware.js with app directory and deploy it in Vercel:
```
export { default } from "next-auth/middleware";
import { NextResponse } from "next/server";

export function middleware(request) {
    const response = NextResponse.next();

    if (request.nextUrl.pathname.startsWith("/calendar/")) {
        response.headers.delete("X-Frame-Options");
    }

    return response;
}

export const config = {
    matcher: ["/dashboard", "/edit/:path*"],
};
```
`X-Frame-Options` are removed for `/calendar/` paths, however the next-auth route protection stopped working. How can I maintain route protection while disabling SameOrigin policies for some paths. 

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
You cannot export two middleware, this is not related to Vercel either.

Check out the docs for wrapping your middleware: https://next-auth.js.org/configuration/nextjs#advanced-usage
