### ISSUE TITLE
https://next-auth.js.org/getting-started/example doesn't include a `type` attribute, but it should.

### ISSUE THREAD

**Issue by hamirmahal** [nextauthjs/next-auth#8624]
### What is the improvement or update you wish to see?

`<button>`s in https://next-auth.js.org/getting-started/example#frontend---add-react-hook,

```JavaScript
import { useSession, signIn, signOut } from "next-auth/react"
export default function Component() {
  const { data: session } = useSession()
  if (session) {
    return (
      <>
        Signed in as {session.user.email} <br />
        <button onClick={() => signOut()}>Sign out</button>
      </>
    )
  }
  return (
    <>
      Not signed in <br />
      <button onClick={() => signIn()}>Sign in</button>
    </>
  )

```

don't include a `type` attribute, but they should.

### Is there any context that might help us understand?

https://webhint.io/docs/user-guide/hints/hint-button-type/

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/getting-started/example#frontend---add-react-hook

**Comment by balazsorban44** [comment]
Thanks, but it's unclear why this would be necessary. If this is causing a bug, please open a bug report instead.

**Comment by hamirmahal** [comment]
You're welcome. https://webhint.io/docs/user-guide/hints/hint-button-type/ has the relevant information, but a quick summary is that

> The default type for `<button>` is submit (not type="button" as one might expect). This can lead to surprising keyboard behavior within a form.

> The best way to avoid unexpected surprises is to always explicitly set a type on `<button>`s.

**Comment by hamirmahal** [comment]
I think example code should be free of linting errors, which

```jsx
import { useSession, signIn, signOut } from "next-auth/react"
export default function Component() {
  const { data: session } = useSession()
  if (session) {
    return (
      <>
        Signed in as {session.user.email} <br />
        <button onClick={() => signOut()}>Sign out</button>
      </>
    )
  }
  return (
    <>
      Not signed in <br />
      <button onClick={() => signIn()}>Sign in</button>
    </>
  )
```

is not.

![image](https://github.com/nextauthjs/next-auth/assets/43425812/d7f958db-9ed7-49b3-be33-a750106ed423)

**Comment by hamirmahal** [comment]
@balazsorban44 just bumping this in case you didn't see it
