### ISSUE TITLE
Request timed out error while using Cognito provider

### ISSUE THREAD

**Issue by itsevon** [nextauthjs/next-auth#8627]
### Provider type

Cognito

### Environment

  System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 3.56 GB / 15.78 GB
  Binaries:
    Node: 20.6.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 116.0.5845.188
    Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.31)
    Internet Explorer: 11.0.22621.1

-----

 "dependencies": {
    "@types/node": "20.6.2",
    "@types/react": "18.2.21",
    "@types/react-dom": "18.2.7",
    "autoprefixer": "10.4.15",
    "eslint": "8.49.0",
    "eslint-config-next": "13.4.19",
    "next": "13.4.19",
    "next-auth": "^4.23.1",
    "postcss": "8.4.29",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "tailwindcss": "3.3.3",
    "typescript": "5.2.2"
  }

### Reproduction URL

https://github.com/itsevon/eleck-web.git

### Describe the issue

After following the docs for NextAuth and Cognito Provider, after I click Sign In with Cognito button it just keeps showing the "Try to sign in with different account" alert.
![chrome_sAJCB9t5Qq](https://github.com/nextauthjs/next-auth/assets/23398407/ccbf45fb-024e-4106-a2d9-236143ffb6aa)

And this is the error message I get
![Code_l8UK6SvtJr](https://github.com/nextauthjs/next-auth/assets/23398407/4e5ca647-9e8a-4e76-a922-d32fe9663cbf)

After reading some similar timeout issues 
What I've tried:

1. Wifi restart
2. using personal mobile data
3. laptop restart
4. changed timeout in nextauthoptions
5. Upgrade Node to v20x.

But no luck so far.

### How to reproduce

1. Click sign in button
3. Click sign in with cognito button

### Expected behavior

Pop up this window for you to type credentials
![chrome_uSFp2xrgbC](https://github.com/nextauthjs/next-auth/assets/23398407/250c2c6b-fe14-4a87-8b14-faa088eb1638)

**Comment by balazsorban44** [comment]
There is a semi-hidden provider option added in: https://github.com/nextauthjs/next-auth/pull/3287

It's not well documented, as it should barely be needed. A bigger issue here is likely why it takes more than 3.5s for cognito to answer.

See https://github.com/nextauthjs/next-auth/issues/3920#issuecomment-1039043401

**Comment by 3-w-c** [comment]
Encountered this issue, and adding `httpOptions: {timeout: 10000}}` resolved it. Thanks!

**Comment by devMatheusR** [comment]
> Encountered this issue, and adding `httpOptions: {timeout: 10000}}` resolved it. Thanks!

right, but where i found httpOptions? In my authOptions object?

**Comment by 3-w-c** [comment]
@devMatheusR sorry, I didn't get a notification for this for some reason! 

Here's where I added this:

```
export const authOptions: NextAuthOptions = {
  providers: [
    CognitoProvider({
      clientId: process.env.COGNITO_USER_POOL_CLIENT_ID as string,
      clientSecret: process.env.COGNITO_USER_POOL_CLIENT_SECRET as string,
      issuer: `https://cognito-idp.${process.env.AWS_REGION}.amazonaws.com/${process.env.COGNITO_USER_POOL_ID}`,
      httpOptions: {
        timeout: 10000,
      },
```
