### ISSUE TITLE
Twitter callback URI error

### ISSUE THREAD

**Issue by Grinyaka** [nextauthjs/next-auth#8630]
### Provider type

Twitter

### Environment

  System:
    OS: Linux 5.15 Linux Mint 21.2 (Victoria)
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 11.50 GB / 15.04 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.14.1 - /usr/local/bin/node
    Yarn: 1.22.1 - ~/.yarn/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
    pnpm: 6.11.0 - /usr/local/bin/pnpm
  Browsers:
    Chromium: 115.0.5790.170

### Reproduction URL

https://next-auth-example.vercel.app/

### Describe the issue

Even on next-auth example page, when I'm trying to sign in with twitter, I get error "Try signing in with a different account."
![image](https://github.com/nextauthjs/next-auth/assets/88576356/698372dd-f0a6-4c3e-ae79-835b5cca08d8)
![image](https://github.com/nextauthjs/next-auth/assets/88576356/1efb709e-b953-4e18-b58a-77d1a0c072f7)

I have three similar projects: 1) using Privy (with twitter oAuth2), 2) using passport-twitter on express (oAuth1) and 3) using next auth.
First two are working ok with same twitter credentials, but Twitter auth seems broken.
![image](https://github.com/nextauthjs/next-auth/assets/88576356/7b3e8b70-a9cd-41cc-b633-193a7d39bb71)

### How to reproduce

1) Go to https://next-auth-example.vercel.app/
2) Try to sign in with Twitter

### Expected behavior

I guess, the problem is in POST request, that sends callbackUrl without any "callback" mentions

**Comment by sky4git** [comment]
I am getting the `403 forbidden` error as well. I am not sure issue is from Nextauth side or from Twitter. But I posted it here https://twittercommunity.com/t/getting-403-forbidden-oauth2-on-basic-plan/205949

I created a separate project with a simple Twitter provider using OAUTH `version 2.0` without any adapters and `jwt` session strategy. I still get the same error.

**Comment by hairyf** [comment]
Will this problem be solved? Unable to log in using Twitter now

**Comment by balazsorban44** [comment]
Login with Twitter on https://next-auth-example.vercel.app/ should work now. Individual issus will need a reproduction.
