### ISSUE TITLE
Prisma adapter error when using next-auth's native signIn function

### ISSUE THREAD

**Issue by leodrez** [nextauthjs/next-auth#864]
**Describe the bug**
When using signIn function, Prisma throws the following error at navigation to /api/auth/signin

`Argument identifier: Got invalid value null on prisma.createOneVerificationRequest. Provided null, expected String.`

**Steps to reproduce**

1. Create next app
2. Install prisma client, cli and next-auth
3. Set up [...nextauth].js route to handle paswordless login with Email provider and Prisma Adapter
4. Trigger signIn() from page

**Expected behavior**
Prisma client should not have data identifier null when calling prisma.verificationRequest.create()

**Screenshots or error logs**
`logger.js:21 [next-auth][error][create_verification_request_error] Error: 
Invalid `prisma.verificationRequest.create()` invocation:

{
  data: {
    identifier: null,
                ~~~~
    token: 'XXX',
    expires: '2020-11-20T17:35:33.584Z'
  }
}
`

**Comment by wuminqi** [comment]
@leodrez , can you share how to fix this?

**Comment by duongdangng** [comment]
@leodrez how did you solve this issue?

**Comment by Agahan** [comment]
@duongdangng. I got the same error; the issue was I had not added a verification request table to my database: https://next-auth.js.org/schemas/models#verification-request

**Comment by duongdangng** [comment]
@Agahan thank you! I realized I was not remapping my model correct. It wasn't using camelCase that Prisma was expecting

**Comment by steven-tey** [comment]
For those who are also struggling with this bug, all you have to do is fill your `prisma/schema.prisma` file with the exact same attributes outlined here: https://next-auth.js.org/adapters/prisma#setup

And you should be good! :)

**Comment by 4t4sh** [comment]
Any solution about this problem guys? 🤔

**Comment by kushthakker** [comment]
I am having same problem while connecting planetscale with prisma in next-auth. 
Error : "Argument providerAccountId: Got invalid value 43739786 on prisma.findUniqueAccount. Provided Int, expected String."

**Comment by balazsorban44** [comment]
Your problem is different, please open a separate issue. FWIW, this is not an actual problem with `next-auth` but how your Identity Provider returns an Int as an ID, but your Prisma schema expects it to be a String.

**Comment by Sumit2701** [comment]
I am not getting any error on localhost but only on my domain. What can be the reason.

**Comment by reckziegelwilliam** [comment]
@Sumit2701 did you ever find a solution to this?
