### ISSUE TITLE
issue template has bad envinfo arguments

### ISSUE THREAD

**Issue by NilSet** [nextauthjs/next-auth#8644]
### What is the improvement or update you wish to see?

the issue creation template asks you to run `npx envinfo --system --binaries --browsers --npmPackages "next,react,next-auth,@auth/*"`

Unfortunately it seems like envinfo cannot combine a comma separated list with a glob pattern, so it doesn't list any npm package versions for the suggested invocation.

### Is there any context that might help us understand?

`npx envinfo --npmPackages "next,react,next-auth"` works 
`npx envinfo --npmPackages "@auth/*"` works 

Maybe consider fixing https://github.com/tabrindle/envinfo to support both at the same time.

**Comment by ThangHuuVu** [comment]
We can tweak the template to instruct developers to print the version of the exact packages that they are using. 👍 PR is welcome

**Comment by mhpjay422** [comment]
Working on this now
