### ISSUE TITLE
Add AuthOption.session maxAge option - undefined 

### ISSUE THREAD

**Issue by dbstjrrb12** [nextauthjs/next-auth#8645]
### Description 📓

Hello, I would like to request a way to set the authOption.session's maxAge value to undefined. 

Typically, when implementing a "remember-me" button, if a user logs in without selecting the button and the browser is closed, it requires automatic logout. This is why the cookie containing the **login token should be designated as a session cookie.** 

Currently, next-auth sets _maxAge_ by default, which results in the cookie being stored as a _permanent_ one. I request an extension of the maxAge option to allow developers to change the stored cookie options as needed.

### How to reproduce ☕️

Through next-auth, when logging in, it can be observed that the **"MaxAge"** of the "next-auth.session-token" stored in the cookie is set to 30 days instead of being a "Session"

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
Unfortunately, this still seems to be inconsistent in browsers as stated back in #4693

Setting `document.cookie="foo=bar;expires=Session"` in Chrome/Firefox, close/open won't delete the cookie in all cases. Eg. if the user has "Continue where I left off", "run apps in the background even if Chrome is closed" or "Open previous windows and tabs", this setting will have no effect on cookie expiry.

This inconsistency might be confusing, or **worse**, the session is **never** deleted. On public computers, this could be a huge issue.

The recommendation in this case would be to set a very low `maxAge` instead.

**Comment by dbstjrrb12** [comment]
> Unfortunately, this still seems to be inconsistent in browsers as stated back in #4693
> 
> You can test this by setting `document.cookie="foo=bar;expires=Session"` in Chrome/Firefox, close/open, and you will observer that it won't delete the cookie in all cases. Eg. if the user has "Continue where I left off", "run apps in the background even if Chrome is closed" or "Open previous windows and tabs", this setting will have no effect on cookie expiry.
> 
> This inconsistency might be confusing, or **worse**, the session is **never** deleted. On public computers, this could be a huge issue.
> 
> The recommendation in this case would be to set a very low `maxAge` instead.

However, if the user does not take any action before the cookie expires, a problem arises where the cookie expiration time is not updated. If the user begins to interact with the site after the cookie expiration time, wouldn't the cookie have already been deleted, automatically logging them out? Can the 'refetchinterval' option solve this issue

**Comment by tilgovi** [comment]
I don't understand the reasoning here. The session still has a validity / expiration maintained by NextAuth.js. The JWTs have an expiration and the database sessions are supposed to store an expiration. The internal session route checks the expiration, for both strategies.

What this means is that persisting a cookie past the session expiration is of little consequence. In the best case, using a non-persistent cookie _will_ expire the cookie when the user closes the browser. In the worst case, it is no worse than today.

Is the argument against this feature that developers will misunderstand it and have a false sense of security? If so, can we just link to MDN with a warning about this? I think many security conscious developers would want to turn this on anyway.

Even if the feature is a best effort, that's better than no effort, no?

**Comment by tilgovi** [comment]
I made a function that I'm calling from my route handlers for the time being, but it's not great. Note that `getSetCookies` depends on a runtime that supports this modern addition to the `Headers` interface (e.g. Node.js 20+).

```
export function removeSessionCookiePersistence(response: Response) {
  const cookies = response.headers.getSetCookie();
  response.headers.delete('set-cookie');

  for (let cookie of cookies) {
    if (cookie.includes('next-auth.session-token')) {
      cookie = cookie.replace(/Expires=.*?; /i, '');
    }

    response.headers.append('set-cookie', cookie);
  }
}
```
