### ISSUE TITLE
Cold boot of saved session is slow to load in next 13 with app router

### ISSUE THREAD

**Issue by YoniChechik** [nextauthjs/next-auth#8652]
### Environment

  System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 6.62 GB / 15.88 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (117.0.2045.31)
    Internet Explorer: 11.0.22621.1

### Reproduction URL

https://github.com/YoniChechik/next-auth-app

### Describe the issue

need to wait ~2 secs for the session to be authorized (and show the logged in user) when returning to the site when you logged in the past. this happens ~15 mins after revisiting the site.

### How to reproduce

- sign in to the site with your google account.
- leave the site and return after ~15 mins,
- need to wait ~2 secs for the session to be authorized (and show the logged in user). this doesn't happens if you do a reload to the page immidiatly after, so this only happens in cold boots.

please check this simple repro github repo and vercel deployment: https://github.com/YoniChechik/next-auth-app

### Expected behavior

the session should be shown immidiatly when cold booting.

**Comment by balazsorban44** [comment]
There are not many actionable things we can do here, other than #7443, that will make `next-auth` fully edge-compatible which comes with performance boosts that might help in your case too.
