### ISSUE TITLE
Public PKCE OIDC auth flow with SvelteKit

### ISSUE THREAD

**Issue by pozsa** [nextauthjs/next-auth#8658]
### Question 💬

I am getting a missing secret error (https://authjs.dev/reference/core/errors/#missingsecret) when setting up authentication with a custom OIDC provider.
I am using SvelteKit and my idea was to use the PKCE auth flow. The client is configured as a public client with the oauth provider.

Do you have any ideas about what am I doing wrong? Is this auth flow simply not supported by AuthJS?

### How to reproduce ☕️

```
# src/hooks.server.ts
import { SvelteKitAuth } from '@auth/sveltekit';
import type { OIDCConfig } from '@auth/core/providers';

export const handle = SvelteKitAuth({
	providers: [
		{
			id: 'eduid',
			name: 'SWITCH edu-ID',
			type: 'oidc',
			issuer: 'https://login.test.eduid.ch/',
			clientId: '<my-client-id>',
			checks: ['pkce']
			// clientSecret: process.env.CLIENT_SECRET
		} satisfies OIDCConfig
	]
});
```

when navigating to `auth/signin` the missing secret error is thrown

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
The error you see is unrelated. You are likely missing `AUTH_SECRET` which is not the same as your provider's client secret. That one is always necessary and is used for encrypting the SvelteKit Auth JWT for example.

**Comment by pozsa** [comment]
Hello @balazsorban44,
Thanks for the quick response. Yes, I have figured as much, and I also know that if I set a value that solves the problem.

I guess I just really don't understand what this secret is used for. E.g.: you mention SvelteKit Auth JWT, what is that and what is it used for? Is it really needed? (I couldn't find a proper description/explanation in the docs.) I thought the OIDC provider issues the JWT for the client.

Thanks for your help

**Comment by balazsorban44** [comment]
It is needed as SvelteKit Auth creates you a session. This secret is used to encrypt that session which is stored as a JWT by default in a cookie.

**Comment by pozsa** [comment]
So does that mean I am not able to create a flow like this with authjs?
Where the `User` is the user of the application, `App` is my sveltekit app, `Auth0 Tenant` is my oidc provider, `Your API` is a backend API that is not part of the sveltekit app.

![image](https://github.com/nextauthjs/next-auth/assets/11932472/33385cf6-245d-4db6-8a85-6e37c9dccfff)

**Comment by balazsorban44** [comment]
This is exactly the flow Auth.js makes possible. 🤔

**Comment by pozsa** [comment]
#8728 
I really don't think this is working as intended with a public client
