### ISSUE TITLE
sessionToken cookie seems to be broken

### ISSUE THREAD

**Issue by jWytrzes** [nextauthjs/next-auth#8676]
### Environment

OS: Windows
Node 18.17.1
React 18.2.0
Next 13.4.10
Next-auth ^4.22.5

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

I have a NextAuth configured with a custom OAuth Provider, but I noticed that the problem occurs even in next-auth-example repo (signing in with Google)

Authorization seems to be working fine, but the session-token cookie seems to be incorrect. There are more than 3 sections, one of them is empty and it's overall looking weird. What are the possible reasons?

![image](https://github.com/nextauthjs/next-auth/assets/32808627/752634b6-2e0a-447e-ba1e-07b2e95ec44f)

### How to reproduce

Clone https://github.com/nextauthjs/next-auth-example, add GOOGLE_ID and GOOGLE_SECRET to .env.local and sign in with Google account

### Expected behavior

sessionToken cookie is a proper JWT token

**Comment by balazsorban44** [comment]
it's encrypted
