### ISSUE TITLE
Cookies in responses are sent with __Secure prefix in local environment when using Nextjs 13.5

### ISSUE THREAD

**Issue by nicholasprowse** [nextauthjs/next-auth#8702]
### Environment

System:
OS: macOS 13.3.1
CPU: (8) arm64 Apple M1
Memory: 344.88 MB / 16.00 GB
Shell: 5.9 - /bin/zsh
Binaries:
Node: 20.7.0 - /usr/local/bin/node
Yarn: 1.22.17 - /opt/homebrew/bin/yarn
npm: 10.1.0 - /opt/homebrew/bin/npm
Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
Browsers:
Chrome: 116.0.5845.187
Safari: 16.4

### Reproduction URL

https://github.com/nicholasprowse/next-auth-cookie-example

### Describe the issue

I recently upgraded from Nextjs 13.4.10 to 13.5.2, and pretty much all of my authentication using next-auth broke. After a few hours debugging it I have identified the issue. After upgrading to Nextjs 13.5, the cookies sent back from the server are not saved in development, because they are sent back with the __Secure or __Host prefix. Because the csrf is not stored, it is regenerated on each request, which breaks authentication. This is not an issue in production, because the __Secure prefix is expected when using https, but it breaks local development using http.

I may be wrong, but after diving into the code, I think I have found the problem:
next-auth uses a combination of the `x-forwarded-proto` header and the `VERCEL` env variable to determine if the request is coming from http or https (As can be seen [here](https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/core/index.ts#L83C3-L83C66) and [here](https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/utils/detect-origin.ts)). If the `VERCEL` variable is set, then the `x-forwarded-proto` header is used to determine if the protocol is http or https, which determines if the __Secure/__Host prefixes are added to cookies. By default, vercel projects have the `VERCEL` env variable set to `"1"`, so I expect this will be a problem for all vercel projects running Nextjs 13.5.

However, in Nextjs 13.5, the `x-forwarded-proto` is no longer sent in requests. Not sure why this was changed, but I just noticed it through my testing, and it results in next-auth assuming the protocol is https, when it is not.

Like I said, the lack if the `x-forwarded-proto` header, results in next-auth assuming https, resulting in the cookies being sent with __Secure/__Host prefixes, which the browser rejects because the protocol is actually http.

Note: this can be easily worked around by manually removing the `VERCEL` environment variable, however this isn't ideal, as vercel expects it to be there and every time I run `vercel env pull` it adds back in the variable.

### How to reproduce

1. Clone repo: `git clone https://github.com/nicholasprowse/next-auth-cookie-example.git`
2. cd into it: `cd next-auth-cookie-example/`
3. Install dependencies: `npm i`
4. Run in development (`npm run dev`) and go to `localhost:3000/api/auth/csrf`. Refresh a few times and the token is different every time. If you open dev tools, you can see the csrf cookie is not being saved, and the response header with the cookie has the __Host prefix.

### Expected behavior

Since we are in a development environment (http), the cookie should have been sent without the __Secure/__Host prefixes. This results in the cookie being stored in the browser, and the returned csrf token from the api endpoint is always the same.

This behaviour can be seen by removing the `VERCEL` environment variable or downgrading Nextjs to 13.4. The above example also prints out the request headers. In Nextjs 13.4.10 the header keys are
```
[
  'accept',
  'accept-language',
  'cache-control',
  'connection',
  'cookie',
  'host',
  'pragma',
  'sec-ch-ua',
  'sec-ch-ua-mobile',
  'sec-ch-ua-platform',
  'sec-fetch-dest',
  'sec-fetch-mode',
  'sec-fetch-site',
  'sec-fetch-user',
  'upgrade-insecure-requests',
  'user-agent',
  'x-forwarded-for',
  'x-forwarded-host',
  'x-forwarded-port',
  'x-forwarded-proto',
  'x-invoke-path',
  'x-invoke-query',
  'x-middleware-invoke'
]
```
In Nextjs 13.5, the header keys are (notice there are no `x-forwarded-` headers):
```
[
  'accept',
  'accept-encoding',
  'accept-language',
  'cache-control',
  'connection',
  'cookie',
  'host',
  'pragma',
  'sec-ch-ua',
  'sec-ch-ua-mobile',
  'sec-ch-ua-platform',
  'sec-fetch-dest',
  'sec-fetch-mode',
  'sec-fetch-site',
  'sec-fetch-user',
  'upgrade-insecure-requests',
  'user-agent'
]
```

**Comment by luke-maddox** [comment]
Ran into this too.

**Comment by Thevyn** [comment]
Same issue here

**Comment by balazsorban44** [comment]
This is unrelated to NextAuth.js. The change seems to originate somewhere between 13.4.12 -> 13.4.13.

Could you open an issue in the Next.js repo with a minimal reproduction?
