### ISSUE TITLE
Broken link to built-in providers

### ISSUE THREAD

**Issue by nrsimha** [nextauthjs/next-auth#8703]
### What is the improvement or update you wish to see?

Link to built in provider to work.

### Is there any context that might help us understand?

On OAuth authentication page in documentation (https://authjs.dev/getting-started/oauth-tutorial) there is link to "built-in providers" (https://authjs.dev/reference/providers/oauth-builtin) and that page shows Page Not Found error.

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/oauth-tutorial

**Comment by balazsorban44** [comment]
I think we should create a dedicated Providers page, similar to https://authjs.dev/reference/adapters

**Comment by Idan-Garay** [comment]
If this is still available, can this be assigned to me?
