### ISSUE TITLE
SvelteKitAuth not working with SvelteKit's base path

### ISSUE THREAD

**Issue by aakash14goplani** [nextauthjs/next-auth#8707]
### Environment

```
  System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 6.64 GB / 15.41 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.5.1 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.36)
    Internet Explorer: 11.0.22621.1
```

### Reproduction URL

https://github.com/aakash14goplani/SvelteKit-Auth0-NextAuth/tree/basepath

### Describe the issue

Unable to initiate authentication flow with SvelteKitAuth while using base path.

This issue was recently claimed to be fixed via https://github.com/nextauthjs/next-auth/pull/8231 and https://github.com/nextauthjs/next-auth/issues/8230. Even after following instructions specified within those fix, authentication flow is broken.

### How to reproduce

1. Add base path in SvelteKit
   ```js
   kit: {
     paths: {
       base: '/hello'
     }
   }
   ```
2. Update SvelteKitAuth configuration object
   ```ts
   const config: SvelteKitAuthConfig = {
     providers: [...],
     prefix: '/hello',
     ...
   }
   ```
3. Initiate sign-in process and observe the error :
   ![image](https://github.com/nextauthjs/next-auth/assets/13452115/d604e370-8f60-423d-bea3-ee19ce942e31)

**NOTE**:
I also tried experimenting with NEXTAUTH_URL by setting its value to -> `http://localhost:4200`, `http://localhost:4200/hello` and `http://localhost:4200/hello/auth` but none of them worked for me!

**Dependency Versions Used**:
```json
"dependencies": {
  "@auth/core": "^0.15.1",
  "@auth/sveltekit": "^0.3.7"
},
"devDependencies": {
  "@sveltejs/adapter-vercel": "^3.0.3",
  "@sveltejs/kit": "^1.25.0",
  "svelte": "^4.2.1",
  "svelte-preprocess": "^5.0.4",
  "typescript": "^5.2.2",
  "vite": "^4.4.9"
}
```

### Expected behavior

The authentication flow should work with the base path.

**Comment by jonek** [comment]
@aakash14goplani I just tested the example from my reproduction URL https://github.com/jonek/next-auth/commits/example-fix-base-path/apps/examples/sveltekit for issue https://github.com/nextauthjs/next-auth/issues/8230 against these versions of the dependencies:
```
  "dependencies": {
    "@auth/core": "^0.14.0",
    "@auth/sveltekit": "^0.3.7"
  }
```
Those versions contain the changes from this PR https://github.com/nextauthjs/next-auth/pull/8231.
I can confirm that the example that was broken before, started working as expected when using the versions of the dependencies above.

I also verified that it still works with the versions you included in this bug report that are even newer than above.

The only obvious difference is that you seem to be using `@sveltejs/adapter-vercel` while I was using `@sveltejs/adapter-auto`.

**Comment by aakash14goplani** [comment]
@jonek - after comparing my code with your, I realized there is no need to add `prefix` property in the configuration object.

For the folks looking for solution, here is how it is to be done:

1. Login on user Action:
   - In the *svelte.config.js` file set `base` property.
   - Initiate sign-in flow: `signIn('auth0', { redirect: false }, { scope: '...' })`
   - Initiate sign-out flow: `signOut()`

2. Login Programmatically:
   - First step remains same i.e. to update *svelte.config.js` file with `base` property.
   - Sign-in request: key is to add prefix (*hello*, in this example) in API calls:
      ```ts
      const tokenCall = await fetch('/hello/auth/csrf');
      ...
      const signInRequest = await fetch('/hello/auth/signin/auth0? ' + params.toString(), {
        method: 'POST',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          'X-Auth-Return-Redirect': '1'
        },
        body: formData.toString()
      });
      ```
   - Sign-out request
      ```ts
      const tokenCall = await fetch('/hello/auth/csrf');
      ...
      await fetch('/hello/auth/signout', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          'X-Auth-Return-Redirect': '1'
        },
        body: formData.toString()
      });
      ```
