### ISSUE TITLE
How to get OAuth2 Access Token in API request using custom provider configuration

### ISSUE THREAD

**Issue by ChuckJonas** [nextauthjs/next-auth#871]
**Your question**

How do I get the OAuth2 `access_token` in API request for custom provider configuration?

**What are you trying to do**

I have an app that is authenticating users with an oAuth2 service (Salesforce) and then will make requests on there behave.

I have configured next-auth so that I am successfully able to login using the "custom provider"

```typescript
import NextAuth, { InitOptions } from 'next-auth';
import Providers from 'next-auth/providers';

const options: InitOptions = {
  providers: [
    {
      id: 'salesforce',
      name: 'Salesforce',
      type: 'oauth',
      version: '2.0',
      scope: 'api',
      params: { grant_type: 'authorization_code' },
      accessTokenUrl: 'https://test.salesforce.com/services/oauth2/token',
      requestTokenUrl: 'https://test.salesforce.com/services/oauth2/authorize',
      authorizationUrl: 'https://test.salesforce.com/services/oauth2/authorize?response_type=code',
      profileUrl: 'https://test.salesforce.com/services/oauth2/userinfo',
      profile: (profile, token) => {
        console.log('profile!', profile, token);
        return {
          id: profile.user_id,
          name: profile.name,
          email: profile.email,
          image: profile.picture,
        };
      },
      clientId: process.env.CLIENT_ID,
      clientSecret: process.env.CLIENT_SECRET,
    },
  ],
};

export default (req, res) => NextAuth(req, res, options);
```

Now I need to pull data from the salesforce REST API using the access token which is returned by the oAuth request.  However, it's unclear how I can get the access token in my `API` service.

```typescript
// pages/api/getData

import { NextApiRequest, NextApiResponse } from 'next';
import { Rest } from 'ts-force';
import { getSession } from 'next-auth/client';
export default async (req: NextApiRequest, res: NextApiResponse) => {
  const session = await getSession({ req });
  console.log('Session', JSON.stringify(session, null, 2)); //does not contain access token
  try {
    console.log(req.query['sobject']);
    const r = new SFRestClient({
      instanceUrl: ???,
      accessToken: ???,
    });
    res.statusCode = 200;
    res.json(await (await r.request('/services/data/v49.0/sobjects/')).data);
  } catch (e) {
    throw new Error('Failed to load SObjects!');
  }
};

```

Seems like maybe JWT needs to be setup so the token can securely be stored on the client side?  Unfortunately I'm not finding any clear documentation or examples of this.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Hi.

You should probably check out the `jwt` and `session` [callbacks](https://next-auth.js.org/configuration/callbacks).

Our identity provider sent an access token in the `jwt` callback's third argument, called accound in the first call. Returning a new token in `jwt` and returning the second argument in `session` made the `access_token` available through `get|useSession`
