### ISSUE TITLE
how to set localstorage after successful signin

### ISSUE THREAD

**Issue by arifikhsan** [nextauthjs/next-auth#872]
**Your question**
how to set localstorage in next auth?.

**What are you trying to do**
i want to save user information in local storage using next auth after signin success. so that i can use the value into axios interceptors.

i cant use useSession() because of invalid hook

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Could you tell a bit more about what this means:
> i cant use useSession() because of invalid hook


It is probably not an issue with `next-auth`, but how you try to access the session. Make sure you follow the [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html).

When `useSession()` is used correctly, you could create the following hook that updates `localStorage`:

```js
function useSessionToLocalStorage() {
  const [session] = useSession()

  React.useEffect(() => {
  if(localStorage.getItem("session-info"))
    return 
  }
  localStorage.setItem("session-info", JSON.stringify(/*part of the session you want to save*/))
  }, [session])  
}
```


Please note, that you generally do not want to save sensitive information in `localStorage`, as it might be read by any JavaScript accessing your site. If you absolutely must, maybe you could use `sessionStorage` instead, but probably you do not need any of these, if you just use `useSession()` correctly. If you are server-side (for example an `/api` route or `getServerSideProps`), you can also try to use [`getSession()`](https://next-auth.js.org/getting-started/client#getsession) instead.

**Comment by arifikhsan** [comment]
hi sir, thanks for the reply,

this is how my code is looks like.
when signin is success, i request an `access-token` from my backend. and then`access-token` is sent via response header, which saved into `token`.

`next auth jwt` callback:

```javascript
jwt: async (token, user, account, profile, isNewUser) => {
      const isSignIn = !!user;

      if (isSignIn) {
        token.id = account.id;
        const response = await network.post(
          `${process.env.LOST_API_URL}/signin_from_google`,
          { profile: { email: token.email, id: token.id } }
        );

        // set token from api
        token["access-token"] = response.headers["access-token"];
        token["token-type"] = response.headers["token-type"];
        token.client = response.headers.client;
        token.expiry = response.headers.expiry;
        token.uid = response.headers.uid;
      }

      return Promise.resolve(token);
    },
```

my problem is, my axios interceptor is located in a `.js` file. outside a react component. somehow i need to get the `access-token` out from next auth.

in the future, my backend can provide a new `access-token`. so it must be saved into token too.

axios interceptor: 

```javascript
import axios from "axios";

const networkClient = axios.create({
  baseURL: process.env.NEXT_PUBLIC_LOST_API_URL,
  headers: {
    "X-Custom-Header": "foobar",
  },
});

networkClient.interceptors.request.use((config) => {
  config.headers = { "access-token": "### from next auth token ###" };
  return config;
});

networkClient.interceptors.response.use((res) => {
  // set new access-token from backend into token
  return res;
});

export default networkClient;
```

thats why i cannot use `useSession()` in axios config file. 
`token` is not available from `getSession()`

how can i read and write next-auth token in axios config file?

**Comment by balazsorban44** [comment]
`useSession` and `getSession` gets their data from the same place, namely `/api/auth/session` 

So if you don't have the token in your session, make sure you forward it properly with the session callback. 

(I do this in my `[...next-auth].js` callback options, I naddition to the jwt callback you wrote. I have one smiliar to yours.:
```js
//... 
session(_, token) {
  return token
}
//... 
```)

So with `next-auth`, you should have access to this token inside api routes, and I nyour frontend. 

If you call your apis in the api routes, you could easily attach the access token there, before they are sent. 

If you do it in the frontend, you could create a hook that returns your api client, but memoized, with setting the access token every time it changes.



Docs: https://next-auth.js.org/getting-started/client

**Comment by balazsorban44** [comment]
@arifikhsan I assume this helped, or you found a solution. I am going to close this, feel free to reopen or comment if you need further assistance.
