### ISSUE TITLE
`unable to resolve dependency tree when installing` typeorm-adapter

### ISSUE THREAD

**Issue by gkorland** [nextauthjs/next-auth#8769]
### Adapter type

@auth/typeorm-adapter

### Environment

  System:
    OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 16.05 GB / 31.06 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 17.6.0 - ~/.nvm/versions/node/v17.6.0/bin/node
    npm: 8.5.1 - ~/.nvm/versions/node/v17.6.0/bin/npm
    pnpm: 8.7.4 - ~/.nvm/versions/node/v17.6.0/bin/pnpm
  Browsers:
    Chrome: 117.0.5938.132

### Reproduction URL

https://github.com/FalkorDB/falkordb-cloud/

### Describe the issue

Error on npm install dependencies 

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: falkordb-cloud@0.1.0
npm ERR! Found: mssql@7.3.5
npm ERR! node_modules/mssql
npm ERR!   peerOptional mssql@"^6.2.1 || 7" from @auth/typeorm-adapter@1.0.2
npm ERR!   node_modules/@auth/typeorm-adapter
npm ERR!     @auth/typeorm-adapter@"^1.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional mssql@"^9.1.1" from typeorm@0.3.17
npm ERR! node_modules/typeorm
npm ERR!   typeorm@"^0.3.17" from the root project
npm ERR!   peer typeorm@"^0.3.7" from @auth/typeorm-adapter@1.0.2
npm ERR!   node_modules/@auth/typeorm-adapter
npm ERR!     @auth/typeorm-adapter@"^1.0.2" from the root project
```

### How to reproduce

Set the following in your package.json

```
  "dependencies": {
    "@auth/typeorm-adapter": "^1.0.2",
    }
```

### Expected behavior

dependencies install without errors

**Comment by gkorland** [comment]
thanks!

**Comment by balazsorban44** [comment]
It's out already. https://github.com/nextauthjs/next-auth/releases/tag/%40auth%2Ftypeorm-adapter%401.0.3

You can check https://github.com/nextauthjs/next-auth/releases for when something is released.
