### ISSUE TITLE
Updating @auth/core breaks type declaration for added Session properties

### ISSUE THREAD

**Issue by sillvva** [nextauthjs/next-auth#8792]
### Environment

  System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 78.91 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.2 - /usr/local/bin/node
    npm: 9.5.1 - /usr/local/bin/npm
    pnpm: 8.7.6 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 117.0.5938.132
    Safari: 17.0

### Reproduction URL

https://github.com/sillvva/ddal-svelte/tree/auth/corev0.10.0

### Describe the issue

I am using `@auth/core` and `@auth/sveltekit` in my SvelteKit app.

When I update `@auth/core` to any version later than `0.10.0`, it breaks the following type declaration:

```ts
import "@auth/core/types";

declare module "@auth/core/types" {
	interface Session {
		user?: {
			id: string;
		} & DefaultSession["user"];
		error?: string;
	}
}
```

And the following code in `src/hooks.server.ts` complains that the properties don't exist on the Session.

![CleanShot 2023-10-04 at 13 43 49@2x](https://github.com/nextauthjs/next-auth/assets/5138384/659b6ffe-0644-4a43-9b65-11c2e2659f63)

This causes those properties to break throughout the application.

### How to reproduce

1. Clone the repo
2. Install the packages
3. Update `@auth/core`
4. Open `src/hooks.server.ts`
5. Restart the TS server

Before:
![CleanShot 2023-10-04 at 13 49 17@2x](https://github.com/nextauthjs/next-auth/assets/5138384/ea6bf5c7-5ddc-4c40-8cf1-bf17aefb8870)

After:
![CleanShot 2023-10-04 at 13 48 31@2x](https://github.com/nextauthjs/next-auth/assets/5138384/e86a5afa-4282-40fb-855c-cc4f7de586ac)

### Expected behavior

The type declaration should continue to work.

**Comment by sillvva** [comment]
Found a temporary work around:

1. Import the custom Session type from the declaration.
2. Assign custom values to variables.
3. Output a custom object using `satisfies` with the imported type.

```ts
// hooks.server.ts
import type { ..., Session, ... } from "@auth/core/types";

export const auth = SvelteKitAuth({
	callbacks: {
		...
		async session({ session, user }) {
			let err = "";
			let userId = "";

			...

			return {
				...session,
				error: err,
				user: {
					...session.user,
					id: userId
				}
			} satisfies Session;
		}
	},
	...
})
```

4. In the layout, import the custom type from the declaration.
5. Assign the session to a variable with that type, modifying as needed.

```ts
// +layout.server.ts
import type { Session } from "@auth/core/types";

...

const session: Session | null = await event.locals.getSession();
```

**Comment by ThangHuuVu** [comment]
hi @sillvva do you still see the issue for the latest release of `@auth/core`?

**Comment by sillvva** [comment]
> hi @sillvva do you still see the issue for the latest release of `@auth/core`?

In 0.16.0 and 0.17.0 it is still broken. The below screenshot is from 0.17.0. Though I'm not particularly worried about it anymore since the above fixes the type issues. It's just a bit messier is all.

![CleanShot 2023-10-22 at 08 17 38@2x](https://github.com/nextauthjs/next-auth/assets/5138384/251dbfaf-1143-4417-8655-15195acc167e)

![CleanShot 2023-10-22 at 08 17 57@2x](https://github.com/nextauthjs/next-auth/assets/5138384/36bc8590-b630-4bc4-9a92-16dee6bb8c5f)
