### ISSUE TITLE
Azure B2C "Forgot My Password"

### ISSUE THREAD

**Issue by BenRedmondBenham** [nextauthjs/next-auth#882]
**Your question**
How do I handle Azure B2C "forgot my password" redirect to my nextauth app.

**What are you trying to do**
When I click "forgot my password" on an azure b2c flow, I get redirected to the next auth app. I want to capture that I have been redirected here so i can handle appropriately.

**Feedback**
I followed this ticket for my b2c setup: https://github.com/nextauthjs/next-auth/issues/468 I have a feeling the issue is that state is set to false but setting it to true breaks it.

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Hi there! Could you be able to share more context here? Maybe some relevant Azure B2C documentation?

Also, if it is helpful, `next-auth@canary` now includes this provider by default: https://next-auth-git-canary.nextauthjs.vercel.app/providers/azure-ad-b2c

**Comment by BenjaminWFox-Lumedic** [comment]
@balazsorban44 it's the same issue mentioned here: https://github.com/nextauthjs/next-auth/issues/517

**Comment by vadymberkut-unicreo** [comment]
Check my answer related to this here https://github.com/nextauthjs/next-auth/issues/1234#issuecomment-872881725. Might be useful.

**Comment by vadimberkut** [comment]
Check my answer related to this here https://github.com/nextauthjs/next-auth/issues/1234#issuecomment-872882814. Might be useful.
