### ISSUE TITLE
Google Provider Sveltekit - Error 400 redirect_uri_mismatch

### ISSUE THREAD

**Issue by DaviRolim** [nextauthjs/next-auth#8827]
### Provider type

Google

### Environment

 System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
    Memory: 6.25 GB / 15.50 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.2.0 - ~/Documents/projects/chadebebe/node_modules/.bin/npm
    pnpm: 8.1.1 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 117.0.5938.132

### Reproduction URL

https://github.com/DaviRolim/google-auth-issue

### Describe the issue

Google provider for sveltekit is giving `Error 400 redirect_uri_mismatch` even though is configured properly (following the documentation).

This is my svelteKitProvider:
![image](https://github.com/nextauthjs/next-auth/assets/19915084/a89691a2-b47d-46c7-ad6e-a93d9caa3d18)

With this configuration, I can access a sign-in page using svelte on `http://localhost:5173/auth/signin`  and this page is shown:
![image](https://github.com/nextauthjs/next-auth/assets/19915084/46cac01f-0342-4a91-9eaa-ae0f5a0f0623)

When I click the Sign in with Google button, the consent page opens but with this error:
![image](https://github.com/nextauthjs/next-auth/assets/19915084/d38d8a73-7aeb-437b-afb0-16cdfda73309)

When I click on `error details`:
![image](https://github.com/nextauthjs/next-auth/assets/19915084/15128117-2af5-43b1-9d77-8c2d40d1f2d2)

Checking the documentation and some guides on how to fix this error, I should just copy and paste the redirect_uri provided on the error on my `Authorized redirect URIs` on Google Console, as shown below:
![image](https://github.com/nextauthjs/next-auth/assets/19915084/00e3afe4-ff24-46a5-8caf-6292c39f1258)

I tried with this URI, and tried with .../api/auth/callback/google and others but nothing seems to fix this redirect error.

I tried using other providers like Github and it works as expected. I also tested EmailProvider and it worked as well. Only google is presenting this error.

### How to reproduce

- Clone the github repo on `Reproduction URL`.
- Install the dependencies.
- Create a `.env.local` file and add values for  `AUTH_SECRET`, `GOOGLE_CLIENT_ID`, `GOOGLE_CLIENT_SECRET`.
- Run the application `npm run dev`.
- Go to `http://localhost:5173/auth/signin`.
- Click the Sign In with Google button

### Expected behavior

The error 400 redirect_mismatch page should appear on the consent screen.

**Comment by fabiorodriguesroque** [comment]
I've cloned your repo, and everything works. are you sure that your keys are setup correctly ?

**Comment by DaviRolim** [comment]
I'm not sure. The steps I took to configure the keys were:

- Go to the [Google developer identity console](https://developers.google.com/identity/oauth2/web/guides/get-google-api-clientid).
- Followed these steps:
![image](https://github.com/nextauthjs/next-auth/assets/19915084/a68ce249-45ec-42f2-8a46-87876e99a0cf)
- Added the URIs for Authorized JavaScript origins and Authorized redirect URIs.

That was all I've done. Should I've done something differently? How do I know that I configured it incorrectly?

If there's any information you need to help me figure this out I'll be happy to share, just let me know. Thank you.

**Comment by DaviRolim** [comment]
Found the issue, my **~/.zshenv** was overwriting my **.env.local**. I'll close this issue. @fabiorodriguesroque Thanks again for taking the time, knowing that the keys were the problem made it easy to find out the issue.
