### ISSUE TITLE
`accessToken` missing in session object for GitHub provider

### ISSUE THREAD

**Issue by ogroppo** [nextauthjs/next-auth#883]
**Your question**
The `accessToken` prop is missing in session object.

**What are you trying to do**
After having logged in with GitHub, I expect the accessToken to be available.
This is needed to make requests to GitHub.

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by afoyer** [comment]
@ogroppo maybe #862 will help

**Comment by ogroppo** [comment]
@afoyer many thanks for getting back to me so swiftly, all good now! 👍
