### ISSUE TITLE
Nextjs Server Actions when using next auth

### ISSUE THREAD

**Issue by Rosalza** [nextauthjs/next-auth#8855]
### Environment

```
  System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 131.84 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.7.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 118.0.5993.70
    Edge: 117.0.2045.47
    Safari: 16.1
```

### Reproduction URL

https://github.com/Rosalza/pulsepoint-prod/blob/main/src/app/app/page.tsx

### Summary

Hello I want to use Server Actions to handle my forms.

But with the implementation below I get the following error (Note: I only get this error when nextAuth is used for auth in a project)

I think this has something to do with the fact that I am using next-auth in this project because I do not get this error in a project that is not using next-auth.

**Error:** 
```
Error: e._formData.get is not a function
```

### How to reproduce

Code:
```
import React from 'react'

export default async function page() {

  async function handle(data: FormData) {
    'use server'
    console.log('test!')
  }

  return (
    <div>
      <form action={handle}>
        <input type='email' name='email' />
        <input type='password' name='password' />
        <button type='submit'>Submit</button>
      </form>
    </div>
  )
}
```

### Expected behavior

Logging "test!" in the server logs.

**Comment by balazsorban44** [comment]
Server Actions support is being worked on. You can follow/test out #7443
