### ISSUE TITLE
Custom User Schema/Model ignoring custom fields

### ISSUE THREAD

**Issue by carlobolla** [nextauthjs/next-auth#891]
**Your question**
I can't understand why my custom fields for a User are not stored in the database (MongoDB). I'm surely missing a step, but cannot find it in the documentation.

**What are you trying to do**
These are my relevant snippets. I have added a 'country' field to the default User schema for testing.
I read about the `createUser` event, but it doesn't access the profile information returned from the provider.

```javascript
// pages/api/auth/[...nextauth].js

import NextAuth from 'next-auth'
import Models from '../../../models'
import Adapters from 'next-auth/adapters'

const options = {
  providers: [
    {
      id: 'vatsim',
      name: 'VATSIM Connect',
      type: 'oauth',
      version: '2.0',
      scope: 'full_name vatsim_details email country',
      params: { grant_type: 'authorization_code' },
      authorizationUrl: process.env.VATSIM_AUTH_URL,
      accessTokenUrl: process.env.VATSIM_TOKEN_URL,
      profileUrl: process.env.VATSIM_PROFILE_URL,
      profile: (profile) => {
        return {
          id: profile.data.cid,
          name: profile.data.personal.name_full,
          email: profile.data.personal.email,
          image: null,
          verifiedEmail: null,
          country: profile.data.personal.country.id
        }
      },
      clientId: process.env.VATSIM_CLIENT_ID,
      clientSecret: process.env.VATSIM_CLIENT_SECRET
    }
  ],
  database: process.env.AUTH_DB,
  adapter: Adapters.TypeORM.Adapter(
    process.env.AUTH_DB,
    {
      models: {
        User: Models.User
      }
    }
  ),
  debug: true
}
export default (req, res) => NextAuth(req, res, options)
```

```javascript
// models/user.js

import Adapters from 'next-auth/adapters'

export default class User extends Adapters.TypeORM.Models.User.model {
  constructor (name, email, image, emailVerified, country) {
    super(name, email, image, emailVerified)
    if (country) { this.country = country }
  }
}

export const UserSchema = {
  name: 'User',
  target: User,
  columns: {
    ...Adapters.TypeORM.Models.User.schema.columns,
    country: { type: String }
  }
}
```

```javascript
// models/index.js

import User, { UserSchema } from './User'

export default {
  User: {
    model: User,
    schema: UserSchema
  }
}

```

This is the resulting User:
```
[next-auth][debug][typeorm_create_session] User {
  name: 'Web One',
  email: [REDACTED],
  createdAt: 2020-11-28T15:25:08.457Z,
  updatedAt: 2020-11-28T15:25:08.457Z,
  emailVerified: null,
  image: null,
  id: 5fc26bd4a4ad16177c2300ee
}
```

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

Edit: syntax '^^

**Comment by rjblopes** [comment]
Crossed this issue while trying to solve another one. 

I'm not expert but I just found in the source that the built-in default adapter calls the User constructor with exact args (name, email, image, emailVerified); therefore your custom property will never be seen by your class constructor.

The only way I see to workaround this is to create a custom Adapter (https://next-auth.js.org/tutorials/creating-a-database-adapter). In the `createUser` method you have access to the exact profile returned by the provider.

**Comment by luizwhite** [comment]
I can't get it to work too..
when the session/jwt is "revalidated", they get a user from the database without the custom props (even if the database users has those props and i defined a new User model)

Should i create a new issue to raise this problem?
