### ISSUE TITLE
Passing an argument to callbacks via getSession? (conditionally query database through callbacks)

### ISSUE THREAD

**Issue by dayvista** [nextauthjs/next-auth#892]
**Your question**
Is it possible to pass an argument to the callback functions via getSession or some other way?

**What are you trying to do**
I would like to conditionally call my database to update the session via a callback when a logged-in user updates personal information (like a profile picture or name). Currently, I'm able to throttle the session refreshes so as not to spam my API too badly, but I'd prefer to choose when my database gets called.

I found [this issue/comment](https://github.com/nextauthjs/next-auth/issues/371#issuecomment-722175124) very helpful when trying to force an update of the session object without making too many unnecessary calls to my database. I'm still making more API calls than I would prefer. This solution is somewhat hacky and I'm not sure how it will perform in production.

Is this just a shortcoming of the library? From other issues, it seems that this feature has the possibility of being implemented in the future, but I need a fix ASAP.

Thanks to anyone that takes the time to respond. It seems like this library is being swamped with issues and I'm not sure what it's maintenance status is.

**Feedback**

* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by iaincollins** [comment]
> Is it possible to pass an argument to the callback functions via getSession or some other way?

Can you give an example in code / psuedo-code of what you'd like to be able to do?

> I would like to conditionally call my database to update the session via a callback when a logged-in user updates personal information (like a profile picture or name). Currently, I'm able to throttle the session refreshes so as not to spam my API too badly, but I'd prefer to choose when my database gets called.

The `updateAge` property lets you choose how often to update session server side.

https://next-auth.js.org/configuration/options#session

e.g. if `maxAge` is 30 days and `updateAge` is 24 hours, then the session state will not be updated unless the session is 29 days old (but the session will still expire at 30 days in activity) as a simple way of throttling that avoids writing to the session database every time a session is checked.

If you also want to avoid *reading* from the database too often then I would look at JWT sessions, as they only need to read from the database at sign in - you can also add conditional logic to the `jwt` session to preform call other functions as needed.

**Comment by dayvista** [comment]
Thanks for the quick response, @iaincollins. I believe that I've worked out the logic of what I'm trying to do.

I'm currently using JWT sessions. I'm reducing the frequency that the session is auto-fetched using sessionOptions and setting the options in the AuthProvider in _app.js.

```
const sessionOptions = {
  clientMaxAge: 2 * 60 * 60,
  keepAlive: 60 * 60,
};

const App = ({ Component, pageProps }) => {
  return (
    <AuthProvider session={pageProps.session} options={sessionOptions}>
      <Component {...pageProps} />
    </AuthProvider>
  );
};
```
In my JWT callback in [...nextauth].js, I'm calling the database to receive the full user object that pertains to the current user, then passing certain parameters from that object to the session state:
```
jwt: async (token, user) => {
      const tokenObj = user ? user : token;

      const userParams = await prisma.user.findUnique({
        where: {
          email: tokenObj.email,
        },
      });

      token.name = userParams.name;
      token.image = userParams.image;
      token.role = userParams.userRole;
      token.startDate = userParams.emailVerified.toLocaleString();

      return Promise.resolve(token);
    },
    session: async (session, user) => {
      session.user.name = user.name;
      session.user.image = user.picture;
      session.user.role = user.role;
      session.user.startDate = user.startDate;

      return Promise.resolve(session);
    },
```
I then pass the session state object to a global state object created with the Context API. This way, I can make sure that components are never referencing a stale session state (a problem I've seen some people mention in other issues here). I can use the Context state within components instead of getSession or useSession - thus, I'm able to (nearly) fully control when the JWT callback function is called (and my database is queried, most importantly) using getSession (save for when the session is refreshed, or the user reloads the page, or performs some other action I'm not yet aware of).

At least, I think I have it figured out. 😁 I'm rather new to this library and Next.js in general. Thanks for creating such a simple and helpful library! I got auth worked out in a couple of days and I get to own my data/database. It's a win-win.

**Comment by tpulido** [comment]
Is this best practice? I'm trying to do something very similar and for the past hours I've been trying to get the user data inside of the session callback, to not call my db on every request. Is this possible at all or would this be the only way to go?

**Comment by dayvista** [comment]
I'm not sure. [The solution I thought I had figured out](https://github.com/nextauthjs/next-auth/issues/892#issuecomment-736193804) didn't end up working for me after all. It's been a while since I tried using next-auth and I don't recall exactly what issues I ran up against. I ended up using [supabase's auth feature](https://github.com/supabase/supabase) with cookies via [next-iron-session](https://github.com/vvo/next-iron-session) to implement auth in my app.
