### ISSUE TITLE
How do you redirect after successful login?

### ISSUE THREAD

**Issue by gbwashleybrown** [nextauthjs/next-auth#893]
How do you redirect after successful login?

**What are you trying to do**
Redirect after logging in with a provider, such as Google. After I'm re-directed back to my website from Google, it sends me back to the login page. Why do I go back to the login page? Is there anyway to change this? 
I'm using a custom login page by the way. After logging in, I'd want to go to /dashboard.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x ] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by get6** [comment]
I think you already resolved this problem.

For finding the same problem here is the answer.

add options in [...nextauth].js 
`
  callbacks: {
    redirect: async (_url: string, baseUrl: string) => {
      return Promise.resolve(`/dashboard`);
    },
  },
`
