### ISSUE TITLE
Auth0 can't sign out

### ISSUE THREAD

**Issue by domlen2003** [nextauthjs/next-auth#8976]
### Provider type

Auth0

### System:
- OS: macOS 14.0
- CPU: (8) arm64 Apple M1
- Memory: 78.97 MB / 8.00 GB
- Shell: 5.9 - /bin/zsh
### Binaries:
- Node: 16.15.0
- npm: 9.8.1
### Browsers:
- Chrome: 118.0.5993.117
### AuthJs
- @auth/core: 0.18.0
- @auth/sveltekit: 0.3.11

### Reproduction URL

https://github.com/domlen2003/cf-auth0-drizzle-sveltekit-example

### Describe the issue

When signin in everything works as intended, but signout doesn't remove the cookies from Auth0.
So when signing in again (directly after a signout) the user never sees the Auth0 site because the cookie still exist and Auth0 automatically uses it for granting a code again.

### How to reproduce

Configure a (SvelteKit) project with Auth0 as the only provider. 
Then signin, signout and signin again. 
The second signing wont bring you to the Auth0 signin screen but rather signin directly (as if you were never signed out and just refreshed).

### Expected behavior

After a signout the user should always be displayed with the signin options again. 
E.g. forgot password or change account is only possible this way.

**Comment by balazsorban44** [comment]
This is currently expected, as we don't support federated logouts out of the box yet, although it's possible to achieve. See #836
