### ISSUE TITLE
Broken link for Auth0 page

### ISSUE THREAD

**Issue by pippinmole** [nextauthjs/next-auth#8990]
### What is the improvement or update you wish to see?

The link below is broken:

![image](https://github.com/nextauthjs/next-auth/assets/40035529/69398581-6f0d-4f94-93d2-0db5d47eb9b7)

it points [here](https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/providers/auth0.ts) which doesn't exist:

![image](https://github.com/nextauthjs/next-auth/assets/40035529/459b8c8e-7ca7-4a9f-9d07-4eb779c12031)

### Is there any context that might help us understand?

Nope

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/providers/auth0

**Comment by balazsorban44** [comment]
These files have been moved to the v4 branch, care to open a PR?

https://github.com/nextauthjs/next-auth/tree/v4/packages/next-auth/src/providers

**Comment by pippinmole** [comment]
@balazsorban44 Done. Let me know if anything's wrong with what I've done - this is my first time opening a PR for nextauth.

**Comment by balazsorban44** [comment]
Fixed via #8998

If you have the time, would love to get it fixed for all other adapters too in a separate PE. 🙏
