### ISSUE TITLE
wrong path for route.ts on upgrade to v5

### ISSUE THREAD

**Issue by slysiou** [nextauthjs/next-auth#9001]
### What is the improvement or update you wish to see?

on https://authjs.dev/guides/upgrade-to-v5

in the sentence:
`The old configuration file, contained in the API Route (pages/api/auth/[...nextauth].ts), now becomes a 1-line handler for GET and POST requests for those paths.`

it must be: `app/api/auth/[...nextauth]/route.ts` and not `pages/api/auth/[...nextauth].ts`

Thanks for your amazing job !

### Is there any context that might help us understand?

Nothing to add ;-)

### Does the docs page already exist? Please link to it.

https://authjs.dev/guides/upgrade-to-v5

**Comment by balazsorban44** [comment]
Thanks, this was intentional as most people will likely come from the Pages Router/ API Routes rather than App Router/Route Handler world.
