### ISSUE TITLE
Spotify Provider Options: Dead URL

### ISSUE THREAD

**Issue by parisosuch-dev** [nextauthjs/next-auth#9005]
### What is the improvement or update you wish to see?

The URL for the spotify options no longer exists.

### Is there any context that might help us understand?

The url for the options on the [spotify provider page](https://next-auth.js.org/providers/spotify) no longer exists. The bullet point [Spotify Provider Options](https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/providers/spotify.ts), specifically.

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/providers/spotify

**Comment by parisosuch-dev** [comment]
If anyone could also explain why the `spotify.ts` no longer exits in `/src/providers/`, that would be great!

**Comment by balazsorban44** [comment]
Fixed in https://github.com/nextauthjs/next-auth/commit/09f5aabce6ec03652b0d825463f92c8fa6e016c1

`next-auth` v4 source code has been moved to a different branch
