### ISSUE TITLE
How can I pass additional parameters to signIn() function?

### ISSUE THREAD

**Issue by leodrez** [nextauthjs/next-auth#901]
**Your question**
How can I pass additional parameters to signIn with email function to use on callback?
Cant find passed values on the sign in callback

**What are you trying to do**
Im trying to add an additional "name" parameter to the signIn() function, along with the email and callback url. 
Currently Im using the prisma adapter and would like to add a value to the native "name" property that the schema requires you to have.

**Feedback**
https://next-auth.js.org/schemas/adapters
https://next-auth.js.org/getting-started/client#signin

`signIn("email", {
    email: email,
    callbackUrl: userCallbackUrl,
    name: 'Test Name',
})`

* [x] Could not find relevant documentation

**Comment by balazsorban44** [comment]
Hi, would https://github.com/nextauthjs/next-auth/pull/823 solve this issue?
