### ISSUE TITLE
Documentation outdated for Next.js 14 and 13.4

### ISSUE THREAD

**Issue by Manzoor231** [nextauthjs/next-auth#9014]
### What is the improvement or update you wish to see?

The NextAuth.js documentation is outdated for Next.js 14 and 13.4. For example, the code examples in the documentation are still using the old Next.js API routes and APIs. This can be confusing for developers who are trying to use NextAuth.js with the latest version of Next.js.

### Is there any context that might help us understand?

Next.js 14 and 13.4 introduced a number of breaking changes to the API routes and APIs. These changes are necessary to improve the performance and security of Next.js applications. However, they can also be disruptive for developers who are upgrading to the latest version of Next.js.

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/getting-started/introduction

**Comment by balazsorban44** [comment]
https://next-auth.js.org/ is going to be used for `next-auth` v4. Next.js API Routes are going to work as before, so no real reason to worry.

http://authjs.dev however is aimed to document `next-auth` v5 which you can try out now in beta, you can see https://authjs.dev/guides/upgrade-to-v5 so all code there will eventually be updated to App Router-first.

> Next.js 14 and 13.4 introduced a number of breaking changes to the API routes and APIs. These changes are necessary to improve the performance and security of Next.js applications. However, they can also be disruptive for developers who are upgrading to the latest version of Next.js.

This is incorrect information. None of these APIs have introduced breaking changes and will operate just as before. The App Router migration is fully optional.

**Comment by Manzoor231** [comment]
> https://next-auth.js.org/ is going to be used for `next-auth` v4. Next.js API Routes are going to work as before, so no real reason to worry.
> 
> http://authjs.dev however is aimed to document `next-auth` v5 which you can try out now in beta, you can see https://authjs.dev/guides/upgrade-to-v5 so all code there will eventually be updated to App Router-first.
> 
> > Next.js 14 and 13.4 introduced a number of breaking changes to the API routes and APIs. These changes are necessary to improve the performance and security of Next.js applications. However, they can also be disruptive for developers who are upgrading to the latest version of Next.js.
> 
> This is incorrect information. None of these APIs have introduced breaking changes and will operate just as before. The App Router migration is fully optional.

oh so so sorry, i was using old version maybe thats why but i am soo happy that you read my issue, because i really had issue with old documentation so i made alot of errors./
