### ISSUE TITLE
Next Auth fails within an iframe

### ISSUE THREAD

**Issue by bdesouza** [nextauthjs/next-auth#902]
**Describe the bug**
Unable to login with next-auth when the app is inside an iframe.

**Steps to reproduce**
Create a page with an iframe.

```
<iframe src="https://next-auth-example.now.sh/" width="100%" height="550"></iframe>
```

On inspection, noticed that the request is received in `[...nextauth].js`. However, the `NextAuth` app doesn't seem to act upon it.

```
export default (req, res) => {
   console.log(req.body);
   return NextAuth(req, res, options);
};
```

**Expected behavior**
Should work as normal and I should be able to login.

**Feedback**

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by mikestopcontinues** [comment]
Hey, what's your use case? I was just thinking about how to solve this problem for an app that needs to keep a user signed in across domains. I'm thinking maybe to use an iframe on `login.example.com` simply to store the session data, but not to handle sign-in. As an example, a user logs in on `admin.example.com`, window messaging sends the session data to the iframe, then when they visit `app.example.com`, their session is pulled from the iframe.

**Comment by bdesouza** [comment]
In our case, the app is loaded in an iframe by another application. Essentially a third party service that a customer can embed in their dashboard.
