### ISSUE TITLE
signIn() with credentials provider throws Error: Invariant: headers() expects to have requestAsyncStorage, none available.

### ISSUE THREAD

**Issue by mwolf1989** [nextauthjs/next-auth#9027]
### Environment

 System:
    OS: macOS 14.0
    CPU: (12) arm64 Apple M2 Pro
    Memory: 539.86 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.9.2 - ~/Library/pnpm/pnpm
    bun: 1.0.4 - ~/.bun/bin/bun
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 17.0

  npmPackages:
    next: 14.0.1 => 14.0.1 
    next-auth: beta => 5.0.0-beta.3 
    react: ^18 => 18.2.0 

  npmPackages:
    @auth/prisma-adapter: ^1.0.5 => 1.0.5 

### Reproduction URL

https://github.com/mwolf1989/next-14-authjs

### Describe the issue

If i create a custom login page

with this submit function:

    const onSubmit = async (data: z.infer<typeof registerFormSchema>) => {
        console.log("Login form submitted", data);
        await signIn("credentials", {
                redirect: true,
                redirectTo: "/",
            }, {
                email: data.email,
                password: data.password
            }
        )
    }

I get the error:

![Bildschirmfoto 2023-11-02 um 10 46 10](https://github.com/nextauthjs/next-auth/assets/17257611/8b6b71dc-b4a0-4ba9-b0e1-a48e7e632b8c)

with the build in login page it works.

### How to reproduce

Install  the project, create a user and try to login using the custom page.

### Expected behavior

The user should logged be in and get a session.

**Comment by thevuong** [comment]
Here's a good example that you can refer to:
https://github.com/vercel/next-learn/blob/94f19a17aa0b916b105ac4e1911e50ce85a0ec86/dashboard/final-example/app/lib/actions.ts#L122

**Comment by mwolf1989** [comment]
> Here's a good example that you can refer to: https://github.com/vercel/next-learn/blob/94f19a17aa0b916b105ac4e1911e50ce85a0ec86/dashboard/final-example/app/lib/actions.ts#L122

Thank you. is signIn() server only?

**Comment by balazsorban44** [comment]
Yes. That method is. for client-side signin, you can use the one from `next-auth/react`
