### ISSUE TITLE
MongoDB Connector

### ISSUE THREAD

**Issue by BrandonCopley** [nextauthjs/next-auth#908]
I am trying to connect to mongodb using next-auth and I receive the error:

    Cannot destructure property 'manager' of 'connection' as it is null

I have added my string to the [...nextAuth].js file, adding the option:

    database:   'mongodb://username:password@cluster0.vlmha.mongodb.net:27017/winston'

The database is a BLANK slate. Yet I cannot seem to connect to it and do email login.

**Comment by BrandonCopley** [comment]
I'm seeing lots of errors from the docs, I just think the docs may be outdated with google provider? I no longer get verified email from google oauth.

**Comment by BrandonCopley** [comment]
@balazsorban44 are you seeing errors now as well? I'm getting some really funky errors today from nextAuth.js

**Comment by balazsorban44** [comment]
Don't know if it's coincidence, might be related to Google outages today?: https://www.bbc.com/news/technology-55299779

**Comment by BrandonCopley** [comment]
Perhaps.
-- 
[image: Giftnix]

Brandon Copley

Founder & CEO

t: 512.784.6060 <(512)%20784-6060>

e: copley.brandon@gmail.com

**Comment by CodingJinxx** [comment]
Same here

**Comment by trivektor** [comment]
Me too

**Comment by joanoliete** [comment]
With a local mongodb database is working, not with Atlas

**Comment by balazsorban44** [comment]
@CodingJinxx @trivektor, thanks for chipping in, but a reproduction repo and some config information would be very helpful.

**Comment by c7nasr** [comment]
+1 here

**Comment by trivektor** [comment]
Here's my config https://github.com/trivektor/nextjs-ticket-tracking/blob/main/pages/api/auth/%5B...nextauth%5D.js#L11

After googling around, I found that the solution is to use typeorm 0.2.28

https://github.com/trivektor/nextjs-ticket-tracking/blob/main/package.json#L25

**Comment by c7nasr** [comment]
> Here's my config https://github.com/trivektor/nextjs-ticket-tracking/blob/main/pages/api/auth/%5B...nextauth%5D.js#L11
> 
> After googling around, I found that the solution is to use typeorm 0.2.28
> 
> https://github.com/trivektor/nextjs-ticket-tracking/blob/main/package.json#L25

`{
  "name": "next-test-auth",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "axios": "^0.21.1",
    "jsonwebtoken": "^8.5.1",
    "mongodb": "^3.6.3",
    "next": "10.0.5",
    "next-auth": "^3.1.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "reflect-metadata": "^0.1.13",
    "typeorm": "0.2.28"
  },
  "peerOptionalDependencies": {
    "mongodb": "^3.6.2"
  },
  "resolutions": {
    "typeorm": "0.2.28"
  }
}
`

my Package.json and still get this error

`[next-auth][error][oauth_callback_handler_error] TypeError: Cannot destructure property 'manager' of 'connection' as it is null.`

**Comment by BrandonCopley** [comment]
typeorm 0.2.29 has a bug in it, not sure when they'll fix it.
-- 
[image: Giftnix]

Brandon Copley

Founder & CEO

t: 512.784.6060 <(512)%20784-6060>

e: copley.brandon@gmail.com

**Comment by balazsorban44** [comment]
So as far as I can understand, this is an upstream issue, not  directly `next-auth`. I would like to close this issue then, feel free to comment later on, when a fix is released upstream, so we can incorporate it here as well.
