### ISSUE TITLE
Problem with routing after setting basePath and internationalization

### ISSUE THREAD

**Issue by kjxbyz** [nextauthjs/next-auth#9091]
### Environment

```
  System:
    OS: macOS 14.1.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 32.48 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.9.2 - /usr/local/bin/pnpm
    bun: 1.0.4 - /usr/local/bin/bun
    Watchman: 2023.10.02.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 119.1.60.110
    Chrome: 119.0.6045.123
    Safari: 17.1


  npmPackages:
    next: 13.4.12 => 13.4.12 
    next-auth: 4.24.4 => 4.24.4 
    react: 18.2.0 => 18.2.0 


  npmPackages:
    @auth/prisma-adapter: ^1.0.5 => 1.0.5 
```

### Reproduction URL

https://github.com/cyf/cyf-insider/tree/i18n

### Describe the issue

Problem with routing after setting basePath and internationalization

incorrect path: `https://dev.chenyifaer.com/join/zh/join/sign-in/`

correct path: `https://dev.chenyifaer.com/join/zh/sign-in/`

### How to reproduce

1. Visit `https://dev.chenyifaer.com/join/zh/` in the browser
2. Click the `加入计划` button

### Expected behavior

Routing is correct

**Comment by balazsorban44** [comment]
see https://github.com/nextauthjs/next-auth/issues/9425#issuecomment-1909248027
