### ISSUE TITLE
In authorized callback auth object is null all the time

### ISSUE THREAD

**Issue by amit548** [nextauthjs/next-auth#9097]
### Environment

 System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 5500U with Radeon Graphics
    Memory: 5.76 GB / 15.38 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.9.2 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.44)
    Internet Explorer: 11.0.22621.1

  npmPackages:
    next: ^14.0.1 => 14.0.1 
    next-auth: ^5.0.0-beta.3 => 5.0.0-beta.3 
    react: 18.2.0 => 18.2.0 

### Reproduction URL

https://github.com/nextauthjs/next-auth-example/blob/main/auth.ts

### Describe the issue

![image](https://github.com/nextauthjs/next-auth/assets/36206377/fd1c9d5e-b666-4556-a4cf-ae626c98ee9a)
![image](https://github.com/nextauthjs/next-auth/assets/36206377/78281439-0329-45dc-a0a5-3fc0e2c8dbc4)

**After login with credentials, in the authorized callback I can't access auth object, all time auth object is null but when I check cookies the session token is present**

### How to reproduce

use credentials provider

### Expected behavior

the auth object should not be empty or null after login

**Comment by apshenichniy** [comment]
I encountered the same problem. Adding AUTH_URL to the environment variables solved it.

**Comment by amit548** [comment]
> I encountered the same problem. Adding AUTH_URL to the environment variables solved it.

Thank you, it works.

**Comment by travelerr** [comment]
Confirmed also works for me. Was encountering this with my localhost:3000 while auth worked as expected in prod vercel site. Vercel must automatically set an AUTH_URL env variable? 

Working example: AUTH_URL="http://localhost:3000"

**Comment by vinayavodah** [comment]
Thanks @apshenichniy!

**Comment by leohxj** [comment]
> Confirmed also works for me. Was encountering this with my localhost:3000 while auth worked as expected in prod vercel site. Vercel must automatically set an AUTH_URL env variable?确认也对我有用。我的 localhost：3000 遇到了这个问题，而 auth 在 prod vercel 站点中按预期工作。Vercel 必须自动设置一个 AUTH_URL 环境变量？
> 
> Working example: AUTH_URL="http://localhost:3000"工作示例：AUTH_URL=“ http://localhost:3000”

add `AUTH_URL="http://localhost:3000"` in `.env` file, but always got null.

**Comment by Vibrat** [comment]
I experienced the same issue. In my case it's due to same-site origin policy that prevents exchanging cookies which leads to `null` on `session = await auth()`. The solution is changing to fetch  `local` API.  I'm not sure what causes this and would love to hear an answer from everyone. 

```javascript

// This will works
return await fetch(
        `/api/payments`,
        {
          method: "POST",
          body: JSON.stringify(data),
        }
);

// This will not work as expected
return await fetch(
        `http://127.0.0.1:3000/api/payments`,
        {
          method: "POST",
          body: JSON.stringify(data),
        }
);
 ```

**Comment by iamdevlinph** [comment]
Adding `AUTH_URL="http://localhost:3000"` didn't help for me. It's still returning null.

![Image](https://github.com/user-attachments/assets/94356aff-e77e-4e82-8c37-fde14aa8763d)

```ts
// auth.ts
import NextAuth from "next-auth";
import Google from "next-auth/providers/google";

export const { handlers, signIn, signOut, auth } = NextAuth({
  providers: [Google],
  pages: {
    signIn: "/",
    error: "/",
  },
  callbacks: {
    authorized: async ({ auth }) => {
      console.log("🍉 ~ authorized: ~ auth:", auth);
      console.log(
        "🍉 ~ authorized: ~ process.env.AUTH_URL:",
        process.env.AUTH_URL,
      );
      // return Promise.resolve(!!auth);
      return {};
    },
    // redirect: () => {
    //   return "/admin";
    // },
  },
});
```
