### ISSUE TITLE
allow custom errors to propagate to the client from authorized callback

### ISSUE THREAD

**Issue by amit548** [nextauthjs/next-auth#9099]
### Environment

 System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 5500U with Radeon Graphics
    Memory: 4.76 GB / 15.38 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.9.2 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.44)
    Internet Explorer: 11.0.22621.1

  npmPackages:
    next: ^14.0.1 => 14.0.1 
    next-auth: ^5.0.0-beta.3 => 5.0.0-beta.3 
    react: 18.2.0 => 18.2.0 

 npmPackages:
    @bomdi/codebox: ^2.0.0 => 2.0.0 
    @editorjs/attaches: ^1.3.0 => 1.3.0 
    @editorjs/checklist: ^1.5.0 => 1.5.0 
    @editorjs/code: ^2.8.0 => 2.8.0 
    @editorjs/delimiter: ^1.3.0 => 1.3.0 
    @editorjs/editorjs: ^2.28.2 => 2.28.2 
    @editorjs/embed: ^2.6.0 => 2.6.0 
    @editorjs/header: ^2.7.0 => 2.7.0 
    @editorjs/image: ^2.8.2 => 2.8.2 
    @editorjs/inline-code: ^1.4.0 => 1.4.0 
    @editorjs/link: ^2.5.0 => 2.5.0
    @editorjs/list: ^1.8.0 => 1.8.0
    @editorjs/marker: ^1.3.0 => 1.3.0
    @editorjs/nested-list: ^1.3.0 => 1.3.0
    @editorjs/paragraph: ^2.11.3 => 2.11.3
    @editorjs/quote: ^2.5.0 => 2.5.0
    @editorjs/raw: ^2.4.0 => 2.4.0
    @editorjs/simple-image: ^1.5.1 => 1.5.1
    @editorjs/table: ^2.2.2 => 2.2.2
    @editorjs/underline: ^1.1.0 => 1.1.0
    @editorjs/warning: ^1.3.0 => 1.3.0
    @hookform/resolvers: ^3.3.2 => 3.3.2
    @nx/cypress: 17.0.3 => 17.0.3
    @nx/esbuild: 17.0.3 => 17.0.3
    @nx/eslint: 17.0.3 => 17.0.3
    @nx/eslint-plugin: 17.0.3 => 17.0.3
    @nx/jest: 17.0.3 => 17.0.3
    @nx/js: 17.0.3 => 17.0.3
    @nx/next: 17.0.3 => 17.0.3
    @nx/node: 17.0.3 => 17.0.3
    @nx/react: 17.0.3 => 17.0.3
    @nx/workspace: 17.0.3 => 17.0.3
    @swc-node/register: ~1.6.7 => 1.6.8
    @swc/cli: ~0.1.62 => 0.1.62
    @swc/core: ~1.3.85 => 1.3.95
    @swc/helpers: ~0.5.2 => 0.5.2
    @tailwindcss/aspect-ratio: ^0.4.2 => 0.4.2
    @tailwindcss/typography: ^0.5.10 => 0.5.10
    @tanstack/eslint-plugin-query: ^5.6.0 => 5.6.0
    @tanstack/react-query: ^5.7.2 => 5.7.2
    @tanstack/react-query-devtools: ^5.7.2 => 5.7.2
    @tanstack/react-query-next-experimental: ^5.7.2 => 5.7.2
    @testing-library/react: 14.0.0 => 14.0.0
    @types/bcrypt: ^5.0.1 => 5.0.1
    @types/compression: ^1.7.4 => 1.7.4
    @types/cookie-parser: ^1.4.5 => 1.4.5
    @types/cors: ^2.8.15 => 2.8.15
    @types/express: ~4.17.13 => 4.17.20
    @types/hpp: ^0.2.4 => 0.2.4
    @types/jest: ^29.4.0 => 29.5.6
    @types/morgan: ^1.9.7 => 1.9.7
    @types/multer: ^1.4.9 => 1.4.9
    @types/node: 18.14.2 => 18.14.2
    @types/nodemailer: ^6.4.13 => 6.4.13
    @types/react: 18.2.24 => 18.2.24
    @types/react-dom: 18.2.9 => 18.2.9
    @types/validator: ^13.11.5 => 13.11.5
    @typescript-eslint/eslint-plugin: ^5.60.1 => 5.62.0
    @typescript-eslint/parser: ^5.60.1 => 5.62.0
    autoprefixer: ^10.4.16 => 10.4.16
    axios: ^1.6.0 => 1.6.0
    babel-jest: ^29.4.1 => 29.7.0
    bcrypt: ^5.1.1 => 5.1.1
    clsx: ^2.0.0 => 2.0.0
    compression: ^1.7.4 => 1.7.4
    cookie-parser: ^1.4.6 => 1.4.6
    cookies-next: ^4.0.0 => 4.0.0
    cors: ^2.8.5 => 2.8.5
    cypress: ^13.0.0 => 13.3.3
    daisyui: ^3.9.4 => 3.9.4
    date-fns: ^2.30.0 => 2.30.0
    dotenv: ^16.3.1 => 16.3.1
    editorjs-text-color-plugin: ^2.0.4 => 2.0.4
    esbuild: ^0.19.2 => 0.19.5
    eslint: ~8.46.0 => 8.46.0
    eslint-config-next: 13.4.1 => 13.4.1
    eslint-config-prettier: ^9.0.0 => 9.0.0
    eslint-plugin-cypress: ^2.13.4 => 2.15.1
    eslint-plugin-import: 2.27.5 => 2.27.5
    eslint-plugin-jsx-a11y: 6.7.1 => 6.7.1
    eslint-plugin-react: 7.32.2 => 7.32.2
    eslint-plugin-react-hooks: 4.6.0 => 4.6.0
    express: ~4.18.1 => 4.18.2
    express-mongo-sanitize: ^2.2.0 => 2.2.0
    express-rate-limit: ^7.1.3 => 7.1.3
    helmet: ^7.0.0 => 7.0.0
    hpp: ^0.2.3 => 0.2.3
    html-react-parser: ^5.0.5 => 5.0.5
    jest: ^29.4.1 => 29.7.0
    jest-environment-jsdom: ^29.4.1 => 29.7.0
    jest-environment-node: ^29.4.1 => 29.7.0
    jose: ^5.0.2 => 5.0.2
    lucide-react: ^0.290.0 => 0.290.0
    mongoose: ^7.6.3 => 7.6.3
    morgan: ^1.10.0 => 1.10.0
    multer: ^1.4.5-lts.1 => 1.4.5-lts.1
    nanoid: ^5.0.2 => 5.0.2
    next: ^14.0.1 => 14.0.1
    next-auth: ^5.0.0-beta.3 => 5.0.0-beta.3
    next-share: ^0.27.0 => 0.27.0
    nodemailer: ^6.9.7 => 6.9.7
    nx: 17.0.3 => 17.0.3
    postcss: ^8.4.31 => 8.4.31
    prettier: ^2.6.2 => 2.8.8
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    react-editor-js: ^2.1.0 => 2.1.0
    react-hook-form: ^7.47.0 => 7.47.0
    react-select: ^5.7.7 => 5.7.7
    react-toastify: ^9.1.3 => 9.1.3
    sharp: ^0.32.6 => 0.32.6
    tailwind-merge: ^2.0.0 => 2.0.0
    tailwindcss: ^3.3.5 => 3.3.5
    theme-change: ^2.5.0 => 2.5.0
    ts-jest: ^29.1.0 => 29.1.1
    ts-node: 10.9.1 => 10.9.1
    tslib: ^2.3.0 => 2.6.2
    typescript: ~5.1.3 => 5.1.6
    validator: ^13.11.0 => 13.11.0
    xss-clean: ^0.1.4 => 0.1.4
    zod: ^3.22.4 => 3.22.4

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

![image](https://github.com/nextauthjs/next-auth/assets/36206377/a110b549-94b4-4f6e-9521-524c3b7001ca)
![image](https://github.com/nextauthjs/next-auth/assets/36206377/6a346d2a-c9a6-4cff-99b8-fa1d66e40ca1)

**How can I access login related api error messages like password or email is invalid or etc, in next-auth v4 it works perfectly but in v5 does not work**

### How to reproduce

After login and If I do input some wrong credentials 

### Expected behavior

Login related error should be pass to the frontend so user can see the login error

**Comment by shgrth** [comment]
I've been having this exact problem since migrating to v5.

For some reason, next-auth decided to gatekeep this feature as a "security measure". It makes no sense. I have opened a discussion about this exact issue and it has zero responses. Maybe it's not important to them?

My company's web portal uses next-auth as auth. We can no longer prompt custom error messages to signIn calls for example when a user account is suspended or requires MFA.

**Comment by amit548** [comment]
> I've been having this exact problem since migrating to v5. #8999
> 
> For some reason, next-auth decided to gatekeep this feature as a "security measure". It makes no sense. I have opened a discussion about this exact issue and it has zero responses. Maybe it's not important to them?
> 
> Another thread mentioning the same issue was closed with no resolution.
> 
> My company's web portal uses next-auth as auth. We can no longer prompt custom error messages to signIn calls for example when a user account is suspended or requires MFA.

IDK, what kind of security measure they calculated but this is very important feature, it is required.

**Comment by shgrth** [comment]
> > I've been having this exact problem since migrating to v5. #8999
> > For some reason, next-auth decided to gatekeep this feature as a "security measure". It makes no sense. I have opened a discussion about this exact issue and it has zero responses. Maybe it's not important to them?
> > Another thread mentioning the same issue was closed with no resolution.
> > My company's web portal uses next-auth as auth. We can no longer prompt custom error messages to signIn calls for example when a user account is suspended or requires MFA.
> 
> IDK, what kind of security measure they calculated but this is very important feature, it is required.

This issue was raised back in January 2023 also. #6512 
The following comment explains the reason and the commit.

([#](https://github.com/nextauthjs/next-auth/issues/6512#issuecomment-1404902257))

I think it's a bad decision and a deal-breaker.

**Comment by amit548** [comment]
> > > I've been having this exact problem since migrating to v5. #8999
> > > For some reason, next-auth decided to gatekeep this feature as a "security measure". It makes no sense. I have opened a discussion about this exact issue and it has zero responses. Maybe it's not important to them?
> > > Another thread mentioning the same issue was closed with no resolution.
> > > My company's web portal uses next-auth as auth. We can no longer prompt custom error messages to signIn calls for example when a user account is suspended or requires MFA.
> > 
> > 
> > IDK, what kind of security measure they calculated but this is very important feature, it is required.
> 
> This issue was raised back in January 2023 also. #6512 The following comment explains the reason and the commit.
> 
> ([#6512 (comment)](https://github.com/nextauthjs/next-auth/issues/6512#issuecomment-1404902257))
> 
> I think it's a bad decision and a deal-breaker.

My mind though the same.

**Comment by gnllucena** [comment]
I've commented on #6512 on July still no response from next-auth team.

This library is amazing but having no communication between server side and client side with CredentialsProvider is really a deal breaker.

MFA authentication and First Time Login are really important features that are very hard (impossible AFAIK) to implement without the communication.

@balazsorban44 is there a way to implement this communication with the library? Will the library ever support this features again?

**Comment by shgrth** [comment]
Is there any way to get a response to this issue? Should this post be tagged with "providers"? I would like a confirmation from authjs team if this feature is deprecated forever or will be reverted back to how it was in V4, or a new secure way to throw custom errors to the front-end.

**Comment by A7med3bdulBaset** [comment]
I'm have the exace issue https://github.com/nextauthjs/next-auth/discussions/9249

This feature is required to my use case. If the v5 got red of it. I'll be ended by down grading back to v4. 

I hoped to knew this trade-off before upgrading

**Comment by amit548** [comment]
> I'm have the exace issue #9249
> 
> This feature is required to my use case. If the v5 got red of it. I'll end up with down-grading back to v4.
> 
> I hoped to knew this trade-off before upgrading

I have the same issue, so I downgraded it to v4 :(

**Comment by balazsorban44** [comment]
will revisit

**Comment by balazsorban44** [comment]
Wanted to let you know that I'm tracking this. I want to come up with a good solution here. Leave your comments! No need for "+1" or "need this" etc. comments, let's keep it effective and constructive. Come with suggestions!

My initial reasoning was to nudge developers to not send back errors like "invalid password" or "invalid username", which generally is not recommended, as you could let someone enumerate your users, probably other problems with it too.

## My proposal

Any generic error would still use the "catch-all" error type, but for custom ones that extend `AuthorizeError`, we would just re-throw.

We already do this actually, if you extend `AuthError`, but this was never documented:

https://github.com/nextauthjs/next-auth/blob/7963880593fa358905cd4e31285715783b66470f/packages/core/src/lib/actions/callback/index.ts#L373-L376

Not all `AuthError` should end up on the client either though, to obfuscate server details as much as possible. I've been meaning to come back to this here: 
https://github.com/nextauthjs/next-auth/blob/7963880593fa358905cd4e31285715783b66470f/packages/core/src/index.ts#L172-L173

**So** we need a specific error type, `AuthorizeError`, that you would use like so:

```ts
import { AuthorizeError } from "next-auth/errors"

class CustomAuthorizeError extends AuthorizeError {
  code = "custom"
}

// ...
authorize() {
  // ...
  throw new CustomAuthorizeError("foo")
}
```

Then, you would have the following options when you invoke `signIn`:

Client Components/Pages Router:

- get redirected to this error page `/error?error=AuthorizeError&code=custom`
- if `redirect: false` was set on `signIn`, it returns the error and code properties.

Server Actions:

- `await signIn()` would throw `CustomAuthorizeError` that you would need to handle in a catch block.

Let me know what you think about this?

**Comment by AmphibianDev** [comment]
> My initial reasoning was to nudge developers to not send back errors like "invalid password" or "invalid username", which generally is not recommended, as you could let someone enumerate your users, probably other problems with it too. So I just want to make doing this very explicit.

Ok, but how do I get rid of the error? Is there a way, right now, to make it the recommended way and get rid of the console error `[auth][error] CredentialsSignin ...`, even though it works, it annoys me so much! How can I get rid of it?

**Comment by amit548** [comment]
> Wanted to let you know that I'm tracking this. I want to come up with a good solution here. Leave your comments! No need for "+1" or "need this" etc. comments, let's keep it effective and constructive. Come with suggestions! (You can just 👍 👎 for a simple opinion)
> 
> My initial reasoning was to nudge developers to not send back errors like "invalid password" or "invalid username", which generally is not recommended, as you could let someone enumerate your users, probably other problems with it too. So I just want to make doing this very explicit.
> 
> ## My proposal
> Any generic error would still use the "catch-all" error type, but for custom ones that extend `AuthorizeError`, we would just re-throw.
> 
> We already do this actually, if you extend `AuthError`, but this was never documented:
> 
> https://github.com/nextauthjs/next-auth/blob/7963880593fa358905cd4e31285715783b66470f/packages/core/src/lib/actions/callback/index.ts#L373-L376
> 
> Not all `AuthError` should end up on the client either though, to obfuscate server details as much as possible. I've been meaning to come back to this here:
> 
> https://github.com/nextauthjs/next-auth/blob/7963880593fa358905cd4e31285715783b66470f/packages/core/src/index.ts#L172-L173
> 
> **So** we need a specific error type, `AuthorizeError`, that you would use like so:
> 
> ```ts
> import { AuthorizeError } from "next-auth/errors"
> 
> class CustomAuthorizeError extends AuthorizeError {
>   code = "custom"
> }
> 
> // ...
> authorize() {
>   // ...
>   throw new CustomAuthorizeError("foo")
> }
> ```
> 
> Then, you would have the following options when you invoke `signIn`:
> 
> Client Components/Pages Router:
> 
> * get redirected to this error page `/error?error=AuthorizeError&code=custom`
> * if `redirect: false` was set on `signIn`, it returns the error and code properties.
> 
> Server Actions:
> 
> * `await signIn()` would throw `CustomAuthorizeError` that you would need to handle in a catch block.
> 
> Let me know what you think about this?

Thank you for this.

**Comment by Ahmedelwaafy** [comment]
> Wanted to let you know that I'm tracking this. I want to come up with a good solution here. Leave your comments! No need for "+1" or "need this" etc. comments, let's keep it effective and constructive. Come with suggestions! (You can just 👍 👎 for a simple opinion)
> 
> My initial reasoning was to nudge developers to not send back errors like "invalid password" or "invalid username", which generally is not recommended, as you could let someone enumerate your users, probably other problems with it too. So I just want to make doing this very explicit.
> 
> ## My proposal
> Any generic error would still use the "catch-all" error type, but for custom ones that extend `AuthorizeError`, we would just re-throw.
> 
> We already do this actually, if you extend `AuthError`, but this was never documented:
> 
> https://github.com/nextauthjs/next-auth/blob/7963880593fa358905cd4e31285715783b66470f/packages/core/src/lib/actions/callback/index.ts#L373-L376
> 
> Not all `AuthError` should end up on the client either though, to obfuscate server details as much as possible. I've been meaning to come back to this here:
> 
> https://github.com/nextauthjs/next-auth/blob/7963880593fa358905cd4e31285715783b66470f/packages/core/src/index.ts#L172-L173
> 
> **So** we need a specific error type, `AuthorizeError`, that you would use like so:
> 
> ```ts
> import { AuthorizeError } from "next-auth/errors"
> 
> class CustomAuthorizeError extends AuthorizeError {
>   code = "custom"
> }
> 
> // ...
> authorize() {
>   // ...
>   throw new CustomAuthorizeError("foo")
> }
> ```
> 
> Then, you would have the following options when you invoke `signIn`:
> 
> Client Components/Pages Router:
> 
> * get redirected to this error page `/error?error=AuthorizeError&code=custom`
> * if `redirect: false` was set on `signIn`, it returns the error and code properties.
> 
> Server Actions:
> 
> * `await signIn()` would throw `CustomAuthorizeError` that you would need to handle in a catch block.
> 
> Let me know what you think about this?

is this a solution ?
i am trying to do this importing but it results this error
Cannot find module 'next-auth/errors' or its corresponding type declarations.

**Comment by A7med3bdulBaset** [comment]
> is this a solution ? i am trying to do this importing but it results this error Cannot find module 'next-auth/errors' or its corresponding type declarations.

Not released yet.

Follow https://github.com/nextauthjs/next-auth/pull/9871

**Comment by Ahmedelwaafy** [comment]
> > is this a solution ? i am trying to do this importing but it results this error Cannot find module 'next-auth/errors' or its corresponding type declarations.
> 
> Not released yet.
> 
> Follow #9871

ok, thank you

**Comment by Andrii-Antoniuk** [comment]
@balazsorban44  @A7med3bdulBaset 
For error messages currently (v0.28.0) we have the following modification of the message: 
```typescript
const url = `https://errors.authjs.dev#${this.type.toLowerCase()}`;
this.message += `${this.message ? " ." : ""}Read more at ${url}`;
```

Will it be possible to remove this string from custom errors?

E.g. here I'd like to be able to get a message as it was passed in the constructor
```typescript
/**
 * @description use this error only with messages that should be accessible on the client
 */
export class ClientMessageError extends AuthError {
  code = CLIENT_AWARE_ERROR_CODE;
}

```

**Comment by Jared-Dahlke** [comment]
yes we really need to be able to return custom error messages. I used authjs to allow users of my app to deploy the app using custom OIDC credentials so that they can use any OIDC compliant provider they want. I need to show the actual error messages they are getting so that they can more easily debug/figure out what scopes/credentias etc they may have wrong or be missing while setting up /deploying the app. Currently the only way to tell is in the dev tools select "preserve log", then view the network calls and look at the error there. I need to be able to pass that error to the UI for them to see.

**Comment by Jared-Dahlke** [comment]
ah thank you @ndom91. But how can I use this in my custom OIDC provider? I am not using `CredentialsProvider`

```
import NextAuth from "next-auth";
import type { NextAuthConfig } from "next-auth";
import { jwtDecode } from "jwt-decode";
import { UserSetupStatus, validateGeniusAndGetUserData } from "@/utils";
import type { OIDCConfig } from "@auth/core/providers";


export const config = {
  providers: [
    {
      id: "generic",
      name: "Generic Provider",
      type: "oidc",
      clientId: process.env.CLIENT_ID,
      clientSecret: process.env.CLIENT_SECRET,
      issuer: process.env.ISSUER_BASE_URL,
      checks: ["pkce", "state"], // had to add this for okta
      authorization: {
        params: {
          audience: process.env.AUDIENCE, // had to add this for Auth0
          prompt: "login",
          scope: process.env.AUTH_SCOPE || "openid profile email",
        },
      },
    } satisfies OIDCConfig<any>,
  ],
  trustHost: true,
  secret: process.env.AUTH_SECRET,
  pages: {
    signIn: "/",
  },
  callbacks: {
    async jwt({ token, account, user }) {
     REDACTED
    },
    async session({ session, token, user }) {
     REDACTED
      }
      return newSession;
    },
  },
} satisfies NextAuthConfig;

export const { handlers, auth, signIn, signOut } = NextAuth(config);

```

**Comment by BertramYe** [comment]
> Wanted to let you know that I'm tracking this. I want to come up with a good solution here. Leave your comments! No need for "+1" or "need this" etc. comments, let's keep it effective and constructive. Come with suggestions! (You can just 👍 👎 for a simple opinion)
> 
> My initial reasoning was to nudge developers to not send back errors like "invalid password" or "invalid username", which generally is not recommended, as you could let someone enumerate your users, probably other problems with it too. So I just want to make doing this very explicit.
> 
> ## My proposal
> Any generic error would still use the "catch-all" error type, but for custom ones that extend `AuthorizeError`, we would just re-throw.
> 
> We already do this actually, if you extend `AuthError`, but this was never documented:
> 
> https://github.com/nextauthjs/next-auth/blob/7963880593fa358905cd4e31285715783b66470f/packages/core/src/lib/actions/callback/index.ts#L373-L376
> 
> Not all `AuthError` should end up on the client either though, to obfuscate server details as much as possible. I've been meaning to come back to this here:
> 
> https://github.com/nextauthjs/next-auth/blob/7963880593fa358905cd4e31285715783b66470f/packages/core/src/index.ts#L172-L173
> 
> **So** we need a specific error type, `AuthorizeError`, that you would use like so:
> 
> ```ts
> import { AuthorizeError } from "next-auth/errors"
> 
> class CustomAuthorizeError extends AuthorizeError {
>   code = "custom"
> }
> 
> // ...
> authorize() {
>   // ...
>   throw new CustomAuthorizeError("foo")
> }
> ```
> 
> Then, you would have the following options when you invoke `signIn`:
> 
> Client Components/Pages Router:
> 
> * get redirected to this error page `/error?error=AuthorizeError&code=custom`
> * if `redirect: false` was set on `signIn`, it returns the error and code properties.
> 
> Server Actions:
> 
> * `await signIn()` would throw `CustomAuthorizeError` that you would need to handle in a catch block.
> 
> Let me know what you think about this?
in my opinion, you didn't including all of the functions in the authrization of the fronts, for the functions you should directly return a objects like this here below:

```tsx
type Response = {
     success:boolean,
    data:{} | {
        user:{},
       token:string,
       expired:string
      ........ maybe more objects have been defined
     } ,
    message:string
}

// then when calling the Providers liek below, the Objects should be included, and then let the user to customise define the result,

export const { handlers, auth } = NextAuth({
    providers: [
        CredentialsProvider({
            ....
            async authorize(credentials,response:Response ) {
                  // let the user customeised there verify logical
                  try {
                          const user = await do some thing in the Db to verify
                         if(user){
                                  response.success = true,
                                 response.message = "credentails valid !!!"
                         }else{
                           //  do nothing, bu use can customise the error like below:
                              response.messge = "credentails valid !!!!!!"
                         }           
                 }catch(er){
                         // then also catch the error, and put in the message
                         response.messge = "something went wrong  !!!!!!"

                  }
                  // whatever then do just return the onject of the Response 
                 // then so that the user can get the costomised error in there `message` when the 
                  retrun response
            }
        })
    ]
})


................

```


and then in your souce code of the files(`node_modules\@auth\core\lib\actions\callback\index.js`) you can do like this below:
````tsx
try{
.........

const userFromAuthorize = await provider.authorize(credentials, 
            // prettier-ignore
            new Request(url, { headers, method, body: JSON.stringify(body) }));
         // the userFromAuthorize  should be a response objects
response = {....userFromAuthorize }      

      if (!response.success ){
              retrurn response
       }
    .........         

catch (err){
        // here also you can included the error inform
      response.message = "some of the error message"
     return response
}
````

and then in the client side or in the server side, user can costomise their forms not been forcely to use the form style of the next-auth predefined as you just return the `response` result of above, just like below,


```
// use can all the signIn, signOut, auth and so on like below:
// all of then just return the response 
const response = await signIn('credentails', formData)
const response = await signOut('credentails', formData)
const response = await auth ('credentails', formData)


// then user can do anything then want
if(response.success){  // login valid
     const user = response.user
}else {   // login invalid


}


```

in summary, you should return the right of  costomising the frontend `form` styles to the user, not incuding all of the functions even the   frontend `form` styles 

here are also I have defined a functions template, you can reference I think below,
````tsx
// you can define all of the functions like below: 
type Response<T> = {
    success: boolean,
    message?: string,
    data?: T
}

interface PromiseCallBackInterface<T> {
    (...args: any[]): Promise<Response<T>>
}

const PromiseActionHandler = async <T,>(CallBack:PromiseCallBackInterface<T>,...args: any[]) =>{
    let Response: Response<T> = {
        success: false
    }
    try {
        const response = await CallBack(Response,...args)
        Response = {
            ...response
        }
    } catch (error) {
        const errorMessage = (error as any).message
        Response.message = `error happend: ${errorMessage} !!!`
    }
    return Response
}


```

**Comment by Ahmedelwaafy** [comment]
now there is a solution which is here on the docs
https://authjs.dev/getting-started/providers/credentials#custom-error-messages
if the custom error message (code) doesn't appear in the params, try to console log the result in the client side
{error: 'CredentialsSignin', code: 'UserNotRegistered', status: 200, ok: true, url: null}

**Comment by hashaaan** [comment]
> now there is a solution which is here on the docs https://authjs.dev/getting-started/providers/credentials#custom-error-messages if the custom error message (code) doesn't appear in the params, try to console log the result in the client side {error: 'CredentialsSignin', code: 'UserNotRegistered', status: 200, ok: true, url: null}

This is working for now. Thanks!

**Comment by Ahmedelwaafy** [comment]
> > now there is a solution which is here on the docs https://authjs.dev/getting-started/providers/credentials#custom-error-messages if the custom error message (code) doesn't appear in the params, try to console log the result in the client side {error: 'CredentialsSignin', code: 'UserNotRegistered', status: 200, ok: true, url: null}
> 
> This is working for now. Thanks!

Good to hear! Thanks for letting me know.

**Comment by Abhishek21k** [comment]
> now there is a solution which is here on the docs https://authjs.dev/getting-started/providers/credentials#custom-error-messages if the custom error message (code) doesn't appear in the params, try to console log the result in the client side {error: 'CredentialsSignin', code: 'UserNotRegistered', status: 200, ok: true, url: null}

is there a way to get  this type of error  params in google auth
