### ISSUE TITLE
"Update" function is not on the documentation

### ISSUE THREAD

**Issue by bekogeko** [nextauthjs/next-auth#9115]
### What is the improvement or update you wish to see?

Documentation Page should be updated.

If the `useSession`hook is called, it returns an object with 3 properties inside. But in current Documentation it says it returns 2 instead of 3.
https://next-auth.js.org/getting-started/client#usesession

<img width="400" alt="Screenshot 2023-11-10 at 2 59 07 PM" src="https://github.com/nextauthjs/next-auth/assets/53656966/1353a81e-0ba5-40d8-8d38-50b63abf53ec">

### Is there any context that might help us understand?

The usage of update function is not clear to me. If there are resources Im ready to create a pull Request for it

**Comment by balazsorban44** [comment]
Please svroll down: https://next-auth.js.org/getting-started/client#updating-the-session
