### ISSUE TITLE
Mention the AUTH_ enviornment variable prefix in v5 breaking changes

### ISSUE THREAD

**Issue by Celsiusss** [nextauthjs/next-auth#9116]
### What is the improvement or update you wish to see?

The "Upgrade Guide (v5)" page should mention that auth.js now also uses environment variables prefixed with `AUTH_` (as mentioned [here](https://authjs.dev/reference/nextjs/module.index#environment-variable-inferrence).

### Is there any context that might help us understand?

I upgraded to v5 today, and followed the "Upgrade Guide (v5)" page.

After going through the whole page, I was surprised to see that my application was not using the correct redirect uri. 

Then on a completely unrelated page, I found this:

> Since NextAuth.js v5 can also automatically infer environment variables that are prefiexed with AUTH_.

And my `.env.local` has these lines:
```
AUTH_URL=https://localhost:7127
NEXTAUTH_URL=http://localhost:3000
```

This caused auth.js to use `AUTH_URL` instead of `NEXTAUTH_URL`, which is different behaviour from v4.

### Does the docs page already exist? Please link to it.

https://authjs.dev/guides/upgrade-to-v5

**Comment by balazsorban44** [comment]
Hi, this is an added feature, not a breaking one. The fact that you already had `AUTH_URL` set up is not something we could have been aware of. The reason behind it by the way is the unification on naming across Auth.js librararies, with the `AUTH_` prefix.

But exactly for the reason of not introducing a breaking change, NextAuth.js v5 will keep supporting `NEXTAUTH_URL` (and `NEXTAUTH_SRECRET`) in addition to `AUTH_URL` and `AUTH_SECRET`!
