### ISSUE TITLE
Regarding stale issues

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#912]
Hi there! 👋 

If you are reading this, you probably met our little non-human 🤖 friend who told you to come here.

In an effort to reduce the number of open issues, we use [stalebot](https://github.com/probot/stale) to close old/inactive issues.

**If you think your issue is still relevant and/or unresolved, we encourage you to comment on the issue, so it will be marked as not stale again.**

We hope that this will help us maintain the project better.

If you have any thoughts on this decision, feel free to comment on this issue.

**Comment by jaredpalmer** [comment]
Bump

**Comment by 4mohdisa** [comment]
I get error: Try signing in with a different account.
when i try to login with google auth i am using next-auth
