### ISSUE TITLE
Can't use auth() to get values from jwt() callback in v5

### ISSUE THREAD

**Issue by Celsiusss** [nextauthjs/next-auth#9122]
### Environment

    next: 14.0.2 => 14.0.2 
    next-auth: ^5.0.0-beta.3 => 5.0.0-beta.3 
    react: ^18 => 18.2.0 

### Reproduction URL

https://github.com/Celsiusss/nextauth-demo

### Describe the issue

In the [documentation](https://authjs.dev/guides/upgrade-to-v5?authentication-method=server-component#authenticating-server-side), it says that:

> When using auth(), the [session() callback](https://authjs.dev/reference/core/types#session) is ignored. **auth() will expose anything returned from the [jwt() callback](https://authjs.dev/guides/reference/core/types#jwt)** or if using a ["database" strategy](https://authjs.dev/reference/core#session), from the [User](https://authjs.dev/reference/core/adapters#adapteruser). This is because the session() callback was designed to protect you from exposing sensitive information to the client, but when using auth() you are always on the server.

I tried to test this, but could not get values from the `jwt()` callback to be returned by `auth()`. It seems like the opposite of what this text says is true.  Values from the `session()` callback is being returned, instead of `jwt()`. Not quite sure what the intended behavior really is, but I would love to access encrypted token values using `auth()`.

### How to reproduce

I have tried to create a minimal example in the Github link.

Here I am using `auth()` in a server component and in a route handler, to demonstrate it in two different ways.
[`page.tsx`](https://github.com/Celsiusss/nextauth-demo/blob/master/app/page.tsx) shows it being used in a server component.
[`api/route.ts`](https://github.com/Celsiusss/nextauth-demo/blob/master/app/api/route.ts) shows it being used in a route handler.
[`client.tsx`](https://github.com/Celsiusss/nextauth-demo/blob/master/app/client.tsx) client component for signing in and using the route handler
[`auth.ts` ](https://github.com/Celsiusss/nextauth-demo/blob/master/app/auth.ts)registers an oidc provider and defines the `jwt()` callback.

### Expected behavior

I expected to be able to use `auth()` to retrieve values from the `jwt()` callback in server side components.

**Comment by czymstef** [comment]
I've encountered the same issue, and it would be fantastic if it worked as described in the documentation. I aim to avoid exposing the access token to the client.

As far as I understand, there isn't a way to obtain the up-to-date JWT in server calls. Although there's a getToken method, it only retrieves the JWT from the request, which might require updating (e.g., refresh token rotation). Getting the updated JWT directly from auth() would resolve this.

**Comment by mwawrusch** [comment]
Just ran into this as well after upgrading from a previous beta version. This is a pretty critical bug.

**Comment by judewang** [comment]
I also met the issue and figured out that the migration guide of this part was a little misleading. After tracing the source code, I found that the `auth` returned by `NextAuth` was just a `getSession` call with auth config. According to the documentation, both of the return values of `auth` and `getSession` are `Session` and `Session` is the return value of `session()` callback, so the return value of `auth` is the return value of `session()` callback, and the returned value of `jwt()` callback will be encode and set with server side cookie.

If we want `auth` to contain the returned value of `jwt()` callback, we can do this within `session()` callback.

```typescript
callbacks: {
  session({ session, token }) {
    // token is the returned value of `jwt()`
    return { ...session, ...token }
  }
}
```

**Comment by judewang** [comment]
@czymstef I supposed we can avoid exposing the token without using `useSession`, was I wrong? Since we are always on the server, are there any differences that the `Session` returned from `auth` is somehow by `session()` or by `jwt()` ?

**Comment by czymstef** [comment]
As far as I know, there is still the /api/auth/session endpoint (used by `useSession()`), which is just one GET-request away. I'm sure that there is a way to "disable" this endpoint (e.g. by defining a no op api route with the same name), but I'd not bet that there is no other way to somehow get the token in a compromised client.

**Comment by alessandrojcm** [comment]
So is there no way at the moment to get the raw token server-side? Seems pretty limiting

**Comment by judewang** [comment]
@czymstef I tried https://next-auth-example.vercel.app and also got my token printed within the console. However when doing the same thing on my site, I still got a 404 error. I noticed that I didn't export the `handlers` to any api routes, and that was what I found the demo page done, so maybe that caught the leak.

https://github.com/nextauthjs/next-auth/blob/main/apps/examples/nextjs/app/api/auth/%5B...nextauth%5D/route.ts

**Comment by czymstef** [comment]
@alessandrojcm Mind sharing how you could get the token server side in v4? I thought that this was not possible, too (with refresh token rotation and all).

@judewang If you don't export the handlers, then the callback endpoint does not exist, too, which makes logging in impossible, doesn't it? But we could only export the required handlers and just don't export the session one, or as @alessandrojcm suggested: Catch the call to /session and strip it. But who says that authjs won't add a method at a later stage which uses server actions?

This is just not as the library is intended to be used; `session()` is for client side data. I don't think you should have to jump through those hoops to just get the (possibly refreshed, including new Set-Cookie headers) value from `jwt()` on server side.

**Comment by alessandrojcm** [comment]
> @alessandrojcm Mind sharing how you could get the token server side in v4? I thought that this was not possible, too (with refresh token rotation and all).
> 
> @judewang If you don't export the handlers, then the callback endpoint does not exist, too, which makes logging in impossible, doesn't it? But we could only export the required handlers and just don't export the session one, or as @alessandrojcm suggested: Catch the call to /session and strip it. But who says that authjs won't add a method at a later stage which uses server actions?
> 
> This is just not as the library is intended to be used; `session()` is for client side data. I don't think you should have to jump through those hoops to just get the (possibly refreshed, including new Set-Cookie headers) value from `jwt()` on server side.

There is v4's [getToken](https://next-auth.js.org/tutorials/securing-pages-and-api-routes#using-gettoken), though now that I think of it I am not entirely sure if that does execute `session`; you might be right. 

And as per your second point, yes you are right one should not rely on patching `session` since it might either break in the future or we might be leaking the token somewhere else. IMO there should be a way of getting the raw token server-side as we might need it, for examplet to authenticate with 3rd party APIs if necessary.

**Comment by alessandrojcm** [comment]
Just to add, I am not quite able to get the `getToken` function from `@auth/core/jwt` to work. Even tho I am passing the same parmeters to the function that get passed by the library internally; even is this worked I don't think it'd be a good idea to mimic the internals. Maybe @balazsorban44 or someone from the dev team could advice in this case on how to get the raw JWT token?

**Comment by czymstef** [comment]
Just to emphasize this again: I personally do not only want the raw unencrypted token, but have a refreshed one. I'm looking for a method to get the content of the `jwt()` callback including a Set-Cookie header in case the `jwt()` content changed (e.g. refresh token rotation occured). Something like [`unstable_getServerSession()`](https://authjs.dev/guides/basics/securing-pages-and-api-routes#using-unstable_getserversession), but for the `jwt()` content instead of `session()`

**Comment by G4RDS** [comment]
I'm experiencing the same issue. Has there been any update or resolution?

I'm attempting to retrieve user IDs using `auth()` in Server Components, but returned `user` object includes only `name`, `email`, and `image`.

```ts
const session = await auth();
console.log(session.user) // { image: '...', email: '...', name: '...' }
```

I ran through the code and figured out that this segment does nothing:

https://github.com/nextauthjs/next-auth/blob/d7a116558700785880ecb03658b7de7c98bcf4bf/packages/next-auth/src/lib/index.ts#L76-L83

Because the supplied `args[0].session` has hard-coded `user` which only contains them.

https://github.com/nextauthjs/next-auth/blob/d7a116558700785880ecb03658b7de7c98bcf4bf/packages/core/src/lib/actions/session.ts#L52-L59

**Comment by eessadrati** [comment]
@G4RDS  I have the same issue, did you find any solution?

**Comment by statusunknown418** [comment]
@G4RDS does doing the module augmentation had any positive impact on solving the issue? or did you find a solution?

**Comment by alessandrojcm** [comment]
If you need more info from the OIDC provider you can always get it by modified the session object through the [`jwt`](https://authjs.dev/guides/basics/callbacks#jwt-callback) and [`session`](https://authjs.dev/guides/basics/callbacks#session-callback) callback. Just get whatever you need from the `account` parameter that gets passed to the `jwt` callback, then that object gets passed down to `session` and whatever you return from that you can get through `auth`.

**Comment by statusunknown418** [comment]
Is any of you guys by any chance using the drizzle-adapter and have the extended session object working?

**Comment by snettah** [comment]
For me that's not true I doesn't have the `jwt` properties in my `session` object 
<img width="907" alt="image" src="https://github.com/nextauthjs/next-auth/assets/10152935/383bee00-2f41-4e90-a0d8-9bfcea163e9f">

**Comment by felicksLindgren** [comment]
Currently facing the same issue, does not feel safe including 3rd party token in the session object.

**Comment by felicksLindgren** [comment]
> Just to add, I am not quite able to get the `getToken` function from `@auth/core/jwt` to work. Even tho I am passing the same parmeters to the function that get passed by the library internally; even is this worked I don't think it'd be a good idea to mimic the internals. Maybe @balazsorban44 or someone from the dev team could advice in this case on how to get the raw JWT token?

I managed to get the token to return the JWT with the following Route Handler: 
![image](https://github.com/nextauthjs/next-auth/assets/18117985/9751c0ef-1a6c-44d2-b98c-e4d9744e526c)

Intentionally didn't send in a salt param, typescript does not approve.

**Comment by felicksLindgren** [comment]
> Just to emphasize this again: I personally do not only want the raw unencrypted token, but have a refreshed one. In other words: I'm looking for a method to get the content of the `jwt()` callback including a Set-Cookie header in case the `jwt()` content changed (e.g. refresh token rotation occured). Something like [`unstable_getServerSession()`](https://authjs.dev/guides/basics/securing-pages-and-api-routes#using-unstable_getserversession), but for the `jwt()` content instead of `session()`
> 
> If I understand the documentation correctly, `getToken()` does indeed get the raw token, but it's the token from the cookie, which is potentially stale.

**Comment by devsmartproject** [comment]
whats is resolver ? 🚩

![image](https://github.com/nextauthjs/next-auth/assets/140632490/9b8408bc-71b9-4219-adbc-3ae2d7370b3c)

**Comment by obnol** [comment]
Hey, I'm facing the same issue. However, you can "access" the `token` object even though there's a type error

```ts
    async session({ session, token }) {
      session.user.id = token.id;
      return session;
    },
    async jwt({ token, user }) {
      if (user) {
        token.id = user.id;
      }
      return token;
    },
```

**Comment by ARJohnsonKwik** [comment]
Has anyone found a way to access the JWT token server side / api routes? Upgrading to v5 really seems like a down grade so far.

**Comment by felicksLindgren** [comment]
> Has anyone found a way to access the JWT token server side / api routes? Upgrading to v5 really seems like a down grade so far.

Not tried a API route, but managed to access the JWT via getToken(...) in a Next.js Route Handler (https://github.com/nextauthjs/next-auth/issues/9122#issuecomment-1898644981).

All it does is decode the cookie with your AUTH_SECRET. 

It's a work around for sure but as long as you have the Request Headers available you should be able to use this method if thinking.

**Comment by xiavn** [comment]
> Hey, I'm facing the same issue. However, you can "access" the `token` object even though there's a type error
> 
> ```ts
>     async session({ session, token }) {
>       session.user.id = token.id;
>       return session;
>     },
>     async jwt({ token, user }) {
>       if (user) {
>         token.id = user.id;
>       }
>       return token;
>     },
> ```

Just as a note, the type error with using token in the session callback is due to the typing where it will either have a token (if using jwt) or a user (if using a database); you can get around the type error somewhat by using the in operator narrowing:

```ts
    session(sessionArgs) {
         // token only exists when the strategy is jwt and not database, so sessionArgs here will be { session, token }
        // with a database strategy it would be { session, user } 
        if ("token" in sessionArgs) {
            return {
                 ...sessionArgs.session,
                user: {
                        ...sessionArgs.session.user,
                        roles: sessionArgs.token.roles, // something you are bringing in from your hwt function return via the token
                },
            };
        }
        return sessionArgs.session;
     }
```

**Comment by xiavn** [comment]
Yes good point! I was augmenting my session shape to avoid errors, didn't think of augmenting the session function args too.

**Comment by vineetkia** [comment]
How did you augment your session shape to avoid errors @xiavn , can you provide the code please?

**Comment by lukasb** [comment]
Thanks to everyone for their help. For some reason I had to add more type checks to make it work, in case anyone wants a fully working auth.config.ts example ...

```
import type { NextAuthConfig } from 'next-auth';
import { DefaultSession } from 'next-auth';
import { User as NextUser } from 'next-auth';

declare module "next-auth" {
  interface Session {
    user: {
      id: string
    } & DefaultSession["user"]
  }
}

export const authConfig = {
  pages: {
    signIn: '/login',
  },
  session: {
    strategy: "jwt",
  },
  callbacks: {
    authorized({ auth, request: { nextUrl } }: { auth: any, request: { nextUrl: any } }) {
      const isLoggedIn = !!auth?.user;
      const isOnEditorPage = nextUrl.pathname.startsWith('/page');
      if (isOnEditorPage) {
        if (isLoggedIn) return true;
        return false; // Redirect unauthenticated users to login page
      } else if (isLoggedIn) {
        return Response.redirect(new URL('/page', nextUrl));
      }
      return true;
    },
    jwt({ token, user }) {
      if (user) token.user = user;
      return token;
    },
    session(sessionArgs) {
     // token only exists when the strategy is jwt and not database, so sessionArgs here will be { session, token }
     // with a database strategy it would be { session, user } 
     if ("token" in sessionArgs) {
        let session = sessionArgs.session;
        if ("user" in sessionArgs.token) {
          const tokenUser = sessionArgs.token.user as NextUser;
          if (tokenUser.id) {
            session.user.id = tokenUser.id;
            return session;
          }
        }
     }
     return sessionArgs.session;
    },
  },
  providers: [], // Add providers with an empty array for now
} satisfies NextAuthConfig;
```

**Comment by holahoon** [comment]
Currently using `"next-auth": "5.0.0-beta.5"`.
Why is it that I can't have access to the `token` even though I set it to 'jwt' strategy??
<img width="1055" alt="image" src="https://github.com/nextauthjs/next-auth/assets/42850638/b4b2735a-f40e-4724-a535-40dec4619229">

**Comment by vineetkia** [comment]
I switched back to "5.0.0-beta.4" @lukasb , and it worked fine for me. in 5.0.0-beta.5 they had this breaking change. I guess until they go under stable release the 5.0.0-beta.4 works fine for session({ session, token })

**Comment by Celsiusss** [comment]
The documentation has changed. The bit that I originally quoted is now gone. (b5d5f20)

The commit references another issue (#9329) that was created after this describing the same problem.

Quoting a comment made on that issue:
>we reverted the ignoring part and will rather introduce the change via a flag in https://github.com/nextauthjs/next-auth/pull/9702 so the behavior is more consistent/less breaking for now. Will update the migration guide shortly

https://github.com/nextauthjs/next-auth/issues/9329#issuecomment-1909255054

Seems like `auth()` will only use the `session()` callback. A new way of suing `auth()` with `AuthData` is in the works, and may solve this.

Would have appreciated some better communication seeing as this issue has gathered a lot of traction, but at the same time many people commenting here is not even commenting about the original issue that I described, so I can see due to the discussions that emerged here it may not be clear what this issue really was about.

**Comment by olems** [comment]
Faced the same issue and the struggles with documentation about this use case. For me the only workable solution was to use getToken(), even though the docs say it is not recommended.

**Comment by gaganbiswas** [comment]
On nextjs 14, I got the `access_token` in the rsc, actions and routes by creating a cookie in the `jwt()` function using `next/cookies`. Doing this ensured that my `access_token` can't be accessed from the client or by going to `/api/auth/session`. I also handled some situations like deleting my cookies on expiry syncing its expiry with my session cookies from next-auth.

```ts
async jwt({ token, user }): Promise<JWT | null> {
      const cookie = cookies();
      if (user) {
        const accessDecode = jwtDecode(user.accessToken);

        const userProfile: User = {
          id: token.sub,
          name: user.name,
          email: user.email,
          image: user.image,
          accessToken: "",
          refreshToken: "",
          username: user.username,
        };

        cookie.set("access-token", user.accessToken, {
          expires: accessDecode.exp! * 1000,
          httpOnly: true,
          secure: process.env.NODE_ENV === "production",
          sameSite: "lax",
        });

        return {
          access_token: user.accessToken,
          expires_at: accessDecode.exp as number,
          refresh_token: user.refreshToken,
          user: userProfile,
        };
      } else if (Date.now() < token.expires_at * 1000) {
        return token;
      } else {
        if (!token.refresh_token) {
          cookie.delete("access-token");
          throw new Error("Missing refresh token");
        }

        try {
          const { data } = await axios.get(
            process.env.API_URL + "/user/generate-new-refresh-token",
            {
              headers: {
                Authorization: token.access_token as string,
                refreshToken: token.refresh_token as string,
              },
            }
          );

          if (data.error) throw new Error("Bad request");

          const accessDecode = jwtDecode(data.data.accessToken);

          cookie.set("access-token", data.data.accessToken, {
            expires: accessDecode.exp! * 1000,
            httpOnly: true,
            secure: process.env.NODE_ENV === "production",
            sameSite: "lax",
          });

          return {
            // Keep the previous token properties
            ...token,
            access_token: data.data.accessToken,
            expires_at: accessDecode.exp as number,
            refresh_token: data.data.refreshToken,
          };
        } catch (error) {
          cookie.delete("access-token");
          return null;
        }
      }
    },
    async session({ session, token }) {
      if (token.user) {
        // @ts-ignore
        session.user = token.user as User;
      }

      return session;
    },
  },
  session: {
    maxAge: 60 * 60,
  },
```

**Comment by alestuber** [comment]
I was able to get it creating the following function in my auth.ts file (AUTH_SECRET is your env variable for the secret to decode your token):

``
export const getAuthJwt = async () => {
  const { headers, cookies } = require('next/headers');
  const req = {
    headers: Object.fromEntries(await headers()),
    cookies: Object.fromEntries(
      (await cookies()).getAll().map((c) => [c.name, c.value])
    ),
  };

  const token = await getToken({ req, secret: process.env.AUTH_SECRET });

  return token;
};
``
