### ISSUE TITLE
Inconsistant use of jwt callback

### ISSUE THREAD

**Issue by davidnewcomb** [nextauthjs/next-auth#9126]
### What is the improvement or update you wish to see?

On page: https://next-auth.js.org/configuration/callbacks you state the signature for callback:jwt is:
```
async jwt({ token, user, account, profile, isNewUser }) {
```

On page: https://next-auth.js.org/getting-started/example#extensibility
```
async jwt({ token, account }) {
```

On page: https://authjs.dev/reference/core/providers/credentials
```
async jwt(token, user, account, profile, isNewUser) {
```

When you actually run it then it turns out to be:
```
async jwt({ token, user, account, profile, isNewUser, trigger }) {
```

### Is there any context that might help us understand?

The signature is not defined explicitly anywhere except in these examples and they don't agree with themselves. Can you make each signature complete even though you are not using all the items in the signature. It's really confusing. I've just started my implementation of Next-Auth and while the package itself seems to do everything I need, I keep getting tripped up by stuff like this.

**Comment by balazsorban44** [comment]
https://next-auth.js.org/configuration/callbacks is correct

https://next-auth.js.org/getting-started/example#extensibility is an example, not API reference so it doesn't need to show unused properties. (Your IDE will!)

https://authjs.dev/reference/core/providers/credentials  was a typo, fixed now!
