### ISSUE TITLE
session.accessToken is undefined

### ISSUE THREAD

**Issue by iamchathu** [nextauthjs/next-auth#913]
**Your question**
I'm using Auth0 provider and I have a 3rd Party Backend which is also secured with Auth0.
I have setup the provider as following but when I try to access session.accessToken, it returned as undefined.

**What are you trying to do**
To retrieve accessToken to access the backend which is not with Next.js.

// api/auth/[...nextauth].ts

```ts
import NextAuth from 'next-auth';
import Providers from 'next-auth/providers';

const options = {
  providers: [
    Providers.Auth0({
      clientId: process.env.AUTH0_CLIENT_ID,
      clientSecret: process.env.AUTH0_CLIENT_SECRET,
      domain: process.env.AUTH0_DOMAIN,
    }),
  ],
  secret: process.env.NEXTAUTH_SECRET,
  jwt: {
    encryption: true,
    secret: process.env.NEXTAUTH_JWT_SECRET,
  },
  pages: {
    signIn: '/auth',
  },
};

export default (req, res) => NextAuth(req, res, options);


```

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Could you please provide a bit more information about how you set up Auth0 with `next-auth`?

**Comment by iamchathu** [comment]
@balazsorban44 Updated the question.

**Comment by balazsorban44** [comment]
What do you mean by:
> To retrieve accessToken to access the backend which is not with Next.js.

Right now, `next-auth` is only intended to be used with Next.js.

You can use the `accessToken` both client and server-side though if you use [API Routes](https://nextjs.org/docs/api-routes/introduction).

Please refer to the documentation:
To add an access token to the session:
- https://next-auth.js.org/configuration/callbacks#jwt-callback
- https://next-auth.js.org/configuration/callbacks#session-callback

To access it from client and server-side:
- https://next-auth.js.org/getting-started/client#getsession
- https://next-auth.js.org/getting-started/client#usesession

**Comment by iamchathu** [comment]
I tried to use `useSession` hook but seems I'm not getting accessToken.

I tried to access accessToken as in 


```ts
const IndexPage: NextPage = () => {
  const classes = useStyles();
  const [session, loading] = useSession();

  const login = () => signIn('auth0');

  return (
    <>
      {!session && (
          <b>
            Sign in
          </b>
          <Button onClick={login} color="primary" variant="contained">
            Sign In
          </Button>
        </AuthLayout>
      )}
      {session && (
        <div>
              <p>Session : {session.expires}</p>
              <p>Token : {session.accessToken}</p>
          </div>
      )}
    </>
  );
};

export default IndexPage;

```

but session.accessToken is `undefined`.

**Comment by balazsorban44** [comment]
You have to forward it in the `jwt` and `session` callbacks, please look at the links.
