### ISSUE TITLE
Session.user.id and session.accessToken when using next-auth to gain access to the Spotify api.

### ISSUE THREAD

**Issue by griffin610** [nextauthjs/next-auth#916]
**Your question**
How am I supposed to access the Spotify users id and the access token granted by Spotify using next-auth.

**What are you trying to do**
I am trying to implement a function to export my playlist I have saved to Spotify. I use next-auth in order to handle the user login with Spotify. However I am having trouble when trying to access the user id and the access token. However, I get the username and the email correctly returned when testing. 

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ X] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [X ] Found the example project helpful
* [ ] Did not find the example project helpful

I made the changes suggested in previous issues but to no avail. 
`callbacks:{

    jwt: async ( token, user) => {
      if(user){
        token.uid = user.id;
      }
      return Promise.resolve(token);
    },
    session: async (session, user) => {
      session.user.id = user.id;
      return Promise.resolve(session);
    }
  }`
But session.user.id and session.token are both undefined.

**Comment by balazsorban44** [comment]
Hi @griffin610 anf thanks for raising this issue.

Could you please provide a bit more information about your usecase? Maybe a reproduction repository? 

Did you use the [Spotify](https://next-auth.js.org/providers/spotify) provider?

**Comment by griffin610** [comment]
Hi @balazsorban44 Thank you for the quick reply.
I am developing a project where I am trying to be able to export a playlist I have created to Spotify. In order to do so I need the Spotify user ID and the access token granted when they sign in order to do this through the Spotify api. 

I used your provided Spotify provider and changed it to match the scopes I needed as follows. 
`providers: [

    Providers.Spotify({
      scope: 'user-read-email playlist-modify-public playlist-modify-private',
      clientId: process.env.SPOTIFY_CLIENT_ID,
      clientSecret: process.env.SPOTIFY_CLIENT_SECRET
    }),
  ],`

Which does provide the proper scopes granted when the user logs in. When running `session.user.name and session.user.email` The correct values are provided. But  `session.user.id and session.token` are undefined.

**Comment by balazsorban44** [comment]
Right.

https://github.com/nextauthjs/next-auth/blob/main/src/providers/spotify.js

Here you can see the configuration for the `Spotify` provider. You can add a `profile` method to your configuration, and see if you can find the id.

You can also check out the `jwt` callback, and see what information is available to you there on sign in.

Please check out the [relevant docs](https://next-auth.js.org/configuration/callbacks#jwt-callback)

**Comment by griffin610** [comment]
Well that's what is confusing is that in your documentation is does have an id property. 

`
export default (options) => {

  return {
    id: 'spotify',
    name: 'Spotify',
    type: 'oauth',
    version: '2.0',
    scope: 'user-read-email',
    params: { grant_type: 'authorization_code' },
    accessTokenUrl: 'https://accounts.spotify.com/api/token',
    authorizationUrl:
      'https://accounts.spotify.com/authorize?response_type=code',
    profileUrl: 'https://api.spotify.com/v1/me',
    profile: (profile) => {
      return {
        id: profile.id,
        name: profile.display_name,
        email: profile.email,
        image: profile.images.length > 0 ? profile.images[0].url : undefined
      }
    },
    ...options
  }
}
`

**Comment by balazsorban44** [comment]
So if you `console.log` profile, there is no profile id? 

You can also try adding the `debug: true` configuration option to have a bit more information about what is returned from the Spotify API. This will log some debug information in your terminal.

**Comment by griffin610** [comment]
So here's what I found out.  

Here's my [...nexthauth] file
`
const options = {
  providers: [

    Providers.Spotify({
      scope: 'user-read-email playlist-modify-public playlist-modify-private',
      clientId: process.env.SPOTIFY_CLIENT_ID,
      clientSecret: process.env.SPOTIFY_CLIENT_SECRET,
      debug: true,
      profile: (profile) => {
        console.log('In profile');
        console.log(profile.id);
         return {
          id: profile.id,
          name: profile.display_name,
          email: profile.email,
          image: profile.images.length > 0 ? profile.images[0].url : undefined
        }
      }
    }),
  ],
  session: {
    jwt: true,
  },
  callbacks:{
    jwt: async ( token, profile) => {
      console.log('Injwt');
      console.log(token);
      if(profile){
        token.uid = profile.id;
      }
      return Promise.resolve(token);
    },
    session: async (session, profile) => {
      console.log('In session');
      console.log(session);
      session.user.id = profile.id;
      return Promise.resolve(session);
    }
  }
};
export default (req, res) => NextAuth(req, res, options);
`

What is logged in jwt is
 `
  name: 'Griffin',
  email: 'gpizzano@middlebury.edu',
  picture: 'https://i.scdn.co/image/ab6775700000ee85373b845cd06a0b1aeee1a636',
  iat: 1607203347,
  exp: 1609795347
`
And in session 
`{
  user: {
    name: 'Griffin',
    email: 'gpizzano@middlebury.edu',
    image: 'https://i.scdn.co/image/ab6775700000ee85373b845cd06a0b1aeee1a636'
  },
  expires: '2021-01-04T21:22:28.415Z'
}
`

If I log the profile parameter from the jwt callback it is undefined.

**Comment by balazsorban44** [comment]
According to the Spotify docs: https://developer.spotify.com/documentation/general/guides/authorization-guide, you should be able to get an id from https://api.spotify.com/v1/me which IS configured. Getting information from the endpoint requires sending an access_token, and since you get the username and e-mail, it seems that you are actually getting the access_token as well.

At this point, I would ask you to provide a minimal reproduction, - rather than code snippets - so I can help you better.

**Comment by griffin610** [comment]
Sorry it took a while to get back to you. I appreciate the help you are giving us. My friend shared the project with you on git the repository is onelistprototype. I am still getting the same object returned to me I had returned yesterday.

**Comment by balazsorban44** [comment]
Thanks. I'll have a look at this tomorrow.

**Comment by balazsorban44** [comment]
@griffin610 I sent you a suggestion to fix your problem. now both `accessToken` and `id` are available in your session.

You defined the `session` callback outside of the `callbacks` config option property

**Comment by MatD1** [comment]
> 
> 
> Sorry it took a while to get back to you. I appreciate the help you are giving us. My friend shared the project with you on git the repository is onelistprototype. I am still getting the same object returned to me I had returned yesterday.

I know this has been closed but this exact thing I want to do but I caanot figure it out anychance you could share the code you had to achieve this? It would be a load of help!
