### ISSUE TITLE
Leave custom base path documentation in custom base path section

### ISSUE THREAD

**Issue by CPChiste** [nextauthjs/next-auth#9160]
### What is the improvement or update you wish to see?

On this page:
https://next-auth.js.org/getting-started/client#options

The first instance of basePath should show a default (and correct) implementation, leaving the custom base path implementation to be described further down. I know "cool-app" COULD very well be the full path to NextAuth, but this example doesn't give enough context to ensure the user would understand and implement correctly.

### Is there any context that might help us understand?

The first instance of basePath highlights an errant usage of custom base paths. This could lead the reader to assume thats all they need to know about custom base paths and that that is a correct example with 0 context, so they would stop reading and not get to the section all about base paths and how they need to define the full path to NextAuth if custom. Update this section of documentation to show default behaviour, leaving the custom base path section to correctly describe how to use a custom base path.

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/getting-started/client#options

**Comment by ItsJohnTheDeveloper** [comment]
bump

**Comment by chetan1507** [comment]
In the page mentioned above to docs, NEXTAUTH_URL maps to https://example.com/custom-route/api/auth.
Can we not have a url mapping to https://example.com/api/custom-route/auth?
I tried this and this seems to be failing in prod environment. Not sure how its working in my local dev.

**Comment by CPChiste** [comment]
@chetan1507 if it's failing in prod but working locally that seems to point to an environment variable being out of sync between the two environments? Have you ensured the prod NEXTAUTH_URL is updated to match what you have locally?

**Comment by chetan1507** [comment]
@CPChiste  Yes. I had used the auth url to be of the format `https://example.com/api/custom-route/auth`, and also added basePath as `api/custom-route/auth`.
The google provider in these cases would simply go to `/api/auth` which is the default route.

**Comment by ndom91** [comment]
Hey thanks for pointing this out, we've recently shipped a new docs site and this is hopefully clearer there. Each provider has a callbackUrl section with the default basePaths defined for each frameowrk (where they're potentially different). 

If you find any issues int he new docs, feel free to open a new issue :pray:
