### ISSUE TITLE
Broken link on the Email Provider page

### ISSUE THREAD

**Issue by garthtee** [nextauthjs/next-auth#9184]
### What is the improvement or update you wish to see?

Fix the link to the database adaptor on the [Email providers page](https://next-auth.js.org/providers/email).

This is the text:

> Do not forget to setup one of the database [adapters](https://authjs.dev/reference/adapters) for storing the Email verification token.

If someone could provide me with the link I can make the update!

### Is there any context that might help us understand?

Link no worky.

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/providers/email

**Comment by balazsorban44** [comment]
Fixed: https://github.com/nextauthjs/next-auth/commit/a8f9c0679fdd728fc15c9a8d1c6e1617d437306c

FYI, for future reference, there is an "Edit this page" button on every page. feel free to PR! :green_heart:
