### ISSUE TITLE
Directory import is not supported resolving ES modules imported from

### ISSUE THREAD

**Issue by Nefcanto** [nextauthjs/next-auth#9202]
### Environment

    System:
      OS: Linux 6.2 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
      CPU: (4) x64 Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz
      Memory: 8.05 GB / 15.49 GB
      Container: Yes
      Shell: 5.2.15 - /bin/bash
    Binaries:
      Node: 20.9.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.4 - /usr/local/bin/npm
    Browsers:
      Chromium: 119.0.6045.159
    npmPackages:
      @auth/core: ^0.18.1 => 0.18.2 

### Reproduction URL

https://github.com/Nefcanto/AuthCoreBug

### Describe the issue

I upgraded to Vite 5 and updated the dependencies. I'm using `@auth/core` and `@builder.io/qwik-auth`.

After update when I run `npm run build` I get this error:

> Internal server error: Directory import '/home/projects/qwik-starter-y42h1d/node_modules/@auth/core/lib/actions' is not supported resolving ES modules imported from /home/projects/qwik-starter-y42h1d/node_modules/@auth/core/lib/index.js

Since it might be related to configuration, I'm going to send this issue to Qwik and Vite and Auth/Core repos.

### How to reproduce

Create a Qwik project
Add @auth/core and @builder.io/qwik-auth
Import them somewhere
Update to the latest versions
Build
You should see the error

### Expected behavior

@auth/core should work out of the box in terms of stuff related to NPM and Node

**Comment by brehen** [comment]
I'm experiencing the same when trying to set this up with SvelteKit as well. 

Look like it's related to the @auth/core package, and not specifically @auth/sveltekit or @auth/<insert-framework-here>

**Comment by brehen** [comment]
For reference, I've recreated the same bug in a clean SvelteKit project here:

https://github.com/brehen/sveltekit-auth-import-bug

**Comment by fetimo** [comment]
Can confirm this is also the case when using Vite 4.5.0.

**Comment by JinIgarashi** [comment]
I also faced this error with sveltekit when `@auth/core` was updated to 0.18.1.

**Comment by balazsorban44** [comment]
Fixed via #9205! Please upgrade.
