### ISSUE TITLE
Referencing NEXTAUTH_URL in app router causes build error for runtime environment variables

### ISSUE THREAD

**Issue by c-kirkeby** [nextauthjs/next-auth#9212]
### Environment

(From CodeSandbox)
System:
OS: Linux 6.1 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
CPU: (2) x64 AMD EPYC
Memory: 400.73 MB / 2.01 GB
Container: Yes
Shell: 5.8 - /bin/zsh
Binaries:
Node: 20.9.0 - /usr/local/bin/node
Yarn: 1.22.19 - /usr/local/bin/yarn
npm: 9.8.1 - /usr/local/bin/npm
pnpm: 8.10.2 - /usr/local/share/npm-global/bin/pnpm
npmPackages:
next: latest => 14.0.3
next-auth: beta => 5.0.0-beta.3
react: ^18.2.0 => 18.2.0

### Reproduction URL

https://github.com/c-kirkeby/next-auth-example

### Describe the issue

Referencing `NEXTAUTH_URL` in the app directory causes builds to fail if NEXTAUTH_URL is not available at compile time. This is causing issues in CI when we build a docker image that uses environment variables at runtime. I've modified the next-auth-example to use the `cookies` option in the auth config. In attempting to figure out how to make this work I've put `unsable_noStore()` and `export dynamic = 'force-dynamic'` in just about every page and it still doesn't work.

The GitHub bot was unhappy when I linked to Codesandbox last time so I've added the attached repo instead but the link to Codesandbox is [here](https://codesandbox.io/p/github/c-kirkeby/next-auth-example/main?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp925hsr00072e67aqpnnzvf%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp925hsr00032e679g44iybx%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp925hsr00052e67u5q4gf03%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp925hsr00062e67cbn4nz5g%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp925hsr00032e679g44iybx%2522%253A%257B%2522id%2522%253A%2522clp925hsr00032e679g44iybx%2522%252C%2522activeTabId%2522%253A%2522clp93dboe03092e67dk9ioa8k%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.next%252Fserver%252Fapp%252Fapi%252Fprotected%252Froute.js%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522endLineNumber%2522%253A1%252C%2522startColumn%2522%253A1912%252C%2522endColumn%2522%253A1912%257D%255D%252C%2522id%2522%253A%2522clp93dboe03092e67dk9ioa8k%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clp925hsr00062e67cbn4nz5g%2522%253A%257B%2522id%2522%253A%2522clp925hsr00062e67cbn4nz5g%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clp92bwsh00qa2e67lpplq7qn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp92bwsh00qa2e67lpplq7qn%2522%257D%252C%2522clp925hsr00052e67u5q4gf03%2522%253A%257B%2522id%2522%253A%2522clp925hsr00052e67u5q4gf03%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp925hsr00042e67gc6d16bu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clp92csz0002aedcifhhh0db6%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clp925iem006v2e67w30upg32%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clp927lqv00ae2e671rxwu1lp%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%252C%2522id%2522%253A%2522clp92bsrf00kj2e67at0p82f6%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp925hsr00042e67gc6d16bu%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

### How to reproduce

Open the CodeSandbox and `npm run build`. Do not set any environment variables for the build as they should be defined at runtime.

### Expected behavior

As far as I understand, next-auth shouldn't be trying to access the environment variables at build time if we opt into dynamic rendering.

**Comment by balazsorban44** [comment]
This makes sense and is expected. Some routes might be rendered at build time, so this variable needs to be present then as well. FWIW, this variable is rarely needed anymore, what's the use case?

**Comment by c-kirkeby** [comment]
For our particular use case we're sharing a secure cookie to have a persisted session token across our subdomains such as [this approach here](https://github.com/nextauthjs/next-auth/issues/405#issuecomment-737593528). This works so long as we use the page router, but if we try to migrate to the app router we get an error at build time.

**Comment by balazsorban44** [comment]
This can be addressed, as lazy initialization (prev. advanced initialization) is now supported in v5 too. seehttps://github.com/nextauthjs/next-auth/pull/9638
