### ISSUE TITLE
import error in providers/email.ts

### ISSUE THREAD

**Issue by stimw** [nextauthjs/next-auth#9213]
### Environment

  System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.27 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 7.27.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 119.0.6045.159
    Edge: 119.0.2151.72
    Safari: 17.1
  npmPackages:
    next: ^13.2.4 => 13.5.6 
    next-auth: ^4.24.5 => 4.24.5 
    react: 18.2.0 => 18.2.0 

### Reproduction URL

https://github.com/nextauthjs/next-auth/blob/next-auth%404.24.5/packages/next-auth/src/providers/email.ts

### Describe the issue

<img width="919" alt="image" src="https://github.com/nextauthjs/next-auth/assets/30977647/3f69a5b4-8a29-438a-9726-4c361f440b0c">

There's an import error here in the version `next-auth: ^4.24.5` : https://github.com/nextauthjs/next-auth/blob/next-auth%404.24.5/packages/next-auth/src/providers/email.ts

An example corrent path is `"nodemailer/lib/smtp-transport/index.js`

This error doesn't exist in the beta version.

### How to reproduce

- install the latest (not beta) next-auth: ^4.24.5 and the latest `nodemailer`
- go to `node_modules/next-auth/src/providers/email.ts`

### Expected behavior

no import error

**Comment by balazsorban44** [comment]
Hi, this is lib code, and should not affect your project. Are you seeing a bug because of this? If so, please report it with your application (minimized) code, please. Thank you!
