### ISSUE TITLE
Request for Documentation Update - authjs.dev (formerly next-auth.js.org)

### ISSUE THREAD

**Issue by mdasiff** [nextauthjs/next-auth#9218]
### What is the improvement or update you wish to see?

Dear Team,

I hope this letter finds you well. I am writing to bring to your attention a concern regarding the documentation for authjs.dev (formerly next-auth.js.org), specifically related to the structure based on the app directory in Next.js.

Upon reviewing the documentation available on authjs.dev/next-auth.js.org, it has come to my attention that the information provided is outdated and primarily focuses on pages-based code structure. As you may be aware, Next.js has evolved, and the latest versions (v13,v14) promote an app directory-based code.

Considering the advancements in Next.js and the increasing adoption of the app directory structure, I believe it would greatly benefit the Next-auth.js community to have updated documentation that aligns with the current best practices.

To enhance the user experience and provide accurate guidance, I kindly request that you consider updating the documentation to reflect the app directory-based code structure in Next.js. This update will ensure that developers receive the most relevant and up-to-date information when integrating Next-auth.js into their projects.

I understand the effort involved in maintaining documentation, and I appreciate the work your team has put into supporting the authjs.dev community. Your commitment to providing accurate and timely information is crucial for the success and ease of use of the authjs.dev library.

If there are any additional resources or information required from my end to assist in this process, please do not hesitate to reach out. I am more than willing to collaborate and contribute to the improvement of the authjs.dev documentation.

Thank you for your attention to this matter. I look forward to seeing the documentation updated to reflect the latest practices in Next.js.

_Sincerely,
Muhammad Asif
Team Lead | MERN Stack | PHP Laravel
Ph. +91-8882248742
Email: mdasiff007@gmail.com
Website: inertiapixel.com_

### Is there any context that might help us understand?

<img width="216" alt="image" src="https://github.com/nextauthjs/next-auth/assets/35130721/5432be74-31f9-4a73-9f07-b49ba06165ab">

### Does the docs page already exist? Please link to it.

[inertiapixe.com](https://next-auth.js.org/getting-started/introduction)

**Comment by balazsorban44** [comment]
Thanks. This is a continuous effort and we are constantly working on improving the documentation. If there is a a specific area you would like to get improved, feel free to open a PR with a suggestion and we can review. I'll close this issues as this is - in its current form - unactionable.
