### ISSUE TITLE
Option to disable redirect on signin

### ISSUE THREAD

**Issue by fandy** [nextauthjs/next-auth#922]
**Summary of proposed feature**
Would be great if there were an option in the email provider to disable the redirect to `/api/auth/verify-request?provider=email&type=email` on signin, while also knowing whether the verification succeeded or failed on the client.

**Purpose of proposed feature**
Better UX since you are not taken to a different page, and can instead show a state change.

**Potential problems**
None

*Please indicate if you are willing and able to help implement the proposed feature.*
Possibly

**Comment by balazsorban44** [comment]
Could you please fill out the feature request issue template?

**Comment by fandy** [comment]
@balazsorban44 done

**Comment by styxlab** [comment]
Having exactly the same issue. I can change the custom route in the configuration (´pages: { verifyRequest: '/custom-url' }`) but would like to avoid an additional post request and display a success message without leaving the page.

**Comment by balazsorban44** [comment]
@fandy it took some time, but this is now possible 😅 Sorry for the delay, I haven't had the confidence with the source code just yet when you opened this issue.

**Comment by fandy** [comment]
@balazsorban44 beautiful, thank you for the update!
