### ISSUE TITLE
Incorrect links in the SvelteKit OAuth section

### ISSUE THREAD

**Issue by BahaaZidan** [nextauthjs/next-auth#9246]
### What is the improvement or update you wish to see?

The [docs](https://authjs.dev/getting-started/providers/oauth-tutorial?frameworks=sveltekit#create-server-hook) state that `SvelteKitAuth` is going to generate api routes behind `/api/auth/*`, this is wrong. The routes are behind `/auth/*`. 

If this is not a bug and it's a case of outdated documentation, I'm more than happy to contribute with a PR fixing this little typo.

### Is there any context that might help us understand?

https://authjs.dev/getting-started/providers/oauth-tutorial?frameworks=sveltekit#create-server-hook

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/providers/oauth-tutorial?frameworks=sveltekit#create-server-hook

**Comment by ndom91** [comment]
@BahaaZidan yes good catch, I'm going to close this issue but we'd really appreciate a PR!

**Comment by ndom91** [comment]
@BahaaZidan yes good catch, I'm going to close this issue but we'd really appreciate a PR! 🙏
