### ISSUE TITLE
NextAuthJS login work in the test environment but cannot be built to production

### ISSUE THREAD

**Issue by phamvant** [nextauthjs/next-auth#9250]
### Environment

Node v20.7.0
Next 14

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

I am trying to deploy a NextJS application to vercel. This is a test sign in model using AuthJS. When I run the program using npm run devit works fine and I am able to log in to my discord account which is connected to an application on the developer portal. However, when I deploy it to Vercel and try and build the application for production I receive this error.

`Type error: Route "app/api/auth/[...nextauth]/route.ts" does not match the required types of a Next.js Route.
  "authOptions" is not a valid Route export field.`

### How to reproduce

For context I am using NextJS 13 and it's app folder method of rendering pages along with the NextAuth.js.

```
import NextAuth from "next-auth";
import type { NextAuthOptions } from "next-auth";
import DiscordProvider from "next-auth/providers/discord";

export const authOptions: NextAuthOptions = {
  providers: [
    DiscordProvider({
      clientId: process.env.DISCORD_CLIENT_ID!,
      clientSecret: process.env.DISCORD_CLIENT_SECRET!,
    })
  ]
};

const handler = NextAuth(authOptions);
export { handler as GET, handler as POST }
```

### Expected behavior

No error when build

**Comment by balazsorban44** [comment]
invalid repro. it's not the same code as what you are showing https://github.com/nextauthjs/next-auth-example/blob/main/app/api/auth/[...nextauth]/route.ts

put the `authOptions` object in a non-route file and this should work. Check the repo code you linked to for an example on how to do it.

**Comment by Chimennadi** [comment]
import NextAuth, { NextAuthOptions } from "next-auth"

const authOptions: NextAuthOptions = { }

const handler = NextAuth(authOptions)
export { handler as GET, handler as POST, authOptions }

Try this

**Comment by Chimennadi** [comment]
Move the authOptions in a different folder

import { AuthOptions } from "next-auth";
import GoogleProvider from 'next-auth/providers/google';

export const authOptions: AuthOptions = {
    providers: [
        GoogleProvider({
            clientId: process.env.GOOGLE_ID as string,
            clientSecret: process.env.GOOGLE_SECRET as string,
        }),
    ],
}

And import into the "route.ts"

import { authOptions } from '@/lib/authOptions';

const handler = NextAuth(authOptions);

export { handler as GET, handler as POST}

**Comment by prashantgitproject** [comment]
@balazsorban44 By putting authOptions object in a non-route file, I was able to deploy next 14 application. I was literally struggling for 2 weeks for this to deploy. There is no solution elsewhere. THANKSA LOT this helped.

**Comment by jonathanrstern** [comment]
I moved my authOptions object to a non-route file, but still not working.

Encountering the exact same error!

```
src/app/api/auth/[...nextauth]/route.ts
Type error: Route "src/app/api/auth/[...nextauth]/route.ts" does not match the required types of a Next.js Route.
  "auth" is not a valid Route export field.
```

Any thoughts?

**Comment by prashantgitproject** [comment]
@jonathanrstern can you share the code of [...nextauth]/route.ts file and screenshot of the folder structure. I might be able to see a flaw.

**Comment by andreimacavei** [comment]
Hi [balazsorban44](https://github.com/balazsorban44), I have followed the advice to put `authOptions` to a non-route file (`/app/config/authOptions.ts`) and I have passed the above error, but now on my Vercel deployment I'm getting :
```
src/app/api/auth/[...nextauth]/route.ts
--
17:31:59.700 | Type error: Route "src/app/api/auth/[...nextauth]/route.ts" does not match the required types of a Next.js Route.
17:31:59.700 | "handler" is not a valid Route export field
```

Here's the path and content of my auth route:
```code
src/app/auth/[...nextauth]/route.ts
--
import NextAuth from "next-auth";
import { authOptions } from "@/config/authOptions";

export const handler = NextAuth(authOptions);
export { handler as GET, handler as POST };
```

Is there anything I'm missing here? Thanks in advance

**Comment by icyJoseph** [comment]
@andreimacavei 

You have:

```js
export const handler =  NextAuth(authOptions);
```

Change that line to:

```js
const handler =  NextAuth(authOptions);
```
