### ISSUE TITLE
Partitioned Option - CHIPS on Cookie Settings, not working

### ISSUE THREAD

**Issue by Juan-Pestana** [nextauthjs/next-auth#9254]
### Environment

`    "next": "latest",
    "next-auth": "beta",
    "react": "^18.2.0",`

### Reproduction URL

https://github.com/Juan-Pestana/partitionedChipsFeatReq/

### Describe the issue

Im trying to build an iframe embedable app, so of course some cookie configuration must be done in order for cross-site information to work. 
Currently my cookies are been treated as 3rd party cookies, that will soon be deprecated in chrome. I tried to set **partitioned attribute** on the cookie config, as according to[ this article ](https://developer.chrome.com/docs/privacy-sandbox/chips/) this seems the way to go for future chrome versions, but this doesn't seem to have any effect.

As this is a fairly new thing...   To be honest, I'm not sure if this is a bug or a feature request.

### How to reproduce

Just add the partitioned attribute set to true on the cookie options.

``` 
cookies: {
    sessionToken: {
      // name: `__Secure-next-auth.session-token`,
      name:
        process.env.NODE_ENV === 'production'
          ? `${cookiePrefix}next-auth.session-token`
          : 'next-auth.session-token',
      options: {
        httpOnly: true,
        sameSite: 'none',
        path: '/',
        partitioned: true,
        secure: true,
      },
    },
    callbackUrl: {
      name:
        process.env.NODE_ENV === 'production'
          ? `${cookiePrefix}next-auth.callback-url`
          : 'next-auth.callback-url',
      options: {
        sameSite: 'none',
        path: '/',
        partitioned: true,
        secure: true,
      },
    },
    csrfToken: {
      name:
        process.env.NODE_ENV === 'production'
          ? `${hostPrefix}next-auth.csrf-token`
          : 'next-auth.csrf-token',
      options: {
        httpOnly: true,
        sameSite: 'none',
        path: '/',
        partitioned: true,
        secure: true,
      },
    },
    pkceCodeVerifier: {
      name:
        process.env.NODE_ENV === 'production'
          ? `${cookiePrefix}next-auth.pkce.code_verifier`
          : 'next-auth.pkce.code_verifier',
      options: {
        httpOnly: true,
        sameSite: 'none',
        path: '/',
        partitioned: true,
        secure: true,
      },
    },
  },

```

### Expected behavior

According to the article and [this demo site](https://chips-site-a.glitch.me/) the cookie set in the browser, must have a Partitioned Key property defined.

![Partitioned Key example image](https://wd.imgix.net/image/vgdbNJBYHma2o62ZqYmcnkq3j0o1/QcTVEgWjGYQZJtMX0g4a.png?auto=format&w=845)

**Comment by QamarQ** [comment]
I join the question. Does anyone know how to solve this as I have a frontend using nextauthjs login via cookies where I have set samesite to none but now chrome shows that soon it won't work without partitioned.

**Comment by professorhaseeb** [comment]
latest version of [jshttp/cookie](https://github.com/jshttp/cookie) has added `partitioned`, which is behind `useCookie`

**Comment by corbin-c** [comment]
facing the same issue here

**Comment by eshrager** [comment]
adding Partitioned does work. However, it does not work on iOS Chrome or iOS Safari if the device has cross-site tracking blocked in the settings menu. 

CHIPS is supposed to work even in these scenarios - does anyone have a workaround?

**Comment by Chucheen** [comment]
Has this been solved on any version of next-auth? I'm encountering the same issue where `partitioned: true` is not doing anything. I.E. not adding partitioned property to the cookie :(

**Comment by eshrager** [comment]
i can get it to work where i see partitioned: true but it does not work on the scenarios i described above. this is what my auth.js file looks like (for the cookies section) where it does work:
`cookies: {
    sessionToken: {
      options: {
        sameSite: "None",
        path: "/",
        secure: true,
        partitioned: true,
      },
    },
    callbackUrl: {
      options: {
        sameSite: "None",
        path: "/",
        secure: true,
        partitioned: true,
      },
    },
    csrfToken: {
      options: {
        sameSite: "None",
        path: "/",
        secure: true,
        partitioned: true,
      },
    },
  },`
