### ISSUE TITLE
Broken links: All adapter links broken

### ISSUE THREAD

**Issue by pippinmole** [nextauthjs/next-auth#9260]
### What is the improvement or update you wish to see?

-  [Options | NextAuth.js](https://next-auth.js.org/configuration/options) | [Ref](https://github.com/nextauthjs/next-auth/blob/v4/docs/docs/configuration/options.md?plain=1#L30)
    - Is: https://authjs.dev/reference/adapters#verification-token
    - Should: https://authjs.dev/getting-started/adapters#verification-token
-  [Upgrade Guide (v4) | NextAuth.js](https://next-auth.js.org/getting-started/upgrade-v4) | [Ref](https://github.com/nextauthjs/next-auth/blob/v4/docs/docs/getting-started/upgrade-to-v4.md?plain=1#L322)
    - Is: https://authjs.dev/reference/adapters#verification-token
    - Should: https://authjs.dev/getting-started/adapters#verification-token
-  [Introduction | NextAuth.js](https://next-auth.js.org/getting-started/introduction) | [Ref](https://github.com/nextauthjs/next-auth/blob/v4/docs/docs/getting-started/introduction.md?plain=1#L19)
    - Is: https://authjs.dev/reference/adapters
    - Should: https://authjs.dev/getting-started/adapters
-  [GitHub | NextAuth.js](https://next-auth.js.org/providers/github) | [Ref](https://github.com/nextauthjs/next-auth/blob/v4/docs/docs/providers/github.md?plain=1#L7)
    - Is: https://authjs.dev/reference/adapters
    - Should: https://authjs.dev/getting-started/adapters
-  [Frequently Asked Questions | NextAuth.js](https://next-auth.js.org/faq) | [Ref](https://github.com/nextauthjs/next-auth/blob/v4/docs/docs/faq.md?plain=1#L292)
    - Is: https://authjs.dev/reference/adapters
    - Should: https://authjs.dev/getting-started/adapters
-  [Create an Adapter | NextAuth.js](https://next-auth.js.org/tutorials/creating-a-database-adapter) | [Ref](https://github.com/nextauthjs/next-auth/blob/v4/docs/docs/tutorials/creating-a-database-adapter.md?plain=1#L10)
    - Is: https://authjs.dev/reference/adapters#models
    - Should: https://authjs.dev/getting-started/adapters#models
-  [Twitter | NextAuth.js](https://next-auth.js.org/providers/twitter) | [Ref](https://github.com/nextauthjs/next-auth/blob/v4/docs/docs/providers/twitter.md?plain=1#L7)
    - Is: https://authjs.dev/reference/adapters
    - Should: https://authjs.dev/getting-started/adapters
-  [Azure Active Directory | NextAuth.js](https://next-auth.js.org/providers/azure-ad) | [Ref](https://github.com/nextauthjs/next-auth/blob/v4/docs/docs/providers/azure-ad.md?plain=1#L14)
    - Is: https://authjs.dev/reference/adapters
    - Should: https://authjs.dev/getting-started/adapters

### Is there any context that might help us understand?

Looks like all the adapter links are broken.

Let me know if you want me to make a PR for this,
Thanks

**Comment by balazsorban44** [comment]
Fixed via #9262, appreciate it! :pray:
