### ISSUE TITLE
[Getting Started > Deployment] Doc: generate random string for `AUTH_SECRET` variable

### ISSUE THREAD

**Issue by Elkiwa** [nextauthjs/next-auth#9297]
### What is the improvement or update you wish to see?

The description below describes 2 distinct ways of generating a random string:
> Auth.js libraries require you to set an AUTH_SECRET environment variable. This is used to encrypt cookies and tokens. It should be a random string of at least 32 characters. On Linux systems, you can generate a suitable string using the command openssl rand -base64 32. You can also use a tool like [generate-secret.vercel.app](https://generate-secret.vercel.app/32) to generate a random value.

1. Base64 uses 4 ascii characters to encode 24-bits (3 bytes) of data, so I would prefer the following for consistent results:

Auth.js libraries require you to set an AUTH_SECRET environment variable. This is used to encrypt cookies and tokens. It should be a random string of at least 32 characters. On Linux systems, you can generate a suitable string using the command `openssl rand -base64 24`. You can also use a tool like [generate-secret.vercel.app](https://generate-secret.vercel.app/32) to generate a random value.

As 24 is divisible by 3, the result would also avoid paddings with '=' 

2. However, it is not straight-forward to reason with the mechanism of base64 and not everyone is a sysadmin, so we may need further explanation or replace openssl command with something else

### Is there any context that might help us understand?

References:
1. [Google Cloud: Generating a strong pre-shared key](https://cloud.google.com/network-connectivity/docs/vpn/how-to/generating-pre-shared-key)
2. [RedHat: 6 OpenSSL command options that every sysadmin should know](https://www.redhat.com/sysadmin/6-openssl-commands)

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/deployment#environment-variables
https://next-auth.js.org/deployment#vercel

**Comment by ndom91** [comment]
Thanks for pointing this out! Someone also [opened a PR](https://github.com/nextauthjs/next-auth/pull/10154) explaining this to us and we've updated the example command to use 33-bits, so it gets truncated correclty without the `=` padding :+1:
