### ISSUE TITLE
`session()` callback is invoked using `auth()`, contrary to what is stated in the documentation.

### ISSUE THREAD

**Issue by jakobpack** [nextauthjs/next-auth#9329]
### What is the improvement or update you wish to see?

In the [Migration Guide ](https://authjs.dev/guides/upgrade-to-v5) it states:
> When using auth(), the [session() callback](https://authjs.dev/reference/core/types#session) is ignored.

But as I currently tried to modify my jwt token, returned by the Credentials provider, I had to use the `session()` callback to get the data via the `auth()` method in a server action.

### Code for context

```js
// data.ts
"use server";

import { auth } from "@/auth";

export async function getData() {
  const session = await auth();
  console.log(session.user.profileId); //works
}
```

```js
// auth.ts

// ...

export const { auth, signIn, signOut } = NextAuth({
// ...,
  providers: [
    Credentials({
      async authorize(credentials) {
        const parsedCredentials = z
          .object({ email: z.string().email(), password: z.string().min(6) })
          .safeParse(credentials);

        if (parsedCredentials.success) {
          const { email, password } = parsedCredentials.data;
          const user = await getUser(email);
          if (!user) return null;
          const passwordsMatch = await bcrypt.compare(password, user.password);

          if (passwordsMatch) {
            return {
              id: user.id,
              profileId: user.profiles[0].id,
            };
          }
        }

        console.log("Invalid credentials");
        return null;
      },
    }),
callbacks: {
    authorized({ auth, request: { nextUrl } }) {
      const isLoggedIn = !!auth?.user;
      const isOnDashboard = nextUrl.pathname.startsWith("/dashboard");
      if (isOnDashboard) {
        if (isLoggedIn) return true;
        return false; // Redirect unauthenticated users to login page
      } else if (isLoggedIn) {
        return Response.redirect(new URL("/dashboard", nextUrl));
      }
      return true;
    },
    async session({ session, token }) {
      if (token?.user) {
        session.user = {
          id: token.user.id,
          profileId: token.user.profileId,
        };
      }
      return session;
    },
  },
  session: {
    strategy: "jwt",
  },
  ],
} satisfies NextAuthConfig);
```

### Does the docs page already exist? Please link to it.

https://authjs.dev/guides/upgrade-to-v5

**Comment by vinayavodah** [comment]
Hey @jakobpack, the auth object received in the authorized callback (or inside the middleware - req.auth) is always null for me even if I have logged in the user (CredentialProvider). Do you happen to know what the reason might be? I see its working for you.

**Comment by vinayavodah** [comment]
@jakobpack nevermind, got it working https://github.com/nextauthjs/next-auth/issues/9097.

Also thanks for the above insight!

**Comment by leohxj** [comment]
I am next-auth@beta, @auth/prisma-adapter@1.0.10.

the auth object received in the authorized callback (or inside the middleware - req.auth) is always null too!!

**Comment by balazsorban44** [comment]
we reverted to ignoring part and will rather introduce the change via a flag in #9702 so the behavior is more consistent/less breaking for now. Will update the migration guide shortly
