### ISSUE TITLE
Typescript Module Augmentation example in documentation is wrong?

### ISSUE THREAD

**Issue by Huijiro** [nextauthjs/next-auth#9377]
### What is the improvement or update you wish to see?

There's a [example on the website](https://authjs.dev/getting-started/typescript) to get typescript to behave properly with the custom User etc, but i think it is wrong because the example did not work for me, but i don't know if it is a svelte issue, or another thing.

### Is there any context that might help us understand?

Augmenting the "@auth/core" module does nothing to the interfaces, you need to actually augment the "@auth/core/types" to make it work properly.

With augmentation to the "@auth/core" it does not know that the user has the property of role.
![image](https://github.com/nextauthjs/next-auth/assets/84474751/b8758346-076a-4c54-bab4-2cc470548948)

But with augmentation of the "@auth/core/types" it works
![image](https://github.com/nextauthjs/next-auth/assets/84474751/b18dd771-2b79-4cb3-a502-04a7ab0ac38a)

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/typescript

**Comment by vexra** [comment]
looks like in this issue [#9253](https://github.com/nextauthjs/next-auth/issues/9253)

**Comment by cexra** [comment]
looks like the same with this issue [#9253](https://github.com/nextauthjs/next-auth/issues/9253)

**Comment by Huijiro** [comment]
> looks like the same with this issue [#9253](https://github.com/nextauthjs/next-auth/issues/9253)

So this is not a svelte specific issue? Just that the docs need to be updated then?

**Comment by ndom91** [comment]
Closing, this has been fixed. Thanks for the PR @Huijiro
