### ISSUE TITLE
What actually triggers the nextauth's "newUser" page?

### ISSUE THREAD

**Issue by 0x02f0bcd4** [nextauthjs/next-auth#9394]
### What is the improvement or update you wish to see?

The nextauth documentation about Pages says about newUser page, but doesn't mention what actually makes user to redirect to newUser page.

### Is there any context that might help us understand?

 My theory was that when an user logs in, the isNewUser field found in jwt callback may trigger the redirection. To test this, I manually set the isNewUser field in jwt callback like so ->

```

async jwt(jwt_Details){
 jwt_Details.isNewUser = true;
 return jwt_Details.token;
}

```

However, my theory seems to be not to be the case, as no redirection was made to the newUser page.

```
pages:{
newUser: '/newUser'
}
```
The oauth provider is github, who doesn't set the isNewUser by default (`jwt_Details.isNewUser === undefined`), even when it is the first time user authorizing the application.

I already have made a newUser page in -> app/newUser/page.js

Using app router.

These information were retrieved from the package.json file ->

```
"next": "14.0.4",
"next-auth": "^4.24.5",
"react": "^18",
"react-dom": "^18",
```

### Does the docs page already exist? Please link to it.

from newer [auth.js doc](https://authjs.dev/guides/basics/pages) , older [next-auth.js doc](https://next-auth.js.org/configuration/pages)

**Comment by ThangHuuVu** [comment]
https://github.com/nextauthjs/next-auth/blob/5254ff78f2002c0eacf13389c26baac47a2b5326/packages/core/src/lib/actions/callback/index.ts#L281-L288
This is the code that does it. The developer needs to configure the newUser page and use an adapter for this to be triggered.
