### ISSUE TITLE
@auth/sveltekit does not install in sveltekit version 2 project

### ISSUE THREAD

**Issue by nicholasmordecai** [nextauthjs/next-auth#9409]
### Environment

System:
OS: macOS 12.3
CPU: (10) arm64 Apple M1 Pro
Memory: 83.55 MB / 16.00 GB
Shell: 5.8 - /bin/zsh
Binaries:
Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
Yarn: 1.22.19 - /usr/local/bin/yarn
npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
Browsers:
Chrome: 120.0.6099.109
Safari: 15.4

### Reproduction URL

https://github.com/nicholasmordecai/sveltekit-2-broken-authjs

### Describe the issue

NPM errors when you try to install @auth/sveltekit due to an unmet peer dependency. This has been an issue for 5 days since sveltekit 2 was released into production. 

### How to reproduce

Use any project with sveltekit 2 and run:

```
npm install --save @auth/sveltekit
```

### Expected behavior

I would expect it to install the depdency.

**Comment by nicholasmordecai** [comment]
I can see there is a pending job waiting for this update to release:

https://github.com/nextauthjs/next-auth/commit/6c958d7e10edabb2915e101096e1dba5e22fff6b

If anybody comes here, this should be released shortly I hope!

**Comment by balazsorban44** [comment]
Thanks, it should be released now! https://github.com/nextauthjs/next-auth/releases/tag/%40auth%2Fsveltekit%400.5.0
