### ISSUE TITLE
type error for Prisma Client with extensions

### ISSUE THREAD

**Issue by jeremy-code** [nextauthjs/next-auth#9413]
### Adapter type

@auth/prisma-adapter

### Environment

**System:**
OS: macOS 14.2
CPU: (8) arm64 Apple M1
Memory: 101.66 MB / 8.00 GB
Shell: 5.9 - /bin/zsh

**Binaries:**
Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
Yarn: 1.22.19 - ~/.yarn/bin/yarn
npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm

**Browsers:**
Chrome: 120.0.6099.109
Safari: 17.2

**npmPackages:**
@auth/prisma-adapter: ^1.0.11 => 1.0.11 
next: 14.0.4 => 14.0.4 
next-auth: ^4.24.5 => 4

### Reproduction URL

https://github.com/jeremy-code/example-prisma-accelerate-adapter

### Describe the issue

After extending a Prisma Client with [Accelerate](https://www.prisma.io/docs/accelerate/api-reference) to use Prisma in edge environment, the Prisma Adapter throws an error, saying that the argument passed is not correct or 'PrismaClient<PrismaClientOptions, never, DefaultArgs>', and is missing the `$on` and `$use` properties.

Similar issue has been raised in [`prisma/prisma`](https://github.com/prisma/prisma) in issue: https://github.com/prisma/prisma/issues/22050: Type issues with prisma accelerate.

Issue occurs on both NextAuth.js v4 and Auth.js v5.

Error thrown is:
```typescript
Argument of type 'DynamicClientExtensionThis<TypeMap<InternalArgs & { result: {}; model: { $allModels: { aggregate: () => <T, A>(this: T, args: Exact<A, Args<T, "aggregate"> & PrismaCacheStrategy>) => AcceleratePromise<...>; ... 6 more ...; groupBy: () => <T_7, A_7>(this: T_7, args: Exact<...>) => AcceleratePromise<...>; }; user: { ....' is not assignable to parameter of type 'PrismaClient<PrismaClientOptions, never, DefaultArgs>'.
  Type 'DynamicClientExtensionThis<TypeMap<InternalArgs & { result: {}; model: { $allModels: { aggregate: () => <T, A>(this: T, args: Exact<A, Args<T, "aggregate"> & PrismaCacheStrategy>) => AcceleratePromise<...>; ... 6 more ...; groupBy: () => <T_7, A_7>(this: T_7, args: Exact<...>) => AcceleratePromise<...>; }; user: { ....' is missing the following properties from type 'PrismaClient<PrismaClientOptions, never, DefaultArgs>': $on, $use
  
ts(2345)
  ```
  
<img width="1021" alt="image" src="https://github.com/nextauthjs/next-auth/assets/43259194/0485b720-7072-44bf-a11f-142aab9508e8">

### How to reproduce

1. Generate and instantiate a Prisma Client (as the default type is `any`) and extend it with [Accelerate](https://www.prisma.io/docs/accelerate/api-reference):

```javascript
import { PrismaClient } from "@prisma/client/edge";
import { withAccelerate } from "@prisma/extension-accelerate";

const prisma = new PrismaClient().$extends(withAccelerate());
```
2. Pass Prisma Client to `PrismaAdapter`, which results in TypeError

### Expected behavior

No TypeError should have happened instead of what actually happened.

**Comment by boredland** [comment]
This seems to be a more general problem with extensions, not only with the Accelerate extension.
