### ISSUE TITLE
findOne() is deprecated in Prisma v2.13.0

### ISSUE THREAD

**Issue by awey95** [nextauthjs/next-auth#942]
**Describe the bug**
`findOne` is deprecated in v2.13.0 of Prisma. Needs to be updated to use `.findUnique()`

**Steps to reproduce**
use `findOne()` you'll encounter the warning.

`warn(prisma)  findOne is deprecated. Please use findUnique instead.`

**Comment by balazsorban44** [comment]
Hi there! Thanks for raising an issue. This has been fixed in #881.

We hope to get a `canary` release out in December with all the recent changes. Keep in mind, there might be breaking changes until we release it to stable on npm. (We need to add some tests before that)
