### ISSUE TITLE
Auth0Provider does not respect audience settings in V5

### ISSUE THREAD

**Issue by mackinleysmith** [nextauthjs/next-auth#9422]
### Provider type

Auth0

### Environment

```
  System:
    OS: macOS 14.1.2
    CPU: (12) arm64 Apple M2 Pro
    Memory: 82.81 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.2.0 - ~/.nvm/versions/node/v21.2.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.2.0/bin/npm
  Browsers:
    Chrome: 120.0.6099.109
    Safari: 17.1.2
  npmPackages:
    next: 14.0.3 => 14.0.3
    next-auth: ^5.0.0-beta.4 => 5.0.0-beta.4
    react: ^18 => 18.2.0
```

### Reproduction URL

do not have, would need to set up an auth0 account? let me know how to proceed here.

### Describe the issue

Hi there, I'm trying to use the Auth0Provider with NextAuth v5 beta, and cannot for the life of me get it to respect the audience value that I supply. I've confirmed that I can fetch a token via curl or Postman with my custom audience, but it never seems to get passed into the request that's made to Auth0 by NextAuth's internals.

### How to reproduce

My `Auth0Provider` has been through several iterations, but currently looks like this:

```typescript
Auth0Provider({
  clientId: process.env.AUTH0_CLIENT_ID,
  clientSecret: process.env.AUTH0_CLIENT_SECRET,
  issuer: process.env.AUTH0_ISSUER_BASE_URL,
  token: { params: { audience: process.env.AUTH0_AUDIENCE } },
  authorization: {
    params: {
      connection: "google-oauth2",
      scope: "openid profile email offline_access",
      audience: process.env.AUTH0_AUDIENCE,
    },
  },
});
```

The `connection` and `scope` parameters are relayed to Auth0 properly, so what's up with `audience`?

### Expected behavior

The token fetched from Auth0 has the audience that I specify.

**Comment by balazsorban44** [comment]
I could not reproduce this, please add a full reproduction with a link.

Using your example, the authorization URL was constructed as expected:

```
https://foo.auth0.com/authorize?response_type=code&client_id=id&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fcallback%2Fauth0&audience=https%3A%2F%2Fapi.example.com%2F&scope=openid+profile+email&code_challenge=jIn9bPahM08lj9ToS_tmeJLvuEgph0l1p-2Ch41-nnc&code_challenge_method=S256
```

Then, the returned `access_token` correctly lists my audience under the `aud` property.

Adding `audience` to the  `token` params is probably not necessary, I think it would be used only if you are using client_credentials flow.

Make sure that the `AUTH0_AUDIENCE` env. variable is correctly set. Feel free to open a new issue if you have a full reproduction, but this sounds like a possible misconfiguration.

**Comment by mackinleysmith** [comment]
@balazsorban44 how did you print out the constructed authorization URL? I would like to try this in my application.

**Comment by balazsorban44** [comment]
it's in the inspector, but you can also add the `debug: true` flag to see it on the server terminal with more info. see https://authjs.dev/reference/core#debug

**Comment by mackinleysmith** [comment]
Aha! This helped me determine that NextAuth is indeed sending the audience flag in the URL to Auth0 -- it's the handling on Auth0's side that's a little odd, I guess. It seems the returned `id_token`, which is the one I've been using, ignores the `audience` setting, but as you said, the `access_token` actually does include it. The _way_ it is included is a little strange -- it seems my `access_token` now includes an array of strings in the `aud` field, which I thought was against the JWT spec... Oh well. This is enough for me to move forward with, thank you for your time.
