### ISSUE TITLE
Error: PrismaClient is unable to run in Vercel Edge Functions (in local dev environment)

### ISSUE THREAD

**Issue by erinnovations** [nextauthjs/next-auth#9423]
### Adapter type

@auth/prisma-adapter

### Environment

  System:
    OS: Windows 11 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900H
    Memory: 10.40 GB / 31.70 GB
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.77)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @auth/prisma-adapter: ^1.0.11 => 1.0.11
    next: latest => 14.0.4
    next-auth: beta => 5.0.0-beta.4
    react: ^18.2.0 => 18.2.0

### Reproduction URL

https://github.com/erinnovations/next-auth-example-main-vercel-edge-error

### Describe the issue

I'm encountering AdapterErrors on my localhost, despite not using any edge functions:

"Error: PrismaClient is unable to run in Vercel Edge Functions"

![image](https://github.com/nextauthjs/next-auth/assets/253455/1bbd5827-c9cb-4e95-8763-63e4a274c82d)

### How to reproduce

Add the Prisma adapter to the AuthJS V5 Beta. (It's already included in the example for reproduction.)
Run 'yarn dev' on localhost, and you'll see the error.

### Expected behavior

There are no errors when Vercel edge functions are not in use.

**Comment by hainguyents13** [comment]
same issue, so annoying

**Comment by balazsorban44** [comment]
This is not something Auth.js can fix, it's up to Prisma.

But you can have a look at:
https://authjs.dev/guides/upgrade-to-v5#edge-compatibility

You can also follow their issue here: https://github.com/prisma/prisma/issues/21394

Another alternative is to try using https://www.prisma.io/data-platform/accelerate for now, which is compatible.
