### ISSUE TITLE
Importing @auth/solid-start anywhere in an application causes an error

### ISSUE THREAD

**Issue by hansoksendahl** [nextauthjs/next-auth#9427]
### Environment

OS: OSX Ventura 13.3.1 (a)
Node: v20.3.1
@auth/solid-start: 0.1.8
Browser: Chrome 120.0.6099.71 (Official Build) (arm64)

### Reproduction URL

https://github.com/BeanSoftwareGroup/auth-solid-start-bug

### Describe the issue

Simply importing the `@auth/solid-start` library breaks the build.

```
[vite] Error when evaluating SSR module ~start/entry-server: failed to import "@auth/solid-start"
|- Error: Cannot find module '/Users/username/Code/auth-solid-start-bug/node_modules/.pnpm/@auth+solid-start@0.1.8_solid-js@1.8.5_solid-start@0.3.10/node_modules/@auth/solid-start/chunk-HXRSFH6L.js' imported from /Users/username/Code/auth-solid-start-bug/node_modules/.pnpm/@auth+solid-start@0.1.8_solid-js@1.8.5_solid-start@0.3.10/node_modules/@auth/solid-start/index.js
    at finalizeResolution (node:internal/modules/esm/resolve:263:11)
    at moduleResolve (node:internal/modules/esm/resolve:908:10)
    at defaultResolve (node:internal/modules/esm/resolve:1121:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36)

An unhandled error occured: Error: Cannot find module '/Users/username/Code/auth-solid-start-bug/node_modules/.pnpm/@auth+solid-start@0.1.8_solid-js@1.8.5_solid-start@0.3.10/node_modules/@auth/solid-start/chunk-HXRSFH6L.js' imported from /Users/username/Code/auth-solid-start-bug/node_modules/.pnpm/@auth+solid-start@0.1.8_solid-js@1.8.5_solid-start@0.3.10/node_modules/@auth/solid-start/index.js
    at finalizeResolution (node:internal/modules/esm/resolve:263:11)
    at moduleResolve (node:internal/modules/esm/resolve:908:10)
    at defaultResolve (node:internal/modules/esm/resolve:1121:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36)
```

I have tried the usual workarounds of including the library in the `ssr.external` array in vite.config.ts to no effect.

### How to reproduce

Run the dev server.

```
pnpm run dev
```

### Expected behavior

The build should not break when importing `@auth/solid-start`

**[Edit: Updated issue title and description to be indicative of the nature of the error. Not just limited to SSR builds]**

**Comment by hansoksendahl** [comment]
@ThangHuuVu @balazsorban44 Any chance of getting eyes on this? This is a hard blocker for my team.

**Comment by hansoksendahl** [comment]
I dug in deeper the compiled `@auth/solid-start` module has an import of the file `chunk-HXRSFH6L.js`. This file does not exist in the module.

**Comment by hansoksendahl** [comment]
@ThangHuuVu @balazsorban44 I discovered the source of the error.

There is an error in the build step for this module. Believe it or not this module has been broken since the release of version `0.1.3`. The built source code attempts to import a file that does not exist.

Reverting to version `0.1.2` resolves the error.

**Comment by aronmal** [comment]
I also encounter this problem. I also reverted back to `0.1.2` for now.

**Comment by hansoksendahl** [comment]
@ThangHuuVu @balazsorban44 Any chance of getting eyes on this. @auth/solid-start has been broken for 6 version iterations now. It appears to be due to something in the build process. The built files are referencing a file that does not exist. Please see [here](https://github.com/nextauthjs/next-auth/issues/9427#issuecomment-1870650541) for more information.

**Comment by balazsorban44** [comment]
Please refrain from tagging maintainers, as it won't result in quicker resolution. We will look into this when we have the time. Feel free to dive into the source code, maybe send a PR with a fix if you find it. 🙏

**Comment by marbonestu** [comment]
I think the issue is because that file is missing in the package.json https://github.com/nextauthjs/next-auth/blob/main/packages/frameworks-solid-start/package.json#L9
Including something like this should fix it. 
```
...
  "files": [
    "*.d.ts*",
    "*.js",
    "src"
  ],
  ...
  ```
