### ISSUE TITLE
Session updates are firing multiply in the beta (v5)

### ISSUE THREAD

**Issue by minakawa-daiki** [nextauthjs/next-auth#9446]
### Environment

System:
OS: macOS 13.3.1
CPU: (8) arm64 Apple M1
Memory: 46.20 MB / 16.00 GB
Shell: 5.9 - /bin/zsh
Binaries:
Node: 18.17.1 - ~/.nodebrew/current/bin/node
Yarn: 1.22.19 - ~/.nodebrew/current/bin/yarn
npm: 9.6.7 - ~/.nodebrew/current/bin/npm
pnpm: 8.11.0 - /opt/homebrew/bin/pnpm
bun: 1.0.3 - ~/.bun/bin/bun
Browsers:
Chrome: 120.0.6099.109
Edge: 120.0.2210.91
Safari: 16.4
npmPackages:
next: latest => 14.0.4
next-auth: beta => 5.0.0-beta.4
react: ^18.2.0 => 18.2.0

### Reproduction URL

https://github.com/minakawa-daiki/next-auth-sandobox

### Describe the issue

I am using the beta version of next-auth with nextjs App Router, but session updates are firing multiply.

The following URL, which is provided by the official version, also reproduces the problem.
https://next-auth-example.vercel.app/client-example

I also confirmed that for the adapter's updateSession, it was firing twice per request.

https://github.com/nextauthjs/next-auth/assets/22878067/dd9af189-1357-4ed4-a710-edc3cfbee728

### How to reproduce

In the official sample, multiple session updates run as you go back and forth between tabs.

In the development environment at hand, it fires multiple times, even at browser reload timing.

### Expected behavior

The number of session updates should be done only once per process, with only one request.

**Comment by balazsorban44** [comment]
This should be fine in dev, since Next.js runs in React Strict mode by default. When a tab switch happens, we trigger an effect which can be called twice.

Read more at https://nextjs.org/docs/pages/api-reference/next-config-js/reactStrictMode

**Comment by A7med3bdulBaset** [comment]
What about https://next-auth-example.vercel.app/client-example (production)?

**Comment by minakawa-daiki** [comment]
> This should be fine in dev, since Next.js runs in React Strict mode by default. When a tab switch happens, we trigger an effect which can be called twice.
> 
> Read more at https://nextjs.org/docs/pages/api-reference/next-config-js/reactStrictMode


React Strict mode" is not relevant.
It is also happening in the production environment.

**Comment by eliza921** [comment]
I might be wrong, but isn't that a normal behavior when different components call for the useSession() or auth() session hooks?

**Comment by A7med3bdulBaset** [comment]
> I might be wrong, but isn't that a normal behavior when different components call for the useSession() or auth() session hooks?

No, not normal.

- `auth()` is fetching the session server-side. so It won't exist in the network tab.
- `useSession()` is receiving its value from `<AuthProvider />` that fetches the session once when the provider mounts (useEffect with empty dependency array) and on `visibilty` event listener.
