### ISSUE TITLE
Sign out from NextAuth and OAuth provider

### ISSUE THREAD

**Issue by marco910** [nextauthjs/next-auth#946]
**Your question**
I'm using NextAuth for logging in to my web app with AWS Cognito hosted UI. The sign in process and authentication is working well but when I'm using the NextAuth `signOut()` function the user is only signed out from the web app - not from Cognito. If now another user wants to sign in on the same machine, he is signed in with the Cognito account of the previous user.
How can I sign out the user also form Cognito?

**What are you trying to do**
Signing out a user from NextAuth and AWS Cognito (OAuth provider).

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [X] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Hi there! There is already an issue opened about this here: #836 Going to close this one in favor of the already opened one! If you have any comments, please go to #836.

Thank you!
