### ISSUE TITLE
signIn using redirect: false does not return specified object

### ISSUE THREAD

**Issue by renanleonel** [nextauthjs/next-auth#9465]
### What is the improvement or update you wish to see?

when signing in using `const request = await signIn('credentials', {
			redirect: false,
			...data,
		});`, the request variable isn't an object like this:
		
		`{error: string | undefined, status: number, ok: boolean,  url: string | null}`, 

instead only returns the url that called the signIn method.

### Is there any context that might help us understand?

using next auth v5 beta, with this behavior of signIn with redirect false i can't validate if the signIn was successful without redirecting to the default page specified in auth.config.ts. also, it is currently breaking the usage of useFormState, throwing a runtime error: formState is undefined

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/getting-started/client#using-the-redirect-false-option

**Comment by GoudekettingRM** [comment]
+1

I'm doing this:

```ts
const resp = await signIn('credentials', {
  username: data.username,
  password: data.password,
  callbackUrl: '/dashboard',
  redirect: false,
});

console.log({ resp });
```

But it just throws a 401 when I enter wrong credentials and nothing gets logged. Even if I add a `try/catch` around it, it does not catch.

**Comment by ZeroCho** [comment]
also, error status which is thrown in `authorize` function is not sent to client.
in v4, #8775 resolves this issue, but in v5, I think this issue happens again.

**Comment by sezercoban** [comment]
Issue seems to be persisting in V5, (5.0.0-beta.24). If I throw in authorize, client still gets ok: true, status:200, error:credentials.

**Comment by benkissi** [comment]
Am using
`"next-auth": "^5.0.0-beta.25",`
If I set redirect to false it returns a URL and not the response. Is there something am doing wrong?
```const response = await signIn("credentials", {
            email,
            password,
            redirect: false,
        })

// response is http://localhost:3000/login
```
