### ISSUE TITLE
Improve Contrast for Highlighted Text in Code Blocks within .env files

### ISSUE THREAD

**Issue by tomaszwysocki** [nextauthjs/next-auth#9470]
### What is the improvement or update you wish to see?

In the documentation, when presenting code blocks containing .env files, the color formatting for highlighting environment variables needs improvement due to low contrast, making the highlighted text difficult to read.

### Is there any context that might help us understand?

![image](https://github.com/nextauthjs/next-auth/assets/121371814/d5a87969-6104-4dbb-8991-c0f638543647)

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/providers/email#smtp

**Comment by roy9495** [comment]
Can I work on this issue?

**Comment by tomaszwysocki** [comment]
Sure

**Comment by MohammedAslam106** [comment]
> Can I work on this issue?

Hey,
Are you working on this?

**Comment by roy9495** [comment]
> > Can I work on this issue?
> 
> Hey, Are you working on this?

Yeah
