### ISSUE TITLE
resolve the inconsistency in table names

### ISSUE THREAD

**Issue by qqpann** [nextauthjs/next-auth#9539]
### Environment

System:
OS: macOS 14.2.1
CPU: (8) x64 Apple M1
Memory: 10.76 MB / 16.00 GB
Shell: 5.9 - /bin/zsh
Binaries:
Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.2/bin/yarn
npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
pnpm: 8.14.0 - ~/.local/share/pnpm/pnpm
bun: 1.0.1 - ~/.bun/bin/bun
Browsers:
Brave Browser: 102.1.39.122
Chrome: 120.0.6099.129
Edge: 120.0.2210.91
Safari: 17.2.1
npmPackages:
@auth/core: ^0.19.0 => 0.19.0
@auth/drizzle-adapter: ^0.3.12 => 0.3.12
next: ^14.0.4 => 14.0.4
next-auth: 5.0.0-beta.4 => 5.0.0-beta.4
react: ^18.2.0 => 18.2.0

### Reproduction URL

https://github.com/qqpann/next-auth-inconsistent-table-names

### Describe the issue

The table names is inconsistent across documentations and codes.
E.g. users and user, accounts and accounts, sessions and session, verification_tokens and verification_token and verificationToken and verificationTokens.
Also, the field name is not consistent either.
E.g. userId while other being snake_case

### How to reproduce

Follow the official instruction for supabase and drizzle, you will easity encounter this.

- https://authjs.dev/reference/adapter/supabase
- https://authjs.dev/reference/adapter/pg
- https://authjs.dev/reference/adapter/drizzle

### Expected behavior

The table name is consistent and doesn't cause error because of inconsistency.

**Comment by balazsorban44** [comment]
We try to follow the conventions of the underlying ORM/database docs/conventions, which might result in inconsistencies _between_ adapters' **default** table names.

However, most adapters should already allow you to override the default names, to match your desired style. If this is missing for your adapter, you can open a PR adding a config option for that Adapter or open a feature request if you are not sure how to do so.

If the current default doesn't match the convention, we encourage you to open a PR for the adapter to make the default match the ORM/db convention, which we then might release with a major (breaking) bump.

Added a note about this under our [adapter guidelines](https://authjs.dev/guides/adapters/creating-a-database-adapter#official-adapter-guidelines)

**Comment by qqpann** [comment]
So you basically try only to normalize the adapter interface, but not database table naming convention, right?

**Comment by balazsorban44** [comment]
Yeah, because the adapter interface is what Auth.js libs need to adhere to, so it works the same way. The database models are up to the ORM/db, and Auth.js doesn't really care about its formatting.

**Comment by qqpann** [comment]
Understood. Thanks
