### ISSUE TITLE
No Package Found In Registry @auth/express

### ISSUE THREAD

**Issue by solo8116** [nextauthjs/next-auth#9555]
### What is the improvement or update you wish to see?

please publish @auth/express package

### Is there any context that might help us understand?

on the website docs it is mentioned to install @auth/express using npm but its not working

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@auth%2fexpress - Not found
npm ERR! 404
npm ERR! 404  '@auth/express@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

### Does the docs page already exist? Please link to it.

https://authjs.dev/reference/express

**Comment by balazsorban44** [comment]
https://www.npmjs.com/package/@auth/express it's there, please try again
