### ISSUE TITLE
Incomplete documentation 

### ISSUE THREAD

**Issue by shinebarbhuiya** [nextauthjs/next-auth#9557]
### What is the improvement or update you wish to see?

Hey I was trying to read about refresh token rotation but the doc was incomplete.  

Link of the page is - https://authjs.dev/guides/basics/refresh-token-rotation 

Please check the under Database strategy tabs.

### Is there any context that might help us understand?

https://authjs.dev/guides/basics/refresh-token-rotation

### Does the docs page already exist? Please link to it.

https://authjs.dev/guides/basics/refresh-token-rotation?frameworks=next

**Comment by ndom91** [comment]
We've updated the refresh token guide a bit in the new docs - https://authjs.dev/guides/refresh-token-rotation. However, we know its not ideal, the whole situation is a bit hacky and could use some improvement.
