### ISSUE TITLE
Outdated peerDependencies

### ISSUE THREAD

**Issue by aaronfulkerson** [nextauthjs/next-auth#956]
**Describe the bug**
Installing the package using NPM v7 causes installation to fail unless the --force flag is used.

**Steps to reproduce**
Create a new Next.js project and attempt to install next-auth.

**Expected behavior**
No

**Screenshots or error logs**
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: project@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1" from next-auth@3.1.0
npm ERR! node_modules/next-auth
npm ERR!   next-auth@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Additional context**

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Thank you! This looks legit. Our `canary` branch lists react 17 as a possible peer dependency version. We hope to release it to npm this month.

**Comment by foaadnami** [comment]
related to [814](https://github.com/nextauthjs/next-auth/issues/814) [819](https://github.com/nextauthjs/next-auth/pull/819)

**Comment by nyoung697** [comment]
Is there a workaround for this currently?  I tried installing the canary branch but then got another error:

`error - ./node_modules/next-auth/client.js:1:0
Module not found: Can't resolve './dist/client'`

create-next-app is using React 17.

**Comment by balazsorban44** [comment]
This was released yesterday! You can install it with `npm i next-auth@canary`
