### ISSUE TITLE
Minor things in a documentation

### ISSUE THREAD

**Issue by mihilt** [nextauthjs/next-auth#9591]
### What is the improvement or update you wish to see?

These are not that big of a deal, but I'll just write it down.

### Is there any context that might help us understand?

There's a typo in v3 documentation

<kbd>![image](https://github.com/nextauthjs/next-auth/assets/50368758/146acb4a-2226-4fc4-8533-d0509181b3c6)</kbd>

---

I don't know why only `Providers` and `Guides`'s expansion buttons change their background color when I hover my mouse in v4 documentation.

https://github.com/nextauthjs/next-auth/assets/50368758/86f8adf5-5fa0-406e-b8d1-c6b52a6ffdde

**Comment by balazsorban44** [comment]
Indeed, minor. Since v3 hasn't been upgraded in a long time and nobody should use it, I don't that's a big issue. Not sure about the second issue either, but feel free to investigate and send a PR! I'll close this, as we're not going to prioritize this.
