### ISSUE TITLE
Improve `redirectTo` documentation

### ISSUE THREAD

**Issue by lpbonomi** [nextauthjs/next-auth#9592]
### What is the improvement or update you wish to see?

It would be nice that the docs specified that the redirectTo param must be a relative path. I was passing the whole url (www.example.com/whatever) instead of the relativePath (/whatever) and couldn't make it work until I saw the code for the redirectCallback

### Is there any context that might help us understand?

-

### Does the docs page already exist? Please link to it.

https://authjs.dev/reference/nextjs#signin

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth/blob/d85269d1169d068448b831d2ee9517e4673c78b8/packages/next-auth/src/index.tsx#L241

Wan to open a PR? 🙏

**Comment by lpbonomi** [comment]
@balazsorban44 Thanks for everything that you do. I've just created a PR here https://github.com/nextauthjs/next-auth/pull/9792 . LMK if it needs anything else. I was also thinking that the type of redirectTo could be modified to /${string} , what do you think?

**Comment by nik132-eng** [comment]
hey @lpbonomi  is this issue fixed?

**Comment by lpbonomi** [comment]
@nik132-eng you can check the status in #9792
