### ISSUE TITLE
Okta missing `state` parameter

### ISSUE THREAD

**Issue by hakoares** [nextauthjs/next-auth#9625]
### Provider type

Okta

### Environment

```
System:
    OS: macOS 14.1.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 161.89 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.7.4 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
  Browsers:
    Safari: 17.1
  npmPackages:
    @auth/core: ^0.20.0 => 0.20.0 
    @auth/sveltekit: ^0.5.2 => 0.5.2 
```

### Reproduction URL

https://github.com/hakoares/authjs-okta-example

### Describe the issue

When using SvelteKitAuth with Okta as provider, login fails with the following description:
```
[auth][debug]: OAuthCallbackError {
  "providerId": "okta",
  "error": "invalid_request",
  "error_description": "The authentication request has an invalid 'state' parameter."
}
```

By manually adding `&state=random-string` to the authorization URL it works.

### How to reproduce

```ts
// hooks.server.ts
export const handle = SvelteKitAuth(async () => {
	const authOptions = {
		secret: YOUR_SECRET,
		trustHost: true,
		debug: true,
		providers: [
			Okta({
				clientId: OKTA_CLIENT_ID,
				clientSecret: OKTA_CLIENT_SECRET,
				issuer: OKTA_ORG_URL
			})
		]
	};
	return authOptions;
}) satisfies Handle;
```

### Expected behavior

If I'm missing something in my setup, the documentation is lacking this step. Otherwise it should work like the setup above.

**Comment by jollytoad** [comment]
I've hit the same problem, although in a Next.js app, but after scouring the source, I discovered there is a `checks` option that can be passed to the provider, and it appears you need to use `["pkce", "state"]` for Okta...

```
  providers: [OktaProvider({
    checks: ["pkce", "state"]
  })],
```

(using `"next-auth": "^5.0.0-beta.4"`)

**Comment by Rithikreddy** [comment]
> I've hit the same problem, although in a Next.js app, but after scouring the source, I discovered there is a `checks` option that can be passed to the provider, and it appears you need to use `["pkce", "state"]` for Okta...
> 
> ```
>   providers: [OktaProvider({
>     checks: ["pkce", "state"]
>   })],
> ```
> 
> (using `"next-auth": "^5.0.0-beta.4"`)

I am using an external application which uses Next.js in their app. As I cannot change the application code internally, what is the best to resolve this issue "error_description": "The authentication request has an invalid 'state' parameter." ?
