### ISSUE TITLE
wrong signout button action URL generated

### ISSUE THREAD

**Issue by xmlking** [nextauthjs/next-auth#9703]
### Environment

 System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 26.54 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - /opt/homebrew/bin/node
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: 8.14.1 - /opt/homebrew/bin/pnpm
    bun: 1.0.19 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 17.2.1
  npmPackages:
    @auth/core: 0.22.0 => 0.22.0 
    @auth/hasura-adapter: 0.2.15 => 0.2.15 
    @auth/sveltekit: 0.8.0 => 0.8.0 

### Reproduction URL

https://github.com/xmlking/spectacular/tree/main/apps/console-fb

### Describe the issue

I have my signout link printed to `/auth/signout?callbackUrl=/blog` but  Signout button action  URL is incorrectly  generated 
expected: `http://localhost:5173/auth/signout?callbackUrl=/blog`
actual : `http://localhost:5173/auth/signout?callbackUrl=/blog/signout`

<img width="1123" alt="image" src="https://github.com/nextauthjs/next-auth/assets/627951/79436104-da21-490e-b47a-ccb910d127c8">

I guess this is location of the bug: https://github.com/nextauthjs/next-auth/blob/658e4f2e65be1ec2f7bbfdbdb5f336946d4db463/packages/core/src/lib/pages/signout.tsx#L40

this link take `http://localhost:5173/auth/signout?callbackUrl=/blog` and add `/signout` to it. 

### How to reproduce

clone https://github.com/xmlking/spectacular/tree/main/apps/console-fb
```shell
cd apps/console-fb
turbo dev
```
then try  logout after login.

### Expected behavior

when we have logout link `/auth/signout?callbackUrl=/blog`  for  Signout , The Signout button action  URL  should be   `http://localhost:5173/auth/signout?callbackUrl=/blog`

otherwise we get 404 error

<img width="1123" alt="image" src="https://github.com/nextauthjs/next-auth/assets/627951/978aac37-6b39-49fa-8915-6f33eeb742ad">

**Comment by xmlking** [comment]
turbo build also failing with `TypeError: Cannot read properties of undefined (reading 'length')` error

<img width="1762" alt="image" src="https://github.com/nextauthjs/next-auth/assets/627951/6d5e808c-a14d-40a4-8e67-a69fd8c0ada1">

when Open the the location of error, it points to : https://github.com/nextauthjs/next-auth/blob/658e4f2e65be1ec2f7bbfdbdb5f336946d4db463/packages/frameworks-sveltekit/src/lib/index.ts#L284

**Comment by ndom91** [comment]
Hey thanks for the detailed issue and reproduction instructions!

We just shipped a little sveltekit basePath fix and it looks like it fixes the build error. However, the errant `/signout` that gets appended to the end of the path is still an issue. Without a callbackUrl, for example, the form action URL ends up being `/auth/signout/signout`, meaning it seems to just be naively concatenated on the end. Making me thing the error location you pointed to in the signout page's form action is correct. 

We'll take a closer look at this one :+1:
