### ISSUE TITLE
https://next-auth.js.org/v3/adapters/prisma - suggest `prisma-case-format` mention

### ISSUE THREAD

**Issue by iiian** [nextauthjs/next-auth#9737]
### What is the improvement or update you wish to see?

Taken from you docs [0]:

> "TIP: While Prisma includes an experimental feature in the migration command that is able to generate SQL from a schema..."

So, this isn't entirely accurate: `prisma` explicitly covers **model-first** vs. **database-first** development approaches, and officially supports both of them [1], so I don't think it's fair to call `prisma migrate dev` or `prisma deploy` experimental anymore (if they ever were). Related, I maintain a small repository called `prisma-case-format` [2]. The whole project is basically a linter/autofixer for prisma `model/view/enum`s. The tool offers a commandline arg for `--uses-next-auth`, that protects both **model-first** and **database-first** users from screwing up their `next-auth` models when trying to do `prisma migrate`.

As such, there's an opportunity here for you guys to notify users that **model-first** is supported by `next-auth`--just protect your `next-auth` models with `prisma-case-format`.

### Is there any context that might help us understand?

[0] https://next-auth.js.org/v3/adapters/prisma
[1] https://www.prisma.io/docs/orm/prisma-migrate/understanding-prisma-migrate/mental-model#patterns-for-evolving-database-schemas
[2] https://github.com/iiian/prisma-case-format/

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/v3/adapters/prisma

**Comment by balazsorban44** [comment]
v3 has been unmaintained for years now. this will likely not be addressed.

**Comment by iiian** [comment]
v3 of what?
