### ISSUE TITLE
End Session on Browser Close

### ISSUE THREAD

**Issue by jacklimwenjie** [nextauthjs/next-auth#974]
**Summary of proposed feature**
Expose an option to _not_ persist a session, which the session will be terminated on browser close. 

**Purpose of proposed feature**
Some system has a "remember me" or "keep me logged in" option to specify if a session should be persisted to avoid a scenario such as forgot to log out from a public computer.

**Detail about proposed feature**
Make the `session` options to support `maxAge:0` to set the cookie to expire on `'Session'`. Currently, setting `maxAge` to value `0` will cause an error.  

Alternatively, expose the cookie as an API from the module so that developer can use it to modify the cookie as needed, such as setting the expiry to `'Session'`.

**Comment by balazsorban44** [comment]
Although it would be possible to expire the cookie when  losing the browser but without federated logout, the user will still potentially be logged in on the computer.

**Comment by ricardasjak** [comment]
Same issue for me, I would like to set expire time to browser session.

**Comment by narutodev123** [comment]
Want user to get logged out if user close the browser. Please guide us on this.

**Comment by Ronnehag** [comment]
> Want user to get logged out if user close the browser. Please guide us on this.

I ended up changing the GET route in /api/auth/[...nextauth]/route.ts.
You also need to remove the auth wrapper in middleware.ts if you have any, that will override this cookie as it renews the expiration on every execution. We're using a basePath, so you need to modify the code to fit your setup.

```
import { handlers } from '@/auth';
import { NextRequest, NextResponse } from 'next/server';

//Handles __Secure prefix in production and no prefix for local dev
const cookieRegex =
  /(?:__Secure-|__Host-)?authjs\.[^=]+=(?:[^,]|,(?!\s*(?:__Secure-|__Host-)?authjs\.))+/g;

function rewriteRequest(req: NextRequest) {
  const {
    headers,
    nextUrl: { protocol, host, pathname, search }
  } = req;

  const detectedHost = headers.get('x-forwarded-host') ?? host;
  const detectedProtocol = headers.get('x-forwarded-proto') ?? protocol;
  const _protocol = `${detectedProtocol.replace(/:$/, '')}:`;
  const url = new URL(
    _protocol + '//' + detectedHost + process.env.NEXT_PUBLIC_BASE_PATH + pathname + search
  );

  return new NextRequest(url, req);
}

function modifyResponseCookies(res: Response): NextResponse {
  const setCookieHeader = res.headers.get('set-cookie');

  if (!setCookieHeader) {
    return new NextResponse(res.body, {
      status: res.status,
      statusText: res.statusText,
      headers: res.headers
    });
  }

  // Split cookies
  const cookies = setCookieHeader.match(cookieRegex) || [];

  const response = new NextResponse(res.body, {
    status: res.status,
    statusText: res.statusText
  });

  // Copy all headers except set-cookie
  res.headers.forEach((value, key) => {
    if (key.toLowerCase() !== 'set-cookie') {
      response.headers.set(key, value);
    }
  });

  // Process and add cookies
  cookies.forEach((cookie) => {
    if (cookie.includes('authjs.session-token=')) {
      // Remove Expires and Max-Age to make it a session cookie
      const sessionCookie = cookie
        .replace(/;\s*Expires=[^;]+/gi, '')
        .replace(/;\s*Max-Age=[^;]+/gi, '')
        .trim();
      response.headers.append('set-cookie', sessionCookie);
    } else {
      response.headers.append('set-cookie', cookie);
    }
  });

  return response;
}
```

Then the API route looks like this:
```
export async function GET(req: NextRequest) {
  const res = await handlers.GET(rewriteRequest(req));
  return modifyResponseCookies(res);
}

export async function POST(req: NextRequest) {
  const res = await handlers.POST(rewriteRequest(req));
  return res;
}
```
