### ISSUE TITLE
Inconsistent useSessions() loading state

### ISSUE THREAD

**Issue by ericvrp** [nextauthjs/next-auth#975]
**Describe the bug**
loading state of useSession() not working consistently without Provider wrapper component

**Steps to reproduce**
Remove usage of Provider and have a component and it's child call useSession() and the parent eventually gets loading=false while the child keeps having loading=true.

**Expected behavior**
Slower but consistent behaviour with or without Provider

**Comment by balazsorban44** [comment]
Hi there! Could you maybe create a minimal reproduction repo of your problem?

**Comment by sebasptsch** [comment]
I'm having a similar issue where the state of loading doesn't update until I change some element of my browser e.g window width or open my browser's search bar. Up until that point it hangs on the loading screen I setup (controlled by loading from the useSession() hook.

**Comment by sebasptsch** [comment]
> 
> 
> I'm having a similar issue where the state of loading doesn't update until I change some element of my browser e.g window width or open my browser's search bar. Up until that point it hangs on the loading screen I setup (controlled by loading from the useSession() hook.

Update: By using the Provider in `_app.tsx` these weird loading issues disappeared and navigating between routes was infinitely faster.

**Comment by jlarmstrongiv** [comment]
Can confirm https://github.com/nextauthjs/next-auth/issues/975#issuecomment-756800324 Using the Provider fixed the inconsistencies

**Comment by balazsorban44** [comment]
I'm inclined to think that we should make `Provider` required or at least much more recommended in a future major release.

#1473 is an attempt to make the client-side code more React friendly, and it would rely on the Provider for things like tab syncing as well.
