### ISSUE TITLE
crypto is not defined when running on Node.js

### ISSUE THREAD

**Issue by Stadly** [nextauthjs/next-auth#9814]
### Environment

```
  System:
    OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 9.13 GB / 15.50 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.18.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
  npmPackages:
    @auth/prisma-adapter: ^1.0.11 => 1.0.14 
    @auth/sveltekit: ^0.5.2 => 0.5.2
```

### Reproduction URL

https://github.com/Stadly/reproduction-auth.js-crypto-is-not-defined

### Describe the issue

I need to mock some tokens in order to mock authentication in end-to-end tests. I'd like to use the functionality built in to Auth.js, but it doesn't work on Node.js, since Auth.js assumes `crypto` to be globally available.

### How to reproduce

In a Node.js environment:

```js
import { encode } from '@auth/core/jwt';

const encoded = await encode({
  salt: 'my salt',
  secret: 'my secret',
});
```

The following line inside `encode` fails, since crypto is not defined: `.setJti(crypto.randomUUID())`.

### Expected behavior

That `encode` worked.

I guess it can be solved by something like:

```js
let crypto;

if (typeof process !== 'undefined' && process.versions && process.versions.node) {
    // Node.js environment detected
    crypto = require('crypto');
} else {
    // Browser environment, or crypto is already available globally
    crypto = window.crypto;
}
```

What do you think?

**Comment by balazsorban44** [comment]
Auth.js does not polyfill anything.


You have a few options:
- You can add the above to your codebase
- use at least Node.js 19, which has `globalThis.crypto` by default
- add the `--experimental-global-webcrypto` flag when using Node.js (available from v16, but since the minimum supported version is 18 currently, you should not be using anything older anyway)


Ref: https://nodejs.org/api/globals.html#crypto_1

**Comment by zionnite** [comment]
please how do i add the `--experimental-global-webcrypto` flag when using Node.js?
