### ISSUE TITLE
SignIn Callback doens't accept URL return anymore

### ISSUE THREAD

**Issue by MatheusAdorno** [nextauthjs/next-auth#9827]
### Environment

 System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
    Memory: 125.05 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 19.6.1 - ~/.nvm/versions/node/v19.6.1/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 9.4.0 - ~/.nvm/versions/node/v19.6.1/bin/npm
    pnpm: 8.10.2 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 121.0.6167.85
    Edge: 121.0.2277.83
    Safari: 14.0.3
  npmPackages:
    @auth/core: ^0.24.0 => 0.24.0 
    @auth/prisma-adapter: ^1.1.0 => 1.1.0 
    next: 14.0.3 => 14.0.3 
    next-auth: ^5.0.0-beta.5 => 5.0.0-beta.5 
    react: ^18 => 18.2.0 

### Reproduction URL

https://github.com/anest-on/aneston

### Describe the issue

I updated my Next-Auth to version 5 (beta), and since then, the SignIn Callback no longer accepts a URL return, it only accepts a boolean value.

<img width="731" alt="Screen Shot 2024-01-27 at 19 15 38" src="https://github.com/nextauthjs/next-auth/assets/69514084/8a3a88b2-3a1c-4a0c-a09f-58916681afd3">
 
In my case, I need that if the user doesn't check the option to grant access to the google calendar, it returns to an error page informing this, with the option for them to click again on the Google account link button and grant the connection. In version 4.24.5, which I was using before, I used to perform this return with a URL, and it worked perfectly.

The documentation about Auth and NextAuth says that I can continue using URL return in SignIn Callback, but it doens't allow it. When I compare the next-auth lib inside node modules I can see that in the older version the SignIn return accepted both String and Boolean, and in version 5 it only accepts Boolean values.

Return in SignIn on version 4.24.5:

<img width="982" alt="Screen Shot 2024-01-27 at 19 23 28" src="https://github.com/nextauthjs/next-auth/assets/69514084/3b9fe4d4-2dca-499b-a9d5-56aa68b1ff51">

Return in SignIn on version 4.24.5:

<img width="984" alt="Screen Shot 2024-01-27 at 19 22 07" src="https://github.com/nextauthjs/next-auth/assets/69514084/8630ec42-dfb5-42e2-88fe-91e753c86044">

### How to reproduce

Go to http://localhost:3000/register and click on the button "Conectar".
Try to connect your account without giving permission for the application get access to calendar.
Your not going to be redirected to the URL informed.

### Expected behavior

It should be redirect to "http://localhost:3000/register/?error=permissions"

**Comment by balazsorban44** [comment]
Thanks! This was intentional by the time, but since then I came to the decision that we should be doing as little breaking changes "just for the sake of it" as possible. I'll re-add this feature to v5 to keep v4 compatibility.

**Comment by ypanagidis** [comment]
Thank you so much for this, I was encountering the same issue! I assume when a new version get's released that includes this, when we redirect by returning a string the signing in flow stops and it's equivalent of returning false? Only asking cause any time i return false in the callback it throws the correct error (AuthorizedCallbackError) followed by a type error (immutable) but there is no way to catch it anywhere. I tried both server actions and the signin methods from the react package. If this is now what's supposed to happen happy to make a repo and raise a new issue!
