### ISSUE TITLE
Be more specific on cypress-social-login dependency.

### ISSUE THREAD

**Issue by pippinmole** [nextauthjs/next-auth#9832]
### What is the improvement or update you wish to see?

Currently, there exists a note about cypress-social login:
> If you are using username/password based login, you will not need the cypress-social-login dependency.

This isn't clear. Are you talking about **just** the [credentials provider](https://authjs.dev/guides/providers/credentials), or the credentials provider AND oauth providers like [Auth0](https://authjs.dev/reference/core/providers/auth0), which provides username/password based login.

### Is there any context that might help us understand?

Auth0 provides username/password based login. So does the credentials provider. My question is: do I need the cypress-social-login dependency if I'm using Auth0? This needs to be more clear on the docs.

### Does the docs page already exist? Please link to it.

https://authjs.dev/guides/testing/testing-with-cypress

**Comment by balazsorban44** [comment]
Even though Auth0 has a username/password flow, it's still considered an OAuth provider.

For Auth.js, Auth0 is still OAuth, even if you are logging in with credentials on their site.

Hope this explains it. I feel like it's clear enough in the docs, but if you have a better suggestion, feel free to send a PR for review!
