### ISSUE TITLE
ERR_MODULE_NOT_FOUND in drizzle adapter

### ISSUE THREAD

**Issue by xkalf** [nextauthjs/next-auth#9844]
### Adapter type

@auth/drizzle-adapter

### Environment

  System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900KF
    Memory: 42.27 GB / 63.83 GB
  Binaries:
    Node: 18.18.2 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    npm: 9.8.1 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
    pnpm: 8.13.1 - ~\AppData\Local\pnpm\pnpm.CMD
    bun: 1.0.21 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (121.0.2277.83)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @auth/drizzle-adapter: ^0.4.0 => 0.4.0 
    next: ^14.0.4 => 14.1.0 
    next-auth: ^4.24.5 => 4.24.5 
    react: 18.2.0 => 18.2.0 

### Reproduction URL

https://github.com/xkalf/nomad_competition

### Describe the issue

```
⨯ Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\hitech\code\nomad_competition\node_modules.pnpm@auth+drizzle-adapter@0.4.0\node_modules@auth\drizzle-adapter\lib\utils' imported from C:\Users
\hitech\code\nomad_competition\node_modules.pnpm@auth+drizzle-adapter@0.4.0\node_modules@auth\drizzle-adapter\lib\pg.js
at new NodeError (node:internal/errors:405:5)
at finalizeResolution (node:internal/modules/esm/resolve:327:11)
at moduleResolve (node:internal/modules/esm/resolve:946:10)
at defaultResolve (node:internal/modules/esm/resolve:1132:11)
at nextResolve (node:internal/modules/esm/loader:163:28)
at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
at ModuleWrap. (node:internal/modules/esm/module_job:77:40)
at link (node:internal/modules/esm/module_job:76:36) {
code: 'ERR_MODULE_NOT_FOUND'
}
```

### How to reproduce

pnpm dev and go to the localhost:3000 in server console is getting error calling db request is also not woking for this bug

### Expected behavior

i just want work well without the error

**Comment by balazsorban44** [comment]
Fixed the imports, but tests failed which is blocking release: https://github.com/nextauthjs/next-auth/actions/runs/7690823696/job/20955193600

Will need to look at it when I wake up. If somebody finds the fix before me, feel free to PR. Apologies!

**Comment by jadiaheno** [comment]
Happening on versions 0.4.0 and on 0.3.6

**Comment by xkalf** [comment]
Because of this issue i can't deploy my code to production in local i just changed node_modules file in production i can't

**Comment by LukaHietala** [comment]
> Happening on versions 0.4.0 and on 0.3.6

I only get this issue on 0.4.0, not on 0.3.6 🤔

**Comment by jeroenpelgrims** [comment]
> I only get this issue on 0.4.0, not on 0.3.6 🤔

Can confirm I'm not getting the error there either, but for some reason the default UI for the login page is messed up.

I also tried looking at this issue myself but I can't even get the unit tests for the project to run properly for some reason.

**Comment by balazsorban44** [comment]
Please don't spam the comments with "same issue".

The issue is was the missing `.js` import. The question is only why tests are failing https://github.com/nextauthjs/next-auth/actions/runs/7710641249/job/21014387531#step:8:70

**Comment by balazsorban44** [comment]
This was caused by an upstream bug in Drizzle. See the explanation here: https://github.com/nextauthjs/next-auth/pull/9870#issue-2111190965

Should be fixed now, please upgrade to at least `@auth/drizzle-adapter@0.5.0`!
