### ISSUE TITLE
Confusing wording in Upgrade to v5 docs

### ISSUE THREAD

**Issue by iiian** [nextauthjs/next-auth#9847]
### What is the improvement or update you wish to see?

> While NextAuth.js strictly uses standard Web APIs (and thus can run in any environments that supports that), some libraries/ORM packages that you rely on might not be ready yet.

##### 1. What is meant by "standard Web APIs" here? Unclear. Furthermore, 

> *any environments that supports* 

is a typo--should be either: *any environment**s** that support* or *any environment that support**s***.

---

##### 2. What does it meant that a lib or ORM

> might not be ready yet.

### Is there any context that might help us understand?

...

### Does the docs page already exist? Please link to it.

https://authjs.dev/guides/upgrade-to-v5#edge-compatibility

**Comment by iiian** [comment]
Oh, wait, you're literally talking about https://developer.mozilla.org/en-US/docs/Web/API.

Cool. Fine to close this ticket, although consider hyperlinking to this here as well?

**Comment by balazsorban44** [comment]
1. you found it out. 🙂
2. want to open a PR? 🙏
3. an ORM is a way to talk to a database from your code, think Drizzle, Prisma, etc.
