### ISSUE TITLE
createUser event not being triggered on credentials provider

### ISSUE THREAD

**Issue by samuelpalaciosdev** [nextauthjs/next-auth#9852]
### Provider type

Credentials

### Environment

 System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.12 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (120.0.2210.144)
  npmPackages:
    @auth/prisma-adapter: ^1.0.17 => 1.0.17
    next: ^14.1.0 => 14.1.0
    next-auth: ^5.0.0-beta.5 => 5.0.0-beta.5
    react: ^18 => 18.2.0

### Reproduction URL

https://github.com/samuelpalaciosdev/psicoreinventar-2024

### Describe the issue

Hello, I’m using both the credentials and Google providers for my authentication setup. However, I’m having trouble with the stripeCustomerId field in my user schema. When I register a user using the credentials provider, the createUser event is not being triggered, which causes the stripeCustomerId field to turn null. On the other hand, when I register a user with the Google provider, the stripe customer is created and the field has its corresponding ID. Pls help :)

### How to reproduce

```
CredentialsProvider({
      name: 'Credentials',
      credentials: {
        email: {
          label: 'Email',
          type: 'email',
          placeholder: 'jsmith@gmail.com',
        },
        password: { label: 'Password', type: 'password' },
      },
      async authorize(credentials) {
        // If not credentials are provided, return null to indicate no user logged in
        if (!credentials?.email || !credentials?.password) {
          return null;
        }

        //* Check if user exists
        const user = await prisma.user.findUnique({
          where: {
            email: credentials.email as string,
          },
        });

        if (!user || !user.password) {
          return null;
        }

        const isPasswordValid = await bcrypt.compare(
          credentials.password as string,
          user.password!
        );

        if (!isPasswordValid) {
          return null;
        }

        return {
          id: user.id,
          name: user.name,
          email: user.email,
          image: user.image,
          role: user.role,
          stripeCustomerId: user.stripeCustomerId || 'lol',
        };
      },
    }),
  ],
  //! STRIPE CUSTOMER ID ONLY BEING ADDED TO ACCOUNTS CREATED WITH GOOGLE PROVIDER
  events: {
    createUser: async ({ user }) => {
      // 1. Create a customer in Stripe
      if (user.name && user.email) {
        const customer = await stripe.customers.create({
          email: user.email,
          name: user.name,
        });

        console.log('User created in stripe');

        // 2. Update the user in Prisma with the Stripe customer id
        await prisma.user.update({
          where: {
            id: user.id,
          },
          data: {
            stripeCustomerId: customer.id,
          },
        });
      }
    },
  },
```

### Expected behavior

The stripe customer should be created when a new user signs up, but currently only is created when user registers with google provider and not when register with credentials provider

**Comment by balazsorban44** [comment]
This is expected. The credentials flow won't call the createUser event, as well as won't invoke adapter methods in comparison to other providers.

Whatever logic you need to run in createUser needs to be part of the authorize callback.

**Comment by samuelpalaciosdev** [comment]
Thank you! @balazsorban44. In that case, the logic in the authorize callback will work with both providers, right?

**Comment by balazsorban44** [comment]
there is no authorize callback for other providers.

For user creation, you might not need the createUser event, the OAuth providers (like Google) can use their profile callback. whatever you return there will automatically be saved on the created user.

https://authjs.dev/getting-started/adapters#user

**Comment by samuelpalaciosdev** [comment]
Thank you. I’m trying to create a stripe customer and add the customer id to the user created with next-auth :)
