### ISSUE TITLE
Customer attributes missing from Patreon provider profile

### ISSUE THREAD

**Issue by baku-yaki** [nextauthjs/next-auth#9858]
### Provider type

Patreon

### Environment

```
System:
OS: Linux 6.5 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Memory: 8.81 GB / 15.47 GB
Container: Yes
Shell: 5.1.16 - /bin/bash
Binaries:
Node: 21.6.1 - /usr/bin/node
npm: 10.2.4 - /usr/bin/npm
Browsers:
Chrome: 121.0.6167.85
npmPackages:
@auth/core: ^0.23.0 => 0.23.0
next: ^14.1.0 => 14.1.0
next-auth: 5.0.0-beta.5 => 5.0.0-beta.5
react: 18.2.0 => 18.2.0
```

### Reproduction URL

https://github.com/baku-yaki/patreon-bug-report

### Describe the issue

I am returning this along with other data.
```json
              "creator_id": creator,
              "patron_id": patron,
              "reward_id": reward,
```
But when running this method I don't get these fields back.
```javascript
Auth({
  providers: [Patreon({ profile: profileData => {
              "id": profile["data"]["id"],
              "name": profile["data"]["attributes"]["full_name"],
              "email": profile["data"]["attributes"]["email"],
              "image": profile["data"]["attributes"]["image_url"],
              "creator_id": creator,
              "patron_id": patron,
              "reward_id": reward,
            } })],
})
```

### How to reproduce

Add the given fields in profile callback in Patreon provider.

### Expected behavior

Each of three fields should show up in auth's response user field.

**Comment by balazsorban44** [comment]
Looks like we need to update our endpoint here:

https://github.com/nextauthjs/next-auth/blob/f33a0ace66dab3523d9cd0883d65558b29837b7b/packages/core/src/providers/patreon.ts#L81

To `https://www.patreon.com/api/oauth2/v2/identity`
Based on: https://docs.patreon.com/#get-api-oauth2-v2-identity

**Comment by baku-yaki** [comment]
That endpoint barely returns any data and IMO should not be used based on how it's design.

OTOH, My issue is not getting data from there. But the data I return in the `profile` callback is not saved.

**Comment by balazsorban44** [comment]
In that case, you don't actually seem to use a database adapter, so it's not going to be persisted anywhere. The `profile()` callback is only used to populate the User, if you would use a database adapter.

Instead, you can just read the raw `profile` in the `jwt` callback, which should give the entire object you are getting from Patreon. and then save whatever you need on `token`

Ref:

https://github.com/nextauthjs/next-auth/blob/9cb4350e3fb6805f2736dc615449cbed5cadef4d/packages/core/src/types.ts#L307-L312

https://github.com/nextauthjs/next-auth/blob/9cb4350e3fb6805f2736dc615449cbed5cadef4d/packages/core/src/providers/oauth.ts#L145-L153
