### ISSUE TITLE
EmailProvider Options

### ISSUE THREAD

**Issue by cooljohnny3** [nextauthjs/next-auth#9882]
### What is the improvement or update you wish to see?

In the EmailProvider docs it lists id and name as valid fields however they is not a valid fields anymore. 

### Is there any context that might help us understand?

EmailUserConfig used to inherit from EmailConfig but now it doesn't.
We were using 2 email providers and were using the id to distinguish which when calling signin(). It still seems to work but it wont compile without ts-ignore.

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/configuration/providers/email#options

**Comment by balazsorban44** [comment]
This sounds like a bug. We will need a reproduction. Please open a bug report instead. :pray:
