### ISSUE TITLE
Explicit return value and error hinting on `next-auth` Client APIs 

### ISSUE THREAD

**Issue by arung-agamani** [nextauthjs/next-auth#9894]
### What is the improvement or update you wish to see?

Add more verbose return value description of sections other than `useSession`, as well as link to relevant page containing the detailed return types.

Example :

[https://github.com/nextauthjs/next-auth/blob/v4/docs/docs/getting-started/client.md](https://github.com/nextauthjs/next-auth/blob/v4/docs/docs/getting-started/client.md)
From
---
```
### Redirects to sign in page when clicked

```js
import { signIn } from "next-auth/react"

export default () => <button onClick={() => signIn()}>Sign in</button>
```

### Starts OAuth sign-in flow when clicked

By default, when calling the `signIn()` method with no arguments, you will be redirected to the NextAuth.js sign-in page. If you want to skip that and get redirected to your provider's page immediately, call the `signIn()` method with the provider's `id`.

For example to sign in with Google:

```js
import { signIn } from "next-auth/react"

export default () => (
  <button onClick={() => signIn("google")}>Sign in with Google</button>
)
```
---
To
---
```
### Redirects to sign in page when clicked

```js
import { signIn } from "next-auth/react"

export default () => <button onClick={() => signIn()}>Sign in</button>
```

### Starts OAuth sign-in flow when clicked

By default, when calling the `signIn()` method with no arguments, you will be redirected to the NextAuth.js sign-in page. If you want to skip that and get redirected to your provider's page immediately, call the `signIn()` method with the provider's `id`.

For example to sign in with Google:

```js
import { signIn } from "next-auth/react"

export default () => (
  <button onClick={() => signIn("google")}>Sign in with Google</button>
)
```

> `signIn` returns an object containing result of signing in user using the provided credentials and sign in options:
> - [returned field] : [description]
> 
> In case of failed request (failed HTTP request, or something similar), `signIn` will return undefined.
> 
> In case of error on signing in (wrong credentials, server returns error), `error` will be populated with error message similar with sign in page error messages. You can read this [page](https://next-auth.js.org/configuration/pages#sign-in-page) for your reference

---

The requested change will add additional return value section to each section that doesn't currently mention it. The above example changes are shown quoted for better clarity

### Is there any context that might help us understand?

Client API page is missing additional necessary hint regarding the return value of functions provided.  

If compared with `useSession` section, the return values of the hook is explicitly described, while almost all other sections aren't.
Adding more verbose description for the return values of each section will help users to find documentation better. For example, I had to go to [Configuration > Pages](https://next-auth.js.org/configuration/pages) to have better clarity on what values are returned in `signIn` function error value. This is counter-intuitive as the mentioned page is explicitly targeted only for NextAuth's authentication page. With the lack of detailed API reference section, the easier way is to add description to return values on Client API pages

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/configuration/pages

**Comment by ndom91** [comment]
Hey @arung-agamani, we've recently shipped a brand new docs site (https://authjs.dev), including an updated `API Reference` section which includes all the autogenerated typedoc documentation from the types and jsdoc in the code, so all the explicit return values from any funciton you need should be found there :+1: 

Check out [this page](https://authjs.dev/getting-started/session-management) for docs on using the `signIn` / `signOut` methods
