### ISSUE TITLE
document how can we test components with next-auth v5

### ISSUE THREAD

**Issue by renanleonel** [nextauthjs/next-auth#9913]
### What is the improvement or update you wish to see?

currently there isn't any documentation about writing tests with jest in components that require authentication. currently, i'm not able to test anything in my protected routes because there isn't a way to test it 

### Is there any context that might help us understand?

please a documentation explaining how to set up and how to test components with auth

**Comment by Yohannfra** [comment]
I finally found a way to test my API routes endpoint, I'll try to explain briefly how.

I use the Credentials signin provider (this is the only one I need and use in my app).

My testing library is Jest but I believe it could work with any other.

First I need to get the csrftoken, I wrote this little function to help me do it.
See the comments in the function for more details about why all this logic is needed (I couldn't find a better solution)

```ts
async function getCsfrToken(): Promise<{
partialToken: string
fullToken: string
}> {
const res = await fetch(`${BASE_URL}/api/auth/csrf`)

const body = await res.json()

// I don't understand why it's like this but it works :/
// https://github.com/nextauthjs/next-auth/issues/1110#issuecomment-1548075055

// So TLDR we get two differents csrftokens from this request, one is in the body and the other in the set-cookie
// The token in the set-cookie has more informations (idk what)
// When we want to signin we must give the partial token in the body and the full token in the cookies

const token_from_body = body['csrfToken']
const token_from_cookie = getCookieValue(res.headers.getSetCookie()[0], 'next-auth.csrf-token')

// console.log(token_from_body)
// console.log(token_from_cookie)

return { partialToken: token_from_body, fullToken: token_from_cookie }
}
```

Now that I have the csrfTokens I can fetch the signin endpoint, I made this function.


```ts
async function signinWithEmailAndPassword(email: string, password: string): Promise<string | null> {
  const csrfTokens = await getCsfrToken()

  const res = await fetch(`${BASE_URL}/api/auth/callback/credentials`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      Cookie: `next-auth.csrf-token=${csrfTokens.fullToken}`, // note that we give the csrfToken here
    },

    body: new URLSearchParams({
      email,
      password,
      csrfToken: csrfTokens.partialToken, // and here
      redirect: 'false',
      json: 'true',
    }),
  })

  const error = new URL(data.url).searchParams.get('error')

  if (res.ok) {
    const auth_token = getCookieValue(
      res.headers.getSetCookie().join(';'),
      'next-auth.session-token'
    )
    return auth_token
  } else {
    console.log('Signin failed: ', error)
  }
  return null
}
```

So I run this function with a custom test account I created in my database and it gives me back the value of the **next-auth.session-token** that was in the set-cookies.

Once I have this session token I can fetch any endpoint and add it in the cookie and it will work.

Again my custom function (I have a similar one for HEAD/PUT/POST/DELETE ...)

```ts
export async function httpGetWithSessionToken(endpoint: string, token: string): Promise<Response> {
  const res = await fetch(`${BASE_URL}${endpoint}`, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
      Cookie: `next-auth.session-token=${token}`,
    },
  })
  return res
}
```

**Comment by mjlading** [comment]
@renanleonel Did you figure this out? Im also trying to test a protected procedure and get weird module errors

**Comment by renanleonel** [comment]
@mjlading yes! created this mock folder in [this repo](https://github.com/renanleonel/next-auth-v5-middleware/tree/main/__tests__/mocks):

**Comment by Waqar-SE** [comment]
@Yohannfra I'm doing the exact same thing but strangely I'm being rediected to `http://localhost:3000/api/auth/signin?csrf=true`. Any idea why

**Comment by faisalprady12** [comment]
> [@mjlading](https://github.com/mjlading) yes! created this mock folder in [this repo](https://github.com/renanleonel/next-auth-v5-middleware/tree/main/__tests__/mocks):

I don't know what it does, but it definitely solved my issue! thanks!
