### ISSUE TITLE
NextAuth v5 `TypeError: next_dist_server_web_exports_next_request__WEBPACK_IMPORTED_MODULE_0__ is not a constructor`

### ISSUE THREAD

**Issue by chungweileong94** [nextauthjs/next-auth#9922]
### Environment

```
System:
    OS: macOS 14.3
    CPU: (8) arm64 Apple M2
    Memory: 2.59 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
Binaries:
    Node: 18.19.0 - ~/Library/Caches/fnm_multishells/18527_1707202116497/bin/node
    Yarn: 1.22.21 - ~/Library/Caches/fnm_multishells/18527_1707202116497/bin/yarn
    npm: 10.2.3 - ~/Library/Caches/fnm_multishells/18527_1707202116497/bin/npm
    pnpm: 8.14.1 - ~/Library/Caches/fnm_multishells/18527_1707202116497/bin/pnpm
    bun: 1.0.26 - /opt/homebrew/bin/bun
Browsers:
    Safari: 17.3
npmPackages:
    next: 14.0.4 => 14.0.4 
    next-auth: 5.0.0-beta.8 => 5.0.0-beta.8 
    react: ^18 => 18.2.0
```

### Reproduction URL

https://github.com/chungweileong94/nextauth-route-handler-error

### Describe the issue

If one of the `AUTH_URL` and `NEXTAUTH_URL` is set, we will get the following error.
```
TypeError: next_dist_server_web_exports_next_request__WEBPACK_IMPORTED_MODULE_0__ is not a constructor
```

### How to reproduce

1. Clone the repro
2. Run the app via `pnpm dev`
3. Navigate to `http://localhost:3000/api/auth/signin`

### Expected behavior

It should show the next-auth built-in sign-in page. Instead, it shows throw 500 error (`TypeError: next_dist_server_web_exports_next_request__WEBPACK_IMPORTED_MODULE_0__ is not a constructor`)

**Comment by chungweileong94** [comment]
The problem seems to be caused by `new NextRequest(...)` in `reqWithEnvURL` 
https://github.com/nextauthjs/next-auth/blob/8a2ca6b280457f202ff77f74dc699cbf85606d43/packages/next-auth/src/lib/env.ts#L11

Which is why setting either `AUTH_URL` or `NEXTAUTH_URL` will bypass the problem.

**Comment by Talent30** [comment]
I can confirm this bug, same setup

**Comment by balazsorban44** [comment]
Related to #9795. This sounds like an upstream Next.js bug which I thought has been fixed. Will have a look there. The workaround is to patch `new NextRequest` to `new NextRequest.default` for now.

Note: You most likely don't need `AUTH_URL` or `NEXTAUTH_URL`, it's not been required for a very long time, unless you want a custom path for your auth route, or behind a proxy.

**Comment by chungweileong94** [comment]
> Note: You most likely don't need `AUTH_URL` or `NEXTAUTH_URL`, it's not been required for a very long time, unless you want a custom path for your auth route, or behind a proxy.

Ah, good to know.

**Comment by balazsorban44** [comment]
Fix is on the way in Next.js https://github.com/vercel/next.js/pull/61721

**Comment by chungweileong94** [comment]
Will close this issue, as it was fixed in the latest NextJS canary release.

**Comment by Zelzazor** [comment]
> Note: You most likely don't need `AUTH_URL` or `NEXTAUTH_URL` anyway, it's not been required for a very long time, unless you want a custom path for your auth route, or behind a proxy.

Thing is, I do use a proxy because I am working with a Docker container and using nginx to deploy the app. What are my options in this case?

**Comment by itskaransingh** [comment]
Hi @Zelzazor , can you please tell me how you were able to make the auth work using NEXTAUTH_URL_INTERNAL, thanks.

**Comment by irclausen** [comment]
> Hi @Zelzazor , can you please tell me how you were able to make the auth work using NEXTAUTH_URL_INTERNAL, thanks.

I was able to apply a fix for local dev at least by changing:

```
AUTH_URL=***********
```
to
```
NEXTAUTH_URL_INTERNAL=***********
```
in my .env file. If you don't have AUTH_URL perhaps add NEXTAUTH_URL_INTERNAL instead of replacing

**Comment by itskaransingh** [comment]
Thanks, btw my error resolved when i shifted to  previous version 5.0.0-beta.4 from 5.0.0-beta.8

**Comment by bwheeele** [comment]
I am still getting this error. I tried adding AUTH_URL , NEXTAUTH_URL_INTERNAL and still keep getting this error.

**Comment by chungweileong94** [comment]
@bwheeele This is an upstream Next.js bug, which has been fixed in https://github.com/vercel/next.js/pull/61721, and landed in the latest Next.js canary version, but yet to be landed in the stable version.

**Comment by oscarmylla** [comment]
I've encountered a potential edge case when using the prisma adapter together with prisma accelerate and the following versions in my project:

@prisma/client: ^5.10.2
@prisma/extension-accelerate: ^0.6.3
next-auth: ^5.0.0-beta.13
next: ^14.1.0,

I observed that this issue was resolved when I set the route handler to run on the edge.

----

This doesn't work:
```
import { auth } from "@/server/auth";

export const runtime = 'edge';

export const GET = auth(async (req) => {
   const session = req.auth
   ...
   return Response.json({data})
})
```

This works:
```
import { auth } from "@/server/auth";

export const runtime = 'edge';

export const GET = auth(async (req) => {
   const session = req.auth
   ...
   return Response.json({data})
})
```

**Comment by philippemiguet** [comment]
> > Hi @Zelzazor , can you please tell me how you were able to make the auth work using NEXTAUTH_URL_INTERNAL, thanks.
> 
> I was able to apply a fix for local dev at least by changing:
> 
> ```
> AUTH_URL=***********
> ```
> 
> to
> 
> ```
> NEXTAUTH_URL_INTERNAL=***********
> ```
> 
> in my .env file. If you don't have AUTH_URL perhaps add NEXTAUTH_URL_INTERNAL instead of replacing

This is what fixed it for me on `"next-auth": "^5.0.0-beta.17"`

**Comment by IhorAnDev** [comment]
> This is what fixed it for me on `"next-auth": "^5.0.0-beta.17"`

God, bless you! Thanks a million.

**Comment by mclbdn** [comment]
I am on 4.2.5 and nor AUTH_URL nor NEXTAUTH_URL_INTERNAL solved it for me.

**Comment by johnkdunyo** [comment]
> Related to #9795. This sounds like an upstream Next.js bug which I thought has been fixed. Will have a look there. The workaround is to patch `new NextRequest` to `new NextRequest.default` for now, or drop the env variables.
> 
> Note: You most likely don't need `AUTH_URL` or `NEXTAUTH_URL` anyway, it's not been required for a very long time, unless you want a custom path for your auth route, or behind a proxy.


Removing `AUTH_URL` or `NEXTAUTH_URL` works fine locally, but gave me error below:


error { error: 'unauthorized_client' }
--
  | 2025-01-04T06:16:52.515Z | [90m[auth][debug]:[0m callback route error details {
  | 2025-01-04T06:16:52.515Z | "method": "GET",
  | 2025-01-04T06:16:52.515Z | "query": {
  | 2025-01-04T06:16:52.515Z | "code": "e955cdb4-9224-4c9b-a159-b5d88a523cae",
  | 2025-01-04T06:16:52.515Z | }
  | 2025-01-04T06:16:52.515Z | }
  | 2025-01-04T06:16:52.515Z | [31m[auth][error][0m CallbackRouteError: Read more at https://errors.authjs.dev#callbackrouteerror
  | 2025-01-04T06:16:52.516Z | [31m[auth][cause][0m: Error: TODO: Handle OIDC response body error
  | 2025-01-04T06:16:52.516Z | at iz (/var/task/.next/server/chunks/9583.js:409:31004)
  | 2025-01-04T06:16:52.516Z | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  | 2025-01-04T06:16:52.516Z | at async i5 (/var/task/.next/server/chunks/9583.js:409:36906)
  | 2025-01-04T06:16:52.516Z | at async on (/var/task/.next/server/chunks/9583.js:409:48224)
  | 2025-01-04T06:16:52.516Z | at async os (/var/task/.next/server/chunks/9583.js:409:52977)
  | 2025-01-04T06:16:52.516Z | at async /var/task/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:41960
  | 2025-01-04T06:16:52.516Z | [31m[auth][details][0m: {
  | 2025-01-04T06:16:52.516Z | "provider": "cognito"
  | 2025-01-04T06:16:52.516Z | }

**Comment by Azazali009** [comment]
A possible fix is here, do not waste your time.
Just remove the NEXTAUTH_URL variable from the .env.local file or replace the name of the variable from NEXTAUTH_URL=********** to NEXTAUTH_URL_INTERNAL=**********, and that is it.✅
