### ISSUE TITLE
Why is users collection named userUsers in production builds

### ISSUE THREAD

**Issue by tiivik** [nextauthjs/next-auth#993]
I am trying to extend the User schema with additional metadata for the user. I've followed the tutorial here
https://next-auth.js.org/tutorials/typeorm-custom-models successfully and added `plan` and `stripeCustomerId` in the following manner

**models/user.js**
```
import Adapters from 'next-auth/adapters'

export default class User extends Adapters.TypeORM.Models.User.model {
  constructor(name, email, image, emailVerified) {
    super(name, email, image, emailVerified)
  }
}

export const UserSchema = {
  name: 'User',
  target: User,
  columns: {
    ...Adapters.TypeORM.Models.User.schema.columns,
    plan: {
      type: 'varchar',
      nullable: true
    },
    stripeCustomerId: {
      type: 'varchar',
      nullable: true
    }
  }
}
```

**models/index.js** looks like
```
import User, { UserSchema } from './User'

export default {
  User: {
    model: User,
    schema: UserSchema
  }
}

```

In `[...nextauth].js` I've added plan and stripeCustomerId to the session callback

```
import NextAuth from 'next-auth'
import Providers from 'next-auth/providers'
import Adapters from 'next-auth/adapters'

import Models from '../../../models'

const options = {
  providers: [
    ...
  ],
  database: process.env.MONGODB_URI,
  adapter: Adapters.TypeORM.Adapter(
    process.env.MONGODB_URI,
    {
      models: {
        User: Models.User
      }
    }
  ),
  callbacks: {
    session: async (session, user, sessionToken) => {
      session.user.id = user.id
      session.user.plan = user.plan
      session.user.stripeCustomerId = user.stripeCustomerId
      return Promise.resolve(session)
    }
  }
}

export default (req, res) => NextAuth(req, res, options)

```

When a new user signs up these collections are made in MongoDB OK
```
sessions
sites
users
verificationRequests
```

When user subscribes to a plan, I update the record in `users` collection, adding a `plan` and `stripeCustomerId`. I can then access `plan` and `stripeCustomerId` client side OK.

Now, the problem is this is working OK in development mode when running `npm run dev` however not in production optimised builds `npm run build && npm run start` or in my case when deployed to Vercel.

When user signs up these collections are made (not `users` but `userUsers`). 

```
sessions
sites
userUsers
verificationRequests
```

I'm unable to figure out why production-optimised builds create a differently named collection than when running in development mode.

I'm using MongoDB Atlas.

* [X ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [X ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by sinuheshinbr** [comment]
Did you manage to solve this problem? Just faced the exact same issue here now

**Comment by tiivik** [comment]
> Did you manage to solve this problem? Just faced the exact same issue here now

Unfortunately no

**Comment by sinuheshinbr** [comment]
I managed to make it work. I changed the following:

```
//[...nextauth.js]

adapter: Adapters.TypeORM.Adapter(process.env.DATABASE_URL, {
  models: { users: Models.users }
}),
```
In the documentation the code above appears as models: { User: Models.User }

```
//models/index.js

import User, { UserSchema } from './User'
export default {
  users: {
    model: User,
    schema: UserSchema
  }
}
```

**Comment by lacabra** [comment]
Thanks @sinuheshinbr. I encountered this very same problem, and lost many hours trying to figure this out, and your solution worked like a charm! Especially because `npm run dev` and `npm run build` behave differently quite unexpectedly 🤷‍♂️

Love NextAuth all throughout, this was just been a slightly painful hiccup in my journey. Thanks @iaincollins for the amazing work open sourcing this amazing piece of software! 🙏

**Comment by balazsorban44** [comment]
someone visiting this, looks like the answer is provided here: https://github.com/nextauthjs/next-auth/issues/993#issuecomment-770898334

the docs could be updated jn a PR to reflect this, we welcome anyone doing it! 🙏

**Comment by balazsorban44** [comment]
https://github.com/lacabra/proco-map-app/pull/33 fixed this

**Comment by brunogrcsada** [comment]
Me and @liamdebellada are currently using the following workaround to fix this issue:
```
const User = class extends (<any>Adapters.TypeORM.Models.User.model)  {
    constructor(name: any, email: any, image: any, emailVerified: any, rating: number) {
        super(name, email, image, emailVerified, rating);
        this.rating = 0.0;
      }
}
```
Changed ```export default class extends``` to ```const User = class extends```. By setting the User class as a constant, the collection naming issue goes away completely. I also exported the const as default so that it could be imported elsewhere. This workaround maintains the properties you already have for your UserSchema. 🙂
