### ISSUE TITLE
Use camelCase field names as a flag (even if it's not MongoDB)

### ISSUE THREAD

**Issue by dmythro** [nextauthjs/next-auth#994]
**Summary of proposed feature**
Is there a reason why camelCase collection & field names are [for MongoDB only](https://next-auth.js.org/schemas/mongodb#objects-in-mongodb), not as a separate flag? Or am I missing something?

**Potential problems**
I want to use camelCase for all field/property names consistently across the project (with any database), mixing with snake_case feels ugly.

**Comment by joniaiuser** [comment]
I have the opposite requirement, want to use snake case for MongoDB, can't seem to find a way to customise it.

**Comment by balazsorban44** [comment]
Although not documented currently, but I think there might be a way of configuring this, as we have different naming strategies in the source code for the TypeORM adapter (assuming you use that one).
https://github.com/nextauthjs/adapters/blob/canary/packages/typeorm-legacy/src/lib/naming-strategies.js
