### ISSUE TITLE
PKCE code_verifier cookie was missing in development

### ISSUE THREAD

**Issue by trevorpfiz** [nextauthjs/next-auth#9990]
### Environment

System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 7.12 GB / 9.72 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.15.1 - ~/.local/share/pnpm/pnpm
    bun: 1.0.14 - ~/.local/share/pnpm/bun
    Watchman: 2024.01.22.00 - /home/linuxbrew/.linuxbrew/bin/watchman

### Reproduction URL

https://github.com/trevorpfiz/create-t3-turbo/tree/main

### Describe the issue

adding pkceCodeVerifier cookie gives error `PKCE code_verifier cookie was missing` when using Google or Discord providers in development.

### How to reproduce

add

```
pkceCodeVerifier: {
    name: 'next-auth.pkce.code_verifier',
    options: {
      httpOnly: true,
      sameSite: 'none',
      path: '/',
      secure: process.env.NODE_ENV === 'production',
    },
  },
```

see error when trying to login in during development with Discord or Google.

### Expected behavior

I would expect no error like in production.

**Comment by marlon307** [comment]
I have the same problem but to authenticate on my subdomains

https://codesandbox.io/p/devbox/next-auth-sub-domains-forked-lwj25m?file=%2Fauth.ts%3A19%2C46

**Comment by leo3linbeck** [comment]
Same problem with Auth0 provider.

**Comment by Painwraith** [comment]
Any solution on this? Trying to use AzureB2C as provider in local test environment hitting this snag. 

    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'azure-ad-b2c',
  message: 'PKCE code_verifier cookie was missing.'

**Comment by daved-gowithhero** [comment]
Is there any update on this?

**Comment by DuanTranHuy** [comment]
same problem with google provider nextauth v5

**Comment by wade-liwei** [comment]
same problem with github provider nextauth v5

**Comment by serethomas** [comment]
Same problem with github provider and google provider on next-auth": "5.0.0-beta.17".  Has anyone found a solution?

**Comment by DeepaPrasanna** [comment]
I am using github provider and followed the documentation as it is and facing the exact same issue!

**Comment by zhefciad** [comment]
I have the same problem. Any fixes?

**Comment by DeepaPrasanna** [comment]
> I have the same problem. Any fixes?
> 
> _Edit by maintainer bot: Comment was **automatically** minimized because it was considered unhelpful. (If you think this was by mistake, let us know). Please only comment if it adds context to the issue. If you want to express that you have the same problem, use the upvote 👍 on the issue description or subscribe to the issue for updates. Thanks!_

i have switched to supabase auth

**Comment by jonoise** [comment]
remove cookies from the browser. that fixed it for me.

**Comment by yeasin-2002** [comment]
I'm also getting the same error, 
I'm  using OAuth and google provider 




![image](https://github.com/nextauthjs/next-auth/assets/87494463/ed67caf0-2571-40ad-bbbc-55ec4661ead1)

**Comment by zhefciad** [comment]
I fixed my problem by changing NEXTAUTH_URL in env.local from 127.0.0.1 to localhost.

**Comment by pedrobando** [comment]
> remove cookies from the browser. that fixed it for me.

THANK YOUUUUUUUU

**Comment by trevorpfiz** [comment]
> @trevorpfiz did you figure this one out? And if not, can I see your DiscordProvider config?

no. this? https://github.com/MithridHealth/create-t3-turbo/blob/d20d8625f9579e7c90e154d866e7425e48f5a8d1/packages/auth/src/index.ts#L32

**Comment by aramshiva** [comment]
Even after removing cookies and changing the NEXTAUTH_URL to `localhost:3000`, I receive this same error with Notion Provider.

**Comment by ThangHuuVu** [comment]
Hello all, I can reproduce what you are reporting with the code example from @trevorpfiz. This isn't an issue of Auth.js though, it is the way cookies work in the browser. If you set the "Same-site" attribute to none, you also need to set "Secure" to true always (See the screenshot below):  
<img width="886" alt="Screenshot 2024-08-25 at 13 20 13" src="https://github.com/user-attachments/assets/d359f55d-8d84-493d-81c1-5eba27e50306">

Read more at: https://web.dev/articles/samesite-cookies-explained#samesitenone_must_be_secure

```js
pkceCodeVerifier: {
    name: 'next-auth.pkce.code_verifier',
    options: {
      httpOnly: true,
      sameSite: 'none',
      path: '/',
      secure: true,
    },
  },
```

I'm closing this issue, feel free to open a new issue if you have problems with custom cookies!

**Comment by Painwraith** [comment]
@ThangHuuVu Worked for me. Thank you.

**Comment by anon-phantom** [comment]
`__Secure-next-auth.pkce.code_verifier` when using ssl in development environment instead of `next-auth.pkce.code_verifier`

This is how I fixed the issue

```ts

import NextAuth from "next-auth";

const isDevelopment = process.env.NODE_ENV === "development";

export default NextAuth({
  providers: [
    Providers.Apple({
      clientId: process.env.APPLE_CLIENT_ID,
      clientSecret: process.env.APPLE_CLIENT_SECRET,
    }),
  ],
  useSecureCookies: !isDevelopment, // Disable secure cookies in dev
  cookies: {
    pkceCodeVerifier: {
      name: isDevelopment
        ? "next-auth.pkce.code_verifier"
        : "__Secure-next-auth.pkce.code_verifier",
      options: {
        httpOnly: true,
        sameSite: "lax",
        path: "/",
        secure: !isDevelopment, // Use Secure only in production
      },
    },
  },
});

```
