### ISSUE TITLE
/auth/api/signin not working as expected

### ISSUE THREAD

**Issue by BrandonCorn** [nextauthjs/next-auth#9994]
## Redirect to /auth/signin

Hi, I'm having an issue to what's described and I have a custom signin page. The issue I'm experiencing is that when a user already has a linked account they redirect to [ /api/auth/signin?error=OAuthAccountNotLinked](#). My expectation is to be redirected to[ /auth/signin?error=OAuthAccountNotLinked](#). I may be missing something in the documentation though I read "The following errors are passed as error query parameters to the default or overridden sign-in page:" at the page you had linked above. 

### Dependencies
```
    "next": "^13.4.14-canary.0", // Using App Router
    "next-auth": "^4.23.0",
```

### SignIn Page
http://localhost:3000/auth/signin

### Steps to Reproduce: 
- User with no account signs in with Github provider successfully
- User signs out 
- User with account from Github provider signs in with Discord provider
- Discord requests authorization
- User is redirected to [/api/auth/signin?error=OAuthAccountNotLinked](#)

### Expected Behavior:
- Users tries to sign in with different provider when account already exists
- User is redirected to [/auth/signin?error=OAuthAccountNotLinked](#)

### NextAuth Options 

```
export const authOptions: NextAuthOptions = {
  adapter: PrismaAdapter(prisma),
  //configure one or more auth providers
  providers: [
    GitHubProvider({
      clientId: process.env.GITHUB_CLIENT_ID!,
      clientSecret: process.env.GITHUB_CLIENT_SECRET!,
    }),
    DiscordProvider({
      clientId: process.env.DISCORD_CLIENT_ID!,
      clientSecret: process.env.DISCORD_CLIENT_SECRET!,
    }),
    CredentialsProvider({
      name: "Credentials",
      credentials: {
        email: { label: "email", type: "text", placeholder: "email" },
        password: {
          label: "password",
          type: "password",
          placeholder: "password",
        },
      },
      async authorize(credentials, req) {
        const res = await fetch(`${process.env.NEXTAUTH_URL}/api/auth/signin`, {
          method: "POST",
          body: JSON.stringify(credentials),
          headers: { "Content-Type": "application/json" },
        });

        const user = await res.json();
        //no error and user exists
        if (res.ok && user) {
          return user;
        }
        //no valid user
        return null;
      },
    }),
  ],
  pages: {
    signIn: '/auth/signin',
    error: '/auth/signin',
  },
  secret: process.env.NEXTAUTH_SECRET,
  callbacks: {
    async session({ session }){

      return session;
    },
  }, 
  session: {
    strategy: 'jwt'
  }
}
```

### Custom signin handler uses 

```
import { signIn } from 'next-auth/react

  const handleProviderSignIn = (
    providerName: string
  ) => {
    signIn(providerName, {
      callbackUrl: process.env.VERCEL_URL || "http://localhost:3000",
    });
  };
```

_Originally posted by @BrandonCorn in https://github.com/nextauthjs/next-auth/issues/7880#issuecomment-1937360135_

**Comment by ThangHuuVu** [comment]
This is by design; see our doc at: https://authjs.dev/reference/core/errors#oauthaccountnotlinked
> For security reasons, Auth.js does not automatically link OAuth accounts to existing accounts if the user is not signed in.
If you trust the OAuth provider to have verified the user's email address, you can enable automatic account linking by setting [allowDangerousEmailAccountLinking: true](https://authjs.dev/reference/core/providers#allowdangerousemailaccountlinking) in the provider configuration.

**Comment by BrandonCorn** [comment]
Hi @ThangHuuVu I understand this behavior is expected, I don't want the accounts to be linked. I want the user to be redirected to my own /signin page as defined in the options with the provided error. This isn't happening with my custom page set in the NextAuth options.

**Comment by jcrowe85** [comment]
Experiencing the same issue. Any further progress?

**Comment by torgestehr** [comment]
I have the same problem

**Comment by BrandonCorn** [comment]
No progress on my end yet, just haven't had time to address it further. Any luck yourself? @jcrowe85

**Comment by mantzu132** [comment]
same problem

**Comment by krilbert** [comment]
I have the same situation. Even if I return false on the `signIn` callback, seems that all errors on oAuth are not being correctly redirected.

I noticed I'm being redirected to `http://localhost:3000/api/auth/login?error=AccessDenied` but if I replace the `/login` to `/signin` the redirection does works (to my custom page).
`/login` is the value on my pages configuration.

My flow with credentials works as expected.

**Comment by jcrowe85** [comment]
> No progress on my end yet, just haven't had time to address it further. Any luck yourself? @jcrowe85

It appears to be an open bug. I've been following this thread: https://github.com/nextauthjs/next-auth/discussions/10234#discussioncomment-8784398

**Comment by krilbert** [comment]
Correct, I was going to take a look but first I looked on the pull requests and found this PR #10288

**Comment by ConnectWithNoor** [comment]
I can confirm the error exists on v 5.0.0-beta.15. I am trying to add custom pages which are inside of `app.auth.login.page.tsx` to show to the users in case of errors. However, I'm being redirected to `/api/auth/signin` page which isn't the behavior I want. 

` pages: {
    signIn: "/auth/login",
    error: "/auth/login",
  }`

Expected behavior on error:
`/auth/login?error=message_here`
Actual behavior 
` /api/auth/signin?error=message_here`

I fixture would be really appreciated
